### ISSUE TITLE
map div's position gets changed to relative

### ISSUE THREAD

**Issue by vishcious** [Leaflet/Leaflet#100]
The api seems to change the map div's position to relative from what ever the user had set it to. I had position the map at  a certain absolute position on my page, but the maps is created, the div's position is changed to relative which messes up the layout of the map on my page

Thank You,
Vish

**Comment by Ethaan** [comment]
Did you find a solution to this?

**Comment by danzel** [comment]
This got fixed as above.
If it is broken again then please open a new issue and relate it to this. Thanks.

**Comment by almereyda** [comment]
For the next one to reopen a new issue to follow up on this one, I had to use

```
#map {
    position: fixed !important;
}
```

which felt bad and ugly to fix a map to the background.

**Comment by Slevender** [comment]
Had to use !important too.
