### ISSUE TITLE
<input type="text"> doesn't work in a control

### ISSUE THREAD

**Issue by rulatir** [Leaflet/Leaflet#1001]
When &lt;input type="text"&gt; is placed in a leaflet control, it cannot be interacted with using mouse. Clicking on it doesn't focus it, and attempting to select some text with mouse drags the map instead. 

Happens in newest Opera and Firefox. Leaflet v4.4

EDIT: apparently solved by stopping propagation of mousedown events from form elements inside leaflet controls. Will mark as solved if this solution doesn't cause other problems in my app.

EDIT 2: OK, solved, and of course it is enough to stop propagation on the control container. How do I close my own issue?

**Comment by nayyargaurav-aristocrat** [comment]
No Need to do this just try map tap property to fix this. example 

Leaflet.Map('map', { zoomControl: false , tap: false}).setView
