### ISSUE TITLE
CircleMarker.setStyle() does not respect changes in radius

### ISSUE THREAD

**Issue by fdlk** [Leaflet/Leaflet#1012]
CircleMarker does not override setStyle() and therefore setStyle() only changes PathOptions.
But in the constructor the radius is part of the style.

Use case:
I am generating CircleMarkers from GeoJSON Points using pointToLayer.
When the user zooms in and out, I want to change the style of these CircleMarkers, in particular their color and radius. To do this, I call setStyle() on the generated GeoJSON Layer, but this does not change the radius of the CircleMarkers, only the color.

**Comment by jainruchi** [comment]
is it resolved? I am still getting this issue.

**Comment by IvanSanchez** [comment]
@jainruchi This issue is literally four years old. Create a new issue with a proper reproducible test case if you can reproduce it in 1.0.0-rc3.
