### ISSUE TITLE
Problem with marker click and popup/pan

### ISSUE THREAD

**Issue by Mathbl** [Leaflet/Leaflet#1041]
Hello!

Not sure if the problem is with my code, but here is the situation : 
- Android app with Leaflet inside a webView.
- I'm currently testing on nexus7 (running jelly bean 4.1)
- I'm running last dev (master from github)
- I'm disabling 3D so that the webview crash doesn't happen

Problem is that on nexus7 (but not on HTC Glacier running 2.3.6), when I click on a marker, the map pans, the binded popup opens, but it closes right after.

I did a little video to show what I mean.

http://d.pr/v/Na1j

Here is the way I do it (i've changed some variables name to simplify the code)

<code>marker = new L.Marker(aMarkerLocation);
marker.bindPopup("<b>Point </b>" + (poiNumber+1) );
</code>

I set the click event listener : 

<code>marker.addEventListener('click', function()
{
  enableContent(circuitInfo, poiNumber, index, numberOfPoi, aMarkerLocation);
}
</code>

And finally the enableContent function does that

<code>map.setView(aMarkerLocation, map.getZoom());
marker.openPopup();
</code>

Anyone have a cue on what the problem could be ?

P.S. While testing several times, it seems to me that when a marker is clicked, the map pans, the popup opens but there seems to be another click triggered at the position where the marker was before panning...weird.

Thanks !

**Comment by dtruel** [comment]
I have this same issue in both ie and chrome for desktop.

**Comment by 0xae** [comment]
Hello guys, i've found a rather dirty fix for this:
I went to leaflet-src.js and comment the lines 6939 to 6943 and the touch worked great in android:

```javascript
// 				if (type === 'click' && L.Browser.android) {
// 					handler = function (e) {
// 						return L.DomEvent._filterClick(e, originalHandler);
// 					};
// 				}
				obj.addEventListener(type, handler, false);
```

**Comment by 0xae** [comment]
The fix (or another name you want to give it) also fixes the touches on the map.
so all these issues are gone. I've made tests on my google chrome and it works just fine.
@Mathbl @dtruel my app is a ionic / cordova app and it works like a charm now!

**Comment by hackberd** [comment]
0xae's [fix](https://github.com/Leaflet/Leaflet/issues/1041#issuecomment-144994331) fixed an issue for me with ionic where leaflet would only recognize every other click event. It works perfectly now.
