### ISSUE TITLE
Leaflet incorrectly detects touch support in Chrome in some cases

### ISSUE THREAD

**Issue by FoolMeOnce** [Leaflet/Leaflet#1059]
When using Chrome I cannot click and drag to pan a map, though I can use the keyboard to pan.
The scroll wheel also does not work, however you can zoom using Leaflet's buttons.

Both IE and Firefox work just fine, and I was using the example map at http://leaflet.cloudmade.com/ to test this.
I believe that map is running on Leaflet 0.4, although it also happens with any other Leaflet map I try to use.

I'm running on the latest stable version of Chrome (22.0.1229.94), with no extensions.

I didn't have any issues about a week ago, and I know Google released an update recently http://googlechromereleases.blogspot.com/

I also noticed that when I click and drag, I get a "ghosted" image of the map that follows my cursor.
It's almost like Chrome is treating the map like a static image.

**Comment by mtbsomi** [comment]
4 years later I can reproduce this in Chrome (Version 54.0.2840.87 m) within debugger view. (I'm trying to make my page responsive, so need some test.)

Keyboard works as mentioned above, so I can scroll with keys. 

However the test results are false, so touch not detected!

'ontouchstart' in document.documentElement
false
L.Browser.touch
false

On my phone I can scroll the map normally.

If I use a custom device, and it is set to Desktop device, I can scroll with mouse as without debugger view, so in my custom "kisfelbontású asztali" view everything is ok.

http://imgur.com/a/A5jPw

What should I change to be able to use the map in the debugger in responsive or in a selected mobile device / laptop mode?

(Sorry for my English :))
