### ISSUE TITLE
grid of black/white lines appear during zooming on Firefox

### ISSUE THREAD

**Issue by jfirebaugh** [Leaflet/Leaflet#1066]
Several users of Firefox have reported seeing a grid of black or white lines appearing while zooming on the OpenStreetMap leaflet map (http://leaflet.apis.dev.openstreetmap.org/).

[Frederik Ramm](http://lists.openstreetmap.org/pipermail/rails-dev/2012-October/001082.html):

> On my Firefox under Linux, I see a somehwat unpleasant grid of white lines at the tile boundaries when zooming in or zooming out; it is only visible as long as the new tiles haven't loaded and the old tiles are shown scaled. Naturally it is most visible over water. Anyone else see this, or is my machine acting up?

[Erik Johansson](http://lists.openstreetmap.org/pipermail/rails-dev/2012-October/001083.html):

> They are black on my Firefox version 16 on Linux.

I can also reproduce the white grid lines on Firefox 15 on Mac.

**Comment by af7** [comment]
I see the lines on latest Chrome, did anything change in Leaflet v1.0 in order to solve the problem? Thanks.

**Comment by IvanSanchez** [comment]
@af7 Make sure you're not experiencing #3575

**Comment by af7** [comment]
@IvanSanchez Indeed, this is exactly my issue. I hope you can find a solution.

Google Maps layer on leaflet also has another issue when dragging the map, the tiles delay their moves. Do you happen to know if there is a fix on this on v1.0? Thanks.

**Comment by naknode** [comment]
This appears on Chrome v47 on Max OSX as well El Capitan

**Comment by IvanSanchez** [comment]
@naknode You're experiencing #3575 then

**Comment by naknode** [comment]
@IvanSanchez My apologies. You are correct. I couldn't find the correct issue.
