### ISSUE TITLE
Memory leak: Webkit dont release memory for tile img

### ISSUE THREAD

**Issue by Scalar4eg** [Leaflet/Leaflet#107]
Removing any &lt;img&gt; from DOM tree not causes memory freeing in Webkit (i'm using latest 12.0.742.91):
all image files stay in memory even after removing their <img> elements.

So even if we set unloadInvisibleTiles to true - it not cause performance increase, and while you scroll the map - your memory leaking out.

You must set image element attribute "src" to "empty.png" or to empty string to remove previous image, stored in memory.

**Comment by SatadruBhattacharjee** [comment]
@mourner For reference , The Webkit Bug ID : https://bugs.webkit.org/show_bug.cgi?id=31253
Setting img src = '' does fix the memory leak.
