### ISSUE TITLE
missing tiles, unpredictable zooming with RTL layout

### ISSUE THREAD

**Issue by jfirebaugh** [Leaflet/Leaflet#1095]
Leaflet doesn't work very well with a right-to-left layout. Tiles are missing from all but the rightmost border, and zooming doesn't work as expected.

Test case:

```
<html dir="rtl">
<head>
  <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.4.5/leaflet.css" />
  <script src="http://cdn.leafletjs.com/leaflet-0.4.5/leaflet.js"></script>
  <style>
    #map { height: 100%; }
  </style>
</head>
<body>
<div id="map"></div>
<script>
  var map = L.map('map').setView([51.505, -0.09], 13);
  L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(map);
</script>
</body>
</html>
```

**Comment by ayyash** [comment]
I know this is an old thread, but I don't understand, is there something I should be doing to get it to work in RTL? a setting?

**Comment by mufaddalmw** [comment]
@ayyash For me I stoped compiling of RTL leaflet css and it worked. (so its using en css in ar )

**Comment by ayyash** [comment]
@mufaddalmw yes thats what i did too, I forced that part into ltr 👍

**Comment by alihajqani** [comment]
Hi, I using leaflet and vue2 leaflet in a vue basic template. When I change the layout to RTL I miss some of the tiles. like the attachment file.
Can you help me?
regards
![map](https://user-images.githubusercontent.com/33779789/85367609-d38c2b80-b53e-11ea-8bfe-d6ac17b29165.gif)

**Comment by shomalikhashayar** [comment]
> Hi, I using leaflet and vue2 leaflet in a vue basic template. When I change the layout to RTL I miss some of the tiles. like the attachment file. Can you help me? regards ![map](https://user-images.githubusercontent.com/33779789/85369146-c9b7f780-b541-11ea-92e3-2f2299ba52b5.gif) [ ![map](https://user-images.githubusercontent.com/33779789/85369146-c9b7f780-b541-11ea-92e3-2f2299ba52b5.gif) ](https://user-images.githubusercontent.com/33779789/85369146-c9b7f780-b541-11ea-92e3-2f2299ba52b5.gif) [ ](https://user-images.githubusercontent.com/33779789/85369146-c9b7f780-b541-11ea-92e3-2f2299ba52b5.gif)

I have same problem
