### ISSUE TITLE
Map tilesload event

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#11]

**Comment by hy9be** [comment]
The event is useful to interact with the new basemap tiles after user changes the zoom level or viewport. Can we have it implemented?

**Comment by mourner** [comment]
There's a TileLayer `load` event instead.

**Comment by hy9be** [comment]
It looks the load event only works for the initial loading of the map, rather than the subsequent viewresetting.

**Comment by mourner** [comment]
Not Map load event, but TileLayer load event.

**Comment by hy9be** [comment]
Okay I will give it a try. Thanks!
