### ISSUE TITLE
[IPad] input textbox and click button in custom control

### ISSUE THREAD

**Issue by geopan** [Leaflet/Leaflet#1163]
When a <input type="text or "search"> is placed in a custom control, the user can't get the focus on the textbox and interact with it either.

I have got the same problem with the Bing Geocoder plugin from sa3m so I assume that come from leaflet.

Happens on IPad in Opera and Chrome. Leaflet v4.5

**Comment by SebastianVomMeer** [comment]
The disableClickPropagation approach solves a lot of issues for me. I wonder if that can be extended to mousewheel events. My control area is scrollable but using the mousewheel goes through and zooms the map instead. Is there a similar approach to get this working?

**Comment by mourner** [comment]
@SebastianVomMeer try `L.DomEvent.disableScrollPropagation(el)`.

**Comment by SebastianVomMeer** [comment]
Thank you, works like a charm! :+1:
