### ISSUE TITLE
Switching layers manually doesn't update the layers control

### ISSUE THREAD

**Issue by jamesjenner** [Leaflet/Leaflet#1165]
I'm not sure if I'm missing something here, but I couldn't find a way to get the control to update after I had done a bringToFront() for a layer.

The problem can be seen [here](http://jsfiddle.net/metalskin/9TWb6/).

When the code runs it will set mapquest to the top, which works (it is displayed). But if you open the control, you see that it thinks that a different one is selected (ESRI World Topographical).

Just noticed that the attrib. is showing the one associated to ESRI World Topographical as well.

Cheers.

**Comment by simonpartel** [comment]
LevelControl.removeFrom(map);
