### ISSUE TITLE
Map freezes on Android 4.1.1 Samsung Galaxy Note2

### ISSUE THREAD

**Issue by florianf** [Leaflet/Leaflet#1182]
When pinch-to-zoom the map freezes with the enlarged tiles shown, no new tiles are loaded and the map can't be moved after. Zooming via the buttons with activated animations also freezes the map. This is reproducable for versions 0.4.4 and 0.5.

I think the problem is somehow related to the css3 animations. Disabling all animations and disabling pinch-to-zoom by manually setting the L.Browser.android23=true, fixes the freeze. 

First thought was, that the transitionEnd standard event isn't fired correctly, but the problem persists when using the webkit specific events (browser seems to support unprefixed events, but in our code transitionEnd wasn't fired, but webkitTransitionEnd was).

Interestingly everything works fine in stock Android 4.0.3 / CyanogenMod on a Samsung Galaxy S phone.

**Comment by VCodepp** [comment]
I can't show the map with webview.(Android 4.1.2) How did you manage?
