### ISSUE TITLE
Leaflet-rails plugin

### ISSUE THREAD

**Issue by axyjo** [Leaflet/Leaflet#1195]
Hi,

I was wondering whether you could add the leaflet-rails gem for Rails to the following webpage: http://leafletjs.com/plugins.html

The plugin is available at http://github.com/axyjo/leaflet-rails. Let me know if you'd like me to make a PR against gh-pages. Thanks!

**Comment by ghybs** [comment]
Hi @axyjo,

I see that you maintain the leaflet-rails gem, but for some reason your link has not made it into the Leaflet plugin page?

Please can you open a PR, or would you agree if I make the PR directly?

**Comment by axyjo** [comment]
@ghybs feel free to do it
