### ISSUE TITLE
EPSG 4326 Support Broken for TileLayers

### ISSUE THREAD

**Issue by jasonbeverage** [Leaflet/Leaflet#1207]
Map's created with crs: L.CRS.EPSG4326 appear to be broken.  http://jsfiddle.net/hueBa/3/ shows the issue.  The map only displays the western hemisphere of the earth and the marker is incorrectly positioned.

EPSG4326 L.TileLayer.WMS layers seem to work fine though.

**Comment by scottlepp** [comment]
@davidchouse can you provide a snippet of how you used scale?

**Comment by DrYSG** [comment]
@scottlepp - I no longer have any issues with 4326.

**Comment by scottlepp** [comment]
I'm on 0.7.x.  It appears the scale function should work on 0.7.x?  Trying @davidchouse example here:  http://plnkr.co/edit/rGH91y?p=preview

**Comment by DrYSG** [comment]
@scottlepp and @davidchouse I am using 0.8 with no problems.

**Comment by scottlepp** [comment]
@DrYSG tried 1.0 but still no luck:  http://plnkr.co/edit/2KZdXt?p=preview

**Comment by RyanHickman** [comment]
@scottlepp You're missing a { in your URL for {x}.

http://plnkr.co/edit/ZRJZv5zRM7OkXmfkLBh2?p=preview

**Comment by scottlepp** [comment]
Oops...thanks @RyanHickman

**Comment by scottlepp** [comment]
It's working on 0.7.x with a custom crs (based on what leaflet 1.0 is doing):  http://plnkr.co/edit/rGH91y?p=preview

**Comment by orangeagain** [comment]
I got this offset, X axis is correct, Y axis is wrong, anyone know how to fix it?
![无标题](https://user-images.githubusercontent.com/12761984/136363117-de651b06-4f03-4680-a1d1-c2f28545a507.jpg)
My code:
```
 var myCrs = L.extend({}, L.CRS.EPSG4326, {
          transformation: new L.Transformation(1 / 360, 0.5, -1 / 360, 0.5),
          }
        );
        var map = L.map('mapid', {
          crs: myCrs,
          zoomControl: false,
          attributionControl: false,
          zoomSnap: 0.25,
          maxBoundsViscosity: 1.0,
        })
       googlemap = 'http://172.23.163.76:8082/maps/vt?lyrs=s&gl=cn&x={x}&y={y}&z={z}&time=1602824597685&scale=2'
       var googleTerrain = L.tileLayer(googlemap, {})
```
