### ISSUE TITLE
Window scrolls on first click

### ISSUE THREAD

**Issue by ansjob** [Leaflet/Leaflet#1228]
I have an issue which causes different problems in different browsers.
I create a simple map and added a few markers, and when I click anywhere in the map the following happens depending on which browser I use:
- Chrome 23: The window scrolls vertically down to center the mouse pointer
- Firefox 17: The popup for the marker only fades in "half way"
- IE 8: The map enters some "dragging" mode and follows the cursor just like when clicking and dragging the map, this does not end until I click again (probably when there's an "on up" event).

The code is fairly integrated into my project, so it's a bit difficult to extract something that'll be useful to you guys, I'm just looking for a pointer in the right direction of where the problem could lie.
Thanks!

**Comment by nilguncelik** [comment]
This is still an issue on Chrome as of today ( 14/05/15 ).
As noted by a comment in commit  b61b7b4 by @Matheo13, removing `this._map._container.focus();` line (7743 in leaflet-src 0.7.3) fixes the bug.

**Comment by mourner** [comment]
@nilguncelik it's a master version fix (2).

**Comment by slako** [comment]
I saw something same issue in 1.0.3. My page scrolling up when I clicked the map after popup.
Issue going off when I commented string #12077:
`		window.scrollTo(left, top);`

**Comment by perliedman** [comment]
@slako this is an old and closed issue. If you believe you have found a similar issue, please open a new one, clearly stating the problem, and the platform you're seeing it on, and preferably also an example reproducing it.

**Comment by sumer9999** [comment]
Hi Folks, I still faced this issue. I added ID to the map by passing prop => id='mapDiv'

then in React hooks adding below effect
  useEffect(() => {
    document.getElementById('mapDiv').focus();
  });

**Comment by Candyffm** [comment]
> Hi Guys, i had the exact same issue on a bootstrap modal. I fixed it by focusing on the div id after loading all markers. :)

You did not see the scrolling behaviour at all with this workaround? This just caused instant scrolling / jumping for me.

**Comment by ardicoetzee** [comment]
I also have this problem.  This did make things better:
"document.getElementById('mapDiv').focus();"

But it's still not ideal. Unless you have a loading screen, you will still see that slight jerk. And I'm too scared to open it in Firefox to see how bad it is there. (I'm using Brave)

**Comment by jonkoops** [comment]
Locking this conversation as there is no use bumping issues that have been closed. As mentioned before, if you are still experiencing a similar issue please open up a new issue with clear steps to reproduce.
