### ISSUE TITLE
Create an IPopup interface and implement map, markers, etc in terms of this interface

### ISSUE THREAD

**Issue by abierbaum** [Leaflet/Leaflet#1249]
This is a general feature request for popups.  I have been writing a custom popup class and it works pretty well with the interface that map requires for popups (ie. addLayer and _close), but I can't bind it to Markers or Paths.  The reason is that those classes contain hardcoded references to instantiate L.Popup objects and use them.

I think it would make a very nice extension point in the system if everything was generalized a bit so there was:

* A common interface for plugin objects
* Config parameters to classes that create/user plugins so users can pass in their own

I am not sure, but I think this would be helpful to other people as well.

**Comment by mourner** [comment]
Now all layers are inherited from Layer which implements all popups methods so I think this can be closed.
