### ISSUE TITLE
Map jumping when scrolling beyond the bounds when tileLayer noWrap = true

### ISSUE THREAD

**Issue by Jakobud** [Leaflet/Leaflet#1267]
I am experimenting with Leaflet for use with a map from a fictional video game world, sorta like how people have made maps for Minecraft or other games.  The map is just a flat map.  It does not represent a planet or spherical body.  The map has a top, bottom, left and right sides.  It does not stretch on forever.  It's just a square map.

Here is a basic example of what I'm doing:

(I'm using some custom earth tiles for this example)
http://jsfiddle.net/CumhN/1/

If you start panning the map around, you will see that the map jumps to the next tiled map to the left and right.  The tileLayer has noWrap true, so the images are not wrapping, but it's still there.

Is it possible to disable this behavior and get what I want?  I just want a plain, flat, square map.  I want to allow the user to pan/zoom anywhere they want, but I don't want the wrapped maps to appear on the sides when they get too close to the edge of the map.

Also I notice sometimes when scrolling near the edge, it makes a snapping jump to the map next to it.

Is it possible to do what I want?

I did read through this issue:  #105  But I'm not exactly sure what the original user is doing or if they solved the problem I'm having or not...

Any help would be greatly appreciated.

**Comment by mattcav** [comment]
worldCopyJump: false will help to solve the second issue
