### ISSUE TITLE
Max/Min Zoom Visibility for layers or layer groups?

### ISSUE THREAD

**Issue by Jakobud** [Leaflet/Leaflet#1270]
Is it possible to set a Max and/ Min Zoom value for various layers or layer groups that would control what zoom levels those layers would be visible at?

For example: You have a marker with minzoom = 4 and maxzoom = 6.  As you zoom in the following levels, the visibility of the marker changes:

Zoom 1: invisible
Zoom 2: invisible
Zoom 3: invisible
Zoom 4: visible
Zoom 5: visible
Zoom 6: visible
Zoom 7: invisible
etc...

Is there something like this built into Leaflet Layers or LayerGroups?  If not, would the only option for implementing this be to hook the map's `zoomend` and then selectively show/hide layers depending on what you have set for their min/max zoom values?

**Comment by Luooooooo** [comment]
so, how did you resolve it? @Jakobud
