### ISSUE TITLE
Enable gzip compression for CDN

### ISSUE THREAD

**Issue by Koc** [Leaflet/Leaflet#1306]
From PageSpeed:

>Сжатие следующих ресурсов посредством gzip позволит уменьшить их размер для переноса на 140.9Кб (на 75%).
>
>    Сжатие http://cdn.leafletjs.com/leaflet-0.4.4/leaflet-src.js позволит уменьшить размер на 134.7Кб (на 75%).
>    Сжатие http://cdn.leafletjs.com/leaflet-0.4.4/leaflet.css позволит уменьшить размер на 6.1Кб (на 75%).

**Comment by kynan** [comment]
Could you explain this in English please? Why was this closed? There is still no gzip compression for the resources on the CDN afaict.

**Comment by danzel** [comment]
Use google translate, mourner says to use cdnjs which has gzip compression.

**Comment by mourner** [comment]
Actually I think this should be revisited. Initially I worried that CloudFront doesn't support automatically gzipping and serving based on content headers. But now that all browsers/clients support gzip, we should just gzip by default.

**Comment by innerspirit** [comment]
Hi, I saw this issue on http://up-for-grabs.net/ and wanted to give it a shot, see if I can help you guys out.

Does this refer to the leaflet website itself? Anyhow, I have not been able to find the code for the backend, just the frontend, and this looks like either a backend issue or a cdn configuration issue.

**Comment by mourner** [comment]
We switched our CDN to unpkg.com, so this can be considered fixed. http://leafletjs.com/download.html
