### ISSUE TITLE
Hiding markers off-screen to increase performance

### ISSUE THREAD

**Issue by skunkfu2** [Leaflet/Leaflet#1324]
I’m not sure if this is a minor or major feature, and that it has probably already been suggested (with the MarkerCluster plugin being the result) but I will give it a shot.

I am placing custom markers on a game map for loot locations. Currently there are approx. 200 markers on the map, and I have covered around 10% of it so far. When viewing the map with all the markers displayed on either the laptop or a Galaxy Nexus, I notice a slowdown of the map. I fear this will grow significantly when I've placed all the markers.

I would consider using MarkerCluster if it wasn't for the nature of needing to see all of the marker locations at once, and the whole two clicking bug in Android using a WebView (even with jerel’s fix).

Question: How easy would it be to implement a function that would hide markers that are off screen, just like how the tiles are rendered? This would boost the map performance considerably, and be of much help for many people.

I realise this has probably been looked at before, and there is a reason why such a feature hasn't been implemented, but I thought I’d ask.

Thank you for Leaflet Vladimir and its contributors, it has been bliss for me so far :)

**Comment by Danielku15** [comment]
Even though I might be reviving corpses here with this comment I wanted to share my fiddle with you guys. We today encountered a similar issue that with 1000+ markers the map starts to lag. 

Enabling markercluster as plugin might be a bit an overhead and also did not provide satisfying results for us. MarkerCluster might delay the icon creation leading to problems when you also want to update icon styles for hidden markers. 

I created a small mixin/extension to the `L.Marker` class which does nothing but removing/adding the icons and shadows from/to the DOM depending on their visibility. The result can be seen here: 

https://jsfiddle.net/n5rqfhg9/7/ (Virtualization Enabled - Smooth)
https://jsfiddle.net/n5rqfhg9/8/ (Virtualization Disabled - Laggy)

The demo also shows the number of marker and shadow DOM elements. Also it does not improve the loading time but once the markers are initialized, the zooming and panning is a lot smoother than without virtualization. 

Also be aware that the add/remove of the icon from the DOM might have side effects like a spoiled z-index of elements.

**Comment by dyardyGIT** [comment]
@Danielku15 I am not sure i notice difference in #7 and #8 above.  Is this still best choice for showing/hiding based on bounding box?
thanks

**Comment by Danielku15** [comment]
@dyardyGIT What browser did you use in testing? I can see a noticeable performance difference on the latest chrome. I tried to record it but due to the compression some details might be lost. [here the gif on giphy](https://gph.is/g/4DAAQvn).

**Comment by joachimoak** [comment]
Thanks @Danielku15 ; very useful.

**Comment by jake-cryptic** [comment]
Thank you @Danielku15 ! 

The code snippet you posted increased the performance of my map significantly (I'm rendering about 19,000 markers spread across the UK)

**Comment by bhekuwenza** [comment]
👍  @Danielku15
