### ISSUE TITLE
Improve the navigation in the API page

### ISSUE THREAD

**Issue by paulovieira** [Leaflet/Leaflet#1327]
The API page looks great. However, as Leaflet gets more core methods and options, the navigation between the different classes becomes difficult. I have to scroll up and down endless times until I find the class I'm looking for.

It would be much easier if there was a fixed lateral navigation menu, displaying all the classes (as the menu on the top).

I was thinking in something similar to the "affix" plugin from twitter bootstrap:
http://twitter.github.com/bootstrap/javascript.html#affix

Or the "magellan" component from zurb foundation:
http://foundation.zurb.com/docs/magellan.php

This would make the API page even greater.

Thanks.

**Comment by mourner** [comment]
Done in #3578
