### ISSUE TITLE
WMS tiles disappear on zoom out in Chrome on OS X

### ISSUE THREAD

**Issue by drwelby** [Leaflet/Leaflet#1351]
In map with a tiled base layer, a transparent WMS layer on top of that, and geojson vector layer group on the very top, the WMS tiles disappear when zooming out. They'll flash in briefly before disappearing sequentially in a sort of spiral pattern. Panning after a zoom out also shows the same disappearing tile behavior. Too make things more interesting, one tile will remain displayed, and independent of zoom level the remaining tiles are all about in the same place in space.

Zooming in, and pans after a zoom-in, work as expected. I don't have a public example at the moment but will try to get something up. I don't see this behavior in Safari, or on iOS for that matter.

Chrome 21.0.1180.89
OS X 10.6.8
Leaflet 0.5

**Comment by sookoll** [comment]
I just ran into same behaviour in Mac OSX + chrome, safari, opera, ff. Using leaflet-1.0.0-beta1.
JsFiddle: https://jsfiddle.net/Pe5xU/79/
