### ISSUE TITLE
Please, remove *.js dist files

### ISSUE THREAD

**Issue by Vanuan** [Leaflet/Leaflet#1354]
Keeping those dist files in the repo causes huge pain when merging.
I think they should be removed and added to the `.gitignore` file.

If people want the built version, they shouln't go to github, built versions should be stored elsewhere. Or they should run jake to build it themselves.

It shouldn't be hard to set up travis to push built versions to the github pages.

**Comment by nmccready** [comment]
So what is the aws s3 url for https://github.com/Leaflet/Leaflet/releases/tag/v1.0.0-beta.1 or beta.2? \

 http://leaflet-cdn.s3.amazonaws.com/build/leaflet-1.0.0-beta1.zip ? Is there a url which outputs the entire possible list of downloads avail?

**Comment by nmccready** [comment]
Partial list is here, http://leafletjs.com/download.html. Honestly this breaks bower completely as other dependent libraries have no idea what version they will be on. I guess we should switch to npm for angular-leaflet-directive. 

As a possible compromise why not publish the dis/.*.js only on tagging? This would have the same effect as publishing to npm and keeping your development complications down on merging.

**Comment by mourner** [comment]
@nmccready that's exactly what we do already. The fact beta1 didn't have dist files commited is a bug, I'll figure out what's going on before pushing beta2.

**Comment by mourner** [comment]
On a related note, I hate bower.

**Comment by nmccready** [comment]
Ha, well we may change to npm; but I can't make that decision on my own.

**Comment by nmccready** [comment]
In theory angular-leaflet-directive should support npm, but is currently targeted towards bower more.

**Comment by nmccready** [comment]
On a side note I feel your pain on angular-google-maps I have to support meteor too. So I am managing 3 package managers. Total nightmare to add the 3rd (meteor). See this feed for same type of complaints https://github.com/mbostock/d3/pull/2130#issuecomment-64965388 :)

**Comment by Vanuan** [comment]
Seems like JSPM is a new hotness now.

**Comment by trusktr** [comment]
Why not just finally convert to CommonJS or ES6 modules @mourner? That'll solve lots of problems (including global builds compiled from the project index.js file which simply just imports everything?).

For example: https://github.com/infamous/motor/blob/joe/package.json#L18 and https://github.com/infamous/motor/blob/joe/src/index.js

That library is work-in-progress, but the build scripts are useful. See [here for details on how that package.json file was designed](http://forums.infamous.io/t/api-build-system-goals/46/2?u=joe). It supports many build-system use cases. The only thing missing is support for bower, in which case the `build-global` script would be a big stepping stone for that.

Just do it, you can probably convert in like, a day.

**Comment by mourner** [comment]
> Seems like JSPM is a new hotness now.

Hereby I predict that NPM will eventually win over any "new hotness" package managers that appear every single day. I'll be really happy when that happens.

@trusktr for background on ES6 modules in Leaflet, see #3229. I thought about converting to it or CommonJS some day, but it's not a priority right now. And we don't have as many problems with the current setup as you suggest. Also, CommonJS/ES6 won't save us from Bower issues.

**Comment by nmccready** [comment]
JSPM another shinny thing .. kill me now :skull:

**Comment by Vanuan** [comment]
> JSPM another shinny thing

If you learn more about it, you'd be happy to know that jspm is just a tool and a registry that makes possible to use both bower and npm registry in one project.

**Comment by nmccready** [comment]
I did look into and yes its another layer of management to deal with for many projects.  I am not necessarily bashing jspm. But it would be nice if they worked together to just update npm instead of adding something else. 

Just venting , anyways the community will decide.

**Comment by trusktr** [comment]
> is just a tool and a registry that makes possible to use both bower and npm registry in one project.

Yep, JSOM doesn't replace NPM. It uses NPM (plus bower, github, and other sources). It's a package manager that lets you specify *where* packages come from, including NPM.
