### ISSUE TITLE
Zooming under Android 3 crashes the browser

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#137]
The browser crashes when zooming on Android 3 tablet. Have no idea why this happens and how to debug this, so any help is much appreciated.

**Comment by kaynz** [comment]
Is this still an issue?
`		if (!L.Browser.android) {
			this.on('tileunload', this._onTileRemove);
		}`

My app is running fine on Crosswalk 22 (Chromium 52) without the upper check.
