### ISSUE TITLE
Zoom out via double right click Edit

### ISSUE THREAD

**Issue by maugsburger** [Leaflet/Leaflet#1378]
I'm used to zooming out via double right click, which doesn't work with Leaflet. On normal google map, this works fine.

**Comment by tranzitwww** [comment]
It is possible with

`
var Right_dblclick = false;

map.on("contextmenu ", function(e) {
	if(Right_dblclick) {
		if (map.getZoom() > 2) {
			map.setZoom(map.getZoom() - 1);
		}
	} else {
		Right_dblclick = true;
		setTimeout(function(){Right_dblclick = false;}, 250);
	}
 });`
