### ISSUE TITLE
map.closePopupOnClick doesn't work

### ISSUE THREAD

**Issue by drolbr** [Leaflet/Leaflet#1391]
Changing map.closePopupOnClick doesn't change the behaviour of the map.

In the example
http://overpass-api.de/leaflet-example.html
I've set on purpoose map.closePopupOnClick = false. But still the popup closes on click somewhere.

**Comment by jameeshpm** [comment]
Hi I wanted to extend L.Map Like this
L.Map = L.Map.extend({
                openPopup: function(popup) {
                    //        this.closePopup();  // just comment this
                    this._popup = popup;

                    return this.addLayer(popup).fire('popupopen', {
                        popup: this._popup
                    });
                }
            });

But i am using leaflet is there anyway to extent like so that i can prevent closing my marker popup

**Comment by foobarbecue** [comment]
These options appear to be broken. Repro: http://jsfiddle.net/776cc6Lc/1/

**Comment by foobarbecue** [comment]
ugh, 4189

**Comment by foobarbecue** [comment]
Ok, I see. This only happens if you take a shortcut and create the popup using `mymarker.bindPopup("SomeText")` instead of using `let mypopup = leaflet.popup(); mymarker.bindPopup(mypopup)`

**Comment by perliedman** [comment]
@foobarbecue this issue is very old and most likely doesn't have the correct context.

If you believe there is still an issue with `closeOnClick` or `closePopupOnClick`, please open a new issue with an example illustrating the issue.
