### ISSUE TITLE
Is Point in Polygon function within scope of project?

### ISSUE THREAD

**Issue by Jakobud** [Leaflet/Leaflet#1480]
In my map app, I added some code to determine if a `LatLng` point is within the bounds of a Polygon (returns boolean).  I was going to provide a pull request with this code for the project, but first I wanted to ask here if it was something you considered to be within the scope of the project enough to put it in or not.  I didn't see anything like this in the existing project so I wasn't sure.  But it is definitely helpful.  And honestly the code itself is pretty basic and not bloaty.

**Comment by 3zzy** [comment]
@Jakobud Could you please share your code?

**Comment by Jakobud** [comment]
@3zzy Well, it's somewhere in this project:

https://github.com/ps2maps/ps2maps.com

Honestly I can't remember what I would have been using this for in the project so I'm not sure where to look in the files for it. Maybe you can find it.

**Comment by 3zzy** [comment]
@perliedman Thanks, but ideally I’m looking to achieve this without any dependencies. I’m trying a solution posted here https://stackoverflow.com/a/31813714/172637 but doesn’t to work. I’ll find @Jakobuds solution and see if it works.

**Comment by stefangrotz** [comment]
I can recommend turf.js (http://turfjs.org/) to put a marker in the center of Polygons.
