### ISSUE TITLE
Target zoom in zoomstart event data

### ISSUE THREAD

**Issue by Jakobud** [Leaflet/Leaflet#1509]
I wanted to run an event that would tell me what zoom level I was zooming to, when zooming:

```
map.on('zoomstart', function(event)
{
  console.log(event.target);
  console.log(event.target._animateToZoom);
}
```

When loading up a map, the first time I zoom, this returns `undefined`.  The next time I zoom (and every time after that) it returns the expected result.

The `undefined` is returned even though I inspect the `event.target` from the previous `console.log` and I can see that the value is there and that it's clearly not `undefined`. 

Any clue as to why I'm seeing this behavior?

**Comment by mourner** [comment]
Closing, see https://github.com/Leaflet/Leaflet/pull/1600#issuecomment-77186793
