### ISSUE TITLE
Strange Behavior in chrome and firefox

### ISSUE THREAD

**Issue by ghost** [Leaflet/Leaflet#1519]
Hello I have a fairly simple leaflet app you can see here https://gist.github.com/tyrel86/5167688.

The map loads and all of the markers are properly positioned however the center is off. I set the center to Denver Colorado and the map loads some 75 miles west. Then even odder both in Chrome and Firefox when inspect element is opened the map snaps to Denver and looks exactly like I wanted it to.

Also before this happens the map behaves sluggishly. It sometimes doesn't load tiles leaving random grey boxes and when it does load them it takes longer than it should. Again very odd yet as soon as inspect element is opened every thing starts working perfectly. No javascript errors are logged. I can then close the inspect element window and everything continues to function nicely. 

Does any on have any insights as to why this is and what can be done about it. Thank you.

**Comment by fcFn** [comment]
I had the same issue and solved it by wrapping with a `$(window).on("load", {...})`, but I also had to disable Rocket Loader feature on CloudFlare.
