### ISSUE TITLE
Responsive Map?

### ISSUE THREAD

**Issue by Jakobud** [Leaflet/Leaflet#1544]
Is it possible to create a map that is responsive to the size of the container that you put the map in?  I'm looking at various things regarding CRS scale but I'm not sure if it's possible or not...

**Comment by heldchen** [comment]
as a workaround until this is fixed `.leaflet-container { -ms-touch-action: inherit !important; touch-action: inherit !important; }` can be added to the embedding page's css. tested in chromes device emulator.
