### ISSUE TITLE
Map tiles are not clipped by border-radius in Webkit

### ISSUE THREAD

**Issue by frankrowe** [Leaflet/Leaflet#1549]
Setting border-radius on the #map div does not affect the map itself. Not sure if this is a bug in Webkit, Leaflet, or expected behavior. Looks good in Firefox and IE 9.

![Caroline DES](https://f.cloud.github.com/assets/410285/304926/fc022a76-964a-11e2-85b3-960eb6b5568f.png)

**Comment by clentfort** [comment]
Thank you so much for this answer <3

**Comment by jonathanlurie** [comment]
Hey, I tried @gwithian  trick and it works well, even with another value. Seems that just to specify a z-index make it work (Chrome Version 49.0.2623.112 )

**Comment by romaopedro** [comment]
@gwithian thanks, it works

**Comment by dankarran** [comment]
@gwithian this neat little trick works in Safari too - thanks!
