### ISSUE TITLE
Make it clear in the docs what layers from the layers control are shown

### ISSUE THREAD

**Issue by tmpsa** [Leaflet/Leaflet#1580]
If a map is initiated with more than one base layer, and a L.control.layers is set up for those base layers, then ALL base layers will be shown, in quick sequence. Very ugly. Only one should be drawn, of course.

The problem seems to be in this case that there's no default base layer set. So all of them are drawn.

There should be a built-in mechanism to by default set the first of the specified base layers as 'selected'.

There should also be a API method to specify some other layer as the default selected.

See:

http://leaflet.uservoice.com/forums/150880-ideas-and-suggestions-for-leaflet/suggestions/2635855-make-layer-control-docs-example-clearer-about-whic

http://leaflet.uservoice.com/forums/150880-ideas-and-suggestions-for-leaflet/suggestions/3825916-a-method-to-set-which-radiobutton-is-selected-in-l

**Comment by Timmmm** [comment]
Still an issue IMO. I only found the answer here after a few minutes of fruitless searching for "leaflet set default layer", "leaflet set layer", etc.

**Comment by ismailsunni** [comment]
Hi @Timmmm 
As @mourner said, just add to the layer control, but don't add it to the map.

```
layerControl = L.control.layers().addTo(map);
layerControl.addOverlay(tile_layer , "layer_name");
map.addLayer(tile_layer);  # Add this if you want to show, comment this if you want to hide it.
```

I stumbled on the same issue also.
