### ISSUE TITLE
map within offset iframe does not grab click event

### ISSUE THREAD

**Issue by kaore** [Leaflet/Leaflet#1605]
When a map is displayed within an iframe which is not placed at the top of a page, a click on the map causes the browser to scroll down to the iframe position and the click event to be lost.

See here for an example: http://dl.dropboxusercontent.com/u/2009989/tests/leafletiframe/parent.html

**Comment by robbiet480** [comment]
Just wanted to leave a note that this also fixed my iFrame + Leaflet related issues. We are running inside of a Facebook Page Tab which is just an iframe pointing to our content. We had an issue where clicking any kind of link was causing the page to jump so the top of the iframe was at the top of the window. Just throwing `{keyboard: false}` into options instantly fixed it, and let us remove all our hacks, so thanks!
