### ISSUE TITLE
Overlays obscured by baselayers when using layer control and layergroups.

### ISSUE THREAD

**Issue by spamdaemon** [Leaflet/Leaflet#1667]
This issue may be related to #1096. I've tried to reproduce the issue here (using github/master):
http://plnkr.co/edit/RyEYkY?p=preview

This is a simple example with 3 layers,  2 base layers and 1 overlay layer. Each layer lives within a layergroup. The layer group is added to the control before adding any layers to it.

Initially the layers are displayed correctly, but after toggling the baselayers once or twice, they obscure the overlay. 

The problem goes away if I add my layers into the group before adding the group to the control. Setting a z-index on the layergroup had no effect.

**Comment by jzadra** [comment]
This seems to still be a problem. When I change the base layer (polygons), the overlay layer gets pushed behind the base layer.

**Comment by perliedman** [comment]
@jzadra can you provide a running example of the issue?

**Comment by jzadra** [comment]
@perliedman yes, however I"m using leaflet R.  I've also posted this here: https://github.com/rstudio/leaflet/issues/430

```
require(acs)
require(tigris)
require(leaflet)
require(tidyverse)

leaflet(data = counties(state = "UT")) %>% 
  addPolygons(color = "red", fillColor = "orange", group = "base1", fillOpacity = 1) %>% 
  addPolygons(color = "pink", fillColor = "purple", group = "base2", fillOpacity = 1) %>% 
  addPolygons(color = "yellow", fillColor = "green", group = "overlay", fillOpacity = 1) %>% 
  addLayersControl(baseGroups = c("base1", "base2"), options = layersControlOptions(collapsed = F), overlayGroups = "overlay")
```
Output from the above code: http://rpubs.com/bvila/overdraw

Also posted here:
https://stackoverflow.com/questions/44122246/r-leaflet-is-drawing-base-layers-on-top-of-overlay-layers

**Comment by newmanw** [comment]
This is a problem for me as well.

If you can only ever turn on one base layer, why is a base layer is not always on the bottom?  

If you had a control that could turn on more than one base layer then maybe set all base layers to the same z index, but shouldn't overlays always have higher z-index than base layers?

**Comment by perliedman** [comment]
@newmanw can you provide an example where this is an issue? If you leave `autoZIndex` enabled, this should work as long as you add the layers in correct order; if you can't do that, disable `autoZIndex` and use `setZIndex` individually on your layers for the desired order.

**Comment by newmanw** [comment]
@perliedman 

> If you leave autoZIndex enabled, this should work as long as you add the layers in correct order; if you can't do that, disable autoZIndex and use setZIndex individually on your layers for the desired order.

This is of course correct :)  The confusing part from a user standpoint IMHO is that a base layer is on the bottom and overlays are overlaid on top.  With the current setup a user gets into trouble with that assumption, as that is not how leaflet works.  Currently base layers are just a mutually exclusive layer group of overlays.

Has there been any consideration to always putting baselayers at a lower zindex to overlays?  Then autoZIndex is a feature of overlays, not base layers.

**Comment by IvanSanchez** [comment]
Please remember we have map panes (and a tutorial for them) since Leaflet 1.0.

**Comment by newmanw** [comment]
@IvanSanchez thanks!

Still begs the question, no 'baseLayerPane' by default? Or at least why are layers marked as base layers going in the same pane as overlays?  Goes back to why call something a 'base layer' if you are able to put it on top of overlays?

Thoughts on Control.Layers adding base layers to a different pane (with a lower z-index) than overlay layers?

**Comment by perliedman** [comment]
@newmanw the terms "baselayer" and "overlay" only exist in the layers control. The rest of Leaflet isn't designed with this difference, if you don't count vector layers and markers, which end up in their own panes. For ordering among tile layers (and vector layers and markers, respectively), it's up to the application to arrange the order. My guess is that `autoZIndex` was introduced for this very reason, to help do this in a fashion that works for most.

Making the layers control rearrange the panes of added layers does not look like a good idea to me.
