### ISSUE TITLE
Some form of control over z-order of a layer when adding it

### ISSUE THREAD

**Issue by JasonSanford** [Leaflet/Leaflet#167]
Perhaps this is related to [issue 73](https://github.com/CloudMade/Leaflet/issues/73), but I think it would be helpful to have two different types of tiled maps.

I'm using standard base maps from CloudMade, MapQuest, etc and I'm overlaying a custom tiled map of bike trails on top. Switching "base maps" puts my custom overlay map on the bottom and the base map on top, which is far from ideal.

**Comment by cdunlap** [comment]
Thank you!!

**Comment by Slevender** [comment]
Should the zIndex or .setZIndex(x) in 2017?
