### ISSUE TITLE
hasLayer not working when supposed to be false

### ISSUE THREAD

**Issue by florentj46** [Leaflet/Leaflet#1724]
Hi,

I have a map displaying a building that I retrieve from a Geoserver. It's composed of 3 base layers, each base layer corresponding to a floor. I also have 2 overlays, a heatmap and a set of markers representing the locations of some sensors.

When I switch the base layer, I'd like to update the overlay if it's displayed. To check wether an overlay is displayed or not, I use the method map.hasLayer(overlay). This method works when the overlay parameter is displayed on the map. However, if it isn't, the method bugs and the code after the call of the method is not read.

Here is my code : 

```
        map.on('baselayerchange', onBaseLayerChanged);

        // Called when the base layer (meaning the floor) is changed
        function onBaseLayerChanged(event) {
            // Update the current floor
            if (event.layer == ground_floor)
                current_floor = ground_floor;
            else if (event.layer == first_floor)
                current_floor = first_floor;
            else if (event.layer == second_floor)
                current_floor = second_floor;

            // Update the heatmap and sensors' location
            // if they are displayed
            if (map.hasLayer(heatmapLayer)) {
                removeHeatmap();
                addHeatmap();
            }

            if (map.hasLayer(sensorsLayer)) {
                removeSensors();
                addSensors();
            }

        }
```

So if the heatmapLayer is displayed, it works. If it isn't, it doesn't and the second if condition is not checked.

I must have done a silly mistake but I don't see it, although I'v been seeking for a long time...

I hope I've been clear enough to let you understand my problem.

Thanking you in advance.

**Comment by caglardursun** [comment]
The problem is still exist in here http://jsfiddle.net/EaKn6/2/ @mourner 
When you try to change the layer in first time, event cannot fired. But second time it will work.

**Comment by IvanSanchez** [comment]
@caglardursun The `baselayerchange` event fires when a base layer is *added* to the map. In your case, you're initializing the map with both base layers, so the first change doesn't add any layer, so no event is fired. This is *not* a bug in Leaflet but rather a PEBCAK.

Change this:
```js
    mapOptions.layers.push(baseMap);
```
with this:
```js
    if (i===0) mapOptions.layers.push(baseMap);
```
