### ISSUE TITLE
Idea: LayerGroups show/hide via grouped css display:none/block

### ISSUE THREAD

**Issue by Jakobud** [Leaflet/Leaflet#1734]
I have an idea for how Leaflet could possibly be improved in order to increase performance for quickly showing/hiding LayerGroups:

I've had a hard time determining the best way to turn on/off LayerGroups, for maximizing speed and performance.  In my mapping application, I have various markers on the map showing or hidden, depending on what zoom level the map is currently at.  I simply hook the `zoomend` event and, based off of predefined values, LayerGroups are either added to the map or removed from the map, depending on if they should be visible or not for the current zoom level.

So the problem with this, is that `myLayerGroup.addTo(map)` and `map.removeLayer(myLayerGroup)`, basically consists of Leaflet iterating through each layer in the group and individually adding to or removing from the map.  I feel like this is potentially slow, especially if you have a lot of markers on a map.

So I had a bit of an idea today.  Lets say I have 5 LayerGroups of markers.  Each one of those markers is put in this DOM heirarchy:

```
<div class="leaflet-marker-pane">
    <div class="leaflet-marker-icon leaflet-zoom-animated"></div>
    <div class="leaflet-marker-icon leaflet-zoom-animated"></div>
    <div class="leaflet-marker-icon leaflet-zoom-animated"></div>
    <div class="leaflet-marker-icon leaflet-zoom-animated"></div>
    etc...
</div>
```

So all of the markers are put under the same `div.leaflet-marker-pane`, even though they are in different LayerGroups.  So here is where my idea comes into play: What would happen if you grouped Layers under individual div's, one for each LayerGroup?  So you would have this:

```
<div class="leaflet-marker-pane">
    <div class='myLayerGroupContainer'>
        <div class="leaflet-marker-icon leaflet-zoom-animated"></div>
        <div class="leaflet-marker-icon leaflet-zoom-animated"></div>
    </div>
    <div class='someOtherLayerGroupContainer'>
        <div class="leaflet-marker-icon leaflet-zoom-animated"></div>
        <div class="leaflet-marker-icon leaflet-zoom-animated"></div>
    </div>
    etc...
</div>
```

So now, if someone wanted to show/hide a LayerGroup, it would simply be a matter of doing `myLayerGroup.hide()` or `myLayerGroup.show()`, which would simply change the css `display` to `none` or `block`.  Now it's just a basic css change to hide/show all the LayerGroup markers.  No need to iterate through 100's (or 1000's) of individual markers/layers and adding/removing them.  Seems like this would be MUCH faster.  No more JavaScript overhead.

Also another advantage to this approach, is that if your LayerGroup consists of multiple types of layers (markers, polygons, popups, etc), each type of layer could still be grouped under a `<div class='myLayerGroupContainer'>` within each appropriate map pane.  So the usage would be the same.

That being said, I don't really know anything about the performance drawbacks of having a bunch of layers/markers on a map but simply having them hidden.  I know that removing a LayerGroup actually removed the layers from the DOM. So if there were 1000's of markers on the map, but simply hidden in the DOM, does it affect performance or not?  I don't really know the answer to this, but in this type of situation, `map.remove(myLayerGroup)` and `myLayerGroup.addTo(map)` is still an option.

What do you guys think about this?  Would this be worth investigating?  I haven't tested this yet but it seems like it would be a great performance improvement if you have a mapping application that shows/hides markers a lot.

**Comment by mnquintana** [comment]
Are there any updates on this? (Last update was almost 2 years ago, so just wanted to check.)

**Comment by Jakobud** [comment]
Yes this is all possible in 1.0 beta using the Pane Management features.

**Comment by mnquintana** [comment]
@Jakobud Awesome, thanks! Is anyone using 1.0 beta in production yet? I'd like to get a sense for its stability.

**Comment by Jakobud** [comment]
I've been using a version of it from several months ago for ~ 4+ months now in production without issue on http://ps2maps.com

**Comment by thewebkid** [comment]
This is massively important to us in an analytics application. We create thousands of polylines we want to group and toggle temporarily. This is in its early stages, so any ideas on caching in mem and re-rendering would help. Currently setting opacity to 0 and ignoring pointer events based on state, but that is a terrible hack.

**Comment by perliedman** [comment]
@thewebkid if you want to hide/show layers as a group, I'd currently suggest using panes and hiding/showing the pane (a pane is just a DOM element, so you can use any common DOM manipulation there).

There is a tutorial about panes, if you haven't seen it: http://leafletjs.com/examples/map-panes/

**Comment by perliedman** [comment]
@mourner @Jakobud I tried reading through the comments here to understand why this is still open.

On one hand, it looks like what we're discussing is already possible using panes, but maybe with a less intuitive API than suggested here. On the other hand, it looks like @mourner had ideas about actually implementing something (https://github.com/Leaflet/Leaflet/issues/1734#issuecomment-30091754).

I'm going to go ahead and actually close this for now, since my understanding is this is not something we really need. Just tell me if you think this is the wrong decision, and what the plan ahead here should be.

**Comment by thewebkid** [comment]
Ah thanks for telling me about panes. That'll probably save me a lot of "pain". Will check it out.

**Comment by Jakobud** [comment]
Indeed panes did solve this issue. I'm not sure why it was left open.

**Comment by bimalgrg519** [comment]
Thank you @Jakobud ...

**Comment by bimalgrg519** [comment]
Here is my solution on this topic.. Let me know if this helped you..

```
map.createPane("myCustomPane");
var marker = L.marker([51.5, -0.09], { icon: customIcon, pane: 'myCustomPane'}).addTo(map);
```
