### ISSUE TITLE
Refresh tiles by force / memory leak

### ISSUE THREAD

**Issue by dantel35** [Leaflet/Leaflet#1772]
Hi. I need Leaflet to refresh all visible tiles by some actions like dragend. I stumbled upon this ticket: https://github.com/Leaflet/Leaflet/issues/788

Someone there suggests to use "map._resetView(map.getCenter(), map.getZoom(), true)" to accomplish a smooth refreshing. While this works quite good at the beginnig, it seems to consume all available memory over time making leaflet unusable after some time.

map._resetView(map.getCenter(), map.getZoom(), false) does also reset the view, but you can see the screen becoming black for a moment before the tiles are reloaded which is really annoying. Here the memory leak does not appear.

Can somebody explain this to me or even better provide a solution for my problem resetting the view without visible flickering?

I appreciate every hint. Thanks in advance!

**Comment by jonomillin** [comment]
Is there a possibility that this has been improved in Leaflet 1.0?

**Comment by nickponline** [comment]
@mourner I'm also very interested in your answer to this ^

**Comment by perliedman** [comment]
@nickponline Could you provide a reproducible example which triggers these crashes? AFAIK the Leaflet team isn't aware of any crashes from excessive memory consumption.

Having said that, of course Leaflet, just like any web page, _will_ have trouble if you just throw in huge numbers of images (like a large number of stacked tilelayers). Like @mourner says above, to our knowledge this is not a Leaflet problem but a general problem for the browser.
