### ISSUE TITLE
Mouse wheel zooms too fast in FF

### ISSUE THREAD

**Issue by klimashkin** [Leaflet/Leaflet#1794]
One mousewheel zooms page 3 times.
Leaflet 0.6, FF 22

**Comment by ganeshx** [comment]
Has this issue been fixed? The zoom in/out is too sensitive

**Comment by mourner** [comment]
@ganeshx can you try the master version?

**Comment by CramericaIndustries** [comment]
Sorry but that bug is back. Tested with Fire Fox 54.0.1 and Leaflet 1.1.0. Chrome works fine (v59.0.3071.115).
Example map: [http://leafletjs.com/](http://leafletjs.com/)

**Comment by perliedman** [comment]
@CramericaIndustries please open a new issue if you believe this is a bug in the current Leaflet release, it's highly unlikely it's related to this four year old issue.

**Comment by CramericaIndustries** [comment]
The `mousewheel.with_alt.delta_multiplier_y` parameter was set to `500` (default 100) in `about:config`
