### ISSUE TITLE
Prevent map tile images from dragging.

### ISSUE THREAD

**Issue by AndreyKozlov1984** [Leaflet/Leaflet#1821]
I use leaflet inside an ExtJS app. I test in Chrome. I use Mac OS X, Retina display. The openstreetmaps layer images are draggable, i.e. I drag the tile img which looks weird.
This css style solves the issue: {
  -webkit-user-drag: none;
  user-drag: none;
}
Leaflet already uses -webkit-user-select: none. It is enough in most cases, but looks like not always.

I'll try to set up a jsfiddle example but whatever I think this extra css will not make things worse. At least that is what I use as a workaround in my current project.

**Comment by nara007** [comment]
jfirebaugh  L.DomUtil.disableImageDrag() works like a charm,  thank you !
