### ISSUE TITLE
Layers control minimises itself too quickly in IE8

### ISSUE THREAD

**Issue by kingrollo** [Leaflet/Leaflet#1850]
See the Leaflet example page here: http://leafletjs.com/examples/layers-control.html

Behaviour is as follows in IE8:
- Hover over the control, it expands
- Click on a layer name to change visibility, nothing happens and it minimises
- Click on a checkbox / radio to change visibility, it works but minimises immediately

This is different from the behaviour in Chrome/FF/etc:
- Hover over the control, it expands
- Click on a layer name, it changes visibility and stays expanded
- Click on a checkbox / radio, it changes visibility and stays expanded

I've just checked against Leaflet 0.5.1 and IE8 was working as expected.

**Comment by Turbo87** [comment]
@mourner I've run into similar problems in https://github.com/Turbo87/leaflet-sidebar/issues/31 and just found out about `_fakeStop()` which would fix that issue. It appears to be a private method though and I wanted to make sure that it won't be removed in the near future.
