### ISSUE TITLE
No option exists to add an id to divIcon

### ISSUE THREAD

**Issue by mhkeller** [Leaflet/Leaflet#1862]
Per the [divIcon documentation](http://leafletjs.com/reference.html#divicon), you can add a `className` but it doesn't look like you could add an `id`. Is this possible or could it be logged as a small feature request?

The use case is you have a marker that is specific for one thing and should most logically have an `id`. You could obviously add a unique `className` but that's not the precise use of a class and id's are faster than classes to select with jQuery, so that would help there.

**Comment by Falke-Design** [comment]
Linking: #1010, #230

**Comment by jonkoops** [comment]
I'm closing this issue as it's already possible to extend the `DivIcon` class as per https://github.com/Leaflet/Leaflet/pull/1010#issuecomment-963393644. The `createIcon()` method returns a [`HTMLElement`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement) that can be modified directly.
