### ISSUE TITLE
Leaflet not responding to Chrome Emulated Touch Events

### ISSUE THREAD

**Issue by springlab** [Leaflet/Leaflet#1890]
Leaflet doesn't seem to be responding to the touchmove event. I'm testing in Chrome on Windows 8 with Emulate Touch Events turned on. It won't let me drag the map at all.

var map = new L.Map( 'map', {
    center: new L.LatLng(29.89, -81.31),
    zoom: 16,
    dragging: true,
    touchZoom: true,
    tap: false,
    inertia: true,
    inertiaDeceleration: 3000,
    inertiaMaxSpeed: 1500
});

It doesn't seem to work on the example or tutorial maps on the Leaflet site either. Any help would be greatly appreciated.

**Comment by zralokh3** [comment]
Hey I'm refreshing this topic as I wasn't able to find a fix to this issue. 
Has anyone else found a workaround or a serious solution to this behavior?

**Comment by mourner** [comment]
Closing in favor of #3466 (the same issue with more detailed description)
