### ISSUE TITLE
Moving circleMarkers does not move open popups

### ISSUE THREAD

**Issue by domoritz** [Leaflet/Leaflet#1921]
I'd expect the popup to move with a circleMarker. A marker can be moved by setting its location via `setLatLng`.

**Comment by guillaumeprevost** [comment]
Similar issue seems to be present when calling:

`map.fitBounds(bounds);`

Maybe I'm doing things wrong but here is the context: a circle marker is placed on the map with a popup binded to it. Inside the popup content, in addition to information about the marker, a "Zoom in" link triggers a javascript function that uses the location of the marker and call map.fitBounds();

The map center and zoom level is updated, the circle marker is moved accordingly, but the popup binded to the marker doesn't move.
