### ISSUE TITLE
Pinch Zoom freeze with zoomAnimation: false

### ISSUE THREAD

**Issue by nhinze** [Leaflet/Leaflet#1922]
HI,

the shramov/leaflet-plugins Google Layer used to work with LL 0.5.1. However, with LL 0.6.4, it freezes when using pinch zoom in the iOS Simulator 6.1. Zoom buttons and double click zoom work fine.

To reproduce the issue, simply download the repo at https://github.com/shramov/leaflet-plugins and apply the corresponding LL version to the examples/google.html and load in iOS Simulator

I know that this plugin is not supported by LL, but I was looking for help on how to debug this since it only happens with pinch zoom. I'm wondering what breaking changes could have been done to the zoom animation since LL 0.5.1. I think the plugin is trying to trigger a zoom before the end of the zoom animation. Any help would be appreciated.

Link to issue: https://github.com/shramov/leaflet-plugins/issues/62

Thanks,

Nick,

**Comment by sylvaindurand** [comment]
Same issue here : using `zoomAnimation:false` made Leaflet completely crash on iOS.

However, i found a simple hack in order to wait; it will use zoom animation only on iOS:

```javascript
var iOS = ( navigator.userAgent.match(/(iPad|iPhone|iPod)/g) ? true : false );
var map = L.map('map',{zoomAnimation:iOS})
```
