### ISSUE TITLE
Changing to an unsupported tile provider zoom level removes all tiles and reports a load of errors

### ISSUE THREAD

**Issue by thomaslindstrom** [Leaflet/Leaflet#1934]
![screen shot 2013-08-04 at 4 14 10 am](https://f.cloud.github.com/assets/2833514/906516/a318e02c-fcab-11e2-8aef-17dc891cb7c5.png)

Would be nice to have an option to cap tile layer url zoom without screwing up the coordinates and still see the CSS3 zooming while pinching and animating. Will also result in fewer requests if I can specify that no tiles have decimal zoom levels.

EDIT: This is a really bad description, refer to the one below: https://github.com/Leaflet/Leaflet/issues/1934#issuecomment-22192219

**Comment by owlcode** [comment]
It may be unbelievable, but after two years I'm still running into the same issue. I am writing hybrid mobile app using ionic2. I've installed leaflet package using npm, it seems to be the most recent version. `private L: any = require('leaflet');` I have no idea what I'm doing wrong but leaflet is putting non integer values into url causing 404. It happens on android 5.0.1.

**Comment by dtruel** [comment]
I'm having the same issue with Ionic 2 for ipad only.  Unfortunately I'm stuck with the .7 version because the Angular 2's zone.js messes with the pan function.  Any idea why this won't work in .7?

**Comment by verbeeckjan** [comment]
Same issue with ionic2 on an android device

**Comment by IvanSanchez** [comment]
@owlcode @dtruel @verbeeckjan Please don't resuscitate a three-year old closed bug about `maxNativeZoom` and zoom animations for an unrelated problem. If you have issues with Leaflet somehow using *non-integer zoom levels* under certain circumstances, create a new bug report detailing those circumstances and how to reproduce the problem.
