### ISSUE TITLE
Markers positioned too far North on Yandex maps only

### ISSUE THREAD

**Issue by RikdeBoer** [Leaflet/Leaflet#1964]
First: Leaflet JS rocks! Thanks so much for this great, great library.

I'm using it in Drupal. See http://flink.com.au/tips-tricks/27-reasons-not-to-use-google-maps

Does anyone know why markers seem to be spot-on on every map displayed through Leaflet, except for Yandex (see bottom map on above link). 
For instance enter: lat = 43.19282, lon = 131.813521 (Vladivostok bay area) and compare Yandex to the other maps on the same page.
Is there some sort of correction I need to apply?

**Comment by vistar** [comment]
See maps on link from first comment: https://www.drupal.org/node/2061411#comment-11128045 marker is Northern...
