### ISSUE TITLE
Dynamic zoom-levels / skipping them

### ISSUE THREAD

**Issue by fab1an** [Leaflet/Leaflet#2005]
Is there a way to seamlessly skip a zoomlevel, like make the "+" icon jump from 7 to 9 and after that normally to 10,11 and so on?

**Comment by spillevink** [comment]
@mourner: I want to do that! I'm drawing a hexmap with fixed width hexes. The dataset is large and has to be aggregated in the backend where we can only afford to save a few zoom levels. Would you please reconsider this ticket?

**Comment by IvanSanchez** [comment]
@spillevink There is no need to reopen this ticket. Create a custom CRS with different `scale` and `zoom` functions, so the scale is not 2^(zoom level).

**Comment by fab1an** [comment]
I opened this ticket, but now I don't think it's a good idea to do this, because it changes the way the user expects leaflet to behave.

There are a couple of ways around performance-issues. Maybe you don't need more than URL-rewriting on your backend.
