### ISSUE TITLE
Scale control is inaccurate

### ISSUE THREAD

**Issue by mataamad** [Leaflet/Leaflet#2006]
The scale control is inaccurate, for example the square areas south west of Palm Springs / Palm Desert should be exactly 1 mile by 1 mile:
http://www.openstreetmap.org/#map=12/33.8195/-116.3038

e.g. compare with Google Maps: https://www.google.com/maps/preview#!data=!1m4!1m3!1d70454!2d-116.610454!3d33.7160376

At zoom level 12 the squares show up as around 1.3 miles wide, ~0.9 miles wide at zoom level 11, and 0.8 miles wide at zoom level 10.

I'm pretty sure this isn't just an open street map issue because we get the same problem with our own custom tile server.
![invalid map scales](https://f.cloud.github.com/assets/2156335/1069314/4811060e-1412-11e3-9e29-85dcfa04b1da.png)

**Comment by MarZab** [comment]
Sorry to open up an old bug.

![untitled 4](https://cloud.githubusercontent.com/assets/1311249/8720109/fff12f44-2bb0-11e5-9a2d-3b7dd26a0b18.png)

Here ( [gist](https://gist.github.com/MarZab/7e3b1522ebc383f448a0), [preview](http://zabreznik.net/wp-content/uploads/2015/05/lf.html) ) is a example of this issue on leaflet-1.0.0-b1 using a linear CRC and no custom CSS with this fix:
```
.leaflet-control-scale-line {
  box-sizing: border-box;
}
```

**Comment by mourner** [comment]
Hmm, I wonder what's up with the wonky zoom animation in your example... 
Can you clarify what's exactly wrong, and what's the expected output?

**Comment by MarZab** [comment]
Yeah the wonky zoom is something I've been wondering about for ages as well :)

I would expect leaflet to have a somewhat accurate scale on a generic page by default. 
The example I gave has a linear projection so we can rule out projection distortion.
Image 1 is without the fix and image 2 is with the fix - try it with subtracting the coordinates at the beginning and end of the scale.
