### ISSUE TITLE
noClip: true isn't working for polylines in Chrome or FireFox

### ISSUE THREAD

**Issue by mataamad** [Leaflet/Leaflet#2028]
As far as I understand it, the noClip:true option for polylines should disable clipping polylines to the screen.  It doesn't seem to be working in firefox or chrome, but it's working in IE.

To reproduce, open up the JsFiddle, zoom in to the polyline, and pan around the map without releasing the left mouse button.

A workaround seems to be to set:
L.Path.CLIP_PADDING = {some large number};

I want to disable clipping because it's really annoying to be scrolling along a route and not be able to see the polyline until you stop scrolling.  I guess for my use case it'd be nice to be able to have an option to keep the polyline clipped but automatically redraw it on the map as the user pans (throttled to some reasonable update interval).  I haven't played with it, but I can probably figure something out with polyline.redraw() and an event listener on the pan event as a more performant workaround.

http://jsfiddle.net/gyNTJ/

![noclip](https://f.cloud.github.com/assets/2156335/1146956/125b8b74-1e8a-11e3-9476-c361e5fc31f6.png)

**Comment by srcspider** [comment]
@mourner it should probably be renamed to noCulling or noSimplification, or at least the docs should be more exact and not just say "Disabled polyline clipping."  The word "[clipping](https://en.wikipedia.org/wiki/Clipping_(computer_graphics))" in the context of computer graphics implies too deeply "only drawing in specific region". 

It's very likely for someone to enable it and not test if it actually did the work or assume something else went wrong and eventually forget to remove it. Accidentally turning it on does a lot more harm then good. When do you even want for leaflet to not simplify the polyline for display purposes? It might as well be "shootYourselfInTheFoot" :gun:
