### ISSUE TITLE
Drag scrolling on touch devices fails because leaflet.js stops propagation of touchmove events

### ISSUE THREAD

**Issue by votive** [Leaflet/Leaflet#2031]
I've configured leaflet to display a map with gesture support disabled (drag to move map, pinch to zoom etc.) as I'd like to display the map completely read-only. Even with touch options turned off, the leaflet map still stops propagation of the touch move event, which means the user can't drag the page up and down on a touch screen device, if they start the drag on the map. This is a problem on a mobile phone where the map portion of the page takes up most of the screen, prohibiting the user from scrolling down to the rest of the page.

**Comment by kuntalparbat** [comment]
I know "tap: false" this trick work for many people but not for me.
I am trying to enable move map in mobile devices.
it not let me drag map like desktop browser.

My code is below Please review and let me know how I can solve this. 

Or if possible I like to add a direction move button where user can click to move map up down + left right.

`var map = L.map('map', {
        layers: [osmMap],
        center: new L.LatLng(22.5726, 88.3639),
        zoom: 12,
        zoomControl: false,
    attributionControl: true,
 dragging: true,
    tap:true
    })
//add zoom control with your options
map.attributionControl.setPrefix(geo_link);

L.control.zoom({
     position:'bottomleft'
}).addTo(map);


var baseLayers = {
	"OSM Mapnik": osmMap,
	"Google": googleMap,
	"Landscape": landMap,
};

L.control.layers(baseLayers).addTo(map);`

**Comment by IvanSanchez** [comment]
@kuntalparbat This issue tracker is used for reporting bugs and discussing new features, not for gratis support reopening 3-year-old bugs. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
