### ISSUE TITLE
Leaflet is buggy when opened in a separate window

### ISSUE THREAD

**Issue by Zverik** [Leaflet/Leaflet#2054]
http://jsfiddle.net/rcrrV/2/

Dragging does not work: it seems that listeners are attached to the parent window. There might be other problems.

This is #620 but with an example. Can it be that I'm first to try opening a map in a new window?..

**Comment by mourner** [comment]
Closing because there's no clear solution inside Leaflet and there is a workaround. Will reopen if someone finds a way to fix it elegantly.

**Comment by imosapatryk** [comment]
Has something changed about it?

**Comment by ghybs** [comment]
Hi @imosapatryk,

Nope unfortunately.
Here is the same JSFiddle with current version of Leaflet (1.3.1): https://jsfiddle.net/rcrrV/17/

The mentioned workaround should still work however.

It might be possible to improve the situation, but I suspect that would require tracking down every use of `document` in Leaflet, and finding a way to pass it by reference to all classes.
Probably a big refactoring, for an edge use case.

**Comment by jonasViehweger** [comment]
I think this isn't an issue anymore in v.2.0.0?

Tried here: https://jsfiddle.net/yaxjeLbk/

But I am in general kind of confused on the status of v.2.0.0. Unsure of this is actually the version which will land or not.
