### ISSUE TITLE
Tile layer may hang if maxZoom or minZoom are set to undefined

### ISSUE THREAD

**Issue by Zverik** [Leaflet/Leaflet#2067]
http://jsfiddle.net/LcjJC/1/

When there are no layers, `map.getBoundsZoom()` for zero-sized bounds returns 1015. After adding a tile layer, the map panel remains empty. In the jsfiddle it can be solved by zooming out, but in some cases zooming does not help, and sometimes leaflet even hangs and later crashes with an out of memory error (after calling `map.fitBounds()`).

**Comment by IvanSanchez** [comment]
Behaviour has been revamped, so closing this one.
