### ISSUE TITLE
Partial scroll wheel zoom disabling

### ISSUE THREAD

**Issue by Zverik** [Leaflet/Leaflet#2076]
It was suggested that zooming by mouse wheel could work when `scrollWheelZoom` is set to false, but a modifier key (e.g. shift) is pressed. This way page scrolling with mouse wheel is not affected, but users still have a way to quickly zoom out.

**Comment by ValentinH** [comment]
Any update about this feature? It would be really cool to only start the zoom when the scroll starts on the map...

**Comment by Uyara** [comment]
Any update? I really would like to use this.

**Comment by Nycroth** [comment]
Not a patch, sorry. However, here's a no underscore version of a debounce for a leaflet map assuming `map = L.map`. I'm sure this can be added nearly verbatim to leaflet.js with an option to toggle it.

```javascript
// Only enable scrolling if the user hasn't scrolled the page in 1 second
document.addEventListener("scroll", function() {
        map.scrollWheelZoom.disable()
        var timeOut = null;
        if(timeOut != null){
                clearTimeout(timeOut);
        }
        timeOut = setTimeout("map.scrollWheelZoom.enable()", 1000);
});
}```

**Comment by DanielHeath** [comment]
@Nycroth That's only on the map container - if the debounce applied to the whole document instead (and only zoomed if the event target was in the map container) it would solve the issue.

**Comment by vincent3569** [comment]
hi
is there some news on that issue?
the googlemap behavior on this issue is OK for me: if mousse wheel zoom is disabled, so ctrl + mousse wheel in enabled and users can zoom in or zoom out when mouse is over a map.

**Comment by mguinness** [comment]
Reading through the various issues what is the consensus on the modifier key, is shift preferred over ctrl?

Keeping similarity with Google Maps might not be a bad idea, i.e. use `scrollWheelZoom.disable()` which can be overridden with ctrl+scroll.

**Comment by Erwane** [comment]
Hi,
google maps display a backdrop with a text "Control + mousewheel to zoom".
Maybe it's possible to do the same with leaflet ?
Thanks.

**Comment by IvanSanchez** [comment]
Already implemented by the https://github.com/elmarquis/Leaflet.GestureHandling/ plugin. No plans so far to implement this in the core.
