### ISSUE TITLE
Layer order in `L.Control.Layers` is not preserved with GeoJson/FeatureGroup

### ISSUE THREAD

**Issue by jieter** [Leaflet/Leaflet#2086]
When I do

```JavaScript
L.control.layers({
    'OSM': L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(map)
}, {
    'Circle': L.circle([53, 4], 111111),
    'Polygon': L.polygon([[48, -3], [50, -4], [52, 4]]),
    'GeoJSON': L.geoJson(geojson)
}, {
    collapsed: false
}).addTo(map);
```

I expect the order of the overlays to be as I supplied them, however, GeoJSON and FeatureGroup layers are moved up top. This is because the FeatureGroup gets its `_leaflet_id` while it's created, while the other layers get it while they're added to Control.Layers.
FeatureGroup is stamped because it's passed as the context to `layer.on` in FeatureGroup.js:19.

Not sure how to fix this:
 - stamping each layer while initializing? Seems dirty. 
 - Different sorting mechanism in Control.Layers?

http://jsfiddle.net/km5H9/1/

**Comment by Rikaelus** [comment]
I think this is still valid?
I have a geoJSON layer among several tileLayers. Initial placement works fine but on certain page events that may change layer availability I trigger a "refresh" by removing and re-adding all layers in the same order as before, but my geoJSON layer now appears at the top of the control.

I was able to work around this by removing the old geoJSON layer and replacing it with a new one (ostensibly with a new internal ID in a proper order) and it appears in the correct place.

**Comment by minskmaz** [comment]
Hi folks. I'm also experiencing this with geojson featuregroups. Lots of overlapping polygons and the zindex changes confuse the user. Can anyone suggest a canonical/somewhat-future-proof method for maintaining group display order ?

**Comment by tomchadwin** [comment]
Afraid not. I build an array of layers in their correct order, and cycle through the whole array each time layers are added, bringing every layer in turn to the front. Horrible, but it works. I have no alternative at this stage.

**Comment by Rikaelus** [comment]
I'm basically doing what tomchadwin has except more explicit, since I've just kind of grown into the code. If I get around to refactoring it I'll either use a similar array or probably make my own little Javascript snippet to manage my own control interface and stick it within the map.

**Comment by patrickarlt** [comment]
If anyone here is using Leaflet 1.0.0 you should be able to use the new `pane` option to control this:

```
map.createPane('bottom');
map.createPane('middle');
map.createPane('top');

// now pane order controls layer ordering not the control!
L.control.layers({
    'OSM': L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(map)
}, {
    'bottom': L.geoJson(geojson, {pane: 'bottom'}),
    'middle': L.geoJson(geojson, {pane: 'middle'}),
    'top':  L.geoJson(geojson, {pane: 'top'}),,
}, {
    collapsed: false
}).addTo(map);
```

You can see this inaction with lots of overlapping polygons [here](http://esri.github.io/esri-leaflet/examples/layer-ordering.html).

**Comment by minskmaz** [comment]
patrickarlt thanks - this is helpful.

**Comment by minskmaz** [comment]
patrickarlt thought I'd let you know I implemented the pattern you outlined above. This does lay out the order of the panes properly such that panes and their associated layer group are added to the map such that the pane appears beneath successively added panes. However, when using l.control.layers.addOverlay to then associate L.control.layers with panes on the map --> zero order to the layer names as they appear in the control seems possible. Half way there! Any suggestions ?

**Comment by patrickarlt** [comment]
I look a look at the code. It looks like layers are stored internally in the control by the layers internal Leaflet ID https://github.com/Leaflet/Leaflet/blob/master/src/control/Control.Layers.js#L115-L121. The internal ID generator gets called A LOT. For example in my JS Bin http://jsbin.com/vocigipive/1/edit?html,css,js,output it is already at 177 by the time everything gets done.

Since all browsers sort objects when looping like `for (i in this._layers)` by the order in which they are defined http://stackoverflow.com/questions/280713/elements-order-in-a-for-in-loop this means that you cannot really rely on any specific ordering when using `L.Control.layers`.

@mourner I'm wondering if this could be refactored to use an array of layers internally rather then an object.

```js
// convert basemaps and overlays to ordered arrays internally
L.control.layers({
    'OSM': L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(map)
}, {
    'bottom': L.geoJson(geojson, {pane: 'bottom'}),
    'middle': L.geoJson(geojson, {pane: 'middle'}),
    'top':  L.geoJson(geojson, {pane: 'top'}),,
}).addTo(map);

 // add a new position property to control where the added layer falls in the order. Default would be at the bottom.
control.addOverlay(layer, name, position);
```

**Comment by mourner** [comment]
@patrickarlt I think that's a great approach. I would be up for a PR on this.

**Comment by yohanboniface** [comment]
@patrickarlt up for working on this before 1.0 or should I postpone? :)

**Comment by jieter** [comment]
Huh, I already made a PR for this...
