### ISSUE TITLE
Possible to change header info for tile request?

### ISSUE THREAD

**Issue by newmanw** [Leaflet/Leaflet#2091]
I need to access tile servers which require a token to be passed.  Is there any way to intercept the tile request so that I can add something to the header before the request is made.  I.E. it would be nice if I could listen for a pre-tile request, via an event, mess with the headers and send the request on its way.

**Comment by zhenyanghua** [comment]
adding as query params is fine, but it exposes the token in the request url. when implementing a OAuth 2.0, the suggestion is to write the token into the header. This issue should be a new pull request.

**Comment by rrameshkumar76** [comment]
yes this feature would be greatly useful for OAuth 2.0 to add the authorization header.

**Comment by perliedman** [comment]
@zhenyanghua @rrameshkumar76 as mentioned above, `TileLayer` is just an `img` tag, and to out knowledge there is no way to set custom headers for an image tag.

Having said that, you can load tiles any way you want (like using AJAX) if you extend `GridLayer`. There's some pretty good examples on how to do things like that in the [Extending Leaflet, New Layers](http://leafletjs.com/examples/extending/extending-2-layers.html) tutorial.

**Comment by rrameshkumar76** [comment]
Thanks @perliedman for the answer and the tip. I will extend GridLayer for my purpose.

**Comment by SunnyMittal** [comment]
Hi Ramesh Kumar, is it possible for you to share the extended WMS class for reference ?
Thanks heaps

**Comment by rrameshkumar76** [comment]
I used superagent for ajax, replace it as needed. 

L.TileLayer.WMS_Headers = L.TileLayer.WMS.extend({
  createTile(coords, done) {
    const url = this.getTileUrl(coords);
    const img = document.createElement('img');
    superagent
      .get(url)
      .set(‘header’, ‘header value’)
      .responseType('blob')
      .then((response) => {
        img.src = URL.createObjectURL(response.body);
        done(null, img);
      });
    return img;
  }
});

L.tileLayer.wms_headers = (url, options) => new L.TileLayer.WMS_Headers(url, options);

**Comment by SunnyMittal** [comment]
@rrameshkumar76 thanks it helped :)

**Comment by ticinum-aerospace** [comment]
based on @rrameshkumar76 anwser, I built a super easy [plugin](https://github.com/ticinum-aerospace/leaflet-wms-header ).
Hope you will enjoy it.

**Comment by AB-Kent** [comment]
If any one wants to add headers to `L.TileLayer` instead of `L.TileLayer.WMS`, this is possible by a simple modification of @ticinum-aerospace 's [plugin](https://github.com/ticinum-aerospace/leaflet-wms-header). Just change the base class from `L.TileLayer.WMS` to `L.TileLayer` and rename the new class and function appropriately.

**Comment by jaq316** [comment]
I've modified @ticinum-aerospace 's plugin for `L.TileLayer` instead of `L.TileLayer.WMS` her: https://github.com/jaq316/leaflet-header/blob/master/index.js

**Comment by bkanuka** [comment]
Are there any thoughts or plans on integrating this into the core library? I can't imagine it would be a breaking change because by default you just wouldn't send extra headers.

**Comment by johnd0e** [comment]
> Are there any thoughts or plans on integrating this into the core library?

No plans.
But anyone can propose this in PR.

**Comment by JoseMeneghetti** [comment]
I'm using old versions of react-leaflet in my project, so I could reach this lib old lib : **react-leaflet-extendable** and I did it by extending my TileLayer component.

`import { ExtendableTileLayer } from "react-leaflet-extendable";
import { withLeaflet } from "react-leaflet";
import { TileLayer as LeafletTileLayer } from 'leaflet'

async function fetchImage(url, callback, headers, abort) {
  const controller = new AbortController();
  const signal = controller.signal;
  if (abort) {
    abort.subscribe(() => {
      controller.abort();
    });
  }
  const f = await fetch(url, {
    method: "GET",
    headers: headers,
    mode: "cors",
    signal: signal
  });
  const blob = await f.blob();
  callback(blob);
}

const LWMSTileLayerWithHeader = LeafletTileLayer.WMS.extend({
  initialize: function (url, options) {
    const { headers, abort, results, ...props } = options;
    LeafletTileLayer.WMS.prototype.initialize.call(this, url, props);
    this.headers = headers;
    this.abort = abort;
    this.results = results;
  },
  createTile(coords, done) {
    debugger
    const url = this.getTileUrl(coords);
    const img = document.createElement("img");
    img.setAttribute("role", "presentation");

    fetchImage(
      url,
      resp => {
        const reader = new FileReader();
        reader.onload = () => {
          img.src = reader.result;
          if (this.results) {
            this.results.next(reader.result);
          };
        };
        reader.readAsDataURL(resp);
        done(null, img);
      },
      this.headers,
      this.abort
    );
    return img;
  }
});

class NewTileComponent extends ExtendableTileLayer {
  componentDidMount(...attributes) {
    super.componentDidMount(...attributes);
  }

  createLeafletElement(props) {
    const options = this.getOptions(props);

    // Adicione os headers desejados aqui
    const headers = {
      "Custom-Header": "Custom-Value",
      // Adicione mais headers conforme necessário
    };

    // Combine os headers com os options existentes
    const mergedOptions = {
      ...options,
      headers: {
        ...options.headers,
        ...headers
      }
    };
    return new LWMSTileLayerWithHeader(props.url, mergedOptions);
  }

  createTile(coords, done) {
    const url = this.getTileUrl(coords);
    const img = document.createElement("img");
    img.setAttribute("role", "presentation");

    fetchImage(
      url,
      resp => {
        const reader = new FileReader();
        reader.onload = () => {
          img.src = reader.result;
          if (this.results) {
            this.results.next(reader.result);
          };
        };
        reader.readAsDataURL(resp);
        done(null, img);
      },
      this.headers,
      this.abort
    );
    return img;
  }

  updateLeafletElement(fromProps, toProps) {
    super.updateLeafletElement(fromProps, toProps);
    if (toProps.url !== fromProps.url) {
      this.leafletElement.setUrl(toProps.url);
    }
  }
}

export default withLeaflet(NewTileComponent);
`

**Comment by smartm0use** [comment]
> based on @rrameshkumar76 anwser, I built a super simple [plugin](https://github.com/ticinum-aerospace/leaflet-wms-header). Hope you will enjoy it.

I have forked it here: https://github.com/smartm0use/leaflet-wms-header-opt

```
updated source code according to latest dist original version;
made abort and results parameters as optional;
updated rxjs and typescript versions
```

**Comment by mariochermes** [comment]
I don't know quite the why - as it isn't referenced in the docs - but just adding the authkey to the options parameter works for me:

```
layer: L.tileLayer.wms(url, {
                attribution: '',
                layers: WORKSPACE:LAYER_NAME,
                format: 'image/png',
                transparent: true,
                authkey: authkey
              } as any).on('tileload', this.loadingEventHandler)
```

**Comment by IvanSanchez** [comment]
> I don't know quite the why - as it isn't referenced in the docs

@mariochermes See https://leafletjs.com/reference.html#tilelayer-wms, specifically the bit that says «If any custom options not documented here are used, they will be sent to the WMS server as extra parameters in each request URL.»

**Comment by mariochermes** [comment]
> > I don't know quite the why - as it isn't referenced in the docs
> 
> @mariochermes See https://leafletjs.com/reference.html#tilelayer-wms, specifically the bit that says «If any custom options not documented here are used, they will be sent to the WMS server as extra parameters in each request URL.»

Thanks for the info, I didn't see that.

**Comment by hexxone** [comment]
Fyi if someones comes across the same problem and wants to use it in react, I posted my code here: https://github.com/PaulLeCam/react-leaflet/issues/852#issuecomment-4143956289
