### ISSUE TITLE
Zoom issues with Apple trackpad (Magic Mouse)

### ISSUE THREAD

**Issue by ekelleyv** [Leaflet/Leaflet#2154]
Zooming with the scroll gesture causes very jumpy behavior between zoom levels. The calls to `_performZoom` seem to add up, meaning the map keeps zooming after the user has stopped scrolling.

Basically the Apple trackpad creates A LOT of calls to `_onWheelScroll` and because of inertial scrolling, continues to call it after the user has actually stopped scrolling. For my uses, changing the value 

`var left = Math.max(40 - (+new Date() - this._startTime), 0);`

to something more like:

`var left = Math.max(200 - (+new Date() - this._startTime), 0);`

works decently. It makes the apple mouse a little too sensitive (harder to move between small numbers of zoom levels), but seems to get rid of the jumping effect. Any ideas of a better solution?

**Comment by DennisSchiefer** [comment]
Any news on this front? schovi mentioned that this solution works perfectly, but even with the current master, I still see issues when using a Magic Mouse. They can be classified roughly into two categories:
- Sometimes when zooming, there is a zoom by one level in the wrong direction at the end or at the beginning. I assume this could be when not swiping completely vertical on the mouse, as swiping horizontally also initiates zooming
- Zooming is not as intuitive as with a scroll wheel. One is likely to overshoot the intended zoom level (sometimes a small touch on the mouse zooms by 2-3 levels - this is also when just trying to perform a click with the mouse). Maybe adding a threshold for _delta could help, i.e. only trigger a zoom after enough delta value has accumulated?

**Comment by ccolgrove** [comment]
I'm also interested in the status of this issue. We recently upgraded from 0.7.2 to 0.7.3 and started seeing  bizarre scrolling behavior when using an Apple trackpad. It made scrolling so unusable we had to downgrade.

**Comment by mourner** [comment]
I had some work in progress on this that should in theory improve things in https://github.com/Leaflet/Leaflet/pull/3653. Can you try out that branch? I would appreciate feedback.

**Comment by ccolgrove** [comment]
Thanks for the quick response! I played around with that branch and it does look like the over-zooming problem is fixed. However, I noticed when I zoom in, the image does not stay centered on the mouse, but instead zooms off to one side and then snaps back into place. Happy to provide more details if you need them.

**Comment by DennisSchiefer** [comment]
Thank you for still working on the problem. I know that this is a tough one to solve - I also gave it a quick try but quickly realized that finding a satisfying solution won't be easy.
That said, your new branch unfortunately does not noticably change the behaviour I see in Safari with the MagicMouse as described above.

**Comment by yohanboniface** [comment]
Should be fixed with #3653 please open a new issue if needed.
