### ISSUE TITLE
Leaflet JS - Country Boundaries

### ISSUE THREAD

**Issue by hemanta25** [Leaflet/Leaflet#2195]
The only query / issue I have is the big lines it draws blue (or themed borders) around countries.

There is a method to remove them?

**Comment by abrice** [comment]
It's a shame you couldn't provide an answer. Pointing to a documentation page that has no response to the original question isn't useful at all. 

Equally, it's pretty useless having something that draws a map with a big blue border around every country and no explanation as to how to remove it.

**Comment by IvanSanchez** [comment]
@abrice This kind of passive-aggressiveness is disrespectful towards maintainers.

I suggest reading ["How To Ask Questions The Smart Way"](http://www.catb.org/esr/faqs/smart-questions.html) and ["How to Report Bugs Effectively"](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) so you can make good bug reports in the future.
