### ISSUE TITLE
L.geoJson layer's bringToFront() function is not working

### ISSUE THREAD

**Issue by alperdincer** [Leaflet/Leaflet#2200]
I'm working on a multi layered map app. There are tile and GeoJSON layers. GeoJSON is used for getting info. When GeoJSON layer is created and added to map before a tile layer and tile layer is added after this, mouse click event is not working due to layer queue. 

I tried to run bringToFront() function after getting GeoJSON, but it doesn't work.

Is it a bug or wrong usage of the API?

**Comment by allthesignals** [comment]
I had a lot of trouble getting JSFiddle to work, but I tried to replicate the issue with bringToFront():
http://jsfiddle.net/HQhzr/104/

If L.GeoJSON extends L.FeatureGroup, then the bringToFront() method should be available according to the docs but I'm probably misunderstanding. Seems similar to #2439. (bringToBack() throws the same error).

Without the method call, the GeoJSON draws correctly. 

(Unrelated: L.CircleMarker does not seem to allow you to change the border like a regular L.Path).
