### ISSUE TITLE
Open Multiple Markers (popups) 

### ISSUE THREAD

**Issue by ofirattia** [Leaflet/Leaflet#2201]
Hi,
I would like to know if there is option to prevent close of popup while clicking another marker, I want to be able to open all of them.
thanks.

**Comment by catbadger** [comment]
I know this is old, but this is still a problem in RC3.

**Comment by perliedman** [comment]
@catbadger have you read [the docs for popup](http://leafletjs.com/reference-1.0.0.html#popup) which explain how this can be done?

If you still think this is an issue with Leaflet, you should post some code illustrating the problem.

**Comment by catbadger** [comment]
The docs are out of date. I actually needed to do some overrides to make this happen.

`L.Popup = L.Popup.extend({
    getEvents: function () {
        var events = L.DivOverlay.prototype.getEvents.call(this);

        if ('closeOnClick' in this.options ? this.options.closeOnClick : this._map.options.closePopupOnClick) {
            //events.preclick = this._close;
        }

        if (this.options.keepInView) {
            events.moveend = this._adjustPan;
        }

        return events;
    },
});`

**Comment by perliedman** [comment]
@catbadger that looks a bit complicated.

Setting `closePopupOnClick: false` in your map options and using `map.addLayer` as stated in the docs should be enough. See this example: http://playground-leaflet.rhcloud.com/veza/edit?html,output

We should update the docs to include info on `closePopupOnClick` to make this clearer.

**Comment by raywu** [comment]
Passing `autoClose: false` as an option does the trick: http://leafletjs.com/reference-1.0.0.html#popup-autoclose
