### ISSUE TITLE
fill-pattern

### ISSUE THREAD

**Issue by fab1an** [Leaflet/Leaflet#2214]
I would like to be able to fill GeoJson-Elements with a pattern like seen here: http://www.carto.net/svg/samples/patterns.shtml

**Comment by pyrog** [comment]
@fab1an :+1: 

There are some issues in [HOT OSM Task Manager](http://tasks.hotosm.org/about) (Humanitarian OpenStreetMap Team)
* hotosm/osm-tasking-manager2#432
* hotosm/osm-tasking-manager2#500 and [specific comment](https://github.com/hotosm/osm-tasking-manager2/issues/500#issuecomment-67761569) about **[color blindness](http://vischeck.com/daltonize/)**

Even with this trick, the tiles over the map could be more readable with fill pattern :wink: 

See http://www.etre.com/tools/colourblindsimulator/

Without color blindness
![without color blindness](https://cloud.githubusercontent.com/assets/2158081/5591899/5e7c2f3a-9199-11e4-88be-899b98410e46.jpeg)

Protanopia
![protanopia](https://cloud.githubusercontent.com/assets/2158081/5591900/65b9b38a-9199-11e4-9208-3c07c9b3daea.jpeg)

Deuteranopia
![deuteranopia](https://cloud.githubusercontent.com/assets/2158081/5591901/6b870b5a-9199-11e4-9d54-70bb4d0fd2b8.jpeg)

Tritanopia
![tritanopia](https://cloud.githubusercontent.com/assets/2158081/5591902/71800caa-9199-11e4-8027-ca95cf472e0c.jpeg)

**Comment by teastman** [comment]
I found we needed this feature for our product as well.  I took a stab at implementing it and have made a pull request.  If anyone can take a look and let me know what you think.  I put some example code uses here http://jsfiddle.net/ehucL6v5/ but I have no idea how to link my fork of leaflet.js in jsfiddle to show the example working.

**Comment by pyrog** [comment]
In external resource tab, remove leaflet.js and add a link to your fork ?
![external ressource](https://cloud.githubusercontent.com/assets/2158081/5964690/682acbd6-a7f6-11e4-8da8-59899324b130.png)

**Comment by teastman** [comment]
Ok, I've uploaded the initial code for a plugin to handle this.  I'm still adding more shapes and default patterns.  But pretty well any pattern can be created using the PatternPath shape.  [Leaflet.pattern](https://github.com/teastman/Leaflet.pattern)

**Comment by mourner** [comment]
@teastman awesome! Don't forget to include a demo in the repo, and submit a PR to gh-pages branch to add it to the plugins list.

**Comment by IvanSanchez** [comment]
Leaflet.pattern is in the plugins page already.

**Comment by joshdickerson92** [comment]
This thread specifies the requirements of applying a style to a GeoJSON and has been closed because of the creation of the Leaflet.Pattern plugin. However, <a href="https://github.com/teastman/Leaflet.pattern/issues/3">an issue raised</a> on the <a href="https://github.com/teastman/Leaflet.pattern">Leaflet.Pattern</a> plugin repository suggests that this isn't possible. Is this just an undocumented feature that is actually possible or does the plugin not work with a GeoJSON?

**Comment by d3netxer** [comment]
yes it is possible, teastman added a geojson pattern example on this issue you linked to: https://github.com/teastman/Leaflet.pattern/issues/3
