### ISSUE TITLE
Tiles get corrupted / mis-organized in Chrome

### ISSUE THREAD

**Issue by onyxfish** [Leaflet/Leaflet#226]
We're frequently seeing an issue where tiles in Chrome get mixed up and put in the wrong positions while dragging and zooming. Sometimes the tiles rearrange themselves back into the correct order after a moment, but more frequently they stay out of order and you have you have to re-pan/re-zoom to get a correct sequence back.

**Comment by matsaman** [comment]
I happened upon this issue just now with an old implementation. After swapping out leaflet-0.7.5.js & .css for 1.5.1 versions both, the issue was resolved.
