### ISSUE TITLE
L.imageOverlay does shifts or disappears when zoomed in

### ISSUE THREAD

**Issue by wenzeslaus** [Leaflet/Leaflet#2282]
Hi, I'm using L.imageOverlay for bigger images such as 6000x6000px and it works pretty well. But I noticed that when I zoom in the layer shifts at one zoom level and when I zoom more the layer completely disappears.

This is the code to reproduce (derived from tutorial and manual, JSFiddle: http://jsfiddle.net/vq7aS/ ):

```
var map = L.map('map').setView([40.712216, -74.22655], 13);

L.tileLayer('http://{s}.tile.cloudmade.com/BC9A493B41014CAABB98F0471D759707/997/256/{z}/{x}/{y}.png', {
			maxZoom: 18,
			attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery Â© <a href="http://cloudmade.com">CloudMade</a>'
		}).addTo(map);

var imageUrl = 'http://www.lib.utexas.edu/maps/historical/newark_nj_1922.jpg',
imageBounds = [[40.712216, -74.22655], [40.773941, -74.12544]];

L.imageOverlay(imageUrl, imageBounds, {opacity: 0.7}).addTo(map);
```

I'm getting the error for different image sizes, so maybe it is related to image geographic bounds. For the example above, I get only the shift (image is off its right position) with maximum zoom in. If I change the bounds to:

```
imageBounds = [
        [40.712216, -74.22655],
        [41.773941, -76.12544]
    ];
```

the image layer disappears when I zoom in a lot.

Testing with some other image than the example one, clearly shows that the non-shifted image nicely matches the base layers (as expected) and that shifted one is at wrong position.

This image overlay really simplifies the process of publishing the data and is able to handle relatively large images, so it makes sense to zoom in and see the details.

Tested browsers: Chromium 31, Firefox 26, Epiphany Web Browser 3.4.1 (WebKit 1.8.3)
Tested Leaflet versions: 0.7, 0.7.1

**Comment by meredithmmyers** [comment]
Also wondering the status of this. Still an issue and @wenzeslaus' fix still resolves it for Leaflet 0.7.3 and Chrome 39.

**Comment by mauricedb** [comment]
The CSS tweak mentioned by @wenzeslaus fixed the zooming issue for us as well. Please include.

**Comment by petervojtek** [comment]
Hi all,
I use imageOverlay with 640x480px image stretched over large area (Slovak republic) and 15000px is not enough in such case (it was fine till zoomLevel:12). I has to increase it to 480000px to avoid this bug on zoom level 16. The webapp is [here](http://radar.cyklonaut.sk/).

**Comment by IvanSanchez** [comment]
@petervojtek This issue won't be fixed for 0.7.x. Use 1.0-beta1.

**Comment by petervojtek** [comment]
ok, noted. thanks for quick reply.

**Comment by MojoKingBee** [comment]
It' doesn't seem to be included in beta1 as it still has
.leaflet-container img.leaflet-image-layer {
	max-width: 15000px !important;
	}
that prevents the solution (so I overrided that in my css, as proposed above).

Also, at very high width the browser doesn't seem to manage well the overlay.
In my case at a width: 437267px (on firefox) the overlay is shifted somewhere.

**Comment by IvanSanchez** [comment]
@MojoKingBee Use beta2 then. It's fixed in the `master` branch, so there's nothing else to do in regards to this issue.
