### ISSUE TITLE
getPopup for layers other than markers

### ISSUE THREAD

**Issue by tmcw** [Leaflet/Leaflet#2292]
Not sure why this is a discrepancy, but it is - it would be nice to have getPopup on other types of layers that support `bindPopup`.

**Comment by anderius** [comment]
Any chance this will be backported to 0.7.x? I am missing getPopup on Path.

**Comment by mourner** [comment]
@anderius can you just use something like `path._popup`?

**Comment by anderius** [comment]
That would work, thank you!
