### ISSUE TITLE
continuous zoom / non integer zoom levels

### ISSUE THREAD

**Issue by gouilaz** [Leaflet/Leaflet#2295]
I tried out the mentioned approach stated here: https://github.com/Leaflet/Leaflet/pull/1941 
Currently, I have the same effect as user dlev reports below in the commentary of the link:  "mousewheel-zoom and I'm not on integer tile levels, the tile requests fail and the map goes grey"

The roapmap has no current implementation of this feature ... why that? I would say a continous zoom becomes more and more essential as user tend to surf more with their mobile devices and tablets. Without this fluid zoom it feels just strange on those devices.

**Comment by jedateach** [comment]
is there a demo of this somewhere?
