### ISSUE TITLE
dom container has no id -> TypeError: el.className is undefined

### ISSUE THREAD

**Issue by voxspox** [Leaflet/Leaflet#2302]
Hi,

if I call "new L.map()" on a div container which has no id set, then I get the following error message (Firefox 25, Windows):
TypeError: el.className is undefined

I tracked the error down and this happens in
_initLayout -> addClass -> classList.add

Something goes wrong in addClass(). This function starts with:
if (el.classList !== undefined) {
  ...
  el.classList.add(...)

With FireBug I can point onto classList and it is undefined. Nevertheless processing continues in the if-statement. Thus the check if el.classList is undefined somehow fails!

If I define an id for the div-container everthing is ok.

I hope this helps to find the error.
Knut

**Comment by ravimkh1991** [comment]
when i m using data-emojiable  after that onpresskey submit not working
