### ISSUE TITLE
Blink after panning on mobile device

### ISSUE THREAD

**Issue by danydev** [Leaflet/Leaflet#2313]
Leaflet 0.7, with L_PREFER_CANVAS
Device: iPhone 5 \ iPod 4g

When panning, just after releasing the touch, I see the canvas elements blinking\flickering (just like a flash) before it gets rendered.

Is it a known behaviour? Please let me know if you need a jsfiddle to demonstrate it (though it's pretty easy, just draw something using canvas and load it on mobile).

**Comment by mourner** [comment]
Should be fixed on master. Will reopen if you see this.
