### ISSUE TITLE
`setMaxBounds` does not work with `CRS.Simple`

### ISSUE THREAD

**Issue by Fil** [Leaflet/Leaflet#2348]
If I'm not mistaken `setMaxBounds` does not work with CRS.Simple; the map is "trapped" vertically at its center. The problem lies with the tests in `panInsideBounds` that check if the point is "outside" the bounds. Those checks assume that north is "higher" than south, and east "higher" than west. However when the scales are inverted by the `transformation`/`projection` (e.g., the vertical scale is "top-down" in `Simple`), the tests fail.

a potential solution:
```
		if (viewNe.y < ne.y) { // north
			dy = ne.y - viewNe.y;
		}
```

could be corrected as:
```
		if ((viewNe.y - ne.y) * (ne.y-sw.y<0 ? -1:1) < 0) { // north
			dy = ne.y - viewNe.y;
		}
```

and so on for the four tests.

Thank you.

PS: I just realized that this has been totally refactored under 0.7.1 with the `_limitCenter` function; the bug still appears to be here though.

**Comment by IvanSanchez** [comment]
Can not reproduce with current master.

**Comment by mourner** [comment]
I think it may have been fixed recently by a Bounds + flipped y axis fix.
