### ISSUE TITLE
Confusing documentation on the popupopen event

### ISSUE THREAD

**Issue by sellonen** [Leaflet/Leaflet#2354]
Given marker m, I did something along the lines

```
p = L.popup().setLatLng('..').setContent('...');
m.bindPopup(p);
m.on('popupopen', function(e){ ...});
```

Then I clicked on the marker, saw the popup open, but my popupopen handler function was never executed. I realize now that I have to explicitly set the source for the popup when I create it, but it took me quite some time as i assumed bindPopup() to take care of it.

Is this intended behaviour or a bug?

**Comment by uniphil** [comment]
I am running into this problem in v0.7.3 -- is this fix only going to land in 1.0? (or maybe it regressed?) This issue closed just before 0.7.2.

My work-around is to pass `m` in as the `source` parameter for `p`.

```javascript
p = L.popup({}, m);
m.bindPopup(p);
```
