### ISSUE TITLE
Rename documentation references with L. prefix

### ISSUE THREAD

**Issue by tmcw** [Leaflet/Leaflet#2366]
If references in Leaflet's docs were more explicit, like L.Bounds rather than just Bounds, then it would be possible to auto-link the source instead of relying on the somewhat fuzzy translation of class name to location hash.

**Comment by IvanSanchez** [comment]
Leafdoc's "AKA" directives make this automatic. Is this still relevant for the 1.0.0 docs?

**Comment by tmcw** [comment]
Closing; 1.x is the priority.
