### ISSUE TITLE
Leaflet on devdocs.io

### ISSUE THREAD

**Issue by tmcw** [Leaflet/Leaflet#2375]
Docs! Might be neat to feature Leaflet on http://devdocs.io/ - I can write the scraper as soon as I sort out my ruby version problems.

**Comment by tmcw** [comment]
PRs accepted, not going to get the bandwidth to do this myself.

**Comment by simon04** [comment]
Fixed via https://github.com/freeCodeCamp/devdocs/commit/c8291a742813be8798639cdebe8abe4584105951 in 2018.
