### ISSUE TITLE
Support for kinetic dragging

### ISSUE THREAD

**Issue by ghost** [Leaflet/Leaflet#239]
Hi,  
most of the map libs out there now allows for kinetic dragging ie. http://openlayers.org/dev/examples/kinetic.html. Leaflet would gain a lot from it especially for the mobile experience. Have you guys considered it?

Thanks
R.

**Comment by daydarkln** [comment]
> Yep, planned for this release: https://github.com/CloudMade/Leaflet/issues/17
> Closing the issue as duplicate.

The link is broken
