### ISSUE TITLE
Allow for bounds to be specified for WMS layers so requests aren't made outside the bbox

### ISSUE THREAD

**Issue by ericdahl** [Leaflet/Leaflet#2390]
WMS layers have a BoundingBox defined which defines the location of the data. It is more efficient to not request data that is outside of the bounding box, because it just results in needless HTTP requests that result in empty/transparent tiles.

There should be a way to configure the bounding box for the layer for `TileLayer.WMS`, ideally accounting for the CRS.

**Comment by kaynz** [comment]
`maxBounds` should solve this.

**Comment by kaynz** [comment]
Looks like it doesn't. `maxBounds` is set,

```
          maxBoundsViscosity: 1,
          bounceAtZoomLimits: false,
          worldCopyJump: true,
```

When I drag past my maxBounds limit, leaflet tries to load tiles which are outside of the bounds.

**Comment by IvanSanchez** [comment]
@kaynz @ericdahl Can you check if this is solved in `master` by #4646? If not, please provide 
 a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour.

**Comment by kaynz** [comment]
For me it is not solved. I will try to provide a fiddle laters.

**Comment by ericdahl** [comment]
This works fine for me with [GridLayer's bounds attribute](http://leafletjs.com/reference-1.0.0.html#tilelayer-wms-bounds), testing using 1.0.1.

Thanks

**Comment by perliedman** [comment]
@ericdahl great to hear! Only took us a year to notice, but I'm closing this now. Thanks!
