### ISSUE TITLE
Set pointer-events: none to TileLayer and all non-iteractive layers

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#2396]

**Comment by tomhughes** [comment]
Can I ask what the reason was for removing pointer events from tile layers?

Only the removal of "view image" etc from the context menu has caused a certain amount of complaints on openstreetmap.org and if I knew the reason for this change it would make it easier to decide whether to override the CSS and re-enable them there.

**Comment by IvanSanchez** [comment]
Off the top of my head, I don't think there is a strong rationale or obvious use case.

From my personal point of view, preventing pointer events on gridlayers/tilelayers would prevent some weird edge cases such as a mobile browser zooming to a tile's extent on double-tap. It *should* be possible that the `touch-action` CSS will work for this, but there might be some browser weirdness. This means that overriding the `pointer-events` CSS rule **should** be a safe option and not cause any problems.

Also Leaflet does not expect users to attach pointer event handlers to gridlayers/tilelayers, so the easiest way to prevent problems (or additional logic) with event bubbling has been to avoid events in gridlayers altogether.

Please also note that https://github.com/Leaflet/Leaflet/pull/5290 would get rid of `<img>`s in the DOM altogether, by stitching them in a `<canvas>` like OpenLayers does. It's the only way to get rid of https://github.com/Leaflet/Leaflet/issues/3575 I'm afraid. This is planned, and the sensible idea is to have it on by default, but can be disabled.

**Comment by tomhughes** [comment]
Thanks @IvanSanchez. Sounds like it might be best to avoid that then and add something (more sophisticated) to our new context menu then.
