### ISSUE TITLE
Поведение Popup после смены иконки у маркера

### ISSUE THREAD

**Issue by DiamondSteel** [Leaflet/Leaflet#2401]
Пример: http://jsfiddle.net/nFYxj/2/

Если у маркера поменять иконку ( marker.setIcon( customicon ) ) то после перетаскивания у маркера самопроизвольно начнёт открываться popup. Так же у всплывающего окна сбросятся параметры ( offset: new L.Point(0, -40) )

Если иконку у маркера не менять - перетаскивание маркера не влияет на popup

**Comment by IvanSanchez** [comment]
@DiamondSteel Can you still reproduce with Leaflet 1.0.0?

**Comment by perliedman** [comment]
Closing this. Happy to reopen if we can re-state the issue in english, and it's still an issue in latest Leaflet.
