### ISSUE TITLE
splitwords fails with undefined

### ISSUE THREAD

**Issue by MarcBanc** [Leaflet/Leaflet#2408]
Hi,

I builded lastes leaflet and markercluster and it failed on simply matter:

```
Uncaught TypeError: Cannot read property 'trim' of undefined leaflet-src.js:135
L.Util.trim leaflet-src.js:135
L.Util.splitWords leaflet-src.js:140
L.Evented.L.Class.extend.on leaflet-src.js:354
L.MarkerClusterGroup.L.FeatureGroup.extend.initialize leaflet.markercluster.js:6
L.Class.extend.NewClass leaflet-src.js:247
L.markerClusterGroup leaflet.markercluster.js:6
Markers Markers.js:74
```

variable **types** is **undefined** when comes from L.Evented.L.Class.extend.on so **trim** on in throws error

**Comment by andreschardong** [comment]
Hi FalloutPL 
Had similar issue with the latest leaflet dev build and Leaflet.markercluster. the problem is with Leaflet.markercluster build version I guest. By using src files works fine. Hope this helps.
