### ISSUE TITLE
panInsideBounds becomes unstable with custom projection

### ISSUE THREAD

**Issue by perliedman** [Leaflet/Leaflet#2427]
In an issue reported on Proj4Leaflet (https://github.com/kartena/Proj4Leaflet/issues/59#issuecomment-33789825), @kvolleberg has figured out that ```panInsideBounds``` can become unstable for some situations, causing the map to continue panning very slowly in some direction.

An easy fix appears to be to adjust ```LatLng.MAX_MARGIN```, to make it less sensitive to small coordinate differences, but that might of course also affect other code.

The calculations in ```Map._limitCenter``` could also be adjusted to make it less sensitive to small rounding errors, but I'm not sure how the best accomplish that.

**Comment by perliedman** [comment]
Here's a fiddle to reproduce the issue: http://jsfiddle.net/v5ej8rv4/

As mentioned in #3200, it seems that the bug is most easily triggered by switching to fullscreen (F11) and zooming in a bit. Don't know if it's related, but zooming near to northern bounds (about Den Helder in the fiddle), seems to easily trigger it.

Have been able to reproduce it on both Chrome 40 and Firefox 35 on Ubuntu

**Comment by perliedman** [comment]
Ok, made an update to the fiddle that monkey patches `Map.panInsideBounds` to output the difference between `center` and `newCenter` when there is a difference.

When the bug triggers, the output looks like this on my machine:

```
"dlat=4.429224986779445e-9, dlng=1.2464296261782692e-9" script.js:50
"dlat=4.429288935625664e-9, dlng=1.2464358434272071e-9" script.js:50
"dlat=4.42935998989924e-9, dlng=1.2464411724977253e-9" script.js:50
"dlat=4.429445255027531e-9, dlng=1.2464447252114041e-9" script.js:50
"dlat=4.4294878875916766e-9, dlng=1.2464500542819223e-9" script.js:50
"dlat=4.429551836437895e-9, dlng=1.2464536069956011e-9"
```

Currently the tolerance for difference between two `LatLng`s is set by `L.LatLng.MAX_MARGIN` to 1e-9. Obviously, changing this to 1e-8 makes the problem go away on my machine. From https://github.com/Leaflet/Leaflet/issues/2427#issuecomment-33874223, it seem that this might not be a general fix, though, although I can preproduce such a huge error (0.5 degrees difference sounds a bit odd, maybe indicating some other problem).

I'll think some more about this.

**Comment by perliedman** [comment]
@dylanparry would be nice if you could try to monkeypatch your code like the fiddle above (http://jsfiddle.net/v5ej8rv4/1/) and see what `dlat`/`dlng` values you see when you enable the bounds.

**Comment by perliedman** [comment]
Did a test to determine what precision we can expect from projecting and then unprojecting a `LatLng` through Proj4Leaflet/Proj4:

```js
var center = map.getCenter();
for (var i = 3; i < 13; i++) {
  var centerPoint = map.options.crs.projection.project(center, i);
  var newCenter = map.options.crs.projection.unproject(centerPoint, i);
  console.log('dlat=' + (newCenter.lat - center.lat) + ', dlng=' + (newCenter.lng - center.lng));
}
```

For Leaflet's default spherical mercator, this gives dlat/dlng of exactly zero. For EPSG:28992 however, it gives values slightly larger than 1e-9:

dlat=4.0159662262340134e-9, dlng=1.611052624639342e-9

So it is pretty apparent that it is the numerical stability of the project/unproject operation in Proj4 that is the culprit, and not any logic within Leaflet.

Given this, I think the only option is to set a higher value for `L.LatLng.MAX_MARGIN`, or at least use a higher tolerance for the test in `panInsideBounds`.

Any thoughts on this, @mourner?

**Comment by mourner** [comment]
@perliedman yeah, I think `1e-8` is more than enough as a default.

**Comment by mourner** [comment]
Oh, read the situation more thoroughly and it seems like a set margin won't do it. Can we somehow derive the max margin value to use in `panInsideBounds` from the projection?

**Comment by perliedman** [comment]
Just thinking out loud, we could perform the test above when the map is first loaded, to determine the delta when projecting and unprojecting the map's center, and then setting the tolerance for `panInsideBounds` based on this value (selecting a slightly larger value, or 1e-9 if the diff is zero, which is what will happen with the default CRS).

I could make a PR if that sounds reasonable.

**Comment by mourner** [comment]
Another idea — what if we add `equals` as a CRS method that accepts two latlng objects like we did with distance? Then margin will be chosen according to each CRS, and we could then calculate margin in Proj4J and set some defaults for baked-in Leaflet CRS.

**Comment by perliedman** [comment]
Yes, better. Keeps the untidy details of weird projections out of Leaflet's core. :+1:

**Comment by emacgillavry** [comment]
Ran into same issue today using Leaflet 0.7.5. We clogs just love a custom projection... ;-) Hacked it with the suggested MAX_MARGIN fix for now. Any further suggestions? Don't suppose `equals` has been added as a CRS method yet?

**Comment by perliedman** [comment]
@emacgillavry it hasn't, as far as I know. However, the 1.0 version includes a lot of changes, it would be interesting to see if this problem still exists there.

**Comment by emacgillavry** [comment]
Wasn't aware Proj4Leaflet already had a branch compatible w/ Leaflet 1.0. That's great news. Will certainly investigate whether issue still exists. Thanks for pointing out.

**Comment by emacgillavry** [comment]
Prepared an example with Leaflet 1.0.0 beta 2 and branch from Proj4Leaflet compatible w/ this beta. Bug still appears. Open in Firefox and open Firebug to change the view window to see the map scroll down again... Check out http://bl.ocks.org/emacgillavry/raw/0e2696ea9ba3ac5ed2c7/

**Comment by perliedman** [comment]
Yes, reproducible in Chrome on Win8.1 for me as well.

My time is unfortunately very limited at the moment, but it should be fairly straightforward to implement a fix for this in Leaflet and Proj4Leaflet following [mourner's suggestions above](https://github.com/Leaflet/Leaflet/issues/2427#issuecomment-73292352).

**Comment by perliedman** [comment]
Apparently couldn't resist trying to implement this anyway.
