### ISSUE TITLE
zoomend triggered before scroll zoom complete

### ISSUE THREAD

**Issue by jduhls** [Leaflet/Leaflet#2429]
I make an ajax call on zoomend. When scrollWheelZoom is enabled, zoomend is triggered before the scrollzoom is complete. Is there a way to detect scrollzoomend? I want to make my ajax call on scrollzoomend because zoomend is triggered too early during the scrollzoom.

**Comment by amnesia7** [comment]
@jduhls do you have an example of the code you ended up using because I'm having a similar issue?

**Comment by amnesia7** [comment]
Since there's `this._map.fire('boxzoomstart');` would it be useful to also have `this._map.fire('scrollwheelzoomstart');` so it could be targeted easier?
