### ISSUE TITLE
leaflet-touch class always applied on map with Firefox 26 on Ubuntu

### ISSUE THREAD

**Issue by brunob** [Leaflet/Leaflet#2437]
Hi, as reported on Leaflet/Leaflet.draw#267, the leaflet map container always get the leaflet-touch class with FF 26 on Ubuntu (not with chromium or opera). The problem is that it makes controls render differently (see the screenshot in the issue referenced above).

**Comment by snkashis** [comment]
Could this issue be related to this upstream bug report https://bugzilla.mozilla.org/show_bug.cgi?id=970346 ?. Albeit from a Windows user.

**Comment by danzel** [comment]
Possibly, I found if you have logmein (Or some other RDC software? Can't remember) installed on a windows computer sometimes chrome will decide you are touch capable also.

**Comment by brunob** [comment]
For the update, as said in : https://bugzilla.mozilla.org/show_bug.cgi?id=970346#c2 this browser preference can be set if you play with "emulate touch events" in dev tools.Nnot a leaflet bug, we can close this issue.
