### ISSUE TITLE
getBoundsZoom uses zoom > maxZoom

### ISSUE THREAD

**Issue by kermit-the-frog** [Leaflet/Leaflet#2440]
Hi,
I'm using a very special CRS where the scale for a zoom is not computed via a formula but is looked up in an array instead. 

    scale: function (zoomIndex) {
        return this.getZoomScale(0) / this.getZoomScale(zoomIndex);
    },

    getZoomScale: function (zoomIndex) {
        // auf gültige Werte beschränken
        if (zoomIndex < 0 || zoomIndex > this.zooms.length - 1)
        {
            alert("Ungültiger Zoomindex: " + zoomIndex);
        }
        return this.zooms[zoomIndex].scale;
    },

As you can see I included an alert, to see if everything is ok. When I use L.Map.getZoomBounds sometimes the alert is shown. That's because you're using a do-while-loop an you increment zoom at the beginning of the loop. That results in zoom == maxZoom+1, if the bounds would fit in maxZoom.

Regards,
kermit-the-frog

**Comment by IvanSanchez** [comment]
I think this one might go away during the current refactor of `_resetView`.

**Comment by mourner** [comment]
Did it go away?
