### ISSUE TITLE
Adding an object (GeoJSON) to the tiles pane

### ISSUE THREAD

**Issue by robballou** [Leaflet/Leaflet#2473]
I'm creating a map with two sets of tiles: the base map (mapbox tiles) and some tiles that represent a heatmap. Then I'm adding a GeoJSON object of the country. It looks like objects are placed in `.leaflet-objects-pane` and all the tiles are placed in `.leaflet-tile-pane`, which means those can't be positioned the way I'd like: base map tiles, geojson, heatmap tiles.

Is there a way to get this setup? I've tried adding the base & country as a layerGroup and messing with z-index values but that still doesn't position them correctly.

Thanks!

**Comment by adrianbj** [comment]
I know this is ancient, but why do the docs state that geoJSON inherits the `pane` option from "Layer"?
https://leafletjs.com/reference-1.7.1.html#geojson-pane
