### ISSUE TITLE
Android 4.1 crash on zoom

### ISSUE THREAD

**Issue by JerryBels** [Leaflet/Leaflet#2478]
Hello guys !

So I'm starting a new app based on Cordova, and wanted to use Leaflet for my maps - either via Mapbox or directly with OSM. I encountered an issue when testing the most basic example, on Android 4.1 only, the app crashes when zooming in. I looked for many hours all over the internet, and found solutions that either didn't work or even sometimes I didn't understand ( someone said << android23 = ua.search('android [23]') !== -1 || ua.search("android 4.0") !== -1 || ua.search("android 4.1") >> - where am I supposed to put that ?!)

Note that the issue isn't even linked to the application itself, because when launching the stock Android browser and going to the leaflet website or mapbox website, when trying to zoom in on the available examples, the browser crash ! On Chrome for Android all is fine, though.

Sooo there it is, how to prevent that crash ?

Thanks !

**Comment by ilvalle** [comment]
@mourner is it visible to add this issue to https://github.com/Leaflet/Leaflet/milestones/1.0-beta1 ?

**Comment by mourner** [comment]
@ilvalle not sure if it's the same bug as #2693, can you verify any of the proposed fixes?

**Comment by ilvalle** [comment]
I changed Browser.js as
```
android23 = ua.search('android [23]') !== -1 || ua.search('android 4.1') !== -1
```
and loaded leaflet with
```
window.L_DISABLE_3D = true;
```
still crashing after a very few zoom.
With the following, it seems that the crash happens when you reach max-zoom 
```
#map {
    transform: none;
}    
```
In general the app crashes when is loading tiles and you try to zoom at the same time.
Hope it helps

**Comment by fab1an** [comment]
Please have a look at my comment [1]. I did a lot of debugging on this and all of the freezes could be traced back to browsers crashing when `css-transform` was set to it's previous value.

[1] https://github.com/Leaflet/Leaflet/issues/2693#issuecomment-46053713

**Comment by ilvalle** [comment]
I followed @fab1an's suggestion
I placed in https://github.com/Leaflet/Leaflet/blob/4c0f02879470cb4c1781db1739138d286040f0b4/src/dom/DomUtil.js#L141
```
pos.x = pos.x + (Math.random() / 10000);
```
it isn't so pretty, but it works. For me, the last thing is to apply this trick only when an android41 is detected.

**Comment by fab1an** [comment]
It's not pretty at all, but I think it fixes the problem at it's core. I don't think it's possible to reason about the code in a way that we can be sure identical values will never be set. Another way would be to store the last value that has been set and compare it or something?

**Comment by mourner** [comment]
@fab1an yeah. I'm thinking of a prettier solution. Thanks again for finding out the root cause of the issue.

**Comment by fab1an** [comment]
You're welcome, thanks for your work again ;).

**Comment by mourner** [comment]
Guys, could you please test if things got better after #3270?
