### ISSUE TITLE
Canvas circleMarker not clearing properly

### ISSUE THREAD

**Issue by adimitrov** [Leaflet/Leaflet#2483]
![screen shot 2014-02-21 at 14 50 17](https://f.cloud.github.com/assets/300693/2229868/16525052-9af7-11e3-81e6-b498bb101d7c.png)
Again it goes away when you interact with the map
I've narrowed down the problem to this line: https://github.com/Leaflet/Leaflet/blob/master/src/layer/vector/Canvas.js#L176
If I update it to `layer._prevWeight = ctx.lineWidth = clear ? layer._prevWeight + options.weight + 1 : options.weight;`
The problem goes away. I've never worked with canvas so I don't know if it is ok like this.

Here is a jsfiddle from #2476 with the problem: http://jsfiddle.net/w4D59/6/

**Comment by adimitrov** [comment]
Updated the jsfiddle to the latest master and the issue is gone, so I'm closing this. :+1: 

P.S
One less issue untill 1.0-beta :)

**Comment by mourner** [comment]
Awesome! I don't remember doing anything related so pretty weird that it's fixed :)
