### ISSUE TITLE
Popups unaware of content resizing

### ISSUE THREAD

**Issue by wthorp** [Leaflet/Leaflet#250]
Popups are unaware of their content being resized.  EG:  marker.bindPopup("Look!: &lt;br/&gt; &lt;img ...&gt;").  In this example, when the image loads, it will extend beyond the pop-up.

**Comment by bluebirdtech** [comment]
Just encountered this when calling ``setContent()`` in response to an AJAX request via Angular.

If I pass an element to ``setContent()`` the width is not updated.  If I pass HTML to ``setContent()`` everything is updated fine.

I wanted to compile and link the popup using Angular, but Angular provides the DOM element, not HTML. And HTML alone wouldn't have the scope binding.

As a workaround I'm manually building the HTML string.  Of course this means I can't use ng-click, but managed to work around it with:
``onclick="angular.element(this).scope().ctrl.myElementClick()"``

Note: ``ctrl`` is just from controller as.
