### ISSUE TITLE
Tabbing onto and off minimised layer group selection

### ISSUE THREAD

**Issue by boars** [Leaflet/Leaflet#2516]
This appears to occur in Chrome (32 & 33) - the other browsers I have access to seem to function correctly (IE8-11/Firefox). I don't have an earlier version of chrome to test with at present, sorry. 

When a map has the layer group controls, you can tab onto the minimized layer selection div. However the next tab doesn't take you to the radio buttons, it takes you to the start of the page. Doing a shift tab alternatively takes you to the footer of the page. If you cycle back through all the links on the page you can get to the radio buttons.

Edit: Now confirmed to not work correctly in version 33 of chrome also.

**Comment by Falke-Design** [comment]
Is working with Leaflet 1.7.1 and Chrome 96
![layer_control_tab](https://user-images.githubusercontent.com/19800037/144113131-443dd91d-08c9-4fca-b1d0-bdc3eaf8d76d.gif)
