### ISSUE TITLE
Double tap on disabled zoom button triggers double tap on map (to zoom or pan)

### ISSUE THREAD

**Issue by menzer** [Leaflet/Leaflet#2526]
-Observed on iOS 7 Safari, IE 11 (Surface RT), Chrome latest on Nexus 7 (Android 4.4.2)
-Observed on Leaflet 0.7.2

#### Steps to repro

1. Load http://leafletjs.com
2. Zoom all the way out.
3. Double tap the disabled zoom out button.

Expected behavior: nothing happens
Observed behavior: the map zooms in

Extra observations:
- On iOS, the active style on the buttons verifies that they are the touch targets
- On iOS and Chrome for Android (but not IE11) double tapping the zoom in on a fully zoomed-in map will pan the map as if the map was double tapped below

**Comment by IvanSanchez** [comment]
Closing as a duplicate of #3532

**Comment by umurzatayev** [comment]
This issue is still reproducible on http://leafletjs.com
