### ISSUE TITLE
Add option "disable fire event" in setView method or add new user event

### ISSUE THREAD

**Issue by maxdeepfield** [Leaflet/Leaflet#2532]
I want to know what caused map view change - user interaction or internal setView usage. Events "moveend" and "zoomend" fires in both cases, event "dragend" fires only when user manually dragged map.
So solutions can be:
1. new zoom change event that fires only when user changes it (via scroll or double click)
2. option to disable fire event on setView (maybe setZoom, panTo and others modifiers too)

**Comment by PascalPflaum** [comment]
I would need this feature as well and I'm willing to implement it, if there is not a solution already.
Would do it the way @AndriiHeonia suggested, if nobody insist on another way.

**Comment by ghybs** [comment]
Closing in favour of duplicate #2934
