### ISSUE TITLE
leaflet zoomAnimation result in black lines in mapview

### ISSUE THREAD

**Issue by apachemaven** [Leaflet/Leaflet#2541]
I am using leaflet 0.7.2, and I found that if I zoom the map continuely and quickly, I will find some black lines in the map view.
	
After read the source codes ,it seems that this is caused by the duplicate css style in the element of tile panel, I make a screenshot:
![xx](https://f.cloud.github.com/assets/4485890/2419954/8306da80-ab67-11e3-833e-83c38d08a300.png)

It seems that each time I zoom the map, the ```transform: translate(xxpx, -xxpx) scale(x);``` will be appended to the style of the element.

Is this a bug or do I miss anything?

**Comment by mourner** [comment]
Closing, will reopen if reproducible in master version.
