### ISSUE TITLE
GeoJSON shape distorted on Spherical Mercator WMS map

### ISSUE THREAD

**Issue by andreamartelli** [Leaflet/Leaflet#2543]
Hello,

I have a map with a simple **WMS** layer in spherical mercator projection (rendered by a OSM-Mapnik-TileCache server stack, everything is in **EPSG:900913 / EPSG:3857**).

First: I can't understand why, if Leaflet uses CRS **EPSG:3857**, whose unit is _**meters**_, I still have to provide coordinates, like _maxBounds_ and _center_, in WGS84 format, which is _**degrees**_. Is it an API inconsistency?

Second: I need to render a **GeoJSON** feature expressed in WGS84 coordinates (**EPSG:4326**), but the shape is visibly distorted (see pics below). Should I _**convert**_ the shape from EPSG:4326 to EPSG:3857? How? If I did so, I would have coordinates expressed in meters, while Leaflet still expects degrees! 

_I made a double check with a simple wms layer in OpenLayers and a GeoJSON overlay and it works fine, so I proved that the distortion is not in the data._

Any clue?

Here is the test GeoJSON, hope someone can understand the reason of the issue:

```
{
    "type": "Polygon",
    "coordinates": [
        [
            [14.740017498458682, 40.673078870109705],
            [14.740132563378529, 40.673283531348574],
            [14.741625561383819, 40.67246759585111],
            [14.741671820229074, 40.672308542443076],
            [14.74151049646397, 40.672262934612235],
            [14.740017498458682, 40.673078870109705]
        ]
    ]
}
```

GeoJSON feature on Leaflet map:
![snap 2014-03-13 at 18 19 02](https://f.cloud.github.com/assets/6525042/2421556/5cc77dcc-ab83-11e3-838a-0b0a913e13c6.png)

GeoJSON feature on OpenLayers map:
![snap 2014-03-13 at 18 18 48](https://f.cloud.github.com/assets/6525042/2421557/5ce1f972-ab83-11e3-9e4d-a8d8107c1f83.png)

**Comment by shenzhuxi** [comment]
> I tried to add this to a standard Leaflet map, but couldn't see any distortion except when on the outermost zoom levels (levels 0-2): http://jsfiddle.net/n6szg/ - I think this distortion might be due to Leaflet attempting to simplify the polygon.

I tried it with the latest leaflet http://jsfiddle.net/y6hns1gc/ and found geojson was sill not rendered the same in L.CRS.EPSG4326 and L.CRS.EPSG3857. 

As I understand, with default crs L.CRS.EPSG3857 option, geojson (which is ESPG:4326 and will be locked to it) has been projected correctly by leaflet automatically. 

But with L.CRS.EPSG4326 option, does Leaflet just untouch geojson data at all?
