### ISSUE TITLE
Init hooks for parent classes not getting called

### ISSUE THREAD

**Issue by nikgavalas** [Leaflet/Leaflet#2545]
This is reference to commit d0e7293 (I hope that is the right number). But the code is here in Class.js. The length check causes the problem.

// call all constructor hooks
if (this._initHooks.length) {
    this.callInitHooks();
}

This commit alone seems to break a plugin I am using. I have a plugin that uses addInitHook for a Polyline like so:
L.Polyline.addInitHook(function () {
// plugin code
});

When I create a L.Polygon (which is derived from L.Polyline), the initHooks don't get called. I stepped through the code and it seems because the L.Polygon object's _initHooks array is length 0. The problem is, the parent class (L.Polyline) does have a function in it's _initHooks array but it will never call it because it can't make it past the 'length' check in the L.Polygon class. Is this by design now? Is there a new way to should call addInitHook?

Thanks a lot for your time! Leaflet is awesome and I hope this helps!

**Comment by ventralnet** [comment]
Has this been resolved? I am still seeing this in v1.0.3
