### ISSUE TITLE
Initial positioning of TileLayer

### ISSUE THREAD

**Issue by schniedan** [Leaflet/Leaflet#255]
I've got 4 tiles each 256x256px large in zoom level 1. When creating a 512x512 px canvas for my map initialising it with zoom-level 1, why are the 4 tiles not "properly" positioned? As they would fit exactly into the 512x512 canvas, I would expect all tiles to be fully visible. Instead of this the whole picture is moved several px down-left, or respectively south-west. 

Is that somehown intended or considered a bug?

Further I need some correlation between LatLng of the map and tileLayer-Position. More precisely, I would need to be able to set: Zoom-Level 0 of TileLayer xy spreads from LatLng s to LatLng e. So I would always be able to draw Polygons oder Polylines at fixed LatLng positions.

This should be possible already, shouldn't it? Any ideas, what I'm doing wrong with my TileLayer positioning?

Kind regards!

**Comment by jianyunli** [comment]
> The number of tiles used for the world horizontally and vertically is 2^zoom. So for zoom 0, it's 2^0 = 1, for zoom 1 it's 2^1 = 2, for zoom 2 - 2^2 = 4 (not 3) and so on.

I believe this is not right, it should be  2^(zoom*2), at zoom level 1 => 4 tile images, at zoom level 2 =>16,  because every direction is doubled
