### ISSUE TITLE
L.Control.Layers doesn't work with dark theme from MapBox

### ISSUE THREAD

**Issue by cebence** [Leaflet/Leaflet#2554]
Leaflet's Layers Control doesn't work with MapBox's dark theme.
Control's background color should be dark and the icon white but the background color stays white.

Browser: Google Chrome 33.0.1750.154 m
OS: Windows 7 Professional Service Pack 1
Leaflet: 0.7.2
Demo: http://jsfiddle.net/cebence/53nJr/ (based on https://www.mapbox.com/mapbox.js/example/v1.0.0/layers-control/)

One part of the issue is in Leaflet, the other in MapBox.
Leaflet issue: https://github.com/Leaflet/Leaflet/issues/2554
MapBox issue: https://github.com/mapbox/mapbox.js/issues/716

Example:
    <script scr='https://api.tiles.mapbox.com/mapbox.js/v1.6.2/mapbox.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox.js/v1.6.2/mapbox.css' rel='stylesheet' />

    <div id="map" class="dark"></div>

    <script>
    var map = L.map('map').setView([38.902, -77.001], 13);

    L.control.layers({
      'Base Map': L.mapbox.tileLayer('examples.map-zgrqqx0w').addTo(map),
      'Grey Map': L.mapbox.tileLayer('examples.map-20v6611k')
    }, {
      'Bike Stations': L.mapbox.tileLayer('examples.bike-locations'),
      'Bike Lanes': L.mapbox.tileLayer('examples.bike-lanes')
    }).addTo(map);
    </script>

**Comment by yohanboniface** [comment]
Seems fixed by https://github.com/Leaflet/Leaflet/commit/f51f783b3a480a9e243dbf910783e59a5bf46730 to me.
