### ISSUE TITLE
0.8dev: iPad 2, iOS 7, pinch zoom beyond max and min levels freezes the map (canvas render)

### ISSUE THREAD

**Issue by asprega** [Leaflet/Leaflet#2584]
Hi all. I'm experiencing a weird issue not reproducible with Leaflet 0.7.

I have a simple map with no tiles (circle/rect layers only) drawn using the canvas renderer. Two levels of zoom (1 and 2).

```
_map = L.map('map-id', {
	minZoom: 1,
	maxZoom: 2,
	crs: L.CRS.Simple,
	zoomControl: false,
	attributionControl: false,
	renderer : L.canvas()
});
```

When I pinch to zoom on an iPad2 running iOS 7, Safari browser, the map freezes in the following conditions:

- When trying to pinch zoom out further when already at minimum zoom level 1 (map fully zoomed out)
- When trying to pinch to zoom in when already at the maximum zoom level 2 (map fully zoomed in)

The browser window is then stuck: the only way to recover is to reload the page.

More or less the same issue is present when using the SVG renderer but looks a little less severe, in the sense that the browser window seems to keep responding to touch events every once in a while (even if the map is still pretty much stuck).

I read of other similar issues here on GitHub but they all seem to be fixed with pull request so far.

**Comment by mourner** [comment]
@chasemgray did you have a chance to make a good test case for the issue? Also, what hack did you use?

**Comment by mourner** [comment]
OK, moving to `unconfirmed` milestone until we can reproduce this consistently on master version.

**Comment by mourner** [comment]
No reliable test case to reproduce this and also no subsequent feedback so closing for now.
