### ISSUE TITLE
Headless version for server-side usage (no DOM, no map)

### ISSUE THREAD

**Issue by hgoebl** [Leaflet/Leaflet#2588]
What do you think about a special build to produce a library which can be used completely without browser?

I store tracks in a MongoDB database (with geo-index). It would be handy if I can use the same objects (LatLng, LatLngBounds, ...) in my server-side logic with Node.js, e.g. calculating distances, bounds, ...

I haven't tried it, because I've no idea how many dependencies exist between the source code files. But after the first screening I identified some files which look like they could run server-side too (at least with small modifications):
- core/Class
- core/Util (without window.*)
- geo/**
- geometry/\* (maybe useful for SVG rendering or the like)
- GeoJSON (depends on many other classes, but would be nice to be independent of DOM stuff)

Of course I could clone the repo and change a lot of things and create a server-side library. But if the maintainers of Leaflet believe that this could be valuable for more users (not just me), this could probably done in the main repo.

What do you think?

**Comment by nyurik** [comment]
I think now it makes sense to implement Leaflet support for the server-side nodejs execution. I think the leaflet-headless library will run into compatibility issues and will have to constantly play catch-up.

Mapbox is moving from Mapnik-based to WebGL client-side styling, so if we want to support older browsers without WebGL, as well as the static images (e.g. show a map as a png image until user clicks on it to switches to dynamic map), we would need to render identical maps both client side and server side. We could keep using Mapnik on the server, but that would mean maintaining CartoCSS and WebGL styles in sync, which might not match in features.

I am thinking of implementing this functionality for [Kartotherian](https://github.com/kartotherian/kartotherian)

**Comment by hgoebl** [comment]
I've created https://github.com/hgoebl/Leaflet.POJSO for my own requirements, but it lacks all kind of rendering completely. Maybe a full Leaflet running in PhantomJS would be an alternative for you, @nyurik

**Comment by mourner** [comment]
@nyurik FYI Mapbox will also launch fallback image tiles generated from GL styles on the server.

**Comment by nyurik** [comment]
@mourner thanks, that's good to know, do you know which lib will used? Yet, I assume that it will only render the base gl tiles, and I need to render a static image that is identical to the client-side view generated by Leaflet -- with all the extra layers and pin clusterings and layouts, etc.  This way clicking that image and switching to dynamic map (client leaflet) would look the same.
@hgoebl thanks, rendering is what I am looking for. PhantomJS might be an option, but feel a bit heavy.
