### ISSUE TITLE
Offset in custom projection with ImageOverlay

### ISSUE THREAD

**Issue by tomvantilburg** [Leaflet/Leaflet#2592]
Not sure wether this is an issue with Leaflet or with proj4leaflet (I think the latter) but I would be happy if anyone can put me in the right direction.

I have an ImageOverlay that is custom projected with proj4leaflet but gets an offset when zooming to lower scales. The offset depends on where you zoom to.

Original issue:
https://github.com/kartena/Proj4Leaflet/issues/67

Fiddle showing the issue:
http://jsfiddle.net/_Tom_/ueRa8/
Fiddle showing correctly without projection:
http://jsfiddle.net/_Tom_/L9Ax8/

**Comment by vehrmann** [comment]
> You might also be interested in this recently added plugin, if you prefer working with LatLngs. From the description, it sounds like what @stvno proposes (use four corner coordinates instead of two).
> 
> https://github.com/ScanEx/Leaflet.imageTransform

Since Leaflet.imageTransform does not seem to be available anymore, I recommend [](https://gitlab.com/IvanSanchez/Leaflet.ImageOverlay.Arrugator) by @IvanSanchez 
Works flawlessly after I had trouble with Proj4Leaflet's approach to only use topleft and bottomright corners which led to offsets.
