### ISSUE TITLE
Custom Leaflet image finder regex

### ISSUE THREAD

**Issue by tmcw** [Leaflet/Leaflet#2603]
[this method for finding images](https://github.com/Leaflet/Leaflet/blob/master/src/layer/marker/Icon.Default.js#L32-33) fails when leaflet.js is not called leaflet.js. In mapbox.js land, we've settled on [hardcoding this](https://github.com/mapbox/mapbox.js/blob/repackage/mapbox.js#L3-5), but that approach breaks as soon as we want to distribute non-hosted, like as a zip download, bower, or etc.

**Comment by IvanSanchez** [comment]
We might want to consider using the error stack as the source for the filename of the leaflet library:

https://gist.github.com/plepe/3891980
https://gist.github.com/BR0kEN-/8620537

**Comment by mourner** [comment]
@IvanSanchez does it work on old IE?

**Comment by sheppard** [comment]
See #3559 for an alternate approach using CSS properties.

**Comment by ChristopheBougere** [comment]
Hi,
I have the same issue than @branonbarrett when minifying leaflet.js : "Couldn't autodetect L.Icon.Default.imagePath, set it manually.".
The only way is to define L.Icon.Default.imagePath manually, or do you think that it's going to be fixed on next release ?
Thanks

**Comment by mourner** [comment]
@ChristopheBougere there's no way to fix it for everyone. Leaflet code can't figure out where the images are if they're not present where it expects by default. I don't think it's a big hassle to add a 1 simple line of code.

**Comment by ChristopheBougere** [comment]
Sure @mourner, thank you !

**Comment by tmcw** [comment]
Closing; not seeing any actions out of this issue.
