### ISSUE TITLE
layer blending modes in addition to opacity

### ISSUE THREAD

**Issue by dnelson** [Leaflet/Leaflet#2608]
Hi,

For my application it would be very interesting to use different modes of blending two layers together, other than decreasing the opacity of the top layer. E.g.

http://nyalldawson.net/2013/03/coming-soon-in-qgis-2-0-blend-modes-for-layers/

Seems like this could either take the form of "CSS Blend Modes" or using canvas, depending on browser support:

http://blogs.adobe.com/webplatform/2013/06/24/css-background-blend-modes-are-now-available-in-chrome-canary-and-webkit-nightly/
http://blogs.adobe.com/webplatform/2013/01/28/blending-features-in-canvas/

Any interest?

**Comment by lzinga** [comment]
@mourner Hey I know this is quite old now but was wondering how one would do this? I am currently using the leaflet-heatmap plugin and encountering an issue. [I opened this issue](https://github.com/Leaflet/Leaflet.heat/issues/109) on the heatmap plugin but after trying to find ways to accomplish what I am wanting I think this has to do more so with the leaflet rendering of layers. If you could provide any direction on this it would help me out a lot!

**Comment by eddy-geek** [comment]
For a TileLayer, it seems like one needs to use https://github.com/Leaflet/Leaflet/pull/4553
And for an image overlay, see 
[How do I add custom CSS class to an image overlayer in Leaflet](https://gis.stackexchange.com/questions/234868/how-do-i-add-custom-css-class-to-an-image-overlayer-in-leaflet)
