### ISSUE TITLE
.toGeoJSON on anything should add options from the layer/item to the properties of GeoJSON

### ISSUE THREAD

**Issue by robbiet480** [Leaflet/Leaflet#2616]
Title is pretty self explanatory. I don't want to have to manually assign properties that are already in options to the GeoJSON that comes from .toGeoJSON on anything.

**Comment by jbcoder** [comment]
@robbiet480 Where did you find what you were looking for?

**Comment by robbiet480** [comment]
@jbcoder In your marker/feature/whatever, you should have a JSON object next to the options object named `feature` containing your input GeoJSON

**Comment by jbcoder** [comment]
@robbiet480 So, if I'm saving a ```featureGroup``` to GeoJSON using ```toGeoJSON()```, you're saying to grab the options from each layer and add it to the properties of the GeoJSON?

Thanks for the quick response!
