### ISSUE TITLE
Polygon rings API

### ISSUE THREAD

**Issue by danzel** [Leaflet/Leaflet#2618]
Currently in polyline.js we have a bunch of TODOs around rings
https://github.com/Leaflet/Leaflet/blob/master/src/layer/vector/Polyline.js#L20

And we have a weirdness with polygon creation that causes issues with leaflet.draw:
Create a polygon with new L.Polygon -> _latlngs is flat ```[ latLng, latLng, latLng ]```
Create a polygon from GeoJson -> _latlngs is nested ```[ [ latLng, latLng, latLng ] ]```

What are your thoughts on the Polyline/Polygon API?

We could change it so internally polygons are always nested and polylines never.
Then expand the api like:
```addLatLng: function (latlng, index)```
With index defaulting to 0.
By putting the index parameter second, people not using rings won't need to worry.

refs #2290

**Comment by yohanboniface** [comment]
> We could change it so internally polygons are always nested and polylines never.

+1, this would mirror the [GeoJSON specs](http://geojson.org/geojson-spec.html), and thus facilitate a lot of interactions with GeoJSON.

@mourner do you want me to work on a PR on this direction?

**Comment by mourner** [comment]
@yohanboniface sure!

**Comment by yohanboniface** [comment]
Should we close, now that #3279 is merged?
