### ISSUE TITLE
Fairly serious bug in the way marker click events are handled.

### ISSUE THREAD

**Issue by ghost** [Leaflet/Leaflet#2619]
This is really noticeable on Android but easily replicable on desktop - both 0.7.2 and the latest 0.8.0 are affected.  All you need is a map and a marker with a 'click' event.

Tap the marker (click handler will fire)
Move the map
Tap the marker (click handler will NOT fire)
Tap the map
Tap the marker (click handler will fire)

It's more noticeable on Android because tapping the map will often result in a 'drag' or 'move' - on desktop you have to actually drag the map.  Android probably needs a threshold below which 'touches' are not read as 'moves' but that's a separate issue I think.

The issue is in line 3724 (0.7.2 src.js)
'''if ((!this.dragging || !this.dragging._enabled) && this._map.dragging && this._map.dragging.moved()) { return; }'''

this._map.dragging.moved() = 'true' because the map was moved!!  I've no idea why it's checking that in the marker event - but the result is that it's easy to make markers 'unresponsive' - esp on Android

Note: I suspect this is what https://github.com/Leaflet/Leaflet/issues/2583 is talking about - but as the bug isn't specific to Android, I thought I'd create this one.

**Comment by jordandh** [comment]
Is this fix in any of the released versions or is it expected to be in 1.0? (I am experiencing it on 0.7.2)

**Comment by mourner** [comment]
Not sure. If you experience it in 0.7.3, then it's expected to be fixed in 1.0.
