### ISSUE TITLE
worldCopyJump panning interia over 180th meridian bug

### ISSUE THREAD

**Issue by ghost** [Leaflet/Leaflet#2624]
If you drag the map, release and let inertia carry you over the 180th meridian, the map bounces back and starts to spin.

To test, go to the following fiddle.  Drag the map and try let interia carry you over New Zealand in either direction east or west.

http://jsfiddle.net/73WEG/1/

I have tested in Chrome and Firefox on PC, Chrome on Android.  My apologies if there is a similar issue already logged but I couldn't see one.

**Comment by We-St** [comment]
Still not working for me In the current version 0.7.3:
[updated jsFiddle with current version](http://jsfiddle.net/qjbgnq4d/1/)

**Comment by mourner** [comment]
@We-St yeah, it was fixed in the master branch, soon to be 1.0.

**Comment by thatgirlcancode** [comment]
anyway this can be fixed in a pre-1.0 release? unfortunately i'm not able to upgrade until the plugins play catch up...
