### ISSUE TITLE
Using Leaflet with Web Workers

### ISSUE THREAD

**Issue by danimt** [Leaflet/Leaflet#2625]
I'm trying migrate some critical loops to Web Workers, as they need to process many points, and I can't have the page unresponsive or even crash the browser.

These loops are used to go through all points and create the respective leaflet objects (eg: `L.circle`, Generate `MaskCanvas` layers) for future use, as they get loaded for the current bounding box. These points, and its information and Leaflet object are stored on TaffyDB.

In the migration process I've found that Web Workers don't have access to the `window`, `document` and `parent` global objects. Even though I can bypass the `window is undefined` error by assigning the `self` object as `self.window`, in the Web Worker.

It would be useful to be able to use utility functions that don't require the map, to generate leaflet objects, and don't require `window` or `document`.

**Comment by nesterenko0602** [comment]
But it can help with the calculations that can be done within web worker, e.g.: I want to pass the array of LatLng tuples and get an array of LatLng tuples back after some calculations be done under the Web Worker hood (using the `leaflet` lib).

At this moment `leaflet` simply rises an error when being imported in Web Worker. Any chance `window` will be replaced with `this`?

**Comment by nesterenko0602** [comment]
> > Any chance `window` will be replaced with `globalThis`?
> 
> No chance until IE support completely dropped.
> https://caniuse.com/?search=globalThis

Do you consider using polyfill? Or how long do you consider to support IE (0.85% of market to date)?
