### ISSUE TITLE
L.LatLngBounds.pad negative parameter...

### ISSUE THREAD

**Issue by stefanocudini** [Leaflet/Leaflet#2673]
I was thinking that the pad method is much more useful if also accept negative values​​, that is, reduce the boundings.

**Comment by dawadam** [comment]
+1

"pad" methode with negative value doen't work correctly on Leaflet 1.0.3

**Comment by IvanSanchez** [comment]
@dawadam Please open a new bug report, don't resurrect a 2-year-old one.
