### ISSUE TITLE
set the click tolerance around a marker o a line

### ISSUE THREAD

**Issue by aborruso** [Leaflet/Leaflet#2689]
Hi,
is there a way to expand around a marker (or a line) the area that responds to the mouse click? A sort of a pixels buffer around?

It's too narrow for a geojson line object.

Thank you very much,

Andrea

**Comment by perliedman** [comment]
For other finding this issue, Makina Corpus' plugin AlmostOver might be of help to you: https://github.com/makinacorpus/Leaflet.AlmostOver

**Comment by aborruso** [comment]
@perliedman thank you very much

**Comment by pmacMaps** [comment]
I'll also add that it can be a pain for a GeoJSON line feature to register a "click" on touch devices.  While AlmostOver is nice, it would be great if there could be a great tolerance for click events on lines for touch devices.

**Comment by perliedman** [comment]
FWIW, I've also made this plugin to solve this problem: https://github.com/perliedman/leaflet-touch-helper

@pmacMaps I'll ponder over if there's something I can do in that plugin to help with the GeoJSON use case you mention.

**Comment by arashmad** [comment]
I found that this topic is still open :)
My workaround was
```javascript
this.map = L.map('map', {
      renderer: L.canvas({ tolerance: number })
    });
```
