### ISSUE TITLE
Map.setMaxBounds does not work with non-inverted CRS

### ISSUE THREAD

**Issue by Expyron** [Leaflet/Leaflet#2703]
I'm using a CRS with all positive transformation coefficients (e.g. "L.Transformation(1,0,1,0)" ). The coefficient c especially is positive, meaning that the y axis is not reverted.

When using Map.setMaxBounds, the map does get correctly bound horizontally. However, if I try to move the map vertically, it always goes back to the vertical center of the bounds, even if I didn't pan it out of bounds.

Expected result: Map should be panned correctly inside the bounds.
Observed result: Map cannot be moved vertically and always goes back to the center of the bounds.

I tested it with several browsers and always got the same error. I'm using the master branch

**Comment by OleLaursen** [comment]
I have a fix for this in #4030.

I'm currently monkey-patching _getBoundsOffset from the outside, and so far everything else seems to be working with the non-inverted y axis.
