### ISSUE TITLE
Using boxZoomEnd and destroying map instance

### ISSUE THREAD

**Issue by tzulberti** [Leaflet/Leaflet#2712]
I have a special case...

When the **boxzoomend** event is fired, I do some things and create new instances the map (without reloading the old map). The problem with this is that once that the map is recreated the value of **L.Draggable._disabled** has the value of true. 

The problem with this is that on the new map I can't drag.

**Comment by Malvoz** [comment]
Was this issue fixed by https://github.com/Leaflet/Leaflet/pull/3050?

**Comment by mourner** [comment]
Yep, seems like it!
