### ISSUE TITLE
Collapse layer control after tap on mobile phones

### ISSUE THREAD

**Issue by nhinze** [Leaflet/Leaflet#2713]
Is it possible to have the layer control collapse/close once a user selects a new layer?  On desktop the layer control collapses when the cursor moves out of the control. On a mobile phone, a user has to tap outside the control to close it. It would be nice if it would close after a layer has been selected.

**Comment by yohanboniface** [comment]
See https://github.com/Leaflet/Leaflet/pull/3049#issuecomment-204756291
