### ISSUE TITLE
scrollWheelZoom set as false, map is still zoomable with mouse wheel

### ISSUE THREAD

**Issue by Oxonium** [Leaflet/Leaflet#2720]
Hey ! :)

I have a hard time disabling the scroll wheel zoom on my map. The scrollWheelZoom option is set as false, but the map is still zoomable :

Code :

_map.leafletMap.options.scrollWheelZoom = false;

Result in console :

![scrollwheelzoom](https://cloud.githubusercontent.com/assets/2041167/3158889/aeff199a-eb09-11e3-8403-78f772b12469.png)

Do you have any idea about this issue ?

Thanks a lot in advance !

Em.

**Comment by timkelty** [comment]
@mourner Why is it listed as an option then if it doesn't work? http://leafletjs.com/reference.html#map-scrollwheelzoom

**Comment by perliedman** [comment]
@timblakely it works; if you set `scrollWheelZoom: false` when creating your map, it will not let you zoom with the scroll wheel.

Although not entirely apparent from the question, the issue is if you want to disable scroll wheel zoom _after_ the map is instantiated, you can't do it by just overwriting the option. Leaflet has no way of knowing that you changed the option. Instead, you need to disable the `scrollWheelZoom` handler as described by @mourner above.

**Comment by timkelty** [comment]
@perliedman Ah, sorry for the confusion.
All makes sense now, thanks.

**Comment by snehakamble** [comment]
map.scrollWheelZoom.disable(). is not working for my case.
I have initialised map earlier like :
  map = new L.Map('container',
            {
                center: [20, 0],
                zoom: 2,
                attributionControl: false,
                scrollWheelZoom: false
            });

now on ctrl+scroll need to set  scrollWheelZoom: true. Can anyone please help , how to update the leaflet properties?

**Comment by perliedman** [comment]
@snehakamble if you want to enabled the scroll wheel again, simply use `map.scrollWheelZoom.enable()` instead.

**Comment by bampnet** [comment]
`<l-map
...
:options="{scrollWheelZoom : false,}"
...>`

**Comment by lbrassaw** [comment]
I'm trying to disable an existing map scrollWheelZoom as per the above

`document.addEventListener("DOMContentLoaded", function () {
        var existingMap = L.DomUtil.get('map-edit-field-geo-location-0-value');
        existingMap.scrollWheelZoom.disable();
});`

but am getting a TypeError: Cannot read properties of undefined (reading 'disable'). What am I missing?
