### ISSUE TITLE
Toggle map.tap on Android (Leaflet 0.7.3)

### ISSUE THREAD

**Issue by juanel** [Leaflet/Leaflet#2736]
Hello!

On mobile devices I want to activate/deactivate the map with one tap. Main reason is to allow scrolling of the page when the map is occupying a big part of the viewport.

Toggling map.tap when the user taps on the map works always on iOS, but not on Android :

The tile (and sometimes the tiles surrounding it) that was touched to deactivate the map won't fire more 'click' events after map.tap is disabled.

My code is: 

	if (L.Browser.mobile) {
		map.dragging.disable();
		map.touchZoom.disable();
		if (map.tap) map.tap.disable();
		map.on('click', onTapToggleInteraction);
	} 

	function onTapToggleInteraction(e) {
	
		if ( !map.dragging.enabled() ) {
			map.dragging.enable();
			map.touchZoom.enable();
			map.tap.enable();
		} else {
			map.dragging.disable();
			map.touchZoom.disable();
			map.tap.disable();
		}
	}

I tested on:
Android 4.4.3: Firefox 30 and Chrome 35  
Android 4.2: Chrome 35

iOS 6-7: Safari and Chrome  (Click is always fired, allowing to switch state of map.tap) 

Any help would be highly appreciated. Thanks.

**Comment by yohanboniface** [comment]
Can you check if this is still a problem on latest master? If yes, please set up a minimal test case with http://playground-leaflet.rhcloud.com/ or any other jsfiddle like.

**Comment by IvanSanchez** [comment]
No more information has been provided, and more than a few weeks have passed. We'll assume this issue is no longer relevant and/or there is no interest to make a better report.
