### ISSUE TITLE
How to deal with maps loaded but hidden on current page?

### ISSUE THREAD

**Issue by seyfro** [Leaflet/Leaflet#2738]
Hi Mourner,

If a map is loaded hidden on a page and then gets displayed via toggle link or tab change for example, the map is not shown properly and you have to call invalidateSize() in order to fix this.

The issue here for me is that within my Wordpress plugin I cannot always detect if the map is loaded in a hidden div - I built a workaround to support jQuery tabs which is widely used and supports events which are fired when a tab is changed and as a followup calls invalidateSize(). Unfortunately many non-standardized solutions exist where the map does not show up properly and which do not fire events I could use in order to fire invalidateSize().

It would be great if a future version of leaflet could support proper map display even if it is loaded in a hidden div, but as I am pretty sure that this is not an option, I´d appreciate any hint on how to approach this issue.
thx,

Robert

**Comment by lismore** [comment]
I cannot get invalidateSize() to fire, it keeps telling me 
"Uncaught TypeError: this.$.map.invalidateSize is not a function"

**Comment by perliedman** [comment]
@lismore sounds like a problem with your setup, since `this.$` isn't something Leaflet uses.

If you think this is a Leaflet issue anyway, please make a JSFiddle or similar that illustrates the problem, and create a new issue.

**Comment by lismore** [comment]
thanks for the quick response

**Comment by perliedman** [comment]
@lismore you should probably ask/file a bug with the authors of the custom element, and they can create a Leaflet issue of there's really a problem in Leaflet.

It's unfortunately impossible for the Leaflet developers to keep track of how all projects that wrap and use Leaflet work.

**Comment by sn3p** [comment]
`invalidateSize` works, but it does not position open marker popups very well when they are already open.

![Screenshot 2019-10-15 at 13 01 26](https://user-images.githubusercontent.com/935529/66826079-eaa86180-ef4b-11e9-81f5-eabde2e24700.png)
