### ISSUE TITLE
IE11 svg-paint is massively slower than in 0.7.3

### ISSUE THREAD

**Issue by fab1an** [Leaflet/Leaflet#2751]
Paint-times in IE11 are much slower than 0.7.3, when using thousands of <path> elements, because for every change to a path the whole svg-hierarchy is relayouted and repainted.

If I add a single group to the <svg> and add all the pathes in there it works perfectly.

**Comment by stuartpb** [comment]
While this is a weird bug, I don't think there's anything wrong with putting a `<g>` around the `<path>` elements, as this allows some degree of encapsulation to the SVG that may prove useful later / to the end developer (other SVG elements may be included alongside the paths).

**Comment by mourner** [comment]
Yeah, I think we can add `g` back for both VML and SVG.
