### ISSUE TITLE
tileerror event not documented

### ISSUE THREAD

**Issue by tmcw** [Leaflet/Leaflet#2756]
http://leafletjs.com/reference.html#tilelayer-loading

But

https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/GridLayer.js#L424

**Comment by arahansen** [comment]
Just ran into a case today where it would have been nice to have tileerror documented somewhere. +1

**Comment by IvanSanchez** [comment]
The 1.0.0 docs already have this: http://leafletjs.com/reference-1.0.0.html#tilelayer-tileerror

Maybe worth a simple PR to fix the 0.7.x docs?

**Comment by IvanSanchez** [comment]
Closed via #4203 / #3916
