### ISSUE TITLE
Jumpy scrolling with touchpad (vertical/horizontal double finger scroll).

### ISSUE THREAD

**Issue by ChALkeR** [Leaflet/Leaflet#2757]
When using a touchpad with double-finger scroll enabled for both vertical and horizontal directions, the scroll becomes jumpy in some cases.

This happens when the user moves his fingers not following a straight vertical line, but a bit in horizontal direction. For example, left and bottom cause opposite scrolling, so left-bottom movement becomes jumpy.

This could be solved simply by ignoring horizontal mouse scroll events (like google maps do).

**Comment by mourner** [comment]
Hey, can you check if https://github.com/Leaflet/Leaflet/pull/3653 works?

**Comment by ChALkeR** [comment]
Sorry, missed this somehow.
I can confirm that this is fixed in the recent 1.0 beta.

**Comment by IvanSanchez** [comment]
@ChALkeR beta2 was released 2015-oct-14, and the [commit fixing horizontal scroll](https://github.com/Leaflet/Leaflet/commit/a969d204766a1275ac362f76e64358d5e920194b) was merged 2015-oct-20. Please use `master` instead of beta2 for this.

**Comment by ChALkeR** [comment]
Huh? I was under an impression that I was checking beta2. Will recheck later today.

**Comment by IvanSanchez** [comment]
@ChALkeR Exactly my point: the bug is present in beta2 but fixed in `master`.

**Comment by ChALkeR** [comment]
@IvanSanchez What do you mean? I stated above that I didn't observe this bug anymore.

**Comment by ChALkeR** [comment]
Ah, yes. I was actually checking `master`, not beta2.
