### ISSUE TITLE
zoomAnimation, markers, and fitBounds generate visualization problems

### ISSUE THREAD

**Issue by gacarrillor** [Leaflet/Leaflet#2774]
Say you create a marker and call fitBounds.
Now you want to do the same for another point, first removing the previous marker.
You've got a problem: tiles are not properly shown this time.
It is reproduced in http://jsfiddle.net/gcarrillo/73mVh/4/ (Marker A -> Marker B -> Marker A)

Setting zoomAnimation to false avoids the issue.
I'm using FF 30.0, not sure if it happens on other browsers as well.

Regards, 
Germán

**Comment by IvanSanchez** [comment]
Cannot reproduce.
