### ISSUE TITLE
0.8-dev, can't add polyline to a custom pane?

### ISSUE THREAD

**Issue by Jakobud** [Leaflet/Leaflet#2779]
I have the following:

```
map.createPane("myCustomPane");
L.polygon([[0,0],[5,5],[3,3]], { pane: "myCustomPane" });
```

Doesn't show up.  Pane's container is empty.  Looking through the source, it looks like Markers can be easily added to panes.  Can polylines not be added?

`L.Polygon` extends `L.Polyline` extends `L.Path` extends `L.Layer`, which has `overlayPane` set in the options:

https://github.com/Leaflet/Leaflet/blob/master/src/layer/Layer.js#L5

Am I missing something here?

Adding markers to panes works fine:
```
map.createPane("myCustomMarkerPane");
L.marker([0,0], { pane: "myCustomMarkerPane" });
```

**Comment by zhxsh** [comment]
Keep only one map,it solves my big problem,thank you very much
