### ISSUE TITLE
0.8-dev IE10 map overflows outside of map container

### ISSUE THREAD

**Issue by DeadBurger** [Leaflet/Leaflet#2788]
On Internet Explorer 10 the map overflows outside the container when zooming and then resets back to normal.

Here is a JSFiddle to reproduce the issues: http://jsfiddle.net/D3vC8/5/

**Comment by danzel** [comment]
From @surkova
A member of our team has a laptop with touch support (Lenovo Yoga Pro 2, Windows 10 Technical preview, touch screen with 3200x1800 resolution) and he uses IE11 11.0.9800.0. He experiences a weird zoom bug that you can reproduce even on Leaflet's homepage (currently using version 0.7.3) on Overview Tab. When you try to zoom in / out in the map, it overflows the container and the overflow may take up to whole screen.

**Comment by IvanSanchez** [comment]
This looks like a IE10 rendering heisenbug to me. I can reproduce by disabling the animated zoom end transition so it stays on the screen... but as soon as you alt-tab to the web developer tools, or just  move the cursor on top of the faulty tiles, IE10 redraws the screen. And triggering while having a tile selected in the DOM explorer causes it to be non-reproducible: the map just glitches between zoom levels without overflowing.

I see no way of solving this glitch, short of disabling animations for IE10 altogether :-(

**Comment by IvanSanchez** [comment]
Interestingly enough, setting `z-index: -1` (or lower) in the map `<div>` container seems to alleviate the bug :-D

**Comment by mourner** [comment]
Wow, WTF.

**Comment by IvanSanchez** [comment]
Unfortunately, setting `z-index: -1` on the map container will break all touch interactions on WinPhones (and make it glitch extra hard).

Which begs the question of how the f*** to solve this for the edge case of IE10 on a Win8 tablet.

I have been trying a few alternative methods to try and make IE10 isolate the map div so it will clip the contents (nested container, alternate ways of creating a z-index stacking context) with no luck at all.
