### ISSUE TITLE
[Proposal] Add isVisible() Method to L.Path

### ISSUE THREAD

**Issue by jchamberlain** [Leaflet/Leaflet#2793]
Leaflet clips paths and descendant classes to fit the current viewport. In some cases it'd be nice to have an easy way of determining whether a feature has been entirely clipped out, i.e., is not visible. `_checkIfEmpty()` does basically that, but it's obviously a private method, and it fails for items that have not yet been added to the map (they don't have `._parts` set). Would something of this nature be acceptable in a PR? (`L.Path` is so complicated I didn't want to mess with it without asking first. :p)

**Comment by mourner** [comment]
I think it's fine to do double work here because it doesn't pose any significant performance hits. At least I can't think of a use case where it does.
