### ISSUE TITLE
Proposal to Reorganize API docs to individual pages

### ISSUE THREAD

**Issue by Jakobud** [Leaflet/Leaflet#2794]
The API doc page is getting huge and is going to continue to get even bigger as time goes on.

This is a drastic change but I was thinking about reorganizing the API doc page into many pages, one page per API class/topic.  Each page would have a table of contents at the top, and then whatever class is being discussed below it.

Below that, each page could have links to tutorials for that class, extra examples for how to use the class, etc... There would be a lot of extra room to put some good info on these pages that would otherwise make the already huge API doc page too big.

Any thoughts on this? It wouldn't be too hard to do, just a little time consuming.  I think it would be a positive change.

**Comment by mourner** [comment]
I think we're solving the concerns here by the dynamic table of contents implemented as a part of #3578, so we're good here — adding individual pages in addition to one global docs page would only increase confusion and complexity in my opinion. Maybe we should still split the huge page into parts purely for code organization concerns, but that's a topic for discussion in another issue. @Jacobud sorry not to accept this!
