### ISSUE TITLE
setZoom does not fire a moveend event during tests

### ISSUE THREAD

**Issue by manleyjster** [Leaflet/Leaflet#2796]
I'm writing tests for a plugin and they are failing because `moveend` is not being fired on the map after I call `map.setZoom`.

I'm writing a plugin which extends `L.Polyline`.  I want to write a test to make sure that my polyline layer is oriented correctly after the user zooms, since I had trouble with this for a while.

I've got this feature working correctly in the browser (i.e. when I navigate to my demo page), but my tests are still failing.  I've isolated the cause of these failing tests to a missing 'zoomend' event (although there is likely another root cause which is at the bottom of both).

Specifically, the test that fails is:

```javascript
it("Origin is preserved during zoom.", function(done) {
	var anchor = new L.LatLng(41.7918, -87.6010),
		pointer = new L.Illustrate.Pointer([new L.Point(0,0)], anchor).addTo(map),
		latlngs;

	map.on('zoomend', function() {
		latlngs = pointer._getLatLngs();
		expect(latlngs[0]).to.be.closeToLatLng(pointer._latlng);
		done();
	});

	pointer._map.setZoom(pointer._map.getZoom() - 1);
});
```
The error message that the test reporter prints is:
```
✗ Origin is preserved during zoom.
  Chrome 35.0.1916 (Linux)
  Error: timeout of 2000ms exceeded
```

It's clear from this that the `done()` callback is never invoked, which suggests that the `zoomend` event is not being caught.

Any ideas what might be causing this?  I've struggled with this for quite a while - the asynchronous nature of the animation (specifically `L.Util.requestAnimFrame`) make it difficult to test.

You should be able to reproduce this error by cloning the [Leaflet.Illustrate](https://github.com/manleyjster/Leaflet.Illustrate) repository, then running
```
npm install
grunt test
```

**Comment by mourner** [comment]
Could you look into this again for the master branch? I'll reopen if it's still an issue.
