### ISSUE TITLE
Bug in DomEvent: removeListener does not remove listener is some cases

### ISSUE THREAD

**Issue by Scalar4eg** [Leaflet/Leaflet#281]
removeListener does not remove SAME listeners
Here is simple test:

``` javascript
function OnClick() {console.log("i'm OnClick listener");}

for(var i=0;i<10;i++) L.DomEvent.addListener(document, "click", OnClick);
for(var i=0;i<10;i++) L.DomEvent.removeListener(document, "click", OnClick);
```

Now we can click on the page and we'll see message "i'm OnClick listener" 9 times instead of 0.

**Comment by mikila85** [comment]
so how am i spose to do this?
i get duplicate events fired because it initialized the controller few times :(
