### ISSUE TITLE
paths don't work with Java FX web view

### ISSUE THREAD

**Issue by calvinmetcalf** [Leaflet/Leaflet#2858]
paths seem to be projected wrong in the java fx web view
![screen shot 2014-08-20 at 9 40 19 am](https://cloud.githubusercontent.com/assets/1128607/3981599/a49b73f6-286f-11e4-957d-f489e9dac282.png)
![screen shot 2014-08-20 at 9 40 27 am](https://cloud.githubusercontent.com/assets/1128607/3981601/a7c49fe4-286f-11e4-9c96-1d11c5da8cd9.png)

you can pan the map fine, but when you lift up the mouse button the shapes move.

will give more information once I figure out how the hell to debug java fx webview

**Comment by achennuru** [comment]
Upgrading to Java 8 Fixed this problem.
