### ISSUE TITLE
mobile double tap on zoom control

### ISSUE THREAD

**Issue by sallyw0802** [Leaflet/Leaflet#2878]
on mobile, double tap on the zoom control is recognised as a double tap zoom event on the map. the map also moves to the location of the zoom control button. 

eg: if you double tap on the zoom out button, the map will be zoomed in since it is recognised as a double tap zoom in event

a quick example would be http://leafletjs.com/examples/mobile-example.html

**Comment by javimolla** [comment]
Is this still a bug? If I double tap on zoom out button the map is zoomed out, not in

**Comment by IvanSanchez** [comment]
@javimolla Can you check if double-tapping on a zoom control fires any `click` or `dblclick` events on the map? e.g. `map.on('dblclick', function(){...})`. If not, I think we can safely close this one.

**Comment by javimolla** [comment]
I've checked and no events(click, dblclick) on map when double tapping on zoom controls

I also think you can close this one

**Comment by akkatracker** [comment]
@IvanSanchez time for a close?

**Comment by yohanboniface** [comment]
Thanks
