### ISSUE TITLE
L.control.layers with scroll doesn't works correctly on touch devices

### ISSUE THREAD

**Issue by jcagarcia** [Leaflet/Leaflet#2882]
Scroll on **L.control.layers** works fine on Desktop browsers when there's many layers. However, on touch devices when drag **L.control.layers** element to scroll it, map detects firsts the drag event and move the map without scroll controlLayer.

To solve this, i've change the method **_initControlPos** on leaflet.js:8387 and replace it with:

var corners = this._controlCorners = {}, l = 'leaflet-', container = this._controlContainer = L.DomUtil
							.create('div', l + 'control-container',
									this._container.parentElement);

NOTE: Modify CSS to adapt control layers.

With this, mobile devices detects scroll event instead of map drag event.

Pull Request?

**Comment by crazydeanofino** [comment]
The above solution didn't exactly work for me with the <a href="https://github.com/ismyrnow/Leaflet.groupedlayercontrol" target="_blank">grouped layer control plugin</a>.

Here is how I modified:

var grouplayercontrol = L.control.groupedLayers(baseMaps, controllayers, {position: 'topright'});
map.addControl(grouplayercontrol);	
if (!L.Browser.touch) {
  console.log("not touch");
  console.log(grouplayercontrol._container);
   L.DomEvent
    .disableClickPropagation(grouplayercontrol._container)
    .disableScrollPropagation(grouplayercontrol._container);
} else {
  console.log("touch");
    L.DomEvent.disableClickPropagation(grouplayercontrol._container);
}

**Comment by maptastik** [comment]
For what it's worth, I was having a similar issue to @jcagarcia and the solution from @crazydeanofino worked like a charm!
