### ISSUE TITLE
Layer initialization slowwww on IE on touch device

### ISSUE THREAD

**Issue by ghost** [Leaflet/Leaflet#2908]
Hi,
in my page I use a topojson with ~ 4800 polygons. The layer initilialization takes about 15 min on IE11 vs. 2 sec on Chrome and Firefox (Leaflet 0.7.0). I narrowed it down to the addEventListener calls (about 13000) and the problem disappeared when on my touch monitor I set the touch flag to false in the debugger. On a machine without touch there was no problem.
As this is a prototype app that's not yet published I can only give you a link via PN. It's in German, so I have to create a description how to reach the map page first.
Thanks,
Thomas

**Comment by t-sch** [comment]
I fear this bug has reappeared in 0.7.7.
Just try my fiddle again and change the version number to 0.7.7 - running in previous versions is fast.
