### ISSUE TITLE
WP8.1: tapping outside map layer moves map (only in master)

### ISSUE THREAD

**Issue by pexi72** [Leaflet/Leaflet#2910]
With WP8.1. IE11  (Lumia phones) and Leaflet master version tapping div that is outside of map affects also map 
But only after map is moved by dragging it. Direct after page load it doesn't happen

With stable version no problem

master version: http://gpspekka.kapsi.fi/leaflet/test8.html
stable version: http://gpspekka.kapsi.fi/leaflet/test7.html

**Comment by IvanSanchez** [comment]
I can not reproduce this on a Lumia 735. Instead, I get glitches very similar to those of #2788.
