### ISSUE TITLE
Problem with numbers rounding in L.PolyUtil.clipPolygon

### ISSUE THREAD

**Issue by aparshin** [Leaflet/Leaflet#2917]
It was added rounding of clipping result in util functions `L.PolyUtil.clipPolygon` and `L.LineUtil.clipSegment` in commit b329c4a9fd9e0070e7569c858be8ac8c4b7ae118.

But I use that functions in https://github.com/aparshin/leaflet-boundary-canvas as general-purpose clipping utilities without any assumptions of scale. Such rounding breaks the plugin when I try to use it with Leaflet 0.8-dev.

Is it appropriate way to add optional parameter to clipping util functions, as you did for `L.Point`? If that is ok, I will implement it and make PR.

**Comment by aparshin** [comment]
@danzel @mourner Is there any progress with this issue and corresponding PR?

Can I help somehow to move on (tests, examples, etc)?

**Comment by danzel** [comment]
Need to wait on @mourner to review, looks like everything is there.

**Comment by mourner** [comment]
Sorry I took so long to review this, merged!

**Comment by aparshin** [comment]
Many thanks for merge!
