### ISSUE TITLE
mapbox doesn't work "out of the box"

### ISSUE THREAD

**Issue by dcsan** [Leaflet/Leaflet#2920]
I created a new project following the tutorial, but all the mapbox tile URLs return 

GET http://b.tiles.mapbox.com/v3/MapID/9/252/169.png 404 (Not Found) 

indeed when i try to open the URLs directly:
http://b.tiles.mapbox.com/v3/MapID/9/252/169.png

```
{"message":"Not Found"}
```

https://www.mapbox.com/help/message-not-found/
you will need to point your map embed to share.html instead of index.html at the end of your file path. See the map options for more details on extending the map embed options.
https://www.mapbox.com/developers/api/maps/#embeds

how do i do this with Leaflet?

or do i need to upgrade to a paid mapbox account with an access token to use their tiles?
then with leaflet how do i pass in this token information?

using the meteor framework, so not sure if that is related.

also i notice mapbox documentation is all around /v4 whereas leaflet is using /v3

is there another tile provider that is easier to get started with? this is quite a user-unfriendly first experience.

**Comment by FBRTMaka** [comment]
Spent all weekend trying to get out of the 404 issue...I'll give this a try but at this point Mapbox seems to not work well out of the box.

**Comment by perliedman** [comment]
@FBRTMaka here's the relevant documentation from Mapbox's site: https://www.mapbox.com/developers/api/maps/

If you want to the true "out of the box" experience, I think you should use [Mapbox.js](https://www.mapbox.com/mapbox.js/api/v2.2.3/) directly instead of going via Leaflet, although using Leaflet is just a matter of pasting in the correct URL.

**Comment by pu239ppy** [comment]
Go to https://www.mapbox.com/studio/styles/ select a style you would like to use, click `Leaflet` and a helpful URL will be provided you may the copy it and paste as the first parameter in L.tileLayer
