### ISSUE TITLE
Requesting HTTPS support for CDN

### ISSUE THREAD

**Issue by fulldecent** [Leaflet/Leaflet#2944]
For example this page
https://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.388.html

Uses leaflet CDN but looks like this for me:
![screen shot 2014-10-13 at 18 26 44](https://cloud.githubusercontent.com/assets/382183/4621187/067da4a8-5328-11e4-9a24-20bf19011275.png)

Because Chrome refuses to load insecure content from leaflet CDN

**Comment by mourner** [comment]
Not feasible right now for cdn.leafletjs.com. We should recommend using https://cdnjs.com/libraries/leaflet for this case.
