### ISSUE TITLE
Problem adding geoJson a second time

### ISSUE THREAD

**Issue by RobbieTheWagner** [Leaflet/Leaflet#2947]
I am using PruneCluster with Leaflet and I have custom logic happening to attempt to add and remove polygons when clusters are created. It mostly works, but I have an issue when I leave the page, and come back. I need all the markers that were put on the map previously, to be added again. This seems to work fine for markers without a geoJson layer, but when I try to add back a geoJson layer I get `Uncaught TypeError: Cannot read property 'min' of undefined` which is being triggered by this in Leaflet:

``` js
    _getBitCode: function (/*Point*/ p, bounds) {
        var code = 0;

        if (p.x < bounds.min.x) { // left
            code |= 1;
        } else if (p.x > bounds.max.x) { // right
            code |= 2;
        }
        if (p.y < bounds.min.y) { // bottom
            code |= 4;
        } else if (p.y > bounds.max.y) { // top
            code |= 8;
        }

        return code;
    },
```

My custom code to add shapes, when the marker is not clustered looks like this:

``` js
    pruneCluster.PrepareLeafletMarker = function (leafletMarker, data) {
      if (data.isShape) {
        map.addLayer(data.geoJsonLayer);
      }
      leafletMarker.on('click', function (e) {
        GenerateRrosePopup(e, data.popupContent);
        if(data.isShape) {
          map.fitBounds(data.boundsForFit);
        }
      });
      leafletMarker.setIcon(data.icon);
    };
```

`map.addLayer(data.geoJsonLayer)` is what causes the issue. I'm not sure why though because my geoJson object looks as I expect it to.

Why would this same code work for initially adding the geoJson layer, but then fail when I come back to the page and try to add the points and shapes I previously added?

**Comment by codeofsumit** [comment]
I have the same issue.

After re-adding geoJSON layer to a map and calling `fitBounds`, i get:

`Cannot read property 'min' of undefined`

Might this be related?

**Comment by codeofsumit** [comment]
Alright we're using the beta version now to have this resolved.
Kinda scary to use it in a huge production app.

**Comment by a1an77** [comment]
I just hit a similar problem when updating to 1.0beta2 and it took quite a bit to figure out plugin compatibility as the root source. It would be very appreciated to catch the error and give advice on the possible cause when introducing backward incompatibility points. It will save developers quite a bit of debugging time.

**Comment by pedrovsra** [comment]
I'm getting this problem while using the version 1.03. I'm trying to print a map using the browser print, working with an empty map. When I add my layers, it doesn't work anymore and I get the "Uncaught TypeError: Cannot read property 'call' of undefined" error.
![image](https://user-images.githubusercontent.com/3902763/27292253-43e142f8-54e9-11e7-9916-52d5dbbe6438.png)
I tried to disable canvas and messagebox but no success

**Comment by perliedman** [comment]
@pedrovsra if you believe this is a bug, I suggest you open a new issue. Also, please first make sure the plugins you use are compatible with 1.0, as you can see from comments above, old plugins could be the source of this issue.

It would be great if you could provide a running example of the problem, for example using http://playground-leaflet.rhcloud.com/?html,output - this makes it a lot easier to find, understand and debug the problem.

With the information we have from your report now, it's more or less impossible for us to tell if this is a bug or not.
