### ISSUE TITLE
TileLayer loading event fired before layeradd event

### ISSUE THREAD

**Issue by ventralnet** [Leaflet/Leaflet#2967]
Fiddle of the issue http://jsfiddle.net/ventralnet/rnp2f769/

Notice that the 'loading' event is not logged to the console.  This is because the loading event fires before the layeradd event is fired

I came across this issue when trying to incorporate a loading indicator to display when layers are loading.  Do you think this is a valid issue?

**Comment by yohanboniface** [comment]
`layeradd` event is fired after `onAdd` has been called. So everything that's run during `onAdd` can't be hooked on the `layeradd` event. I think this was already the case in 0.7.x.
@mourner should we have some `beforeadd` event that'd be fired before `onAdd` is run?

**Comment by jasonoverland** [comment]
+1 to asking the question but not having a clear solution.

I'm using the plugin Leaflet.Loading which also suffers from this issue (https://github.com/ebrelsford/Leaflet.loading/issues/28)

I also considered using Leaflet.Spin plugin which looks like it would have the same issue.

The hack fix is to peek at _loading when the listener receives the layeradd event. Could this kind of fix be put into _layerAdd?

Or would it be feasible to have layeradd fire before loading is called?

**Comment by perliedman** [comment]
From what I gather, you want to add a `load` listener to every layer. How about adding an init hook to `L.Layer`, instead of trying to do it on layer add from the map class? From 1.0, all layers must extend `L.Layer`. Or am I missing something?

**Comment by Falke-Design** [comment]
Like @perliedman described, the listener can be added in the initHook:
```
L.Layer.addInitHook(function() {
    this.on('loading',function(e){
    	console.log(e);
    });
});
```
http://jsfiddle.net/falkedesign/yaznmdeq/
