### ISSUE TITLE
autofit

### ISSUE THREAD

**Issue by SmuSmu** [Leaflet/Leaflet#2969]
Hi,

a autofit method would be fine. So after adding markers and so one i like to call a autofit method set set the view to all markers with the minimum zoom level.

**Comment by perliedman** [comment]
@SmuSmu Leaflet does not keep track of markers in any special way: markers are layers, and generally you don't want to fit all visible layers into view.

I would suggest keeping track of the markers in your application. If you keep all of them are in a `FeatureGroup`, you can easily get the bounds with [`getBounds`](http://leafletjs.com/reference.html#featuregroup-getbounds).

If you _really_ want an autoFit method, you can hack it together with the `eachLayer` method. Here's a quick hack:

```
        function autoFit(map) {
            function getBounds(layerContainer) {
                var bounds;
                layerContainer.eachLayer(function(l) {
                    var layerBounds;
                    if (l.eachLayer) {
                        var layerBounds = getBounds(l);
                        bounds = bounds ? bounds.extend(layerBounds) : layerBounds;
                    } else if (l.getLatLng) {
                        var latLng = l.getLatLng();
                        bounds = bounds ? bounds.extend(latLng) : L.latLngBounds([latLng]);
                    }
                });

                return bounds;
            }

            var bounds = getBounds(map);

            if (bounds) {
                map.fitBounds(bounds);
            }
        }
```

This will, however, fit any layer with a `getLatLng` method, not only markers.
