### ISSUE TITLE
ID property missing when passing GeometryCollection to pointToLayer

### ISSUE THREAD

**Issue by bricemciver** [Leaflet/Leaflet#2971]
Could be fixed by changing the following code. Useful for tracking of markers by ID.

In src/layer/GeoJSON.js:
line 107:
	layers.push(this.geometryToLayer({
geometry: geometry.geometries[i],
type: 'Feature',
properties: geojson.properties
}, options));

should be:
	layers.push(this.geometryToLayer({
geometry: geometry.geometries[i],
type: 'Feature',
properties: geojson.properties,
id: geojson.id
}, options));

**Comment by yohanboniface** [comment]
I agree with @jfirebaugh but I guess now it's on the history of Leaflet and should leave with it. Closing as no action is expected.
