### ISSUE TITLE
master: almost all tilelayer.wms options are added to wmsParams

### ISSUE THREAD

**Issue by sheppard** [Leaflet/Leaflet#2972]
It looks like there is [code in TileLayer.WMS](https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/TileLayer.WMS.js#L24-L30) that is meant to filter out `crs`, `uppercase`, and anything that looks like it belongs to `this.options`.  The `crs` and `uppercase` filters still work, but the rest of the options are passed on, e.g: `pane`, `attribution`, `opacity`, and `tileSize`.  These end up getting added to the URL, which is usually harmless, but can break things depending on the property.  (I've seen WMS services break when the attribution was set with HTML content).

I think this has to do with the use of `hasOwnProperty()` as the filter predicate which isn't working with the new `this.options` prototype stack.  In [leaflet.wms' Overlay](https://github.com/heigeo/leaflet.wms/blob/gh-pages/leaflet.wms.js#L258-L272) I ended up using an explicit blacklist but I'm not sure that's the right approach either.

**Comment by FilmCoder** [comment]
Has this bug been fixed in Leaflet 1.0?
