### ISSUE TITLE
Map becomes blurry after moving the map because of CSS transitions (Chrome) (branch: master)

### ISSUE THREAD

**Issue by bb-generation** [Leaflet/Leaflet#2979]
If you open any leaflet example in the current master branch and move the map a little bit, everything which is in view again (after it was outside) will be blurry.
# Steps to reproduce:
1. Checkout current master branch
2. Open debug/map/map.html in Chrome
3. Zoom in a little bit, so that you can clearly read the brown text (below the coffee symbol)
4. Scroll to the right, so that this area will get out of view
5. Scroll to the left again to get the coffee shop back into view.
6. The text (and everything else) is now blurry.
# Example View

Before: ![clear view](http://i.imgur.com/AsZ2lgB.png)
After: ![blurry view](http://i.imgur.com/ln4AlBu.png)
(It's best to open these two images in two tabs and switch between them to see the difference)
# Browsers

**Affected browsers**:
- Chrome 38.0.2125.111 Windows 7
- Chrome 38.0.2125.111 Mac OS X 10.10

**Unaffected browsers**:
- Internet Explorer 11.0.9600.17358
- Mozilla Firefox 33.0.1
# Analysis:

A quick bisect shows that commit a33eff73f0d46b326d6fe59a7072f31624527c23 is the cause. It seems that the introduction of the CSS3 transitions caused this behavior in Google Chrome.

**Comment by vstyle** [comment]
I have the same problem using the leaflet 1.5.1 version, is it normal? Actually the demo is also blurry, here the screenshot: 

![image](https://user-images.githubusercontent.com/3931476/63330135-f4db2480-c33b-11e9-80d5-96a9aee234d8.png)

I am using Chrome Version 75.0.3770.100
