### ISSUE TITLE
Leaflet assumes zoom levels increase scale with a factor of two

### ISSUE THREAD

**Issue by perliedman** [Leaflet/Leaflet#2990]
In `Map`, I think I've found a remaining assumption about how the scales of zoom levels are configured: ([`Map.getScaleZoom`](https://github.com/Leaflet/Leaflet/blob/master/src/map/Map.js#L401)):

```javascript
return fromZoom + (Math.log(scale) / Math.LN2);
```

This works well as long as the zoom levels' scales grow by a factor of two for each zoom. For some (not too common) maps, this doesn't hold true.

I'm thinking it would make more sense to move this function to the CRS, where the scales are defined, and can know more about how calculate the scaling between two zooms; default would be to use the current implementation.

**Comment by Charlotteis** [comment]
To get started with this issue, courtesy of Iván Sánchez Ortega:

1. Read the CONTRIBUTING guide before you get started! -- https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md
2. The line of code you need to concern yourself with is here: https://github.com/Leaflet/Leaflet/blob/master/src/map/Map.js#L403
3. Try and write some unit tests to make sure your code works, unit tests belong here: https://github.com/Leaflet/Leaflet/blob/master/spec/suites/geo/CRSSpec.js

> "Make sure getScaleZoom (which is bad) behaves as the inverse of getZoomScale (which is good), and write a couple unit tests"

Ask here for help if you need it!

(I will be tweeting about this issue from @yourfirstpr, hopefully on Friday!)

**Comment by IvanSanchez** [comment]
A note for people coming from @yourfirstpr:

There should be a test to make sure that `getScaleZoom` and `getZoomScale` complement each other. In other words, something like:

```
toZoom = 10;
fromZoom = 5;
var scale = getScaleZoom(toZoom, fromZoom);
toZoom = getZoomScale(scale, fromZoom);
// Check that the value of toZoom hasn't changed
```

This has to work with arbitrary values, and CRSs other than the default one.
