### ISSUE TITLE
BoxZoom remains in bad state after initial use

### ISSUE THREAD

**Issue by brendan-ward** [Leaflet/Leaflet#3026]
```this._moved``` is set to true on first capture of mouse move event (https://github.com/Leaflet/Leaflet/blob/master/src/map/handler/Map.BoxZoom.js#L49)

however, it is not reset until the next ```mousedown``` event, which results in it being in a bad state.  Outside calls to its ```moved()``` function (e.g., [this fix](https://github.com/Leaflet/Leaflet/commit/aa8be5451361db6c5044116fe275e05c16336cce)) result in other click events on the map being blocked.

The fix should be as simple as adding 
```this._moved = false;``` toward the end of ```BoxZoom::_onMouseUp()``` function.

Happens on current version of master branch.

**Comment by balrog-kun** [comment]
Is anything preventing merging of this fix?  The problems is still present in master on firefox.

**Comment by yohanboniface** [comment]
> However it won't work for IE <9.

I think it's the "anything" your are asking for ;)

**Comment by mourner** [comment]
> Trying to track _moved state has been the source of a lot of bugs.

It's true that an alternative solution would be perfect, but since we didn't find a cross-browser approach to it, I'd try to fix the current boxZoom issue in a more trivial way.

**Comment by mourner** [comment]
Should be fixed by #3637
