### ISSUE TITLE
fitBounds problem in async initialize map

### ISSUE THREAD

**Issue by Trufi** [Leaflet/Leaflet#3031]
http://jsfiddle.net/7caou3e7/2/

If we asynchronously initialize map, add several rectangles to group and use `map.fitBounds` to `rectanaglesGroup.getBounds()`, map don't work fine.

This error occurs is not always. If everything ok, please click to `Run` in JsFiddle a couple of times.

Bug disappears if we wrap `fitBounds` in `setTimeout` http://jsfiddle.net/7caou3e7/4/

Chrome 38, Ubuntu 14.04 or MacOS
Firefox 33, Ubuntu

Sorry for my english =\

**Comment by powahftw** [comment]
I just encountered this bug while migrating from Promise to await/async 
Leaflet version: 1.6.0,

Snippet

Before
```Javascript
response.json().then((data) => {
  const a = data[`key1`];
  const b = data[`key2`];
  loadMap(a, b);
});
```

After
```Javascript
const data = await response.json();
const a = data[`key1`];
const b = data[`key2`];
loadMap(a, b);
```

Loadmap (Some omiss)
```Javascript
function loadMap(..., latLngs) {
 const mymap = L.map(`mapid`);
  L.tileLayer(...).addTo(mymap);

  const markers = [];
  latLngs.forEach((latLng) => {
    const marker = L.marker(latLng).addTo(mymap);
    markers.push(marker);
  });

  const group = L.featureGroup(markers);
  //mymap.fitBounds(group.getBounds().pad(0.5)) <- This doesn't work 
  setTimeout(() => mymap.fitBounds(group.getBounds().pad(0.5)));
}
```
