### ISSUE TITLE
Sometimes zooming a map will still block the map.

### ISSUE THREAD

**Issue by volkerrichert** [Leaflet/Leaflet#3040]
Under some "special" (yet unknown) circumstances the map still blocks zooming and panning. At this point  _onZoomTransitionEnd wasn't called and the map ist still in animation mode.

You can reproduce it using the public site: 

http://www.miele.hk/domestic/find-a-dealer-384.htm

- put "Causeway Bay, Hong Kong" in "Your location"
- select "Foor Care" als product range
- you will see no result, which is ok.
- zoom out 2 times
- map stops working 

this._animatingZoom is still true.
class "leaflet-zoom-anim" is still a class of the map.

Normally zoom works fine.

leafletjs 0.7.3. is part of http://www.miele.hk/media/common/js/libs/dealersearch_leaflet.js
the changes from https://github.com/Leaflet/Leaflet/commit/9a2399ee500cfa24efd320e44c68ebf1c4109d78 are inserted manually at the moment for testing. 

Volker

**Comment by mourner** [comment]
Closing until there's a reproducible minimal test case.
