### ISSUE TITLE
Mouseover fires continuously when layer.bringToFront() is called in IE

### ISSUE THREAD

**Issue by kerryarts** [Leaflet/Leaflet#3042]
If `bringToFront()` is called on layer mouseover, the DOM manipulation of `bringToFront()` will trigger another mouseover, which will call `bringToFront()` again, which will trigger another mouseover...etc.

This is not a leaflet bug, rather the specific implementation of mouseover by Internet Explorer (all versions).

The same issue occurs in [Raphael js](https://github.com/DmitryBaranovskiy/raphael/issues/225)

**Comment by Lambdac0re** [comment]
Well that is horrible...

**Comment by re3lex** [comment]
this is reproducible in IE11 as well
