### ISSUE TITLE
add `openOnClick` option for popups

### ISSUE THREAD

**Issue by maackle** [Leaflet/Leaflet#3058]
Popup options have a `closeOnClick` option to override the default behavior when using `bindPopup`. In my use case I need more control over marker popups and want all the benefits of `bindPopup` (move and remove events on the marker, `openPopup`, `closePopup`, etc) EXCEPT for the `click` event. I see no easy way to do this. I can `.removeEventHandler('click')` but in the way I'm using it, it's tricky to make it not remove my own click handler.

I propose there should also be a `openOnClick` option, defaulting to true, to disable the default click event. I'm going to attempt a pull request for this, but let me know if there's any other better way to handle this.

**Comment by yohanboniface** [comment]
See https://github.com/Leaflet/Leaflet/pull/3059#issuecomment-204728004
