### ISSUE TITLE
Documentation Suggestion: coordstoLatLng

### ISSUE THREAD

**Issue by hrishiballal** [Leaflet/Leaflet#3061]
A example show how coordstoLatLng should be used would be great. I am utterly confused about how to use it. I want to convert Geojson to polygon object. 

Currently the documentation lacks any code about it.

**Comment by mourner** [comment]
Tracked in #3098

**Comment by abettermap** [comment]
> You can see how it is used in the [Leaflet core](https://github.com/Leaflet/Leaflet/blob/master/src/layer/GeoJSON.js#L120).

Here's a correct [permalink](https://github.com/Leaflet/Leaflet/blob/f8e09f993292579a1af88261c9b461730f22e4e6/src/layer/GeoJSON.js#L196-L204) to what I think is the correct section.
