### ISSUE TITLE
Can't switch back if overlay layer was removed

### ISSUE THREAD

**Issue by HarelM** [Leaflet/Leaflet#3064]
Here is the scenario I want to do:
create two base layer maps.
allow only one map to have an overlay.
expected results: when clicking on the second map the overlay checkbox will appear, when clicking on the first map the overlay checkbox will disappear.
actual results: clicking on the second map the checkbox appear, but from this point on you can't switch back to the first map.

below is the code I tried to use:
in order to achieve this I'm listening to the baselayerchange with the following function:
<code>
    var layerSwitcher = new L.Control.Layers({
      'Map1': map1, 
      'Map2': map2
    });
    map.addControl(layerSwitcher);
    map.on('baselayerchange',function(e) {
      if(e.name == 'Map2') {
        layerSwitcher.addOverlay(overlay, 'Overlay');
       } else {
        layerSwitcher.removeLayer(overlay);
      }
    });
</code>

**Comment by mourner** [comment]
OK, so it's fixed in master, right?
