### ISSUE TITLE
Geojson layer is not visible in Internet Explorer though work fine with Chrome

### ISSUE THREAD

**Issue by Vikash-Mehta** [Leaflet/Leaflet#3068]
![chrome](https://cloud.githubusercontent.com/assets/6582757/5234227/f7150904-77e2-11e4-8a0f-e18c7b4ba9db.png)
![ie 11](https://cloud.githubusercontent.com/assets/6582757/5234229/0043056c-77e3-11e4-85e8-bbdfb3485ea6.png)

**Comment by mdulin** [comment]
Ever solve this issue? i'm having the same issue. geojson layers (specifically polygons) won't show up in my leaflet app in IE. works great in FF and Chrome though.

**Comment by mourner** [comment]
@mdulin can you answer to the questions above?

**Comment by mdulin** [comment]
JSFiddle Link here. 
http://jsfiddle.net/cu1c7Lgf/

**Comment by mdulin** [comment]
switched event to "viewreset" and showLayerWhen to zoomVal and IE handled it. 
--------------------------------------------------------------------------------------------------------------------------------
map.on('viewreset', function(){
  var zoomVal = map.getZoom();
  //console.log('viewreset')
  
  zoomVal <= 10 ? map.addLayer(mrrp_site_points_lyr) : map.removeLayer(mrrp_site_points_lyr);
  zoomVal <= 10 ? map.removeLayer(mrrp_site_area_lyr) : map.addLayer(mrrp_site_area_lyr);
  zoomVal <=8 ? map.removeLayer(RM_10mi_lyr) : map.addLayer(RM_10mi_lyr);
  zoomVal <=13 ? map.removeLayer(RM_1mi_lyr) : map.addLayer(RM_1mi_lyr);

  //showLayerWhen(1,mrrp_site_points_lyr, zoomVal <= 10);
  //showLayerWhen(2,mrrp_site_area_lyr, zoomVal >10);
  //showLayerWhen(3,RM_10mi_lyr, (zoomVal  > 8 && zoomVal < 13));
  //showLayerWhen(4,RM_1mi_lyr, zoomVal >12);

**Comment by IvanSanchez** [comment]
Is this still an issue?

**Comment by mourner** [comment]
Probably not. At least in master. Also noticed it uses L_PREFER_CANVAS.
