### ISSUE TITLE
Check all in Control.Layers

### ISSUE THREAD

**Issue by sellonen** [Leaflet/Leaflet#3071]
I need a 'check all overlays' functionality in the Control.Layers.

A natural position for the checkbox would be between base layers and overlay layers. However, I cannot add an input element there because L.Control._onInputClick loops through each input element and expects them to have a layer associated with it.

https://github.com/Leaflet/Leaflet/blob/master/src/control/Control.Layers.js#L203

Could the variable 'inputs' in the function _onInputClick() be changed to include only inputs of class 'leaflet-control-layers-selector', like this

    var inputs = this._form.getElementsByClassName("leaflet-control-layers-selector")

best
Sakari

**Comment by IvanSanchez** [comment]
Given that there are already [several layer switching plugins](http://leafletjs.com/plugins.html#layer-switching-controls), either this is solved by one of those, or a new plugin can be develop for this - so not a needed core feature.
