### ISSUE TITLE
L.Canvas : bad performance in removing layers

### ISSUE THREAD

**Issue by lapinos03** [Leaflet/Leaflet#3076]
As I'm doing some performance analysis through canvas and svg rendering (with thousands of geometries), I discovered in L.Canvas._draw that to-be-removed layers were updated (means computed/redrawn) just before being removed ! 

	_draw: function (clear) {
		this._clear = clear;
		var layer;

		for (var id in this._layers) {
			layer = this._layers[id];
			if (!this._redrawBounds || layer._pxBounds.intersects(this._redrawBounds)) {
				layer._updatePath();
			}
			if (clear && layer._removed) {
				delete layer._removed;
				delete this._layers[id];
			}
		}
	},

So I changed this like so : 

	_draw: function (clear) {
		this._clear = clear;
		var layer;
	
		for (var id in this._layers) {
			layer = this._layers[id];
	//		if(0) { // original
	//			if (!this._redrawBounds || layer._pxBounds.intersects(this._redrawBounds)) {
	//				layer._updatePath();
	//			}
	//			if (clear && layer._removed) {
	//				delete layer._removed;
	//				delete this._layers[id];
	//			}
	//		} else 
			{ // lapinos03 : erase ELSE redraw
				if (clear && layer._removed) {
					delete layer._removed;
					delete this._layers[id];
				} else
				if (!this._redrawBounds || layer._pxBounds.intersects(this._redrawBounds)) {
					layer._updatePath();
				}
			}
		}
	},

Far much better !

**Comment by mourner** [comment]
@wpf500 this would be an easy thing to grab if you're working on Canvas rendering :)

**Comment by mourner** [comment]
@lapinos03 note that your proposed fix introduced a regression so I had to revert: https://github.com/Leaflet/Leaflet/issues/3661
