### ISSUE TITLE
L.GridLayer (new logic with _levels) : pb with _level.origin

### ISSUE THREAD

**Issue by lapinos03** [Leaflet/Leaflet#3077]
As I render geometries in canvases as tiles, I noticed that the geom was shifted inside the tiles after the map was panned. The more the panning, the more the shifting. This happens when panning the map and then zoomin in/out to a previous level that has already been created. (In my code, I use the tilePos to shift the origin of the canvases by a ```ctx.translate()``` )

First, I changed the functions 
```
	_setZoomTransform: function (level, center, zoom) {
		var scale = this._map.getZoomScale(zoom, level.zoom),
	    	//translate = level.origin.multiplyBy(scale).subtract(this._map._getNewPixelOrigin(center, zoom)).round();
	    	translate = this._map.getPixelOrigin().multiplyBy(scale).subtract(this._map._getNewPixelOrigin(center, zoom)).round();
		
		L.DomUtil.setTransform(level.el, translate, scale);
	},
```
and
```
	_getTilePos: function (coords) {
		//return coords.multiplyBy(this._tileSize).subtract(this._level.origin);
		return coords.multiplyBy(this._tileSize).subtract(this._map.getPixelOrigin());
	},
```
...by replacing ```_level.origin``` by ```_map.getPixelOrigin()```, which solved my problem.
But finally I changed only the function
```
	_updateLevels: function () {
		var zoom = this._tileZoom;

		for (var z in this._levels) {
			this._levels[z].el.style.zIndex = -Math.abs(zoom - z);
		}

		var level = this._levels[zoom],
		    map = this._map;

		if (!level) {
			level = this._levels[zoom] = {};

			level.el = L.DomUtil.create('div', 'leaflet-tile-container leaflet-zoom-animated', this._container);
			level.el.style.zIndex = 0;

			//level.origin = map.project(map.unproject(map.getPixelOrigin()), zoom).round();
			level.zoom = zoom;
		}
		level.origin = map.project(map.unproject(map.getPixelOrigin()), zoom).round();

		this._level = level;

		return level;
	},
``` 
where ```_level.origin``` is moved outside the ```if(!level) {...}``` body, so that it is updated every time the zoom is changed. ...which solves also my problem.

Am I right ?

**Comment by yohanboniface** [comment]
Can you set up a jsfiddle with latest master to demonstrate the issue? http://playground-leaflet.rhcloud.com/ may help.

**Comment by IvanSanchez** [comment]
No more information has been provided, and more than a few weeks have passed. We'll assume this issue is no longer relevant and/or there is no interest to make a better report.
