### ISSUE TITLE
Possible Marker Dragging Bug on IE

### ISSUE THREAD

**Issue by jnswider** [Leaflet/Leaflet#3082]
Hi there, 

In Chrome, initializing a marker with draggable = true, then disabling dragging on mousedown, causes the marker to be undraggable (as expected) when you try and drag the marker. In IE10 (and other IEs I think), the marker is still draggable on the first mousedown event. 
Here's a JSFiddle to illustrate the issue:
http://jsfiddle.net/jnswider/71dhve9e/1/

To reproduce:
- Open JSFiddle with IE10
- Try dragging the marker

In Chrome, the first time you try dragging the marker, it is already undraggable.
In IE10, the first time you try dragging the marker it actually drags when in my opinion the expected result is for the marker to not drag. 

Any feedback is appreciated, thanks!

**Comment by jnswider** [comment]
Any other insight on this issue? 
I'm noticing that I'm still having issues disabling dragging in IE. I call marker.dragging.disable() and the marker stops getting it's drag event but the marker itself will still move.
Thanks! :)

**Comment by mourner** [comment]
Does the same happen on the 1.0-dev version?

**Comment by Eschon** [comment]
I tried this with 1.0-dev and now the marker just stays draggable even in Safari and Chrome. [Here's](http://jsfiddle.net/Eschon/zb6vbwku/) the updated fiddle.
