### ISSUE TITLE
Option to modify map state via the API without triggering any events

### ISSUE THREAD

**Issue by day-me-an** [Leaflet/Leaflet#3088]
This is similar to #1686.

I'd like to be able to do something like:

```
map.fitBounds(myBounds, {muted: true});
```

and it not trigger any events. This is similar to http://amsul.ca/pickadate.js/api.htm#muted-callbacks

It seems quite important to be able to distinguish between programmatic and user initiated changes to map state, but no map library seems to have this feature.

**Comment by ghybs** [comment]
Closing as duplicate of #2934
