### ISSUE TITLE
Set max bounds problem

### ISSUE THREAD

**Issue by eMarek** [Leaflet/Leaflet#3092]
Hi guys!
Does anyone has problem with `map.setMaxBounds` in Leaflet 0.7.3?
I am changing image overlay in my app. Basically there is a list of images outside the leaflet and user can select which image will be shown in leaflet. After image is changed, I have to correct bounds with `map.setMaxBounds`. When I do this, the leaflet is behaving somehow weird. At first the bounds are corrected ok. If I try to pan the image, it just stays where I stop panning. If I try to pan again, than image first jumps to the middle and than the panning is made as usual.
Any idea?

Here is the code:
```js
            // calculate the edges of the image, in coordinate space
            var southWest = this.map.unproject([0, mapImgHeight], 1);
            var northEast = this.map.unproject([mapImgWidth, 0], 1);
            this.bounds = new L.LatLngBounds(southWest, northEast);

            // remove previous house image
            this.map.removeLayer(this.imageOverlay);

            // tell leaflet that the map is exactly as big as the image
            this.map.setMaxBounds(this.bounds);
            
            // correct image overlay, so that it covers the entire map
            this.imageOverlay = new L.ImageOverlay(img.src, this.bounds);

            // add selected house image
            this.map.addLayer(this.imageOverlay);
            this.imageOverlay.bringToBack();
```

**Comment by Starefossen** [comment]
Hi @eMarek, could you create a [jsfiddle](http://jsfiddle.net/) to help the developers replicate this bug?
