### ISSUE TITLE
Disabling touch prevents click drag on Windows

### ISSUE THREAD

**Issue by ljbade** [Leaflet/Leaflet#3094]
I have a new HP Windows 8.1 laptop with a touch screen + normal trackpad.

When touch events are disabled to prevent a trap e.g. https://www.mapbox.com/blog/runkeeper-million-routes/

I observe this behavior:
* IE 11: Click drag works, and so does touch drag creating a trap
* Chrome: Neither click drag or touch drag works and it still creates a touch drag trap (touch drag does not scroll the page when inside the map)

**Comment by mourner** [comment]
Can be closed, right?
