### ISSUE TITLE
maxNativeZoom broken (includes solution)

### ISSUE THREAD

**Issue by louisptremblay** [Leaflet/Leaflet#3096]
Hi!

With the master branch, the maxNativeZoom option doesn't seem to work and if you zoom past its value, no tiles load.

Easy to reproduce, simply zoom in on this example:
http://jsfiddle.net/louisptremblay/LpqnuwkL/

To fix it, change:
https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/TileLayer.js#L107
From:
Math.round(map.getZoomScale(zoomN, zoom) * options.tileSize) :
To:
Math.round(options.tileSize / map.getZoomScale(zoomN, zoom)) :

As a side note, in JSFiddle, I linked to the latest master leaflet-src.js, but I had to download the zip, unzip and reupload to my CDN, could be nice to put the whole "dist" folder unzipped on the leaflet CDN so we can link more easily to the dev version!

Thank you!

**Comment by olivierdalang** [comment]
Hi,

Not sure if related (probably not), but maxNativeZoom already had problems under 0.7.3 when the tilelayer defines bounds, so this could be fixed at the same time.

Try zooming in this (with the first options, then with the second options) :
http://jsfiddle.net/cxZRM/143/

**Comment by chrskrchr** [comment]
Louis,
Thanks for the workaround!  I had to make one minor tweak and switch this:
```
zoom = map.getZoom() + options.zoomOffset,
```
To this:
```
zoom = this._tileZoom + options.zoomOffset,
```

The zoom level returned by map.getZoom() was returning the map's _previous_ zoom level, and not the zoom level for which tiles were about to be fetched.

**Comment by DS-Vocology** [comment]
great thanks!

**Comment by louisptremblay** [comment]
great thanks!

**Comment by DS-Vocology** [comment]
What is this?
