### ISSUE TITLE
Website API documentation innacurate

### ISSUE THREAD

**Issue by chriserickson** [Leaflet/Leaflet#3111]
The website API documentation states that I can call `map.AddLayer(layer, true) ` to have the layer inserted at the bottom. The second argument `insertAtBottom?` that is mentioned in the API docs is not supported.

The website API docs should be updated to reflect the correct usage.

**Comment by Starefossen** [comment]
Nice catch @chriserickson! This option was removed quite some time ago in [this commit](https://github.com/Leaflet/Leaflet/commit/cdfaad994f277a2eb90bcf4499c86786a6aa707f). This was removed for more fine grained control functions such as [layer.bringToFront()](http://leafletjs.com/reference.html#tilelayer-bringtofront), [layer.bringToBack()](http://leafletjs.com/reference.html#tilelayer-bringtoback), and [layer.setZIndex()](http://leafletjs.com/reference.html#tilelayer-setzindex).

I'll create a pull request to remove the reference to this option in the documentation.

**Comment by perliedman** [comment]
Closed by #3170.
