### ISSUE TITLE
Error when attempting to interact with an empty map

### ISSUE THREAD

**Issue by initram** [Leaflet/Leaflet#3116]
In the function L.Draggable._onMove the startPos is calculated based on the position of an element that is not always initialized. like this: 

```
this._startPos = L.DomUtil.getPosition(this._element).subtract(offset);
```

I am unsure of when L.DomUtil.getPosition(this._element) returns undefined, but we see this error logged a few times a week on our site. It may be a timing issue where the the map is being moved before it is fully initialized.

If you then move the map again afterwards the followong line will also break:
   this._newPos = this._startPos.add(offset);

This is because the startPos is not initialized while _moved have been set to true. 

If you need more information, please let me know.

**Comment by mourner** [comment]
Interesting. It would be nice to figure out the exact use case where this is happening and set up a minimal JSFiddle.

**Comment by initram** [comment]
I found the issue with our site. We had call to a service to that would translate IP to location, that was used to set the center of our map. This service have been slow recently and if you start moving the map before the center is set, you will get the problem mentioned above.

Here is a jsfiddle where the center is not set for the map: http://jsfiddle.net/umwo0rn1/
If you try to move the map you will get exceptions when it tries to call "subtract" and "add". I still think this should be handled better by leaflet, so that we at least get a better error message in this case.

**Comment by Falke-Design** [comment]
With Leaflet 1.7.1 we throw an error with a clear meassage:
![grafik](https://user-images.githubusercontent.com/19800037/144109523-f17cd9d9-88ed-4c0a-aaf7-0e3417af7c83.png)

If you don't want to get this error you can set a default center while creating the map.
