### ISSUE TITLE
GeoJson SVG

### ISSUE THREAD

**Issue by domialex** [Leaflet/Leaflet#3119]
I noticed that Leaflet only renders geojson svg that is visible instead of preloading all the data.
Is there a way to preload everything so that the svg is visible while panning instead of on 'moveend' only?

**Comment by domialex** [comment]
L.Path.CLIP_PADDING seems to do the job.

**Comment by mourner** [comment]
Yeah, although note that it affects performance if you overlay large amounts of data.

**Comment by domialex** [comment]
Makes sense.
