### ISSUE TITLE
Precision with concentric circle

### ISSUE THREAD

**Issue by laurentClave** [Leaflet/Leaflet#3120]
I have concentric circles with the same radius that do not appear in the same position with different zoom

ZOOM 2 : The circles do not have the same center
![1](https://cloud.githubusercontent.com/assets/7510673/5678034/3d603d72-97ee-11e4-9d73-f76f922fcb90.jpg)

ZOOM 1 : The circles are concentric
![2](https://cloud.githubusercontent.com/assets/7510673/5678036/42609ea2-97ee-11e4-9033-873cd9bc9745.jpg)

**Comment by mourner** [comment]
Is this a Leaflet problem? What do you draw the concentric circles with? Can you make a minimal JSFiddle?

**Comment by laurentClave** [comment]
sorry, i thing the problem is Semi Circle API https://github.com/jieter/Leaflet-semicircle/issues/4
