### ISSUE TITLE
ETA for 1.0?

### ISSUE THREAD

**Issue by bjorm** [Leaflet/Leaflet#3122]
I would like to re-post my question from [Leaflet Google group](https://groups.google.com/forum/#!topic/leaflet-js/L7tYSYL1lPI), since I am unsure where to ask:

>We are currently considering to switch from Leaflet to OpenLayers because it allows us to abitrarily stack vector and tiles layers. Unfortunately OpenLayers does not offer an SVG renderer, which will cause us some extra effort in order to migrate. 
>
>Recently I stumbled upon PR #2786 ("Pane management: huge refactoring and rewrite") which is due for 1.0 and would help us a lot with regard to layering.
>
>Since we have no other big issues with Leaflet expect the layering and the move to OpenLayers ~~looks like~~ is a big thing, I would be very interested to know when to expect 1.0.

Thanks a lot.

**Comment by mourner** [comment]
Hi Bjorn, 1.0 was delayed but the first beta is due this month. I don't recommend migrating to OL if you don't want to spend a huge migration effort only to discover that you no longer need to do it. :)

**Comment by mourner** [comment]
Discussion here #3124
