### ISSUE TITLE
Make sure we didn't regress performance / smoothness with new tile loading logic

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#3123]
I'm still worried that the new way to load tiles (after #2382) can affect performance considerably in some cases, although there was no other way to be able implement `flyTo`. We need to find a way to measure the map browsing experience compared to the old way, and optimize if necessary. cc @jfirebaugh 

Also known glitch to fix: #3053

**Comment by Jakobud** [comment]
How could we measure this to compare? FPS or something?

**Comment by mourner** [comment]
Much better now.
