### ISSUE TITLE
Leaflet 1.0-beta1 release effort

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#3124]
Hey guys @jfirebaugh @danzel @jacobtoye @patrickarlt @perliedman @snkashis @tmcw @Jakobud @yohanboniface 

I'm going to return to focused Leaflet work to finally wrap up 1.0. It has been delayed too much already, we just have to crack it down now — it's so close!

Most remaining issues for a solid beta release are captured in the milestone: https://github.com/Leaflet/Leaflet/milestones/1.0-beta1. It seems pretty doable to make an awesome release this month with some focus. :) Feel free to suggest postponing anything or including other issues that I missed.

In terms of finalizing API, the most important issue is deciding the right pane management approach — see discussion at #2786. In terms of user experience, my biggest worry is new tile loading logic #3123. All other tasks are relatively straightforward.

I'd also like to make discussions / coordination around it easier — in addition to GitHub issues, what do you think about using Gitter for quick chats? Gitter got pretty nice since the first time I saw it: https://gitter.im/Leaflet/Leaflet

Any help is highly appreciated — not only code, but also feedback. 

Thanks for all your awesome work on this!

**Comment by Jakobud** [comment]
I am up to help out with anything I can. I'm excited to see a 1.0 release sometime in the near future.

**Comment by danzel** [comment]
Woo. I'll work with kerry on the IE8 one this week. I'm pretty busy but bump me on any you want me to look at.

**Comment by patrickarlt** [comment]
I'll keep up on the Documentation checklist https://github.com/Leaflet/Leaflet/issues/3098 if everyone can keep dumping things there.

If anyone could review the work I've done so far in

* #3097 - class and layer reorganization
* #3101 - first pass at vector refactor
* #3107 - needs refactoring after #3097 gets merged because the layer methods (but not the class have moved)

so they could get merged I would be grateful.

**Comment by hastebrot** [comment]
Maybe we could consider naming the release "1.0-beta.1" (with a dot in the pre-release part) to match Semantic Versioning (http://semver.org/spec/v2.0.0.html).

**Comment by mourner** [comment]
11 issues left in the milestone https://github.com/Leaflet/Leaflet/milestones/1.0-beta1, lets track everything in individual tickets

**Comment by stuartpb** [comment]
@hastebrot @mourner The correct Semantic Versioning version would be "1.0.0-beta.1", not "1.0-beta.1".

**Comment by mourner** [comment]
Yes, I'll conform to the semantic. `1.0.0-beta.1`

**Comment by bfishman** [comment]
Very excited for 1.0.0-beta.1!
