### ISSUE TITLE
Cannot add the same layer to multiple maps

### ISSUE THREAD

**Issue by rwwagner90** [Leaflet/Leaflet#3125]
I am using Leaflet.draw to draw shapes on my maps. I have two maps, one large main map, and one small filter map. I need to sync the shapes between them, so I have been using the draw events and copying the layer to the other map, but once the layer is copied, the old layer seems to be messed up. It would appear Leaflet does not support having the same layer in multiple maps. If I switch it from a layer to geoJson instead, it somewhat works.

**Comment by mourner** [comment]
Yes, unfortunately making Leaflet support adding the same layer instance to multiple maps would require too much complexity in the code. So it's not worth the hassle, especially as there are workarounds for cases that need this.

**Comment by jieter** [comment]
Note the function I wrote for minimal control: https://github.com/jieter/Leaflet.layerscontrol-minimap/blob/gh-pages/L.Control.Layers.Minimap.js#L11

**Comment by rwwagner90** [comment]
Thanks @mourner. Now that I know there is no way to support it, I will work on a workaround. I will try out @jieter 's solution.

**Comment by jieter** [comment]
Factored out that function to a npm module: https://github.com/jieter/leaflet-clonelayer
