### ISSUE TITLE
retain parent tiles when child tiles are 404s

### ISSUE THREAD

**Issue by answerquest** [Leaflet/Leaflet#3127]
![leaflet tile disappearing issue](https://cloud.githubusercontent.com/assets/9089552/5691122/6977d6d2-98dd-11e4-8d04-cb9228c5101c.jpg)

[Please see screenshot attached]
This issue crops up especially when using custom tilesets that are at different levels of depth for different locations, as well as when the internet connection is down or slow or the server is busy.
Suppose the available tiles for one area on the map stop at zoom level 8. When a user zooms in from 8 to 9, the 8-level tiles rescale, blur and remain while the transition animation is happening, but then vanish, without waiting for the next tiles to replace them.

Contrast this with openstreetmap.org default behaviour : tiles from the previous state stay, enlarged, as long as the newer tiles don't load. That make sense. In case the next level's tiles aren't available, the previous tiles stay there indefinitely. Same case happens when zooming out : Previous level's tiles shrink and remain in place as long as new tiles aren't fully loaded.This prevents the map from going blank. I guess this is standard across googlemaps, osm, etc.

So I don't get why leaflet.js is getting rid of previous tiles without bothering to wait for next level to load? The rescaling is happening properly, as witnessed during transition. If performance/memory is a concern, then please set an option to toggle, similar to http://leafletjs.com/reference.html#tilelayer-unloadinvisibletiles

Where the new zoom level's tiles aren't available at all and the server/browser returns an error (which I'm guessing can be caught and handled), leaflet should keep the previous (or closest) level's tile in place indefinitely; and not blank that space out or error-tile it.

The "maxNativeZoom" option doesn't fix this situation as it applies universally and prevents deeper zoom level tiles for specific locations from being displayed even if they are available. In the use case I'm working on, most regions' tiles are available only till a few top levels, but in certain locations like a city the deeper level tiles are available. 

Please make leaflet.js behaviour more like OSM in this case, so the map browsing experience is kept seamless and so users don't suddenly get blank screens / error-tiles when they zoom in (or out) a little.

**Comment by mourner** [comment]
While I'll answer with a more detailed response later, just wanted to quickly comment that OSM.org uses Leaflet, so your comparison with OSM having something that Leaflet doesn't is very confusing.

**Comment by answerquest** [comment]
Ok.. noted. So this is happening in those tilesets where not all tiles are available at certain levels of zoom. Typical case : City > depth till 15; Countryside : depth till 10.  This becomes a feature request, then : At times when the "error-Tile" would be displayed, please introduce an option/flag/toggle for just displaying the scaled version of whichever is the nearest tile available at that location, at a lower zoom (meaning higher altidude..) level. So rather than the error-tile, user sees a blurred enlarged tile. A variable, location-dependent maxNativeZoom, if you will. In case there is no tile available all the way to the top, then just display the error tile.
With an error-tile specified, this is how it currently looks when there are tiles available at one location and not at another:
![screenshot22](https://cloud.githubusercontent.com/assets/9089552/5691560/7121cfae-98f2-11e4-82c2-d671e6c1bac7.jpg)

And this is how we want it to look, hopefully with some "show-nearest-available" option set:
![partialtiles](https://cloud.githubusercontent.com/assets/9089552/5691562/dfb7a376-98f2-11e4-8d04-63e8ad48fa71.jpg)

Apologies for not having consistent base layers in screenshots.. but you get the idea, right?

**Comment by jfirebaugh** [comment]
Note that this feature wouldn't work as you expect for the tile source in your screenshot, which is always returning images -- it just happens that instead of satellite imagery, some of them are the "Sorry, more data is not available..." placeholder image. From Leaflet's perspective, this is just as valid an image as any other tile.

For tile sources that actually return 404s rather than a placeholder image, this might work, but in my experience the placeholder approach is much more common.

**Comment by answerquest** [comment]
"For tile sources that actually return 404s rather than a placeholder image, this might work"
>> Yes so please do this for those cases.

**Comment by mourner** [comment]
Those cases are extremely rare in practice so very low priority.

**Comment by answerquest** [comment]
I'll wait :P

**Comment by ghybs** [comment]
Hi,

Just to let you know that this use case is probably quite uncommon indeed, but still applicable to a few applications. E.g. for pre-rendered tile sets where only some areas were prepared up to highest zoom levels.

See for example this post on SO:
[Mapbox.js - Fallback tile image from lower zoom level, when missing in requested zoom level](http://stackoverflow.com/questions/20705754/mapbox-js-fallback-tile-image-from-lower-zoom-level-when-missing-in-requested)

The desired behaviour as described here above is really not difficult to implement, I will try to turn my workaround into a plugin. It is mainly based on this:
[Elegant overlapping with photographic layers in Leaflet](http://makina-corpus.com/blog/metier/2013/elegant-overlapping-with-photographic-layers-in-leaflet)

**Comment by ghybs** [comment]
Here you go: https://github.com/ghybs/Leaflet.TileLayer.Fallback

**Comment by mourner** [comment]
Nice! Please submit to the plugin list.

**Comment by hrj** [comment]
While the fallback plugin by @ghybs addresses the missing tile problem, another common problem still remains: slow connection speed.

While the images are being fetched on a slow connection, only grey tiles are visible. Is there a solution for this? Thanks!

**Comment by perliedman** [comment]
@hrj not sure what you need that isn't already there: if I set Chrome to throttle network traffic to GPRS and zoom in, Leaflet uses the blurry, stretched images until the new tiles have loaded, like I would expect.

Is there anything else you need?

**Comment by perliedman** [comment]
Also, closing this. As far as I can tell @ghybs's plugin is a perfect solution for the (not so common) problem.

Of course, just tell me if this is still a valid, actionable issue and I'll re-open.

**Comment by hrj** [comment]
@perliedman Thanks for looking. Indeed, when I see examples from leafletjs, everthing works fine. For example, [this page](http://leafletjs.com/examples/quick-start/example.html) with throttled network works fine.

But if I create a custom layer like this:

```
L.TileLayer.FLIF = L.TileLayer.extend({
  createTile: function (coords, done) {
    var tile = document.createElement('div');
    tile.setAttribute("style", "color: red;background:yellow; box-shadow: inset 0 0 0 10px rgba(0, 255, 0, 0.5)");
    tile.innerHTML = "<p style='margin-bottom:50px'>Tile " + coords.x + ", " + coords.y + ", level: " + coords.z + "</p>";
    setTimeout(function() { done(null, tile); }, 1000);
    return tile;
  }
});
```

then I see a grey image for 1 second (because of the timeout) when I zoom into the next level. (For debugging, there is no network involved here; the delay is being created by the setTimeout).

If I use a GridLayer, then this problem doesn't happen. (But I will have to rework the co-ordinates and some other behaviour is different with GridLayer).

**Comment by hrj** [comment]
> If I use a GridLayer, then this problem doesn't happen. (But I will have to rework the co-ordinates and some other behaviour is different with GridLayer).

Ok, I managed to use `GridLayer` without much changes, and things work fine now!

---
For the benefit of other users that hit a similar problem:
The documentation says `TileLayer` is only to be used for `img` elements, while I was using it with `div` elements. (I didn't see any JS code to handle `img` and assumed it would be fine. Now I realize that the *CSS* has special rules for `img` element).

So it's best to follow documentation. Sorry for the noise.
