### ISSUE TITLE
Polygons not drawing during animated panning or mouse-drag events

### ISSUE THREAD

**Issue by stephenmartindale** [Leaflet/Leaflet#3128]
During the panning deceleration animation or a mouse-drag event (between drag-start and mouse-up) primitives such as Polygons are not redrawn, creating a very poor user experience. To see this, zoom in on a polygon so that it extends out of the visible bounds and drag.

This is even worse because part of the stroke of the polygon *is* drawn where the old visible-bounds ended before the pan. See below:

![image](https://cloud.githubusercontent.com/assets/6370145/5705209/6a54a272-9a6f-11e4-95c3-676f774a5ea5.png)

(That polygon on the example page doesn't end where its right-hand edge is drawn in the above screenshot.)

This is an easy one to reproduce because you can see it on the Quick-Start example: http://leafletjs.com/examples/quick-start-example.html

**Comment by mourner** [comment]
This is done by design for performance reasons. See CLIP_PADDING in the docs. You can make it clip further off the screen to reduce the effects.

**Comment by stephenmartindale** [comment]
Ok. I have read the docs. There doesn't seem to be any way to change that value, however.

Searching for CLIP_PADDING, I also found this issue: https://github.com/Leaflet/Leaflet/issues/2814 in which the same question was raised and also unanswered. There was no resolution on how to change that value without forking the whole code-base and editing the constant.

**Comment by stephenmartindale** [comment]
Nevermind. I found the solution was to set `L.Path.CLIP_PADDING = 0.75;' or something like that.
It's obtuse but it works.
