### ISSUE TITLE
Drop single-statement brackets in code style?

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#3130]
For quite some time, I've dropped the requirement to wrap everything after `if`/`for`/`while` in brackets in my other libraries and see no strong reasons to adhere to the old conventional wisdom in Leaflet as well.

It's not that we need to convert to non-bracketed single statements everywhere, but in a lot of places, it actually helps code readability, while I never experienced the trap that was the original cause of the "always require brackets" rule by Crockford. 

Opinions?

**Comment by perliedman** [comment]
Personally, I think it's fine, and can improve readability, as long as the whole statement is on one line. For example:

```
if (foo) bar();
```

but I'm not so fond of:

```
if (foo)
    bar();
```

It's of course mostly a matter of opinion. I used to hate indenting with tabs, but after working with Leaflet for a while, I don't think about it any more :smile:.

**Comment by mourner** [comment]
Yes, I'm not using the second type notation either. So we can limit the rule to one-line statements.

**Comment by jfirebaugh** [comment]
I never experienced the trap either, so this comes down to a matter of preference -- whatever you prefer is fine.

**Comment by danzel** [comment]
:+1: Paint the shed :)

**Comment by Starefossen** [comment]
I assume brackets will be inserted automatically when the code is minified?

**Comment by mourner** [comment]
@Starefossen on the contrary, brackets are removed on the minification step. It's a matter of code maintenance.

**Comment by Starefossen** [comment]
I see. As a side note, this is what the [Airbnb JavaScript Style Guide() {](https://github.com/airbnb/javascript#blocks) says about blocks:

```js
// bad
if (test)
  return false;

// good
if (test) return false;

// good
if (test) {
  return false;
}

// bad
function() { return false; }

// good
function() {
  return false;
}
```

**Comment by daverayment** [comment]
I'm a fan of always including braces, just in case you get tricked by the indentation level of your code. Apple's GotoFail bug is an infamous example of when an incorrect indentation level can trick even the most experienced of coders, e.g.

    if (test)
        doThings();

Gets added to over time and is changed to

    if (test)
        doThings();
        doOtherThings();
    ...

and `doOtherThings` gets called whatever the value of `test` is.

I don't believe removing braces aids readability, is faster or more efficient so I'd keep them. They'll get minified away when they're not required, so let automated tools take care of the inessential ones ;) I also think it aids beginners to see rules like this applied consistently.

**Comment by mourner** [comment]
@daverayment this trap can only happen if you allow the statement to go on new line. If you write like this: `if (test) doThings();`, it's unlikely to happen.

In my experience, removing braces aids readability in some cases where it makes the code easier to skim.

But you bring an excellent point of it aiding beginners. Leaflet gets contributions from people of all experience levels, so it's probably not worth changing the conventions. And after switching to ESLint, we'll have a more strict test script to aid in making pull request in line with conventions.
