### ISSUE TITLE
"leaflet-touching" and "leaflet-zoom-anim" classes should be added while pinch-zooming

### ISSUE THREAD

**Issue by xwipeoutx** [Leaflet/Leaflet#3135]
Repro (on 0.8)

Make a map and perform a pinch-zoom on a touch device.

Observe: No extra css classes on the map pane
Expected: `leaflet-touching` and `leaflet-zoom-anim` should be added, so we can use `leaflet-zoom-hide` and disable transitions.

This seems to be how 0.7 worked.

**Comment by Eschon** [comment]
I think this is the same problem that I have. I have a custom layer that uses the `leaflet-zoom-hide` class. But when I pinch-zoom on a touch device the layer stays visible and does not move until i release. After that it disappears and and reappears in the right size and position.

**Comment by IvanSanchez** [comment]
Pinch-zooming had quite an overhaul since this was reported. @xwipeoutx , can you see if 1.0.0-rc1 behaves as expected?

**Comment by xwipeoutx** [comment]
Looks like it's still not 100%.  I hacked up a jsbin quickly here to set the opacity of the map to 0.1 when leaflet-zoom-anim is on the map. 

http://jsbin.com/hejejomifi 

Hit it up on Chrome for Android and it doesn't add the class until the zoom is completed.  It also doesn't ever have a leaflet-touching class.

That said, I'm not maintaining the project that needed this anymore.  @soxtoby - mind checking? Or at least telling them this isn't important to us anymore? (cc @Eschon see above)

**Comment by Eschon** [comment]
I don't have this issue anymore since I implemented a zoom animation for my custom layer so I have no idea if it is fixed. When I find the time I can try to reproduce a sample similar to my old code.

**Comment by IvanSanchez** [comment]
No more information has been provided, and more than a few weeks have passed. We'll assume this issue is no longer relevant and/or there is no interest to make a better report.
