### ISSUE TITLE
map.getCenter() returning array after flyTo()

### ISSUE THREAD

**Issue by bcamper** [Leaflet/Leaflet#3139]
After a `map.flyTo()` animation completes, `map.getCenter()` starts returning an array (I assume a `LatLng` is always expected?). This can be reproduced in `debug/map/zoompan.html` in console.

On page load:
```
map.getCenter()
L.LatLng {lat: 38.91, lng: -77.04, equals: function, toString: function, distanceTo: function…}
```

Click to pan to SF, then:
```
map.getCenter()
[37.77, -122.42]
```

**Comment by bcamper** [comment]
If this is a confirmed bug: it seems it is caused by the [final `flyTo` frame](https://github.com/Leaflet/Leaflet/blob/d93e82893527326bd27294447084589e66869eba/src/map/anim/Map.FlyTo.js#L52), which calls `map._resetView` with the `targetCenter` argument (which is an array in that demo). Should `flyTo` convert to `L.latLng(targetCenter)` before passing to `_resetView` (or should `_resetView` itself enforce a `LatLng`)? If so happy to submit a PR.

**Comment by mourner** [comment]
@bcamper yeah, `targetCenter` should be converted in the beginning of `flyTo`.

**Comment by iambelawalumer** [comment]
j
