### ISSUE TITLE
Everything is NewClass?

### ISSUE THREAD

**Issue by Jakobud** [Leaflet/Leaflet#3146]
On the master branch right now, practically all objects are referenced as `NewClass`:

```
// In Chrome dev tools console:
> var marker = L.marker();
> marker
NewClass {options: Object, _latlng: undefined, _initHooksCalled: true, constructor: function, initialize: function…}
```

Pretty much all objects are like this. It seems to be because they are all extending a distant object that is type `NewClass`. Is this a bug or is this just how JavaScript is? Would be nice if it said what class the object actually is, like `Marker`...

Any clues on this?

**Comment by danzel** [comment]
Pretty certain this is the same in 0.7
Class recognition in JS is hard!

**Comment by Jakobud** [comment]
Looks like back in 0.6 Class names didn't come up. It would just say something like `e > {... }` in the chrome console.

**Comment by mourner** [comment]
Unfortunately it's just how JS works. The only way to have pretty class names in the console combined with a sophisticated class system is transpiling code a-la Coffeescript or Traceur.
