### ISSUE TITLE
You can create duplicate panes. Bug or Feature?

### ISSUE THREAD

**Issue by Jakobud** [Leaflet/Leaflet#3148]
@mourner Just FYI I noticed that you can create duplicate panes:

```
map.createPane('test');
map.createPane('testPane');
```
results in two identical DOM objects:
```
<div class="leaflet-pane leaflet-test-pane"></div>
<div class="leaflet-pane leaflet-test-pane"></div>
```

Each one is referenced by their unique name: `map.getPane('test');` and `map.getPane('testPane');`

This obviously has to do with how the word "pane" is stripped from the generated class name and then appended when you create a pane.

So what do you guys think? Is this a bug or a feature? Do you want me to fix this or leave it?

**Comment by mourner** [comment]
I think it's fine, no need to fix unless anyone has a real trouble with this.
