### ISSUE TITLE
When drawing GeoJson layer, end points connect sometimes.

### ISSUE THREAD

**Issue by facultymatt** [Leaflet/Leaflet#3150]
I have a map with a GeoJson LineString layer and sometimes the end points of the LineString are connected on the map. This is generally when it happens: 

- I remove any previous geoJson using map.removeLayer()
- I create a new L.geoJson() LineString1
- I add the layer to the map
- LineString1, it draws normally.

Then, 
- I remove any previous geoJson using map.removeLayer()
- I create a new L.geoJson() LineString2
- I add the layer to the map
- It draws, but the end points of the LineString are connected!

I am using the angular leaflet directive, and have [opened an issue here](https://github.com/tombatossals/angular-leaflet-directive/issues/605), but I'm not sure if the bug is isolated to Leaflet or the Angular Leaflet Library. 

End points not connected - correct!
![correct](https://cloud.githubusercontent.com/assets/1406258/5778525/ee7a3114-9d69-11e4-827d-7f5b19e2416d.png)

End points connected - bad!
![wrong](https://cloud.githubusercontent.com/assets/1406258/5778526/f081cd28-9d69-11e4-9bd2-59d42b28b26c.png)

Any thoughts?

**Comment by mourner** [comment]
Can you try reproducing this in a minimal JSFiddle test case (without Angular)?

**Comment by facultymatt** [comment]
I was not able to successfully isolate this issue in jsFiddle using Angular - so I suspect I would not be able to isolate without Angular either. Here is my attempt: http://jsfiddle.net/mL6s2wdb/3/, but as you see the drawing works fine.

Closing for now - I will reopen if things change.
