### ISSUE TITLE
Can't load Leaflet plugin using RequireJS

### ISSUE THREAD

**Issue by ssuarezbe** [Leaflet/Leaflet#3157]
Hi, I need some help.

I am trying to load leaflet plugin using requirejs.

For example if I want to use the leaflet.AnimatedMarker, I do this:
```
require.config({
  paths: {
    'leaflet': './bower_components/leaflet-dist/leaflet',
    'leafletAnimatedMarker': './js/leaflet.AnimatedMarker/AnimatedMarker'
  },
  shim: {
    'leafletAnimatedMarker': {
        deps: ['leaflet'],
        exports: 'LeafletAnimatedMarker'
    }
  }
});
```
I use it in this way.
```javascript
require(['leafletAnimatedMarker'],function(leafletAnimatedMarker)
{
  ...
});
```
If the code before is correct why it does not work.

When I verify if the plugin is loaded using `console.log(leafletAnimatedMarker)` is shows *'undefined'* and I do not know if I'm doing something wrong or if leaflet do not support require yet.

**Using the bower version - "leaflet-dist": "~0.7.2"**

**Comment by jfirebaugh** [comment]
Hi @ssuarezbe. Thanks for using Leaflet!
 
However, this is an issue tracker, for reporting bugs with Leaflet. It's not a support forum. Please post to the [forum](https://groups.google.com/forum/#!forum/leaflet-js), you are more likely to find help there.
