### ISSUE TITLE
Where's the GeoJSON data gone?

### ISSUE THREAD

**Issue by mfc-julius** [Leaflet/Leaflet#3158]
I'm using L.geoJson and adding layer to my map, then with items.on('click', function (event) {}) displaying info of selected object which is stored in event.layer (getting info with toGeoJSON()).

Problem is, when there are some of the items, everything seems to work, but now when there are >1000 polygons, some of the data when using on('click') does not contain my info of the feature inside event.layer.

What could be a problem?

**Comment by jfirebaugh** [comment]
Hi @mfc-julius. Thanks for using Leaflet!
 
However, this is an issue tracker, for reporting bugs with Leaflet. It's not a support forum. Please post to the [forum](https://groups.google.com/forum/#!forum/leaflet-js), you are more likely to find help there.
