### ISSUE TITLE
Leaflet freezes on zoom when it's in an XSLTForms XML file

### ISSUE THREAD

**Issue by gal007** [Leaflet/Leaflet#3161]
I explained the problem and posted the solution here:
http://stackoverflow.com/questions/28092712/leaflet-freezes-on-zoom-when-its-in-an-xsltforms-xml-file/28092713#28092713

**Comment by mourner** [comment]
Did you try the master version?

**Comment by gal007** [comment]
Do you mean Leaflet 0.8-dev? If so, Yep. I'm working with the in-progress version, developed on the master branch.

**Comment by gal007** [comment]
But I had the same problem with the last stable version. That's why I moved to 0.8

**Comment by gal007** [comment]
@mourner sorry, I forgot to mention you.  This is new for me :p

**Comment by IvanSanchez** [comment]
We're gonna need some way to reproduce this bug. Any chance of uploading the XSLTForms page to somewhere public, like a JSFiddle?
