### ISSUE TITLE
Popup on GeoJSON polygon is not centered on the polygon center but on its border

### ISSUE THREAD

**Issue by marcu** [Leaflet/Leaflet#3162]
The layers are created with `L.geoJson`. On each feature, a popup is binded : `layer.bindPopup(popup_string)`. When `layer.openPopup()` is called, the popup is open but centered on the border of the polygon (in the middle of the line).

![screen shot 2015-01-22 at 17 00 40](https://cloud.githubusercontent.com/assets/1483144/5859139/5564dba2-a258-11e4-9bac-c15e5da5a8a6.png)

I didn't understand how the position of the popup is computed for this case. If you explain it to me I can try to create a patch.

**Comment by snkashis** [comment]
Can you provide a JSFiddle?

**Comment by marcu** [comment]
http://jsfiddle.net/u9LLyd6f/

**Comment by mourner** [comment]
@marcu it's the way popup works on polygon in the stable version, but it has been improved in master version — now proper polygon center is calculated.

**Comment by marcu** [comment]
Thanks a lot.

Can you tell me where is it in the code (for my knowledge)?

**Comment by jieter** [comment]
https://github.com/Leaflet/Leaflet/blob/master/src/layer/vector/Polygon.js#L11-30
