### ISSUE TITLE
Canvas Tile Layer --> GridLayer

### ISSUE THREAD

**Issue by bennlich** [Leaflet/Leaflet#3163]
I see in [tilelayer-related-changes](https://github.com/Leaflet/Leaflet/blob/master/CHANGELOG.md#tilelayer-related-changes):

> Removed TileLayer.Canvas in favor of the much more flexible and powerful GridLayer.

Are there plans to write a CanvasGridLayer? There's a little bit of logic to be added on top of GridLayer before it can totally replace TileLayer.Canvas, right?

**Comment by mourner** [comment]
The logic is 2 lines of code. See https://github.com/Leaflet/Leaflet/blob/master/debug/map/canvas.html for an example.

**Comment by bennlich** [comment]
Ah, k. Cool. Might be good to document somewhere that `L.GridLayer.createTile(coords)` is the new `L.TileLayer.Canvas.drawTile(canvas, tilePoint, zoom)`. Do you think this would be worth adding to the changelog? Or is it enough to just add it to the docs?

When I was looking through GridLayer.js, part of my confusion came from looking for a function that accepted something like a `coords` argument, but the default [`createTile`](https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/GridLayer.js#L118-L120) implementation doesn't use a `coords` argument (since it doesn't need one). It wasn't intuitive for me to look at where [`createTile()` is actually called](https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/GridLayer.js#L516) to determine what arguments it has access to.

**Comment by mourner** [comment]
Yeah, we'll update the docs.
