### ISSUE TITLE
Leaflet + GeoJson converted from OSM Data - Relations

### ISSUE THREAD

**Issue by VoyteckPL** [Leaflet/Leaflet#3164]
Hi,
I'm new to Leaflet and JavaScript so please forgive if I ask silly questions. Here is my main purpose. I'm trying to display bicycle relations which I downloaded from geofabrik, converted with osmconvert, filtered with osmfilter and converted to geojson. At the moment Leaflet displays line strings and nodes correctly on the map. The problem is with data from relations that are included in the file. Here is a part of my GeoJson file (I won't include whole file becauce it's just too big):
var rower = {
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "id": "way/27149688",
            "properties": {
                "type": "way",
                "id": "27149688",
                "tags": {
                    "agricultural": "no",
                    "bicycle": "yes",
                    "highway": "residential",
                    "maxweightrating:hgv": "24",
                    "maxweightrating:hgv:condtitional": "none @ marked",
                    "name": "Mikołaja Reja",
                    "source:maxweightrating:hgv": "PL:sign_B-5-note"
                },
                "relations": [
                    {
                        "role": "",
                        "rel": "4046118",
                        "reltags": {
                            "colour": "blue",
                            "description": "Leśna trasa rowerowa, preferowany rower górski / Forest track, Mountain Bike preferred",
                            "lcn_ref": "niebieski",
                            "name": "Szlak Trójmiejski",
                            "network": "rcn",
                            "route": "bicycle",
                            "type": "route"
                        }
                    }
                ],
                "meta": {
                    "timestamp": "2014-04-17T11:58:45Z",
                    "version": "20",
                    "changeset": "21747999",
                    "user": "wojtas82",
                    "uid": "729745"
                },
                "tainted": true
            },
            "geometry": {
                "type": "LineString",
                "coordinates": [
                    [
                        18.5024141,
                        54.4354139
                    ],
                    [
                        18.503622,
                        54.4353485
                    ],
                    [
                        18.5053714,
                        54.4352858
                    ]
                ]
            }
        },

As you can see relations are in square brackets. I wish to display different colours of tracks depending on relations>reltags>colour tag. Here is my main html file (actually the party that doesnt work):

var rower2 = L.geoJson(rower, {
		style: function (feature) {
		switch (feature.properties.relations) {
            case 'blue': return {color: "#ff0000"};
            case 'red':  return {color: "#0000ff"};
			}
		}	
		}).addTo(map);

I tried to modify this part (feature.properties.relations) to (feature.properties.relations.reltags.colour) but it doesn't work. Is there any way to overpass this problem? Thanks a lot in advance for your help!
Best regards,

**Comment by Starefossen** [comment]
Hi @VoyteckPL. This is the issue tracker for the development of Leaflet source code, and not a support forum. Instead, you should try asking on the [Leaflet forum](https://groups.google.com/forum/#!forum/leaflet-js), or on [StackOverflow](http://stackoverflow.com/questions/tagged/leaflet).

**Comment by VoyteckPL** [comment]
Ok sorry. Newbies mistake. Please delete. Thx
