### ISSUE TITLE
Request: minNativeZoom

### ISSUE THREAD

**Issue by latviancoder** [Leaflet/Leaflet#3165]
maxNativeZoom gives us the ability to zoom in beyond available zoom levels. Is it possible to add similar functionality for zooming out?

Currently I have tiles for level 3 only and want user to have the ability to zoom to 1-2. But leaflet tries to load non-existing tiles and then clears screen completely.

This is how it looks now: http://g.recordit.co/virkXkRPIt.gif

```
L.tileLayer('img/tiles/{z}/{x}/{y}.png', {
	tileSize: 200,
	minZoom: 0,
	maxNativeZoom: 3,
	crs: L.CRS.Simple
}).addTo(map);
```

Is it possible that I'm doing something wrong here?

**Comment by mourner** [comment]
I wouldn't want to add that because it's an extremely rare case and is usually harmful for tile servers because you need to load too many tiles. E.g. if you have z3 tiles and want them to load on z1, you would have to load 16 times more tiles as usual.
