### ISSUE TITLE
L.tileLayer.canvas memory issues on chrome and safari

### ISSUE THREAD

**Issue by Brenden-Morales** [Leaflet/Leaflet#3166]
I'm seeing issues with the canvas tileLayer that are similar to https://github.com/Leaflet/Leaflet/issues/3102 . I'm drawing lots of stuff to a canvas tileLayer at certain zoom levels, and it looks like chome and safari (both desktop and mobile) refuse to free memory for some reason. I can pretty easily make chrome use up 1+ gig of memory despite heap snapshots telling me that I'm under 20M.

[Fiddle](http://jsfiddle.net/h6cretw7/4/)

Steps to reproduce:

1) load up Fiddle and take heap snapshot to verify "base" memory
![heapsnap1](https://cloud.githubusercontent.com/assets/3261844/5883641/ff429a62-a319-11e4-96e4-ceceb5b02843.PNG)

2) Check memory reported in Chrome task manager
![taskmanagersnap1](https://cloud.githubusercontent.com/assets/3261844/5883643/0157e122-a31a-11e4-862b-8f69b18ed92c.PNG)

3) Zoom in on map so that canvas tiles show up
![canvases](https://cloud.githubusercontent.com/assets/3261844/5883646/038971d6-a31a-11e4-8877-0a9e5470298e.PNG)

4) Pan around and watch memory increase in chrome task manager
![taskmanagersnap2](https://cloud.githubusercontent.com/assets/3261844/5883651/0a161fb8-a31a-11e4-8a37-94539c235950.PNG)

5) Take heap snapshot and notice that heap *isnt really that big*
![heapsnap2](https://cloud.githubusercontent.com/assets/3261844/5883653/0c6f8114-a31a-11e4-8caf-8be8b9927c6f.PNG)

6) Zoom out (way out) until Canvases are no longer visible

7) Notice that the Task Manager still has a lot of memory for leaflet tab (even after manually garbage collecting)
![heapsnap3](https://cloud.githubusercontent.com/assets/3261844/5883667/356628e8-a31a-11e4-8a27-7add8511846d.PNG)

Perform these same steps with I.E. and you'll notice that I.E. appears to be managing memory properly.

I've looked at the _removeTile method in leaflet and it looks like It's doing all the right things, and the fact that I.E. is properly garbage collecting in both the Fiddle and in my real-world application leads me to believe this is a browser issue.

Anyone have any ideas / thoughts?

**Comment by mourner** [comment]
No idea what's going on. Can you set up a minimal non-Leaflet JSFiddle that creates a bunch of canvases, draws something on them and then removes them? I'm wondering if it's the same without Leaflet.
