### ISSUE TITLE
Layers control does not support scrolling

### ISSUE THREAD

**Issue by lookuptable** [Leaflet/Leaflet#3167]
I've noticed that the layers control does not support scrolling such that, when having a large number of layers, the items at the bottom won't be displayed and there is thus no way to select/unselected these layers.

I semi-repro of this problem can be seen here (I've used a very narrow map): http://jsfiddle.net/lookuptable/ke3gevug/1/

**Comment by jieter** [comment]
I fixed this for L.Control.Minimap with this [`_onResize()` method](https://github.com/leaflet-extras/leaflet-providers/blob/master/preview/L.Control.Layers.Minimap.js#L143-L150) ([called on map resize](https://github.com/leaflet-extras/leaflet-providers/blob/master/preview/L.Control.Layers.Minimap.js#L104-L105)) and some extra [CSS](https://github.com/jieter/Leaflet.layerscontrol-minimap/blob/gh-pages/control.layers.minimap.css)

**Comment by mourner** [comment]
I think this was fixed on master, can you verify?

**Comment by Starefossen** [comment]
[Here](http://jsfiddle.net/starefossen/ke3gevug/2/) is an updated fiddle with latest master.

**Comment by lookuptable** [comment]
Looks like it hasn't be fixed on master based on @Starefossen 's fiddle.

**Comment by mourner** [comment]
Ah, I now remember there was a related issue #2882

**Comment by rowanwins** [comment]
@mourner can be closed now
