### ISSUE TITLE
Disable zoom control buttons?

### ISSUE THREAD

**Issue by amnesia7** [Leaflet/Leaflet#3172]
Is it possible to disable the zoom control buttons?

On `zoomend` I perform a request to the backend for data. 

I can disable `touchZoom`, `scrollWheelZoom`, `doubleClickZoom` and `boxZoom` on the map but I can't see any way to disable the zoom control buttons (`[+]` and `[-]`) because the user is still currently able to click these to change the zoom whilst data for the previous zoom level is still being requested from the database.

I want to prevent further zoom changes to the map whilst the data is being requested.

Is there a way to disable the zoom control buttons without just making them `visibility: hidden`, then `visibility: visible` again when the data has been returned from the database?

I have the same callback function for `dragend` but just disabling `dragging` on the map seems to be working fine for this.

Thanks

**Comment by tmcw** [comment]
The [zoomcontrol](http://leafletjs.com/reference.html#map-zoomcontrol) option does this.

**Comment by mourner** [comment]
I assume you mean disable dynamically. Do you want to hide the controls or set them in a "disabled" state just like when you reach min or max zoom?

**Comment by amnesia7** [comment]
Yes, I want to disable the buttons dynamically so they are unclickable whilst results are produced and then re-enable them again once the results have been shown.

**Comment by amnesia7** [comment]
@tmcw I saw the zoomcontrol option but I don't want to turn the buttons off and on again because it breaks the user experience, I just want to disable the buttons temporarily like when you reach min or max zoom.
I wondered if it was possible to set the map's `minZoom` and `maxZoom` to match the current map zoom level while the results loaded and then revert them afterwards to what they should be but I'm not sure that it can be done using the API.

**Comment by mourner** [comment]
@amnesia7 makes sense! Seems like an easy feature to add.

**Comment by mourner** [comment]
@amnesia7 try `map.zoomControl.enable()` and `disable()` in master version now!

**Comment by amnesia7** [comment]
Works a charm. Thanks @mourner. I saw a couple of SO questions relating to something like this so if I can find them I'll point them in the direction of master.

**Comment by ignacio82** [comment]
@mourner could you post an example? I tried:

```
library(leaflet)
leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=174.768, lat=-36.852, popup="The birthplace of R") %>% 
  map.zoomControl.disable()
```

But I get an error: `could not find function "map.zoomControl.disable"`

**Comment by IvanSanchez** [comment]
@ignacio82 That looks like a Leaflet + R question.

However, this issue tracker is used for reporting bugs and discussing new features for **leaflet only**, not Leaflet+R. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
