### ISSUE TITLE
Multipolygon's popup's changed content reverts

### ISSUE THREAD

**Issue by chronixlo** [Leaflet/Leaflet#3174]
Couldn't find much regarding changing popup contents in general so this could be the wrong approach.

I'm trying to change a part of a multipoly's popup. The reverting also happens with a normal polygon but setting

    layer._popup._content = null;

after changing the content solved that.

Fiddle I threw together, open popup -> click change -> reopen popup
http://jsfiddle.net/chronixlol/e0m8nar1/4/

**Comment by mourner** [comment]
You should change popup content with public API methods, such as `layer.getPopup().setContent("bla")`.

**Comment by chronixlo** [comment]
Neither polygon or multipoly have a getPopup method (0.7.3). Should I get the popups innerhtml, change it and bindPopup it back to the layer?

**Comment by mourner** [comment]
In 0.7.3, try just doing `multiLayer.bindPopup(content)`.

**Comment by chronixlo** [comment]
Sorry I was a bit unclear, I want to change a part of the content.

**Comment by mourner** [comment]
@chronixlo hmm, `bindPopup` also accept a DOMElement. Try createinga hidden div with the content and then modify/pass it around.

**Comment by chronixlo** [comment]
Somehow didn't cross my mind. Got it now, thanks.
