### ISSUE TITLE
WP8.1: pinch-zoom gets messed up after a while (only in master)

### ISSUE THREAD

**Issue by pexi72** [Leaflet/Leaflet#3182]
With WP8.1 (Lumia phones) pinch-zooms starts working irrationally after a few zooms.
Here video showing pinch-zooming in page http://gpspekka.kapsi.fi/leaflet/test8_new.html
http://gpspekka.kapsi.fi/leaflet/lumia2.wmv

It isn't messed up in the beginning but after a while especially zooming out isn't possible any more (with pinch-zoom). Map zooms out but as soon as fingers are taken up it reverts to previous zoom or even zooms in one level.

Zooming with +- buttons works ok after that.

No problems with stable version, just master.

(also #2910 's  "map expands over the div outside the map" is still present on the video)

**Comment by mourner** [comment]
Hmm, could you try bisecting commits between stable and master to find the culprit?
cc @danzel

**Comment by pexi72** [comment]
Didn't find time to bisect but got now Lumia Denim update on the phone (including Windows Phone 8.1 Update 1) and can't re-produce this issue any more with that.

But #2910 's "map expands over the div outside the map"  still existing

**Comment by mourner** [comment]
OK so probably something that's not worth trying to hack on the Leaflet side for pre-update Win.
