### ISSUE TITLE
Tiles not redrawn until touch released

### ISSUE THREAD

**Issue by ianwalberg** [Leaflet/Leaflet#3183]
Using chrome on windows new tiles are drawn as the map is dragged with the mouse and left button held down.

Using chrome on an android tablet with the same application new tiles are not drawn until you stop touching the display.

Is this by design and if so can we modify this behavior?

Thanks

**Comment by danzel** [comment]
https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/GridLayer.js#L14

This is the option, change it on your TileLayer.
