### ISSUE TITLE
Accept Icon iconSize as number

### ISSUE THREAD

**Issue by khoobks** [Leaflet/Leaflet#3185]
Consider the following code snippet

```Javascript
myLayer.setIcon(new L.Icon({
    'iconUrl': myIconUrl,
    'iconSize': 96
});
```

This will reach the function called _setIconStyles in src/layer/marker/Icon.js 

Notice that the anchor variable will be instantiated effectively by going
```Javascript
var anchor = L.point(96/2);
```
At this stage, anchor.x is defined but anchor.y is undefined. That anchor.y is undefined is the key fact here.

Further down in _setIconStyles, the function says
```Javascript
img.style.marginTop  = (-anchor.y) + 'px';
// Which is the same as 
// img.style.marginTop = "NaNpx"
```

On Chrome, this works fine however on IE8, this will cause an "Invalid argument." error.

 You can work around this issue by doing the following
```Javascript
layer.setIcon(new L.Icon({
    'iconUrl': myIconUrl,
    'iconSize': [myIconSize, myIconSize],
    'iconAnchor': [myIconAnchor, myIconAnchor]
}));
```

Arguably I should have been doing this from the start however it would be a fairly simple fix to instantiate L.point with both an x and a y if the assumption that the icon is a square is acceptable.

**Comment by gmpersons** [comment]
Any ideas how this could be clarified a bit? Seems like there should be an easier way...

https://gist.github.com/gmpersons/d86796aecac61015718b
