### ISSUE TITLE
Warn developers if they forgot to include css file

### ISSUE THREAD

**Issue by k-nut** [Leaflet/Leaflet#3189]
I recently found myself using leaflet and it not working the way I wanted. I figured out pretty quickly that this was because I forgot the css file. 

I figured that I could add a simple check to see if the `.leaflet-map-pane`-CSS class is defined and if not warn the developer on the console that they forgot to include the file. Would you accept such a feature or do you think that it would bloat the code base too much?

**Comment by mourner** [comment]
Yeah, that could be useful if it can be done in just a couple lines of code.

**Comment by k-nut** [comment]
As far as I can tell this should do the trick:
```javascript
function isLeafletCssLoaded() {
  for (var i = 0; i < document.styleSheets.length; i++) {
    var rules = document.styleSheets[i].rules || document.styleSheets[i].cssRules;
    for (var x in rules) {
      if (typeof rules[x].selectorText === 'string'  && rules[x].selectorText.indexOf('.leaflet-map-pane') !== -1) {
        return true;
      }
    }
  }
  return false;
}

if (!isLeafletCssLoaded()) {
  throw new Error('Leaflet css class not found. Did you forget ton include the css?');
}
```
Not the prettiest/shortest function in the world but it does the right thing. One could of course also just check if  `leaflet.css` is in the loaded stylesheets but people could always change the name. So I found that checking for the CSS class is the best option and this seems to be the way to do it.

I'm just not sure where to include it. Directly in the `initialize` function in  `Map.js` just before everything else is executed? Or where would be the appropriate place to put this?

**Comment by zimmicz** [comment]
@k-nut does that mean it would be ran everytime you load the page? What happens when there is like a ton of CSS stylesheets included? Wouldn't it slow you down a bit? What if someone decides to use `@import` statement instead of linking leaflet css directly?

**Comment by k-nut** [comment]
Thats right. It would of course have to be loaded every time. And you are also right that this could become a performance issue. I guess we could also wait until the map has loaded and then check for something that we know. Something like:
`document.querySelectorAll(".leaflet-container")[0].style.length > 0`
Do you think that could work? It should be a lot better on the performance side I guess.

**Comment by zimmicz** [comment]
I'm not really sure that Leaflet should deal with missing stylesheet. It might be better to tell people (via the docs) that if they don't include the stylesheet, something really ugly is going to happen.

**Comment by danzel** [comment]
I don't really think we need this in leaflet.
If you miss the CSS it's going to be really broken and discovered at development time.

**Comment by snkashis** [comment]
I tend to agree. Not worth the extra code IMO.

**Comment by jfirebaugh** [comment]
Same here.
