### ISSUE TITLE
Couldn't Remove Markers from Marker Cluster on new Ajax Call

### ISSUE THREAD

**Issue by wondie** [Leaflet/Leaflet#3190]
I couldn't get a good way to hide or remove markers on new ajax call with Marker clustering. I used jquery hide(); function to hide marker images. Also I tried map.removeLayer and clearlayer functions. 

So when marker cluster groups and shows markers, previously hidden markers becomes visible. Meaning, markers that were previously searched and hidden becomes visible. 

Is there a way to hide markers from marker clusters on new ajax load?

demo -  http://projects.tsa.co.ke/marsabit/
To reproduce:
1. Make a search on hospitals, then uncheck health and search security. 
2. Then zoom in and out to group and un-group markers with cluster. Health markers previously searched hospitals are visible. 

The code. 
   $(document).ready(function(){
       $("#viewbtn").on("click",function(){
           $.ajax({
            type: 'POST',
            dataType: "json",
            url:'scripts/queries.php',
            data:$('#mapsearch').serializeArray(),
            beforeSend:function() {
                $('img.leaflet-marker-icon.leaflet-zoom-animated.leaflet-clickable').fadeOut('slow');
                $('.marker-cluster').fadeOut('slow');
                $('<img class="loading" src="images/loading.gif">').appendTo("#rangeserch").fadeIn("slow");
                
                $('.leaflet-marker-icon').hide();
            },
            success:function(data){
                $('.loading').fadeOut('slow'); 
                drawpoints(data); 

            }
        })// end of ajax
    });

    function drawpoints(data){
        var LeafIcon = L.Icon.extend({
          options: {
               iconSize:     [32, 37],
               shadowSize:   [50, 64],
               shadowAnchor: [4, 62],
               popupAnchor:  [0, -20]
          }
        });
         var hosicon= new LeafIcon({iconUrl: 'images/hospital.png'}), 
             secicon= new LeafIcon({iconUrl: 'images/security.png'}); 

        if($("#hospitals").prop('checked') == true){ 

            var hospitalPoints = [];
            for (var i = 0; i < data['hospitals'].length; i++) {
              hospitalPoints[i] = [data['hospitals'][i].lat, data['hospitals'][i].lon];
            } 
            var markers = new L.markerClusterGroup({ 
              disableClusteringAtZoom: 14, 
              animateAddingMarkers: true, 
              spiderfyDistanceMultiplier: true
            });
            for (var i = 0; i < hospitalPoints.length; i++) {
              var a = hospitalPoints[i];
              var title = a[2];
              var marker = L.marker(new L.LatLng(a[0], a[1]), {icon: hosicon}).addTo(map).bindPopup('<div><h6>'+data['hospitals'][i].name+'</h6><br/>'+"<form method='post' action='' id='dbdetail'><input type='hidden' name='health' value='marsabit_health;"+data['hospitals'][i].id+"' id='hosp'></form></div>"); 
              markers.addLayer(marker);
              map.addLayer(markers);     
            }
        }
        if($("#security").prop('checked') == true){ 
            var securityPoints = [];
            for (var i = 0; i < data['security'].length; i++) {
              securityPoints[i] = [data['security'][i].lat, data['security'][i].lon];
            } 
            var markers = new L.markerClusterGroup({ 
              disableClusteringAtZoom: 14, 
              animateAddingMarkers: true, 
              spiderfyDistanceMultiplier: true
            });
            for (var i = 0; i < securityPoints.length; i++) {
              var a = securityPoints[i];
              var title = a[2];
              var marker = L.marker(new L.LatLng(a[0], a[1]), {icon: secicon}).addTo(map).bindPopup('<div><h6>'+data['security'][i].name+'</h6><br/>'+"<form method='post' action='' id='dbdetail'><input type='hidden' name='security' value='marsabit_security;"+data['security'][i].id+"' id='sec'></form></div>"); 
              markers.addLayer(marker);
              map.addLayer(markers);           
            }
        }
    }

Thank you in advance, it is urgently need. Your input is appreciated.

**Comment by jfirebaugh** [comment]
Hi @wondie. Thanks for using Leaflet!
 
However, this is an issue tracker, for reporting bugs with Leaflet. It's not a support forum. Please post to the [forum](https://groups.google.com/forum/#!forum/leaflet-js), you are more likely to find help there.

**Comment by wondie** [comment]
Ok, I thought this an issue because there is no easy way of removing marker cluster with markers on ajax. I have also posted the same question on the google group leaflet page and no one answered it yet. I thought this is where most of the developers and users follow leaflet and post question and answers than the forum.
