### ISSUE TITLE
Custom control with select tag scrolls tile when clicked

### ISSUE THREAD

**Issue by wmarcos** [Leaflet/Leaflet#3192]
On clicking the select inside the custom control the tile moves below de control when the mouse moves, as seen in the example:

http://jsfiddle.net/wmarcos/3h2gLtsr/

Solved in the example by uncommenting the line:

//div.firstChild.onmousedown = div.firstChild.ondblclick = L.DomEvent.stopPropagation;

Info provided by this Issue: https://github.com/Leaflet/Leaflet/issues/936

I leave the issue only as a log for users with the same problem.

Thanks a lot !!
M

**Comment by mourner** [comment]
Thanks! See also #2481

**Comment by wmarcos** [comment]
That is a much clearer explanation indeed.

Thanks! Spectacular work with Leaflet!

I'm using it to map social and poverty related issues in Argentina with and ONG ( http://www.techo.org/argentina/ ). It's making a lot of people happy ! 

https://dl.dropboxusercontent.com/u/1426595/mapong.png
