### ISSUE TITLE
fitBounds issue calling couple times in a row.

### ISSUE THREAD

**Issue by menduz** [Leaflet/Leaflet#3193]
When you call two or more times in a row the method map.fitBounds something inside gets broken. The values of the projection are OK, but the tile layers, overlays and animations were paused and continues with the old offset. I propose a debouncing method on fitBounds, that was my solution.

Best regards.

**Comment by mourner** [comment]
This is a known issue. Did you try master version?

**Comment by menduz** [comment]
I'm resolving an issue for production in a project. Only stable releases are allowed. I'll try it later

**Comment by mourner** [comment]
See also #2021. The fix was backported to stable branch recently, try that out too.
