### ISSUE TITLE
Circle markers border displayed, despite no weight when rendering to canvas

### ISSUE THREAD

**Issue by optical** [Leaflet/Leaflet#3195]
Fiddle: http://jsfiddle.net/o74et25L/3/

Using Leaftlet 0.7

When using L_PREFER_CANVAS, the circle markers border is displayed despite the weight being 0. In the attached fiddle you can see a red edge around the circle which should not be there. When L_PREFER_CANVAS is not set, the behaviour is normal - no border is displayed.

As a workaround I can set the opacity to 0 and the circle is rendered correctly, but still appears to be a minor bug nonetheless. 

Tested using IE11, FF34, Chrome40 all on Windows 8.1 - all have the same behaviour.

**Comment by optical** [comment]
I have just tried this on master and it appears to work as expected, so going to close this issue.

**Comment by mourner** [comment]
Thanks!

**Comment by mourner** [comment]
Note that Canvas is triggered differently in master (not with `L_PREFER_CANVAS`), I assume you looked at debug examples?

**Comment by optical** [comment]
Good thing you mentioned that, I hadn't checked to see how canvas rendering worked in master.

Looks like the bug is still present. I've updated fiddle using the newest version of leaflet. Here it is http://jsfiddle.net/o74et25L/3/ - hopefully my use of the canvas is correct, based it off the vector2 example in debug.

**Comment by optical** [comment]
This has been fixed in #3203

**Comment by mourner** [comment]
:+1:
