### ISSUE TITLE
Tiles not loading when panning with no animation

### ISSUE THREAD

**Issue by Cage1976** [Leaflet/Leaflet#3196]
Hi,
I grabbed the latest version of leaflet 0.8-dev today (3rd Feb 2015).  Now when I jump to a position on my map with panTo/setView/resetView, with no animation, the tiles are not loaded in.  If I turn animation on, it loads them in fine.  They are also loaded in fine when scrolling around the map and zooming.

This worked fine in 0.8-dev until recently.

Thanks.

**Comment by mourner** [comment]
Probably regressed after #3142 cc @jfirebaugh

**Comment by jfirebaugh** [comment]
I can't replicate this -- I tried `map.setView(latLng, center, {animate: false})` and tiles loaded as expected. Can you provide a JSFiddle please?
