### ISSUE TITLE
Enable all layers by default - Leaflet

### ISSUE THREAD

**Issue by vbivigneshg** [Leaflet/Leaflet#3199]
I am using leaflet maps to compare heat layer and marker layer. I've an option to add multiple marker and heat layers dynamically. For me Heat layers are enabled by default as on when user adds new layer. I face issue when user adds marker layer the layer is created and it is not enabled by default. User needs to go and check the check box then it's getting enabled.

My question is, How to enable marker layers by default as on when users adds a new layer. Attached screen shots for better understanding of my question.

Thanks in anticipation.
![heat_marker_layer_comparison](https://cloud.githubusercontent.com/assets/9553503/6056992/82ed4532-ad3e-11e4-88f5-8c1e2d097d7b.png)
![layer_comparison](https://cloud.githubusercontent.com/assets/9553503/6056993/82ef47ba-ad3e-11e4-92db-e630aa94e3aa.png)

**Comment by mourner** [comment]
You just add all layers to the map in the initialization code. `map.addLayer(layer)`.

**Comment by vbivigneshg** [comment]
Thanks Vladimir.  It works.  And Sorry for such a silly question.

**Comment by mourner** [comment]
No worries, all questions are fine :)

**Comment by simanjuntak123** [comment]
not work, how?
