### ISSUE TITLE
Map scrolling by itself

### ISSUE THREAD

**Issue by dylanparry** [Leaflet/Leaflet#3200]
Hi,

I’ve got a map that uses Leaflet and Angular and is resized to fill the available screen. Here’s an example:

http://conwy.opus4.co.uk/planning/localism/abergele/maps/abergele-placemaking-plan

It works fine in Opera and Firefox (both latest) until you maximise the browser, then the map mysteriously starts moving downwards all by itself. I’m baffled by this. It only happens when the browser is truly maximised too—resizing the browser to fill the screen doesn’t cause this effect.

In IE11 and Chrome (latest) it moves downwards by itself all the time even when the browser is windowed.

The map sits in a DIV which is given 100% width/height, which in turn sits inside another div that gets its height set by Javascript to be 100% width/height minus the header bar at the top of the page. The map then of course expands to fill the resized DIV.

Has this behaviour been experienced before? It seems to be occurring sometime around when the invalidateSize() function gets called following the map resizing, but I’m not entirely sure about that.

Thanks.

**Comment by dylanparry** [comment]
In addition, when I view the code in Developer Tools I see the following:

<div class="leaflet-map-pane leaflet-pan-anim" style="transform: translate3d(357px, 54px, 0px); -webkit-transition: all 0.25s cubic-bezier(0, 0, 0.5, 1); transition: all 0.25s cubic-bezier(0, 0, 0.5, 1);">

Where the second parameter to the translate3d is continuously increasing by 1px.

Not sure if this is of any help in figuring out what’s going on though!

**Comment by mourner** [comment]
Super-weird. So far I've been able to trace it down to `panInsideBounds` which is called when `maxBounds` is set. No idea why it thinks the view is outside of max bounds by 1px though. Maybe a rounding issue somewhere. What maxBounds do you set there?

**Comment by dylanparry** [comment]
Hmm, code got stripped sorry. Here it is properly:

```html
<div class="leaflet-map-pane leaflet-pan-anim" style="transform: translate3d(357px, 54px, 0px); -webkit-transition: all 0.25s cubic-bezier(0, 0, 0.5, 1); transition: all 0.25s cubic-bezier(0, 0, 0.5, 1);">
```

**Comment by dylanparry** [comment]
It does indeed appear to be connected to the maxBounds property. I commented it out and then the map works exactly as expected in all four browsers I tested it in.

Here’s the code I’m using to set up the map:

```javascript
// Create the projection
this.crs = new L.Proj.CRS(
	'EPSG:' + config.projection.code, // Eg. 27700
	config.projection.proj4, // The proj4 string
	{
		resolutions: config.panZoom.resolutions, // Array of resolutions
		origin: [0, 0]
	}
);

// Get the bounds from the config
var southWest = this.crs.projection.unproject(L.point([config.panZoom.maxExtents.left, config.panZoom.maxExtents.bottom]));
var northEast = this.crs.projection.unproject(L.point([config.panZoom.maxExtents.right, config.panZoom.maxExtents.top]));
var bounds = L.latLngBounds(southWest, northEast);

// Create the map
this.map = new L.Map(
	'opusMap',
	{
		crs: this.crs,
		continuousWorld: true,
		worldCopyJump: false,
		attributionControl: false,
		zoomControl: false,
		maxBounds: bounds,
		maxZoom: config.panZoom.resolutions.length - 1, // The number of resolutions -1 to account for array indexing
		minZoom: 0
	}
);
```

A lot of the things in the code above are supplied via a config object that’s passed to the function creating the map. The projection is created using the Proj4 plugin, and the bounds are generated from some coordinates passed in and reprojected by the Proj4 plugin.

Commenting out the "maxBounds" line in the map creation block has solved the immediate issue, but now of course users can scroll the map way outside the area I want them to see, so it’s not a great solution really.

**Comment by perliedman** [comment]
Sounds awfully similar to #2427, which we never really solved...

**Comment by mourner** [comment]
Yes, very likely the same issue, so closing as duplicate.
It didn't reproduce at first but started reproducing when I set true fullscreen mode.
