### ISSUE TITLE
Broken tile animations in Safari

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#3206]
Tile animations are pretty broken in Safari. `git bisect` says it started with 22cfd12956f6dcf4e3f5d3e2ee34b8046bdf1fe4. @jfirebaugh thoughts?

**Comment by jfirebaugh** [comment]
@mourner Say more? Not seeing any immediate issues with 8.0.3 (10600.3.18).

**Comment by jfirebaugh** [comment]
Oh, I was on the wrong branch, never mind.
