### ISSUE TITLE
Closing popup on map click in mobile browsers.

### ISSUE THREAD

**Issue by ilfa** [Leaflet/Leaflet#3207]
We set closePopupOnClick in true.

When we have opened popup and tap to map in mobile we often want only close popup, and not to open new one on map click event.

I see 2 ways:
- not fire click event in this case (but it seems bad way)
- add flag to event, that popup was closed in this click, decide what to do.

What do you think about this?

**Comment by IvanSanchez** [comment]
Carry a flag around and manually control if there's a popup open in the map.

I agree that having something like `L.Map.isPopupOpen()` would be nice - but this can be done via mixins in a plugin.
