### ISSUE TITLE
Error with 'dragEnd' for Tablet Browsers

### ISSUE THREAD

**Issue by ttback** [Leaflet/Leaflet#3211]
We are seeing some random js errors related to drag + drop handling on Leaflet for iPad and Android tablet

For example, onDragEnd triggers following error report
Leaflet version: 0.7

````
At _onDragEnd
Message: 	undefined is not an object (evaluating 'this._positions[0]')
Exception type:	TypeError
Browser: iPad Safari 8.0
User agent:	Mozilla/5.0 (iPad; CPU OS 8_1_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12B466 Safari/600.1.4

````
Test url to drag on: http://timesmachine.nytimes.com/timesmachine/1969/07/21/issue.html

I think it's related to this line of code but not sure what might cause this to be undefined on iPad. Is there any way we could safeguard against this case on our end?
https://github.com/Leaflet/Leaflet/blob/c3a39f50cf7e36278749deebbd6855e5d83b4f98/src/map/handler/Map.Drag.js#L120

**Comment by jfirebaugh** [comment]
Can you provide a JSFiddle that demonstrates the issue please?

**Comment by ttback** [comment]
@jfirebaugh I don't have a JSFiddle for this one. I am not sure if you guys had any generic JSfiddle that loads some tiles in Leaflet. This one prob has nothing to do with our specific app but the drag and drop handling on tablet. I wonder what `this` would be on that line of code.

**Comment by mourner** [comment]
Try to set up a JSFiddle test case, it's pretty easy. Also, always verify issues on the latest stable and master versions rather than reporting an issue on an old version, since it may have been fixed already.
