### ISSUE TITLE
Error on Draggable<._onUp on Windows Firefox

### ISSUE THREAD

**Issue by ttback** [Leaflet/Leaflet#3212]
This primarily happens on Windows Firefox, from version 25.0 to 34.0.
Leaflet version: 0.7

````
Message: 	e.className is undefined
Exception type: TypeError
Browser:	Windows Firefox 34.0
User agent:	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0

Stack trace
a.DomUtil._getClass
a.DomUtil.removeClass
a.Draggable<._onUp
a.DomEvent.addListener/s
````
Test url to drag on: http://timesmachine.nytimes.com/timesmachine/1969/07/21/issue.html

I traced it down to following lines, but can't see what calls `_getClass` that caused this error on Firefox.

https://github.com/Leaflet/Leaflet/blob/76440b9df2e802fa5691686834c76008e4488927/src/dom/Draggable.js#L111

https://github.com/Leaflet/Leaflet/blob/cb1994a3db1029bcfc2fe5bbb95c813b6a91869c/src/dom/DomUtil.js#L76

**Comment by jfirebaugh** [comment]
Please provide a JSFiddle that demonstrates the issue and a list of steps to replicate.

**Comment by mourner** [comment]
Also, does it reproduce on latest stable (0.7.3)? What about master?

**Comment by ttback** [comment]
@mourner we'll try to deploy the 0.7.3 in about 2 weeks and see what the system finds.

**Comment by mourner** [comment]
OK, will reopen if there's a reproducible test case on 0.7.3 or master later.
