### ISSUE TITLE
Integrating Leaflet 0.8 with an external SVG library

### ISSUE THREAD

**Issue by akauppi** [Leaflet/Leaflet#3213]
Hi all,

I'm studying the `master` source code, and have looked into 0.7 Raphael binding and Leaflet:Draw. My need is simple, but I'm not sure it's currently covered by Leaflet.

I wish to build an SVG application on top of map, so that when there's panning and zooming, things simply scale right, in the SVG arena, without modifying the elements themselves. That is, the transformation of the SVG should change. 

As far as I've tracked, the current SVG zooming tends to change the elements themselves.

Within such a system:

- the SVG coordinates should be given in meters (or whatever is the projection's native measure)
- since the pan/zoom would happen in the transformation, the SVG world could have what seems to be called "linear zoom" (i.e. animated between zoom stages) - not crucial for me, though

I can put time in doing this - what I'm not sure yet, is whether Leaflet has the necessary pieces already in place (none of the demos seems to be doing exactly what I wish). Pointers to right sections would be helpful, as would collaboration with other people who would benefit from such.

The idea is, one could pick any SVG library one wants, to do the app part.

**Comment by jfirebaugh** [comment]
> when there's panning and zooming, things simply scale right, in the SVG arena, without modifying the elements themselves. That is, the transformation of the SVG should change.

Yes, this should be possible. In fact it's exactly how Leaflet's built in SVG feature layer behaves -- take a look at [Renderer.js](https://github.com/Leaflet/Leaflet/blob/54c712cf2b8040ba2da18680914a98971dbc25be/src/layer/vector/Renderer.js#L46-L51) and other layers that bind to the `zoomanim` event.

**Comment by mourner** [comment]
> As far as I've tracked, the current SVG zooming tends to change the elements themselves.

That's because the core SVG renderer clips and simplifies data for each zoom for performance, so we can't avoid that. You could write a custom renderer though that accomplishes everything you mentioned pretty easily. If you implement this, don't forget to share! If the solution is generic, it could be a great plugin.

**Comment by akauppi** [comment]
Thanks, @jfirebaugh @mourner 

Forgot to mention one of the design criteria (that you implied):
- no clipping of the SVG, it will all remain in the DOM at all times

This is doable for performance in the kind of application I have in mind, and would allow that in zooming out and panning, the data is immediately visible.

**Comment by akauppi** [comment]
I've filed the results today as a pull request: https://github.com/Leaflet/Leaflet/pull/3243
