### ISSUE TITLE
Documentation says that FeatureGroup has layeradd / layerremove events, but it doesn't

### ISSUE THREAD

**Issue by chriserickson** [Leaflet/Leaflet#3214]
Looking at the source, there doesn't seem to be any "fire" called on the feature group, but the documentation says it does...
![image](https://cloud.githubusercontent.com/assets/1971519/6088486/3881cc3a-ae14-11e4-94fc-bf9c501be9af.png)

**Comment by chriserickson** [comment]
Note: these events would be very useful.

**Comment by jfirebaugh** [comment]
These events do exist.

Master: [layeradd](https://github.com/Leaflet/Leaflet/blob/2925be1112d3f8840050d023375d1d1f8d80ae76/src/layer/FeatureGroup.js#L21-21), [layerremove](https://github.com/Leaflet/Leaflet/blob/2925be1112d3f8840050d023375d1d1f8d80ae76/src/layer/FeatureGroup.js#L40)
Stable: [layeradd](https://github.com/Leaflet/Leaflet/blob/8849980cd70fb70be6acac8f08ea9c7a1a5f11ee/src/layer/FeatureGroup.js#L28), [layerremove](https://github.com/Leaflet/Leaflet/blob/8849980cd70fb70be6acac8f08ea9c7a1a5f11ee/src/layer/FeatureGroup.js#L47)
