### ISSUE TITLE
Draggable marker on map when move it around the map the map does not move

### ISSUE THREAD

**Issue by FranDelaCasa** [Leaflet/Leaflet#3225]
Hi, I use leaflet with here maps, and I have a map with a draggable marker in it.

When I press left mouse button and drag the marker around the map... the map doesn't move ... maybe is it due to use Here maps instead Google maps?

Is there any option to configure this?

Thanks in advance.
Fran.

**Comment by jfirebaugh** [comment]
Hi @FranDelaCasa. Thanks for using Leaflet!
 
However, this is an issue tracker, for reporting bugs with Leaflet. It's not a support forum. Please post to the [forum](https://groups.google.com/forum/#!forum/leaflet-js), you are more likely to find help there.
