### ISSUE TITLE
Invalid Geojson Object, cannot add data after filtering

### ISSUE THREAD

**Issue by IOR88** [Leaflet/Leaflet#3226]
http://stackoverflow.com/questions/28480206/invalid-geojson-object-angularjs-leafletjs

I made question on stackoverflow, I cannot track if issue is on the side of angular filtering or leaflet,

direct link to fildder : http://jsfiddle.net/ior88/5ea8yxwo/2/

The problem is i cannot pass geojson after angular filtering into leaflet directive, but i can pass clear data without filtering, but i try to make my map dynamic, i cannot understand it because both clear geojson and the one after filtering have the same syntax. thanks

**Comment by jfirebaugh** [comment]
This is an issue in your code somewhere. I commented on your SO post.
