### ISSUE TITLE
Markers don't repeat across globe

### ISSUE THREAD

**Issue by rthill91** [Leaflet/Leaflet#3227]
Markers don't appear to show up when you move the view "around" the world.  For instance, if starting in Alabama with a marker, I moved east until the map repeats and i'm back in Alabama, the marker does not appear.
![capture](https://cloud.githubusercontent.com/assets/6558170/6171939/7be97750-b2a3-11e4-9014-4fa4db175857.PNG)

**Comment by pufanalexandru** [comment]
You should set worldCopyJump option to true: http://leafletjs.com/reference.html#map-worldcopyjump

**Comment by rthill91** [comment]
Evidently, I need to RTFM a little more carefully, lol.
Thank you
