### ISSUE TITLE
Animated gif overlay strange behavior (chrome only)

### ISSUE THREAD

**Issue by Grandmasg** [Leaflet/Leaflet#3232]
Spotted some strange behavior of a animated overlay (only in chrome)
![strange](https://cloud.githubusercontent.com/assets/6714237/6200485/f8afbd8e-b47a-11e4-9e34-7ca5c85b7c49.png)
Sample link: http://ontladingen.nl/testing.html

**Comment by danzel** [comment]
The border? I don't get that locally in chrome.

**Comment by mourner** [comment]
Looks fine for me too. What OS? In any case, I don't think this has to do with Leaflet, which just puts an image on the map.

**Comment by Grandmasg** [comment]
System: windows 8 (64 bit)
Seems to happen when i repeatedly press CTRL + F5
Looks like a **chrome cache problem** or so...  I sometimes see parts of the rest of the page in the picture. Looks like i'm at the wrong place then ... You can close this issue
![screenshot_2](https://cloud.githubusercontent.com/assets/6714237/6202390/4fe0b334-b4e8-11e4-9ff9-643635679f85.png)
