### ISSUE TITLE
tiled map editor

### ISSUE THREAD

**Issue by gurumelo** [Leaflet/Leaflet#3237]
Hello.
what do you think about to use tiled http://www.mapeditor.org/ for to create tilelayer in leaflet?
is possible?
Thanks.

**Comment by danzel** [comment]
Hi @gurumelo. Thanks for using Leaflet!
 
However, this is an issue tracker, for reporting bugs with Leaflet. It's not a support forum. Please post to the [forum](https://groups.google.com/forum/#!forum/leaflet-js), you are more likely to find help there.
