### ISSUE TITLE
Show GH stars and date of last update in plugin list

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#3240]
Here's a nice example we could follow when revamping the plugins page: http://www.staticgen.com/
It uses a static generator script to fetch number of stars for each repo / etc. A bit more cumbersome to maintain, but will make the plugins list more useful. It starts to get out of hand. Dynamic search / sorting would also help a lot.

**Comment by geomajor56** [comment]
Date of last update would be nice too

On Wednesday, February 18, 2015, Vladimir Agafonkin <
notifications@github.com> wrote:

> Here's a nice example we could follow when revamping the plugins page:
> http://www.staticgen.com/
> It uses a static generator script to fetch number of stars for each repo /
> etc. A bit more cumbersome to maintain, but will make the plugins list more
> useful. It starts to get out of hand. Dynamic search / sorting would also
> help a lot.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Leaflet/Leaflet/issues/3240>.
>


-- 
Sent from Gmail Mobile

**Comment by mourner** [comment]
Agreed.

**Comment by IvanSanchez** [comment]
Maybe something entirely client-side with octokat.js (https://github.com/philschatz/octokat.js) would be possible.

Also: add another column indicating whether the plugin is available through Bower / NPM / [insert name of favourite framework or package manager here].

**Comment by mourner** [comment]
@IvanSanchez doing this completely client-side would be a GitHub API abuse — imagine making 200 requests on one page load just to show stars... I think the only way to make it work currently well is precalculating stars. 

Although I just realized it would be so awesome to have a Node service running somewhere that would track number of stars to a set number of repos, cache them and serve. It would be useful not only for Leaflet but for other projects.

Column for package managers would make the list too verbose and noisy I think. One column I think would be useful is one indicating the Leaflet version requirements (e.g. does it support master or only 0.7.3).

**Comment by jieter** [comment]
Is having this list in a html like structure a requirement? I would say the number of plugins justifies a  sortable and searchable list/table with some more information available when selecting a plugin. This is where we can add things like npm/bower package links without cluttering the main list.

Making this table searchable and having good tags/keywords for each plugin will make the categories less important and the reduces the discussion about in which category we need to put a plugin.

I once started to make something like the above, but I cannot find it any more...

**Comment by IvanSanchez** [comment]
> Is having this list in a html-like structure a requirement?

I'd say "yes". In my mind, the plugins should be:

* Browsable with javascript disabled in the browser,
* Easy to by making pull requests against `gh-pages`, and
* Should not require extra backend work. Maybe a Jekyll hack would be nice, but I wouldn't like to see a complex build system just for this.

**Comment by jieter** [comment]
> Browsable with javascript disabled in the browser,
Really? Why would you be searching for javascript plugins for a javascript framework with javascript disabled?

You're right about the ease of pull requests of course. Current situation is not the easiest either.

**Comment by Eschon** [comment]
> Really? Why would you be searching for javascript plugins for a javascript framework with javascript disabled?

I do that quite often. I usually use NoScript and allow only scripts of pages that I trust and I tend to get upset when pages don't work without JavaScript. 

But I guess not many people are as paranoid as I am.

**Comment by mourner** [comment]
Another argument for HTML is that it is searchable, and people often search for Leaflet plugins with Google. We could augment the HTML list with dynamic search though, it's a good feature if implemented right.

**Comment by mourner** [comment]
BTW, switching from categories to keywords with live search may be a good approach in future. The current category break is not the final way to organize plugins, and we may come up with better ways eventually, but it's a huge improvement over what was before.
