### ISSUE TITLE
Weird looking line in DomEvent.js (0.8.x master)

### ISSUE THREAD

**Issue by akauppi** [Leaflet/Leaflet#3242]
During my read-through of the Leaflet.js code, I spotted this line, that looks like a bug:

https://github.com/Leaflet/Leaflet/blob/master/src/dom/DomEvent.js#L14

````javascript
if (typeof types === 'object') {
			for (var type in types) {
				this._on(obj, type, types[type], fn);
			}
		} else {
			types = L.Util.splitWords(types);

			for (var i = 0, len = types.length; i < len; i++) {
				this._on(obj, types[i], fn, context);
			}
		}
````

It's hard to tell for sure, since the `on` method does not seem to be included in the `gh-pages` documentation of 0.8.x.

If the second param is a map with different functions for each of the keys, why the last `fn` that would end up as a `context` for `_on` call.

Just saying check this. I may be wrong (in which case it would be good to mark the expected parameter types as a comment).

**Comment by jfirebaugh** [comment]
`on` is an alias for `addListener`, which [is documented](http://leafletjs.com/reference.html#domevent-addlistener). However, this particular form of arguments isn't documented. It works like:

```
L.DomEvent.addListener(obj, {'click': this.onClick, 'dblclick': this.onDblClick}, this);
```

The third argument is the context. In the definition that's `fn`. So this isn't a bug, but the documentation is incomplete.

**Comment by akauppi** [comment]
So.. is this okay to be closed?
