### ISSUE TITLE
Problems using Leaflet inside Shadow DOM

### ISSUE THREAD

**Issue by MeloJR** [Leaflet/Leaflet#3246]
Hi, I wanted to use Leaftlet inside my custom elements built with Polymer and I have found a problem with it, that is, the map was totally "broken" with tiles outside the div container. Here is a picture with leaftlet working in the body (not inside a custom element):

![leaflet](https://cloud.githubusercontent.com/assets/5193005/6318252/b565e260-ba88-11e4-9bbf-a3cfe58b6df8.png)

And here is leaftlet inside a custom element:

![leaflet-problem](https://cloud.githubusercontent.com/assets/5193005/6318254/bc4d9384-ba88-11e4-80cc-491b82e933e7.png)

It seems to be a problem with the css/js selectors that don't support Shadow DOM. What can I do to solve this problem?

**Comment by mourner** [comment]
Are you sure Leaflet CSS gets applied to the shadow DOM container?

**Comment by MeloJR** [comment]
Excuse my mistake... I found the problem, I forgot to include the Leaflet CSS inside the polymer-element tag... It works perfectly now.
Thank you!
