### ISSUE TITLE
Panning in iOS (iPad) re-adds L.Circle

### ISSUE THREAD

**Issue by alexcroox** [Leaflet/Leaflet#3248]
When I pan around on iOS 7 iPad it seems to re-add the L.Cirlces previously added. Normally this wouldn't be an issue but I have some css3 transitions that trigger when it's first added that I don't want repeated. I can't replicate this behaviour on any other device. Is this intended behaviour?

**Comment by mourner** [comment]
Can you reproduce this in a minimal JSFiddle test case?
