### ISSUE TITLE
new created map is misplaced

### ISSUE THREAD

**Issue by pointhi** [Leaflet/Leaflet#3251]
Leaflet-Version: 7.3
Bug can be reproduced in Firefox 35 as well as in Chromium using Ubuntu 14.04

Currently, I'm rewriting the js-codebase of [searx](https://github.com/asciimoo/searx). Mainly to support bigger codebases without handling problems. Because of that I have rewrite the current code to typescript, which can be compiled into javascript.

the rewrite is logical identical, but now I stored the map object inside a class, and the layers also stored inside an extra class, which shouldn't be a problem. But now, the map isn't working until I force a resize event on the window.

### how it look with the new code

This is the code which cause that problems:
https://github.com/pointhi/searx/blob/0c4c3061e569da56a8be3edcbdee2793a593ce45/searx/static/themes/oscar/typescript/map/Map.ts#L40

![leaflet_misplacing](https://cloud.githubusercontent.com/assets/1652144/6377292/848c4312-bd23-11e4-85bf-88b1e8a21d2d.png)

after resizing the window, leaflet is showing the tiles in a correct way

### how it should look (old script version)

on my server is a working version with the old script:
https://searx.oe5tpo.com/?q=%21map%20M%C3%BCnchen&pageno=1&category_map

this is the old code:
https://github.com/pointhi/searx/blob/fb4bb425cffde21df683701a30f0799105b27931/searx/static/themes/oscar/js/searx_src/leaflet_map.js#L43

![leaflet_misplacing_correct_image](https://cloud.githubusercontent.com/assets/1652144/6377334/b88f015e-bd23-11e4-9974-31637c02da23.png)

**Comment by mourner** [comment]
See `map.invalidateSize()`

**Comment by pointhi** [comment]
this line doesn't work, either after the ```L.map``` or after every other command in the init-function.

```typescript
this.map.invalidateSize({});
```
