### ISSUE TITLE
Map zoom controls loose focus after click

### ISSUE THREAD

**Issue by lee101** [Leaflet/Leaflet#3254]
Focus moves back to the map added in #2148
Could we keep the focus on the zoom buttons but let users keyboard events like +/- and arrows fall through to the map when they are focused on the zoom buttons? I find it a bit strange that the focus seems to disappear when i click enter after tabbing to the zoom button, i think it would be better to maintain focus because people might want to click enter on the zoom buttons multiple times.

**Comment by juliensoret** [comment]
This issue has been posted here : https://github.com/Leaflet/Leaflet/issues/3159

**Comment by mourner** [comment]
Yep, duplicate
