### ISSUE TITLE
Drawing with canvas fails to round lines

### ISSUE THREAD

**Issue by sombra2eternity** [Leaflet/Leaflet#3261]
Setting

    window.L_PREFER_CANVAS = true;

to gain some performance using canvas I got this result:

![map](http://i.imgur.com/BcGyfkN.png)

As you can see those island and some other corners are too sharp so I checked leaflet lib and found:

    ctx.lineCap = 'round';
    ctx.lineJoin = 'round';

Unfortunately this is not currently working, go to (nearly) line 5118 and change "_drawPath" function to this (just for testing, note the alert):

    _drawPath: function () {
		var i, j, len, len2, point, drawMethod;

		this._ctx.beginPath();

		for (i = 0, len = this._parts.length; i < len; i++) {
			for (j = 0, len2 = this._parts[i].length; j < len2; j++) {
				point = this._parts[i][j];
				drawMethod = (j === 0 ? 'move' : 'line') + 'To';
    if(drawMethod == 'lineTo'){
	    alert(this._ctx.lineJoin);
    }
				this._ctx[drawMethod](point.x, point.y);
			}
			// TODO refactor ugly hack
			if (this instanceof L.Polygon) {
				this._ctx.closePath();
			}
		}
	}

Then if you run this modified code you'll get "miter" in the alert screen but It should be "round". To workaround this bug you can fill lineCap and lineJoin again with correct values but Im not sure if it is the correct approach for the issue:

    _drawPath: function () {
		var i, j, len, len2, point, drawMethod;

		this._ctx.beginPath();
		this._ctx.lineCap  = 'round';
		this._ctx.lineJoin = 'round';

		for (i = 0, len = this._parts.length; i < len; i++) {
			for (j = 0, len2 = this._parts[i].length; j < len2; j++) {
				point = this._parts[i][j];
				drawMethod = (j === 0 ? 'move' : 'line') + 'To';

				this._ctx[drawMethod](point.x, point.y);
			}
			// TODO refactor ugly hack
			if (this instanceof L.Polygon) {
				this._ctx.closePath();
			}
		}
	}

Almost this solves the bug for me.

![map](http://i.imgur.com/xXhTQW1.png)

 Thanks

**Comment by mourner** [comment]
Is this reproducible on master?

**Comment by sombra2eternity** [comment]
Seems fixed at first sight, may it only affect stable version.

Anyway window.L_PREFER_CANVAS = true; stopped working and I was unable to find some doc to enable it via params so I has to hack to code to enable it.

Thanks

**Comment by mourner** [comment]
@sombra2eternity there's a different syntax for this now. See `debug/vector/vector2.html` for an example.
