### ISSUE TITLE
Leaflet version published on npm as 0.7.3 is in fact version 0.7.2

### ISSUE THREAD

**Issue by burmisov** [Leaflet/Leaflet#3262]
Install leaflet from [npm](https://www.npmjs.com/package/leaflet) with `npm i leaflet@latest`.
Look into node_modules/leaflet.
package.json lists version 0.7.3
Other sources list L.version='0.7.2'.

**Comment by mourner** [comment]
Yes, that's just an error in the `L.version` property. It's identical to `0.7.3` except for the number.
