### ISSUE TITLE
Panning/zooming in iOS/android redraws polygon layers when movement ends

### ISSUE THREAD

**Issue by houkah** [Leaflet/Leaflet#3265]
When panning/zooming in iOS and android polygons disappear and are readded.  This is quite pronounced as i have a css fade transition effect on the polygons.  I can understand them redrawing when zoomed but not sure why it does it when panning.  A test version of this map can be seen here.

http://ceb.nlm.nih.gov/~mchung/nirenberg-chart11c.html

changing method to prefer canvas fixed this but broke some click propagation and css transitions.  Any idea why this is occuring?

**Comment by mourner** [comment]
I think this is fixed on the master version. Also see #1348 #2671
