### ISSUE TITLE
Severe regression on iOS after tile anim refactor

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#3268]
@jfirebaugh commit bbf32ebfcdb0d24d187dbb54eecbea367fd7b72d introduced a severe performance regression on iOS (at least on my iPhone). Pinch zoom is pretty much unusable. Probably a bug — this is apparent while you pinch, even before releasing the fingers for an animation.

**Comment by mourner** [comment]
Hmm, while this could be fixed by disabling `GridLayer` `_reset` routine while doing pinch-zoom (seems to work), there's a different issue: animations have weird shifts even when you use the zoom buttons and double tap only. Reproducible pretty much immediately when you start pushing the zoom buttons.

**Comment by jfirebaugh** [comment]
Didn't get a chance to test on non-simulator, but should be better now.

**Comment by mourner** [comment]
The latter is fixed for now by disabling fade-in-during-zoom animation in mobile WebKit, which works better than unstable reqAnimFrame hacks with markers going out of sync.
