### ISSUE TITLE
How to remove GeoJSON Layer?

### ISSUE THREAD

**Issue by sindre** [Leaflet/Leaflet#327]
When trying to remove a GeoJson Layer via map.removeLayer(geoJsonLayer) the following Error occurs "Uncaught TypeError: Cannot read property '_panes' of null" The same with geoJsonLayer.clearLayers();

**Comment by mercelsantos** [comment]
I wrote the below example to show how to remove multiples geoJSON layer.


///adding geoJSON data

          var myGeoJSON = L.geoJSON(myData, {

		    onEachFeature: function (feature, layer) {
		        layer.myTag = "myGeoJSON"
		    }

	    });


////// function to remove geoJSON layers 

	var removeMarkers = function() {
		map.eachLayer( function(layer) {

		  if ( layer.myTag &&  layer.myTag === "myGeoJSON") {
			map.removeLayer(layer)
        	  }
	
	        });

	}

//// calling function 

removeMarkers();
