### ISSUE TITLE
What Tutorials on leafletjs.com do people want to see for 1.0?

### ISSUE THREAD

**Issue by Jakobud** [Leaflet/Leaflet#3271]
1.0 is getting close. The tutorials on leafletjs.com have been pretty minimal for a while. The purpose of this issue is to get a list of tutorial topics that everyone look like to see created and added to the site.

What do you guys want to see? Just reply with basic topic ideas or design approaches that either you want to know more about or that you feel that new users of Leaflet would greatly benefit from.

**Comment by mourner** [comment]
There were several on my list that I have been putting off until after 1.0 refactoring:

- Custom overlays
- Flat maps & custom projections
- Simple server-side integration tutorial (ajax, updating markers in view etc.)
- Performance best practices
- Tutorials integrating popular plugins

**Comment by Jakobud** [comment]
* Custom Panes
* Custom Renderers
* SVG Marker Icons

**Comment by Jakobud** [comment]
@mourner Does gh-pages get pushed to leafletjs.com automatically? If we wanted to start adding new tutorials, where should they be put in the meantime?

**Comment by mourner** [comment]
@Jakobud gh-pages-master

**Comment by karim2001** [comment]
How to load markers from sql DB?

**Comment by jindrichmynarz** [comment]
I fail to find a tutorial on custom Leaflet events. That would be a great addition to the documentation.

**Comment by patrickarlt** [comment]
* Finding and working with geospatial data
* Advanced layer ordering

**Comment by Jakobud** [comment]
@patrickarlt Re: Advanced layer ordering do you mean being able to know how to use the z-index to alter the order of the different layers?

**Comment by patrickarlt** [comment]
@Jakobud Yup using the new pane API.

**Comment by Jakobud** [comment]
I'm really familiar with it, I wrote part of it. I'll put together a tutorial for that part.

**Comment by aosho235** [comment]
- CRS.Simple and game maps

**Comment by mourner** [comment]
Closing in favor of #4239
