### ISSUE TITLE
IE7-9 graceful degradation for animations & fractional zoom

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#3272]
In IE7-9, all API methods should never break. Fractional zoom levels should fallback to round ones. We can skip animations too.

**Comment by mourner** [comment]
This issue is relatively easy to grab — the basic task is to make sure that:

- make sure basic map functionality and examples still work in IE 7-9
- calls to `flyTo` don't animate in IE < 9 (that doesn't support CSS3 transforms) and instead just jump to final value
- calls to `setView` and the family with fractional zoom values silently sets it to round zooms in IE < 9

**Comment by Jakobud** [comment]
How are you typically detecting if IE < 9? Your second point (making `flyTo` not animate) will be pretty easy using CSS3 transform detection. But what feature do we need to try to detect regarding the `setView` change?

**Comment by mourner** [comment]
I try to detect based on capabilities whenever possible (e.g. `L.Browser.any3d`), otherwise there are other props in `L.Browser`.
For `setView`, we need to use round zooms in case transforms are not available.

**Comment by Jakobud** [comment]
Do you want those zoom values to round up, down or to the nearest whole number?

**Comment by mourner** [comment]
To the nearest whole number I think, like GridLayer does.

**Comment by Jakobud** [comment]
I should be able to tackle this. I'll take a look tonight.

**Comment by mourner** [comment]
Did you look into this by chance?

**Comment by Jakobud** [comment]
I started to but got sidetracked. Sorry I am in the process of getting my house ready to sell and haven't had time to mess with lately. In a few weeks I will have more time.

**Comment by mourner** [comment]
Sure, no worries!

**Comment by IvanSanchez** [comment]
In a related note: `setView(somewhere, 9.25);` works but `flyTo(somewhere, 9.25);` crashes.

**Comment by IvanSanchez** [comment]
This is literally a 2-liner. However, IE <= 9 doesn't run `L.Map._resetView()` properly, as it somehow fails to reset the position of the tiles relative to the pane. :confused:

**Comment by mourner** [comment]
@IvanSanchez that's pretty much expected since IE9 didn't support transform transitions as far as I remember, so it can't do zoom animations properly.

**Comment by IvanSanchez** [comment]
Actually it was GridLayer's fault - it was calling code for 3d transforms without checking `L.Browser.any3d`.
