### ISSUE TITLE
Layer isPopupOpen method

### ISSUE THREAD

**Issue by piotreksenel** [Leaflet/Leaflet#3281]
Hi,

I wanted to open popup for `circleMarker` on `mouseover`, it was working correct for the `marker`, but with the `circleMarker` whenever we move mouse inside of it the popup is closed and reopened. I tried to use `mouseenter` and I found that there is a code responsible for handling that event but it's not fired, so are we suppose to use this event?

Cheers

**Comment by pufanalexandru** [comment]
If you want to prevent the popup from opening again and again, you can use the following code:
    
    //create the circleMarker
    var circle = L.circleMarker([latlng].addTo(map);

    //Bind the desired popup to the circleMarker
    circle.bindPopup('Desired content');

    //Use mouseover event to open the popup, if it's not already opened
    circle.on('mouseover', function () {
        if (!circle._popup._isOpen) {             //this is important, as it checks to see if the popup is already opened
            this.openPopup();
        }
    });

**Comment by piotrdonicz** [comment]
I used `circle._popup._isOpen` as a temporary solution, I would prefer not to use private properties and wondering if there is an option to solve that in a different way
