### ISSUE TITLE
Bug when removing tilelayer which is still loading tiles

### ISSUE THREAD

**Issue by jblarsen** [Leaflet/Leaflet#3283]
Example:

        var map = L.map('map').setView([56.5, 12.0], 5);
        var baseLayer = L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            maxZoom: 18,
            attribution: '&copy; <a href="http://www.openstreetmap.org/copyright" target="_blank">OpenStreetMap</a> contributors</a>'
        });
        baseLayer.addTo(map);
        baseLayer.removeFrom(map);

When this code is run it results in a error (this._map is null) for each tile on screen. The error originates from the _tileReady callback. (this._map is null).

As far as I can see the problem is that the tiles are not loaded when the layer is removed. And the _tileReady callback is therefore called after this._map has been set to null.

The removeFrom method for the TileLayer is defined in the Layer class. Maybe TileLayer needs to override the removeFrom method to call _abortLoading before calling the removeFrom method of the Layer class?

**Comment by mourner** [comment]
Maybe just adding a check inside `_tileReady` will be easier.

**Comment by jblarsen** [comment]
I enclosed the entire body of _tileReady in a:

if (this._map) {}

block and it worked fine. But I am a bit unsure whether parts of the method be executed even if this._map is null?

**Comment by mourner** [comment]
I'll look into it. Should be a minute fix.

**Comment by IvanSanchez** [comment]
This should be already fixed by bb230d0a
