### ISSUE TITLE
Tiles desappear after zoom (in or out)

### ISSUE THREAD

**Issue by JcDenton86** [Leaflet/Leaflet#3295]
Hello,
I am using leaflet along with cordova to build a hybrid app. I can load the map using this 
```
L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
	attribution: 'Map data © <a href="http://openstreetmap.org">OpenStreetMap</a> contributors',
	maxZoom: 12,
	minZoom:6
}).addTo(map);
```
I 've also registered on Mapbox and got an access token so to use different tiles. 
The map shows up correctly when I navigate to the map page, but when I zoom in, the tiles start to disappear and not load again in the new zoom number. I can see only the markers placed on the map and I can pan the (invisible)map but there are no tiles just squares with a broken image icon on the top left corner. Why is that?

**Comment by danzel** [comment]
You need to ```L.invalidateSize()``` after the map becomes visible.

**Comment by JcDenton86** [comment]
Hi, can you be more specific with that? Trying the above I get `Uncaught TypeError: undefined is not a function`. Changing to `map.invalidateSize()` doesn't throw any errors but the same is happening. Should I wrap it in a whenReady() event?

**Comment by danzel** [comment]
Woops, yeah map.invalidateSize.
You call it any time the map element changes size or becomes not display:none
I'm not 100% sure when this would be on Cordova sorry

**Comment by JcDenton86** [comment]
the map element is full screen and doesn't change size. Anyway it was android's permission issue. I added `<uses-permission android:name="android.permissions.INTERNET" />` and the map loads in every zoom level.
