### ISSUE TITLE
Docs don't mention that L.LatLng is not expandable by .include

### ISSUE THREAD

**Issue by akauppi** [Leaflet/Leaflet#3301]
The [plugin guide](http://leafletjs.com/2013/06/28/leaflet-plugin-authoring-guide.html) states that:

> If you want to add new methods to existing Leaflet classes, you can do it like this: `L.Marker.include({myPlugin: …}).`

However, this is not true to [`LatLng`](https://github.com/Leaflet/Leaflet/blob/master/src/geo/LatLng.js), which does not use the `L.Class` mechanism but traditional, bare bones JavaScript function-objects.

This is because of optimization reasons, right? I think the plugin guide should mention such exceptions (s.a. ", except for classes `L.LatLng`, ..."), and such classes' source code should have a comment, stating why they are not derived from `L.Class`.

`git grep ".prototype ="` shows the following classes to be non-extensible via `.include`:
- `L.LatLng`
- `L.LatLngBounds`
- `L.Bounds`
- `L.Point`
- `L.Transformation`

**Comment by mourner** [comment]
Yes, this is for performance reasons. You're right that we should mention this in the docs.

**Comment by IvanSanchez** [comment]
This will be covered by #4356 - there's a handy UML class diagram there, showing inheritances.

**Comment by jieter** [comment]
I think a small note in the docs for `L.LatLng` won't hurt, one is probably not going to read the tutorial if getting error messages while trying to do `.include()` on `L.LatLng`
