### ISSUE TITLE
Change the color of a polyline dynamically?

### ISSUE THREAD

**Issue by hanfeisun** [Leaflet/Leaflet#3305]
For example, I used `L.polyline([[0,1],[1,1]], {color: '#000'}).addTo(map)` to add a polyline to map.

However, I found that leaflet doesn't seem to provide a method to change the option of a polyline object (I mean `color` here)  after the object being created.

I tried `L.setOptions(polyline, {color:"#0F0"})` and `polyline.options.color="#0F0"`, but none of them works for existing polylines..

I was wondering whether there would be a way to change the color of a polyline dynamically..

**Comment by yohanboniface** [comment]
Try `polyline.setStyle()`.

However, this is an issue tracker, for reporting bugs with Leaflet. It's not a support forum. Please post to the [forum](https://groups.google.com/forum/#!forum/leaflet-js), you are more likely to find help there.

And thanks for using Leaflet :)
