### ISSUE TITLE
Modularize leaflet packaging

### ISSUE THREAD

**Issue by moimael** [Leaflet/Leaflet#3306]
Hi,

I'm using leaflet for a while, previously in a pure backbone app, now transitioning to a react + flux app.
Leaflet is great but always felt like an "allinone" lib, hard to cleanly integrate with other libs/framework (altough working very well).

It could be great to separate leaflet into multiple small component (ala Ampersand.js) available from npm.

I was thinking of decoupling view and state, also split different functionality (like the build script did).

That was already partly discussed here : https://github.com/Leaflet/Leaflet/issues/1364

I would be glad to hear your thoughts about this !

Thanks for your great work !

**Comment by mourner** [comment]
No, I think that at this point it'll confuse users much more than it'll help.
