### ISSUE TITLE
on-click error with Polymer and Android

### ISSUE THREAD

**Issue by MeloJR** [Leaflet/Leaflet#3309]
Hello, I am building a web component with a Leaflet map embedded. During my development I found out that Google Chrome for Android does not catch the on-click events over the map if the map is in a web component.

I have done several tests and if I use Leaflet without web components Google Chrome catch the on-click events perfectly.

Can I do something to solve this problem? Thank you!

**Comment by mourner** [comment]
I have no idea to be honest, don't have any experience with Polymer... Needs some investigation.

**Comment by mourner** [comment]
Probably not possible to fix on Leaflet side unless there's a clear reproducible JSFiddle test case and a proof that the problem is on Leaflet side.
