### ISSUE TITLE
Circle over tilelayer

### ISSUE THREAD

**Issue by nflsalex** [Leaflet/Leaflet#3311]
Hi,

I am using titelayer as background and circle to show our data. But tilelayer is always on top of circle, How can I fix that? Thanks

Yilun

**Comment by nflsalex** [comment]
I am using leaflet 0.73 seems that it does not support bringToFront

**Comment by perliedman** [comment]
@nflsalex could you post an example illustrating this problem? Ideally on jsfiddle or similar, but at least some code.

If you're using a standard tilelayer and circlemarkers on it, they should never end up below the tiles, and you shouldn't need `bringToFront`, unless you're doing something special.

**Comment by nflsalex** [comment]
@perliedman 


 <script src="/car_cities{% static 'js/TileLayer.GeoJSON.js'%}"></script>
var map = L.map('map').setView([39.7326,-98.9196], 5);

	   var style = {
       // "clickable": true,
        "color": "#0354A5",
        "fillColor": "#0354A5",
        "weight": 0.5,
        "opacity": 0.5,
        "fillOpacity": 0.3
    };
    var hoverStyle = {
        "fillOpacity": 0.5
    };

    var geojsonURL = 'http://polymaps.appspot.com/state/{z}/{x}/{y}.json';
    var geojsonTileLayer = new L.TileLayer.GeoJSON(geojsonURL, {
            clipTiles: true,
            unique: function (feature) {
                return feature.id; 
            }
        }, {
            style: style,
        }
    );
    geojsonTileLayer.setZIndex(-1)
    map.addLayer(geojsonTileLayer, true);



For circle:
	$.each(data, function(index, value) {
		L.circle([value[1], value[2]], 60000, {
			fillColor: getColorbyValue(value[3], min, max), 
			fillOpacity: 1,
			stroke: false
		}).bindPopup(value[0] + ' (' + value[3] + ')').addTo(map);
	});

**Comment by mourner** [comment]
Why do you set zIndex to -1?

**Comment by nflsalex** [comment]
@mourner  if I don't, the tilelayer is still on top of the circle. Thank you

**Comment by perliedman** [comment]
Ah, you're using `L.TileLayer.GeoJSON`, not a normal tilelayer. Might be worth checking if it's a plugin problem rather than a Leaflet problem.

**Comment by nflsalex** [comment]
Yes. I am using https://github.com/glenrobertson/leaflet-tilelayer-geojson/. Do you have an idea how to fix it? I have spent a day on it. Thank you very much

**Comment by perliedman** [comment]
From a quick look at https://github.com/glenrobertson/leaflet-tilelayer-geojson/blob/master/TileLayer.GeoJSON.js, it looks like it's internally using a `L.GeoJSON` layer (https://github.com/glenrobertson/leaflet-tilelayer-geojson/blob/master/TileLayer.GeoJSON.js#L58); it's really this layer you need to put set the z-index for.

**Comment by nflsalex** [comment]
I tried to put a zindex here, the option should be passed into the new L.GeoJSON(null, geojsonOptions), it still doesn't work

var geojsonTileLayer = new L.TileLayer.GeoJSON(geojsonURL, {
        clipTiles: true,
        unique: function (feature) {
            return feature.id; 
        }
    }, {
        style: style,
        zIndex:0
    }
);

**Comment by perliedman** [comment]
I think it's pretty clear this is an issue with the plugin, not with Leaflet, and you should post the issue with leaflet-tilelayer-geojson.

**Comment by nflsalex** [comment]
Do we have some ways to change the zIndex of 'L.GeoJSON'? or increase the zIndex of circle?

**Comment by nflsalex** [comment]
@perliedman @mourner Can I use something like 'pane'  or 'layergroup' to put circle over L.GeoJSON?

**Comment by perliedman** [comment]
If you access the actual GeoJSON layer instance, you should be able to use `bringToBack`, I guess.

As mentioned, you should discuss this problem with the leaflet-tilelayer-geojson plugin authors, since it's not a Leaflet issue, as far as I can tell.

Also, this is Leaflet's issue tracker: it's meant for discussing bugs and changes to Leaflet, not questions and answers on how to use Leaflet. There's the forum, IRC channel and gis.stackexchange.com for that. Thanks.
