### ISSUE TITLE
Disable dragging not possible as expected

### ISSUE THREAD

**Issue by netAction** [Leaflet/Leaflet#3312]
When calling *map.dragging.disable()* the mouse cursor is still a hand and it is not possible to scroll the page using touch gestures over the map.

Additionally, when a popup pans the map, there is no way to pan it back manually because of disabled dragging. When dragging is disabled, closing a popup should restore the map's position. *autoPan=false* is no workaround as it crops the popups instead of letting them overflow the map.

**Comment by mourner** [comment]
To disable touch gestures, try also `map.tap.disable()`. For mouse cursor, there's an existing ticket #3233. To restore position on popup close, subscribe to `popupclose` event and do it manually — it's pretty easy. I don't think we should introduce code complexity for a rare use case.
