### ISSUE TITLE
Zoom animation not resetting the Grid/TileLayer correctly.

### ISSUE THREAD

**Issue by rickj33** [Leaflet/Leaflet#3313]
When the zoom is animated, the grid/tile layer does not get reset correctly when the animation is done.
The tile origins return the incorrect values.
I have created a jsfiddle to demo the issue https://jsfiddle.net/rickj33/eqLdnfm7/14/
In the GridLayer code, the _reset function, gets called when the animation ends, but this statement 
if (!noUpdate && (hard || tileZoomChanged)) {
stops it from calling _updateLevels and _resetGrid,

I found this by trying to make the Leaflet-image work with the latest 0.8 version.

The console output looks like this

Origins with out animation
(index):76 tile position = {"x":-150,"y":-136}
(index):76 tile position = {"x":106,"y":-136}
(index):76 tile position = {"x":362,"y":-136}
(index):76 tile position = {"x":618,"y":-136}
(index):76 tile position = {"x":-150,"y":120}
(index):76 tile position = {"x":106,"y":120}
(index):76 tile position = {"x":362,"y":120}
(index):76 tile position = {"x":618,"y":120}
(index):76 tile position = {"x":-150,"y":376}
(index):76 tile position = {"x":106,"y":376}
(index):76 tile position = {"x":362,"y":376}
(index):76 tile position = {"x":618,"y":376}

(index):57 Origins with animation
(index):76 tile position = {"x":-31,"y":-224}
(index):76 tile position = {"x":225,"y":-224}
(index):76 tile position = {"x":481,"y":-224}
(index):76 tile position = {"x":-31,"y":32}
(index):76 tile position = {"x":225,"y":32}
(index):76 tile position = {"x":481,"y":32}
(index):76 tile position = {"x":-31,"y":288}
(index):76 tile position = {"x":225,"y":288}
(index):76 tile position = {"x":481,"y":288}

**Comment by IvanSanchez** [comment]
I don't see any strange behaviour when performing animated zooms and `flyTo()`s. Perhaps this was fixed already in https://github.com/Leaflet/Leaflet/commit/9274ee2b5f691c6f90a3615901a7fc355c884cba#diff-f1e6be67599c594731fff6191c710420R355 ?

Otherwise, it's very possible that Leaflet-image is only compatible with Leaflet 0.7.x.

**Comment by rickj33** [comment]
Yes, the Leaflet-image is only compatible with Leaflet 0.7.x. But in trying to update the code to work with Leaflet 0.8x I found the issue. If you got to http://jsfiddle.net/rickj33/eqLdnfm7/14/ then open developer tools and the console, you will see the difference in the tile positions when using animation and no animation. I would think that the coordinates would be the same after zooming. 
The fiddle is using the leaflet code from http://leaflet-cdn.s3.amazonaws.com/build/master/leaflet.js
if there is a newer one let me know an i will update and see if the issue still occurs.

Note: 
The original js fiddle i linked too, included the https which would not run the fiddle.

Thanks for investigating this.
Rick

**Comment by rickj33** [comment]
Not sure what i did that it closed the issue, but that was not my intent

Yes, the Leaflet-image is only compatible with Leaflet 0.7.x. But in trying to update the code to work with Leaflet 0.8x I found the issue. If you got to http://jsfiddle.net/rickj33/eqLdnfm7/14/ then open developer tools and the console, you will see the difference in the tile positions when using animation and no animation. I would think that the coordinates would be the same after zooming. 
The fiddle is using the leaflet code from http://leaflet-cdn.s3.amazonaws.com/build/master/leaflet.js
if there is a newer one let me know an i will update and see if the issue still occurs.

Note: 
The original js fiddle i linked too, included the https which would not run the fiddle.

Thanks for investigating this.
Rick

**Comment by mourner** [comment]
Thanks for the clarification! That should help us track down the issue.

**Comment by IvanSanchez** [comment]
@rickj33 The code controlling zoom animations and tile loading have gone through a lot of changes lately. I've checked your fiddle, and I think everything looks fine.

(I've also updated the fiddle to use the latest Leaflet build, see http://jsfiddle.net/eqLdnfm7/19/ )

Can you please check it, and tell us if the bug is gone or still there?

**Comment by mourner** [comment]
Closing, will reopen if it turns out to still be an issue.
