### ISSUE TITLE
Where is map._initPathRoot()  in development version of leaflet. 

### ISSUE THREAD

**Issue by melmeseery** [Leaflet/Leaflet#3315]
I was using  Leaflet 0.7.3 and D3 to actually render some points (circle) or hexbins ( http://projects.delimited.io/experiments/hexbins/starbucks.html)  on leaflet map.  It was working fine then I starting facing problem with zooming and loading of tiles. Some tiles just does not loading when user zoom in or out.   I tried to work with the development  version  (Leaflet 0.8 ) but now all my svg elements are not displayed.  It also says that map._initPathRoot() the function I used to initialize svg pane the does not exist any more. 

Here is the code I use to initialize the SVG panes 

```javascript
	/* Initialize the SVG layer */
map._initPathRoot()
/* We simply pick up the SVG from the map object */
var svg = d3.select("#map").select("svg"),
g = svg.append("g"); 
```
I also tried this code to get the SVG pane but still all my elements are not displayed. 

```javascript
var svg = d3.select(map.getPanes().overlayPane).append("svg"),
g = svg.append("g").attr("class", "leaflet-zoom-hide"); 
```

I have to go back to  Leaflet 0.7.3  to see all my points and I still have some problem with the zooming.

**Comment by mourner** [comment]
Try doing this instead: `L.svg().addTo(map)`.
