### ISSUE TITLE
L.tileLayer issues when zoomReverse and detectRetina are true

### ISSUE THREAD

**Issue by kobesin** [Leaflet/Leaflet#3319]
I'm not sure it's a bug. When zoomReverse and detectRetina are true, the adjusted zoomOffset may be wrong. Go to line 2458(Leaflet 0.7.3) and add check
```javascript
if (options.detectRetina && L.Browser.retina && options.maxZoom > 0) {

	options.tileSize = Math.floor(options.tileSize / 2);
	options.zoomOffset++;

	if (options.minZoom > 0) {
		options.minZoom--;
	}
	this.options.maxZoom--;
}
```
change to this

```javascript
if (options.detectRetina && L.Browser.retina && options.maxZoom > 0) {

	options.tileSize = Math.floor(options.tileSize / 2);
	if (!options.zoomReverse) {
		options.zoomOffset++;
	}

	if (options.minZoom > 0) {
		options.minZoom--;
	}
	this.options.maxZoom--;
}
```
It seems works fine.

**Comment by mourner** [comment]
Does it work in master?

**Comment by kobesin** [comment]
I just test this codes with master, it seems also works fine.

**Comment by mourner** [comment]
OK, safe to close then.

**Comment by kobesin** [comment]
Sorry, I mean the problem is also in master. If zoomReverse and detectRetina both set true in L.tileLayer options, map didn't show the tileLayer. But if go to line 31(TileLayer.js) and change
https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/TileLayer.js#L31
```javascript
options.zoomOffset++;
```
http://jsfiddle.net/lamperder/ghz3j3y6/1/

to

```javascript
if (!options.zoomReverse) {
    options.zoomOffset++;
}
```
http://jsfiddle.net/lamperder/q4puoke7/

My English isn't very good, please don't mind.
