### ISSUE TITLE
Sometimes not zooming in on marker location - marker drifts out of the map on zoom.

### ISSUE THREAD

**Issue by J-F-O** [Leaflet/Leaflet#3322]
Hello mourner.

There is an issue when zooming in on the marker with the control. Sometimes it zooms to a different spot and the marker drifts out of the map. It seems, the center of the map is calculated to one pixel and the marker on another? And the more you zoom the more the marker drifts off. This only happens once in a while, and most of the time it works as it should, so I cannot give you 'steps to reproduce' (other than try it a 100 times). So maybe it got something to do with rounding the coordinates? Anyways, just to let you know... cause when it happens, and you zoom in on the marker it seems kind of crappy that you end up somewhere else.

Source code for geolocation web page using Leaflet 0.7.3, where issue was noted, issue has occurred both with a new marker placed on the map, and with the original geolocation marker: https://github.com/J-F-O/Geolocation

Screenshot: zoom at level 15 - marker drifting off, at level 17 it is outside the map.
![zoom_15](https://cloud.githubusercontent.com/assets/9885655/6765281/45558500-cfd9-11e4-8f10-11e2d00ec015.png)

**Comment by mourner** [comment]
Can you put up a minimal JSFiddle test case?

**Comment by J-F-O** [comment]
Well I don't know how to make a test case for it... I've tested it 10-15 times now and it works as it should, but a day ago it happened 2-3 times when zooming in from setView level 7 to 18, so there is no mistake about it... or maybe it was solar winds messing up the computer? what do I know :D

Something similar to this:  https://github.com/Leaflet/Leaflet/issues/426 could it be, possibly still acting up? From one time to another, the only thing that differs that I can think of is the marker coordinates, right? And for the most it seem to work.
