### ISSUE TITLE
How to repeat a shape over the joint of two identical world maps?

### ISSUE THREAD

**Issue by chfw** [Leaflet/Leaflet#3324]
Hi all

Normally, when a OSM map is zoomed out, you will see multiple world maps repeated. Now, I am having a problem when drawing a **single**
 KML layer(a circle for example) the joint of the two maps. I would expect the circle to be closed and to be repeated across all copies. But instead, leafet.js closes the circle the other way around. I am attaching the expected and actual maps that represents my complex shapes.
![expected](https://cloud.githubusercontent.com/assets/4280312/6779895/579f9766-d158-11e4-979b-851cadbee1de.PNG)

Here's what I actually got:
![actual](https://cloud.githubusercontent.com/assets/4280312/6779902/617a2af8-d158-11e4-8d59-1551b52761ec.PNG)

Is there any way to get round this limitation?

Thanks

**Comment by jfirebaugh** [comment]
Yes, see #404 and other duplicate issues.
