### ISSUE TITLE
Map gets broken inside an hybrid app related ionic view

### ISSUE THREAD

**Issue by schuppo** [Leaflet/Leaflet#3327]
Hi leaflet team!
Firstly I want to thank for your great map framework. It helps us a lot in developing a map feature integrated inside an hybrid mobile app.
But I have one small issue which is related to the interaction between the ionic framework (a framework which provides a lot native app like features and behavior)  and the leaflet map layer which is contained inside a view of the framework. 

In its most reduced form you can see the app here: http://codepen.io/schuppo/pen/PwXMpN
The problem now is: When an modal view is opened while the nav view containing the map is in cached state the positioning coordinates of the dom element containing the map get broken. The reason is because showing a modal triggers a global window resize event and leaflet is listening to resize events too.

I have already addressed the ionic team (as you can see here driftyco/ionic#3383) but they don't think it is an issue of their framework. So now I try it here and my question is: Is there a way to make a leaflet map react more sensible to resize events of the window object? I did not analyze the reasons for the bug in our app more deeply but to me it seems that map gets broken when its surrounding view is in cached state because its cached state means that the addition of a `display: none` css attribute.

You can reproduce the behavior like this:
1. Open the pen (see link above) in chrome.
2. Click on "Show map".
3. Activate "Break on attributes modification" on "

" node.
4. Click on "Show default".
5, Click on "Show modal".
Now you should see the call stack indicating that the resize event being triggered is also listened to by leaflet.
6. When you finish the call stack and return to the map view you can see that the map content is dislocated.
Hope my issue description is clear enough. If something is missing or misleading, leave me a note. I am looking forward to your reply!

**Comment by mourner** [comment]
Does it help to pass `trackResize: false` Map option?

**Comment by mourner** [comment]
Also, maybe related: https://twitter.com/bianchimro/status/521935480766877696

**Comment by schuppo** [comment]
Sorry for my delayed reply. Very likely your first suggestion did that trick. I will test the behavior of the map in different contexts but I am quite confident that it is working right now. So thanks for your quick and helpful reply. I will close this issue now.

**Comment by mourner** [comment]
Thanks!

**Comment by DazChong** [comment]
Thanks for this log!
