### ISSUE TITLE
Leaflet tries to load tiles with negative coordinates with L.CRS.Simple

### ISSUE THREAD

**Issue by Eschon** [Leaflet/Leaflet#3329]
I managed to reproduce the error in this jsfiddle http://jsfiddle.net/Eschon/suy4pmbv/

**Comment by mourner** [comment]
This is by design. L.CRS.Simple doesn't have any bounds set by default.

**Comment by Eschon** [comment]
I actually set bounds in my project, but they are calculated after the map is created like in this fiddle http://jsfiddle.net/Eschon/m1cemf5c/

The problem still occurs. Is there anything wrong with how I set the bounds?

**Comment by perliedman** [comment]
@Eschon the map's bounds are used for preventing the user to pan outside a certain area. The CRS/projection has its own bounds, which is what you want to set here.

In particular, `CRS.Simple` has the property `infinite: true` by default, which is what @mourner refers to above. It means there are in effect no bounds to the CRS/projection. You need to set `infinite` to false and make sure the CRS's projection has its `bounds` property set to what you want. You can look at the existing CRS/projection implementations to get an idea of how to do this.

**Comment by Eschon** [comment]
@perliedman thanks, that really helped me. I wrote my own custom crs and projection and it mostly works now.
