### ISSUE TITLE
Keyboard-tabbing to an offscreen marker breaks pane positioning

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#3333]
* Create a map with at least one L.Marker (ensure the "keyboard" option of the marker is set to "true", should be the default) - http://leafletjs.com/examples/quick-start-example.html will work.
* Pan the map so that the L.Marker is partially off-screen, like so:

![out-of-screen-tabbing-1](https://cloud.githubusercontent.com/assets/1125786/6868235/2ac44aae-d48a-11e4-828f-2932b328a78a.png)

* Press "Tab" on your keyboard until the L.Marker is focused. The positioning of all map panes breaks up: see how all the L.Controls (attribution, zoom, etc) move around:

![out-of-screen-tabbing-2](https://cloud.githubusercontent.com/assets/1125786/6868236/2ac49662-d48a-11e4-965a-9558d41ebae2.png)

I can reproduce this in Firefox 35, Chrome 41, and MSIE11.

**Comment by mourner** [comment]
Confirmed, will think about this...

**Comment by IvanSanchez** [comment]
It has to do with the browser forcing the `.scrollTop` and `.scrollLeft` properties of the map container HTML element to something other than 0, even when `overflow` is set to `hidden`, which should prevent scrolling the element around.

The `onFocus` event of the marker can be handled, but behaviour varies across browsers. Just handling the event in Firefox solves the issue. Panning the map to ensure it contains the entire marker fixes it in Chrome. MSIE is the awkward boy (as usual), so there is a straightforward way of knowing if a marker is fully visible or not. Haven't tried Safari.

I'd push a branch with some ideas, but the github DDoS is preventing me from doing so.

**Comment by IvanSanchez** [comment]
Actually, I think that catching the `onScroll` event on the map container is the safest cross-browser, non-glitchy way to deal with this.

In `Map.js`:

```
	_initContainer: function (id) {
		// [.....]
		L.DomEvent.addListener(container, 'scroll', this._onScroll, this);
		container._leaflet = true;
	},

	_onScroll: function (ev) {
		this._container.scrollTop  = 0;
		this._container.scrollLeft = 0;
	},
```
