### ISSUE TITLE
Missing basic "installation" instructions for non-CDN use

### ISSUE THREAD

**Issue by teo1978** [Leaflet/Leaflet#3338]
At http://leafletjs.com/download.html
it says:
> Using a Hosted Version of Leaflet
> The latest stable Leaflet release is hosted on a CDN — to start using it straight away, place this in the head of your HTML code:

```
<link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css" />
<script src="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js"></script>
```

But it doesn't say a word about where you are supposed to place the downloaded files and how to link them if I want to use the downloaded version hosted on my own server. Specifically, whether the "images" folder should be placed in the same path where the .css and .js are, or where else.

Note that CDN cannot be used on a page served over https as per #3337, which is equivalent to saying that the CDN version is half useless.

**Comment by IvanSanchez** [comment]
Done in #3595.
