### ISSUE TITLE
Gaps between tiles while zooming (chrome 41)

### ISSUE THREAD

**Issue by jieter** [Leaflet/Leaflet#3339]
I just noticed small gaps between tiles while zooming in chromium with current master.
![test](https://cloud.githubusercontent.com/assets/1470389/6893842/8b181b68-d6d0-11e4-8f17-64854eff5122.gif)

Chromium 41.0.2272.76 Ubuntu 14.04 (64-bit)

This fiddle http://jsfiddle.net/vzLkqtf2/ has a layer with only black tiles and Stamen Toner to check.

Not reproducable on Firefox 36.0.4

**Comment by mourner** [comment]
Unfortunately there's probably nothing Leaflet can do to fix this. It's the way browser handles CSS transform transition. You can probably make this less noticeable by setting the map element background to black.

**Comment by jieter** [comment]
Ah, too bad. I thought it might be fixable, since I've seen multiple zoom/gap issues fixed...

**Comment by Trufi** [comment]
@jieter you can try removing `will-change` css property from `leaflet-tile`. It worked for me. http://jsfiddle.net/vzLkqtf2/1/

**Comment by mourner** [comment]
@Trufi note that this may significantly decrease performance in some cases, e.g. flyTo animation.

**Comment by jieter** [comment]
@Trufi yes, that works.
