### ISSUE TITLE
I want to make a menu when right clicking on the map

### ISSUE THREAD

**Issue by liujia1** [Leaflet/Leaflet#3344]
The codes are:

map.on("contextmenu",function(e) {
    		var tlatlng=e.latlng;
    		var tdiv='Hello world!';
    		/* making a popup*/
    		var tpopup = L.popup()
    		.setLatLng(e.latlng)
   		.setContent(tdiv)
   		.openOn(map);
                tpopup.on('click',alert("hello");
});

The problem is when i rightclick on the map, it pops up the alert and the popups. I thought it should pop the popups first and when I click on the popups, it alerts 'hello'. 

How should I fix this?

**Comment by Eschon** [comment]
@liujia1 on needs a function as the second argument. Try it like this:

tpopup.on('click', function(){alert("hello")});

**Comment by liujia1** [comment]
@Eschon I tried it like this
map.on("contextmenu",function(e) {
    		var tdiv='<dt id="omark" class="omark">test</dt>';
    		var tpopup = L.popup({closeButton:false})
    		.setLatLng(e.latlng)
   		.setContent(tdiv)
   		.openOn(map);
		tpopup.on('click', function(){alert("hello");});
});
It fix the problem that popups and the alert dialog show up simultaneously. But actually the alert never shows up when I click the popups.  T^T.

**Comment by Eschon** [comment]
@liujia1 I tried it and it seems like listening for click events on popups does not work, but I found a small example at mapbox.com that you could try:

https://www.mapbox.com/mapbox.js/example/v1.0.0/clicks-in-popups/

**Comment by liujia1** [comment]
@Eschon thank you . i guess it is a bug or at least a functional issue. The example at mapbox is an alternative way of doing it.  but not quite logical consistent to me. I have to operate the html dom element instead of the map object itself. but anyway i'm doing it.

**Comment by mourner** [comment]
> tpopup.on('click',alert("hello");

This is not valid JS. Also, Popup doesn't have a `click` event.
