### ISSUE TITLE
A bug with L.popup()

### ISSUE THREAD

**Issue by liujia1** [Leaflet/Leaflet#3345]
The codes are:
```
map.on("contextmenu",function(e) {
var tlatlng=e.latlng;
var tdiv='\<p onclick=alert('+tlatlng+')\>test\</p\>';
/* making a popup*/
var tpopup = L.popup()
.setLatLng(e.latlng)
.setContent(tdiv)
.openOn(map);
});
```
Actually when i click on the button "test" when the popups shows on the map, nothing happens. I checked the html code and the button element. The html file shows 
\<p onclick="alert(LatLng(65.89866," -252.55079))=""\>test\</p\>
it seems like the setContent() does a wrong transformation.

is it a bug?

**Comment by danzel** [comment]
The bug is your html.
Try 
```
var tdiv='<p onclick="alert('+tlatlng+')">test</p>';
```

**Comment by liujia1** [comment]
@danzel acutally, that's what i worte.
var tdiv='<p onclick="alert('+tlatlng+')">test</p>';

In case this website filter those "<" ">" mark, i used "\". 

So can you consider this issue again?

**Comment by danzel** [comment]
Ok reopened. Can you please make a jsfiddle with this example?

**Comment by liujia1** [comment]
I don't know how to use jsfiddle. it's too elgant for me. May I post my short code herein?

&lt;!DOCTYPE html&gt;
&lt;html&gt;
&lt;head&gt;
	&lt;meta http-equiv="Content-Type" content="text/html" charset="utf-8"/&gt;
	&lt;meta name="viewport" content="initial-scale=1.0, user-scalable=no" /&gt;
	&lt;script type="text/javascript" src="http://libs.baidu.com/jquery/1.10.2/jquery.min.js"&gt;
&lt;/script&gt;
	&lt;link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css" /&gt;
	&lt;script src="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js"&gt;&lt;/script&gt;
&lt;script&gt;	
	var map=new Object();
	function initialize()
	{
			map = L.map('Map').setView([0, 0], 1);
			L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png',
				{attribution: 'Marklancer &copy;'}				
			).addTo(map);
			map.locate({setView:true});
			$("div#Map").bind("contextmenu",function(e){
        return false;
    	});
    	map.on("contextmenu",function(e) {
				var tlatlng=e.latlng;
				var tdiv='&lt;p onclick=alert('+tlatlng+')&gt;test&lt;/p&gt;';
				/* making a popup*/
				var tpopup = L.popup()
				.setLatLng(e.latlng)
				.setContent(tdiv)
				.openOn(map);
			});
	}
&lt;/script&gt;
&lt;title&gt;Marklancer&lt;/title&gt;
&lt;style type="text/css"&gt;
  	html { height: 100% }
  	body { height: 100%; margin: 0; padding: 0 }
  	#map_canvas { height: 100% }
&lt;/style&gt;
&lt;/head&gt;	
&lt;body  onload="initialize()"&gt;	
&lt;div id="Map" style="width:100%;height:480px;"&gt;&lt;/div&gt;
&lt;/body&gt;
&lt;/html&gt;

**Comment by danzel** [comment]
Put that in jsfiddle and it'll make a site

**Comment by mourner** [comment]
I think it's a bug in your code, not Leaflet, since you're trying to pass a latlng object in place where you expect a string.

**Comment by liujia1** [comment]
Well, shouldn't the alert dialog show Object object?

**Comment by sisou** [comment]
@mourner was correct, it's a bug with your string escaping. This works:

    var tdiv='<p onclick="alert(\''+tlatlng+'\')">test</p>';
