### ISSUE TITLE
Map drag is broken in Opera 12

### ISSUE THREAD

**Issue by RLRR** [Leaflet/Leaflet#3348]
**Steps to reproduce:**

1. Open a map in Opera 12
2. Try to drag it

**Result:** tiles don't move at all.

**Versions:** Opera 12.16, Ubuntu 14.04.

The bug occurs in current master. `git bisect` points at this commit: https://github.com/Leaflet/Leaflet/commit/6e5d3e26e64665e32749fe1caed6426e208d796b

**Comment by danzel** [comment]
Related #2574

**Comment by mourner** [comment]
Closing here unless you can point out really strong reasons to support such an obscure browser version that was superseded a long time ago.

**Comment by Trufi** [comment]
Many people don't want move to Opera with webkit and continue to stay on the 12 version. Our statistics show that Opera 12 is used as often as the IE8.

**Comment by mourner** [comment]
OK, makes sense. I merged that pull — counting on you to make sure everything works on Opera 12. :)

**Comment by Trufi** [comment]
Thank you! : )
