### ISSUE TITLE
 circle layer  disappears in max  zooming for mapbox

### ISSUE THREAD

**Issue by kiran15** [Leaflet/Leaflet#3350]
IN map When i do the  max zooming   circle layer  disappears in   maxzoom level at 18 but coming at level  17 and i m not want set max zoom is there any way to find the solution

**Comment by mourner** [comment]
Can you set up a JSFiddle with the issue?

**Comment by mourner** [comment]
SVG probably can't handle a circle of such a size...

**Comment by kiran15** [comment]
but without that vehicle marker icon geofences circle display about max zoom if i click on marker (i set if click on marker it will  display max zoom map  with  icon with popup details about icon and in geofances circle ) geofences disappears
(without click zoom level =4 if click on the marker zooming level=18)  

the marker on clicke code is:
vm.marker().on('click', function() {
                var data = vehicle.get('current_data');
                this._trail.setProperties({
                    checkins: data.map(toProcessed.bind(null, vehicle, faults, lightDuty)),
                    vehicle: vehicle,
                    isClick: false
                });
                if (!_.isEmpty(data)) {
                    
                    var lineBounds = this._trail.getLineBounds();
                  
                    this.map.fitBounds(lineBounds, {
                        padding: [29, 29]
                });

                }
            }.bind(this));

**Comment by mourner** [comment]
> I cant set in JSFiddle 

I need a minimal reproducible test case to be able to approach this issue.

**Comment by kiran15** [comment]
I got issue but i dont no how to solve, when we creating circle geofences  in  particular zoom level we set the radius in my map minzoom=4 and maxzoom=18 in that i set radius on circle when click on map check zoom level and set  the radius automatically  ,(if i click on map that time zoom level is 4 than it take radius take 75000m show the circle ) 

this my code:
 function getHalfRadius(zoom) {
            switch (zoom) {
                case 4:
                    HalfRadius = 750000;
                    break;
                case 5:
                    HalfRadius = 420000;
                    break;
                case 6:
                    HalfRadius = 200000;
                    break;
                case 7:
                    HalfRadius = 100000;
                    break;
                case 8:
                    HalfRadius = 50000;
                    break;
                case 9:
                    HalfRadius = 25000;
                    break;
                case 10:
                    HalfRadius = 10000;
                    break;
                case 11:
                    HalfRadius = 6000;
                    break;
                case 12:
                    HalfRadius = 3000;
                    break;
                case 13:
                    HalfRadius = 1500;
                    break;
                case 14:
                    HalfRadius = 750;
                    break;
                case 15:
                    HalfRadius = 300;
                    break;
                case 16:
                    HalfRadius = 150;
                    break;
                case 17:
                    HalfRadius = 100;
                    break;
                case 18:
                    HalfRadius = 50;
                    break;
            }
        }
this working fine when geofences equal to radius 75000m or less than that,
if you create geofance  less than that 75000m or equals,  onclick in  marker maxzoom 18 geofence appears there is no problem in geofence in circle but  (in creation of circle we can drag the geofence and we increase the radius of more than 75000m ) if i create more than that radius 75000m that time if click on marker it disappears  the maxzoom level 18 (in creating circle if increase the radius more than 75000m that time if increase zoom level about 18 circle will disappears we are svg to create circle)

**Comment by mourner** [comment]
So, can you provide a minimal JSFiddle with the problem?

**Comment by DarrylLeckenby** [comment]
I'm able to reproduce this issue when adding a circle (transparent fill with red border) to the map with a radius of 50 metres. On a map the circle stops displaying when at zoom level 19 and 19 (19 being my max zoom). At zoom level 18 it does not draw off the screen so I would not expect this behavior as using any excessive resources.

I note this may be hard to re-produce because it has been very hard for me to reproduce it. I can confirm it happens only on a few specific phones but confirmed on a physical S2Mini Android 4.4.2 and a browserstack Galaxy Note 3 Android 4.3. Also, on those phones it can only be seen using the Android stock browser.
