### ISSUE TITLE
Set the maxNativeZoom before blank page in mapbox

### ISSUE THREAD

**Issue by kiran15** [Leaflet/Leaflet#3353]
We're using the leaflet JavaScript API with a tile layer which supports. in different place different zooming level supports some place 17 and some place 19 .I'd like to zoom about supports the zooming level in different place if not supports zoom level that time maxNativeZoom will be set 17 0r 19 depends on zooming level supports,that time  i want stretch the map automatically not before zooming level supports Is this possible ? any one get this ans please reply me (already i used maxNativeZoom set 17 its working fine but after 17 its stretch i want stretch when zooming level not supports )
OR any other way to solve this problem

**Comment by kiran15** [comment]
In map canada saskatoon  maxzoom level 17 in other place its 19 how to control  please guide for this

**Comment by mourner** [comment]
I don't think it's directly possible in Leaflet currently, since you'd have to have some server-side API that would indicate what areas are covered, and change `maxNativeZoom` dynamically on map movement.

**Comment by jekuno** [comment]
The GoogleMaps JS API has a `MaxZoomService` which returns supported zoom levels for a certain geolocation by the method `getMaxZoomAtLatLng()`. Probably APIs of other map providers have similiar methods.

@mourner Did I get you right that currently leaflet doesn't support such APIs? Both maxZoom and maxNativeZoom need to be set by the user manually?

**Comment by mourner** [comment]
@jekuno yes, since Leaflet is not an all-in-one integrated service – it's just a JS library, while every developer choses a service provider to go with it on its own.

**Comment by jekuno** [comment]
@mourner Thanks for your answer. A manual implementation for all relevant map providers would indeed be the way to go then.
