### ISSUE TITLE
how to unspiderfy cluster mapbox markers 

### ISSUE THREAD

**Issue by kiran15** [Leaflet/Leaflet#3354]
how to unspiderfy cluster mapbox markers  on clicking and one zooming  ??
![kiranspderfy](https://cloud.githubusercontent.com/assets/8223463/6982065/f8d91376-da29-11e4-94a8-4b1ababba6b8.png)

**Comment by mourner** [comment]
This is not a place to submit markercluster plugin issues. Please go to the markercluster repo.
