### ISSUE TITLE
Tiles not loading when panning the map on requestAnimationFrame()

### ISSUE THREAD

**Issue by iaaaan** [Leaflet/Leaflet#3355]
Hi,

Here is a jsfiddle documenting the issue:
https://jsfiddle.net/ft4qr9r2/3/
It could be related to https://github.com/Leaflet/Leaflet/issues/3196
Worth noting: this was working in a previous version of leaflet (not sure which one, I can look into it!)

There might be a smarter way to incrementally pan the map, or to force the redrawing of the tiles... But I could not find it.

Thanks for your great work!

**Comment by danzel** [comment]
Might be worth looking at how flyTo implements this?
https://github.com/Leaflet/Leaflet/blob/master/src/map/anim/Map.FlyTo.js

**Comment by mourner** [comment]
Looks like a valid bug — `map.panTo` should fire events that get the map to update, not sure what's happening here — will investigate.
