### ISSUE TITLE
bindPopup click with DivIcon

### ISSUE THREAD

**Issue by Juleffel** [Leaflet/Leaflet#3357]
Hi !

I have a problem with the function bindPopup applied to a marker which has a Icon of type [DivIcon](http://leafletjs.com/reference.html#divicon). This issue appears in a compiled version of master from today (5 april - 11:30) and not in the stable version 0.7.3. I have the same comportement on Firefox (Version = 37.0) and on Chrome (Version = 41.0.2272.118 m) ; both on Windows 7.

When I create a DivIcon with an html like the following code (a simple red point), it is then impossible to click on the circle to make the popup appear. But if you click on the extreme corner of the divIcon (not on this circle but still on the .my-div-icon), the popup appears.
```html
<div style='width: 100%; height: 100%; border-radius: 50%; background-color: red'/>
```

I have created two jsfiddle to illustrate my point, the [first](http://jsfiddle.net/adwth6xn/10/) with Leaflet on master, the [second](http://jsfiddle.net/y5ju07zp/3/) with Leaflet v0.7.3. The code is simply the basic example of the documentation to which I have added a DivIcon.

You can see that on the first you can click on blue part (corners) but not on the red part (circle). On the second, you can click on both.

Thanks for your wonderfull work and your support!

**Comment by pufanalexandru** [comment]
Plus one! 
I have observed that this also happens when using Leaflet.awesome-markers plugin, you can only click at the border of the icon. 
http://jsfiddle.net/pufanalexandru/am454ygc/1/

**Comment by Trufi** [comment]
I think it's the same problem as in https://github.com/Leaflet/Leaflet/pull/3288

**Comment by Juleffel** [comment]
Yes, well seen, and it's corrected as the issue mentionned. I close.
