### ISSUE TITLE
Markers not clickable, when overlay pane positioned over

### ISSUE THREAD

**Issue by laacz** [Leaflet/Leaflet#3359]
What did I do: Created simple map, added L.marker and L.circle. Repositioned `.leaflet-overlay-pane` with CSS `z-index` on top so circles are visible at all times. 

Expected behaviour: Both circle and marker should be clickable.

Actual result: Only circle is clickable. Overlay pane hijacks all mouse events.

[Demo can be seen here](http://laacz.lv/tmp/leaflet-markers-not-clickable.html).

**Comment by mourner** [comment]
That's kind of expected result with the overlay pane taking the whole map space, you can't overcome this unless you manually set `pointer-events: none` on the pane (not supported in older browsers though).
