### ISSUE TITLE
Baidu layer (plugin)

### ISSUE THREAD

**Issue by dandv** [Leaflet/Leaflet#3361]
For the Greater China region, a Baidu Map plugin, [similar to Pavel Shramov's plugins](http://leafletjs.com/plugins.html) for Googel and Bing, would be very helpful.

I've created a Wikipedia page about [Baidu Maps and their BD-09 coordinate system](https://en.wikipedia.org/wiki/Baidu_Maps#Coordinate_system.

Baidu has an [extensive API](http://developer.baidu.com/map/) with large rate limits. The documentation is in Chinese, but installing the Google Translate extension makes it relatively readable.

So far I've found the API for returning tiles. They're branded with Baidu's logo, but hopefully someone else can pick up from here.

```js
"http://api.map.baidu.com/staticimage?center="
  + lon + "," + lat 
  + "&width=" + width + "&height=" + width + "&zoom=" + zoom;
```

Result of http://api.map.baidu.com/staticimage?center=121,31&width=300&height=300&zoom=15:

![Baidu map tile](http://api.map.baidu.com/staticimage?center=121,31&width=300&height=300&zoom=15)

https://github.com/sureleo/leaflet-baidu seems like the most promising project to incorporate.

Random code that adds a Baidu layer to OpenLayers:

* https://github.com/shitao1988/baidu/blob/master/OpenLayers.Baidu.js

* https://github.com/Cao-Bin/cao-bin.github.io/blob/47467436705438a77c661d8511b8ae7ede336f76/article/2015/02/ol2baidumap/index.html#L83

* https://github.com/talk2js/project/blob/master/talk2gis/WebRoot/js/lib/talk2js/gis/openlayers/layer/Baidu.js

**Comment by mourner** [comment]
Thanks a lot for the suggestion. This is an issue tracker though — it's for tracking Leaflet core issues. Plugin requests like this should go to a forum or our UserVoice page.
