### ISSUE TITLE
LayerGroup.clearLayers() throwing NotFoundError when in IE11 Only

### ISSUE THREAD

**Issue by mikelittman** [Leaflet/Leaflet#3364]
In Chrome, Safari, and Firefox this issue does not present itself.
It appears when trying to run the LayerGroup.clearLayers() or Map.remove() method, IE11 will throw a NotFoundError. Anyone else experiencing this issue?

**Comment by IvanSanchez** [comment]
Can you please provide a webpage where this is reproducible?

**Comment by mikelittman** [comment]
At the moment I am unable to provide access to this page as it is behind a login gate and I do not have authorization to bypass this.

I can provide stack trace information.

**Comment by mourner** [comment]
@mikelittman can you recreate a minimal test case that reproduces the problem in e.g. JSFiddle?

**Comment by mourner** [comment]
No reproducible test case so closing.
