### ISSUE TITLE
Feature request: set exact z-index of a marker

### ISSUE THREAD

**Issue by toebu** [Leaflet/Leaflet#3365]
At the moment, the z-index of a marker is set based on its latitude. One can influence the z-index with `setZIndexOffset`. This however only ads an offset to the calculated z-index. The z-index of the marker is still calculated based on the latitude plus this offset.

I would like to propose a new option to be able to set the exact z-index of a marker. Use case: A map where not all the shown markers are equally important. I could for example want to set the z-index based on a rating the place that the marker represents has, or the size of the place (in my case I'm showing restaurants on a map and want the higher rates ones to always be in front of lower rates ones). These attributes are not related to the latitude, so having the latitude included in the calculation of the z-index prohibits satisfying this use case.

If you don't agree that this would be useful, or would complicate the API too much, I would at least suggest to add a parameter to be able to switch of setting the z-index altogether. Then at least one can overwrite it in CSS without using `!important`.

If you agree to introduce this feature, I would code it up and make a PR (after agreeing on the API with you).

Thanks for considering this request! (I saw that this was briefly discussed in #741, but I think it should be considered again given the use case I explained.)

**Comment by mourner** [comment]
Hmm, yeah, that's not the first time the current way causes confusion. I think it might make sense adding an optional `zIndex` option (not used by default) and `setZIndex` method to control zIndex precisely. If set, Leaflet would use it instead of latitude-based+offset zIndex.

**Comment by danzel** [comment]
http://leafletjs.com/reference.html#marker-zindexoffset
This might be useful?

**Comment by mourner** [comment]
@danzel see the first sentence :)

**Comment by danzel** [comment]
lol true :)

We use zIndexOffset ourselves for this, we just add enough that it'll appear above any other markers of lower priority (like 1000 or something).

**Comment by toebu** [comment]
@danzel: that's possible if you only want a few "layers" of markers and don't care how they are z-index-ordered within that layer. I would like however to have a very fine grained control, i.e. a marker with a rating of 4.93 should be in front of one with 4.92.

@mourner: I'll prepare a PR in the next week or so with the new option and new method.
I would make it behave the following way:
- If only `zIndex` or `zIndexOffset` option is given, the corresponding method for setting the z-index is used.
- If `setZIndex` is called, it will switch to setting the absolute z-index.
- If `setZIndexOffset` is called, it will switch setting the z-index with the latitude-based value.
- What happens however if during the creation of a marker, both `zIndex` and `zIndexOffset` option are given?

**Comment by danzel** [comment]
I'm still not totally sold on this, but maybe.

If you have two markers that have the same zIndex, the order will be decided by the order they were added to the map (I think?)
So sorting by just rating could lead to weird looking overlaps (assuming there are overlapping markers of the same rating)

For 2dp ratings, you could do ```setZIndexOffset(rating * 100000)```. We have heaps of z-index range to work with and it keeps the lat-sorting of the default z-index working.

**Comment by toebu** [comment]
OK, I see your point. This works If I know in which bounds the z-index based on the latitude is set. Is there a fixed upper bound?

**Comment by danzel** [comment]
I don't think so, IIRC we init it when a zoom happens then it gets +/-'d as the user scrolls up and down.

The z-index should only matter when the markers overlap, so as long as a 0.01 rating is at least markericon.height pixels different then it will work fine.

**Comment by toebu** [comment]
So I implemented a solution now that assumes that the latitude-based z-index will always be below 1000. This means I'm using ridiculously high z-indices that go up to 700000. But it seems to work fine.

So from my end we can close this issue. Even though I think that it would be nice to be able to tell Leaflet to drop the latitude-based part. It is a good solution that works and look good in most of the cases. To enforce it however seems like to strict to me.

Thanks for the good support and for reacting so quickly!

**Comment by danzel** [comment]
Cool :+1:
Up to @mourner whether directly setting the zIndex should be supported. I vote for leave it as is.

**Comment by mourner** [comment]
Thanks finding a solution, guys! I think we should close now and reconsider if someone else comes up with a similar use case that can't be easily solved. Simpler = better.

**Comment by diegomura** [comment]
I agree with @toebu that this would be a nice feature. In my case, I have like a 'drawn in the map' markers list where the user can order them. The only way I found to have that fine grained control was by setting `marker._icon.style.zIndex` directly, which is of course awful.
