### ISSUE TITLE
Replacement for CloudMade's /shortest.js function 

### ISSUE THREAD

**Issue by aureliogandra** [Leaflet/Leaflet#3366]
Hi,

Last year I've been working on a project that requests the shortest path on CloudMade given 2 coordinates and it plots the route with JxMAP.

my_route = JsonReader.readJsonObjFromUrl("http://routes.cloudmade.com/28bd515edca9463d89460039aaa8671a/api/0.3/" + startpoint + "," + endpoint + "/car/fastest.js");

And it would give me the shortest path between the points.

I can't work with cloudmade anymore, so I would like to know if there is any service I could pull the function from.

Thanks

**Comment by mourner** [comment]
Check out http://project-osrm.org/.

**Comment by fedechagu** [comment]
@depadua inbox
