### ISSUE TITLE
Semi Circle clashes when start angle greater than stop angle

### ISSUE THREAD

**Issue by inclanfunk** [Leaflet/Leaflet#3368]
I am using the [Semi Circle plugin](https://github.com/jieter/Leaflet-semicircle) and noticed that if the start angle is greater than the stop angle, the circle is not draw as desire.
I know it is not a leaflet issue, but I was wondering:
If there is a clash between the plugin and the leaflet library where should I start to search for a workaround ?

**Comment by mourner** [comment]
I have no idea, but you shouldn't open an issue here unless you're sure it's a Leaflet issue. I'd start with the plugin code.

**Comment by jieter** [comment]
As I've written in the known issues:
> Not really robust yet for cases when startAngle is bigger than stopAngle.

**Comment by inclanfunk** [comment]
Sorry guys. My point was just to find an solution or a work around. No offence.
