### ISSUE TITLE
Fix overlays being out of sync with Google Map motions (pan, zoom)?

### ISSUE THREAD

**Issue by trusktr** [Leaflet/Leaflet#3370]
If you check this map out ([mapsmarker.com](https://www.mapsmarker.com/)), you notice that if you choose any of the Google layers, then when you pan or zoom the overlay will move out of sync with the map.

Is there a way to fix this?

**Comment by mourner** [comment]
This is not a place to report plugin issues, and not a support forum. Try asking on the Leaflet forum, or report to MarpsMarker developers.

**Comment by trusktr** [comment]
@mourner I made a topic in the Google Group: https://groups.google.com/forum/#!topic/leaflet-js/tK8QeHeORq4

**Comment by trusktr** [comment]
Honestly, this place is probably better than the Google Group. Why not just add a `discussion` label to it?

**Comment by mourner** [comment]
Because adding lots of discussions that don't necessarily require attention of the project maintainers only makes their work harder, slowing down development process and making issues harder to manage.

**Comment by trusktr** [comment]
Hmmm, I think this is a more general question: How do we sync a layer containing a 3rd party renderer (f.e. Google Maps) with Leaflet's animations? It doesn't seem easily possible (it would be very hacky).
