### ISSUE TITLE
Leaflet auto zoom adding memory in google chrome

### ISSUE THREAD

**Issue by Bravoz** [Leaflet/Leaflet#3374]
Hi,

I have used setinterval method for auto zoom. In chrome memory is getting added. Any code correction to be made.

map = L.map('map', { zooms: [4, 5, 6, 7, 8, 11] }).setView([36.99, -101.47], 4);
            L.tileLayer('tiles_jpeg/{z}/{x}/{y}.jpg', { attribution: '© <a>FDS</a>', nativeZoom: [4, 5, 6, 7, 8, 11], unloadInvisibleTiles: true, updateWhenIdle: false, reuseTiles: true }).addTo(map);

setInterval(function () {
                var zoomNumber = null;
                zoomNumber = map.getZoom();
                if (zoomNumber == 11) { zoomNumber = 3; }
                zoomNumber = zoomNumber + 1;
                if (zoomNumber == 9) zoomNumber = 11;
                map.setView(new L.LatLng(36.99, -101.47), zoomNumber, { animate: true, duration: 15.0 });
                clearInterval(zoomNumber);                                
            }, 5000);

**Comment by mourner** [comment]
Do you see the same behavior with the master version?

**Comment by Bravoz** [comment]
Where can I find master version?

**Comment by Bravoz** [comment]
Yes its add memory in chrome browser in master version to

**Comment by mourner** [comment]
I think it's perfectly normal for Chrome memory to go up since it's loading more images with each zoom. It's a browser's responsibility to decide how to handle memory for tiles. We can't "fix" this on the Leaflet side.
