### ISSUE TITLE
In NDV3 how to  calculate  x-axis even hours in particular point  

### ISSUE THREAD

**Issue by kiran15** [Leaflet/Leaflet#3378]
Currently i am using NVD3 multiBarHorizontalChart.The issue is that i need to set the tick intervals to even points in the format HH:MM:SS
For example: 00:00:00,02:00:00,04:00:00...
   code:    chart.yAxis
                 .tickFormat(function (d) {
                    
                })
The value passed to d is in seconds. On conversion seconds to HH:MM:SS formate even through i get the the value,but its not in the regular interval.

**Comment by mourner** [comment]
I have no idea what you're talking about but it apparently has nothing to do with Leaflet.
