### ISSUE TITLE
Multipolygon not editable

### ISSUE THREAD

**Issue by kespindler** [Leaflet/Leaflet#3381]
This seems to be a glaring omission, but multipolygons seem to be not editable in Leaflet. 

Specifically, I cannot delete polygons from a multipolygon nor edit existing ones.

I can do so if I have multiple features in a geojson, consisting of separate Polygon objects. But it doesn't work if there is a single MultiPolygon type.

**Comment by mourner** [comment]
This is not a Leaflet issue. If you're using something like Leaflet.draw plugin for editing, submit an issue there.

**Comment by kespindler** [comment]
Oops, will do. Thanks for quick response.
