### ISSUE TITLE
IE 11, Surface Pro 3, Difficult to click Markers with Surface Pen (usually triggers map drag)

### ISSUE THREAD

**Issue by DBemis** [Leaflet/Leaflet#3382]
Overview:
We noticed an odd issue now that some people have started using a site we are working on when using their Surface Pro 3 with a pen in IE 11.

I was able to repeat the issue using the leaflet tutorials (specifically, I tried Leaflet on Mobile and Markers with Custom Icons)

Issue:
When trying to use the Surface Pen in IE 11, most of the time it just moves the map around (just a tiny bit, maybe a few pixels) instead of registering the click event to show the popup. If I keep trying to tap the marker it will eventually show the popup

Using a finger to tap the markers works fine in the same scenario. Also, using the pen in Chrome on the same device works fine

Versions:
I was using 0.7.3, and tried upgrading to the latest 0.8-dev, but the issue remained

**Comment by mourner** [comment]
Hmm, I don't have a Surface device to confirm this... @danzel any ideas?

**Comment by mourner** [comment]
No people to help figure this out so out of scope.
