### ISSUE TITLE
Possible Memory Leak with map.addLayer

### ISSUE THREAD

**Issue by domi771** [Leaflet/Leaflet#3399]
I created a few weeks back the following real-time map based on leaflet:

https://map[.]virustracker[.]net

when looking at the memory usage I noticed two patterns which cause the memory usage to increase:

1) Zooming in and out
2) map.addLayer

It seems like although the markers are removed correctly from the map that they are never removed from the browsers memory. This issue is in all browsers the same. What I am doing wrong? I did quite extensive research on the topic and invested substantual time but I can not see where I am doing the mistake(s). 

If anybody needs parts of the code please let me know.

**Comment by mourner** [comment]
Please:

1. Make a minimal JSFiddle test case reproducing the leak
2. Describe browser / OS versions where the leak is reproducible.
3. Try it on Leaflet master version and see if it's the same.
