### ISSUE TITLE
L.divIcon incompatible with marker alt text

### ISSUE THREAD

**Issue by remilev** [Leaflet/Leaflet#3400]
Hello, I'm using latest leaflet stable 0.7.3.

* After creating a marker with a "regular' L.Icon and an alt text option set, 
I change icon on certain user action using setIcon();
If the new icon is a L.divIcon one (only, no problem if not), the alt text wil disappear from the DOM.
If a change again and set the first icon, alt text comes back.

* If I create a marker directly with a divIcon, there is no alt text at all.

--> DivIcon has no "alt text capabilities" ?
It is maybe intended, because documentation says : "DIvIcon Represents a lightweight..."

Note : I'm using divIcon in this case for animation of icon using css @keyframes. My divIcon is created like this :
<code>var DraggableIcon = L.DivIcon.extend({ options: { className: 'drag-icon', iconSize :[38, 95], iconAnchor : [22, 94], popupAnchor : [-3, -76]} });
var dragIcon = new DraggableIcon({className: 'drag-icon'});</code>

**Comment by mourner** [comment]
This works as intended since `alt` attribute is only defined for `img`, `area` and `input` elements: http://devdocs.io/html/attributes#alt

To make divIcon accessible, you could add some text inside the HTML and then hide it with CSS.

**Comment by remilev** [comment]
Of course! No alt attribute for div. Sorry I was sleeping :)

Actually, I use alt for accessibility and for adding a "hard coded" link between leaflet markers and their DOM representation : I put marker._leaflet_id (plus some text) in there in order to retrieve my markers (whose I put in an markerMap array) on some actions not covered by leaflet ($(document).keyup, ...)
It is a bit tricky but it works. That's why the lack of alt on divIcon made my code break :)

Sorry for disturbing and thanks for your reply
