### ISSUE TITLE
bindPopup giving error on click

### ISSUE THREAD

**Issue by virtual-monk** [Leaflet/Leaflet#3402]
$.get( "/events.json", function( data ) {
      var coordsArray = [];
      for (i=0; i<data.length; i++) {
        var coordinatesArray =  [data[i].latitude, data[i].longitude];
        var marker = L.marker([coordinatesArray[0],coordinatesArray[1]]);
        marker.addTo(map);
        //build up popup content html string
        var popupHTML = data[i].date
        marker.bindPopup(popupHTML);
      }
    });

I'm trying to pull multiple locations from my database. I have a separate map page that loads the markers without a problem, but my popups keep giving me an error `Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'`.

**Comment by danzel** [comment]
What type is ```data[i].date``` ?
Callstack would be good too.

**Comment by virtual-monk** [comment]
It is in a string. I started a new app and It's working fine now. 
    $.get( "/events.json", function( data ) {
    showCoordinates = []
    for (i=0; i<data.length; i++) {
      var coordinatesArray =  [data[i].latitude, data[i].longitude];
      var marker = L.marker([coordinatesArray[0],coordinatesArray[1]]);
      marker.addTo(map);
      var popup = "<h1>" + data[i].title + "</h1>"
      popup += "<h3>" + data[i].date + "</h3>"
      popup += "<h3>" + data[i].start_time + "-" + data[i].end_time + "</h3>"
      marker.bindPopup(popup);
     }

**Comment by mourner** [comment]
> It's working fine now. 

Great! :)

**Comment by virtual-monk** [comment]
Thanks for the help.

**Comment by bharathnav** [comment]
#4784 Error in popup layer after upgrading from 3 to 3.8.2 #4784.

Could someone help me on this please?
