### ISSUE TITLE
map.panTo() stop working after toggling layers 

### ISSUE THREAD

**Issue by cesarGimenez** [Leaflet/Leaflet#3403]
Here in my toggling layers example: http://jsfiddle.net/5mm1o3d5/3/ when the user show a layer (food/shop) for the first time, the map center on markers coordinates when clicked them, but when the user remove and show a layer for second time the line 81 of the script: map.panTo(e.layer.getLatLng()); stop working but the rest of the code work. can anyone help me to find out what I am missing? any help would be appreciated. thanks!

**Comment by IvanSanchez** [comment]
First: Please don't use Github issues for getting help. Use the user forum for that. This is for bugs with the Leaflet code itself.

Second: Don't hook up event handlers for the markers inside the layer toggling code. That will make your event handler run twice if you toggled the layer off and on twice (et cetera). Add the event handlers to the markers before being added to the map, and do that just once.

**Comment by cesarGimenez** [comment]
Ok, and thanks for your suggestion, I think fix my issue..

updated code:http://jsfiddle.net/5mm1o3d5/6/
