### ISSUE TITLE
Pass event parameter when map auto-adjusted / auto-zoomed

### ISSUE THREAD

**Issue by mclapa** [Leaflet/Leaflet#3407]
On such events as fitBounds can we have an parameter returned that lets us know if the final map's zoom and boundary coordinates differ than the ones initially provided by the function call.

In other words when calling fitBounds (latLng, latLng) if the map requires a re-adjust to fit the bounds, let us know so we can work around it.

Something along these lines work

this.fire('moveend', {adjusted:true});

this.fire('dragend', {adjusted:true});

so we can do something like

.on('moveend dragend', function(e) {
if (e.adjusted) {alert ('adjusted')};
}

**Comment by IvanSanchez** [comment]
I don't think this is needed in the leaflet core.

```javascript
map.fitBounds(myBounds).once('moveend',function(){
  if (map.getBounds() != myBounds) {doSomething();}
});
```

**Comment by mourner** [comment]
Yeah, there's a workaround so I don't think we need to add this in core. Simpler is better.
