### ISSUE TITLE
"L.latLngBounds" behavior differs from "new L.LatLngBounds"

### ISSUE THREAD

**Issue by aparshin** [Leaflet/Leaflet#3408]
If I want empty bounds, I can write

```
var bounds = new L.LatLngBounds(); //returns empty bounds
```
but can't write
```
var bounds = L.latLngBounds(); //returns undefined
```

Is it intended behavior or a bug?

**Comment by IvanSanchez** [comment]
Intended behaviour. RTFM, http://leafletjs.com/reference.html#class :

> You may have noticed that Leaflet objects are created without using the new keyword. This is achieved by complementing each class with a lowercase factory method:

> ```
new L.Map('map'); // becomes:
L.map('map');
```

**Comment by IvanSanchez** [comment]
Note to self: do not close things too hastily disregarding them as newbie questions.

Seems like intended behaviour, as per https://github.com/Leaflet/Leaflet/blob/665e7666086c8c5f1512c22b23090346bfbece23/src/geo/LatLngBounds.js#L157 - notice that geometry/bounds.js also has that code.

**Comment by yohanboniface** [comment]
Sounds like the initial question was about the different signature of `new L.LatLngBounds` (which accept no arguments and returns an empty bounds) and `L.latLngsBounds()` (which returns `undefined` when empty bounds), which I'm not sure is intentional actually.

**Comment by IvanSanchez** [comment]
It's a bit weird that the code for that hasn't been touched since 2012. I'm not really sure.

**Comment by yohanboniface** [comment]
I would remove `!a || ` from the check given that an `undefined` `a` is already covered by `LatLngBounds` constructor it seems. And consistent signature and responses are better :)

**Comment by mourner** [comment]
As per my https://github.com/Leaflet/Leaflet/pull/3409#issuecomment-99540622, I think we shouldn't make the constructor behave exactly like factory, but at least we should patch the empty bounds case because it's very common.

**Comment by aparshin** [comment]
> As per my #3409 (comment), I think we shouldn't make the constructor behave exactly like factory

From the user's point of view, it will complicate the API: for each class you must remember two sets of parameters. One for the constructor and another one for the factory. Not sure that even perfect documentation will help here...

**Comment by mourner** [comment]
@aparshin from the user's point of view, you don't need to care about constructors. This is already reflected in the API docs because it only described one way of creating objects (factories), e.g. http://leafletjs.com/reference.html#marker

**Comment by aparshin** [comment]
Looks like I missed that change in documentation. I apologize.

Then everything is ok!
