### ISSUE TITLE
Adding ruler in leaflet and toggling grids on map.

### ISSUE THREAD

**Issue by kamet4u** [Leaflet/Leaflet#3412]
Is there any way to add ruler to map ?
My requirment is to add ruler on map. Something like this along x and y axis.
![a utm 9](https://cloud.githubusercontent.com/assets/8874512/7389715/518d1382-ee8e-11e4-9e21-bcbed947447c.gif)

I am using leaflet to creat floorplan application and for that I need ruler and grid on map. 

Also ,I used SimpleGraticule to draw grid on my floormap. 
I need a toggle button or control to switch on or switch off the grids and rulers on map. 

Please suggest if this is possible in leaflet to draw ruler on map and also providing toggle to switch it on and off.

**Comment by IvanSanchez** [comment]
This is a good idea for a [leaflet plugin](http://leafletjs.com/plugins.html), but the leaflet core bugtracker is not the place to ask for help on that.

**Comment by kamet4u** [comment]
Do we have ruler or anything like that , that i can use ? Also the toggle?

**Comment by IvanSanchez** [comment]
I don't see any rulers on the [leaflet plugins](http://leafletjs.com/plugins.html) page. If it's not there, it probably doesn't exist.

A toggler to enable/disable a graticule is trivial to do:

```javascript
var map = L.map(...);
var graticule = L.graticule(...)

function toggleGraticule(){
   if (map.hasLayer(graticule)){
      map.removeLayer(graticule);
   } else {
      map.addLayer(graticule);
   }
}
```

**Comment by kamet4u** [comment]
Thanks alot Ivan . It worked :)
