### ISSUE TITLE
Place marker toolbar outside map

### ISSUE THREAD

**Issue by kamet4u** [Leaflet/Leaflet#3413]
Hi, 
   My requirment is to place my custom markers toolbar outside the map area and into an html element, within my UI framework so that I can get more space on map area and also I can write custom css for my custom markers toolbar.   Here is a similar example of what I need. 

http://blog.georepublic.info/2012/leaflet-example-with-wfs-t/

Here is a problem in the above example that while zooming in the marker get misplaced to some other location. 

Please, can you guide me into that ,that how to place the markers toolbar outside the map, I am stuck here and can not proceed ahead in my project.

Thanks in advance for your help.

**Comment by IvanSanchez** [comment]
> Please, can you guide me into that

No, we can not.

Please read https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md carefully, in particular the part that says:

> If you just want some help with your project, try asking on the [Leaflet forum](https://groups.google.com/forum/#!forum/leaflet-js) instead.

**Comment by mourner** [comment]
@IvanSanchez hey, lets say things like this in a more positive tone :)
