### ISSUE TITLE
Plugins page: split in categories

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#3414]
As is pointed out in #3240, the plugins page is getting out of hand. An idea to fix this would be to split plugins into more categories, e.g.:

- Composition/transformation layers (works with other layers)
- Data Viz layers (works with data)
- Markers & UI layers
- Tile layer sources
- Vector layer sources
- Geocoding
- Routing
- Visual controls
- Non-visual controls
- Controls for 3rd party services

An index to jump to the different plugin categories would also be great.

**Comment by mourner** [comment]
Yes! As a first-pass solution, it would be great. We can do a table of contents at the top just like on the API page. We should keep category names simple though — e.g. "Composition/transformation layers (works with other layers)" sounds pretty confusing.

**Comment by mourner** [comment]
@IvanSanchez wanna take a stab at this?

**Comment by IvanSanchez** [comment]
Yeah, I'm up for it but couldn't find the time yet.
