### ISSUE TITLE
Default icon is not using L.Point

### ISSUE THREAD

**Issue by Ish-rivera** [Leaflet/Leaflet#3421]
The options for the default icon is using arrays and not L.Points

**Comment by IvanSanchez** [comment]
And why is this a problem? Icon sizes & anchors are casted into `L.Point`s in `L.Icon._setIconStyles` anyway.

**Comment by Ish-rivera** [comment]
When I access the size of the icon it should be oMarkerObject.icon.iconSize.x and .y as documented. 

----- Original Message -----
