### ISSUE TITLE
Markers and other map elements only show once

### ISSUE THREAD

**Issue by epelc** [Leaflet/Leaflet#3423]
If you zoom out a lot or keep going left/right until you go around the world back to your marker position you will not see your marker or anyother map elements.

http://leafletjs.com/examples/quick-start.html
![image](https://cloud.githubusercontent.com/assets/5204642/7415680/836edca6-ef28-11e4-898f-b5c482c12260.png)

Google maps handles this by showing your markers/elements every time you see where they should be. For example if you put a marker on Australia and you zoom out to the point where you see Australia 3 times you will see your marker on each Australia.

https://developers.google.com/maps/documentation/javascript/examples/marker-simple
![image](https://cloud.githubusercontent.com/assets/5204642/7415715/bed4609a-ef28-11e4-9f77-bcba05f641bb.png)

 This is more of a problem when you move your view around the world all the way you wont see your markers/elements at all unless you go back around the other way.

**Comment by mourner** [comment]
This is the way Leaflet works. Implementing repeating elements would hit performance and add complication that I find not worth it for the benefit. There's also `worldCopyJump` option (see the docs) which kind of solves the last issue.
