### ISSUE TITLE
Empty coordinate-array in LineString is not handled

### ISSUE THREAD

**Issue by hs06** [Leaflet/Leaflet#3424]
When importing a kml (via omnivore) of which a segment with empty coordinate set (<coordinates></coordinates> exists, leafletjs will crash (coordinates NaN).

the problem exits in 	coordsToLatLngs: function (coords, levelsDeep, coordsToLatLng) { // (Array[, Number, Function]) -> Array

I fixed the problem by throwing an own exception and catching it here:
L.extend(L.GeoJSON, 
in 		case 'GeometryCollection':
			for (i = 0, len = geometry.geometries.length; i < len; i++) {

with this:

                        try {
				newGeo = this.geometryToLayer({
					geometry: geometry.geometries[i],
					type: 'Feature',
					properties: geojson.properties
				}, pointToLayer, coordsToLatLng, vectorOptions);
				layers.push(newGeo);
                        }
                        catch (e)
                        {
                                console.log("Coordinate error: "+e);

                        }

Hope that helps. I'm using stable / 0.7.3

**Comment by hs06** [comment]
PS: I'm not doing a fork/pull request as 1) i'm not really into git yet and 2) i'm not sure how the throw/catch should be best handled. my fix works for me, but it should be up to those who know and maintain leatletJS to judge and apply the patch. cheers! -hendrik

**Comment by IvanSanchez** [comment]
Can you please provide a sample KML file, or a GeoJSON object, which triggers the bug?

**Comment by hs06** [comment]
sure. here it is.


````
<?xml version="1.0" encoding="UTF-8"?> <kml xmlns="http://earth.google.com/kml/2.2"><Document><name>Track from 2015-04-20_12.56.22.kml</name><Style id="roadStyle"><LineStyle><color>FFFF0000</color><width>10</width></LineStyle></Style><Placemark><name>Route</name><styleUrl>#roadStyle</styleUrl><MultiGeometry><LineString><coordinates> </coordinates></LineString><LineString><coordinates>-73.958763,40.784317,41.010499 -73.958488,40.784653,42.510883 -73.958488,40.784653,43.011011 -73.957977,40.785316,43.261075 -73.957977,40.785316,43.411115 -73.957222,40.786339,42.677593 -73.957222,40.786339,42.153648 -73.956886,40.787056,42.135787 -73.956886,40.787056,42.121894 -73.956978,40.787697,40.910475 -73.956978,40.787697,39.919311 -73.956825,40.788338,38.759923 -73.956825,40.788338,37.778901 -73.957077,40.788914,36.795133 -73.957077,40.788914,35.942536 -73.957344,40.789238,35.196510 -73.957344,40.789238,34.538253 -73.957283,40.789898,33.841996 -73.957283,40.789898,33.219030 -73.956848,40.790581,32.858410 -73.956848,40.790581,32.532140 -73.955940,40.791454,32.235524 -73.955940,40.791454,31.964705 -73.955139,40.792133,31.508066 -73.955139,40.792133,31.087958 -73.955009,40.792473,30.700168 -73.955009,40.792473,30.341101 -73.955025,40.793488,30.150575 -73.955025,40.793488,29.973190 -73.954857,40.794231,29.774289 -73.954857,40.794231,29.588219 -73.954666,40.794598,29.132458 -73.954666,40.794598,28.704318 -73.954193,40.794922,28.360202 -73.954193,40.794922,28.035749 -73.953590,40.795223,27.673751 -73.953590,40.795223,27.331321 -73.953377,40.795620,26.875302 -73.953377,40.795620,26.442667 -73.953865,40.795986,26.006658 -73.953865,40.795986,25.591917 -73.954468,40.795837,25.196926 -73.954468,40.795837,24.820307 -73.955162,40.795540,24.438074 -73.955162,40.795540,24.072830 -73.955734,40.795765,23.810444 -73.955734,40.795765,23.559223 -73.955589,40.796219,23.318470 -73.955589,40.796219,23.087543 -73.954941,40.796844,22.885858 -73.954941,40.796844,22.692083 -73.954346,40.797680,22.544233 -73.954346,40.797680,22.401962 -73.954361,40.798260,22.264960 -73.954361,40.798260,22.132940 -73.954659,40.798584,22.005633 -73.954659,40.798584,21.882795 -73.955032,40.798840,21.781438 -73.955032,40.798840,21.683516 -73.955322,40.799007,21.588861 -73.955322,40.799007,21.172086 -73.955795,40.799210,20.721972 -73.955795,40.799210,20.271856 -73.956039,40.799286,19.821742 -73.956039,40.799286,19.371626 -73.956505,40.799377,19.004865 -73.956505,40.799377,18.638105 -73.956749,40.799412,18.221332 -73.956749,40.799412,17.804557 -73.957329,40.799484,17.604507 -73.957329,40.799484,17.404455 -73.957787,40.799576,17.271088 -73.957787,40.799576,17.137720 -73.958229,40.799389,17.121050 -73.958229,40.799389,17.104379 -73.958496,40.799118,17.087708 -73.958496,40.799118,17.071038 -73.958595,40.798771,17.087708 -73.958595,40.798771,17.104379 -73.958435,40.798447,17.187733 -73.958435,40.798447,17.271088 -73.958015,40.798115,17.354443 -73.958015,40.798115,17.437797  </coordinates></LineString> </MultiGeometry></Placemark></Document></kml>
```

**Comment by IvanSanchez** [comment]
This is a "garbage in, garbage out" problem - the KML or geoJSON is invalid, then leaflet panics and ends up in flames.

From the [KML docs](https://developers.google.com/kml/documentation/kmlreference#linestring) on `LineString`: 
```
<coordinates>(required)
    Two or more coordinate tuples
```

From the [GeoJSON docs](http://geojson.org/geojson-spec.html#linestring) on `LineString`:

```For type "LineString", the "coordinates" member must be an array of two or more positions.```

There are several ways to proceed with this:

* Ignore the bug because it's the user's fault for providing non-standards-conforming data
* Hack around the GeoJSON parser to throw more meaningful errors so the user knows the data is dirty (I'd go for this one)
* Hack the GeoJSON parser so it skips empty geometries, even though they're invalid.

@mourner: Can you please enlighten me on the best course of action?

**Comment by mourner** [comment]
> Hack around the GeoJSON parser to throw more meaningful errors so the user knows the data is dirty (I'd go for this one)

Yes. I think this should be reported to @tmcw's togeojson repo probably which handles the parsing.
