### ISSUE TITLE
zoom sensitivity in L.geoJson

### ISSUE THREAD

**Issue by mariusnita** [Leaflet/Leaflet#3425]
Is it possible to style geojsons differently depending on zoom level? For example I am using `L.circleMarker` and want the radius to be relative to the zoom level (small radius at low zoom, large radius at high zoom). By default it renders with a fixed radius independent of zoom level. I want to do the same with the `weight` property.

**Comment by IvanSanchez** [comment]
You might want to do something like:

```javascript
map.on('zoomend', function(){
   var radius = (map.getZoom() > 15) ? 10 : 5;
   myCircleLayer.setradius(radius);
}
```

**Comment by mariusnita** [comment]
I will give this a go, thanks @IvanSanchez

**Comment by mariusnita** [comment]
Just for posterity, I was able to do
```js
map.on("zoomend", () => {
  myCircleMarkerLayer.getLayers().forEach((circle) => {
    circle.setRadius(someFunctionOf(map.getZoom(), circle));
  });
});
```
