### ISSUE TITLE
vector layers stop double click from propagating to map

### ISSUE THREAD

**Issue by MuellerMatthew** [Leaflet/Leaflet#3428]
Currently doubleClicking for zooming in and doubleClicking + shift for zooming out does not work when double clicking above a geoJSON layer.  This issue is visible in the second map in the Choropleth example - http://leafletjs.com/examples/choropleth.html . I am not yet sure how to fix it, so the default actions occur.

**Comment by IvanSanchez** [comment]
We can hack around the issue by doing

```js
geojson.on('dblclick', function(ev) {
	map._fireDOMEvent(map, ev.originalEvent, 'dblclick');
});
```

Maybe it's possible to do this directly in the geojson.js code.

**Comment by IvanSanchez** [comment]
I expected this to be a SVG-related problem, but can also be reproduced with the Canvas renderer.

**Comment by mourner** [comment]
I think the issue here is that double click automatically triggers click as well, and the example has `fitBounds` set on click, which triggers an animation that blocks other zooming actions while its running. @MuellerMatthew does that sound right?

**Comment by MuellerMatthew** [comment]
It isn't the `fitbounds` set on click that is preventing the zoom.  Here is a quick js fiddle of only a geojson layer without anything else.  the double click only works when the mouse is not above the layer. 

http://jsfiddle.net/3w3vhv40/1/

**Comment by mourner** [comment]
Yep, you're right. Does the same bug reproduce on the master version?

**Comment by Eschon** [comment]
> Does the same bug reproduce on the master version?

Yes it does, I just forked @MuellerMatthew's fiddle and tested it.
http://jsfiddle.net/Eschon/Lsnqfao6/1/

**Comment by mourner** [comment]
OK, we need to fix that. If anyone's up to looking into this, you're welcome!

**Comment by IvanSanchez** [comment]
#3307 will solve this (and allows for a event handler in the `L.Path` to stop event propagation if needed).
