### ISSUE TITLE
accessibility : get _leaflet_id when tabbing on a marker

### ISSUE THREAD

**Issue by remilev** [Leaflet/Leaflet#3429]
I'm using leaflet stable 0.7.3.
The popups I bind to markers contain some link and buttons. They trigger actions relative to the marker, but NOT contained in it (because too big or needing an ajax call, i.e. : "history of this city : blablabla...). For this interaction I need the _leaflet_id of the marker (or some other id which represent THIS marker in a markerMap array). I think this is a normal way to do it (or am I wrong?)

***My problem : As I have a lot of markers (with images in it), I bind them on.MOUSEOVER only. The reason of the mouseover is for preloading. If the internet connection is ok, the 1/2 second between hover and click is sufficient to load the content and it's then displayed immediately on click.
Example with pseudo-code :
<pre>marker.on('mouseover', function() {
	var leafletId = marker._leaflet_id;
	var popupContent= $("< btn-or-a-tag >something with"+ leafletId+"to trigger action< / btn-or-a-tag >");
	this.bindPopup(popupContent, {options});
});</pre>

This is very easy and fonctional when interacting with the mouse. But when using keyboard "TAB" to focus a marker, it will fail of course because I have no way (that I know:) to get _leaflet_id from DOM. So the popup won't be bound.

***My workaround : I put _leaflet_id in alt (or title) attribute when creating markers. Then when hitting "TAB", I look for it and bind the popup using :
<pre>var lefletId= document.activeElement.alt		
marker = markerMap[lefletId];
marker.fire('mouseover');</pre>

***Idea : this works but this is a very bad use of alt attribute regarding screen readers. So wouldn't it make sense to create a new marker option allowing to display the _leaflet_id directly on DOM using the HTML data-attibute ?

***Code : I tried successfully to implement this idea. In leaflet-src.js I added :
<pre>L.Marker = L.Class.extend({
	includes: L.Mixin.Events,
	options: {
		icon: new L.Icon.Default(),
		dataId: true,								//++
...

_initIcon: function () {
...
		if (options.dataId) {							//++
				icon.dataset.id = this._leaflet_id;		//++
		}</pre>

Then I have data-id in the DOM marker img tag :
<pre>tabindex="0" data-id="30" alt="blabla" style="margin-left: ..." class="leaflet-marker-icon leaflet-zoom-animated leaflet-clickable" src="dirTo/marker-icon.png"</pre>

<b>I know that my way to bind popups on hover is a bit weird. Though I wrote this because it may be useful for other accessibility purposes to have the _leaflet_id on DOM...</b>

**Comment by IvanSanchez** [comment]
Use this:

```js
        L.DomEvent.on(marker.getIcon(), 'focus', function(ev) {
			console.log('marker focus', marker._leaflet_id );
        });
```

> For this interaction I need the _leaflet_id of the marker (or some other id which represent THIS marker in a markerMap array). I think this is a normal way to do it (or am I wrong?)

You're wrong :-P

Whenever possible, carry around references to the markers themselves, and do not use `_leaflet_id` (or any other object property which starts with `_`, as they're supposed to be private properties). It's OK to have several data structures with several references to a marker.

**Comment by remilev** [comment]
Awsome but I can't get it work :
<pre>var marker = new L.Marker(location,{alt: altText});
map.addLayer(marker);
L.DomEvent.on(marker.getIcon(), 'focus', function(ev) {
	console.log('marker focus', marker._leaflet_id );
});</pre>

I got JS error : marker.getIcon is not a function
getIcon is not in the docs. Is it in the version 0.7.3 ?

**Comment by IvanSanchez** [comment]
> I got JS error : marker.getIcon is not a function

Yeah, you're right. Try `marker._icon`, or create a custom icon and work from there, e.g.:

```js
var myIcon = new L.Icon.Default();
var myMarker = new L.Marker(location, {alt: whatever, icon: myIcon})
L.DomEvent.on(myIcon, 'focus', function(ev) {
    console.log(myMarker._leaflet_id)
});
```

Just keep in mind that the `focus` event is a bit tricky, as the event target is the icon and not the marker.

**Comment by remilev** [comment]
Yeah, I was just playing with marker._icon to make it work :)
Even if you're right to warn me from using private properties.

Thanks a lot for your hyper quick support, I think I will find a solution with your help!

**Comment by IvanSanchez** [comment]
Variable scope is biting you in the ass. It's a common problem for beginner-intermediate JS programmers :-)

Basically, there is only one variable called `marker` in your code - and **not** one variable called `marker` for every step of the loop. 

I suggest you do some research on Javascript variable scope and [closures](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures). Everything will become clear then ;-)

**Comment by remilev** [comment]
Yeah! It has allways be a nightmare for me!
Thanks for the link to MDN. It is not totally clear yet, but the section "Creating closures in loops" made me achieve my goal :)

It's now ok with this :
<pre>
$.getJSON("databaseMarker.php", function (data) {

function idOnFocus(marker) {
	L.DomEvent.on(marker._icon, 'focus', function(ev) {
		console.log('marker focus', marker.mapId );
	});
};

    for (var i = 0; i < data.length; i++) {
        var mapId = data[i].database_id;    // id from database        
        var marker = new L.Marker(location,{icon: waitIcon, alt: "blabla"});
        marker.mapId = mapId; // new attribute to avoid using privete propertie _leaflet_id
        map.addLayer(marker);
        idOnFocus(marker);
});</pre>


It's certainly imperfect but it works.
Thanks again
