### ISSUE TITLE
tilerLayer.setOpacity not changing active tiles on master

### ISSUE THREAD

**Issue by jplante** [Leaflet/Leaflet#3431]
Is anybody else having a problem setting the opacity on a tileLayer with the latest master build?
Calling `.setOpacity(x)` doesn't seem to do anything.  Maybe there is an issue with the `._updateOpacity` method check perhaps?  Sample page and code reference are listed below.

**Simple Sample Page**
The page has the latest zip from master set locally.  It simply creates a map, a tile layer and then attempts to change its opacity. This happens even on layers higher in the stack.  No tile layers seem to change their opacity.
```
<html><head><title>Sample Page</title>

<-- Pulled from latest master download -->
<link rel="stylesheet" href="/stylesheets/leaflet-0.8.css" />
<script type="text/javascript" src="/javascripts/leaflet-0.8.debug.js"></script>

<script type="text/javascript">
	var map = L.map('map').setView([51.508, -0.11], 3);
	var earth = L.tileLayer('http://otile{s}.mqcdn.com/tiles/1.0.0/osm/{z}/{x}/{y}.png', {
		subdomains: ["1", "2", "3", "4"]
	}).addTo(map);
	
	// ** This does not seem to have ANY effect  **
	earth.setOpacity(0.5);  
</script>

</head>
<body>
	<div id="map"></div>
</body>
</html>
```

**Code Reference**
I'm just poking around, so I'm not really sure what the issue is, or if anyone else can reproduce it.  Stepping through however, it looks like `tile.active` is always true and then just continues instead of changing the opacity.
```
_updateOpacity: function () {
	...
	for (var key in this._tiles) {
		var tile = this._tiles[key];

		// ** THIS ALWAYS SAYS tile.active = TRUE AND CONTINUES **
		if (!tile.current || !tile.loaded || tile.active) { continue; }  

		var fade = Math.min(1, (now - tile.loaded) / 200);
		if (fade < 1) {
			L.DomUtil.setOpacity(tile.el, opacity * fade);
					nextFrame = true;
				} else {
					L.DomUtil.setOpacity(tile.el, opacity);
					tile.active = true;
					this._pruneTiles();
				}
			}
```

**Comment by jplante** [comment]
Further investigation seems to indicate that it is in fact tied to tiles that are currently showing in the viewport.  panning away reveals tiles whose opacity has changed, but they are not consistent with the tiles that were visible when the call was made, and those visible tiles should have changed too.

**Comment by jplante** [comment]
I have verified that making the following change produces the expected result:

**from**
``` 
if (!tile.current || !tile.loaded || tile.active) { continue; }
```

**to**
``` 
if (!tile.current || !tile.loaded) { continue; }
```

I don't want to do a pull request for this, because I'm assuming that there is a reason I don't understand as to why the check for `tile.active` was there.

**Comment by jplante** [comment]
The logic for `_updateOpacity` was changed in the following commit back in January:
https://github.com/Leaflet/Leaflet/commit/22cfd12956f6dcf4e3f5d3e2ee34b8046bdf1fe4?diff=unified

It has to do with fading tiles, but I would still expect the currently visible tiles to change their opacity when the call is made as well.

I'm not sure if the check for `tile.active` in `_updateOpacity` is necessary or not.

**Comment by mourner** [comment]
cc @jfirebaugh

**Comment by jfirebaugh** [comment]
The `setOpacity` case should probably trigger separate code. If you remove the `tile.active` check then calling `setOpacity` will trigger `_pruneTiles` once for every active tile, which would probably be slow for a use case like an interactive opacity slider.

The separate code would also loop over tiles, but only change opacity on active tiles. Alternatively, we could have `setOpacity` always set opacity on the container, and fully separate that from tile fading. [This comment](https://github.com/Leaflet/Leaflet/blob/8f3a353d84909f7b6cf27d6a37b162af01cc2dc0/src/layer/tile/GridLayer.js#L151) indicates that IE8 and lower may not handle that correctly but I'm happy to punt on that.

**Comment by IvanSanchez** [comment]
See PR #3513
