### ISSUE TITLE
Map does not return to max bounds on minor/slow panning

### ISSUE THREAD

**Issue by rikvanmechelen** [Leaflet/Leaflet#3432]
On 0.8-master branch, when you pan slowly, slightly diagonally the map does not snap back to its max bounds.

**Comment by cduzan** [comment]
I'm getting a similar issue. I'm not sure if it's diagonal, but the map only snaps back if you drag it quickly and release. If I make sure I stop moving before releasing the mouse then the map doesn't snap back.
