### ISSUE TITLE
Fixed size Ployline and Polygon like CircleMarker?

### ISSUE THREAD

**Issue by schniedan** [Leaflet/Leaflet#344]
Hi, 

I'd like to have fixed-size Polylines and Polygons. How would I have to alter the code? I can't really see how the "not-rescaling" is done in CircleMarkers?!

Cheers, 
Andreas

**Comment by RossThorn** [comment]
I've followed the rabbit hole of these issue numbers but didn't quite understand where it was going. I know this is an old thread, but I'm facing issues like this. Basically I want to create star plots (see attachment) 
![graph 2](https://user-images.githubusercontent.com/24381390/30068428-6aa64d1c-9223-11e7-8984-0154a11868bc.png)
that are different for data at certain locations so I cannot use a custom image for each one (thousands of different sites with data). 

I need to be able to set a lat long for the origin and center of the point and then use relative pixel locations to draw the points of the star plot at a certain euclidean distance from the origin. 

If someone could guide me, that would be oh so spectacular. Thanks!

**Comment by perliedman** [comment]
@RossThorn sounds like a case for `DivIcon`: you can create a `Marker` with a `DivIcon` as its icon, and you can set the contents of the `DivIcon` to anything you like: SVG diagrams, images, text, and so on.

The marker will ensure that your content is correctly placed on the map, while you can concentrate on creating whatever visualization you need.
