### ISSUE TITLE
Too many polylines drawn on map

### ISSUE THREAD

**Issue by Gaurav-Walia** [Leaflet/Leaflet#3442]
Hi Team;
We have integrated leaflet-rails gem (version: 0.7.4) in my application. In our application we upload GPX file and then displays them on map but when we upload GPX and displays them on map, we see too many polylines connecting the coordinates. I am attaching the image of leaflet map. Please guide us and it is very urgent.
![gpx](https://cloud.githubusercontent.com/assets/2232191/7530974/ac3a44c0-f56f-11e4-9900-a18f328ff4f1.png).

.

**Comment by yohanboniface** [comment]
Hi @Gaurav-Walia :)

You should post on the Leaflet forum to get help: https://groups.google.com/forum/#!forum/leaflet-js

This issue tracker is only for Leaflet code itself.
