### ISSUE TITLE
TRACKING

### ISSUE THREAD

**Issue by FoughtWon** [Leaflet/Leaflet#3451]
Okay if I wanted to make my map into a tracking map, say tracking different cars or buses etc... While showing up on the map, kinda like the App Waze does for like a social GPS, but I want to create a lesser version of Waze that like tracks city buses through say an app what would I need to do? Is that even possible using this map code or not, I have seen a few tracking code plugins and a few for GPS like features, but I am also wondering would this work worldwide, if I hooked it up with a bigger server maybe?
Thanks!

**Comment by IvanSanchez** [comment]
Leaflet's github is not the place for asking help on developing an app. Please read the repo's guidelines for contributing.
