### ISSUE TITLE
Problem with Leaflet Mobile ex

### ISSUE THREAD

**Issue by FoughtWon** [Leaflet/Leaflet#3456]
I have followed all the steps on the Leaflet Mobile tutorial page and I can not get it to work. What can I do to fix it experts? I think that the tilelayer may be messing up?

```
<!DOCTYPE HTML>
<html>
<head>
    <title>Mobile</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />   
    <link rel="stylesheet" href="leaflet.css" />
<script src="leaflet-src.js"></script>   
<style>
body {
    padding:0;
    margin:0;
}
    #map {
	height: 100%;
}
</style> 
</head>
 
<body>
    <div id="map"></div>
<script>
 var map = L.map('map');

L.tileLayer('http://{s}.tiles.mapbox.com/v3/MapID/997/256/{z}/{x}/{y}.png', {
    maxZoom: 18,
    attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
}).addTo(map);
    function onLocationFound(e) {
    var radius = e.accuracy / 2;

    L.marker(e.latlng).addTo(map)
        .bindPopup("You are within " + radius + " meters from this point").openPopup();

    L.circle(e.latlng, radius).addTo(map);
}

    function onLocationError(e) {
    alert(e.message);
}
    map.on('locationfound',onLocationFound);
    map.on('locationerror', onLocationError);
    
map.locate({setView: true, maxZoom: 16});
};
</script>
</body>
</html>
```

**Comment by IvanSanchez** [comment]
> I can not get it to work

Be specific. What can't you get to work?

**Comment by FoughtWon** [comment]
I found my error in that code under map.locate line, before script I had};, didn't need it though.  When I run the code now it always comes up with error message. I am using Google Chrome Browser. It continues to say that this page has been blocked. It says I have denied access when I just ran the code.  Help?

**Comment by IvanSanchez** [comment]
Be. Specific.

> [...] it always comes up with error message

What error message?

---

You will get better and faster answers if you ask the proper questions. Please read this a few times before asking something: http://www.catb.org/esr/faqs/smart-questions.html

**Comment by FoughtWon** [comment]
Javascript Alert
Geolocation error:User denied Geolocation

This alert

**Comment by IvanSanchez** [comment]
Then it is not a Leaflet bug. Familiarize yourself with the HTML5 Geolocation API, https://developer.mozilla.org/en-US/docs/Web/API/Geolocation
