### ISSUE TITLE
Split L.Control.Button off L.Control.Zoom

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#3459]
Quite a few plugins subclassing `L.Control` use buttons. But if you look at `L.Control.Zoom`, there's a private `_createButton()` which fixes some onClick behaviour, and a tiny bit of CSS which applies to zoom buttons only (it was quite a bit more in stable BTW).

Is it a good idea to split off `L.Control.Button`?

**Comment by mourner** [comment]
No, I think it's enough to have https://github.com/Leaflet/Leaflet.toolbar if you need reusable Leaflet buttons.
