### ISSUE TITLE
how to add L.DomEvent into geojson layer

### ISSUE THREAD

**Issue by adspuma** [Leaflet/Leaflet#3461]
Hi experts

I do like this, but the marker is not displaying on the map. Thanks so much!

        var marker;
	var geoJsonLayer = new L.GeoJSON(null, {
				pointToLayer : function(feature, latlng) {
					marker = L.marker(latlng, {});
				L.DomEvent.on(marker._icon, 'focus', function(ev) {
					});
			});
geoJsonLayer.addTo(map);
geoJsonLayer.addData(geoJsonData);

**Comment by IvanSanchez** [comment]
Use the forums for support, not the issue tracker.

**Comment by adspuma** [comment]
Sure, sorry for that. Thanks!
