### ISSUE TITLE
composer.phar support

### ISSUE THREAD

**Issue by fmiguelroliveira** [Leaflet/Leaflet#3471]
Hello,

I was wondering if the leafletjs team have in mind to support leafletjs by the composer.phar .

This would be great for lots of developers who already have 3rd party components managed by composer.

**Comment by IvanSanchez** [comment]
I don't think any of the core devs use composer.phar. I, for one, don't want to get involved in a flamewar about NPM vs Bower vs Composer.

I suggest you make a pull request adding the composer.phar files to Leaflet's build system - that will get this done far quicker.
