### ISSUE TITLE
Jerkiness when drawing circle

### ISSUE THREAD

**Issue by bfishman** [Leaflet/Leaflet#3474]
This occurs in leaflet 0.8-dev only. 

When drawing a circle, it can be easily 'expanded' in size - but when you attempt to reduce the size, the drawing either freezes or stutters.  Note this does not happen when editing an existing circle - only when creating a new one.

Interestingly, when dragging from a bottom-right part of the circle back towards the middle, the circle cannot be shrunk. But if instead you start the mouse to the top-left (or bottom-left) part of the circle and then back towards the middle, the reduction in size will occur, although jerkily.

Hope this description makes sense.

**Comment by mourner** [comment]
Can you make a JSFiddle to demonstrate the issue?

**Comment by bfishman** [comment]
I'm sorry, this was supposed to be posted to leaflet.draw, closing and will open there.

**Comment by mourner** [comment]
No problem, thanks!
