### ISSUE TITLE
Responsive Grid on Leaflet

### ISSUE THREAD

**Issue by ubinam** [Leaflet/Leaflet#3475]
We are developing a project for which we would like to place the a responsive grid like gridstack.js layout on top the map background based on Leaflet keeping both functionalities.
This is not possible right now. I understand you can reference objects by the map positions but not by the relative position on the viewport. Would you help us making it possible?

**Comment by mourner** [comment]
This is a place to report Leaflet issues, not to ask for help developing an app. Please try asking on the Leaflet forum or StackOverflow instead.
