### ISSUE TITLE
Leaflet freezes in Bootstrap 3 modal after zooming, closing and reopening the map

### ISSUE THREAD

**Issue by clemensg** [Leaflet/Leaflet#3479]
Hi,

I use Leaflet (master) to show the geolocation of different photos on a map in a modal dialog. When opening the modal with the map, everything works. But when I zoom in, close the modal dialog and click on another photo (with same or different lat and lng) the modal opens but the map does not respond to the mouse anymore. Everything except for the keyboard is frozen. If I move the view with the keyboard, it unfreezes. But I can't change the zoom level with the mouse or move around, it does not respond to that..

Neither map.setView / map.setZoom nor map.invalidateSize() unfreeze the map.
However, I found out that calling `map.flyTo(map.getCenter())` and for example `map.fire('moveend')` unfreeze the map controls. But I'd rather not use those without understanding what the problem is. Do you have an idea, what the underlying problem could be?

Here my CoffeeScript code:

I call the following once with every page:load and page ready handler:
```coffeescript
exports = this

# Create a global variable with the map object
exports.map = L.map('map-canvas')

# Add an OpenStreetMap tile layer
L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(exports.map)

# Create a global variable with the marker object
exports.marker = L.marker([0, 0]).addTo(exports.map)

# Workaround for Bootstrap 3 modal dialog, resizes the map after the dialog is visible
$("#geoModal").on "shown.bs.modal", (e) ->
    exports.map.invalidateSize()
```

My click handler, which opens the modal dialog containing the map, looks like this:
```coffeescript
exports = this

mapClickHandler = ->
    # Show on the map, where the photo was taken
	coords = L.latLng($("a#photo-maplink").data('latitude'), $("a#photo-maplink").data('longitude'))
	zoomlevel = $("a#photo-maplink").data('zoom-level') || 14
    # Change the position of our cached map object
	exports.map.setView(coords, zoomlevel)
    # Change the position of our cached marker object
	exports.marker.setLatLng(coords).update()
    # Open the modal dialog
	$('#geoModal').modal()
```

Is this a bug in Leaflet or did I get something wrong in my setup code / click handler?

**Comment by mourner** [comment]
Can you set up a minimal JSFiddle test case reproducing the issue?

**Comment by anthonykeller79** [comment]
I'm experiencing a similar issue. The zoom controls work perfectly on my map when no markers have been added. Once a marker is added, after using the zoom controls the map freezes. It seems intermittent-sometimes I can zoom in and out over 10 times before it freezes while other times I can only zoom once. 

I may be able to make a small test case in a couple of days to reproduce the issue.

**Comment by clemensg** [comment]
@mourner Yes. Here is my JSFiddle: http://jsfiddle.net/khg64uzw/25/

It behaves the same as on my site, with one difference: As I show the map on a modal dialog, I always call map.invalidateSize(); after the modal is shown, but it only fixes the size but does not fix this bug. In my JSFiddle however, adding a map.invalidateSize(); call after the .show(); fixes the problem. Therefore I am not 100 percent sure, if I am reproducing the exact same issue I am facing on my site or something different.

**Comment by mourner** [comment]
Having to call `invalidateSize` after showing the map container is expected. Can you try reproducing the problem with the call and see what may trigger this?

**Comment by clemensg** [comment]
OK, I'll try! Maybe I have to add Bootstrap and show the map in a modal dialog exactly as I do on my site to reproduce this issue.

**Comment by clemensg** [comment]
It looks like the `shown.bs.modal` event is not always fired and therefore `invalidateSize` does not get called every time the map container is shown. Calling `invalidateSize` both before I open the modal and after the `shown.bs.modal` event fired, does seem to fix the issue.

**Comment by mourner** [comment]
Cool! Closing the issue for now then. @anthonykeller79 please make a JSFiddle test case that reproduces your issue and I'll reopen.

**Comment by anthonykeller79** [comment]
I'm not using bootstrap so when I get a test case setup I'll raise a new issue.
