### ISSUE TITLE
contextmenu event doesnt get called for circleMarker on canvas leaflet

### ISSUE THREAD

**Issue by abarik1981** [Leaflet/Leaflet#3481]
Problem: contextmenu event doesnt get called for circleMarker on canvas leaflet

Steps to reproduce:

1. create following code:

html header: must contain `L_PREFER_CANVAS=true;`

    <script>L_PREFER_CANVAS=true;</script>
    <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css" />
    <script src="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js"></script>

    <div id="map"></div>

javascript:

    map = L.map('map', {
        center: [7.2, 40.9],
        zoom: 2
    });

    L.tileLayer('http://{s}.mqcdn.com/tiles/1.0.0/map/{z}/{x}/{y}.png', {
        attribution: "Map: Tiles Courtesy of MapQuest (OpenStreetMap, CC-BY-SA)",
        subdomains: ["otile1", "otile2", "otile3", "otile4"],
        maxZoom: 12,
        minZoom: 2
    }).addTo(map);

    var marker1 = new L.Marker([1, 1]);
    marker1.on('contextmenu', function() {
         $('body').append('right-clicked-on-marker')
    })
    map.addLayer(marker1);

    var cmarker1 = new L.circleMarker([1, 20]);
    map.addLayer(cmarker1);
    cmarker1.on('contextmenu', function() {
         $('body').append('right-clicked-on-circle-marker')
    })

2. rightclick on simple marker and you will see `right-clicked-on-marker` getting appended to body

3. rightclick on circle marker and you will NOT see `right-clicked-on-circle-marker` getting appended to body

4. Tested that if I remove `L_PREFER_CANVAS=true;`, then contextmenu works for circlemarker

jsfiddle: http://jsfiddle.net/abarik/vg7b2ttb/5/

Please help

Using version: 0.7.3

**Comment by mourner** [comment]
Can you reproduce the same issue on 1.0-dev (master)? Example of using canvas renderer is on map/debug/vector2.html.

**Comment by IvanSanchez** [comment]
I can **not** reproduce in master. Both canvas and SVG layers fire the `contextmenu` event as expected.

**Comment by IvanSanchez** [comment]
I can also confirm the bug is reproducible in stable. I've taken the liberty of putting together a fiddle at http://jsfiddle.net/wx0yq03p/

**Comment by mourner** [comment]
Will be fixed in #3482 for stable branch.

**Comment by abarik1981** [comment]
thanks
