### ISSUE TITLE
 load on demand

### ISSUE THREAD

**Issue by arkadi** [Leaflet/Leaflet#3483]
Hello, I have some problems, I have many markers and I need to implement the following logic: when I move the map to the new region, new markers must be loaded. I mean they must load on demand, only when the region is visible. Please help. Thanks.

**Comment by mourner** [comment]
Hey, thanks for using Leaflet! However, this is a place to report Leaflet issues, not to request support for your app.  Please try asking on the <a href="https://groups.google.com/forum/#!forum/leaflet-js">Leaflet forum</a> — you are more likely to find help there.
