### ISSUE TITLE
Leflet error in IE11 only: NotFoundError

### ISSUE THREAD

**Issue by tolmik** [Leaflet/Leaflet#3485]
I think the issue I found is the same as the one in this ticket:
https://github.com/Leaflet/Leaflet/issues/3364

Contrary to that ticket I actually have a way to reproduce the error:
Open the Search Sellers page:
http://www.zaahib.com/user_search/En/users/search/List/

Then click the Map button. In IE you will see the following error:
NotFoundError
File: script block (8), Line: 7, Column: 28156
This is the onRemove function, and the cursor is standing at the first command: t._pathRoot.removeChild

But the error also happens if you have map mode opened:
http://www.zaahib.com/user_search/En/users/search/Map/

And then type istanbul in the input field and click search.

Error is only present in IE, I could not reproduce it in any other browser.

**Comment by mourner** [comment]
Can you try reducing the test case to a minimal JSFiddle example?

**Comment by tolmik** [comment]
Uhh, that might be an issue. I will look into the possibility, but I can not promise you any definite answers before Monday. It is already the last workday of the week here, and Now comes a weekend.

**Comment by mourner** [comment]
Sure, no worries. Just note that we can't start looking into this until there's an easily reproducible minimal test case with code.

**Comment by tolmik** [comment]
In the mean time do you need debug, callstack and other information that I can gather running the page in VS2013 debug mode?

**Comment by IvanSanchez** [comment]
Call stack would be nice, but only if you can run that with the non-minified leaflet source (or with a sourcemap)

**Comment by tolmik** [comment]
I took a look at the source code. On IE11 only if the leaflet container div is not visible when you call leaflet.clearLayers() the it will throw you that error. I will try to put together a small JSFiddle example by Monday that reproduces the error.
I will change the leaflet for the non-minified source and give you a call stack

**Comment by tolmik** [comment]
The Exception that Leaflet throws is this:
-	{exception}	{...}	[Object, DOMException]
-		[Methods]	{...}	
		ABORT_ERR	20	Number
		code	8	Number
		DATA_CLONE_ERR	25	Number
		DOMSTRING_SIZE_ERR	2	Number
		HIERARCHY_REQUEST_ERR	3	Number
		INDEX_SIZE_ERR	1	Number
		INUSE_ATTRIBUTE_ERR	10	Number
		INVALID_ACCESS_ERR	15	Number
		INVALID_CHARACTER_ERR	5	Number
		INVALID_MODIFICATION_ERR	13	Number
		INVALID_NODE_TYPE_ERR	24	Number
		INVALID_STATE_ERR	11	Number
		message	"NotFoundError"	String
		name	"NotFoundError"	String
		NAMESPACE_ERR	14	Number
		NETWORK_ERR	19	Number
		NO_DATA_ALLOWED_ERR	6	Number
		NO_MODIFICATION_ALLOWED_ERR	7	Number
		NOT_FOUND_ERR	8	Number
		NOT_SUPPORTED_ERR	9	Number
		PARSE_ERR	81	Number
		QUOTA_EXCEEDED_ERR	22	Number
		SECURITY_ERR	18	Number
		SERIALIZE_ERR	82	Number
		SYNTAX_ERR	12	Number
		TIMEOUT_ERR	23	Number
		TYPE_MISMATCH_ERR	17	Number
		URL_MISMATCH_ERR	21	Number
		VALIDATION_ERR	16	Number
		WRONG_DOCUMENT_ERR	4	Number

**Comment by tolmik** [comment]
Call Stack:

Name | Line | Language
----------------------------------|-----------|--------------
onRemove [leaflet-src.js] | Line 4552	 | Script
removeLayer [leaflet-src.js] | Line 1725 | Script
removeLayer [leaflet-src.js] | Line 4302 | Script
eachLayer [leaflet-src.js] | Line 4353 |	Script
clearLayers [leaflet-src.js] | Line 4317 |	Script
clearMap [UserSearchJS.js] | Line 1113 |	Script
updateresult [UserSearchJS.js] | Line 324 |	Script
searchRouteHandler [UserSearchJS.js] | Line 265 |	Script
Anonymous function [UserSearchJS.js] | Line 2544 |	Script
callback [kendo.web.min.js] | Line 10 |	Script
worksWith [kendo.web.min.js] | Line 10 |	Script
_urlChanged [kendo.web.min.js] | Line 10 |	Script
o [kendo.web.min.js] | Line 10 |	Script
trigger [kendo.web.min.js] | Line 9 |	Script
_navigate [kendo.web.min.js] | Line 10 |	Script
navigate [kendo.web.min.js] | Line 10 |	Script
navigate [kendo.web.min.js] | Line 10 | Script
navigate [globaljs.js] | Line 791	| Script
Search_click [LoaddefaultTempalte.js] | Line 346 | Script
onclick [script block] | Line 103 | Script

**Comment by tolmik** [comment]
Running Leaflet version '0.7.3';

**Comment by IvanSanchez** [comment]
It seems the error is in [stable layer/vector/Path.js#L68](https://github.com/Leaflet/Leaflet/blob/stable/src/layer/vector/Path.js#L68) - now the question is what set of SVG vector layers will cause `layerGroup.clearLayers()` to fail.

> On IE11 only if the leaflet container div is not visible when you call leaflet.clearLayers()

I've tried hacking some of the pages in `debug/vector/` to reproduce this (adding the same path twice and then clearing, removing the group before removing the path, etc), with no luck.

**Comment by mourner** [comment]
OK, let's wait for a JSFiddle from the author then.

**Comment by tolmik** [comment]
That is going to take more time than expected. Basically I am trying to shrink it down to as little code as possible, but the source code is around a 500K in size.

But until it is done here is what the page does. On page load it will create the following layers:
A tile layer for map mode, a tile layer for satellite mode.
7 Layer groups: 
currentViewLayer, provincesLayer, provincesListingsLayer, citiesLayer, citiesListingsLayer, districtsLayer, districtsListingsLayer

Reason being: We will show Province / City / District borders (around 2000 in total), and in every location a number in a yellow circle (number of listings). In addition to that we have a separate layer for GPS locations. So for example if you are zoomed out to Country level you will see the map, then the Province borders on top of it, and the exact location listings. When you zoom in to a Province we will hide the Province borders, show the city borders and the exact location listings for that Province.

Now. The part that fails is this:
            if ($("#search_listing_map").is(':visible')) {
                classifieds_free_text_search_results.currentViewLayer.clearLayers();
                classifieds_free_text_search_results.provincesLayer.clearLayers();
                classifieds_free_text_search_results.provincesListingsLayer.clearLayers();
                classifieds_free_text_search_results.citiesLayer.clearLayers();
                classifieds_free_text_search_results.citiesListingsLayer.clearLayers();
                classifieds_free_text_search_results.districtsLayer.clearLayers();
                classifieds_free_text_search_results.districtsListingsLayer.clearLayers();
            }

If I do not check if the map container is visible and try to clear the layers, then it throws the error.
Line 1113 is the first one. So the NotFoundError is thrown when trying to clear the currentViewLayer.

**Comment by mourner** [comment]
@tolmik if it's hard to reduce a huge app, you could also try building a test case from scratch, adding stuff until it starts reproducing.

**Comment by tolmik** [comment]
The main issue, is that we actually need that amount of crap for the page to load. I am working on it, but the boundaries file for example is 1 MB of minified JS containing a JSON object of boundary coordinates :(

I will have a smaller version up and running in about a day or so.

**Comment by tolmik** [comment]
Ok, as per the debug information I have the cause of the error seems to be, that map._pathRoot.childNodes.length is 0 at the time of the call. As per my understanding this can only happen in IE11, as in Firefox once I enter the search string the Kendo navigation will not fire the layer clearing. In IE however JS seems to behave a bit differently than in any other browser, so the function call is fired. And Leaflet - as usual for third party plugins - does not have error handling.

And this is also the main reason why I am having a hard time giving you a reproducible JSFiddle example: It is not only the map, but the map AND the Kendo navigation together that causes this error.

**Comment by mourner** [comment]
@tolmik if you handle the error when calling `clearLayers` with something `try/catch` block, are there any other unwanted effects?

**Comment by tolmik** [comment]
no, there are none. Basically all it does is clear the map so that we can re-zoom on the results and show the results on it. Also I do handle the error by checking $("#search_listing_map").is(':visible') and it will also get rid of the errors. I just wanted to raise a question about the fact, that if for any reason there is a circumstance like this Leaflet will fail, and only fail in IE.

**Comment by mourner** [comment]
OK, then I think we can close the issue. I'll reopen if someone comes up with an easy test case, otherwise not worth spending tons of time on.
