### ISSUE TITLE
Map's reported bounds increase past longitude 180 when panning 

### ISSUE THREAD

**Issue by slead** [Leaflet/Leaflet#3486]
Apologies if this is a known issue but I couldn't see it mentioned after a quick search.

When panning the map continuously to the east or west, the longitude reported by `map.getBounds` increases past +/- 180 degrees.

See http://jsfiddle.net/tgxj3npk/1/ for a simple example:
```
map.on("moveend", updateCoords);
function updateCoords() {
    long = map.getBounds()._northEast.lng;
}
```
Pan the map continuously to the east and note that the reported longitude increases past 180 degrees. The longitude should instead wrap back to -180.

**Comment by mourner** [comment]
This is by design. If you want the longitude wrapped, use something like `map.getBounds().getNorthEast().wrap()`.
