### ISSUE TITLE
Move <leaflet-map> to https://github.com/Leaflet/ ?

### ISSUE THREAD

**Issue by nhnb** [Leaflet/Leaflet#3492]
&lt;leaflet-map&gt; is a web component for Leaflet, which allows to use the most common features by just writing declarative html code. Advanced features can be added with JavaScript as usual.

There is a demo page at https://nhnb.github.io/leaflet-map/demo.html

Webcomponents are an emerging HTML standard. At this time it is fully supported by Chrome natively. The missing parts are emulated by webcomponent.js on Firefox, Safari and Internet Explorer.

&lt;leaflet-map&gt; is currently in beta and getting ready for its stable release in June. Therefore, if moving it to https://github.com/Leaflet/ is an option, now will be a good time.

**Comment by IvanSanchez** [comment]
Is this not the same as https://github.com/prtksxna/leaflet-map-component ?

**Comment by IvanSanchez** [comment]
I suggest you coordinate development with @prtksxna and release some stable version before considering to transfer ownership of the repo to the Leaflet org.

Also, if your polymer component offers different functionality thant @prtksxna's, add it to `plugins.md` in the `gh-pages` branch.

**Comment by nhnb** [comment]
Yes, we discussed that. I merged prtksxna's work and granted him commit access to https://github.com/nhnb/leaflet-map a long time ago. But he made it clear that he prefers not contribute to a project belonging to someone else and suggested moving it to the leaflet organization. 

Both components will have some incompatibilities, when Polymer 1.0 is released. That's why we refrain from calling them stable now, despite them working well. https://github.com/nhnb/leaflet-map/ has a 0.9 branch which depends on Polymer 0.9. I like to avoid breaking compatibility twice. So if the move should happen, doing that with 1.0 seems to be a good idea.

**Comment by yohanboniface** [comment]
An option may be to move it to https://github.com/leaflet-extras in a first step? ping @brunob

**Comment by brunob** [comment]
Why not, any thoughts about it @leaflet-extras ?

**Comment by jieter** [comment]
yeah, why not
