### ISSUE TITLE
Problem about using customed crs

### ISSUE THREAD

**Issue by DarwinSenior** [Leaflet/Leaflet#3501]
I am currently working on a project that used RAD and DEC in the astronomical sense. And the scale function is 
```
scale: function (zoom) {
		 	        return Math.pow(2, zoom);
		 	    }
```
Thus, there are some problems related to the following code:
```
max = this._map.options.crs.scale(zoom) / tileSize;
var xw = (x + max) % max, yw = (y + max) % max;
```
in `_update`
and 
```
max = map.options.crs.scale(map.getZoom()) / tileSize;
x = (x + max) % max;
y = (y + max) % max;
```
in `_objectForEvent`.

Because max in this case is a number way smaller than one. 
In order for this to work, I basically commented out the calculation of wx, wy and x, y.

So, I just did this by hacking. It seems like that it wanted to prevent x and y to be out of bounds.
And it obviously did not think of dealing with number that is not integer and when `max` << `x` or `y`.

I am not sure how to fix this other than hacking at this moment though.

**Comment by IvanSanchez** [comment]
Is there any example of this CRS at work, in order to reproduce the problem?

**Comment by perliedman** [comment]
@DarwinSenior where is this code and which Leaflet version are we talking about?

```
max = this._map.options.crs.scale(zoom) / tileSize;
```

It doesn't look right, in stable (0.7.3), CRS's `getSize` should probably be used rather than `scale`, the master branch has the same concept as `getProjectedBounds` if I recall correctly.

In 0.7.3, `getSize` by default just calls `scale` (since that works for our spherical mercator CRS), but you can easily override it of course.

**Comment by DarwinSenior** [comment]
```
L.CRS.RADEC = L.extend({}, L.CRS, {
		 	    projection: L.Projection.LonLat,
		 	    transformation: new L.Transformation(1, 0, 1, 0),
		 	    scale: function (zoom) {
		 	        return Math.pow(2, zoom);
		 	    },
		 	    latLngToPoint: function(latlng, zoom) {
		 	        var adjlatlng = L.latLng((latlng.lat-this.adjust.y)/this.adjust.scale.y, (latlng.lng-this.adjust.x)/this.adjust.scale.x);
		 	        return L.CRS.Simple.latLngToPoint(adjlatlng, zoom);
		 	    },
		 	    pointToLatLng: function(point, zoom) {
		 	        var latlng = L.CRS.Simple.pointToLatLng(point, zoom);
		 	        latlng.lng = (latlng.lng*this.adjust.scale.x)+this.adjust.x;
		 	        latlng.lat = (latlng.lat*this.adjust.scale.y)+this.adjust.y;
		 	        return latlng;
		 	    },
		 	    adjust: {
		 	        x: 322.477471,
		 	        y: 0.713879+0.3736110,
		 	        scale: {
		 	            x:0.00278884,
		 	            y:0.0027886
		 	        }
		 	    }
		 	});
```
Is that information enough? The scale is not from my code. I means in this case, 
```
var map = new L.Map('map', {
		 	  center: [0.7305505, 322.8344425],
		 	  crs: L.CRS.RADEC,
		 	  zoomControl : true,
		 	  attributionControl : false,
		 	  minZoom: 0,
		 	  maxZoom: 7,	
		 	  zoom: 1
		 	}).addLayer(utfgridL).addLayer(mapL);
```

**Comment by perliedman** [comment]
@DarwinSenior yes. Like I mentioned above, if this is for Leaflet 0.7.3, you probably need to implement your own version of `L.CRS.getSize` and put it into `L.CRS.RADEC`, or extend it and add your override.

`getSize(zoom)` should return the size of the given zoom level, in pixels. By default, it will call `scale` to calculate this value, which means for your CRS, the world will be 1 x 1 pixels at zoom 0, 2 x 2 at zoom 1, and so on.

**Comment by mourner** [comment]
@perliedman so is this an issue, or can be closed?

**Comment by perliedman** [comment]
@mourner you're right, does not look like a Leaflet issue at this point.

@DarwinSenior feel free to add more info if you think this is a Leaflet issue, and we can reopen. Otherwise, we can move the discussion to one of the forum, IRC or one of the stackexchange sites.
