### ISSUE TITLE
Proposal: add option to show image when map's current zoom is out of layer's zoom range

### ISSUE THREAD

**Issue by smellman** [Leaflet/Leaflet#3506]
Latest my pull request (#3505) has some trouble about cache when zoom out after zoom in.

```javascript
       var zoom = 10;

       map = L.map('map', {
         maxZoom: 12,
         minZoom: 8,
         crs: L.CRS.Simple
       });
       map.setView(map.unproject([512, 512], zoom), zoom);
       // ...
       var layer1 = L.tileLayer('http://tiles.smellman.org/red/{z}/{x}_{y}.png', {
         attribution: 'Map data &copy;',
         continuousWorld: true,
         zIndex: 2,
         minZoom: 8,
         maxZoom: 11,
         opacity: 0.5
       }).addTo(map);
       var layer2 = L.tileLayer('http://tiles.smellman.org/takano32_test/{z}/{x}_{y}.png', {
         attribution: 'Map data &copy;',
         continuousWorld: true,
         zIndex: 1,
         minZoom: 11,
         maxZoom: 12
       }).addTo(map);
```
[PR 3505 Problem demo](http://smellman.github.io/Leaflet_PR_3505/pr_3505.html)
In this case, start at zoom 10 and zoom-in to 11 is ok. But zoom-out from 11 to 10 show zoom 11's cache.

I make a proposal to add option like a errorTileUrl to L.tileLayer.

```javascript
       map = L.map('map', {
         maxZoom: 12,
         minZoom: 8,
         crs: L.CRS.Simple
       });
       // ...
       var layer1 = L.tileLayer('http://tiles.smellman.org/red/{z}/{x}_{y}.png', {
         attribution: 'Map data &copy;',
         continuousWorld: true,
         zIndex: 2,
         minZoom: 8,
         maxZoom: 11,
         opacity: 0.5,
         outOfZoomTileUrl: './empty.png'
       }).addTo(map);
```
[outOfZoomTileUrl proposal demo](http://smellman.github.io/Leaflet_PR_3505/zoomtest.html)
New option: outOfZoomTileUrl used when map's current zoom is out of layer's zoom range. In this case, empty.png will use instead of tile url when zoom level is 12. Also, browser don't get 404 errors by zoom level.

**Comment by mourner** [comment]
I see the problem, although I think it should probably be handled differently — e.g. by clearing the tile layer buffers when your going past the zoom range.

**Comment by smellman** [comment]
@IvanSanchez Thank you. Your patch is good for our products.
