### ISSUE TITLE
Safari stops zooming on continuous trackpad scrolling

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#3516]
That feels really weird and buggy from UX points of view. We should look into why that happens.

**Comment by IvanSanchez** [comment]
Is this on the `events-refactor` branch or in `master`?

**Comment by mourner** [comment]
Both. When you do a slow trackpad swipe, it zooms 1-2 times and then stops (unlike other browsers). Which makes it quirky when you're trying to navigate quickly.

**Comment by IvanSanchez** [comment]
Related to #2154?

**Comment by mourner** [comment]
@IvanSanchez well, that issue is more general - it's about the trackpad user experience on all browsers. This one is specifically about Safari.

**Comment by glathoud** [comment]
For what it's worth, here are some facts I could gather during a failed attempt to solve this, using 0.7.3:

1. If you put a mousewheel listener on the document.body, it *also* stops firing after a while (even with capture:true). So it can only be a bug internal to OSX and/or Safari.

2. in _tileOnLoad, if you comment out this line: ``` L.DomUtil.addClass(this, 'leaflet-tile-loaded'); ```  then the various mousewheel listeners keep firing - which is correct. But of course you don't see any tile anymore.

3. Alternatively, if you comment out the whole contents of leaflet.css, the various mousewheel listeners also keep firing (correctly). You can see tiles but of course the whole layout is then broken.

4. The current google maps version does not seem to have this problem. I could not find the decisive difference, though.

I hope this helps.

**Comment by mourner** [comment]
@glathoud nice research, thanks! Hopefully we can find the source on this one...

**Comment by IvanSanchez** [comment]
We need to test this again now that #3653 has been merged

**Comment by mourner** [comment]
Not reproducible anymore, yeah!
