### ISSUE TITLE
_pruneTiles throws exception when swapping TileLayers

### ISSUE THREAD

**Issue by skalb** [Leaflet/Leaflet#3522]
I get an exception on the following line if I switch the TileLayer/GridLayer before it's finished loading all tiles: https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/GridLayer.js#L238

Currently, I'm removing the current TileLayer/GridLayer before I add the new one, which means the layer loses reference to underlying map object.

Shouldn't there be a null reference check for map before getting the current zoom?

**Comment by mourner** [comment]
Maybe. Can you put up a JSFiddle?

**Comment by skalb** [comment]
Upon further testing, it seems it's the combination of layer change then map move/pan:

http://jsfiddle.net/skalb/2vu5gper/10/

**Comment by skalb** [comment]
Wow, thanks for the quick turnaround!

I'm still seeing this issue in our app sometimes, if the map pans at all before it's moved. Perhaps due to the throttle interval delay?

Example here: http://jsfiddle.net/skalb/2vu5gper/11/

(to see the error you need to move the map before the 500ms timeout executes)
