### ISSUE TITLE
layer.bindPopup does not use offset option

### ISSUE THREAD

**Issue by skalb** [Leaflet/Leaflet#3525]
Some of the popup options are used, like closeButton, but not offset.

Example here: http://jsfiddle.net/skalb/7mjgLokx/1/

**Comment by snkashis** [comment]
Bisect indicates https://github.com/Leaflet/Leaflet/commit/ff470d586150fbc6e51e1b99662d80e6864985f0 as where we should be looking.

**Comment by IvanSanchez** [comment]
I'm going to point a finger to https://github.com/Leaflet/Leaflet/commit/ff470d586150fbc6e51e1b99662d80e6864985f0#diff-030637463a34ab9099284091317e4775R92

**Comment by yohanboniface** [comment]
Meeeh, I was pointing to https://github.com/Leaflet/Leaflet/blob/master/src/layer/Layer.Popup.js#L130 too ;)
We may self assign an issue before looking at it :p

**Comment by mourner** [comment]
сс @patrickarlt

**Comment by snkashis** [comment]
Could be as simple as this possibly?

**Comment by snkashis** [comment]
Nope, back with something else in a bit.

**Comment by snkashis** [comment]
Yeah, functional now, but slight unintentional horizontal offset introduced. I don't think I'm placing this in the right area. @patrickarlt @IvanSanchez you probably have a better idea.
