### ISSUE TITLE
bounceAtZoomLimits=false prevents tiles from loading

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#3530]
How to reproduce:

* In any map, set `minZoom` and/or `maxZoom`, plus `bounceAtZoomLimits` to false.
* Using a touchscreen/tablet/phone, pinch-zoom until you reach either zoom limit
* When reaching the zoom limit:
 * It is impossible to pan the map
 * When releasing the pinch, tiles are not loaded properly.

**Comment by IvanSanchez** [comment]
Had a brief look removing the return condition from `Map.TouchZoom.js`. When hitting the zoom limit, `L.Map._zoom()` is still called with the right arguments, and the map's `_pixelOrigin` is updated, and events are fired, but nothing refreshes.

**Comment by IvanSanchez** [comment]
I plan to set up some unit tests with [prosthetic-hand](https://github.com/IvanSanchez/prosthetic-hand) to debug this.

**Comment by IvanSanchez** [comment]
I think I've found the root cause of this.

Whenever `L.Map._move()` is called with the same zoom level, the `pixelOrigin` gets updated, but all the layers ignore the `move` map event!

Most layers react to the `zoom` and `viewreset` events to redraw themselves. When the user is performing two-finger interactions, the `zoom` event is fired on every frame, which triggers the redrawing/repositioning of stuff around. However, **layers do not react to the `move` event** at all.

This creates a funny edge case: a two-finger pan where the pixel distance between fingers is exactly the same (not humanly possible, but shows easily with prosthetic-hand).

I see a couple of approaches to the problem:
* Fire `viewreset` in `L.Map._move()` when the zoom level stays the same
* Fire `zoom` in `L.Map._move()` if called from `L.Map.TouchZoom` (via the `pinch` flag)
* Make all layers respond to the `move` event in a similar fashion to `viewreset` (more work, might incur in duplicate repositionings)

**Comment by IvanSanchez** [comment]
I have made a handy webpage for testing this in the [`bounce-touch`](https://github.com/Leaflet/Leaflet/tree/bounce-touch) branch

**Comment by mourner** [comment]
Oh wow. That's a tricky one. I guess the lesser of all evils would be to fire `zoom` when pinch-zooming even when a zoom doesn't change.

**Comment by yohanboniface** [comment]
Nice investigation!
But why is it working with mouse and not the touch? i.e. where is the breakpoint between both scenarios?

**Comment by IvanSanchez** [comment]
@yohanboniface As far as I remember, mouse interactions rely on `L.Draggable` and do not call `L.Map._move`.
