### ISSUE TITLE
Events fired from DoubleTap ignore stopPropagation

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#3532]
This is better explained with an example:

* Using anything with a touchscreen, go to any page with a map that has a `L.Control.Zoom`. http://leafletjs.com/examples/mobile-example.html works OK for this.
* Zoom all the way out, so that the "zoom out" button is disabled and grayed out.
* Double-tap on the "zoom out" button.
* See how the map is zoomed in because of a `dblclick` event, even though `L.Control.Zoom._createButton` explicitly stops propagation of dblclick events.

This is reproducible both on 0.7.3 and master.

Maybe our resident expert in events @yohanboniface can shed some light on the issue. And BTW, the bug also happens in the `map-domevent` branch, in case you were wondering.

**Comment by perliedman** [comment]
This sounds like a duplicate of #16, so if this is fixed, #16 should also be closed, right?
