### ISSUE TITLE
Leaflet Benchmarks?

### ISSUE THREAD

**Issue by colllin** [Leaflet/Leaflet#3537]
Do you have a standard way of benchmarking Leaflet?  If I'm contributing a pull request, I would like to make sure that I'm improving or at least maintaining current performance.

**Comment by mourner** [comment]
There are no formal benchmarks yet. It's pretty hard to measure performance of things that are reliant on DOM. If you think your pull request can affect performance, you're welcome to write a benchmark specific to the feature you're adding.
