### ISSUE TITLE
L.Path.mergeOptions does not affect classes that inherit from L.Path

### ISSUE THREAD

**Issue by ellvtr** [Leaflet/Leaflet#3538]
Example `L.Path.mergeOptions({color:'red'});` - that does not affect classes that inherit from L.Path, only L.Path itself.

The inheritance from L.Path to other vector classes seems to take place before I get the chance to run that statement, ie the change affects only L.Path, not eg L.Circle which remains blue. When I write L.Circle.mergeOptions({ color: 'red' }); in my app, it works - for circles only. I'd have to do that for all L.Path subclasses. 

See more detailed description here:
http://gis.stackexchange.com/questions/150935/configure-default-styles-in-leafletjs

**Comment by danzel** [comment]
Why do you want this?
I would expect you to set the color of the things you add if you care what color they are.

**Comment by ellvtr** [comment]
If that behaviour was not intended, then I guess it is not a bug, but at feature request. 

You ask why? Most apps have a colour scheme - i.e. just like configuring the map's projection or the default layout of markers and popups, it makes sense to configure a default style for all vector layers, to fit the overall style/layout of the app. In specific cases, the developer may want to overrule the default style.

**Comment by FadilEldin** [comment]
Think should be closed
