### ISSUE TITLE
Add GCJ-02 coordinate system for users in China?

### ISSUE THREAD

**Issue by hanfeisun** [Leaflet/Leaflet#3542]
[GCJ-02][1] is a standard coordinate system in China based on WGS-84. However, I didn't find a leaflet plugin which could enable `crs: L.CRS.GCJ02` option..

I was just wondering whether it is possible for Leaflet or plugins to support GCJ-02..

  [1]: https://en.wikipedia.org/wiki/Restrictions_on_geographic_data_in_China

**Comment by IvanSanchez** [comment]
Is it possible? Yes.
Has it been done yet? No.
Will it be done in the core Leaflet (which is what this issue tracker is for)? Most probably not.

**Comment by perliedman** [comment]
I haven't used it myself, but it looks like it should be pretty straight forward to use this library: https://github.com/googollee/eviltransform/tree/master/javascript

Given that GCJ-02 seems like weird thing (deliberately obfuscating data, see https://en.wikipedia.org/wiki/Restrictions_on_geographic_data_in_China#GCJ-02), I don't think it's a good fit for something in Leaflet core, but it could definitely be a nice plugin.

**Comment by dbauszus-glx** [comment]
I would very much like to write a plugin for GCJ-02. Please let me know if anybody is still interested in this.
