### ISSUE TITLE
Use .osm local file

### ISSUE THREAD

**Issue by inakigarcia** [Leaflet/Leaflet#3543]
Hi everyone.

I'm triying to render a local .osm file in local but I don't find any example of this.
Is there any way to do this? Do I need to conver this file? Am I completely wrong?

Thanks you for your time.

**Comment by IvanSanchez** [comment]
Iñaki,

Do not use the github issue tracker for questions on how to use leaflet for your project. That's pretty clearly explained in https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md#reporting-bugs

Either get tilemill/kosmtik to render your data into tiles, or research how to use some of the vector tiles plugins.
