### ISSUE TITLE
open attribution link with target=_top

### ISSUE THREAD

**Issue by oberhamsi** [Leaflet/Leaflet#3546]
we embed leaflet with an iframe (oldschool.. but i guess we are not alone). what do you think of opening the attribution with target="_top" per default?

i've seen  #2644

**Comment by mourner** [comment]
Well my answer is the same as in #2644.

**Comment by oberhamsi** [comment]
i would argue it's okay (not bad practice) for something likely used in an iframe, because unless leaflet is used in frame/iframe scenario, _top behaves identical to no target attribute.

but i can live with the manual solution in #2644
