### ISSUE TITLE
Use “map.setView()” to align a LatLng to position other than center?

### ISSUE THREAD

**Issue by hanfeisun** [Leaflet/Leaflet#3553]
The current setView API looks like this:

```
setView( <LatLng> center, <Number> zoom?, <zoom/pan options> options? )
```

The first parameter is a `LatLng` object, which will be aligned to the center of the map.

However, sometimes, it would be very helpful if `LatLng` object could be aligned to 25% from the bottom of the map instead of center (center, as a special case, might be 50% from the bottom of the map and 50% from the left of the map). 

Would it be possible for this parameter (align position) to be added somewhere in the option?

**Comment by mourner** [comment]
Yes. Currently something similar is possible with `fitBounds`. See #859 for more discussion.

**Comment by IvanSanchez** [comment]
There are a couple of plugins (active-area and ControlledBounds) that might help: http://leafletjs.com/plugins.html#events

**Comment by johnd0e** [comment]
[latLngToContainerPoint](https://leafletjs.com/reference.html#map-latlngtocontainerpoint), [getSize](https://leafletjs.com/reference.html#map-getsize), [scaleBy](https://leafletjs.com/reference.html#point-scaleby), [containerPointToLatLng](https://leafletjs.com/reference.html#map-containerpointtolatlng)
