### ISSUE TITLE
how depict count roads via leaflet

### ISSUE THREAD

**Issue by KEFIR4UK** [Leaflet/Leaflet#3554]
Hi.I have the following There is graph describing the road network.
Tables describing the nodes and edges is in the database Postgresql
How i can via Leaflet show this graph ?

**Comment by mourner** [comment]
Hey, thanks for using Leaflet! However, this is a place to report Leaflet issues, not to request support for your app.  Please try asking on the <a href="https://groups.google.com/forum/#!forum/leaflet-js">Leaflet forum</a> — you are more likely to find help there.
