### ISSUE TITLE
IE9, v1.0-dev: custom layer pane features offset after panning

### ISSUE THREAD

**Issue by tmfrnz** [Leaflet/Leaflet#3555]
the new createPane function is great however, features added to a custom pane appear to "lose" their position after panning the map on IE9. features on the default pane however are synchronised correctly with the basemap. a subsequent zoom will re-align the features again

see attached screen shot that shows the same feature on the default pane (outline) and on a custom pane (filled) after panning the map
![ie9 issue leaflet](https://cloud.githubusercontent.com/assets/5811956/8295429/a6ffb2ae-1998-11e5-92fc-eb57ad7fab3d.png)

**Comment by mourner** [comment]
Thanks for the report! Can you set up a minimal JSFiddle test case for that?

**Comment by mourner** [comment]
Closing, will reopen if there's a proper test case.
