### ISSUE TITLE
load event not firing in leaflet

### ISSUE THREAD

**Issue by ramprakash-ravi** [Leaflet/Leaflet#3560]
I'm trying to do a business logic on a map whenever some events are done by a user.

I'm able to get working drag , dblclick and zoomstart events.
But load event is not getting fired for me. (On Browser load initially)

My sample code below :
```javascript
  var map = L.map('map').setView([34.7320,-86.5966], 14);

  map.on('load drag dblclick zoomstart', function() {      
         // My business logic goes here.
  });
```

**Comment by IvanSanchez** [comment]
The `load` event is firing before the `load` event handler is attached, as you're running `setView` right after instantiation.

This, in the other hand, is what you want:
```js
var map = L.map('map').on('load', function(){......}).setView([34.7320,-86.5966], 14);
```
