### ISSUE TITLE
Attribution is not changed between layers when using custom prefix

### ISSUE THREAD

**Issue by pufanalexandru** [Leaflet/Leaflet#3565]
Hello!

In the master version of Leaflet, I have two layers, each with their own attribution. I initialize my map with `attributionControl: false`, because I want to create a custom prefix. But when I do that, the attribution of the layers won't change anymore when I switch them. Below is a JSFiddle demonstrating this issue, change the layers and note that the attribution remains the same:

http://jsfiddle.net/exa2xwvu/1/

This works well in the stable version of Leaflet.

**Comment by rowanwins** [comment]
HI @pufanalexandru 

Have a look at this [updated fiddle](http://jsfiddle.net/rowanwins/exa2xwvu/3/) for a solution

What you need to do is 
````
map.attributionControl.setPrefix('Created by Alexandru Pufan using <a href="http://www.leafletjs.com" target=_blank>Leaflet</a>');
````
Hope this helps
Rowan

**Comment by pufanalexandru** [comment]
Yes, this works fine, thanks. I'm just curious, is this an issue, or just a problem with my code?

**Comment by rowanwins** [comment]
Hi @pufanalexandru 

It was just a problem with your code. I think that your original approach wasn't watching for changes to the map as it wasn't bound to it, it was just there as a standalone attribution control. If you could close the issue im sure that would be appreciated :)

Cheers
Rowan

**Comment by pufanalexandru** [comment]
Sure, thanks!

**Comment by mourner** [comment]
@rowanwins thanks for looking into this!
