### ISSUE TITLE
XY bounds for L.tileLayer in CRS.Simple

### ISSUE THREAD

**Issue by Fynjy888** [Leaflet/Leaflet#3567]
Sorry for my english

Hi, I have leaflet.js (image of map 5913x7863) and there L.CRS.Simple

I had

```
var imageBounds = [[1468.9700,-11.7050], [1968.2705,363.7705]];
var file0 = new L.imageOverlay(imageUrl, imageBounds).addTo(map);
```
and everything was good, but I understood, that L.imageOverlay - it's wrong way and I need tiles. So now I have

```
L.tileLayer('images/tiles/{z}/{x}/{y}.png', {
continuousWorld: true,
noWrap: true,
maxZoom: 6,
minZoom: 3 
}).addTo(map);
```
But I don't know how to do L.tileLayer with this bounds (coordinates) [1468.9700,-11.7050], [1968.2705,363.7705]

Now bounds near this: [0,0], [-123,92], but I need [1468.9700,-11.7050], [1968.2705,363.7705]
And **I don't understand why is so hard to do bounds with tiles as easy with imageOverlay?**

I have tried this:
```
var southWest = L.latLng(1468.9700,-11.7050),
northEast = L.latLng(1968.2705,363.7705),
mybounds = L.latLngBounds(southWest, northEast);
...
bounds: mybounds
```
but it have not helped. 

So my issue is: **I want the same option like imageBounds for L.imageOverlay, but for L.tileLayer (for example tileBounds)**

If I don't understand something, and solution for L.CRS.Simple and XY coordinates exist - I'm sorry, but I haven't found it.

P.S. Thanks for answers

**Comment by perliedman** [comment]
Hi, thanks for using Leaflet! This place is the issue tracker for Leaflet, a place to report bugs and new feature requests.

Questions on using Leaflet is better to post on [the leaflet forum](https://groups.google.com/forum/#!forum/leaflet-js), the IRC channel, or just ask on stackoverflow or gis.stackexchange.com. Thanks!
