### ISSUE TITLE
Mouse events on canvas rendering have possible race condition 

### ISSUE THREAD

**Issue by shawel** [Leaflet/Leaflet#3568]
Hovering over one layer to another (say two different adjacent states ) triggers mouseover and mouseout events in different order.  This is not appear to be the case in svg rendering. 
["mouse over"]
["mouse out"]
["mouse over"]
 ["mouse over"]
["mouse out"]
A hack i currently have in my code is to execute code on mouseover to be about 100ms delay using setTimeout

**Comment by danzel** [comment]
Could you make a jsfiddle to reproduce this? Thanks

**Comment by shawel** [comment]
Here is a code pen showing the mouse event triggers.  It shows the tooltip on some states disappearing b/c of mouse event sequence. It happens only on canvas rendering.  

http://codepen.io/anon/pen/Jdpdav   <= canvas version 
http://codepen.io/anon/pen/rVJVqG  <= svg version

Another unrelated issue I found is, overlapping layers like circles drawn on each state, randomly disappear when you change styles of state layers on mouse over event. The problem can be seen on the same code pen. I can create a new issue. This also happens on the canvas drawing only.  

-- Thanks for a great library. Saved me a lot of time on many projects. The performance on the new version of leaflet is impressive. I was looking to upgrade.

**Comment by mourner** [comment]
Yay fixed!

**Comment by shawel** [comment]
Just tested the problem still exists. 
new build
http://codepen.io/anon/pen/eNVBJz

**Comment by mourner** [comment]
cc @wpf500 :(

**Comment by wpf500** [comment]
I think this is because the canvas hit detection is calculating that the layers are "overlapping". Given that under normal circumstances (i.e. real SVG) you would never get `mouseover` for more than one element at time, the fix is probably just to only look for one hit then stop. What do you think @mourner?

**Comment by mourner** [comment]
@wpf500 yes, sounds right.

**Comment by mourner** [comment]
@shawel how about now?

**Comment by shawel** [comment]
@mourner @wpf500  it works now :+1:
