### ISSUE TITLE
non-square tiles?

### ISSUE THREAD

**Issue by fabiosantoscode** [Leaflet/Leaflet#3570]
To faithfully represent non-square images one needs to use non-square tiles.

Unfortunately leaflet does not support this.

Last year I did a nasty patch so that it does support this (options.tileSize became a Point) and went on to create a zoomable image gallery.

Would you like me to clean up that patch and do a pull request, or is this feature out of the scope of the project?

**Comment by Eschon** [comment]
:+1: Would be a nice feature.
For now my solution was to fill up border tiles with a transparent background.

**Comment by mourner** [comment]
How difficult would it be to do? Whether I want to merge this in depends on how much complexity and additional code it introduces in the codebase.

**Comment by fabiosantoscode** [comment]
IIRC, it was a small change in the initialisation (if options.tileSize is a Number, it's now a Point...), and in a dozen lines which use tileSize to calculate stuff.

**Comment by IvanSanchez** [comment]
> How difficult would it be to do?

Not a lot, actually. See https://github.com/IvanSanchez/Leaflet.GridLayer.NonSquare

I guess the decision to merge it (or to leave as an already-working plugin) depends on if we want `L.GridLayer.options.tileSize` to be a `L.Point` or to remain as an integer.

**Comment by mourner** [comment]
We certainly don't want to break compatibility, but we could make Leaflet accept both a number and a Point.

**Comment by IvanSanchez** [comment]
Not breaking compatibility to the client is easy, see https://github.com/IvanSanchez/Leaflet.GridLayer.NonSquare/blob/gh-pages/L.GridLayer.NonSquare.js#L7 - but plugins developers might expect the tile size to always be an integer :-S

**Comment by mourner** [comment]
Can you think of a use case where a plugin developer may get burned by this?

**Comment by IvanSanchez** [comment]
> Can you think of a use case where a plugin developer may get burned by this?

https://github.com/IvanSanchez/Leaflet.MandelbrotGL/blob/master/src/Leaflet.GridLayer.MandelbrotGL.js#L53 and https://github.com/namrehs/Leaflet.Gigapan/blob/master/L.TileLayer.Gigapan.js#L28

Granted, as long as the default is an integer, and as long as `L.GridLayer.options.tileSize` remains an int no matter how many times `_getTileSize()` is called, everything should work, but plugins extending gridLayer might need some extra work to make this work. Maybe there's a need to document `_getTileSize()`.

**Comment by mourner** [comment]
Or make it public `getTileSize()`. Generally I think it's not a huge problem if someone uses MandelbrotGL plugin and suddenly realizes that it breaks when setting non-square tiles.

**Comment by IvanSanchez** [comment]
As long as the GigaPan or WMTS plugins don't break, it should be fine. I don't have a strong opinion about having this functionality, though.

**Comment by IvanSanchez** [comment]
Agh, I messed up the nomenclature for vector math. I'll push a fix directly to master with just the name changes later.
