### ISSUE TITLE
Move map at the edge of map on marker dragging

### ISSUE THREAD

**Issue by marslan390** [Leaflet/Leaflet#3572]
when you drag a marker to the edge of the map, the map would pan along with you, making it easy to move your marker long distances.  But, as far as I can tell, Leaflet doesn't do this.  In  order to move your marker to a location that isn't currently visible, you have to zoom out, move your marker, and then zoom back in.

Am I missing something?

**Comment by mourner** [comment]
Yes, that's a feature that Leaflet is missing currently.

**Comment by IvanSanchez** [comment]
I gave a shot at this a couple days ago. Triggering a map `panBy()` and then hacking some offset in the `Marker._draggable` in four different ways only proved to be incredibly glitchy.

I'm afraid this doesn't look easy to implement :-(
