### ISSUE TITLE
Windows Phone 10: openstreetmap.org: remove -ms prefix from touch-action

### ISSUE THREAD

**Issue by TheWebJustWorks** [Leaflet/Leaflet#3579]
To reproduce: 

1. (using Windows 10 Mobile) Navigate to openstreetmap.org 
2. Try to pan map left and right using touch

Expected: map pans left and right
Actual: map doesn't pan

Site is using Leaflet map plugin, which only provides –ms-touch-action (and not touch-action).  Adding the unprefixed touch-action makes everything work fine.  

.leaflet-container {

    overflow: hidden;

    -ms-touch-action: none
![leaflet_capture](https://cloud.githubusercontent.com/assets/8117557/8441534/cc18ad6c-1f2d-11e5-9008-bd2463f5201f.PNG)

**Comment by IvanSanchez** [comment]
Is this reproducible anywhere else? (e.g. http://leafletjs.com/examples/mobile-example.html ?)

**Comment by mourner** [comment]
Yeah, it's already fixed in the 1.0-dev version (soon to be released): https://github.com/Leaflet/Leaflet/blob/master/dist/leaflet.css#L20

Meanwhile patching this up on OSM side is easy enough.

**Comment by TheWebJustWorks** [comment]
Awesome! thanks for the quick reply's here - will update on our end that this issue has been fixed in 1.0-dev
