### ISSUE TITLE
Layer setStyle masks/dissappears top layers sporadically on canvas drawing. 

### ISSUE THREAD

**Issue by shawel** [Leaflet/Leaflet#3583]
Circles drawn on top of state layers disappear sporadically when setStyle is applied on mouse over events on state layers. Happens on canvas drawing. 

using current build of leaflet. 
http://codepen.io/anon/pen/VLQmZy

**Comment by mourner** [comment]
Interesting. Looks like a rendering order issue. Can you trim the example into the smallest reproducible test case?

**Comment by shawel** [comment]
I have narrowed the test case to 2 state layers and each state layer contain 1 circle layer.
I noticed: 
- when you change style of state layer using mouseover event, circles in other state layer disappear.  
- the problem in this test case does not exist on zoom 4 or less. 
- when you pan the map the circles appear again. 


http://codepen.io/anon/pen/rVdrrd

**Comment by shawel** [comment]
closed by mistake

**Comment by mourner** [comment]
@shawel could you reduce the test case even further? Stripping titles, tooltips, d3, topojson etc. Maybe simplifying the shapes as well... Debugging the current example is a bit cumbersome...

**Comment by shawel** [comment]
@mourner ok i will make a simpler version.

**Comment by yohanboniface** [comment]
@shawel reminder about the need of a simple test case :)

**Comment by yohanboniface** [comment]
Here is a first simplified version that reproduce the issue: http://playground-leaflet.rhcloud.com/lak/edit?html,output

Not looked at the code at all yet, and not sure I'll have time before Monday, so anyone wanting to jump in, feel free :)

**Comment by mourner** [comment]
Oh, I see the problem now. When a vector shape intersects the redraw bbox, it is redrawn fully, including parts that are outside the redraw bbox and that may overlap other features that don't get redrawn. The fix would be to _only_ redraw the part of feature that's inside the redraw bounds. We should try to use the Canvas `clip` method for that.

**Comment by yohanboniface** [comment]
@mourner https://github.com/Leaflet/Leaflet/pull/3840/files ?
