### ISSUE TITLE
Turn off layer crossfade when layer has semi-opaque content?

### ISSUE THREAD

**Issue by lucasgunn** [Leaflet/Leaflet#3589]
I have a layer that has arbitrary semi-opaque png content. When zooming, the crossfade effect between the old and new content of the layer causes a flicker of heavier colour, then back to normal once the old content is hidden/removed. Can I turn off this cross fade, and just cause the layer to immediately hide the old tiles on zoom end? I get this is to facilitate the nice redrawing of normal raster tiles on zoom, but I've got to try and get rid of this colour shift.

See attached video: https://vid.me/Ql1B

I can't for the life of me figure out where/if there is a setting for the crossfade effect on layer zoom.

**Comment by lucasgunn** [comment]
OK, so it removes the old tiles when the new ones are all loaded. Can I work around that somehow?

**Comment by mourner** [comment]
What's your expected behavior? Having a different type of flicker when your overlay disappears for a moment and then the new one loads? 
Seamless blending in this situation is pretty much impossible technically, or at least very very challenging, so we can't deal with that in the nearest future.

**Comment by lucasgunn** [comment]
Yep, fair enough - that's pretty much what I suspected was the case. Just needed to make sure.
