### ISSUE TITLE
Marker recalculation

### ISSUE THREAD

**Issue by RassaLibre** [Leaflet/Leaflet#3597]
Hei, silly question. I am receiving new lat lngs via websockets and updating my marker based on the data I get. To make the movement smooth I have a transition on `transform` property. It works just awesome but sometimes when you zoom in or out, the recalculation of the marker is done after the zooming ended. This means, that the marker is suddenly relocated after one zooms. The problem when using the transition is that this relocation does not happen immediately but it animates to the position where it should be which is not what one wants. Is there a way how to fetch an event for example `markerrecalculationstart` and `markerrecalculationstart` end?

I had the same problem when zooming but I solved it by removing the transition on `zoomstart` and appending it again on `zoomend`. Any suggestions?

**Comment by mourner** [comment]
Can you demonstrate the problem with a minimal JSFiddle test case?
