### ISSUE TITLE
Fierfox issues 

### ISSUE THREAD

**Issue by kiran15** [Leaflet/Leaflet#3602]
Hi while login i used remember password checkbox of firefox. After login the remembered email and password is autofilled in the text boxes of names with names given as textfield as value=mobileNumber and value=pass.

Here in above textField, mobileNumber is stored with emailId and pass is stored with password, which is entered at the time of login.
<input type="text" value= email/>
<input type="text" value= mobilenumber/>
<input type="text" value= pass/>
how to solve this problem please help me 
i put type="string" now its working fine but we dont have input type="string"
my approach :
<input type="string" value= email/>
<input type="string" value= mobilenumber/>
if any other solution is there please informe 

please look into this : http://stackoverflow.com/questions/8379091/how-can-i-avoid-browser-prepopulating-fields-in-my-registration-form

**Comment by IvanSanchez** [comment]
Not a Leaflet issue.
