### ISSUE TITLE
Click bubbling from marker to map

### ISSUE THREAD

**Issue by ktoto** [Leaflet/Leaflet#3604]
I have:
* marker with popup
* map click handler (for geocoding)

When I click on marker I've got 'click' event on both map and marker.
So popup opened (ok) and geocoding start working (wrong!).

Why event from marker propagates to underlying  map?
How I can prevent this?

**Comment by mourner** [comment]
It doesn't propagate, at least not in my tests. Can you set up a JSFiddle test case that demonstrates your problem?

**Comment by ktoto** [comment]
https://github.com/Leaflet/Leaflet/blob/master/debug/map/markers.html
Click on marker. In console:
```
markerStatic click
map click
```

**Comment by mourner** [comment]
@yohanboniface was this broken after your PR?

**Comment by yohanboniface** [comment]
I'm in a workshop (as a trainer), I'll look on this tonight :/

**Comment by mourner** [comment]
@ktoto please verify the fix.

**Comment by ktoto** [comment]
@mourner It's works for me. :)
