### ISSUE TITLE
preventOutline not always work correctly

### ISSUE THREAD

**Issue by ktoto** [Leaflet/Leaflet#3606]
Make marker with icon with DIV inside:
```js
	var icon = L.divIcon({
		iconSize: null, 
		html: '<div>test marker</div>'});
```
When click on this marker - we have outline border on it.
It happend, because `e.target` for this `mousedown` event is div with text, not whole divIcon marker. :(

May be return `L.DomEvent.propagateDefault(e)` for preventing outline? :)

**Comment by mourner** [comment]
cc @jfirebaugh

**Comment by mourner** [comment]
Should be fixed, please verify.

**Comment by ktoto** [comment]
Fixed.
