### ISSUE TITLE
Mouse events on markers only return the marker's single latlng point

### ISSUE THREAD

**Issue by skalb** [Leaflet/Leaflet#3607]
We use DivIcon markers to display text on our maps, but it looks like https://github.com/Leaflet/Leaflet/pull/3032/files changed marker events to always fire with the marker's single LatLng ignoring the mouse event information.

Not sure if this is a bug, or our use case is just not handled.

Hopefully this simplified fiddle explains better: http://jsfiddle.net/skalb/3sc6nk6b/1/

**Comment by yohanboniface** [comment]
@skalb can you try with current master? (i.e. with #3307 but before #3605 will be merged)

**Comment by skalb** [comment]
I updated the fiddle with the version I downloaded yesterday: d2513b2
