### ISSUE TITLE
Over-helpful JS causing accessibility problem on docs page

### ISSUE THREAD

**Issue by callumlocke** [Leaflet/Leaflet#3609]
If you click/highlight anything at http://leafletjs.com/reference.html the page jumps around. This is a big accessibility problem.

There is already a little 'link' button to get an anchor to the hovered row (shown below), this should be enough of a click target. Please can you remove the JS mouseup listener on the rest of the row?

![image](https://cloud.githubusercontent.com/assets/250617/8600903/74949756-2660-11e5-8472-7006575745bd.png)

**Comment by mourner** [comment]
I agree! I think we fixed this at some point but apparently it regressed...
