### ISSUE TITLE
Overlapping polylines and multipolylines increase in opacity at Intersection - Why?

### ISSUE THREAD

**Issue by rwillett** [Leaflet/Leaflet#3610]
Hi,

We're struggling with an odd issue when using multilines. Very simply if you have two or more lines that overlap each with less than 1 opacity, the intersection of the lines has a 'stronger' opacity. A picture is worth a thousand words so here it is :)

![screen shot 2015-07-09 at 16 56 31](https://cloud.githubusercontent.com/assets/668923/8605489/9ba63cec-267d-11e5-8b3a-5a3f968ac99d.png)

The 'strong' red horizontal line in the middle actually has the sam opacity as all the branches but it looks as if the opacity is now 1.0 when its not.

We've been playing about with polylines and multipolylines, various configuration items such as color, weight, opacity, fillopacity, smooth factors, in fact anything we can find to see if we can have an even opacity across all the multiple lines. 

The documentation does seem to give any hint about this and none of the forums seem to have anything about this which is odd as we think its a problem.

We're generating all the points as either a single multiPolyline or as multiple polylines. We tried both approaches to see if they made a difference. They don't :)

Any hints or pointers to docs that can help is much appreciated. We don't want to generate a complex polygon and fill it when a simple stroke will work (or should work)

The only link we could find was this

http://www.widecodes.com/0ymVgWkejj/leaflet-overlapping-shapes-opacity.html

which assumes we can't do it but doesn't say it definitively.

Thanks for reading

Rob

**Comment by mourner** [comment]
This is just the way SVG works, and Leaflet has nothing to do with it. If you want the color to be even across overlapping lines, you have to use opacity: 1.

**Comment by rwillett** [comment]
Ok, thanks for the quick reply. 

We need a transparent or semi opaque area, so we'll have to calculate a rather complex polygon to draw. 

Rats, thats a couple of days work.

thanks anyway.
