### ISSUE TITLE
v0.7 Firefox 38.0.5 & Chrome 43.0.2357.130 m -  fill improperly rendering when points off screen

### ISSUE THREAD

**Issue by softsprocket** [Leaflet/Leaflet#3611]
To Reproduce:
Create a non-regular shaped, filled polyline and scroll part of it off the screen. The fill will act as though the points off screen don't exist. 0.6 doesn't exhibit this behavior.

**Comment by mourner** [comment]
If you need a filled polyline, use a polygon. Also, please provide a JSFiddle test case and screenshots of the issue if you think it's valid.

**Comment by softsprocket** [comment]
Switching to polygon after the shape was drawn did fix the issue. It might be worth a mention in the docs.
