### ISSUE TITLE
How to order TileLayers mixed with Geojson Layers?

### ISSUE THREAD

**Issue by cosme-benito** [Leaflet/Leaflet#3616]
I wish to be able to change the order of presentation between several Geojson and TileLayers which are mixed up (IE: I may want a Geojson to be "below" a a TileLayer or vice versa). So far I have searched a lot, upgraded to the 0.8 master branch and did not have success.

To accomplish what I wanted I tried to create a "customPane" and sort the layers using the bringToFront() and bringToBack() but while this works for layers of the same "type" it doesn't work between Geojson and Tile layers, so I'm back to square one.

I have created a plunkr with my logic so far: http://plnkr.co/edit/2oKB9InPF42OWXTCYvqW?p=preview

It generates the following html:
    `<div class="leaflet-pane leaflet-custom-pane">`
        `<div class="leaflet-layer"> <!-- Tile layer here --></div>`
        `<svg pointer-events="none" class="leaflet-zoom-animated"><!-- Geojson layer here --></svg>`
    `</div>`

Playing with the zIndexes of the div.leaflet-layer or svg element accomplishes what I want, but I don't find a way to access this element within the code. Maybe something like geojsonLayer.getContainer().css('zIndex', 100); is possible but I'm just unable to find any reference.

Thank you for reading and for any help you can provide.

**Comment by mourner** [comment]
There's a pane management tutorial coming soon, see #3271 

Basically, to change the order of panes, you just change their order in the DOM. E.g. you can set zIndex to customPane.

**Comment by cosme-benito** [comment]
But I don't actually want to re-order the panes, I want to re-order the layers (which are mixed in the same custom pane). I could create a pane for each layer if that is the only solution to my problem but I believe there must be a simpler alternative that I am missing.

**Comment by mourner** [comment]
It's technically not possible to intermix vector layers and tile layers unless you create a separate pane for each layer, because vector layers of one pane are put under one SVG root.

**Comment by cosme-benito** [comment]
Alright, thank you very much for your help!
