### ISSUE TITLE
Make all leaflet-versions (stable/beta) available in npm/bower; Add installation instructions to README.md

### ISSUE THREAD

**Issue by fpauser** [Leaflet/Leaflet#3617]
This would help npm/bower-driven projects to integrate leaflet.

**Comment by mourner** [comment]
All released Leaflet versions are available in NPM and Bower. I don't think they need any installation instructions as it comes down to `npm/bower install leaflet`.

**Comment by fpauser** [comment]
Yeah, but only stable versions are released - so currently I cannot install 1.0.0-dev with npm.

**Comment by mourner** [comment]
That's because there were no published 1.0-dev releases yet. You can always install using just a git url though.
