### ISSUE TITLE
Old build in npm-package (0.7.2 instead of 0.7.3)?

### ISSUE THREAD

**Issue by fpauser** [Leaflet/Leaflet#3619]
I installed leaflet from npm doing `npm install leaflet`.
The version in `node_modules/leaflet/package.json` is 0.7.3, but L.Version in source (`node_packages/leaflet/dist/leaflet.js`) is 0.7.2.

So how to get the latest stable release (build) of leaflet using npm?

**Comment by mourner** [comment]
It's 0.7.3, just with a wrong L.version constant. See #2735
