### ISSUE TITLE
heatmap using leaflet

### ISSUE THREAD

**Issue by agstudy** [Leaflet/Leaflet#3622]
Hi,
Do you think is it possible to create a clustered/heatmap like [this one](http://www.zoopla.co.uk/heatmaps/) using leaflet package?

The clustered part is possible using clusterOptions of the markers but what about the colorpleth/hetmap part?

**Comment by yohanboniface** [comment]
See https://github.com/Leaflet/Leaflet.heat

Also, please note that is a place to post issues about Leaflet itself, not to request help. For this, you can use the [forum](https://groups.google.com/forum/#!forum/leaflet-js).
