### ISSUE TITLE
jQuery Mobile: tiles missing and locate not in the map center

### ISSUE THREAD

**Issue by googol7** [Leaflet/Leaflet#3624]
Steps to reproduce:

1. open: http://output.jsbin.com/gekowud in Chrome, Safari, Firefox or the iOS Simulator
2. the lower tiles are missing
3. press the tab "Locate".
4. your position will be located but the marker is not in the map center. all tiles are being loaded. in the iOS simulator tiles are still missing.

if you resize the browser in step 2. then all missing tiles will be loaded.

Please see the screenshots attached.

Please also test with the iOS simulator in the homescreen mode (website saved to the homescreen an run from there)

The CSS class .ui-content shall not be changed as this would affect the rest of the layout of the app. So we use the DIV with CSS class .map-outer to style the map.

![1_tiles_missing](https://cloud.githubusercontent.com/assets/282412/8674943/63b39498-2a41-11e5-8c29-f868ec46dbfc.png)
![2_locate_not_map_center](https://cloud.githubusercontent.com/assets/282412/8674944/63b7bb4a-2a41-11e5-946e-9c6467e497aa.png)

**Comment by mourner** [comment]
Use `map.invalidateSize()` after the map container size or visibility changed.

**Comment by googol7** [comment]
The map container size or visibility is not being changed dynamically here. The map is being created in the jQuery mobile event pageshow. So when should I call map.invalidateSize() then? Could you please correct the example http://output.jsbin.com/gekowud without styling .ui-content That would be great - thank you very much!

**Comment by mourner** [comment]
I'm not familiar with jQuery mobile — you'll have to ask for help on the Leaflet forum or figure it out yourself. This isn't a Leaflet issue if it can't be replicated without jQuery mobile.

**Comment by googol7** [comment]
ok - solved it here: http://jsbin.com/ruqaqo

by calling:

setTimeout(correct_view, 1);

in the jQuery Mobile "pageinit" event but don't consider it a very elegant solution though.

function correct_view() {
    map.invalidateSize();  
}

**Comment by googol7** [comment]
map.setZoomAround() doesn't seem to work here properly in http://jsbin.com/ruqaqo why is that? if you click on the tab "locate" the map center is not the found position of the user but slightly shifted.

**Comment by yohanboniface** [comment]
@googol7 you should ask on the forum for help using Leaflet: https://groups.google.com/forum/#!forum/leaflet-js
This issue tracker is only for Leaflet codebase itself.
