### ISSUE TITLE
preventOutline throws exception if map is wrapped in div with tabindex=-1

### ISSUE THREAD

**Issue by skalb** [Leaflet/Leaflet#3625]
I ran into this because we display maps in Bootstrap Modals which have tabindex=-1

See: http://jsfiddle.net/skalb/rgfdk25j/3/

As a workaround, adding tabindex="0" to the div#map element fixes it.

**Comment by mourner** [comment]
Thanks! Should be fixed in theory, can you confirm?

**Comment by skalb** [comment]
Looks good, thanks!
