### ISSUE TITLE
Merge gh-pages-master to gh-pages as a separate page

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#3627]
One less branch to care about, and enables us to have docs for several versions on the website. The only con is that people will have to submit parallel changes to 2 files in some cases.

**Comment by Jakobud** [comment]
What exactly needs to be done here?

**Comment by yohanboniface** [comment]
> What exactly needs to be done here?

I think the idea was, instead of only one `reference.html` file in the root, to have something like:

    0.7/reference.html
    1.0/reference.html

Plus I think we need to change the links on the site and have a way to another version of the doc while browsing one.

**Comment by IvanSanchez** [comment]
Closed via #4085
