### ISSUE TITLE
marker.setIcon() shows leaflet default marker icon in iOS Chrome

### ISSUE THREAD

**Issue by crazydeanofino** [Leaflet/Leaflet#3628]
For some reason in iOS Chrome marker.setIcon() changes the icon but still shows a leaflet default marker on top of the changed icon.

You can barely see the outline of the new icon (also blue) behind the default icon

![img_0015](https://cloud.githubusercontent.com/assets/4533595/8712171/e2895088-2b0d-11e5-8816-475af65655fd.PNG)

**Comment by mourner** [comment]
What's the Leaflet version? Is it reproducible on other browsers / devices? Can you make a JSFiddle test case that demonstrates this?

**Comment by snkashis** [comment]
I'm not seeing this behavior while running off of master(5a294998347349cc2b73c4a750020d1d3b885539) today. iPhone 6, iOS 8.4. I used the green leaf icons from http://leafletjs.com/examples/custom-icons.html, they changed over fine, no blue markers below.
