### ISSUE TITLE
.on('click', function(e) { }); not working after dragging the map

### ISSUE THREAD

**Issue by OdzReloaded** [Leaflet/Leaflet#3629]
Hi All,

I use leaflet 0.7.3 and created a draggable circle (not circleMarker because it has be a circle). If I drag the circle first I have no issues but when I drag the map and then try to drag the circle again it sticks to the mouse pointer and doesn't fire the on click event.

You can test it here:
http://jsfiddle.net/2zoth1y5/2/

The issue is similar to this one below but I couldn't fix it or find a workaround.
https://github.com/Leaflet/Leaflet/issues/2619

Thank you.

Kind regards,
Imre

**Comment by mourner** [comment]
Not sure what's going on here, but if you remove the mousemove listener on map mouseup, it all works fine. If it's not reproducible on 1.0.0-beta.1, I think it's safe to close this.

**Comment by tylercubell** [comment]
I'm also experiencing this issue on 1.0.0-rc3. See: https://jsfiddle.net/1d30dbcn/

**Comment by tomick** [comment]
@mourner Yes, this problem stil exists.
