### ISSUE TITLE
preclick fires on dragend

### ISSUE THREAD

**Issue by ktoto** [Leaflet/Leaflet#3632]
`debug/map/markers.html`
- click on marker (got popup)
- drag map
- popup closed when drag ended (wrong)

Before new event model popup is still opened after drag.

It's happed because `preclick` fired on drag end. `preclick` fired because we have `click` event from browser.
`_fireDOMEvent` checked current state in https://github.com/Leaflet/Leaflet/blob/cdb9ce0beb70705fb31b79fdc9376f72c42dc596/src/map/Map.js#L683

May be same check must be in `_handleDOMEvent` or move preclick firing to `_fireDOMEvent`?

**Comment by yohanboniface** [comment]
Confirmed. I'll have a look if nobody else is on it.
