### ISSUE TITLE
Box in BoxZoom not shown

### ISSUE THREAD

**Issue by ktoto** [Leaflet/Leaflet#3633]
`debug/map/markers.html`
Try box zooming (shift + click)
No box visible. :disappointed: 

It's seems forget up zIndex for zoom-box here https://github.com/Leaflet/Leaflet/blob/master/dist/leaflet.css#L66

There are also old zIndex for controls (https://github.com/Leaflet/Leaflet/blob/master/dist/leaflet.css#L99), may be it's affects something else...

**Comment by mourner** [comment]
Yep, forgot to update this one. Fixed, thanks!
