### ISSUE TITLE
dist folder only has css and image files. JavaScript files are missing

### ISSUE THREAD

**Issue by ssylvia** [Leaflet/Leaflet#3635]

**Comment by yohanboniface** [comment]
They are no more tracked in git, see #1354

**Comment by ssylvia** [comment]
@yohanboniface what are the ideal JavaScript files to use when downloading leaflet via bower?

**Comment by yohanboniface** [comment]
Humm, may be a missing step in the deploy process. According to https://github.com/Leaflet/Leaflet/issues/1903
I use my joker, I don't use bower in any way so I'm blind.
@mourner, any hint?

**Comment by IvanSanchez** [comment]
@ssylvia When you do `bower install leaflet`, you'll end up with a copy of the whole repo. Use `dist/leaflet.css`, `dist/images/*` and `dist/leaflet-src.js` (not `dist/leaflet.js`, as Bower's guidelines suggest that you shouldn't use minified versions of files)

**Comment by nikolauskrismer** [comment]
I don't get it.
@IvanSanchez: You can not use dist/leaflet-src.js -> it simply isn't there

One would have to use jake to build it first.
The problem for me now is how to automate this process in bower. What am I missing here?
It would really help if someone just could post a bower.json file that includes the latest version of leaflet (maybe v1.0.0-beta.1) in a sample project

**Comment by mourner** [comment]
The problem with bower was specifically that 1.0.0-beta.1 didn't include dist files in bower distribution for some reason. I'll try to figure out why (0.7.3 was fine) and fix it for the next beta.

**Comment by nikolauskrismer** [comment]
Ok... so at least I now understand how things should work.
Thanks :+1:

**Comment by psicomante** [comment]
It's simply gitignored :dancer: 

dist/*.js

**Comment by nikolauskrismer** [comment]
Will this be fixed for beta2?
Isn't the entry in the gitignore a trigger for a REOPEN on this?

**Comment by psicomante** [comment]
It was deleted because of issues with merging #1354.

**Comment by nikolauskrismer** [comment]
Yes... I know. So what is the solution for using leaflet with bower then (as mourner said the file was just not created for beta1, so I thought it might be there for beta2)

**Comment by psicomante** [comment]
I forked and compiled. Then i used my fork as source in the bower.json 

```
    "leaflet": "https://github.com/psicomante/Leaflet.git#master",
```

**Comment by nikolauskrismer** [comment]
@mourner: What psicomante did is a workaround (though a nice one), but maybe there is a better solution for this problem (so there is no need to fork leaflet when trying to use bower).

I really think that the fix from #1354 does not mean that there can be no dist/leaflet.js. It just means that there can't be this file in master, but it can be there for released versions (tags....)

**Comment by psicomante** [comment]
@nikolauskrismer I agree, it could be a "compiled" repo, with version tags.

**Comment by mourner** [comment]
> Will this be fixed for beta2?

Yes. 

> Isn't the entry in the gitignore a trigger for a REOPEN on this?

No. The new process for publishing a new version is making a new branch with a forced build files commit, tagging the version, pushing it as a release and then deleting the branch, so that the master still doesn't have to contain the built files.

**Comment by nikolauskrismer** [comment]
Great. Thanks again :+1: 
A new publishing process lets me hope for more regular builds (maybe every month or every 60 days or something like this?) :smile:

**Comment by 47ronin** [comment]
So i'm trying to understand the actual workaround here… sounds like all of us on deadline who are building on projects whose devs use 1.0.0-beta.1 are to use @psicomante's fork `https://github.com/psicomante/Leaflet.git#master` as a dependency for now until an official b2 build is released? I just need to make sure our project managers understand so they don't blame bower (and me for introducing this workflow) and go back to building stuff oldschool. I'm totally okay with building with a fork dependency as long as I can switch it later. Thanks

**Comment by psicomante** [comment]
@47ronin i suggest to use your own fork; mine is (and won't be) up to date. Btw the trick works :)
