### ISSUE TITLE
After BoxZoom can't click on marker

### ISSUE THREAD

**Issue by ktoto** [Leaflet/Leaflet#3636]
`debug/map/markers.html`
click on marker - got popup
close popup
use boxzoom for zooming
click on marker - no popup :disappointed:

**Comment by yohanboniface** [comment]
Confirmed. I'm looking at it.

**Comment by mourner** [comment]
Is this different to #3026?

**Comment by yohanboniface** [comment]
No it's not! :)
Closing in favor of #3026 then.
