### ISSUE TITLE
Right click on the map doesn't open context menu in 1.0 beta 1

### ISSUE THREAD

**Issue by Eschon** [Leaflet/Leaflet#3638]
[Here's](http://jsfiddle.net/Eschon/ag7rjx1t/) a small fiddle to reproduce the error.
Right clicking outside the map opens the context menu as expected. Right clicking on the map does nothing. 
Is this intended behaviour?
I usually open the web inspector through the context menu so this can be really annoying when debugging maps that fill the whole window.

**Comment by yohanboniface** [comment]
I think in 0.7.3 we only called `preventDefault` when the target had an eventlistener.
I'll discuss with @mourner and see if we can reimplement this.

**Comment by mourner** [comment]
Yeah, I think this should be reimplemented — a regression.

пятница, 17 июля 2015 г. пользователь Yohan Boniface написал:

> I think in 0.7.3 we only called preventDefault when the target had an
> eventlistener.
> I'll discuss with @mourner <https://github.com/mourner> and see if we can
> reimplement this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Leaflet/Leaflet/issues/3638#issuecomment-122303549>.
>


-- 
Vladimir Agafonkin
http://agafonkin.com/en
+380 (93) 745 44 61
