### ISSUE TITLE
Can you call GeoJSON.addData and not render the changes?

### ISSUE THREAD

**Issue by wpf500** [Leaflet/Leaflet#3640]
I'm trying to reduce the amount of blocking JS that occurs as I load the data for my map. I've moved JSON parsing and TopoJSON to GeoJSON conversion into a Web Worker, and the final thing I want to do gradually add the features to my map. However, each time I call `GeoJSON.addData` it redraws the map.

Is there a nice way to suspend redrawing? This is the hack I'm using (don't laugh :smiley:) https://github.com/wpf500/Leaflet/commit/e9acf302adbe109ed9d28173145f7da38e466351

**Comment by yohanboniface** [comment]
https://github.com/tmcw/leaflet-geojson-stream may help.

**Comment by mourner** [comment]
Yeah, I'm not sure we'd want to support a super-rare case like this in the core. You can do it with monkey patching though — e.g. instead of adding a line of code in the source, just override a method, calling the original one inside with `.apply(this, arguments)`.
