### ISSUE TITLE
Multiple geoJSON data sets

### ISSUE THREAD

**Issue by savannahostrowski** [Leaflet/Leaflet#3641]
Hi!

I want to overlay two geoJSON data sets, and then clip them independently.  It seems like the API only supports having one geoJSON data set, since a single SVG is used for all the geoJSON.

Is there some way I can work around this limitation?

Thanks,
Savannah

**Comment by IvanSanchez** [comment]
Using 1.0-beta1, instantiate a new SVG renderer with `var foo=L.svg()`, and pass that as the `renderer` option to your layer. Remember to check the 1.0-beta1 documentation at https://mourner.github.io/Leaflet/reference.html

Also, please refrain from using github issues as a channel for user support. It's supposed to be for bug reports and code improvements only.

**Comment by sylvaindurand** [comment]
Actually, your answer is really helpful for what I need to do. As L.svg and L.canvas parts of the docs aren't already written, it'll help me to test 1.0-beta1 :)
