### ISSUE TITLE
Document L.Renderer, L.Canvas, L.SVG

### ISSUE THREAD

**Issue by patrickarlt** [Leaflet/Leaflet#3645]
This would probably be helpful for plugin authors. `L.Renderer` should go under Base Classes. `L.Canvas` and `L.SVG` should go under a new Vector Renderers category or under Misc.

**Comment by IvanSanchez** [comment]
Can be superseded by #3916, specifically https://github.com/Leaflet/Leaflet/commit/89dd0a94de2e2e58df8c9d96e3c1c68200623bb2

**Comment by IvanSanchez** [comment]
Closed via #4203 / #3916
