### ISSUE TITLE
Problem with polyline and Joomla

### ISSUE THREAD

**Issue by key4625** [Leaflet/Leaflet#3649]
Hi everybody!

I've a problem.. when I copy the javascript code to draw polyline in a joomla page it doesn't appear... No error message appear, the path is made but nothing showed on the map... 

I'm thinking that there are some incompatibility between joomla and leaflet, anyone has tested this? 

I've tested different example code for try..
this is the last that I've tested:
 <link 
        rel="stylesheet" 
        href="http://cdn.leafletjs.com/leaflet-0.7/leaflet.css"
    />
    <div id="map" style="width: 600px; height: 400px"></div>

    <script
        src="http://cdn.leafletjs.com/leaflet-0.7/leaflet.js">
    </script>

    <script>
        var map = L.map('map').setView([-41.2858, 174.78682], 14);
        mapLink = 
            '<a href="http://openstreetmap.org">OpenStreetMap</a>';
        L.tileLayer(
            'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '&copy; ' + mapLink + ' Contributors',
            maxZoom: 18,
            }).addTo(map);
        
        var polyline = L.polyline([
            [-41.286, 174.796],
            [-41.281, 174.786],
            [-41.279, 174.776],
            [-41.290, 174.775],
            [-41.292, 174.788]
            ],
            {
                color: 'red',
                weight: 10,
                opacity: .7,
                dashArray: '20,15',
                lineJoin: 'round'
            }
            ).addTo(map);
        
    </script>

Someone helpme?

**Comment by key4625** [comment]
P.S. I have a yoomaster theme with warp framework instead.  (Yootheme)

**Comment by mourner** [comment]
Can you reproduce the problem as a minimal JSFiddle test case? If not, I think it's a problem somewhere in your setup. For help with things like this, I'd suggest asking on the Leaflet forum instead.

**Comment by key4625** [comment]
In JSFiddle is working... I think that the problem is betwenn leaflet and Joomla..

**Comment by mourner** [comment]
Oh, I think I've seen something familiar before.... Try adding this CSS:

```css
.leaflet-container svg { max-width: none !important; }
```

**Comment by key4625** [comment]
I love you!

**Comment by key4625** [comment]
I'm trying to visualize like 100 points in the polyline but this is freezing the maps... They are to much?

**Comment by mourner** [comment]
@key4625 no, Leaflet handles thousands of points just well... Again, try reproducing the problem with a JSFiddle test case and I'll look into it.

**Comment by key4625** [comment]
https://jsfiddle.net/xc8xcn32/1/

**Comment by mourner** [comment]
Oh, you've hit a known double-set-view bug here which causes freezing. If you remove the initial `setView` and leave just the `fitBounds`, it works perfectly: http://jsfiddle.net/xc8xcn32/2/

**Comment by key4625** [comment]
That's amore! :) Lot of thanks...
