### ISSUE TITLE
Opacity flickr when zooming WMS Layers

### ISSUE THREAD

**Issue by cosme-benito** [Leaflet/Leaflet#3652]
Hello, I have noticed a small flickr issue on layers which have an opacity lower than 1. 

If a layer has an opacity of 0.5 and you zoom in, it seems like the tiles are first loaded with opacity=1 and then are updated to opacity=0.5. This causes a weird flickr. This issue does not occur in leaflet 0.7.

Fiddle with leaflet 1.0-dev (zoom in and notice the flickr when the tiles are refreshing): http://jsfiddle.net/qf9huvk0/1/
Fiddle with leaflet 0.7.3 (no issues): http://jsfiddle.net/p6k4ejuq/3/

Is there any way I can solve this issue? Many thanks!

**Comment by mourner** [comment]
Maybe some race condition after refactoring fade animations cc @jfirebaugh

**Comment by w8r** [comment]
That's trickier than that. Race condition apparently, the flickering is caused by overlapping tiles during the zoom transition.

**Comment by mourner** [comment]
What is surprising to me is that tiles overlapped during zoom transition in 0.7.3 as well, so I don't know why it's not reproducible on the stable version.

**Comment by w8r** [comment]
because they don't have individual opacity settings, so what user sees is a blend of the blurred and scaled and the original tile at `opacity: 1` and container has `opacity: 0.5`

here we got 2 tiles with `opacity: 0.5` on top of each other

**Comment by mourner** [comment]
Oh, good catch! Hopefully we can find a fix to account for that.

**Comment by w8r** [comment]
So how many attempts were made before the decision was made to set the opacity on tile elements individually? Is it worth trying to get IE `filter` inheritance working? Cause it was working for 0.7.3, and the solution seems like an overkill to satisfy the old and broken browser.

**Comment by w8r** [comment]
@mourner what's your idea? cause I'm willing to spend some time on that, if you don't mind

**Comment by mourner** [comment]
Opacity is now set on tile element individually because tile fade animation is now programmatic (requestAnimationFrame-based as opposed to CSS transitions) — it was not possible to implement the new multi-zoom tile loading logic reliably without that change.

Global tile layer opacity being accounted for in individual tile calculations was an afterthought — we probably decided it would be easier on the performance. But if it introduces side effects like this, we could reintroduce opacity on the container. Not sure — feel free to poke with this and see what's the best compromise here.

**Comment by w8r** [comment]
Btw there are also problems with `z-index` in IE9 in the above example
![ie9](https://cloud.githubusercontent.com/assets/26884/8854674/6c428354-3161-11e5-9119-1db2d238c5f0.png)

**Comment by w8r** [comment]
@mourner, here's my solution to the opacity problem: http://jsfiddle.net/w8r/ukt65wz4/

* Opacity is applied to the layer container
* Individual tile fading is done from 1 to 0 values

I'm ready to create a pull request, but the thing with `z-index` bothers me

**Comment by w8r** [comment]
z-index issue is a separate one and is reproducible with or without the above fix.

**Comment by cosme-benito** [comment]
This seems to solve the problem. Thank you very much for your work @w8r
