### ISSUE TITLE
Display polyline path points without stroke.

### ISSUE THREAD

**Issue by gertcuykens** [Leaflet/Leaflet#3654]
http://leafletjs.com/reference.html#path-options

When I do `stroke: false` nothing is shown, please consider to show the path points only, this wil be useful when a path is incomplete and prevent big gaps between points being connected incase of missing gps data.

**Comment by mourner** [comment]
I don't think this is possible technically with SVG. Besides I think the case you described should be implemented using preprocessing of data, not by visual means, so I don't plan on implementing this.

**Comment by gertcuykens** [comment]
Ok thanks
