### ISSUE TITLE
Using leaflet npm from the browser

### ISSUE THREAD

**Issue by nyurik** [Leaflet/Leaflet#3656]
I'm implementing [kartotherian tile server](https://github.com/nyurik/kartotherian), and it uses [express npm](https://www.npmjs.com/package/express) for serving all content.  I need to add leaflet's /dist dir to be downloadable by the clients, but for that I need to know where it actually is.  One hacky way is this:
```
var pathlib = require('path');
var leafletpath = pathlib.dirname( require.resolve('leaflet'));
```
But if you move the main file to another dir, it would break.  Other libs use [this method](https://github.com/wikimedia/swagger-ui/blob/master/index.js#L6) to publish the location of the dist subdir.  Could you add it please?

Thanks!

**Comment by mourner** [comment]
I think the hacky solution is good enough. Don't want to add an additional file to the root that would have a very rare use case that has an easy workaround.
