### ISSUE TITLE
Vector geometry problem in IE8

### ISSUE THREAD

**Issue by Trufi** [Leaflet/Leaflet#3660]
If create geometry and add to map:
```javascript
var coords = [[54.98, 82.87], [54.975, 82.91]];
var mapp = L.map('map', {
    center: [54.98, 82.89],
    zoom: 14
});
L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png').addTo(mapp);
var geometry = L.polyline(coords);
geometry.addTo(mapp);
```
We see the following in IE8:
![screenshot from 2015-07-23 13 52 30](https://cloud.githubusercontent.com/assets/3996552/8845672/83468e78-313a-11e5-91e2-1a1aa6abcb52.png)

But after ```geometry.removeFrom(mapp).addTo(mapp)``` line loses style and looks like:
![screenshot from 2015-07-23 13 53 11](https://cloud.githubusercontent.com/assets/3996552/8845708/c3cc9866-313a-11e5-81e0-41ca7bf551b8.png)

**Comment by mourner** [comment]
Yeah, looks like the same issue as reported in #2809. Fixing for beta2.
