### ISSUE TITLE
Mouseout event sometimes lost when marker icon changed on mouseover

### ISSUE THREAD

**Issue by ggerber** [Leaflet/Leaflet#3664]
Good day,
I have 2 events on a marker: A mouseover that changes the marker icon and a mouseout event that reverts to the original icon.

However when you mouseover and mouseout leaflet inconsistently fires the events.
Please see my fiddle here: http://jsfiddle.net/1o4swvs6/
(mouseover and mouseout a number of times from various directions)
How can I get the events to fire consistently?
Best regards,
George

**Comment by mourner** [comment]
Can you try the same on the Leaflet 1.0 beta? Does it have the same issue?

**Comment by ggerber** [comment]
Hi,
I am not sure which version of leaflet jsfiddle is using, but I can confirm that leaflet 1.0 beta on my laptop also has this issue.
Any advice will be greatly appreciated.
George

**Comment by ggerber** [comment]
Hi,
Any advice will be greatly appreciated.
Kind regards

**Comment by yohanboniface** [comment]
Not sure it's a Leaflet issue, given that your are adding/removing from DOM the elements the events are binded on. You should try just changing the `src` of the image instead of replacing the element itself.

**Comment by yohanboniface** [comment]
See http://jsfiddle.net/1o4swvs6/1/ as an example.

**Comment by ggerber** [comment]
Thank you!

**Comment by ggerber** [comment]
Hi,
How would you go about with using svg instead of jpg's?
I see yohanboniface's solution works nicely with jpg's, however my jsfiddle below does not respond when replacing the img jpg with an svg string.
http://jsfiddle.net/w85u1L8u/
Any advice would be greatly appreciated,

**Comment by yohanboniface** [comment]
Well, you need to keep the element the events are binded on AND possibility have an hardcoded size for this element, then you can replace anything you want inside this element, so replacing the svg should work just like replacing the src attribute.

**Comment by ggerber** [comment]
Hi,
Is there any chance that someone can give an example? It will take an awfully long time for me to figure out which of the many properties inside L.divIcon needs to be changed in a specific manner to get mouseover and mouseout to work with a svg variable. Google also does not turn up many results for this.
Any advice will be greatly appeciated.
