### ISSUE TITLE
Canvas stroke alignment

### ISSUE THREAD

**Issue by jmlopez-rod** [Leaflet/Leaflet#3665]
I have been searching for a way to specify how the stroke should be drawn when using a canvas but there just does't seem to be a way to specify it. In case this is not clear consider the following diagram: 

![strokeAlignment](http://blog.rockymountaintraining.com/wp-content/uploads/2011/11/Adobe-Illustrator-CS5.1_ss_005.jpg)

The reason I need this is because I am drawing several polygons which overlap at the edges and some times I would like to set a wide stroke in a few of the them. But it just so happens that part of some polygons edges get covered by another one. In this case I prefer to contain the stroke to within the borders of the polygons.

This post explains how to set the stroke to inside: http://lists.w3.org/Archives/Public/public-whatwg-archive/2010Jul/0265.html. I'm not sure if you guys would like to give an option to polygons to be drawn
with the stroke within the limits of the polygon. If so we can make a quick change to `_fillStroke` for `L.Canvas`. I'm currently overwriting the definition with this:

```
L.Canvas.include({
  _fillStroke: function (ctx, layer) {
    var clear = this._clear,
      options = layer.options;

    ctx.globalCompositeOperation = clear ? 'destination-out' : 'source-over';

    if (options.fill) {
      ctx.globalAlpha = clear ? 1 : options.fillOpacity;
      ctx.fillStyle = options.fillColor || options.color;
      ctx.fill(options.fillRule || 'evenodd');
    }

    if (options.stroke && options.weight !== 0) {
      ctx.globalAlpha = clear ? 1 : options.opacity;

      // if clearing shape, do it with the previously drawn line width
      layer._prevWeight = ctx.lineWidth = clear ? layer._prevWeight + 1 : options.weight;
      ctx.strokeStyle = options.color;
      ctx.lineCap = options.lineCap;
      ctx.lineJoin = options.lineJoin;
      if (options.strokeAlignment == 'inside') {
        ctx.save();
        ctx.clip();
        ctx.lineWidth *= 2;
        ctx.stroke();
        ctx.restore();
      } else {
        ctx.stroke();
      }
    }
  }
});
```

The important bit of code is

```
if (options.strokeAlignment == 'inside') {
  ctx.save();
  ctx.clip();
  ctx.lineWidth *= 2;
  ctx.stroke();
  ctx.restore();
} else {
  ctx.stroke();
}
```

In this way we can at least specify if we want the stroke to be done inside if we specify in the option or we do the default thing which is a centered alignment. I tried my best to look at the docs but there doesn't seem to be a way of modifying the stroke so that's why I presented my current solution. Could something like this be considered to be added?

**Comment by patrickarlt** [comment]
:+1: on this. I think it would be really cool and it would make doing things like tint bands easy. It seems simple enough to get support for this into `L.Canvas`. We would also need to support this in `L.SVG` to which looks pretty easy https://svgwg.org/specs/strokes/#SpecifyingStrokeAlignment but I'm curious about browser support for `stroke-alignment`.

I think the `strokeAlignment` option would probably best be suited for `L.Path` since that is the base class for all vectors and we let browsers figure out how to draw it for something that isn't a polygon.

**Comment by jmlopez-rod** [comment]
Sweet. Looking forward for an update on this for SVG as well.

**Comment by mourner** [comment]
I'm OK with this if it's just a couple lines of code and doesn't lead to complications. Is there a similar hack for outside stroke?

**Comment by mourner** [comment]
Or alternatively, we could refactor things a bit so that you could hook into drawing easier (not having to override a big method like above).

**Comment by patrickarlt** [comment]
Here is a JS bin with all 3 styles centered, inside, outside with proper opacity and nothing that looks like a horrible hack http://jsbin.com/nanaguleye/edit?html,js,output.

The relevant hack for outer stroke is 

```js
// assuming ctx is the path you are styling...
ctx.save();
ctx.lineWidth = 16; // twice the desired line width
ctx.globalAlpha = 0.75;
ctx.stroke(); // draw stroke
ctx.globalAlpha = 1;
ctx.fill(); // fill with a 100% opacity to "knock out" the stroke width we don't want
ctx.globalCompositeOperation = "destination-out"; // setup to draw our fill path at the actual opacity
ctx.globalAlpha = 0.5;
ctx.fill(); 
ctx.restore();
```

The only tricky part is that with the outside stroke you have to draw the stroke BEFORE you draw the fill. Since SVG support is just adding `path.setAttribute('stroke-alignment', options.strokeAlignment);` I think we can get this for a pretty low code cost. I'll find some time to do it an open a PR so we can discuss.

**Comment by mourner** [comment]
Nice! Any idea what the SVG support is? Apparently latest Chrome doesn't support it yet...
The canvas outer stroke hack looks like it wouldn't perform very well, although it may be OK for the use cases.

**Comment by patrickarlt** [comment]
According to [this stackoverflow answer](http://stackoverflow.com/a/28787545/449686) there is no browser support. I originally assumed that `stroke-alignment` was SVG 1.1 but apparently it is part of SVG 2.0 :cry:.

The stackoverflow post DOES mention some horrible workarounds like:

> you can achieve the same visual result as "inside" by doubling your stroke width and then using a clipping path to clip the object to itself, and

> you can achieve the same visual result as 'outside' by doubling the stroke width and then overlaying a no-stroke copy of the object on top of itself.

@mourner I wonder if we could refactor the renderer code a little so taht @jmlopez-rod sample could be written like this:

```js
L.Canvas.include({
  drawStroke: function(){
    // define how you want to draw strokes
  },
  drawFill: function(){
    // define how you want to draw fills
  }
})
```

that are called at the appropriate time (with appropriate options) whenever we are not clearing the layer from the canvas.

**Comment by IvanSanchez** [comment]
This is covered by the [Leaflet Polyline Offset plugin](https://github.com/bbecquet/Leaflet.PolylineOffset) already.
