### ISSUE TITLE
Can't disable map drag (Windows IE11 only)

### ISSUE THREAD

**Issue by skalb** [Leaflet/Leaflet#3666]
I'm trying to disable the map drag when a user clicks a layer. It works fine on Mac/Chrome, but on Windows/IE the map drag is not disabled.

It seems like the mousedown event handler on the map object is never actually removed.

See: http://jsfiddle.net/skalb/otwgyutn/3/

Any ideas?

Edit: using leaflet master

**Comment by mourner** [comment]
also cc @danzel

**Comment by IvanSanchez** [comment]
Variable scope problem. `this` is not set correctly when running `map.dragging.disable()` asynchronously.

**Comment by IvanSanchez** [comment]
Hm. Apparently disabling the map dragging works, but the order IE11 fires the events means it's disabled *after* starting the drag (in that fiddle's use case).

**Comment by yohanboniface** [comment]
>  but the order IE11 fires the events

I'm curious about the details

**Comment by skalb** [comment]
Upon further testing, I'm seeing this issue on both iOS Chrome and Safari as well (using iPhone 6 and simulator).

Same fiddle: https://jsfiddle.net/skalb/otwgyutn/5/embedded/result/

**Comment by skalb** [comment]
This looks like a different issue so I opened #3825 instead.

**Comment by IvanSanchez** [comment]
Apparently this is reproducible in beta2 (as reported in #4157) - anyone up to `git bisect` the code?

**Comment by amir-infsoft** [comment]
I did some further testing and found that is works correctly in one (sub)version of 1.0beta2 and not correct in another.

There are also fiddles where you can check.

In current version from [www.leaflet.js] (http://leafletjs.com/2015/10/14/leaflet-1.0-beta2-released.html) it does not work:
Leaflet: Leaflet 1.0.0-beta.2 (954e83d)
http://cdn.leafletjs.com/leaflet/v1.0.0-beta.2/leaflet.js
http://jsfiddle.net/xu72htcy/7/embedded/result/

In version I found in one example fiddle it works correctly in IE:
Leaflet: Leaflet 1.0.0-beta.2 (08d655f)
https://s3.amazonaws.com/fieldwire-dev/leaflet-master/leaflet-src.js
http://jsfiddle.net/xu72htcy/4/embedded/result/

**Comment by IvanSanchez** [comment]
@amir-infsoft Does it work in the current `master` branch? (See https://playground-leaflet.rhcloud.com → "add library" → "Leaflet development version")

**Comment by amir-infsoft** [comment]
Unfortunately no.

Url: https://playground-leaflet.rhcloud.com/jix/1/edit?html,output

**Comment by IvanSanchez** [comment]
`git bisect` says that the regression is at c6d858775341667dceefd0f7b9f0718cf7d52c0e AKA «Don't use maxTouchPoints detection in IE11+ (or edge) either, matching our msPointer detection.»

Damn. :-(

**Comment by amir-infsoft** [comment]
I see. When I add '&& navigator.maxTouchPoints' part in current dev version then it works.

Can you add this in new version(s)?
I presume this was removed because it was causing some other issue/incorrect behavior?

**Comment by IvanSanchez** [comment]
Paging @danzel @yohanboniface - I have no idea how to fix this without breaking #3804/#3839.

> I presume this was removed because it was causing some other issue/incorrect behavior?

@amir-infsoft Exactly. It's not the first time that fixing a very specific bug creates a tiny very specific bug somewhere else.

**Comment by danzel** [comment]
Adding ```&& maxTouchPoints``` isn't a fix, that just means it'll only break on touch devices.
That change was sort of a follow up to ```afa0d1d87b4c522ca3cbeef785c829b886355982``` too.

Gonna investigate this for a bit. What if we cancelled any existing drags when the draggable gets disabled?

**Comment by danzel** [comment]
Ok, so on mouse down if IE feels like it has a touch device, it will generate a ```pointerdown``` event first, which leaflet happily handles starting the drag.
Then IE makes a ```mousedown``` event, which you catch and disable the drag.


We could change ```Draggable.disable()``` to cancel any drags in progress which would make this work... I think that is probably better behaviour too?

**Comment by amir-infsoft** [comment]
@danzel Sounds good.
