### ISSUE TITLE
Is touch supported on leaflet?

### ISSUE THREAD

**Issue by deepakshakya** [Leaflet/Leaflet#3672]
Hi

I have been searching for proper documentation on touch support on leaflet but haven't found on yet.
I am wondering if leaflet properly support touch events on html5 webpage opened on mobile?

Please let me know about this. I am building an important application and it lot depends on this support.

It would be very helpful if you could provide me link/documentation of leaflet which shows touch support on leaflet maps.

Thanks,
Deepak.

**Comment by mourner** [comment]
See the features list on the website. http://leafletjs.com/ And try it for yourself on a mobile.

**Comment by deepakshakya** [comment]
Hi,

Let me ask you specific question.

function onEachFeature(feature, layer) { // does this feature have a
property named popupContent? if (feature.properties &&
feature.properties.popupContent) {
layer.bindPopup(feature.properties.popupContent); } }

In addition to above example, if I want something like:-
function onEachFeature(feature, layer) { // does this feature have a
property named popupContent? if (feature.properties &&
feature.properties.popupContent) {
layer.bindPopup(feature.properties.popupContent);
layer.on('touchstart', function(e) {
alert(feature.properties.Name);
});
} }

Is this touch event possible? It's not working for me, hence I am looking
for some help.

Thanks,
Deepak.

On Sat, Jul 25, 2015 at 1:57 AM, Vladimir Agafonkin <
notifications@github.com> wrote:

> Closed #3672 <https://github.com/Leaflet/Leaflet/issues/3672>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Leaflet/Leaflet/issues/3672#event-364897702>.
>



-- 
Thanks,
Deepak Shakya

**Comment by IvanSanchez** [comment]
Read the documentation. http://leafletjs.com/reference.html#path-click says (emphasis mine):

> Fired when the user clicks **(or taps)** the object.

And, please, do not use the github issue tracker for questions about how to use Leaflet. There's a user forum for that. The github issue tracker is meant for bugs and feature code *only*.
