### ISSUE TITLE
multi-tilelayers response wrong

### ISSUE THREAD

**Issue by ashareye** [Leaflet/Leaflet#3676]
i add two tilelayers into the map, one zooms 0~7,  another zooms 5~7. the first layer is ok, but the next layer zoom 4~7 when zooming in, and zoom 5~7 when zooming out. in other words, when i zoom in the map from 7 to 0,  at level 4 the second layer shows that should not show. but when i zoom out the map from 0 to 7, the second layer shows at level 5 and does not show at level 4. why ? is that a bug?

**Comment by mourner** [comment]
Can you set up a JSFiddle test case to demonstrate the issue?

**Comment by geospatialem** [comment]
I noticed the same issue this morning, here's a [JSFiddle](http://jsfiddle.net/hockeyduck30/11feynjf) that displays the issue.

As @ashareye mentioned, everything performs as-expected with the switch, but when you zoom back out, after the second tilelayer has loaded, both tilelayers are shown simultaneously for one zoom level.

**Comment by geospatialem** [comment]
Below is a screenshot of the functionality (shown in the JSFiddle). After the user zooms in and the second tilelayer loads and the user zooms out on the map, the second tilelayer tiles are still loaded on top of the first tilelayer.

![capture](https://cloud.githubusercontent.com/assets/5023024/9475545/f5088db6-4b2c-11e5-9012-45a3122c95ae.JPG)

**Comment by geospatialem** [comment]
This bug has been fixed with Leaflet v1.0 beta 1 when using the ```zIndex``` option. Here's a working [JSFiddle](http://jsfiddle.net/hockeyduck30/6fcb6rzk/).

**Comment by yohanboniface** [comment]
@geospatialem seems fixed in latest master even without using `zIndex` option, see: http://playground-leaflet.rhcloud.com/pat/edit?html,output

Do you confirm, or am I missing something? :)

**Comment by geospatialem** [comment]
@yohanboniface Works on my end, too. :+1: I re-tested using my Fiddle and it also works, although I remember having issues without the `z-index` while testing, but it could have been related to a slow internet connection at the time...

**Comment by yohanboniface** [comment]
OK, thanks for taking time to test again. :)

Closing then.
