### ISSUE TITLE
map.on('baselayerchange', {}) returns layer instead of event, unclear docs

### ISSUE THREAD

**Issue by robpvn** [Leaflet/Leaflet#3677]
From what I can see in the 1.0 beta docs, the `baselayerchange` event handler should receive a [LayerEvent](https://mourner.github.io/Leaflet/reference.html#layer-event) or [LayersControlEvent ](https://mourner.github.io/Leaflet/reference.html#layers-control-event) depending on whether you believe the [Map API doc](https://mourner.github.io/Leaflet/reference.html#map-events) or the [Control.Layers API doc](https://mourner.github.io/Leaflet/reference.html#control-layers). They both say that the event is triggered when you change the baselayer via the layer control, but say that different events will be fired. 

In any case, both types of events have a `layer` property, but it appears that instead of the event object, the actual layer being changed to is returned instead.

JSBin demonstrating: 
http://jsbin.com/wevezidofo/5/edit?js,console,output

If you use the layer control to switch layers, you will see from the console output that the event properties are undefined, but the object returned has all the properties of a TileLayer.

**Comment by yohanboniface** [comment]
I can have a quick look at this.
