### ISSUE TITLE
Link to leaflet 1.0-dev version is broken.

### ISSUE THREAD

**Issue by Eschon** [Leaflet/Leaflet#3679]
The link to the leaflet 1.0-dev version on the leaflet Website (http://leafletjs.com/download.html) only returns a XML with an error message.

**Comment by marc-dziedzic** [comment]
Noted this as well, posted issue to forums also.   https://groups.google.com/forum/#!topic/leaflet-js/cFVLwSD3sDg

**Comment by mourner** [comment]
Yeah. I'm trying to contact the owner of S3 (@JasonSanford) now. Meanwhile I suggest downloading it [on GitHub](https://github.com/Leaflet/Leaflet) and building yourself with `npm install; npm run prepublish`.

**Comment by JasonSanford** [comment]
This was my fault, but was fixed by @mourner with 2ca1b779a63a9d9c5e97f379665fe65c4aaca5e3. Sorry folks!
