### ISSUE TITLE
Tile loading/display breaks after zoom on mobile with updateWhenIdle is false

### ISSUE THREAD

**Issue by chrigi** [Leaflet/Leaflet#3683]
I use 'updateWhenIdle: false' to get a nicer flyTo animation. (There is issue #3515 tracking the progress to enable this behavior just for flyTo)

When I pinch-to-zoom (or rarely double-tap/flyTo) on a mobile device, it happens quite often that some tiles (often big chunks of the map) don't load at all and only display as grey blocks.

When I set 'updateWhenIdle: true', this does not happen anymore and all tiles load.

But one issue still remains even with this set to 'true': When I exceed my 'maxZoom' during a pinch-to-zoom, the screen turns grey (no tile loaded) until I zoom back out or move the map. I can then often exceed my maxZoom and it will just magnify my map without the issue but not every time.

This happens with 'detectRetina' enabled and disabled and even if my 'maxZoom' is lower than the tile sources max.
It appears like this bug is also discussed in issue #2652 but I can confirm that this also happens on Android. It might also be related to issue #3530.

It seems like it only happens when the 'maxZoom' level has not fully loaded yet.

**Comment by mourner** [comment]
That's surprising, I've never seen the effect before. Possibly a recent regression.

**Comment by yohanboniface** [comment]
So, you are talking about two issues:

1. tiles not loading from time to time when `updateWhenIdle` is `false`
2. map turning grey when pinch overzooming

I'm able to reproduce the 2., and I will try to investigate; though I didn't manage to reproduce the 1 (on Android Chrome). Are you able to narrow it to a step by step that help reproducing?

**Comment by chrigi** [comment]
Sadly we completely moved over to Google Maps and I don't have any code at hand but the behavior was very obvious. I simply moved around on the map, zooming, panning, etc. and from time to time it would just not load certain tiles. When I zoomed in and out they would appear but otherwise would stay grey. I said that setting ``updateWhenIdle`` to ``true`` would help but as far as I can remember it still happened but very infrequently. As far as I can remember the network requests did return correctly but I'm not 100% sure anymore.

**Comment by IvanSanchez** [comment]
With a bit of luck, #3815 might fix this.

**Comment by mourner** [comment]
@chrigi can you please try and reproduce this again with master?

**Comment by chrigi** [comment]
I'm sorry but I won't be able to test it in the near future.

**Comment by mourner** [comment]
Let's assume this was fixed until proven otherwise.
