### ISSUE TITLE
Dragging while zoom animation is active breaks dragging

### ISSUE THREAD

**Issue by helloworld65** [Leaflet/Leaflet#3685]
When the map is locked while the tiles are loading, the user experience becomes not as smooth as it could be. Some map tile providers load map tiles slower than others. I have seen map tile requests that take more than a second to load. That is one second where the map cannot be dragged and moved around. The map becomes clunky to use with speed and efficiency.

**Comment by IvanSanchez** [comment]
Note to self: create a test case where the map has only an image overlay and some markers (no tile layers). The map should be draggable from outside the image overlay.

**Comment by IvanSanchez** [comment]
Cannot reproduce, even when adding a delay to tile loading.

@helloworld65 Have you tried using 1.0-beta1?

**Comment by helloworld65** [comment]
@IvanSanchez The behaviour I am describing seems to happen when the you attempt to the drag the map using mouse down immediately after map zoom. Tested this on Chrome and Firefox with both 7.3 and 1.0-beta1. Not sure if this will help but I made a gif video: http://imgur.com/clLxXt3

**Comment by IvanSanchez** [comment]
@helloworld65 Yes, that helped! I suspect a weird interaction between the zoom proxy and the drag handler, but will need to hack the code and try a few things.

**Comment by jplante** [comment]
Has anybody else been able to verify this? I have pulled down the latest Leaflet-dev build from master, verified that its listing leaflet-1.0-beta2, and that the code changes listed for this are in the pull, and the touch screen laptop that I'm testing Windows 10 edge browser is no longer throwing the "unknown touch event" that I was getting before preventing the map from loading, the map does load now (it was breaking before), however, I am not able to use touch to drag the map.  So, from a touch stand-point, it appears to be a static map.

**Comment by IvanSanchez** [comment]
@jplante The code for Draggable in the `stable` branch is different, and it's not easy to backport this - the reason might be entirely different.

On my part, I don't feel this is critical to guarantee spending time on backporting a fix for `stable`.
