### ISSUE TITLE
leaflet 1.0.0-b1 noWrap not present anymore

### ISSUE THREAD

**Issue by vas85** [Leaflet/Leaflet#3691]
Hi.

Thanks for the great library.

I noticed in master noWrap functionality documented [here](http://leafletjs.com/reference.html#tilelayer-options) is not there anymore.

It was removed in commit 5e6f95dc9ce86fcd2f191f0abbe7a8ea0d4f888f and commented out in commit cdfaad994f277a2eb90bcf4499c86786a6aa707f.

Going forward is noWrap going to be deprecated in 1.x? Or will it come back?

Thanks!

Vas

**Comment by mourner** [comment]
No, probably missed out. Although not as critical since wrapping is now dictated by CRS by default, so e.g. earth CRS have longitude wrapping, but CRS.Simple doesn't.

**Comment by vas85** [comment]
Makes sense.

In my application I need earth CRS (because I have some tile data created via gdal2tiles tool that I cannot change right now). 

The hack I put in my code to remove wrapping is just this: 
delete L.CRS.Earth.wrapLng;

Happy to submit a pull request to add a param to control wrapping if you think its a good idea.

**Comment by rancas** [comment]
Hi, I am trying to create a CRS.Simple layer with no wrapping but with no luck. It worked with version 0.7.5 using the following code:
```
var map = L.map('map').setView([0, 0], 0,crs= 'L.CRS.Simple');
var background = new L.FeatureGroup();
map.addLayer(background);
var tiles = L.tileLayer(scope.diagram.tiles_site+scope.diagram.tile_dir+'{z}/{x}/{y}.png', {
          width: 2048,
          height: 2048,
          minZoom: 0,
          maxZoom: 4,
          continuousWorld: false,
          noWrap: false,
          tms: true,
 });
background.addLayer(tiles);
```
We generate our tiles and it is not a "real map": 
How should I have the same result if I cannot use noWrap attribute?
Thanks.
Luca.
