### ISSUE TITLE
Destruction of bound popup source element on closing.

### ISSUE THREAD

**Issue by JrFolk** [Leaflet/Leaflet#3698]
I am binding an element to it's associated marker popup via `marker.bindPopup(document.getElementById("popup_"+id))`.  Once the popup is closed, the element is destroyed. If I had assigned it to a variable, that variable is now `null` and I can no longer re-query the element with` document.getElementById`.  Is there a less destructive way to close the popups that would allow manipulation and querying after the popup has been closed?

*Note: the source element remains in it's original location upon passing it to `.bindPopup`, and returns to the DOM once the popup is re-activated.  To reproduce this you must first activate the popup and then close it.

**Comment by yohanboniface** [comment]
Can you set up a test case to demonstrate the issue (http://playground-leaflet.rhcloud.com/ for example) ?

**Comment by danzel** [comment]
Unless I've misunderstood you, this works fine.
http://playground-leaflet.rhcloud.com/cip/edit?html,output

Click the marker to do the popup with the content.
Then hit the button, and it can still use the original dom node.
I've saved the content to a variable (window.popupContent), which stays around even after putting it in the marker.

You cannot use document.getElementById to get it anymore as the content of the element are used for the popup.
ref http://leafletjs.com/reference.html#marker-bindpopup

**Comment by JrFolk** [comment]
There are nodes in the popup that i want to manipulate programmatically, like hiding and showing different data. I render the popups elsewhere but then hand them over to leaflets popup module when I initialize the map. Everything works fine up until the first time the popups are closed. They still appear, but I no longer can get a handle on them otherwise to read/write to those nodes.

**Comment by JrFolk** [comment]
Oh. Thank you!
