### ISSUE TITLE
layergroups with custom IDs

### ISSUE THREAD

**Issue by MuellerMatthew** [Leaflet/Leaflet#3699]
Hello, 
I have been thinking about an issue for several days now and I wanted to make a suggestion for a minor change to leaflet. I am attempting to create a simple plugin to enable a user to deeplink to a particular feature or marker on a map. For example, in http://leafletjs.com/examples/choropleth.html, if I wanted to create sharable url which automatically selected 'wisconsin' when the map loaded you would use http://url#layer=<layername>&<fieldname>=<sublayer/feature value> so you could use: http://leafletjs.com/examples/choropleth.html#layer=geojson&name=wisconsin as your url to automatically trigger a click/touch on the wisconsin feature within the geojson layer after the page loads.

Right now in order to find the correct layer/feature I have to loop through all the layers to find a match based on 1 or more feature values which is a very inefficient process, especially if there are a lot of layers.
 
From what I can tell right now the easiest method to select a layer from a feature collection/layer group is to use the layer id which is just a randomly generated value based on the order that the layers and features were loaded into the map. Thus I think the ideal way to make something like this work would be to be able to manually set the layer ids from a unique key already in the dataset as an alternative when loading a layer/layer group instead of always using a randomly generating value so that the layerID can be a set fixed value which can always be used.

Most maps that I am building have dynamic content, where the datasets being displayed changes regularly, so the data is not always going to be loaded into the map in the same order since the data changes every day, but each row already has a custom ID.  Thus I think it would be useful to make a small change to the LayerGroups to allow a field to be passed which would be used to define the ID instead of using `L.stamp(layer)`.

Any thought or suggestions on this proposed change to Leaflet?  I wanted to discuss the idea a bit before I attempt to make changes to Leaflet, and create a pull request.

**Comment by mourner** [comment]
Custom ids would unnecessarily complicate the API. I think what you're trying to achieve could be solved in an easier way:

```
var ids = {};
geojson.eachLayer(function (layer) {
  ids[layer.feature.name] = L.stamp(layer);
});

ids["wisconsin"] // contains an id you can use right away
```
