### ISSUE TITLE
Major disparity in L.Projection.SphericalMercator.project function (between 1.0b and 0.73)

### ISSUE THREAD

**Issue by vas85** [Leaflet/Leaflet#3700]
It seems as part of change 49af3fda5c7811d3a023f2737a364e2bf0d87c31 a bunch of refactoring was done to the L.Projection.SphericalMercator class. 

The project() and unproject() functions are returning different values before and after, causing weird issues in bounds checking and a few other things for me in master.

Have a look at this JSFiddle: http://jsfiddle.net/6Lbm9970/3/

Note: this is not the same as https://github.com/Leaflet/Leaflet/pull/2062. My before version has the fix in that PR.

Thanks!

**Comment by mourner** [comment]
cc @perliedman

**Comment by Ariki** [comment]
The Mercator projection formulae produce infinite ordinate at ±90°. For that reason it's always truncated at some latitude, and one shouldn't rely on values returned at higher latitudes. The old version had a limit at 85.0511287798° and truncated all that was beyond that. The new one has much larger limit but projected ordinates at high latitudes are accordingly high. I believe it's user's responsibility to check whether the data is inside the domain of a particular projection.

**Comment by vas85** [comment]
Thanks @Ariki that makes perfect sense. Seeing how the latitude projection is calculated using Math.tan makes that even more evident.

I do think that silent truncation / inaccuracies at higher latitudes could be surfaced better (maybe a warning, console.log, or some such)? I'll let someone else weigh in, but I think we can close this.

**Comment by mourner** [comment]
Yeah, I probably removed the truncation because I thought it should be handled by CRS, not projection itself.

**Comment by perliedman** [comment]
Keeping the truncation in the projection seems like the right thing: looking at the definition of EPSG:3857, it's valid in -85.06 < lat < 85.06 (http://epsg.io/3857).

I can try to fix this later tonight, if it sounds like a good idea and noone beats me to it.

**Comment by perliedman** [comment]
The other option is of course to refuse projecting such latitudes, but IMO that would be against the spirit of Leaflet - if you try to put a marker on the north pole, most users would prefer a marker at the top of the map, rather than an error that would be cryptic to most, although the latter is technically more correct handling.

**Comment by Ariki** [comment]
I think the old version with truncation at MAX_LATITUDE=arctan(sinh(π))=85.0511287798 was perfectly correct because it produced a square map consistent with popular tiling schemes. Some applications may need wider bounds but such cases are not what EPSG:3857 was intended for.

**Comment by Ariki** [comment]
Though such truncation can distort geometries that cross domain boundary.
