### ISSUE TITLE
Popup width

### ISSUE THREAD

**Issue by thib3113** [Leaflet/Leaflet#3702]
In some browser, the popup have a bad width, my example : http://jsfiddle.net/thib3113/7ojgtqfv/2/ ( with 0.7.3 )
the width is good for chrome or IE, but the width is not good for Firefox or Android browser ( i don't have check on the fiddle, but on my website, some user have this bug ) . When i check the popup maxWidth, the value is 300

Browser I use : 
1. On ubuntu 15.4 64bits:
* Chrome : 44.0.2403.125 unknown (64-bit)
* Firefox dev edition 41.0a2 (2015-07-27)
* Opera 30.0.1835.125
2. On Windows 8.6 :
* Internet explorer 11

Images :
Chrome :
![Chrome version](http://www.zupmage.eu/i/kz3TAtyPaw.png)
Firefox :
![Firefox version](http://www.zupmage.eu/i/580TM7jt1J.png)

**Comment by thib3113** [comment]
It's good with beta, but are beta ready for production website ?

**Comment by mourner** [comment]
Closing because we just released 1.0 and minor issues in 0.7.x are unlikely to be fixed.
