### ISSUE TITLE
Geolocation.clearWatch() throws an error

### ISSUE THREAD

**Issue by mfc-julius** [Leaflet/Leaflet#3707]
We have Opbeat set up on our project, which for now is not perfect for JavaScript, but still gives us some information about errors.

The new errors we were alarmed were caused by Geolocation.clearWatch() from f.Map.include.stopLocate method.

We have not much information tracked down, but the user agent was:
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.13 Safari/537.36

The TypeError value was:
Object [object Object] has no method 'clearWatch'

Do you have any idea why this suppose to happen? Is there any solution to this?

FYI, v0.7.3 is used.

**Comment by yohanboniface** [comment]
Are you able to test with latest master?

**Comment by mfc-julius** [comment]
Not really. I can't put beta release on the live server, where it occurred, also, I cannot reproduce the error myself.

This came from some user, and Opbeat logged the thrown exception.

I thought maybe you might know, if there's problem with clearWatch in some cases. From the code I see, then it checks if navigator.geolocation exists, and the calls the method. But in this case error indicated, that there was no method clearWatch.

**Comment by mourner** [comment]
The user agent looks like it might be the new Microsoft Edge browser which tries to mimic itself as all other browsers. :) No idea why there's no `clearWatch` method, but I'm sure this is not a Leaflet issue, but a browser one and not much can be done on our side. I'd suggest doing a `try/catch` block to catch errors like that.

**Comment by mfc-julius** [comment]
What about checking if the method exist before executing it? If, as in this in example, there might be cases where the method does not exist.

**Comment by mourner** [comment]
@mfc-julius just added a check for that. Thanks!

**Comment by mfc-julius** [comment]
FYI, this is happening with latest Chrome on Windows 10. Again, not sure why.
