### ISSUE TITLE
Zooming on desktop browsers with touchscreen is inconsistent

### ISSUE THREAD

**Issue by stvno** [Leaflet/Leaflet#3712]
I created a very basic leaflet site to test this: http://research.geodan.nl/sites/tests/zoombug.html 
using the CDN version of leaflet andthe viewport metatag set to user-scalable=no and all scale parameters to 1.0

When using Chrome and Firefox on Android 5.1 or Safari on iOS 8.4 you can zoom in on the map using pinch zoom, but not on the text, as expected

However on my Dell XPS 13 with touchscreen and windows 10 the various browsers behave differently:
**Chrome 44** using touchscreen:
- Pinchzoom on the map: zooms the map ✔
- Pinchzoom on the text: zooms the page ✗
- Two finger drag on the map: pan the map and once finished zoom in or out (??) ✗
- Two finger drag on the text: move the page ✔
- One finger drag on the map, initial direction horizontal: pan the map ✔
- One finger drag on the map, initial direction vertical: pan the map ✔

**Firefox 39** using touchscreen:
- Pinchzoom on the map: zooms the page ✗
- Pinchzoom on the text: zooms the page ✗
- Two finger drag on the map: zooms the map ✔
- Two finger drag on the text: move the page ✔
- One finger drag on the map, initial direction horizontal: pan the map ✔
- One finger drag on the map, initial direction vertical: zoom the map ?!? ✗

**Edge 20** using touchscreen:
- Pinchzoom on the map: zooms the page ✗
- Pinchzoom on the text: zooms the page ✗
- Two finger drag on the map: scroll the page  ✗
- Two finger drag on the text: scroll the page ✔
- One finger drag on the map, initial direction horizontal: move the page ✗
- One finger drag on the map, initial direction vertical  move the page ✗

Touchpad behaviour is again different but that could be a driver issue. Mouse (with scrollwheel) does behave as expected on all browsers.

**Comment by Eschon** [comment]
> Pinchzoom on the text: zooms the page ✗

Does this mean that pinchzooming doesn't zoom the page or that it does and this is wrong?

Either way as far as I know the viewport meta-tag is ignored in desktop browsers.
Also correct me if I'm wrong but the page-zooming has nothing todo with leaflet.

**Comment by stvno** [comment]
Sorry for the unclear terminology, but I meant that pinchzoom on the text zooms the page and it is wrong (since user-scalable  = no and maximum-scale = 1 anyway)

I'm aware that it is not (entirely) a leaflet bug, but since it produces inconsistent behaviour with leaflet I wanted to document it somewhere and this is as good a place as any.

The whole zoom on text bit is not that interesting for leaflet, but the zoom/drag on map bits are. It doesn't work in Microsoft Edge at all and Chrome and Firefox show some really weird behaviours.

**Comment by danzel** [comment]
Edge is broken in 0.7.3, A fix has just been merged in #3710 and #3674

Not sure why pinchzoom doesn't work on firefox, but a two finger drag does?
Is firefox generating a mousewheel event instead of sending us touch events?

**Comment by DanielX2** [comment]
In the latest Version of Microsoft Edge on Windows 10, pan, zoom and doubletab aren't working if touch input is used.
This isue ocours in 0.7.3 and 0.7.5.
I spend some time on trying to fix this error and found the solution.
In the latest Version Edge doesn't know "-ms-touch-action" but knows "touch-action".
So adding "touch-action: none" in leaflet.css fixes this error.

```css
.leaflet-container {
         overflow: hidden;
         touch-action:none;
         -ms-touch-action: none;
}
```

The funny thing is, IE 11 knows both but Edge just the one without verndor-prefix.

**Comment by danzel** [comment]
@DanielX2 That fix is in stable and master but hasn't made it in to a stable release yet.

**Comment by paul-peters** [comment]
I got Pinchzoom in IE11 and Edge working with css:
```css
#map {
  -ms-touch-action: none;
      touch-action: none;
}
```

source of that idea: http://blogs.msdn.com/b/ie/archive/2011/10/19/handling-multi-touch-and-mouse-input-in-all-browsers.aspx

**Comment by IvanSanchez** [comment]
There have been a bunch of changes to the two-finger gestures (and we can now automate stuff with prosthetic-hand). @stvno , would you be able to try all this again and maybe see if some prosthetic-hand automated webpages work as expected in your browsers?

**Comment by stvno** [comment]
@IvanSanchez I still have my laptop, so yes I'll be able to test them again. I just did and chrome and edge are properly working (albeit doing a double finger drag on a map still doesn't zoom, but thinking about it I realized that it would be a weird gesture anyway)
However I just did a fresh pull of master and Firefox 45.0.1 still has the same issues. If you have test urls for me, I'm happy to test them with my non prosthetic hand ;)

**Comment by HarelM** [comment]
I just encountered the same issue: Chrome is zooming as expected, Firefox is zooming the page (pitch zoom) Edge is working although I'm not sure who is still using Microsoft's browsers these days... :-).
Windows 10, Dell XPS 15.
I'm testing it on my site:
http://israelhiking.osm.org.il/
Using latest leaflet from bower - 0.7.7.
Can I help in someway? can you point me to a location I can look into and try and debug this?

**Comment by Herst** [comment]
There is also `-ms-content-zooming: none` which you can add to your `:root`.

**Comment by johnd0e** [comment]
This is pretty old issue.
Could anyone confirm that it is still relevant in modern browsers with recent leaflet?

**Comment by johnd0e** [comment]
Ok, as this issue was reported for 0.7.7, I suppose we can close it.
