### ISSUE TITLE
Leaflet Truck Factor

### ISSUE THREAD

**Issue by gavelino** [Leaflet/Leaflet#3713]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Leaflet** and obtained a value of **1**.

The developer responsible for this TF is:

Vladimir Agafonkin - author of 77% of the files 

To validate our results, we would like to ask **Leaflet** developers the following three brief questions:

(a) Do you agree that the listed developer is the main developer of **Leaflet**?

(b) Do you agree that **Leaflet** will be in trouble if the listed developer leave the project (e.g., if he wins in the lottery, to be less morbid)?

(c) Does **Leaflet** have some characteristics that would attenuate the loss of the listed developer (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by yohanboniface** [comment]
In the Leaflet world, we all go by bike, so there is not truck around, so we are quite optimist ;)

> (a) Do you agree that the listed developer is the main developer of Leaflet?

yes

> (b) Do you agree that Leaflet will be in trouble if the listed developer leave the project (e.g., if he 
> wins in the lottery, to be less morbid)?

 yes, but there are other people knowing quite well the code base; plus, the lib being so popular that a team would certainly raise up in case Vlad would win the lottery

> (c) Does Leaflet have some characteristics that would attenuate the loss of the listed developer 
> (e.g., detailed documentation)?

- popularity, a lot of users and plugin writters
- code very well written and readable
- good documentation

**Comment by mourner** [comment]
:+1: what Yohan said.
