### ISSUE TITLE
1.0-dev L.geojson zoom in

### ISSUE THREAD

**Issue by ruick** [Leaflet/Leaflet#3716]
![2015-08-07 5 50 14](https://cloud.githubusercontent.com/assets/9210896/9133266/d91e60e8-3d2c-11e5-8b4e-84388e1d1303.png)
I use Leaflet 1.0-dev L.geojson method to create 2 svgs in overlayPane,  trouble is when I zoom in/out, the shape I draw transform to bottom right / top left corner, then return to the position it should be. I test with Leaflet 0.7.3, it works fine. but still 1.0-dev not working. cheers!

**Comment by mourner** [comment]
Please demonstrate that with a JSFiddle test case.

**Comment by ruick** [comment]
Hi mourner, I double check my code, wasn't problem with leaflet version, I download dev version two month ago and didn't update the leaflet.css, that was the problem, now it is working very well, thanks for the reply!

**Comment by mourner** [comment]
Thanks!
