### ISSUE TITLE
Plugin buttons are inconsistent

### ISSUE THREAD

**Issue by under-score** [Leaflet/Leaflet#3717]
When developing a site from scratch with multiple plugins (zoom, search, locate, forward/backward, bookmark, own stuff) it's a pain to edit all plugin css for a consistent look + feel.
It would be also good to have some bigger buttons for mobile devices.
What about recommending to all leaflet plugin authors some "awesome" button standard??

**Comment by mourner** [comment]
There are generic CSS styles for all buttons in Leaflet. It's the responsibility of plugin authors to follow them or use something different.

**Comment by under-score** [comment]
Is there any possibility to override with leaflet standards?
