### ISSUE TITLE
Question: Custom tiles generation and serving

### ISSUE THREAD

**Issue by iamromeo** [Leaflet/Leaflet#3719]
Hello guys

I know this is not exactly the place to post this but i am at a loss. It is true I am quit new at mapping but i have really searched quite a lot before coming to you. 

I want to create a website that people will be able to upload an image and this will made into tiles and then served to them so they can use leaflet to build up their own custom maps 

My question is. Is there a RESTful of otherwise API Service that I can send images to be rendered into tiles and then host them? If not is there a place I could host them (I already have a script to go from JPG -> Tiles structure (folders/images) 

I would really appreciate the help or just pointing me somewhere I could read.

**Comment by IvanSanchez** [comment]
You want to look at the plugins for non-map layers, which point to several services (http://leafletjs.com/plugins.html#non-map-base-layers) ; at MapTiler (https://github.com/calvinchengx/maptiler) and at gdal2tiles (https://github.com/pramsey/gdal2tilesp, http://www.gdal.org/gdal2tiles.html)

It might not be exactly what you're looking, but it should be enough to give you a few ideas.
