### ISSUE TITLE
Hyperlink in the Popups

### ISSUE THREAD

**Issue by user1982** [Leaflet/Leaflet#372]
A simple question....can i put some hyperlink in the text of the popups?

Thanks!!!!

**Comment by capan** [comment]
How is it possible to open the hyperlink in pop up in a new tab ?

**Comment by IvanSanchez** [comment]
@capan Please [use the Leaflet bugtracker only for bugs](https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md#reporting-bugs) and [do research before asking a question](https://stackoverflow.com/questions/6296013/how-can-i-open-a-link-in-new-tab-and-not-new-window).

**Comment by pipehat** [comment]
@capan To open in a new tab: add `target='blank'` attribute to your **a** tag

**Comment by codemeleon** [comment]
Hi,

When I try to integrate  web link as 

L.marker([14.896579,26.835767]).bindPopup("<a href='www.google.com/'>Google</a><br/>").addTo(map);

The link appears as "http://localhost:8000/www.google.com" in the popup. How can I fix it?

Thanks.

**Comment by pipehat** [comment]
> href='www.google.com/'

href value is relative to current host unless you fully qualify it. 
href=‘https://google.com’

**Comment by codemeleon** [comment]
Thank you. It resolved the problem.
