### ISSUE TITLE
Get Tiles using XHR; Content Security Policies

### ISSUE THREAD

**Issue by michaschwab** [Leaflet/Leaflet#3720]
Hi!
I'm excited to use Leaflet! I'm building a Chrome packaged app with it.

Chrome packaged apps have pretty strict content security policies (CSP). One of them is that eval() etc are not allowed. This gives Leaflet a big advantage here, as it doesn't seem to use it, whereas Google Maps, Nokia's HERE and others use it all over their program.

Another restriction is that I can't have any resources straight from the web, as in img src=http...
This is a problem for me when using leaflet, as the tiles are just loaded by putting the image address in the img source. This doesnt work for packaged apps, so leaflet doesnt work at all there. I do realize this was mentioned in this issue: https://github.com/Leaflet/Leaflet/issues/3056.

What can be done instead is to load the image from the js, using an XHR, and putting the actual image data in the source attribute of the image. I already got it to work that way, it's an easy change.

Instead of using the method getTileUrl in _loadTile, I am using the newly created method setTileUrl, which sets the image source after the tile is loaded:

	setTileUrl: function (tilePoint, tile) {

		// http has to be added here because otherwise it would try to load the image at chrome-extension:// ....
		var addr = 'http://' + L.Util.template(this._url, L.extend({
				s: this._getSubdomain(tilePoint),
				z: tilePoint.z,
				x: tilePoint.x,
				y: tilePoint.y
			}, this.options));

		var xhr = new XMLHttpRequest();
		xhr.open('GET', addr, true);
		xhr.responseType = 'blob';
		xhr.onload = function(e) {
			tile.src = window.URL.createObjectURL(this.response);
		};
		xhr.send();
	},

Then, _loadTile is just changed a little:

		// ...
		this._adjustTilePoint(tilePoint);
		this.setTileUrl(tilePoint, tile);
		// ...

And that makes Leaflet work in Chrome Apps and other environments with strict CSPs.

I'm posting this here hoping that a better implementation of this can be included in the official Leaflet code so that other people can use this as well and so I can use the official version and get updates in the future without needing to do manual edits to the code for my scenario.

I think if it was an option to either load the images using the browser's automatic feature, or to use an XHR, it could easily be included in the official version. What do you think?

Thanks!!
Michail

**Comment by IvanSanchez** [comment]
I see a few problems with implementing this in the core leaflet. On one hand, Leaflet has to run on IE8, even IE7. Using XMLHttpRequest means IE10+. The second one being tile servers with no CORS set up (there are a few out there, specially when people deploy their own). And we don't want these tileservers stop working.

But it should be pretty easy to make this a plugin; just do `L.TileLayer.include({ setTileUrl(){...} }` with your own implementation.

**Comment by mourner** [comment]
XMLHttpRequest works in old IE (I think 6+). But yeah, I don't want to support this in the core — the use case is pretty narrow and specific, and it's easy to make a plugin.

**Comment by michaschwab** [comment]
1. I'm pretty sure CSPs are going to become more and more relevant in the future as Google is pushing hard for them and Leaflet would be positioning itself progressively if it would be able to deal with CSPs. I think downplaying its importance is a mistake.

2. Loading the images through XHR would only be done for people that specifically set that option, and of course the default would be not to. Having this option will never exclude use cases, such as as servers that don't support CORS, because people that want to use those servers will just not set that option. In fact, the opposite is the case, having this option adds use cases to Leaflet, making it one of the best options for CSP-restricted apps as most map tools use eval() and can therefore not be used.  Leaflet can be putting itself in a leading position in a growing field here. It's not growing like crazy yet, but it might later on.

3. I guess I can provide the setTileUrl method as a plugin, but I need to ensure it is actually used. I don't know Leaflet well yet. How do I do that? Thanks

**Comment by mourner** [comment]
> Leaflet would be positioning itself progressively if it would be able to deal with CSPs. I think downplaying its importance is a mistake.

If we didn't "downplay the importance" of every feature our users are asking, we would quickly end up with monstrous bloatware. Let the project maintainers decide what is important and how it should be positioned.

**Comment by IvanSanchez** [comment]
> I guess I can provide the setTileUrl method as a plugin, [...]  I don't know Leaflet well yet. How do I do that?

@ michaschwab Like this: https://gist.github.com/IvanSanchez/34513a0f8810c7bceee8

Make sure that code works in Leaflet 1.0-beta1, make a repo for it (with README and license and the usual stuff), and read http://leafletjs.com/plugins.html#develop-your-own .

> Leaflet can be putting itself in a leading position in a growing field here. It's not growing like crazy yet, but it might later on.

Sorry, mate, I've been in the web far too long to drink the "it's gonna be huge in the future" kool-aid.

> XMLHttpRequest works in old IE (I think 6+).

@mourner Yeah, but it was an ActiveX component back then (see https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#Browser_Compatibility), which means implementing `L.Util.XHR()` or something like that.
