### ISSUE TITLE
e.originalEvent is undefined for leaflet b1

### ISSUE THREAD

**Issue by ivanmobigis** [Leaflet/Leaflet#3724]
Hi there,

I'm getting an error: "e.originalEvent is undefined" in the _filterClick function of L.DomEvent, when using Firefox (39) on Android (5).

adding a simple:

    if (e.originalEvent === undefined) {
        handler(e);
        return;
    }

at the top of the function seems to fix the problem without any obvious adverse effects. I'm not sure if i should be reporting issues for the beta version to this GitHub repo ?

cheers

-i

**Comment by IvanSanchez** [comment]
I'm afraid I don't fully understand the issue.

Can you please post the code that triggers this? A jsfiddle, or a link to a page with this error?

**Comment by ivanmobigis** [comment]
Hi there ivan (also my name !)

ok it took me a while to make the fiddle but in doing so maybe i found why it happens..

the fiddle is here:
https://jsfiddle.net/kx1mkLmq/11/
point your mobile here:
https://jsfiddle.net/kx1mkLmq/11/embedded/result/

in fact using the latest version of leaflet b1 i can only reproduce it when we click on overlays for the layer control.. turn 'cities' on and off for a while and the error will come up.. maybe because on clicking on the 'label' instead of the 'input' its no longer the original (native) event ? 

Unfortunately, Leaflet definitely assumes e.originalEvent is never null because it inspects: e.originalEvent.timeStamp without first verifying e.originalEvent.. I think this should be considered a bug.

For some reason chrome on android never arrives at the _filterClick function, I'm not sure why.

cheers

-i

**Comment by yohanboniface** [comment]
Unable to reproduce. Can you try with latest master (http://playground-leaflet.rhcloud.com/ may help for that) ?

**Comment by frbehrens** [comment]
I can confirm the bug also for leaflet v0.7.7 on Firefox 37.0.2 on Android.
When tapping on layer control I receive:
 `W/GeckoConsole(12657): [JavaScript Error: "TypeError: e.originalEvent is undefined" {file: ".../leaflet-src.js" line: 6583}]`.

Regards,
   Frank

**Comment by ivanmobigis** [comment]
Hi there,

Sorry i had never seen the message that yohanboniface couldn't reproduce.

i can confirm that my fiddle does reproduce 'reliably'. you need to use *Firefox* on Android (sorry that i used the word 'Chrome' in my second post !.. so you need to jump through the hoops to get a console window available:

https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_Firefox_for_Android_with_WebIDE

but once there then clicking on the 'Cities' label will give:

    TypeError: e.originalEvent is undefined
    L.DomEvent._filterClick()     leaflet-src.js:6977
    L.DomEvent._on/handler(        leaflet-src.js:6824
    L.Map.Tap<._simulateEvent(  leaflet-src.js:7886
    L.Map.Tap<._onUp()          leaflet-src.js:7860
    L.DomEvent._on/handler()      leaflet-src.js:6795


The problem is it is not every time, sometimes the click simply doesn't work, with no error. So even if you can't extract the error, you can at least see that clicking the label doesn't do anything, which is probably for the same reason ?

**Comment by IvanSanchez** [comment]
@ivanmobigis Can you please check if #4256 fixes the problem?
