### ISSUE TITLE
Canvas tile layer doesn't cover entire map in non-mercator projections.

### ISSUE THREAD

**Issue by motionsmith** [Leaflet/Leaflet#3728]
My demonstration of the issue can be seen in [this JSFiddle](http://jsfiddle.net/motionsmith/nyqg4x3t/).

I need to use the ``TileLayer.Canvas`` layer on a Leaflet map that uses equal-area projection. My project specs prohibit using the default Mercator projection.

Notice that **the tiles do not cover the entire map**.

On a default CRS projection (Mercator), the tile layer starts in the upper left corner. When I change the CRS to a different projection, the tile layer starts at LatLng(0, 0). This is fine (it even makes sense), but as you can see, **Leaflet is not rendering any tiles above the equator**. It gets even worse if you set the``noWrap`` option to ``true`` on the canvas layer.

Any suggestions would be very helpful.

**Comment by IvanSanchez** [comment]
Is this reproducible in 1.0-beta1?

I suspect something similar to #2981 - a "less-than vs less-than-or-equal-to" problem with the map bounds. https://github.com/Leaflet/Leaflet/blob/stable/src/layer/tile/TileLayer.js#L357 looks like the right point to start tracing the code, if you've got the time for it.

**Comment by motionsmith** [comment]
I'd like to test it in Beta1, but it's failing at line 26 of that JSFiddle: ```var canvasTiles = L.tileLayer.canvas();``` It says that the ``canvas()`` function does not exist. Did this implementation change in the Beta? How do you create a new canvas layer in Beta 1?

**Comment by motionsmith** [comment]
Okay, I see that I can create a new canvas layer with ``L.canvas()``.

But ``canvas.drawTile()`` never executes. Is this a Beta 1 bug?

**Comment by IvanSanchez** [comment]
No, `L.Canvas` is a vector **renderer**, not a kind of tiled layer.

`L.TileLayer.Canvas` is gone in 1.0. In its place, you should use the new `L.GridLayer`, following the examples in the 1.0 docs: https://mourner.github.io/Leaflet/reference.html#gridlayer

**Comment by motionsmith** [comment]
Ah. Well, for this project, we really would/should not move to the Beta version anyway. We're already using the stable version in production. We will need to resolve it in 0.7.3.

You're recommendation of looking near ``_tileShouldBeLoaded`` seems correct. I'm quite confident this is where the bug is. I'll monkey around in there. With your experience in the codebase, you may find the solution is a quick and obvious. If you were able to take a few minutes and step through there to see if anything obvious pops up, we would be very appreciative. Either way, I'll keep looking.
