### ISSUE TITLE
Proj4leaflet CRS not working

### ISSUE THREAD

**Issue by chronixlo** [Leaflet/Leaflet#3731]
crs = new L.Proj.CRS.TMS('EPSG:3067',
        '+proj=utm +zone=35 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs',
        [-548576, 6291456, 1548576, 8388608],
        {
            origin: [0, 0],
            resolutions: [
                8192, 4096, 2048, 1024, 512, 256,
                128, 64, 32, 16, 8, 4, 2, 1, 0.5,
                0.25, 0.125, 0.0625, 0.03125, 0.015625
            ]
        }
    );

map.setView() throws

    Uncaught TypeError: Cannot read property 'min' of undefined

Works in 0.7.3 but not in master. Does proj4leaflet need to be updated and do you know if that's happening?

**Comment by mourner** [comment]
There's a separate branch of Proj4Leaflet that's compatible with Leaflet master (since a lot has changed in projections code). @perliedman can say more.

**Comment by perliedman** [comment]
@chronixlo yes, there's a branch here: https://github.com/kartena/proj4leaflet/tree/leaflet-proj-refactor

It should work with master, please open an issue with Proj4Leaflet if you have further problems!
