### ISSUE TITLE
No maps at a scale greater than 13

### ISSUE THREAD

**Issue by evgenyshev** [Leaflet/Leaflet#3734]
Not displayed map with a single address at a scale greater than 13. If more than one address - everything is fine. If one - card only appears when you click on the marker.

see — http://youtu.be/Adv7PM8RDbo

I use the library for http://leafletjs.com/download.html site on Drupal (modules https://www.drupal.org/project/ip_geoloc and https://www.drupal.org/project/leaflet), contact the developers, but they refer to the library itself. I would like to know if you meet a similar problem and, if so, how to solve it? Thank you. 

see — https://www.drupal.org/node/2547631

**Comment by mourner** [comment]
Can you reproduce the issue with a minimal JSFiddle test case? (just a static example with Leaflet, no Drupal stuff/etc). I'm not sure this is a Leaflet issue.

**Comment by evgenyshev** [comment]
I was just important to know how the card (eg Google) by Leaflet with one marker and scale greater than 13 (14, 16, 18). If "pure" script everything is fine, I will refer to the Drupal developers. With the library itself, I do not know, so I address to you and to see you are met with a similar problem or not.

**Comment by IvanSanchez** [comment]
@evgenyshev Then let us know if the problem is *not* related to Drupal (or when you have a simple failing use case), in order to re-open this bug.
