### ISSUE TITLE
No contextmenu on map in beta 1.0.0

### ISSUE THREAD

**Issue by FileNotFound** [Leaflet/Leaflet#3735]
The standard browser right click menu seems to be disabled in 1.0.0-b1.

The API for Map -> Events suggests to subscribe to `contextmenu`-event to prevent default browser behaviour, 
> Fired when the user pushes the right mouse button on the map, prevents default browser context menu > from showing if there are listeners on this event. Also fired on mobile when the user holds a single touch for a second (also called long press).

so I think the *default* behaviour should be enabled by default.
See [1.0.0 result](http://jsbin.com/duwowanika/edit?html,js,output) vs. [0.7.3 result](http://jsbin.com/vuhicufelu/edit?html,js,output).
Tested on Firefox and Chromium.

**Comment by mourner** [comment]
I think this was brought up before but can't remember when exactly, @yohanboniface?

**Comment by yohanboniface** [comment]
Should be fixed by https://github.com/Leaflet/Leaflet/pull/3639

**Comment by IvanSanchez** [comment]
@mourner Do you mean #3639 ?
