### ISSUE TITLE
Incomplete documentation on how to implement a custom canvas layer (v1.0.0-beta1)

### ISSUE THREAD

**Issue by denilsonsa** [Leaflet/Leaflet#3736]
As mentioned in [issue 3728](https://github.com/Leaflet/Leaflet/issues/3728#issuecomment-130000074):

> `L.TileLayer.Canvas` is gone in 1.0. In its place, you should use the new `L.GridLayer`, following the examples in the 1.0 docs: https://mourner.github.io/Leaflet/reference.html#gridlayer

However, the documentation seems incomplete, or simply non-working. The documentation is missing the lines to actually add the new layer to the map.

I wrote a [testcase on JSFiddle](https://jsfiddle.net/m3b2buxo/) trying to add the new canvas layer to the map, but it throws `this.callInitHooks is not a function`.

Suggestion 1: improve the documentation, or if this is a bug, fix the bug.

Suggestion 2: add some documentation on how to convert old `L.TileLayer.Canvas` code to the new 1.0 version.

Tested on v1.0.0-beta1, on Google Chrome 44.

**Comment by mourner** [comment]
You forgot `new` with a couple more variable typos. Here's the working version: https://jsfiddle.net/m3b2buxo/2/

**Comment by denilsonsa** [comment]
Thanks, @mourner ! Would you mind adding the missing `new` line to the beta documentation?

I didn't know it would require calling `new`, as the built-in layers work don't need that.

**Comment by IvanSanchez** [comment]
@mourner Please keep in mind #3733 if you plan on modifying the `gh-pages-master` branch

**Comment by mourner** [comment]
Don't use Class extend then. Here's how you'd use that without "new": https://jsfiddle.net/m3b2buxo/3/
