### ISSUE TITLE
Marker Popups / clickable multiple times Beta 1.0

### ISSUE THREAD

**Issue by clemenslermen** [Leaflet/Leaflet#3739]
Hi guys,
in Beta1 of 1.0 the .bindPopup behavior seems a bit different.
Till now it was always that way, that you were only able to click a marker once. Now the touch event doesn't seem to be removed, and so I can click multiple times on the marker - which results in the Popup opening again, but with different position, with every click moving upwards.

**Comment by IvanSanchez** [comment]
I cannot reproduce with vanilla markers. Can you please provide a webpage where this error appears? Does the error display in more than one browser?

**Comment by clemenslermen** [comment]
Unfortunatly i can't provide an example at the moment.
As additional information: I'm using https://github.com/stefanocudini/leaflet-layerJSON for building the markers out of a JSON response from my server API

**Comment by clemenslermen** [comment]
Found now the problem - it was in my code. I had an additional fuction triggered on click, which did a bindpop up - every click - what a mess.
That was stupid. In Leaflet 0.7 it somehow worked - in the 1.0 beta1 somehow it always added the popupanchor difference with every click.
