### ISSUE TITLE
opening a popup with a click event

### ISSUE THREAD

**Issue by levelos** [Leaflet/Leaflet#374]
Hey gang - I'm stumped as to the best way to open a popup event through a click event of a DOM object. E.g., I have a search interface with a list of results, that are also plotted on the map, and I want to open the corresponding popup when one of the results are clicked.

I see the Leaflet map object contains a list of features in _layers indexed by _leaflet_id. Is that intended to be private? How do I get at the _leaflet_id when creating a marker?

**Comment by dksivagis** [comment]
ge
