### ISSUE TITLE
On Zoom and setView: Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by jrweinb** [Leaflet/Leaflet#3742]
Hello - 

When either zooming or setting the view of a map, I am getting the following error. 
`Line 480 of Leaflet-src.js: Uncaught TypeError: Cannot read property 'slice' of undefined `

I am using the plugin TileLayer.GeoJSON to render a vector slippy map layer. 

This is the code at line 480 in Leaflet-src.js: 

          for (contextId in typeIndex) {
                listeners = typeIndex[contextId].slice();

                if (listeners) {
                    for (i = 0, len = listeners.length; i < len; i++) {
                        listeners[i].action.call(listeners[i].context, event);
                    }
                }
            }

I was able to fix the issue by changing the code to the following:

            for (contextId in typeIndex) {
                if (typeof(typeIndex[contextId]) !== 'undefined'){
                    listeners = typeIndex[contextId].slice();
                }

                if (listeners) {
                    for (i = 0, len = listeners.length; i < len; i++) {
                        listeners[i].action.call(listeners[i].context, event);
                    }
                }
            }

I have some questions:

1. Is this a known issue?
2. Is my approach to fixing the issue the correct one, or is it hacky?

Happy to submit a pull request if this is the correct approach...

**Comment by IvanSanchez** [comment]
Two things:

1) AFAIK, that code exists only on the `stable` (AKA 0.7.x) branch. Try usin Leaflet 1.0-beta1.

2) What browser(s) are you using? That reminds me of a classic IE8 problem where a `for (a in b)` iterates over the default methods of an array.

**Comment by jrweinb** [comment]
I am Leaflet 0.7.3 on Chome 44.0.2403.130 (64-bit). I will try the beta and see if I still have an issue.

**Comment by jrweinb** [comment]
It seems that the plugin TileLayer.GeoJSON only works with the stable version, so I cannot reproduce the issue in the beta.

**Comment by IvanSanchez** [comment]
Hm, I wouldn't expect this to happen in up-to-date Chrome. :-1:

Can you post an example of a webpage which triggers this bug (a jsfiddle, maybe)? I wouldn't mind to have a look.

Also: glenrobertson/leaflet-tilelayer-geojson#27

**Comment by jrweinb** [comment]
@IvanSanchez - apologies for the delay, I was on summer vacation. I will do my best to get a jsfiddle up in the next 2 days

**Comment by yohanboniface** [comment]
ping @jrweinb
