### ISSUE TITLE
.trigger not working on zoom controls

### ISSUE THREAD

**Issue by kcabhish** [Leaflet/Leaflet#3743]
I am trying to unit test the zoom in controls in leaflet. For some reason .trigger('click') does not work on the control buttons. The button elements for both zoom in and zoom out exists in the DOM and each has class name of 'leaflet-control-zoom-in' and 'leaflet-control-zoom-out' respectively.

My default zoom level is set to 5. And following are my sample code for testing the trigger event.

console.log(map.getZoom());    //displays 5
console.log(angular.element('a.leaflet-control-zoom-in').attr('class'));   //checking to see if element exists
angular.element('a.leaflet-control-zoom-in').trigger('click');   //expecting to trigger click event
console.log(map.getZoom());    //expected zoom level 6, but displays 5.

**Comment by kcabhish** [comment]
Sorry for posting without much research. This is a non issue. Since .trigger only works with events added using jQuery it did not work. 

angular.element('a.leaflet-control-zoom-in')[0].click(); worked.

**Comment by IvanSanchez** [comment]
Note that zoom controls use `L.DomEvent.on('click')` and **not** `L.Evented.on('click')`. `trigger()` exists only in `L.Evented`.

You need to trigger DOM events, not Leaflet events. See https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events#Triggering_built-in_events on how to do so.
