### ISSUE TITLE
doc anchors are inaccessible

### ISSUE THREAD

**Issue by jfirebaugh** [Leaflet/Leaflet#3746]
It's no longer possible to click on the anchor icon in documentation to get a permalink: just when the cursor gets near the anchor, the anchor disappears.

![anchor](https://cloud.githubusercontent.com/assets/98601/9279919/95e93058-426f-11e5-8816-a6e49b76d186.gif)

**Comment by mourner** [comment]
Interesting, it works fine for me in Chrome under OS X. Did you try different browsers? Which is that?

**Comment by jfirebaugh** [comment]
It's Chrome 44.0.2403.130 on OS X.

**Comment by jfirebaugh** [comment]
Seems to happen on some items and not others -- if you don't see it at first try a different section.

**Comment by snkashis** [comment]
I can't seem to replicate this either. Chrome 44.0.2403.157 on OS X.

**Comment by yohanboniface** [comment]
Seems like a conflict with the `toc-copy` element:

![screenshot from 2015-09-28 12 46 11](https://cloud.githubusercontent.com/assets/146023/10133625/ffa0d284-65de-11e5-94d2-0f85f26faf59.png)

**Comment by yohanboniface** [comment]
@rowanhogan are you able to have a quick look on that?
