### ISSUE TITLE
implement https only for www.leafletjs.com

### ISSUE THREAD

**Issue by robertharm** [Leaflet/Leaflet#3748]
It would be great if www.leafletjs.com could be provided via https only. A good summary, why this is advised (for every site) can be found at https://medium.com/so-now-you-know/10-reasons-to-go-https-a2cba5734bb6

**Comment by TheSisb** [comment]
Doesn't matter *too* much for a site like leaflet.com, really.  However, cloudflare does offer free https so shouldn't be too difficult.

**Comment by mourner** [comment]
leafletjs.com is hosted on GitHub pages, not CloudFlare. I also don't think this is critical, since this is just a static website, so there's no privacy to be protected.

**Comment by robertharm** [comment]
yes, it is definitely not critical for leafletjs.com, although nice to have ;-)

**Comment by TheSisb** [comment]
@mourner Cloudflare isn't actually a webhost, it's more like a reverse proxy.  You just modify some minor DNS entries on your domain registrar for leafletjs.com and it goes through Cloudflare to the Github pages, with some added benefits (such as free SSL).  It's all free too, unless you want more features.

https://www.benburwell.com/posts/configuring-cloudflare-universal-ssl/

**Comment by mourner** [comment]
@TheSisb oh wow, I didn't know that! Very cool. I'll look into it.

**Comment by IvanSanchez** [comment]
FYI: Upstream bug at https://github.com/isaacs/github/issues/156
