### ISSUE TITLE
Leaflet 1.0 beta and polylinedecorator issue

### ISSUE THREAD

**Issue by Szecskkaa** [Leaflet/Leaflet#3749]
I tried to use the leaflet polyline decorator with leaflet 1.0 beta, but I ran into a problem. When I set rotate: true, the markers are not on the polylines, but when I use the leaflet 0.7.3, the markers are on the polylines. (See the two pictures (first: 0.7.3, second: 1.0 beta)) 

[![enter image description here][1]][1]

[![enter image description here][2]][2]

I use the same code, the difference is the version of leaflet. 

var map = L.map('map').setView([52, -11.0], 5);

L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);
			
var markerLine = L.polyline([[58.44773, -28.65234], [52.9354, -23.33496], [53.01478, -14.32617], [58.1707, -10.37109], [59.68993, -0.65918]], {}).addTo(map);
			
var pathPattern = L.polylineDecorator(markerLine,{
	patterns: [
		{ offset: '10px', repeat: '100px', symbol: L.Symbol.marker({rotate: true, markerOptions: {
			icon: L.icon({
				iconUrl: 'images/marker-icon.png',
				iconSize: [11, 17]
			})
		}})}
	]
}).addTo(map);

  [1]: http://i.stack.imgur.com/q0KLF.png
  [2]: http://i.stack.imgur.com/PIRM9.png

**Comment by IvanSanchez** [comment]
This is a [issue of the polyline decorator plugin](https://github.com/bbecquet/Leaflet.PolylineDecorator/issues), not a Leaflet core issue. Please file this bug there instead.

**Comment by Szecskkaa** [comment]
Thank you for your answer. I just don't understand why is it the plugin's issue. I didn't change the plugin version (master), just the leaflet version. But I am going to report this issue at the polyline decorator plugin's page.

**Comment by IvanSanchez** [comment]
Leaflet 1.0 is a big release, which breaks compatibility. It's up to the plugin authors to ensure that the plugin works the same with Leaflet 1.0, and not the other way around.
