### ISSUE TITLE
[bower] 1.0 beta 1 version is unbuilt on bower

### ISSUE THREAD

**Issue by hyperknot** [Leaflet/Leaflet#3750]
Leaflet 0.7.3 on bower provides the built files in dist/, just like the downloadable zip.
Leaflet 1.0 beta 1 version does not, the repository is missing the files which are in the cdn zip.

**Comment by IvanSanchez** [comment]
This is the *third* time I see a duplicate of #3635. Folks, look for existing bugs before posting a new bug, please.
