### ISSUE TITLE
Zoom controls broken in Shadow DOM on mobile Chrome

### ISSUE THREAD

**Issue by andyearnshaw** [Leaflet/Leaflet#3752]
We're using Leaflet inside a custom HTML element, which works fine on desktop browsers or mobile browsers where our polyfill is in place.  On Android Chrome, however, there's a problem with Shadow DOM's event retargeting that occurs for touch events.

At [this part of the code](https://github.com/Leaflet/Leaflet/blob/45034155bdf8d958554b43ed8dbd7020df9ca6ab/src/map/handler/Map.Tap.js#L71), the event target is the custom element containing the shadow root, instead of the zoom controls.

This issue affects at least the zoom controls.  Panning and zooming using touch don't seem to be affected, however.

**Comment by yohanboniface** [comment]
Can you set up a test case to demonstrate the issue? http://playground-leaflet.rhcloud.com/ may help :)
