### ISSUE TITLE
Clicking on layer triggers both map.on('click') and layer.on('click') events in 1.0 b1

### ISSUE THREAD

**Issue by lobitolufty** [Leaflet/Leaflet#3756]
When an overlay layer has an associated ```'click'```event, and the map has an associated ```'click'```event, clicking on the overlay layer will trigger both events. This issue did not occur in 0.7.3.

Fiddle: http://jsfiddle.net/lobitolufty/xjqdnr5p/25/

**Comment by IvanSanchez** [comment]
@yohanboniface This was expected behaviour with the refactored event logic, wasn't it?

**Comment by yohanboniface** [comment]
> This was expected behaviour with the refactored event logic, wasn't it?

Yep, see also https://github.com/Leaflet/Leaflet/pull/3605#issuecomment-119594089 for a recent discussion on why we've made an exception for markers.

@lobitolufty in the layer click callback, add something like this:

```
    L.DomEvent.stop(e);
```

This will prevent the map to get the event too.
