### ISSUE TITLE
Infowindow popup maxWidth not working

### ISSUE THREAD

**Issue by dhiman252** [Leaflet/Leaflet#3760]
I am facing an issue with the infowindow maxWidth property. This prperty is getting set up but is not working. Below is my code
<pre>
var marker = L.marker(new L.LatLng(a.lat, a.lng), {title: title});
marker.bindPopup('Loading..',{minWidth:150,maxWidth:200,maxHeight:250});
</pre>
By using the above code max height property is working fine but maxWidth and minWidth does not work.

**Comment by IvanSanchez** [comment]
What version of Leaflet are you using? 0.7.x or 1.0-beta1?

What do you mean by "not working"? If you use the developer tools in your browser, what is the CSS styling being applied to popups?

**Comment by dhiman252** [comment]
Leaflet version is 0.7.3
Not working means that the width is being assigned which i can see in the console under the infowindow options but its not working.

**Comment by IvanSanchez** [comment]
Please provide a link to a demo. I cannot see what's going on without seeing it for myself.

**Comment by dhiman252** [comment]
Please refer to the screenshot link: http://prntscr.com/86d5js

I have set the maxWidth property of the infowindow to 250 which can be seen easily but it does no effect the infowindow width.

**Comment by IvanSanchez** [comment]
What are the CSS properties of the popup's `_container`?

**Comment by dhiman252** [comment]
![untitled](https://cloud.githubusercontent.com/assets/8954468/9353076/4cf1c064-4683-11e5-93ee-d7b02507174b.jpg)
Its the default properties, but i guess the infowindow is taking a width of 320px from _containerWidth.
How can we modify the container width ?

**Comment by IvanSanchez** [comment]
The width of the popup is determined by the width of the *contents* of the popup, as per https://github.com/Leaflet/Leaflet/blob/master/src/layer/Popup.js#L202

So it's a problem on your side, not a leaflet bug, which means I'm closing this.

**Comment by dhiman252** [comment]
if the width of the popup is determined by the width of the contents of the popup then an empty popup with 10 letters of content also take the  _containerWidth. Is there any way to customize this attribute ?
