### ISSUE TITLE
mouseout and mousemover on svg not work in IE10

### ISSUE THREAD

**Issue by ilfa** [Leaflet/Leaflet#3761]
Problem started in #3684.

IE10 on desktop have window.MSPointerEvent and after this fix leaflet detect IE10 as mobile browser.

**Comment by IvanSanchez** [comment]
Sorry, but how is `L.Browser.msPointer` connected to SVG mouseout events?

**Comment by ilfa** [comment]
I'm not found yet, but after detecting ```L.Browser.msPointer``` Leaflet starts working in mobile mode.

```L.Browser.msPointer``` sets ```L.Browser.pointer``` and here problems start theirs way.

I found that mouseout and mousemover not works on svg, it's not works in canvas too. May be there another cases.

**Comment by mourner** [comment]
Should have been fixed by #3839
