### ISSUE TITLE
Can ILayer.onAdd be asynchronous?

### ISSUE THREAD

**Issue by neothemachine** [Leaflet/Leaflet#3762]
The documentation is not clear on what is and isn't allowed in ILayer.onAdd. For example, is it allowed to asynchronously load external data? I was [suggesting this](https://github.com/mpetazzoni/leaflet-gpx/issues/24) in the leaflet-gpx plugin as a fix to make `loaded` events work reliably, however I am not sure if this is how it should be.

Edit: I already mentioned using onAdd in this way in [google groups](https://groups.google.com/forum/#!topic/leaflet-js/tMiEFYCKnGU) but didn't get an answer if this is the right way to do it.

**Comment by IvanSanchez** [comment]
> is it allowed to asynchronously load external data?

Yes.

> [...] as a fix to make `loaded` events work reliably

Note that `layer`s do not define a `loaded` event (see `Marker`, for example), so it's up to you to fire that event when the layer actually loads.
