### ISSUE TITLE
GeoJSON Polygon not completely filled when not all of its points are visible

### ISSUE THREAD

**Issue by i-am-the-slime** [Leaflet/Leaflet#3764]
I have this Polygon. It is displayed fine.

However when I pan down or zoom in too much parts of it are not filled.
![bildschirmfoto 2015-08-21 um 14 50 02](https://cloud.githubusercontent.com/assets/1588055/9408813/0d46326c-4816-11e5-9de3-634652828dd4.png)
![bildschirmfoto 2015-08-21 um 14 50 10](https://cloud.githubusercontent.com/assets/1588055/9408815/0d6a3d10-4816-11e5-97dd-d17923a76027.png)
![bildschirmfoto 2015-08-21 um 14 50 17](https://cloud.githubusercontent.com/assets/1588055/9408814/0d690f76-4816-11e5-993c-426228b0c343.png)
![bildschirmfoto 2015-08-21 um 14 50 26](https://cloud.githubusercontent.com/assets/1588055/9408817/0dc65d02-4816-11e5-8827-0953e77062f5.png)

The polygon is created from a GeoJson source. Which is this:
```json
    {
        "type": "Feature",
        "geometry": {
            "type": "LineString",
            "coordinates": [
                [
                    6.843612910433537,
                    51.20941905680739
                ],
                [
                    6.830562412355305,
                    51.23766270716715
                ],
                [
                    6.843592,
                    51.2496964
                ],
                [
                    6.8460656,
                    51.2500734
                ],
                [
                    6.8624629,
                    51.2403688
                ],
                [
                    6.863794667943361,
                    51.23810950525879
                ],
                [
                    6.8628855,
                    51.2173121
                ],
                [
                    6.8619949,
                    51.2116952
                ],
                [
                    6.843612910433537,
                    51.20941905680739
                ]
            ]
        },
        "properties": {
            "type": "hotspot"
        }
    }
```
Now I create the layer like this:

```scala
val layerOptions = GeoJsonLayerOptions
        .fill(true)
        .fillColor("#bb0055")
        .fillOpacity(0.1)
        .color("#bb0055")
        .weight(1)
        .clickable(false)
        .build

      L.geoJson(json, layerOptions)
```

Is this an SVG or a Leaflet or an issue from my side? What can I do?

**Comment by IvanSanchez** [comment]
Please see #3763.

**Comment by i-am-the-slime** [comment]
Alright, I *think* this is because this is a LineString and not a Polygon. Therefore leaflet is not sure that it is a LinearRing, which it is and becomes crazy trying to fill it.

**Comment by i-am-the-slime** [comment]
Alright it works if it's a MultiPolygon. Sorry for the trouble, although somebody might want to document that somewhere.
