### ISSUE TITLE
Tiles are sometimes retained when they shouldn't

### ISSUE THREAD

**Issue by livemixlove** [Leaflet/Leaflet#3765]
Using Leaflet 1.0-dev (46d2d6a)

When I zoom in, the old (more zoomed out) layers do not disappear.   You have to drag or cause some other even for the layer to properly refresh.  See the attached image.  My hack to fix this is to add map.panBy([1, 1]);  to zoomend - not ideal.  Are there work arounds, or a fix in the works?   

Not sure if it matters, but the map div is downstream/inside a reactjs object - there might be some dom manipulation that's screwing things up...

<img width="353" alt="screen shot 2015-08-21 at 4 13 27 pm" src="https://cloud.githubusercontent.com/assets/148947/9420905/1adc2d6e-4820-11e5-9a8f-a7e15d676286.png">

**Comment by livemixlove** [comment]
Map option {zoomAnimation: false} fixed this.

But I'd like to keep the animations for usability/niceness.

**Comment by mourner** [comment]
Can you set up a JSFiddle test case to show this?

**Comment by brs-fcoo** [comment]
I'm experiencing exactly the same issue, which seems like it might be a race condition.
It doesn't happen every time and not as frequently in some browsers (Chrome/Chromium based seems to be affected the most).

A co-worker set up a JSFiddle test to illustrate the problem.
http://jsfiddle.net/jesper_larsen/c1h5b8wj/

To show the issue you just have to zoom in and out (using the buttons or a mouse-wheel).
You might have to do it 5-10 times, before it happens.

![zoom_issue](https://cloud.githubusercontent.com/assets/14541101/9987504/c652624a-6048-11e5-8c61-b94b93cafa39.png)

**Comment by yohanboniface** [comment]
Reproducible with latest master: http://playground-leaflet.rhcloud.com/had/edit?html,output

**Comment by IvanSanchez** [comment]
This is much easier to reproduce when zooming in/out several zoom levels at once. At least on my firefox, I can consistently reproduce by simply adding `map.zoomIn(4);` to @yohanboniface's code.

This smells like `L.GridLayer._pruneTiles()` is not working as it should. It should be a good place to start looking for the cause.

**Comment by mourner** [comment]
The screenshots look like this is transparent labels on top of each other — is this really a problem we can actually fix? This is not an issue with pruneTiles. The issue is that once we zoom in, z13 parent tile is retained until _all_ 4 of its z14 children are loaded, which certainly means a delay where both z13 and z14 are present on a map. It's unnoticeable with opaque tiles, but becomes a problem with semitransparent ones. I don't think it's possible to fix this without a lot of blood.

**Comment by yohanboniface** [comment]
The issue disappear when removing "updateInterval: 50".

**Comment by yohanboniface** [comment]
> which certainly means a delay where both z13 and z14 are present on a map

@mourner issue here is that sometime the old zoom tiles **remain**.

**Comment by IvanSanchez** [comment]
@mourner I think the "right" way to fix this is to modify pruneTiles so it retains a tile until all its children **visible within the map viewport** have been loaded (not neccesarily all 4 of them).

**Comment by mourner** [comment]
@IvanSanchez oh, haven't thought of that. Sounds like a good idea!
@yohanboniface remain as in forever?

**Comment by IvanSanchez** [comment]
@mourner Remains until the map is panned or otherwise the view is reset.

**Comment by yohanboniface** [comment]
> remain as in forever?

Yep. Like a viewReset is missing.

**Comment by mourner** [comment]
That's certainly a bug, yeah.

**Comment by mourner** [comment]
Think it's a throttle race condition?

**Comment by yohanboniface** [comment]
> Think it's a throttle race condition?

That's my guess right now.

**Comment by yohanboniface** [comment]
Well, I can still reproduce with `updateInverval: 200` but it seems much harder. Real smell of race condition.

**Comment by yohanboniface** [comment]
For the record, I was able to reproduce even on zoom out.

**Comment by IvanSanchez** [comment]
Due to playground maintenance, I messed up the existing examples, so the one for this bug now lives at http://playground-leaflet.rhcloud.com/puw/edit?html,output

**Comment by tehGoti** [comment]
Any news on this issue?

**Comment by hyperknot** [comment]
I inserted a button for map.zoomIn(4) as @IvanSanchez recommended, that way it reproduces 9 out of 10 times in FF and Chrome. 
http://playground-leaflet.rhcloud.com/row/3/edit?html,output

UpdateInterval seems to have no effect for me, putting it to 10000 still didn't change anything (neither bug, nor speed of Leaflet).

Good news is that it's not present in 1.0 beta-1 for me. The animation is faster in this one, though so it might be a different environment here.

**Comment by jblarsen** [comment]
Hi

I have modified the playground example that hyperknot posted 20 days ago with a monkey patched _pruneTiles method for the tile layer:

http://playground-leaflet.rhcloud.com/tur/1/edit?html,console,output

The problem disappears when the call to _retainParent is commented out. It seems like the tiles at the old zoom level are sometimes having their "retain" property set thus preventing them from being purged. I am not sure whether that is OK or not.

I have also added a line of logging. If you look at the tile.active attribute it is sometimes undefined. But that means that !tile.active is true which in turn means that the if statement is fulfilled if tile.current is true. Is that OK?

Best regards,
Jesper

**Comment by jblarsen** [comment]
Hi all

I believe that I am closer to a solution. The problem seems to be caused by the fadeAnimation. If we disable that the problem seems to disappear:

http://playground-leaflet.rhcloud.com/caq/edit?html,console,output

The cause seems to be in the _updateOpacity method where we have

```
for (var key in this._tiles) {
            var tile = this._tiles[key];
            if (!tile.current || !tile.loaded) { continue; }

            var fade = Math.min(1, (now - tile.loaded) / 200);

            L.DomUtil.setOpacity(tile.el, fade);
            if (fade < 1) {
                nextFrame = true;
            } else {
                if (tile.active) { willPrune = true; }
                tile.active = true;
            }
        }

        if (willPrune && !this._noPrune) { this._pruneTiles(); }
```

I believe this should be:

```
for (var key in this._tiles) {
            var tile = this._tiles[key];
            if (!tile.current || !tile.loaded) { continue; }

            var fade = Math.min(1, (now - tile.loaded) / 200);

            L.DomUtil.setOpacity(tile.el, fade);
            if (fade < 1) {
                nextFrame = true;
            } else {
                willPrune = true;
                tile.active = true;
            }
        }

        if (willPrune && !this._noPrune) { this._pruneTiles(); }
```

If we look at what happens when we have fadeAnimation set to false we have (in _tileReady):

```
if (this._map._fadeAnimated) {
            L.DomUtil.setOpacity(tile.el, 0);
            L.Util.cancelAnimFrame(this._fadeFrame);
            this._fadeFrame = L.Util.requestAnimFrame(this._updateOpacity, this);
        } else {
            tile.active = true;
            this._pruneTiles();
        }
```

This means that we always prune the tiles when fadeAnimation is set to false. The tile does not have to be active "beforehand". My suggestion for a fix modifies the fadeAnimation behaviour to do the same.

I am however not sure what the intention of the if (tile.active) statement in original code is. Have I missed something?

Regards,
Jesper

**Comment by IvanSanchez** [comment]
@jblarsen Can you please turn that into a pull request? It makes looking at the changes and testing so much easier.

**Comment by IvanSanchez** [comment]
I've run into something very similar in #4193 - and I've realized there is a mismatch between the tiles being `load`ed, the gridlayer being `load`ed, and the tiles *fading in*.

So the pruning algorithm runs whenever the gridlayer has finished loading, which can be *sooner* than when the tiles have faded in, which means they haven't been set to *active*, which means they are not pruned.

Maybe we can document with comments the semantics of all these tile states?

**Comment by IvanSanchez** [comment]
@brs-fcoo @livemixlove Could you please test if this bug is still reproducible in `master`? I'm hoping that the change from https://github.com/Leaflet/Leaflet/pull/4193/files#diff-f1e6be67599c594731fff6191c710420R674 might have fixed this.

**Comment by jblarsen** [comment]
@IvanSanchez brs-fcoo and I have tested the newest master in our setup. We cannot reproduce the bug anymore.

**Comment by IvanSanchez** [comment]
@jblarsen @brs-fcoo Glad to hear the bug is gone! :-D

I'll close the bug and pull req for you.
