### ISSUE TITLE
Focus input inside a popup when showing

### ISSUE THREAD

**Issue by HarelM** [Leaflet/Leaflet#3766]
Hi, I'm not sure if I'm doing something wrong or this is a bug but I want to achieve the following scenario:
1. User clicks on Marker
2. Popup shows up with and input inside.
3. The input is focused and the user can write in it.

I have tried to call JQuery's ```.focus() ``` like so:
```js
marker.on("click", function (e) {
                marker.openPopup();
                $("#markerInput").focus();
            });
```
it didn't work...
help is appreciated, using leaflet 0.7.3.

**Comment by IvanSanchez** [comment]
I tried that on http://jsfiddle.net/xko92ef8/ , and cannot reproduce your error.
