### ISSUE TITLE
Delegated events over all markers in L.featureGroup

### ISSUE THREAD

**Issue by TheSisb** [Leaflet/Leaflet#3767]
(I'm using Leaflet 1.0.0 beta 2)

Rather than binding events to every feature individually in a featureGroup, there is documentation to bind events to an entire featureGroup (http://leafletjs.com/reference.html#featuregroup).  The problem here is that the event callbacks aren't provided with enough information to determine which exact item in the group triggered the event - just that it triggered.

The only reference to this issue I found on Stackoverflow was here: http://stackoverflow.com/questions/30849283/how-to-get-id-of-layer-in-feature-group-on-click  
The only solution proposed involves binding events to every item manually which goes against the purpose of binding events to the featureGroup itself.

After some investigation I found a solution that worked in 'mouseover', but not consistently in 'click'.
```js
// THIS WORKS
L.featureGroup([...])
  .on('mouseover', function(e) {
    var elementObj = this._layers[e.layer._leaflet_id];
    console.log( elementObj.getLatLng();
  });

// THIS GIVES THE ERROR: Uncaught TypeError: Cannot read property '_leaflet_id' of undefined
L.featureGroup([...])
  .on('click', function(e) {
    var elementObj = this._layers[e.layer._leaflet_id];
    console.log( elementObj.getLatLng();
  });
```

My idea is to provide the focal element that triggered the event for that featureGroup as part of the arguments into the callback function.
Example: 
```js
L.featureGroup([...])
  .on('mouseover', function(e, *element*) { 
    console.log(element.getLatLng());
  });
```

Any thoughts on this? Am I missing something?  Thanks for an awesome library!

**Comment by Eschon** [comment]
I never used a featureGroup with different kinds of items before but couldn't you just do something like:

```JavaScript
L.featureGroup(...).on('mouseover', function(e) {
  if (e.layer instanceof L.Marker) {
    //handle the event
  }
});
```

**Comment by mourner** [comment]
I don't quite understand the issue here.

```js
// aren't those lines the same?
var elementObj = this._layers[e.layer._leaflet_id];
var elementObj = e.layer;
```

If you're getting some kind of error in a specific case, can you set up a JSFiddle test case so that I could reproduce it?

**Comment by TheSisb** [comment]
Figured it out.

The error I was getting was because I was doing 

```js
.on('click', function(e) {
	...
	this.fire('mouseover');
})
.on('mouseover', function(e) {
	var elementObj = this._layers[e.layer._leaflet_id]; // This was causing the error in my first snippet
})
````

When you fire, the event object is defined as { type: "mouseover", target: e.layer } - first of all I shouldn't be firing to the mouseover event!  I thought the error was occurring on my click event which is what confused me.


Also e.layer == this._layers[e.layer._leaflet_id]
Thanks for that shorthand!
