### ISSUE TITLE
[feature request] continual inertial zoom.

### ISSUE THREAD

**Issue by trusktr** [Leaflet/Leaflet#3768]
Like in MapBoxGL or maps.google.com, where two-finger-drag zoom precisely the amount you drag, versus having specific levels of zoom.

**Comment by trusktr** [comment]
Oh wait, I see here "it works": https://github.com/Leaflet/Leaflet/issues/2295

How do we enable it? Is that the `zoomAnimationThreshold` option?

**Comment by trusktr** [comment]
Maybe it doesn't work for me because I'm in Linux, and the two finger drag behaves like mousewheel scrolls in Chrome?

**Comment by IvanSanchez** [comment]
Zoom animations are on by default as long as your browser is capable of CSS tranforms. See https://github.com/Leaflet/Leaflet/blob/master/src/map/anim/Map.ZoomAnimation.js#L10 and https://github.com/Leaflet/Leaflet/blob/master/src/core/Browser.js#L44

Are you using some kind of obscure web browser?

**Comment by trusktr** [comment]
@IvanSanchez I'm in Google Chrome 44.0.2403.157 64-bit in Linux. It has CSS transforms for sure, but Chrome in Linux uses GTK2 which doesn't have smooth/inertial scrolling like GTK3. Could that be why?

**Comment by IvanSanchez** [comment]
I honestly don't know. Chromium 44.0.2403.107 works without a hitch in my 64bit Debian.

You might want to check chrome://gpu (in particular, compositing), and check if the inline examples of CSS transitions at https://developer.mozilla.org/docs/Web/Guide/CSS/Using_CSS_transitions work for you.

**Comment by trusktr** [comment]
@IvanSanchez Well, CSS transforms work just fine in my browser, the animation is buttery smooth.

What I mean is continual scrolling. Like for example, if I'm at zoom level 2, then if I slide my two fingers on the touchpad just a little bit, I want to end up at zoom level 2.34561943, not zoom level 3.

Know what I mean?

**Comment by IvanSanchez** [comment]
You mean #3523 :-)

Closing as duplicate.

**Comment by trusktr** [comment]
@IvanSanchez Aah, alright, cool!
