### ISSUE TITLE
Zoom anim breaks vector layers at low zooms

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#3769]
How to reproduce:

* Load up `/debug/vector/vector.html`
* Repeteadly zoom in and out between zoom levels 0-1 or 1-2.
* See how the vector doesn't line up with the markers.

![leaflet-bug-1](https://cloud.githubusercontent.com/assets/1125786/9461981/c0899df6-4b12-11e5-9157-638de66469b4.png)
![leaflet-bug-2](https://cloud.githubusercontent.com/assets/1125786/9461982/c08c745e-4b12-11e5-9dbb-36edd295c6da.png)

Apparently vector layers are not positioned vertically in the right position during zoom anims, but only when the vector layer fits within the entire map container.

Affects both canvas and svg (see `/debug/vector/vector2.html`)

Using latest master. Reproducible on (at least) FFX and Chrome.

**Comment by mourner** [comment]
Wow, this is surprising.

**Comment by w8r** [comment]
That's a tricky one caused by `renderer._topLeft` being calculated from max latitude, which is then clamped if you are outside of [-90, 90] boundaries

**Comment by IvanSanchez** [comment]
The culprit seems to be #3700. cc @vas85 @perliedman.

So it's either:
* Reverting the changes from #3700 and make the 1.0 API break 0.7.x stuff (easier).
* Add some edge case management to calls to `L.Map.project` from `L.Map._latLngToNewLayerPoint` (because it later subtracts pixels so that the result is within bounds) (dirtier).
* Change `L.Renderer` so it uses the layer center to do the computations instead (cleaner but harder).

**Comment by perliedman** [comment]
Interesting.

I think the cutoff from #3700 is correct and removing it would not only break the API, it wouldn't be compatible with the [OSM/Google Maps/... tiling scheme](http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames). Under the section "X and Y", it states:

> Y goes from 0 (top edge is 85.0511 °N) to 2<sup>zoom − 1</sup> (bottom edge is 85.0511 °S) in a Mercator projection

So this cutoff is part of the definition for the CRS, and it looks like a bad idea to break that.

I can also imagine other projections/CRS would do the same or similar things, so it is probably good if Leaflet can handle it.
