### ISSUE TITLE
[BUG] detectRetina not working in Linux.

### ISSUE THREAD

**Issue by trusktr** [Leaflet/Leaflet#3773]
I've got `detectRetina` set to `true`, but it doesn't seem to work in Linux. I'm on a Macbook Pro Retina.

**Comment by trusktr** [comment]
Hmmm, although `L.Browser.retina` is `true`, the Open Street Map tiles are the same size and still pixelated after setting `detectRetina` to `true`.

**Comment by trusktr** [comment]
Is there a way to force the retina feature?

**Comment by IvanSanchez** [comment]
Retina tiles only work for specific tileservers. If memory serves right, the main OSM one is not retina-capable.

**Comment by mourner** [comment]
No, `detectRetina` option works on any tiles, just makes them smaller. I'm surprised it doesn't work for you but it probably a browser bug rather than a Leaflet feature.

**Comment by mourner** [comment]
What's the browser?

**Comment by IvanSanchez** [comment]
Also, what's the value of `L.Browser.retina`?

**Comment by trusktr** [comment]
@IvanSanchez The value is `true`.

@mourner I'm in Chromium 44.0.2403.157, Linux.

**Comment by trusktr** [comment]
I wonder if it has to do with Cinnamon/Gnome desktop in Linux scaling the whole desktop times 2.

**Comment by trusktr** [comment]
Have you guys tried in Linux before?

**Comment by trusktr** [comment]
I just tried it on Android, and it looks like this, still pixelated:

![screenshot_2015-08-25-12-40-06](https://cloud.githubusercontent.com/assets/297678/9477407/f870d11c-4b26-11e5-99ad-ed9100034a87.png)

I'm setting up the map like this

```js

        this.gMap = new L.Map(document.getElementById('map'), {
            zoomControl: false,
            center: [
                Meteor.user().profile.location.latitude,
                Meteor.user().profile.location.longitude
            ],
            zoom: 15,
            detectRetina: true,
            reuseTiles: true,
            tileSize: 256
        })

        // Open Street Map layer for our leaflet instance.
        var osmUrl='https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
        var osmAttrib='Map data © <a href="https://openstreetmap.org">OpenStreetMap</a> contributors';
        var osm = new L.TileLayer(osmUrl, {
            minZoom: 0,
            maxZoom: 18,
            attribution: osmAttrib
        });
        this.gMap.addLayer(osm)
```

**Comment by trusktr** [comment]
I'm setting up the map like this

```js

        this.gMap = new L.Map(document.getElementById('map'), {
            zoomControl: false,
            center: [
                Meteor.user().profile.location.latitude,
                Meteor.user().profile.location.longitude
            ],
            zoom: 15,
            detectRetina: true,
            reuseTiles: true,
            tileSize: 256
        })

        // Open Street Map layer for our leaflet instance.
        var osmUrl='https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
        var osmAttrib='Map data © <a href="https://openstreetmap.org">OpenStreetMap</a> contributors';
        var osm = new L.TileLayer(osmUrl, {
            minZoom: 0,
            maxZoom: 18,
            attribution: osmAttrib
        });
        this.gMap.addLayer(osm)
```

**Comment by IvanSanchez** [comment]
Try using Stamen's Toner instead, using `http://a.tile.stamen.com/toner/{z}/{x}/{y}.png`. Compare http://a.tile.stamen.com/toner/0/0/0@2x.png versus http://a.tile.stamen.com/toner/0/0/0.png

**Comment by mourner** [comment]
@trusktr oh, I think you put the option in the wrong place (it should be in TileLayer options, not Map).

**Comment by trusktr** [comment]
@mourner Aah, yep. Doh. Thanks. :}

@IvanSanchez interesting, those 2x map tiles. Thanks.
