### ISSUE TITLE
leaflet 1.0-beta: Click on layer triggers click on map

### ISSUE THREAD

**Issue by syldor** [Leaflet/Leaflet#3782]
When having one map with a GeoJSON layer with both click events listener, clicking on the layer will trigger the map click listener. It seems it was not the case previously, is it expected behavior ?

    var roads_layer = L.geoJSON();
    roads_layer.on({
      click: onRoadClick();
    });

    map.on({
      click: onMapClick();
    });

Click on roads_layer triggers both onRoadClick() and onMapClick();
This creates trouble when highlighting feature on click, and remove the highlight on map click.

**Comment by yohanboniface** [comment]
This is a known API change, you need to stop the event yourself in the layer listener if you want to prevent others to receive it.

```
roads_layer.on({
  click: function (e) {
      L.DomEvent.stop(e);
      …
  };
});
```
