### ISSUE TITLE
Feature Properties Coherence with geojson.in

### ISSUE THREAD

**Issue by gotjoshua** [Leaflet/Leaflet#3783]
Greetings,
In the process of getting geoJSON feature objects from geoJSON.io into leaflet, i realized that I needed to adapt the property names.
At geojson.io, they are referring to this
https://github.com/mapbox/simplestyle-spec/tree/master/1.1.0
as ["the closest & best-adopted GeoJSON has to a styling standard."](https://github.com/mapbox/geojson.io/issues/473#issuecomment-135438424)

Do you have a standard that you adopt for your layer styling properties?

I wonder if we could develop a coherence and/or flexibility framework for matching property names and styles?

thanks for your engagement!

**Comment by mourner** [comment]
No standard, you can use any standard you want. I think there's even a Leaflet plugin for that, check out the list.

**Comment by gotjoshua** [comment]
thanks for the quick reply!
what do you mean by:
>you can use any standard you want
?

if i set a layer style fill:#555 it doesn't work because leaflet uses fillColor
so the choice of fillColor over fill or any other name is not based on any standard?
