### ISSUE TITLE
catching GeoJson filter rejects

### ISSUE THREAD

**Issue by MuellerMatthew** [Leaflet/Leaflet#3784]
Good afternoon, I am thinking of submitting a small patch to alter the geojson layer functionality so a second layer can be passed when adding data to the layer to catch any geojson data which is rejected when a layer has a filter function.
Currently if the data is filtered out, it just gets discarded but it would be useful for testing purposes and when re-filtering large datasets if you can see both the pass and the failed data to both ensure that your filter is working properly, and so if the filter is changed, so you may only have to re-filter part of the data.    
 Is there any specific reason why this type of functionality would be a bad idea, or an existing alternative which might perform better?

**Comment by IvanSanchez** [comment]
I don't think it is a piece of functionality that would be of much use to most users, so I would say "make a plugin for it".

Also, it should be pretty trivial for a user to create two geoJSON layers, one of them with a negated filter function. Yes, runtime should be double, but there is no need to touch the core code.

**Comment by danzel** [comment]
plugin +1

**Comment by mourner** [comment]
Agreed.
