### ISSUE TITLE
Consistency between Circle and CircleMarker radiuses

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#3785]
The factory for `L.Circle` takes in a `radius` parameter, whereas `L.CircleMarker` takes in the options parameter with a `radius` option inside.

For consistency, it would be very nice to have both classes have the radius as an option (instead of a constructor parameter).

**Comment by yohanboniface** [comment]
I agree. With retrocompatibility in mind (`if (typeof options === "string")…`), this can be done within the 1.0 jump I think.

**Comment by yohanboniface** [comment]
Committed with 3924d49bcdd4d88099b0d9a3196ebcd29479a4f7
