### ISSUE TITLE
Pinch zoom animation

### ISSUE THREAD

**Issue by chronixlo** [Leaflet/Leaflet#3786]
Pinch zooming in 1.0 (on android at least) doesn't zoom "in real time" as it did in 0.7. It is currently very suffer-y to use without any visual feedback.

**Comment by mourner** [comment]
What do you mean? Can you make a video? Can you test on other browsers and devices?

**Comment by IvanSanchez** [comment]
Also, which version of Android (2, 3, 4, 5)? Which browser (Android stock web browser, Chrome, Firefox mobile, other)

**Comment by chronixlo** [comment]
Not a Leaflet issue, I have something conflicting here.

**Comment by chronixlo** [comment]
Or is it? Using a proj4 crs seems to cause this.

The issue is that pinch zooming doesn't update map position & zoom until touchend.

**Comment by IvanSanchez** [comment]
> Or is it? Using a proj4 crs seems to cause this.

In that case, please post a minimal jsfiddle (or any kind of public demo) so we can look at the issue.

**Comment by chronixlo** [comment]
Unfortunately I can't share the mapserver I'm using. The map also tries to load tiles out of bounds which didn't happen in 0.7 which I guess is a projection(/proj4leaflet) issue as well?

The pinch zoom bug occurs at least on Chrome and Firefox on Android 4.3.

**Comment by mourner** [comment]
@chronixlo are you using the 1.0-compatible version of Proj4Leaflet (in a branch)?

**Comment by perliedman** [comment]
@chronixlo it might be that you're running into this issue: https://github.com/kartena/Proj4Leaflet/pull/73

It's fixed in Proj4Leaflet for 0.7.3, but hasn't been ported to the branch that's compatible with 1.0.

I've opened https://github.com/kartena/Proj4Leaflet/issues/92 to address this.

**Comment by chronixlo** [comment]
@mourner yep

**Comment by IvanSanchez** [comment]
Since this seems to be a Proj4Leaflet issue, we can close this now.
