### ISSUE TITLE
SVG-Path without attributes

### ISSUE THREAD

**Issue by fab1an** [Leaflet/Leaflet#3789]
For performance reasons I would like to set only the classNames of the SVG-paths and skip all the "stroke-width" attributes etc.

Is that possible?

**Comment by IvanSanchez** [comment]
Is that possible?

[http://homepage.ntlworld.com./jonathan.deboynepollard/FGA/questions-with-yes-or-no-answers.html](Yes.)

Have you done any benchmark of the performance gains of doing so?

**Comment by fab1an** [comment]
Yes, but a year ago in an application which displays about 4000 svg-polygons. I have patched this behaviour in a version for myself and I would like to go back to upstream-leaflet.

**Comment by IvanSanchez** [comment]
> I would like to go back to upstream-leaflet.

That's what pull requests are for :-)

**Comment by IvanSanchez** [comment]
Let's make a reference to #2662.

Having thought a bit about the issue, it should be easy to just set `stroke` and `fill` to false, then let the `className` do its magic. Even do a small plugin for the SVG renderer which forces that. But doing so in a way compatible with Canvas can be insanely difficult.

**Comment by fab1an** [comment]
I'm closing this, I don't really need it anymore, found my performance-gains somewhere else.
