### ISSUE TITLE
Data not showed in replicated map.

### ISSUE THREAD

**Issue by Rajavelu** [Leaflet/Leaflet#3790]
Dear team,
Our data not showed in replicated maps(horizontally).
Also Map is draggable after reached bottom/top of the map, but shows empty page.
Kindly refer the following questions for more details

Refer:
https://help.openstreetmap.org/questions/44891/how-to-fit-world-map-in-full-screen
https://help.openstreetmap.org/questions/44204/markers-not-showed-in-multiple-maps

**Comment by yohanboniface** [comment]
Hi @Rajavelu and thanks for using Leaflet! This issue manager though is for Leaflet itself, not for requesting help about using Leaflet.

Hopefully you'll have help on help.osm.org, but you can also try the [Leaflet forum](https://groups.google.com/forum/#!forum/leaflet-js) for that.

**Comment by Rajavelu** [comment]
@yohanboniface : Thanks for your information.

I felt, "map shows empty page when reach top / bottom" is a leaflet issue, so only asked here.
