### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by SamMousa** [Leaflet/Leaflet#3792]
I know this has been discussed in #1903.

First I'll try to sum the facts / arguments as I understood them
1. Leaflet requires a build.
2. Checking in build artifacts into a development repo is an anti pattern.
3. Bower should support post install scripts to support building after download.

Other libraries work around this issue by creating a release repo, effectively only committing build artifcats to that repo and using github / git / bower as a distribution method.
This would make it:
1. Easy to push new releases, just add a line that pushes to the correct github to the build script.
2. Easy to use with bower.

Are there any reasons not to do this? Note that you already have several leaflet plugins that use bower, making it even more confusing!

The original issue is from 2013, so if Bower hasn't resolved it by now, it might be time to look at an alternative?

(Disclaimer: I am a PHP developer so all I want is an easy way to get this code into my project via fxp-composer-asset-plugin without worrying about building or executing javascript specific build tools).

**Comment by mourner** [comment]
This is done already.

**Comment by SamMousa** [comment]
Where is it located? I can't find it on bower.io.

**Comment by mourner** [comment]
Try `bower info leaflet` from the command line. 
1.0-beta1 specifically is bugged (no dist files) but that's a known issue that has been discussed already.
