### ISSUE TITLE
Feature Request: Option to scale map tiles

### ISSUE THREAD

**Issue by mk-pmb** [Leaflet/Leaflet#3793]
Hi, I'm trying to scale my map tiles up, independent of zoom, to more easily decipher tiny symbols on them. For now I use a CSS scale transform on the container, giving the same mouse coordinate problems as in #2795 .
Instead of diving into scale detection and related cross-browser issues, is there an option to actually scale the map tiles, or could you add one?
Another benefit of specific scaling for just the tiles would be to avoid messing with size and blurriness of markers, UI buttons etc.

**Comment by IvanSanchez** [comment]
Make the tiles larger on the browser. http://leafletjs.com/reference.html#tilelayer-tilesize

**Comment by mk-pmb** [comment]
Thanks for the quick reply!

I tried this with leaflet v0.5 and unfortunately it messed up calculations. For testing I place a marker on Brussels, Belgium [50.8465565 , 4.351697] and set zoom level 8. With the original tile size of 256, the tile filename for that position is `z8/x131/y85`, same as libOSM's prediction.

When I increase the tile size slightly (+1 = 257), the predicted tile filename stays the same, but markings on the tile show that `z8/x130/y85` is being displayed at the marker position, and the marker is shown about half a tile north-west of Brussels.

When I decrease the tile size slightly (-1 = 255), predicted file is the same again, but markings show `z8/x131/y86` and the marker is shown about half a tile south-east of Brussels.

I'll retry with the latest leaflet tomorrow if it's still worth a try by then.

**Comment by danzel** [comment]
@mk-pmb Make up a new issue with a reproducible test case on jsfiddle or similar and hopefully someone will be able to take a look at this, thanks.

**Comment by mk-pmb** [comment]
Since it turned out that
> http://leafletjs.com/reference.html#tilelayer-tilesize

is not a configuration option to
> Make the tiles larger on the browser.

but instead has to strictly correspond to the chosen tile naming scheme, could someone re-open or deny this feature request please?

**Comment by danzel** [comment]
Reopening to get some more comment

**Comment by mourner** [comment]
If you double the tile size, you can also use `zoomOffset` option to make up for the different numbers (either -1 or 1 should work, don't remember exactly).

**Comment by mk-pmb** [comment]
Works for me, thanks a lot!
A `zoomOffset` of `-1`, makes the map show tiles from z=7 in zoom level 8 in [my demo](http://mk-pmb.github.io/leaflet-js-demos/zoom-offset.html) (last box).
