### ISSUE TITLE
mouseover is not fired on nested HTML inside marker

### ISSUE THREAD

**Issue by bardt** [Leaflet/Leaflet#3797]
The example mentioned in this [issue](https://github.com/Leaflet/Leaflet/issues/3708) doesn't work properly in master for hovering markers with nested HTML. Expected behaviour is:
1. mouseover event on marker when mouse is entering it from the map
2. mouseout event as mouse moves from marker itself onto the nested HTML
3. another mouseover event fired by marker, which bubbles from the nested HTML

The second mouseover is not fired because of [this commit](https://github.com/Leaflet/Leaflet/commit/c1f21eb38f62b73977a8a7654297c4863ca439d3), preventing bubbling for hover events. 

That makes hovering markers with nested HTML unusable. Any ideas?

**Comment by yohanboniface** [comment]
Humm, is this issue different from https://github.com/Leaflet/Leaflet/issues/3708#issuecomment-127594835 ?

**Comment by bardt** [comment]
@yohanboniface this issue corresponds with first issue described in your comment, but I'm saying about broken events (mentioned by you as "the natural DOM behaviour") while mouse is moving from marker onto the nested HTML. As mouse enters nested HTML element, a new mouseover event is expected, but is absent. 

Should I better write a sample code to demonstrate it?

**Comment by yohanboniface** [comment]
> Should I better write a sample code to demonstrate it?

It wont hurt ;)

**Comment by bardt** [comment]
Here I use leaflet-1.0.0-b1 instead of current master http://jsfiddle.net/bLm6r3qp/1/

![demo](https://s3.amazonaws.com/f.cl.ly/items/441M111G1M0x0Q3X1Q3O/Screen%20Recording%202015-09-02%20at%2007.47%20PM.gif)

As you see, mouseover is fired 2 times while I hover the marker (first for marker div itself, second for nested img). If you run this code using current master, only one mouseover will be fired, followed with mouseout.

The reason I've found is commit I mentioned in issue description.

**Comment by yohanboniface** [comment]
If I understand your point, I'm not reproducing it with current master: http://jsfiddle.net/vp1x65oo/1/

**Comment by bardt** [comment]
Ok then, probably I misunderstood the expected behaviour and the whole "mouseover vs. mouseenter" discussion. But the question is still open. 

I added some code to your fiddle: http://jsfiddle.net/vp1x65oo/2/. What I want to achieve is showing something (tooltip for example) while marker is hovered. Obvious way to do so in earlier leaflet versions was listening to marker's mouseover and mouseout events. As long as `L.divIcon` is an official way of customizing markers appearance we need a fix or replacement for those events to act on the whole marker including nested HTML, don't we?

**Comment by yohanboniface** [comment]
> As long as L.divIcon is an official way of customizing markers appearance we need a fix or 
> replacement for those events to act on the whole marker including nested HTML, don't we?

I agree. I'll look into that.

**Comment by skalb** [comment]
I had this same issue, but resolved it (at least until an upstream fix) by removing pointer events on the nested elements.

```
.div-icon {
  pointer-events: none;
}
```
http://jsfiddle.net/skalb/vp1x65oo/3/

**Comment by bardt** [comment]
@skalb yeah, but I have to remind about browser support: http://caniuse.com/#feat=pointer-events
