### ISSUE TITLE
One-finger pan + two-finger zoom = broken vectors on stable

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#3798]
This is reproducible in the `stable` branch, at least with 0.7.3 and 0.7.5. Apparently 1.0 works fine.

Reproducible in both Chrome for Android and Safari on iPad.

* Put down one finger:

![img_20150902_174747](https://cloud.githubusercontent.com/assets/1125786/9636430/91d80cba-519b-11e5-832f-634c479c120d.jpg)

* Pan the map:

![img_20150902_174750](https://cloud.githubusercontent.com/assets/1125786/9636429/91d74050-519b-11e5-9154-137cc6f6cee4.jpg)

* Put down a second finger:

![img_20150902_174753](https://cloud.githubusercontent.com/assets/1125786/9636428/91d387ee-519b-11e5-94b2-13f4a0b7bda2.jpg)

* Zoom and watch the vectors break:

![img_20150902_174757](https://cloud.githubusercontent.com/assets/1125786/9636427/91d1c49a-519b-11e5-95a9-1d1869519383.jpg)

I do not know if this is worth a backport.

**Comment by mourner** [comment]
Probably not worth the hassle if the fix is not super-simple.

**Comment by kaynz** [comment]
Breaks on 1.0 following your guide too.

**Comment by IvanSanchez** [comment]
@kaynz That's #3814, a different issue.

**Comment by IvanSanchez** [comment]
Closing down, as the fix for 0.7.x is not trivial, and the 1.0.0 is looming.

**Comment by perliedman** [comment]
@ikhudo I tried this on Leaflet's example page (http://leafletjs.com/examples/quick-start/), and can not reproduce what you're saying.

I you believe this is an issue in Leaflet, could you please open a new issue together with a test case reproducing the problem?

**Comment by ikhudo** [comment]
![leaflet 2](https://user-images.githubusercontent.com/35076442/37651406-5380f18c-2c38-11e8-8b4e-86fa22baf85f.gif)

it is reproducible when using canvas or svg markers

**Comment by perliedman** [comment]
Again, if you believe this is an issue with Leaflet, can you please _open a new issue_, together with an example reproducing the issue. That is, it's unfortunately impossible for me to tell what is happening in the screenshot you posted above. For me, this is not reproducible, at least not with the standard examples, so we need some more information to able to do anything about this.

As this is most likely not the same issue that was reported here originally, please open a new issue.

**Comment by ikhudo** [comment]
ok, thank you, i'll create new issue with jsfiddle.
