### ISSUE TITLE
Lasso Selection - Leafleet.

### ISSUE THREAD

**Issue by vigneshncc** [Leaflet/Leaflet#3799]
I am trying to build a map with lasso selection as shown in this video (https://goo.gl/iLc42c).  I'm unable to find any reference in web to do the same.  Kindly help me with some reference / solution.

**Comment by mourner** [comment]
Hey, thanks for using Leaflet! However, this is a place to report Leaflet issues, not to request support for your app.  Please try asking on the <a href="https://groups.google.com/forum/#!forum/leaflet-js">Leaflet forum</a> — you are more likely to find help there.

**Comment by IvanSanchez** [comment]
Also, http://leafletjs.com/plugins.html#areaoverlay-selection

**Comment by vigneshncc** [comment]
@mourner Sorry. Here it is, https://groups.google.com/forum/#!topic/leaflet-js/0PLtwzO9jBU  @IvanSanchez Lets continue of discussion in forum.

**Comment by kabudahab** [comment]
Try this plug-in: https://github.com/ImperialCollegeLondon/leaflet-lassoselect
