### ISSUE TITLE
Empty Polyline creates error

### ISSUE THREAD

**Issue by MuellerMatthew** [Leaflet/Leaflet#3802]
Right now when you create a polyline you have to add data to it, you cannot create an empty Polyline.  I just tested this with the latest dev version, and it is still crashing.

**Comment by yohanboniface** [comment]
This should work:
```
L.polyline([]);
```

**Comment by IvanSanchez** [comment]
@yohanboniface Yes, it does: https://playground-leaflet.rhcloud.com/ros/1/edit?html,output

**Comment by IvanSanchez** [comment]
@MuellerMatthew Please note that the first parameter to `L.polyline()` is **not** optional according to the docs. So, an undefined value (which is different from an empty array) is expected to not work.
