### ISSUE TITLE
Make Map.getScaleZoom aware of CRS

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#3808]
Right now `getScaleZoom` is using `log2`, whereas `getZoomScale` uses `crs.scale()`.

It looks like we should edit `getScaleZoom` to use CRSs also. And make unit tests.

This looks like an easy task, so if there's any non-core-developer who wants to give it a shot, I'd love to see it happen :-)

**Comment by perliedman** [comment]
I think this is a duplicate of #2990, but possibly more clearly stated :)

**Comment by mourner** [comment]
Yes, let's close as duplicate.
