### ISSUE TITLE
Cannot bring overlapped popups opened with Map#addLayer on top

### ISSUE THREAD

**Issue by dijam** [Leaflet/Leaflet#3813]
When you have multiple popups opened with Map#addLayer and some of them overlapped with others, it is not possible to bring the one behind others front.
So we have part of popup A on top of popup B. It would be good when you click on B, it comes froward and popup A goes behind it.
Any thought?

**Comment by IvanSanchez** [comment]
Can you please link to an example where this is reproducible? jsfiddle, codepen, or the like?

**Comment by dijam** [comment]
Take a look at this: https://jsfiddle.net/u4xzasuu/
I think it would be good if we could bring the first popup in front of the other one by clicking on it.

**Comment by mourner** [comment]
We should probably add something like `popup.bringToFront` (similar to other layers) to address this.
