### ISSUE TITLE
Marker drifts when tileLayer's tileSize !== 256

### ISSUE THREAD

**Issue by mk-pmb** [Leaflet/Leaflet#3817]
As @danzel requested in #3793 , here's a [demo page](http://mk-pmb.github.io/leaflet-js-demos/tilesize.html) ([repo](https://github.com/mk-pmb/leaflet-js-demos)) for how my marker on Brussels drifts due to miscalculated tile URLs. The yellow circle is part of the image for tile `131:85@8` and always stays in its lower left corner, where I'd expect the marker.

I'm testing with Firefox 40.0.3 on Ubuntu 12.04.5 LTS.

**Comment by IvanSanchez** [comment]
I only see expected behaviour - bigger tiles mean less tiles needed to cover the same pixel coordinates from the grid's origin pixel.

I think I understand what you meant with #3793. Have you tried fractional zoom, or the `zoomOffset` option of a tilelayer?

**Comment by mk-pmb** [comment]
Thanks for checking! I've made a [screenshot](https://github.com/mk-pmb/leaflet-js-demos/blob/screenshots/marker_drift_3817_firefox_40.jpeg) in case it helps, and will try fractional zoom asap.

**Comment by mk-pmb** [comment]
I tried to investigate the calculation further, and I realized I don't really understand how the grid origin factors into this, as the marker position is configured in lat/lon, not pixels.

As I understand the tile number algorithm, the length of the equator always is 2^zoom tiles, independent of tile size. (in demo, z=8 => n=256)
The longitude is converted to a fraction of equator length (in demo: 4.351697 ° east ≈ 0.512088 equator lengths), and multiplied by equator's length in tiles to get a tile position including the fraction. (in demo: 0.512088 eql * 256 tiles = tile # 131.094528 => tile x coordinate = 131, marker position = 0.094528 tiles from left. So actually I should have placed the yellow circle's `cx` at 9.4528%, not 10%.)

So no matter the tile size, the marker should always hover over a tile with x=131.

Only when I want to convert the tile number fraction into pixels, I need the tile size:
0.094528 * 256 = 24.199168 px from left --> matches screenshot.
0.094528 * 255 = 24.10464  px from left --> screenshot: (left edge of tile #131) + 155 px
0.094528 * 257 = 24.293696 px from left --> screenshot: (left edge of tile #131) - 107 px

Is that math something that could really differ by browsers?

**Comment by IvanSanchez** [comment]
> ... how the grid origin factors into this, as the marker position is configured in lat/lon, not pixels.

Look at the code for `L.GridLayer._getTiledPixelBounds()`. Note that `map.project()` will give you the pixel coordinates for a latlng and zoom level.


> The longitude is converted to a fraction of equator length [...] and multiplied by equator's length in tiles to get a tile position

You're wrong. Pixel coordinates are calculated for the map bounds, then those pixel coordinates are divided by the tile size. Look at the code for `L.GridLayer._pxBoundsToTileRange()`.

**Comment by mk-pmb** [comment]
Thanks for the clarification. Do you see any chance Leaflet might add a compatibility mode for OpenStreetMap's [Slippy Map naming scheme](http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames) (sections "X and Y" + "Derivation of tile names"), or does anyone know a compatible project with most nice features of Leaflet?

**Comment by IvanSanchez** [comment]
What do you mean by "compatibility mode"? Leaflet tile scheme matches that of OSM perfectly.

**Comment by mk-pmb** [comment]
Then I don't understand how a marker placed on [50.8465565, 4.351697] could ever end up on a tile with x !== 131. Is there a flaw in my calculations? The formulae on OSM wiki don't factor in any tile size, as they operate on tiles as their length units, not pixels.

**Comment by IvanSanchez** [comment]
> I don't understand how a marker placed on [50.8465565, 4.351697] could ever end up on a tile with x !== 131.

Because in Leaflet, the calculations for pixel coordinates remain the same, no matter what the tile size is. This helps position everything (think markers, vectors) easily.

So, calculate the pixel coords for your point with `map.project`. Divide by 256, and you'll get 131. Divide by something else, and you'll get something else.

**Comment by mk-pmb** [comment]
I can't help but see a direct contradiction.

> Leaflet tile scheme matches that of OSM perfectly.

I've linked to the Slippy Map tile naming description on OSM wiki, and I demonstrated it step-by-step with the example numbers from my demo page. That's why I asked about a flaw in my calculation, but since it matches for 256px, I tend to consider them sound.

> Because in Leaflet, the calculations for pixel coordinates remain the same, no matter what the tile size is.

Since the X and Y of the Slippy Map naming scheme are independent of tile size, I conclude that pixel coordinates would have to adapt when tile size changes. This behavior would be the compatibility mode I mentioned.

The Slippy Map page gives constant numbers of tiles in its [section "Zoom levels"](http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#Zoom_levels).  It says that on zoom level 2 you always need 4x4 tiles, so in OSM Slippy Map compatibility mode, the equator would always be `(4*tileSize)` px wide. Its far east end, would be ot the `(4*tileSize)`-th pixel, so if Leaflet's pixel coordinates remain the same when tileSize goes up, its default mode is not compatible.

In suggested OSM Slippy Map compatibility mode, tile names' x/y would be compatible with the [JavaScript code examples](http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#ECMAScript_.28JavaScript.2FActionScript.2C_etc..29) given on Slippy Map page, which my Firefox calculates as:
```javascript
var zoom = 8, lat = 50.8465565, lon = 4.351697,
  x = long2tile(lon,zoom), y = lat2tile(lat,zoom);
console.log([x, y]);    // [ 131, 85 ]
```

**Comment by IvanSanchez** [comment]
Overload `L.GridLayer._pxBoundsToTileRange()` so it unscales everything by 256 instead.

Alternatively, change the size of the world pixel bounds by using a CRS with a different [CRS-coordinates-to-pixel-coordinates scale function](https://github.com/Leaflet/Leaflet/blob/master/src/geo/crs/CRS.js#L34).

(And, please, try to read through and understand Leaflet's code instead of pushing the OSM Slippy Tilenames as The One True Way To Do Things. Leaflet needs to have support for stuff other than EPSG:3857, and right now it's quite good, and it's not going to go away).

**Comment by mk-pmb** [comment]
> instead of pushing the OSM Slippy Tilenames as The One True Way To Do Things

Sorry, I never intended to push OSM standards onto anyone. I just fell for the similarity, and for the OSM tiles in the Leaflet tutorials, laziy searching the web for "OpenStreetMap tile names".
As soon as you clarified that, I switched to asking for a mere compatibility mode.

My later comparison wasn't meant to change Leaflet's default mode either, but just to resolve my confusion about your statement
> Leaflet tile scheme matches that of OSM perfectly.
Also, to be fair, if you had been aware that I'd have to overload a coordinate transform function in addition to configuring the tile size, you could really have told me in your first reply on #3793 .

That said, thank you for showing me where to start implementing an OSM compat mode if I decide to tackle it myself. Should I open a feature request ticket for original Leaflet in the meantime, or wait until I have a PR? (If ever… because I admit I'll first search for other, already OSM-compatible projects before I'll try to read through and understand Leaflet's code.)

**Comment by IvanSanchez** [comment]
I'm sorry I came out strong. I didn't have the best day to discuss this kind of stuff. :-(

> [...] start implementing an OSM compat mode if I decide to tackle it myself. Should I open a feature request ticket for original Leaflet in the meantime, or wait until I have a PR?

The usual thing we say for features that cover specific cases: make a plugin for it.

**Comment by mk-pmb** [comment]
No problem, and good luck for better next days! :-)
Maybe I can at least make a PR to clarify the documentation of tileLayer's tileSize, but don't hesitate if you can do it earlier.
