### ISSUE TITLE
Leaflet confused about its default marker icon URL

### ISSUE THREAD

**Issue by mk-pmb** [Leaflet/Leaflet#3818]
On my [demo page](http://mk-pmb.github.io/leaflet-js-demos/default-marker-icon-src.html) ([repo](https://github.com/mk-pmb/leaflet-js-demos)), the default marker image is broken. Its image URL contains `/404/prepare-js.cgi?` which leads me to believe that Leaflet was confused about its script URL.
In case it helps, I demonstrated my favorite way to detect a script's src URL when loaded into a website.

I'm testing with Firefox 40.0.3 on Ubuntu 12.04.5 LTS.

**Comment by mourner** [comment]
We can't possibly work around confusing URLs like that. I think we should leave that for developers to handle, setting `L.Icon.Default.imagePath` manually.

**Comment by danzel** [comment]
Our code looks for a script tag with a (possibly versioned) leaflet.js file in it.
https://github.com/Leaflet/Leaflet/blob/master/src/layer/marker/Icon.Default.js

@mk-pmb has this, finding the last script tag (at script load time?)
https://github.com/mk-pmb/leaflet-js-demos/blob/gh-pages/lib_demos.js#L8-L11
Google suggests this might be a good way to do it: http://stackoverflow.com/questions/2976651/javascript-how-do-i-get-the-url-of-script-being-called

Maybe we should grab the last script tag that matches instead? Looks like it might be more reliable. There would still be edge cases but yeah...

**Comment by mk-pmb** [comment]
> finding the last script tag (at script load time?)

Yes, detecting it at script load time is the crux. When loading it synchronously, it will act immediately upon the DOM of the partially loaded page. The only confusion problem I know of would be when the script tag is generated by another script and inserted before existing script tags. However, most script loaders I encountered so far just `appendChild()` to `<body>` since it's easier than `insertBefore()`.
