### ISSUE TITLE
Map box tiles are displaying empty if i change the width of the map 

### ISSUE THREAD

**Issue by prudvi** [Leaflet/Leaflet#3820]
Hi,

I am using mapbox and leafletJs.
In my cases there are 2 cases the map will render tiles .
Case 1: if left navigation pane is bigger, then the map rendering will be done very fine and here i m attaching the image for this case
Case 2: if i changed my left navigation pane, then the map rendering will increase the size and renders right corner of the map will display empty tiles.

Here i am attaching the images of my 2 issues

as per case2 : If map size increases, why map tiles are not displaying?Please guide on this
 
![case1](https://cloud.githubusercontent.com/assets/5299636/9756223/19ffa710-56f6-11e5-90d5-85e7cd8e14ce.png)
![case2](https://cloud.githubusercontent.com/assets/5299636/9756224/1a0619ba-56f6-11e5-945e-4afeee2fd01a.png)

**Comment by yohanboniface** [comment]
Call `map.invalidateSize()` after changing the container size.

**Comment by kiran15** [comment]
i also have same problem still i am not get any solution (map.invalidateSize()  its not working) is this css issues or map issues i am not getting please guide us

**Comment by yohanboniface** [comment]
Please use [Leaflet forum](https://groups.google.com/forum/#!forum/leaflet-js) to request for help on using Leaflet. This is an issue tracker for Leaflet code base itself.
