### ISSUE TITLE
Path mouse event is fired without a map associated to it

### ISSUE THREAD

**Issue by ageblade** [Leaflet/Leaflet#3827]
I receive the following error:
``
Uncaught TypeError: Cannot read property 'mouseEventToContainerPoint' of null
L.Path.L.Path.extend._fireMouseEvent	@	leaflet-src.js:4746
L.DomEvent.addListener.handler	@	leaflet-src.js:6403
``

This happens in L.Path.L.Path.extend._fireMouseEvent() as for some reason this._map is null.
However i checked when this event is initialized and the map exists in its context.

Anyone experienced this issue ?  I'm using leaflet 0.7.5

**Comment by IvanSanchez** [comment]
Can you link to an (minimal) example where we can reproduce this?

**Comment by yohanboniface** [comment]
I wonder if this is not the same as #3829

**Comment by ageblade** [comment]
This is a duplicate as @yohanboniface stated.
Closing this one
