### ISSUE TITLE
Zoom in further over tiles layer

### ISSUE THREAD

**Issue by asotoopensky** [Leaflet/Leaflet#3834]
Hi, i'm using leaflet 0.7.3 to render some tile layers over a map via WMTS. When I zoom in until level 20, the layer disappears and shows up Google Map.
According to Leaflet Documentation this problem is solved setting a value to **maxNativeZoom** property which prevents more server requests after level 18 but I tried to increment the **maxZoom** value  in order to zoom in to layer and didn't work.

I want to zoom in further with out losing the tile layers, i'm ok if the layer gets some blur.

The problem is similar to this:
http://jsfiddle.net/gwacker/3kWRy/ (The layer disappears when zooming in)

The Layer options:
```
{
	tiled: true,
	format: 'image/png',
	transparent: true,
	tileSize:256,
	maxZoom: 20,
	maxNativeZoom: 18
}
```

**Comment by IvanSanchez** [comment]
Are you using any plugin for the WMTS layer?

**Comment by asotoopensky** [comment]
Hi @IvanSanchez,

Yes, i'm using Leaflet Boundary Canvas.
https://github.com/aparshin/leaflet-boundary-canvas

**Comment by IvanSanchez** [comment]
It might be a plugin issue. Can you try removing that plugin and see if the error still happens?

**Comment by markstuart** [comment]
We have found the same problem on 0.7.3 @asotoopensky, `maxNativeZoom` seems to be being ignored causing the scaling not to occur. Upgrading to 0.7.5 has fixed the issue for us. We are not using any plugins, just standard tile server requests.

**Comment by yohanboniface** [comment]
Sounds like fixed in latest stable, yep: https://github.com/Leaflet/Leaflet/blob/3ff1b65b6453cb859f358a96f4034e0afff62ccd/CHANGELOG.md#074-september-1-2015

**Comment by asotoopensky** [comment]
Hi all,
I'm upgrading to Leaflet 1.0 Beta and maxNativeZoom now is working with the plugin i'm using. However, i'm having some compatibility problems with new version,
Thanks
