### ISSUE TITLE
Paths off screen are not updated when moved into screen

### ISSUE THREAD

**Issue by yohanboniface** [Leaflet/Leaflet#3836]
![polygon-bug](https://cloud.githubusercontent.com/assets/146023/9829838/acbbc5e4-5916-11e5-9133-a59ac58dace6.gif)

According to `git bisect`, the guilty commit is 61c07bd3e3d9a5a2bb4855ba81e1f368cc80090b

And indeed when I revert it it works back as expected. Swimming pool time, but I'll try to have a shot at investigating today. :)

**Comment by mourner** [comment]
Nope, vectors are still pretty much broken in master :( cc @IvanSanchez

**Comment by IvanSanchez** [comment]
Yeah, looks like a problem related to the order the events are being registered and fired. I think `Renderer._draw` is being called *before* `Renderer._update` somehow. Need to check later.

**Comment by yohanboniface** [comment]
> Nope, vectors are still pretty much broken in master :(

Can you be a bit more specific? Seems to work for me **on branch rendered-update**.

**Comment by IvanSanchez** [comment]
@yohanboniface In current `master`, canvas layers disappear when panning, and SVG vectors use the bbox from the last map pan when panning several times in sequence.

**Comment by yohanboniface** [comment]
But `rendered-update` branch is supposed to fix that I think.

**Comment by yohanboniface** [comment]
Well, included in `canvas-redrawbounds` actually now.

**Comment by IvanSanchez** [comment]
@yohanboniface Is there a PR for those branches?

**Comment by yohanboniface** [comment]
#3840 :)

**Comment by IvanSanchez** [comment]
@yohanboniface So is this bug reproducible when using `canvas-redrawbounds`? :-)

**Comment by yohanboniface** [comment]
> So is this bug reproducible when using canvas-redrawbounds? :-)

Nope

**Comment by mourner** [comment]
Right, I remember now! It was a part of a bigger PR which I wanted to merge but it has problems, so merged just this fix instead.
