### ISSUE TITLE
How to extend pixelBounds?

### ISSUE THREAD

**Issue by Wilzi** [Leaflet/Leaflet#3838]
Hi!
I would like to extend the view to render more tiles because my map is 3D rotated on the X axis.
This piece of code works well in version < 1:
```
var getPxBounds = map.getPixelBounds;
map.getPixelBounds = function() {
   var bounds = getPxBounds.call(this);
   // ... extend the bounds
   var value = 250;
   bounds.min.x = bounds.min.x - value;
   bounds.min.y = bounds.min.y - value;
   bounds.max.x = bounds.max.x + value;
   bounds.max.y = bounds.max.y + value;
   return bounds;
};
```
Could you please help me how to do the same in version 1.0.0-b1?
Here is two jsbins to reproduce the problem:

version 0.7.5
http://jsbin.com/pubanovuqi/edit?js,output

version leaflet-1.0.0-b1
http://jsbin.com/fuwicuxobe/edit?js,output

**Comment by perliedman** [comment]
In 1.0, you can accomplish the same by hacking into GridLayer's `_getTiledPixelBounds` method.

I updated your jsbin to do this: http://jsbin.com/yogakagumi/edit?js,output

**Comment by yohanboniface** [comment]
Answered by @perliedman, so closing.

**Comment by Wilzi** [comment]
Thank you very much @perliedman! :)
