### ISSUE TITLE
Regression: layers added to LayerGroups don't show

### ISSUE THREAD

**Issue by Ugoku** [Leaflet/Leaflet#3843]
This might be a bug, or a feature. It certainly is a regression in 1.0.0 from 0.7.3 so I thought I'd share.

Imagine you have two layer groups:
```
var group1 = new L.LayerGroup(),
    group2 = new L.LayerGroup();
```

You add several (GeoJSON) layers to both: `group1.addLayer(layer);` and you add the layer groups to the map: `map.addLayer(group1);`

So far, so good. The layers show up just fine. Next up, we move a layer from one group to the other:
```
group1.removeLayer(group1.getLayerId(layer));
group2.addLayer(layer);
```

In 0.7.3, `layer` would show up on the map just fine. However, not in 1.0.0 (checked in both beta1 as current master). In 1.0.0 you have remove and add the layer to be visible again:
```
map.removeLayer(group2);
map.addLayer(group2);
```

Is this a bug or a feature?

**Comment by yohanboniface** [comment]
Sounds like a bug.
Can you setup a jsfiddle to demonstrate the issue? http://playground-leaflet.rhcloud.com/ for example.
Thanks!

**Comment by Ugoku** [comment]
Thanks for reminding me to make a test case, that got me to the problem quickly:
http://playground-leaflet.rhcloud.com/sil/edit?html,output

My code had
```
      group2.addLayer(firstLayer);
      group1.removeLayer(layerID);
```
which failed. Switching the statements (remove from group1 first, then add it to group2) works just fine.

**Comment by yohanboniface** [comment]
Yeah, you can't have a given layer in two groups at the same time.

**Comment by Ugoku** [comment]
Made a mistake in my previous comment, I will investigate this further.
