### ISSUE TITLE
custom layer control

### ISSUE THREAD

**Issue by xaadim** [Leaflet/Leaflet#3846]
Hello,

I work in a project and I want to create a control layer manually. I want to create custom checkbox I want to make manipulating haslayer removelayer and when you click on the checkbox.

I would not load all my layers from JSON (they are heavy) then I would like that when you click the checkbox, it uses the server to add a layer on the map so on.

Thank you
![sans titre](https://cloud.githubusercontent.com/assets/12086380/9901523/76d94a0a-5c68-11e5-9d72-2b7fc3b3f12b.png)

**Comment by xaadim** [comment]
@bmcbride

**Comment by yohanboniface** [comment]
Same as #3847 
See also plugins that may suit your needs: http://leafletjs.com/plugins.html#layer-switching-controls

**Comment by xaadim** [comment]
Thank you @yohanboniface
