### ISSUE TITLE
Keep state checkbox layer control

### ISSUE THREAD

**Issue by xaadim** [Leaflet/Leaflet#3847]
Hello,

Is it possible to remember the layers in the layer control checked when changing page, for example?

Thank you

**Comment by xaadim** [comment]
@bmcbride

**Comment by yohanboniface** [comment]
hi @xaadim,

Thank you for using Leaflet. This issues tracker though is a place to discuss the development of Leaflet itself. Not to ask for help or how to use the library. For this, please use the forum:

https://groups.google.com/forum/#!forum/leaflet-js

Thanks!
