### ISSUE TITLE
1.0beta1 - RangeError on panning if no panning possible due to maxbounds

### ISSUE THREAD

**Issue by WGPSenshi** [Leaflet/Leaflet#3848]
If using a CRS.Simple, panning can completely break if the maxbounds are set so no panning is possible.
If I use the 0.75 version, everything works: You can still pan, with the view "bouncing" back on release. However, I don't want to use 0.75 because of other issues (black jpg tiles, for one). In 1.0, no drag happens at all after a few tries, and huge error stack are immediately shown in the console.

This happens to me on current Chrome (and Opera 31), while Edge and IE11 are not troubled by this (at least they don't complain with errors). Not sure if Firefox is affected.

```
Uncaught RangeError: Maximum call stack size exceeded
L.Evented.L.Class.extend.fire @ leaflet-src.js:476
L.Map.include.panBy @ leaflet-src.js:9141
L.Map.include._tryAnimatedPan @ leaflet-src.js:9194
L.Map.include.setView @ leaflet-src.js:9121
L.Map.L.Evented.extend.panTo @ leaflet-src.js:1760
L.Map.L.Evented.extend.panInsideBounds @ leaflet-src.js:1817
L.Map.L.Evented.extend._panInsideMaxBounds @ leaflet-src.js:2223
L.Evented.L.Class.extend.fire @ leaflet-src.js:488
L.Map.include.panBy @ leaflet-src.js:9141
L.Map.include._tryAnimatedPan @ leaflet-src.js:9194
L.Map.include.setView @ leaflet-src.js:9121
L.Map.L.Evented.extend.panTo @ leaflet-src.js:1760
L.Map.L.Evented.extend.panInsideBounds @ leaflet-src.js:1817
L.Map.L.Evented.extend._panInsideMaxBounds @ leaflet-src.js:2223
...
repeats a gazillion times
...
```

However, sometimes I also get a different error. Seems to be random if the one below or above shows up:
```
Uncaught RangeError: Maximum call stack size exceeded L.LatLng @ leaflet-src.js:1171

L.LatLngBounds.getSouthEast @ leaflet-src.js:1335
L.Map.L.Evented.extend._getBoundsOffset @ leaflet-src.js:2422
L.Map.L.Evented.extend._limitCenter @ leaflet-src.js:2404
L.Map.include.setView @ leaflet-src.js:9106
L.Map.L.Evented.extend.panTo @ leaflet-src.js:1760
L.Map.L.Evented.extend.panInsideBounds @ leaflet-src.js:1817
L.Map.L.Evented.extend._panInsideMaxBounds @ leaflet-src.js:2223
L.Evented.L.Class.extend.fire @ leaflet-src.js:488
L.Map.include.panBy @ leaflet-src.js:9141
L.Map.include._tryAnimatedPan @ leaflet-src.js:9194
L.Map.include.setView @ leaflet-src.js:9121
L.Map.L.Evented.extend.panTo @ leaflet-src.js:1760
L.Map.L.Evented.extend.panInsideBounds @ leaflet-src.js:1817
L.Map.L.Evented.extend._panInsideMaxBounds @ leaflet-src.js:2223
...
repeats a gazillion times
...
```

This error appears once, twice, or sometimes even more, but after usually 5-10 times, panning will completely break: Even if you zoom in again, where panning should be possible, it will no longer work and the view will be fixed. Other map actions still work.

You can replicate it yourself right now by visiting http://tournament.realitymod.com/mapviewer/
Open your browser's console.
Click on one of the maps in the gallery.
Note: The map's maxbounds are set to image dimensions on load, so you should not be able to pan "into the black".
Zoom out once the map is opened.
Try panning. Errors should show up.

Someone has an idea?

**Comment by yohanboniface** [comment]
Can you reduce to a simple test case with http://playground-leaflet.rhcloud.com/ ?

**Comment by WGPSenshi** [comment]
Can't use that playground, because I get 

    Uncaught ReferenceError: L is not defined
    GET https://cdn.leafletjs.com/leaflet-1.0.0-b1/leaflet.css net::ERR_INSECURE_RESPONSE
    GET https://cdn.leafletjs.com/leaflet-1.0.0-b1/leaflet.js net::ERR_INSECURE_RESPONSE


Using jsfiddle I can reproduce the error with this barebone example:
http://jsfiddle.net/mdmmdsjw/3/

**Comment by IvanSanchez** [comment]
@WGPSenshi The error is caused by HTTPS in the `.js` files, you can get around it by not using HTTPS to load them.

**Comment by WGPSenshi** [comment]
What? You probably mean the INSECURE_RESPONSE. I don't care about that, tbh, that was just a hint for @yohanboniface.

The actual issue and steps to reproduce (RangeError) are shown in the jsfiddle I linked in previous post.

**Comment by yohanboniface** [comment]
Unable to reproduce with the JSFiddle provided, neither with Firefox 41, Chromium 45.0.2454.85 Ubuntu 15.04 (64-bit) nor Chrome 45.0.2454.101 (64-bit).

@WGPSenshi can you try with latest master, just to be sure? You should be able to do that easily with http://playground-leaflet.rhcloud.com/ choosing "latest development version" in the least. Thanks!

**Comment by yohanboniface** [comment]
I think I've been able to reproduce y chance using `debug/map/max-bounds-bouncy.html` debug page.

**Comment by WGPSenshi** [comment]
Sorry for the late reply. I tackled this issue anew, and it seems something changed, probably because I messed up during my initial diagnosis attempts.

For me, the craziness seems to show up only on the master branch, NOT on 1.0 beta1.

http://playground-leaflet.rhcloud.com/diy/3/edit?html,css,js,output

I can reproduce using above playground. If I change the exact same palyground to use 1.0 beta1, the error no longer occurs.

How to reproduce (fairly reliable):
Zoom out as far as you can (so the full map extent is visible).
Then start panning multiple times in rapid succession with some momentum so the view doesn't have time to bounce back fully). Do 5 to 10 such quick "fling" pan movements, then once you stop dragging and the view has completely finished "bouncing" back, script errors show up. The number of script errors depends on the drag clicks you performed previously:
If you start new dragging operations before the bounce-back has fully completed, the "maximum call stack size exceeded" error will not show up until you stop starting new pan operations and let it fully bounce back. At this time, all errors will show in quick succession. E.g. if you have dragged five times without letting it reset, five errors will show up once you let the view settle.
Once you are at this stage, every single future pan operation will result in a new "stack size exceeded" error message.

If you gather up a lot of errors by doing ~20 pan operations before allowing it to bounce back, you get a noticeable seize-up before the error shows up (also pointing at an infinite loop falling apart).

The one thing I can no longer reproduce is the "breaking of the panning" after a couple of errors. So better disregard that for now. Might be it was a particular issue with the master branch version I was using back then and was "accidentally" fixed by then.

**Comment by yohanboniface** [comment]
So, when adding maxBounds to the map, we start listening to `moveend` event, and, when fired, trigger a `_panInsideMaxBounds`, which ends by triggering a `setView`, and thus a `moveend`. And again. And again… ;)

We need a way not to loop again when the map center is unchanged, but we [do need](https://github.com/Leaflet/Leaflet/issues/3655) to always fire a `moveend` as soon as `setView` is called.

What about adding the offset to the `moveend` event payload, so it can be checked by who listens to the event in order to decide whether this `moveend` is relevant or not for its purpose?
