### ISSUE TITLE
Country labels over color layer in Map

### ISSUE THREAD

**Issue by ytzvan** [Leaflet/Leaflet#3850]
Hello, I've a map similar to this: http://leafletjs.com/examples/choropleth-example.html, but I want the states label be over the color layer. It seems to me they're above the color, but I want over it instead. I'm using mapbox with leaflet. 
Any thoughts ?

**Comment by IvanSanchez** [comment]
Github is **not** the place to ask question about how to use Leaflet, there is a forum for that.

Make sure you're using the right map panes and check your `zIndex`es.
