### ISSUE TITLE
Partial zoom

### ISSUE THREAD

**Issue by dtruel** [Leaflet/Leaflet#3852]
Hello,

We are using leaflet in an application, and my boss demands that I find a way to implement partial zoom - say in .2 increments instead of 1.  I googled around trying to find a way, but the best I found was a comment in 2012, where Vladimir, a maintainer said that it was too much work. That is not really an option for me, as my boss says that a big client demands this.

https://leaflet.uservoice.com/forums/150880-ideas-and-suggestions-for-leaflet/suggestions/2839764-continuous-fluid-zoom

I have looked through the source.  Does anybody have any suggestions on where to start?  If I get it figured out I may be able to submit a pr.

THANKS!

**Comment by mourner** [comment]
Fractional zoom is already supported in beta1, but there are further improvements coming soon — see https://github.com/Leaflet/Leaflet/pull/3523

**Comment by dtruel** [comment]
Hallelujah!  Thanks a million!
