### ISSUE TITLE
Firing contextmenu outside of map on long touch

### ISSUE THREAD

**Issue by chronixlo** [Leaflet/Leaflet#3854]
Put some real effort in this fiddle: http://jsfiddle.net/4ohyjLpg/

Doing a touch long press fires the contextmenu everywhere.

**Comment by mourner** [comment]
Your JSFiddle doesn't work, could you update it to be a valid test case with a Leaflet map? Also, please provide details on browser/device/operating system and versions of Leaflet that are affected.

**Comment by chronixlo** [comment]
A leaflet map doesn't have to be initialized for this, just need the script loaded.

Reproducible on Chrome 45 on win7 with chrome's touch emulation.

Happens on Leaflet home page demo too so 0.7 and 1.0 both.

**Comment by mourner** [comment]
Oh wow. OK, will look into it.

**Comment by jieter** [comment]
Isn't this just a touch emulation quirk? On mobile chrome it just selects text when long-pressing outside the map. Firefox has the same behaviour though.

**Comment by yohanboniface** [comment]
I can't reproduce neither on Ubuntu Touch browser nor on Android Chrome. I'm tempted to say like @jieter

**Comment by yohanboniface** [comment]
Actually, this seems to be the expected behaviour on Chrome device emulator, whatever Leaflet is loaded or not: https://code.google.com/p/chromium/issues/detail?id=395352#c3
