### ISSUE TITLE
CSS Validation trouble

### ISSUE THREAD

**Issue by Virtakuono** [Leaflet/Leaflet#3855]
I am having a hard time modifying the leaflet.css into a shape that I can pass through the W3C validator: https://jigsaw.w3.org/css-validator/validator?uri=http%3A%2F%2Frawgit.com%2FLeaflet%2FLeaflet%2Fmaster%2Fdist%2Fleaflet.css&profile=css3&usermedium=all&warning=1&vextwarning=&lang=en

Of course nowhere is it said that one should be able to pass the file through the validator, so sorry if this lands on the wrong forum.

**Comment by mourner** [comment]
Yeah, there's no way Leaflet could conform to the ancient validator rules because there are a lot of modern properties. Also no reason to conform.
