### ISSUE TITLE
Map load event does not fire when having center property in options object

### ISSUE THREAD

**Issue by iH8** [Leaflet/Leaflet#3856]
// Fails
    new L.Map('leaflet', {
        'center': [0, 0],
        'zoom': 0
    });

    // Also fails
    new L.Map('leaflet', {
        'center': [0, 0],
        'zoom': 0
    }).setView([0, 0], 0);

    // Works
    new L.Map('leaflet', {
        'zoom': 0
    }).setView([0, 0], 0);

    // Also works
    new L.Map('leaflet',{}).setView([0, 0], 0);

Is this by design, a bug or maybe an oversight or something?

**Comment by IvanSanchez** [comment]
How are you attaching the `load` event?

**Comment by yohanboniface** [comment]
Is it on stable (`0.7.x`) or on master or both?

A jsfiddle may help: http://playground-leaflet.rhcloud.com/?html,output or http://jsfiddle.net/ :)

**Comment by iH8** [comment]
Chained directly at instanciation: 

    new L.Map('leaflet', {
        'center': [0, 0],
        'zoom': 0
    }).on('load', function () {
        console.log('Fire!');
    });

**Comment by mourner** [comment]
This is to be expected, since first your initializing the map fully, and then adding a listener _after_ it had already been loaded.
