### ISSUE TITLE
Loading tiles not working when webpage is loaded in facebook-app

### ISSUE THREAD

**Issue by alexaagreen** [Leaflet/Leaflet#3857]
Hi, I made this site using leaflet js for the maps. When the site is view in the Facebook app/browser the map wont load. Anyone know how to fix this problem?

Site is here, but in a normal browser, everything works neatly:
https://www.skarpekniver.com/hvorliggerknivbutikken/

**Comment by perliedman** [comment]
@alexaagreen hm, I can't see a map on that page. Also, it looks like it should be possible to scroll, but at least I can't in my browser (Chrome/Ubuntu): no scrollbar, keyboard doesn't work either. Am I missing something?

Also, do you have any info on what the policy for JavaScript is in Facebook's app/browser? I can imagine they would impose some restrictions on what you can do.

**Comment by alexaagreen** [comment]
Hi,

Yes, you need to click the button, and then click the button on the drop down. I have done some debugging and it is only the Facebook Android app that has this problem. On iOS the map resources load pretty good. Any idea? Can you get to the map?

**Comment by mourner** [comment]
The page has a bunch of warning like this: 

> Mixed Content: The page at 'https://www.skarpekniver.com/hvorliggerknivbutikken/' was loaded over HTTPS, but requested an insecure image 'http://otile3.mqcdn.com/tiles/1.0.0/osm/14/8683/4767.png'. This content should also be served over HTTPS.

I think this could be what Facebook doesn't like. I'd suggest making sure you don't do mixed http/https requests on one page.
