### ISSUE TITLE
setZoom causes a move event to be fired

### ISSUE THREAD

**Issue by joehoyle** [Leaflet/Leaflet#3858]
For some reason, even if I zoom using the zoom controls, or set the zoom pragmatically, the location changes very slightly, this causes a map moved event to fire. This plays havoc with my moved events triggering when they shouldn't do.

Is there any reason for this? zooming in / out while not setting different coordinates seems like it should keep the center in the exact same position.

**Comment by IvanSanchez** [comment]
@joehoyle Leaflet 0.7.x or 1.0.0-beta?

**Comment by jieter** [comment]
beta: http://jsfiddle.net/1ut69n06/3/
0.7.5: http://jsfiddle.net/vm1L8hms/1/

The center doesn't change (not even slightly). `L.Map._move` just always fires a move event (in beta).

**Comment by mourner** [comment]
Yes. `move` event was designed to fire when the view changes in any way (including zoom). If you want to do something only on pan or only on zoom, there are corresponding events at your disposal.

**Comment by jlp277** [comment]
I'm also running into an issue where extra callbacks are getting fired because `zoom` + `move` events are fired on `setZoom` just like in OP's case. What are the "only on pan" and "only on zoom" events mentioned in the closing comment exactly? I can't find them in the docs.
