### ISSUE TITLE
[Leaflet 0.7.5] [Chrome] Space between tiles in certain zoom levels when using bootstrap css

### ISSUE THREAD

**Issue by adgoncal** [Leaflet/Leaflet#3862]
Sometimes there is 1px space between map tiles on Chrome Version 45.0.2454.99 m. This only happens when using bootstrap css. I have not been able to pinpoint the css rule causing this issue, but it does not seem to be caused by box-sizing: border-box because overriding that rule does not fix the problem.

http://plnkr.co/edit/M79tebSjND26NS28NjWe?p=preview

![leaflet-space-between-tiles](https://cloud.githubusercontent.com/assets/10856791/10023923/83e28018-6122-11e5-9937-7c61c9f191ae.png)

Does anyone know what is causing this?

It may be related to #3575.

**Comment by IvanSanchez** [comment]
Cannot reproduce in Chromium 43. Anyone around can try with 45?

**Comment by mourner** [comment]
Works fine for me in Chrome 45 on OS X...

**Comment by adgoncal** [comment]
I am using Windows 7 BTW.

**Comment by yohanboniface** [comment]
Works for me with Chrome Version 45.0.2454.99 (64-bit) on Ubuntu.
Are you sure the browser is not zoomed in any way? Are you able to test on another computer around you?

**Comment by mourner** [comment]
@adgoncal this will be tough to track down for us. Can you try bisecting the bootstrap CSS to find the culprit rule? I mean stripping out half of the code to see what half causes the issue, then stripping down further etc. until you get down to a single CSS rule.

**Comment by adgoncal** [comment]
@yohanboniface: Yes, the browser was slightly zoomed out and I did not notice it. Thanks! I am sorry for all this trouble.
