### ISSUE TITLE
Click on overlaying element is redirected to map

### ISSUE THREAD

**Issue by raieise** [Leaflet/Leaflet#3864]
Setup:
Angular 1.3 with IONIC
Leaflet 1.0-dev (ef7e30f) with Nokia HERE (also tested with 1.0.0-beta.2 (3ff1b65))

The map is shown on the screen. An Input field is available at the top of the map (search for location). 
General functionality: A click on a position of the map centres the clicked coordinates and displays a popup with the clicked address.
During the search process, a suggestion list (IONIC-List) is shown below the input field on top of the map (overlaying).
Required behaviour: The user selects (clicks) an element of the suggestion list. The suggestion list is hidden and the map zooms to the selected location.

Actual behaviour: The list is hidden and the map zooms to the location but instantly switches to the position of the map that was behind(!) the suggestion list at the time of the click.

This behaviour can be prevented by:
- using a timeout to hide the list after 550 or more milliseconds
- disabling the list-hiding (only for testing, not an option in for the product)

This problem can't be reproduced if the map is replaced by a click-sensitive div --> It is caused by leaflet.

Basic layout:
```html
<ion-content>
   <div class="search">
      <input searchbox.......>
      <div class="suggestionList" ng-if="showSuggestion">
         <ion-list>
            <ion-item>
               <div ng-click="selectedElement(coords)">Location Suggestion1</div>
            </ion-item>
         </ion-list>
      </div>
   </div>

   <map></map>

</ion-content>
```

Reproducible with:
Mobile devices like Nexus 5/Samsung S6, Iphone 6
Desktop: Chrome 45.0.2454.93 (only @Windows) in emulation mode(!) (Tested with Emulation "Nexus 5)

**Comment by yohanboniface** [comment]
Can you narrow the issue you want to demonstrate to a jsfiddle (maybe using http://playground-leaflet.rhcloud.com/) without any external dependency?

**Comment by Ganster41** [comment]
Try to add data-tap-disabled="true" to your map container. Ionic tap system conflicts with Leaflet. http://ionicframework.com/docs/api/page/tap/

**Comment by mourner** [comment]
If the suggestion above fixes the issue, I don't think we can or should do anything about it in Leaflet.

**Comment by gorshkov-leonid** [comment]
I think, I have same problem 
http://jsfiddle.net/goleon/s70gqdqj/  in 0.8-dev click fired only polygon overlay 
http://jsfiddle.net/goleon/3250kgd8/ in 1.0-beta2 click fired on polygon and map
So we emulating selection if user clicked on polygon and drop if user clicked on the map. Nothing is selects...
