### ISSUE TITLE
Previous removed polygons are not removed until we zoom in or zoom out the map when using with L_PREFER_CANVAS to true

### ISSUE THREAD

**Issue by prasad4491** [Leaflet/Leaflet#3866]
![canvas](https://cloud.githubusercontent.com/assets/8524977/10042958/b5098e30-620c-11e5-8cac-4454ba90612e.PNG)

As per your documentation,True if Canvas is used for vector rendering  I used settings global variable L_PREFER_CANVAS to true before the Leaflet include in my page.

Polygon are created dynamically on the map. I am removing previously created polygon using removeLayer() method. At the same time i am adding a new polygon to the map. Previously created polygon is not removed until the map is zoomed in or zoomed out.

![with same latlngs different polygon are drawn on the map](https://cloud.githubusercontent.com/assets/8524977/10043056/884e77a6-620d-11e5-920a-e8f4524b2b46.PNG)

  Above image depicts i am trying to remove and add polygon with same latlngs. Previous polygon is not removed. Please solve my issue anyone.

**Comment by mourner** [comment]
Can you make a minimal JSFiddle or [Leaflet playground](http://playground-leaflet.rhcloud.com/) test case that reproduces the issue?
