### ISSUE TITLE
Can't use getCenter() on polygon bounds

### ISSUE THREAD

**Issue by mohamedHoud** [Leaflet/Leaflet#3873]
Hi,

I don't understand what is happening here and i can't really say if it is a bug or not.
I wan't to get a polygon center so i do the folowing : 
var polygon = new L.Polygon(polygonPoints).setStyle({fillColor: 'red',color:'#CC0000',weight:2});
var polycenter = polygon.getBounds().getCenter();

In the browser console i get the following error : 
    TypeError: this._southWest is undefined                                leaflet.js:6:15641

Can you please help me ?

**Comment by yohanboniface** [comment]
Which Leaflet version?
Can you set up as small jsfiddle (maybe with http://playground-leaflet.rhcloud.com/) that demonstrates the issue?

**Comment by mohamedHoud** [comment]
Thank you for responding,
I use leaflet-0.7.4.

Here is the jsfiddle http://playground-leaflet.rhcloud.com/nar/edit?html,output

It's the first time that i use jsFiddle sorry if it doesn't work.

**Comment by yohanboniface** [comment]
Works for me http://playground-leaflet.rhcloud.com/guc/1/edit?html,output
