### ISSUE TITLE
Custom cellSize puts display off centre

### ISSUE THREAD

**Issue by kodeo** [Leaflet/Leaflet#3880]
When the cellSize parameter is used to specify a size other than 256, the resulting display is off center. For example ` L.map('map').setView([0, 0], 0)` shows `/0/0/0.png` like this with `cellSize: 256`:

![tile256](https://cloud.githubusercontent.com/assets/996340/10203132/28c8f870-67ac-11e5-8295-7dc7e2acdb02.png)

but like this with  `cellSize: 100`:

![tile100](https://cloud.githubusercontent.com/assets/996340/10203168/50c89984-67ac-11e5-8152-becfd8dd6eda.png)

**Comment by mourner** [comment]
What do you mean by cellSize? This word isn't even present anywhere in Leaflet code. You probably opened the issue in a wrong repo.

**Comment by kodeo** [comment]
Sorry, I meant `tileSize`.

**Comment by mourner** [comment]
Oh, I see. This looks like intended behavior, since when you change the tile size, the tile numbers also change and the center doesn't necessarily have to line up with a center of a tile.

**Comment by kodeo** [comment]
I don't understand how this can be. This leaves `setView` inaccurate doesn't it?

**Comment by mourner** [comment]
No. If you take your time with projection math, you'll figure out that this is correct behavior. For a given zoom, you have `256 * 2^zoom` pixels with the standard projection. If you have a tile size that's not a multiple of 256, it will be shifted relative to the center. If you need a different behavior, you need to write a custom projection.

**Comment by kodeo** [comment]
Isn't `setView([0, 0], 0)` always supposed to centre the view at the centre of the map?
