### ISSUE TITLE
Google Layer doesn't work with Leaflet 1.0.0 Beta

### ISSUE THREAD

**Issue by asotoopensky** [Leaflet/Leaflet#3881]
Hi all,

I'm creating a map and i'm trying to add a tile layer with Leaflet 1.0.0 Beta, this is my code:

```
var myCenter = new L.LatLng(50.5, 30.51);
var map = new L.Map('map', {center: myCenter, zoom: 15});
var positron = L.tileLayer('http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png', {});
map.addLayer(positron);

```

It works perfectly, but when i try to add a Google Layer with Leaflet Google library(http://matchingnotes.com/javascripts/leaflet-google.js) doesn't work:

```


var map = new L.Map('map', {center: myCenter, zoom: 15});
var ggl = new L.Google();
   map.addLayer(ggl);

```

after that i tried to change the version of Leaflet to 0.7.5 and worked perfectly. I need to use Leaflet 1.0.0 Beta because of some features so i can't just change the version on my project.

Check an example in:
http://jsbin.com/nafoloxade/edit?html,console,output

Please could you help me with this?

**Comment by IvanSanchez** [comment]
This issue tracker is only for the Leaflet core. Issues for plugins (such as matchingnote's plugin for using google maps) must be reported to the plugin's author instead.

Note that the Leaflet API has changed from 0.7.x to 1.0.0-beta, and as a result, plugins might break.

**Comment by asotoopensky** [comment]
OK, so, do you know any way to add a Google Layer to Leaflet 1.0.0 Beta you can tell me?

**Comment by IvanSanchez** [comment]
> OK, so, do you know any way to add a Google Layer to a map using Leaflet 1.0.0 Beta?

Unfortunately not. You can always try to adapt the code from leaflet-google so it works with 1.0.0, if you're up to the task.

**Comment by juanpablogd** [comment]
Hi all,

any solution?

Thanks in advance!

**Comment by juanpablogd** [comment]
SOLVED: download and replace file Google.js

https://raw.githubusercontent.com/shramov/leaflet-plugins/leaflet_one/layer/tile/Google.js

**Comment by rashadk** [comment]
Thanks

**Comment by Snnapy** [comment]
404 wrong link.

**Comment by mikhailir** [comment]
https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant
