### ISSUE TITLE
Problem interpreting WMS documentation for NOAA nowCOAST

### ISSUE THREAD

**Issue by vielmetti** [Leaflet/Leaflet#3887]
I'm trying to decipher the documentation provided by NOAA nowCOAST at

http://nowcoast.noaa.gov/help/#!section=mapservices

which has a WMS service for weather layers. Its documentation is aimed at ESRI's ArcMap or ArcGIS Explorer users, and it's by no means clear which parameters and base URL to use against the docs here

http://leafletjs.com/reference.html#tilelayer-wms

At the minimum, this would be a documentation question. Apparently there's some kind of layer discovery system that WMS provides. I was able to get WMS working with this server described at

http://mesonet.agron.iastate.edu/GIS/radview.phtml

so I know that something works, but it's not at all clear how all the details fit together.

**Comment by IvanSanchez** [comment]
You use the `GetCapabilities` URL, but without the `?request=GetCapabilities`.

I fail to see how this is a Leaflet problem. If you have some specific suggestion for the wording of Leaflet's documentation, feel free to submit a pull request.
