### ISSUE TITLE
Overlayed circles does not respond to mouse events (CANVAS ONLY)

### ISSUE THREAD

**Issue by shawel** [Leaflet/Leaflet#3888]
Mouseover events on circles added as a layer on top of state layers do not respond to mouse events. 

Here is an example. Hovering over circle should update the text  top right legend. This feature existed on 0.7 version of leaflet. It works on svg version. 

http://playground-leaflet.rhcloud.com/hag/edit?html,output

**Comment by IvanSanchez** [comment]
OK, the culprit is around https://github.com/Leaflet/Leaflet/blob/master/src/layer/vector/Canvas.js#L314

That is never called because `L.Canvas._updateCircle` doesn't add the circle marker to `this._drawnLayers`, so the loops in `_onClick` and `_handleMouseHover` skip it.

So in order to fix this:
- Change the code in `L.Canvas._updateCircle` to make sure that circle markers are added/removed to/from `this._drawnLayers`
- Check that `L.CircleMarker._containsPoint` runs on every pointer interaction on a canvas renderer
- Check that this works for both `L.CircleMarker` and `L.Circle`

**Comment by IvanSanchez** [comment]
I think this is easy enough for any newbie dev to fix, so I'm calling the good folks at @yourfirstpr to see if somebody wants to pick this one up. Remember to read `CONTRIBUTING.md`.

**Comment by Charlotteis** [comment]
@IvanSanchez thanks Ivan! I'll be tweeting about this at 1PM GMT today. Great instructions :sunny:

**Comment by brylie** [comment]
Hi, just following up with a couple of questions. 

Are the circle markers in the `ctx`object? Where are the pointer interaction event hooks?

**Comment by IvanSanchez** [comment]
> Are the circle markers in the ctx object? 

@brylie No, `ctx` is a [2D Canvas rendering context](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D).

The instances of `L.CircleMarker` (and any other subclass of `L.Path`, such as lines and polygons) are in `L.Canvas._layers`. Paths add themselves to a `L.Renderer` (by default `L.Map` instantiates one). Paths ask the renderer to re-render on certain conditions (and not the other way around).

> Where are the pointer interaction event hooks? The following seem relevant:

Yeah, events are set up in [`L.Canvas._initContainer()`](https://github.com/Leaflet/Leaflet/blob/master/src/layer/vector/Canvas.js#L20).

For the Canvas renderer (as opposed to the SVG renderer), the paths do not exist in the DOM tree, so the renderer must loop through every drawn path to see if a pointer event applies to it.


The code flow might not be a bit convoluted and not what you'd expect, but it's quite easy to follow by reading the code for `L.Renderer`, `L.Canvas`, `L.Path` and `L.CircleMarker`.

**Comment by IvanSanchez** [comment]
Due to playground maintenance, I messed up the existing examples, so the one for this bug now lives at http://playground-leaflet.rhcloud.com/fis/edit?html,output

**Comment by oliverroick** [comment]
Just wanted to look into this—but it seems to be fixed on master, isn't it?

**Comment by IvanSanchez** [comment]
@oliverroick No, it's still not fixed. Check the playground example, see how the behaviour of hovering your mouse over a circle still changes if `preferCanvas` is set to different values.
