### ISSUE TITLE
Disable map zoom while page is scrolling

### ISSUE THREAD

**Issue by lightonflux** [Leaflet/Leaflet#3889]
If you scroll a simple page with a leaflet frame you might stop scrolling halfway through the page and start zooming in the map.

Many embedded maps therefore disable scroll zoom. Which makes them very tedious to use. 

If leaflet would disable if it detects that the page move, that would eliminate accidental  zooming when scrolling the page.

I couldn't find a issue that describes that. But if there is one already: sorry. :)

**Comment by IvanSanchez** [comment]
In the case of embedded maps, assuming `<iframe>`s, it's pretty much impossible to respond to events (i.e. `mousewheel`) on the parent document from the iframed document, which in turn makes this impossible to implement.

**Comment by lightonflux** [comment]
Good to know. Is there a best practice to reduce the annoyance with the scrolling? Like a timeout. So you can only use the mouse wheel if your cursor was hovering the frame for several hundred milliseconds?

**Comment by IvanSanchez** [comment]
I guess you could do something like:

```js
map.on('mouseover', function() {
   window.setTimeout(map.scrollWheelZoom.enable.bind(map.scrollWheelZoom), 2000);
});

map.on('mouseout', map.scrollWheelZoom.disable.bind(map.scrollWheelZoom) );
```

And BTW it's a good practice to do stuff only on the map container, and not in the whole document.
