### ISSUE TITLE
Incorrect cursor over popup in IE11 if map cursor changed

### ISSUE THREAD

**Issue by chupikk** [Leaflet/Leaflet#3891]
If I change map cursor with css rule

``` css
.leaflet-container {
    cursor: crosshair
}
```

then this 'crosshair' cursor is also shown above popup. You can check this on tutorial page: http://leafletjs.com/examples/quick-start-example.html
Tested on IE11 + IE8-10 in emulation mode. OS Win7.
The problem exists for 0.7.5 and 1.0.0-b1

Can this be fixed without setting css cursor value for each element inside the popup pane (I have a form inside the popup)?

**Comment by Ram-one** [comment]
```
.leaflet-container { cursor:crosshair; }
.leaflet-popup-pane { cursor:default; }
```
Seems to work for me. Leaflet 7.7.0, Tested on IE7/8/9, firefox 42, chrome 46

**Comment by chupikk** [comment]
This combination seems to work for me as well, even for 0.7.5. Hmm... probably I was applying popup styling to a wrong element.

**Comment by Malvoz** [comment]
The problem with setting `.leaflet-popup-pane { cursor: default; }` is that it overrides cursors for text and interactive elements inside the popup. It seems that IE neither supports `cursor: auto` nor `cursor: initial`, which is perhaps why this bug exists.

Is there still interest in solving this bug, or is it time to close this issue?

**Comment by jonkoops** [comment]
Closing this issue as we have decided to drop support for Internet Explorer in a future version of Leaflet (see #6136).
