### ISSUE TITLE
Street Name is Incorrect

### ISSUE THREAD

**Issue by squibbfarm** [Leaflet/Leaflet#3896]
The street that runs between the boxes labelled as "Bruce" and "Sod & Samek" is displayed as Centre SideRoad, however that street is actually Green Valley Line.  This is in Ontario, Canada.

![street name on map incorrect](https://cloud.githubusercontent.com/assets/14997822/10310656/a81e8ac6-6c08-11e5-8e3a-5b9b32fe4201.jpg)

**Comment by IvanSanchez** [comment]
Leaflet is just a provider-independent map visualization library, not a map service. Contact the provider of the maps with the wrong road name instead.

**Comment by IvanSanchez** [comment]
This will help you understand that Leaflet just shows maps, which can come from a thousand different map providers: https://leaflet-extras.github.io/leaflet-providers/preview/
