### ISSUE TITLE
Map is not rending tiles when user touch end outside of the web view ( iOS )

### ISSUE THREAD

**Issue by kaga** [Leaflet/Leaflet#3900]
Environment
iOS - (e.g. iPad mini with OS 9.0.2 )

Repo steps:
1. Create a UIWebview that is smaller than the available screen size
2. Load the quick start example page

>let url = NSURL(string: "http://leafletjs.com/examples/quick-start-example.html")
>let urlRequest = NSURLRequest(URL: url!);
>webview.loadRequest(urlRequest);

3. Drag the map with touch ended outside the web view 

Expected 
- Map will load

Actual 
- Map didn't load with grey background, see screenshot below. 
![screen shot 2015-10-07 at 2 26 36 pm](https://cloud.githubusercontent.com/assets/1161744/10327132/3d4cce9e-6d00-11e5-9261-bd2941a2b31c.png)

Notes 
1. Tapping the web view once will trigger the load
2. No Error observed in web inspector

**Comment by IvanSanchez** [comment]
- Leaflet 0.7.x or 1.0.0-beta1?
- Is this reproducible in Safari using a non-fullscreen `<div>` or a iframe?
- Does the UIWebView fire any particular DOM event when the touch moves outside it or when the touch ends?

**Comment by mourner** [comment]
I take it this is only reproducible inside WebView, right? This might be an iOS bug.

**Comment by kaga** [comment]
Both my own project and the quick start example uses 0.7.5, haven't tested on 1.0.0beta
This is not reproducible for me in mobile safari ( iPad mini, 9.0.2 ), I set the map with 50% width and height.

UIWeview seems to fire touchmove even when the finger is touching outside of the webview. Interestingly, the touchend event is fire on the next touch event (i.e. on the next time the user touches the web view, 2 touch end event fired )

I tried the same thing on WKWebview, the bug seems not reproducible.

**Comment by danzel** [comment]
I suspect this is not fixable in leaflet, we probably just stop getting touch events when the touch leaves the webview (and not get a touch up event)

WKWebView [is recommended for all new development](https://developer.apple.com/library/ios/documentation/WebKit/Reference/WKWebView_Ref/)

**Comment by mourner** [comment]
Probably, yeah.

**Comment by anthony-jacquesSP** [comment]
Hi guys,

I'm developing an application using leaflet in a webview on android 4.0.3, and I've got the same issue. Do you have any idea how I could fix this bug ? 

Best regards,
Anthony.

**Comment by anthony-jacquesSP** [comment]
I must add that it is not happening every time but sporadically.
