### ISSUE TITLE
Streamline release workflow

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#3901]
Currently making a release involves a lot of manual steps, introducing lots of friction, so we tag releases less often than we could. This is a big problem and needs to be addressed urgently, with the following steps:

- [x] Describe the current release workflow in detail (specific list of steps done on each release)
- [x] Investigate whether it's possible to grant @yohanboniface @IvanSanchez access to the S3 bucket Leaflet CDN is on, and do it
- [x] Look into how we can make the process simpler, preferably just a few steps with as much as possible automated

**Comment by yohanboniface** [comment]
Would http://docs.travis-ci.com/user/deployment/ help?

**Comment by mourner** [comment]
Probably. Travis is already set up to upload builds on each commit (see https://github.com/Leaflet/Leaflet/blob/master/.travis.yml). We should improve the set up to do the same for release tags, plus upload zip downloads too.

**Comment by yohanboniface** [comment]
OK, so I let you do this task "Describe the current release workflow in detail (specific list of steps done on each release)" and I'll try to work on the `.travis.yml` to match it then :)

**Comment by mourner** [comment]
It would probably be easier for me to do since I have access to Leaflet S3 and can test everything out.

**Comment by jfirebaugh** [comment]
+1 for automating this so that Travis uploads to S3 any time it builds a tag. For mapbox-gl-js, the way this works (modulo that it's on Circle rather than Travis) is:

* AWS credentials in [encrypted environment variables](http://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables)
* [deploy.sh script](https://github.com/mapbox/mapbox-gl-js/blob/master/deploy.sh)
* call the script if `$TRAVIS_TAG` is non-empty

**Comment by mourner** [comment]
Now the current release workflow (since v1.0.0-beta.2) is:

- [x] update version in `src/Leaflet.js`
- [x] update version in package.json https://github.com/Leaflet/Leaflet/commit/55fe46250828d54d95cac0b8ca8b7a21dd97dbeb
- [x] run `npm run release` (provided you have `npm publish` rights)
- [x] wait for the Travis to build and upload artifacts (the build, leaflet.zip, etc.)
- [ ] Update `download.md` page in `gh-pages` branch to point to the new release (`http://cdn.leafletjs.com/leaflet/v1.0.0-beta.2/leaflet.js`, etc.)
- [ ] post a blog post and tweet about the new release

I'll port the scripts & travis config to stable branch and release 0.7.6 tomorrow. I also need to add @IvanSanchez @yohanboniface to NPM owners.

**Comment by mourner** [comment]
Also need to add `RELEASE.md` to `/build` with steps.

**Comment by yohanboniface** [comment]
Doing before time will eat your memory ;)
