### ISSUE TITLE
Zoom animation "bounces" when triggered during drag inertia

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#3902]
- Load any map in a desktop computer with a mouse.
- Drag the map around, release the mouse button while dragging so that a drag inertia movement is triggered.
- Quickly (before the inertial pan has finished) use the scrollwheel to zoom in or out.
- See how the zoom animation seems to be played twice.

Easier to reproduce when using a lower inertia deceleration (longer duration), e.g.:

```js
var map = L.map('map', {inertiaDeceleration: 500})
```

Reproducible only in `master` AFAIK. Multiple browsers. I don't recall this behaviour a couple a weeks ago so a `git bisect` might help.

**Comment by mourner** [comment]
Bisected, this is yours :) https://github.com/Leaflet/Leaflet/commit/7098b04cd7ccbd465a403a95c86aa96ba36f2814
