### ISSUE TITLE
missing method: map._latLngToNewLayerPoint

### ISSUE THREAD

**Issue by rkjdid** [Leaflet/Leaflet#3903]
unless I'm missing something, 08c7793  (#3895) breaks at 3 locations, related to _animateZoom methods:

https://github.com/Leaflet/Leaflet/blob/master/src/layer/ImageOverlay.js#L141
https://github.com/Leaflet/Leaflet/blob/master/src/layer/Popup.js#L246
https://github.com/Leaflet/Leaflet/blob/master/src/layer/marker/Marker.js#L207

**Comment by IvanSanchez** [comment]
Damn, I thought `L.Map._latLngToNewLayerPoint` wasn't being used anywhere else and was too quick removing it. I'll revert tomorrow.

**Comment by mourner** [comment]
Reverted.

**Comment by jieter** [comment]
No test to expose this?

**Comment by mourner** [comment]
Yeah, I mentioned the same concern in chat. Tests for this are a challenge though because this method is only used in animations.
