### ISSUE TITLE
Default zoom controls don't scroll map in FF, Safari

### ISSUE THREAD

**Issue by geografa** [Leaflet/Leaflet#3904]
Default zoom controls for scroll the map if the map's container is below the visible page. This is working as expected on Chrome and doesn't work on FF and Safari.

Example with default and custom zoom controls:
http://output.jsbin.com/vusobogoqi

I'm not clear if this is a bug or feature but for now, it has some browser inconsistencies.

**Comment by IvanSanchez** [comment]
I don't really understand the issue. Can you be more specific as to the *exact* steps required to reproduce the bug?

(Also, I used my mouse scrollwheel outside of the map area and got no strange behaviour)

**Comment by IvanSanchez** [comment]
No more information has been provided, and more than a few weeks have passed. We'll assume this issue is no longer relevant and/or there is no interest to make a better report.
