### ISSUE TITLE
Haversine or Spherical law of Cosines for latLng.distanceTo()?

### ISSUE THREAD

**Issue by francis-chui** [Leaflet/Leaflet#3911]
Documentation says Haversine forumla for L.latLng.distanceTo() while the L.CRS.Earth.distance() uses "spherical law of cosines approximation"

**Comment by francis-chui** [comment]
https://github.com/Leaflet/Leaflet/blob/master/src/geo/crs/CRS.Earth.js line 22

**Comment by perliedman** [comment]
Comparing the formula in `CRS.Earth` to [Wikipedia's article on Great circle distance](https://en.wikipedia.org/wiki/Great-circle_distance), it certainly looks like we're using the first formula used in that article, which is the "spherical law of cosines".

We should update the [docs for `distanceTo`](http://leafletjs.com/reference-1.2.0.html#latlng-distanceto) to reflect this.

**Comment by loisgh** [comment]
If this still requires fixing.  I'd be happy to take this on.

**Comment by perliedman** [comment]
@loisgh go for it! 👍

**Comment by loisgh** [comment]
So I made the change and created a branch for it.  I Can't push remotely as I don't have access.  Please advise.

**Comment by perliedman** [comment]
@loisgh ok, please open a pull request from the your branch in your repository!

Here's some GitHub docs on pull requests if you aren't familiar with them: https://help.github.com/articles/about-pull-requests/

**Comment by loisgh** [comment]
Here's the problem, I need to create a branch remotely before I can create a pull request.  I'm getting a 403 error.  I assume that I need to add permissions somewhere for this to happen. 
```
git push -u origin update_distance_to
remote: Permission to Leaflet/Leaflet.git denied to loisgh.
fatal: unable to access 'https://github.com/Leaflet/Leaflet.git/': The requested URL returned error: 403

```
Please advise

**Comment by IvanSanchez** [comment]
@loisgh Fork the `Leaflet/Leaflet` repo into `loisgh/Leaflet`, then push to your fork, then create a pull request from your forked repo to Leaflet's main repo. You can push branches to your own repos, but only Leaflet maintainers can push branches to the Leaflet main repo.

I suggest you take a bit of time to read https://help.github.com/articles/working-with-forks/ , as well as https://help.github.com/articles/changing-a-remote-s-url/

I know it takes some time to get used to a git workflow and it can be frustating. Have a bit of patience, and don't despair.

**Comment by wehelie** [comment]
@IvanSanchez is this still open?

**Comment by loisgh** [comment]
I sent a PR for this a while ago.  It should be closed.

**Comment by cherniavskii** [comment]
Closed by #5791

**Comment by mguinness** [comment]
The current formula for `distance()` is haversine *not* spherical, see https://www.movable-type.co.uk/scripts/latlong.html#distance.

https://github.com/Leaflet/Leaflet/blob/5dba5e685400947922e7a432aac897414cc05a5e/src/geo/crs/CRS.Earth.js#L21-L31

**Comment by francis-chui** [comment]
This issue refers to this version of CRS.Earth.js (9 years old): https://github.com/Leaflet/Leaflet/blob/2b52369fac8e2007cce37e43ea189032f46cd4b6/src/geo/crs/CRS.Earth.js

It was subsequently updated to use the haversine formula (8 years ago) but the comment was not updated: https://github.com/Leaflet/Leaflet/blob/f0c31c169125d5c47c7d27439dfb78e23263f39d/src/geo/crs/CRS.Earth.js
