### ISSUE TITLE
how to support indoor navigation on a leaflet map?

### ISSUE THREAD

**Issue by Byronic94** [Leaflet/Leaflet#3912]
now I have a indoor leaflet map generated by leaflet-indoor(cbaines/leaflet-indoor), and I want to achieve the feature of indoor navigation on this map. what need I do to complete it?Should I find a indoor navigation Algorithm to calculate the best way between two nodes?

**Comment by IvanSanchez** [comment]
> Should I find a indoor navigation Algorithm to calculate the best way between two nodes?

Yes.

This is not a Leaflet issue.
