### ISSUE TITLE
Polyline cross Greenwich

### ISSUE THREAD

**Issue by xSirrioNx** [Leaflet/Leaflet#3914]
Hi!
When i try to make polyline that cross Greenwich (longitude 180) i see this bug on map:
https://gyazo.com/6063e8ad7aca42007d074ddbee47ad32

It's because in response from server-side i have negative and positive latitude values  
(example: 
first point: -179.99937449989375,
next point: 179.99890150001738

So i try to convert negative values to positive:
```js
if(point.lon < 0){
    point.lon = 360 + point.lon;
}
var pointLatLng = new L.LatLng(point.lat, point.lon);
```

But in this case i see: 
https://gyazo.com/95bbafc7e52fc9355f997bddf9cf3ef4
Left point has longitude 0

In response frome server where is no points with longitude 180 or 0

And sometimes there is no this bug and track is correct with same server response.
I really can't find bug in my code and think that it is Leaflet bug...

P.S.: 
Sorry for my English =)

**Comment by IvanSanchez** [comment]
It's a known issue (#1293, #2645), so I'll just close this as duplicate.

And you don't mean "greenwhich" (which is a place near London), you mean the [antimeridian](https://en.wikipedia.org/wiki/180th_meridian).

A workaround is to split your polylines at the antimeridian. Read this: http://blog.cartodb.com/jets-and-datelines/
