### ISSUE TITLE
L.Renderer layer position wrong during pinch zoom  

### ISSUE THREAD

**Issue by cmulders** [Leaflet/Leaflet#3919]
In the vector-mobile debug page, using current leaflet master, the path is not positioned properly during a pinch zoom (with two vingers). 

![img_7073](https://cloud.githubusercontent.com/assets/8112493/10402076/6127ff22-6ec3-11e5-9224-a072e9b8fd42.JPG)

Path should be between the markers.

Using: iPad with IOS 9.0, Safari

Position of the L.Renderer layer is updated during pinch zoom by https://github.com/Leaflet/Leaflet/blob/master/src/layer/vector/Renderer.js#L61. Possibly a more complicated calculation is needed, as done in L.Renderer._animateZoom.

**Comment by yohanboniface** [comment]
Are you on latest master? I wonder if https://github.com/Leaflet/Leaflet/commit/a2595bbfe8109dc9cd24a15d28e0e4e6048e2e5f does not fix that yet.

**Comment by cmulders** [comment]
Yes, latest. a2595bb did not fixed it.
However, without a2595bb, the path does not zoom correctly either.

**Comment by IvanSanchez** [comment]
Dang. I should have a look at this next week.

**Comment by rkjdid** [comment]
just to add some more info, I'm having this bug on desktop

to me it looks like the position isn't updated at all during the zoom animation, at the end of it though it is redrawn correctly.

2 screenshots, first is when being still, second is during a zoom animation, the path is shifting to the right
![normal](https://cloud.githubusercontent.com/assets/1699009/10427485/66a1ab5a-70ea-11e5-8db4-fc942d29090b.png)
![zooming](https://cloud.githubusercontent.com/assets/1699009/10427487/69036eb0-70ea-11e5-9b3d-130f41a495c0.png)


I see you're working on it, I'll be happy to test the results

**Comment by IvanSanchez** [comment]
@rkjdid See 3923

**Comment by rkjdid** [comment]
let me try it

**Comment by rkjdid** [comment]
I do not notice any change, maybe my issue is not related

**Comment by mourner** [comment]
@rkjdid did you try `renderer-pinch-zoom` branch specifically?

**Comment by rkjdid** [comment]
ok my mistake, while trying to put up a test-case on rhcloud I realized the bug is coming only when using  [leaflet active area](https://github.com/Mappy/Leaflet-active-area)

I realize it's not the place but pointers to alternative solutions would be really welcome, I need the active area feature. Cheers

**Comment by IvanSanchez** [comment]
> I realized the bug is coming only when using leaflet active area

ActiveArea and ControlledBounds do magic with the map center to work. They're a separate issue.

**Comment by mourner** [comment]
@IvanSanchez so would the plugins be fixed by moveend on second finger touch?

**Comment by yohanboniface** [comment]
There is a 1.0 branch yet: https://github.com/Mappy/Leaflet-active-area/tree/leaflet-1.0 (not tested myself).

**Comment by IvanSanchez** [comment]
@mourner Not sure. I'm the creator of ControlledBounds, and AFAIK they don't depend on events.
