### ISSUE TITLE
Canvas does not refresh

### ISSUE THREAD

**Issue by Brutusn** [Leaflet/Leaflet#3926]
I have multiple layers with GeoJSON objects (either points or polygons). I can switch between those layers, but the old layer doesn't disappear. I am using the latest dev version of leaflet (Leaflet 1.0.0-beta.2 (a7f72fd)). However it did work with version: Leaflet 1.0.0-beta.2 (8f47372). Also some other plugins (marker cluster and draw) have similar issues. 

Is this an issue on my side, or on the side of Leaflet? See below for screenshots and a description.

Default render is correct.
![image](https://cloud.githubusercontent.com/assets/6348907/10428617/113c9270-70f3-11e5-8ce4-b247b5f4ce18.png)

Then I switch to a layer without markers but with "buildings", the objects not in the cluster marker are still on the page (though behind the buildings).
![image](https://cloud.githubusercontent.com/assets/6348907/10428643/37b609b8-70f3-11e5-9860-29e889aaef65.png)

Shown in this image, switched back to the first layer, the orange buildings should have been gone.
![image](https://cloud.githubusercontent.com/assets/6348907/10428666/5d24e0a2-70f3-11e5-9669-df26714521d9.png)

They are after you move the map.
![image](https://cloud.githubusercontent.com/assets/6348907/10428693/89c750fe-70f3-11e5-80c3-4d056edfb38d.png)

Same applies to the on hover areas of the cluster marker. The polygons should have been removed on mouse out, they aren't, only after a move on the map.
![image](https://cloud.githubusercontent.com/assets/6348907/10428712/9fb1f072-70f3-11e5-8816-d00ff0b24f7f.png)

It happens also with the leaflet.draw plugin when I try to remove a shape. It keeps being displayed until you move the map.

**Comment by yohanboniface** [comment]
Can you set up a minimal test case (without dependency) with http://playground-leaflet.rhcloud.com/ to reproduce the issue?

**Comment by Brutusn** [comment]
This should be the link: https://playground-leaflet.rhcloud.com/joh/edit?html,output

**Comment by yohanboniface** [comment]
Humm, scripts on your servers doesn't seem to load. Are they absolutely needed to reproduce?

**Comment by yohanboniface** [comment]
Sounds like https issue, switching everything on http seems OK. But I'm not sure how to reproduce the issue then. Missing some button or control I guess?

**Comment by Brutusn** [comment]
![image](https://cloud.githubusercontent.com/assets/6348907/10429644/5f414f40-70fa-11e5-83d4-b5598ae0e720.png)

Just hover on the circle with the 10 inside.

(and yes, my https is a self signed certificate thing. Sorry about that).

**Comment by IvanSanchez** [comment]
@Brutusn What branch of Leaflet.MarkerCluster are you using? `master`?

**Comment by Brutusn** [comment]
The leaflet-master branch. Though I didn't build it myself.

**Comment by IvanSanchez** [comment]
@Brutusn That branch is a bit out of date, unfortunately. Until things stabilize, can you try `leaflet-master-merge`?

**Comment by Brutusn** [comment]
@IvanSanchez I tried to use the leaflet-master-merge branche but the problem is not solved. Also I don't suspect that library because it happens in other libraries aswell. And it did work before. To me it looks like the canvas layer is not updated, until you do a move/zoom.

**Comment by IvanSanchez** [comment]
Hhhmmm, I see.

I would like to have a reproducible test case where hovering over a polygon would change its styling, but I don't have the time for that right now.

**Comment by yohanboniface** [comment]
> Also I don't suspect that library because it happens in other libraries aswell.

Then a more useful test case would be without any external library or plugin that are not needed to reproduce.

**Comment by Brutusn** [comment]
Something like this: https://playground-leaflet.rhcloud.com/vak/1/edit?html,output ? this adds a polygon and after about 2 seconds it tries to remove.

**Comment by yohanboniface** [comment]
Yes :)
But this one seems to be working for me (Tip: use the "Add libary" menu to add Leaflet")

**Comment by yohanboniface** [comment]
https://playground-leaflet.rhcloud.com/koh/1/edit?html,output

**Comment by yohanboniface** [comment]
Related #3840

**Comment by Brutusn** [comment]
Yes I noticed that aswell. But the version from the add library seems different: Leaflet 1.0.0-beta.2 (6e9236d)

Opposed to: Leaflet 1.0.0-beta.2 (514e27a) (the lastest build I got from http://leafletjs.com/download.html)

**Comment by yohanboniface** [comment]
OK, thanks, reproduce now. Investigating.

**Comment by yohanboniface** [comment]
@Brutusn can you try with last commit please?

**Comment by Brutusn** [comment]
That fixed it! Thanks :+1:

**Comment by yohanboniface** [comment]
Welcome :)
Thanks you for reporting it! :)
