### ISSUE TITLE
Marker taps are not recognized on Android with jQuery mobile

### ISSUE THREAD

**Issue by arminus** [Leaflet/Leaflet#3929]
Is there still an issue with taps on markers not being recognized on certain devices? In my case, the marker taps work fine on an iPhone 4S but not (or rather ~80% not) on an Android Galaxy S5neo.

I've tried various suggestions (e.g. setting options.tap to false as suggested in #3184 or tapTolerance to a higher value) on both 0.7.3 and 1.0 beta1 without apparent success. Taps work always fine on the iPhone and almost never on the Galaxy.

This is how I initialize my markers:

```javascript
    g_markers = new L.MarkerClusterGroup();
    for( var i=0; i<g_trails.length; i++ ) {
        var trail = g_trails[i];
        if( trail.type == trailType ) {
            var marker = new L.Marker(new L.LatLng(trail.lat, trail.lon), {id: trail.wayid});
            g_markers.addLayer(marker);
        }
    }
    g_markers.on('click', function (a) {
        showTrail(a.layer.options.id,true);
    });
```

**Comment by IvanSanchez** [comment]
@arminus Which browser are you running on the Galaxy? Stock android browser, chrome, opera, firefox, something weirder?

If anyone out there has a Galaxy S5 and can look into what kinds of events it fires when tapping on the screen, this issue can use some help.

**Comment by arminus** [comment]
Sorry, forgot to mention that... It looks like Firefox works reliably (but feels kind of slower), stock Android works mostly (but also not always) and Chrome almost never works.

Where could I insert trace statements (in the leaflet code) to see the differences between the browsers?

**Comment by IvanSanchez** [comment]
@arminus You can use something like the following wherever you instantiate your map:

```js
var map = L.map(...);
L.tilelayer(...).addTo(map);

// This traces leaflet events ('click' should be fired)
map.on('click preclick', function(ev){
    console.log(ev.type);
});

// This traces native DOM events ('click' should be fired)
L.DomEvent.on(map.getContainer(), 'click mousedown touchstart pointerdown', function(ev){
    console.log(ev.type);
});
```

You might also want to check out the repo, run some examples from source and trace the code from `src/map/handler/Map.Tap.js`.

**Comment by arminus** [comment]
Neither of these 2 events seem to fire in my case. Added this after a
map.on( 'moveend', function() ...
which I already have in the code (and which fires ok)

**Comment by rossholdway** [comment]
Hey @IvanSanchez 

I'm also getting this issue. Using the debug code and tapping on a marker or the map itself gives me mousedown and touchstart native events but no click event. map.on('click preclick'... does not fire anything.

I'm using leaflet 1.0.0-beta.2 within a Cordova 5.3.3 app on a **2nd gen Moto G (Android Lollipop 5.0.2)**. Click events work fine on iPhone and also work on Android 4.4.4 KitKat (1st gen Moto E).

If you can point me in the right direction I can try and debug this, or if you need me to test anything else on an actual Android Lollipop device let me know.

Thanks!

**Comment by kiwicreation** [comment]
I'm experiencing the same issue on my Nexus 4, with Leaflet 1.0.0-beta.2 (99a48a5). I added the lines that @IvanSanchez provided and did some test with Chrome Desktop touch emulation (which works) and on my Nexus 4 (dont work).

My test consisted of a single tap on a marker. Here's the results :

Win10, Chrome 46
```
domevent click tap mousedown mouseup touchstart touchend pointerdown pointerup => mousedown
domevent click tap mousedown mouseup touchstart touchend pointerdown pointerup => touchstart
domevent click tap mousedown mouseup touchstart touchend pointerdown pointerup => touchend
map click preclick => preclick
```

Nexus 4, Chrome 46
```
domevent click tap mousedown mouseup touchstart touchend pointerdown pointerup => mousedown
domevent click tap mousedown mouseup touchstart touchend pointerdown pointerup => touchstart
domevent click tap mousedown mouseup touchstart touchend pointerdown pointerup => touchend
domevent click tap mousedown mouseup touchstart touchend pointerdown pointerup => mouseup
```

`map click preclick => preclick` don't get fired and there is some new event "mouseup" on the Nexus 4, which is kind of odd.

A patch or a hack would be appreciate.

**Comment by IvanSanchez** [comment]
Weird. There is a `touchend` event that, for some reason, is not triggering the code in `L.Map.Tap` to fire the synthetic `click` event.

This should never happen - all my test devices behave properly there.

> Anything I can do to help fix this?

I think there is. A `console.log` or a breakpoint at `L.Map.Tap._onUp` should let you see what's going on when the `touchend` event fires:

- [ ] Check whether `_onUp()` is executed after a `touchend` event (on the Nexus)
- [ ] Check if the touch event is a native DOM Touch event, or some synthetic stuff from ionic/cordova/other emulation layer/etc. (Maybe `console.log()` the event that `_onUp()` receives) 
- [ ] Check if the touch event is properly formatted (does it have `changedTouches`? is the lenght of the `touches` array exactly 1?)

I hope with a bit of debugging we can reach the bottom of this.

**Comment by kiwicreation** [comment]
- [x] `_onUp()` is executed after a `touchend` (as recorded with `L.DomEvent.on`)
- [x] `_onUp(e)` receive a `TouchEvent` :
```
TouchEvent {
  altKey: false,
  bubbles: true,
  cancelBubble: false,
  cancelable: true,
  changedTouches: TouchList, // length 1
  ctrlKey: false,
  currentTarget: null,
  defaultPrevented: true,
  detail: 0,
  eventPhase: 0,
  isTrusted: true,
  metaKey: false,
  path: Array[15],
  returnValue: false,
  shiftKey: false,
  srcElement: img.leaflet-title.leaflet-tile-loaded,
  target: img.leaflet-tile.leaflet-tile-loaded,
  targetTouches: TouchList, // length 0
  timeStamp: 1447775446924,
  touches: TouchList, // length 0
  type: "touchend",
  view: Window,
  which: 0
}
```
- [x] `e.changedTouches.length` is 1 and `e.touches.length` is 0

**Comment by kiwicreation** [comment]
With the new log & breakpoint, here's the new event history that I'm getting.

Win10, Chrome 46.0.2490.80 m
```
L.DomEvent.on(map.getContainer(), "click tap mousedown mouseup touchstart touchend pointerdown pointerup" mousedown
L.DomEvent.on(map.getContainer(), "click tap mousedown mouseup touchstart touchend pointerdown pointerup" touchstart
L.DomEvent.on(map.getContainer(), "click tap mousedown mouseup touchstart touchend pointerdown pointerup" touchend
Map.on("click preclick" preclick
Marker clicked ! // marker.on('click')
L.DomEvent.on(map.getContainer(), "click tap mousedown mouseup touchstart touchend pointerdown pointerup" click
L.Map.Tap._onUp touchend 1 0
L.Map.Tap._onUp _simulateEvent("mouseup", Touch {} )
L.DomEvent.on(map.getContainer(), "click tap mousedown mouseup touchstart touchend pointerdown pointerup" mouseup
L.Map.Tap._onUp _isTapValid() true
L.Map.Tap._onUp _simulateEvent("click", Touch {} )
```

Nexus4, Chrome 46.0.2490.76
```
L.DomEvent.on(map.getContainer(), "click tap mousedown mouseup touchstart touchend pointerdown pointerup" mousedown
L.DomEvent.on(map.getContainer(), "click tap mousedown mouseup touchstart touchend pointerdown pointerup" touchstart
L.DomEvent.on(map.getContainer(), "click tap mousedown mouseup touchstart touchend pointerdown pointerup" touchend
L.Map.Tap._onUp touchend 1 0
L.Map.Tap._onUp _simulateEvent("mouseup", Touch {} )
L.DomEvent.on(map.getContainer(), "click tap mousedown mouseup touchstart touchend pointerdown pointerup" mouseup
L.Map.Tap._onUp _isTapValid() true
L.Map.Tap._onUp _simulateEvent("click", Touch {} )
```

I can confirm that the `touchend` in both case the `srcElement` is the same marker. You can also notice that `click preclick` event happens in both case before the `L.Map.Tap._onUp`.

**Comment by kiwicreation** [comment]
@IvanSanchez I solved my problem. It had nothing to do with Leaflet. I use Framework7 to build my app and the framework has bunch of _feature_ to "help" with tap/taphold events.

It happen to mess everything up with Leaflet events. Might be related with #3184.

I had to disable all these _feature_ in Framework7 init options and now Leaflet works as expected. 

```
var App = new Framework7({
	...

	materialRipple: false,
	fastClicks: false,
	activeState: false,
	tapHold: false,
	tapHoldPreventClicks: false,
	swipeBackPage: false
});
```

**Comment by arminus** [comment]
Well, for my part, I do not use Framwork7 (I do have jQuery Mobile in the mix, though). So for me the issue is not closed...

**Comment by IvanSanchez** [comment]
@aminus Have you tried removing jquery mobile? Do you use any other kind of frameworks or libraries that might be interfering with touch?

**Comment by arminus** [comment]
Let me do some more tests. It seems that 0.7.7 kind of behaves differently, i.e. after upgrading to that version, I have some strange behavior in other areas which I need to resolve first.

**Comment by arminus** [comment]
Ok, apparently, the current combination of my Chrome version, jQuery mobile version and Leaflet 0.7.7 works ok for the marker taps. I do have some strange behavior (again apparently only on Chrome) in other areas with taps on menus but this is most likely unrelated.

There's just too many moving parts over time which sometimes really make the case for doing native apps where the environment is more "controlled"... Anyway, I guess this can be closed then after all. Thanks for the help!

**Comment by IvanSanchez** [comment]
OK then! :-)

**Comment by DavidFrahm** [comment]
Adding that similar to [@kiwicreation's comment above](https://github.com/Leaflet/Leaflet/issues/3929#issuecomment-161762930) removing Angular-Material from our AngularJS web app allowed the taps to work.  The map zoom controls and popups were all failing silently, but after removing angular-material they all work as expected.
