### ISSUE TITLE
every add and remove markers is slover and slover in IE 

### ISSUE THREAD

**Issue by tombtom** [Leaflet/Leaflet#3935]
Hello
when add some markers then remove them and then add and remove and so ...
IE is slover after every cycle and  at last totaly isnt responding.
Chrome and FireFox is OK
simple sample:
http://jsfiddle.net/m2Lm05e9/1/
you can see as IE is slover afer some time

thanks for help

**Comment by IvanSanchez** [comment]
Which version of IE and which version of leaflet?

Are you able to provide benchmarks for different versions?

**Comment by tombtom** [comment]
I have last ver IE 11.

**Comment by tombtom** [comment]
In IE 10  is same problem

**Comment by yohanboniface** [comment]
Can you have a try with latest master? http://playground-leaflet.rhcloud.com/ may help ("Add library" then choose "Leaflet development version").

**Comment by mourner** [comment]
IE having a leak, who would have thought! Hehe. We take performance seriously so adding beta3 milestone until we make sure it's not a problem in Leaflet master.

**Comment by tombtom** [comment]
With master and also beta1,2 my sample working fine so you probably solved it already

**Comment by mourner** [comment]
Wooohooo! Thanks so much for making sure! I think we can close this.

**Comment by tombtom** [comment]
ok,  I use PureCluster plugin and when I upgrade to beta2 nothing work, so I hope that I can solve this ;)
