### ISSUE TITLE
Non-interactive markers prevent event propagation to overlapping vectors

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#3936]
If a marker is on top of a vector layer (for example, a polygon or a circle), clicking on the marker will prevent any mouse events from being fired in said vector layer.

Explained better with a bit of code ([live example at the playground](http://playground-leaflet.rhcloud.com/wiy/edit?html,output)):
```js
var somewhere = L.latLng([51.505, -0.09]);
var circle = L.circle(somewhere, 1000).addTo(map);
var marker = L.marker(somewhere, { interactive: false}).addTo(map);

map.toString = function(){ return "map"; };
circle.toString = function(){ return "circle"; };

function logEvent(ev) {
	console.log(ev.type + ' fired on ' + ev.target, performance.now());
}

map.on('click', logEvent);
circle.on('click', logEvent);
```

The expected behaviour is: whenever the user clicks anywhere inside the circle, the `click` event fires. That includes pixels covered by the non-interactive marker.

@yohanboniface I'm looking into the problem right now, I'll see if this can be actually worked around with some CSS.

**Comment by mourner** [comment]
@IvanSanchez note that Leaflet master link has changed, now it's https://leafletjs-cdn.s3.amazonaws.com/content/leaflet/master/leaflet.js

**Comment by yohanboniface** [comment]
As just discussed in IRC, I think that behaviour is expected. But I'm OK keeping the issue open to find a clean way to workaround that.

**Comment by yohanboniface** [comment]
Now I connect on marker being `{ interactive: false}` so issue is valid :)
