### ISSUE TITLE
Map doesn't pan back into bounds when dragging small distances on L.CRS.Simple with 1.0-beta2

### ISSUE THREAD

**Issue by Eschon** [Leaflet/Leaflet#3938]
First a GIF showing the bug:
![drag](https://cloud.githubusercontent.com/assets/11647830/10513487/31ac0854-7348-11e5-8ce1-12986f7977e9.gif)

If you drag small distances the map doesn't pan back into bounds until you drag bigger distances.
I also have fiddle that shows the bug [here](http://jsfiddle.net/Eschon/a691bj58/) (sorry I didn't have a tile source for this but you can still see it)

Tested this on:
* Safari 9.0
* Chrome 45.0.2454.101 (64-bit)
* Firefox 41.0.1
* Firefox 43.0a2 (2015-10-13)

**Comment by IvanSanchez** [comment]
> sorry I didn't have a tile source for this but you can still see it 

Luckily we've got fractals: http://playground-leaflet.rhcloud.com/cox/edit?html,output

**Comment by perliedman** [comment]
This issue isn't specific to `L.CRS.Simple`, but also reproducible with the default CRS. Check `debug/map/max-bounds.html`: you can pan as far north as you like as long as you do it in very small steps.

**Comment by perliedman** [comment]
Bisecting finds this issue as the source of the problem: 8f189bce239edffdbbd15e3580c545da89fe9fbf. 

However, it appears that although the you can't pan outside the bounds before this commit, on the other hand the map seems to freeze pretty regularly when you bounce against the bounds in earlier revisions.

/cc @yohanboniface
