### ISSUE TITLE
Pane z-index changes are not specified in Release.md .

### ISSUE THREAD

**Issue by louity** [Leaflet/Leaflet#3940]
Since commit 7ee404a  was merged in Master brach (see https://github.com/Leaflet/Leaflet/pull/3591/files ) , z-index of pane were mutiplied by 100. It might cause problems on apps that were designed for previous version of leaflet. It should be specified in Release.md.

**Comment by mourner** [comment]
Agreed, we should mention this in the changelog under "Breaking changes" section.

**Comment by perliedman** [comment]
While still technically correct, I think we're beyond the point where this makes any difference for anyone.

The changelog mentions z-indexes being changed, I think that's good enough.
