### ISSUE TITLE
Error when checking for moving draggable in canvas mouseMove handler

### ISSUE THREAD

**Issue by klaftertief** [Leaflet/Leaflet#3941]
Moving over a map with a canvas layer and the `dragging` option of a map is set to `false` throws an error. See http://jsbin.com/xoyiqifoki/edit?js,console,output

This is because the test in https://github.com/Leaflet/Leaflet/pull/3547/files#diff-5b3512e2ba3d374197128a67b330a0efR205 (introduced in #3547) doesn't check if the map is draggable.

**Comment by yohanboniface** [comment]
Fixed by #3942
