### ISSUE TITLE
Release 0.7.6

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#3945]
- [x] draft changelog in GitHub releases
- [x] update changelog in stable
- [x] update changelog in CHANGELOG.md in `master`
- [x] update version in `src/Leaflet.js`
- [x] update version in `package.json` 
- [x] port Travis config changes from master to stable
- [x] run `npm run release`
- [x] wait for the Travis to build and upload artifacts (the build, leaflet.zip, etc.)
- [x] Update the download page in `gh-pages` to point to the new release 
- [x] Update the rest of the website to use the new release (examples, tutorials, etc.)
- [x] Update the website to actually use the new release
- [x] tweet about the new release
- [x] publish the GitHub release entry

**Comment by wambacher** [comment]
Hi Vladimir,

thank's for you work.

will http://leafletjs.com/download.html be updated to bring this info to 
the world?

Regards

walter

Am 16.10.2015 um 12:48 schrieb Vladimir Agafonkin:
