### ISSUE TITLE
Canvas paths ignore 'interactive:false' option

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#3946]
Self-explaining. The following code will still allow a canvas-drawn polygon to fire `click` events:

```js
    var canvas = L.canvas();

    var path = L.polygon([
      [[[50.5, 30.5], [50.5, 40], [40, 40]]],
      [[[20, 0], [20, 40], [0, 40]]]
    ], {
      renderer: canvas,
      interactive: false
    }).addTo(map).bindPopup('Hello Canvas');
    
    path.on('click', function(ev){ 
      console.log('Clicked on the path');
    });
```

Live example at http://playground-leaflet.rhcloud.com/dac/edit?html,output

Reproducible on current master branch, multiple browsers.

The cursor does change when the `interactive` option is switched, though.

Slightly related to #3936

**Comment by yohanboniface** [comment]
I can have a look on this tonight if you are not in a hurry
