### ISSUE TITLE
Canvas paths disappear on animated zoom start and only appear again when zoom ends

### ISSUE THREAD

**Issue by klaftertief** [Leaflet/Leaflet#3947]
See http://jsbin.com/xoyiqifoki/edit?html,js,output or `debug/vector/vector-canvas.html` and zoom in/out. This was probably introduced in #3923 
There might be a race condition in writing and reading `this._map._animatingZoom` (the important read for this issue is here https://github.com/Leaflet/Leaflet/blob/v1.0.0-beta.2/src/layer/vector/Canvas.js#L29, it's always `undefined` or `false` there), but an easy fix might be to just not call `update()` in `_onZoomStart`.

**Comment by Malvoz** [comment]
Fixed in https://github.com/Leaflet/Leaflet/pull/3950.
