### ISSUE TITLE
getBounds failing on Geojson layer

### ISSUE THREAD

**Issue by fccoelho** [Leaflet/Leaflet#3951]
I have  a geojson layer which is created with  `L.geoJson(...` and then added to map.
later I want to call `map.fitBounds(geojson.getBounds())`.
But I keep getting this error:

```javascript
TypeError: bounds is undefined
bounds = bounds.getBounds ? bounds.getBounds() : L.latLngBounds(bounds)
```

**Comment by IvanSanchez** [comment]
Is your GeoJSON empty by any chance? If not, can we have a look at it?

**Comment by fccoelho** [comment]
I figured out what it was. I was calling the getBoiunds before geojson was done loading. Since the loading is asynchronous, one needs to take care with that.
