### ISSUE TITLE
Make window attachment only happen when commonjs or amd is not invoked

### ISSUE THREAD

**Issue by tmcw** [Leaflet/Leaflet#3958]
If this line https://github.com/Leaflet/Leaflet/blob/master/src/Leaflet.js#L27 was an `else if` instead of an `if`, browserify users wouldn't have the unexpected side effect of `require('leaflet')` automatically exposing the library under window.L

Downstream: https://github.com/mapbox/mapbox.js/issues/1060

**Comment by mourner** [comment]
This is by design, background with PRs and discussion here #2364. If a user cares about `L` global, there's `L.noConflict()`.
