### ISSUE TITLE
map.removeLayer() seems to clear all event listeners of the map

### ISSUE THREAD

**Issue by narrowtux** [Leaflet/Leaflet#3960]
When I setup my map, I add listeners for the `click` and `mousemove` events. Some time later, layers (in this case markers and polylines) get added and removed. Once a layer is removed, the map doesn't send any more events to my `click` listener, the `mousemove` listener however still gets the event.

When I register the `click` listener again, it will resume sending events, so a workaround for me is to re-add all my listener after I removed layers.

**Comment by yohanboniface** [comment]
Can you setup a minimal test case to reproduce the issue: http://playground-leaflet.rhcloud.com/ ?

**Comment by narrowtux** [comment]
I'm using Mapbox 2.2.2, but since the bug is in the leaflet API, I reported this here. My test case uses only the latest leaflet and there it works without any issues.

http://playground-leaflet.rhcloud.com/dig/2/edit?html,output

**Comment by IvanSanchez** [comment]
@narrowtux If I replace the Leaflet 0.7.x library from your playground example and select MapboxJS 2.2.2 from the drop-down menu, the bug is still not reproducible.

**Comment by narrowtux** [comment]
Seems like something else is wrong. I'm using http://inkblot.io/angular-mapbox/ to be able to use mapbox in my Angular project, and there's probably a bug there then.

**Comment by narrowtux** [comment]
Update to this: I changed my project around a bit so I am not using angular-mapbox in any way, just the normal Mapbox 2.2.2 Javascript library. The bug still persists, weirdly only for the `click` event.

**Comment by narrowtux** [comment]
I'll try to make a working example of the bug later.

**Comment by Aaron-Pool** [comment]
Hey, just wanted to give a specific example of this, because I discovered this behavior as well. Like narrowtux, this event only manifested itself with the click event.

If you look at the code below, it nukes the click events added in the `onEachFeature` property, because I remove a layer after adding the click listener

```
MapDataService.getGeodocsData(MapService.getDataCategory())
                .then(function(geojson) {
                    var newGeoJsonLayer = L.geoJson(geojson, {
                            onEachFeature: featureFunction
                        }),
                        oldGeoJsonLayer = vm.geoJsonLayer;

                    // this also calculates color breaks, so it must be called before style is set
                    MapDataService.calculateLabels(MapService.getDataCategory());

                    newGeoJsonLayer.setStyle(styleFunction);

                    vm.map.addLayer(newGeoJsonLayer);

                    vm.geoJsonLayer = newGeoJsonLayer;

                    if(vm.map.hasLayer(oldGeoJsonLayer)) {
                        vm.map.removeLayer(oldGeoJsonLayer);
                        oldGeoJsonLayer = null;
                    }
                });
        }

function featureFunction(feature, layer) {
            layer.on({
                click       : function(e) {
                    showPopup(e);
                },
                mouseover   : function (e) {
                    highlightLayer(e.target);
                },
                mouseout    : function (e) {
                    revertStyle(e.target);
                }
            });
        }
```

However, if I reverse the order like so: 

```
MapDataService.getGeodocsData(MapService.getDataCategory())
                .then(function(geojson) {
                    var newGeoJsonLayer = L.geoJson(geojson, {
                            onEachFeature: featureFunction
                        }),
                        oldGeoJsonLayer = vm.geoJsonLayer;

                    // this also calculates color breaks, so it must be called before style is set
                    MapDataService.calculateLabels(MapService.getDataCategory());

                    newGeoJsonLayer.setStyle(styleFunction);

                    if(vm.map.hasLayer(oldGeoJsonLayer)) {
                        vm.map.removeLayer(oldGeoJsonLayer);
                        oldGeoJsonLayer = null;
                    }

                    vm.map.addLayer(newGeoJsonLayer);

                    vm.geoJsonLayer = newGeoJsonLayer;
                });
        }
```

The click events register fine. This isn't a real, breaking issue for me, because I can just reverse the order. For others however, this could be a breaking bug.

**Comment by lemieuxs** [comment]
I am having the same issue here... Sadly I can't just reverse the order. 

I am removing data when the data is too far from the screen bounds. When I do all the other click events on my other layers stops working...

I tried to do a simple fiddle, but since I do not know the cause it's really hard to replicate the issue. It's really only the click event. My mouseover / mouseout events are still working fine...

Some help would really be appreciated.
