### ISSUE TITLE
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by carrbrpoa** [Leaflet/Leaflet#3961]
I'm toggling between my available baselayers (with or without overlays) and sometimes this error comes:

![error_toggling_baselayers](https://cloud.githubusercontent.com/assets/10212618/10693881/dad72c38-7979-11e5-8341-af6b2156918c.png)

And the line pointed in ```BasemapLayer.js``` is:

```javascript
onRemove: function(map){
      // check to make sure the logo hasn't already been removed
      if(this._logo && this._logo._container){
        map.removeControl(this._logo); // Line 232
        map._hasEsriLogo = false;
      }
      (...)
```

Here's a plnkr: http://plnkr.co/edit/jyXgske9YXYRViqLamBc?p=preview

It's a simplified version of my app, without overlays. See that you just need to start switching the baselayers and in a while the error occurs.

Sometimes it just doesn't loads the selected baselayer due to the error.

Any ideas?

Thanks in advance

**Comment by snkashis** [comment]
So that file(BasemapLayer.js) is coming from the Esri plugin(https://github.com/Esri/esri-leaflet/blob/master/src/Layers/BasemapLayer.js) - have you posted an issue there?

**Comment by carrbrpoa** [comment]
@snkashis, didn't noticed that. I'll try there. Thanks!
