### ISSUE TITLE
Error: Map Container Is Already Initialized

### ISSUE THREAD

**Issue by bibeputt** [Leaflet/Leaflet#3962]
refreshing a leaflet map giving Error: Map Container Is Already Initialized

**Comment by snkashis** [comment]
Sounds like you are trying to re-init an existing map... The issues boards here is more for working through bugs and suggestions of new features. StackOverflow(http://stackoverflow.com/questions/tagged/leaflet) is a better place for troubleshooting your usage of the library. If you do believe this is from a bug, post your example case in a JSFiddle or another demo site.

**Comment by bibeputt** [comment]
Looks like issue is related to implementation in MVVM and not a bug. Will try to search some MVVM  examples using leaflet.

**Comment by ralexrdz** [comment]
same issue here... what could it be?

**Comment by mourner** [comment]
@ralexrdz perhaps a container that you initialize more than once?

**Comment by ralexrdz** [comment]
@mourner The html is basically html head loading js and css and a div with id="map". And the only js that I have is 
map.setView([19.34, -99.15], 12);
  L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
      attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
      maxZoom: 18,
      id: '<mapboxMapId>,
      accessToken: '<mapboxAccessToken>'
  }).addTo(map);
How could that be that a container is initialize before?

**Comment by epicallan** [comment]
i am having the same issue, i am using leaflet in React

**Comment by danzel** [comment]
That'll be a react-leaflet bug probably @epicallan

**Comment by epicallan** [comment]
@danzel i am using react, its react-leaflet bug, just did some hacky work arounds

**Comment by srflorea** [comment]
@epicallan Can you please explain what you did? I have the same issue with React and Leaflet.

**Comment by Dipinrajc** [comment]
Before initializing map check for is the map is already initiated or not

var container = L.DomUtil.get('map');
      if(container != null){
        container._leaflet_id = null;
      }

**Comment by adrielstar** [comment]
@Dipinrajc With this method your not available to drag with mouse on the map.

**Comment by fillipefeitosa** [comment]
Any ideia how to drag map again with mouse @adrielstar ?

**Comment by adrielstar** [comment]
I us this @fillipefeitosa .

**HTML:** 
<div id="map"></div>

**render map:**
document.getElementById('map').innerHTML = "<div id='map' style='width: 100%; height: 100%;'></div>";

to reload content of div where render map.
Hoop this will help you too

**Comment by fillipefeitosa** [comment]
Thanks friend, but that did not work. It replaced my ```var map``` with the div and map not loads

**Comment by enzojimenez** [comment]
> Before initializing map check for is the map is already initiated or not
> 
> var container = L.DomUtil.get('map');
> if(container != null){
> container._leaflet_id = null;
> }

is there an existent leaflet method for this?

**Comment by mohafouad** [comment]
same problem with me :(

**Comment by SyedAkmal** [comment]
> > Before initializing map check for is the map is already initiated or not
> > var container = L.DomUtil.get('map');
> > if(container != null){
> > container._leaflet_id = null;
> > }
> 
> is there an existent leaflet method for this?

@enzojimenez , You can create one method for this as I have created below

function initializingMap()   // call this method before you initialize your map.
{  
var container = L.DomUtil.get('map');
if(container != null){
container._leaflet_id = null;
}
}

**Comment by josuelmm** [comment]
Para resolver el problema, define:
import * as Map from 'leaflet';

@ViewChild('map') mapElement: ElementRef;
  map: Map.Map;

this.map = Map.map(this.mapElement.nativeElement, {
      maxZoom: 18
});

Solucion aquí: https://www.designlimbo.com/leaflet-ionic-3-and-map-container-is-already-initialized/

**Comment by amin-setayeshfar** [comment]
as said [here](https://stackoverflow.com/questions/19186428/refresh-leaflet-map-map-container-is-already-initialized), this would be the best way of doing it:
`if (map != undefined) {
    map.remove();
}`

**Comment by MRVirus007** [comment]
> Before initializing map check for is the map is already initiated or not
> 
> var container = L.DomUtil.get('map');
> if(container != null){
> container._leaflet_id = null;
> }

You are an Angel

**Comment by Ashik-AD** [comment]
Try this it might work

----HTML----
```
<div class="map-wrapper">
   <div id="map"><div>
</div>
```

----JS------
//map-wrapper and map
const mapWrp = document.querySelector('.map-wrapper');
const map = document.querySelector('#map');

//Create a new map element 
const newMap = document.createElement('div');
newMap.setAttribute('id', 'map');

// Remove older/previous map element
mapWrp.removeChild(map);

// insert new map element
newMap.append(newMap);
```
**Please insert this code before Actual map initialized**

**Comment by fillipefeitosa** [comment]
@Ashik-AD ,

there is a time since I last messed up with this, but I certainly try and feedback to you. Thanks for your time

**Comment by kirklimbu** [comment]
i was facing same issue as in Angular, i was using maps in two different components with same id  <div id="map" ></div>. I simply changed id and kept two separate ids and solved this issue.

**Comment by masoudnemati** [comment]
```
useEffect(() => {
    var map = L.map("map").setView(newLatLng, 17);
    L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
      attribution:
        '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
    }).addTo(map);


    L.marker(newLatLng).addTo(map).bindPopup("فروشگاه لوازم خانگی").openPopup();

    var popup = L.popup();

    function onMapClick(e) {
      popup
        .setLatLng(e.latlng)
        // .setContent("You clicked the map at " + e.latlng.toString())
        .openOn(map);
      setNewLatLng(e.latlng);
      map.remove();
    }

    map.on("click", onMapClick);
  }, [newLatLng]);

**Comment by raulandrez** [comment]
don't use:
```
var osm = L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 19,
        attribution: '© OpenStreetMap'
    }).addTo(map);
```
use:
```
var osm = L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 19,
        attribution: '© OpenStreetMap'
    });
map.addLayer(osm);
```

**Comment by ndi-dev90** [comment]
A faced this issue in a vue project. The solution (in my case) is initialzing the map with a template ref instead of using native HTML id.

In my case, i'm rendering multiple maps using loops etc. on the same page, so using native HTML ids caused the nodes not being uniqely identifiable. So organizing code like the map component has its own template with a ref to the node where the map needs to be rendered, solved the problem.

**Comment by MuhammadArsalanAhmed** [comment]
I'd been stuck in this problem, then I thought about this solution. It works for me.

const [unmountMap, setunmountMap] = useState(false);
//to prevent map re-initialization
useLayoutEffect(() => {
setunmountMap(false);
return () => {
setunmountMap(true);
};
}, []);

if (!unmountMap)
return (

);
else return "loading map...";

**Comment by khalilr2k** [comment]
If you using Angular, check your RouterModule. maybe you set a conflicted rule that load the AppComponent twice.
e.g:
`{ path: '', component: AppComponent }`

**Comment by ovirta** [comment]
> Before initializing map check for is the map is already initiated or not
> var container = L.DomUtil.get('map'); if(container != null){ container._leaflet_id = null; }

> @Dipinrajc With this method your not available to drag with mouse on the map.

Encountered the same issue with React app using js leaflet, where drag is not working. Problem is related to React loading components twice in development. In production the issue is not visible. 

If you check the html elements in browser you can probably find duplicate elements of `class="leaflet-pane leaflet-map-pane"` under your leaflet map container div.

Imho this issue could be resolved by leaflet devs by making sure that duplicates are not created in Map.js `_initPanes` but as said this only affects dev build so perhaps priority does not justify such a change.

Hope this is helpful for someone.

**Comment by alaa-m1** [comment]
To solve this problem we can use useEffect with return function (to apply cleanup mechanism for useEffect), as the following:
```
  useEffect(() => {
    const position: LatLngExpression = [51.5, -0.09];

    const map = L.map("map").setView(position, 13);

    L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png", {
      maxZoom: 19,
      attribution:
        '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>',
    }).addTo(map);

    L.marker(position).addTo(map);

    return () => {
      map.remove();
    };

  }, []);
```
