### ISSUE TITLE
Old links for CSS and JS files

### ISSUE THREAD

**Issue by brendancheney** [Leaflet/Leaflet#3965]
Our media company uses leaflet for our maps and our archive stories use the following links to files that don't seem to be working today: 

http://leafletjs.com/dist/leaflet.css

http://leafletjs.com/dist/leaflet.js

For the two new stories we published today I updated with this: 

http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css

http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js

And those stories work. But it seems the maps in old stories with the old java script and css files don't work. Are those old files being updated? Or would I have to update all old stories with the new files?

**Comment by danzel** [comment]
You should update the old stories to use the 0.7.7 URLs you have posted. Those unversioned files were never meant for public consumption.

**Comment by brendancheney** [comment]
So does that mean every time you have a new version, I'll have to update all urls in all previous articles?

**Comment by danzel** [comment]
No, the old versions stay around.
http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css and http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js as an example.

**Comment by brendancheney** [comment]
Is there any way to keep the unversioned file around? Or a redirect? We have so many stories in the archives that use it. We love your maps and use them a lot. A lot. And I dread the idea of going to IT folks to change all of the links.

**Comment by danzel** [comment]
I'm going to say no. But CC'ing in @mourner for the final word.

**Comment by mourner** [comment]
@brendancheney as Dave said, the links from the website were never meant to be used publicly and were never exposed anywhere except the website source code, and the download pages always encouraged the use of versioned CDN links, so you have no one to blame but the one who used those links. Using unversioned links is also never a good idea since they can break anytime an incompatible change is introduced — they were always asking for trouble. 

I'm afraid you'll have to update all the incorrect links. But the good thing is that you'll only have to do this once.

**Comment by brendancheney** [comment]
I accept the fact that I didn’t fully understand, so you are probably right that I have no one to blame but myself. 
But it seems like a fix could be relatively easy (unless there is something I don't fully understand?). 
Up until now, we have been very happy with Leaflet. And we liked that it was relatively accessible to a non-expert, self-taught coder and reporter like me. We like it so much that we’ve created I think more than 100 maps for various stories. It will be a huge task to update the links in all of those stories.
And more so, as we think about which service to use for the likely (hopefully?) hundreds of maps we plan to make in the future, we’ll want to make sure it is one where we can get help, even in situations when we have no one to blame but ourselves. 
So if there is anything at all you can do, we'd greatly appreciate it.

**Comment by mourner** [comment]
Sorry, unfortunately there's nothing we can help with in this case. You'll have to update the links. If you worry that it would take too much time, I'd suggest automating replacements with a script — should be easy.
