### ISSUE TITLE
setStyle to different layers and resetting the style back

### ISSUE THREAD

**Issue by franleplant** [Leaflet/Leaflet#3966]
Hi!
    Im trying to perform a _selection_ effect on several layers. I can easily run `layer.setStyle(selectionStyle)` but I haven't find a way of resetting the style back to what it originally was.

What I tried to do is to save the current styles from `layer._options`, but my layers have nothing there, even though the layers clearly have styles in them.

There is also the problem where the layers might recursively have layers inside them (`_layers`).

Is there anyway of resetting the style?

Thanks a lot for your help!
Fran

**Comment by mourner** [comment]
It's `layer.options`, not `layer._options`. Saving and then resetting should work OK, it works the same way for `geojson.resetStyle`

**Comment by franleplant** [comment]
@mourner I dont have `options`, I only have `_options` with the described problems:

<img width="371" alt="screen shot 2015-10-27 at 10 54 39 am" src="https://cloud.githubusercontent.com/assets/1852455/10759997/3e0ba05a-7c99-11e5-8cf7-b59bcb2db5b2.png">

Any ideas?

Appendix:
Also, while Im at it, it is really difficult to find out the type of the layer Im inspecting.

**Comment by mourner** [comment]
Set up a JSFiddle with your use case please.

**Comment by franleplant** [comment]
What I found is that those layers that **do not** have `options` they tend to have sub layers that **do** have options, so I resolved that in that way. 

Thanks a lot for your help!
