### ISSUE TITLE
L.circle marker not being projected onto map

### ISSUE THREAD

**Issue by linebp** [Leaflet/Leaflet#3969]
When I make a very large circle it is not distorted by the map projection but simply being drawn as a circle on the map. My map uses the webmercator projection 3857, so this should distort the circle into an ellipse.

I am not entirely convinced this is the actual bug, as the documentation is hazy on this point. But my reasoning is that, since the radius of the circle is given in meters and the radius should be the same on the whole circle, this is either misleading or it is an actual bug that the circle is not drawn with the same distance in meters from the center to the edge of the circle on the whole circle.

jsfiddle demonstrating the issue: http://jsfiddle.net/p6ssbvqj/10/

**Comment by mourner** [comment]
This was somewhat fixed in the beta 2 version, try that one!
