### ISSUE TITLE
Overlay not redrawn if map moves when overlay deselected

### ISSUE THREAD

**Issue by JamesRamm** [Leaflet/Leaflet#3970]
This works:

- Add overlay to the map
- Turn layer off (using layer control) and turn it back on. It gets redrawn.
- Move map
- Turn layer off and on. It gets redrawn.

This does not work:

- Add overlay to map
- Turn layer off (using layer control).
- Move map
- Turn layer on. It doesnt get redrawn until I move the map again with the layer on. 

Is this intentional?

I want it to always redraw the layer when I toggle it back on....

**Comment by mourner** [comment]
Can you set up a minimal JSFiddle test case?

**Comment by IvanSanchez** [comment]
I can **not** reproduce with marker overlays in either 0.7.x or 1.0.0-betas: http://playground-leaflet.rhcloud.com/yos/edit?html,output

**Comment by IvanSanchez** [comment]
I can **not** reproduce with either 0.7.x or 1.0.0-betas using a marker overlay: http://playground-leaflet.rhcloud.com/sum/1/edit?html,output

**Comment by IvanSanchez** [comment]
I'm closing this, as a request for more information was made more than one month ago but no further information has been provided.
