### ISSUE TITLE
Event bubbling issue for draggable markers in 1.0b1

### ISSUE THREAD

**Issue by snkashis** [Leaflet/Leaflet#3971]
We have discovered an issue in our platform that we didn't notice before updating to 1.0b1..
Looks like draggable markers are having their dragend event fall into click events on the underlying map(if the marker doesn't have a popup bound to it)
I have built a simple test page (https://github.com/snkashis/Leaflet/blob/bd84dc7c428bccf77b2a1bb39d1effeeea15bcca/debug/tests/click_after_drag.html) in my branch https://github.com/snkashis/Leaflet/tree/drag_bubbling to demonstrate.

To see this behavior, try dragging the east-most marker of the two on this map. 
In 1.0b1, a click event(which logs 'click' to the console) on the map is fired after drag end.
Bisection indicates ee3f2f8b1e259833badd590a646e2523a5eaff7b is the problem commit.

If you copy this new debug file into your repo, and then switch back to 7ca19b59eae4e98abf0fc0fbd46e0ce335b9d18b(the previous), you will notice that the click event is not fired. Is there some other issue in play here causing this?

**Comment by yohanboniface** [comment]
> updating to 1.0b1

Have you tested with latest master too?

**Comment by snkashis** [comment]
Yes. Is this the intended behavior now?

**Comment by snkashis** [comment]
Here is an example on the playground - http://playground-leaflet.rhcloud.com/tir/2/edit?html,console,output

**Comment by yohanboniface** [comment]
That sounds a bug to me. I'll have a look.

**Comment by yohanboniface** [comment]
Not trivial to fix.
Workaround if needed in the meantime: listen to click on the marker too.

**Comment by yohanboniface** [comment]
> listen to click on the marker too.

This seems weird, so let me explain a bit: if you listen to click on the marker, the marker will not be skipped while looking for the event target, and thus we'll check on it if it's in dragging mode.

**Comment by snkashis** [comment]
Yeah, I didn't see an easy pathway to fixing this yesterday...Will try out your suggestion.

**Comment by snkashis** [comment]
That worked, thanks.
