### ISSUE TITLE
Overlapping loaded tiles affect opacity of semi-transparent layer

### ISSUE THREAD

**Issue by fullofcaffeine** [Leaflet/Leaflet#3973]
Hi there!

I have a heatmap layer that's served from GeoServer through WMS. It looks like this:

<img width="538" alt="screenshot 2015-10-28 22 50 32" src="https://cloud.githubusercontent.com/assets/81248/10810419/5f498574-7dc6-11e5-82e1-e3ff8829e42d.png">

The problem arises when I zoom in or out. The new loaded tiles are shown above the old scaled tiles and affect the overall visual opacity of the layer, and it affects the opacity of the layer, it looks less transparent, for a while:

<img width="1043" alt="screenshot 2015-10-28 22 56 21" src="https://cloud.githubusercontent.com/assets/81248/10810486/24e42d34-7dc7-11e5-80d6-46a68dfa9128.png">

Does leaflet have any setting(s) that would allow me to prevent showing the old tiles when a new one is loaded? Any ideas on how I could solve this issue?

Thanks!

**Comment by IvanSanchez** [comment]
Hola, Marcelo,

Tiles are unloaded when all the tiles which overlap the same area in a different zoom level have finished loading. There is no easy way to crop tiles right now (it's doable with WebGL but requires a lot of work).

You can work around the issue with something like:

```js
map.on('zoomstart', function(){
  heatmaptiles.removeFrom(map);
});
map.on('zoomend', function(){
  heatmaptiles.addTo(map);
});
```

Given the complexity of the workaround, I don't know if it's worth it to add an option to gridlayers to control overlapped loading. I'll leave the issue open in case somebody thinks that's the case.

**Comment by mourner** [comment]
This was discussed many times before (just search for issues with the word "opacity"). There's no easy way to gracefully fix this in Leaflet.

**Comment by fullofcaffeine** [comment]
@IvanSanchez Thanks. I slightly modified it and the following snippet was a good enough workaround:

```javascript
    this._map.on('zoomstart', function(){
      that._map.removeLayer(that.wms);
    });
    this._map.on('zoomend', function(){
      that._map.addLayer(that.wms);
    });
```
