### ISSUE TITLE
Pinch-zoom with "custom fractional zoom" in 1.0-beta-2

### ISSUE THREAD

**Issue by pexi72** [Leaflet/Leaflet#3975]
I've been using "custom fractional zoom" with CRS.Simple and one background map without any tiles successfully earlier with just:

L.CRS.CustomZoom = L.extend({}, L.CRS.Simple, {
    scale: function (zoom) {
        return Math.pow(2,(zoom+1.0)*0.5);
    }
});

Idea is to get more zoom levels than just 2x.

Now with 1.0-beta-2 pinch-zooming with iPhone fails such that when I start pinch-zoom, map jumps to nearest 2x-zoom level if it was in "middle-zoom". With 0.8-dev -version there is/was no such issue.

With 1.0-beta-2:
http://gpspekka.kapsi.fi/leaflet2/test10beta2.html
With 0.8-dev (4/2015):
http://gpspekka.kapsi.fi/leaflet2/test08.html

Is there any simple workaround or is that fractional zoom now somehow possible without that "CRS.CustomZoom"?

**Comment by IvanSanchez** [comment]
I suggest you try the code from `fractional-zoom-controls` branch, see #3523.

**Comment by pexi72** [comment]
With fractional-zoom-controls seems to work fine, thanks.
http://gpspekka.kapsi.fi/leaflet2/test10fzc.html
