### ISSUE TITLE
once() can cause infinite loops

### ISSUE THREAD

**Issue by foundryspatial-duncan** [Leaflet/Leaflet#3979]
I noticed the one-time event listener function `once` [runs the callback, and _then_ unbinds the event listener](https://github.com/Leaflet/Leaflet/blob/v1.0.0-beta.2/src/core/Events.js#L186). If the callback function fires more of the same event, this can cause infinite loops, and I don't think that would ever be the desired behaviour.

jQuery's similar `one` function [unbinds the event listener before it runs the callback](https://github.com/jquery/jquery/blob/master/src/event.js#L83), so it can't ever get stuck in a loop.

A simple example:

```
/* this code causes an infinite loop */
myMap.once('fooEvent', function(){
    console.log('fooEvent fired!'); // this should only run once, but it goes infinitely
    myMap.fire('fooEvent'); // fire the event again inside the listener callback
});
myMap.fire('fooEvent'); // fire the event initially
```

jQuery equivalent:

```
/* this code works as expected */
$(myMap).one('fooEvent', function(){
    console.log('fooEvent fired!'); // this will only print once
    $(myMap).trigger('fooEvent'); // fire the event again inside the listener callback
});
$(myMap).trigger('fooEvent'); // fire the event initially
```

I was using Leaflet's `once` to listen for an initial `filtersReady` event, and then the callback would run a bunch of methods that could sometimes result in another `filtersReady` being fired, which froze the app in a loop described above.
Switching the order of the callback and the unbind would make `once` more flexible, and probably not break any existing code.

**Comment by IvanSanchez** [comment]
@foundryspatial-duncan Seems you've got the problem rounded up. Care to submit a pull request?

**Comment by foundryspatial-duncan** [comment]
I took a look, but I wasn't able to get it working with the existing code. I thought initially that it would be as simple as switching the order of the `.on` or `.off` lines, but that's not the case.

I also tried to mimic the flow jQuery.one uses, where it explicitly unbinds the listener and then calls `.apply` on the callback. Any thoughts?

**Comment by radnor** [comment]
@foundryspatial-duncan I've successfully mimicked the flow of jQuery.one in #4003 - this should fix your issue!

**Comment by mourner** [comment]
Closing in favor of #5376.
