### ISSUE TITLE
Vector layers offset after interrupting flyTo()

### ISSUE THREAD

**Issue by nathansnider** [Leaflet/Leaflet#3985]
Clicking on the map in the middle of a `flyTo` animation will cause vector layers to be drawn incorrectly. The animation will stop, but the vector layers will not redraw immediately; they continue to show only the subset that was contained in the view at the beginning of the animation. 

Then, if you pan the map, the vectors will redraw, but offset and scaled as if the map were still at the starting location of the `flyTo` event. They will remain offset and mis-scaled until you zoom or complete another `flyTo`.

Here is a jsfiddle with which you can verify the behavior:

http://jsfiddle.net/nathansnider/37sm4y60/

I am seeing this with v1.0.0-beta.2 on both Chrome and Firefox.

**Comment by mourner** [comment]
Confirmed, will look into it.

**Comment by IvanSanchez** [comment]
The changes in the fractional zoom controls alleviate this a bit, but the bug can still be reproduced by setting `zoomSnap: 0` in the map options.

Easiest way to fix this should be to fire a `zoomend` event whenever a zoom/flyTo animation is stopped with `zoomSnap=0`, to force redrawing of vector (and plugin) layers.
