### ISSUE TITLE
Allow zoomControl position in default map options

### ISSUE THREAD

**Issue by dalvarez** [Leaflet/Leaflet#3987]
When you init L.map, you can provide a `zoomControl` boolean as to whether the map should have the zoom control by default or not. This automatically places it in the top left. For our use case, we want it in the bottom left, but there's no clear way to do this in the default. Currently, we pass `zoomControl: false` to the default options, and then create a separate zoom control to be added after the initialize:

```
L.control.zoom({ //L.control extension for (+/-) on the map
    position: 'bottomleft'
  })
```

It would be great if you could pass in the position to the default options to get around this.

**Comment by mourner** [comment]
You can just do `map.zoomControl.setPosition('bottomleft')`.
