### ISSUE TITLE
Leaflet-0.7.3 is not working anymore

### ISSUE THREAD

**Issue by leolux** [Leaflet/Leaflet#3989]
I did not make any code changes, but suddenly the map stays white and nothing gets displayed inside the map.

Is the version 0.7.3 supposed to work at the moment?
Has the compatibility for older versions beeing dropped ?

**Comment by IvanSanchez** [comment]
0.7.3 works just fine: https://playground-leaflet.rhcloud.com/suy/edit?html,output

Have you tried using a different version? Using the debug console to check for any errors?

**Comment by leolux** [comment]
Well, the link shows the error:
Mixed Content: The page at 'https://playground-leaflet.rhcloud.com/runner' was loaded over HTTPS, but requested an insecure script 'http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js'. This request has been blocked; the content must be served over HTTPS.

**Comment by leolux** [comment]
Here is a screenshot:
http://i65.tinypic.com/2zswknk.png

**Comment by leolux** [comment]
I am running chrome browser Version 46.0.2490.80 m

**Comment by leolux** [comment]
Even if I server leaflet-0.7.3.css and leaflet-0.7.3.js from my own server the tiles get blocked from the browser nevertheless. Here is an error message in chrome:
"Mixed Content: The page at 'https://localhost:8181/...' was loaded over HTTPS, but requested an insecure image 'http://b.tile.osm.org/18/137212/89481.png'. This content should also be served over HTTPS."

This seems to be a design problem. How to solve this without making changes to the browser security settings?

**Comment by leolux** [comment]
I will close this issue, because map works in version 0.7.3 at the moment when javascript and css gets server over secure connection. 

But the browser keeps producing warning messages for all tile images ("Mixed Content"). Maybe this warning will be turned into a error in future which would actually stop it from working.

Thank you for your fast support!

**Comment by leolux** [comment]
Related discussion can be found here: https://github.com/Leaflet/Leaflet/issues/3186

**Comment by IvanSanchez** [comment]
@leolux Load that example over plain http or allow http scritps on a https page. There's a separate issue all about why the CDN doesn't allow https.

Still, my point stands: 0.7.3 just works.
