### ISSUE TITLE
Geojson Line weight not resetting after resetStyle/mouseout event (1.0-b2)

### ISSUE THREAD

**Issue by DaveF63** [Leaflet/Leaflet#3990]
Hi
I'm having specific problem with the mouseout event using 1.0:
http://jsfiddle.net/z3kxdk46/6/

With this jsfiddle (using 1.0 b2) when the mouse hovers over the line it changes from weight=8 to 15 but doesn't reset when It's moved away. Notice that the opacity & color both change back to the original. If I amend the ref to ver 0.75 it works as expected.

Edit 0.75 version:
http://jsfiddle.net/z3kxdk46/7/

Any ideas for a solution?

Cheers
Dave F.

**Comment by IvanSanchez** [comment]
> Any ideas for a solution?

In order to debug this, I suggest setting a breakpoint at `L.GeoJSON.resetStyle()` and/or `L.GeoJSON._setLayerStyle()`. The function call to `_setLayerStyle` should receive the same parameters when the layer is loaded the first time, and when the style is reset.
