### ISSUE TITLE
clicking on a marker whose popup is open make the popup close AND open at the same time (V1 beta2)

### ISSUE THREAD

**Issue by remilev** [Leaflet/Leaflet#3992]
http://jsfiddle.net/Pe5xU/261/

With the new leaflet v1 beta 2 :
1 - you click on the blue marker icon -> the popup open
2 - you REclick on the marker icon -> the popup close (fadeOut) AND re-open (fadIn)

With the older 0.7 version : 
1 - you click on the blue marker icon -> the popup open
2 - the popup is just closing. It is more what we expect.

To have the same result in v1 than in v0.7, we must use map.options.closePopupOnClick : false.
But of course, with that, a click on the map does'nt close the open popup anymore...

How to retrieve the old behaviour of v0.7 with v1 ?

**Comment by IvanSanchez** [comment]
@yohanboniface Is this the expected behaviour with the 1.0.0 event handling?

**Comment by yohanboniface** [comment]
> @yohanboniface Is this the expected behaviour with the 1.0.0 event handling?

Nope. I add that to my todo list, unless you have a look before ;)

**Comment by JoranBeaufort** [comment]
Could it be that this problem still exists when binding popups to polygons? So if a popup is open and a user clicks somewhere else on the polygon that the `map.on('popupopen',function(e){})` or the `map.on('popupclose',function(e){})` are not fired correctly?

**Comment by yohanboniface** [comment]
Which Leaflet version are you using?

**Comment by JoranBeaufort** [comment]
Im using Leaflet 1.0.0-rc2: `<script src="https://npmcdn.com/leaflet@1.0.0-rc.2/dist/leaflet.js"></script>`. Maybe a bit more information: I am creating polygons with: `L.polygon()` and then bind popups to the polygons with: `polygon.bindPopup()`. In the popup, I have a div in witch I generate a SVG. So I only want to generate the SVG if the popup is actually open as to increase performance. So naturally, I use: 
```
map.on('popupopen',function(e){
   ... SVG GENERATION HERE ...
}
```
And when the popup closes, I destroy the SVG again:
```
    map.on('popupclose',function(e){
        var svg = d3.select("#my-SVG-div").selectAll("*").remove();
    });
```
It works fine for all cases, except when I click on the same polygon as has an open popup. Then the events do not seem to get fired.

**Comment by yohanboniface** [comment]
May just be another face of #4743.
Can you try with #4769 by chance?

**Comment by JoranBeaufort** [comment]
Dont think it has to do with the first issue because the SVG is not drawn on the map, but into the popup. And it works if I open a popup, close it again with the little "x" in the top right corner of the popup and then click on the same polygon again to open a new popup. 
The second issue I dont fully understand because I basically only have 2 event listeners on the map, a popupopen and a popupclose and Im guessing my order of open --> close is the natural order for these listeners?

**Comment by yohanboniface** [comment]
The root of #4743 is the order of event listeners not being honoured, and it may be the same for the issue you are talking about.

**Comment by JoranBeaufort** [comment]
Hm ok. How can I test that and where can I see what order I need to honour?

**Comment by yohanboniface** [comment]
Oh, that something different than the original issue then.
Can you open a new issue and create a jsfiddle to reproduce (with http://playground-leaflet.rhcloud.com/) ?

**Comment by JoranBeaufort** [comment]
Ok, recreated error in the fiddle: http://playground-leaflet.rhcloud.com/zewi/edit?html,js,console,output Please let me know if the fiddle works for you because I have no experience with fiddles :)
