### ISSUE TITLE
Allow user NOT to have the popup fadeOut animation on closepopup (v1 beta2)

### ISSUE THREAD

**Issue by remilev** [Leaflet/Leaflet#3994]
The new leaflet v1 bring the fadeOut animation when closing popup. It is great, but :

It would be great to have an option to let user choose to have or NOT this fadeOut. 
Explaination : I run some functions map.on.popupopen to style in real time the popup wich is opening (different styles for different places on earth). And with the new fadeout now included, the styles I add are already visible during fadeOut of the CLOSING popup (before the new popup is opened). Which leads to an ugly visual mix:)

http://jsfiddle.net/Pe5xU/268/

I think It would be great to let us choose to have/not have fadeIn/fadeOut of popups independently of each other rather than the global option fadeAnimation true/false.

Even without regarding "my" little problem, I love to see the popups disappear without fade and mybe I'm not alone... :)

**Comment by IvanSanchez** [comment]
If you are already styling popups, just add this bit of CSS:

```css
.leaflet-fade-anim .leaflet-popup {
  transition: none;
}
```

> let us choose to have/not have fadeIn/fadeOut of popups independently of each other rather than the global option fadeAnimation true/false.

Just add a CSS class to those popups you want to disable fade anims for, and use the same bit of CSS :-)

I don't think this is a very important feature to have, specially when it can be worked around with a bit of extra CSS.

**Comment by remilev** [comment]
Thanks. But It skip the fadeIn too in the meanwhile...

It's not very important though, you're right.
It can be done by stripping a line in the source code (it's bad, I know:).
When removing popup :
<code>
onRemove:function(t){
/* commented to avoid fadeOut of popup
t._fadeAnimated
?
(o.DomUtil.setOpacity(this._container,0),this._removeTimeout=setTimeout(o.bind(o.DomUtil.remove,o.DomUtil,this._container),200))
:
*/
o.DomUtil.remove(this._container),t.fire("popupclose",{popup:this}),this._source&&this._source.fire("popupclose",{popup:this},!0)
}</code>

**Comment by IvanSanchez** [comment]
@remilev Please don't modify the minified version of the source code. No one can understand that.

**Comment by RhinoDevel** [comment]
> Just add a CSS class to those popups you want to disable fade anims for, and use the same bit of CSS :-)

Maybe I misunderstood, but adding class to popup with option className and then setting this via CSS for the class, e.g:

`.my-popup 
{ 
    transition: none; 
}`

At least does not seem to work with Leaflet v1.0.3 & Firefox & Win.

But @IvanSanchez 's

> .leaflet-fade-anim .leaflet-popup {
  transition: none;
}

works fine (although applied to ALL).

**Comment by trandaison** [comment]
@IvanSanchez Thanks!
```css
.leaflet-fade-anim .leaflet-popup {
  transition: none;
}
```
This works for me.
