### ISSUE TITLE
fitBounds ignores maxZoom option when its value is 0

### ISSUE THREAD

**Issue by simsibimsiwimsi** [Leaflet/Leaflet#3995]
A {maxZoom: 0} option is ignored in L.Map.fitBounds method, while any other value like {maxZoom: 5} works fine. 

Applies to both stable and master branches.

Problem is caused by 
```js
		zoom = (options.maxZoom) ? Math.min(options.maxZoom, zoom) : zoom;
```
where options.maxZoom evaluates to false when its value is 0.

In stable branch this happens in `fitBounds` directly, in master branch it has moved to `_getBoundsCenterZoom`.

Created a fiddle to illustrate:
http://jsfiddle.net/simsibimsiwimsi/ysq9ny8L/

**Comment by IvanSanchez** [comment]
This should be a quick fix, just changing `(options.maxZoom)` to `(options.maxZoom !== undefined)`.

@simsibimsiwimsi Why don't you try to make a pull request for this? You've located the bug, it should be easy for you to fix and test it :-)

**Comment by simsibimsiwimsi** [comment]
@IvanSanchez I've approached it with (typeof options.maxZoom === 'number') in https://github.com/Leaflet/Leaflet/pull/3996 shortly after creating the issue. Wasn't sure if I should do it for stable & master at the same time.. Bear with me - I'm new here ;-)

**Comment by IvanSanchez** [comment]
Yeah, `typeof` will also work :-)

Usually we focus only on master, but you're welcome to write a fix for stable too :-)

**Comment by simsibimsiwimsi** [comment]
Alright, I'll add the pull request with the fix for the master in the evening :-)
https://github.com/Leaflet/Leaflet/pull/3996 adresses stable already..

**Comment by IvanSanchez** [comment]
@simsibimsiwimsi :+1:

**Comment by simsibimsiwimsi** [comment]
Pull request with a fix for the master: https://github.com/Leaflet/Leaflet/pull/4000

**Comment by IvanSanchez** [comment]
Fixes look good to me. Thanks!
