### ISSUE TITLE
Showcase companies using Leaflet

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#400]
Major services:
Foursquare: http://foursquare.com http://blog.foursquare.com/2012/02/29/foursquare-is-joining-the-openstreetmap-movement-say-hi-to-pretty-new-maps/
Craigslist: http://t.co/V4EiURIA
IGN: http://www.ign.com/wikis/the-elder-scrolls-5-skyrim/interactive-maps/Skyrim
StreetEasy: http://streeteasy.com/
City-data.com: http://www.city-data.com/city/Iowa2.html
Nestoria: http://blog.nestoria.co.uk/why-and-how-weve-switched-away-from-google-ma
Meetup.com: http://meetup.com/craftsy
Geocaching.com: http://www.geocaching.com/map/
Postcrossing.com http://www.postcrossing.com/postcards/CA-208202
USGS: http://earthquake.usgs.gov/earthquakes/eventpage/usb0009tk0#summary http://earthquake.usgs.gov/monitoring/netquakes/map/
US National Park Service: http://www.nps.gov/npmap/blog/switching-park-maps-to-npmap-and-leaflet.html
SF Park Alliance: http://www.sfparksalliance.org/visit/find-events-parks
Citymaps.com: http://www.citymaps.com/map
DPLA: http://dp.la/map
Energy.gov: http://energy.gov/articles/announcing-top-10-list-green-utility-leaders
Data.gov: http://www.data.gov/
CodeClub: http://codeclub.org.uk/
RunKeeper http://runkeeper.com/

News:
New York Times: 
http://www.nytimes.com/interactive/2012/01/15/business/one-percent-map.html http://www.nytimes.com/interactive/dining/new-york-health-department-restaurant-ratings-map.html
The Boston Globe: http://www.boston.com/news/weather/specials/hurricane_sandy_reports_mapped/
http://boston.com/news/politics/2012/reports_from_polling_places/
http://www.bostonglobe.com/2013/02/08/main/NMg9OejQo82CsJUR1maUeI/story.html
The Guardian: http://www.guardian.co.uk/environment/interactive/2011/dec/08/carbon-emissions-global-climate-talks
http://www.guardian.co.uk/news/datablog/interactive/2013/feb/25/italian-elections-results-interactive-guide
NPR: http://stateimpact.npr.org/pennsylvania/drilling/
http://apps.npr.org/moore-oklahoma-tornado-damage/
The Wall Street Journal: http://projects.wsj.com/campaign2012/maps
Los Angeles Times: http://projects.latimes.com/mapping-la/
http://spreadsheets.latimes.com/boyscouts-cases/
Chicago Tribune: http://media.apps.chicagotribune.com/chicago-census/index.html
The Daily Beast: http://www.thedailybeast.com/articles/2012/10/19/ground-game-obama-opens-up-big-lead-in-state-headquarters.html
CBC News: http://www.cbc.ca/news/interactives/cp-census/
ProPublica: http://projects.propublica.org/redistricting-maps/mcnerney
Washington Times: http://www.washingtontimes.com/campaign-2012/AK/live-map/
Minnpost: http://www.minnpost.com/data/2012/03/mapping-voter-same-day-registrations-minnesota
Waterloo-Cedar Falls Courier: http://wcfcourier.com/app/special/hunting_grounds/
Associated Press: http://hosted.ap.org/interactives/2012/aging-nuclear/
Texas Tribune: http://www.texastribune.org/library/data/us-senate-runoff-results-map/
Topic: http://www.topix.com/
Washington Post: http://www.washingtonpost.com/wp-srv/special/politics/election-map-2012/senate/
http://www.washingtonpost.com/wp-srv/special/politics/election-map-2012/president/
Pittsburg Post-Gazette http://newsinteractive.post-gazette.com/OYW/
WNYC http://www.wnyc.org/articles/wnyc-news/2012/oct/28/transit-tracker/
NRK.no http://www.nrk.no/fordypning/dette-er-smuglartrendene-1.10881930
Detroit News: http://www.detroitnews.com/article/20130221/SPECIAL01/130220003/
Reuters: http://www.reuters.com/subjects/academy-awards#interactive
http://www.reuters.com/article/interactive/idUSBRE94L19020130522?view=large
USA Today: http://www.usatoday.com/story/news/nation/2013/03/14/census-county-population-trends/1986171/
Gazette: http://gazette.com/map-black-forest-fire-perimeter-hot-spots/article/1502261
GQ: http://www.gq.com/long-form/no-exit

GIS startups:
GisCloud: http://www.giscloud.com/
MapBox: http://mapbox.com/
Skobbler: http://maps.skobbler.com/

Small web aps:
Map Tales: http://maptal.es
FreshyMap http://freshymap.com
SickWeather http://www.sickweather.com/

Other:
National Geographic Education: http://globalcloset.education.nationalgeographic.com/map
NASA Astrobiology Institute: https://astrobiology-alpha.arc.nasa.gov/nai/reports/annual-reports/2011/
New York Public Library: http://directme.nypl.org/latest
GPSies: http://gpsies.com
Jann Arden Tour 2012: http://tour.jannarden.com/
Drupical: http://www.drupical.com/
Chartbeat: http://chartbeat.com/demo/#geo
Footwork: http://etpio.com/
Food Truck Fiesta: http://foodtruckfiesta.com/
IGN: http://www.ign.com/wikis/guild-wars-2/interactive-maps/WorldFull
WOWHead World of Warcraft map: http://www.wowhead.com/map
Rome II: Total War http://wiki.totalwar.com/w/Panorama
Hipmunk http://www.hipmunk.com
Art Map Project: http://www.artmapproject.com/
American Progress: http://www.americanprogress.org/issues/economy/news/2013/07/12/64832/mapping-the-sequester/
London Heathrow Airport: http://maps.heathrow.com/

Mobile apps:
Official Wikipedia Android app: https://play.google.com/store/apps/details?id=org.wikipedia&hl=en
Official Wikipedia iOS app
http://blog.wikimedia.org/2012/04/05/new-wikipedia-app-for-ios-and-an-update-for-our-android-app/
Taxonomy http://taxono.my/, http://blog.untogether.co.uk/post/17554554409/i-had-no-idea-how-to-make-custom-maps-so-i-learnt-by
Snowciety: http://snowcietyapp.com/
Gather: https://gather.at/

**Comment by mourner** [comment]
Will be covered by #3578

**Comment by jieter** [comment]
What about the app gallery?

**Comment by mourner** [comment]
@jieter yeah, we should probably do that eventually but not a high priority currently.
