### ISSUE TITLE
Empty SVG

### ISSUE THREAD

**Issue by ayozebarrera** [Leaflet/Leaflet#4002]
Hi

When I add a polyline to the map, it appends a svg in the .leaflet-overlay-pane. That is ok.
But when I remove the polyline, the svg keeps on the dom but empty.

I'm having performance problems with lot of data but just after adding/removing a polyline. I think there is an event on that svg and I'm getting a 3-4 seconds of lag when I try to pan.

Should that svg keeps on the dom? Or It should be like it's initial state, without the svg?
thankyou!

**Comment by mourner** [comment]
Can you set up a minimal JSFiddle test case reproducing your performance problem?

**Comment by ayozebarrera** [comment]
Not at the moment, but I will later.

Anyway... forgetting performance.. shouldn't that svg be deleted? There's no sense having that svg translating 3d and triggering events... or there is?

thanks for the reply

**Comment by mourner** [comment]
It shouldn't. It adds no overhead when there are no layers.

**Comment by IvanSanchez** [comment]
I'm closing this, as a request for more information was made more than one month ago but no further information has been provided.
