### ISSUE TITLE
Pinch zooming behaviour issues in v1.0.0 b2 compared to 0.7.7

### ISSUE THREAD

**Issue by fnicollet** [Leaflet/Leaflet#4006]
Hello,

I noticed that the behaviour of pinch zoom degraded between 0.7.7 and 1.0.0 beta2
Here is a jsfiddle for a simple map for 0.7.7:
http://jsfiddle.net/fnicollet/8r452bvp/
And the same with 1.0.0 beta2
http://jsfiddle.net/fnicollet/z0fps41d/

I am using a laptop with a touch screen, with Chrome (same bad behaviour in IE11). 
First test is simple, just pinch zoom until your fingers touch each other.
0.7.7 >> Correct behaviour, the map keeps zooming out
1.0.0 beta2 >> Zooming stops when your fingers are like 30px apart. Sometimes freezes the map, until you tap it again

Second test: pinch zoom out a little bit and keep both fingers on the screen, still
0.7.7 >> Correct behaviour, the map keeps doesn't barely zoom anymore
1.0.0 beta2 >> The map keeps doing little zoom in/out glitches, just as if the map was more "sensitive" to tiny changes when trying to keep still.

What do you think?
Fabien

**Comment by jjrv** [comment]
I've also run into this. When slowly zooming in with a pinch gesture, the zoom changes in small fractional increments. When it passes the previous zoom level plus 0.5, tiles are drawn from the deeper zoom level. For some reason, touch events stop coming at that moment, and the touchEnd event never fires. That leaves the map in a strange state, for example you cannot pan around with the mouse. If you then pan with a touch gesture and lift your finger, touchEnd finally fires and the map returns to normal.

**Comment by perliedman** [comment]
I think I have the same issue, tried with Leaflet's dev version as of today (2015-11-27), no plugins.

Look at this example: http://playground-leaflet.rhcloud.com/rik/

When I pinch zoom out on my laptop (Lenovo X1 Carbon running Ubuntu 14.04 and Chrome), the zoom freezes when I've zoomed out a bit, and repeating the pinch sometime snaps the zoom level back to where I started the zoom. It's very hard to zoom as desired.

An ugly video showing the problem (this is me *just* trying to pinch zoom out):

![pinchzoom](https://cloud.githubusercontent.com/assets/1246614/11445588/c51735b2-952d-11e5-8fe3-714a22f178b9.gif)

Is this known, tracked elsewhere? It seems like a pretty major problem unless it's just something on my machine.

**Comment by perliedman** [comment]
Good news is that I can't reproduce this on my phone. It might be that this only happens on desktop Chrome with a touch enabled screen?

Hard to debug, but I've at least figured out that when the map locks up, the `_onTouchEnd` method in `Map.TouchZoom.js` is never called, for whatever reason.

**Comment by fnicollet** [comment]
Might be related to:
https://github.com/Leaflet/Leaflet/issues/2693

**Comment by IvanSanchez** [comment]
@fnicollet @jjrv @perliedman Is this problem still relevant in the rc1 code? If so, would anybody be willing to spend some time to make a reproducible case with prosthetic-hand?

**Comment by fahad86** [comment]
Any workarounds for this?

**Comment by perliedman** [comment]
@IvanSanchez \o/ This bug does not occur in latest master, but in -beta.2!

**Comment by perliedman** [comment]
In case you're interested, I bisected, and this appears to be the commit that fixed this: 0cfe85897fef257d952d1cec5a5a11005fa66da0

**Comment by fnicollet** [comment]
I can confirm that the issue is fixed in master, thanks a lot :)
Fabien

**Comment by moklick** [comment]
I am using the current master but I still have a problem with pinch zoom. When I pinch to zoom out the map starts to zoom in and I end up at the same zoom level where I started. It's possible to zoom out but it feels very quirky. I have this issue on chrome 50/nexus 5 and safari 9.1/iPhone6.

**Comment by perliedman** [comment]
@moklick can you reproduce it with the example posted above (http://playground-leaflet.rhcloud.com/rik/)?

I tried that with my Nexus 6 / Chrome 50, and zooming works as expected.

**Comment by moklick** [comment]
That works fine! I will check my code and Leaflet version again. Thanks for the fast reply!
