### ISSUE TITLE
beta compatible plugins?

### ISSUE THREAD

**Issue by codeofsumit** [Leaflet/Leaflet#4007]
We're currently using leaflet beta 1 (soon v2) in a production environment as it ships with some bugfixes and features compared to the latest stable that we absolutely need.

Leaflet itself works fine but we're having a very hard time to find plugins that at least specify which beta version they're compatible with.
Leaflet.draw is our main concern right now. They have a master-leaflet branch that's supposed to work with the beta but there seem to be a lot of issues still.

Can anyone recommend plugins that work with the leaflet 1.0 beta releases? We're especially interested in drawing tools to edit (geojson) layers.

Thanks in advance for any advice.

**Comment by danzel** [comment]
Not really the place to discus this sorry.
Open bugs on leaflet.draw for the things that don't work, or maybe just post them in https://github.com/Leaflet/Leaflet.draw/issues/455
