### ISSUE TITLE
 Bug with twice event handling in 1.0.0-beta.2

### ISSUE THREAD

**Issue by NatonVanCliff** [Leaflet/Leaflet#4008]
By clicking on the polygon the event is twice handled on map listener and polygon listener.For marker such behavior is not observed. In version 0.8 dev it is work fine.

Examples:
[Leaflet 1.0.0-beta.2](http://jsfiddle.net/goleon/3250kgd8/)
[Leaflet 0.8-dev](http://jsfiddle.net/goleon/s70gqdqj/) 
See console output

 Checked in browsers: Chome, IE 11

**Comment by yohanboniface** [comment]
That's by design. Is that an issue for you?

**Comment by yohanboniface** [comment]
See https://github.com/Leaflet/Leaflet/pull/3605 for a bit of context.

**Comment by NatonVanCliff** [comment]
That's not issue for me.
In attached issue i found solution to my problem
Sorry, I immediately not found describe in the release notes.

Thank you.
