### ISSUE TITLE
bounce map

### ISSUE THREAD

**Issue by kennethhutw** [Leaflet/Leaflet#4011]
I would like to do button like Fly to Bern button in the below link.

Is it possible to do ?

http://openlayers.org/en/v3.2.1/examples/animation.html

var flyToBern = document.getElementById('fly-to-bern');
flyToBern.addEventListener('click', function() {
  var duration = 2000;
  var start = +new Date();
  var pan = ol.animation.pan({
    duration: duration,
    source: /** @type {ol.Coordinate} */ (view.getCenter()),
    start: start
  });
  var bounce = ol.animation.bounce({
    duration: duration,
    resolution: 4 * view.getResolution(),
    start: start
  });
  map.beforeRender(pan, bounce);
  view.setCenter(bern);
}, false);

**Comment by IvanSanchez** [comment]
> Is it possible to do ?

[Yes](http://homepage.ntlworld.com./jonathan.deboynepollard/FGA/questions-with-yes-or-no-answers.html).

A better question would be "How do I make a fly-to animation like this one?", to which the response is "[Check the `flyTo()` documentation of Leaflet 1.0.0-beta](https://mourner.github.io/Leaflet/reference.html#map-flyto)"

**Comment by kennethhutw** [comment]
Can I implement it by leaflet-0.7.2?

**Comment by mourner** [comment]
@kennethhutw unfortunately no, it's only available in 1.0 beta.

**Comment by kennethhutw** [comment]
@mourner  Thank you very much for your reply.
