### ISSUE TITLE
Error with bounds as array notation used on WMS layers

### ISSUE THREAD

**Issue by bohwaz** [Leaflet/Leaflet#4013]
If I add a WMS layer with boundaries like this:

     bounds: [[36.6582, -9.3054], [43.7698, 3.8899]]

(these are the boundaries of Spain)

I get this error in FireBug:

    TypeError: options.bounds.intersects is not a function
    if (!options.bounds.intersects([nw, se])) { return false; }
    leaflet-src.js (line 2768, col 39)	

This doesn't happen with a 'normal' tileLayer. And everything works if I first do this:

     layer.options = L.latLngBounds(layer.options);

Thanks!

**Comment by IvanSanchez** [comment]
@bohwaz How does the full layer definition feel like? What version of Leaflet are you using?

**Comment by bohwaz** [comment]
------- Original message -------
> From: Iván Sánchez Ortega <notifications@github.com>
> To: Leaflet@noreply.github.com
> Cc: bohwaz@bohwaz.net
> Sent: 16/11/'15,  23:22
> 
> @bohwaz How does the full layer definition feel like? What version of Leaflet are you using?

Latest stable version from the website, always.

**Comment by IvanSanchez** [comment]
This is covered in the 1.0.0 code. Doubtful whether we'll spend time to fix this in 0.7.x.

**Comment by mourner** [comment]
Closing because we just released 1.0 and minor issues in 0.7.x are unlikely to be fixed.
