### ISSUE TITLE
What are the reasons for setting detectRetina default to false?

### ISSUE THREAD

**Issue by ocefpaf** [Leaflet/Leaflet#4014]
This is not an issue.  Just a question.

I am wondering why the default value for  [detectRetina](http://leafletjs.com/reference.html#tilelayer-detectretina) is set to `false`.

Thanks!

**Comment by IvanSanchez** [comment]
Because we assume that the default webpage has "normal" pixel density, i.e. one CSS pixel equals 1 screen pixel, i.e. the CSS resolution is 1[dppx](https://drafts.csswg.org/css-values-3/#resolution).

**Comment by ocefpaf** [comment]
Thanks!

**Comment by mourner** [comment]
Also because it's a hack for situations when you want sharp tiles but don't have a retina-optimized tile source (512px, with adjusted label sizes, etc.).

**Comment by ocefpaf** [comment]
Makes sense. That explain some tiny labels I see sometimes.

Thanks!
