### ISSUE TITLE
fitBounds crashes map if new bounds include a corner in preexisting bounds (I think)

### ISSUE THREAD

**Issue by muziejus** [Leaflet/Leaflet#4015]
Here is a jsfiddle that recreates my error:

http://jsfiddle.net/5ez3h7cw/5/

I initialize a map with `setView([40.7308, -73.9975], 15)`.

If I set `fitBounds` to `[[40.7220936, -74.0016566], [40.7714327, -73.9676216]]` (or `brokenBounds`), the map hangs.

If I comment that line out and move the map to `[[41.7220936, -74.0016566], [41.7714327, -73.9676216]]` (or `workingBounds`) instead, `fitBounds` works as expected.

The bounds have the same cartesian size, and the only difference is that `brokenBounds` includes a corner that is in the original bounds as set with `setView`. 

If I set the original zoom in `setView` to 18, then the `fitBounds` works correctly with `brokenBounds`.

I'm currently getting around this by throwing in a `map.panTo([0,0]);` before calling `fitBounds`, since I know the dataset has no points near `[0,0]`. But this seems to be a clumsy hack.

**Comment by IvanSanchez** [comment]
@muziejus Please don't use old versions of Leaflet for your examples - that fiddle is using 0.6.x, several years old.

If this is reproducible in 1.0.0-beta, and is **not** the same as #3249, please feel free to comment/reopen.

**Comment by muziejus** [comment]
@IvanSanchez Thanks. I noticed the problem on 0.7.7, which is what I have on my development machine, but now that I've updated the fiddle to 0.7.7, the problem seems to have gone away. I'll look into using the beta on my project.

The description of #3249 (zoomed out and frozen) corresponds to the problem I was describing here.
