### ISSUE TITLE
Inertia scrolling and zooming does not feel "natural" (compared to OpenLayers)

### ISSUE THREAD

**Issue by derwaldgeist** [Leaflet/Leaflet#4017]
I am currently evaluating which JavaScript library I will use for mapping. The first library I found was OpenLayers, but then I stumbled upon Leaflet and was amazed by its "reduce-to-the-max" principle.

But there's one thing I am feeling very uncomfortable with in direct comparison with OpenLayers: the scrolling and zooming behaviour.
1. Both libraries support inertia scrolling, which is great. But the scrolling behaviour of OpenLayers feels much more "natural" on desktop PC's . The main reason for this is that it reacts on even the slightest "push", whereas Leaflet requires a rather "tough push" to give it enough inertia to scroll. This might be configurable somehow (I'm still a noob), but at least the standard behaviour is not really satisfying.
2. I'm using a Mac with the Apple MagicMouse. This mouse's surface can be used as a mouse button and as a scroll wheel at the same time, it is more like a touchpad than like a traditional mouse. If I grab the map to scroll it around, it quite often jumps wildly between zoom layers. It seems as if scrolling and zooming are triggered at the same time. This does not happen with OpenLayers, maybe they prevent zooming while dragging to suppress unwanted zooming.

I am not the one who tends to criticize each framework just after an hour of usage. But in this case, I thought it might be interesting for the dev team to get such a "noob feedback", since it is often the "first impression" that counts. :-)

**Comment by IvanSanchez** [comment]
> This might be configurable somehow (I'm still a noob) 

You have had a look at the [options for inertial drag](http://leafletjs.com/reference.html#map-inertia), right? ;-)

I don't see any difference with the [OpenLayers.Kinetic options](http://openlayers.org/en/v3.11.1/apidoc/ol.Kinetic.html). It might be worth to look into the source to see if the default values are different.

> Apple MagicMouse [...] it quite often jumps wildly between zoom layers.

That *might* be fixed with #3653. You'll have to test again when that code is merged.

**Comment by perliedman** [comment]
Closing this since it doesn't seem actionable and is very old.

Feel free to add direct suggestions on how to improve the feel of Leaflet's inertia, and we'll consider re-opening.
