### ISSUE TITLE
map.fitBounds issue with custom projection

### ISSUE THREAD

**Issue by MAD-GooZe** [Leaflet/Leaflet#4020]
Hello!

I am not quite sure if this is even a bug (or a bug of proj4leaflet library), but anyway.
I am trying to use Leaflet to display GeoJSON of Russia using EPSG:3576 projection. 

I have a problem with fitBounds method - when I try to fit the bounds of GeoJSON layer, map moves to some strange position. 
See the example at http://jsfiddle.net/MAD_GooZe/eomyf5qp/2/
The same also happens with maxBounds option - it limits map to some strange position.
Any ideas how this can be fixed?

**Comment by IvanSanchez** [comment]
@MAD-GooZe Please specify the Leaflet version you're using.

There is a similar issue, #3968. They might (or might not) be related. My guess is that there is a similar bug (a `LatLngBounds` object being calculated with just two and not four projected corners) somewhere in the code.

**Comment by MAD-GooZe** [comment]
I am using v1.0.0-beta.2

**Comment by perliedman** [comment]
@IvanSanchez correct me if I'm wrong, but even using all four corners might not necessarily solve this.

An axis-aligned box in lat-lng space, can end up with sides which are curved when reprojected, which in turn means that the max and min coordinates might not be at the corners, but rather somewhere along one of the sides.

I have no experience with EPSG:3576, but looking at the projected map in @MAD-GooZe's example, this might be the case here: the point with the minimum projected y-coordinate might not be the same as the point with the minimum latitude.

Using four corners is no doubt better than just two, but I don't think it will solve this in the general case.

**Comment by perliedman** [comment]
To get some insight to the complexities involved when transforming an evelope from one projection to another, have a look at GeoTool's code to do this: https://github.com/geotools/geotools/blob/master/modules/library/referencing/src/main/java/org/geotools/referencing/CRS.java#L1392

If this kind of complexity should be handled at all, I think Proj4Leaflet is probably a better place than in Leaflet's core.

**Comment by MAD-GooZe** [comment]
It looks like all bounds related stuff in Leaflet assumes Mercator projection (correct me if I`m wrong).

I made a dirty hack to fit the map to the territory of Russia (based on Leaflet code):
```javascript
function getPointsZoom(map, point1, point2) {
    point1 = L.latLng(point1);
    point2 = L.latLng(point2);
    var zoom = map.getMinZoom(),
        maxZoom = map.getMaxZoom(),
        size = map.getSize(),
        zoomNotFound = true,
        boundsSize;
    do {
        zoom++;
        boundsSize = map.project(point2, zoom).subtract(map.project(point1, zoom)).floor();
        zoomNotFound = size.contains(boundsSize);

    } while (zoomNotFound && zoom <= maxZoom);
    return zoom - 1;
}

function fitRussia() {
    var topRight = L.latLng([50.85360287457749, 186.81229925270603]);
    var bottomLeft = L.latLng([32.28195040994254, 46.99349796160391]);
    var zoom = getPointsZoom(map,
        topRight, bottomLeft
    );
    var center = L.latLng([71.06831305557495, 85.3104556226539]);
    map.setView(center, zoom);
}
```
Do you have any ideas if I can emulate maxBounds option in this case?
