### ISSUE TITLE
Customize layer control position and solve bug-changing layer

### ISSUE THREAD

**Issue by ivanssa** [Leaflet/Leaflet#4021]
Hello I'm using the leaflet with directive to make the google map and I have a problem to position the control layers I researched a lot and found the map.zoomControl.setPosition code ('bottomleft'); positioning the zoom control more get nothing to do the same with the layers and I am with this view with the code below (screen 1) and how I want to stay in (screen 2)

Another problem is that the control is over the issue bar that is solved when I add the class class = "has-header" in <leaflet> </ leaflet> but when I click to change the map to satellite it negates that class and returns to run out of the top margin (screen 3)

I thank those who could help follows the code below;

![mapas](https://cloud.githubusercontent.com/assets/3166174/11167019/a86b3642-8b2e-11e5-8c90-0454b9a1b291.jpg)

MapController.js
```

angular.extend($scope, {
                center: {
                    lat:mylat,
                    lng:mylng,
                    zoom: 14
                },
                layers: {
                    baselayers: {
			   googleRoadmap: {
                            name: 'Map',
                            layerType: 'ROADMAP',
                            type: 'google'
                        },
                        googleHybrid: {
	                        name: 'Satelite',
	                        layerType: 'HYBRID',
	                        type: 'google'
	                    }                       
                    },
					options: {
					position: 'bottomleft'
				}
                },
				markers: [],
				events: {}
			});
		
		  leafletData.getMap().then(function(map) {		
		   map.zoomControl.setPosition('bottomleft');
		   //control position - allowed: 'topleft', 'topright', 'bottomleft', 'bottomright'
		  });
     

```

Map.html
```
<ion-view title="Map" ng-controller="MapController" id="map" can-swipe-back="false">

	<ion-nav-bar class="bar-positive">
      <ion-nav-back-button>
      </ion-nav-back-button>
    </ion-nav-bar>

	<ion-nav-buttons side="left">
    <button menu-toggle="left" class="button button-icon icon ion-navicon"></button>
	</ion-nav-buttons>
  
    <ion-nav-buttons side="right">
    <button ng-click="locate();" class="button button-icon2 icon ln-magnifier ico-ajst"></button>
	</ion-nav-buttons>
  
	<leaflet lf-center="center"  layers="layers" markers="markers" width="100%" height="100%" class="has-header"></leaflet>

	 <ion-tabs class="tabs-icon-top tabs-positive">

        <ion-tab title="locate" icon="ln-locate" ng-click="locate();">
          <ion-nav-view name="about-tab"></ion-nav-view>
        </ion-tab>

      </ion-tabs>
	  
</ion-view>

```

**Comment by mourner** [comment]
Hey, thanks for using Leaflet! However, this is a place to report Leaflet issues, not to request support for your app. Please try asking on <a href="http://stackoverflow.com/">StackOverflow</a> — you are more likely to find help there.

**Comment by ivanssa** [comment]
Hello thank you, but doubts that reported refer to the bug when changing the map layer and the question of changing the options of layers buttons not found in any place and believed they were questions pertaining to the leaflet, more fine mourner thanks for return, I will turn to StackOverflow.

**Comment by ivanssa** [comment]
I managed to solve with some css below:

.leaflet-control-container {
display: block;
}

.leaflet-control-zoom {
left: 5px;
top: 50px;
}

.leaflet-control-layers {
left: 5px;
top: 50px;
}

.leaflet-touch .leaflet-control-attribution {
display: none;
}
