### ISSUE TITLE
zoomEnd event fired twice in master with FF & Chrome

### ISSUE THREAD

**Issue by ghybs** [Leaflet/Leaflet#4023]
Hi,

It looks like Leaflet master (and 1.0.0-beta.2) sometimes fires **twice** `zoomEnd` event after a zoom in our out, whether using the mouse wheel, zoom control buttons, or programmatical `map.zoomIn()` / `map.zoomOut()`.
- With Leaflet CDN 1.0.0-beta.2: http://jsfiddle.net/3v7hd2vx/11/
- With CloudFlare CDN 1.0.0-beta.2.rc.2: http://jsfiddle.net/3v7hd2vx/9/

However, Leaflet 1.0.0-b1 does not seem to have this issue (nor stable).
- With Leaflet CDN 1.0.0-b1: http://jsfiddle.net/3v7hd2vx/10/

I am using FF and Chrome on Ubuntu.

**Comment by IvanSanchez** [comment]
This is a regression introduced by 4eb39d531255a6deaf3f3c56fb24933d44f5eccc. It might be possible to hack around it by setting the `_animatingZoom` flag to false exactly when `_onZoomTransitionEnd` is called, but then you *might* hit the crazy iOS tile loading race condition that e15097dc1acc9cb80cab72bdbdb7355c77f1a9d0 fixed :-S

**Comment by czb** [comment]
Any solution to this nearby? It impact other libraries. Se e.g. 

https://github.com/Leaflet/Leaflet.markercluster/issues/646

**Comment by mourner** [comment]
@IvanSanchez why does it get called twice if the `_onZoomTransitionEnd` sets `_animatingZoom` to false?

**Comment by yohanboniface** [comment]
@mourner it's now only set through an anim frame, see https://github.com/Leaflet/Leaflet/commit/e15097dc1acc9cb80cab72bdbdb7355c77f1a9d0

I'm a bit worried about mixing setTimeout and requestAnimFrame, but I've no plan B to suggest (and I've no iOS at hand to investigate) :(

**Comment by yohanboniface** [comment]
Given the conversation here https://github.com/Leaflet/Leaflet/pull/3897 I'm tempted to suggest to remove the iOS hack until proven it's still needed in master.
Thoughts?

**Comment by perliedman** [comment]
The original fix (3e200bed22bdb1f59e54f37c93b4fce034fd7ee4) protects a call to `_resetView`, while the current code in master doesn't call `_resetView` directly, but only indirectly by when calling `_moveEnd`.

How about just calling the `_moveEnd` inside the `requestAnimFrame`? Might of course introduce some other race.
