### ISSUE TITLE
how to trigger event "locationfound" with a location

### ISSUE THREAD

**Issue by lincoln310** [Leaflet/Leaflet#4027]
Hi, i want to trigger "locationfound" with a specified location. How to do that?
By the way, we have the system to locate the location more presizly.

**Comment by IvanSanchez** [comment]
This is a bug tracker, not a place to ask questions. The place to ask questions is [StackOverflow](https://gis.stackexchange.com/questions/tagged/leaflet).

> Hi, i want to trigger "locationfound" with a specified location. How to do that?

```
map.fire('locationfound', {latlng: foo, bounds: baz, timestamp: quux});
```

Also read through https://github.com/Leaflet/Leaflet/blob/master/src/map/ext/Map.Geolocation.js . Consider making a plugin with a structure similar to that file.

**Comment by lincoln310** [comment]
sorry to the mistake.
