### ISSUE TITLE
Define rotation for ImageOverlay

### ISSUE THREAD

**Issue by SuberFu** [Leaflet/Leaflet#4029]
I'm trying to overlay an image on the map using information from a KML file. I noticed that there's an additional field for rotation which indicates how much the original image need to rotate on the map.

I noticed that this can be resolved by adding a "rotate()" transform to the image-layer's transform style with the degree that's inverted (KML says -5, add rotate(5deg) lines it up).

Is it possible to add the functionality to define a rotation for the L.ImageOverlay?

P.S. Is there a work around? Something like attaching a moveend event handler to the layer and adding an additional rotate through jQuery?

**Comment by SuberFu** [comment]
Note sure if this helps. But I found a working (at least for me) workaround by extending the L.ImageOverlay as followed
```javascript
L.rotateImageLayer = function(url, bounds, options) {
    return new L.RotateImageLayer(url, bounds, options);
};
// A quick extension to allow image layer rotation.
L.RotateImageLayer = L.ImageOverlay.extend({
    options: {rotation: 0},
    _animateZoom: function(e){
        L.ImageOverlay.prototype._animateZoom.call(this, e);
        var img = this._image;
        img.style[L.DomUtil.TRANSFORM] += ' rotate(' + this.options.rotation + 'deg)';
    },
    _reset: function(){
        L.ImageOverlay.prototype._reset.call(this);
        var img = this._image;
        img.style[L.DomUtil.TRANSFORM] += ' rotate(' + this.options.rotation + 'deg)';
    }
});
```
The Google's KML rotation is defined in the opposite direction, so I had to set the options.rotation value to the negative of Google's KML rotation definition.

**Comment by perliedman** [comment]
This isn't supported out of the box, but I think you might be interested in the [Leaflet.imageTransform](https://github.com/ScanEx/Leaflet.imageTransform) plugin, and there is also [Leaflet.DistortableImage](https://github.com/publiclab/Leaflet.DistortableImage) which does similar things.

**Comment by DexiongYung** [comment]
https://github.com/IvanSanchez/Leaflet.ImageOverlay.Rotated

There's this by some nice fella
