### ISSUE TITLE
L.GeoJson not load a good json data, throw "n is null or undefined" on the error console

### ISSUE THREAD

**Issue by p4535992** [Leaflet/Leaflet#4035]
Hello, I use Leaflet already for a while, and I've never had this error, when I try to load with L.GeoJson a correct data content file, it's returns "n is undefined," , I try to find the problem by myself , but I did not succeed, so i pray for your help.
```javascript
//Here mi json file to test, in the specific is a geoJson.
//https://cdn.rawgit.com/p4535992/repositoryForTest/master/testWitSources/fileForTest/test.json

//The line fo code where is throw the error:
var content = ..... //my json content parsed and all, checked with other functions.
var layer = L.geoJson(content,layerOptions);

//Firefox say  -> "n is undefined or null"; 
//Chrome say ->  "cannot read property 'geometries' of undefined"
```
**NOTE**: i use the leaflet version from remote of the documentation    <script src="http://cdn.leafletjs.com/leaflet-0.7/leaflet.js"></script>

**Comment by mourner** [comment]
Your GeoJSON is not valid. E.g. this line: https://github.com/p4535992/repositoryForTest/blob/master/testWitSources/fileForTest/test.json?short_path=79b58d9#L1129
