### ISSUE TITLE
Using image overlay with base64 data url

### ISSUE THREAD

**Issue by kuvark** [Leaflet/Leaflet#4037]
Hi,

I ve tried to load image on map with base64 dataurl. But it didnt worked.

Also i ve created an image object and gave source to image overlay. It did'nt worked. 

       var img = new Image();
        img.onload = function() {
            loadMap(img);
        };
        img.src =  myBase64src;

function loadMap(img){
        var map = L.map('map_draw', {
            maxZoom: 32,
          }).setView(mapCenter, 0).fitBounds(imageBounds);

        L.imageOverlay(img.src, imageBounds).addTo(map);
}
Any idea?

**Comment by IvanSanchez** [comment]
> Any idea?

Yes: ask in GIS stack exchange, because github issues is only for reporting bugs.

https://gis.stackexchange.com/questions/tagged/leaflet

**Comment by kuvark** [comment]
Thanks Ivan. I thought that, this is a bug. sorry about that

**Comment by IvanSanchez** [comment]
@kuvark If you think it's a bug, make it sound as a bug. I suggest you read http://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by kuvark** [comment]
Ok. thanks.

**Comment by IvanSanchez** [comment]
@kuvark Also, when it's a bug, it's always a good idea to provide an example of the bug in action. And FYI, base64-encoded image overlays work just fine: http://playground-leaflet.rhcloud.com/bexi/edit?html,output

**Comment by kuvark** [comment]
@IvanSanchez thanks for all good replies. And i really sorry about taking your time.
