### ISSUE TITLE
Clear geojson layers

### ISSUE THREAD

**Issue by kha67** [Leaflet/Leaflet#4038]
Hi,
I want to make dynamic map with dynamic json file generated by php. to avoid slowing down the display, I generate json depending on bounds and zoom, but my probleme is to how clear the old geojson layers

for exemple the "removeLayer" here don't work:

```
map.on('moveend', function() {
     var geojson;
     map.removeLayer(geojson);
     geojson = L.geoJson(statesData, {
			style: style,
			onEachFeature: onEachFeature
      }).addTo(map);
});
```

**Comment by IvanSanchez** [comment]
```
     var geojson;
     map.removeLayer(geojson);
```

Why are you trying to run `map.removeLayer` passing an empty variable as a parameter?

Next time please reserve the github issues for bugs, and ask your usage questions at https://gis.stackexchange.com/questions/tagged/leaflet

**Comment by kha67** [comment]
Ok sorry.
