### ISSUE TITLE
Markers' zindex property ignored in Chrome

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#4042]
We know markers are assigned a `zindex` CSS property so that the lower ("south-er") markers are shown on top of the upper ("north-er") ones.

For some weird reason, my Chrome (46.0.2490.71) ignores the CSS property, or otherwise doesn't create a z-stacking context for the markers.

Left: Firefox (OK). Right: Chrome (not OK).
![markers-zindex](https://cloud.githubusercontent.com/assets/1125786/11333506/72948a7c-91ce-11e5-9d40-e844ec4ea9de.png)

Using leaflet Master from CDN, live example at:
https://ivansanchez.github.io/Leaflet.Icon.Glyph/demo.html

**Comment by mourner** [comment]
I think this is a plugin bug — the markers lack `position` property set to absolute or relative to have zIndex working.
