### ISSUE TITLE
add bounds, multiple bounds

### ISSUE THREAD

**Issue by kaynz** [Leaflet/Leaflet#4043]
Hi,

current state of TileLayer bounds:

    When this option is set, the TileLayer only loads tiles that are in the given geographical bounds.

I would like to set multiple bounds, e.g.:

    bounds: [latlngBounds1, latlngBounds2, latlngBounds3]

to achieve following: 
![multiple bounds](https://cloud.githubusercontent.com/assets/12952835/11333764/7fb54f64-91d0-11e5-9eb9-12a18b915ae9.png)

How can I achieve this with leaflet? Is there a plugin which does this?

Thanks!

**Comment by mourner** [comment]
Someone would need to write a plugin, which should be too hard to do. However this is out of scope for Leaflet core, so closing the issue.
