### ISSUE TITLE
Custom Icons for Markers become Offset (when there are multiple custom icons)

### ISSUE THREAD

**Issue by JohnHanks** [Leaflet/Leaflet#4047]
I can provide my markup in a later comment.  I did want to open this issue however since defining the iconAnchor (or not) for one of my custom icons will offset ALL of my custom icons, but only sometimes.  I will play with my code in order to provide some fiddles in order to help everyone properly debug this.

My popups render in the correct place.  I can see the proper locations for all my markers if I render them as circlemarkers.  But again, if I use custom markers, everything is offset strangely and moves around alot when zooming.

**Comment by yohanboniface** [comment]
@JohnHanks please provide a minimal test case to demonstrate the issue (http://playground-leaflet.rhcloud.com/ may help).

**Comment by IvanSanchez** [comment]
No more information has been provided, and more than a few weeks have passed. We'll assume this issue is no longer relevant and/or there is no interest to make a better report.
