### ISSUE TITLE
For whom i send my examples repo for add this in official web site ?

### ISSUE THREAD

**Issue by jonatasfreitasv** [Leaflet/Leaflet#4052]
https://github.com/jonatasfreitasv/Leaflet_Examples

**Comment by IvanSanchez** [comment]
Oi, @jonatasfreitasv, if you want to add something to the official website, make a pull request against the `gh-pages` branch. It's quicker if you modify the website including the examples, and then we can review those changes.

**Comment by IvanSanchez** [comment]
Also, read: https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md#improving-documentation

**Comment by jonatasfreitasv** [comment]
Thx @IvanSanchez !!!

**Comment by jonatasfreitasv** [comment]
Which site area you indicate ? @IvanSanchez

**Comment by IvanSanchez** [comment]
@jonatasfreitasv You probably want to have a look at https://github.com/Leaflet/Leaflet/blob/gh-pages/examples.md and https://github.com/Leaflet/Leaflet/tree/gh-pages/examples

I suggest you clone the Leaflet repo, switch to the `gh-pages` branch, run jekyll as described in `CONTRIBUTING.md`, and play with `examples.md` and the files in the `examples/` directory.

**Comment by jonatasfreitasv** [comment]
Nice ! Thx.

**Comment by jonatasfreitasv** [comment]
ps.: your site [http://ivan.sanchezortega.es](http://ivan.sanchezortega.es) is offline.
