### ISSUE TITLE
How to get a unique id or name of a new base layer selected by the user?

### ISSUE THREAD

**Issue by derwaldgeist** [Leaflet/Leaflet#4054]
I've implemented the Layers control on top of my map and would like to react on base layer changes by the user. Goal is to store the layer name alongside with lat/lng information in the database, so I can restore both the correct location and the base layer that had been active at that time.

The ```onbaselayerchange``` event does deliver a ```name``` property, but unfortunately this name is also used for the display of the layer in the Layers control, so I had to use a language-specific string here (to be able to internationalize my app).

So I cannot use this name to identify the selected base layer. There is also a ```layer``` property delivered with the event, but I could not find any useful information in this ILayer object to re-construct the layer at a later time. The only thing I found is the URL pattern.

It would be really helpful if the Layers control would use the ```name``` for id purposes only and use a separate displayName for the display in the control, so one could separate both things. Or did I miss something that I could use instead?

**Comment by IvanSanchez** [comment]
The github bug tracker is no place for asking questions on how to use Leaflet (hint: it's for tracking *bugs*).

Ask in the forum or in gis.stackexchange.com.
