### ISSUE TITLE
Add API to automatically set zoom so given points are displayed

### ISSUE THREAD

**Issue by gdesmott** [Leaflet/Leaflet#4056]
I'd like to make sure that user's position is displayed as well as one (or more) point(s).
map.fitBounds() does the trick but the user postion and given point are spread on each side of the map while I'd like to keep the map centered on the user position. An API keeping the map current position but ensuring all the given points are displayed by adjusting the zoom would be useful for this use case.

**Comment by IvanSanchez** [comment]
Use `getBoundsZoom` for getting the zoom level you want, then call `setView` with the center you want and the zoom you just got.

Just remember to calculate the bbox of the points, and make a symmetric bbox using the user position as the origin of the [point symmetry](https://en.wikipedia.org/wiki/Point_reflection). This will ensure the behaviour you want.

I think this use case is very specific, so adding a whole new API method would not be very beneficial.
