### ISSUE TITLE
Leaflet on secure connections (https)

### ISSUE THREAD

**Issue by pierrebonbon** [Leaflet/Leaflet#4059]
This is a rather obvious fix and not really an issue, but I thought I should share just in case anyone else runs into the same problem. 

If you're trying to use Leaflet on a secure connection, map rendering will break, regardless of whether you're serving the tiles yourself or through a secure connection. You will want to serve Leaflet.css and Leaflet.js locally (as a dependency). Another alternative is to add Leaflet.css programatically to your project. Download the following library and add it as a dependency: 

https://github.com/leaflet-extras/leaflet.css: 

Explanation: Since Leaflet is delivered over an unsecure network, rendering of the tiles will break if you attempt to serve Leaflet.css and Leaflet.js through Leaflet's unsecure CDN links. 

You may then serve the tiles yourself or use a provider that serves them over a secure protocol. See this: 

https://github.com/Leaflet/Leaflet/issues/3186#issuecomment-155360520

**Comment by mourner** [comment]
Or you can just use CDNs that support secure connections, like https://npmcdn.com/.
