### ISSUE TITLE
Problems with MultiPolygon GeoJSON in Internet Explorer

### ISSUE THREAD

**Issue by silentHoo** [Leaflet/Leaflet#4060]
Hi all, I've spent several hours identifying the "long running script" issues with leaflet on Internet Explorer 10, 11 and Edge. And I've found out, that big MultiPolygons will crash Internet Explorer if the user doesn't wait until all calculations for all polygon layers are done. And this can take up to minutes.

The problem in my webapp is, that I must add GeoJSON features to the map right after initialization. It's a central use case that the user can select a single country with just one click. This will highlight the country in a different style.

All works good if I have single Polygons, but if I use MultiPolygons (e.g. for enclaves or countries which own regions spread over the world) then IE have a lot of work to do.

To fix this problem I've tried all together:

* Reducing the amount of data points by using the integratet Simplify.js (http://mourner.github.io/simplify-js/) which uses the Douglas-Peucker algorithm
* Using `geoJsonLayer.addData` instead of pushing all data at once with `L.geoJSON(geoJsonFeatures)`
* Using async approaches with `setTimeout`s

Do you have any idea how I can handle this?

Currently I use this approach:

````
var simplifyGeometry = function(geometry) {
	var simplifyPolygon = function(polygonCoordinates) {
	  var coordinates = polygonCoordinates.map(function(point) {
		return {
		  x: point[0],
		  y: point[1]
		};
	  });

	  return L.LineUtil.simplify(coordinates, 0.1).map(function(point) {
		return [point.x, point.y]
	  });
	};

	if (geometry.type === 'Polygon') {
	  geometry.coordinates[0] = simplifyPolygon(geometry.coordinates[0]);
	} else if (geometry.type === 'MultiPolygon') {
	  geometry.coordinates.forEach(function(c, index) {
		geometry.coordinates[index][0] = simplifyPolygon(c[0]);
	  });
	}

	return geometry;
};

featureCollection.features.forEach(function (f, index) {
	if (f.geometry) {
	  featureCollection.features[index].geometry = simplifyGeometry(f.geometry);
	}
});

layer['country'] = L.geoJson(featureCollection, {
	style: function () {
	  return defaultCountryStyle
	},
	onEachFeature: function (feature, localLayer) {
	  // when clicking on a layer, we want to highlight the clicked polygon
	  localLayer.on('click', function (e) {
		if (selectedCountry.featureLayer) {
		  // unselect last highlighted country
		  selectedCountry.featureLayer.setStyle(defaultCountryStyle);
		}
		// set highlight style only for clicked country
		localLayer.setStyle(highlightCountryStyle);

		selectedCountry = {
		  code: feature.properties.ISO2,
		  featureLayer: localLayer
		};
		$rootScope.$emit('mapService:countryClicked', {code: feature.properties.ISO2});
	  });
	}
}).addTo(myMap);
````

I don't know if this issue is caused by applying the styling, so maybe it would be better to do that work async.

**Comment by mourner** [comment]
It's hard to say what may be the problem here before we see a minimal test case here, e.g. in http://playground-leaflet.rhcloud.com/ or JSFiddle. It may be related to the way MultiPolygons are implemented in Leaflet 0.7.* — can you try the same data in Leaflet 1.0 beta 2? It might improve performance significantly.

**Comment by silentHoo** [comment]
@mourner This worked perfectly. Performance is now lightning fast in Internet Explorer. Thanks for your advice using beta 2.

**Comment by mourner** [comment]
Awesome!
