### ISSUE TITLE
IE11 regression in 0.7.7

### ISSUE THREAD

**Issue by jmullo** [Leaflet/Leaflet#4061]
Something leaks or loops when clearing & adding markers derived from L.Path to L.LayerGroup while panning the map. UI becomes slower and slower until starts to freeze totally.

Works fine in 0.7.5.

**Comment by IvanSanchez** [comment]
I'm gonna guess this is directly related to #4041

**Comment by jmullo** [comment]
Yep, I also see those addEventListener() calls taking time when profiling.

**Comment by davojta** [comment]
Seems that [that commit] (https://github.com/danzel/Leaflet/commit/4b289ab8071e480c182bb5df76bbfe0cac2a54e0)  broke IE11 in stable

**Comment by davojta** [comment]
I will try figure out more about cause of the bug and prepare a new release with fix )

**Comment by mourner** [comment]
@danzel hmm I think I remember seeing some discussions of perf problems with pointer detection, want to take a look?

**Comment by danzel** [comment]
It's probably related to this one:
https://github.com/Leaflet/Leaflet/issues/3972#issuecomment-152373252

@jmullo do you have a prepared test so I can reproduce this easily?

**Comment by jmullo** [comment]
Nope, pretty hard to detach from our code...

"Only affects repeatedly adding and removing markers on IE(11/10) with a touch device."

Not a touch device in my case.

**Comment by Monduiz** [comment]
I have the same issue. I had to revert to version 0.7.5 so the applications I am developing can work on IE 11.

**Comment by mourner** [comment]
Closing as duplicate of #4357
