### ISSUE TITLE
On 1.0beta2, Map.fadeAnimation option inteacts with GridLayer.opacity option

### ISSUE THREAD

**Issue by rgrocha** [Leaflet/Leaflet#4068]
In fact, a false Map.fadeAnimation prevents any opacity option on GridLayer taken into account.

I think I've found the problem on src/layer/tile/GridLayer.js:

The blame view on the _updateOpacity() function gives us the result:

```javascript
 		// IE doesn't inherit filter opacity properly, so we're forced to set it on tiles
-		if (!L.Browser.ielt9 && !this._map._fadeAnimated) {
-			L.DomUtil.setOpacity(this._container, opacity);
+		if (L.Browser.ielt9 || !this._map._fadeAnimated) {
 			return;
 		}
 
+		L.DomUtil.setOpacity(this._container, this.options.opacity);
```

You can see those two sentences groups are not equivalent: **!( !a && !b)** is not **a || !b**, it should be **a || b**.

This could make sense on the logic side, but we will have another interaction: GridLayer.setOpacity() will never update the opacity if Map.fadeAnimation is true.

The Map.fadeAnimation should be only taken into considetation if called from the GridLayer._initContainer() function, not from GridLayer.setOpacity() or GridLayer._tileReady() functions.

Perhaps a new boolean parameter on _updateOpacity() could do the job.

**Comment by IvanSanchez** [comment]
I can confirm this. Setting `fadeAnimation: true` in the map options for `debug/tests/tile-opacity.html` makes the example fail.

**Comment by IvanSanchez** [comment]
See #4228
