### ISSUE TITLE
bower install leaflet --save

### ISSUE THREAD

**Issue by epartipilo** [Leaflet/Leaflet#4073]
Working in a team, both made 'bower install leaflet --save' and one of us was getting into bower_components: 'leaflet/Leaflet-0.7.7/dist/' and the other one 'leaflet/dist/' so always had problems on pulling the changes of project.

The workaround was instead of the bower instruction mentioned before, we did a 'bower install https://github.com/Leaflet/Leaflet/archive/v0.7.7.zip --save' pointing direct to the .zip and both got the same project structure.

I did not figure out what was the problem, maybe different NODE versions. But was weird.

By the way. Good job on the Leaflet library.

**Comment by IvanSanchez** [comment]
Non-reproducible, and there's a workaround, so closing. Everyone's moving away from Bower anyway now, anyway.
