### ISSUE TITLE
anchor popup to point feature dynamically on zoom event?

### ISSUE THREAD

**Issue by JasonFitz** [Leaflet/Leaflet#4076]
..not sure if this is an issue or just something I haven't figured out yet...

We have an app that uses divIcons for point markers.  The markers change size at different zoom levels (by using a variable concatenated into the html tag for the icon).  We also need to re-anchor the popup at different zoom levels for the different sized markers.
Is there a way to do this?

I tried adding the offset as a variable in the popup properties, but that hasn't worked:
  var popupOptions = {        
        autoPan:true,
        closeButton: false,
        minWidth: 220,
        maxWidth: 220,
        zoomAnimation:true,
        offset: curOffset
      };

**Comment by IvanSanchez** [comment]
I guess this is a user issue. Just use some CSS hack to modify the (negative) margin of your `DivIcon` on each zoom level change. Normal `Icon`s and `DivIcon`s are anchored using negative margins IIRC.

**Comment by JasonFitz** [comment]
The problem is not the divIcon, it is the popup anchor.

**Comment by IvanSanchez** [comment]
Have you tried modifying the `popupAnchor` property of the icon (on every zoom level change)?

You might also be able to modify the popup's (negative) margins if you're zooming with the popup open.

**Comment by JasonFitz** [comment]
That is what I posted above. I tried to add the offSet as a variable which is reset at each zoom level, but it didn't work.  I'll look into a css solution, but since the popup is a point based on the marker position (correct?) I would rather modify the popup property if possible.

**Comment by JasonFitz** [comment]
hmm, I tried to reposition the csss of the leaflet-popup dynamically with JQuery, but that's not working either..I think using the popup anchor property would be best if possible.

**Comment by IvanSanchez** [comment]
The problem is that allowing users to change the `popupAnchor` property dinamically involves a lot of changes and testing to code that reliably, and it's not worth it (in my opinion) to code that into the leaflet core.

Please do look into a CSS solution. Keep the offset at [0,0] so you can manipulate it reliably with your code.

Also, refer to stackexchange to ask user questions like this one.

**Comment by JasonFitz** [comment]
I postede there first: http://stackoverflow.com/questions/34097715/mapbox-reset-a-popup-offset-dynamcally .. no responses though.  Isn't using different sized icons (therefore different popup anchors)  for different zoom levels common? 

I tried getting the current top (to start) using Jquery:
var curTop = $('.leaflet-popup').position().top;

then modifying this, but this just throws the popup way off (maybe since the default value for top is auto?)
Thanks for your ideas.

**Comment by IvanSanchez** [comment]
Update the `popup.options.offset`, then call the private method `popup._updatePosition`. It's not the cleanest, but it should work.

**Comment by JasonFitz** [comment]
OK thanks foir idea.
If I understand you correctly, I would need to name the popup (here you named it 'popup')?  I tried it like this:
  thisPopup = new L.Popup({
        autoPan:true,
        closeButton: true,
        minWidth: 220,
        maxWidth: 220,
        zoomAnimation:true,
        offset: [0,4]
      });

and then used 'thisPopup' the way you described...but the offset is not updated, in fact it seems to revert to a default setting of [0,7] when i view the preoperty in consloe after a zoom:
console.log(thisPopup.options.offset);

**Comment by JasonFitz** [comment]
( in an older version of this app, we were able to pretty easily set the iconAnchor property as a property of 'icon' in the geoJSON, then modify this dynamically on a zoom..that version used markerLayer):

 markerlayer.features.push({	
                type: "Feature",
                geometry: {
                    type: "Point",
                    coordinates: [item.longitude, item.latitude]
                },
                properties: {
                name: item.stationName, 
                bikes: item.availableBikes,
                docks: item.availableDocks,
                status: item.statusValue,
                "icon": {
                    "iconUrl": 'img/icons/sign.svg',
                    "iconSize": SizeIcon,
                    "iconAnchor": AnchorIcon, 
                    "popupAnchor": PopBikeIcon,
                    }
                    
                }
