### ISSUE TITLE
Code Exceeds JS Function Boundaries and Fires Instantly

### ISSUE THREAD

**Issue by DoubleExposure** [Leaflet/Leaflet#4086]
The following code is in a javascript function within a file called maplocation.js that is supposed to fire only on a button click but instead it fires automatically when the page loads for the first time. The code does not wait for the button click but loads the map instantly. On button click it is supposed to add a new image of a car  to the location.

    window.map.panTo([data.Data.LatLng.Lat, data.Data.LatLng.Lng]);

                            var vehicleIcon = L.icon({
                                iconUrl: settings.mapIcon,
                                iconSize: [22, 25],
                                iconAnchor: [11, 20],
                                popupAnchor: [0, -22]
                            });

                            L.circle([data.Data.LatLng.Lat, data.Data.LatLng.Lng], 140, { color: 'Green' }).addTo(window.map);

                            L.marker([data.Data.LatLng.Lat, data.Data.LatLng.Lng], { icon: vehicleIcon }).addTo(window.map).bindPopup("<b style='width:200px;'>" + settings.mapTitle + "</b><br />");

**Comment by IvanSanchez** [comment]
This doesn't sound like it's a bug in leaflet - and we only use this issue tracker for bugs. Do read [contributing.md](https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md) carefully again for pointers on where to ask these kinds of questions.

**Comment by DoubleExposure** [comment]
How is this not a bug? Your code is not supposed to do this. If it is a wrong use of the api then where is the error handling?

**Comment by DoubleExposure** [comment]
Ok, sorry for not following the recommended procedures.

**Comment by IvanSanchez** [comment]
> How is this not a bug? Your code is not supposed to do this.

Why are you so sure our code is not "supposed to do this"? How can *I* be sure it is not a problem in your code instead?

For example, you're talking about stuff not firing on `click`, but I can see no code that refers to event click handlers. I cannot be sure you are *not* calling a event handler outside of the event.

I must encourage you to read [how to report bugs effectively](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html)
