### ISSUE TITLE
Max latLngBounds

### ISSUE THREAD

**Issue by assaad** [Leaflet/Leaflet#4088]
Hello,
If I want to overlay an image on the whole world, what would be the latlngBounds? 
Thanks!

**Comment by IvanSanchez** [comment]
This doesn't sound like it's a bug in leaflet - and we only use this issue tracker for bugs. Do read [contributing.md](https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md) carefully again for pointers on where to ask these kinds of questions.
