### ISSUE TITLE
Scale control breaks on custom projection

### ISSUE THREAD

**Issue by emacgillavry** [Leaflet/Leaflet#4091]
this.options.crs.distance is not a function

[Test case](http://bl.ocks.org/emacgillavry/raw/1a654b76d35deceb9bec/) using EPSG:28992 (Amersfoort New)

Using in conjunction with Kartena plugin.

**Comment by perliedman** [comment]
This is a bug in Proj4Leaflet, since its CRS class doesn't implement the `distance` method.

I've created https://github.com/kartena/Proj4Leaflet/issues/109 as a result.

A quick-hack workaround is to just set `crs = L.CRS.Earth.prototype.distance` for now!

Thanks for reporting!

**Comment by emacgillavry** [comment]
Thank you for follow up! Will keep track of
https://github.com/kartena/Proj4Leaflet/issues/109

**Comment by perliedman** [comment]
An updated workaround until this is fixed, to handle the fact that `L.CRS.Earth.distance` needs the earth radius as a constant:

```
crs.distance = L.CRS.Earth.distance;
crs.R = 6378137;
```

**Comment by huyongdi** [comment]
兄嘚，1.3.4版本也出现了这个问题
