### ISSUE TITLE
.leaflet-container img max-width too !important

### ISSUE THREAD

**Issue by Spaxe** [Leaflet/Leaflet#4092]
The following CSS code prevents someone from including `<img>` tags in popup embedded in a marker with a max-width set, because the max-width is, apparently, `!important`.

    /* .leaflet-container svg: reset svg max-width decleration shipped in Joomla! (joomla.org) 3.x */
    /* .leaflet-container img: map is broken in FF if you have max-width: 100% on tiles */
    .leaflet-container .leaflet-overlay-pane svg,
    .leaflet-container .leaflet-marker-pane img,
    .leaflet-container .leaflet-tile-pane img,
    .leaflet-container img.leaflet-image-layer {
      max-width: none !important;
    }

Could we consider taking the `!important` out and properly isolate whichever issue this is trying to patch?

**Comment by IvanSanchez** [comment]
Hhhmmm. What about defining a custom pane for those popups?

**Comment by IvanSanchez** [comment]
The change comes from https://github.com/Leaflet/Leaflet/commit/c75af44ca2ed736cbff98a8b6d417b04355e275c , apparently. It might be a good idea to make the CSS selector more specific to avoid images inside popups, though.

**Comment by Spaxe** [comment]
@IvanSanchez I would support a more definitive CSS selector, yes. Discussion welcome.

**Comment by yohanboniface** [comment]
Humm, something does not turn to me: popups are in the `leaflet-popup-pane`, which is not targeted by the `!important` trick. Can you set up a minimal test case to demonstrate the issue in a more specific way (http://playground-leaflet.rhcloud.com/ may help)?

**Comment by Spaxe** [comment]
@yohanboniface I was using the example from https://github.com/PaulLeCam/react-leaflet#getting-started, which nests popup inside a marker.

**Comment by yohanboniface** [comment]
Oh, OK. Weird way of implementing Leaflet. But I guess I'm too old to get on the React way of coding.

Anyway, my opinion is that this way of nesting popup inside a marker is not compliant with Leaflet and should not be encouraged. Leaflet has panes just for controlling this kind of things. (Also, it will go into trouble regarding the zindex of markers vs popups). Note that the `!important` trick is already a workaround for some third party hacks conflicts (Bootstrap among others), see https://github.com/Leaflet/Leaflet/commit/61d746818b99d362108545c151a27f09d60960ee#commitcomment-6062234 for example.

**Comment by Spaxe** [comment]
Darn Bootstrap.

Anyway, I agree with you, that implementation is weird and you aren't really obliged to stop using `!important`, however bad practice it is quoting yourself :]

I'll close this now. So far I've been using a workaround by specifying `width` in my projects and dance around `max-width`.
