### ISSUE TITLE
GridLayer event tileunload not firing in all cases

### ISSUE THREAD

**Issue by tcoats** [Leaflet/Leaflet#4093]
In three cases the event on GridLayer `unloadtile` is not fired. Is it intended to be always called when a tile is removed or unloaded from a GridLayer? I'd like to use it to keep track of other tasks I'm performing per tile and at the moment I have no way to know when a tile is unloaded other than check the dom element.

https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/GridLayer.js#L44
https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/GridLayer.js#L219
https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/GridLayer.js#L284

I'm happy to put through a pull request with a fix if useful.

**Comment by IvanSanchez** [comment]
Yeah, I think this is a good small improvement. I'm not sure of the exact semantics (should it be `tileunload` or `tilecancel` or what?), but it seems like a good idea that belongs to the code core.

I think we would appreciate a PR - specially if you could include some example/test of this functionality (in the `debug/` directory).

**Comment by tcoats** [comment]
An implementation seems to be already started here:
https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/GridLayer.js#L556

The event is `tileunload`.

**Comment by tcoats** [comment]
All good to proceed with a PR by firing a 'tileunload' event from these three locations?

https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/GridLayer.js#L44
https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/GridLayer.js#L219
https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/GridLayer.js#L284

**Comment by IvanSanchez** [comment]
#4099 looks good! :+1: 

See also 6a283294fa582fba16b2cbe641cb9bb6dd2ef13a
