### ISSUE TITLE
BBOX coordinates rounding in WMS requests

### ISSUE THREAD

**Issue by mfilocha** [Leaflet/Leaflet#4095]
Tile bounding box coordinates generated by WMS requests have no fixed numerical format. That results in slightly different URLs generated by different browser. This is not a problem for a WMS server, but if you try to use a generic web accelerator (like Varnish) in front of this WMS server, requests for the same tile coming from different browsers are handled as separate requests and cached more than once.

Rounding to 2 decimal places (or even to integer number) should be sufficient for such cases.

Leaflet 0.7.7, FF 42.0, MS Edge 25.10x. Example page: http://geo.nebula.grid.icm.edu.pl/

**Comment by IvanSanchez** [comment]
I'm going to say "no" on this one. WMS requests were never designed to be easily cache-able, and if Leaflet rounds up coordinates, I bet there will be edge cases where users of weird CRSs will hit rounding problems.

If you need caching, I encourage you to use [MapProxy](http://mapproxy.org/), as handles tiling schemes (unlike Varnish *et al*).

**Comment by perliedman** [comment]
I agree with @IvanSanchez: avoid hardcoding assumptions that happen be correct for you specific environment. Also +1 regarding using cache tailored for handling tiles, WMS + Varnish sounds like setting up for problems.

However, if you really want to do this, overriding `L.TileLayer.WMS.getTileUrl` is really easy!

**Comment by mfilocha** [comment]
I'm well aware of that class of caching solutions. In my case, varnish act as a load balancer and "first line" cache for a cluster of Geoserver+GeoWebCache instances. Anyway, I'm dropping few lines below for varnish users (tested for EPSG:3857 coordinates), just in case.

```
sub vcl_hash {
  hash_data(regsub(req.url,"(.*)BBOX=(-?\d*\.?\d{0,2}).*?,(-?\d*\.?\d{0,2}).*?,(-?\d*\.?\d{0,2}).*?,(-?\d*\.?\d{0,2}).*","\1BBOX=\2,\3,\4,\5"));
  return (hash);
}
```
