### ISSUE TITLE
opacity option broken in IE9 for GridLayer in Leaflet master

### ISSUE THREAD

**Issue by msiadak** [Leaflet/Leaflet#4096]
The opacity option for L.TileLayer.WMS seems to be broken in IE9 in the current Leaflet master.  I haven't done any digging into the commit history to hunt down the cause yet, but here's a fiddle (and some screenshots) that show the issue.  

http://jsfiddle.net/tugpa0L5/1/

### IE9
![ie9](https://cloud.githubusercontent.com/assets/1743015/11821880/56c2d640-a331-11e5-96be-19dff0555410.png)

### Firefox 42.0 (working correctly)
![firefox](https://cloud.githubusercontent.com/assets/1743015/11822076/629cc9c0-a332-11e5-9032-795477a22046.png)

**Comment by msiadak** [comment]
I did some digging through the source.  It looks like the problem is the check in the `_updateOpacity` method of L.GridLayer.  See https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/GridLayer.js#L162-L164

IE9 is failing the check because `L.Browser.any3d` is false for it, which causes `this._map._fadeAnimated` to be false.  There's a comment referencing setting opacity on tiles individually, but I wasn't able to find where this was happening elsewhere in the code.

I'm not familiar enough with the codebase, project history, and CSS opacity browser compatibility issues to suggest a fix. Looks like this block was changed to fix another nasty opacity issue (#3652). Any feedback from those more familiar with the issue would be much appreciated.

**Comment by msiadak** [comment]
Somehow I missed #4068 when submitting this.  This is a duplicate of that issue.

**Comment by IvanSanchez** [comment]
@msiadak Thanks for taking the time to investigate the issue and notice it's a duplicate! :-)

Please subscribe to notifications about #4068 - we can always use an extra pair of eyes (and an extra IE9) to test a fix when it becomes available.
