### ISSUE TITLE
How can I use a map designed with map box studio (the new version)?

### ISSUE THREAD

**Issue by otmezger** [Leaflet/Leaflet#4097]
Hi, 

I tried to use a map created with map box studio (the new version, not map box studio classic), but can't figure out a way of getting the ID of the map. 

Is leaflet compatible with the new version of map box? 

thanks.

**Comment by perliedman** [comment]
Hi and thanks for using Leaflet!

However, this is an issue tracker for bugs and new features in Leaflet, not a forum for questions, and this does not appear to be a bug in Leaflet.

I guess you will be better of asking Mapbox's support, or perhaps on [gis.stackexchange.com](gis.stackexchange.com), or even Stackoverflow.
