### ISSUE TITLE
Big controls in IE

### ISSUE THREAD

**Issue by bas-jansen** [Leaflet/Leaflet#4101]
Internet Explorer (I tested IE10 and IE11) shows big zoom and layer controls on desktop.
The browser is detected as 'touch' browser: The 'leaflet-touch' class is added to the top div

**Comment by IvanSanchez** [comment]
This is expected behaviour; read the comments on #3944, and [this one](https://github.com/Leaflet/Leaflet/issues/3944#issuecomment-148703870) in particular.

**Comment by bas-jansen** [comment]
ok, thanks for the quick response
