### ISSUE TITLE
L.circle getBounds() issue

### ISSUE THREAD

**Issue by imShara** [Leaflet/Leaflet#4102]
`L.circle` `getBounds()` returns bounds with shifted lattitude.

![007436944-ptlrgqquczosrqgggxgzbfvvyirzgmbf](https://cloud.githubusercontent.com/assets/4913196/11905731/09dad5c6-a5d9-11e5-9dae-1865afb723aa.png)

```js
var map = L.map('map').setView([51.505, -0.09], 8);

L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
    attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
    minZoom: 5,
    maxZoom: 10,
    id: 'mapbox.streets',
    accessToken: 'pk.eyJ1IjoiZG9ub3RidWdtZSIsImEiOiIzTDhlVzJFIn0.yaAnv7Tlc0ROYQe0-e5BNw'
}).addTo(map);

var circle = L.circle([51.505, -0.09], 200000, {
  stroke: false,
  fill: true,
  color: '#f00',
  opacity: 0.5
}).addTo(map);

var rectangle = L.rectangle(circle.getBounds(), {
  stroke: false,
  fill: true,
  color: '#00f',
  opacity: 0.5
}).addTo(map);
```

[JSFidde example](https://jsfiddle.net/089y1b3u/1/)

**Comment by celadevra** [comment]
This is a bug only in v0.7.7 but not in v1.0.0. I believe 7ff0fa9 and onwards have solved this issue. So is it necessary to back port changes to tag v0.7.7? Or should we just tell people to use v1.0.0?

**Comment by mourner** [comment]
Oh, I see. Yeah, I believe it's not worth backporting — it's not a blocking issue.
