### ISSUE TITLE
Fix retina in 1.0

### ISSUE THREAD

**Issue by hyperknot** [Leaflet/Leaflet#4103]
There are two ways of displaying retina resolution titles.

**Real retina tile rendered on server**
In this mode, instead of loading `1/2/3.png` leaflet of size 256x256 pixels, the client is downloading `1/2/3@2.png` of size 512x512 pixels and displaying in as higher resolution version of the original. Mapbox JS does this.

**Fake retina / underzoom on client**
In this mode, the client is composing 4 tiles from the next zoom level to create 1 tile. This is a hack and while it works for layers like satellite without lables, it produces unreadably small text for anything else. Leaflet calls this option `detectRetina`.

In Leaflet 0.7 the only way to enable real retina was to use something like: `{z}/{x}/{y}' + (L.Browser.retina ? '@2x' : '') + '.png'` in the tileLayer url.

The problem is that in Leaflet 1.0, leaflet started supporting the `{r}` part, and at the moment these two concepts are mixed, and it's only possible to enable both of them or none-of them. When both are enabled, you get 4 times the tile downloads, as well as the downsides of fake retina's tiny texts.

The problematic lines are:
https://github.com/Leaflet/Leaflet/blob/92e449a0ce7cacedec169c9f24fcddbc985ef707/src/layer/tile/TileLayer.js#L79
combined with
https://github.com/Leaflet/Leaflet/blob/92e449a0ce7cacedec169c9f24fcddbc985ef707/src/layer/tile/TileLayer.js#L28

This is because `r: this.options.detectRetina && L.Browser.retina && this.options.maxZoom > 0 ? '@2x' : ''`

I think there are two options here:
- rename `detectRetina` to `fakeRetina` and use `detectRetina` to actually detect real retina tiles (that is use the `{r}` part if present).
- just use real retina tiles whenever `{r}` is present. That would mean changing the line to simply:
`r: L.Browser.retina ? '@2x' : ''` Probably the better choice, since it'd be backwards compatible with Leaflet 0.7. Users who would like not to enable retina, would just remove the `{r}` part from the url.

**Comment by mourner** [comment]
Hmm you're right! The second approach looks better to me.

**Comment by yohanboniface** [comment]
@hyperknot do you mind opening a pull request with option 2?

**Comment by hyperknot** [comment]
No,  I'm happy to do it!

**Comment by IvanSanchez** [comment]
Fixed in #4110.
