### ISSUE TITLE
Leaflet block map

### ISSUE THREAD

**Issue by kha67** [Leaflet/Leaflet#4104]
Can you tell me if you know the reason of this blocked map when i put

if (zoomLevel<13 && map.hasLayer(contacts) ) {
					//map.removeLayer(contacts);
				}

I can't move on the map but when I put this

if (zoomLevel<13  ) {
					//map.removeLayer(contacts);
				}

there is no issue

**Comment by danzel** [comment]
Please create a jsfiddle to reproduce this.
What do you mean by 'blocked map' ?

**Comment by kha67** [comment]
Think You
http://jsfiddle.net/VaGy5/475/

 if (map.getZoom()<10 && map.hasLayer(square)) {
      map.removeLayer(square);
  } 

Don't work and the map is blocked

But with this the script work
 if (map.getZoom()<10 ) {
     // map.removeLayer(square);
  } 

for example, I want to remove the layers when zoom is under 10

**Comment by kha67** [comment]
http://jsfiddle.net/VaGy5/476/

I want to remove "square if zoom is under 10

**Comment by danzel** [comment]
In the example you've posted, square is not defined the first time it is used.

**Comment by kha67** [comment]
Ok thinks, Before I was putting "var square" after "map.on('moveend', function() { "

But now I put it Before and it works thinks
