### ISSUE TITLE
Map Portions that are not displayed when expand the area

### ISSUE THREAD

**Issue by ivaalfo** [Leaflet/Leaflet#4106]
Regards. I have a similar problem, but not the same as described in #4069.
When I expand the visible area (ZoomOut) there are portions of the map that is no displayed until I move the map.
If not actually be a bug or not, as it happens in some PCs and not in others.
Leaflet Version: 0.7.7
PS: the option that the problem resides in the browser  version/model is excluded.

Any solution? Thanks

**Comment by yohanboniface** [comment]
@ivaalfo your issue is missing elements for us to be able to answer.
Best thing you could do is to create a minimal test case for reproducing the bug, for example with http://playground-leaflet.rhcloud.com/ or http://jsfiddle.net/

**Comment by IvanSanchez** [comment]
I'm closing this, as a request for more information was made more than one month ago but no further information has been provided.

**Comment by AkshyKumarS** [comment]
Hi, I have worked with a React project that uses the leaflet to show the map feature. I am also getting the error @ivaalfo mentioned. Below is the video that shows.
I have used the Geojson layering the to render the map.

https://user-images.githubusercontent.com/60968632/145685733-afd05a8f-7dc1-4e68-a164-6e1f8567c151.mp4

Code for reference:
`<MapContainer
    style={containerStyle}
    center={[10, 0]}
    zoom={2}
    minZoom={2.4}
    maxZoom={10}
>
    <MapConsumer>
        {(map) => {
            map = map
            return null
        }}
    </MapConsumer>
    <button className="map-reset">
        <img src={resetIcon} alt="reset-icon" id="reset-button" onClick={resetMapView} />
    </button>
    <GeoJSON style={contryStyle} data={features} onEachFeature={onEachCountry} ref={geoJsonRef} />
    <MapChild />
</MapContainer>`

Thanks

**Comment by Falke-Design** [comment]
@AkshyKumarS you can add this code to re-render the layer while moving:
```
map.on('move',(e)=>{
	map._renderer._update()
})
``

**Comment by AkshyKumarS** [comment]
It works fine. Thank you...!
