### ISSUE TITLE
L.GeoJson.AddData() (replace, or update GeoJSON data)

### ISSUE THREAD

**Issue by DrYSG** [Leaflet/Leaflet#4115]
Would it be possible that the L.GeoJson.AddData() return the created sub-layer, instead of the top GeoJson layer? Alternatively, could GroupLayer.find() [in addition to a <layer> or <id>] take a predicated function that can return true (so I can search the feature.properties)?

Why? (currently using Leaflet 1.0Beta2)

I am using Leaflet GeoJson to show live data in a GeoJSON (point, line, polygon). It is a CRUD interface (Create, Update and Delete). I receive WebSocket messages with GeoJSON data, each one with a GUID. 

I the case of a **CREATE** I just do a GeoJSon.AddData() to the appropriate layer.

But for the **UPDATE** and **DELETE** I want a handle for the layer that was added to the GeoJSON so that I can update its location, or update the Geometry. addData is not giving me this handle. And it is really hard to get it from onEachFeature() or from pointToLayer()

Currently, I do have a way that works but ugly. I have to do is search the entire layer with GeoJSon.eachLayer(fn)
whenever an update or delete occurs. It seems a bit expensive.

{even if Leaflet is not truly engineered for this live r/t display of data, it is working, and it seems sad if you cannot use it for watching a lot of sensor data, IoT) as we are doing.

```javascript
        this.delete = function (layerName, feature) {
            if (!(layerName in self.myLayers)) {
                alert("live.display: Missing Layer: " + layerName);
                return;
            }
            var layerInfo = Live.myLayers[layerName];
            var base = layerInfo.layer;
            var id = feature.properties.objectID;
            this.find(layerName, id, function (layer) {
                this.removeLayer(layer);
                Tools.debug(16, "live.delete:", "killed object: " + id);
            });
        }
        this.find = function (layerName, id, action) {
            var base = Live.myLayers[layerName].layer;
            base.eachLayer(function (feature) {
                if (!("objectID" in feature.feature.properties)) { return; }
                var objectID = feature.feature.properties.objectID;
                if (objectID == id) {
                    action.call(base, feature);
                }
            });
        }

```

**Comment by perliedman** [comment]
You might want to have a look at [leaflet-realtime](https://github.com/perliedman/leaflet-realtime), which does almost exactly what you are talking about. It's perfectly possible to accomplish with ’onEachFeature’.

I don't think reworking the API for GeoJSON is something we need at this point, and extra functionality should rather be handled through plugins.

**Comment by DrYSG** [comment]
@perliedman do consider an extended version of GroupLayer.find( <fn>) so that a function can run through all the layers (in this cases the properties) and return a list of features where the properties match a criteria. I think that would be appropriate at the base Leaflet layer (not an add-on) and would also be well within the simplicity, succint goals of leaflet. (filter is only for adding data to begin with)

For my case, real-time is not what I want, since i am also working with the author of Leaflet.Timeline to provide for analysis of logs of the real-time data, to allow scrubbing, and they use different ideas as to what the layers should be and how they work (probably indicates, that a middleware layer above Leaftet-core would be useful, so that folks can layer on compativel features (e.g. For  the Timeline I would like to merge in features from PouchLayer, but it is also hard to do).

**Comment by DrYSG** [comment]
@perliedman BTW, I see you are the author of Leaflet.realtime. I am not saying anything bad about it. It is good work. But in my case I am getting the data via a stand-alone host for C#/.NET SIGNALR, http://www.asp.net/signalr which is very good for low latency, rapid update push from a server. (I would have used Node.JS, but the server has to also talk to the a UDP source of messages (https://lcm-proj.github.io/) and  that was not possible. I getting to like Signlar, since I can also host the Leaflet pages in it via static-files.

I do not want a pollling solution from the client, if I can avoid it.

**Comment by perliedman** [comment]
@DrYSG didn't mean you necessarily should use leaflet-realtime, just that you might want to look at the code to see how it accomplishes what you're talking about: it can find out which layers to add, update or delete when new data arrives, without resorting to looping over layers.

Using `onEachFeature`, you can map features to Leaflet layers with very few lines of code, and layers are already mapped to features using the `feature` property, so I'm not convinced there is a need to add something like `find`/`filter` etc. into core.

**Comment by rowilsonh** [comment]
help, I have the same problem

**Comment by perliedman** [comment]
@rowilsonh Thanks for using Leaflet!

Please note that this is our issue tracker, where bugs and feature requests and posted and discussed. For questions on how to use Leaflet and other support, you're better off using [stackoverflow](https://stackoverflow.com/) or [gis.stackexchange.com](https://gis.stackexchange.com/).
