### ISSUE TITLE
L.CircleMarker.bringToFront throws an error

### ISSUE THREAD

**Issue by ntilwalli** [Leaflet/Leaflet#4117]
CodePen:  http://codepen.io/anon/pen/VemMam
Leaflet bundled w/ Mapbox version: 2.2.3

I am adding two circleMarkers to a map and when I call `bringToFront` on one of them I see this in the console:
```
VM896 mapbox.js:7 Uncaught TypeError: Cannot read property '_pathRoot' of undefined
```
What am I misunderstanding about how to use `bringToFront`?

This is similar to https://github.com/Leaflet/Leaflet/issues/2439, except the layers are added to the map in this case so it seems unrelated.

**Comment by ghybs** [comment]
Hi,

You have to set a map view before your layers are actually added to the map.
Updated CodePen: http://codepen.io/anon/pen/LGbOVO

So I guess it **is** the same as #2439.

Hope this helps.

**Comment by ntilwalli** [comment]
Ah. That solved it!  Thanks!
