### ISSUE TITLE
Small issue with removeLayer

### ISSUE THREAD

**Issue by DecSander** [Leaflet/Leaflet#4118]
Hey, so I recently switched to browserify and while making the transition, I noticed a small issue and was wondering if anybody else has come across this. When I call map.removeLayer(marker) on a marker, I get `Uncaught TypeError: Cannot read property '40' of undefined`

I tracked down the issue and it seems to be coming from line 1692 in leaflet-src.js. `if (!this._layers[id]) { return this; }` After some debugging, I realized the issue comes from the fact that `this` as used in the function references the window rather than the map object, so `this` doesn't have a property `_layers`

The odd thing is that when I checked the function above, addLayer, it is able to grab `this` (as in the map object) correctly. Any ideas? Thanks!

**Comment by hyperknot** [comment]
When you switch to Browserify, you also stop being in the "everything is global" world of classic browser js development, and you have to take great care of what variable is accessible and what is not. 

Try `console.log(marker)`, `console.log(map)`, etc. to see what is your variable doing. Lot of people are using Leaflet in browserify, and I believe the codebase is really well tested agains this usage, so there shouldn't be a bug in common functions like `removeLayer()`.

**Comment by DecSander** [comment]
Yep, that seems to have done it. Looks like I was calling it wrong or something because when I put it in a wrapper class (i'm using a map over an array)
```
function removeObj(layer) {
  return map.removeLayer(layer);
}
```
rather than just using `map.removeLayer` by itself, it worked. Probably didn't set map in the correct order. Thanks!
