### ISSUE TITLE
Allow viewing different area on site main page

### ISSUE THREAD

**Issue by jidanni** [Leaflet/Leaflet#4119]
On http://leafletjs.com/ we see a sample map of London.

But there is a very big chance potential users would like to see how a different area looks before choosing leaflet,

Therefore a choice should be added there, allowing users to see instead somewhere else too, without needing to zoom all the way out, move to another continent, then zoom back in.

**Comment by jidanni** [comment]
Also add a permalink link to a corner of that map.

Some users might want to use that map to check if a problem occurs in a certain area and report back to you.

**Comment by yohanboniface** [comment]
@jidanni seems your confusing Lealfet, which is a javascript library to display maps, with the map itself.
With Leaflet, you can display many maps, OpenStreetMap based or not, and it comes with no default map.
See for example this plugin for some easy to set up choices: http://leaflet-extras.github.io/leaflet-providers/preview/

**Comment by jidanni** [comment]
Mainly in https://www.facebook.com/groups/OpenStreetMap.TW/permalink/969547683110701/
we are trying to find out who to blame for putting village names right
on top of boundaries, on opencellid.org. We see "leaflet" there in the corner...

**Comment by yohanboniface** [comment]
> map data: OpenStreetMap© | ODbL 1.0, tiles: CC-BY-SA 2.0

**Comment by yohanboniface** [comment]
And specifically, if you are on the rendering, you should talk here: https://github.com/gravitystorm/openstreetmap-carto/

**Comment by matkoniecz** [comment]
Note that https://github.com/gravitystorm/openstreetmap-carto/ should be used only for developing openstreetmap-carto - this particular map style is either badly outdated version or some fork.

**Comment by jidanni** [comment]
> map data: OpenStreetMap©
By the way, that links to http://www.openstreetmap.org/ .
Couldn't it better link to http://www.openstreetmap.org/#map=17/24.20816/120.74495 (if that link is indeed made by leaflet.)
