### ISSUE TITLE
flyTo not working with google maps plugin

### ISSUE THREAD

**Issue by thatgirlcancode** [Leaflet/Leaflet#4120]
I made some minimal updates to the google maps leaflet  plugin to be compatible with leaflet 1 beta, following this PR:

https://github.com/shramov/leaflet-plugins/pull/175

If you select OSM as the baselayer, flyTo works. If a Google baselayer is selected, the flyTo animation does not work. No errors are thrown. I wonder if it's even possible to use flyTo in conjunction with a google layer? 

My plunk > http://plnkr.co/edit/ouynceGB0XvjWk7TkWoh?p=preview

**Comment by perliedman** [comment]
This is most likely a problem with the Google Maps Leaflet plugin, not an issue with Leaflet itself. You should create an issue with [Leaflet Plugins](https://github.com/shramov/leaflet-plugins)

**Comment by j16sdiz** [comment]
This is because leaflet support  non-integer zoom level, but google map don't.
When you try to set a non-integer zoom level, the google layer reset it to the nearest integer.

**Comment by j16sdiz** [comment]
For ZoomAnimation, google layer listen to 'zoomanim' event and use the google's internal zoom animation.

I think an event is needed for flyTo to implement this.

**Comment by joemesk** [comment]
googlemap zoom -1 for compability with mapbox or leaflet
