### ISSUE TITLE
Adding a meters-based geojson layer

### ISSUE THREAD

**Issue by Aaron-Pool** [Leaflet/Leaflet#4121]
Hey guys,

Well, I've been on the hunt for a solution to this for nearly two days now, with limited success. I'm working on a GIST-based project, and I'm getting fed geojson from a server. It's in projection ESPG 3857, and the units are in meters. Suffice to say, when I try to add the geojson layer to the map, nothing shows. I'm assuming this is because the geojson coordinates are expected to be in degrees. I've looked everywhere for a solution to this, but can't seem to find any. I tried looping through my coordinates and using map.unproject on them, but that gave me a ridiculous result for most points(as in o.LatLng {lat: -90, lng: 643277.095706718} ridiculous).

So, what do I do? How do I take my geojson in meters and get them to display on a leaflet map?

**Comment by hyperknot** [comment]
@Aaron-Pool you are mixing a few concepts here. ESPG 3857 by definition only takes coordinates in WGS 84 degrees and it has no understanding of meters or any length units.
https://en.wikipedia.org/wiki/Web_Mercator

If you have meters you are using a projection what is not ESPG 3857. If you could figure out what projection you are using, you can transform your geometry to 3857 via various tools.

**Comment by Aaron-Pool** [comment]
@hyperknot 

Ok, I actually found out its that the geojson is already projected for me. Is there a way I can add a geojson layer and disable it being projected, since that process has already been done for me?

**Comment by perliedman** [comment]
@Aaron-Pool you can either use the [`coordsToLatLng`](http://leafletjs.com/reference.html#geojson-coordstolatlng) option to make your own transformation from your projection to lat/lng (WGS84), or you can use [Proj4Leaflet](https://github.com/kartena/Proj4Leaflet), which already has builtin projection support for GeoJSON.
