### ISSUE TITLE
Leaflet CDN get an internal error late at night

### ISSUE THREAD

**Issue by m3talstorm** [Leaflet/Leaflet#4123]
Using the Leaflet CDN over at: http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css

Getting this response at 05:51 Thursday, 31 December 2015 (GMT)

    <Error>
    <Code>InternalError</Code>
    <Message>
    We encountered an internal error. Please try again.
    </Message>
    <RequestId>BDE055075F3242B3</RequestId>
    <HostId>
    rJ6nP1PNc+7X+6pcL6pTRRyQR+2w1h/qQaCkkU70SOaNJ/qPBPHHuD5vomET/rylYRHSymwSCLM=
    </HostId>
    </Error>
This seems to be a recuring problem around this time of night/early morning, it normally fixes itself within 30 mins or less.

**Comment by mourner** [comment]
Sorry, nothing I can do about it - it's some type of internal Amazon CloudFront problem. You can try alternative CDNs like cdnjs and npmcdn.
