### ISSUE TITLE
Layer Register

### ISSUE THREAD

**Issue by WangXiaoLun** [Leaflet/Leaflet#4128]
I wish the leaflet can increase a function, layer's registration . We are now much handling of layer on layer is added to the map, but I hope the layer has not been added, you can do some processing, such as take out Ploygon's render to draw, and now this process must be added on the map to achieve, but if you can at the time of registration will be able to get the render to do a lot of processing.

**Comment by IvanSanchez** [comment]
There is no benefit of adding such a "registration" workflow. In particular...

> if you can at the time of registration will be able to get the render to do a lot of processing.

...leaflet doesn't *render* anything. Leaflet adds elements to the webpage's DOM, and then the browser renders it. There is no way for leaflet to render something without adding it to the webpage first.

Adding layers in a detached state would just add a lot of complexity (check detached layer's bbox, etc), with no tangible benefits.
