### ISSUE TITLE
Double "grabbing" cursor on Chrome on Win10

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#4130]
When trying to investigate #4127, I stumbled upon a double sighting of the "grabbing hand" cursor:

![win10-double-cursor](https://cloud.githubusercontent.com/assets/1125786/12168609/a1d3da08-b533-11e5-897a-5c3be0cb06dd.png)

Apparently there is a win10 "grab" cursor and then a chrome "grab" cursor, and the latter lags a bit behind the former.

This is using chrome 47.0.2526.106 in Win10 enterprise evaluation build 10240 inside Virtualbox, and Leaflet 1.0.0-beta2.

I'm going to do a wild guess and say it's a platform-specific CSS bug. It might not be worth to investigate if it cannot be reproduced easily.

**Comment by IvanSanchez** [comment]
It might be an upstream bug, as it is reproducible outside of leaflet webpages (case in point, horizontal scroll thingie in developer console:)

![win11-double-cursor-devconsole](https://cloud.githubusercontent.com/assets/1125786/12169889/80327a36-b53c-11e5-9add-aa57bf6753b2.png)

**Comment by mourner** [comment]
Yes, let's close and reopen if it turns out to be fixable on the Leaflet side.
