### ISSUE TITLE
Game Map

### ISSUE THREAD

**Issue by kauegimenes** [Leaflet/Leaflet#4138]
I am looking for a framework to build a custom game map and i would like to know if Leaflet is able to support this.

If yes, please share some tutorials or demos if you have any.

Thanks.

**Comment by mourner** [comment]
Leaflet is being used for game maps a lot, just google "leaflet js game map". E.g. here's one of the first results: http://googlemapsmania.blogspot.com/2014/05/mapping-game-worlds-with-leaflet.html
