### ISSUE TITLE
invalidateSize()

### ISSUE THREAD

**Issue by lrusnac** [Leaflet/Leaflet#4139]
I'm doing some animations with a map (using velocity.js), I need to change the size of the div and the map should stay centered on the same point. I created a fiddle to illustrate the problem.

https://jsfiddle.net/n236wLcm/

it works nice and smooth for me on chrome but not on firefox or edge, or even qtwebview. I need the animation to be smooth.

during the animation I'm continuously calling invalidateSize(). I dug in the code  and I saw that in the end the invalidate size uses `translate` to move things.

I don't know if somebody had this type of issue.

**Comment by mourner** [comment]
I don't think you should be calling `invalidateSize` that often. Can you throttle it to, say, 100ms? This seems like app-specific issue rather than something that should be fixed on the Leaflet side.

**Comment by lrusnac** [comment]
well, there is no way of making invalidateSize with an animation for instance

**Comment by IvanSanchez** [comment]
The leaflet-active-area and Leaflet.ControlledBounds plugins (http://leafletjs.com/plugins.html#events) might help - also, check the code for both to have an idea to how difficult it is to keep things centered. You might need to do some plugin to make your animations work.

**Comment by lrusnac** [comment]
thanks
