### ISSUE TITLE
svg element click fails, and stopPropagation fails, 1.0.0-beta.2

### ISSUE THREAD

**Issue by jimmont** [Leaflet/Leaflet#4144]
L.version 1.0.0-beta.2 Chrome  47.0.2526.111 OSX 10.10.5
Clicking an svg element with `.on('click', <handler>)` fails to fire or register at all. Solution (in my case) was to use css: `.leaflet-container .leaflet-overlay-pane svg {pointer-events: fill;}` which overrides the svg element's `pointer-events="none"` inline attribute and the events now register with my handler. :+1: +1
With this in-place I then had an issue with the click event propagating up to a (conflicting) click-handler on the map itself. `<click-event>.originalEvent.stopPropagation()` didn't work. Debugging showed that `<click-event>.originalEvent._stopped = true` resulted in the callback-event system effectively stopping propagation of the event to the map without any obvious issues. :+1: +2 These both appear to be bugs (or quite very possibly, my ignorance of some important details and stuff :-1: -5).

**Comment by yohanboniface** [comment]
Can you please provide a minimal testcase to reproduce the issue (with http://playground-leaflet.rhcloud.com/ or any jsfiddle like service) ?

**Comment by hassoncs** [comment]
I ran into this same problem and was able to fix it with your <click-event>.originalEvent._stopped = true; approach. :+1:

**Comment by IvanSanchez** [comment]
No more information has been provided, and more than a few weeks have passed. We'll assume this issue is no longer relevant and/or there is no interest to make a better report.
