### ISSUE TITLE
Fractional zoom tiles not loading at map edges

### ISSUE THREAD

**Issue by hyperknot** [Leaflet/Leaflet#4145]
Just made an example for the 1px fraction tiles bug and realised in master, the tiles near the map edges do not load:
http://jsbin.com/ratoli/5/edit?html,js,output

In beta 2 they load OK.

**Comment by IvanSanchez** [comment]
Looks like an off-by-one error somewhere in the tile loading logic. We shall use `debug/tests/tile-bounds.html` to locate the error.

**Comment by hyperknot** [comment]
It's introduced with https://github.com/Leaflet/Leaflet/commit/e2fbe196
cc: @yohanboniface

**Comment by IvanSanchez** [comment]
Should be fixed by #4156
