### ISSUE TITLE
Is it possible to access EPSG:3857 coordinates in leaflet?

### ISSUE THREAD

**Issue by 5chdn** [Leaflet/Leaflet#4146]
Is it possible to access EPSG:3857 metric coordinates in leaflet *without* triggering spherical reprojections (to/from degree)? I am researching a performance critical task and wish to use the metric units rather than the degree units. Is this possible?

What I've done so far is this:

    L.point(
        L.Projection.SphericalMercator.project(
            map.getBounds().getNorthEast()
        ).x * 6378137.0,
        L.Projection.SphericalMercator.project(
            map.getBounds().getNorthEast()
        ).y * 6378137.0
    );                                       // Point(1497143.40914, 6895833.38915)

I'm asking because I read somewhere that EPSG:3857 is the internally default used projection. Could you clarify on this? Thanks!

**Comment by mourner** [comment]
How would you avoid spherical reprojections if degrees are spherical, and EPSG3857 are projected metric units?

**Comment by IvanSanchez** [comment]
Short answer: no.

Long answer: Internally, Leaflet transforms EPSG:4326 coordinates to *pixel coordinates*. These pixel coordinates are the EPSG:3857 coordinates divided by a power of 2 (and then rounded).

It might be possible to fetch some of these coordinates (look at methods like `L.Map.latLngToLayerPoint`) and then multiply stuff given the zoom level, but beware of rounding errors.

And in the future, please refrain from asking questions in the bug tracker - we want to use it for, you know, *tracking bugs*. Please have a look at https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md#reporting-bugs

**Comment by 5chdn** [comment]
Thanks for the quick reply. Now I get the pixel coordinates. I was withholding this question for half a year now, I had the hope I would get it on stackexchange: http://gis.stackexchange.com/q/153849/13692

Excuse me for abusing your bug tracker to get a shortcut on the answer. :-) :heart:

**Comment by IvanSanchez** [comment]
Wow, you waited half a year. Then everything is forgiven ;-) :+1:
