### ISSUE TITLE
Best way to cancel pending tiles requests or Ajax requests?

### ISSUE THREAD

**Issue by mehany** [Leaflet/Leaflet#4149]
I notice that Leaflet cancels ajax requests at a certain point when there is a lot of panning, zooming or other activities that causes a layer to request additional tiles which works good in different cases. Furthermore, when the map changes layers and the layer being rendered is still waiting for tiles, those requests don't get canceled and causes a major delay with the rendering of the new requests because first comes first serve type of thing. 
P.S:to simplify what I am after, i wish there is a magic method that would clean up everything that is not needed for current viewport.

**Comment by perliedman** [comment]
Leaflet doesn't do AJAX, it loads images using the standard `img` DOM element.

However, it aborts loading under some circumastances, you can check how it's done here: https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/TileLayer.js#L140

Basically, setting the `img` element's `src` to an empty image makes the browser abort the loading operation.

**Comment by IvanSanchez** [comment]
This is a duplicate of #3765 anyway.

**Comment by mehany** [comment]
@perliedman @IvanSanchez thanks. what would be a leaflet way to abort loading those tile images. Something like MyTileLayer. abortLoading().
