### ISSUE TITLE
GeoJSON MultiPolygon style not resetting after resetStyle

### ISSUE THREAD

**Issue by deristnochda** [Leaflet/Leaflet#4152]
I am having problems with resetStyle on a mouse-out event after highlighting a GeoJSON polygon. If a certain style attribute is not set in the default style (in the [JSFiddle](https://jsfiddle.net/LtLube2k/): color) the resetStyle does work for a simple Polygon but not for a MultiPolygon. However, if the attribute is set in the default style (in this case: fillColor), the resetting works.

I used Leaflet 0.7.7 and checked with Safari and Chrome on Mac OS 10.11.2.

**Comment by yohanboniface** [comment]
Can you check with 1.0.0-beta2?

**Comment by deristnochda** [comment]
The behaviour is changed in 1.0.0beta2 and consistent for both types, see  http://jsfiddle.net/c4gn7qy7/2/ 

So the only question that remains is, wether or not resetStyle should reset to the default style that is not explicitly set in the GeoJSON (in the JSFiddle: color that does not change back to default blue). Or is this the intended behaviour?

**Comment by yohanboniface** [comment]
Seems fixed to me in master: http://playground-leaflet.rhcloud.com/fow/edit?html,output

I don't think we will backport in stable given that's not critical, so I'm closing. Feel free to reopen if you disagree :)
