### ISSUE TITLE
#832b43ac breaks Leaflet.Editable line guides

### ISSUE THREAD

**Issue by hyperknot** [Leaflet/Leaflet#4153]
// Opening this here, as it might have a more general effect, not just Editable.

https://github.com/Leaflet/Leaflet/commit/832b43ac587553372264046a98f769beb06d4b6f breaks the 2nd+ line guides in Leaflet.Editable. 

Reproducing: just draw 2 polygons or polylines in the official Editable example:
http://leaflet.github.io/Leaflet.Editable/example/index.html

It throws error at: 
```
L.Polyline._project
...
if (this._bounds.isValid()) {
			pxBounds.min._subtract(p);   <- this line
			pxBounds.max._add(p);
			this._pxBounds = pxBounds;
		}

Uncaught TypeError: Cannot read property '_subtract' of undefined
```

**Comment by hyperknot** [comment]
cc: @perliedman @yohanboniface

**Comment by perliedman** [comment]
My guess is that `_bounds` is somehow initialized but no coordinates are projected, for some reason. This would lead to uninitialized `pxBounds`.

I'm a bit pressed for time the coming days, but I will look at it later in no else beats me to it.

**Comment by yohanboniface** [comment]
@hyperknot good catch, and good guess @perliedman :)

I've just fixed it on Leaflet.Editable side: basically it was failing when removing latlngs while not resetting the bounds.

Should be OK on the Leaflet.Editable side, but I wonder if we should anyway be a bit more defensive and checking for pxBounds validity also. I think I'll not be the only one to remove a latlng from a path without thinking about resetting the bounds. Thoughts?

**Comment by perliedman** [comment]
@yohanboniface I agree, checking `pxBounds` sounds like the right thing to do!
