### ISSUE TITLE
L.control.layers: No way to control selection programmatically

### ISSUE THREAD

**Issue by 9662** [Leaflet/Leaflet#4154]
In a map with multiple base layer options (and overlays) and a Layers control, I would like to reflect the state of the map in the URL. I can do that by listening for the `'baselayerchange'` event, and adding something like `"baselayer=" + event.name` to the query or fragment parts of the URL. That works fine.

Conversely, on loading the page, I would like to set the base layer according to the URL parameter described above. Ideally something like `layerControl.setActiveBaseLayer(name)`. However, there is no such function and, as far as I can see, no way of doing this without accessing the layer control's private members.

Same for overlays.

**Comment by snkashis** [comment]
I may misunderstand your question...but on load, why cant you just only use `map.addLayer` for the things you want active? The layers you add to a layerControl do not need to exist on the map when you init the control.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https//gis.stackexchange.com) or [stackoverflow](https://stackoverflow.com).

Having said that: attach `add` and `remove` event handlers for your layers and update the URL's hash accordingly.

**Comment by 9662** [comment]
@IvanSanchez It wasn't a question but a feature request. I shall try both yours and @snkashis' suggestions when I get back to that particular project and report back on whether those cover the specific requirement that gave rise to this report. Thanks in any case!

> For questions on using Leaflet, please use gis.stackexchange.com or stackoverflow.

More of a fan of irc://irc.freenode.net/leaflet myself. :smiley:
