### ISSUE TITLE
Scroll-zooming in Safari can move page position

### ISSUE THREAD

**Issue by hyperknot** [Leaflet/Leaflet#4159]
Both in 0.7 and in 1.0, scrolling can move the page scroll in Safari. It's even visible on http://leafletjs.com, you can scroll down to the "Trusted by the best" part, by just doing a big scroll inside the Leaflet map. It happens 1 out of 5 times, but when a big jump happens it's quite shocking.

Made an example for trying the different versions: 
http://playground-leaflet.rhcloud.com/wey/1/edit?html,output

Usually it's just 10-20 px, but can be a big jump as well. 

Safari 9.0.2, OS X 10.9.5

**Comment by mourner** [comment]
Reproducible on Chrome as well, happens when you scroll on a popup. It shouldn't propagate to the page...

**Comment by IvanSanchez** [comment]
Weird, as `L.Popup._initLayout` calls `L.DomEvent.disableScrollPropagation`: https://github.com/Leaflet/Leaflet/blob/master/src/layer/Popup.js#L187

**Comment by hyperknot** [comment]
That's great to have it fixed, but my issue was not related to popups. Removed the popup from the example, have a look:
http://playground-leaflet.rhcloud.com/sow/1/edit?html,output

Screen recording:
https://youtu.be/qVjqGycT0u0

**Comment by hyperknot** [comment]
Have a look at this, somehow even this can move the page (try scrolling outside, then over the container):
http://playground-leaflet.rhcloud.com/rac/edit?html,output

**Comment by mourner** [comment]
Let's make a clean minimal non-Leaflet example. I'd assume that this is a Safari bug we can't get around.

**Comment by IvanSanchez** [comment]
Not reproducible with Safari 9.0. Reproducible with Safari 9.1 and today's Webkit Nightly for Mac.

**Comment by IvanSanchez** [comment]
Cannot reproduce on Safari 9.0 nor on webkit nightly on a MacMini.

**Comment by hyperknot** [comment]
Just updated to Safari 9.1 on 10.9, same behaviour. I guess probably 10.9 related.

**Comment by IvanSanchez** [comment]
@hyperknot I saw you being able to reproduce this in a leaflet-less webpage, just `<div>`s and `preventDefault()`s. Did you open an upstream bug report?

**Comment by hyperknot** [comment]
@IvanSanchez not yet, I will do it. I think it's related to OS X 10.9, but I'm not sure. 

Can someone have a look at http://playground-leaflet.rhcloud.com/sow/1/edit?html,output in OS X 10.10 or 10.11 using Safari?

**Comment by perliedman** [comment]
Is it still worthwhile to keep this issue open? If we believe this is an OS X bug in a specific version, and we don't have a workaround, it sounds unlikely this is something we should invest time and energy in.
