### ISSUE TITLE
Css in leaflet fails to compile when CssResource.enableGss flag is turned on

### ISSUE THREAD

**Issue by gxtUser** [Leaflet/Leaflet#4162]
After turning on the Gss flag, the CSS to GSS conversion fails in leaflet.css with these errors (GWT v2.7):

                     [ERROR] Error in [auto-converted gss files from : [jar:file:/.../g-leaflet-0.4.9.jar!/org/peimari/gleaflet/client/resources/leaflet.css]][line: 504 column: 56]: GSS constant not defined: M11
                     [ERROR] Error in [auto-converted gss files from : [jar:file:/.../g-leaflet-0.4.9.jar!/org/peimari/gleaflet/client/resources/leaflet.css]][line: 504 column: 72]: GSS constant not defined: M12
                     [ERROR] Error in [auto-converted gss files from : [jar:file:/C:/.../g-leaflet-0.4.9.jar!/org/peimari/gleaflet/client/resources/leaflet.css]][line: 504 column: 88]: GSS constant not defined: M21
                     [ERROR] Error in [auto-converted gss files from : [jar:file:/C:/.../g-leaflet-0.4.9.jar!/org/peimari/gleaflet/client/resources/leaflet.css]][line: 504 column: 105]: GSS constant not defined: M22
                     [ERROR] Error in [auto-converted gss files from : [jar:file:/C:/.../g-leaflet-0.4.9.jar!/org/peimari/gleaflet/client/resources/leaflet.css]][line: 505 column: 52]: GSS constant not defined: M11
                     [ERROR] Error in [auto-converted gss files from : [jar:file:/C:/...2/g-leaflet-0.4.9.jar!/org/peimari/gleaflet/client/resources/leaflet.css]][line: 505 column: 68]: GSS constant not defined: M12
                     [ERROR] Error in [auto-converted gss files from : [jar:file:/C:/.../g-leaflet-0.4.9.jar!/org/peimari/gleaflet/client/resources/leaflet.css]][line: 505 column: 84]: GSS constant not defined: M21
                     [ERROR] Error in [auto-converted gss files from : [jar:file:/C:/.../g-leaflet-0.4.9.jar!/org/peimari/gleaflet/client/resources/leaflet.css]][line: 505 column: 101]: GSS constant not defined: M22
         [ERROR] Errors in 'org/peimari/gleaflet/client/resources/LeafletResourceInjector.java'
            [ERROR] Line 11: Failed to resolve 'org.peimari.gleaflet.client.resources.LeafletClienBundle' via deferred binding

**Comment by IvanSanchez** [comment]
You need to explain what's going on there (please read some tips at https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md#reporting-bugs ). You're not using Leaflet in a web page, are you?

**Comment by gxtUser** [comment]
Hi Ivan, 
I'm using the leaflet on the webpage as a part of a GWT app.
Leaflet version is 0.4.9.

**Comment by IvanSanchez** [comment]
> Leaflet version is 0.4.9.

You know that the stable version is 0.7.7 and that we have betas for 1.0.0, right?

**Comment by mourner** [comment]
This looks like a GSS problem — it can't parse IE filter properties.

**Comment by gxtUser** [comment]
I tried the latest leaflet version, it still fails.

**Comment by gxtUser** [comment]
Anyone using leaflet library who enables GSS will have this problem.

**Comment by IvanSanchez** [comment]
As @mourner said, the CSS files need to stay the same to provide support for old versions of IE.

I suggest you research using PostCSS to lint and/or clean up the CSS before feeding it to GWT.

**Comment by gxtUser** [comment]
The problem is that the css is coming from a jar file.

**Comment by IvanSanchez** [comment]
That `.jar` file is not coming from any of the Leaflet developers. Contact whoever built that `.jar` file instead.

**Comment by gxtUser** [comment]
Good point, thanks. It is coming from g-leaflet.

**Comment by Stemby** [comment]
Are you planning to drop support for IE7/IE8?

Thank you!

**Comment by hyperknot** [comment]
@Stemby, @gxtUser if you don't need to support IE7/8, you can just remove the problematic lines from the CSS.

**Comment by gxtUser** [comment]
I can't do it directly since I'm using leaflet inside a GWT framework via g-leaflet wrapper (compiled into a jar).

**Comment by hyperknot** [comment]
I recommend asking the maintainer of the framework about how can you change the CSS and re-build the jar.
