### ISSUE TITLE
WMS Layer hidden when changing base layers

### ISSUE THREAD

**Issue by ismail44** [Leaflet/Leaflet#4166]
There are 2 issues I am seeing here, to set up this issue/question here is what I am programmatically adding an WMS layer after my map is originally drawn. I have 2 base layers in my L.control.Layers control. 

If I do not add the autoZIndex: false when I am creating my Layers Control, my WMS layers seem to have a zIndex lower than my base layer. So, I set autoZIndex: false and my WMS layer happily shows up when I add it. 

Now, if I were to change base layers my WMS layer then gets hidden, until I programmatically add it back. 

I don't know if this is a bug or if I am adding my WMS layer incorrectly. 

I am adding my WMS layer like the following:

    var newLayer = L.tileLayer.wms(
        url, {
        layers: (layers ? layers.split(',') : []),
        transparent: true,
        format: 'image/png'
    });
    map.addLayer(newLayer);

Note: url and layers are being set before this is being called. 

I don't really want to add this (or other layers) to the layer controller, because I want them always present. 

Thanks.

**Comment by IvanSanchez** [comment]
Can you reproduce this in a public-facing webpage? (e.g. http://playground-leaflet.rhcloud.com/ ) That would help to see if there is a leaflet bug or not.

**Comment by ismail44** [comment]
I created a sample at the link you provided... here is the link:

http://playground-leaflet.rhcloud.com/rura/1/edit?html,output

You can switch between the satellite and street view once until the WMS layer is covered up.

Thanks.

**Comment by IvanSanchez** [comment]
I think I cannot reproduce in firefox... have you tried in different web browsers?

**Comment by ismail44** [comment]
I tried it in both Firefox and Chrome.

**Comment by ismail44** [comment]
Yeah... it shows up fine when it loads... I click Satellite it works...
then when I click on Street again the WMS disappears.

**Comment by ismail44** [comment]
I created a screencast using Chrome version 47... here is the link:

https://www.dropbox.com/s/wx9niywufd6mo6j/quickcast-21-01-2016-08-35-54.mp4?dl=0

**Comment by ghybs** [comment]
Hi,

It looks like you could simply use [`bringToFront()` method](http://leafletjs.com/reference.html#tilelayer-bringtofront) on your WMS layer when the base layer is changed (add a listener on map [`"baselayerchange"` event](http://leafletjs.com/reference.html#control-layers-baselayerchange)): 
http://playground-leaflet.rhcloud.com/puc/edit?html,output

Or even more simple, use the [`zIndex` option](http://leafletjs.com/reference.html#tilelayer-zindex) on your Tile Layers (it can also be used on WMS Tile Layers) to specify the stacking order:
http://playground-leaflet.rhcloud.com/qay/1/edit?html,output

Hope this helps.

**Comment by ismail44** [comment]
Thanks... that was the work-around I ended up with.

**Comment by rowanwins** [comment]
Hi @ismail44 

You should just be able to set the [zIndex](http://leafletjs.com/reference.html#tilelayer-zindex) of the layer 

```
var nexrad = L.tileLayer.wms('http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r.cgi', {
   layers: ['nexrad_base_reflect'],
   format: 'image/png',
   transparent: true,
   zIndex: 1000
});
````

Updated fiddle [here](http://playground-leaflet.rhcloud.com/rec/1/edit?html,output)

Cheers
Rowan

**Comment by ismail44** [comment]
Right on... I didn't realize that the WMS layer supported zIndex... wasn't in the docs... I suggest an addition to them. Thanks again... I'll go ahead and close this issue!

**Comment by IvanSanchez** [comment]
> I didn't realize that the WMS layer supported zIndex... wasn't in the docs

*Technically* it's in the docs, but we are aware they are quite confusing about the matter (WMS inherits from TileLayer, TileLayer inherits from GridLayer, GridLayer has zIndex). There are some ideas on how to make inherited options more obvious, but they're not ready yet :-(
