### ISSUE TITLE
touchcancel and touchleave cases unhandled for IE and Edge on Touch Screen Devices

### ISSUE THREAD

**Issue by micahiverson** [Leaflet/Leaflet#4168]
We have been working on a site using Leaflet.js which has been working fine in Chrome and Firefox, IE and Edge on NON touch screen devices, but IE and Edge do not work on touch ENABLED devices like the Surface Pro, Surface Book, Windows Phone.

It's been bugging me for months and finally dug a bit deeper and discovered that "touchcancel" and "touchleave" events don't seem to not be handled in Leaflet-0.7.3+ which then throws an exception.

Here is the current Case statement:
	addPointerListener: function (obj, type, handler, id) {
		switch (type) {
		case 'touchstart':
			return this.addPointerListenerStart(obj, type, handler, id);
		case 'touchend':
			return this.addPointerListenerEnd(obj, type, handler, id);
		case 'touchmove':
		    return this.addPointerListenerMove(obj, type, handler, id);
		default:
			throw 'Unknown touch event type';
		}
	},

Need something like this:
	addPointerListener: function (obj, type, handler, id) {

		switch (type) {
		case 'touchstart':
			return this.addPointerListenerStart(obj, type, handler, id);
		case 'touchend':
			return this.addPointerListenerEnd(obj, type, handler, id);
		case 'touchmove':
		    return this.addPointerListenerMove(obj, type, handler, id);
		case 'touchcancel':
		    return this.addPointerListenerCancel(obj, type, handler, id);
		case 'touchleave':
		    return this.addPointerListenerLeave(obj, type, handler, id);
		default:
			throw 'Unknown touch event type';
		}
	},

And then need appropriate functions to support them.
Thanks!

**Comment by IvanSanchez** [comment]
> "touchcancel" and "touchleave" events don't seem to not be handled in Leaflet-0.7.3+

So then the first question is: Have you tried with 1.0.0-beta2?

**Comment by IvanSanchez** [comment]
No more information has been provided, and more than a few weeks have passed. We'll assume this issue is no longer relevant and/or there is no interest to make a better report.
