### ISSUE TITLE
Prevent map dragging while mousedown on control in IE

### ISSUE THREAD

**Issue by netfusion** [Leaflet/Leaflet#4170]
When you click on the control on http://leafletjs.com/ (top left corner) an drag the mouse, the map will move in IE but not in Chrome, FF, etc.

I wasn't able to prevent this behavior on my custom controls either.

Looks like IE bubbles the event first so it gets fired on the map-pane before it reaches the control.

PS.: I hope this issue isn't a duplicate of #3666

**Comment by a1an77** [comment]
On custom controls the map gets dragged anyways unless the developer prevents it with own code. A more uniform solution would be to make all controls "solid" in that they do not let mouse event through their container. Would that be feasible in an uniform way?

**Comment by johnd0e** [comment]
> A more uniform solution would be to make all controls "solid" in that they do not let mouse event through their container. Would that be feasible in an uniform way?

#7124

**Comment by johnd0e** [comment]
> the map will move in IE

Unable to reproduce with recent Leaflet in IE11.
