### ISSUE TITLE
Removing GeoJSON layer issue

### ISSUE THREAD

**Issue by RatanMishra** [Leaflet/Leaflet#4176]
Hi,

I am new to leaflet. I have used remove layer feature of leaflet as follows
```js
var layermap = L.geoJson(data, {
				style: options.style,			
				onEachFeature: options.onEachFeature
			}).addTo(map);
```
Then i tried to remove the layer as follows.
`map.removeLayer(layermap);`
Its removing the layer from current zoom level but once i change the map zoom, the layer comes again.
I want to remove the layer permanently.

Please suggest.

**Comment by yohanboniface** [comment]
Can you provide a jsfiddle reproducting the issue (with http://playground-leaflet.rhcloud.com/ for example) ?
Also, which Leaflet version are you using?

**Comment by RatanMishra** [comment]
Thanks,

I am using leaflet version 0.7.2
I will try to create a sample.

**Comment by RatanMishra** [comment]
My mistake, I was reloading the layer unknowingly.
Thanks.
