### ISSUE TITLE
Fixing 4x tile usage

### ISSUE THREAD

**Issue by hyperknot** [Leaflet/Leaflet#4180]
Leaflet 1.0 beta has 4x tile usage compared to 0.7, when zooming in (and other scenarios involving fractional zoom levels).

@yohanboniface fixed it in: https://github.com/Leaflet/Leaflet/pull/4040
however this broke fractional zoom levels at the edge of the map: https://github.com/Leaflet/Leaflet/issues/4145

@IvanSanchez fixed it in https://github.com/Leaflet/Leaflet/pull/4156
however it raised the tile usage again to 4x.

I made a test for it (based on @yohanboniface 's test):

- 0.7.5 (only using browser tools): 8 tiles at load, +6 tiles at zoom: http://playground-leaflet.rhcloud.com/puh/1/edit?js,output
- 1.0 beta 2: 8 tiles at load, +24 tiles at zoom: http://playground-leaflet.rhcloud.com/jet/1/edit?js,console,output
- 1.0 just before #4156: 8, +6, http://playground-leaflet.rhcloud.com/ciz/1/edit?js,console,output
- 1.0 after #4156: 8, +24 http://playground-leaflet.rhcloud.com/biq/1/edit?js,console,output

**Comment by IvanSanchez** [comment]
Can we turn that into a unit test?

**Comment by hyperknot** [comment]
@yohanboniface did this, it is what I based my playground example on, but it doesn't seem complete:
https://github.com/Leaflet/Leaflet/pull/4040/files#diff-19a7d53df5d545ee8cde69a53256057cR123 Also there is a line that it doesn't work on PhantomJS.

**Comment by hyperknot** [comment]
Test with #4193, OK:
http://playground-leaflet.rhcloud.com/wek/1/edit?js,console,output
