### ISSUE TITLE
Bigger .leaflet-zoom-animated than it's container

### ISSUE THREAD

**Issue by Yamakaky** [Leaflet/Leaflet#4181]
I use a `width: 100%; height: 100vh;` div#map, so 1280x460 on my computer, but div.leaflet-zoom-animated has a fixed 1980x723 size. Is it normal ? It breaks fullpage.js, as the fullscreen map overflows on the following slide.

**Comment by IvanSanchez** [comment]
@Yamakaky Can you ellaborate on *how* does that break `fullpage.js`? (what exactly do you mean by `fullpage.js` anyway?

Please take a minute to read [CONTRIBUTING.md](https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md#reporting-bugs), and make sure to point out your leaflet version and provide a test case we can have a look at.

**Comment by IvanSanchez** [comment]
No more information has been provided, and more than a few weeks have passed. We'll assume this issue is no longer relevant and/or there is no interest to make a better report.
