### ISSUE TITLE
LatLng#distanceTo is always higher than calculated by any other geo-library

### ISSUE THREAD

**Issue by lonelyelk** [Leaflet/Leaflet#4184]
Might I suggest that you use any other than equatorial Earth radius in [CRS.Earth.js](https://github.com/Leaflet/Leaflet/blob/master/src/geo/crs/CRS.Earth.js)? Most of geo-stuff libraries use authalic radius (6371 km) or approximated average radius (6372.8 km). Or any suggested [code snippet](http://rosettacode.org/wiki/Haversine_formula) here. Equatorial radius is never used hence your formula will always give ~1% higher result than any other.

**Comment by mourner** [comment]
Yes, that makes sense. Should be an easy fix.

**Comment by lonelyelk** [comment]
Do you need a pull request for that? If yes, which radius do you prefer?

**Comment by hyperknot** [comment]
@lonelyelk I guess the best one is the one which is closest to a Vincenty formula's result on various points, isn't it?
