### ISSUE TITLE
Export map as geojson

### ISSUE THREAD

**Issue by HugoHeneault** [Leaflet/Leaflet#4185]
Hi there, 
Thanks for giving us Leaflet. It's so powerfull.

Is it possible to export geojson from leaflet to save the map state?

I want to store the markers, zoom & map center to load it later, but I can't figure out a way to do this by using geojson.

Thanks!

**Comment by perliedman** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https//gis.stackexchange.com) or [stackoverflow](https://stackoverflow.com).

Having said that, check at using your layers' [toGeoJSON](http://leafletjs.com/reference.html#polygon-togeojson) method!

**Comment by HugoHeneault** [comment]
Thanks for your reply. I thought (by mistake) that this was not possible yet. 

I've found a solution on http://stackoverflow.com/questions/35125036/export-leaflet-map-to-geojson
