### ISSUE TITLE
map not loading android 4.1.2

### ISSUE THREAD

**Issue by donny08** [Leaflet/Leaflet#4187]
I have tried setting `<script>L_DISABLE_3D = true;</script>` before including leaflet.js but still the problem is not solved.

**Comment by IvanSanchez** [comment]
Does any website powered by Leaflet still work? e.g. if you visit leafletjs.com, do you see the map using the same Android 4.1.2?

**Comment by donny08** [comment]
yess i can see map

**Comment by IvanSanchez** [comment]
Then you must be more specific in describing the circumstances of your problem: which web browser (stock? chrome?), which Leaflet version, whether if your example works on a desktop browser, etc.

Also, please read [CONTRIBUTING.md](https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md#reporting-bugs), it contains tips on how to write a good bug report, and where to search for help if this is not Leaflet's fault.

**Comment by IvanSanchez** [comment]
No more info provided after a month. Reopen if more specific conditions are provided.
