### ISSUE TITLE
closePopupOnClick map option possibly unused

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#4189]
As @ssured notes in #4188, the `closePopupOnClick` option doesn't work properly - there is a need for refactoring the `preclick` event handler of `L.Popup`, and possibly make a unit test to prevent regressions.

**Comment by MattSidor** [comment]
Is this still a bug? Should we close this issue?

**Comment by johnd0e** [comment]
@IvanSanchez 
It seems that this is not the case atm, right?

**Comment by Falke-Design** [comment]
@johnd0e can you please add this issue to `Refactor DivOverlay/Popup/Tooltip ` it looks like that it is working no with `closePopupOnClick` but if we change the preclick logic for Tooltips (#7532) we can also change it for Popups like suggested.

**Comment by johnd0e** [comment]
Just checked and found no issues there.
