### ISSUE TITLE
Marker click event stops firing after dynamically changing its icon

### ISSUE THREAD

**Issue by anderser** [Leaflet/Leaflet#419]
I've got a map with markers added by looping through a json file and adding the markers with my add_marker function. 

The function also binds som events to the marker/layer on mouseover/out in order to change the icon when the user is hovering the marker. That works ok. 

But after I added the mouseover event (with change of the icon), the click event on the same marker does not seem to fire when the user clicks the marker. 

Maybe I am missing something essential here, or it might be a bug...

``` javascript

function add_marker (index, a) {

    latlng = new L.LatLng(a.lat, a.lng)
    var m = new L.Marker(latlng, {icon: icon});

    m.on('mouseover', function(e) { 
        m.setIcon(hover_icon);
    });

    m.on('mouseout', function(e) {      
         m.setIcon(icon);
    });

    m.on('click', function(e) { 
        console.log("click");   
    });

    map.addLayer(m);
}
```

**Comment by hughlomas** [comment]
This is actually happening for me right now in 0.7.7. Everything works fine by commenting out marker.setIcon().

What is unexpected is that I'm using setIcon at other times and the events continue to work, but if I change it inside of a mouseover event handler, it seems to unbind everything.
