### ISSUE TITLE
Missing documentation for `disableScrollPropagation`

### ISSUE THREAD

**Issue by febeling** [Leaflet/Leaflet#4194]
The method `L.DomEvents.disableScrollPropagation` isn't mentioned in the documentation.

**Comment by IvanSanchez** [comment]
This will be fixed in https://github.com/Leaflet/Leaflet/commit/e3f65b8dad62051079c659c9ebcf66af4ad97bbb#diff-4126cb436737830035255df088f7be61R169 when #4085 and #3916 are merged in.

**Comment by febeling** [comment]
:+1: Thanks.
