### ISSUE TITLE
button switch between map / satellite layers

### ISSUE THREAD

**Issue by ivanssa** [Leaflet/Leaflet#4195]
Hello day I'm looking for a solution to create a button to switch between map / satellite layers, as in the example image below, someone could help in creating this switch style?

![map_change](https://cloud.githubusercontent.com/assets/3166174/12825911/4e4b2aa0-cb57-11e5-972f-b60c06726694.jpg)

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https//gis.stackexchange.com) or [stackoverflow](https://stackoverflow.com).

**Comment by ivanssa** [comment]
I could settle with the function found here https://github.com/angular-ui/ui-leaflet/issues/22 was all he needed to create my custom layer switch

$ Scope.changeBaseLayer = function (key) {
         leafletData.getMap (). Then (function (map) {
             leafletData.getLayers (). Then (function (layers) {
                 _.each (layers.baselayers, function (layer) {
                     map.removeLayer (layer);
                 });
                 map.addLayer (layers.baselayers [key]);
             });
         });
     };
