### ISSUE TITLE
getPointAtLength of Path Line wrong coordinates

### ISSUE THREAD

**Issue by trippal** [Leaflet/Leaflet#4198]
Good day, 
There is something strange:
I'm using Leaflet 1.0 beta 2. and D3.js to label paths.
So, getTotalLength()  - work great. Total length in pixels to repeat line labels works, but when I try to get current pixel position on path(X,Y) - this is fly away by 2-3 hundred pixels to the right. 
For example - I draw line on clock-side demention around. And pixels x and y at the begining of line (0,0) - normal, at the end coordinates looks like line become straight.

Can you help me with this problem. I did not find any solutions.

P.S. sorry for my english, I haven't practiced for a long time ^_^

**Comment by IvanSanchez** [comment]
I think we could understand the problem better with pictures and/or examples. Can you post some code in a public place (e.g. http://playground-leaflet.rhcloud.com/ ) so we can *see* what you mean?

**Comment by trippal** [comment]
Firstly, I use eachLayer
` 	_resetLabels: function() {
 		this._removeLabels();

 		this.labelingLayer.eachLayer(function(layer) {
 			if (layer.feature.geometry.type === "LineString") {
 				this._LineLabel(layer);
 			} else {
 				alert("Incorrect data!")
 			}
 		}, this);
 	},`

Secondly: lineLabel method
`layer._path.id = "layer" + layer._leaflet_id;//add path id to use d3,js selections
if (opt.labelOptions.lineLabelPosition.repeat === true) {
           for (var i = 0; i < d3.selectAll("#layer" + layer._leaflet_id)[0][0].getTotalLength(); i = i + opt.labelOptions.lineLabelPosition.repeatOffset) {
          console.log(d3.selectAll("#layer" + layer._leaflet_id)[0][0].getPointAtLength(i).x, d3.selectAll("#layer" + layer._leaflet_id)[0][0].getPointAtLength(i).y)
}
}`

**Comment by trippal** [comment]
I'm so sooooory! I found my error!))

**Comment by IvanSanchez** [comment]
No problem! ;-)
