### ISSUE TITLE
documentation examples: displaying GPS trace?

### ISSUE THREAD

**Issue by bagage** [Leaflet/Leaflet#4202]
I read the [Quick Start Guide](http://leafletjs.com/examples/quick-start.html) and quickly got a working map, thanks to the great documentation!

From what I can see on the [examples page](http://leafletjs.com/examples.html), there is not (yet?) an example for dealing with route / trace display. From nicest (in my opinion!) to simplest to write (I think), would it be reasonable to have an example for:

1. Displaying a route with play/pause animation (like [Strava flyby](http://labs.strava.com/flyby/viewer/#479846016?c=u0589zgr&z=G&t=1MfwzN) does)
- Displaying a route provided through a .GPX, .KML or .TCX file 
- Displaying a route using hard-coded checkpoints?

What do you think of it?

**Comment by hyperknot** [comment]
Leaflet is just a core library, probably more minimal then you might think. What you mentioned here can be done with external plugins and/or custom implementation.

1. Strava's example is not an "example", it is a sophisticated front-end app. I'd guess it takes 500+ lines of code to implement a basic version if it, definitely not something which fits in a tutorial for beginner.
2. For this one, look into Leaflet plugins: http://leafletjs.com/plugins.html Again, as Leaflet is just a core library, writing tutorials for this use case is out of Leaflet scope.
3. Isn't this exactly just polyline with markers?

I think your ideas would be great if you've written them as a blog post, I guess maybe the Leaflet devs would even tweet about it.
(// I'm just a Leaflet user)

**Comment by bagage** [comment]
1. Sure, 1. is probably way overkill. 
* I wasn't sure if Leaflet handled it internally, but the conversion to poly-line should not be a big deal.
* This gets interesting; maybe a small subsection of the start guide will be enough to just show that it's there and how it looks like (I know it's ridiculously easy to code, but nice to read it in an example tutorial!).
Thanks for your comment @hyperknot: to be clear, if this "idea" does not bring anything, I am fine with it being closed. But I really think it would be cool to see it somehow in examples :-).

**Comment by danzel** [comment]
2 would be handled by plugins, so I don't think it would suit as a leaflet example.

https://github.com/Leaflet/Leaflet/blob/master/debug/vector/vector-bounds.html has an example of 3, which is just creating a L.Polyline using an array of latlngs. So I'm not not sure we really need an example of that.

**Comment by bagage** [comment]
Well indeed `vector` example exists -I do not think it's the same usage though, but I guess it's enough for new users!
