### ISSUE TITLE
Leaflet/GeoJSON - Symbolizing the default blue icon to other .png files

### ISSUE THREAD

**Issue by kmdufa** [Leaflet/Leaflet#4207]
How can I use different .png files to symbolize my GeoJSON data?
I have one property in my GeoJSON file that I would like to symbolize the data by (feature.properties.issue). For each different issue type, I would like to display a different .png file as a clickable marker.

Here is what I have so far. I'm very new to Leaflet/HTML/GeoJSON.
I can get each default marker to have a click-able popup that reads the GeoJSON properties [(Imgur pic of output here),](http://imgur.com/Mbjtu4m) but I do not know how to change the symbology from the default blue marker.
You can see that I have two other .png files in the directory called "warningicon" and "testicon.png", but I'm unsure of where to put it in my code, or how to use a conditional statement in this instance to differentiate based on issue type.

> var warningicon = {
    iconUrl: 'warningicon.png',
    iconsize: [32,32],
    };

> var testicon = {
    iconUrl: 'testicon.png',
    iconsize: [32,32],
    };

      
>  $.getJSON("./geojson/sidewalks.geojson",  
     function(data) {
        var geojson = L.geoJson(data, 
                                        {onEachFeature: >action_To_Perform_When_Marker_Is_Clicked_On_The_Map});
        geojson.addTo(map);
        myGeoJSONLayers.addLayer(geojson);
     }
  );

>var overlayMaps = {"Sidewalk Issues": myGeoJSONLayers};	

>L.control.layers(baseMaps, overlayMaps,myGeoJSONLayers).addTo(map); 
    
>function action_To_Perform_When_Marker_Is_Clicked_On_The_Map(feature, layer) {
    if (feature.properties)
    {
		var PopupText = []; 
		PopupText.push("<b>Accessibility Issue: </b>" + feature.properties.Issue);
        PopupText.push("<b><br/>Description: </b>" + feature.properties.Descriptio);
        PopupText.push("<b><br/>Recorded: </b>" + feature.properties.CreationDa);
		layer.bindPopup("<p>" + PopupText.join("") + "</p>");						
	} 
>}

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https//gis.stackexchange.com) or [stackoverflow](https://stackoverflow.com).

Also, pay attention to the `pointToLayer` option in the GeoJSON class in the docs: http://leafletjs.com/reference.html#geojson-pointtolayer
