### ISSUE TITLE
Fractional zoom controls broke maps when initial zoom isn't specified

### ISSUE THREAD

**Issue by hyperknot** [Leaflet/Leaflet#4208]
All maps are broken (total grey) which are not specifying initial zoom manually, but by using fitBounds.

It's because of 3fde3c03, which changes getBoundsZoom, which now gives NaN when initial zoom isn't set.

Affected examples (almost all which contain the string fitBounds):
- map/image-overlay.html
- map/tile-opacity.html
- map/wms.html
- vector/vector-mobile.html
- vector/vector-canvas.html
- vector/vector.html
- tests/svg_clicks.html
- tests/add_remove_layers.html

**Comment by IvanSanchez** [comment]
I wonder how the unit tests for `L.Map.fitBounds` haven't caught this one.

**Comment by IvanSanchez** [comment]
Closed via #4209
