### ISSUE TITLE
popup closing after autopan

### ISSUE THREAD

**Issue by damiendevienne** [Leaflet/Leaflet#4210]
Hello, 
I am having this problem with leaflet: 
When a popup opens, the map autopans to make the popup fully visible (which is good), but then the popup automatically closes. Is this a bug ?
Cheers

**Comment by IvanSanchez** [comment]
I cannot reproduce (see http://playground-leaflet.rhcloud.com/xisu/edit?html,output ), so I have to assume it's a bug in your code.

As explained in [CONTRIBUTING.md](https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md), this issue tracker is used for reporting bugs and discussing new features. Double-check your code and consider asking for advice in [gis.stackexchange.com](https//gis.stackexchange.com) or [stackoverflow](https://stackoverflow.com).

If you think that, in fact, there is a bug in Leaflet, please provide a *reproducible* use case that exhibits the unexpected behaviour.
