### ISSUE TITLE
Doubled-up transforms on SVG layers in non-3D environments (e.g. PhantomJS)

### ISSUE THREAD

**Issue by Mr0grog** [Leaflet/Leaflet#4211]
In the 1.0 beta, SVG layers get both a transform and a top/left position applied when running in a non-3D browser, effectively doubling their offset and rendering them visually out-of-sync with the rest of the map. I ran into this while trying to do some snapshotting in PhantomJS (where 3D is turned off):

![output](https://cloud.githubusercontent.com/assets/74178/12912299/69c78ee0-cecc-11e5-8adc-41a123a82f51.jpg)
*GeoJSON/SVG layer of bus routes overlaid on SF city streets*

This is happening because SVG layers update their viewbox and call `DomUtil.setPosition()` in their [`_update()` method](https://github.com/Leaflet/Leaflet/blob/master/src/layer/vector/SVG.js#L47-L48), but also inherit an [`_updateTransform()` method from `L.Renderer`](https://github.com/Leaflet/Leaflet/blob/master/src/layer/vector/Renderer.js#L66) that explicitly calls `DomUtil.setTransform()`. When 3D is on, they both wind up setting a transform on the SVG (which is fine; one overrides the other), but when 3D is off, as in PhantomJS, one sets a transform and other sets the top/left properties, resulting in a doubled-up offset.

I don't know the exact history of how this situation came to be or how these two parts are intended to work (or not intended!) together, so I'm not sure on the best approach for a fix. Either way, though, these two methods seem to be in conflict.

**Comment by IvanSanchez** [comment]
I cannot reproduce this one. I'm putting the usual

```html
	<script>
	L_DISABLE_3D = true;
	</script>
```

in [/debug/vector/vector2.html](https://github.com/Leaflet/Leaflet/blob/master/debug/vector/vector2.html), and I can confirm the bug.

It doesn't show up at first, but it can be triggered by mousewheel-zooming when far from the map center.

**Comment by IvanSanchez** [comment]
@Mr0grog Can you please check if #4212 fixes the problem for your case?

**Comment by Mr0grog** [comment]
@IvanSanchez as noted in the PR, that works great in my use case (thanks!). Not sure if the loss of zoom/scale would cause problems in other potential use cases, though.

**Comment by IvanSanchez** [comment]
> Not sure if the loss of zoom/scale would cause problems in other potential use cases, though.

No. Scaling renderers is only used during zoom animations, and those don't happen when `L.Browser.any3d` is false. So no problem.

**Comment by Mr0grog** [comment]
Ah, gotcha. :thumbsup:
