### ISSUE TITLE
L.Control.Layers does not cleanup event listeners when removed

### ISSUE THREAD

**Issue by perliedman** [Leaflet/Leaflet#4213]
When a layer control is removed from a map using `removeControl`, it does not remove the event listeners that it has attached to its layers.

This causes an exception if one these layers are later added or removed from the map, since it will trigger the layer control's listener, which assumes `this._map` to be defined, but it isn't.

I think the control should remove all listeners when it is removed from the map.

Example to reproduce: http://playground-leaflet.rhcloud.com/gic/edit?html,output

Tested with 1.0.0-beta.2.

**Comment by perliedman** [comment]
Also verified this issue exists with development version as of today, 2016-02-09.

**Comment by IvanSanchez** [comment]
Looks easy, working on a fix.

**Comment by IvanSanchez** [comment]
#4214 should do the trick.

**Comment by perliedman** [comment]
That's fast, nice work!

**Comment by IvanSanchez** [comment]
@perliedman Can you please test and merge if it looks good? ;-)

**Comment by perliedman** [comment]
No time right now, but will try to find time later tonight!
