### ISSUE TITLE
Right click touchpad action zooms out map

### ISSUE THREAD

**Issue by hyperknot** [Leaflet/Leaflet#4215]
Since a1ff60bf, a right click on the touchpad (Macbook, OS X), triggers a zoom out. 

I believe it is because of ths `Math.max(d3, this._map.options.zoomSnap || 0)` line. I think it should be a round to the nearest zoomSnap, not a max.

Can be tested in every sample / example.

**Comment by IvanSanchez** [comment]
Does this mean that right-clicking the touchpad triggers a `wheel` event??

I've seen problems with horizontal scroll touchpads, but I'm not aware this was possible also :-S

**Comment by hyperknot** [comment]
Yes, I've just tested it, it triggers a 0.

**Comment by hyperknot** [comment]
Here is a comparison between the old function (zigzag) and the new one (smooth) on -1000...1000 delta range. I *think* what you wanted originally is a smoother zig-zag, isn't it? Also the old one returned 0 -> 0, the new one returns 0 -> 1, hence the bug.

![figure_1](https://cloud.githubusercontent.com/assets/494223/12993193/0561a4fa-d119-11e5-98ee-f1c460aaeb2e.png)

**Comment by hyperknot** [comment]
Fixed in #4224, gives smaller zig-zag with zoomSnap and identical to old version when zoomSnap = 1.

![figure_1](https://cloud.githubusercontent.com/assets/494223/12995257/70f1ac30-d126-11e5-9c71-8cbb4293ab76.png)

Gives smooth curve with zoomSnap = 0.
![figure_1](https://cloud.githubusercontent.com/assets/494223/12995278/a1f8ca66-d126-11e5-81bc-da8662ae28b4.png)

(green is old version)

**Comment by hyperknot** [comment]
Fixed as of https://github.com/Leaflet/Leaflet/pull/4224
