### ISSUE TITLE
Changing the panes of feature group

### ISSUE THREAD

**Issue by dbanka** [Leaflet/Leaflet#4216]
I want to draw a geojson layer and on top of that I want to put some colored tiles and above that I want to draw circles(L.circle).
The issue is that both geojson layer and circles are coming in the overlay pane, so either both of them come above tile layer or below tile layer.
Can I put both of them(geojson layer and circles) in different panes?

**Comment by IvanSanchez** [comment]
In the 1.0.0-betas, all layers have a `pane` option, as noted in the docs: http://leafletjs.com/reference-1.0.0.html#layer-pane

As explained in [CONTRIBUTING.md](https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md), this issue tracker is used only for reporting bugs and discussing new features. If you need to ask for advice on how to use Leaflet, please use [gis.stackexchange.com](https//gis.stackexchange.com) or [stackoverflow](https://stackoverflow.com).
