### ISSUE TITLE
Does leaflet support an SVG as background?

### ISSUE THREAD

**Issue by salmansidd** [Leaflet/Leaflet#4218]
Hi, I want to use SVG in the background with leaflet.js instead of a map. I know it supports SVG as markers, but I have no idea whether an SVG can be put in the background or not. Does someone has any experience with this?

**Comment by IvanSanchez** [comment]
Hi! Glad you like to push Leaflet to its limits!

As explained in [CONTRIBUTING.md](https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md), this issue tracker is used for reporting bugs and discussing new features. For user advice on Leaflet, please consider asking in [gis.stackexchange.com](https//gis.stackexchange.com) or [stackoverflow](https://stackoverflow.com).
