### ISSUE TITLE
map is not being shown properly 

### ISSUE THREAD

**Issue by garden786** [Leaflet/Leaflet#4222]
I have my map in a hidden div. When that div becomes visible all if the map is grey except the upper left corner. When I resize the map or open the browser console the map becomes visible properly.[link to image](http://screencast.com/t/y2OILrskI)

[link to video ](http://screencast.com/t/e6TlmHHtAPH)

**Comment by IvanSanchez** [comment]
I'm afraid this is not a good bug report. Please take a minute to read [CONTRIBUTING.md](https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md#reporting-bugs), and make sure to point out your leaflet version and provide a test case we can have a look at.

**Comment by jieter** [comment]
`map.invalidateSize()` might help though...

**Comment by garden786** [comment]
@jieter  that does not helps. I tried that but that didn't work either

**Comment by garden786** [comment]
@IvanSanchez  yes you are right. it is not a bug. I'm sorry but I need to ask something that I'm getting a error that `L.geoJson.ajax` is not a function. Why I am getting this error. I have placed the `leaflet.ajax.min.js` this file in the folder where the html file is present but that is not helping I'm still getting that error

**Comment by IvanSanchez** [comment]
@garden786 Once again: if it's not a bug or discussion about a new feature, this is not the right place. [stackoverflow](https://stackoverflow.com/search?q=l.geoJson.ajax) is the right place.
