### ISSUE TITLE
How can I add data attributes?

### ISSUE THREAD

**Issue by Trecoolius** [Leaflet/Leaflet#4225]
I've been trying [this tutorial ](http://chris-osm.blogspot.com/2013/11/using-leaflet-with-database.html)and while everything works fine, I need a way to attach an ID to every marker so I can trigger individual bootstrap modals like so:

`data-toggle="modal" data-target="some id"`

After doing some reading, everything seems to indicate that I should do something similar to this:

`marker._icon.dataset.toggle = 'modal';

marker._icon.dataset.target = '<?php echo some id; ?>';`

However, I can't seem to quite grasp where I should put this. This is my code:

`/*
 * global variables
 */
var map;			// global map object
var lyrOsm;			// the Mapnik base layer of the map
var lyrPlq;			// the geoJson layer to display plaques with
var blueicon;		// a blue icon for blue plaques	
var greenicon;		// a green icon for green plaques
var whiteicon;		// a white icon for white plaques

// when the whole document has loaded call the init function
$(document).ready(init);

function init() {		
	// map stuff
	// create the icons
	blueicon=L.icon({
		iconUrl: 'images/blueplaque.png',
		iconSize:     [24, 24], // size of the icon
		iconAnchor:   [12, 23],	// point of the icon which will correspond to marker's location
		popupAnchor:  [0, -12]  // point from which the popup should open relative to the iconAnchor
	});
	greenicon=L.icon({
		iconUrl: 'images/greenplaque.png',
		iconSize:     [24, 24], // size of the icon
		iconAnchor:   [12, 23],	// point of the icon which will correspond to marker's location
		popupAnchor:  [0, -12]  // point from which the popup should open relative to the iconAnchor

	});
	whiteicon=L.icon({
		iconUrl: 'images/whiteplaque.png',
		iconSize:     [24, 24], // size of the icon
		iconAnchor:   [12, 23],	// point of the icon which will correspond to marker's location
		popupAnchor:  [0, -12]  // point from which the popup should open relative to the iconAnchor

	});
	
	// base layer
	var osmUrl='https://api.tiles.mapbox.com/v4/mapbox.streets-basic/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoiaHVpdHppbG9wIiwiYSI6ImNpajFmcW15NjAwOXR1ZGx3czNobHg1MDEifQ.cYoJoMWkFT8YkQk1ElTmag';    
	var osmAttrib='Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors';
	
	lyrOsm = new L.TileLayer(osmUrl, {
		minZoom: 9, 
		maxZoom: 19, 
		attribution: osmAttrib
	});
	
	// a geojson layer
	lyrPlq = L.geoJson(null, {
		pointToLayer: setIcon
		}
	);
	
	// set the starting location for the centre of the map
	var start = new L.LatLng(53.7610,-0.3529);	
	
	// create the map
	map = new L.Map('mapdiv', {		// use the div called mapdiv
		center: start,				// centre the map as above
		zoom: 12,					// start up zoom level
		layers: [lyrOsm,lyrPlq]		// layers to add 
	});
	
	// create a layer control
	// add the base layers
	var baseLayers = {
		"OpenStreetMap": lyrOsm
	};

	// add the overlays
	var overlays = {
		"Plaques": lyrPlq
	};

	// add the layers to a layer control
	L.control.layers(baseLayers, overlays).addTo(map);
	
	// create the hash url on the browser address line
	var hash = new L.Hash(map);
	
	map.on('moveend', whenMapMoves);
	
	askForPlaques();
}

function whenMapMoves(e) {
	askForPlaques();
}

function setIcon(feature,ll) {
	var plq; 
	if (feature.properties.colour=='green') {
		plq=L.marker(ll, {icon: greenicon});
	}
	else if (feature.properties.colour=='white') {
		plq=L.marker(ll, {icon: whiteicon});
	}
	else {
		plq=L.marker(ll, {icon: blueicon});
	}
	plq.bindPopup(feature.properties.plaquedesc);
	return plq;
}

function askForPlaques() {
	var data='bbox=' + map.getBounds().toBBoxString();
	$.ajax({
		url: 'ajax/ajxplaques.php',
		dataType: 'json',
		data: data,
		success: showPlaques
	});
}

function showPlaques(ajxresponse) {
	lyrPlq.clearLayers();
	lyrPlq.addData(ajxresponse);
}
`

Thanks!

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https//gis.stackexchange.com) or [stackoverflow](https://stackoverflow.com).

Having said that: look into `L.DivIcon`, which allows you to manually specify HTML code you can then attach to a marker.
