### ISSUE TITLE
Quickly changing / removing tile layers results in a _pruneTiles error

### ISSUE THREAD

**Issue by hyperknot** [Leaflet/Leaflet#4230]
If the tile layer is quickly removed after being added (which might happen when the user is quickly selecting tile layers from a list), a _pruneTiles error might be thrown.

Try quickly clicking the switch button multiple times:
http://playground-leaflet.rhcloud.com/yin/2/edit?html,output

Error: `Cannot read property 'getZoom' of null`

```
_pruneTiles: function () {
		var key, tile;
		var zoom = this._map.getZoom();
```

Should _pruneTiles start with `if(!this._map) {return}`?

**Comment by yohanboniface** [comment]
> Should _pruneTiles start with if(!this._map) {return}?

I'd say so, yes, given we are using requestAnimFrames, which is async.
