### ISSUE TITLE
Polyline.getCenter() throws TypeError: this._rings is undefined

### ISSUE THREAD

**Issue by diocles** [Leaflet/Leaflet#4231]
I'm using 1.0 beta 2, but get the same error with the 1.0-dev zip file. I'm trying to add labels to the centroid of GeoJSON polygons using this code:

```
                $.getJSON("./map.geojson", function(data) {
                        var geojson = L.geoJson(data, {
                                onEachFeature: function(feature, layer) {
                                        var label = L.marker(layer.getCenter(), {
                                                icon: L.divIcon({
                                                        className: 'label',
                                                        html: feature.properties.name,
                                                        iconSize: [100, 40]
                                                })
                                        }).addTo(map);
                                }
                        });
                        geojson.addTo(map);
                });
```

But I get an error in the console:

TypeError: this._rings is undefined

(Apologies in advance if there's a silly mistake here; it's quite late.  But I'm pretty sure I've got polyline objects, it's just there's a problem finding the centroid?)

**Comment by yohanboniface** [comment]
@diocles can you reproduce on a jsfiddle so we can investigate? http://playground-leaflet.rhcloud.com/ for example. Thanks :)

**Comment by diocles** [comment]
@yohanboniface http://playground-leaflet.rhcloud.com/vum/1/edit?html,output

Hope that helps!

**Comment by yohanboniface** [comment]
@diocles the layer has not been added to the map at this time, so we can't project its center yet.
Try using the `layeradd` event on the geojson layer instead. Something like:
```
geojson.on('layeradd', function (e) {
    var center = e.layer.getCenter();
…
});
```

**Comment by neothemachine** [comment]
I stumbled over the same thing just now. The fact that getCenter() only works after the layer is added to the map should be added to the docs.
