### ISSUE TITLE
Misleading error message when circle radius is NaN

### ISSUE THREAD

**Issue by k-nut** [Leaflet/Leaflet#4235]
If a `L.circle` is created with proper coordinates but a radius that is `NaN` (e.g. `L.circle([36.83711,-2.464459], NaN)` )leaflet throws an error like: `Uncaught Error: Invalid LatLng object: (36.83711, NaN)`. 

This makes it look like the latitude/longitude are `NaN` where it really is the circle's radius. 

This is very confusing and it makes debugging harder because you start looking at the wrong place. 

See [this fiddle](http://jsfiddle.net/p8137Lbo/) for an example. As far as I can tell it happens with leaflet 0.7.7 as well as the 1.0.0-beta.2 and is not browser dependent.

**Comment by IvanSanchez** [comment]
I don't think this is really critical, but throwing a couple of verbose errors in the `L.Circle` constructor is easy enough.

**Comment by k-nut** [comment]
Awesome, thank you for that amazingly quick fix! I also just added a test for this in #4241.

**Comment by jonasroessum** [comment]
@k-nut Thank you so much, you just saved me. I kept looking through the call stack and couldn't figure out why the longtitude of my latLng got parsed as NaN.
