### ISSUE TITLE
Default size for L.DivIcon should not be set by default?

### ISSUE THREAD

**Issue by MadTigger** [Leaflet/Leaflet#4238]
Think I found a design bug. I was working with some L.DivIcon objects tonight, and I noticed that if I put text in the html field, it would spill out of the div rendered on map. I took a look at the source (in both 0.7.7 and Leaflet 1.0.0-beta.2, I am testing both in my project), and the code is as follows:

L.DivIcon = L.Icon.extend({
	options: {
		iconSize: [12, 12], // also can be set through CSS
		/*
		iconAnchor: (Point)
		popupAnchor: (Point)
		html: (String)
		bgPos: (Point)
		*/
		className: 'leaflet-div-icon',
		html: false
	},

I suspect that the default Icon size was set to 12,12 because this object is inheriting from the Icon base class, where a fixed 12x12 image would be a logical default value. However, since this is for 'everything else but an icon type image', setting this default seems counterproductive, and extra css that will probably get overridden every time it is used. Why not just set the height & width to auto or omit a fixed height or width entirely? 

Not a critical bug, but it is certainly inconvenient to have to hunt down and set a css override.

**Comment by hyperknot** [comment]
@MadTigger Leaflet is using these L...extend(options: {}) structure to define the **default** settings for every object type, but those are just *defaults*. 

You are encouraged to use your own values, for an example how: have a look at https://github.com/Leaflet/Leaflet/blob/master/debug/tests/opacity.html

Also, do not use a CSS override, as the centerings would be off!

**Comment by MadTigger** [comment]
I understand how the options tags work, and for some cases what you suggested might work. If I had an image with fixed dimensions to display for example.

However, if you were to use an element of unknown size, say a string, what do you pass to the override? I was trying to dynamically put some location names on a map as clickable tags with a border around the name, and to do that you would need do do something like:

                L.marker([data.X, data.Y],
                {
                    icon: L.divIcon({className:'MapElement', html:data.Name, iconSize: 'auto' })
                })

...in order to tell the class that it needs to auto size the div around whatever string that you pass in. iconSize expects a point object, and whatever value is passed in is used to set the explicit height and width of the div.

Perhaps I am using the wrong object to display strings on a map, but it seems to me that you are caught in the mindset that a marker should only ever be used for images. (Although that even is kind of a poor argument, as what if I want to dynamically display differing size images on a map? Do I have to open each file to get its dimensions first? seems inefficient...) 

If there is a better object, please tell me, but then your documentation needs correction, as it says, 'Represents a lightweight icon for markers that uses a simple div element instead of an image.' which is a pretty clear indicator of intent.

**Comment by lucymcknight** [comment]
Why was this never addressed? I have the same use case as MadTigger

**Comment by MadTigger** [comment]
hyperknot closed this before actually trying to understand the problem fully. I didn't pursue it because if the project devs aren't going to take the time to discuss an issue before closing it, I am not going to waste my time trying to help them.

Good luck lucymcknight, perhaps they will listen to you.

**Comment by IvanSanchez** [comment]
@MadTigger We do take time on issues. We also have a lot of issues, and a real life outside of the issue tracker that takes time. I would appreciate if you stopped using passive-aggressive language.

> Why not just set the height & width to auto or omit a fixed height or width entirely?

Because [this line of code](https://github.com/Leaflet/Leaflet/blob/release-v1.0.3/src/layer/marker/Icon.js#L112) assumes that the `iconSize` (and `shadowSize`) are instances of `L.Point` to calculate a default value for the icon anchor. Notice how `DivIcon` doesn't set a value for the `iconAnchor`, and how the `DivIcon` anchors itself on its centre.

> However, if you were to use an element of unknown size, say a string, what do you pass to the override? 

Nothing, because right now [this line of code](https://github.com/Leaflet/Leaflet/blob/release-v1.0.3/src/layer/marker/Icon.js#L121) will always evaluate `size` to `true`, because `size` was assigned an explicit instance of `L.Point`, and there's no branch to treat the case where `sizeOption` is a [falsy](https://developer.mozilla.org/en-US/docs/Glossary/Falsy) value.

So in order for the code to accept falsy values for the `iconSize` and `shadowSize` options, there need to be unit tests for the cases where the anchor is or is not defined, and think about when `size` and `anchor` should be allowed to be falsy, and where should the icon anchor to in that case, and note that in the docstrings.

I think I've used a reasonable amount of time pointing out why the current behaviour, and how to overcome it. You folks will be more than welcome to *use* your time writing a patch for it and submitting a merge request.

**Comment by MadTigger** [comment]
I apologize if I came off as passive aggressive. The tone I was shooting
for was straight aggressive, but perhaps I was being too polite.

I totally understand that on projects like this, work is done on a
volunteer basis and that there are a limited number of hours in a day. I
have no problem with this, and I am prepared to be infinitely patent to
work through an issue. I am willing to work with key stakeholders on a
project to insure solid, robust design. I don't mind in writing a patch and
submitting it, or just assisting another dev who owns a particular feature.
I am in for whatever it takes to get to the code in a good final state,
regardless of how long it takes.

What I am not prepared to do, is put up with people summarily closing a
ticket I open. When someone takes the time to document a potential design
issue, you might at least do them the courtesy of discussing it. I could
have just made the change, but I was under the illusion that good dev
practices included understanding the design intents before you start coding
and coordinating your ideas with others.

So, you have burnt a bridge. Good luck with your project, I have other
things I can do with my time.

**Comment by fchabouis** [comment]
Hello,
I'm no expert but it seems that explicitly creating the divIcon with iconSize: null works.
For example : http://jsfiddle.net/595cuzws/
Hope it helps

**Comment by joallard** [comment]
@fchabouis Thanks. I'd recommend that for the documentation.

**Comment by DanielRuf** [comment]
Interesting, this was the only way to get a fluid width. This should be documented.

**Comment by perliedman** [comment]
@DanielRuf @joallard PRs very welcome!

**Comment by tuukka** [comment]
@IvanSanchez How to best document the current situation with Leafdoc - that is, can `iconSize` in `DivIcon` be documented as overriding the default value and description while showing that it is originally defined in `Icon`? I'm imagining a way to visualise this with a remark "This option inherited from Icon" with an expandable row to easily compare with the original definition.
