### ISSUE TITLE
Strange zooming behaviour with vector (extended L.geoJson) layers on 1.0.0

### ISSUE THREAD

**Issue by grantHarris** [Leaflet/Leaflet#4247]
I have extended L.geoJson for my own purposes. This extended class takes care of querying the backend with a bbox amongst other tasks. Upon upgrading from 0.7.7 to 1.0.0 I have encountered a strange zooming problem where the vector layers get moved out of sync from the base tile layer. See below:

![gif](https://cloud.githubusercontent.com/assets/1750776/13058246/d058bc24-d3d6-11e5-81c8-63f66a5cb30d.gif)

I'm a bit at a loss for what is causing this. Have you encountered anything similar? Any ideas?

Setting zoomAnimation to false on the map prevents this issue (obviously with a lack of animation).

**Comment by willemx** [comment]
Seems the same as my problem [here](https://github.com/Leaflet/Leaflet/issues/4053)
I haven't found a solution yet. Went back to 0.7

**Comment by mourner** [comment]
@grantHarris can you set up a _minimal_ test case (e.g. on JSFiddle) that reproduces the issue?

**Comment by grantHarris** [comment]
@mourner Will do. Might take me a couple days before I have the time, but I'll post back here.

**Comment by kdhenry** [comment]
@mourner Not the original poster, but I was able to replicate the issue and trace it down (in my case) to having mapbox.js loaded in after leaflet 1.0.0. See fiddle [here](http://jsfiddle.net/khenry/p39mvgnr/)

The zoom behavior is [normal with 0.7.7](http://jsfiddle.net/khenry/tqa3vaxo/), and I haven't delved too deeply into mapbox.js and what may be causing the issue there.

**Comment by mourner** [comment]
@kdhenry mapbox.js needs some adjustments for 1.0.0, and the released version is tailored for 0.7.7, so this does not appear to be a Leaflet issue.

**Comment by MuellerMatthew** [comment]
I just updated my leaflet JS from an older 1.0-dev version to 1.0.0-rc1, and I noticed this behavior occurring when I was using my old css.  Once I updated my leaflet css this behavior was fixed.

**Comment by MarioDabrowski** [comment]
Having the same issue (1.0.1), anybody find a solution?

**Comment by ghybs** [comment]
Hi @MarioDabrowski,

The described symptoms are very similar to https://github.com/Leaflet/Leaflet/issues/4774
MuellerMatthew's finding about CSS version mismatch is the same as in the above linked issue.

**Comment by grantHarris** [comment]
@MarioDabrowski I can confirm the issue (in my case) was a CSS version mismatch as mentioned by @ghybs

**Comment by kofronpi** [comment]
I have the same css version and this issue is still happening sometimes.

**Comment by perliedman** [comment]
@kofronpi please post a minimal example illustrating the issue if you believe this is a problem in Leaflet. With the current information, it is impossible for us to take this further.
