### ISSUE TITLE
Need to stop map drag propagation

### ISSUE THREAD

**Issue by turban** [Leaflet/Leaflet#4249]
The drag start event in L.Draggable propagates causing trouble if a draggable map is placed within a draggable container. The dragging of the container is overriding map dragging, which is not what I would expect. I'm not able to access the event outside the Leaflet API to stop the propagation.

![Leaflet drag bug](https://cloud.githubusercontent.com/assets/548708/13073625/12655a0e-d4a0-11e5-9d5c-a7ba5067b4b9.gif)
The fix is to add "L.DomEvent.stopPropagation(e);" to the _onDown-method: https://github.com/Leaflet/Leaflet/blob/master/src/dom/Draggable.js#L46

![Leaflet drag fix](https://cloud.githubusercontent.com/assets/548708/13073608/060a307c-d4a0-11e5-869b-598f450ecaea.gif)
Leaflet version 1.0 beta 2

**Comment by IvanSanchez** [comment]
@turban Can you please make a pull request with your proposed fix?
