### ISSUE TITLE
getBounds() + fitBounds() zooms out map

### ISSUE THREAD

**Issue by hyperknot** [Leaflet/Leaflet#4255]
Running a getBounds() and then a fitBounds() might zoom out the map.

It depends on zoom level, map element size, probably some rounding error.

http://playground-leaflet.rhcloud.com/juq/2/edit?html,output

**Comment by hyperknot** [comment]
Introduced with 3fde3c03 cc @IvanSanchez

**Comment by IvanSanchez** [comment]
Not really critical, so I'll push it to 1.1. This will need some unit tests.

**Comment by hyperknot** [comment]
You are right about unit tests, but this broke non-fractional users, so existing uses might be affected if this gets in rc1.

**Comment by IvanSanchez** [comment]
OK, let's push it into 1.0...

**Comment by mohsen1** [comment]
I'm still seeing this issue in version 1.0.2

**Comment by perliedman** [comment]
@mohsen1 I think you're seeing a different problem - if you check that playground linked in the first comment to this issue (http://playground-leaflet.rhcloud.com/juq/2/edit?html,output), it runs latest `master`, and it does not exhibit the described issue any longer.

Can you provide an example that triggers the problem you're seeing?

**Comment by mohsen1** [comment]
@perliedman after hours of head-scratching I finally was able to make a JSBin that reproduces the issue:

http://playground-leaflet.rhcloud.com/voli/1/edit

It only happens if you provide padding option to `fitBounds`

**Comment by perliedman** [comment]
@mohsen1 not sure if I follow, but if you include padding, the map will have to be zoomed out to include the old map bounds as well as the padding. The map's current bounds doesn't include any padding, so if you add padding, the map _must_ be zoomed out. So I'd say the observed behaviour is exactly as expected.

**Comment by mohsen1** [comment]
If you click on fit bounds button multiple times you'll see map is zooming out again and again. Shouldn't it for those two points considering given padding at first try and when we try?

**Comment by perliedman** [comment]
No, each time you call the map's `getBounds`, it will return the _current_ bounds, not accounting for any padding you gave to `fitBounds`. The padding is only used to expand the actual bounds we fit to, it's not a part of the maps state.

**Comment by mohsen1** [comment]
So instead of starting from `map.getBounds()` I should start with `new L.LatLngBounds();` I think. Is that correct?

**Comment by MiguelMRebocho** [comment]
I spent quite some time around this issue. Posted my solution on stackoverflow: https://stackoverflow.com/a/61810549/12347905
