### ISSUE TITLE
Attributions not changing when tilelayer changes

### ISSUE THREAD

**Issue by siimots** [Leaflet/Leaflet#4257]
Hi!

Problem: Modified Attribution Control text not changing when tilelayer is changed.
Version: Not working in 1.0, but works in 0.7.7

My code:
```
var map = L.map('map', {
	center: [58.81, 23.08],
	minZoom: 8,
	maxZoom: 19,
	attributionControl: false,
	zoomControl: !L.Browser.mobile,
	layers: [navionics_kaart, weatherstations]
});
```

```
L.control.attribution({
	prefix: false,
	position: 'bottomleft'
}).addTo(map);
```

When I delete second block and use default position for Attribution control, then everything works fine.

Am I using L.control.attribution incorrectly in 1.0? Because same code in 0.7.7 works as I want.

[Link to my website where bug is present](http://siim.planet.ee/meri/)

**Comment by IvanSanchez** [comment]
Hhhhmmmm, interesting. At first sight I don't see any problem with your code.

I've copy-pasted the relevant bits of the website into a playground to have a better look: http://playground-leaflet.rhcloud.com/jad/1/edit?html,output

**Comment by snkashis** [comment]
Bisecting indicates we should be looking at https://github.com/Leaflet/Leaflet/commit/6b132009af48b4e3f9b4f25cbcf241e47009f905

**Comment by snkashis** [comment]
Okay, so made a debug page directly from @siimots code, and this PR solves for his case, as well as not affecting existing behavior for  attribution controls added by init hooks.

**Comment by IvanSanchez** [comment]
@snkashis Unfortunately your fix was incomplete - I needed to make some unit tests at https://github.com/Leaflet/Leaflet/commit/663978227dc89a4b0269a50b6c6d4d7dcce79f5c - unit tests are your friend!

**Comment by snkashis** [comment]
Yep, thanks for spotting this, had a feeling it involved more than my initial commit.
