### ISSUE TITLE
map on click fires when GeoJSON is clicked on leaflet 1.0

### ISSUE THREAD

**Issue by rgtaylor1989** [Leaflet/Leaflet#4258]
In leaflet 1.0 beta2, when clicking on a GeoJSON with a click function assigned along with a map click function defined, they both fire instead of just one. This doesn't happen in the older versions of leaflet. See fiddle for examples.

Leaflet 7.7
http://jsfiddle.net/tator/5e209s9c/14/

Leaflet 1.0 beta2
http://jsfiddle.net/tator/em9cLfk4/4/

**Comment by IvanSanchez** [comment]
@rgtaylor1989 This is now expected behaviour in 1.0.0 - events from layers bubble up to the map. See, for example, #3307

**Comment by rgtaylor1989** [comment]
I see. Have to use 
L.DomEvent.stopPropagation(e)
to prevent this from happening. 

Keep up the good work leaflet team.
