### ISSUE TITLE
panTo() ignores worldCopyJump option

### ISSUE THREAD

**Issue by delner** [Leaflet/Leaflet#4260]
I've been developing a web app using Leaflet where the user locates a city by panning to it, then double clicking to place a marker. After the marker is placed, I call the `panTo()` function to pan the map to the location of the city.

Through the course of this interaction, the user gets a weird experience if they pan around the entire map before `panTo()` is called: 
1. It will rubberband the map around the entire world back to the equivalent place where they started.
2. Any markers on the location in question will 'disappear' (presumably still on a neighboring copy to the center map that Leaflet pans to.)

Here's a video of the interaction I'm seeing. In this case, I'm starting at Los Angeles, scrolling westward around the Earth back to Los Angeles, placing a map marker (the circle that appears before the rubberband), and then calling `panTo` with the coordinates of Los Angeles. When I call `panTo` it rubberbands eastward around the world.

![panTo oddity](http://i.imgur.com/KhDKwqQ.gif)

I'm not sure whether it qualifies as a bug, but it definitely doesn't feel like great behavior, especially because it "wipes out" map markers in the process. Thoughts?

**EDIT**:

This is for Leaflet master (1.0.0beta2 + some recent bugfixes)

I was calling `panTo()` with the following:

```
leafletMap.panTo([city.lat, city.lng], { animate: true, duration: 1 });
```

**Comment by IvanSanchez** [comment]
Have you tried the `worldCopyJump` map option?

**Comment by IvanSanchez** [comment]
I've made a [playground](http://playground-leaflet.rhcloud.com/kim/edit?html,console,output) showing this bug:

```js
	var mad = [40.40, -3.7];

    var map = new L.Map('map', {center: mad, zoom: 2, worldCopyJump: true});

    var positron = L.tileLayer('http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, &copy; <a href="http://cartodb.com/attributions">CartoDB</a>'
    }).addTo(map);

    var marker = new L.Marker(mad);
    map.addLayer(marker);

    for(var i=1; i<=4; i++) {
		setTimeout((function(a){
			return function(){
				console.log('panning to', [40.40, -3.7 + (90 * a)]);
				map.panTo( [40.40, -3.7 + (90 * a)]);
            }
		})(i), 1000 * i);
    }

	setTimeout(function() {
		map.panTo(mad);
	}, 5000);
```

**Comment by delner** [comment]
Oh, interesting. No I haven't, I'll see if adding the option changes anything.

**Comment by pmast** [comment]
Probably dublicate: #2125

**Comment by Malvoz** [comment]
> Probably dublicate: https://github.com/Leaflet/Leaflet/issues/2125

Yes.
