### ISSUE TITLE
_convertLatLong Returns nothing Causing _initWithHoles to Fail

### ISSUE THREAD

**Issue by ismail44** [Leaflet/Leaflet#4264]
There is an instance where _initWithHoles fails because _convertLatLong returns nothing if a set of holes is passed in that already an instance of LatLong. 

```
_initWithHoles: function (latlngs) {
		var i, len, hole;
		if (latlngs && L.Util.isArray(latlngs[0]) && (typeof latlngs[0][0] !== 'number')) {
			this._latlngs = this._convertLatLngs(latlngs[0]);
			this._holes = latlngs.slice(1);
			for (i = 0, len = this._holes.length; i < len; i++) {
				hole = this._holes[i] = this._convertLatLngs(this._holes[i]);
				if (hole[0].equals(hole[hole.length - 1])) {
					hole.pop();
				}
			}
		}
		// filter out last point if its equal to the first one
		latlngs = this._latlngs;

		if (latlngs.length >= 2 && latlngs[0].equals(latlngs[latlngs.length - 1])) {
			latlngs.pop();
		}
	},
```

The second call to convertLatLngs seems to return nothing because the previous call already converted the set of LatLngs to a LatLng type?

**Comment by IvanSanchez** [comment]
> There is an instance where [...]

How can that instance be triggered? Can you publish some reproducible case? (e.g. using http://playground-leaflet.rhcloud.com/ )

**Comment by ismail44** [comment]
I actually first noticed it while trying to integrate the WFS-T plugin from Flexberry into the app. I can certainly add that to the playground if you like. However, it still seems like the issue is that this._convertLatLngs can return nothing which would make the following line:

`if (hole[0].equals(hole[hole.length-1])){`

File because hole is then undefined.

**Comment by IvanSanchez** [comment]
@ismail44 That's still not helpful. You don't need to point at the tiny bit that you think is wrong, you need to *convince* me that there is a problem in the first place, and that the problem is Leaflet's fault.

Let me quote from [How to report bugs effectively](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html):

> It's the same with programmers. Providing your own diagnosis might be helpful sometimes, but always state the symptoms. The diagnosis is an optional extra, and not an alternative to giving the symptoms. Equally, sending a modification to the code to fix the problem is a useful addition to a bug report but not an adequate substitute for one. 
> 
> [...] Using your intelligence to help the programmer is fine. Even if your deductions are wrong, the programmer should be grateful that you at least *tried* to make their life easier. But report the symptoms as well, or you may well make their life much more difficult instead.

**Comment by ismail44** [comment]
But, you DO see how potentially returning from a method without a value, then using attempting to use that undefined value 1 line later could potentially be bad. 

Frankly, you can fix it or not... I will find another solution. I'll close this issue.

Thanks for your "help"?

**Comment by IvanSanchez** [comment]
> But, you DO see how [...]?

No, @ismail44, I don't see that! If I cannot see the problem (in a reproducible manner), if I cannot see an error message, if I cannot see a screenshot, if I cannot see Leaflet misbehaving somehow, then I cannot be sure there's a problem.

Show me a case in which Leaflet misbehaves, then I'll pay attention (as I did with hundreds of bugs right here). If you show me nothing, I cannot be sure there's a problem, I cannot be sure of the impact of the hypothetical problem, and I cannot start thinking about fixing something that I don't know how is failing.

**Comment by ismail44** [comment]
You honestly cannot from a software engineering standpoint see where if you
return nothing from a method then try to use that value 1 line farther down
it will produce an error. This isn't rocket science. Again... I have my own
problems. Look at it, don't look at it... It is really inconsequential to
me. I've fixed it locally.

**Comment by hyperknot** [comment]
@ismail44 I believe people would be more than happy to help you, IF you could provide a minimal http://playground-leaflet.rhcloud.com/ example. 

We need to see a working example, reproducing the bug, showing console errors!

**Comment by ismail44** [comment]
I have ZERO interest in discussing this further. The question isn't whether
or not someone would or would not be happy to help, I believe they are (and
have been). However, it's a simple principle.. again it's not rocket
science... if you return null (nothing, undefined, whatever) and try to use
it later the it causes a runtime error. That was all I was trying to say.
There is nothing I could put in the sandbox to show that if you do return
nothing then try to use it it breaks.

**Comment by IvanSanchez** [comment]
So I've had a look at the thing anyway.

The only way to trigger the issue (`_convertLatLong` returning `undefined`) is to use the 0.7.x versions of Leaflet (a piece of information that *should* have been provided, as we ask in [`CONTRIBUTING.md`](https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md#reporting-bugs)), and feed **non-numerical** data to a polyline or polygon constructor.

We can safely dismiss this as a case of [GIGO](https://en.wikipedia.org/wiki/Garbage_in,_garbage_out) (unless proven otherwise).

Finally, I must ask @ismail44 to read [How to ask questions the smart way](http://catb.org/~esr/faqs/smart-questions.html) and [How to report bugs effectively](http://www.chiark.greenend.org.uk/%7Esgtatham/bugs.html) - if you make it easier for the upstream devs to understand your problems, your requests will be handled quicker. Help the developers help you. And I'm not talking about Leaflet - I'm talking about any software project out there.

**Comment by ismail44** [comment]
Is 0.7 not the current version that should be used? It's the version that's stated on the site. Again it may be GIGO, the plugin may be sending poor data, however, again... returning nothing from a method, regardless of the data coming into it... then trying to use that value after, will ALWAYS return a runtime error.

Again... I was just trying to bring something to the devs attention... I certainly didn't have to as I fixed it locally. Being insulting and combative is certainly not a way to treat other humans. I know no one wants to hear that their code is bad, but in this case again read the code... if you hit that path where you return nothing from _convertLatLng, then try to evaluate that response it will result in an error. Maybe throw an exception or return the original value... who knows. Again, that's not my problem... 

Having said that... thank you for looking into this. In the future if I find something I feel isn't correct I'll better attempt to help you help me.

**Comment by mourner** [comment]
:+1: thanks, we'll keep this in mind. No need for long dramatic discussions.
