### ISSUE TITLE
ImageOverlay Bring To Back Error

### ISSUE THREAD

**Issue by PowerPan** [Leaflet/Leaflet#4269]
This is my code:
```
var imageUrl = 'images/thermal.png';
var imageBounds = [[54.3, 6.7], [54.6,7.5]];
var overlay = L.imageOverlay(imageUrl, imageBounds).addTo(map);
overlay.bringToBack();
```

And Firebug give me this Error Back:
```
TypeError: this._map is undefined
...mage),this},bringToBack:function(){var t=this._map._panes.overlayPane;return thi...

	
```

I Use Leaflet 0.7.7 in Firefox

**Comment by IvanSanchez** [comment]
I [cannot reproduce the error](http://playground-leaflet.rhcloud.com/soc/edit?html,output). Can you make a full reproducible example?

**Comment by IvanSanchez** [comment]
No more information has been provided, and more than a few weeks have passed. We'll assume this issue is no longer relevant and/or there is no interest to make a better report.
