### ISSUE TITLE
Leaflet does not display 2048x2048px tiles at their native resolution (at least v0.7.2)

### ISSUE THREAD

**Issue by stirringhalo** [Leaflet/Leaflet#4270]
I have a complete geowebcache serving up WMS tiles directly from the gwc endpoint (http://localhost:8080/geoserver/gwc/service/wms). However, I'm facing an issue where the entire map scene is scaled to fit the window, even if I make the map area a fixed pixel size area. The result is that the tiles are not displayed at their native resolution.

I can see the WMS requests go out and return a 2048x2048px response. Since each pixel is larger than my screen size, it should only require a single WMS request to fill the map. However since the the WMS tiles are rescaled, it takes many (>100 WMS requests) to fill the display.

Even in chrome on high zoom levels, I get a brief flash where the tile is displayed at the proper scale and then it is scaled to fit.

If I change leaflet.js and leaflet-src.js, 

        }), o.TileLayer = o.Class.extend({
            includes: o.Mixin.Events,
            options: {
                minZoom: 0,
                maxZoom: 18,
                tileSize: 2048, /* This is important, was 256 */
                subdomains: "abc",
                errorTileUrl: "",
                attribution: "",
                zoomOffset: 0,
                opacity: 1,
                unloadInvisibleTiles: o.Browser.mobile,
                updateWhenIdle: o.Browser.mobile

It performs exactly as expected. 1-2 WMS requests go out, perfect scaling and responds very quickly.

How would this best be fixed for WMS layers?

**Comment by mourner** [comment]
We don't support really old Leaflet versions like 0.7.2. 

1. Try to reproduce this in 0.7.7 and 1.0.0-beta2.
2. Create corresponding minimal test cases (e.g. with JSFiddle).

**Comment by stirringhalo** [comment]
Oop, I was integrating a WMS server with a website already in use by someone else so I was going with the existing leaflet version.

1) I can confirm the problem persists in both 0.7.7, 1.0-dev 1.0.0-beta2 and 
Behaviour is different. In 0.7.7, the map is displayed but scaled to fit in the map window. In 1.0-dev, the any param (height: "2048", width: "2048") I add to the L.tileLayer.wms request is ignored. I then get a response from the WMS server that the 256 tile size requested does not match the 2048 tiles supported by the WMS server.

2) I can't do a minimal test case with my own WMS server, but I will set up a geoserver for you to download that is pre-cached. I will have that attached shortly.

**Comment by stirringhalo** [comment]
Bah, I hadn't had enough coffee.

If I used "tileSize" instead of height/width, it works fine. Also, I was using the pixel size in quotes, which prevented it working properly despite showing the correct parameters in the Firefox developer tab. 

Though, a single tileSize does prevent non-square WMS tiles (but this isn't an issue for me currently)

Cheers
