### ISSUE TITLE
Dynamic show/hode zoomControl

### ISSUE THREAD

**Issue by zatziky** [Leaflet/Leaflet#4271]
Hello,

I know that zoomControl can be disabled or hidden on startUp using defaults (http://leafletjs.com/reference.html#control-zoom). Dynamically it can be done using `visibility: hidden | visible`. It would be nice to have similar methods as for `map.zoomControl.enable()` and `disable()`. Would this feature make it to a future release?

Best regards,
Zat

**Comment by IvanSanchez** [comment]
No. You can already use `control.addTo(map)` and `control.remove()`.
