### ISSUE TITLE
Adding or removing layers from layers control which has been removed from the map causes null reference

### ISSUE THREAD

**Issue by perliedman** [Leaflet/Leaflet#4274]
If you add a layers control to the map, and later remove it from the map, you can't add or remove layers from it, since it causes a null reference.

The problem occurs when `_addItem` is called, and `this._map` is not set: https://github.com/Leaflet/Leaflet/blob/master/src/control/Control.Layers.js#L190

We could probably just skip calling `_update` when `this._map` is not set, since `_update` will be called again when (if) the control is added to the map again.

This issue also exists in 0.7.x.

Fiddle to reproduce: http://playground-leaflet.rhcloud.com/cal/edit?html,output

**Comment by IvanSanchez** [comment]
Looks like skipping `this._update()` when calling `addBaseLayer` or `addOverlay` or `removeLayer` if `this._map` is not set should do the trick.

This seems very simple. How about we tell @Charlotteis/@YourFirstPR so a newbie can fix it?

**Comment by perliedman** [comment]
@IvanSanchez :+1: sounds like a plan!

**Comment by Charlotteis** [comment]
Thank you!

**Comment by errebenito** [comment]
I can probably do this one. Just so we're all on the same page, I suppose the _modus operandi_ would be as follows, feel free to correct me if I overlooked something:

1. Claim the issue (done, I guess)
2. Fork the repo
3. Modify _addBaseLayer_, _addOverlay_ and _removeLayer_ to only return _this._update()_ if _this._map_ is not null. Point of interest: what should be returned if it is null?
4. Commit fix and make pull request.

If that is correct and nobody else claimed it while I typed this, I'll get to it.

**Comment by IvanSanchez** [comment]
@errebenito If you read the [docs for `L.Control.Layers`](http://leafletjs.com/reference-1.0.0.html#control-layers-addbaselayer), you'll see that the three methods return `this`. In other words, they return a reference to the control so you can chain methods.

If you look at the code, then the three public methods do `return this._update()` and then `_update()` does `return this;`.

(Por cierto, Raúl: si rodeas texto con *accent greu*, entonces tiene `apariencia de código`. Si lo rodeas con asteriscos, *entonces es cursiva* ;-) )

**Comment by errebenito** [comment]
Ah, I see. So if `this._map` is null I merely return `this` without calling `_update()`. Alright, I'll comment again once it's done. Thanks for the clarification (y el consejo sobre Markdown).

**Comment by errebenito** [comment]
Pull request created. For reference, the return statement now looks like this:

`return (this._map === null) ? this : this._update;`

**Comment by IvanSanchez** [comment]
OK, Raúl, a few things didn't go too well on your first try :-P

* The unit tests failed! (check the link from pull request for details, and run `npm test` locally next time)
* There is a very important difference between the old `return this._update();` and the new `: this._update;`!
* The rest of the Leaflet code doesn't check if `this._map` is a certain type (`null`, `undefined` or `false`), it just checks if `this._map` is [truthy](https://developer.mozilla.org/docs/Glossary/Truthy) - see for example https://github.com/Leaflet/Leaflet/blob/master/src/layer/LayerGroup.js#L25 . If I had to guess, `this._map` starts being `undefined` and will never take a value of `null`.

Fix that, then `git commit --amend`, then push again, then I'll have another look at the PR ;-)

**Comment by errebenito** [comment]
Apparently I need more coffee before I start coding. I removed the trailing spaces that were causing the build to fail, added the missing parentheses to `_update()` (whoops), and modified the check for null to adapt to existing coding style. 

The unit tests are timing out, however. Not sure if that's due to my changes.

**Comment by IvanSanchez** [comment]
@errebenito :

![](http://www.homewetbar.com/images/prod/w-Giant-Coffee-Cup75917.jpg)

Read this carefully: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator , then look at your ternary operators.

Also, @mourner has a strong dislike for having several commits to make a small change - please consider [squashing all commits into one](http://makandracards.com/makandra/527-squash-several-git-commits-into-a-single-commit).

**Comment by IvanSanchez** [comment]
The unit tests that are timing out are mine (from https://github.com/Leaflet/Leaflet/commit/f777f42c6bf98ed0cfad53d429d95c7621eee01d ), and this is not the first time I see them timing out today. I would guess the Travis CI servers are experiencing high load, and maybe we'll need to increase the timeout limit for those.

**Comment by errebenito** [comment]
Thanks for the coffee and the patient guidance (apparently there's no shortage of opportunities to shoot oneself in the foot, even with the simplest of issues; great way to get experience though). It seems I really needed it, switching the ternary operator around and all... :(

Alas, the tests still timeout, and I had to deal with merge conflicts due to having started the work directly on github instead of cloning to my local machine (which I ended doing since one can't rebase directly from the web interface; my mistake once again), so if I did the rebase right, I ended up with an additional commit for the merge conflicts. I can rebase and commit again after dinner if I have to.

**Comment by IvanSanchez** [comment]
@errebenito Don't worry, these kind of "newbie" issues are just for that: learning how the review workflow works (other people will notice mistakes), and things like rebasing to make clean PRs.

Please take a bit of time to rebase and squash into one commit. Hopefully, Travis will behave this time and the unit tests won't timeout.

**Comment by errebenito** [comment]
Sure. I'm at work right now, but I'll look into it later today.

**Comment by errebenito** [comment]
Soooo... I think I learned to rebase. The PR shows one commit only now, and I double-checked the ternary operators, just in case. Travis isn't behaving though. I'll await further instructions, but it seems an improvement over the initial plethora of mistakes.

**Comment by IvanSanchez** [comment]
@errebenito Yeah, the PR looks much nicer now!

Let's wait for some testing on #4289, which *should* fix Travis failing the unit tests, then we can give another kick at your PR :-)

**Comment by errebenito** [comment]
Alright. Let me know if there's anything else I have to do. If not, I'm glad I could help, and I'll be happy to contribute again if there's anything I can tackle. Thanks for everything.

**Comment by IvanSanchez** [comment]
Apparently @mourner jumped in and checked the unit tests and the build. Thanks, @errebenito! (And we hope to see you here again if you'd like!)
