### ISSUE TITLE
put a function plugin as a layer

### ISSUE THREAD

**Issue by candidobugarin** [Leaflet/Leaflet#4282]
Hello!
I'm looking to put a function of a plug with a layer on my map . Example : I have an animation, but it can only appear if you select the animation layer. It is possible?

Thanks

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com) or [stackoverflow](https://stackoverflow.com).
