### ISSUE TITLE
L.tileLayer: Support tms {-y} format

### ISSUE THREAD

**Issue by mvl22** [Leaflet/Leaflet#4284]
When using tms format with a -y value in the tileserver specification, currently Leaflet.js requires this to be specified as ```{y}``` but with a flag ```tms: true``` as documented at:
http://leafletjs.com/reference.html#tilelayer-tms

Various documentation contains references like this:

```
http://geo.nls.uk/mapdata2/bartholomew/great_britain/{zoom}/{x}/{-y}.png
```

e.g. many examples here:
http://wiki.openstreetmap.org/wiki/National_Library_of_Scotland
http://osmlab.github.io/historic-imagery-index/

It would be useful if Leaflet.js could natively support ```{-y}``` so these can be cut-and-pasted and then people spend a few hours working out that they need to remove the - and add the ```tms: true``` flag.

**Comment by mourner** [comment]
That's actually a pretty good idea. Looks more elegant than a `tms` option.
