### ISSUE TITLE
L.geoJSON.resetStyle should be callable without arguments.

### ISSUE THREAD

**Issue by JrFolk** [Leaflet/Leaflet#4298]
`geoJSON.setStyle()` does not require or even utilize a target layer thus, I believe in the spirit of consistency `geoJSON.resetStyle()` should also operate without a target layer.

[My proposed change is here.](https://github.com/Leaflet/Leaflet/compare/master...JrFolk:GeoJSON-api)

I believe `layer.DefaultOptions` was unused because the style was taken from the `geoJSON` layer's *current* style rather than the `featureGroup`'s 'default' style.

Previously, if additional featureGroups were added to a `geoJSON` layer then resetting them all, on a `mouseout` event for instance, would have to be done with `geoJSON.eachLayer()`.  Additionally, the propagated style would be taken from the *last `geoJSON` layer to fire the event*, which could vary depending on which featureGroup initially fired the event, resulting in un-intuitive behavior

With this change, if you add additional `featureGroup`s to a `geoJSON` layer it will retain the 'default' style that it was instantiated with rather than being forced to use the current `geoJSON`'s style.

&nbsp;

As an example, I load several geoJSON features with varying styles into a single `geoJSON` layer.  I want them all to highlight when any feature is hovered over to indicate their grouping, but return to their original style on `mouseout`.  This allows a simple event callbacks to accomplish this:

```javascript
layer.on('mouseover', function(){ this.setStyle(/* highlight features */) })
     .on('mouseout', function(){ this.resetStyle() })
```

&nbsp;

It also allows the addition of a `geoJSON` layer to another `geoJSON` layer and the `styleReset` will propagate as described above.  Previously, because the `geoJSON` layer has no 'default' style, it would end up using no style, which defaulted to the Leaflet style.  While this is probably not recommended, it is possible and thus I think expected behavior should be supported.

**Comment by JrFolk** [comment]
[Another possible addition.](https://github.com/JrFolk/Leaflet/compare/GeoJSON-api...JrFolk:setDefaultStyle)

The inspiration for this, and example application, is giving the user controls to do things like remove the polygon fill/outline, randomize colors in a tessellated layer etc. like Google Earth, but I want to continue to use `geoJSON.resetStyle()` & `geoJSON.resetStyle()` for things like highlighting temporarily on `mouseover` in the manner described in the original issue.

**Comment by IvanSanchez** [comment]
@JrFolk It seems you deleted your feature branch. Can you review the state of your code and submit a pull request?

**Comment by IvanSanchez** [comment]
No more information has been provided, and more than a few weeks have passed. We'll assume this issue is no longer relevant and/or there is no interest to make a better report.

**Comment by ahuillet** [comment]
I suggest re-opening - there is a valid feature request.
The API isn't orthogonal if you can setStyle() without an argument, but can't resetStyle() the same way. One needs to iterate over each layer with eachLayer to call resetStyle.
