### ISSUE TITLE
the zoomend event execute two times

### ISSUE THREAD

**Issue by cnroland** [Leaflet/Leaflet#4299]
map.on("zoomend", zoomend);
function zoomend(evt){
    document.getElementById("test").innerHTML = map.getZoom() + ".zoomend<br>" + document.getElementById("test").innerHTML;
}

**Comment by IvanSanchez** [comment]
Duplicate of #4023

Next time you report a bug, please take time to look for duplicates and follow the guidelines in [CONTRIBUTING.md](https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md)
