### ISSUE TITLE
click event is not working

### ISSUE THREAD

**Issue by jcguarinpenaranda** [Leaflet/Leaflet#4301]
Hello, 

I'm new to Leaflet, but as I have seen from the documentation, the following code should work:
       
`
var map = L.map('map').setView([51.505, -0.09], 13);
map.on('click', function(e){
    console.log(e)
})
`

I am working on Linux Ubuntu with Leaflet v0.7.7. The click event is not being fired with the left click, but with the right click.

Also, on mobile it doesn't work (with cordova).

I got it working on PC with   `map.on('mouseup click tap', function(e) { })`, but on mobile it doesn't want to work. I guess this is an issue.

**Comment by IvanSanchez** [comment]
I'll guess this has been already replied at https://stackoverflow.com/questions/35815735/clicking-on-leaflet-js-stops-working-on-mobile

**Comment by jcguarinpenaranda** [comment]
Thank you!

Juan Camilo Guarín Peñaranda
Estudiante de Ingeniería Multimedia y Emprendedor en tecnología
Universidad Autónoma de Occidente
Otherwise Studios: http://otherwise-studios.com
<http://mailstat.us/tr/t/pleg6bmaikkbgvuq/h/http://otherwise-studios.com/>

2016-03-06 12:29 GMT-05:00 Iván Sánchez Ortega <notifications@github.com>:
