### ISSUE TITLE
continuous drag or scaling problem

### ISSUE THREAD

**Issue by cnroland** [Leaflet/Leaflet#4302]
Hi, at present our project is using the leaflet, I take the map parameters to background program (map.getZoom()  and map.getbounds()) , then load the returned picture by imageoverlay.
excuse me how to solve continuous drag or continuous scaling, only the implementation of calling a daemon?

**Comment by danzel** [comment]
I am not sure what you are asking about. Can you please explain with more details?

This sounds like a "How do I" question, which is better suited for stackoverflow than an issue on github. If so please close this and open a question there.
Thanks.

**Comment by cnroland** [comment]
thank you.
