### ISSUE TITLE
after the program is released to the server

### ISSUE THREAD

**Issue by cnroland** [Leaflet/Leaflet#4305]
in chrome, no scaling effect after released to the server(IIS7), and after scaling, tips to load some of the tiles, each times

**Comment by IvanSanchez** [comment]
I do not understand what you're trying to say. Please read [CONTRIBUTING.md](https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md#reporting-bugs) and write a more clear bug report, providing more information.

**Comment by cnroland** [comment]
when the map is posted to the server, the zoom effect is not in the browser.

**Comment by IvanSanchez** [comment]
What server?

**Comment by cnroland** [comment]
window server 2008 R2 standard

**Comment by IvanSanchez** [comment]
I asked "What server?", not "What OS does your server run?".

Can I use my own web browser to look at your deployed map?

Also, why are you sure this is a Leaflet bug?

**Comment by cnroland** [comment]
sorry, this is my problem.
but, i found a new problem, in IE11, drag the map is not smooth.
http://leafletjs.com/
In your official website home page, the map example is also the same problem.
