### ISSUE TITLE
Button relative to another button (left, right)

### ISSUE THREAD

**Issue by loiggeb** [Leaflet/Leaflet#4307]
Is there a common way to place a button relative to another button. So for example if the user clicks on a tools button in the top-left corner, 4 other buttons with tool functionalities right to the tools button appear. Something like a pop-up button group. When the user clicks the tool button for a second time, all the other buttons dissapear

**Comment by IvanSanchez** [comment]
http://leafletjs.com/plugins.html#user-interface , https://github.com/Leaflet/Leaflet.toolbar

In the future, please use this bug tracker only for bugs.

**Comment by loiggeb** [comment]
Thank you! I will!
