### ISSUE TITLE
In IE11, drag the map is not smooth

### ISSUE THREAD

**Issue by cnroland** [Leaflet/Leaflet#4310]
I found a new problem, in IE11, drag the map is not smooth.
http://leafletjs.com/
In your official website home page, the map example is also the same problem.

**Comment by perliedman** [comment]
Sorry, I can't reproduce this problem. I've looked at http://leafletjs.com/ with IE11 (11.0.9600.18163 on Win7), and it looks about as smooth as it can.

Maybe something on your machine, like a plugin or similar causing this?

**Comment by cnroland** [comment]
my version is ie11(11.0.9600.16384 on window server 2012 R2)

**Comment by IvanSanchez** [comment]
Are you using remote desktop?

**Comment by cnroland** [comment]
yes

**Comment by IvanSanchez** [comment]
Then the lag is introduced by the network lag in RDP, not by Leaflet. The problem will persist using any other browser under those circumstances.

**Comment by cnroland** [comment]
Wait a minute. I'm looking for a few computers.

**Comment by cnroland** [comment]
Thank you very much.
