### ISSUE TITLE
`this._times.length` is `undefined` in `Map.Drag.js`

### ISSUE THREAD

**Issue by czb** [Leaflet/Leaflet#4311]
I have just got report from my client that `this._times.length` is `undefined` in [Map.Drag.js](https://github.com/Leaflet/Leaflet/blob/09c322121197ae8ecb6110ac61bffdafd9d72d25/src/map/handler/Map.Drag.js) in `_onDragEnd` on line `noInertia = !options.inertia || this._times.length < 2;`. I could not reproduce the error so far. The error was triggered on IPad, iOS 9.2.1 in WKWebview. `options.inertia` is kept at default, i.e. `true`.

My only explanation to this error is that in rare situations the `_onDragEnd` is called without `_onDragStart` which then means that this

    if (map.options.inertia) {
        this._positions = [];
        this._times = [];
    }

is never called and `this._times` remains `undefined`.

What do you think?

**Comment by IvanSanchez** [comment]
Yes, the only case where this should happen is when the `inertia` option of the map is changed mid-drag, or somehow `_onDragStart` not firing properly. I would not be surprised if this is a browser bug about the `dragstart` event not firing.

I wonder if [prosthetic-hand](https://github.com/IvanSanchez/prosthetic-hand) could be used to write a reproducible test case. Otherwise it can be hard and tedious to debug.

Maybe we can just work around the problem by setting `this._times` in `addHooks()` no matter what. I'm not sure we want to do that.

**Comment by mourner** [comment]
> Maybe we can just work around the problem by setting this._times in addHooks() no matter what. I'm not sure we want to do that.

There should be no side effects of this though, so I would add it.

**Comment by IvanSanchez** [comment]
If @mourner thinks it's safe to add it, then I'll second.

The change seems quite trivial, so I'll let a newbie commit the changes (wink wink nudge nudge, @yourfirstpr @errebenito @Charlotteis !).

* [ ] Claim the issue
* [ ] Fork the Leaflet repo
* [ ] `git clone`
* [ ] Create a feature branch like `git checkout -b drag-undefineds`
* [ ] Edit the code: Initialize `this._times` (and `this._positions` for good measure) to an empty array in the `addHooks()` method of `L.Map.Drag`
* [ ] Check that you didn't break anything by running `npm test`
* [ ] `git commit` and `git push`
* [ ] Create a pull request

**Comment by errebenito** [comment]
@IvanSanchez I'm at work currently and therefore unable to take a look at this issue, but it seems simple enough, so if nobody else has claimed it by the time I get home, count me in.

**Comment by IvanSanchez** [comment]
@errebenito Let's give @yourfirstpr a bit of time to tweet about it and see if anyone else wants to jump in.

**Comment by errebenito** [comment]
@IvanSanchez Sure. It's gonna be a long day for me at work either way, so there's even the possibility I won't want to look at more source code by the time I finish my shift here ;)

**Comment by IvanSanchez** [comment]
I see @LucasMouraDeOliveira has opened #4324, but I don't think it's quite right.
