### ISSUE TITLE
add a circle layer, but will add two layer to the map object

### ISSUE THREAD

**Issue by cnroland** [Leaflet/Leaflet#4312]
**add a circle layer, but will add two layer to the map object.
Why would you add one more layer?**

var map = new L.Map('map', {});
var osmUrl = 'http://a.tile.openstreetmap.org/{z}/{x}/{y}.png';
var osmAttrib = 'Map data © OpenStreetMap contributors';
var osm = new L.TileLayer(osmUrl, { minZoom: 1, maxZoom: 17, attribution: osmAttrib, detectRetina: true });
map.addLayer(osm);
map.fitBounds(new L.LatLngBounds([51,7],[51,7]));
var circle = L.circle([51, 7], {
            color: 'red',
            fillColor: '#f03',
            fillOpacity: 0.5,
            radius: 100
        });
map.addLayer(circle);

**[this._map.layers] contains 3 values.Why would you add one more layer? Is it a bug?
But use ImageOverlay, [this._map.layers] contains 2 values.**

var map = new L.Map('map', {});
var osmUrl = 'http://a.tile.openstreetmap.org/{z}/{x}/{y}.png';
var osmAttrib = 'Map data © OpenStreetMap contributors';
var osm = new L.TileLayer(osmUrl, { minZoom: 1, maxZoom: 17, attribution: osmAttrib, detectRetina: true });
map.addLayer(osm);
map.fitBounds(new L.LatLngBounds([51,7],[51,7]));

var overlay = new L.ImageOverlay("https://www.lib.utexas.edu/maps/historical/newark_nj_1922.jpg", new L.LatLngBounds([51, 7], [51, 7]), {
            opacity: 0.5,
            interactive: true
        });
        map.addLayer(overlay);

**Comment by perliedman** [comment]
I'm not seeing this on for example Leaflet's homepage (http://leafletjs.com/index.html), it shows the expected three layers (tilelayer, marker, popup).

Can you provide a fiddle or similar illustrating the issue?

**Comment by cnroland** [comment]
**var map = new L.Map('map', {});
var osmUrl = 'http://a.tile.openstreetmap.org/{z}/{x}/{y}.png';
var osmAttrib = 'Map data © OpenStreetMap contributors';
var osm = new L.TileLayer(osmUrl, { minZoom: 1, maxZoom: 17, attribution: osmAttrib, detectRetina: true });
map.addLayer(osm);
map.fitBounds(new L.LatLngBounds([51,7],[51,7]));
var circle = L.circle([51, 7], {
color: 'red',
fillColor: '#f03',
fillOpacity: 0.5,
radius: 100
});
map.addLayer(circle);**

You add a break point in L.Map.addLayer(), you will see this methord three times.

**Comment by perliedman** [comment]
Ok, the extra layer is the renderer being added. See https://github.com/Leaflet/Leaflet/blob/master/src/layer/vector/Renderer.js#L102 . In other words, this is normal.

For the future, please read [CONTRIBUTING.md](https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md#reporting-bugs), and make sure to include a running example illustrating the issue on for example https://playground-leaflet.rhcloud.com/ or https://jsfiddle.net/. Examining issues without examples is a lot of work for Leaflet devs, so you're much less likely to get help unless you do your part.

**Comment by cnroland** [comment]
ok, thank you very mach!
