### ISSUE TITLE
[Documentation] Marker Arrays need a specific notation to work

### ISSUE THREAD

**Issue by trahloff** [Leaflet/Leaflet#4319]
When building the marker array dynamically the notation has to be:
```javascript
newMarkers["m"+some_positive_integer]
```
For example:
```javascript
for(var i=0;i<data.length;i++){
newMarkers["m"+data[i].DEVICE_ID]={...]
}
```
Otherwise the marker won't make it on the map

**Comment by yohanboniface** [comment]
@trahloff sorry, I don't get your point here. I think I'm missing the context.
I'll close the issue because it seems to me no action is required on our part. Please comment and give more details if you think I'm wrong.

Thank you!
