### ISSUE TITLE
GridLayer "load" event fires before tiles are rendered in 1.x?

### ISSUE THREAD

**Issue by jplante** [Leaflet/Leaflet#4322]
We are working with Leaflet and Mapbox and a major mapping project to create a map capable of animating a data-layer over the map to represents different points in time using VCR-buttons and a scrubber.  We achieve this having a single data-layer composed of number of Leaflet-layers that we turn on and off.  Normal on/off of Leaflet would cause a blink, so we can either hide via opacity or visibility of the parent container.  In order to minimize background tile loading, we also constrain layer bounds to 0,0,0,0 when the layer is hidden, and re-expand to desired bounds when enabled.

Regardless, after hitting "play", when we "switch frames", and the next hidden layer become visible for the first time, it doesn't have its tiles yet.  No problem, Leaflet is off and getting them, and once they are there it renders.  Of course, what this causes is that during the first loop, all the frames "blink" until we've looped around, then the shifting is a nice smooth animation.

In order to deal with the "blinking" problem on first pass, we raise a frameChanging event, where we prepare the upcoming hidden layer in the background, listening for its "load" event, and then make it visible, followed by a frameChanged event.  The problem?  It still blinks.  It appears as though the "load" event occurs, and the blank tiles are in the DOM, but hasn't been rendered yet.  If set wrap a `setTimeout(..., 500)` to the "load" event, it's all rendered as desired when "load" is called.  Dropping it to 250ms causes minor blinking, and dropping it to 50ms increases the blinking even further.  

Setting `fadeAnimation: false` fixes the problem when walking through a debugger, but when letting it play at normal speed, swapping hidden-layers every 300ms for example, does not fix it, so obviously walking through the debugger gives it enough time to render.

I'm not sure if this is a browser-issue related to decoding and rendering the image, but it makes the "load" event appear to be a bit of a misnomer, because even though the tile has been 'loaded' or received, and there are not more tiles to get, it's not actually drawn yet.

I'm not sure what the best solution for this is, but I know it would be good to allow Leaflet to be able to deal with the Time (t) dimension as well as z,x,y without a disruptive blink effect.

**Comment by IvanSanchez** [comment]
Can you publish a reproducible example somewhere? (e.g. jsfiddle, jsbin, codepen, http://playground-leaflet.rhcloud.com/ ) We cannot be *exactly* sure of what you mean until we see it with our own eyes (and browsers).

Also: Leaflet 0.7.x or 1.0.0-beta?

**Comment by jplante** [comment]
This is happening in 1.0.0-betaX.  I'm currently trying to track it down myself, and I'll see if I can get a playground set up.  It appears based on some browser event testing, that the "load" event of an HTMLImageElement is fired after its rendered, which is good.  So, it may be related to the fact that tiles fade in.  There seems to be a slight fade even after setting `fadeAnimation: false`, so I'm trying to find what's causing that and see how it responds if I control or prevent it.

**Comment by jplante** [comment]
This is *not* an issue with Leaflet, but MapBox.  MapBox.css has:

```
.leaflet-fade-anim .leaflet-tile {
	opacity: 0;
	-webkit-transition: opacity .2s linear;
	-moz-transition: opacity .2s linear;
	-o-transition: opacity .2s linear;
	transition: opacity .2s linear
}
```

Which forces a transition, regardless of `fadeAnimation: false`.  The issue it causes, is that it appends an additional 200ms to the rendering phase, and so the even though the image `load` event fires, it has not yet been fully drawn, causing a 'blink' if you were to try to swap to that `L.GridLayer` as soon as the layer's `load` event fired.  Removing that CSS rule puts things back in sync.  

I'll try to learn more from MapBox about the true intent of that add-on rule.
