### ISSUE TITLE
Leaflet 0.7.7 throwing Unknown touch event type error in IE10 and IE11 on page load

### ISSUE THREAD

**Issue by DeanoFino** [Leaflet/Leaflet#4323]
Leaflet 0.7.7 (line 7163 leaflet-src.js) error is throwing in IE10 and IE11 (but not IE9) that is preventing page load. 
```javascript
	addPointerListener: function (obj, type, handler, id) {

		switch (type) {
		case 'touchstart':
			return this.addPointerListenerStart(obj, type, handler, id);
		case 'touchend':
			return this.addPointerListenerEnd(obj, type, handler, id);
		case 'touchmove':
			return this.addPointerListenerMove(obj, type, handler, id);
		default:
			throw 'Unknown touch event type';
		}
	},
```

**Comment by IvanSanchez** [comment]
This bug report could be better - my test maps work just fine in IE10/IE11 in stable, so you must be doing something that specifically triggers this bug.

Are you attaching any touch events to anything?

**Comment by DeanoFino** [comment]
This was being caused by an outdated version of the Leaflet-Draw plugin, not Leaflet. Thank you for the input Ivan! Your insight steered me into the right direction. Sorry for the false bug!

**Comment by IvanSanchez** [comment]
It's OK - just keep in mind that the more detailed a bug report is, the easier it is to track down and fix ;-)
