### ISSUE TITLE
leaflet: change popup image using popup.setContent()

### ISSUE THREAD

**Issue by StephGS** [Leaflet/Leaflet#4331]
I am trying to make images in popups change periodically. The function refreshImage periodically `GET` from server a 64based string of image data and sets the src of the img using `popup.setContent()`. The second part takes the coordinance data from a json file and create markers, bind popups and initiate a onClick event handler that will trigger the refreshImage function. Everything from create marker to get data works properly, the data can be shown as image if used in a simple HTML situation. But it just cannot show and refresh the image in a popup. I have tried `popup.setContent()`, `$(popup._contentNode).html()`, `document.getElementById(imageID).src = ` and `document.getElementById(imageID).innerHTML=""`, but none seems to work. Here is my code: 

		function refreshImage(popup,cName,starttime,endtime,curtime) {//the times are Date object
			var data;
			var hour = 60 * 60 * 1000;
			var nexttime = new Date(curtime.valueOf()+hour);
			strcurtime = curtime.toLocaleString();
			strstarttime = starttime.toLocaleString();
			strendtime = endtime.toLocaleString();
			strnexttime = nexttime.toLocaleString();
			if(endtime<nexttime){
				$.get( "/images",{camname:cName, starttime: strcurtime,endtime: strendtime}, function( data, status ) {//
				});
				curtime = starttime;
			}else{
				$.get( "/images",{camname:cName,starttime:strcurtime ,endtime:strnexttime}, function( data, status ) {//      
				});
				curtime = nexttime;
			}

			popup.setContent("<img src=\"data:image/jpeg;base64, "+ data +"\" alt=\"camera_image\" width=\"305\" height=\"210\" border=\"0\" align=\"middle\" id=\"myPic\"><br><p>"+cName+"</p>");
			setTimeout(refreshImage,1000,popup,cName,starttime,endtime,curtime);
		}

		var markers = [];
		d3.csv("static/data/cam_coordinates.json", function(error, data) {
			var cameras = data;
			var starttime = new Date('2015-12-07 07:00:03');
			var endtime = new Date('2015-12-08 08:15:00');
			console.log(cameras.length);
			for(var i = 0; i<cameras.length; ++i){
				var marker = L.marker( [cameras[i].lat, cameras[i].log], {icon: cam}, {title: cameras[i].camera}).addTo(map);
				window.markers.push(marker);
				window.markers[i].bindPopup("<img src=\"\" alt=\"camera_image\" width=\"305\" height=\"210\" border=\"0\" align=\"middle\" id=\"myPic\"><br>"+cameras[i].camera);
				
				var popup = window.markers[i]._popup;

				window.markers[i].on('click', function(popup){
					
					refreshImage(popup,'Ft_Washington_@_179_St', starttime, endtime, starttime);
				});
			}
		});

Developer tool outputs: `Uncaught TypeError: popup.setContent is not a function`
I am noob to Javascript and leaflet, anyone could help me plz?

**Comment by IvanSanchez** [comment]
This is a bug tracker, you will get no support here. See the CONTRIBUTING.md file for pointers on where to ask these kind of questions.
