### ISSUE TITLE
Wrong fonts rendering

### ISSUE THREAD

**Issue by liratanak** [Leaflet/Leaflet#4332]
Hi,

The native name of [Cambodia](https://en.wikipedia.org/wiki/Cambodia) should look like this: 
![](https://cloud.githubusercontent.com/assets/1790248/13902461/fb836542-ee7b-11e5-963e-674f7ffaa15e.png)

While the current on http://leafletjs.com look like this:
![](https://cloud.githubusercontent.com/assets/1790248/13902469/290b20ea-ee7c-11e5-987e-cd5fc007a487.png)

Thanks for considering to fix

Sincerely,
Liratanak

**Comment by IvanSanchez** [comment]
This is not a Leaflet bug, but rather an OpenStreetMap rendering bug. Consider researching into the typefaces used in github.com/gravitystorm/openstreetmap-carto , and see http://www.openstreetmap.org/relation/49898
