### ISSUE TITLE
Leaflet for a custom game map.

### ISSUE THREAD

**Issue by balciseri** [Leaflet/Leaflet#4333]
Hi i'm trying to upgrade my project from 0.7.7 to 1.0.0-beta.2.

I have made two identical fiddles to show you my problem. 

Working with leaflet 0.7.7 https://jsfiddle.net/Mavvo/Lm0Lv6d3/
Not working with leaflet 1.0.0-beta.2 https://jsfiddle.net/Mavvo/k0ofzmbg/
`leaflet.js:6 Uncaught TypeError: Cannot read property 'max' of undefined`
I think this is where max is coming from: `y:this.options.tms?this._globalTileRange.max.y-t.y:t`

I have googled alot and i've seen some old topic about this similar issue.
In one of those topics someone said that the problem was probably that you can't have   tms: true if you are also using crs: L.CRS.Simple.
In another of those topic someone said to don't use tms:true but instead a custom y function something similar to y: function(data)({ -data.y };)} but i coudn't make it work. At the moment i can't find the link to this one, but here some link to similar issues:
https://github.com/Leaflet/Leaflet/issues/2298
https://github.com/Leaflet/Leaflet/issues/2776

If i recall correctly i started my project from http://build-failed.blogspot.it/2012/11/zoomable-image-with-leaflet.html .  Here he said to use tms: true.

At the moment i don't know how to upgrade my little app, do you have any clue? Is this a bug?
Thank you!

**Comment by hyperknot** [comment]
Just a quick note, use: https://leafletjs-cdn.s3.amazonaws.com/content/leaflet/master/leaflet-src.js in your fiddle, it'll tell you where the bug is.

So it is indeed trying to look for `this._globalTileRange.max.y` while `this._globalTileRange` is not initialised, because of tms somehow.

But why are you using TMS? Do you realise it's just a simple Y flipping? If it's a game map, you can just generate the correct coordinates so you don't need TMS flipping.

**Comment by balciseri** [comment]
Thanks for your suggestions! 
When I started I didn't know much about this kind of stuff, actually I don't know so well now either. 
I simply followed two blogs post telling me how to make the tiles out my big picture representing the game map and then used tms:true because with that everything was working fine! 
So back to the present.. I'm more than happy to adapt and do as you said. The problem is that I couldn't make it work they way it should be. 
When I tried to make the Y flip thing leaflet was searching for images with NaN as y.
By the way do I have to make the tiles again or at least organize hem differently in the folders if I switch tms to false?

**Comment by balciseri** [comment]
I've found the posts about the y flipping : 
https://github.com/Leaflet/Leaflet/commit/678a5cbd052a1761787068b8320e81a993cdc3e8#commitcomment-5224256

https://github.com/Leaflet/Leaflet/issues/2897

I tried again : https://jsfiddle.net/Mavvo/2hfoakxy/
I'm doing it wrong because in the console i can see i can't retrieve the tiles:
`Failed to load resource: the server responded with a status of 404 (Not Found)`
`http://mavvo.altervista.org/dofus/mapTiles/3/2/NaN.png`

**Comment by hyperknot** [comment]
@balciseri you don't need -y or TMS, but you will need to regenerate / reorganize your title files not to use the TMS option.

Did you know there is a recent tutorial for a similar case?
http://leafletjs.com/examples/crs-simple/crs-simple.html

**Comment by balciseri** [comment]
Hello.
I was reading it right now :D 
At the moment i don't fully understand it yet.
Anyway i was hoping for just an immediate way of upgrading from an older version of leaflet to a new one. I know there are many projects that used leaflet to render custom images and gamemaps simply following the old tutorials telling to use crs.simpe and tms: true but now it seems not doable to just upgrade to a newest version without redoing part of the project.

So here i am trying to find a solution to my problem.
The tutorial you linked, if i understand correctly, is using just a flat image. The "Zoom" it's not really implemented there are no "zoomed" tiles, it's alwais a single image i think.

I don't understand what the problem is. I mean why before was working and why now it's not. That's why i don't know what to do to adapt to the new leaflet.

Right now you are beeing so helpful to me i appreciate it so much.
It's just that i don't yet see the next step in the right direction!

**Comment by hyperknot** [comment]
I think this is a bug in 1.0, but I'm not an expert in CRS so I cannot confirm it. 

If it's been working in 0.7 and it's broken in 1.0 (as you proved with examples) then I believe it will be fixed soon, so you don't need to do anything.

**Comment by balciseri** [comment]
Thank you again.
For the moment i will stick to 0.7 then.
In the meanwhile i'll try to generate new tiles to work with tms= false like you suggested.
Waiting for an expert to look into this issue then :D

**Comment by perliedman** [comment]
Repeating short form of what I wrote in #4338: `L.CRS.Simple` will not work with `tms: true` in 1.0, since `L.CRS.Simple` has `infinite: true`, meaning it has no bounds. Leaflet needs bounds when working with TMS, since the bounds are used to flip the tile's row coordinate.

This works in 0.7, but only because of implicit bounds inherited from Leaflet's default projection. A better idea is to either:

* flip y coordinates without using TMS (as mentioned in https://github.com/Leaflet/Leaflet/commit/678a5cbd052a1761787068b8320e81a993cdc3e8#commitcomment-5224256)
* fix the tiling scheme to row coordinates growing downwards, like non-TMS, as mentioned by @hyperknot

**Comment by balciseri** [comment]
Thank you, i went down the second path.
Fixing the tiling scheme to row coordinates growin downwards fixed it.

**Comment by balciseri** [comment]
Here is the modified gdal2tiles app which
allowed me to generate tiles without TMS flipping:
[gdal2tiles-leaflet](https://github.com/commenthol/gdal2tiles-leaflet) 
Happy mapping!
