### ISSUE TITLE
Uncaught Error: iconUrl not set in Icon options (see the docs).

### ISSUE THREAD

**Issue by dotku** [Leaflet/Leaflet#4334]
I setup the icon like this

```
var centerMarkerIcon   = L.icon({iconURL:'http://leafletjs.com/docs/images/logo.png'});
var centerMarker       = L.marker(map.getCenter(), {icon: centerMarkerIcon});
```

but I got the error: 

> Uncaught Error: iconUrl not set in Icon options (see the docs).

**Comment by tzetter** [comment]
That's because you put `iconURL` in the icon options instead of  `iconUrl` like it said in the docs (and error message). JavaScript is case sensitive.
