### ISSUE TITLE
Zoom animation sometimes stopped mid-way in Safari with Google tiles (>=0.7.4)

### ISSUE THREAD

**Issue by mlazowik** [Leaflet/Leaflet#4342]
Safari 9.0.3 (11601.4.4), leaflet >= 0.7.4

When complex enough zoom animations are happening on Safari with Google Maps tiles the animation is sometimes stopped before completing. The bug was introduced with [workaround for another bug](https://github.com/Leaflet/Leaflet/commit/4eb39d531255a6deaf3f3c56fb24933d44f5eccc).

I _think_ that this happens when there are two simultaneous zoom animations happening, but it's not that easy to debug.

Here is a demo code of the bug, the smallest snipped that we have managed to separate. It will appear only sometimes, and only when the viewport is small enough for the fitBounds to have any effect.

https://lazowik.pl/leafletbug.html

Recorded example (you can see two reloads, after the second one the bug does not appear):
![leaflet-bug](https://cloud.githubusercontent.com/assets/1978721/13937205/797f5904-efc3-11e5-986d-e4bb07958db0.gif)

**Comment by hyperknot** [comment]
What do you mean by >=0.7.4? What is the exact version?

The workaround you linked was for 1.0, it's not in 0.7 branch.

Can you make a minimal example on http://playground-leaflet.rhcloud.com/?

**Comment by mlazowik** [comment]
Right, I've linked to the wrong commit (as it does the same). Here's the [correct one](https://github.com/Leaflet/Leaflet/commit/91477588faa44e2b266d86a5a44cb98490244d39).

Will try to port the example from https://lazowik.pl/leafletbug.html should that help in any way.

**Comment by mlazowik** [comment]
[Done](http://playground-leaflet.rhcloud.com/val/1). Interestingly enuogh, it won't happen in the embedded output view, I had to take it full screen. Still happens only sometimes, and only with viewport sizes that make fitBounds do zooming out.

**Comment by IvanSanchez** [comment]
This is old, and maybe depends on some of the ugly old hacks for google tiles. Closing for now, unless this is reproducible with 1.0.3.
