### ISSUE TITLE
TileLayer: unloadInvisibleTiles and reuseTiles have no effect

### ISSUE THREAD

**Issue by pke** [Leaflet/Leaflet#4343]
I have these options for my tilelayer:

```
const defaultLayerOptions = {
  detectRetina: true,
  updateWhenIdle: false,
  unloadInvisibleTiles: false,
  reuseTiles: true
}
const Hydda_Full = L.tileLayer("http://{s}.tile.openstreetmap.se/hydda/full/{z}/{x}/{y}.png", defaultLayerOptions)
```

Yet, when panning around back and forth, new tiles are constantly faded in. Seems like those options have no effect at all.

**Comment by IvanSanchez** [comment]
Those options were removed in 1.0.0. The documentation update from #4203 should cover this.

**Comment by pke** [comment]
Ah ok, yeah I am on 1.0.0 already. Docs are still for 0.7.x

**Comment by IvanSanchez** [comment]
No, there are docs for 1.0.0 and they mention the options you referred to: http://leafletjs.com/reference-1.0.0.html#tilelayer-unloadinvisibletiles

**Comment by pke** [comment]
So why isnt't it working then?

**Comment by IvanSanchez** [comment]
Because those options were removed in 1.0.0. The only problem here is that the 1.0.0 docs still refers to those options.

**Comment by pke** [comment]
Whats the suggested upgrade path. The default behaviour is barely acceptable.

**Comment by IvanSanchez** [comment]
The tile pruning behaviour is a different issue: #4039
