### ISSUE TITLE
How to visualize a heatmap with numbers using Leaflet map?

### ISSUE THREAD

**Issue by TopologyApplied** [Leaflet/Leaflet#4347]
I wish to create a heatmap similar to the following: 

http://www.trulia.com/local/san-francisco-ca/tiles:1|points:1_crime

With the number changes at different zoom level - the number can appear in a mouse-hover window instead of directly showing on the map.

Any idea how to make this with Leaflet map?

**Comment by perliedman** [comment]
Hi, and thanks for using Leaflet!

This issue tracker is used for bugs and new feature discussions. That means that questions on how to use Leaflet and similar is better discussed at Stackoverflow or gis.stackexchange.com.
