### ISSUE TITLE
adding a L.geoJson layer to the map is slow in IE with v0.7.7

### ISSUE THREAD

**Issue by clhenrick** [Leaflet/Leaflet#4357]
Adding a new layer to the map object hangs the browser in IE10+. Depending on the complexity of the geometry it could be 10 seconds or over a minute. Seems related to #4061 

Issue can be replicated by viewing the following in IE, (notice the lag when clicking on a polygon and new data is added to the map): http://clhenrick.github.io/fosi-test/

Reverting Leaflet to version 0.7.5 fixes the problem.

Below is a screenshot of IE11's "UI Responsiveness" profile. I'm viewing on Browser Stack so can't export the actual profile data. Note the abundance of `document.createElement()` & `document.appendChild()` calls.

![bs_win8 1_ie_11 0 1](https://cloud.githubusercontent.com/assets/161748/14154875/f34eb854-f68c-11e5-8296-bc94505ab251.jpg)

![bs_win8 1_ie_11 0 2](https://cloud.githubusercontent.com/assets/161748/14154876/f34ec7a4-f68c-11e5-9089-9862d3779fc0.jpg)

**Comment by danzel** [comment]
Have you tried this with leaflet 1.0.0-beta2?

**Comment by clhenrick** [comment]
@danzel seems that this is not an issue in 1.0.0.-beta2.

**Comment by IvanSanchez** [comment]
If I recall correctly, this is due to IE10 spending an awful lot of time to attach `dblclick` event handlers in 0.7.x, and 0.7.7 in particular attaches events to everything so it works OK with `msPointer` events in IE10/IE11 (which were causing problems in Win8 touchscreens in 0.7.5).

Making everything work in every browser for 0.7.x is a lot of work, and we must focus on 1.0.0-rc1. I suggest you consider upgrading to one of the 1.0.0 betas (or the rc1 when it's out).

**Comment by clhenrick** [comment]
Thanks @IvanSanchez, I can see how the focus needs to be on getting 1.0.0 out the door. However this seems like a fairly large bug to overlook for v0.7.7 given the popularity of IE users. 

The project I ran into this with ( http://fosigrid.org ) appears to work fine with v0.7.5. I just wanted to point this issue out here in case anyone else happens to run into it.

**Comment by mourner** [comment]
We would be extremely grateful if someone could look into this and provide a PR with a fix. I don't currently have a Windows/Edge machine to test on unfortunately.

**Comment by ryanjhodge** [comment]
FYI - Microsoft provides free virtual machines for testing Microsoft Edge and versions of IE6 through IE11.

https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/windows/

**Comment by davojta** [comment]
https://github.com/davojta/Leaflet/commit/a545f38fab7dc0a857e09e459eb4a594c68480c3
This fix was working for us in 0.7.7
(revert touch detection from commit https://github.com/danzel/Leaflet/commit/4b289ab8071e480c182bb5df76bbfe0cac2a54e0) 
https://github.com/davojta/Leaflet/commits/stable_0_7_7_1_release - branch with fix

**Comment by bhaskarvk** [comment]
Will this be ever merged into the 0.7 branch?

**Comment by IvanSanchez** [comment]
@bhaskarvk No. Making IE<11 perform well with hundreds of vector layers with potential `dblclick` event handlers required refactoring the whole event handling logic, which was a big chunk of the 0.7.x→1.0.x work. In other words: there is no quick fix that can backport this to 0.7.x.

**Comment by bhaskarvk** [comment]
I must be mistaken then, I thought as per @davojta's comments in https://github.com/Leaflet/Leaflet/issues/4357#issuecomment-204241232 it was fixed.

**Comment by IvanSanchez** [comment]
See https://github.com/davojta/Leaflet/commit/a545f38fab7dc0a857e09e459eb4a594c68480c3 then. We are not working on the 0.7.x anymore. And with things like #5180, I'm very reluctant to backport any code that touches pointers or dblclicks, unless it's been tested in a good variety of browsers.

**Comment by bhaskarvk** [comment]
OK cool and thanks for the pointer. I guess I can patch my local 0.7 copy with davojta@a545f38 as a stop gap measure. I can't move to 1.x until Proj4Leaflet officially supports it, there is an experimental branch, but I'm not sure how ready that is.

Thanks for your quick replies.

**Comment by IvanSanchez** [comment]
AFAIK proj4leaflet is looking for a maintainer since @perliedman cannot spend a lot of time on it. If you can spend the time to make fixes for it, they will be welcome.

**Comment by bhaskarvk** [comment]
Ah I didn't know that. I think I might just have to do that as Proj4Leaflet is very critical for R packages based around leaflet. Thanks again!
