### ISSUE TITLE
Shift on zoom toolbar tap (touch version)

### ISSUE THREAD

**Issue by vripoche** [Leaflet/Leaflet#4360]
Hi,

On touch device version, we have a conflict between the zoom toolbar tap and the double tap behavior (center to the cursor), when we tap fast on the +/- zoom, sometimes the double tap event on map bubbles and the zoom shifts to the spot behind the zoom toolbar...

Screencast:
http://imgur.com/bs3urFU

Thank you.

**Comment by IvanSanchez** [comment]
Which Leaflet version?

**Comment by vripoche** [comment]
On the last one v0.7.7 
http://leafletjs.com/examples/mobile-example.html

**Comment by IvanSanchez** [comment]
Be aware that we are focused on releasing 1.0.0 - fixes for the 0.7.x series will take time.

Also you should try reproducing this in 1.0.0-beta2.

**Comment by vripoche** [comment]
Yes indeed it works well on v1.0.0-beta.2.

Thanks.
