### ISSUE TITLE
Leaflet for R

### ISSUE THREAD

**Issue by Patrikios** [Leaflet/Leaflet#4361]
I would like to implement leaflets in shiny with R. I try to go with the simples example I found online:

    library(leaflet)
    library(ggmap)

    >somePlace <-ggmap::geocode("Vienna")  
    Information from URL : http://maps.googleapis.com/maps/api/geocode/json?    address=Vienna&sensor=false  
    >somePlace 
    lon      lat
    1 16.37382 48.20817
    >leaflet(somePlace) %>% addTiles() %>% addMarkers()

It shows a grey space with the blue marker. No trace of OSM or any other spatial visualisation.
Could you point out where is the problem? I do not understad the ERROR message _Information from URL : http://maps.googleapis.com/maps/api/geocode/json?    address=Vienna&sensor=false_
Thanks in advance!

**Comment by IvanSanchez** [comment]
Hi, glad to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet (with or without R), please use [gis.stackexchange.com](https://gis.stackexchange.com) or [stackoverflow](https://stackoverflow.com).

**Comment by Patrikios** [comment]
Thnx for info!
