### ISSUE TITLE
Get rid of gh-pages

### ISSUE THREAD

**Issue by yohanboniface** [Leaflet/Leaflet#4366]
Idea is to keep documentation and static site (tutorial...) in the master branch.

Let's start by looking for hosting alternatives.

It needs to:
- be free for open source
- be deployable through git the easy way
- or be deployable through Travis
- allow prebuild hooks to generate documentation with Leafdoc.
- allow custom domain

Another option is to try to keep gh-pages is sync automatically, but this needs to be digged in.

**Comment by yohanboniface** [comment]
### aerobatic
https://www.aerobatic.com/docs/getting-started
Only works with Bitbuket (akward).
We may want to maintain a Bitbucket mirror, it may be less of a pain than having a separate branch (can be easily automated), but seems a bit complex for what we want to achieve.

**Comment by jieter** [comment]
Why not use travis to build it and deploy to a different repo in the leaflet org for hosting with gh-pages?

**Comment by yohanboniface** [comment]
That's an option. But having two separate repositories (even if we should push only on one) will still be confusing.

**Comment by jieter** [comment]
Would that be less confusing than having to understand a completely different platform?

**Comment by yohanboniface** [comment]
I meant confusing for other users not aware of the subtilties of those two repos, not for us ;)

**Comment by yohanboniface** [comment]
Turns out that surge.sh is free for custom domain, free for SSL, but *SSL on a custom domain* is paid feature.
Apart from that, surge sounds like a really nice service. I've deployed the site in 5 minutes (including time to install jekyll on my new Arch laptop :p ): http://leaflet.surge.sh

Other option to consider: https://github.com/X1011/git-directory-deploy

**Comment by yohanboniface** [comment]
cf also #3277

**Comment by yohanboniface** [comment]
Ingoing discussion here in Madrid: now that documentation is generated, in can makes sense to separate it from the main Leaflet site and blog, which are hand maintained.
So we can have something like:
- a new git repository leafletjs.com that would be a gh-pages only repo, keeping using Github Pages for it (or maybe not)
- a new domain doc.leafletjs.com, and a dedicated surge site, without ssl for now, which is generated from Travis

Not sure the best way to deal with a shared menu if we go this way, so maybe we should remove the menu from the documentation and just have "Back to main site" link on the top of the page?

**Comment by IRus** [comment]
13$ per month? nginx+github webhook+let's encrypt+digital ocean box for 5$ per month in nicest option.

**Comment by hyperknot** [comment]
I would personally recommend using Cloudflare for the CDN, it is free and would allow HTTPS for CDN, blog, docs, website, everything.

I can help setting it up, I did it on a dozen websites last month.

**Comment by sergei-maertens** [comment]
What about Sphinx + readthedocs.org?

**Comment by jieter** [comment]
As of today, you can also use master as a source to build gh-pages for, and even a `docs/` subdirectory in the master branch:

https://github.com/blog/2228-simpler-github-pages-publishing
