### ISSUE TITLE
Prepare 1.0.0-rc1 release

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#4379]
We've closed a bunch of bugs and merged quite a lot of pull requests during the Madrid Leaflet Weekend Code Sprint™, and we ( @yohanboniface  @perliedman @hyperknot @IvanSanchez ) feel like -rc1 is ready.

- [x] write blog post @IvanSanchez 
- [x] write changelog @yohanboniface 
- [x] update changelog with changes of the last few days @perliedman 
- [x] update changelog date and merge @perliedman 
- [x] update version in `src/Leaflet.js` @perliedman 
- [x] update version in `package.json` @perliedman 
- [x] run `npm run release` @mourner
- [x] wait for the Travis to build and upload artifacts (the build, leaflet.zip, etc.)
- [x] update the download page in `gh-pages` to point to the new release 
- [ ] optional: update the website to use the new release (examples, tutorials, etc.)
- [ ] optional: update the playground to show an option for rc1 @ivansanchez
- [x] replace `reference-1.0.0.html` in `gh-pages` with the latest leafdocs built @ivansanchez
- [x] merge RC1 blog post @IvanSanchez 
- [x] tweet about the new release @mourner
- [x] publish the GitHub release entry @mourner

update by @mourner: list of release steps

**Comment by yohanboniface** [comment]
For version of raw changelog: https://gist.github.com/yohanboniface/2def6e7176169e8d5606e01c45eb8572

Should we go with that and edit it by hand (putting it in categories, removing tiny PRs, etc.), or is there something that could be made better by the script before?

**Comment by hyperknot** [comment]
@IvanSanchez what do we need to put rc1 on playground? Is it something only you have access to?

**Comment by IvanSanchez** [comment]
@hyperknot Yeah, I have the rhcloud credentials. Need to make a DB backup and push the modifications done in https://github.com/Leaflet/playground/commit/491fe7dfdfc99015671fd3d953d2dfd3c463ecd3
