### ISSUE TITLE
Removing one path from html canvas removes click event handlers for all paths on the canvas

### ISSUE THREAD

**Issue by MikkoAhtiainen** [Leaflet/Leaflet#4388]
Leaflet version 0.7.7, All browsers

When you remove only part of the path elements from the html canvas (L_PREFER_CANVAS=true)  the click event handlers are also removed from the rest of the path elements that are not removed. Result is that path elements still remaining on the screen can't receive any click events anymore.

Seems that `this._onClick` is `undefined `and commenting the following line fixes the problem.

```
if (L_PREFER_CANVAS) {
    L.Path.include({
        onRemove: function (map) {
            map
		        .off('viewreset', this.projectLatlngs, this)
		        .off('moveend', this._updatePath, this);

            if (this.options.clickable) {
                // Fixed removing of all event handlers by commenting following line
                //this._map.off('click', this._onClick, this);
                this._map.off('mousemove', this._onMouseMove, this);
            }

            this._requestUpdate();
		
            this.fire('remove');
            this._map = null;
        }
    });
}
```

**Comment by yohanboniface** [comment]
Can you please check with latest master? http://playground-leaflet.rhcloud.com/ may help for this?

Thanks!

**Comment by MikkoAhtiainen** [comment]
Ok. Seems to work on latest development version.

Thanks!
