### ISSUE TITLE
No 'mousemove' event fired when pan or zoom with keyboard

### ISSUE THREAD

**Issue by NielsHolt** [Leaflet/Leaflet#4389]
Hi
When the map is paned or zoomed using the keyboard, the mouse position on the map is changed, but no mousemove-event is fired
Kind Regards
Niesl Holt

**Comment by danzel** [comment]
Well, technically your mouse didn't move...

We just pass on the browser mousemove event, and add some extra data to it
https://github.com/Leaflet/Leaflet/blob/master/src/map/Map.js#L934-L935
https://github.com/Leaflet/Leaflet/blob/master/src/map/Map.js#L1036-L1042

Potentially we could fire movemove events when the map moves, but we'd need to check that the mouse was on the map and all sorts of dodgyness. Probably better for a plugin if this is required for you.

What is your use case? Could you just listen to mapmove/zoom events?

**Comment by NielsHolt** [comment]
I think it is a question of perspective :-)
The mouse don’t move on the screen or on the map-element, but the coordinate for the mouse is changed when the map is panned using the keyboard

My current use case is simple to display the coordinates of the cursor on the map.
The moveend, zoomend events only provides Event not MouseEvent

It isn’t implemented in JS either - If the position of an element is changed while the mouse is over it, no mousemove event is fired

I have fixed it for now by turning the coordinate display off on zoomstart movestart events and turning it back on at zoomend moveend

I will look into it at some point to see if an easy method can be implemented

**Comment by IvanSanchez** [comment]
This can also worked around by storing the mouse position (in pixels relative to the map container) on every `mousemove` event, then calling `map.containerPointToLatLng()` with that on `'zoomend moveend'`.

You can even do that automatically by extending the behaviour of the keyboard map handler.

Either way, I see no (good) reason why we should fire a `mousemove` event whenever the map is moved - that would create more problems than it would solve (e.g. stealing focus from elsewhere)

**Comment by NielsHolt** [comment]
Hi
I created my own extension to solve the problem for me:
https://github.com/FCOO/leaflet-mouseposition
