### ISSUE TITLE
L.GridLayer does not honor opacity setting when set using options.

### ISSUE THREAD

**Issue by rickj33** [Leaflet/Leaflet#4390]
This is similar to #4096, but I am not using IE.

When I try to set the opacity of a tile/grid layer using the options.opacity, it is ignored.
I traced it to _initTile : function(tile), It looks like options.opacity is only used if the browser is "ielt9".

```javascript
	// update opacity on tiles in IE7-8 because of filter inheritance problems
		if (L.Browser.ielt9 && this.options.opacity < 1) {
			L.DomUtil.setOpacity(tile, this.options.opacity);
		}
```
I modified my version of the _initTile function  and added the following lines so that the opacity options are used if set.

```javascript
	if(this.options.opacity){
			tile.style.opacity = this.options.opacity;
		}
```

If there is a better/preferred way to handle this, please let me know.

Thanks
Rick

**Comment by danzel** [comment]
Works for me in chrome
http://playground-leaflet.rhcloud.com/pex/edit?html,output

leaflet sets the opacity of the container here:
https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/GridLayer.js#L313-L315

**Comment by rickj33** [comment]
I found I was using an older version of the leaflet src, I updated to the current version in git-hub and It is working as danzel pointed out.
Sorry for premature posting.
Rick
