### ISSUE TITLE
Correct settings for using new mapbox styles (rendered, nonvector) image tiles

### ISSUE THREAD

**Issue by livemixlove** [Leaflet/Leaflet#4391]
Hi All,

When I use the new mapbox styles image tiles, they render too small:

```
mapTileLabelUrl = 'https://api.mapbox.com/styles/v1/t*****t/'+feed.themeParameters.base_labels_id_vector+'/tiles/{z}/{x}/{y}?access_token=' + accessToken;

baseLabelsLayer = new L.tileLayer(mapTileLabelUrl, {
			 attribution: attribution,
			 zoomControl:false,


			 pane: labelPane,
		//	 detectRetina: true
		//	 zoomOffset:-1,
       //tileSize: 512
	   }).addTo(map);
```
<img width="368" alt="screen shot 2016-04-04 at 6 16 06 pm" src="https://cloud.githubusercontent.com/assets/148947/14268573/5a2c6ac8-fa91-11e5-81fd-9f5fc6cebc45.png">

  I tried to use {tileSize: 512} and  {tileSize: 128} on the tileLayer to no avail.  Is there any way to scale the base tiles, to make the tiles bigger?  Can't find much documentation.

**Comment by perliedman** [comment]
Hi and thanks for using Leaflet!

Please note that this is our issue tracker, where bugs and feature requests and posted and discussed. For questions on how to use Leaflet and other support, you're better off using [stackoverflow].(https://stackoverflow.com/) or [gis.stackexchange.com](https://gis.stackexchange.com/).

Having said that, I think you want to look into using [Mapbox's `@2x` tiles](https://www.mapbox.com/help/enable-retina-tiles/) if you're on a high-DPI screen.

**Comment by livemixlove** [comment]
It's maybe not a bug, but it's a gap in or incomplete documentation.  If that's not a github issue, I'll take this elsewhere.  

That said,
It's actually the opposite problem, on @2x it's even smaller.  The image I included is of normal non-2x tiles which are 512x512.  Changing tilesize to a non default value (512) has unexpected behaviours.  The documentation says: "Tile size (width and height in pixels, assuming tiles are square)."  However, I think something is missing there.   I would assume from current docs that changing tile size would not break the map, and that if I have 512x512 tiles, setting tilesize to 512 would work.  Currently this breaks the map and instead of California I get somewhere in Alaska.

**Comment by perliedman** [comment]
If you're using Mapbox raster tiles (and most other tiles), the tiles are __256x256 pixels__, not 512x512. [Mapbox docs](https://www.mapbox.com/api-documentation/#retrieve-tiles) refers to OpenstreetMap's tile naming guide, which specifies this: http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames

You must be doing something weird in your code - out of the box, Leaflet works perfectly with Mapbox's tiles. It would be great if you supply a running example on [Leaflet Playground](http://playground-leaflet.rhcloud.com/?html,output) if you really think this is an issue.

**Comment by livemixlove** [comment]
I'm using the new styles studio.  I was able to reproduce this:

http://playground-leaflet.rhcloud.com/jeg/edit?html,output

Confirmed that the tiles are 512x512:
https://api.mapbox.com/styles/v1/mapbox/streets-v8/tiles/15/19160/11041?access_token=pk.eyJ1IjoidHJpbGxpdW10cmFuc2l0IiwiYSI6ImVUQ2x0blUifQ.2-Z9TGHmyjRzy5GC1J9BTw

I can no longer find documentation for using the new Mapbox styles with
leaflet, but I found some for OpenLayers:
https://www.mapbox.com/help/mapbox-with-openlayers/#openlayers-3x

**Comment by livemixlove** [comment]
With tilesize set to 512:

http://playground-leaflet.rhcloud.com/fek/edit?html,output

**Comment by perliedman** [comment]
Wow, yeah, that doesn't look right. Let me check what's going on here.

BTW, interesting with the tile size, I thought only vector tiles where 512x512, but raster remained in the old size.

**Comment by perliedman** [comment]
The issue can be fixed by using `zoomOffset: -1`: http://playground-leaflet.rhcloud.com/moy/edit?html,output

This actually makes sense, since with 512x512 pixels tiles, if you want the world to cover exactly one tile on zoom 0, you can't use the same scale factor as Leaflet's default (which is based on 256 pixel tiles). Hence, `zoomOffset` to the rescue.

While this might hard to figure out, I have a bit of a hard time to see how this can be solved on Leaflet's side, since it really depends on the tile server's configuration. I don't think this is an issue in Leaflet, after all.

**Comment by livemixlove** [comment]
Thank you for looking into this!!   I really appreciate it.

I posted this on stackoverflow on a related question: http://stackoverflow.com/questions/35590579/is-it-possible-to-use-leaflet-version-1-with-custom-mapbox-style

Seems like mapbox could improve the docs on this.
