### ISSUE TITLE
Zoomin/zoomout control using rectangle selection 

### ISSUE THREAD

**Issue by ajodedra** [Leaflet/Leaflet#4393]
Hi every one i am working on Web GIS application and i need some custom control like zoomin and zoomout using rectengular selection zoombox,if any one whould help me then it is great help  .... thanks....

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

[There's a plugin for what you want to do](http://leafletjs.com/plugins.html#interactive-panzoom). Please do a bit of basic research before asking questions.

Also, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com) or [stackoverflow](https://stackoverflow.com).
