### ISSUE TITLE
Edge Browser breaks assigned geoJSON functions when it includes e.target.bringToFront

### ISSUE THREAD

**Issue by rgtaylor1989** [Leaflet/Leaflet#4394]
It seems like e.target.bringToFront(); breaks leaflet 1.0 beta2 while using the Microsoft's Edge Browser.

In the following example, the mouseout or click functions assigned to the geojson don't work when you include e.target.bringToFront() in the mouseover function.

http://jsfiddle.net/tator/sufc0dLp/4/

Edge works fine if you remove e.target.bringToFront() on leaflet 1.0 beta2

http://jsfiddle.net/tator/sufc0dLp/2/

Edge works fine on leaflet 7.7 (even if you include e.target.bringToFront() in the mouseover function)

http://jsfiddle.net/tator/sufc0dLp/5/

Am I doing something wrong or is this a bug?

**Comment by nikolai-b** [comment]
My guess is that Edge has the same issues IE does
https://github.com/Leaflet/Leaflet/pull/4848

**Comment by IvanSanchez** [comment]
Should be fixed by #4848.
