### ISSUE TITLE
Initial fitBounds regression

### ISSUE THREAD

**Issue by hyperknot** [Leaflet/Leaflet#4395]
#4377 introduced a regression to the initial fitBounds method. By initial I mean when run on a map which has not yet received a zoom level + center, but is using fitBounds to set the view.

The result is that the view is sometimes off, sometimes totally broken with NaN bounds exception.

The reason is that in getBoundsZoom, for zoom level 0, boundsSize has values like:
```
boundsSize = L.Point {x: 0.08415031433105469, y: 0.029537200927705953},
```

Now with the added _rounds() this gets rounded to 0, 0. 

I recommend the following:
1. revert b511c7bc
2. investigate if this affects non-0 zoom levels, or only 0.
3. find a way to solve this
4. come up with test cases for fitBounds on initial map load.

cc: @perliedman

**Comment by perliedman** [comment]
Interesting, yes this looks like it needs some more thought, especially when taking other projections than EPSG:3857 into consideration. I'll look into it.
