### ISSUE TITLE
Leaflet does not create valid WMS-C requests

### ISSUE THREAD

**Issue by kaynz** [Leaflet/Leaflet#4398]
Hi,

please take a look into this conversation: https://sourceforge.net/p/geoserver/mailman/message/34998283/

May you have an idea to fix the problems.

Regards

**Comment by perliedman** [comment]
Hi, I have a hard to figuring out what the issue or question is from reading that thread. It seems there is a problem with EPSG:4326 and WMS-C.

Can you provide an example illustrating the problem, or at least give a clear explanation of what you're trying to do and the result? See the [guide for submitting bugs](https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md#reporting-bugs), if you haven't already.
