### ISSUE TITLE
L.tileLayer error when zoomReverse and detectRetina set true

### ISSUE THREAD

**Issue by kobesin** [Leaflet/Leaflet#4399]
When zoomReverse and detectRetina set true at the same time, tileLayer occur error.

This is my code:

`L.tileLayer("http://gis.sinica.edu.tw/googlemap/AM50K_1944/{z}/{x}/IMG_{x}_{y}_{z}.png", {
            zoomReverse: true,
            detectRetina: true,
            zoomOffset: -1
 }).addTo(map);`

[demo](http://leaflet-test.herokuapp.com/)

I think the adjusted zoomOffset may be wrong.
However, it would work when I modified the lines to the [initialize](https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/TileLayer.js#L80) function (as the following).

https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/TileLayer.js#L90
`!options.zoomReverse && options.zoomOffset++;`

**Comment by yohanboniface** [comment]
Which Leaflet version are you using? 
Seems to be working with latest master: http://playground-leaflet.rhcloud.com/xoz/edit?html,output

**Comment by kobesin** [comment]
I am using latest master version Leaflet.js, Chrome49.0.2623.110 (64-bit), os x el capitan.

If detectRetina don't set true:http://playground-leaflet.rhcloud.com/boz/1/edit?html,output
<img width="1280" alt="2016-04-10 5 24 35" src="https://cloud.githubusercontent.com/assets/5188396/14409347/c0f07d84-ff42-11e5-8a14-0f0d79da0903.png">

When zoomReverse and detectRetina set true at the same time:http://playground-leaflet.rhcloud.com/tih/edit?html,output
It occurs error.
<img width="1280" alt="2016-04-10 5 38 51" src="https://cloud.githubusercontent.com/assets/5188396/14409354/2cac87b6-ff43-11e5-8f70-49e41f468c2e.png">

However, it would work when I modified the lines to the initialize function:http://playground-leaflet.rhcloud.com/seca/edit?html,output
<img width="1280" alt="2016-04-10 5 48 19" src="https://cloud.githubusercontent.com/assets/5188396/14409388/8014598c-ff44-11e5-8fcc-64742cc016c6.png">
