### ISSUE TITLE
Loader Module definition not correct, as it assumes global `L`?

### ISSUE THREAD

**Issue by febeling** [Leaflet/Leaflet#4400]
The [Plugin Guide's section about module loaders](https://github.com/Leaflet/Leaflet/blob/master/PLUGIN-GUIDE.md#module-loaders) suggests a UMD-like defintion that doesn't seem to be correct.

It assumes a variable `window.L`, which typically isn't present in a browserify or webpack environment. So plugins shouldn't generally use this kind of boilerplate code, I believe.

The example code in question is:
```
    // attach your plugin to the global 'L' variable
    if (typeof window !== 'undefined' && window.L) {
        window.L.YourPlugin = factory(L);
    }
```

Plugins that create extensions to the core classes via `include({...})` need a valid reference to `L` though. 

(I'm not sure what the correct version would look like. Are there good examples around aleady?)

**Comment by febeling** [comment]
The plugin leaflet-tilejson does this:

```
(function (factory) {
    var L;
    if (typeof define === 'function' && define.amd) {
        // AMD
        define(['leaflet', 'proj4leaflet'], factory);
    } else if (typeof module !== 'undefined') {
        // Node/CommonJS
        L = require('leaflet');
        proj4leaflet = require('proj4leaflet');
        module.exports = factory(L, proj4leaflet);
    } else {
        // Browser globals
        if (typeof window.L === 'undefined' || typeof window.L.Proj === 'undefined')
            throw "Leaflet and proj4leaflet must be loaded first";
        factory(window.L);
    }
}(function (L) {
```

at https://github.com/kartena/leaflet-tilejson/blob/master/index.js#L8

**Comment by perliedman** [comment]
There's a pretty long discussion of this here: https://github.com/Leaflet/Leaflet/issues/2364. The final word is that `window.L` is the way it will work for now.

Please note that even when used with Browserify and WebPack, Leaflet _will_ set `window.L` if `window` is defined: https://github.com/Leaflet/Leaflet/blob/master/src/Leaflet.js#L27-29 - you'll have to explicitly use `noConflict` if you don't want `window.L`.

**Comment by febeling** [comment]
:+1: Thanks for clarifying.
