### ISSUE TITLE
Exception in L.Canvas _updateStyle function

### ISSUE THREAD

**Issue by rickj33** [Leaflet/Leaflet#4401]
I am getting an exception in the _updateStyle function of the Canvas Renderer
I have traced the exception to the call _updatedDashArray().  The _updateStyle is calling _updateDashArray with out any parameters, when the function expects the layer to be passed in.
This causes the "TypeError: Cannot read property 'options' of undefined" to be thrown.

```javascript
    _updateStyle: function (layer) {
		this._updateDashArray(); //this expects a parameter of layer
		this._requestRedraw(layer);
	},

   _updateDashArray: function (layer) {
		if (layer.options.dashArray) {
			var parts = layer.options.dashArray.split(','),
			    dashArray = [],
			    i;
			for (i = 0; i < parts.length; i++) {
				dashArray.push(Number(parts[i]));
			}
			layer.options._dashArray = dashArray;
		}
	},
```
I am using Leaflet 1.0.0-beta.2 ("139340e")

**Comment by IvanSanchez** [comment]
How are you triggering this problem? It would be very helpful to see what kind of polyline/polygon triggers this error. Something like a fiddle, codepen or http://playground-leaflet.rhcloud.com/ is very helpful.

**Comment by perliedman** [comment]
This sounds like a regression from #4364. Will check it out.
