### ISSUE TITLE
Question about SVG in Leaflet 1.0.0

### ISSUE THREAD

**Issue by ismail44** [Leaflet/Leaflet#4403]
I am working on an application that allows users to add N number of custom layers, paths, basically anything on top of a base layer. These layers can be anything from KML, WMS, WFS, SHP, etc. Sometimes, these layers are also specified in GeoJSON format (i.e. SHP or just plane GeoJSON). When adding these layers, we allow them to "sort" them by to be "above/below", basically modifying the z-index.

My question is more of a design decision question. It looks like all the GeoJSON being ingested is being inserted into a single G element inside of the root SVG, regardless of how many different GeoJSON "data sets" being added. 

Could all the elements being added be grouped together into a single G (group)? So, basically if I'm adding 3 different GeoJSON datasets we would have 3 separate G elements (groups)? Does this question make sense?

**Comment by perliedman** [comment]
I think what you're looking for is _panes_, which allows you to get fine-grained control over z-index and grouping things where the normal `bringToFront`/`bringToBack` is not enough.

Check the [panes tutorial](http://leafletjs.com/examples/map-panes.html) if you haven't already!

**Comment by ismail44** [comment]
Actually,  my question was why is there only one SVG G element being added to the overlay pane regardless of how many GeoJSON datasets are being added. I think it would make more sense to create a G element for EACH GeoJSON dataset added to the map. But, I'll play around with it and make a PR.

Thanks.

**Comment by perliedman** [comment]
@ismail44 ok, sorry if I misunderstood. What is it that you want to achieve by putting the datasets into separate `g` elements?

**Comment by ismail44** [comment]
I want to have discreet control of the ordering of each G element that
comes from a disparate dataset. So, say I have 2 separate GeoJSON datasets
I am adding to the map, I would like each to have its own G representation.
That way, I can manipulate the DOM to order them appropriately. Currently,
all the data, regardless of their source datasets, gets create as a PATH
element inside of just ONE G element. If each GeoJSON dataset had it's own
G element, then I would be able to move it around the DOM (because
apparently z-index doesn't work inside of SVG????).

**Comment by yohanboniface** [comment]
I think custom panes here is the correct option.

**Comment by ismail44** [comment]
Sure, I can get to whatever pane I need from querying my map object.
However, I need a way to take all the separate PATH elements and order them
in the DOM. Currently, though, I don't think there's a way to say, "This
GeoJSON produced this set of PATH elements".

**Comment by perliedman** [comment]
What we mean is that you should put your different objects into separate panes, and then control the order of the panes, not of the paths.

The renderer abstraction exists since Leaflet doesn't always use SVG, and panes is a renderer-neutral way to do what I think you want to do.

You can of course always reach in to the internals and do whatever you want with the SVG elements.

**Comment by perliedman** [comment]
Subclassing the SVG renderer might be another option, and make it add paths in the structure you want. See https://github.com/Leaflet/Leaflet/blob/master/src/layer/vector/SVG.js#L102

**Comment by ismail44** [comment]
I got you... yeah... I was just creating the "stock" L.geoJson... but, I
see what you are saying. Yes, subclassing is a good idea. I didn't think
about that! Thanks!
