### ISSUE TITLE
Leaflet v0.7.7 Layer Control  Overflow Scroll IE Bug

### ISSUE THREAD

**Issue by DeanoFino** [Leaflet/Leaflet#4406]
On Leaflet layer control (v0.7.7) with multiple layers and collapsed:true, with height set and overflow: scroll, IE automatically scrolls to the top of the list, making the control unusable. If collapsed: false, IE auto scroll to top does not happen, but map is dragged when the layer control is moused over. The control works great in Chrome and FF. Also, not sure if this is related, but L.Browser shows touch: true in IE.

This is related to the the issue identified in this pull request: 
[(https://github.com/Leaflet/Leaflet/pull/2544)]

This also may be related to issue [https://github.com/Leaflet/Leaflet/issues/3666] and
[https://github.com/Leaflet/Leaflet/issues/4170].

I created a JSFiddle showing the behavior: [https://jsfiddle.net/DeanoFino/xe3zca7q/]

I have not tested this with other versions of Leaflet.

**Comment by danzel** [comment]
How does this behave with master?
We are unlikely to change this in 0.7 unless it is a breaking bug.

**Comment by DeanoFino** [comment]
Just tested on ie 10,11, FF, and chrome on desktop, and safari and chrome on iOS, and works awesome in master!

**Comment by danzel** [comment]
Cool, will close this off.
Grab one of the 1.0.0 beta releases in the mean time :)
