### ISSUE TITLE
Adding img marker on Canvas

### ISSUE THREAD

**Issue by balciseri** [Leaflet/Leaflet#4407]
So far i was able to extend L.Canvas to add _updateImage function:
...
`ctx.drawImage(layer.options.img, p.x, p.y);`
...
, and also extended L.CircleMarker (i think that's not the right way, but i wanted to just make a quick test) :
`var nettleCanvasMarker = L.CircleMarker.extend({
        options: {
            renderer: cavRend,
            radius: 20,
            img: image
        },
        _updatePath: function () {
            this._renderer._updateImg(this);
        }
    });`

I can see the map is reacting really good, i can draw with no problems 10.000 markers and drag around easy.

But i noticed that **the whole Canvas layer is beeing emptied and redrawn completely on every moveend.** Like after a drag of the map of just 1 pixel we redraw everything.
Here in L.Canvas = ...
```
_update: function () {
		if (this._map._animatingZoom && this._bounds) { return; }

		this._drawnLayers = {};

		L.Renderer.prototype._update.call(this);

		var b = this._bounds,
		    container = this._container,
		    size = b.getSize(),
		    m = L.Browser.retina ? 2 : 1;
		L.DomUtil.setPosition(container, b.min);

		// set canvas size (also clearing it); use double size on retina
		container.width = m * size.x;
		container.height = m * size.y;
		container.style.width = size.x + 'px';
		container.style.height = size.y + 'px';
```

**Why is leaflet doing this?**

**Also there is a bug in the _updateCircle** code(still in L.Canvas) , it is missing this._drawnLayers[layer._leaflet_id] = layer;
One of the direct effects it that _handleMouseHover is not working for CirceMarkers.

**Comment by perliedman** [comment]
Leaflet's vector features (`L.Path`) are clipped, simplified and redrawn on each `moveend`. You can see this in effect if you have polygon or polyline extending outside the viewport - while dragging, areas of the feature that were outside the viewport when drag started, are not shown until you stop dragging.

Since a features geometry is potentially changed on every `moveend`, it also has to be redrawn.

Regarding `_drawnLayers`, it appears this is fixed in latest master: https://github.com/Leaflet/Leaflet/blob/master/src/layer/vector/Canvas.js#L206 - which version are you running?

**Comment by balciseri** [comment]
thank you for the explanation. The redraw is so fast that i didn't even notice there was a redraw until i read the code. 
I'm using Leaflet 1.0.0-beta.2 (55fe462).I downloaded it yesterday to change the canvas code, I probably downloaded an outdated version, sorry for the wrong bug report about the _updateCircle.
Should we change the canvas resize (testing if changed) https://github.com/Leaflet/Leaflet/blob/master/src/layer/vector/Canvas.js#L71  like the svg [https://github.com/Leaflet/Leaflet/blob/master/src/layer/vector/SVG.js#L72](url) ? 
I guess not? Probably you made it on purpose since we said that we are redrawing everything on update, because setting the canvas.width (even if with the same previous width) will empty the canvas as per canvas normal behaviour.

**Comment by balciseri** [comment]
i now tried b74cf17 and i see that in this version they fixed the onZoomStart hiding of the vectors of the cavans. 
Is it hard to implement markerZoomAnimation: false also for the vectors of the canvas layer?
I think it's more clean if the vectors disappear during the zoom ( just like the markers with markerZoomAnimation false ).
I see there is this check here : https://github.com/Leaflet/Leaflet/blob/master/src/map/Map.js#L790
Can i do the same and apply this logic to the cavans?

**Comment by balciseri** [comment]
Well closing this for the moment. I will open soon an issue about the Canvas clearing methos in the update event. 
Clearing the canvas setting the width attribute every time has a noticeable impact on performance on my tests. ( clearRect seems they way to go.)
