### ISSUE TITLE
Missing anchors for H3 in docs

### ISSUE THREAD

**Issue by domoritz** [Leaflet/Leaflet#4412]
The anchor for http://leafletjs.com/reference.html#control-options does not exist, although it is references in http://leafletjs.com/reference.html#control.

**Comment by IvanSanchez** [comment]
0.7 docs, or 1.0 docs?

**Comment by domoritz** [comment]
Both.

**Comment by IvanSanchez** [comment]
I had a look at the current 1.0 docs - we're using Leafdoc now, which means anchors are handled automatically, and the links to the options of the different controls seem to work fine.

Adding an anchor to the 0.7 docs should be very simple - I encourage you to fix it yourself and submit a pull request (you'll have to fork the repo, clone it, switch to the `gh-pages` branch, edit, commit, push, and make a pull request). If you don't have the time for that, this will make a good [yourfirstpr](http://yourfirstpr.github.io/) issue.

**Comment by domoritz** [comment]
Oh, I just saw that the anchor was renamed in the 1.0 docs from `control-options` to `control-option`.
