### ISSUE TITLE
Leaflet layers Z-index

### ISSUE THREAD

**Issue by amir-infsoft** [Leaflet/Leaflet#4416]
I need to set z-index (control what is in foreground) between leaflet layers.

It is possible e.g. to control between 2 (or more) geoJson layers or between 2 (or more) ImageOverlay layers, with bringToFront, bringToBack functions.

L.geoJson layer is always over L.imageOverlay layer and I need to set imageOverlay to be over GeojJson.

**Is this possible in Leaflet?**

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

Also, have a look at the [panes tutorial](http://leafletjs.com/examples/map-panes.html)

**Comment by amir-infsoft** [comment]
Thanks for reply Ivan.

I have now posted a question on StackOverflow:
https://stackoverflow.com/questions/36594994/leaflet-layers-z-index
