### ISSUE TITLE
translation service for draw & map service

### ISSUE THREAD

**Issue by alphonsoTheGreat** [Leaflet/Leaflet#4417]
i have implanted leaflet service at my project and im trying to translate the draw strings
is there any other way to do it other then changing the library code?

**Comment by IvanSanchez** [comment]
What do you mean by "draw strings"?

**Comment by mourner** [comment]
This is probably something that should be reported in the Leaflet.draw repo.

**Comment by alphonsoTheGreat** [comment]
for example when im drawing a circle, there is a string that says "click and drag to draw a circle"
i want to be able to translate all those strings 

![ex](https://cloud.githubusercontent.com/assets/18441506/14492888/e952f6c2-018a-11e6-8cf8-5952365885eb.jpg)

**Comment by IvanSanchez** [comment]
That belongs to the [Leaflet-draw repo](https://github.com/Leaflet/Leaflet.draw) as @mourner said. Furthermore, localization is [explicitly mentioned in the documentation](https://github.com/Leaflet/Leaflet.draw#customizing-language-and-text-in-leafletdraw).
