### ISSUE TITLE
L.TileLayer.Websockets plugin

### ISSUE THREAD

**Issue by knutole** [Leaflet/Leaflet#4420]
We're planning to create a `L.TileLayer.Websocket` class, that requests tiles over websockets, instead of http requests. I realise this is a bit of an undertaking, so I'm just checking in to perhaps get some advice and heads-up on possible caveats. (Also, if anyone has done any work in this direction already, let me know, can't seem to find anything anywhere.)

Rationale for the plugin is that we need to request small tiles at a much higher rate than what browser http request limits permit (doing animation with tiles at >10fps). We run our own tileserver, which will accept websocket requests for tiles.

#### Outline

- use `v1.0.0-beta.2`
- extend `L.TileLayer` to `L.TileLayer.Websockets`
- fallback on `L.TileLayer` if websockets are unsupported ([caniuse/websockets](http://caniuse.com/#feat=websockets)).
- replace `tile.src` ([code](https://github.com/Leaflet/Leaflet/blob/v1.0.0-beta.2/src/layer/tile/TileLayer.js#L72)) with websocket request

Any advice, input or encouragement is greatly appreciated.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet (including plugins), please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

That said: have a look at https://github.com/MazeMap/Leaflet.TileLayer.PouchDBCached/blob/master/L.TileLayer.PouchDBCached.js - you'll have to reimplement `createTile`, call some async method there, and make sure the `done` callback that `createTile` receives gets called when the websockets stuff is done.

**Comment by kaynz** [comment]
Hey @knutole,

I'm really interested in using websockets and leaflet.
Feel free to contact me if you want to work together on this.

**Comment by knutole** [comment]
Hi @kaynz, 

That's great! Would be great to work together. We can continue discussion on my fork, if you like. https://github.com/systemapic/Leaflet/issues/2

**Comment by knutole** [comment]
Thanks @IvanSanchez.
