### ISSUE TITLE
Can not render map to invisible container

### ISSUE THREAD

**Issue by Jonas-WMDE** [Leaflet/Leaflet#4421]
When adding map to a div element that is invisible rendering fails.
1. Div container with display:none
2. Add map to container
3. Change div to display:block
4. Map is not rendered correctly

![image](https://cloud.githubusercontent.com/assets/13198391/14529320/379f8c2c-0254-11e6-950f-1b1e06b05210.png)

**Comment by IvanSanchez** [comment]
http://leafletjs.com/reference.html#map-invalidatesize

**Comment by IvanSanchez** [comment]
See also http://playground-leaflet.rhcloud.com/cug/edit?html,output
