### ISSUE TITLE
Trim... Undefined.. can't happen

### ISSUE THREAD

**Issue by caycek** [Leaflet/Leaflet#4422]
leaflet-src.js

Can't trim an undefined.

line 135

Can't currently do a pull request.

just fix this function

	// trim whitespace from both sides of a string
	trim: function (str) {
            if(typeof str == "undefined") return "";
	        return str.trim ? str.trim() : str.replace(/^\s+|\s+$/g, '');
	},

**Comment by hyperknot** [comment]
Hi, can you provide a bit more information about why are you opening this issue and what are you trying to achieve? What is the context in which you "Can't trim an undefined."?

**Comment by caycek** [comment]
Tbh not sure what triggered it exactly but Javascript trim doesn't work on an undefined. Leaflet 0.7.7 does not have this issue (didn't check to see if it used trim). 
That line returns an empty string if trim is called on undefined. Best fail safe I could think of.
Also, Leaflet should never fail because of a string error.....


Sent on a Sprint Samsung Galaxy Note® 3

-------- Original message --------

**Comment by hyperknot** [comment]
@caycek if there is a case where something happens and outputs this error message, we should solve the case, not change this function. What version of Leaflet are you using and with what plugin? Can you try to reproduce how it happens?

**Comment by caycek** [comment]
Version was 1.0.0.
No plugins.
And did you read the change?
It is only 1 line to fix an undefined call which could occur at any time.. currently working on a project and do not have time to get Leaflet 1.0.0 to work since most of the plugins aren't porting over correctly.
If I find time to do test this again I will but it happened just by updating from 0.7.7 to 1.0.0 beta2.
However, since an undefined obviously could be passed to trim at any point in time, I highly recommend just adding that check. Save you time of trying to prove it csn happen.


Sent on a Sprint Samsung Galaxy Note® 3

-------- Original message --------

**Comment by mourner** [comment]
This is not a Leaflet issue. You should check for `underfined` prior to calling `trim`. If it was called with `undefined` internally, then you should provide us with a JSFiddle test case.

**Comment by caycek** [comment]
Just so we are clear. It was in Leaflet. Not me.

But I'll get you a proof if I get time.

Sent on a Sprint Samsung Galaxy Note® 3

-------- Original message --------

**Comment by hyperknot** [comment]
OK, I found out what is happening here. It is the message when trying to use Markercluster npm build with Leaflet 1.0. Opened a bug there.
https://github.com/Leaflet/Leaflet.markercluster/issues/666

@caycek for the time being, you can get the 1.0 supported version via npm like this:
"leaflet.markercluster": "hyperknot/Leaflet.markercluster#built"

**Comment by caycek** [comment]
@hyperknot Thanks for the update. I did discover it was caused by this exact issue you have pointed out. I appreciate you taking the time to figure it out. Glad to know now I should have mentioned the cause (I thought this would be chopped to "Don't use that version with Leaflet 1.0.0")!

**Comment by hyperknot** [comment]
@caycek we'll be releasing an official 1.0 supported version of markercluster soon, so if you can wait you can just use that version.

**Comment by danzel** [comment]
Yep, https://github.com/Leaflet/Leaflet.markercluster/issues/666#issuecomment-214605517
