### ISSUE TITLE
Path options vs Polyline options

### ISSUE THREAD

**Issue by nathancahill** [Leaflet/Leaflet#4427]
Polyline options adds `smoothFactor` and `noClip` to Path options. Since Polygon and Rectangle all follow the code paths in Polyline that use those options (`_simplifyPoints()` and `_clipPoints()`), it would make sense to switch the documentation from `<Path options> options?` to `<Polyline options> options?`. Otherwise it would seem like Polygon and Rectangle don't have those options.

The downside is that the link in the docs wouldn't go to [Path options](http://leafletjs.com/reference-1.0.0.html#path-option), and the Polyline inherited options could be missed.

I can submit a pull request for this.

**Comment by perliedman** [comment]
Sounds good! I think Leafdoc handles inheriting options and shows the inherited options as well, like here: http://leafletjs.com/reference-1.0.0.html#fitbounds-options, which  show the inherited zoom and pan options.

A PR would be nice!
