### ISSUE TITLE
the extension of spec.hintrc.js should NOT be .js

### ISSUE THREAD

**Issue by HQidea** [Leaflet/Leaflet#4439]
since spec.hintrc.js is a JSON file, it is not a valid JS file
using .js extension will cause some parsers failure

**Comment by IvanSanchez** [comment]
I'm not sure we even *need* that file anymore. We need to try removing it and seeing if everything (specially unit tests) keep running as expected.

**Comment by mourner** [comment]
This is a leftover since we check everything with ESLint now and there's https://github.com/Leaflet/Leaflet/blob/master/spec/.eslintrc in the same folder. Just remove the file.

**Comment by nvignola** [comment]
I'll fix this.
