### ISSUE TITLE
Changing the TILES provider in LEAFLET_CONFIG not reflected in template

### ISSUE THREAD

**Issue by jibusayone** [Leaflet/Leaflet#4440]
I want to change the tile provider used to render the leaflet maps. The current config is as below:

```
LEAFLET_CONFIG = {
   'TILES': 'http://korona.geog.uni-heidelberg.de/tiles/roads/x={x}&y={y}&z={z}',
   'MIN_ZOOM': 4,
   'MAX_ZOOM': 18,
   'RESET_VIEW': False,
   'NO_GLOBALS': False,
   'PLUGINS': {
       'leaflet-search': {
           'css': STATIC_URL + 'cms/css/leaflet-search.css',
           'js': STATIC_URL + 'cms/js/leaflet-search.js',
           'auto-include': True,
       },
   }
}
```
I tried changing the tile provider from the above, to ones like OpenStreetMap.Mapnik, OpenStreetMap.BlackAndWhite, etc by changing the TILES setting.

But it isn't reflected in the template, which still takes the setting `http://korona.geog.uni-heidelberg.de/tiles/roads/x={x}&y={y}&z={z}` to render the map tiles. Am I missing something here?

I am using django-leaflet version 0.18.1.dev0.

**Comment by mourner** [comment]
You should report this to `django-leaflet`, this place is for Leaflet issues only.
