### ISSUE TITLE
Overlay Image dragging and resizing

### ISSUE THREAD

**Issue by fastesol** [Leaflet/Leaflet#4452]
Hello, I want to drag/drop the image overlay and resize(change the bounds by dragging it from corners). I'm using the draggable function for this purpose, the similar way as it is described [Here](https://github.com/Leaflet/Leaflet/issues/3883) in Question. But, I couldn't find the new bounds in 'e', after the drag ends

**Comment by danzel** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet (including plugins), please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

**Comment by fastesol** [comment]
This could be a new feature. When using the image overlays you have to pass the Image Bounds.
but there should be a way to drag/drop overlay images like other shapes (e.g: marker, line etc) drag/drop. 

I dont know if draggable is natively developed for image overlays. If So, there is no way to fetch the updated lat/lngs at the end when you drop the image.

**Comment by IvanSanchez** [comment]
Not a core feature though. I'd suggest developing as a plugin first and, if it's trivial, we'd consider merging it into the core.

**Comment by paulotabarro** [comment]
@fastesol  any follow up on this?

**Comment by perliedman** [comment]
@paulotabarro check the plugins, pretty certain there are multiple plugins that do this already.

**Comment by paulotabarro** [comment]
Well, I have found some that do this on vectors but images not yet.. https://github.com/w8r/Leaflet.Path.Transform is a nice plugin that might be worth considering adding to leaflet.

**Comment by perliedman** [comment]
@paulotabarro see https://github.com/ScanEx/Leaflet.imageTransform and https://github.com/publiclab/Leaflet.DistortableImage

The point of plugins is to keep core small and focused on features almost everybody needs. Path manipulation isn't considered such a feature.
