### ISSUE TITLE
Remove marker Bug if map.markerZoomAnimation = false

### ISSUE THREAD

**Issue by balciseri** [Leaflet/Leaflet#4453]
Only tested on Master.
If you initialize the map with markerZoomAnimation = false the map will fire the event zoomanim even for the removed markers when you zoom in and out.

https://playground-leaflet.rhcloud.com/juzu/1/edit?html,js,output

Zoom in and out on that map for 10 seconds, no problems.
After 10 seconds the marker is removed.
Now if you try to zoom you get an error in the console: `error Script error. (line 0)`
I don't know how to link proper errors from that website, but on my website this is the error i get in the console:
`'Uncaught TypeError: Cannot read property '_latLngToNewLayerPoint' of null` @ https://github.com/Leaflet/Leaflet/blob/master/src/layer/marker/Marker.js#L290`

I think this is happening because when we add a marker this is happening:
https://github.com/Leaflet/Leaflet/blob/master/src/layer/Layer.js#L86 is True so
https://github.com/Leaflet/Leaflet/blob/master/src/layer/marker/Marker.js#L124 gets set.
so it's registering zoomanim  https://github.com/Leaflet/Leaflet/blob/master/src/layer/Layer.js#L89
Then https://github.com/Leaflet/Leaflet/blob/master/src/layer/marker/Marker.js#L101 is False
But when we remove the marker this is what is going on:
https://github.com/Leaflet/Leaflet/blob/master/src/layer/Layer.js#L171 is going to:
https://github.com/Leaflet/Leaflet/blob/master/src/layer/marker/Marker.js#L123 which is false
so it's not removing the handler for the  zoomanim event.

**Comment by IvanSanchez** [comment]
I think this should be easy...

**Comment by balciseri** [comment]
Thanks, should we close this issue?

**Comment by andresgwell** [comment]
is happenig again

**Comment by Fate-ui** [comment]
I solved the question by adding this code to project (anywhere , just sure it will be used)
```
L.Popup.prototype._animateZoom = function (e) {
  if (!this._map) {
    return
  }
  var pos = this._map._latLngToNewLayerPoint(this._latlng, e.zoom, e.center),
    anchor = this._getAnchor()
  L.DomUtil.setPosition(this._container, pos.add(anchor))
}
```

**Comment by Yojahuang** [comment]
Should anyone reopen this issue?

**Comment by jonkoops** [comment]
Please file a new issue if you are experiencing problems with clear steps to reproduce.

**Comment by Fate-ui** [comment]
> I solved the question by adding this code to project (anywhere , just sure it will be used)
> 
> ```
> L.Popup.prototype._animateZoom = function (e) {
>   if (!this._map) {
>     return
>   }
>   var pos = this._map._latLngToNewLayerPoint(this._latlng, e.zoom, e.center),
>     anchor = this._getAnchor()
>   L.DomUtil.setPosition(this._container, pos.add(anchor))
> }
> ```

做个补充，后续发现是响应式造成的，我把定义的地图放在了pinia里的，就会有这个问题。用的时候toRaw(map)处理一下就好了。不过建议直接不要把map放响应式系统里(无论是pinia或者其它响应式数据)，这样使用也不会报这个错，且不会有性能问题。
