### ISSUE TITLE
Canvas circleMarker fires 'click' after being dragged

### ISSUE THREAD

**Issue by balciseri** [Leaflet/Leaflet#4458]
https://playground-leaflet.rhcloud.com/yaq/edit

Scenario:
Map initialized with  `preferCanvas: true` .
Added a circleMarker 
```
var markerC = L.circleMarker(myCenter2,{radius:30}).bindPopup("popUp");
    map.addLayer(markerC);
```
Bug: if you start the drag of the map while having the cursor ontop of the circlemarker and you stop the drag with the cursor still on the circleMarker the click event will fire ( i'm just assuming it's a click event) and the popup will open.
This is not the default behaviour, if you set `preferCanvas: false` this will not happen.
I've found an intresting piece of code https://github.com/Leaflet/Leaflet/blob/master/src/map/Map.js#L969 but i don't know how to fix this for canvas markers.

EDit: the bug occurs also if you don't actually start the drag with the cursor ontop of the marker, it has just to be ontop of the marker when you end the drag

**Comment by balciseri** [comment]
http://playground-leaflet.rhcloud.com/tij/1/edit?html,js,output

Maybe this can fix it:

I've found in an older version ( Leaflet 1.0.0-beta.2 (55fe462))
this piece of code:
```
if ((e.type === 'click' || e.type === 'preclick') && !e._simulated && this._draggableMoved(target)) {
		   console.log("let's exit");
		   return;
}
in `map._fireDOMEvent`
```
So i added it back in the actual rc1 and the bug seems fixed.
But in the actual rc1 this pice of code has been moved  before in _findEventTargets: https://github.com/Leaflet/Leaflet/blob/master/src/map/Map.js#L968
So i'm not sure what to do.

**Comment by IvanSanchez** [comment]
@balciseri That code was changed in https://github.com/Leaflet/Leaflet/commit/64484d5c745fef0b4f1f076dec8cbd851d68c8de by @yohanboniface , as a fix for #3971. It is important to **not** introduce that bug back.

**Comment by balciseri** [comment]
http://playground-leaflet.rhcloud.com/yewu/1/edit?html,js,console,output

I'm trying to reproduce that bug but it's seems to not happen. 
Be aware that in my version there is still the check added by @yohanboniface  in `map._findEventTargets`
but also in `map._fireDOMEvent` . I'm sorry but i don't have the expertise to refactor this checks.

**Comment by balciseri** [comment]
But i see there is this new bug: When you click on the markers and Map click event will trigger..

**Comment by IvanSanchez** [comment]
> But i see there is this new bug: When you click on the markers the Map click event will trigger.

Event delegation is a feature in 1.0.0, not a bug ;-)

**Comment by balciseri** [comment]
Sweet so now if you guys find an elegant way of implementing this double fix would be awesome :D

**Comment by balciseri** [comment]
@IvanSanchez after looking better into it i see what you mean.
You mean that if for example there is no PopUp binded to the marker and you click on the marker the Click event of the Map will fire.
Instead if you click on the marker with a PopUp binded the Click event of the map will not fire.
This is ok for the normal marker http://playground-leaflet.rhcloud.com/bif/1/edit?html,js,console,output
If you click on the normal marker with the Popup binded the Map click event will not trigger, but if you click on the circleMarker with the popup binded.. the map click event will trigger.
Am i correct that this is not the correct behaviour ?

**Comment by yohanboniface** [comment]
>  Am i correct that this is not the correct behaviour ?

That needs a decision ;)

By default, in 1.0.0 version, an event that is not stopped should bubble to the map. But we have made an exception for marker, in the hope of making the life of the Leaflet user easier, see https://github.com/Leaflet/Leaflet/pull/3605#issuecomment-119589147 for context.

Now, CircleMarker is a Path descendant, so it does not inherit this hack. I'm unsure if we should add the same hack here.

BTW, given there is not this behaviour when using SVG instead, this seems to mean that the problem is elsewhere.
And clearly a drag should *not* issue a click, so this is anyway a bug imho.

I'll work on this asap (but at the office right now).
