### ISSUE TITLE
Setting fractional zoom levels no longer works in 1.0.0-rc.1

### ISSUE THREAD

**Issue by Eschon** [Leaflet/Leaflet#4463]
Here is a small example that shows my issue:
http://playground-leaflet.rhcloud.com/zum/edit?html,console,output

On previous versions it worked like that. Am I doing something wrong?

**Comment by IvanSanchez** [comment]
You need to set the `zoomSnap` and `zoomDelta` options. See:

http://leafletjs.com/reference-1.0.0.html#map-zoomsnap
http://playground-leaflet.rhcloud.com/cici/edit?html,output

File under "it's a feature, not a bug" ;-)

**Comment by Eschon** [comment]
Oh sorry I didn't notice this change. 
According to the documentation the zoomDelta is only for +/- Keys and the zoom controls. Is there a similar option for the mouse wheel?

**Comment by IvanSanchez** [comment]
[Yes, yes there is](http://leafletjs.com/reference-1.0.0.html#map-wheelpxperzoomlevel).

See also the discussion at https://github.com/Leaflet/Leaflet/pull/3523
