### ISSUE TITLE
Events: execution order is theoretically not defined

### ISSUE THREAD

**Issue by fab1an** [Leaflet/Leaflet#4475]
Event code uses `for` to iterate over object properties, like seen here: https://github.com/Leaflet/Leaflet/blob/master/src/core/Events.js#L194

This should work, but browser vendors could change the iteration order anytime. Also numerical properties are treated differently apparently: http://stackoverflow.com/a/280861/342947

**Comment by IvanSanchez** [comment]
What's a failing use case for this? Can't really see when this can become a problem.

**Comment by fab1an** [comment]
It probably won't ever fail, as long as there are no event names which start with numbers.

It's technically not correct though to rely on Javascript property iteration order, because it's not defined. Chrome could start iterating properties from behind (which it won't do). If you want predictable iteration you are required to use arrays.

**Comment by IvanSanchez** [comment]
@fab1an Now that #4697 has been merged into `master`, is this still an issue?
