### ISSUE TITLE
Events: listener without context can be added twice

### ISSUE THREAD

**Issue by fab1an** [Leaflet/Leaflet#4477]
```javascript
var m = new L.Marker();
var x = function() {console.log("event fired")};

/* register without context */
m.on("test", x);
m.on("test", x);

/* fires twice */
m.fire("test");

/* register with context */
context = {}
m.on("test2", x, context);
m.on("test2", x, context);

/* fires once*/
m.fire("test2");

```

https://playground-leaflet.rhcloud.com/wum/1/edit?html,js,output

**Comment by IvanSanchez** [comment]
OK, this is clearly inconsistent.

I'm thinking on adopting the behaviour of DOM events for this particular bit: if an event handler is attached twice, it fires once and can be removed with just one call: http://playground-leaflet.rhcloud.com/wuf/edit?js,console,output

Is this acceptable, or is there any case where we should keep track of how many repeated event handlers are there?

**Comment by fab1an** [comment]
Addendum: If you supply the second listener with two _different_ contexts it also fires twice (once for each context).

I would say a listener with the same name and function that fires twice is a bug. I would even go as far as to throw an error when it's registered a second time to make people fix their code.

**Comment by fab1an** [comment]
Any news about this? I think the event-handling code is so important that issues should get settled fast.

**Comment by yohanboniface** [comment]
> Addendum: If you supply the second listener with two different contexts it also fires twice (once for each context).

We had a small chat about this, and it seems it's a feature, not a bug ;)
Basically, this is what you are doing when you do something like:

```
this._map.on('click', this._onClick, layer1)
this._map.on('click', this._onClick, layer2)
```

So what needs to be unique is the combination of listener + context.

**Comment by fab1an** [comment]
> So what needs to be unique is the combination of listener + context.

Listener as in function or as the combination of event and function?

So should 
```javascript
this._map.on('click', this._something, layer1)
this._map.on('move', this._something, layer1)
```

be allowed?

**Comment by perliedman** [comment]
I definitely think so, and I would be surprised if we didn't already have code that does exactly that.

**Comment by perliedman** [comment]
I think the most common scenario that illustrates why we need to allow same listener function with different contexts, is classes like this:

```
L.Layer.extend({
    onAdd: function(map) {
        map.on('moveend', this._onMoveEnd, this);
    },

    _onMoveEnd: function(e) { ... }
});
```

The `_onMoveEnd` is the same function for all instances, but the context (`this`) will differ. We definitely must allow this; otherwise just the first instance will get the event, which would be surprising to say the least.

**Comment by fab1an** [comment]
I don't know what the best behaviour should be, but in any case I think it's viable to phase out or change event-related stuff for the following reasons:

* Leaflet is pre `1.0`. Better change behaviour now than after `1.0`.
* We could emit warnings in `1.0` like reactJS does and remove behaviour in `1.1`.
* AFAIK there's no formal specification of the event-system and even in 1.0 beta included (buggy?) behaviour, that code might still rely on: #4474 #4475 #4478.

In that light, I urge maintainers to take another look at my PR:  https://github.com/Leaflet/Leaflet/pull/2755

It's not necessary to merge it, but for stability's and simplicity's sake it would be a good idea to unite the two code-paths of manipulating listeners with/without context into one.
That means getting rid of that `if` construct: https://github.com/Leaflet/Leaflet/blob/master/src/core/Events.js#L97

**Comment by fab1an** [comment]
This is fixed now, is it?
