### ISSUE TITLE
L.Control throws error when removing non-added layer

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#4486]
From #4227:

This currently fails:

		it('silently returns when trying to remove a non-existing layer from the control', function () {
			var baseLayer = L.tileLayer(),
			    overlay = L.marker([0, 0]),
			    layers = L.control.layers({'base': baseLayer}, {}).addTo(map);

			layers.removeLayer(overlay);
		});

message:
```
undefined is not an object (evaluating 'this._layers[i].layer')
_getLayer@/home/jieter/workspace/Leaflet/src/control/Control.Layers.js:194:31
removeLayer@/home/jieter/workspace/Leaflet/src/control/Control.Layers.js:112:27
/home/jieter/workspace/Leaflet/spec/suites/control/Control.LayersSpec.js:109:22
```

**Comment by jieter** [comment]
This one can be closed.

**Comment by yohanboniface** [comment]
:)
