### ISSUE TITLE
Overlapping canvas paths don't fire 'mouseout' event

### ISSUE THREAD

**Issue by balciseri** [Leaflet/Leaflet#4495]
Check:
https://playground-leaflet.rhcloud.com/rih/edit?html,js,console,output

There are 3 **overlapping** circles. 
http://puu.sh/otXdv/88fe99f2bb.jpg

- Now with your cursor start on the most left and keep moving the mouse to the right.
 Check the console.. the only 'mouseout' event fired is the one coming from the last circle (the one on the right)

- Now do the opposite: start from the most right circle and go to the left.
This time the 'mouseout' event are firing.

The problem is here: 
https://github.com/Leaflet/Leaflet/blob/master/src/layer/vector/Canvas.js#L293
```
for (id in this._drawnLayers) {
    layer = this._drawnLayers[id];
    if (layer.options.interactive && layer._containsPoint(point)) {
        L.DomUtil.addClass(this._container, 'leaflet-interactive'); // change cursor
        this._fireEvent([layer], e, 'mouseover');
        this._hoveredLayer = layer;
    }
}
```
If there are **overlappings** layers `this._hoveredLayer` is alwais the last one so
when hovering the layers in the order they have been added to the map
https://github.com/Leaflet/Leaflet/blob/master/src/layer/vector/Canvas.js#L270
```
		this._handleMouseOut(e, point);
		this._handleMouseHover(e, point);
```
```
	_handleMouseOut: function (e, point) {
		var layer = this._hoveredLayer;
		if (layer && (e.type === 'mouseout' || !layer._containsPoint(point))) {
			// if we're leaving the layer, fire mouseout
			L.DomUtil.removeClass(this._container, 'leaflet-interactive');
			this._fireEvent([layer], e, 'mouseout');
			this._hoveredLayer = null;
		}
	},
```
 the handleMouseOut can't fire the 'mouseout' events properly.

**Comment by balciseri** [comment]
should we allow more than one hoveredLayer is more layers overlaps? 

```
_handleMouseOut: function (e, point) {
                if (typeof this._hoveredLayers == "undefined") { return; }

                for (var i = 0; i < this._hoveredLayers.length; i++) {
                    var layer = this._hoveredLayers[i];
                    if (layer && (e.type === 'mouseout' || !layer._containsPoint(point))) {
                        L.DomUtil.removeClass(this._container, 'leaflet-interactive');
                        this._fireEvent([layer], e, 'mouseout');

                        delete this._hoveredLayers[i];
                    }
                }
            }
```

```
 _handleMouseHover: function (e, point) {
                var id, layer;
                this._hoveredLayers = [];
                for (id in this._drawnLayers) {
                    layer = this._drawnLayers[id];
                    if (layer.options.interactive && layer._containsPoint(point)) {
                        L.DomUtil.addClass(this._container, 'leaflet-interactive'); // change cursor
                        this._hoveredLayers.push(layer);
                    }
                }
                if (this._hoveredLayers.length) {
                    this._fireEvent(this._hoveredLayers, e, 'mouseover');
                }       
            }
```

**Comment by balciseri** [comment]
aww this is still happening I believe. I updated to rc3 today to try this awsome tooltip feature. But because of this bug ( that's what I think it's happening ) the tooltip it's not disappearing when i move from one canvas marker to another when they "overlapp".

I can't put a new online fiddle atm to show what's happening in my map but i probably can modify the existing one to show the same thing.

**Comment by IvanSanchez** [comment]
This will need some debugging of the `this._hoveredLayer` in `L.Canvas`, and checking if `this._hoveredLayer` changes during `L.Canvas._handleMouseHover`. It should be easy to add a `this._fireEvent([this._hoveredLayer], e, 'mouseout')` there.

**Comment by balciseri** [comment]
I tried something like this : https://playground-leaflet.rhcloud.com/heka/edit?html,console,output
``` 
var CanvasTryFix = L.Canvas.extend({
    _handleMouseHover: function (e, point){ var id, layer;

		for (id in this._drawnLayers) {
			layer = this._drawnLayers[id];
			if (layer.options.interactive && layer._containsPoint(point)) {
				L.DomUtil.addClass(this._container, 'leaflet-interactive'); // change cursor
              if (this._hoveredLayer && this._hoveredLayer!= layer)
                {
                  this._fireEvent([this._hoveredLayer], e, 'mouseout')
                }
				this._fireEvent([layer], e, 'mouseover');
				this._hoveredLayer = layer;
			}
		}

		if (this._hoveredLayer) {
			this._fireEvent([this._hoveredLayer], e);
		}
                                          }
});
    L.Canvas = CanvasTryFix;
```

But it doesn't work well, itì firing to many times the mouseout event

**Comment by IvanSanchez** [comment]
In the case of overlapping circles, `layer._containsPoint(point)` might be true for more than one circle at the same time. I think.

**Comment by balciseri** [comment]
Ivan do you have a fix in mind? Or something i could try work on to fix this?
