### ISSUE TITLE
Problem with for...in loop on layers array in L.Control.Layers on IE

### ISSUE THREAD

**Issue by theashyster** [Leaflet/Leaflet#4508]
So I know that this issue is basically caused by the library I am using - JSTS version 1.1.1, but it also shows a small flaw in the way the layers array is looped through.

In the `L.Control.Layers` function `_update()` the iteration through layers array happens using `for...in` which is okay to use on an associative array as I read here http://stackoverflow.com/a/242888, but in the same thread in another comment http://stackoverflow.com/a/243778 it is suggested to also do this check `if (obj.hasOwnProperty(name))`. The same thing should be checked in `onRemove` method for `L.Control.Layers`.

So my suggestion would be to add this line so the iteration looks like this
```
for (i in this._layers) {
    if (this._layers.hasOwnProperty(i)) {
        obj = this._layers[i];
        this._addItem(obj);
        overlaysPresent = overlaysPresent || obj.overlay;
        baseLayersPresent = baseLayersPresent || !obj.overlay;
        baseLayersCount += !obj.overlay ? 1 : 0;
    }
}
```

Example using Leaflet 1.0.0 RC 1 and JSTS 1.1.1 http://playground-leaflet.rhcloud.com/win/1/edit?html,output
This results in an error in the console `Unable to get property '_leaflet_id' of undefined or null reference` and `L.control.layers` not being added to the map.

**Comment by IvanSanchez** [comment]
Which IE version?

**Comment by theashyster** [comment]
Shows the error for me on verssions Edge, 10 and 9 using Developer Tools in IE.

**Comment by jieter** [comment]
related: #1606

**Comment by jieter** [comment]
In this case, we might want to use the `for (var i = 0; i < this._layers.length, i++){`, since `this._layers` is an array now...

**Comment by theashyster** [comment]
Thanks for the reference @jieter now I see why it is done this why :)
Also agree on changing it to standard for instead of for...in.
