### ISSUE TITLE
leaflet-heat + leaflet-1.0.0-rc1 & pinch zoom

### ISSUE THREAD

**Issue by mgleahy** [Leaflet/Leaflet#4511]
Hello all,

I'm trying out [leaflet-heat](https://github.com/Leaflet/Leaflet.heat), and would like to work with the 1.0.0-rc1 version of leaaflet.  So far, pretty much everything is working fairly well, except that the pinch zoom of a leaflet-heat layer on a mobile device does not animate with the rest of the map.  It works fine with leaflet-0.7.7.

I'm just wondering if someone knows what I would need to change in the leaflet-heat source to make it play nice with leaflet 1.0.0...any suggestions?

**Comment by mgleahy** [comment]
Here's a sample - open it on an iPad, other touch device...then try a pinch zoom:

[http://playground-leaflet.rhcloud.com/tohi/1](http://playground-leaflet.rhcloud.com/tohi/1)

**Comment by IvanSanchez** [comment]
Moved to https://github.com/Leaflet/Leaflet.heat/issues/55
