### ISSUE TITLE
geolocalization stop working on cellphones

### ISSUE THREAD

**Issue by rossanag** [Leaflet/Leaflet#4519]
Hi, locate() isn't working on smart devices, it works fine on desktop. The message error is: _"Geolocation error: Only secur origins are allowed"_Any ideas?

**Comment by hyperknot** [comment]
Geolocation is disabled in most modern browsers if you are not on a https:// website. It is not related to smart devices or desktop, it's only the question of browsers.

If you are looking for a free https solution, I recommend you to simply use CloudFlare (easy) or set up Let's Encrypt (intermediate).

**Comment by rossanag** [comment]
Well, the weird thing is that if I use the google API it works fine, and that it was working before using locate as well.
I don't have a clue how worked under those constraints in cellphones then.
Best

**Comment by hyperknot** [comment]
It's just been rolled out in Chrome 50, I believe we'll be seeing a lot more of these tickets in the next weeks.
https://developers.google.com/web/updates/2016/04/geolocation-on-secure-contexts-only
