### ISSUE TITLE
Augmented reality layer

### ISSUE THREAD

**Issue by beradrian** [Leaflet/Leaflet#4522]
Is there any layer that features augmented reality, even a 3rd party one?

**Comment by IvanSanchez** [comment]
This issue tracker is used for reporting bugs and discussing new features. Search in the [Leaflet plugins page](http://leafletjs.com/plugins.html) to see if there are any plugins that do AR. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
