### ISSUE TITLE
Mouseover events not firing from GeoJSON (1.0.0-rc.1 regression)

### ISSUE THREAD

**Issue by febeling** [Leaflet/Leaflet#4523]
I have a regression in an application that was using 1.0.0-beta.2 when upgrading to 1.0.0-rc.1. 

The map uses a GeoJSON layer, which has sublayers (or features). These sublayers each have `mouseover` and `mouseout` listeners attached. After the upgrade none of these events come through any longer.

(Chrome 49.0/OS X 10.11.4)

It doesn't really sound like it's related to #4495, even though both involve mouse events - as I don't receive _any_ events.

**Comment by yohanboniface** [comment]
Can you make a reproducible test case with http://playground-leaflet.rhcloud.com/?

**Comment by febeling** [comment]
I tried, but it doesn't reproduce just like that. No idea why, but my whole setup is more involved.

**Comment by febeling** [comment]
So it's interesting. The regression only affects the very released version for me. 6ea195a, the tagged revision `v1.0.0-rc.1` is broken, while it's immediate parent commit a626826 works ok.

**Comment by febeling** [comment]
I think the results from from my attempt at narrowing down to a commit got compromised by a globally install version of leaflet -_-

The basic observation still holds, though. I'm working with webpack and require, fwiw.

**Comment by febeling** [comment]
I just did a `git bisect` session and narrowed the problem down to a single commit. (I didn't realize how amazing git bisect works, btw.)

The problem is introduced with this commit: 0cfe85897fef257.

My best theory now is: the cause is a layer that I have in front of the layer for which I need the events. It is set to `interactive: false` via the GeoJSON options when creating the layer. And that setting doesn't become effective any longer. 

Now, is this a bug or did I rely on an undocumented internal which has changed? I'm not clear here. 

I had a look at the API reference just now, and I didn't see this option there (or not any longer?). It is documented for `ImageOverlay` and `Marker`, not for `Layer` though.

**Comment by IvanSanchez** [comment]
@febeling Are you using a canvas renderer, or a SVG renderer?

**Comment by febeling** [comment]
default, SVG

**Comment by mourner** [comment]
@febeling it would still be very helpful to get a reproducible test case online, otherwise we wouldn't be able to fix the issue.

**Comment by febeling** [comment]
@mourner – I just build a more complete example which is essentially the same confign as in my application, and all works fine. So I must assume it's some other quirk in my configuration that I can't put my finger on right now. The problem as stated in the subject isn't really there, so I'll close. Sorry for the confusion.
