### ISSUE TITLE
load listener not unregistered when removeEventListener called inside listener

### ISSUE THREAD

**Issue by pke** [Leaflet/Leaflet#4526]
My map "load" listener looks like this:

``` es6
firstTimeLoaded() {
  this.map.removeEventListener("load", this.firstTimeLoaded)
  this.map.on("moveend", this.getVisibleItems)
  this.updateVisibleItems()
}
```

But it does not remove the eventlistener. Instead when the map is moved the listener is called again eventually. Are you not supposed to unregister event handlers from within the handler itself?

**Comment by pke** [comment]
I think this is related to #4478

**Comment by perliedman** [comment]
You're removing the listener for the `load` event, but adding a listener for `moveend`... it looks like it should call your listener again?

If you can post a running example on [Leaflet Playground](playground-leaflet.rhcloud.com), it might be easier to see the problem.

**Comment by perliedman** [comment]
Might also be worth mentioning [once](http://leafletjs.com/reference.html#events-once), which can be used to just run a listener once.

**Comment by pke** [comment]
@perliedman no, I am removing the `load` listener with a different callback. The `moveend` also uses a different callback. I'll try `once`, but the listener handling seems to broken. There is a rule: when you call listeners, make a copy of the array before you call them. Because the listeners could change the array.

**Comment by perliedman** [comment]
@pke which version are you running? I have pushed a fix for #4478 (#4555), but it doesn't look related to the code you posted above.

The current implementation does clear existing listeners, but without copying as you suggest (https://github.com/Leaflet/Leaflet/blob/master/src/core/Events.js#L164-167).

If you provide a complete, running example, it might be possible to investigate further.

**Comment by yohanboniface** [comment]
Can you please test with latest master?

**Comment by pke** [comment]
I'm using `once` now and it works. But maybe I can try in another project.

**Comment by perliedman** [comment]
Looks like there's not much more to do here.

Add more info if this is still an issue and we'll consider reopening.
