### ISSUE TITLE
Unexpected maxNativeZoom: 0 behavior.

### ISSUE THREAD

**Issue by miniyuuzhan** [Leaflet/Leaflet#4527]
Hi everyone,

So I just got started with Leaflet today, I'm gonna explain the work I have to do so you understand my case.
Basically I have to locate goods on a interior map, placing pins on it. That's easy.
For now, my interior map is a 360pixels by 300pixels image. And here is my code :

```
var imageUrl = "myimgurl";                                                                                      
var mymap = L.map('mapid').setView([0,0],0)

L.tileLayer(imageUrl, {
     attribution: 'MyCompany',
     minZoom: 0,
     maxZoom: 2,
     maxNativeZoom: 0,
     // continuousWorld: true,
     noWrap: true,
}).addTo(mymap);

var marker = L.marker([150, 180]).addTo(mymap);
marker.bindPopup("Hello World !").openPopup();
```

I want the users to be able to zoom twice on the base Image, but what it does is that, at each zoom, the background for the previous zoom state gets bigger (intended) then it divides itself in 4 images.

So I've been playing with **maxNativeZoom** to see what's the problem.

And from the previous example I changed nothing but the **maxNativeZoom**, putting it at 1 : `maxNativeZoom: 1`, and then it does kind of what's expected : from 0 to 1 it still zooms in, splitting the base image in 4. Then from 1 to 2 it only scales up the image, what I am looking for.

So end of my story, I think that the behavior of maxNativeZoom when it equals 0, is broken.
I hope you understood what I want to do : go from zoom level 0 to 2 only scaling up the base image.

Thanks in advance,

**Comment by IvanSanchez** [comment]
You're using a `L.TileLayer` when you really want to use a `L.ImageOverlay` (or maybe a L.ImageOverlay.Rotated`, check the plugins list). Do check the tutorial on non-geographic maps also.

Please be aware that this issue tracker is for bug reports (and sane feature requests) only. For this kind of questions on how to use Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet) in the future.

**Comment by miniyuuzhan** [comment]
Alright, my bad, I thought of posting here because after searching on this repo, I've found that there were some previous unwanted behaviors involving this var.

Anyways, thanks for your help.
