### ISSUE TITLE
Fixed map center

### ISSUE THREAD

**Issue by goeroe** [Leaflet/Leaflet#4533]
Is there a way to make the center of a map fixed? I need to be able to zoom in and out without changing the map's center regardless the position of the mouse. Can't seem to get this to work.

**Comment by IvanSanchez** [comment]
You asked this in https://stackoverflow.com/questions/36828519/leafletjs-lock-map-center/36836741. As stated in the `CONTRIBUTING.md` file, do not use the issue tracker for asking questions.
