### ISSUE TITLE
Performance issue with HTML markers

### ISSUE THREAD

**Issue by jitesh-prajapati123** [Leaflet/Leaflet#4540]
Hello Executive,

There is sever performance issue with leaflet for HTML markers.
If number of HTML markers are more on screen, panning on map is very slow.

Is there any resolution/optimization for same?

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
