### ISSUE TITLE
Async GridLayer docs example incorrectly doesn't return the tile

### ISSUE THREAD

**Issue by neothemachine** [Leaflet/Leaflet#4541]
https://jsfiddle.net/34tzatzd/

Tested with 1.0.0-rc.1

**Comment by nathancahill** [comment]
You have to return the tile at the end of createTile, then call the done callback when you finish drawing the tile.

**Comment by neothemachine** [comment]
Ok, then the docs are wrong, they miss the return statement for the async version.

**Comment by nathancahill** [comment]
Indeed.
