### ISSUE TITLE
Adjusting street width.

### ISSUE THREAD

**Issue by jcarpanelli** [Leaflet/Leaflet#4545]
Hello there! I wanted to know if there is way to make the streets widths wider when zooming in. I noticed that when the map is being zoomed, the streets width automatically adjusts to a smaller width. (I'm currently using openstreetmaps). I realized it's not a zoom problem. 
I want to accomplish this (google maps):
http://i.imgur.com/nl5RxVb.png
And I'm getting this:
http://i.imgur.com/JtpJXJd.png

Thanks in advance.

**Comment by SuberFu** [comment]
I think the streets are "drawn" in by the server before serving them to you as map tiles. As such, leaflet have no way of changing this unless the tile server allow you to pass a parameter to define the street width..

**Comment by nathancahill** [comment]
As stated in the CONTRIBUTING.md file, do not use the issue tracker for asking questions. Post to
