### ISSUE TITLE
GridLayer canvas tiles disappear on zoom

### ISSUE THREAD

**Issue by letmaik** [Leaflet/Leaflet#4546]
I found a weird behaviour with Leaflet 1.0.1 + GridLayer + Canvas. Tested on latest Firefox and Chrome.
What happens is that the first drawing works as it should, but as soon as I zoom, nothing of the grid layer is drawn anymore. I can see that createTile gets called and I feel the drawing delay but it's just invisible:

http://letmaik.github.io/xndarray/

The code: https://github.com/letmaik/xndarray/blob/gh-pages/js/demo.js

**Comment by letmaik** [comment]
I just updated the test code to 1.0.1 and the issue is still there.

**Comment by IvanSanchez** [comment]
The `<canvas>` tiles are there, but the rendered data moves around to north canada after zooming, which makes me guess this is a problem on *your* side, failing to calculate the bounds of the tile or the coordinates of each pixel in the tile (ProTip™: use the [`L.GridLayer._tileCoordsToBounds` private method](https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/GridLayer.js#L683))

If you can provide a **minimal** reproducible example, then I'll reopen this. (I usually suggest a reading of ["http://www.chiark.greenend.org.uk/~sgtatham/bugs.html"](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) so people get a feel of *why* we ask for minimal reproducible cases). You example, which depends on some palette library and some data interpolation thing, is **not** minimal.

**Comment by letmaik** [comment]
I found the issue. I forgot to add the second parameter (zoom) to `map.unproject`. In Leaflet 0.7 this parameter defaulted to the current zoom level which makes sense to me. I wonder why it was changed. It's quite a subtle difference to spot when upgrading to 1.0.

**Comment by letmaik** [comment]
Working minimal example: https://bl.ocks.org/letmaik/e71eae5b3ae9e09f8aeb288c3b95230b

**Comment by IvanSanchez** [comment]
@letmaik Yup, in that minimal example the canvas tiles don't disappear, and everything seems to work as expected.

**Comment by letmaik** [comment]
Yes, see my earlier message where I explained how I fixed the bug.
