### ISSUE TITLE
GridLayer Async external promise calls

### ISSUE THREAD

**Issue by Tornado-Tim** [Leaflet/Leaflet#4547]
Hey,
I have implemented a Leaflet Gridlayer which interfaces with a global Webworker to fetch and grab data for the tiled area, however due to the restrictive nature of Gridlayer async promises only being able to be called from CreateTile method.
I cant call the callback with canvas object externally like in previous versions ie:use the  TileDrawn function (in Leaflet 0.7). 

Could this be added back please as I was using it quite extensively

**Comment by nathancahill** [comment]
What do you mean by "restrictive nature of Gridlayer async promises"? I'm using the web worker pattern with GridLayer in Leaflet 1.0, it works fine. As stated in the CONTRIBUTING.md file, do not use the issue tracker for asking questions. Post to http://stackoverflow.com or http://gis.stackexchange.com instead.

**Comment by Tornado-Tim** [comment]
Sorry I dont think I explained correctly.

I am extending the Gridlayer Class but I have a GlobalWeb WebWorker. The Webworker is not initiated within the CreateTile function.

What I am saying is that the callback can only be called within the Layer scope, and not from the the global scope like in previous versions of leaflet by using the TileDrawn function.

I know that it would be fine if the webworker was within the Layer scope but the webworker needs to be accessed outside this layer as it is a shared data source.
 
I wasnt asking a question on how to do it, this is just a feature request, so callback can be called globally from outside leaflet.

**Comment by IvanSanchez** [comment]
> I wasnt asking a question on how to do it, this is just a feature request

I disagree.

This can be done with a global set of references to unfinished `done` callbacks. See the method used in [GoogleMutant](https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant/blob/master/Leaflet.GoogleMutant.js). Just make an array/dictionary/object with the global scope, have the layer and the worker modify it.
