### ISSUE TITLE
Crashy / buggy leaflet 0.7.7 and 1.0.0-rc.1 in Iceweasel 38.8.0 and Firefox 46.0.1

### ISSUE THREAD

**Issue by ldng** [Leaflet/Leaflet#4548]
I can not manage to make leaflet work in Iceweasel nor Firefox.
The first one crashes and the other show up nowhere and marker stays in left-up corner.
It works in Chromium 50.
I'm probably doing something wrong but I don't see it.
Any hint welcome.

```javascript
        var map = new L.map('map', {center: new L.LatLng(latitude, longitude), zoom: 17});
        L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
            attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
        }).addTo(map);
        var icon = L.icon({
            iconUrl: '/img/icon.png'
        });
        L.marker([latitude, longitude], {icon: icon}).addTo(map)
```

**Comment by IvanSanchez** [comment]
Do the maps in the leafletjs.com/examples.html work well on your browser?

**Comment by ldng** [comment]
They do. And so do the maps in the debug/map/ folder of the project.
I can only guess it's a bad interraction with some CSS on my page I suppose.
I'll try to narrow down a test case.

**Comment by IvanSanchez** [comment]
No more information has been provided, and more than a few weeks have passed. We'll assume this issue is no longer relevant and/or there is no interest to make a better report.
