### ISSUE TITLE
Can I reduce the time a mouseover popup takes to appear?

### ISSUE THREAD

**Issue by FunkyLoveCow** [Leaflet/Leaflet#4549]
I'd like to reduce the time a mouseover popup on a marker takes to appear. How to I eliminate the current delay?

**Comment by SuberFu** [comment]
Do you mean the L.popup or the browser's "popup" (which is a tooltip).
As far as I know, there's no built in "popup on mouseover" in L.popup.
As for the browser's tooltip, I don't think you can change it through javascript.

**Comment by FunkyLoveCow** [comment]
It seems that I meant the tooltip. Thank you for that clarification. 

If it can't be done via Javascript, I'll close this issue.
