### ISSUE TITLE
Problems with WMS in CRS 4326

### ISSUE THREAD

**Issue by debjan** [Leaflet/Leaflet#4550]
Hi,

I'm trying to use WMS server with CRS in EPSG:4326 (using leaflet v1.0.0-rc.1):
```javascript
L.tileLayer.wms("http://wrep.ecmwf.int/wms/", {
  layers: 'foreground',
  format: 'image/png',
  width: 256,
  height: 162,
  crs: L.CRS.EPSG4326,
  token: token,
  transparent: true,
}).addTo(map);
```
output:

![screen](http://i.imgur.com/NiTKXeE.png)

Zooming further, distortion is less noticeable, and at levels greater than 5 all looks fine.

OTOH, using same service with `image/svg+xml` format shows this:

![screen](http://i.imgur.com/prewAjw.png)

**Comment by IvanSanchez** [comment]
1) Post a link to a publicly available reproducible example, e.g. in http://playground-leaflet.rhcloud.com

2) Why are you doing this?
```js
source.wmsParams.width = 256;
source.wmsParams.height = 162;
```

**Comment by debjan** [comment]
1) I'll try to find another WMS server in EPSG:4326 as I'm not sure if I am allowed to share the token.

2) The server streams with such tiles, otherwise with default 256x256 I get garbled tiles.

**Comment by IvanSanchez** [comment]
Do check the [WMS tutorial](http://leafletjs.com/examples/wms/wms.html), BTW. I think you're trying to mix 3857 with 4326 in the same map, and that's not supported by Leaflet.

**Comment by debjan** [comment]
Yes, I expected that leaflet will reproject if references are known...

Ok then, I just found WMS with global coverage and EPSG:4326 support and made reproducible example: https://gist.github.com/anonymous/24185591af986184129203f26dcbbb66

I used svg format, and there doesn't seem to be a problem as reported above.

Thanks for your support.

**Comment by IvanSanchez** [comment]
> Yes, I expected that leaflet will reproject if references are known...

No, Leaflet doesn't do on-the-fly reprojection. If you want to use a WMS service in 4326, then your whole map has to be in 4326, as stated in the WMS tutorial.

Mixing CRSs (and reprojecting stuff to match) is out of the scope of Leaflet, and won't be done in the foreseeable future.
