### ISSUE TITLE
Missing Leafdoc template files

### ISSUE THREAD

**Issue by bbecquet** [Leaflet/Leaflet#4556]
When trying to build the 1.0.0 API doc according to https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md#api-documentation, the build fails with a missing `constructor.hbs` message.

Comparing with https://github.com/Leaflet/Leafdoc/tree/gh-pages/templates/leaflet, `constructor.hbs` & `destructor.hbs` are actually missing from the list of files.

**Comment by IvanSanchez** [comment]
Yeah, I forgot to provide templates for Leaflet when I added the constructor and destructor directives to Leafdoc. It should be simple enough for anybody to copy the `factory.hbs` template into `constructor.hbs` and `destructor.hbs`, modify the text slightly and send a PR. Any takers?

**Comment by bbecquet** [comment]
Ok, thanks for the quick reply. I'll propose the fix tonight if nobody took it in the meantime.
