### ISSUE TITLE
Control.Layer._getLayer iterates  too far on layers array

### ISSUE THREAD

**Issue by ValentinH** [Leaflet/Leaflet#4560]
[This line](https://github.com/Leaflet/Leaflet/blob/master/src%2Fcontrol%2FControl.Layers.js#L195) is incorrect:
```js
for (var i = 0; i <= this._layers.length; i++)
```

PR upcoming

**Comment by IvanSanchez** [comment]
Is it possible to make that call fail by requesting an invalid layer ID somehow? Maybe the off-by-one bug just hasn't been reproduced ever, as the layer is always found before reaching the end of the loop.

**Comment by ValentinH** [comment]
I don't really know yet. I'm using angular ui-leaflet and just updated to Leaflet 1.0rc from beta2 and noticed this error in one of my views.
I can investigate further to understand why it reaches the end of the loop.

**Comment by IvanSanchez** [comment]
Can you copy-paste the exact error you got? That'd be useful.

**Comment by ValentinH** [comment]
```
TypeError: Cannot read property 'layer' of undefined
    at L.Control.Layers.L.Control.extend._getLayer (leaflet.js:11685)
    at L.Control.Layers.L.Control.extend.removeLayer (leaflet.js:11603)
    at updateLayersControl (ui-leaflet.js:383)
    at ui-leaflet.js:3972
    at Scope.$digest (angular.js:16664)
    at Scope.$apply (angular.js:16928)
    at angular.js:17224
    at completeOutstandingRequest (angular.js:5804)
    at angular.js:6081(anonymous function) @ angular.js:13236(anonymous function) @ angular.js:9965Scope.$digest @ angular.js:16682Scope.$apply @ angular.js:16928(anonymous function) @ angular.js:17224completeOutstandingRequest @ angular.js:5804(anonymous function) @ angular.js:6081
```

**Comment by IvanSanchez** [comment]
Any idea what is the state of the layers control previous to the call to `removeLayer`? It would be nice to have a unit test about this.

**Comment by ValentinH** [comment]
I think the error is fired because angular ui-leaflet calls `removeLayer` with a baseLayer but doesn't add it before... I'm investigating it.

**Comment by IvanSanchez** [comment]
I cannot make this fail in vanilla leaflet. I'll accept the PR as it's quite trivial, but I will guess that angular-leaflet is playing with the private properties of `L.Control.Layers` manually, and messing up the state by not removing layers cleanly enough.

**Comment by ValentinH** [comment]
OK I got it.

The problem comes from [this block](https://github.com/angular-ui/ui-leaflet/blob/master/src%2Fservices%2FleafletControlHelpers.js#L160) in ui-leaflet.

I'm using a layer control where the base layer is hidden. Thus, ui-leaflet [doesn't add it](https://github.com/angular-ui/ui-leaflet/blob/master/src%2Fservices%2FleafletControlHelpers.js#L180-L184) but the problem is that it tries to [remove it](https://github.com/angular-ui/ui-leaflet/blob/master/src%2Fservices%2FleafletControlHelpers.js#L166-L168) later on...

**Comment by jieter** [comment]
Hmm, that line was wrong indeed, but why is `this._layers[i]` truthy when `i = this._layers.length`? 

I'm trying to come up with a unit test for this case...

**Comment by ValentinH** [comment]
Oh yes, I didn't see that: weird!

**Comment by IvanSanchez** [comment]
No idea. `this._layers` gets `splice()`d and `push()`ed, so I really don't know how a truthy value is getting in there.

**Comment by ValentinH** [comment]
Oh wait, the reason is that in the rc dist file, the `this._layers[i]` truthy check is not there...

**Comment by ValentinH** [comment]
This was added by the @jieter 's commit: 02078c2b39 .
I was also wondering if a check should be added [here](https://github.com/Leaflet/Leaflet/blob/master/src%2Fcontrol%2FControl.Layers.js#L113) because it wasn't there in the RC release.

**Comment by IvanSanchez** [comment]
Oh, so what was happening is that you hit a bug in angular-leaflet that is present in 1.0.0-rc1 but not in the `master` branch :-D

**Comment by ValentinH** [comment]
Yes but the `<=` was still disturbing! :)
