### ISSUE TITLE
Popup Skins

### ISSUE THREAD

**Issue by IAmJulianAcosta** [Leaflet/Leaflet#4562]
Hi! 

I'm using leaflet in order to generate a popup, but I don't need the default styles, so I'm proposing adding a class like `.leaflet-popup-default-style`, and put the css in there, and defaulting `className` to that name. 

Developers should use classes like `.leaflet-popup-dark-style` in order to override the default styles, because there is always better to add styles instead of subtracting them.

Currently we have to do something like: 

```
.leaflet-popup-content-wrapper {
    background: black;
    box-shadow: 0 3px 14px rgba(255,255,255,0.4);
}
.leaflet-popup-content-wrapper {
    border-radius: 5px;
}
.leaflet-popup-content
    padding: 6px;
}
```

I think that is better to have neutral styles in `.leaflet-popup`, and adding styles using other classes for styles.

**Comment by IvanSanchez** [comment]
Nope.

There is already a default CSS class name for Leaflet popups, [`.leaflet-popup`](https://github.com/Leaflet/Leaflet/blob/master/src/layer/Popup.js#L286), and nothing is preventing you from adding another class name and having a set of CSS rules for, for example, `.leaflet-popup.dark`, `.leaflet-popup.dark > .leaflet-popup-content-wrapper`, and so on.

**Comment by IAmJulianAcosta** [comment]
The idea is to not override the styles, adding, not subtracting them. With the current approach, we have to overwrite them, and this is not a good practice. 

My point is that adding current styles to a class style, by just replacing the default class style, the default styles are replaced, not overwritten.

**Comment by IvanSanchez** [comment]
> With the current approach, we have to overwrite them, and this is not a good practice. 

I strongly disagree. This is **cascading** style sheets we're talking about, and creating more detailed CSS selectors is standard practice since ages ago.

Unless the current method has a severe flaw (e.g. repaints take longer in some browser), I see no reason at all to change it, and I don't see why it's a bad practice.

**Comment by IAmJulianAcosta** [comment]
IMO is a bad practice because even if CSS is designed to use cascading, if in a future release a new style is added to `.leaflet-popup-content-wrapper`, that style will be inherited by all the `.leaflet-popup-content-wrapper` instead of the intended default styles.

Leaflet 2.0:
```
.leaflet-popup-content-wrapper {
    padding: 1px;
    text-align: left;
    border-radius: 12px;
    border: solid thin red; //yay, now I have to override border in my theme
}
```

Leaflet 2.5:
```
.leaflet-popup-content-wrapper {
    padding: 1px;
    text-align: left;
    border-radius: 12px;
    border: solid thin red; 
    background: blue; //yay! another property to override
}
```

Less overriding needed is better. Also, why to override all the styles when is possible to start from a blank canvas? The problem about the current implementation is that child styles _might_ or _might not_ inherit default styles. There are some styles that are fine, like the ones that gives the position to the popup, but the others, should not be inherited.

A little bit more about I'm talking about: http://markdotto.com/2012/03/02/stop-the-cascade/

**Comment by IAmJulianAcosta** [comment]
This is all the code I had to write just to _hide_ the default popup and and _reset_ its styles to create a simple empty `<div>`.

```
.leaflet-popup.clean {
	.leaflet-popup-close-button {
		display : none
	}
	.leaflet-popup-content-wrapper {
		padding       : 0;
		text-align    : left;
		border-radius : 0;
		&, .leaflet-popup-tip {
			background : transparent;
			box-shadow : none;
		}
	}
	.leaflet-popup-content {
		margin: 0;
	}
	.leaflet-popup-tip-container {
		margin : 0;
		width  : auto;
		height : auto;
		display : none;
	}
	.leaflet-popup-tip {
		display : none;
	}
}
```
In my opinion, is less maintainable than just adding the styles from scratch.

**Comment by IvanSanchez** [comment]
Pero es que el CSS de los popups es tremendamente estable: ¡la mayoría no ha cambiado desde 2011/2012! El coste de cambiar las clases CSS de los popups ahora es muchísimo mayor, con creces, que el hipotético beneficio de reordenarlas.

Además, el caso de uso típico de popups consiste en sobrecargar alguna de las reglas CSS de los popups, no todos: que algunos de mis popups tengan esta clase para poder estilar algo del interior de una manera o de otra, pero sin tener que reescribir todas las reglas.

Tu cambio reduce el mantenimiento *para un caso de uso particular*, no para los casos típicos que yo me he encontrado muchas veces. En serio, Julián, el cambio no merece la pena.

**Comment by IAmJulianAcosta** [comment]
Estoy de acuerdo en que no es un caso típico, y si te refieres a "no vale la pena", respecto a que es mucho esfuerzo para que no sea algo muy usado, yo estoy dispuesto a implementar la funcionalidad, tampoco se trata de exigir sin aportar.

**Comment by IvanSanchez** [comment]
No, me refiero al esfuerzo que supondría a los usuarios actuales de 0.7.x y de 1.0.0-rc1 adaptarlo todo.
