### ISSUE TITLE
fitBounds with custom projection acts really strange

### ISSUE THREAD

**Issue by theashyster** [Leaflet/Leaflet#4566]
At first I thought that this is fixed with this really easy fix https://github.com/Leaflet/Leaflet/issues/4528, but looks like it actually is not, and by doing the fix a new possible issue has occurred, not 100% sure. Also looks like the fix was actually not done in the right place, probably. This is all speculation, because I cannot reproduce the issue using plain Leaflet, but with a custom projection this issue pops up and does not go away.

By removing the `.add(padding)` from the `boundsSize` we now can ran into issues when working with bounds that are just a point and in that case `boundsSize` will be 0 and will cause trouble on this line calculating scale as `Infinity` and because of that `getBoundsZoom` returns `NaN`:
`var scale = Math.min(size.x / boundsSize.x, size.y / boundsSize.y);`

Working beta2: http://playground-leaflet.rhcloud.com/divo/1/edit?html,output
Working 0.7.7: http://playground-leaflet.rhcloud.com/nov/1/edit?html,output
Not working master: http://playground-leaflet.rhcloud.com/gin/1/edit?html,output
Not working rc1: http://playground-leaflet.rhcloud.com/cit/1/edit?html,output

The other issue I have is that in `getBoundsZoom` function we have this line:
`zoom = this.getScaleZoom(scale, zoom);`

Since zoom is set before like this `var zoom = this.getZoom() || 0` when we call `getScaleZoom` it always gives different result when we pass the function different zoom level and the same scale. If we do multiple fitBounds() calls in a row with the same bounds, but different starting zoom level (do one call, then do another from the resulting zoom level, then do another) this causes map to zoom around strangely. Size and boundsSize does not change, but the calculated zoom using `getScaleZoom` changes due to the changes in the starting zoom level.

Issue shown on rc1: http://playground-leaflet.rhcloud.com/faf/1/edit?html,output
Working as expected on beta2: http://playground-leaflet.rhcloud.com/gug/1/edit?html,output
Not working at all on master: http://playground-leaflet.rhcloud.com/quxi/1/edit?html,output
-- Click on the fitBounds button under the map to see the issue in action

Looks like this is the commit that kind of turned things ugly using custom projections https://github.com/Leaflet/Leaflet/commit/3fde3c0390e03c6d0187ede1c9418c3c57fd1765

So probably I should ask @IvanSanchez to take a look at this

**Comment by perliedman** [comment]
Yes, we had some trouble with this before: #4395, #4402.

When I last looked at it, I was thinking maybe reverting to the loop we had before would be the easiest approach, although the current one is theoretically more elegant.

**Comment by IvanSanchez** [comment]
I see. The map's zoom level gets set to `NaN`.

This is partly Proj4Leaflet's fault (ping @perliedman ). Leaflet's code expects that a call to [`L.CRS.zoom()`](https://github.com/Leaflet/Leaflet/blob/master/src/geo/crs/CRS.js#L60) with an scale factor of `Infinity` shall return `Infinity`. This way, Leaflet can then `Math.min()` and `Math.max()` the zoom levels with the map's `maxZoom` and `minZoom`.

I've done a quick read of the Proj4Leaflet's code for `L.CRS.zoom()`, and it seems that it assigns `undefined` to `this._scales[nextZoom]` (because it's over the highest zoom level), then that becomes `NaN`.

**Comment by IvanSanchez** [comment]
So we can:

* [ ] Fix proj4leaflet so it returns `Infinity` instead of `NaN`
* [ ] Fix Leaflet so `getScaleZoom` checks for `NaN`
* [ ] Both

**Comment by perliedman** [comment]
Sounds like fixing on the Proj4Leaflet side would be desirable!

**Comment by theashyster** [comment]
@perliedman For my project I have tested if everything works fine if I just take the `getBoundsZoom` function and override it in my code with the function that Leaflet had in beta2 and then everything works fine, so I have considered that as a dirty hack for now.

@IvanSanchez Thanks for the info :)

**Comment by perliedman** [comment]
@theashyster yeah, the problem that Proj4Leaflet has to consider is CRS where zoom levels are not a factor of 2, which is the reason for the current implementation. If you have a zoom factor of 2, Leaflet's default will work fine if I remember correctly.

**Comment by theashyster** [comment]
@perliedman Okay, thanks for the clarification

**Comment by jumbosushi** [comment]
Hello! I came here from ttps://twitter.com/yourfirstpr. Is anyone working on this?

**Comment by IvanSanchez** [comment]
@jumbosushi No, there's nobody working on this. Do you have a good understanding of what needs to be done?

**Comment by theashyster** [comment]
Hi, all, I have created two pull requests to fix this issue using the steps provided by @IvanSanchez 
Take a look when you have the time :)

**Comment by theashyster** [comment]
I have retested the original issue after the pull requests has been merged, it seems to be gone now.
So closing the issue.
