### ISSUE TITLE
L.polyline (maybe even L.polygon) graceful fallback for single point.

### ISSUE THREAD

**Issue by SuberFu** [Leaflet/Leaflet#4567]
Currently, if a L.polyline contains a single point, it's not visible. Granted, a polyline with a single point is not exactly a valid "line". However, it would be nice to have an option for a polyline to 'fallback' to displaying a line cap point (same size as stroke width).

I notice that this can be solved, at least in SVG, by just changing "Mx y" to "Mx yLx y". Essentially, drawing a line with head and tail at the same place. So perhaps this change in L.polyline could fix this.

```
	_update: function () {
		if (!this._map) { return; }

		this._clipPoints();
		this._simplifyPoints();
		this._updatePath();
                if (this._parts.length === 1 && this.options.fallbackToPoint){
                        this._parts.push(this._parts[0]);
                }
	},
```

**Comment by hyperknot** [comment]
I believe this issue should be handled in server-side at the data processing step, if required by the application. In my opinion Leaflet core shouldn't do "magic" like this.

**Comment by SuberFu** [comment]
The result latlngs are not the result of server processing, but user activity on the map. For example, a user could "erase" enough points from a polyline to degenerate it into a single point, and then later add new points to it. I was hoping for some way to gracefully handle these cases. Currently I have wrapper code that append an additional duplicate point if a polyline is left with a single point, and remove the extra if it detects a polyline has just two identical points.

**Comment by hyperknot** [comment]
If the user is able to modify the geometries after they have been loaded, then it should be handled in the geometry processing code. Editable does something similar for example.

**Comment by IvanSanchez** [comment]
I do agree with @hyperknot: this is a case of GIGO. The code which adds a second point in the same `LatLng` can do it outside the code for polyline, as well.
