### ISSUE TITLE
FitBound Issue

### ISSUE THREAD

**Issue by sathishrajendrian** [Leaflet/Leaflet#4568]
Hi,
Fitbound internally calls the Zoom event. How to stop calling the Zoom event after fitbound. Is there any option or callback for Fitbound. 

Please give some suggestion to stop zoom on fitbound.

Thanks in advance.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
