### ISSUE TITLE
taphold closes popup w/closeOnClick set to false

### ISSUE THREAD

**Issue by wyattp11** [Leaflet/Leaflet#4572]
I have a popup that I want to require the user to click a button in to close it and move on with building their route on the map... I also have a taphold function, which can close the popup even with closeOnClick set to false(i.e. popup is opened, user performs taphold, popup closes). Not sure if this is really a bug or just a feature request? Would be nice if the closeOnClick also applied to taphold.

**Comment by wyattp11** [comment]
Correct, taphold doesn't seem to be covered by that option

**Comment by yohanboniface** [comment]
Can you please set up a minimal example reproducing the issue with http://playground-leaflet.rhcloud.com/ ?

**Comment by wyattp11** [comment]
Terribly sorry, I'm an idiot. I have a function in my .on('contextmenu') event that creates another popup...which closes the current popup on the map. closeOnClick: false works like it should, a regular popup does not close with taphold.
