### ISSUE TITLE
Popup's _adjustPan has _map is equal to null for popupopen and popupclose events

### ISSUE THREAD

**Issue by zackharley** [Leaflet/Leaflet#4573]
I'm using the `popupopen` and `popupclose` events to adjust data in my application when a popup is clicked. This works the first time a popup is opened via a marker click, but as soon as it is closed, the popup will not reopen. Looking at the dev console in Chrome, I'm seeing that the `this._map` property being called in `_adjustPan` is set to `null`. Somehow the markers are getting removed from the map when I use `popupopen` and `popupclose`. I'm wondering if anyone has any idea what could be causing this to happen?

**Comment by hyperknot** [comment]
Hi, can you make a minimal example of it on playground-leaflet.rhcloud.com? Also, what version are you using?

**Comment by perliedman** [comment]
This sounds like some kind of race condition, but impossible to say without a more detailed example of when this happens.

I'm closing this for now, but consider reopening if more information is added.
