### ISSUE TITLE
svg and canvas styles leak through to markers

### ISSUE THREAD

**Issue by janpaul123** [Leaflet/Leaflet#4575]
[These lines](https://github.com/Leaflet/Leaflet/blob/fbc6265fb7a99b442c6997643e4b12d8c43ba346/dist/leaflet.css#L8-L9) make it harder to use SVG and Canvas elements in markers, as you have to explicitly override these styles. Would it be possible to use something more specific?

**Comment by perliedman** [comment]
Closed by #4597.

**Comment by janpaul123** [comment]
Thank you!
