### ISSUE TITLE
Multiple (looped) panTo events happen too fast or only execute last panTo.

### ISSUE THREAD

**Issue by spydmobile** [Leaflet/Leaflet#4577]
using the 1.0 RC1 version:

When I do a single panTO like this:
  map.panTo(newLatLng, {animate: true, duration: 5.0} );

it works great, but if I loop through a list (Virtual Tour) and try to pan to each of the locations. it will only do the last one. 

if I switch over and use:
 map.flyTo(newLatLng, newZoom, {animate: true, duration: 5.0} );

same results, only the last one works. I Know the array values are good becuase each one works fine if used from the array as a single pan or fly.

I would expect to be able to loop through a list and have each one executed. 

I also added a horrible sleep function to case a 2 second delay between each pan/fly and in the console I can clear see it executing the code, but nothing happens till the function doing the work exists.

**Comment by EricRoque** [comment]
This code can help you?
`setTimeout(function(){map.panTo(L.latLng(-10.350002, -30.923930), {animate: true, duration: 1})}, 1000);`
`setTimeout(function(){map.panTo(L.latLng(10, 30), {animate: true, duration: 2})}, 2000);`
`setTimeout(function(){map.panTo(L.latLng(-10, 45), {animate: true, duration: 3})}, 5000);`
`setTimeout(function(){map.panTo(L.latLng(-10.350002, -30.923930), {animate: true, duration: 1})}, 8000);`

The above solution is not the best but i thought to combine the event as below but I'm not sure yet how to work with a list of points

`map.panTo(L.latLng(10, 30), {animate: true, duration: 3});`
`map.on('moveend', function(ev) {`
     `map.panTo(L.latLng(-10.350002, -30.923930), {animate: true, duration: 1});`
`});`

**Comment by jwoyame** [comment]
The problem you're having is that each call is immediately cancelling the one before it, so only the last one remains. You need to stagger them using a timeout as @EricRoque shows.

Here is how you can do it in a loop:

```javascript
var _tourStops = [ L.latLng(-80, 40), L.latLng(80, 40), L.latLng(30, 0) ],
      _tourDelaySec = 5,
      _tourZoom = 13;

function runTour() {
    for (var i = 0; i < _tourStops.length; i++) {
        setTimeout(function() {
            map.flyTo(_tourStops[i], _tourZoom, {animate: true, duration: _tourDelaySec} );
        }, _tourDelaySec * i);
    }
}
```
