### ISSUE TITLE
IE8: L.Icon.Default.imagePath detected incorrectly

### ISSUE THREAD

**Issue by perliedman** [Leaflet/Leaflet#4579]
In the debug pages, IE8 picks up the path to the default marker icon incorrectly.

Looking at the result marker `img` tag, it har `src="http://192.168.1.53:8081/debug/images/marker-icon.png`", where it should be the equivalent of `http://192.168.1.53:8081/dist/images/marker-icon.png`.

Chrome shows the URL `http://localhost:8081/debug/../src/../dist/images/marker-icon-2x.png` on the same page, so I guess IE8 is thrown off by multiple `..` in the path.

**Comment by IvanSanchez** [comment]
Shall we just inline the image in a `data:` or `blob:` URI and get that over with?

**Comment by perliedman** [comment]
Sounds like that would avoid some problems.

But it would also force everyone to load the default marker images and shadows, even if they're not using them... I guess that will not be really popular.

**Comment by johnd0e** [comment]
Should be resolved by #4605
