### ISSUE TITLE
Improving shape filtering workflow - creation and deletion 

### ISSUE THREAD

**Issue by tdupre** [Leaflet/Leaflet#4580]
Hi, 

I'm the user experience designer at OpenDataSoft and we use Leaflet with some great results.

Sometimes people need to filter pins on the map and Leaflet has the shape filter feature. 
Draw a polygon, circle or rectangle to filter and the pins inside the shape are filtered. 
That works 👍 

![ods-data opendatasoft com 2016-05-18 09-48-22](https://cloud.githubusercontent.com/assets/18527605/15351233/94ea9102-1cde-11e6-8f7a-2feddda4da49.png)

Though, people encounter some issues with guidance, predictibility and feedback when using this feature. 

### Shape drawing - guidance 

- there's no guidance on how to use the feature at all, at first some people are clueless on how to actually draw a circle and it takes a few tries, adding a little guidance when circle draw would help out a lot 

My suggestion is to add a message centered at the bottom of the map indicating: 

> Click to place the center then drag to draw the circle

![capture d ecran 2016-05-18 a 10 09 55](https://cloud.githubusercontent.com/assets/18527605/15351710/e322768a-1ce0-11e6-8a51-c83f5b2e3fa5.png)

And then : 

> Click and drag to draw the rectangle

> Click to add a point, double click or circle back to close the polygon

### Shape drawing - polygon filter - feedback and predictibilty 

- delete last point is enabled even when there's no point  - it should be disabled (greyed out) when there's no point
![ods-data opendatasoft com 2016-05-18 09-49-21](https://cloud.githubusercontent.com/assets/18527605/15351239/a1e746d4-1cde-11e6-8e24-8b361da93a5d.png)

- delete last point doesn't work for the first point - it should be disabled too if it doesn't work, 

Something like this 

![capture d ecran 2016-05-18 a 09 59 44](https://cloud.githubusercontent.com/assets/18527605/15351422/84867a50-1cdf-11e6-8378-48d636d5d40a.png)

### Deletion - Guidance 

This is the most puzzling item. 
When trying to delete a shape, there's a confirmation : this is good, always warn before destruction.

But the wording is strange: the label says save, when the action is actually delete. The user is not saving anything. 

![ods-data opendatasoft com 2016-05-18 09-51-13](https://cloud.githubusercontent.com/assets/18527605/15352340/05d04b46-1ce4-11e6-8176-e9bd9cca606b.png)

So people are wondering:
- is save delete? 
- is cancel delete? 
- do I save the shape somewhere? Why is there a trashcan icon? 

My suggestion is to change the wording for a non ambiguous and totally clear verb + noun wording: 

> Delete shape | Keep shape 

Like this 

![capture d ecran 2016-05-18 a 10 33 38](https://cloud.githubusercontent.com/assets/18527605/15352428/6d020b4c-1ce4-11e6-81f7-72b7ac595581.png)

Thanks for reading :) 

--
Thibaut

**Comment by IvanSanchez** [comment]
This is the leaflet core repo, and I think this belongs to either [Leaflet.draw](https://github.com/Leaflet/Leaflet.draw) or [Leaflet.editable](https://github.com/Leaflet/Leaflet.Editable) - please add the issue to the right repo :-)

**Comment by tdupre** [comment]
Done, sorry about this :)
