### ISSUE TITLE
Erroneous L.circle getBounds() calculations using projected coordinates

### ISSUE THREAD

**Issue by nathansnider** [Leaflet/Leaflet#4582]
In 1.0.0-rc1, the `getBounds()` method for `L.Circle` calculates LatLng bounds based on projected coordinates that are [rounded to the nearest pixel](https://github.com/Leaflet/Leaflet/blob/v1.0.0-rc.1/src/layer/vector/Circle.js#L80) (with a floor of 1). Thus, using `getBounds()` on a circle will produce different bounds when the map is at different zoom levels, with wildly inaccurate results when the circle (as projected on the map) is smaller than a couple pixels wide. 

For example, try this function while at zoom level 0:

```
map.on('click', function(e) {
  var circ = L.circle(e.latlng, {radius:100}).addTo(map);
  var bounds = circ.getBounds();
  var rect = L.rectangle(bounds).addTo(map);
  var width = map.distance([e.latlng.lat, bounds.getWest()], [e.latlng.lat, bounds.getEast()]);
  console.log('Width of bounds: ' + width);
});
```

http://jsfiddle.net/nathansnider/wa2we8t2/

The bounds calculated for a circle with a 100m radius will be as large as 300km on a side, depending on latitude.

**Comment by IvanSanchez** [comment]
Hm, that code is old (2014). Have you tried removing the `Math.round()` statements and seen if anything breaks?

**Comment by nathansnider** [comment]
Removing the `Math.round()` and `Math.max()` statements fixes the problem and doesn't seem to break anything:

    this._radius = isNaN(lngR) ? 0 : p.x - map.project([lat2, lng - lngR]).x;
    this._radiusY = p.y - top.y;

http://jsfiddle.net/nathansnider/Lvrzzcrt/

Submitted a PR just now.

**Comment by mourner** [comment]
I think the original reason for rounding/max was that some browsers (IE?) broke on 0 and non-round values. Although it's probably worth handling this on the rendering side rather then when setting `_radius` and `radiusY` values.

**Comment by nathansnider** [comment]
Sure enough, the changes I posted above break `L.Circle` in IE8 (as emulated by IE11, anyway). Small circles don't draw until you zoom in far enough that they are at least 2 pixels wide. So don't use that!

**Comment by IvanSanchez** [comment]
@nathansnider In that case, I suggest adding some `Math.round()`s in `L.SVG._updateCircle`, `L.SVG.VML._updateCircle` and `L.Canvas._updateCircle`.
