### ISSUE TITLE
Click on leaflet-popup-tip-container

### ISSUE THREAD

**Issue by eliboni** [Leaflet/Leaflet#4589]
What's the preferred way to catch a click on popup's "leaflet-popup-tip-container"? 

My goal is to  just close the popup and stop event propagation on map,  or just  handle the event as if the click were in "leaflet-popup-content-wrapper" (i.e. in general, do nothing).

Any suggestion is appreciated, thanks!

**Comment by yohanboniface** [comment]
Hi, great to hear that you use Leaflet!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

**Comment by eliboni** [comment]
you're right, let me open what I belive is a bug related to this
