### ISSUE TITLE
maxBounds are not enforced when zooming in using the mouse wheel

### ISSUE THREAD

**Issue by a1an77** [Leaflet/Leaflet#4595]
Steps to reproduce:

1 - define a bounding area small enough to be zoomed out to show 'outside borders', that is areas outside the bounding area get shown since the bounded area is too small to fit on the map.
2 - Zoom out enough to show such outside areas
3 - Put the mouse pointer over such an area (as far away as possible from the bounds)
4 - Zoom in using the mouse wheel

If you zoom in enough the area inside the bounds will be 'pushed' outside by the visible area

**Comment by IvanSanchez** [comment]
Leaflet version?

**Comment by a1an77** [comment]
v1.0.0-beta.2 
I saw no trace of related issues so it might affect the rc as well

**Comment by IvanSanchez** [comment]
@a1an77 Please confirm the issue is still reproducible in rc1, maybe there were some changes that affected that behaviour.

**Comment by a1an77** [comment]
Confirmed, just tried with the rc.1

I noticed the enforcement has been improved on drag but still the problem on zoom by mouse wheel persists.

**Comment by jwoyame** [comment]
Maybe I don't understand the issue, but I was able to use maxBounds with no zoom issues on Leaflet `1.0.0-rc.1 (6ea195a)`. Can you provide some code / a demo to reproduce?

**Comment by IvanSanchez** [comment]
I'm unable to reproduce (see http://playground-leaflet.rhcloud.com/zat/edit?html,output - I'm zoom-scrolling in and out outside the bounds, it works as expected).

**Comment by a1an77** [comment]
You are right, it cannot be reproduced. After deeper investigation it turned out to be a  buffer issue: the feature bounds were getting a too wide buffer before being set as maxBounds! Thanks
