### ISSUE TITLE
Click on leaflet-popup-tip-container propagates on map and not on underlying object

### ISSUE THREAD

**Issue by eliboni** [Leaflet/Leaflet#4596]
I've an app that creates a circleMarker at the very point where the user clicks on.
A popup is bind to the circleMarker
When clicking on the circleMarker the popup opens (with the tail pointing in the circle, exactly at where the user clicked). And that's good.

Now, with the popup opened, by clicking again **within the very same circleMarker area** there is an unpredictable behaviour:
1. if the pointer is on on popup tail or at its left/right (i.e. on  leaflet-popup-tip-container) the popup closes but  the event is then propagated to the map: another circleMarker is created.
2. if the pointer is just below  leaflet-popup-tip-container, the popup closes and reopens .

No.2 would be the expected behaviour since the click is anyway within the original circlemarker. 
I tried to add an extra on click event on the circleMarker but I still get behaviour no.1, i.e. the click goes to the map and not on the object. 

Using leaflet 0.7.7

**Comment by eliboni** [comment]
note, what I described looks like what is mentioned in the "a side note" section of #2880

**Comment by jwoyame** [comment]
Looks like this issue can be closed now?

**Comment by johnd0e** [comment]
It looks that the issue is still the case in 1.70..
