### ISSUE TITLE
How do I set a diagonal hatch style when using canvas mode?

### ISSUE THREAD

**Issue by atdiff** [Leaflet/Leaflet#4598]
In my project I have to have `L_PREFER_CANVAS = true` to allow leaflet-image.  On my maps, I'm styling a layer with an option of `fillColor: 'url(#diagonalHatch)'`.  This works great when I don't have L_PREFER_CANVAS, but I need that set for leaflet-image.  When I have it as true, that styled area on the map layer becomes solid black with no styling.  Is there an alternative way to get a diagonal hatch styling or something similar?
Original:
![hatch](https://cloud.githubusercontent.com/assets/16138266/15557148/16b9672c-2297-11e6-9994-4b2cb52e0e97.png)

Using canvas:
![canvas](https://cloud.githubusercontent.com/assets/16138266/15557150/184a91ec-2297-11e6-8f25-eb00eabcfa11.png)

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

**Comment by atdiff** [comment]
@IvanSanchez , you could consider it a bug then - cause it's not working with fillColor and having L_PREFER_CANVAS = true set.  I can open a new issue if that's preferred.

**Comment by IvanSanchez** [comment]
I don't consider it a bug, as the documentation doesn't say anywhere that you can use `fillColor` to use a pattern.

Feel free to open a new issue for a feature request (and this time please avoid language such as "In my project I *need* to have" or "How can I do...?").

It is certainly doable, as the documentation for [`CanvasRenderingContext2D.fillStyle`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/fillStyle) allows for instances of `CanvasPattern` to be used. If and how to implement that (and whether we want to have that in the leaflet core, and how to deal with the asynchrony of loading images, and how to deal with CORS exceptions) should be up for discussion in the feature request. And obviously pull requests would be welcome.

**Comment by atdiff** [comment]
@IvanSanchez, I think this must be a matter of semantics with the definition of "bug" then.  The documentation just says it can use a string, so it's fairly ambiguous in that sense.  If the code allows it's usage and responds correctly, but then doesn't in some circumstances, that sounds like the definition of a bug to me...

Ultimately I just want to know ways to get that sort of styling when using the mode of canvas.
