### ISSUE TITLE
Leaflet 0.7.7 quick start not working in 1.0.0-rc.1

### ISSUE THREAD

**Issue by jwoyame** [Leaflet/Leaflet#4602]
The problem
---
When there is a click event registered for the map itself to show a popup, popups no longer work on child layers.

The cause
---
Clicks are being propagated to the map even when handled by the layer's popup. Although the layer's handler runs, the popup is instantly replaced by the map's own popup.

How to reproduce
---
Compare the quick start:
http://leafletjs.com/examples/quick-start-example.html

With this `v1.0.0-rc.1` demo:
http://jsbin.com/novoxeturi/edit?html,output

This occurs in master as well, I submitted a demo for it (#4601).

**Comment by af7** [comment]
Did something change on click events? It appears that a click event on a "rectangle" does not fire at all. No popup exists on the map. We just want the rectangle to be clicked upon and fire an event, but this does not work anymore. Did anything change and created a regression?
