### ISSUE TITLE
Switch Leaflet coordinates to where 0,0 is southwest?

### ISSUE THREAD

**Issue by railsdevmatt** [Leaflet/Leaflet#4607]
I am working on a leaflet project where I need the coordinates 0 to 4096 and which the leaflet coordinates that I need are the following:

    0,0 bottom left (southWest)
    0,4096' top left (northWest)
    4096',4096' top right (northEast)
    4096',0 bottom right (southEast)

I have tried many things to get the coordinates to map as needed but no luck. Here is my [jsfiddle][1] with my example, which has a console.log when you click on the map which shows the coordinates. If you click in the top left you will see its 0,0 and if you click in the bottom right you will see 4096,4096 which is backwards from whats needed. Here is my code that I have

    url = 'http://{s}.tile.osm.org/{z}/{x}/{y}.png';
    weight = 4096;
    height = 4096;
    mapMinZoom = 1;
    mapMaxZoom = 7;
    map = L.map('map', {
      maxZoom: mapMaxZoom,
      minZoom: mapMinZoom,
      noWrap: true,
      detectRetina: true
    });
    unproject = function(coord) {
      return map.unproject(coord, 4);
    };

    southWest = unproject([0, 0]);
    northEast = unproject([height, weight]);
    map.setMaxBounds(new L.LatLngBounds(southWest, northEast));
    tileLayer = L.tileLayer(url, {
      minZoom: mapMinZoom,
      maxZoom: mapMaxZoom,
      noWrap: true,
      tileSize: 256,
      detectRetina: false
    }).addTo(map);

    map.setView(unproject([0, 0]), 2);

    map.on('click', function(e) {
      var coords, latLong;
      latLong = new L.LatLng(e.latlng.lat, e.latlng.lng);
      coords = map.project(latLong, 4);
      console.log("x="+coords.x+", y="+coords.y);
    });

  [1]: http://jsfiddle.net/d2y5qg1d/6/

**Comment by danzel** [comment]
I think you need to override the CRS
https://github.com/Leaflet/Leaflet/blob/master/src/geo/crs/CRS.Simple.js

Also this is more of a question than a feature request/bug, so is better suited to stackexchange.
