### ISSUE TITLE
tiles don't load correctly with ngDialog

### ISSUE THREAD

**Issue by grimace** [Leaflet/Leaflet#4611]
I can't seem to get the tiles to live inside of the map container.  Is there some trick to this.  I'm using angular and have tried both with leaflet-directive and without.  I've tried timeout map.invalidateSize(), but nothing I tried seems to work. Here's an example of what shows.

![leaflet-ngdialog](https://cloud.githubusercontent.com/assets/33261/15683467/9107db88-2717-11e6-8a77-887c49e87538.png)

**Comment by yohanboniface** [comment]
Hi, great to hear that you use Leaflet!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
