### ISSUE TITLE
Plan for animated bounce markers?

### ISSUE THREAD

**Issue by SuberFu** [Leaflet/Leaflet#4612]
Is there plan for animating bounce marker and/or a standardized API for bounce markers?
I'm asking this because I'm working on a vector-icon based marker that want to provide an animation that shows the marker bouncing (with the shadow moving in the correct direction relative to its skewness to simulate an actual shadow cast against the marker).

I want to know if there some recommended function name I should use on the icon to allow it to set the "floating offset" of the marker and shadow?

Currently, I'm thinking of having L.Icon and derived icons implement a `setFloat(offset, icon, shadow)` method. The `setFloat` function would offset the icon and shadow per their desired behavior. Or `getIconFloatOffset(offset)` and `getShadowFloatOffset(offset)` to have the L.Marker class handle the repositioning of the icon/shadow element per the `get*FloatOffset` result.

**Comment by SuberFu** [comment]
P.S. Currently I've a workaround implementation in my L.Icon derived object that when I create the div element for the icon and shadow, I save a reference to it in the icon itself. That way, when I can invoke `marker.options.icon.setFloat(offset)`, which in turn offsets the saved div icon references. Is it relatively safe to do so?

**Comment by jwoyame** [comment]
I would say that bouncing markers are better handled in a plugin than in the core Leaflet code, in fact there are at least [two](https://github.com/hosuaby/Leaflet.SmoothMarkerBouncing) plugins [already](https://github.com/maximeh/leaflet.bouncemarker) for bouncing markers. I've done it myself just using a simple [CSS animation](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Animations/Using_CSS_animations) with no JavaScript. The offset of the icon and shadow are just CSS styles. Questions about Leaflet can be answered at http://gis.stackexchange.com/.

**Comment by IvanSanchez** [comment]
Yeah, this is covered by [some plugins](http://leafletjs.com/plugins.html#overlay-animations) and there's no need to have this in the core.
