### ISSUE TITLE
Gridlayer's outer edge snapping to vertical center of map

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#4617]
How to reproduce:
* Have a tall map container
* Init a map with a low zoom level (0, 1)
* Drag the map up/down
* When the center of the map is a point outside the [-85, 85] latitude range, the tiles will snap out of alignment

Any other non-gridlayer layers will be positioned properly. This is also reproducible at any other zoom level, if dragging the map near the polar regions.

Playground here: http://playground-leaflet.rhcloud.com/febi/edit?html,output

**Comment by mourner** [comment]
This would be nice to fix sooner, but I don't think it's a blocker — most map apps remain functional since they never pan past the 85 on the map center.

**Comment by hyperknot** [comment]
It's not related to zoom 0, it is happening on all zoom levels. Tilelayers are snapping to vertical center of the map while the others are moving. Checked on playground beta1 was ok, since beta2 it is buggy.

**Comment by hyperknot** [comment]
Git bisect gave 7098b04c
