### ISSUE TITLE
control.layers doesn't redraw layer without changing zoom (1.0.0-rc.1; Chrome 51.0.2704.79 and FF 46.0.1)

### ISSUE THREAD

**Issue by Guerillero** [Leaflet/Leaflet#4622]
Thank you all for maintaining and expanding this wonderful product. I will admit that I am using ESRI's Leaflet plugin to generate my layers so this might be an upstream error.

I have a map with several large layers. They are all controlled via control.layers and are not added to the map automatically. If I turn a layer on it shows up like it supposed to. However, when I turn that layer off and then on again, it does not show up. The only way I can get the layer to redraw is to zoom out which triggers a redraw of the map.

If this isn't a vanilla leaflet issue, would it be possible to get a `map.redraw()` method that just redraws everything currently on the map at the same zoom and center point? Something like that would fix my issue and I can see it being useful for others. 

thanks!

**Comment by jieter** [comment]
Can you create an example of the problem? I tried in the playground below, but the layer shows up every time.

http://playground-leaflet.rhcloud.com/rof/2/edit?html,console,output

**Comment by nathancahill** [comment]
Also see `map.invalidateSize()` to redraw the map.

**Comment by Guerillero** [comment]
@jieter I will see what I can do.The data that I am using can't be used on the internet due to NDAs and such. I will see if I can draw upon a dummy dataset. It could just have to do with using too much memory.

@nathancahill I will look into that. Thanks!

**Comment by IvanSanchez** [comment]
@Guerillero What kind of data are you trying to display? Are you using some dynamic layers from the esri plugin maybe?

**Comment by Guerillero** [comment]
@IvanSanchez Yes, I am using several dynamic layers using the ESRI plugin and my organization's ArcsServer.

**Comment by Guerillero** [comment]
ESRI Leaflet issue. Thanks for the help
