### ISSUE TITLE
Latest Google Chrome update (51.0.2704.79) breaks Leaflet (1.0.0-rc.1)

### ISSUE THREAD

**Issue by bshenk** [Leaflet/Leaflet#4626]
I have an application that uses the Leaflet library and was working fine this past Friday. I fire up the app this morning and it's now showing a blank grey screen. I noticed that it was still working in Safari, but broken on Chrome and Firefox. I contacted a co-worker who confirmed the bug on his end as well. I then went to a second co-worker who had the map still working and I checked what version of Google Chrome he was on - version 50-something. After he updated, the map broke for him as well.

**Comment by hyperknot** [comment]
@bshenk 
1. What version of Leaflet are you using?
2. You said "broken on Chrome and Firefox", while you only updated Chrome, are you sure there was no configuration change on your side?

**Comment by yohanboniface** [comment]
>  1. What version of Leaflet are you using?

The title seems to indicate latest rc ;)

@bshenk many things can ends to an app being broken, so it may or may not be Leaflet itself, but any of the code running Leaflet or a dependency. Without more information it will be hard for us to be of any help.
Try to narrow the issue in a fiddle (http://playground-leaflet.rhcloud.com/), try to load the Leaflet map on http://leafletjs.com, etc.

**Comment by bshenk** [comment]
False alarm - for some reason, the update to Chrome caused one of my div's to require an extra CSS rule in order to show its sibling, the map.
