### ISSUE TITLE
GeoJSON.addData not in 1.0 docs

### ISSUE THREAD

**Issue by neothemachine** [Leaflet/Leaflet#4630]
The addData method is missing in the 1.0 docs.

**Comment by IvanSanchez** [comment]
Looks like a simple job of looking at the [old description from the 0.7.x docs](http://leafletjs.com/reference.html#geojson-adddata), and adding leafdoc-style docstrings to [`src/layer/geojson.js`](https://github.com/Leaflet/Leaflet/blob/master/src/layer/GeoJSON.js#L79). Actually, seems like the `setStyle` and `resetStyle` methods are also undocumented.

I'll let this up for grabs (ping @yourfirstpr) - if anybody wants to work on this, be sure to read the tutorials on making a pull request, and the part about "API documentation" in Leaflet's CONTRIBUTING.md file.
