### ISSUE TITLE
webkitMovementX Deprecation notice

### ISSUE THREAD

**Issue by gsouf** [Leaflet/Leaflet#4634]
Got 2 deprecation notices from **chromium Version 48.0.2564.82** in **leaflet 1.0.0-rc1**:

`'webkitMovementX' is deprecated. Please use 'movementX' instead.`
`'webkitMovementY' is deprecated. Please use 'movementY' instead.`

**Comment by IvanSanchez** [comment]
Duplicate of https://github.com/Leaflet/Leaflet/issues/3943. Please search existing bug reports before submitting a new one.

**Comment by gsouf** [comment]
I searched for [webkitMovementY](https://github.com/Leaflet/Leaflet/issues?q=is%3Aissue+webkitMovementY+is%3Aclosed) and it did not return result :)
