### ISSUE TITLE
Popup sizing broken in 1.0rc1

### ISSUE THREAD

**Issue by neothemachine** [Leaflet/Leaflet#4640]
0.7: http://jsfiddle.net/n6f7hk4t/
1.0rc1: http://jsfiddle.net/5dsac2bm/

What's going on here?

**Comment by jwoyame** [comment]
Hi @neothemachine, this is a duplicate of #4575. There is a fix #4597 that is awaiting review/comment.

**Comment by nathancahill** [comment]
Closing as duplicate.
