### ISSUE TITLE
Invalid out-of-bounds tiles are requested from the server when noWrap and bounds are set

### ISSUE THREAD

**Issue by joanrieu** [Leaflet/Leaflet#4646]
**Symptom**

Invalid out-of-bounds tiles are requested from the server, resulting in 404 errors in the console and the default *image-couldn't-be-loaded* rectangles being displayed instead of no tiles.

--

**Trigger**

This problem happens when a layer has both the `noWrap` and the `bounds` options.

--

**Visual comparison**

The layers are defined with `noWrap: true` and `bounds: [[-90, -180], [90, 180]]`. Incorrect behavior on the left, fixed one on the right.

![Visual comparison](http://i.imgur.com/ZfKoug5.png)

--

**Bug**

The following function located inside `GridLayer` does not respect the `noWrap` option: `map.wrapLatLng(...)` is always called.

```javascript
_tileCoordsToBounds: function (coords) {

	// ...

	nw = map.wrapLatLng(map.unproject(nwPoint, coords.z)),
	se = map.wrapLatLng(map.unproject(sePoint, coords.z));

	return new L.LatLngBounds(nw, se);
},
```

--

**Fix**

If the `noWrap` option is set on the layer, `map.wrapLatLng` *should not* be called.

--

**Explanation**

The `_tileCoordsToBounds(...)` function is called by `_isValidTile(...)`, which relies on it to validate a tile by checking that it is in the user-defined bounds (if any), as seen below.

```javascript
_isValidTile: function (coords) {

	// ...

	if (!this.options.bounds) { return true; }

	// don't load tile if it doesn't intersect the bounds in options
	var tileBounds = this._tileCoordsToBounds(coords);
	return L.latLngBounds(this.options.bounds).overlaps(tileBounds);
},
```

--

**Workaround** (until a fix is released)

You can patch the `layer._tileCoordsToBounds` function on your layers, changing the offending call.

--

**Version**

I am facing this bug in version `v1.0.0-rc.1` and the few changes to this file in `master` are completely unrelated.

**Comment by joanrieu** [comment]
Related issues I found while tracking down the bug:
- Leaflet tries to get negative value images or images that don't exist #2981
- noWrap not working mstahv/v-leaflet#103

**Comment by fyeah** [comment]
Thank you for discovering all this. Still took me a long time to get to work. If anyone else needs a quick fix for this see #4738 
I hope it get's fixed soon.

**Comment by kaynz** [comment]
Is this somehow related to #2390?

**Comment by JoshQuake** [comment]
Still not sure how to fix this. I have 
```
var map = L.map('map').setView([0,0], 2);

L.tileLayer('images/map/{z}/{x}/{y}.png', {
	minZoom: 1,
	maxZoom: 4,
	center: [0,0],
	noWrap: true,
	crs: L.CRS.Simple
}).addTo(map);

var southWest = map.unproject([0, 4096], map.getMaxZoom());
var northEast = map.unproject([4096, 0], map.getMaxZoom());
map.setMaxBounds(new L.LatLngBounds(southWest, northEast));
```

**Comment by IvanSanchez** [comment]
@JoshQuake `noWrap` only has an effect then the map's CRS is wrapping, so the behaviour of your code is unrelated to this bug.

**Comment by JoshQuake** [comment]
@IvanSanchez How do I stop leaflet from trying to load tiles that don't exist to the left and right of max bounds then? Thought it had to do with this issue. I also need to set 0,0 to be the top left, hopefully that's possible.

**Comment by IvanSanchez** [comment]
@JoshQuake this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

**Comment by JoshQuake** [comment]
Deleted my comments. Unrelated to bug.
