### ISSUE TITLE
Popup Mouse Event Does not work

### ISSUE THREAD

**Issue by ekfliu** [Leaflet/Leaflet#4652]
```
marker_popup = new L.popup().setLatLng(over.latlng).setContent('<ul class="map_marker">'+meta_text+'</ul>').openOn(leaflet_map);	            					
marker_popup.on('click', function (e) {
	console.log('popup clicked', e);
});	            					
marker_popup.on('mouseover', function (e) {
	console.log('popup mouseover', e);
});
marker_popup.on('mouseout', function (out) {
	console.log('mouseout', out)
});
```

These mouse events never gets called, when moving or clicking on the popup itself

**Comment by yohanboniface** [comment]
Try something like `L.DomEvent.on(marker_popup._container, 'click', function () {…}).`

**Comment by af7** [comment]
Did something change on click events? It appears that a click event on a "rectangle" does not fire at all.

**Comment by yohanboniface** [comment]
If you intend to submit an issue, please open a new one with a jsfiddle reproducing.
