### ISSUE TITLE
The setLatLngs() method of class Polyline cannot work as same as its description in Docs.

### ISSUE THREAD

**Issue by zhuyunji** [Leaflet/Leaflet#4656]
As is recorded in the documentation of Leaflet v0.7 and 1.0.0-rc1, the setLatLngs() method of class Polyline replaces all the points in the polyline with the given array of geographical points. Howerver, practically, this method does not replace all the points but add the new points at the end of the array of geographical points. The points cannot be totally updated in Polyline. In addtion, there is no method that can clear all the points in Polyline. As a result, it is difficult to change the geographical points of a polyline which has been drawn on map.

**Comment by yohanboniface** [comment]
I think you are doing a mistake somewhere. `setLatLngs` is actually replacing all the latlngs of a Polyline: https://github.com/Leaflet/Leaflet/blob/master/src/layer/vector/Polyline.js#L161
Check again your code, or create a jsfiddle that demonstrate a bug.
