### ISSUE TITLE
map animation from one point to another

### ISSUE THREAD

**Issue by Alphatiger** [Leaflet/Leaflet#4657]
I want map and markers  to change from one point to another the code is
 
The below is for markers which is making the marker move correctly
Lmarker.setLatLng([locallat,locallong]);
circlemark.setLatLng([locallat,locallong]);
circlemark.setRadius(rad);

for map
map.set view([lat,long],16,{animate:true})
The above piece of code is not working as per my assumption, if the given point lies in the same view port it doesn't pan, if it is outside then map should pan

Problem is the map is not moving at  all, and the marker is going out of the view.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

**Comment by Alphatiger** [comment]
ok thanks
