### ISSUE TITLE
mousedown mouseup does not fire on Chrome running on Android

### ISSUE THREAD

**Issue by timdinhdotcom** [Leaflet/Leaflet#4659]
As the title said, the mousedown and mouseup event doesn't get fire when running on Chrome in Android. see minimum demo attached
[leaflet_events.zip](https://github.com/Leaflet/Leaflet/files/326887/leaflet_events.zip)

**Comment by yohanboniface** [comment]
Can you please set up a very minimal example reproducing the issue with http://playground-leaflet.rhcloud.com/ ?

**Comment by timdinhdotcom** [comment]
Sorry for the late response but i'm unable to reproduce the issue now. 
The newer chrome version must have resolve the issue
