### ISSUE TITLE
tile white line appear when zoom the map  using Leaflet 1.0.0-rc1 in my Mac Pro,  but the Leaflet 0.7.7 not

### ISSUE THREAD

**Issue by kocokolo** [Leaflet/Leaflet#4660]
**Leaflet 0.7.7 DEMO:**
    link rel="stylesheet" href="https://rawgit.com/Leaflet/Leaflet/stable/dist/leaflet.css" 
    script type="text/javascript" src="https://rawgit.com/Leaflet/Leaflet/stable/build/deps.js"
    script src="https://rawgit.com/Leaflet/Leaflet/stable/debug/leaflet-include.js"
    script src="http://api.map.baidu.com/api?v=1.5&ak=Gt0BG62R7T5GDvuPSj65MBl4"
    script src="http://wsw0108.github.io/leaflet-baidu/layer/tile/leaflet-baidu.js"
   
   div style="width:1008px; height:520px" id="map"

    var map = new L.map(
            'map',
            {
                'crs': L.CRS.BEPSG3857
            }
    );
    map.setView([39.91, 116.404], 5);
    var baiduLayer = new L.TileLayer.BaiduLayer("Satellite.Map");
    map.addLayer(baiduLayer);

------------
**Leaflet 1.0.0-rc1 DEMO:**

    link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet/v1.0.0-rc.1/leaflet.css"
    script src="http://cdn.leafletjs.com/leaflet/v1.0.0-rc.1/leaflet.js"
    
    script src="http://api.map.baidu.com/api?v=1.5&ak=Gt0BG62R7T5GDvuPSj65MBl4"
    script src="http://wsw0108.github.io/leaflet-baidu/layer/tile/leaflet-baidu.js"

div style="width:1008px; height:520px" id="map" 

    var map = new L.map(
            'map',
            {
                'crs': L.CRS.BEPSG3857
            }
    );
    map.setView([39.91, 116.404], 5);
    var baiduLayer = new L.TileLayer.BaiduLayer("Satellite.Map");
    map.addLayer(baiduLayer);

--
thank you

**Comment by yohanboniface** [comment]
Thanks for the report!
However an online demo would be more convenient than a pasted code. You can use http://playground-leaflet.rhcloud.com/ for example.
Thanks!

**Comment by kocokolo** [comment]
okay 

thank you

**Comment by IvanSanchez** [comment]
Make sure this is not a duplicate of either https://github.com/Leaflet/Leaflet/issues/4637 or https://github.com/Leaflet/Leaflet/issues/3575
