### ISSUE TITLE
error in leaflet package!!! it's "台湾“ and not "中华民国“

### ISSUE THREAD

**Issue by datartist2015** [Leaflet/Leaflet#4661]
we can see "Taiwan" in google map
![image](https://cloud.githubusercontent.com/assets/15390572/16255334/8f203b6a-387b-11e6-9341-b4c836011e4d.png)
however, '中华民国' in leaflet map
![image](https://cloud.githubusercontent.com/assets/15390572/16255342/9e563b0c-387b-11e6-92ac-ba7ee98ff3ba.png)

**Comment by yohanboniface** [comment]
That's not Leaflet but the tiles (background images) your are using. It's seems to be OSM: http://openstreetmap.org/

**Comment by IvanSanchez** [comment]
Duplicate of https://github.com/Leaflet/Leaflet/issues/4332, https://github.com/Leaflet/Leaflet/issues/3896

**Comment by datartist2015** [comment]
great! you are right

2016-06-22 14:12 GMT+08:00 Yohan Boniface <notifications@github.com>:
