### ISSUE TITLE
revisit CDN issue because GitHub Pages now enforces https

### ISSUE THREAD

**Issue by JackDougherty** [Leaflet/Leaflet#4666]
I realize that https CDN issues have been discussed in the past (https://github.com/Leaflet/Leaflet/issues/4080), but it may be time to revisit Leaflet documentation on this topic.

Last week, [GitHub Pages began to enforce https](https://help.github.com/articles/securing-your-github-pages-site-with-https/). This means that anyone who follows the [current Leaflet documentation on "Using a Hosted Version"](http://leafletjs.com/download.html) will encounter errors when hosting on GitHub Pages, as I recently discovered. Not fun.

I saw @Mourner state his preference for NPMCDN, but at present it only supports Leaflet 0.7.7, and none of the newer versions: https://npmcdn.com/leaflet/

Whether the Leaflet team decides to update NPMCDN, or point us to [CDNJS](https://cdnjs.com/libraries/leaflet/1.0.0-rc.1) or somewhere else, I encourage you to revise the documentation.  Thanks.

**Comment by mourner** [comment]
@JackDougherty that's a valid concern, I think we should replace the links with NPMCDN ones. All recent versions like `1.0.0-rc.1` should be present there as well since they're released on NPM too.

**Comment by JackDougherty** [comment]
According to NPMCDN docs, this link should show all Leaflet contents
https://npmcdn.com/leaflet/

But only 0.7.7 appears there.

**Comment by mourner** [comment]
@JackDougherty it's probably because 1.0.0-rc.1 doesn't have a "latest" tag in NPM. But files are accessible, e.g. https://npmcdn.com/leaflet@1.0.0-rc.1/dist/leaflet.js

**Comment by yohanboniface** [comment]
Fixed with #4679
