### ISSUE TITLE
USA state wise zipcode level map

### ISSUE THREAD

**Issue by SrinuvasuL** [Leaflet/Leaflet#4670]
Please provide USA state wise zipcode level map

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
