### ISSUE TITLE
Mouse Events Regression for IE10 in 1.0-rc1

### ISSUE THREAD

**Issue by nitehawk42** [Leaflet/Leaflet#4674]
I am unable to get any GeoJSON layer-specific mouse events to fire in IE10 in 1.0-rc1. These work correctly in 0.7.7. This works fine in IE11, Edge, and the latest Chrome and Firefox.

When I use the debugger to capture the mouse event, what I find is in `_handleDOMEvent`,` e.target` is referencing the tile layer instead of the GeoJSON layer that is on top of the tiles. The result is that no mouse events reach the GeoJSON layers.

Perhaps there is a workaround or a different way to handle events that fixes this. (Tested against the modern.ie Win7/IE10 VM)

1.0-rc1: (Broken in IE10)
https://jsfiddle.net/nitehawk123/p8xqm2sr/19/

0.7.7: (Working in IE10)
https://jsfiddle.net/nitehawk123/xtqrkc3q/4/

Here is an alternate way to handle the mouse events that results in the same problem:
https://jsfiddle.net/nitehawk123/9o04nxh2/

**Comment by IvanSanchez** [comment]
@yohanboniface Maybe this is related to event bubbling?

**Comment by nitehawk42** [comment]
@IvanSanchez I would not be surprised if this is the case. I think one of the issues is that with the new pane support in 1.0 (which I was trying to take advantage of)  and IE10 does not support `pointer-events: none` which may cause the problem. But I am not well versed enough to know for sure.

https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events

**Comment by yohanboniface** [comment]
Missing an IE10 at hand to test.
@nitehawk42 can you check with beta1 and beta2 (use http://playground-leaflet.rhcloud.com/ten/edit?html,output so you can easily toggle from a Leaflet version to another) ?

**Comment by nitehawk42** [comment]
Thanks for that link, it makes it much easier to work with. This works in both beta1 and beta2 on IE10/Win7. Interesting.

**Comment by yohanboniface** [comment]
> This works in both beta1 and beta2 on IE10/Win7

Worth a `git bisect` then. Are you able to do that?

**Comment by nitehawk42** [comment]
Yeah, I think I can figure it out. Let me get back to you with a specific revision.

**Comment by yohanboniface** [comment]
> Though I will have to figure out how to build Leaflet from source and run it in my application.

`npm install && npm build` and then look at dist/ :)

**Comment by mourner** [comment]
Looks like a serious bug so let's prioritize this for rc2.

**Comment by nitehawk42** [comment]
Here is the result from bisect. What is a non-interactive marker?

commit 0cfe85897fef257d952d1cec5a5a11005fa66da0
Author: Iván Sánchez Ortega <ivan@sanchezortega.es>
Date:   Sat Apr 2 19:33:02 2016 +0200
    Make non-interactive markers not fire pointer events
    * Make non-interactive markers not fire pointer events, fixes #3936
    * Make non-interactive image overlays and SVGs not fire pointer events
    * Make gridlayers non-interactive, fixing #2396 too.

Also, bisect is freaking awesome, I have never used it before. :)

**Comment by IvanSanchez** [comment]
> What is a non-interactive marker?

A marker instantiated with the `interactive: false` option, which does absolutely nothing when you click on it.

I'll see if I can spare some time to have a look at this in a IE10 VM.

**Comment by yohanboniface** [comment]
> Anyhow, it seems to rely on pointer-events to work, which IE10 does not support.

MSDN seems to say `pointer-events` are IE9 on: https://msdn.microsoft.com/en-us/library/ff972269(v=vs.85).aspx

**Comment by perliedman** [comment]
According to the MSDN page linked by @yohanboniface, `pointer-events` in IE doesn't support the setting `auto`. Before 0cfe85897fef257d952d1cec5a5a11005fa66da0, we used the setting `visiblePainted`, which is supported by IE, but then switched to `auto`. I guess that's the breaking change.

So, question is: can we just use `visiblePainted`?
