### ISSUE TITLE
Marker has wrong position

### ISSUE THREAD

**Issue by danielreiser** [Leaflet/Leaflet#4675]
Hey guys,

nearly everything is working as expected. I am feeding a geojson file with the correct coodinates (15 decimals). Leaflet renders the markers with only the precision of 11 decimals.

Anyway of fixing that?

Help is much appreciated :)

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by mourner** [comment]
Just FYI: 
![](http://support.oxts.com/wp-content/uploads/2014/04/Image.png)

@IvanSanchez is one chromosome precision good enough? I'm not sure...

**Comment by snkashis** [comment]
Given @mourner's helpful chart, I would probably suggest this issue be closed. @danielreiser what input source are you using for 15 decimal places? Even if the 15 decimal places were all legitimately generated, how would we ever represent that level inside today's web browsers?

**Comment by IvanSanchez** [comment]
So Javascript will always try to use 64-bit floating point numbers (https://blog.mozilla.org/javascript/2013/11/07/efficient-float32-arithmetic-in-javascript/), the kind with 15-16 digits of precision.

On the other hand, this *might* be an architecture-dependent bug. While in practice everybody uses 64-bit processors to run modern browsers nowadays, in theory there should be a platform+browser+code combination which triggers this bug.

However, until that combination is shown in front of me, I'll close this.
