### ISSUE TITLE
GeoJSON polygon click events don't bubble through to CircleMarker Points

### ISSUE THREAD

**Issue by MuellerMatthew** [Leaflet/Leaflet#4676]
When there is a geojson polygon layer above a circlemarker point, the click event on the polygon layer does not bubble through to the circlemarker, although it bubbles through to a regular marker.

Here is a demo in the playground which highlights this issue:
http://playground-leaflet.rhcloud.com/buyo/edit?html,output

I added a layer control to allow you to toggle different types of layers.  If you toggle the regular markers and toggle the polygon layer above them their popups still show when clicked, but if you do the same for the circlemarker layer with the polygon layer above it then the popups don't work.

**Comment by yohanboniface** [comment]
The circle markers are *below* the polygon, while the regular ones are *above* (that's Leaflet default to put Markers above vectors).
So unless the polygon as `interactive: false` I think is normal DOM behaviour not to forward events to an element that is covered.
