### ISSUE TITLE
Mobile: Can't continue scrolling when a map occupy all the screen

### ISSUE THREAD

**Issue by wsenjer** [Leaflet/Leaflet#4677]
Hello, 

We have an issue on mobile which is the user can't keep scrolling if the there is a map on the page and it occupies the whole screen. 

Here is the code:
```
// center of the map
var center = [-33.8650, 151.2094];

// Create the map
var map = L.map('map').setView(center, 3);

// Set up the OSM layer
L.tileLayer(
  'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    maxZoom: 18
  }).addTo(map);

// add a marker in the given location
L.marker(center).addTo(map);
map.dragging.disable();
map.tap.enable();
```

And here is a jsfiddle: 
https://jsfiddle.net/x5p2nLrs/23/embedded/result/#Result

Can you please let me know If I'm missing something? Also, the issue happens on the demo website of leafletjs.

**Comment by yohanboniface** [comment]
You can't both scroll the map AND the page. Try disabling scroll: http://leafletjs.com/reference-1.0.0.html#map-scrollwheelzoom

BTW, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
