### ISSUE TITLE
Most Path-specific events are missing in 1.0.0 docs (but they are present in 0.7.X)

### ISSUE THREAD

**Issue by burmisov** [Leaflet/Leaflet#4681]
In [1.0.0 docs for Path](http://leafletjs.com/reference-1.0.0.html#path) there are no `click`, `mouseover` etc. events listed, though they are supported. Same for Polyline, Polygon etc. One can't infer that this events are present from class inheritance either, they are nowhere to be found.

[0.7.x docs for Path](http://leafletjs.com/reference.html#path) state them clear and its obvious that they are inherited by Polygon, Polyline etc.

**Comment by IvanSanchez** [comment]
Duplicate of #4583, already fixed in `master` by #4585
