### ISSUE TITLE
Popup is misplaced when setting zoomAnimation to false in PopupOption

### ISSUE THREAD

**Issue by fnicollet** [Leaflet/Leaflet#4685]
Hello,

Here is an issue that can be reproduced in master and RC1. Add a marker, bind a popup with zoomAnimation option as false and zoom in or out. The popup is misplaced:
https://playground-leaflet.rhcloud.com/bemi/1/edit?html,output

**Comment by hyperknot** [comment]
If both map and marker is zoomAnimation: false, the bug is not present.

So the problem might actually be that how can a marker be non-zoom animated while the map is? Maybe we should just override one with the other?

**Comment by hyperknot** [comment]
This is what seems to happen in beta1: if map is zoom animated then the popup is zoom animated as well, no matter what option is passed.

**Comment by fnicollet** [comment]
The test could be changed to a test on the map's option in https://github.com/Leaflet/Leaflet/blob/master/src/layer/Popup.js#L116 but then we might as well remove the zoomAnimation option from the PopupOption code (and docs). Which means that users with Flash content in popups would need to disable animations on the whole map

**Comment by fnicollet** [comment]
Found the original issue in leaflet 0.4 that introduced the zoomAnimation on PopupOption:
https://github.com/Leaflet/Leaflet/issues/999
Seems like a bunch of flash-browser related issues

**Comment by fnicollet** [comment]
Just tried reproducing the issue with flash content inside a popup and zoomAnimation true, seems to work alright (Chrome / IE on Windows):
https://playground-leaflet.rhcloud.com/tani/edit?html,output

Maybe the original issue is now outdated and browsers fixed it?

**Comment by hyperknot** [comment]
Hehe, Flash + zoomAnimation disabled on marker but zoomAnimation enabled on map, I'd call this an edge case of an edge case. Meanwhile Flash is kind of dead, the linked iframe example is Flash-less as well, so I wouldn't worry about it.

Personally, I'd recommend removing zoomAnimation from marker options, as it should be handled on a map level.

**Comment by IvanSanchez** [comment]
@fnicollet Your "flash content" is actually a HTML5 `<video>` tag, so that's why modern browsers don't display the bug.

I do agree that flash is pretty much dead nowadays.

I've made a small change to always reposition popups (#4685), but it's failing a test. I'll debug, then we can push it to rc2 and let people open a bug if flash or whatever fails ever again.

**Comment by fnicollet** [comment]
@IvanSanchez yup, took the examples from the original issue, 3 years ago when Youtube was still flash-only, my bad :)
Why not remove the property altogether? After your commit, it is only used in "true" cases, so no point keeping it?

**Comment by IvanSanchez** [comment]
@fnicollet Yeah, removing it altogether might be a better idea. Maybe you can send a PR over the weekend?

**Comment by fnicollet** [comment]
will try, yes

On Fri, Jul 1, 2016 at 5:00 PM, Iván Sánchez Ortega <
notifications@github.com> wrote:

> @fnicollet <https://github.com/fnicollet> Yeah, removing it altogether
> might be a better idea. Maybe you can send a PR over the weekend?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Leaflet/Leaflet/issues/4685#issuecomment-229969438>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABLtoXCbRqm0w4EjQ_RNv201yXDyTPaBks5qRSt3gaJpZM4JAmdK>
> .
>



-- 
Fabien Nicollet
Tel : +33 (0)6 60 54 72 20

**Comment by mourner** [comment]
Seems like a minor issue so moving out ot 1.0-rc2 milestone.

**Comment by fnicollet** [comment]
Added the PR that removes the option and the checks in Popup.js

**Comment by fnicollet** [comment]
A test is failing: https://travis-ci.org/Leaflet/Leaflet/builds/141660040
But I would say that it seems more related to this commit which is already in master: https://github.com/Leaflet/Leaflet/commit/bddfb1168f5ea859181857b5764ba1f16100ddd2
