### ISSUE TITLE
SVG content like marker

### ISSUE THREAD

**Issue by dpineiden** [Leaflet/Leaflet#4700]
Hello
My ask it's about how to insert a svk like a marker, but the text inside, not the url path. That's because i need to change some properties on the interface. There are some example to do that? thanks!

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
