### ISSUE TITLE
L.crs.Simple working only with continuousWorld: true

### ISSUE THREAD

**Issue by Almis90** [Leaflet/Leaflet#4706]
I trying to add custom grid to my map for a game so I needed to use` L.crs.Simple` but if I don't specify `continuousWorld: true` then it's not showing the map. I really want to avoid continuousWorld, can I do anything about it?

http://jsfiddle.net/ts4oyyn0/426/

**Comment by james-brndwgn** [comment]
Just add a bounds to your tileLayer and you will stop seeing the repeated map.

`L.tileLayer(CDB_URL, {
	attribution: ATTR,
	continuousWorld: true,
	noWrap: false,
        bounds: bounds
}).addTo(map);`

**Comment by Almis90** [comment]
That solves my problem, thank you.
