### ISSUE TITLE
Clicking on map marker zooms and recenters inappropriately (Safari only)

### ISSUE THREAD

**Issue by wpalchemist** [Leaflet/Leaflet#4713]
I have a map with a custom image background.  The map has a bunch of markers on it.  When you click on a marker, a pop-up opens.  If the pop-up goes off the edge of the map, the map naturally recenters to keep the pop-up on the screen.  This is all fine and dandy, except in Safari.  In Safari, when you click on the marker, the map zooms way out and pans way off the screen, so it looks like you're just on a blank screen.

Here is a video of the behavior: http://youtu.be/dVsVZZO60is?hd=1

I am using a few extra plugins (Zoomify and Labels), but removing the plugins does not fix the bad behavior.

Here is my code:
```
var map = L.map('camp-half-blood-map', {
            crs: L.CRS.Simple,
        }).setView(new L.LatLng(0,0), 0);

// Fireworks Beach marker
        var beach = L.latLng([ -18, 95 ]);
        L.marker(beach, {icon: goldIcon}).addTo(map)
            .bindLabel('Fireworks Beach', {
                noHide: true,
            })
            .showLabel()
            .bindPopup('<p>Fireworks are a Fourth of July tradition at Camp Half-Blood, and that night is one of the high points of the summer for most campers. It is the time when many older campers ask dates to share their picnic blanket. The beach is also where some deep water training exercises occur, and occasionally the random sea god can be found fishing on the shore.</p>')

var image_dir = assets_directory.camp_half_blood;
        L.tileLayer.zoomify( image_dir, {
            width: 3300,
            height: 2100,
            tolerance: 0.8,
        }).addTo(map);
```

**Comment by yohanboniface** [comment]
@wpalchemist can you set up a jsfiddle with your code reproducing the issue?

http://playground-leaflet.rhcloud.com/ should be a good place for that :)

Thanks!

**Comment by wpalchemist** [comment]
I found what is causing the issue!

If you have this in the CSS:
```
* {
  transition: all 0.2s ease;
}
```
you get strange behavior in Safari.

Example: http://playground-leaflet.rhcloud.com/koq/edit?html,output
Works fine in all other browsers.

In this situation, it's an easy fix to remove that from my CSS.

**Comment by yohanboniface** [comment]
OK, glad you found the bug. :)
Closing here then.

**Comment by wpalchemist** [comment]
Thanks!

**Comment by kaynz** [comment]
@wpalchemist 
Is ` transition: opacity 0.2s linear;` safe to use in Safari?

**Comment by wpalchemist** [comment]
@kaynz Yes, that is safe, although it doesn't do the same thing as the original code.

I realize this issue has been closed, and everything is working fine for me now so I'm happy, but I still think this is probably a bug that ought to be addressed.  `transition: all 0.2s ease;` is a pretty common thing to put in a CSS file, and it makes Safari behave totally differently from all other browsers.
