### ISSUE TITLE
not interactiveable when multiple layers added

### ISSUE THREAD

**Issue by hon** [Leaflet/Leaflet#4718]
Hi, there
  I added two layers to the map. One take charge of draw outlines of some regions, using L.geoJson api, the other one draw some visual information(eg: heatmap) use canvas element. 
  Wanted effect: 
1. When the mouse move over some region, the outline can be highlighted; 
2. When the mouse is over the heatmap, it can be interactive too.

I set the css property to the svg element of outline layer: 

``` css
pointer-event: none;
```

Now the heatmap layer can be interactive, but the outline layer cann't and vice versa.

Is it possible to make both layer interactive at the same time?
Give me some suggestions. 
Thank you.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
