### ISSUE TITLE
fuzzy Popup  under  (Windows 7 Enterprise / Leaflet 0.7.7 / Google Chrome V. 51.0.2704.79 m)

### ISSUE THREAD

**Issue by ricardolle** [Leaflet/Leaflet#4719]
I am seeing as well a fuzzy Popup in leaflet Maps under: Windows 7 Enterprise / Leaflet 0.7.7 / Google Chrome Version 51.0.2704.79 m

![a3put](https://cloud.githubusercontent.com/assets/12683881/16725734/ed26bb76-4758-11e6-87c0-43e899ba6904.png)

Best Regards,

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

And make sure your browser zoom is at 100% (press Ctrl+zero)

**Comment by ricardolle** [comment]
It was about the zoom. 
Thanks
