### ISSUE TITLE
Cannot read property 'reuseTiles' of undefined

### ISSUE THREAD

**Issue by enriquediazmorales** [Leaflet/Leaflet#4720]
Hi Team, I am testing leaflet in Salesforce Lightning Components and getting this issue: Cannot read property 'reuseTiles' of undefined when trying to relocate the MAP using "panTo" function.

I am debugin and the parameters are well and with values ( map.panTo([account.Location__Latitude__s, account.Location__Longitude__s]) but  I am not able to find the issue. Any of you have been facing this issue before in any situation ?  Best Regards,

**Comment by IvanSanchez** [comment]
Sorry, but this bugtracker is for the Leaflet core only. If your problem cannot be reproduced standalone, without using salesforce components, we won't be able to help.

**Comment by altafurrahman** [comment]
@enriquediazmorales, sorry posting reply too late.. if your issue is not yet addressed, i recommend you to install Leaflet latest version and run your code again. this will fix this issue.
