### ISSUE TITLE
MapQuest direct tile access has been discontinued

### ISSUE THREAD

**Issue by bardu** [Leaflet/Leaflet#4723]
As of today July 11, 2016, MapQuest direct tile access has been discontinued.

http://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/

Is there already an API available to add the required API key? Or are we required to use the MapQuest Leaflet plugin from now on?

**Comment by IvanSanchez** [comment]
Not a leaflet bug.
