### ISSUE TITLE
MapQuest basemaps now require AppKey

### ISSUE THREAD

**Issue by tomkralidis** [Leaflet/Leaflet#4724]
As reported in https://github.com/ckan/ckanext-spatial/issues/157, MapQuest tiles now require an AppKey.  It would be valuable to ensure any documentation/examples are updated accordingly.

**Comment by IvanSanchez** [comment]
Duplicate of #4723. The current leaflet website and documentation don't mention MapQuest, except a link to the plugin they provide.

Nothing do be done here.
