### ISSUE TITLE
Question about Control.Zoom event handling

### ISSUE THREAD

**Issue by ValentinH** [Leaflet/Leaflet#4726]
I'm reading some of Leaflet code, especially Control.Zoom.js and I'm wondering where the events listeners bound on the buttons are removed? [These](https://github.com/Leaflet/Leaflet/blob/master/src/control/Control.Zoom.js#L82-L86) are the concerned lines:
```js
L.DomEvent
		    .on(link, 'mousedown dblclick', L.DomEvent.stopPropagation)
		    .on(link, 'click', L.DomEvent.stop)
		    .on(link, 'click', fn, this)
		    .on(link, 'click', this._refocusOnMap, this);
```

Is there a special behavior that automatically removes them when the map is destroyed?

**Comment by IvanSanchez** [comment]
They're not.

The buttons (and the whole control container) is removed from the DOM when the map is destroyed, and all event listeners are garbage-collected shortly afterwards by the browser.

Unless there is a weird memory leak in some weird browser (IE), there is usually no need to remove event listeners before removing the DOM element itself.

**Comment by ValentinH** [comment]
OK thanks for the clarification! :)
