### ISSUE TITLE
iOS 9.3.2 / Safari crashes with too many tiles

### ISSUE THREAD

**Issue by jplante** [Leaflet/Leaflet#4730]
In the most recent update to iOS and Safari, if you have a large viewport and a bunch of tile layers (lets say 12), the browser crashes and restarts, saying simply that something went wrong.  I'm trying to get information out of the console now, but the refresh is making it harder, so I'll report more when/if I get something.

This was never a problem until their most recent update.  I don't know if anyone else can verify it.  I know it might seem like a lot of layers, but this is how we animate layers in Leaflet.  I don't know if this is either from the tile-pruning fix, the iOS/Safari update or something else that might be going on.  

I just wanted to bring it up to the community.

**Comment by jplante** [comment]
It appears to be an issue with requesting too many tiles too quickly. If the 12 layers were turned on one at a time, able to gain the tiles for their viewport before adding switching to the next, there is no problem...  After panning zooming the same areas, they are fine.  Doing so with 4 layers on at a time is not a problem either.  So it doesn't seem like a total memory issue necessarily, and the tile-pruning is probably able to do its work before reaching a limit. 

However, if the 12 layers were either all on at the same time, or in the case of animating, each on is turned on/off before the next every approximately every 300ms, there is a point where we seem to either overload the client-server request capability of Safari on the latest version of iPad, or that we reach some memory limit decoding the images before the Leaflet prune has a chance to do its work.

Again, this is only a very recent problem.  I will try to test to see if a Leaflet version earlier than the recent tile-prune update exhibits the problem or not, helping to identify if it's in Leaflet or iOS or Safari.

**Comment by mourner** [comment]
Interesting. Simultaneous tile fade animation can be a cuplrit too. Can you try removing the `will-change` property from `leaflet.css` or overriding it to `auto` and see if it improves things?

**Comment by yohanboniface** [comment]
#4686 maybe linked then?

**Comment by jplante** [comment]
I was really hopeful that would solve the problem, but early indication is that it persists even after that rule is removed or set to `auto`

**Comment by jplante** [comment]
If I pre-request all the tiles for each layer one at a time, and then animate them (by hiding all but one and turning them on in succession) the error does occur.  This may indicate it has something to do with request queue, image decoding, or perhaps if there is an initial transition (fade) during first-load of the image.

For what exactly happens, Safari refreshes the page with an error that says: 
`A problem occurred with this webpage so it was reloaded."

There are not other assets on the page besides a map and a couple of simple buttons to send in commands.

**Comment by jplante** [comment]
Making things even more interesting, if I slow down the changing from layer to layer to take 10 seconds between switching, the error still occurs.

Yet, if I turn on 29 layers without 'flipping' them, I have no problems.  

I'm going to investigate if it has something to do with the use of opacity to show/hide layers (used to prevent the flicker effect of add/remove)

**Comment by jplante** [comment]
I have been able to narrow the issue down.  It exists within the `_updateOpacity` method of the `/tile/GridLayer.js` class.

If I use `visibility` on the container element instead, the problem is gone.  Not preferred because there is a slight flicker that occurs on initial showing of the layer, likely caused by browser decoding the image first display - could be mitigated by moving the container way off screen.

Still, if you call `.setOpacity` which ultimately leads to `_updateOpacity`, the problem occurs.

This could be from opacity setting, transitions (`requestAnimFrame`), and pruning is in there too as well.

**Comment by jplante** [comment]
I'm not sure yet if Leaflet's image destruction behaves in a manner described by this article (which I understand is aged), but I'm wondering if there is any validity to this.  I'm going to play with it and see what kind of results I get.

http://www.fngtps.com/2010/mobile-safari-image-resource-limit-workaround/

```
function destroyImage(img) {
  img.parentNode.removeChild(img);
  img.src = "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=";
  window.timeout(function() { 
    img = null;
  }, 60000);
}
```

**Comment by jplante** [comment]
The issue is that iOS has a hard limit on the number of images it can have in a single session.  There is no issue directly associated with Leaflet.  The best way to handle this (for the purposes of animation), is to also set the layer's container CSS `display: none` when the layer is not visible - this allows iOS to not bother adding those images to its hard limit.

**Comment by mourner** [comment]
Thanks @jplante!

**Comment by marlo22** [comment]
We've faced maybe not same but similiar issue. In our case rendering tiles as `<canvas>` instead of `<img>` did the job. You can check it here. https://github.com/GIAPspzoo/L.TileLayer.Canvas
