### ISSUE TITLE
L.DomEvent.off() undefined _leaflet_id on removing all events

### ISSUE THREAD

**Issue by rbfowler9** [Leaflet/Leaflet#4731]
Tested on 1.0.0rc1
According to the docs, `L.DomEvent.off(obj, types, fn, context)` "Removes a previously added listener function. If no function is specified, it will remove all the listeners of that particular DOM event from the element."
However this is not working as stated, if one tries to remove listeners from an object without passing the listener function `fn`, the `L.stamp(fn)` call at the beginning of `L.DomEvent._off()` tries to set property `_leaflet_id` of an undefined object and raises an exception.
Perhaps the docs are outdated?

**Comment by IvanSanchez** [comment]
@rbfowler9 Yeah, looks like that's the case :-(

Can you provide some self-contained way of triggering this bug? Bonus points if you can shape it into a unit test inside https://github.com/Leaflet/Leaflet/blob/master/spec/suites/dom/DomEventSpec.js !

**Comment by yohanboniface** [comment]
Can you please try with latest master?

**Comment by jmfolds** [comment]
I am having a similar/same issue: http://codepen.io/jmfolds/pen/YWJVja

Seems to be related to context param on addListener. If you pass in context in the test, it fails:
https://github.com/Leaflet/Leaflet/blob/master/spec/suites/dom/DomEventSpec.js#L69
https://github.com/jmfolds/Leaflet/commit/20118abd27fe4ccd31304969d0e49e85a2a1a51a

Hopefully that's helpful.

**Comment by chriszrc** [comment]
The issue is still there with 1.1.0 -

**Comment by perliedman** [comment]
@jmfolds if you provide a context when adding the listener, you must provide the same context when removing it, otherwise it will not work. So from my understanding of your example, this is not a Leaflet issue (the codepen 404s, btw, so hard to tell for sure).

**Comment by chriszrc** [comment]
I think the docs say otherwise:

```
//Removes a set of type/listener pairs
off(<HTMLElement> el, <Object> eventMap, <Object> context?)
```

context is optional. If this is really working as intended, then it would be great to get a method that would work here, so that users can deal with libraries that add their own listeners-

**Comment by jmfolds** [comment]
@perliedman Thanks for the response! Sorry about the codepen 404, here is an updated example showing `.off` requiring context. https://codepen.io/jmfolds/pen/brYwoX

Looking at the developer tools, I do see what I believe is the original error that was reported:

```
Uncaught TypeError: Cannot read property '_leaflet_id' of undefined
```

**Comment by perliedman** [comment]
I've looked at the docs for [`removeListener` in 0.7](http://leafletjs.com/reference-0.7.7.html#domevent-removelistener) as well as the history of the `DomEvent.js` file, and I can see no sign of this functionality (removing all listeners if `fn` isn't specified) in the current or earlier versions. I think this "bug" was introduced when to docs where moved to code comments, and this method was documented as working the same as `Evented`'s `off` method, which isn't true.

So, there is no problem in the code, and from what I can tell there's no easy way to actually implement this functionality. We should update the docs instead.

**Comment by 77ganesh** [comment]
Hi, I have submitted a PR. Removed docs for off method invoked without passing any listener.
