### ISSUE TITLE
Prepare 1.0.0-rc2 release

### ISSUE THREAD

**Issue by yohanboniface** [Leaflet/Leaflet#4732]
- [x] Merge #3952 @mourner 
- [x] write blog post @yohanboniface 
- [x] write changelog @yohanboniface 
- [x] update changelog with changes of the last few days @yohanboniface 
- [x] update changelog date and merge @yohanboniface
- [x] update version in `src/Leaflet.js` @yohanboniface
- [x] update version in `package.json` @yohanboniface
- [x] add an upgrade path to Leaflet.Label README @yohanboniface
- [x] run `npm run release` @mourner
- [x] wait for the Travis to build and upload artifacts (the build, leaflet.zip, etc.)
- [x] update the download page in `gh-pages` to point to the new release 
- [x] update the website to use the new release (examples, tutorials, etc.)
- [ ] update the playground to show an option for rc2 @ivansanchez
- [x] replace `reference-1.0.0.html` in `gh-pages` with the latest leafdocs built @ivansanchez
- [x] merge [gh-pages-rc2](https://github.com/Leaflet/Leaflet/pull/4734) @mourner 
- [x] tweet about the new release @mourner
- [x] publish the GitHub release entry @mourner

**Comment by mourner** [comment]
I think it's time to switch leafletjs.com maps to `rc2`, to be able to catch potential regressions before we go out with 1.0 final.

**Comment by yohanboniface** [comment]
This line then? :)

> optional: update the website to use the new release (examples, tutorials, etc.)

**Comment by yohanboniface** [comment]
See https://github.com/Leaflet/Leaflet/pull/4733 for version bump.

**Comment by yohanboniface** [comment]
See #4734 for version bump in gh-pages

**Comment by v3ss0n** [comment]
Is this ES6 compatible now? Can we do Import now?

**Comment by IvanSanchez** [comment]
@v3ss0n No.

**Comment by v3ss0n** [comment]
Thanks  @IvanSanchez  , any plan to include ES6 support by 1.0 release?

**Comment by yohanboniface** [comment]
https://github.com/Leaflet/Leaflet.label/pull/160 to add the upgrade path in Leaflet.label readme cc @jieter
