### ISSUE TITLE
setView инициализация параметров по умолчанию

### ISSUE THREAD

**Issue by YaroslavShemshur** [Leaflet/Leaflet#4735]
var mymap = L.map('mapid').setView([51.505, -0.09], 13);

var mymap = L.map('mapid'); - не работает, параметр по умолчанию отсутствует.

При взаимодействии с картой возникают ероры в консоли 

leaflet.js:8 Uncaught TypeError: Cannot read property 'subtract' of undefined_onMove @ leaflet.js:8s @ leaflet.js:8
leaflet.js:8 Uncaught TypeError: Cannot read property 'add' of undefined

**Comment by mourner** [comment]
Working as designed. You have to explicitly set the view of the map.
