### ISSUE TITLE
Dragging a marker doesn't provide 'oldLatLng' in 'move' event.

### ISSUE THREAD

**Issue by Rantanen** [Leaflet/Leaflet#4736]
Moving marker with `setLatLng` yields `oldLatLng` value in the event parameter.

Moving the marker by dragging it around doesn't.

http://playground-leaflet.rhcloud.com/lifu/1/edit?html,output

**Comment by Rantanen** [comment]
Also discussed at Leaflet/Leaflet.markercluster#335

**Comment by mourner** [comment]
Fixed in #4752.
