### ISSUE TITLE
Tooltip don't disappear on mobile

### ISSUE THREAD

**Issue by db255** [Leaflet/Leaflet#4741]
If you click on a marker with a tooltip, it will not erase the previous tooltip.
Tested with Leaflet 1.0.0-rc2, under Android 6.0.1, with Chrome 51 and Firefox 47
Small demo here: https://mercantour.info/leaftest.html
![screenshot_20160720-141505](https://cloud.githubusercontent.com/assets/20557552/16986006/909863ea-4e84-11e6-8491-c30f6f83542d.png)

**Comment by mourner** [comment]
Thanks for the report! cc @yohanboniface
