### ISSUE TITLE
A tiny question about Leaflet size

### ISSUE THREAD

**Issue by gholol** [Leaflet/Leaflet#4742]
This is a quote taken directly from the main page:

> Leaflet is the leading open-source JavaScript library for mobile-friendly interactive maps. Weighing just about 33 KB of JS, it has all the mapping features most developers ever need.

Am I doing something wrong? because it weights *133KBytes* for me. 
Perhaps somebody should fix this typo?

**Comment by mourner** [comment]
@gholol it's gzipped size.
