### ISSUE TITLE
Vector rendering regression in rc2

### ISSUE THREAD

**Issue by wqoq** [Leaflet/Leaflet#4743]
I've loaded a GeoJSON polygon onto the map. I click and drag the map so the polygon is either partially or totally obscured, and then release the mouse. Then I click and drag the map so the polygon should be visible again, and then release the mouse. At this point, the portion of the polygon that was not visible does not get redrawn, but rather the polygon is simply closed with a joining line (or in the case where the polygon was completely obscured, nothing gets drawn at all). Not until I nudge the map again does the polygon redraw correctly.

Changing the clip padding doesn't make a difference. It only extends how far I have to drag the polygon past the viewport. When I drag the polygon back and release the mouse, it still doesn't redraw correctly.

https://jsfiddle.net/Lomtbax3/

Chrome Version 51.0.2704.84 m
Windows 7 Enterprise SP1
Leaflet 1.0.0-rc2

This almost seems like a repeat of #2674, #2814, #2945, or #3128, except those all specifically mention not redrawing while still dragging, which I understand is for performance reasons. My issue is that it's not redrawing correctly after releasing the mouse.

**Comment by SuberFu** [comment]
I can reproduce that error, it also affects L.Polyline

Chrome 51.0.2704.103
Windows 10
Leaflet 1.0.0-rc2

**Comment by hyperknot** [comment]
Vector rendering is broken in rc2. After a panning vector layers are not redrawn. 
Test cases: debug/vector/vector.html and rectangle.html
Git bisect points to 0210071dad5a1e4e73039c76c131b717b24511ed.

Screenshots:
<img width="522" alt="screen shot 2016-07-21 at 22 20 23" src="https://cloud.githubusercontent.com/assets/494223/17037684/5917c898-4f92-11e6-8cdb-c483c6046d03.png">
<img width="823" alt="screen shot 2016-07-21 at 22 21 03" src="https://cloud.githubusercontent.com/assets/494223/17037688/5c296e10-4f92-11e6-8136-d78429727eed.png">

**Comment by mourner** [comment]
Holy crap, how did we miss that? cc @perliedman @IvanSanchez @yohanboniface

**Comment by mourner** [comment]
It looks related to the order of events. Probably the vector code clips the vector before the bounds are updated to new value after panning.

**Comment by yohanboniface** [comment]
Having a quick look on it: my *guess* is that it comes from the fact before events refactoring, events without context where stored in an array, and thus the firing order was the adding order; while now all events are stored in a hash, thus the final firing order is impredictable (and in this given case we need renderer events to be fired before path events). I may be wrong as this is just a quick look.

Moving to a camp in the desert for one week in a few hours and a lot of things to finish, so it's very unlikely that I will have time to hack more on this, so hopefully someone else will have time!

**Comment by shua123** [comment]
I've also reproduced this error for L.Polyline

Chrome 51.0.2704.103
Windows 10
Leaflet 1.0.0-rc2

**Comment by yohanboniface** [comment]
Made one try with #4769
