### ISSUE TITLE
osm doesn't show in andorid 5.1

### ISSUE THREAD

**Issue by frankVig** [Leaflet/Leaflet#4749]
Hi, i'm developing an hybrid app with cordova using leafletjs and osm. The open street map is shown in android 4.1.1 but not in android 5 (it shows gray panel). How i can resolve it?

![untitled](https://cloud.githubusercontent.com/assets/20613950/17078594/6f9c25f8-50f7-11e6-9693-0dcda043c36a.png)

on Andorid 5.1 (CyanogenMod 12.1)

![untitled1](https://cloud.githubusercontent.com/assets/20613950/17078606/d364e796-50f7-11e6-9cc1-64aa48ae92ac.png)

on Andorid 4.1.1

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
