### ISSUE TITLE
Geojson Polygons Click Event Propagate to Map

### ISSUE THREAD

**Issue by TranquilAbyss** [Leaflet/Leaflet#4753]
When a polygon made with GeoJson is clicked the map event will also trigger. I would like only the polygon click event to trigger. How can I stop the polygon click event from propagating? 

I found previous issue with dragging the map around when the mouse was over a polygon.
#834

Here is a example of this problem. It appeared that there was a change from 0.7.5 to 1.0.0 that enabled the polygon click event to propagate.
[http://playground-leaflet.rhcloud.com/xiyi/1/edit?html,console,output](http://playground-leaflet.rhcloud.com/xiyi/1/edit?html,console,output)

Thank you,

**Comment by yohanboniface** [comment]
> How can I stop the polygon click event from propagating?


    L.DomEvent.stopPropagation(e).
