### ISSUE TITLE
Polygon GeoJson Format

### ISSUE THREAD

**Issue by TranquilAbyss** [Leaflet/Leaflet#4756]
Why is it that when I use the code `marker.toGeoJson()` I get the the properties Object under feature feature Object. 
![capture2](https://cloud.githubusercontent.com/assets/2864849/17179897/cffd705c-53e8-11e6-813d-db68d019a091.png)

When I use `polygon.toGeoJson()` the properties Object is found under the options Object.
![capture](https://cloud.githubusercontent.com/assets/2864849/17180078/3c6812c4-53e9-11e6-9b9e-299091b95e41.PNG)

Where should the properties Object be located and how do I correct it?

Here is my create marker script.
```
function CreateMarker() {
		var geojsonFeature = {
			"type": "Feature",
			"properties": {
				"id": "",
				"name": "new",
				"iconID": "15",
				"lastUpdate": ""
			},
			"geometry": {
				"type": "Point",
				"coordinates": [templatlng.lat, templatlng.lng]
			}
		};
				
		var marker;
				
		L.geoJson(geojsonFeature, {
			pointToLayer: function(feature, latlng) {
				marker = L.marker(templatlng, geojsonFeature);
				return marker;
			}
		});
				
		console.log(marker);
}
```
Here is my Complete Polygon Script (newPolygon variable is a stand in to draw the polygon before saving)
```
function CompletePolygon(){
	if(creatingPolygon)
	{
		creatingPolygon = false;
					
		var geojsonFeature = {
			"type": "Feature",
			"properties": {
				"id": "",
				"name": "new",
				"lastUpdate": "",
				"labelID": ""
			},
			"geometry": {
				"type": "Polygon",
				"coordinates": newPolygon.toGeoJSON().geometry.coordinates
			}
		};
					
		var polygon;
					
		L.geoJson(geojsonFeature,{ 				
			onEachFeature: function (feature, layer) {				
				//create new polygon
				polygon = L.polygon(newPolygon.toGeoJSON().geometry.coordinates, geojsonFeature);			
			}
					
		}}

		console.log(polygon);
}
}
```

I am not sure if this is an issue or not but I could not find an answer so I want to bring it your attention.

Thanks.

**Comment by ghybs** [comment]
Hi,

When you create your marker, `L.geoJson()` will use the returned result of your `pointToLayer` function to include it in the Feature Group, and automatically add the `feature` property.

In your code for the polygon, you use the `onEachFeature` option, which is a hook for you but `L.geoJson()` will not use any returned value (you do not return any anyway). So your `polygon` variable will not receive a `feature` property, as it was already added to the `layer` that is passed as 2nd argument of the `onEachFeature` function.
However, notice that you passed `geojsonFeature` variable as 2nd argument of `L.polygon()`, which is normally used for the options. That is why you can find all your GeoJSON in the `option` property of `polygon`.
If you had just done `polygon = layer`, you could have seen the `feature` property.

Notice by the way that you did the same strange 2nd argument trick for your `L.marker()`. And in your screenshot, there is an `options` property on your `marker`, which is surely your GeoJSON data as well…

Hope this helps.

**Comment by TranquilAbyss** [comment]
Thanks for your explanation of the GeoJson. I will give your suggestion a try. 

I was unsure about what L.GeoJson was actually doing in the Leaflet code.

**Comment by TranquilAbyss** [comment]
Thanks for you help. Here are the correction I made to the code.

Get Marker GeoJson
```
function CreateMarker() {
        var geojsonFeature = {
            "type": "Feature",
            "properties": {
                "id": "",
                "name": "new",
                "iconID": "15",
                "lastUpdate": ""
            },
            "geometry": {
                "type": "Point",
                "coordinates": [templatlng.lat, templatlng.lng]
            }
        };

        var marker;

        L.geoJson(geojsonFeature, {
            onEachFeature: function(feature, layer) {
                marker = layer;
            }
        });

        console.log(marker);
}
```

Get Polygon GeoJson
```
function CompletePolygon(){
    if(creatingPolygon)
    {
        creatingPolygon = false;

        var geojsonFeature = {
            "type": "Feature",
            "properties": {
                "id": "",
                "name": "new",
                "lastUpdate": "",
                "labelID": ""
            },
            "geometry": {
                "type": "Polygon",
                "coordinates": newPolygon.toGeoJSON().geometry.coordinates
            }
        };

        var polygon;

        L.geoJson(geojsonFeature,{              
            onEachFeature: function (feature, layer) {              
                  //create new polygon
                  polygon = L.polygon(newPolygon.toGeoJSON().geometry.coordinates, geojsonFeature);           
            }
        }}

        console.log(polygon);
    }
}
```
This information is later saved to a file. Basically I send the layer Json data to the server script that updates a feature group. This is to allow multiple user to edit the map with minimal conflicts.

**Comment by zhuyinjing** [comment]
how to get coordinates on image overlay had annotationed??????
