### ISSUE TITLE
Hover on Leaflet control zoom button causing color switching in Safari

### ISSUE THREAD

**Issue by zhujy8833** [Leaflet/Leaflet#4758]
Hi,

I am currently seeing this issue using Safari. When I set zoom button color and hover color, I was seeing color messed up when hovering on one of buttons causing.

Here is my jsfiddle: https://jsfiddle.net/zhujy_8833/0vLbywyf/3/, where I set regular background color to `blue` and the expected behavior is when hover on zoom button it should turn to grey, however I get this "red" color show up on the other button instead:
![screen shot 2016-07-27 at 4 06 14 pm](https://cloud.githubusercontent.com/assets/1320373/17195672/17d554dc-5414-11e6-87cd-65e30c3cca8c.png)
(In the Jsfiddle, I added a comparable button group and it works fine when hovering, just the one on the map has the problem). 
It seems working fine on Chrome and Firefox.

OS: El Capitan (10.11)
Safari: 9.0
Leaflet: 1.0-rc.2

I also tested using Leaflet 1.0-rc.1, 0.7.7 and 0.7.3 css, and it occurred to all of the versions.
Is it a bug of Safari or something caused inside of Leaflet?

Thanks!

**Comment by IvanSanchez** [comment]
@zhujy8833 Does this happen also when **not** using Leaflet? Can you add a `:hover` rule to a normal HTML element and make the color problem happen?

**Comment by snkashis** [comment]
I cannot replicate this behavior in El Capitan / Safari 9.1.2 .

**Comment by zhujy8833** [comment]
@IvanSanchez it works fine without Leaflet, if you look at my jsfiddle: https://jsfiddle.net/zhujy_8833/0vLbywyf/3/, I put another pair of buttons on the bottom which are just pure html buttons without leaflet, and they work fine. So that's why it makes me think it might be Leaflet related not Safari.

**Comment by zhujy8833** [comment]
@snkashis Did you try it on your laptop screen or a bigger monitor? I am seeing this issue on monitor display only - I have a monitor and connect my laptop display there. So it is weird that it works fine on laptop screen, but as soon as I drag the browser to monitor display, the problem starts to happen.

**Comment by snkashis** [comment]
@zhujy8833 nope, I cannot replicate on my laptop display or external.

**Comment by verythorough** [comment]
I can reproduce on El Capitan/Safari 10.0, but the behavior is very strange.  The hovered button is always gray as expected, but un-hovered buttons are sometimes red, based on the following rules:

![screen shot 2016-11-04 at 6 06 23 pm](https://cloud.githubusercontent.com/assets/6111186/20026545/737ecd38-a2b9-11e6-9b0c-32e5e0adc89f.png)

The pattern is the same if you vertically flipping the hover behavior (i.e., hovering `-` before `+`) produces vertically flipped results.

Clicking and dragging the map removes the behavior completely.

I can predict the pattern consistently, but I'm no closer to understanding why it happens!

**Comment by zhujy8833** [comment]
@verythorough I found this weirdness when I use Safari and render it using my external monitor, that's the only combination that I could reproduce this.

So far I think i've found the workaround and the possible place causing this issue:
https://github.com/Leaflet/Leaflet/blob/master/dist/leaflet.css#L115-L116. If i override the `z-index` value to default, it seems resolved the issue. The alternative way I tried is to "uncheck" `position: absolute`, it did fix the problem but I don't think it is safe since we had `top`, `left` values to control position. So my temporary solution is to override `z-index` as `z-index: auto`.
And an version with the temporary fix is: https://jsfiddle.net/0vLbywyf/6/ and it works fine for me.

The real issue under the hood, I think, still deserved to get more investigations.

**Comment by perliedman** [comment]
This appears to be a quite weird special case in Safari and some monitor configuration, which makes it quite low priority, if it even happens in newer versions of Safari and/or Leaflet.

If this bug still exists and someone wishes to contribute a PR based on [@zhujy8833's suggestions](https://github.com/Leaflet/Leaflet/issues/4758#issuecomment-258993932), I'll consider re-opening and merging, but closing for now.
