### ISSUE TITLE
Popup map panning regression

### ISSUE THREAD

**Issue by db255** [Leaflet/Leaflet#4759]
The map doesn't pan down enough to fit the popup, when the marker is at the top of the map. As a result, you can't see the close button.
Tested here : http://leafletjs.com/index.html
![image](https://cloud.githubusercontent.com/assets/20557552/17204414/b755410c-54a5-11e6-8ad0-906a9efce706.png)
Was ok in 1.0.0-rc.1, and is not ok in 1.0.0-rc.2.

**Comment by yohanboniface** [comment]
bisect points at https://github.com/Leaflet/Leaflet/commit/3ecd4273f3aab07736fdf0679c0874c273a85a0b
