### ISSUE TITLE
Switching maps and loading map result in increased memory consumption

### ISSUE THREAD

**Issue by sudheesh001** [Leaflet/Leaflet#4762]
We are using leaflet for an angular application where we have the ability to switch between different map layers, Whenever we switch a map, we destroy the scope and re render the map. Every map switch is resulting in increased memory consumption even when the older map is selected.

Here's an [example](https://jsfiddle.net/sudheesh001/o1veqf30/)

Steps to reproduce
1. Load the fiddle.
2. Open chrome task manager and notice the memory taken by the tab
3. Zoom the chrome tab to 50% zoom level.
4. Zoom into any location on the map (Notice the spike in memory here)
5. Replace the map type by choosing from the radio buttons on the right hand side.
6. Click on a few of them one by one and wait for the map to load, Notice the increasing peak memory consumed as we click, returning back to the previously clicked map still increases the memory.

![chromeleaflet0](https://cloud.githubusercontent.com/assets/4545925/17246578/afbad686-55aa-11e6-9226-5738d40f8f05.png)

![chromespikedperformance](https://cloud.githubusercontent.com/assets/4545925/17246582/b3ad42b0-55aa-11e6-82a6-7712254b9f42.png)

![jsfiddlechromeleaflet1](https://cloud.githubusercontent.com/assets/4545925/17246585/b7fd7952-55aa-11e6-8679-278c684d07c0.png)

The leak is even faster in Edge

![jsfiddleieleaflet](https://cloud.githubusercontent.com/assets/4545925/17246588/c827c350-55aa-11e6-81e5-3ccbeb3f019c.png)

The issue becomes worse while panning leaflet maps with geojson layers on them and switching between multiple maps with geojson on each one of them.

**Comment by yohanboniface** [comment]
@sudheesh001 Thanks for the report.
I think you should do your metrics with a pure Leaflet code. JSFiddle can affect the memory footprint.

**Comment by sudheesh001** [comment]
@yohanboniface Thanks for looking into it, I could reproduce the same with the code being in a file and run on the browser
<img width="1440" alt="screen shot 2016-08-01 at 3 37 42 pm" src="https://cloud.githubusercontent.com/assets/4545925/17290852/284e88d6-57fe-11e6-8d75-e5b823a523f9.png">

**Comment by hyperknot** [comment]
The issue can be replicated on the official Provider page. It doesn't need to have 50% zoom, the memory usage just grows more quickly then.
http://leaflet-extras.github.io/leaflet-providers/preview/

Moreover you don't need to change provider either, just try panning a lot on a super standard Leaflet map:
http://playground-leaflet.rhcloud.com/wuzuv/1/edit?output

I believe there is no bug here, the code above is using Leaflet 0.7, there really shouldn't be any memory leaks while simply panning in Leaflet 0.7. Chrome might be including the cache in it's memory tab, but would probably clean it as soon as memory wouldn't be enough.

**Comment by sudheesh001** [comment]
The code example i've given is using `Leaflet 1.0.0-rc.2`, The 0.7 one has no memory leaks but it looks like the rc2 does

**Comment by hyperknot** [comment]
@sudheesh001 can you try rc1 also? Tile pruning was changed in rc2. Also, it'd be really important to have an example which doesn't depend on any external plugin or playground / jsfiddle when debugging leaks. At least playground allows you to save a clean html, so a playground example would probably be ok.

**Comment by mourner** [comment]
@sudheesh001 are you sure this is actually a leak and not a default browser behavior? What if you replace Leaflet with just dynamically loading a big image over and over?

**Comment by mourner** [comment]
Closing because of lack of feedback from the original issue author.

**Comment by sudheesh001** [comment]
@hyperknot It's the same in rc1 too but it looks like the spike in memory is lower in that.

@mourner Yes it looks like a leak to me since it happens on all browsers. Loading large images with pano.js isn't giving the same problem.

Sorry for the late reply, seem to have missed this notification.
