### ISSUE TITLE
Angular 2 / Ionic 2 - Path (Polygon-Circle) jumping when zooming

### ISSUE THREAD

**Issue by Oreonax** [Leaflet/Leaflet#4774]
Hi,

When zooming in or out, circle and polygon are jumping - have a delay with the transition, like in the following gif:

![Image of issue](https://framapic.org/shpS5qxtcMnP/A1Fbzfa7R0rd.gif)

I used the code in the quick start guide: http://leafletjs.com/examples/quick-start-example.html

**sequence-start.ts**
```
import {Component} from "@angular/core";
import {Page} from 'ionic-angular';
import * as L from 'leaflet';

@Component({templateUrl: 'build/pages/sequence-start/sequence-start.html'})

export class SequenceStart {

  constructor() {}

  ionViewLoaded(){

    var mymap = L.map('mapid').setView([51.505, -0.09], 13);

		L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpandmbXliNDBjZWd2M2x6bDk3c2ZtOTkifQ._QA7i5Mpkd_m30IGElHziw', {
			maxZoom: 18,
			attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, ' +
				'<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
				'Imagery © <a href="http://mapbox.com">Mapbox</a>',
			id: 'mapbox.streets'
		}).addTo(mymap);

		L.polygon([
			[51.509, -0.08],
			[51.503, -0.06],
			[51.51, -0.047]
		]).addTo(mymap);

    setTimeout(() => {
        mymap.invalidateSize(0);
    }, 800);
  }
```

**sequence-start.scss**

```
  #mapid{
    position:absolute;
    top:0;
    bottom:0;
    height:250px;
    width:250px;
  }
```

**sequence-start.html**

```
<ion-content>
  <div id='mapid'></div>
</ion-content>
```

I tested with and without the` zone.js` patch provided here: #4588 

Appends on Chrome, Android

Using:

- Leaflet RC2
- Angular2
- Ionic2

**Comment by ghybs** [comment]
Hi,

This is usually a symptom of mismatch between Leaflet CSS and JS versions.

Demo using CSS from Leaflet 0.7.7 but JS from Leaflet 1.0.0-rc.2: https://jsfiddle.net/3v7hd2vx/55/

**Comment by Oreonax** [comment]
....thanks that was it !

**Comment by darolsz1** [comment]
@Oreonax  can you please help me setting all needed steps to be able to view the map in leflet. After npm i --save leaflet @types/leaflet, and importing this as you wrote I receive holes, like attached.. What am I missing?
![localhost-8100leaf](https://cloud.githubusercontent.com/assets/7848187/20159346/5edd9ece-a6e0-11e6-8882-6413d4774e40.png)

**Comment by Oreonax** [comment]
Hi @darolsz1 ,
It don't seems to be the same issue. Which version of ionic are you using ?
You need to manually import css file (the location depend on your ionic/angular version). Are you sure that your css of leaflet is loading properly ?

**Comment by meeximum** [comment]
I'm facing exactly the same problem :-(
Ionic2 RC1

`@Component({
  selector: 'page-trunk-list',
  templateUrl: 'trunk-list.html'
})
export class TrunkListPage {

  private latLng: any;
  private marker: any;
  private map: any;

  constructor(public navCtrl: NavController) {
  }

  ionViewDidLoad() {
    this.loadMap();
    setTimeout(() => {
       this.map.invalidateSize(0);
    }, 800);
  }

  onMapClicked(event) {
    this.latLng = event.latlng;
  }

  onMarkerPositionChanged(e) {
    const latlng = e.target.getLatLng();

    this.latLng = latlng;
  }

  loadMap() {
    this.map = Leaflet
      .map("map")
      .setView([51.505, -0.09], 13)
      .on("click", this.onMapClicked.bind(this))

    Leaflet.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
      attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(this.map);

    this.marker = Leaflet
      .marker([51.505, -0.09], { draggable: true })
      .on("dragend", this.onMarkerPositionChanged.bind(this))
      .addTo(this.map);
  }

}`

**Comment by meeximum** [comment]
@Oreonax thx for the css hint :-)
I copied the leaflet.css from /node/modules/leaflet/... directory to the /build directory and referenced it in the index.html
`<link href="build/leaflet.css" rel="stylesheet">`

**Comment by meeximum** [comment]
ok, no good idea to manually copy to build directory, get's deleted after every new ionic serve start :-/

**Comment by darolsz1** [comment]
I added in ionic app scripts> sass.config a line pointing to leaflet css: 'node_modules/leaflet/dist' and then added in app.scss additional line: @import "leaflet"; and it finally worked.. Oh and I put marker icons to asset directory = but I have to point mannually at marker definition -a path to marker like " var myIcon = L.icon({
    iconUrl: 'assets/img/marker-icon.png'
  });
I dont know better way to point the right path..? Do you?

**Comment by meeximum** [comment]
@darolsz1 looks like a good solution maybe it makes sense adapting the copy task too (app scripts) to copy the images directory?

**Comment by meeximum** [comment]
@darolsz1 Hi I tried to get this working, but it seems that I do sthg. wrong :-/

in my package.json
```
"config": {
    "ionic_sass": "./config/sass.config.js"
  },
```

in /config/sass.config.js
```
includePaths: [
    'node_modules/ionic-angular/themes',
    'node_modules/ionicons/dist/scss',
    // added for leaflet import (app.scss)
    'node_modules/leaflet/dist'  
  ],
```
and finally app.scss
`@import 'leaflet';`

**Comment by darolsz1** [comment]
@meeximum  it seems all ok. But of course you did at the beginnig in bash: 
npm i --save leaflet @types/leaflet
and then in your component add line: import * as L from 'leaflet' ?

**Comment by meeximum** [comment]
@darolsz1 yes everything done, it works when I add the css by hand in the index.html after I copied it to the build folder, but I found your approach much smarter :-)
It seems that it doesn't workt with the leaflet.css, it isn't added to the main.css?
I think the sass task is just looking for sass files?

**Comment by darolsz1** [comment]
have you upgraded cli, app scripts etc.. acording ionic blog? which scripts do you use? I use these: (which, I am aware, are not the latest.. so I fear what will happen if I upgrade)
mine:
  "name": "@ionic/app-scripts",
  "version": "0.0.38",

**Comment by meeximum** [comment]
@darolsz1 
Here my system
Your system information:

Cordova CLI: 6.4.0
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 0.0.37-5
OS:
Node Version: v6.7.0

**Comment by meeximum** [comment]
@darolsz1 
upgraded to latest version 0.0.44 now it works!!!

**Comment by darolsz1** [comment]
nice @meeximum . :)

**Comment by zulbil** [comment]
I follow exactly the same step we described. But i have the same issue. What i did in fact, is that i copy all the css classes in leaflet.css and i paste it in app.scss. So finally i have the map in my view but without icon marker. 
![map](https://cloud.githubusercontent.com/assets/18274050/23344421/69c937d4-fc7c-11e6-9e98-a4c8f9235151.JPG)

**Comment by zulbil** [comment]
I really need help

**Comment by perliedman** [comment]
Hi and thanks for using Leaflet!

Please note that this is not a support forum, it's the _issue tracker_ for Leaflet, where bugs and feature requests and posted and discussed.

For questions on how to use Leaflet and other support, especially when related to other frameworks like Angular or Ionic, you're better off using [stackoverflow](https://stackoverflow.com/) or [gis.stackexchange.com](https://gis.stackexchange.com/).
