### ISSUE TITLE
.bindTooltip permanent: true not working

### ISSUE THREAD

**Issue by JoshQuake** [Leaflet/Leaflet#4778]
Hey for some reason permanent: true stops the tooltip from displaying at all, but setting to false displays correctly on hover. Is there something I'm missing?

`var Tenaland = L.circleMarker([-417, 385.0625], 45, {
    color: '#f03',
    fillColor: '#f03',
    fillOpacity: 0.80
	}).bindTooltip('Tenaland', { 
	permanent: true,
	interactive: true
	}).addTo(map);`

**Comment by yohanboniface** [comment]
Call `addTo` before `bindTooltip`.
I'll see for a way to allow both ways.

**Comment by JoshQuake** [comment]
Awesome thanks!
