### ISSUE TITLE
GeoJSON layer not rendering properly when moving the map

### ISSUE THREAD

**Issue by fitoprincipe** [Leaflet/Leaflet#4780]
Hello, I was just reading the documentation and found this example for map panes: http://leafletjs.com/examples/map-panes-example.html
But when I move the map, this happens:
![error_leaflet2](https://cloud.githubusercontent.com/assets/10751505/17310885/a377cf1c-581d-11e6-8933-4a4db1a8b94a.png)
the geoJSON layer gets cut off this way until I move the map again. It also happens in my cellphone.
As I see in the source code it uses leaflet1.0.0-rc.2

**Comment by ghybs** [comment]
Hi,

Same as #4743 and #4771?

**Comment by fitoprincipe** [comment]
Yes, sorry I don't have the time to read all 200 issues. I hope it gets fixed soon. Although I will try ferminarellano workaround.
