### ISSUE TITLE
Event moveend fired on deleted map

### ISSUE THREAD

**Issue by djibarian** [Leaflet/Leaflet#4782]
In 1.0.rc2, event `moveend` is fired after the map is removed from the DOM and the viewport size is changed. Specifically, the issue appeared when creating a Leaflet map in a popup and then closing the popup. After that, resizing the browser window fires a `moveend` event. Inside the event, `getSize()` returns 0. Tested in Safari, Chrome and Firefox Mac, latest versions.

**Comment by yohanboniface** [comment]
Can you please provide a jsfiddle to reproduce using http://playground-leaflet.rhcloud.com/ ?

**Comment by djibarian** [comment]
Here it goes: http://playground-leaflet.rhcloud.com/cuc/edit?html,console,output

Just in case it disappears, I’ve added the following lines after the lorem ipsum:

    map.on("moveend", function(e){
      console.log(e.target.getSize().x);
    });
    map.on("click", function(){
      document.getElementById("map").remove();
    });

To reproduce, first pan the map to see the viewport width in the console (600 in my case). Then click on the map to delete it. Then resize the browser window. The console should show 0 now.

Ricardo

**Comment by yohanboniface** [comment]
You need to call [map.remove()](http://leafletjs.com/reference-1.0.0.html#map-remove) instead.

**Comment by djibarian** [comment]
Thank you!
