### ISSUE TITLE
CircleMarker causes an error when map's view is set for the first time

### ISSUE THREAD

**Issue by cvisto** [Leaflet/Leaflet#4783]
I create map without center and zoom in options.
Then create CircleMarker and add it to the map.
After that set map's center and zoom.

in 0.7.7 it works - [jsfiddle](https://jsfiddle.net/cvisto/ubkb2dL8/)
in 1.0.0-rc2 the same code does not work - [jsfiddle](https://jsfiddle.net/cvisto/u93ffm7x/)

**Comment by yohanboniface** [comment]
Can you try with latest master?
It should be fixed by #4769.

**Comment by danzel** [comment]
Yep this is fixed in latest master:
https://jsfiddle.net/u93ffm7x/4/
