### ISSUE TITLE
Can a path be draggable?

### ISSUE THREAD

**Issue by elmart** [Leaflet/Leaflet#4784]
I want to draw a rectangle at some place in my map, containing some extra info.
That rectangle has a default position/size. But ideally, I'd like for the user to be able to move/resize that rectangle to a position/size that suits his needs better.
Is that possible somehow?
I have skimmed through the docs, but to my understanding, the answer would be no.
Is that right?

**Comment by yohanboniface** [comment]
Look at https://github.com/Leaflet/Path.Drag.js

**Comment by yohanboniface** [comment]
And for resizing, look at https://github.com/Leaflet/Leaflet.Editable
