### ISSUE TITLE
1.0.0-rc3 release

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#4785]
- [x] fix https://github.com/Leaflet/Leaflet/issues/4783
- [x] update changelog (cf https://github.com/Leaflet/Leaflet/pull/4786)
- [x] update version in `src/Leaflet.js` (cf https://github.com/Leaflet/Leaflet/pull/4786)
- [x] update version in `package.json` (cf https://github.com/Leaflet/Leaflet/pull/4786)
- [x] run `npm run release`
- [x] wait for the Travis to build and upload artifacts (the build, leaflet.zip, etc.)
- [x] update the download page in `gh-pages` to point to the new release (cf https://github.com/Leaflet/Leaflet/pull/4787)
- [x] update the website to use the new release (examples, tutorials, etc.) (cf https://github.com/Leaflet/Leaflet/pull/4787)
- [x] update documentation with Leafdoc (cf https://github.com/Leaflet/Leaflet/pull/4787)
- [x] update the playground to show an option for rc3
- [x] tweet about the new release
- [ ] publish the GitHub release entry
- [x] write and publish blog post (cf https://github.com/Leaflet/Leaflet/pull/4787)

cc @yohanboniface @perliedman @hyperknot @IvanSanchez

**Comment by IvanSanchez** [comment]
Turns out I can just rebuild the jsbin `public/js` files and rsync them to rhcloud. Yay!
