### ISSUE TITLE
Leaflet Realtime Marker Popups

### ISSUE THREAD

**Issue by chaninwongpong** [Leaflet/Leaflet#4789]
This Leaflet Marker Popups >>> http://jsfiddle.net/6s77xfhg/9/

I tried Leaflet Realtime Marker Popups >>> https://jsfiddle.net/hmyxb6ur/67/

`$("a").click(function(){`
`    var id = $(this)[0].id;`
`    **shipLayer**.eachLayer(function(feature){`
`        if(feature.feature.properties.**mmsi**==id){`
`            feature.openPopup();`
`        } `
`    });`
`});`

Who has some ideas?
I'm new. Please advise me, Thank

**Comment by yohanboniface** [comment]
Hi, great to hear that you use Leaflet!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

**Comment by chaninwongpong** [comment]
Thanks, 
Please advise me, >>> https://gis.stackexchange.com/questions/204590/leaflet-realtime-marker-popups
