### ISSUE TITLE
Polygon drawing borders on move in rc2

### ISSUE THREAD

**Issue by inkstak** [Leaflet/Leaflet#4793]
Since I upgraded to 1.0.0.rc2, I've got the following bug:

I use a L.GeoJSON overlay to draw polygons.
After zooming, the polygons are wider than the window
![capture d ecran 2016-08-05 a 09 32 38](https://cloud.githubusercontent.com/assets/474554/17429681/3752d784-5af0-11e6-945f-acf03d0b5438.png)

But when I move, it doesn't draw properly.
The polygons are cutted by a horizontal or vertical border:
![capture d ecran 2016-08-05 a 09 32 45](https://cloud.githubusercontent.com/assets/474554/17429684/39643d1a-5af0-11e6-8d9d-5ea13fa5486a.png)

The problem only happens when moving, not zooming.
It works great on 1.0.0.rc1

**Comment by Ceremony64** [comment]
I think this is a duplicate of #4743 and has already been fixed with #4769

**Comment by inkstak** [comment]
Sorry, didnt use the good keywords to find the issue.
