### ISSUE TITLE
GeoJSON Rendering Errors

### ISSUE THREAD

**Issue by minus34** [Leaflet/Leaflet#4794]
[This dual map](http://minus34.com/pleaseexplain) using v0.7.7 renders the GeoJSON correctly when you pan and zoom.

[This test map](http://minus34.com/test/) using the same code, but with v1.0 rc3 causes the GeoJSON to partially redraw, freeze or render incorrectly after panning and zooming a few times.

![test1](https://cloud.githubusercontent.com/assets/1809598/17434717/89934632-5b4f-11e6-90e5-d4ddafcf75c7.png)
![test2](https://cloud.githubusercontent.com/assets/1809598/17434718/89934a4c-5b4f-11e6-870e-a94880703bf1.png)

Code is [here](https://github.com/minus34/please-explain/tree/leaflet_1.0_rc3_test)

**Comment by IvanSanchez** [comment]
Can't reproduce - I only get two "call stack size exceeded" errors.

Also, when publishing test webpages, please use the non-minified leaflet files (i.e. `https://npmcdn.com/leaflet@1.0.0-rc.3/dist/leaflet-src.js`, notice `-src.js`)

**Comment by minus34** [comment]
Changed Leaflet to non-minified version in both apps.

Problem occurs repeatedly on my Windows 10 desktop and MacBook (both using Chrome) after 2 zoom outs - right map doesn't fully render.

Note: I've changed the Test app basemap to make it easier to see rendering issues

**Comment by IvanSanchez** [comment]
I think it's a bug in your code and not a Leaflet bug. Let me explain. You're syncing the views by doing:
```
    map1.on('moveend', function(e) {
        map2.setView(map1.getCenter(), map1.getZoom());
    });
    map2.on('moveend', function(e) {
        map1.setView(map2.getCenter(), map2.getZoom());
    });
```

So when `map1` ends a move, that triggers a move on `map2`, and when that happens, that triggers back a move on `map1`, and when that happens that triggers a move on `map2`, and so on and so on and so on.

As those events are added before the `L.Renderer` events (you're adding the vector layers later), the infinite loop happens before the `L.Renderer` events ever run.

The fact that it works in Leaflet 0.7.x might be related to the event refactors that took place in Leaflet 1.0.0-rc.

You should try https://github.com/turban/Leaflet.Sync. And if this is really a bug, we're gonna need an even more minimal example (i.e. does this happen with statically loaded GeoJSON?).

**Comment by minus34** [comment]
Good pickup! Have disabled the triggering on map2 and problem no longer occurs.

I'll try out the plugin later on. Thanks.
