### ISSUE TITLE
Polygon has holes if points off screen

### ISSUE THREAD

**Issue by ballwood** [Leaflet/Leaflet#4795]
Hi,

I'm not sure if its just a setting I've missed but when a polygon is rendering with a point off screen it puts a massive hole in it as you can see in the example below. Is there any way to fix this?

![image](https://cloud.githubusercontent.com/assets/4639337/17434795/6bb24cee-5b04-11e6-9782-2cc554279ae9.png)

Thanks :)

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

Looking at the coordinates of your (multi)polygons should help analyze what the issue really is.

**Comment by ballwood** [comment]
Worked it out, I'm using the react-leaflet abstraction and it was doing something weird. Apologies for wasting your time.

**Comment by IvanSanchez** [comment]
@ballwood No big deal ;-)

Just remember to make sure your bug is reproducible next time!

**Comment by ballwood** [comment]
noted, apologies again.
