### ISSUE TITLE
Layers across date line

### ISSUE THREAD

**Issue by khoivm** [Leaflet/Leaflet#4796]
I want to keep the markers appeared across the date line but it keeps "jumping" when I drag across the date line

Is it possible to set the "jumping point" to another point? or something like that?

My targeting is to draw the vessel path across the sea from Japan to US but it seems very hard to do with current version.

Please help :(

<img width="1213" alt="screen shot 2016-08-05 at 15 02 30" src="https://cloud.githubusercontent.com/assets/8154206/17435978/9ec9294c-5b3e-11e6-9e70-358d4ae07458.png">

When I drag little bit to the right, the markers on the lest supposed to be appeared
<img width="1173" alt="screen shot 2016-08-05 at 15 02 22" src="https://cloud.githubusercontent.com/assets/8154206/17435979/9ed3573c-5b3e-11e6-9879-e81adff70b91.png">

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

> Is it possible to set the "jumping point" to another point? or something like that.

You make a good point here, so I'll say it should be possible to subclass `L.CRS.EPSG3857`, and override its [`wrapLong`](http://leafletjs.com/reference-1.0.0.html#crs-wraplng). This will need testing, though.
