### ISSUE TITLE
IE counts wrong mouse position using DOM method getBoundingClientRect

### ISSUE THREAD

**Issue by skarppion101** [Leaflet/Leaflet#4799]
In this code sector https://github.com/Leaflet/Leaflet/blob/master/src/dom/DomEvent.js#L221 using method getBoundingClientRect to calculate the exact position of the cursor gets wrong mouse coordinates in IE. I've created a JSFiddle to show this bug. If you open it in "normal" browser (Chrome, Firefox etc.) everything is working just fine. But in IE you can't draw a line because of the header. You can remove the <header> tag to see the difference.

https://jsfiddle.net/skarppion101/mowv67hp/6/

**Comment by IvanSanchez** [comment]
What IE are we talking about? 8, 9, 10 and/or 11?

**Comment by skarppion101** [comment]
@IvanSanchez each IE in which leaflet works, include edge

**Comment by jonkoops** [comment]
Closing this issue as we have decided to drop support for Internet Explorer in a future version of Leaflet (see #6136).
