### ISSUE TITLE
[0.7.7] Markers only rendered once on endless map (cause we are on a globe)

### ISSUE THREAD

**Issue by amenk** [Leaflet/Leaflet#4800]
I have several markers / geometries in Africa.
Some of them (right of the 0-merdian) are rendered at one place, the others on another place.
But when I zoom into Africa I want to have them next to each other.

Is this a known bug? (did not know what to search for)

![selection_150](https://cloud.githubusercontent.com/assets/1087128/17456507/08d7bca4-5bda-11e6-99a5-18c64f940048.png)

**Comment by yohanboniface** [comment]
http://leafletjs.com/reference-1.0.0.html#map-worldcopyjump is what you are looking for.

**Comment by amenk** [comment]
Unfortunately not in 0.7.7 - so I have to upgrade.
And I found I use coordinates > 360 - maybe that is not that smart at all :-)

coordinates":[[368.26171875,9.4490618268814],[369.84375,17.644022027873],[362.28515625,10.574222078333],[359.208984375,12.897489183756]]}}]}});

Thanks for the quick reply!

**Comment by yohanboniface** [comment]
> Unfortunately not in 0.7.7 

http://leafletjs.com/reference.html#map-worldcopyjump

But you should upgrade anyway ;)
