### ISSUE TITLE
Leaflet mobile example - geolocation not working

### ISSUE THREAD

**Issue by bplmp** [Leaflet/Leaflet#4801]
When opening the [Leaflet mobile example](http://leafletjs.com/examples/mobile-example.html) I get the following error: "Geolocation error: only secure origins are allowed" and a link to this page https://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features.

**Comment by IvanSanchez** [comment]
Duplicate of #4565
