### ISSUE TITLE
autoPanPaddingTopLeft and autoPanPaddingBottomRight options are commented out in the source

### ISSUE THREAD

**Issue by phillmill** [Leaflet/Leaflet#4805]
The title pretty much says it all. Setting those two options manually doesn't work, BUT using autoPanPadding option to set both at once does work.

I could be missing something here because I am new to leaflet, but this is what I see in the source (leaflet-src.js):

<pre>options: {
        minWidth: 50,
        maxWidth: 300,
        // maxHeight: null,
        autoPan: true,
        closeButton: true,
        offset: [0, 7],
        autoPanPadding: [5, 5],
        // autoPanPaddingTopLeft: null,
        // autoPanPaddingBottomRight: null,
        keepInView: false,
        className: '',
        zoomAnimation: true
    },</pre>

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by perliedman** [comment]
From what I can tell, this works exactly as expected: https://playground-leaflet.rhcloud.com/luno/edit?html,output
