### ISSUE TITLE
map.remove() can run on already removed instances

### ISSUE THREAD

**Issue by iamvdo** [Leaflet/Leaflet#4806]
I've made a JSBin to better explain the problem I'm facing:

* Open http://jsbin.com/wozewag
* Change value from input field (remove 'e' for example), then click below the map (in the white zone). 

The first map is removed, then a second one is created (with x/y switched) and everything works fine

* Click "Reload JS"
* Like before, change value from input field, but then click ON the map (not below). 

The first map is removed, the second is created but there is no pan events. Zoom is OK.

I suppose that when we click on the map, the event is received by the first one (that will be removed instantly), so events are lost. Dealing with `setTimeout` helps understand what happens.

I'm using leaflet@1.0.0-rc.3

**Comment by IvanSanchez** [comment]
Sorry, but I don't understand the bug. Can you provide a more minimal example?

**Comment by iamvdo** [comment]
In the top right corner, there is an input with "change value" text. There is a `change` event attached to it, and the callback function will remove the map, then recreate it. In order to dispatch the event (after you change the value) you'll have to click elsewhere in the page. 

(change the value once)

1. If you click below the map (the event is dispatched), everything works as expected. The first map is removed, then recreated (don't care with misorder of tiles).

(change the value again)

2. If you click on the map, the `change` event is dispatched as well, but the map that is recreated no longer have events (you can't pan the map anymore)

**Comment by iamvdo** [comment]
Note that you can add `/edit` to the URL to see and debug code

**Comment by IvanSanchez** [comment]
By "more minimal" I mean "don't make me change values when that can be automated". i.e. https://playground-leaflet.rhcloud.com/kud/edit?html,output

The issue is related to running this sequence of events:

```
map = L.map(…);
map.remove();
map2 = L.map(…);
map.remove();
map2 = L.map(…);
```

The question then is how to prevent a `L.Map` instance from running `remove()` if the map container belongs to a different instance.

**Comment by iamvdo** [comment]
>"don't make me change values when that can be automated"

I'm sorry. It's the minimal use-case I found. In my real example, it's way more complex... I couldn't expect to find an automated case where it also fails

**Comment by IvanSanchez** [comment]
@iamvdo If a bug is caused by user input, that user input should be automated whenever possible, as to reproduce it consistently. (Even when the input is a multi-touch gesture, see https://github.com/Leaflet/prosthetic-hand). A bug which is easy to reproduce is a bug easy to understand (see http://www.chiark.greenend.org.uk/~sgtatham/bugs.html)

**Comment by iamvdo** [comment]
I already know that. I'm not a Leaflet contributor, I don't have much knowledge to help on it. I've done my best to report the bug, and contribute with what I'm able to do.
I'm glad you find where the problem is :+1:

**Comment by IvanSanchez** [comment]
And I appreciate that! But when one has been looking at Leaflet bugs for a while, there is a pattern of "things that happen automatically" which we love and "webpages that require me to do X then Y then Z" which we tend to avoid (as they usually signal bad quality of the bug report). I hope you understand my point of view too.

**Comment by SuberFu** [comment]
@iamvdo
@IvanSanchez 
I took a quick look and got it to reproduce automatically after some tweaks.
http://jsbin.com/wukusasece/3/edit?html,css,js,output
The leaflet map no longer respond to click-drag events.

**Comment by iamvdo** [comment]
Good to see this issue fixed, but this doesn't seem to fixed my initial problem.
(I updated my JSBin to use the latest from master branch => http://jsbin.com/wozewag/edit?js,output)

**Comment by IvanSanchez** [comment]
@iamvdo There's nothing else to do. The Leaflet code works as expected (throws an error in the console to inform you, the developer, that you cannot run `map.remove()` when it has been already removed and the container is being reused by another instance).

Making both instances work in the same map container would be asking for **a lot** of trouble.

**Comment by iamvdo** [comment]
I'm sorry but in my demo, there is no errors. I'm not trying to "run map.remove() when it has been already removed"

What I have is just:
```js
var map = L.map('map')
map.remove();
var map2 = L.map('map')
```

If you use `setTimeout`, everything works fine
```js
var map = L.map('map')
setTimeout(_=>{
  map.remove();
  var map2 = L.map('map')
}, 200)
```

That's why I think this is an issue.
Btw, I'll try to create an automated version that fails.

**Comment by IvanSanchez** [comment]
Sorry, pal, the error is being thrown and can be seen. It's just that JSbin makes it a bit confusing.
![screenshot_20160811_113042](https://cloud.githubusercontent.com/assets/1125786/17584502/22c98e22-5fb7-11e6-9045-ac7515e4893c.png)

**Comment by IvanSanchez** [comment]
> I'm not trying to "run map.remove() when it has been already removed"

And in case you haven't noticed yet, the problem appears when you change the text for a second time and thus `map.remove()` is run a second time.

**Comment by iamvdo** [comment]
Yep, error occurs on second time. But, it fails on first time too, without error

**Comment by IvanSanchez** [comment]
@iamvdo If you have a **minimal, reproducible** case of a map container being used, removed and reused, and then not reacting to DOM events, please open a new bug with that.

**Comment by iamvdo** [comment]
I do my best. Hope it helps. => #4812
