### ISSUE TITLE
How to init map correctly?

### ISSUE THREAD

**Issue by EricSch** [Leaflet/Leaflet#4809]
I have a map, which is displayed or hidden, depending of a button click.
I init the map while she is hidden, add layer, add markers, call fitBounds() for the markers.
My problem is, when the map is hidden, fitBounds doesn't work. After the switch the map is shown as fully zoomed out. When I call fitBounds again, the map is shown correctly.

How do I know, when the map is ready? I tried mapReady, but it is called also when the map is hidden.
Is there another way?

Thanks

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
