### ISSUE TITLE
Remove/Create a new map at the same time than a pan event fails

### ISSUE THREAD

**Issue by iamvdo** [Leaflet/Leaflet#4812]
See #4806 for the initial problem. 
Here is a reduced, automated test-case where bug happens (using prosthetic-hand):

Open http://jsbin.com/qekuyov/edit?html,output and follow instructions:
1. Click "Pan map"
   - Works as expected
2. Click "Create new map"
   - First we focus input text, and add blur event to it
   - Then mouse pan starts, blur is dispatched, so:
     - Map is removed
     - New map is created
   - The new map no longer have pan events
3. Click "Pan new map"
   - No longer works
   - Also, notice you can't select text on page anymore
4. Click "Zoom new map"
   - It still works (on Chrome)

**Comment by IvanSanchez** [comment]
:+1: for good test case!

This will probably need digging on the DOM event handlers of the map container, we've gotta see if they are cleaned properly.

**Comment by IvanSanchez** [comment]
Somehow this is a race condition involving the map being re-created in the `blur` event handler. Possibly the `mousedown` event happens *before* the map is created, consequently breaking event listeners.

If the "create new map" button just handles map creation, and not document focus, everything works as expected.

**Comment by IvanSanchez** [comment]
Note to self: create an DOM-only test case, attaching some event handlers (for `mousedown`) to a DOM element inside a event handler of that same DOM element. Right now the call stack goes through `map._onMouseDown`, which supposedly triggers its own removal and re-attachment. Also, run some debug code on `map._handleDOMEvent`.

@iamvdo You probably want to try adding some timeout between the blur/focus event and the map removal/recreation, to see if you can work around the problem.

**Comment by iamvdo** [comment]
Yep, I found a solution to get around this bug (using `setTimeout`), but I reported it because it may occur in other scenario. ;)

**Comment by Malvoz** [comment]
> Open http://jsbin.com/qekuyov/edit?html,output and follow instructions

That JSBin no longer works (resources are blocked due to [mixed content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content)).

Updated:

- v1.0.0-rc.3: https://jsbin.com/xiyaduxizo
- v1.8.0: https://jsbin.com/waviyemumu

Can reproduce the bug in v1.0.0-rc.3. Not reproducible in v1.8.0.
