### ISSUE TITLE
Control.Layer different index between Rc2 and Rc3

### ISSUE THREAD

**Issue by ClaudioCas** [Leaflet/Leaflet#4814]
Dear all,
I'm using hash plugin modified by calvinmetcalf to have base layer in url hash. It works great in Leaflet Rc2, but it not working anymore in Rc3.
The plugin needs Control.Layer to work. I did a bit of debug of Js to find the issue and I saw that the Index inside the Control.Layer are changed  between the release.
In Rc2 the indexs of _layers are the ids af layers, in the Rc3 the index are the positions of the layer into the array.

![layercontrol](https://cloud.githubusercontent.com/assets/4325427/17617850/9637e078-607c-11e6-9dc2-96720627d633.jpg)

It is correct?
Should I adapt the plugin to work with the new indexing or it's a kind of "regression"?
Thanks a lot
Claudio

**Comment by jieter** [comment]
`L.Control.Layers` uses an array internally as of #4227, so the plugin should get updated.

**Comment by IvanSanchez** [comment]
What @jieter said. Until 1.0.0 final is out, breaking stuff is to be expected, and plugins should be fixed/updated/adapted.

I'll make a note in https://github.com/mlevans/leaflet-hash/issues.

**Comment by ClaudioCas** [comment]
Ok, thanks a lot for your help. I'm working on the plugin and I hope I will fix the issue.
I will do a fork on github.
Thanks

**Comment by IvanSanchez** [comment]
Wait, I'm looking through the code for https://github.com/calvinmetcalf/leaflet-hash/blob/master/leaflet-hash.js and https://github.com/mlevans/leaflet-hash/blob/master/leaflet-hash.js and I cannot see any references to `L.Control.Layers`. Are you sure it's a problem in the plugin?

**Comment by IvanSanchez** [comment]
Hm, I cannot create an issue in the right repo because @calvinmetcalf hasn't got issues enabled in https://github.com/calvinmetcalf/leaflet-hash :-(

**Comment by ClaudioCas** [comment]
Right Ivan, and thanks for your investigations.
lc is a reference of the current LayerControl. 
@jieter You are right, I have different test site and the plugin work in beta2, not in Rc2.
I switch the internal test site from beta2 to rc3. The production site has aready yhe rc2 but it has no hash at the moment.
I changed the issue title. I almost fix the issue with the plugin.
Thanks for your great support.

**Comment by ClaudioCas** [comment]
Here my fork.
https://github.com/ClaudioCas/leaflet-hash
Update the plugin, now works with leaflet RC.
Thanks a lot!
