### ISSUE TITLE
SphericalMercator.project() does not accept [lat,lng] array

### ISSUE THREAD

**Issue by natonic77** [Leaflet/Leaflet#4817]
The documentation for LatLng in Leaflet 0.7.x indicates that:

> All Leaflet methods that accept LatLng objects also accept them in a simple Array form and simple object form (unless noted otherwise)...

However, I was getting NaN results when using this form.  In examining the code it appears that that particular call (on line 11 of the Projection.SphericalMercator.js ) assumes the latlng passed in is a LatLng object.  Checked the latest source in master and it appears this is still the case.

Workaround is obvious, but implementation does seem inconsistent with the documentation.

I have not checked the other projections for this bug.

**Comment by IvanSanchez** [comment]
This might be a documentation issue. At http://leafletjs.com/reference-1.0.0.html#transformation-transform we write about using explicit instances of `L.Point`, but the docs about `L.Projection` don't say anything about that.

I'd say let's keep the code as is (projections can be a critical path that we might want to keep clear of new instantiations), and write verbosier documentation about `Projection`.

**Comment by andmckvr13** [comment]
need any help with rewriting the documentation? I'm very new to contributing to open source so even updating a few lines of HTML would be nice experience

**Comment by IvanSanchez** [comment]
@andmckvr13 The documentation is not held in HTML - rather, the HTML is generated from comments in the source code.

Do read https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md#api-documentation . And obviously, feel free to send a pull request with changes.

**Comment by erickzhao** [comment]
If @andmckvr13 doesn't take it, could I take over? I'm in the same boat as him basically.

**Comment by IvanSanchez** [comment]
@erickzhao Feel free to make a PR if @andmckvr13 doesn't say anything in a couple of days.

**Comment by andmckvr13** [comment]
@erickzaho feel free to take this one
