### ISSUE TITLE
License of logo?

### ISSUE THREAD

**Issue by simon04** [Leaflet/Leaflet#4818]
According to [LICENSE](https://github.com/Leaflet/Leaflet/blob/master/LICENSE), the source code is BSD licensed. What about the logo? Is is – or can it be – released under a license compatible with [Wikimedia Commons](https://commons.wikimedia.org/)?

cc: @jacobtoye

**Comment by danzel** [comment]
It looks like the logo was added in 707bb4624f6c6f043b6a9865910bb6ed0377b42d by @mourner
"add beautiful logo, update design (thanks to Ksenia)"

Can you shed some light on this @mourner ? :)

**Comment by mourner** [comment]
I'm not sure — I thought the BSD license acted on any repo content, including the logo? What's the advantage of having the logo licensed separately under Wikimedia Commons? Are there precedents for this in other open source projects?

**Comment by simon04** [comment]
I would like to have the logo present on Wikimedia Commons in order to include it in the [Wikipedia articles about Leaflet](https://en.wikipedia.org/wiki/Leaflet_(software)). Wikimedia Commons requires [free licenses](https://commons.wikimedia.org/wiki/Commons:Copyright_tags) for its content (including [BSD](https://commons.wikimedia.org/wiki/Template:BSD-2c-KDE)).
If the logo is BSD, everything is set. :smile:  I just wanted to clarify.

**Comment by mourner** [comment]
Ah, great! Let's leave it under BSD then. Thanks for the clarification.
