### ISSUE TITLE
Incomplet Street

### ISSUE THREAD

**Issue by juarezsantana** [Leaflet/Leaflet#4819]
Hello, I detected that the street near my house is incomplete because a street is in another street. The Satellite so you can see that the valencia street at the end meets the beautiful Street Field, and the map is wrong. Would that please be corrected this error.
Thank you! Juarez Santana
-12859771, -38452503 Google Maps
![correct map](https://cloud.githubusercontent.com/assets/21023425/17650028/f5ea8b5e-6218-11e6-9847-43888f132cdf.JPG)
![incorrect map street](https://cloud.githubusercontent.com/assets/21023425/17650031/06338e16-6219-11e6-9a46-983b01202065.JPG)

**Comment by snkashis** [comment]
Hi @juarezsantana Leaflet is a mapping library without any specific ties to basemaps, please contact your tile provider in question(Google) to fix any errors such as this.

**Comment by IvanSanchez** [comment]
Duplicate of #3896, #4661, #4332
