### ISSUE TITLE
Problem remove multiple layer from groupLayer

### ISSUE THREAD

**Issue by markpolarisdesign** [Leaflet/Leaflet#4822]
I  have a problem about the remove multiple layer in groupLayer.

if remove only one layer it's work but when i remove more than one layer 
leaflet remove only last layer. i don't know why

Assume i have an array is storageLayer = [1] , 1 is layer_id.
when i get value from storageLayer for remove. i can remove it.  but ..

storageLayer = [1,2] , 1 and 2 is layer_id.
when i get value from storageLayer for remove. leaflet remove only layer_id = 2 but layer_id = 1 can't remove from map.

Thank you for help.

Jsfiddle 
- Try click remove layer button 
- leaflet remove only blue polygon. don't remove red and blue.
- i need to remove all polygon in my array ( storageLayerId )

[http://jsfiddle.net/Pe5xU/583/](http://jsfiddle.net/Pe5xU/583/)

GIF File
[GIF](http://im2.ezgif.com/tmp/ezgif-2119747620.gif)

**Comment by perliedman** [comment]
Hi, it's hard to determine from the code you've posted if you're actually using the API as intended. Are you using `L.stamp` to access the layer's ids? It's not clear in the example above.

Also, please indicate what Leaflet version you're using.

Can you make a JSFiddle or [Playground](http://playground-leaflet.rhcloud.com/) example illustrating the problem?

**Comment by markpolarisdesign** [comment]
Oh I'm sorry.

Jsfiddle ( try click remove layer button )
[http://jsfiddle.net/Pe5xU/583/](http://jsfiddle.net/Pe5xU/583/)

**Comment by perliedman** [comment]
@markpolarisdesign I see some trouble in your code that is likely to source of the issue.

You're doing more or less this twice:

```
LayerGroupTrack["33396"] = L.layerGroup([LayerGroupTrack["33396"]]).addLayer(PolygonArea1);
```

Each time you do it, you will create a _new_ `LayerGroup`, overwriting the old one. You're effectively creating a number of layer groups which each contain a single layer. When you later remove all layers from `LayerGroupTrack["33396"]`, the `LayerGroup` will only contain the last layer you added.

From this code, I believe this is not a Leaflet issue.

**Comment by IvanSanchez** [comment]
@markpolarisdesign Don't use Leaflet 0.6.4, use something more modern (at least 0.7.7 but preferably 1.0.0-rc3). Your bug is not reproducible in these, see https://playground-leaflet.rhcloud.com/xogi/edit?html,console,output

**Comment by markpolarisdesign** [comment]
@perliedman @IvanSanchez 
Thank you very much. :)
