### ISSUE TITLE
Leaflet rc3: Marker Drag stops when Icon is updated during dragstart event

### ISSUE THREAD

**Issue by codeofsumit** [Leaflet/Leaflet#4824]
During debugging of [this issue](https://github.com/codeofsumit/leaflet.pm/issues/41) in my leaflet plugin, I found that when you change the icon of a marker inside the handler of the `dragstart` event, the event is stuck somehow inside the drag.

Here is a JS fiddle:
http://jsfiddle.net/LnzN2/190/

Disable the code that changes the marker class and the drag works fine.

**Comment by IvanSanchez** [comment]
@codeofsumit Is this the same as #4484 ?

**Comment by codeofsumit** [comment]
yup seems like it. Closed as duplicate of https://github.com/Leaflet/Leaflet/issues/4484
