### ISSUE TITLE
Games written in Leaflet?

### ISSUE THREAD

**Issue by gamb** [Leaflet/Leaflet#4831]
There are a great number of excellent plugins for Leaflet, but I wonder if there are also some *games* out there too?

I wrote [Leaflet.snake](https://gamb.github.io/Leaflet.snake/) recently, for learning purposes. I wanted to brush up on geometry, but it is also an example of how well @lhorie's Mithril.js and Leaflet can mix.

Could this be added to plugins list?

**Comment by IvanSanchez** [comment]
If this is a question about games, the answer is "this is a bug tracker, this is only for reporting bugs".

If this is a question about the plugins list, the answer is "make a pull request to add it to the list".
