### ISSUE TITLE
Incomplete map until resize

### ISSUE THREAD

**Issue by avizcaino** [Leaflet/Leaflet#4835]
Hi,

I'm trying to integrate a map in my application following the documentation. And although the code seems right, the map is not fully displayed:
 
```
    L.Icon.Default.imagePath = 'vendors/leaflet/images';

    var issuesMap = L.map('map',{
      fadeAnimation: false,
      zoomAnimation: false
    }).setView([51.505, -0.09], 13, {
      reset: true,
      animate: false
    });

    EL.basemapLayer('Topographic').addTo(issuesMap);
```
![captura de pantalla 2016-08-22 a les 15 24 12](https://cloud.githubusercontent.com/assets/12660226/17856196/978e5328-687c-11e6-9415-c59225de5738.png)

As it can be seen, the map is almost empty, just displaying a small tile at the top-left of the screen...

After the resize, the map is fully displayed:
![captura de pantalla 2016-08-22 a les 15 26 22](https://cloud.githubusercontent.com/assets/12660226/17856251/d28c9cb4-687c-11e6-95f9-56603fe92885.png)

Anyone facing the same problems?

**Comment by yohanboniface** [comment]
http://leafletjs.com/reference-1.0.0.html#map-invalidatesize is what you need.

**Comment by avizcaino** [comment]
Thanks but still not working... 

Only managed to make it work using a setTimeout, which use I want to skip at all costs...
`setTimeout(function(){ issuesMap.invalidateSize()}, 100);`

It seems that the `invalidateSize()` method is running before my map is rendered...

**Comment by perliedman** [comment]
@avizcaino check if you're running CSS animations or similar - they will of course have to complete before invalidating the size. Depending on why the map takes time before reaching its final size, `setTimeout` or a similar technique might actually be required, although listening for some kind of event is probably preferable.

Anyway, this is outside the scope of Leaflet.

**Comment by avizcaino** [comment]
@perliedman it seems is as you say... there has to be another animation that is overriding the invalidateSize method... we decided to keep with the setTimeout solution for now until we find the problem.

Thanks anyway!

**Comment by ggcaponetto** [comment]
Hello, thanks for all hints. I solved the problem with the following approach:

1. Listen to the css animation events:

`window.addEventListener("animationstart", updateLeAfletMap)
window.addEventListener("animationiteration", updateLeAfletMap)
window.addEventListener("animationend", updateLeAfletMap)`

2. then calling `map.invalidateSize()` in the `updateLeAfletMap` handler and removing the animation 
listeners after invalidating the size.

**Comment by njaros** [comment]
you can also instanciate the map 1 second after the page is rendered.
`
const mapRef = useCallback((node: HTMLDivElement | null) => {
        if (node != null && mapCtx == undefined)
        {
            setTimeout(() => {
            const map = new LeafLetMap(node);
            L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
            {
                attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'
            }).addTo(map);
            map.on("click", handleMapClick);
            var corner1 = L.latLng(40.712, -74.227),
            corner2 = L.latLng(40.774, -74.125),
            bounds = L.latLngBounds(corner1, corner2)
            map.fitBounds(bounds, {padding: [500, 500], maxZoom: 21})
            map.setView([51.505, -0.09], 13);
            
            setMap(map);
            }, 1000)
        }
    }, [])
`
I use UseCallBack but you can use whatever you want
