### ISSUE TITLE
Leaflet anchor changes on declustering

### ISSUE THREAD

**Issue by Klapsa2503** [Leaflet/Leaflet#4845]
I have an issue with custom icons. I create my markers using custom icon (setting anchor and iconSize) and everything looks at the beggining

![good](https://cloud.githubusercontent.com/assets/6784771/17973069/475ade00-6ae1-11e6-8bc5-1e2f57150621.png)

But when i do following things:
1. Open a map with clustered icons
2. Zoom out so that markers will cluster
3. Zoom in so that marker will uncluster
     and now markers are not pointing where they should.

![bad2](https://cloud.githubusercontent.com/assets/6784771/17973063/43732860-6ae1-11e6-8d05-ca9a17df5215.png)

as you see the marker and it's label looks weird and what is important is that label is in correct spot (icon is moved)

This issue is on both 0.7 and 1.0 so I would recommend to fix this on 0.7

**Comment by IvanSanchez** [comment]
Wrong repo, you probably want to report this in https://github.com/Leaflet/Leaflet.markercluster/issues instead.

**Comment by Klapsa2503** [comment]
Yeah, you are right, sorry
