### ISSUE TITLE
Using Leaflet and Plug ins with Webpack issue

### ISSUE THREAD

**Issue by proj-Hobby** [Leaflet/Leaflet#4847]
So I am new to using webpack and I am trying to create a map with leaflet and leaflet marker cluster plugin (https://github.com/Leaflet/Leaflet.markercluster). in my app.js I : `var L = require('leaflet'); require('leaflet.markercluster'); ` but when I try to create new L.markerClusterGroup I get an error  `L.markerClusterGroup is not a function` Is there an issue as to how I am importing leaflet in my app.js?
My map renders fine and I have access to L in the console.

**Comment by proj-Hobby** [comment]
I am sorry, it seems like I was using an outdated package of leaflet.markercluster and I also changed to `new webpack.ProvidePlugin` in config file for the Leaflet module.

**Comment by luffs** [comment]
If somebody else stumbles across this issue, add this to your webpack config: 
`plugins: [
      new webpack.ProvidePlugin({
        L: 'leaflet',
        'window.L': 'leaflet',
      })
    ],`

**Comment by tsalira** [comment]
> If somebody else stumbles across this issue, add this to your webpack config:
> `plugins: [ new webpack.ProvidePlugin({ L: 'leaflet', 'window.L': 'leaflet', }) ],`

Looks like I have run into a similar issue. 

This is the error am getting **Uncaught TypeError: L.tileLayer.offline is not a function** while trying to use this Leaflet offline library https://github.com/robertomlsoares/leaflet-offline 

Unfortunately, am not sure how exactly to edit the webpack config file to add that line. I have added it to the plugins array, and am still getting the error!
