### ISSUE TITLE
Some layers are not rendering

### ISSUE THREAD

**Issue by LuSilf** [Leaflet/Leaflet#4851]
http://playground-leaflet.rhcloud.com/mayu/edit?html,output

![layers](https://cloud.githubusercontent.com/assets/2908711/18005912/9551a89a-6ba5-11e6-9707-22e6a47d5cb4.gif)

Reproducible in master https://github.com/Leaflet/Leaflet/commit/9ab538143b211ba0c09623cac35b10e632939216
Appears after this commit: https://github.com/Leaflet/Leaflet/commit/8047b0b7a99ab1bed75bab7cca9c1c3a0601da87

**Comment by perliedman** [comment]
It appears that the Polygon's `_update` is called before its own renderer's `_update`, which causes it to have the wrong bounds when performing clipping.

Will have to look closer to why that is.

**Comment by perliedman** [comment]
Had a closer look. What happens is this:

* The fiddle adds a `moveend` listener to the `map`. Doing this, it ends up being listener number three for the `moveend` event
* When `moveend` fires the first time, a renderer will be created, which will also add a `moveend` listener, that will be listener number four
* Next time `moveend` is fired, the fiddle's event listener will fire before the renderer's event listener, so the renderer's bounds have not yet been updated
* The fiddle's listener adds back the layers, which will in turn call the polygon's `_reset` and `_update` methods, which will clip the polygon, but against the old bounds
* The renderer's bounds are updated, but too late

It's not entirely clear to me why this was working before, but the regression must be a result of the us changing the order listeners are called in.

**Comment by perliedman** [comment]
Some further info after some debugging by me and @yohanboniface:

The reason it worked in previous versions is something that I can only describe as a weird coincidence: If you add an event handler for the same event type within an event handler, that new event handler would under some circumstances be called _with the same event_.

This would be fine and good, and I guess we could continue implementing it like that, if it weren't for two things:

* DOM listeners don't work this way. If you add a listener within a listener, it's not called until the next time the event fires.
* Note the part above: _"under some circumstances"_ - the old event system didn't always do this, but if you added a listener _with_ a context from a listener _without_ a context, it did. This seems too weird to replicate.

**Comment by perliedman** [comment]
@LuSilf I have no idea why you're handling your layers this way, but thanks for a nice report that caught a really tricky edge case!
