### ISSUE TITLE
L.control with different layers

### ISSUE THREAD

**Issue by bkrrr** [Leaflet/Leaflet#4853]
Hello,

i have a question/feature request according to event handling.
Assuming, i have two layers and each layer has his own colormap implemented as L.control() and i want to switch/add/remove them together with the layer. Right now, i have to do something like this:

```
var layer = L.layerGroup(..) 
let info = L.control({
                  position: 'bottomright'
              }); 
   ....

info.addTo(map);
// hook an eventhandler to the map
map.on('overlayremove layerremove', removeLegend, info);

function removeLegend(e) {
    if (e.target === layer) {
        this.removeFrom(map); // jshint ignore:line
        // remove the listener itself from map
        map.off('overlayremove layerremove', removeLegend);
    }
}
```
My first question, is that right or did i miss something?
Ppl. forget always to remove listener from the map afterwards and once is not useful, because this listener is called for every layer.

I would suggest to extend once() with a simple object filter matching with e.target(or e.layer?) , so that this would become simpler to implement:
```
.....
info.addTo(leaflet);
map.once('overlayremove layerremove', layer, ()=>  info.removeFrom(map));
....
```

**Comment by IvanSanchez** [comment]
Use the `add` and `remove` events of `L.Layer` instead. See http://leafletjs.com/reference-1.0.0.html#layer-add
