### ISSUE TITLE
openPopup() during mouseover fails for circleMarkers

### ISSUE THREAD

**Issue by zorun** [Leaflet/Leaflet#4856]
I want to show a popup when hovering over a marker, and hide the popup when the mouse leaves the marker.  To do that, I use something like this (with Leaflet 0.7.7):

```
myPopup.on('mouseover', myMarker.openPopup);
myPopup.on('mouseout', myMarker.closePopup);
```

It works fine for a regular marker, but for a circleMarker, it does not work at all, and my browser (chromium 52.0.2743.116) shows the following exception:

`leaflet.js:6 Uncaught TypeError: Cannot read property 'lat' of null`

Here is a playground example reproducing the issue: http://playground-leaflet.rhcloud.com/zay/edit?html,output

Try hovering your mouser over the blue marker in the middle: it should show the pop-up.  Try hovering over the blue circle: it does not show the pop-up, and the above exception is logged in the console.  The code is identical in both cases.

Possibly related: #3280

**Comment by snkashis** [comment]
hey @zorun take a look at this, http://playground-leaflet.rhcloud.com/nuwuy/1/edit?html,output
Please note I moved you to 1.0 as that is where active development is happening.
With your original code, in 0.7.7 your marker example worked, and circlemarker failed. When I moved your original code to 1.0.0 both examples failed.My change here gets you the behavior I believe you are looking for. Take a look.

Mouse event being taken as 2nd(latlng) arg in https://github.com/Leaflet/Leaflet/blob/master/src/layer/Layer.Popup.js#L65

**Comment by johnd0e** [comment]
Close, because of lack of feedback
