### ISSUE TITLE
Angularjs leaflet how to parse string from socket

### ISSUE THREAD

**Issue by BinoJozef** [Leaflet/Leaflet#4857]
Hi everyone : 
I use spring boot with WebSocket and StompEndpointRegistry (in server side) and angularjs with sockjs in frontend connection is ok but when I receive data from socket and I want to parse it with leaflet it give me an error :

SyntaxError: Unexpected token u in JSON at position 0
How can I parse it correctly?

Data received from socket is :

{"content":"{\"features\":[{\"geometry\":{\"coordinates\":[[-9.239493333333334,32.28375666666667,0],[-9.239493333333334,32.28375666666667,0],[-9.239493333333334,32.28375666666667,0],[-9.239493333333334,32.28375666666667,0],[-9.239493333333334,32.28375666666667,0],[-9.239493333333334,32.28375666666667,0],[-9.239493333333334,32.28375666666667,0],[-9.239493333333334,32.28375666666667,0],[-9.239493333333334,32.28375666666667,0],[-9.239493333333334,32.28375666666667,0],[-9.239493333333334,32.28375666666667,0],[-9.239493333333334,32.28375666666667,0],[-9.239493333333334,32.28375666666667,0],[-9.239493333333334,32.28375666666667,0],[-9.239493333333334,32.28375666666667,0],[-9.239493333333334,32.28375666666667,0],[-9.239493333333334,32.28375666666667,0],[-9.239493333333334,32.28375666666667,0],[-9.239493333333334,32.28375666666667,0],[-9.239493333333334,32.28375666666667,0],[-9.239493333333334,32.28375666666667,0],[-9.239493333333334,32.28375666666667,0],[-9.239493333333334,32.28375666666667,0],[-9.239248333333334,32.28322,0],[-9.238626666666667,32.28317333333333,0],[-9.237216666666667,32.28408,0],[-9.236928333333333,32.28548833333333,0],[-9.238986666666667,32.287686666666666,0],[-9.23898,32.287868333333336,0],[-9.237838333333332,32.28937,0],[-9.23778,32.28940333333333,0],[-9.23778,32.28940333333333,0],[-9.23778,32.28940333333333,0],[-9.23778,32.28940333333333,0],[-9.23778,32.28940333333333,0],[-9.23778,32.28940333333333],[-6.821266666666666,33.986068333333336,0],[-6.821266666666666,33.986068333333336,0]],\"type\":\"LineString\"},\"type\":\"Feature\"}],\"type\":\"FeatureCollection\"}"}.
my leaflet function is :

$scope.getgeojson = function(datarecu){

            angular.extend($scope, {
                geojson: {
                    data: JSON.parse(datarecu.body).content,
                    style: {
                        'fillColor': '#ff0000',
                        'fillOpacity': 0.5,
                        'color': '#000000',
                        'opacity': 0.2
                    }
                }
            });

    }
thanks in advance

**Comment by IvanSanchez** [comment]
Not a leaflet bug.

**Comment by BinoJozef** [comment]
thanks for fast reply . but really i need help :(

**Comment by IvanSanchez** [comment]
This issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
