### ISSUE TITLE
maxNativeZoom ignored when set to 0

### ISSUE THREAD

**Issue by Gjum** [Leaflet/Leaflet#4858]
The value of `maxNativeZoom` is checked against this call: ([source](https://github.com/Leaflet/Leaflet/blob/f5b3cf0535fdf84a2edd68c45a51a3c42f76910d/src/layer/tile/TileLayer.js#L217))
```js
return options.maxNativeZoom ? Math.min(zoom, options.maxNativeZoom) : zoom
```
This works if `maxNativeZoom` is null, or not zero.
When it is set to zero, this call evaluates 0 to `false`, and default zooming behavior is used instead of scaling the tiles.

A possible fix would be explicitly checking for null instead, something like this:
```js
return options.maxNativeZoom !== null ? Math.min(zoom, options.maxNativeZoom) : zoom
```

I am using version `0.7.7`.

This probably caused #4527 as well.

**Comment by IvanSanchez** [comment]
This is already fixed in the `master` branch and available in 1.0.0-beta1.

Given that we're 4 issues away from 1.0.0-final, we probably won't want to backport this to 0.7.x.
