### ISSUE TITLE
Unsure if long decimal number is expected output from map.getZoom()

### ISSUE THREAD

**Issue by ttback** [Leaflet/Leaflet#4859]
http://playground-leaflet.rhcloud.com/wuho/edit?html,console,output

With delta set to 0.20, and snap at 0.10, the getZoom() can output 13.700000000000001. I am curious if this is expected. 

I'm having some viewport bound check with fractional zoom. My code checks if a layer's bounds intersect with getBounds(). It seems to break when zoom levels are decimal numbers. The bound check works fine with integer zooms but not fractional zooms. 

I have yet to make a playground with the bounds check code, but I wonder if it may have something to do with fraction zoom being a long decimal instead of 13.70, 13.80.

**Comment by IvanSanchez** [comment]
This looks like a classic [floating point number](https://en.wikipedia.org/wiki/Floating_point) rounding issue. Normally most programming languages will account for these kind of rounding errors when comparing numbers.

If you can provide a code snippet (preferible in the form of a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) or so), showing something that **obviously** breaks Leaflet, we can have a look.

If not, I'm afraid we have to send you towards [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet). We want to keep this *bug tracker* clean of things that are not bug reports.

**Comment by ttback** [comment]
@IvanSanchez i will have to create a playground to replicate the issues, so far because my codebase is a bit complex, it's hard to tell if it is my code's issues or leaflet. 

There are some odd issues with zoom level being set at 16(when calling getZoom()) but the actual zoom shown is at about level 13. This only happens after upgrade to 1.0.0 and fractional zoom is involved.

**Comment by ttback** [comment]
@mourner i figured out the problem with calling fitBounds() then setZoom()...just realize both of those functions are not immediate unless animate option is set to false, so if you setZoom in the middle of fitBounds animation, it will have inconsistent zoom value. I am not sure if that should be expected.

**Comment by IvanSanchez** [comment]
That is expected. Multiple concurrent zoom/pan/fly animations might fail, as there is no way of either queueing them or overriding them as of Leaflet 1.0.0.

**Comment by ttback** [comment]
@IvanSanchez That's reasonable. But is there any config to default to no zoom/pan/fly animation when creating the map? And only set animate to true for some of them later?
