### ISSUE TITLE
layeradd event on LayerGroup?

### ISSUE THREAD

**Issue by codeofsumit** [Leaflet/Leaflet#4861]
The functionality of my Plugin [Leaflet.PM](https://github.com/codeofsumit/leaflet.pm) gets initialized on pageload. However sometimes developers add new layers to an existing layerGroup.

Now I'm searching for a way to re-init the functionality as soon as a layer gets added to a layergroup.

Possibility 1:
Afaik, there is no `layeradd` event on LayerGroup, is this correct? That'd be all I need.

Possibility 2:
I could listen to `layeradd` on the map - but then I need to find the layerGroup(s) the newly added layer belongs to. Is there a way to do that?

Thanks in advance for any help.

**Comment by IvanSanchez** [comment]
`LayerGroup`s don't handle events. `FeatureGroup`s do.

Unfortunately these are not documented (just lacking docstrings), which should be an easy fix.

**Comment by codeofsumit** [comment]
okay that works. I'll tell the users to use featureGroups instead of layerGroups if that particular issue shows up.

FeatureGroups seem to inherit the initHooks added to LayerGroups via `addInitHook`, is that correct? If yes, I don't have to change anything :-)

**Comment by IvanSanchez** [comment]
Yeah, when a class is instantiated, it should run its `initialize()` method, then all its hooks - which means, its class init hooks, plus the init hooks of the class(es) it inherits from.

If everything is clear, I'll close this issue. Please reopen if the behaviour of LayerGroups/FeatureGroups is not as expected/documented.
