### ISSUE TITLE
Bug on tooltip with pruneCluster

### ISSUE THREAD

**Issue by wahisoufiane** [Leaflet/Leaflet#4863]
Hi,

Tootlip doesn't show up On PruneCluster till I change zoom.

**Comment by yohanboniface** [comment]
Thanks for your report, but it's missing info for us to understand, reproduce and provide a fix.
Please add a minimal working example reproducing the issue with http://playground-leaflet.rhcloud.com/

**Comment by wahisoufiane** [comment]
Hi,

I'm using Leaflet 1.0.0-rc2 and the plugin PruneCluster. When I bindTooltip to markers and add them to prunecluster, the tooltips didn't show up, but when I Unzoom or zoom, the tooltip works.

Here is a demo : http://playground-leaflet.rhcloud.com/dat/edit?html,js,console,output

**Comment by IvanSanchez** [comment]
This bug tracker is for core Leaflet bugs. Please report this bug in the [https://github.com/SINTEF-9012/PruneCluster/issues](PruneCluster repo) instead.
