### ISSUE TITLE
Slow performance with many popups

### ISSUE THREAD

**Issue by Fouks1** [Leaflet/Leaflet#4867]
I have a dataset of about 70,000 features (LineString) ,  and i am seeing a bad performance in all browsers.

Is there any way to show smoothly the popups on click event ?

I am using geojson-vt and the example from [here](http://bl.ocks.org/Sumbera/c67e5551b21c68dc8299) to add the tiles to the leaflet map.

i tried this but the map keep freezing , so its possible to add too many popups to the leaflet map ?
```
function onEachFeature(feature, layer) {
    layer.on('click', function(e) {
        layer.bindPopup(feature.properties.NUMERO);
    });
}

L.geoJson($scope.dataOfFile.data, {
    onEachFeature: onEachFeature
}).addTo(map);
```

**Comment by IvanSanchez** [comment]
However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

I see that you've already asked this in https://stackoverflow.com/questions/39202528/display-popups-with-leaflet-large-dataset, so please understand you won't get a quicker answer here.

**Comment by Duskfen** [comment]
@IvanSanchez  but he has a point... 
using a lot of markers with (closed!) popups produces jank
