### ISSUE TITLE
How to get all markers in the map to close tooltip?

### ISSUE THREAD

**Issue by hkcity1111** [Leaflet/Leaflet#4870]
I am new commer in leaflet.js and I want to hide all tooltip for each marker if zoom level > certain value and show all tooltip for each marker. So I intend to get all marker in the map first and call marker.closeTooltip . I search stackoverflow and amend with the following code to get all the markers. But I got the error on L.map._layers.
Do someone help me for the direction to change the coding? 
Thanks a lot.
```
function getAllMarkers() {
    var allMarkersObjArray = []; // for marker objects

    $.each(L.map._layers, function (ml) {
        if (L.map._layers[ml].feature) {
            allMarkersObjArray.push(this)
        }
    })
    console.log(allMarkersObjArray);
}
```

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
