### ISSUE TITLE
redraw() throws "Invalid pointer" on IE11/Edge when using large urls (6000 characters)

### ISSUE THREAD

**Issue by sjsafranek** [Leaflet/Leaflet#4872]
redraw() throws "Invalid pointer" on IE11/Edge when using large urls (~6000 characters)
I am using large urls to tell a dynamic tile server what interpolated colors to use.

Leaflet version 0.7.7

File: leaflet.js, Line: 2930, Column: 3  -->  _loadTile
File: leaflet.js, Line: 2958, Column: 3  -->  _tileOnLoad

The culprit seems to be this.src within the _loadTile and _tileOnLoad functions. After some research I found the following article:

**An "Invalid Pointer" script error message may be displayed in Internet Explorer 8**
https://support.microsoft.com/en-us/kb/2688188

I was able to patch this error in my local copy of Leaflet-0.7.7 by replacing "this.src" with "this.attributes.src.value" in both of these functions.

**Comment by yohanboniface** [comment]
Can you try with latest master?
