### ISSUE TITLE
Street view error

### ISSUE THREAD

**Issue by AnujSengar** [Leaflet/Leaflet#4873]
leaflet-google.js is giving error for street view, **Sorry we have no imagery here**. It was working well till last night. Sudden error is very annoying. Satellite view working fine.Please help!!

**Comment by IvanSanchez** [comment]
This is the repository for the core Leaflet code only, we don't handle plugins or extensions such as `leaflet-google`. Find the right repo, and file the bug there. (Also make sure to provide a reproducible example).

**Comment by AnujSengar** [comment]
Thanks Ivan. nut still some help is appreciated.
streetLayer = new L.Google('STREETS', { maxZoom: 18 })
	var center = new Array();
	center[0] = 20.5937;
    center[1] = -78.9629;
	map = L.map('map')
          .setView(center, 3);
	showLayer(map,streetLayer);

this is the code which was working, but giving error now.

**Comment by danzel** [comment]
See Ivans response above. Locking
