### ISSUE TITLE
Make tiles show up while swiping

### ISSUE THREAD

**Issue by aoyama-val** [Leaflet/Leaflet#4878]
Hi,

On a mobile browser, tiles don't show up while swiping, that is, until you lift your finger off the screen. This behavior is different from dragging on a desktop browser, and I feel desktop's behavior better UX.
I tried calling `L.GridLayer#_onMoveEnd` on `move` event, and it looked working. Do you think this causes any problem?

```
diff --git a/src/layer/tile/GridLayer.js b/src/layer/tile/GridLayer.js
index 9cf0924..7340ee8 100644
--- a/src/layer/tile/GridLayer.js
+++ b/src/layer/tile/GridLayer.js
@@ -224,6 +224,7 @@ L.GridLayer = L.Layer.extend({
                        viewprereset: this._invalidateAll,
                        viewreset: this._resetView,
                        zoom: this._resetView,
+                       move: this._onMoveEnd,
                        moveend: this._onMoveEnd
                };
```

**Comment by aosho235** [comment]
I didn't know `updateWhenIdle`... This is what I wanted.
But what kind of performance issue does this option cause? I didn't notice any.

**Comment by aoyama-val** [comment]
I didn't know `updateWhenIdle`... This is what I wanted.
But what kind of performance issue does this option cause? I didn't notice any.

**Comment by IvanSanchez** [comment]
Creating new tiles involves creating new DOM elements and modifying the DOM tree, which in some slow mobile devices can cause a noticeable delay.
