### ISSUE TITLE
Marker events are not propagated to map

### ISSUE THREAD

**Issue by dnsBlah** [Leaflet/Leaflet#4882]
As the title mentioned, I made some markers, and drawing polylines in between.

I did put a click function in for zoom on click:
```
    map.on("click", function(e) {
        map.setView(e.latlng, map.getZoom() + 2);
    });
```

This is not being triggered when I click on a marker, but it does when clicking on polylines.
(I have popup on polylines, and would rather not to have it zooming when I click the polyline)

**Comment by IvanSanchez** [comment]
So it appears that while `L.Path` interactive events are propagated to the map as documented and expected for 1.0.0, the same is not true for markers. A marker's `click` event is not propagated into the map, while a `click` event on a polyline is propagated, which makes the event propagation inconsistent.

(On a side note, the OP's problem is just a lack of `L.DomUtil.stopPropagation`, which highlights the need for #4239)

Playground demo'ing the issue:
https://playground-leaflet.rhcloud.com/mawe/edit?html,console,output

This *sounds* like an easy task of running `addEventParent` to `L.Marker`s when added to a map, but I'll let our event expert @yohanboniface weight in.

**Comment by yohanboniface** [comment]
Humm, but that's expected behaviour https://github.com/Leaflet/Leaflet/blob/master/src/layer/marker/Marker.js#L63 :)

**Comment by IvanSanchez** [comment]
@yohanboniface Should we set events on `L.Path`s non-bubbly as well?

**Comment by dnsBlah** [comment]
@IvanSanchez how is your sample not zooming on the line?
I see you don't have zoom on click, on the double click zoom.

Also I work with a json file with my lines.
```
var drawPolyline = function(pointList, tColor, tWeight = 3, tOpacity = 0.5) {
        var tLine = new L.Polyline(pointList, {
            color: tColor,
            weight: tWeight,
            opacity: tOpacity,
            smoothFactor: 1
        });
        return tLine;
    }
```

Load links, and draw
```
$.getJSON("/map/getLinks", function (jsonLinks) {
        $.each(jsonLinks, function(index, d){
            var pointA = new L.LatLng(d.fromLat, d.fromLng);
            var pointB = new L.LatLng(d.toLat, d.toLng);
            var pointList = [pointA, pointB];

            drawPolyline(pointList, d.color, 3, 1)
                    .bindPopup("<h3 id=\"popupTitle\">Connection Status</h3><br>State: </b>" + d.state + "</b><br>Between <u>" + d.fromLocation + "</u> and <u>" + d.toLocation + "</u>")
                    .addTo(map);
        });
    });
```

And using this to zoom on 'single click / tap' 
```
map.on("click", function(e) {
        map.setView(e.latlng, map.getZoom() + 2);
    });
```

**Comment by IvanSanchez** [comment]
@dnsBlah This is an event bubbling/propagation issue, not a zooming issue. Read the docs for `L.DomUtil.stopPropagation`.

**Comment by yohanboniface** [comment]
@IvanSanchez according to [this discussion](https://github.com/Leaflet/Leaflet/pull/3605#issuecomment-119594089) that was not the @mourner's preference.
My own preference would have been to only stop propagation when we actually use the click event internally (like in bindPopup), because it's closer to DOM behaviour, but I understand that may not be super user friendly (many people needing to add a stopPropagation each time they listen to a click).

**Comment by dnsBlah** [comment]
@IvanSanchez  could you please provide a simple example?

**Comment by yohanboniface** [comment]
@dnsBlah now reading your initial issue:

```
polygon.on('click', function (e) {
   L.DomEvent.stopPropagation(e);
   // Do your normal stuff here
}
```

Per my understanding, we can close here.

**Comment by dnsBlah** [comment]
Hi @yohanboniface 

Thanks, so I understoud that I just put this in the main script of my page.
```
map.on("click", function(e) {
        map.setView(e.latlng, map.getZoom() + 2);
    });
    
    polygon.on('click', function (e) {
        L.DomEvent.stopPropagation(e);
        // Do your normal stuff here
    });
```

It's still zooming. I also tried polyline, L.Polyline, etc
It still zooms :-(

**Comment by IvanSanchez** [comment]
@yohanboniface I'd say "let's add some docStrings to `nonBubblingEvents` so users can tweak the behaviour", but maybe things on `L.Renderer`s would get tricky?

Letting the user enable event bubbling on markers sounds sane to me, but if @mourner has an opinion about keeping the current behaviour, then I'd just rather document it.

**Comment by dnsBlah** [comment]
Let me please be clear, when I remove the code:
```
map.on("click", function(e) {
        map.setView(e.latlng, map.getZoom() + 2);
    });
```

it's not zooming when I click the polyline, for the popup..

But I need the single-click zoom. But may not be triggered when I click on a polyline

**Comment by dnsBlah** [comment]
```
var drawPolyline = function(pointList, tColor, tWeight = 3, tOpacity = 0.5) {
        var tLine = new L.Polyline(pointList, {
            color: tColor,
            weight: tWeight,
            opacity: tOpacity,
            smoothFactor: 1
        });
        tLine.on("click", function(e) {
           L.DomEvent.stopPropagation(e);
        });
        return tLine;
    }
```

Also did the trick, thanks guys!

**Comment by yohanboniface** [comment]
Making a suggestion:
- keep it as is (maybe more doc yeah) for 1.0, to facilitate the upgrade and stay focus, not doing such potentially impacting change after rc3
- remove `nonBubblingEvents` in 1.1, making the Leaflet event system closer to DOM natural behaviour; so maybe a bit less user friendly on first look, but in the meantime much more simple to understand/explain/document, given that such an exception may create more trouble than anything in the long term, by making the API less consistent

One may answer that 1.0 is breaking party, but… ;)

Thoughts?
