### ISSUE TITLE
contextmenu events on touch don't reset properly

### ISSUE THREAD

**Issue by kaynz** [Leaflet/Leaflet#4884]
Hi!

Touch support seems to be broken on latest leaflet rc3. I can reproduce the bug on http://leafletjs.com/examples/quick-start-example.html

Here's a small screencast to show you the problem:
https://youtu.be/7_9zwz1bz3k

My Steps:
0. Open Developer Console in Chrome, select a device (Nexus 6 in my example)
1. Set a listener to `contextmenu` which adds a marker to event.latlng
2. Do left click (everything ok)
3. Do long press left click (everything is ok, marker is added to map on position event.latlng)
4. Do right click on the position of the first marker.

After 4 you see that the (new right click) marker is being placed somewhere else.

**Comment by kaynz** [comment]
Maybe this bug is related to this one: https://github.com/Leaflet/Path.Drag.js/issues/5

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by kaynz** [comment]
Sure: https://playground-leaflet.rhcloud.com/hebi/1/edit?html,output

Don't forget to enable device mode.

**Comment by IvanSanchez** [comment]
Weird. Looks like the `contextmenu` hack is forgetting to send a `mouseup` event, so when I try to drag, I pinch-zoom instead.

**Comment by kaynz** [comment]
Maybe the refactoring of @perliedman lead to this behaviour?

**Comment by yohanboniface** [comment]
Is that two-fingers/right click ever worked? At least, I can see the same (broken) behaviour when using beta1: https://playground-leaflet.rhcloud.com/pewe/edit?html,output

**Comment by kaynz** [comment]
@yohanboniface It worked at revision 4460bd74ad745efe23ff1d68bc4de2041a15b746.

**Comment by yohanboniface** [comment]
I may be missing something, but I'm seeing the exact same behaviour at this revision, i.e. when doing a right click the marker is always added to the same position but not where I've made the right click.

**Comment by kaynz** [comment]
Hm, yeah, you're right :o

**Comment by perliedman** [comment]
So, this looks like a bug, but I would say it's not a blocker since:

* I can reproduce it even in 1.0.0-beta.1
* I can't reproduce it in 0.7.7, but a right click actually brings up the browser's context menu, it doesn't add a marker

So, we should fix this, but perhaps not high priority.

**Comment by johnd0e** [comment]
This bug is pretty old. Could someone to reproduce it with modern browser?

I failed, but that can depend on numerous factors, including buggy Chrome touch simulation, or buggy `tap` handler..
Please reopen if it is still reproducible.
