### ISSUE TITLE
What exactly is closestPointOnSegment returning?

### ISSUE THREAD

**Issue by codeofsumit** [Leaflet/Leaflet#4885]
The description in the 1.0 docs says:
```
Returns the closest point from a point p on a segment p1 to p2.
```

But that confuses me a bit. Does it return the closest coordinate given to the segment (either p1 or p2) to p?
Or does it actually calculate the closest point ON the segment ((possibly) between p1 and p2) to p?

From my tests it seems like it's the first one but to me, the docs suggest the second one.
Also if it's the first one, couldn't you just calc the distance from p to p1 and p2 and compare?

Could someone clarify this real quick?

**Comment by IvanSanchez** [comment]
This has the same semantics as every other GIS out there - check out e.g. http://postgis.net/docs/ST_ClosestPoint.html

If you can find a nice definition (i.e. wikipedia or similar) of this, please do amend the documentation to add a link.

**Comment by codeofsumit** [comment]
thanks for the link. So (just to make sure) it has to be the second: 
```
Or does it actually calculate the closest point ON the segment ((possibly) between p1 and p2) to p?
```
which means I have an error somewhere.
Thanks! If I do find a clearer definition I'll amend the docs.
