### ISSUE TITLE
issue in get directions

### ISSUE THREAD

**Issue by kashifiqbal001** [Leaflet/Leaflet#4887]
Dear leaflet team
i am facing this issue while getting direction using any travel mode, 
"this._altContainer is undefined"

kindly help me

**Comment by perliedman** [comment]
This does not sound like a problem with Leaflet, but perhaps with [Leaflet Routing Machine](https://github.com/perliedman/leaflet-routing-machine). You can try to report an issue there.

However, you need to provide more information, preferably with running code, to be able to track down the problem.
