### ISSUE TITLE
map freezes briefly before trackpad dragend

### ISSUE THREAD

**Issue by meetar** [Leaflet/Leaflet#4889]
**TO REPRODUCE:**
- load any Leaflet map with panning inertia
- drag the map with a touchpad and release while dragging

**RESULT:**

The map will freeze immediately at the `dragend` event for about a half-second, then unfreeze and continue any drag-inertia animation.

![inertia](https://cloud.githubusercontent.com/assets/459970/18315116/d151b8ca-74e3-11e6-855c-f5e475b3a507.gif)

**EXPECTED RESULT:**

No freeze.

**ENVIRONMENT:**

Seen in Chrome, FF, and Safari on Mac OS, using Leaflet v1.0.0-rc.1. Not seen when using a regular mouse.

**COMMENTS:**

I assume it's related to the way the OS detects the end of a trackpad drag.

**Comment by mourner** [comment]
Might have been something that was fixed in the final version — no longer reproducible .
