### ISSUE TITLE
Mobile app performance issue

### ISSUE THREAD

**Issue by xklusive** [Leaflet/Leaflet#4893]
Hi,

We have a problem with an mobile app that we are developing. 
We encounter a problem with performances.

In fact, We try to build an app with an interactive metro map that might have 350 markers if not more. Because it is an image, not a map, my 350 markers are always displayed. No matter what the user does, zooming in, zooming out, moving the map...performances are impacted...the app becomes very slow...Any action requires a recalculation of the marker positions (We think). 

We thought about clusters but because we are on an app, we do not need to zoom out significantly.

Does anyone have any clue to solve the issue?

Regards

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
