### ISSUE TITLE
Zooming out doesn't clear the cache of leaflet in the previous box

### ISSUE THREAD

**Issue by abatany** [Leaflet/Leaflet#4895]
I am working with leaflet to create a site map for my business.
It seems we have a little problem when we zooming out : the cache of the previous zoom is still on the map like this : 

![image1](https://cloud.githubusercontent.com/assets/22076185/18387037/730e6c0a-769a-11e6-8a48-8ad2a3c2612e.jpg)

Is this caused by leaflet?

Thank you, 

Aurélie

**Comment by IvanSanchez** [comment]
Can't tell without looking at the layers setup, but I bet it's a user error, and not a Leaflet bug (and may I remind again that this issue tracker is for Leaflet bugs and features **only**. Please. Pretty please).

Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by abatany** [comment]
Sorry, I am new in GitHub. 
After other tests I have found the problem, it was because all the layers were loaded with tiles that take a lot of times. We use the plugin [Leaflet.NonTiledLayer](https://github.com/ptv-logistics/Leaflet.NonTiledLayer)  which gets the imagery for the complete map viewport whenever it changes.  This plugin has resolved the problem.
Thank you for your help and for the fiddle site.

Aurélie

**Comment by IvanSanchez** [comment]
Slow tileservers were being used so tiles were not being pruned quickly → not a leaflet bug → closing.
