### ISSUE TITLE
Do not perform default action on un-trusted events

### ISSUE THREAD

**Issue by andygup** [Leaflet/Leaflet#4896]
Reference: 

``` javascript
I/chromium: [INFO:CONSOLE(11091)] "A DOM event generated from JavaScript has triggered a default action inside the browser. This behavior is non-standard and will be removed in M53, around September 2016. See https://www.chromestatus.com/features/5718803933560832 for more details.", source: https://cdn.jsdelivr.net/leaflet/1.0.0-rc.3/leaflet-src.js (11091)
```

[Chrome link](https://www.chromestatus.com/features/5718803933560832)

Code reference `leaflet-src.js` line 11091:

``` javascript
    _simulateEvent: function (type, e) {
        var simulatedEvent = document.createEvent('MouseEvents');

        simulatedEvent._simulated = true;
        e.target._simulatedClick = true;

        simulatedEvent.initMouseEvent(
                type, true, true, window, 1,
                e.screenX, e.screenY,
                e.clientX, e.clientY,
                false, false, false, false, 0, null);

        e.target.dispatchEvent(simulatedEvent);
    }
```

Reproducible on:

   Android 6.0.1 
   Android System Webview 52.0.2743.98

**Comment by IvanSanchez** [comment]
@andygup What triggers this? Touch drags, touch pinches, or something else?

Also, do you happen to have a stack trace of calls to `_simulateEvent`? At first glance, that only happens on long presses on touch (`src/map/handler/Map.Tap.js`), but I'd like to be sure. This might be related to #4884, or at least affect the same code region.

This is going to be a pain in the arse, as we kinda depend on prosthetic-hand (a library that triggers synthetic events) for some unit tests. I hope chrome/chromium will have some kind of flag to still allow defaults on synthetic events.

**Comment by andygup** [comment]
>> What triggers this?

In my case, I believe it's being triggered by touch drags while the browser is under load. I'm working on performance testing and was inducing high browser CPU usage while adding points to the map and doing touch drags. It's possible that under high CPU load the touch drag is being interpreted as a long press due to event processing delays.

>>Also, do you happen to have a stack trace of calls to _simulateEvent?

Nope, sorry. I only have the Android logcat dump included above. The error just kinda showed up out of nowhere, and now I've seen it a half dozen times.

**Comment by IvanSanchez** [comment]
Ah, OK, you're using a bleeding edge WebView and not a vanilla browser. We might need to blindly implement this, or wait until the warning hits Chrome beta, then.

**Comment by andygup** [comment]
Yah, FWIW it's the default WebView from the early-August security update on Android 6. The next version of WebView (v53) is now available and shipping with Android 7.

Yeh, this behavior is visible in plain old Cordova and Ionic.

**Comment by rikkitikkitumbo** [comment]
Any fix for this?  It's really making my app un usuable

**Comment by rikkitikkitumbo** [comment]
I don't know where my other comment went, but I'm getting this same error.  I think it has something to do with line 4257 on leaflet77js if that helps anyone
