### ISSUE TITLE
L.tooltip Strange Layout

### ISSUE THREAD

**Issue by WangJi** [Leaflet/Leaflet#4897]
When binding tooltip to markers that are close to one another,  it does not align to the marker, see the pic below:
![image](https://cloud.githubusercontent.com/assets/5742670/18405292/8c9f3dc8-7723-11e6-8f72-82c7434bb937.png)

It seems tooltip adjusts its position to avoid overlap. How to avoid this?

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by WangJi** [comment]
Well, it turns out that when updating to the latest leaflet@1.0.0-rc.3,  I forgot to replace css file. 
Really embarrassing.

**Comment by WangJi** [comment]
It works fine now.
https://playground-leaflet.rhcloud.com/yoj/1/edit?html,console,output
