### ISSUE TITLE
Image not showing on Hover but on click popup working, what I need to show both actions 

### ISSUE THREAD

**Issue by kuntalparbat** [Leaflet/Leaflet#4898]
What I want to make is to show an image on hover on draw layer (it can be marker, poligon, anything) and on click show a popup with GEOjson Property. I can manage to show popup but not able to show image on hover. Those are visible on console.log but on screen not appearing. 
Please help me and very sorry for my bad English.

`var drawControl = new L.Control.Draw(options);
map.addControl(drawControl);

var myGeometry = '{"type":"Feature","properties":{"title":"My school","message":"This is description","school":"DPS School","name":"Rehul Pal","class":"iV"},"geometry":{"type":"Point","coordinates":[88.43603074550629,22.570362143570495]}}';

var myGeoJSON = JSON.parse(myGeometry);

//switcher to add all functions to each feature (department)
        function onEachFeature(feature, layer)
        {
            layer.on({
                click: htmlData,
                mouseover: highlight,
                mouseout: resetHighlight,
                
            });

        }
function htmlData(e){
        var layers = e.layers;
            html = '';
            var html = "<div style='float:left'>" +"Tis is POPUP"  +
                    "</div>" +
                    "<div style='clear:both'></div>"

            var options = {minWidth: 500}
            this.bindPopup(html, options);
        console.log(html, options);

}
        function highlight(e)
        {
            var layers = e.layers;
            images_url ='';
            var images_url = "<div class='hover_img'><img src='http://127.0.0.1/CUSTOM/images/geo-point.png'></div>";
            this.bindPopup(images_url);
              console.log(images_url);
        }

        function resetHighlight(e)
        {
           this.bindPopup();
        }

var geoJsonGroup = L.geoJson(myGeoJSON, {
                onEachFeature  }).addTo(map);

addNonGroupLayers(geoJsonGroup, drawnItems);

// Would benefit from https://github.com/Leaflet/Leaflet/issues/4461
function addNonGroupLayers(sourceLayer, targetGroup) {
    if (sourceLayer instanceof L.LayerGroup) {
    sourceLayer.eachLayer(function (layer) {
        addNonGroupLayers(layer, targetGroup);

    })
  } else {
    targetGroup.addLayer(sourceLayer);
  }
}
`

**Comment by yohanboniface** [comment]
Hi, great to hear that you use Leaflet!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
