### ISSUE TITLE
Map gets initialized past maxZoom level when adding tileLayer with maxZoom smaller than initial zoom

### ISSUE THREAD

**Issue by theashyster** [Leaflet/Leaflet#4915]
Hello,
I am not sure if this is an issue or it is the way it is supposed to work, because I can reproduce it in nearly every version of `Leaflet`.

When initializing the `map` I pass the option `zoom` to be `19`, later on I add a `tileLayer` to show my base layer and that by default has a `maxZoom` option set to `18` in `Leaflet`.

When the `map` is shown I get a `map` without the base layer shown and by pressing `zoomOut` on `zoomControl` the base layer is shown on the `map` (no matter if I enter `19` or `100` as my initial `zoom` level).

I see the point that this could be the way it is supposed to work, since you can control the init `options` of the `map` and set the `zoom` level that is not bigger than the `maxZoom` for `tileLayer`. On the other hand though if I run `map.setView(center, zoom);` after the `tileLayer` is added to the `map` with the same `zoom` level `19` it sets the `map` to the max zoomed in state and does not go any `zoom` levels further.

Demo time http://playground-leaflet.rhcloud.com/waxem/edit?html,output

The `map` will first load without the base layer, pressing the `setView` button will add the base layer.

**Comment by IvanSanchez** [comment]
Hhhmmm. Sounds half expected behaviour, half bug.

@theashyster Can you trace through the code and see if the `setMaxZoom` method of `L.Map` is getting called when the tilelayer is added? I think it *should* but *doesn't* run.

Otherwise, we are aware the wording of the `maxZoom`/`minZoom` documentation is a bit confusing, see #4643.

**Comment by theashyster** [comment]
Okay, I see.

@IvanSanchez For me it looks like the `setMaxZoom` method is not called when tile layer is added, nor when the `setView` button is pressed. Look here http://playground-leaflet.rhcloud.com/zuk/edit?html,output

Thanks for the documentation reference.
