### ISSUE TITLE
CircleMarker.setStyle() does not respect changes in radius. Do I need to re-plot markers.   

### ISSUE THREAD

**Issue by jainruchi** [Leaflet/Leaflet#4920]
I create circleMarker with some radius and then I update radius using setStyle() method but updated radius is not reflecting on my map. Do I need to re-plot markers?

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by jainruchi** [comment]
@IvanSanchez Hi, here is my link 
http://jsfiddle.net/fnewx6hw/

In this example I have created three circleMarkers on map with default radius 12. There is button change radius on top of map div. On clicking that button i am updating style of circleMarker using setStyle() method. But it is updating radius in options of circleMarker but not reflecting change in radius on map.

**Comment by IvanSanchez** [comment]
@jainruchi That fiddle is using Leaflet v0.4.5.

Is this reproducible in 1.0.0-rc3?

**Comment by jainruchi** [comment]
Ohh!! I am sorry, I was working on previous version. It is not replicating in newer version. Thanks for support

**Comment by jainruchi** [comment]
In version 1.0.0-rc3, above issue gets resolved but events are not working. Here is jsfiddle link in which I have attached mouseover event and console,log in its call back function but it is not working.
http://jsfiddle.net/fnewx6hw/4/
