### ISSUE TITLE
Map tiles not loading if setView() is used inside a PHP page

### ISSUE THREAD

**Issue by tbrcrl** [Leaflet/Leaflet#4921]
Hello, 
we found that the tiles do not load (only part of one tile is actually loaded as shown in the attached picture) when we embed the code inside a PHP page. The problem is browser independent. The OS is Win 10 64bit.  The structure of the used code is very basic and is as follows 

```javascript
<head>
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.0-rc.3/dist/leaflet.css" />
</head>
<body>
  <!--  PHP and HTML code here -->
  <script src="https://unpkg.com/leaflet@1.0.0-rc.3/dist/leaflet.js"></script>
  <script>
  $(document).ready(function() {
  var map = L.map('map').setView([51.505, -0.09], 13);
  L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
      attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
  }).addTo(map);  
    <!--  other JS code here -->
  });
  </script>
</body>
```

In order to help troubleshooting I can say that the tiles **load correctly**
1. as soon as **the browser windows is resized**
2. if the statement 
**var map = L.map('map').setView([51.505, -0.09], 13);**
is replaced by
var map = L.map('map');
**map.locate({setView: true, maxZoom: 16});**
3. if the same code (I mean with **setView()) is used in a pure HTML page**

As workaround we are using the statement
map.locate({setView: true, maxZoom: 16});
in place of
 L.map('map').setView([51.505, -0.09], 13);
but this is not the optimal solution as the map is not centered were we would like.

Thanks in advance for any suggestion.

![screenshot 169](https://cloud.githubusercontent.com/assets/16580030/18607594/9cbfefd2-7cd1-11e6-86dc-0912d170ce31.png)

**Comment by IvanSanchez** [comment]
Just initialize the map **after** the code that resizes your map container has run, or run `map.invalidateSize()` when appropiate.

**Comment by ghybs** [comment]
See https://stackoverflow.com/questions/36246815/data-toggle-tab-does-not-download-leaflet-map/36257493#36257493

**Comment by tbrcrl** [comment]
Thanks to @IvanSanchez and @ghybs, for the answer, in the following the test I did.
1. Concerning "initialize the map after the code that resizes your map container has run", yes we are using Boostrap, but I am not aware of any intentional resize of the map container. However I moved the following basic code in an external script that is called at the end of the page, so after all the possible  code that resizes the map container. The problem still persists.
```javascript
$(document).ready(function() {
var map = L.map('map').setView([51.505, -0.09], 13);

L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);

L.marker([51.5, -0.09]).addTo(map)
    .bindPopup('A pretty CSS3 popup.<br> Easily customizable.')
    .openPopup();
    
});
```
2. Concerning "run map.invalidateSize() when appropiate", always in the external script I used the following code. The problem still persists.
```javascript
$(document).ready(function() {

var map = L.map('map').invalidateSize(true);

map.setView([51.505, -0.09], 13);

L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);

L.marker([51.5, -0.09]).addTo(map)
    .bindPopup('A pretty CSS3 popup.<br> Easily customizable.')
    .openPopup();
    
});
```
3. To be sure to assign the proper dimensions to the map container, in the external script I also initialized the map container dimensions as follows, and also in this case the problem still persists.
```javascript
$(document).ready(function() {

$('#map').css({"height": "500px", "width": "100%"});

var map = L.map('map').setView([51.505, -0.09], 13);

L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);

L.marker([51.5, -0.09]).addTo(map)
    .bindPopup('A pretty CSS3 popup.<br> Easily customizable.')
    .openPopup();
    
});
```
At this point in time I am really running out of ideas.
May be that understanding why setView() is not working while map.locate({setView: true, maxZoom: 16}) yes, can help?

**Comment by ghybs** [comment]
`map.locate` is asynchronous, so it will apply the `setView` after a short delay that is enough for your map container to get its final size.

At least try to perform `map.invalidateSize()` in a `setTimeout`, if you are really not able to track down when your container is resized.

**Comment by tbrcrl** [comment]
@ghybs 
I tested the following code, but without success
```javascript
$(document).ready(function() {
var map = L.map('map');

setTimeout(function(){ map.invalidateSize(true)}, 300);

map.setView([51.505, -0.09], 13);

L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);
    
});
```
I will see if am able to post some demo because there is a lot of JS and PHP code and I need to restrict the area of the possible cause.
Thanks
