### ISSUE TITLE
Slider on mobile moves the map while sliding

### ISSUE THREAD

**Issue by juliagreig** [Leaflet/Leaflet#4924]
I have a map with an opacity slider in the top right to slide between two images. in iPad and iPhone chrome and safari, the action of sliding the slider counts as a tap and drag on the map, so the map moves along with the slider. The opacity still changes, and the images still switch.

Let me know if you need more information. Thank yoU!

**Comment by IvanSanchez** [comment]
Bug is caused by a UI component which is not part of the Leaflet core, so this cannot be accepted as a core leaflet bug.
