### ISSUE TITLE
getBoundsZoom from API 0.7.7 to API RC3

### ISSUE THREAD

**Issue by Dot2122** [Leaflet/Leaflet#4927]
Hi,
Currently, I’m working to migrate API Leaflet from the version 0.7.7 to RC3. I use too the api proj4 in my application to create a CRS.
In my app, when I want zoom by box, zoom level return 0 (each time).
After looking for in the source code, I founded the problem in the function getBoundsZoom.
I think the problem is beetwen API Leaflet and values of CRS (define by proj4).

For information, the old version got this : (working well)
```
getBoundsZoom: function (bounds, inside, padding) { // (LatLngBounds[, Boolean, Point]) -> Number
		bounds = L.latLngBounds(bounds);
		padding = L.point(padding || [0, 0]);
		var zoom = this.getZoom() || 0,
		    min = this.getMinZoom(),
		    max = this.getMaxZoom(),
		    nw = bounds.getNorthWest(),
		    se = bounds.getSouthEast(),
		    size = this.getSize().subtract(padding),
		    boundsSize = this.project(se, zoom).subtract(this.project(nw, zoom)),
		    snap = L.Browser.any3d ? this.options.zoomSnap : 1;
		var scale = Math.min(size.x / boundsSize.x, size.y / boundsSize.y);
		zoom = this.getScaleZoom(scale, zoom);
		if (snap) {
			zoom = Math.round(zoom / (snap / 100)) * (snap / 100); // don't jump if within 1% of a snap level
			zoom = inside ? Math.ceil(zoom / snap) * snap : Math.floor(zoom / snap) * snap;
		}
		return Math.max(min, Math.min(max, zoom));
	}
```

The new version got this : (not working well)
```
getBoundsZoom: function (bounds, inside, padding) { // (LatLngBounds[, Boolean, Point]) -> Number
		bounds = L.latLngBounds(bounds);
		var zoom = this.getMinZoom() - (inside ? 1 : 0),
		    maxZoom = this.getMaxZoom(),
		    size = this.getSize(),
		    nw = bounds.getNorthWest(),
		    se = bounds.getSouthEast(),
		    zoomNotFound = true,
		    boundsSize;
		padding = L.point(padding || [0, 0]);
		do {
			zoom++;
			boundsSize = this.project(se, zoom).subtract(this.project(nw, zoom)).add(padding);
			zoomNotFound = !inside ? size.contains(boundsSize) : boundsSize.x < size.x || boundsSize.y < size.y;
		} while (zoomNotFound && zoom <= maxZoom);

		if (zoomNotFound && inside) {
			return null;
		}
		return inside ? zoom : zoom - 1;
	}
```

Am I clear ? If you want more information, ask me.

Do you have any solution ?

Thanks.

**Comment by IvanSanchez** [comment]
This is a bit hard to understand. Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

Also, if you are proposing code changes, please make a pull request for them - it's much easier to review them that way.

**Comment by Dot2122** [comment]
Thanks for your answer,

For see the problem: http://playground-leaflet.rhcloud.com/pec/edit?html,output
Try to do zoom by box (using key "MAJ/SHIFT")

It's not a new proposition, but the code in the API 0.7.7 and the code in API RC3. Do I pull request?

**Comment by Dot2122** [comment]
UP :
I think, i found the issue.
I update the version of the API pro4j in 1.0.0-beta.2 and now it's work.

The solution is because in version 1.0.0-beta.1, they didn't implement a function zoom in L.proj.CRS and by default L.CRS.zoom. In the new version, they implement it. L.proj.CRS.zoom.

Thanks.
