### ISSUE TITLE
Paths rendered by canvas are disappear after map move.

### ISSUE THREAD

**Issue by LuSilf** [Leaflet/Leaflet#4928]
http://playground-leaflet.rhcloud.com/dep/1/edit?html,output
Move a map.

Reproducible in master and rc2.
rc3 and rc1 are fine.

**Comment by IvanSanchez** [comment]
A `git bisect` points to ed1a612e6fc4084f6d39899c83f8d9ce1195250a

**Comment by IvanSanchez** [comment]
This also seems to affect `debug/vector/vector-canvas.html`. This involves some event trickery I'm not familiar with, so I hope @perliedman can shed some light when he has the time.

**Comment by IvanSanchez** [comment]
@LuSilf Would you please look at #4929, and try that? The changes seem to solve this bug, but I would like you to test if it works also for your use case in #4851.

**Comment by LuSilf** [comment]
@IvanSanchez Seems that all working fine. Thanks a lot!

**Comment by perliedman** [comment]
@IvanSanchez good catch, makes total sense to not fire until the overridden `_update`s have completed.
