### ISSUE TITLE
iOS 10, map not loading

### ISSUE THREAD

**Issue by eckersalld** [Leaflet/Leaflet#4930]
Hi,

I've been asked to investigate why a map isn't loading on a form in Safari on iOS 10, it is working fine on earlier versions, just not on iOS 10. I was just wondering if this was a known issue and if there is a fix before I started to see if it was anything on our side.

When testing the issue, I did note a double location request - first for the Safari app, second for the site itself - not present in earlier versions, however that could be down to settings on the test devices.

**Comment by IvanSanchez** [comment]
> I was just wondering if this was a known issue and if there is a fix before I started to see if it was anything on our side.

So if you have a look at https://github.com/Leaflet/Leaflet/search?q=ios+10&type=Issues , you'll see there are no issues mentioning iOS10.

If you really think there is a bug in core Leaflet, do provide your Safari version, and a reproducible test case.
