### ISSUE TITLE
GeoJSON with DivIcons can't be BringToFront'd?

### ISSUE THREAD

**Issue by simopaasisalo** [Leaflet/Leaflet#4934]
Hi,

If I have a GeoJSON layer with a pointToLayer function like this:

    let circleHtml = '<div style="height: ' + x + 'px; width: ' + x + 'px; opacity:' + col.opacity + '; background-color:' + col.fillColor + '; border: ' + col.weight + 'px solid ' + col.color + ';border-radius: 30px;"/>';
    let circleIcon = L.divIcon({ iconAnchor: L.point(x / 2, x / 2), html: circleHtml, className: '' });
    return L.marker(latlng, { icon: circleIcon });

then BringToFront/BringToBack has no effect.

However, if using CircleMarkers or other Path-types, it works as intended.

Any ideas why this happens, and how to reorder the first type of layers?

**Comment by IvanSanchez** [comment]
This is expected behaviour: `L.Marker`s do not have a `bringToFront` method, so running `L.FeatureGroup.bringToFront()` does not affect the markers in that group.

Also note that `L.Path`s do have a `bringToFront` method.

**Comment by simopaasisalo** [comment]
@IvanSanchez Okay, thank you for clarification. I'm guessing I'll have to play around with z-Index then to reorder layers on the map?

**Comment by IvanSanchez** [comment]
@simison Yeah, the way of handling z-ordering on markers is messing with the z-index offsets themselves. While I agree that there should be a way to `bringToFront` markers, it's not easy to make that work along custom z-index offsets.
