### ISSUE TITLE
Bug with VueJS and Leaflet click on map

### ISSUE THREAD

**Issue by Shmasya** [Leaflet/Leaflet#4936]
I init Leaflet in Vue Component. http://i.imgur.com/jKoPkac.png. This work good, but when i click on map, then my cursor snaps to the map and constantly move, as if I squeezed the button. http://i.imgur.com/UviSlD2.gif

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* qGIS2web
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.

In your case it seems that the Leaflet touch event handlers are misbehaving with the vue event handlers. See the `tap` option in Leaflet documentation, or disable the Vue touch hacks somehow.
