### ISSUE TITLE
Clearing Multiple Polyline using a Loop

### ISSUE THREAD

**Issue by bonlemuel** [Leaflet/Leaflet#4944]
Hi Everyone,

First of all, thank you for bringing leaflet. My problem is, I tried this solution in order to clear the polylines on the map. Here's some code for your reference:

     `var line;
     $scope.clearPolylines = function(){
		for(var i = 0; i < coordinates.length; i ++){ // coordinates is an array
			map.removeLayer(line._latlngs[i]);
			console.log("[ DELETE LINES ]", line._latlngs[i]);
		}
	}`

But it is not clearing on the map. It there other ways possible?

This solution is based from http://stackoverflow.com/questions/14585688/clear-all-polylines-from-leaflet-map

Thank you in advance.

**Comment by danzel** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

**Comment by bonlemuel** [comment]
Okay. Noted. Thanks! I will transfer.
