### ISSUE TITLE
zoomDelta not working

### ISSUE THREAD

**Issue by codeplan** [Leaflet/Leaflet#4946]
zoomDelta is not working with leaflet-omnivore.js 0.3.2v. I am using it as following:
  var map = L.map('map', {minZoom: 4, zoomDelta:0.5, attributionControl:false} ).

I check it using map.getZoom() after clicking on default zoomcontrols buttons '+' and '-'. The difference it is shows is 1 after the click.

**Comment by mourner** [comment]
There is not enough details in your bug report. When you created the issue, there was an issue template with a checklist. Please go over it filling the blanks and I'll reopen it if it has enough information:

- [ ] I'm reporting a bug, not asking for help
- [ ] I've looked at the [documentation](http://leafletjs.com/reference-1.0.0.html) to make sure the behaviour is documented and expected
- [ ] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [ ] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using:
- Browser (with version) I'm using:
- OS/Platform (with version) I'm using:
- step 1
- step 2

## What behaviour I'm expecting and which behaviour I'm seeing

## Minimal example reproducing the issue

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

Using http://playground-leaflet.rhcloud.com/ or any other jsfiddle like site.
