### ISSUE TITLE
Leaflet 1.0 breaks webpack

### ISSUE THREAD

**Issue by jefbarn** [Leaflet/Leaflet#4957]
ERROR in ./~/leaflet/dist/leaflet.css
Module not found: Error: Can't resolve './images/' in 'C:\projects\dayapp\node_modules\leaflet\dist'
 @ ./~/leaflet/dist/leaflet.css 6:5987-6007

Caused by:
```
/* Default icon URLs */
.leaflet-default-icon-path {
	background-image: url(images/);
	}
```

It's trying to load a directory as a background image?

**Comment by IvanSanchez** [comment]
Duplicate of #4849. See #4605 for background info.
