### ISSUE TITLE
Standard naming convention for leaflet plugins

### ISSUE THREAD

**Issue by justinffs** [Leaflet/Leaflet#4958]
Not reporting a bug but I noticed this statement on the blog post for 1.0

> A cleaner, more stable plugin ecosystem.

I am looked to see if there is an on going ticket for this but couldn't find one.  

My first question is will there be a consistent naming convention for plugins.  Right now the ones we are using are each different, some `leaflet-plugin` some `Leaflet.plugin` but most are `leaflet.plugin`.  Will this be the standard?  Will you accept  pull request to the documentation for plugins here? https://github.com/Leaflet/Leaflet/blob/master/PLUGIN-GUIDE.md#publishing-on-npm

examples:

```
leaflet-toolbar
Leaflet.DistortableImage
leaflet.imagetransform
leaflet.markercluster
leaflet.zoomhome
```

Second will supporting a module system be required?  The plugin guide already has an example on how to do this, I have added it to leaflet.zoomhome and it was quite easy.  Currently even plugin maintained by Leaflet do not have this, like Leaflet.toolbar.  

Lastly are there any other things that we could do to help with a cleaner, more stable plugin ecosystem?

Thanks for all the hard work,
Justin

**Comment by mourner** [comment]
We have a suggested convention about a name here, but it's not a hard standard: https://github.com/Leaflet/Leaflet/blob/master/PLUGIN-GUIDE.md#name

I don't think we should enforce the convention — it would be unfair to ask existing plugins to rename. The name section above seems good enough for me, but I don't have a strong opinion on this.

**Comment by justinffs** [comment]
Trying to implement these plugins it gets very confusing and messy when there is no standard naming convention.  It took me a while when converting to a npm based install to track down the packages and make sure they were the correct ones, which is why I opened the ticket.

I suggest changing the wording to remove 

> You can use other forms (e.g. "leaflet-my-plugin-name"), just make sure to include the word "Leaflet" in the name so that it's obvious that it's a Leaflet plugin.

Also leading by example I think would help the community a lot as well.  Renaming plugins that are maintained by Leaflet could be renamed to consistent naming.  I can submit PRs for these.

**Comment by ghybs** [comment]
Hi,

FWIW, this situation is general, there is nothing specific to Leaflet.
Discipline is very difficult to enforce on Open Source, not even talking about maturity evolution, changing trends and practices.

npm does not enforce the package name to have the same name as the GitHub repository.
Actually, the author does not even have to specify _any_ repository.
Forks may be added to npm with a slightly different name, or even _preempt_ the npm name.

At least you have the official Leaflet plugins page that lists those plugins (on a voluntary basis, but still better than nothing).

As for _renaming_ plugins, I agree that would be great, but you will quickly have to wonder about _legacy_: what to do about all dependencies, links, etc.? Is it really worth losing everything for renaming? That sounds much more like _hurting_ the community than helping it unfortunately. Like we say "the road to hell is paved with good intentions" (do not know if it exists as is in English?)
Do not underestimate the value of legacy.

Now to come back to your point, I hear that the shift from individual scripts / CDN to package management (npm) is a lot of work in itself (again, nothing specific to Leaflet unfortunately).

Maybe something that could help would be to remind plugin authors to mention under which name they published on npm (if they did). Same with any other package management system (bower…)

This could even be listed on the Leaflet plugins page directly.

**Comment by perliedman** [comment]
Bottom line: we have a recommended convention, but we will not enforce it. Neither will we rename plugins, since that is usually even more confusing for users ("why are there two packages with almost exactly the same name? Which should I use?").

Having said that, we should revise the plugin documentation based on ES6, state of package managers, etc. But that is a separate issue.
