### ISSUE TITLE
map.flyTo is not a function

### ISSUE THREAD

**Issue by xEuPhoRiA-** [Leaflet/Leaflet#4961]
- [x] I'm reporting a bug, not asking for help
- [X] I've looked at the [documentation](http://leafletjs.com/reference-1.0.0.html) to make sure the behaviour is documented and expected
- [X] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [X] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: leaflet@1.0.0 CDN
- Browser (with version) I'm using: Chrome
- OS/Platform (with version) I'm using: OSX El Capitan v10.11.15

``` JS
$('#resultsUL li').on('click',
        function(marker, layer) {
            var markerID = $(this).attr('data-featID');
            dataLayer.eachLayer(function(marker, layer) {
                if (marker.feature.properties.id == markerID) {
                    map.flyTo(marker.getLatLng());
                    marker.bindPopup(marker.feature.properties.name).openPopup();
                };
            });
        });
```

Trying to use the `.flyTo()` method on my map to pan and zoom to a point that is grabbed from the results sidebar. Once I click on the li I am given an error in my console saying "map.flyTo is not a function".

I am using mapbox.js as well, however this builds on top of leaflet, correct? And mapbox.js does not have this feature, this shouldn't affect it, maybe I am wrong?

## What behaviour I'm expecting and which behaviour I'm seeing

`.flyTo()` is listed under documentation and I just can't see why this isn't working, `.panTo()` works but I need it to zoom and pan at the same time.

Here is a list of libraries I have included, in case that helps.
```
<!--Leaflet and Mapbox JS -->
    <link rel='stylesheet' href='https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.css'/>
    <link rel="stylesheet" href="/vendor/leaflet/addons/css/leaflet.markercluster.css" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.0/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.0.0/dist/leaflet.js"></script>
    <script src="/vendor/leaflet/addons/leaflet.listmarkers.min.js"></script>
    <script src='https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.js'></script>
    <script src="/vendor/leaflet/addons/leaflet.markercluster.js"></script>
    <script src="/vendor/leaflet/addons/leaflet.hash.js"></script>
    <script src="/vendor/leaflet/addons/leaflet.makimarkers.js"></script>
```

**Comment by perliedman** [comment]
Mapbox.js is built with its own version of Leaflet, presumably still 0.7.x since Leaflet 1.0.0 was released just yesterday.

When you load Mapbox.js, it will overwrite the previously loaded version of Leaflet, and you will no longer have `flyTo`.

To check, look at the value for `L.version` to see what version of Leaflet you're actually running.

**Comment by IvanSanchez** [comment]
Yup, loading `mapbox.js/v2.4.0/mapbox.js` will overwrite the `L` global with its built-in version of Leaflet, which is 0.7.7.

See https://playground-leaflet.rhcloud.com/viw/edit?html,console

I've opened up https://github.com/mapbox/mapbox.js/issues/1165 for convenience of Mapbox.js users.

This is a problem about loading several libraries at once → not a leaflet bug → closing.

**Comment by xEuPhoRiA-** [comment]
Thanks guys! Appreciate it. Sorry for the wasted issue.
