### ISSUE TITLE
Draw the same marker every time its coordinates repeat on the map

### ISSUE THREAD

**Issue by laginha** [Leaflet/Leaflet#4966]
Hey,

It is possible to draw the same marker (or a polygon) every time its coordinates repeat on the map, after zooming out or after dragging beyond the initial boundaries. For instance:

![screen shot 2016-09-28 at 15 52 24](https://cloud.githubusercontent.com/assets/25960/18918782/c88bf104-8593-11e6-92db-ec213423904d.png)

Thanks

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
