### ISSUE TITLE
Link to announcement blog post in v1.0.0 on github points to localhost:4000

### ISSUE THREAD

**Issue by rdewit** [Leaflet/Leaflet#4971]
- [x] I'm reporting a bug, not asking for help
- [ ] I've looked at the [documentation](http://leafletjs.com/reference-1.0.0.html) to make sure the behaviour is documented and expected
- [ ] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

----

The release text for [v1.0.0](https://github.com/Leaflet/Leaflet/releases/tag/v1.0.0) that says 'Read the announcement blog post' links to [http://localhost:4000/2016/09/27/leaflet-1.0-final.html](http://localhost:4000/2016/09/27/leaflet-1.0-final.html)

I expect it should point to: http://leafletjs.com/2016/09/27/leaflet-1.0-final.html

**Comment by IvanSanchez** [comment]
Seems like @mourner wrote the release notes a bit too quick. Should be fixed now.
