### ISSUE TITLE
leaflet.css .leaflet-default-icon-path (Default icon URLs) breaks webpack import

### ISSUE THREAD

**Issue by iagafonov** [Leaflet/Leaflet#4985]
leaflet.css:
`/* Default icon URLs */
.leaflet-default-icon-path {
	background-image: url(images/);
	}
`
`images/` - is not correct resource path. It can not be resolved in webpack module bundler and another dependency tracking utilities too, I suggess

**Comment by IvanSanchez** [comment]
Duplicate of #4849
