### ISSUE TITLE
Test Suite Recommendation for Plugin Authors

### ISSUE THREAD

**Issue by codeofsumit** [Leaflet/Leaflet#4991]
I'm fairly new to unit tests (or at least the setup that is necessary before). I want to make my leaflet plugin solid with unit tests but I'm not sure how to handle it, especially since I need leaflet itself as well to test.

Is there a guideline/tutorial somewhere that I could follow?

**Comment by mourner** [comment]
You could follow existing projects by example. Leaflet uses mocha as a test library + karma to run it on different platforms; but there are many other libraries. For new projects, I personally use `tape` or `tap`. But in any case, Leaflet issue tracker isn't a place to ask generic JS development questions like this — I think StackOverflow would fit better.
