### ISSUE TITLE
Simpler "quick start" tutorial

### ISSUE THREAD

**Issue by fulldecent** [Leaflet/Leaflet#4998]
The "quick start" tutorial is too complicated.

 > http://leafletjs.com/examples.html

Please make the first example explain how to make a map that centers and shows a pin at 1600 Pennsylvania avenue. Preferably this would not require the reader to look up the coordinates for that address.

Here is the comparable Google example:

> https://developers.google.com/maps/documentation/embed/guide

**Comment by snkashis** [comment]
The first steps of the quick start tutorial initialize the map with the view centered on the marker(your suggestion). If a reader doesn't want to continue onto the circles, polygons,popups & events, that's fine, but I think detailing some of the very basic usage/interactivity of the library is a good idea. If one doesn't need said interactivity or features, maybe they should be using Mapbox Static Maps?  Also..regarding geocoding...that would require using a plugin as we do not have that built in.

**Comment by fulldecent** [comment]
Got, thanks for the heads up, I need to investigate this pluggin.
