### ISSUE TITLE
Migrate types from dt~leaflet to this repo and its `package.json`

### ISSUE THREAD

**Issue by darcyparker** [Leaflet/Leaflet#5003]
## How to reproduce
- Leaflet version I'm using: 1.0.1
## What behaviour I'm expecting and which behaviour I'm seeing

The `package.json` does not define `types` and the typescript definition is not included in this repo.  See http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html for new practice for publishing.

**Comment by nathancahill** [comment]
Opened a PR a couple months ago with updated definitions for 1.0: https://github.com/Leaflet/Leaflet/pull/4516

Should update if there's interest for the finished 1.0 release.

**Comment by darcyparker** [comment]
@nathancahill - Nice to see you've been working on this. I am interested in seeing it finished, retiring the versions on https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0/leaflet, and as you pointed out in your pull request, I also think the definitions should exist and be maintained in this leaflet repo.

**Comment by IvanSanchez** [comment]
From a vanillaJS point of view, I cannot really see the benefits of this. Also, @mourner is working on migrating things to plain ES6 modules.

@nathancahill If the goal is to have a file built based on information on the public interfaces, I'd say that's a job for leafdoc - it should be possible to make some clever leafdoc templates which take the parsed docstrings and output typescript defs. If this thing can be automated, it might be worth a look.

**Comment by mourner** [comment]
Since Leaflet maintainers themselves don't use TypeScript, having them maintained as a part of the repo is dangerous because it will likely go out of sync and we have no bandwidth to officially support the bindings. I think definitions should stay in DefinitelyTyped repo.

**Comment by darcyparker** [comment]
@IvanSanchez - There is no benefit for vanillaJS other than another form of documentation. But for those using typescript, it promotes correct usage of the APIs. I also appreciate the features I have in my editor (vim) for navigating/completing/refactoring code in typescript.  I can use a tern based plugin for vanilla js, but the tags/jump capabilities are not as good as for typescript. So even if I am not really using the full features of typescript, I still get a lot of value in my editor.  I don't want to debate the merits of typescript vs ES6 but there is a growing community of people who do value typescript and use leaflet.

@mourner - I can see the argument for keeping the definitions in DefinitelyTyped, but it would be super helpful for the community that cares about using leaflet in typescript could collaborate on types issues here in this repo.  

Would the leaflet maintainers be willing to add an issue tag for typescript definitions so we can come here to discuss/resolve issues rather than DefinitelyTyped?  VanillaJS users can just ignore issues with this tag and having the `types` in the `package.json` doesn't impact them.

**Comment by nathancahill** [comment]
**Re maintaining**: I volunteered in the other PR to take point in maintaining the TS definitions if they were merged into this repo, since the 80% of my work involves Leaflet and Typescript. I also think that since Typescript documents the public API and not implementation details, the amount of changes should be less now that we've reached 1.0.

**Re generating from leafdoc**: This is indeed the direction I'd like to go. I'll play around with it this week and see how close I can get to the current definitions that I wrote by hand.

**Re merits of Typescript for vanilla users**: When writing the definition by hand from scratch in April, I found and fixed 48 issues and discrepancies between the source/docs/tests/debug/examples: https://github.com/Leaflet/Leaflet/pulls?q=is%3Apr+author%3Anathancahill+is%3Aclosed. Using correct types is advantageous whether you are checking them with TS or not, and this adds one more layer of checks besides the tests.

**Comment by IvanSanchez** [comment]
> **Re generating from leafdoc:** This is indeed the direction I'd like to go. I'll play around with it this week and see how close I can get to the current definitions that I wrote by hand.

If you can do it, I see no problem in keeping the generated descriptions somewhere along the `dist/` files, even in a 1.0.2 release or something like that.

**Comment by mourner** [comment]
> Would the leaflet maintainers be willing to add an issue tag for typescript definitions so we can come here to discuss/resolve issues rather than DefinitelyTyped? VanillaJS users can just ignore issues with this tag and having the types in the package.json doesn't impact them.

@darcyparker how about making a separate repo in the Leaflet organization to track issues?

**Comment by patrickarlt** [comment]
This kind of thing happened with PouchDB https://github.com/pouchdb/pouchdb/issues/5389 and it's `.d.ts` files. In particular https://github.com/pouchdb/pouchdb/issues/5389#issuecomment-228610251, particularly:

> it's better for library authors not to ship their own index.d.ts files, unless they are well-versed in TypeScript and prepared to maintain it. 

Seeing that none of the Leaflet core team has any Typescript experiance, I think @mourner's suggestion of creating a seperate repo like `leaflet-typings` that can simply serve as a common point of discussion for those willing to maintain the types.

**Comment by jmlopez-rod** [comment]
If @mourner is working on using es6 modules why not use typescript as the transpiler instead of babel? All the code can be typed in plain es6 if one desires and when compiling the code typescript can generate all the definition files. Also, the target can be done to es6, es5 and es3. I started out my leaflet project using plain es6 and later I made the jump to typescript and it has been great.

**Comment by IvanSanchez** [comment]
@jmlopez-rod We're not going to use any transpilers.

**Comment by patrickarlt** [comment]
@jmlopez-rod A longer explanation would be this:

Leaflet is not written with a transpiler like Babel or TypeScript the main reason for this is keeping the file size extremely minimal transpiled output is inherently larger. Leaflet is written in ES5 code with the ES2016 import/export syntax. Rollup (a bundler, not a transpiler) bundles the ES2016 syntax into the final output files.

Switching to TypeScript just to make Leaflet fully compatible with TypeScript would have a huge problems for both Leaflet and the Leaflet community. These concerns are mirrored by other medium size projects like PouchDB https://github.com/pouchdb/pouchdb/issues/5389#issuecomment-228610251 where migrating to TypeScript was also suggested.

**Comment by perliedman** [comment]
Hi everyone!

Looking through the comments here, I feel I'm ready to close this one, and #4516, based on:

* we have the "needs discussion" label on it, but no discussion is taking place
* current active maintainers don't feel comfortable keeping TypeScript defs up to date
* from what I gather, TypeScript users are used to workings with defs from DefinitelyTyped

The only reason to keep this open would seem to be if we could generate the TypeScript bindings from Leafdoc, which was suggested as a possible alternative, but that's not something anyone is working on, AFAIK.

So, anyone against closing?

**Comment by danzel** [comment]
Yes, lets close these :+1:
Currently a typescript user will `yarn add @types/leaflet`, and I advise we keep it that way.

The types are hosted in the DefinitelyTyped repository, and can be contributed to there:
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/leaflet
By having these externally we are not held up waiting for `.d.ts` updates for each release, and the types can be improved without requiring a new release.
