### ISSUE TITLE
map.invalidateSize() changes map center

### ISSUE THREAD

**Issue by sonic16x** [Leaflet/Leaflet#5008]
## How to reproduce
- Leaflet version I'm using: 1.0.1
- Browser (with version) I'm using: Chrome  51.0.2704.63 (64-bit) 
- OS/Platform (with version) I'm using: Ubuntu 16.04
### Step 1

Create html file with this content:

``` html
<!DOCTYPE html>
<html>
<head>
    <title>Leaflet</title>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.1/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.0.1/dist/leaflet.js"></script>
</head>
<body>
<div id="mapid" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;"></div>
<script>
    window.map = L.map('mapid').setView([54.98, 82.89], 13);
    L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: ''
    }).addTo(map);
</script>
</body>
</html>
```
### Step 2

In browser console run `map.setView(map.getCenter())`
##### This depends on the window size. If not repeat resize the browser window.

Problems in file `Map.js:1482`.
Maybe we can compare new center with current in function `setView` like this

``` js
if (this._loaded) {
            var currentCenter = this.getCenter();
            var newCenter = L.latLng(center);
            if (newCenter.lat === currentCenter.lat
                && newCenter.lng === currentCenter.lng
                && zoom === this.getZoom()) {
                this.fire('movestart');
                this.fire('moveend');
                return this;
            }
        }
```

But in events will be wrong center.

**Comment by IvanSanchez** [comment]
Cannot reproduce in master with playground at http://playground-leaflet.rhcloud.com/rofi/edit?html,output

Might be related to #3194 / #3197

**Comment by scherebedov** [comment]
@IvanSanchez 
![image](https://cloud.githubusercontent.com/assets/10794912/19164244/5983b35e-8c29-11e6-9d33-d524497a380d.png)
This depends on the size of the window is not always repeated. It is necessary to change the window size.

**Comment by IvanSanchez** [comment]
OK, I see what you mean now. New playground at http://playground-leaflet.rhcloud.com/wewo/1/edit?html,output

**Comment by scherebedov** [comment]
@IvanSanchez, yea. Now it reproduce in your example.The shift is very small. 1-2 pixel. In my example can be seen better.
