### ISSUE TITLE
An error in the doc

### ISSUE THREAD

**Issue by nbaghm** [Leaflet/Leaflet#5009]
the example on **Class** is:
```
var MyClass = L.Class.extend({
    options: {
        myOption1: 'foo',
        myOption2: 'bar'
    }
});
var MyChildClass = L.Class.extend({
    options: {
        myOption1: 'baz',
        myOption3: 5
    }
});
var a = new MyChildClass();
a.options.myOption1; // 'baz'
a.options.myOption2; // 'bar'
a.options.myOption3; // 5
```
The issues is the second class does not inheret from the first one, so result is (undefined) for **a.options.myOption2;** 
The corrected one is:
```
var MyClass = L.Class.extend({
    options: {
        myOption1: 'foo',
        myOption2: 'bar'
    }
});
var MyChildClass = MyClass.extend({
    options: {
        myOption1: 'baz',
        myOption3: 5
    }
});
var a = new MyChildClass();
a.options.myOption1; // 'baz'
a.options.myOption2; // 'bar'
a.options.myOption3; // 5
```

----

## How to reproduce

- Leaflet version I'm using:
- Browser (with version) I'm using:
- OS/Platform (with version) I'm using:
- step 1
- step 2

## Minimal example reproducing the issue

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

Using http://playground-leaflet.rhcloud.com/ or any other jsfiddle like site.

**Comment by perliedman** [comment]
Thanks for reporting! Next time, it would be even better if you provided a PR (you'll get the credit for fixing), or at least provide a link - took me a while to find the actual issue.
