### ISSUE TITLE
CircleMarker not showing when setting `preferCanvas` to true in map option

### ISSUE THREAD

**Issue by stefanhagiu** [Leaflet/Leaflet#5011]
- I'm reporting a bug, not asking for help
- I've looked at the [documentation](http://leafletjs.com/reference-1.0.0.html) to make sure the behaviour is documented and expected
- I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: 1.0.0
- Leaflet plugins used: proj4leaflet v0.7.2 and leaflet.markercluster 1.0.0
- Browser (with version) I'm using: Chrome (but this can be seen in Mozilla Firefox and Edge)
- OS/Platform (with version) I'm using: Windows 10
- step 1 check link in minimal example
- step 2 use the scroll or zoom in/out buttons

## What behaviour I'm expecting and which behaviour I'm seeing

 - Expected behaviour:  the map zooms in and the object geometries are visible at each zoom level (if not clustered);
 - Actual behaviour: the map zooms in/out but the geometries disappear (totally or partially) when zooming in / out (the clustering functionality still works)

## Minimal example reproducing the issue

- using leaflet + marker cluster + svg [ works as expected ]: https://codepen.io/anon/pen/YGLbGq?editors=1010
- using leaflet + marker cluster + canvas [ fails to work ]: https://codepen.io/anon/pen/PGZONy?editors=1010
- using leaflet + canvas [ no clustering works as expected]: https://codepen.io/anon/pen/wzjbgP?editors=1010

**Comment by IvanSanchez** [comment]
Weird. I can reproduce the problem in FFX in Linux, there is some weird flickering of the circle markers when zooming in and out.

I'm gonna hope this is reproducible without markerclusters, need a simpler test case.

**Comment by stefanhagiu** [comment]
@IvanSanchez well _for a simple test case_ i've added all the points to a geojsonLayer and removed the markercluster, the flickering efect is gone (is this what you wanted ?): https://codepen.io/anon/pen/GjddoV?editors=1010

**Comment by IvanSanchez** [comment]
That's... weird. This one will need more analysis to see what's going on.

**Comment by stefanhagiu** [comment]
ok i think i found what starts the bug, but i don't know why ...  
`var markersLayer = L.markerClusterGroup({
        disableClusteringAtZoom: 13,
        animate: false,
        spiderfyOnMaxZoom: false,
        removeOutsideVisibleBounds: false,
        singleMarkerMode: true
    });` 
remove the `animate: false`; to test use https://codepen.io/anon/pen/XjYGzX and comment line 60

**Comment by IvanSanchez** [comment]
I think this is a bug in https://github.com/Leaflet/Leaflet.markercluster/ then.

**Comment by IvanSanchez** [comment]
Moved to https://github.com/Leaflet/Leaflet.markercluster/issues/727.
