### ISSUE TITLE
Flickering on animation

### ISSUE THREAD

**Issue by ClaudioCas** [Leaflet/Leaflet#5012]
Dear all,
I use TimeDimension plugin of Leaflet (https://github.com/socib/Leaflet.TimeDimension).
It works great but has some flicker issue with Firefox with large maps, and it works really bad with Internet explorer and Edge...
## How to reproduce Firefox Issue
- Leaflet: 1.0.1
- Browser : Firefox 49
- OS/Platform: Windows 7
- ```
  open example 7 with firefox http://apps.socib.es/Leaflet.TimeDimension/examples/example7.html
  ```
-     disable all overlay layers
-     enable WMOP - Salinity
-     click on fullscreen button
-     click on play button

![bfa829d6-5f14-11e6-8e36-c1dbae8be781](https://cloud.githubusercontent.com/assets/4325427/19277532/4937bbbc-8fda-11e6-8db4-8b93e4ec1cf8.jpg)
## How to reproduce Miscosoft IE and EDGE Issue
-     open example 12 with Ie or Edge http://apps.socib.es/Leaflet.TimeDimension/examples/example2.html
- click on play button

I also opened an issue on TimeDimension Git, but the author probably is busy at this time.
(https://github.com/socib/Leaflet.TimeDimension/issues/61)
Thanks

**Comment by IvanSanchez** [comment]
@ClaudioCas Is this reproducible **without** the TimeDimension plugin? i.e. what if you *manually* replace tile layers?

If the answer is "no", then this is exclusively a TimeDimension bug.

**Comment by perliedman** [comment]
Closing this for now, feel free to add more information (for example how to reproduce without other plugin)  if you still believe this is an issue.
