### ISSUE TITLE
Inconsistent style-rendering

### ISSUE THREAD

**Issue by vhaze** [Leaflet/Leaflet#5014]
- [x] I'm reporting a bug, not asking for help
- [x ] I've looked at the [documentation](http://leafletjs.com/reference-1.0.0.html) to make sure the behaviour is documented and expected
- [x ] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x ] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using:
- Browser (with version) I'm using: Google Chrome Version 53.0.2785.116 (64-bit)
- OS/Platform (with version) I'm using:  Max osX Yosemity Version 10.10.5 (14F1912)
- step 1: open mapbox preview url below
- step 2: open codepen url 
- step 3: see how the white country-borders show in the preview, but disappear in the codepen example

## What behaviour I'm expecting and which behaviour I'm seeing
I created a style in MapBox Studio.  The preview link shows correctly.  However, when embedding the leaflet-code, the white borderlines are not visible anymore...  

## Minimal example reproducing the issue
Mapbox Studio preview/sharing url: 
https://api.mapbox.com/styles/v1/ngeens/circ2dl5u002hh1kp950caxzq.html?title=true&access_token=pk.eyJ1IjoibmdlZW5zIiwiYSI6ImNpcmMyYXVjMDAwN21pYWx3b2lvcHpvNDAifQ.7QcQaZtD1ttfCq4qgBdzLw#3.577873543226374/48.009524894513106/7.8074666275565505/0

As embedded in my code (borders are not showing anymore): 
http://codepen.io/nikogeens/pen/VKdvXX

This used to render correctly in the past, I think... Is this a bug?

**Comment by IvanSanchez** [comment]
Your codepen is using `mapbox.js`, and **not** `leaflet.js`. Thus, we can not accept this as a leaflet bug. This is why we ask users to check "I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)".

Having a quick look at the map tiles, seems that the Mapbox render server is not outputting the white lines. I suggest you contact Mapbox.

**Comment by IvanSanchez** [comment]
Note that the issue is reproducible with [this minimal example](https://playground-leaflet.rhcloud.com/jox/edit?html,output):

```
<!DOCTYPE html>
<html>
<head>
<link href="https://unpkg.com/leaflet@1.0.0/dist/leaflet.css" rel="stylesheet" type="text/css" />
<script src="https://unpkg.com/leaflet@1.0.0/dist/leaflet-src.js"></script>
  <meta charset="utf-8">
  <title>Leaflet JS Bin</title>
  <style>
    #map {
      width:600px;
      height:400px;
    }
  </style>
</head>
<body>
  <div id='map'></div>

  <script>
    var map = new L.Map('map').setView([50, 10], 3);
    
L.tileLayer(
    'https://api.mapbox.com/styles/v1/ngeens/circ2dl5u002hh1kp950caxzq/tiles/256/{z}/{x}/{y}?access_token=' + 'pk.eyJ1IjoibmdlZW5zIiwiYSI6ImNpcmMyYXVjMDAwN21pYWx3b2lvcHpvNDAifQ.7QcQaZtD1ttfCq4qgBdzLw', {}).addTo(map);

  </script>
</body>
</html>
```

The problem is with the tile generation, not with the Leaflet code.
