### ISSUE TITLE
map.fitBounds throws: Invalid LatLng object: (NaN, NaN)

### ISSUE THREAD

**Issue by guillerrodri25** [Leaflet/Leaflet#5015]
Hello:

I've changed Leaflet version from 0.7.7 to 1.0.1 and when I execute map.fitBounds(bounds) and the bounds _southWest and _northEast latitudes and longitudes are exactly the same it throws Invalid LatLng object: (NaN, NaN) error. If I change one decimal of one of the latitudes or the longitudes it works fine.

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by guillerrodri25** [comment]
It only occurs when I use google maps, here is the fiddle:

https://jsfiddle.net/x4kr5o0r/

**Comment by perliedman** [comment]
@guillerrodri25 if it only happens with leaflet-google, you should post an issue for that plugin, not for Leaflet itself, since that plugin is maintained by someone else and unfortunately we can't offer support for every plugin out there.

**Comment by IvanSanchez** [comment]
I guess this is a good time to pitch GoogleMutant, then. https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant

**Comment by guillerrodri25** [comment]
I'm going to probe It. Thanks for your help!!

**Comment by IvanSanchez** [comment]
@guillerrodri25 "Probar" = "to test". "Sondear" = "to probe" :stuck_out_tongue:

**Comment by guillerrodri25** [comment]
ja ja la proxima vez te escribo en castellano. Gracias por el plugin va muy bien!!
