### ISSUE TITLE
Reading wrong (??) instance member when calling it through eventListener

### ISSUE THREAD

**Issue by sosnet** [Leaflet/Leaflet#5017]
- [X] I'm reporting a bug, not asking for help
- [X] I've looked at the [documentation](http://leafletjs.com/reference-1.0.0.html) to make sure the behaviour is documented and expected
- [~] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [X] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: 1.0.1 with @types/leaflet@1.0.35
- Browser (with version) I'm using: Chrome 54.0.2840.59 (64-bit)
- OS/Platform (with version) I'm using: Linux Mint 17.3
- step 1: listen to click event on the map and call a function
- step 2: read instance member

## What behaviour I'm expecting and which behaviour I'm seeing
In my simple example I set the instance member `test = true;`. When calling the function `show()` it's `true`. But calling the function `show()` with the event-listener it's `undefined`. I'm using Ionic2 framework with Angular2. I'm not sure where the problem belongs to. If I should post it somewhere else, please tell me. I'm sorry if I'm wrong here..

**Edit:** I also posted it here https://github.com/driftyco/ionic/issues/8704

## Minimal example reproducing the issue

- [X] this example is as simple as possible
- [ ~] this example does not rely on any third party code

http://plnkr.co/edit/UZ8cMAzC7RPIvoCsofUr?p=preview

**Comment by IvanSanchez** [comment]
Yeah, this looks like a problem on your side (debug the value of `this` when you're inside `initMap` and inside `show`!!) or in the way you're using angular/ionic. Not a leaflet bug.

(Also, note the use of `context` in [`L.Map.on()`](http://leafletjs.com/reference-1.0.0.html#evented-on), and read up on [`Function.bind()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind) )

**Comment by sosnet** [comment]
Thx @IvanSanchez, adding `this` as third param to `L.Map.on()` solved my problem.
