### ISSUE TITLE
Multiple instance of L.Control.Layers not working

### ISSUE THREAD

**Issue by stefanocudini** [Leaflet/Leaflet#5020]
Instantiate more than one *Control Layers* on the same map causes an error in console.

*"Uncaught TypeError: layer.onAdd is not a function"*

About at row 2224:
```javascript
_layerAdd: function (layer) {
		layer.onAdd(this);
		this.fire('layeradd', {layer: layer});
	},
```

**Comment by IvanSanchez** [comment]
> Instantiate more than one *Control Layers* on the same map causes an error in console.

No, it doesn't. See https://playground-leaflet.rhcloud.com/coku/edit?html,output

If you think there is really a bug, provide a complete, minimal, reproducible test case.

**Comment by stefanocudini** [comment]
yes sorry,  the error at console is caused from other
