### ISSUE TITLE
CRS behaviour in leaflet 0.7.7 and 1.0.1

### ISSUE THREAD

**Issue by ocefpaf** [Leaflet/Leaflet#5029]
- [X] I'm reporting a bug, not asking for help
- [X] I've looked at the [documentation](http://leafletjs.com/reference-1.0.0.html) to make sure the behaviour is documented and expected
- [X] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [X] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: 1.0.1 and 0.7.7
- Browser (with version) I'm using: Chromium Version 53.0.2785.143 (64-bit)
- OS/Platform (with version) I'm using: Linux-64

I have a few example example, like these two below, to show `CRS` distortion to students using leaflet. However, I noticed that the behavior changed from `leaflet 0.7.7` to `leaflet 1.0.1`. Is that expected? I could not find any docs on the change.

# Leaflet 0.7.7
https://bl.ocks.org/ocefpaf/ef8b8c558b40f024a67080d876e2a617

# Leaflet 1.0.1
https://bl.ocks.org/ocefpaf/c01a2777e78550b8a8dfa3cbc88703cd

Thanks for the attention!

**Comment by IvanSanchez** [comment]
- You're not reporting a bug, you're asking for help.
- Yes.
- It's noted [in the changelog](https://github.com/Leaflet/Leaflet/blob/master/CHANGELOG.md#projections-api-improvements).

**Comment by ocefpaf** [comment]
> It's noted in the changelog.

Where?

> You're not reporting a bug, you're asking for help.

Not sure that is true.

**Comment by IvanSanchez** [comment]
https://github.com/Leaflet/Leaflet/blob/master/CHANGELOG.md#projections-api-improvements

**Comment by IvanSanchez** [comment]
>>    You're not reporting a bug, you're asking for help.

>Not sure that is true. 

Putting EPSG:3857 tiles in a Leaflet map with a EPSG:4326 CRS is a PEBKAC, not a Leaflet bug. See
https://playground-leaflet.rhcloud.com/xus/edit?html,output

**Comment by ocefpaf** [comment]
> Putting EPSG:3857 tiles in a Leaflet map with a EPSG:4326 CRS is a PEBKAC, 

A very useful error for teaching distortion. I will just go back to Python libraries to demonstrate this as the behavior there still works  Thank you for the clarification.

**Comment by IvanSanchez** [comment]
So are you actually asking to port a **buggy behaviour** from 0.7.x into 1.0.x, just so you can show how it fails?

**Comment by ocefpaf** [comment]
> So are you actually asking to port a buggy behaviour from 0.7.x into 1.0.x, just so you can show how it fails?

Thanks, but there is no need to change that only for me. It is not a https://xkcd.com/1172/ case. As I mentioned in https://github.com/Leaflet/Leaflet/issues/5029#issuecomment-255349684 there are many other libraries I can use to demonstrate that behavior. Leaflet was just an eye candy to explore the distortion interactively.
