### ISSUE TITLE
setZoom not triggering events

### ISSUE THREAD

**Issue by felipellrocha** [Leaflet/Leaflet#5037]
Hey y'all.

I'm using leaflet 1.0, and I'm finding a weird behavior.

I wrote a function that zooms my map to the topology given:

```
zoomToTopology() {
    console.log('here');

    const [
      [minLng, minLat],
      [maxLng, maxLat],
    ] = this._boundsPath.bounds(this._topology);

    const newBounds = [
      [minLat, minLng],
      [maxLat, maxLng],
    ];

    // zoom the map to the new lat/lng bounds
    // (increasing the bounding box by 20% when calculating the default zoom
    // tends to prevent us from cropping off too much of a state by default.)
    const boundsZoom = this._map.getBoundsZoom(
      (new Leaflet.LatLngBounds(newBounds))
    );
    this._map.setZoom(boundsZoom, { animate: false });

    // forbid the user from panning outside those bounds:
    this._map.setMaxBounds(newBounds);

    // limit the zoom range
    this._map.setMinZoom(boundsZoom);
    this._map.setMaxZoom(boundsZoom + 3);
    console.log('done');
}
```

but it seems like not every call of setZoom triggers the necessary events. I'm also listening to all the zoom events as such:

```
this._map.on('viewreset', () => console.log('viewreset'));
this._map.on('zoom', () => console.log('zoom'));
this._map.on('zoomstart', () => console.log('zoomstart'));
this._map.on('zoomend', () => console.log('zoomend'));
this._map.on('zoomlevelschange', () => console.log('zoomlevelschange'));
this._map.on('load', () => console.log('load'));
```

And here's what gets logged on my console:

```
here
zoomstart
zoom
zoomend
viewreset
done
here
zoomstart
zoom
zoomend
viewreset
done
here
done
here
zoomstart
zoom
zoomend
viewreset
done
here
done
here
done
```

Notice how a couple of times the word `here` gets logged right next to `done`, when it should always log

```
here
zoomstart
zoom
zoomend
viewreset
done
```

in that order.

What could be the issue here?

**Comment by perliedman** [comment]
For one thing, if you `setZoom` to the current zoom level, no zoom will occur, and no zoom events will fire. Might that be the case here?

**Comment by felipellrocha** [comment]
I just fixed the issue. It seems that once I called setMinZoom to a value other than 0, getBoundsZoom would min() using that new value. So, once I zoomed in, I could never zoom out.

I was expecting getBoundsZoom to *always* give me the value I wanted, and if I tried to zoom to a level beyond the level range I allowed, then leaflet would've just zoomed to the minZoom I had previously set.
