### ISSUE TITLE
Why leaflet is working slow in IOS and working fine in android

### ISSUE THREAD

**Issue by dhrubo001** [Leaflet/Leaflet#5039]
I am building a application in which i am loading nearly 700+ markers in a leaflet map and sometimes it's load 100 markers also.
I am fetching the markers through APIs and have a external listview which shows the marker details.
It's working fine in desktop/laptop view, but when opening it from iphone browser things seems to get slower.

And leafletmarkercluster.js is also working here.

Why i am facing this problem, also earlier i saw that the map gets slower bcoz of the listview, so i have changed the logic that the no of markers visible on the map view those ones will only be shown in the listview and it is better after that in desktop but in Iphone it's getting slower a bit i know there is a difference between the WEB browse and mobile browser.

It's freezing in iphone, why does'it freeze in iphone when the leaflet map has more than 500+ markers

**Comment by perliedman** [comment]
Hi there, this looks more like a support question than an actual issue with Leaflet. If you're asking for help [Stackoverflow](http://stackoverflow.com/) or [gis.stackexchange.com](http://gis.stackexchange.com/) are better suited places.

If you think this actually is an issue within the Leaflet library and not with your application code, please submit an example illustrating the issue, for example using http://playground-leaflet.rhcloud.com.
