### ISSUE TITLE
Popup.options.closeOnClick documentation missing, autoClose documentation wrong

### ISSUE THREAD

**Issue by cdauth** [Leaflet/Leaflet#5040]
As far as I can tell, the `closeOnClick` option of `Popup` closes the popup when clicking somewhere else on the map (equivalent to `Map.option.closePopupOnClick`). The `autoClose` option closes the popup when another popup is opened.

The documentation of the `closeOnClick` option is missing, and the `autoClose` documentation instead describes the behaviour of the `closeOnClick` option.

**Comment by eneiluj** [comment]
Thanks a lot, i was becoming mad.

I confirm this issue with Leaflet 1.0.0+b346bb8 .
Nothing in the doc about "closeOnClick".
