### ISSUE TITLE
catch tooltip click

### ISSUE THREAD

**Issue by mepdr** [Leaflet/Leaflet#5043]
Is it possible to catch a tooltip click which doesn't fire marker click handler?
For example the following doesn't work
```
var t = L.tooltip({permanent: true, interactive:true}, marker).setLatLng([51.505, -0.09])
                                                              .setContent("test")
                                                              .addTo(map);
t.on('click', function(){
    console.log("tooltip click handler");
});
```
While, with the following clicking the tooltip fires any marker click handler defined
```
var marker = L.marker([51.5, -0.09]).addTo(map);
var t = L.tooltip({permanent: true, interactive:true}, marker).setLatLng([51.505, -0.09])
                                                              .setContent("test")
                                                              .addTo(map);

marker.bindTooltip(t);
marker.on('click', function(){
    console.log("marker click handler");
});
```
Is it possible to prevent any marker handler defined to be executed when clicking a tooltip?

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

**Comment by gommo** [comment]
Did you get an answer on this @mepdr as I have a similar issue

**Comment by chriszrc** [comment]
As far as I can tell, this is a bug, because attached a click listener should technically work, and if you're working with anything besides a marker, I don't see a way to attach a click listener (which I'd like to do, since I'm working with a "permanent" tooltip)
