### ISSUE TITLE
LayerGroup.toGeoJSON() can produce invalid GeoJSON

### ISSUE THREAD

**Issue by stuporglue** [Leaflet/Leaflet#5045]
## How to reproduce
- Leaflet version I'm using: unpkg.com/leaflet@1.0.1/dist/leaflet-src.js
- Browser (with version) I'm using: Firefox 49.0, Chrome  54.0.2840.71
- OS/Platform (with version) I'm using: Mac 10.11.6
## What behaviour I'm expecting and which behaviour I'm seeing

I expect the output of LayerGroup.toGeoJSON() to be valid GeoJSON. If the object can't be represented with valid GeoJSON I should get an error or warning while calling toGeoJSON().

Instead, the object created by toGeoJSON() is invalid GeoJSON and cannot be consumed by L.GeoJSON and reports.

`Uncaught Error: Invalid GeoJSON object` 

Since FeatureGroup and GeoJSON both extend LayerGroup, this also affects them. 
## Minimal example reproducing the issue

```
function test(){
    var lg = new L.LayerGroup();
    var startingJson = {"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[78.3984375,56.9449741808516]}}]};
    var gj = new L.GeoJSON(startingJson);
    lg.addLayer( gj );

    var json2 = lg.toGeoJSON();
    console.log( json2 );
       // Results in the following. The nesting is all weird. 
       // {"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[78.3984375,56.9449741808516]}}]}}]}

    gf = new L.GeoJSON(json2);
}
test();
```

**Comment by IvanSanchez** [comment]
Playground at https://playground-leaflet.rhcloud.com/mod/edit?html,console , standalone at https://playground-leaflet.rhcloud.com/mod . This involves `FeatureCollection`s being used as GeoJSON geometries.
