### ISSUE TITLE
popup layer + rightClick fail 

### ISSUE THREAD

**Issue by obeckman** [Leaflet/Leaflet#5047]
hi i am using v1.0.0
on chrome, ios 

i have added a layer containing  a popup to the map (so multiple popups will be seen @ the same time )
when the popup is created i use addListener to  'contextmenu' event  but fail to catch the event ... 

```
L.DomEvent.addListener(layer.getElement(), 'click', function(event){
    //works fine
     alert("click")
});

L.DomEvent.addListener(layer.getElement(), 'contextmenu', function(event){
    //doesn't fire
    alert("contextmenu")
 });
```

**Comment by IvanSanchez** [comment]
Playground at https://playground-leaflet.rhcloud.com/lenu/edit?html,output , standalone at https://playground-leaflet.rhcloud.com/lenu .

Not reproducible in android chrome (reminder: "chrome" on iOS uses Safari's webkit engine, not blink).

**Comment by Obeckman** [comment]
just checked your link in desktop on 2 separate computers  IOS chrome (Version 53.0.2785.101 (64-bit)) + Windows chrome (Version 53.0.2785.143m) didn't fired...   

10x for the quick replay

**Comment by johnd0e** [comment]
@obeckman 
Could you provide full code to reproduce the issue?
