### ISSUE TITLE
Zoom bug on some layers

### ISSUE THREAD

**Issue by TechnoMag82** [Leaflet/Leaflet#5048]
```
var littleton = L.marker([47.878364, 35.059151]).bindPopup('This is Littleton, CO.');
var circle = L.circle([47.878364, 35.053151], 200);
var cities = L.layerGroup([littleton]);
cities.addTo(map);
cities.addLayer(circle);
```

Step for reproduce
1. Select google map layer
1. Zoom IN max to circle (circle must fill screen)
2. Zoom out. Bug is visible.
3. Move map left-right. Bug observed.
4. Change map layer. Bug observed.

![bug_zoom](https://cloud.githubusercontent.com/assets/23052720/19683677/d9b7d14a-9abb-11e6-8b60-85654127f6f5.png)

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by TechnoMag82** [comment]
Bug visible in old version of embeded chromium browser for Delphi.
