### ISSUE TITLE
L.geoJSON layer attribution not shown on map control

### ISSUE THREAD

**Issue by matthew-shaw** [Leaflet/Leaflet#5051]
## How to reproduce
- Leaflet version I'm using: 1.0.0
- Browser (with version) I'm using: Chrome 54
- OS/Platform (with version) I'm using: OS X 10.11.6
- Add L.geoJSON layer with an attribution option to a map
## What behaviour I'm expecting and which behaviour I'm seeing

Attribution statement not added to attribution control on map, in the same way that `L.tileLayer` is.
## Minimal example reproducing the issue

https://github.com/MashSoftware/place/blob/master/mash_place/templates/counties.html#L65

**Comment by IvanSanchez** [comment]
Even more minimal example at https://playground-leaflet.rhcloud.com/zuta/edit?html,output

One could argue that this behaviour as documented, as [the docs do not mention an `attribution` option for `L.GeoJSON`](http://leafletjs.com/reference-1.0.0.html#geojson-option). In this way, this is similar to #4277 and #4279.

The workaround, as in those cases, is to make sure that the layers created by `pointToLayer` and `style` callback options create leaflet layers with attribution (or the right pane or whatever).

I can see a use case for this. The question is whether we want an `attribution` option in `L.GeoJSON` or `L.LayerGroup`.

**Comment by matthew-shaw** [comment]
Attribution feels like a feature that should exist in nearly all layer types. I wouldn't expect metadata about layers to behave differently, they're all just text attributes about the spatial data after-all.
