### ISSUE TITLE
Panning map issue when click-drag is initiated on marker

### ISSUE THREAD

**Issue by foodtruckfiesta** [Leaflet/Leaflet#506]
A user holds the mouse button down and drags the mouse to pan around on a map.  There is an issue when the mouse down event is initiated on top of a custom icon.  In that case the default web browser behavior is experienced whereby the image can be dragged off of the webpage.

With Google Maps, when you click on a custom marker and drag the map, the mouse pointer icon turns into the "move" cursor and one is able to pan around on the map.

Google Maps example behavior: http://code.google.com/apis/maps/documentation/javascript/examples/icon-complex.html
Leaflet example behavior: http://leaflet.cloudmade.com/examples/custom-icons.html

I can help develop a solution - please let me know how you would like to proceed.

**Comment by darklomba** [comment]
I think this is happening again in 1.9.3
