### ISSUE TITLE
Dynamic attribution text is added to the last added attribution control on the map

### ISSUE THREAD

**Issue by theashyster** [Leaflet/Leaflet#5061]
## How to reproduce

- Leaflet version I'm using: master
- Browser (with version) I'm using: Mozilla Firefox 49.0.2
- OS/Platform (with version) I'm using: Windows 8.1
- Initialize the map
- Add custom attribution control
- Add tileLayer with an attribution

## What behaviour I'm expecting and which behaviour I'm seeing

After the `tileLayer` is added to the map, the dynamic attribution text that comes from the `tileLayer` options are added to the custom attribution control and not the Leaflet default one. I think there should be a way to specify there the attribution adds up. I have looked at `L.Control.Attribution` and in the method `onAdd` there is this line `map.attributionControl = this;` that makes the last added attribution control the default one to which all other attributions are added. If I use attribution control also for different purposes I get the problem mentioned above. Although if attribution control is supposed to serve only one and only one purpose then this is probably not an issue. But since from the outside it looks like a really flexible `Control` (position and prefix which is basically any html) I have used it to display the logged in user in the bottom right corner and the company logo in the bottom left corner. And doing so the dynamic attribution text can be added to any one of these attribution controls, depends on the order we add them to the map.

Also looks like there is no way of specifying the default position of the default Leaflet attribution control without using mixins on map initialize, it will always be on the bottom right corner.

But if this is not an issue at all, then I will probably have to create a Control that extends `L.Control.Attribution` and overrides `onAdd` to remove the line that messes things up for me.

## Minimal example reproducing the issue

Demo: http://playground-leaflet.rhcloud.com/fom/edit?html,output

**Comment by IvanSanchez** [comment]
@theashyster While I see your point, I'm not sure we should change anything. It does make sense to have a bit better behaviour related to which is the map's default attribution control, though.

Will you please read http://leafletjs.com/examples/extending/extending-3-controls.html#controls , ponder on it a bit, then reply back here?

**Comment by theashyster** [comment]
@IvanSanchez Thanks for the quick answer. I agree, probably there shouldn't be any changes made because of this, because there is a better way of how to achieve what I am trying to do. And I also agree about the default attribution control, because there might be situations when you want to split the attribution text and put it in two lines or place some part of it in a different corner of the map.

Thanks for the example, I think I will just create a basic Control that displays html in the corner I want, without extending `L.Control.Attribution` to achieve it.

**Comment by IvanSanchez** [comment]
I think it's appropriate to close this one with no further action.
