### ISSUE TITLE
Leaflet not getting correct new size when exit fullscreen on Chrome

### ISSUE THREAD

**Issue by ywx649999311** [Leaflet/Leaflet#5062]
## How to reproduce

- Leaflet version I'm using: 1.0.0
- Browser (with version) I'm using: Chrome 54.0.2840.71
- OS/Platform (with version) I'm using: OSX 10.11.6 
- step 1: The official fullscreen plugin demo: http://leaflet.github.io/Leaflet.fullscreen/
- step 2: enter and exit fullscreen, the map will be misplaced

## What behaviour I'm expecting and which behaviour I'm seeing
 I am expecting the map return to where it was after exiting fullscreen mode, however the map was misplaced!
## Minimal example reproducing the issue
http://leaflet.github.io/Leaflet.fullscreen/
- [ ] this example is as simple as possible

Before entering fullscreen mode
![screen shot 2016-10-29 at 1 13 16 am](https://cloud.githubusercontent.com/assets/11515291/19827575/f321433a-9d74-11e6-9390-ec42068fafa9.png)

After exited the fullscreen mode
![screen shot 2016-10-29 at 1 13 27 am](https://cloud.githubusercontent.com/assets/11515291/19827579/04c61048-9d75-11e6-9ed4-11215a35547a.png)

Note: I didn't do any panning or zooming actions.

**Comment by robertharm** [comment]
We discovered the same issue with our WordPress plugin Maps Marker Pro, where we also use the fullscreen plugin. We solved this by triggering invalidateSize() on fullscreenchange:

`map.on("fullscreenchange",function(e){
if(!map.isFullscreen()) {map.invalidateSize();}
}`

**Comment by IvanSanchez** [comment]
Not a bug in core Lealet. Submit this bug to the Leaflet.Fullscreen repo instead.
