### ISSUE TITLE
L.Draggable._dragging stuck

### ISSUE THREAD

**Issue by remster** [Leaflet/Leaflet#5063]
## How to reproduce
- Leaflet version I'm using: //cdnjs.cloudflare.com/ajax/libs/leaflet/1.0.0/leaflet.js
- Browser (with version) I'm using: FF 49.0.2
- OS/Platform (with version) I'm using: Ubuntu 16.04

I have a temporary draggable markers that appear over a feature (on hover) and unless are dragged - I disappear them should the mouse hover away. Unless dragged, i.e.: unless they received 'dragstart'.
When i drag them real quick however (for some reason reproduces more easily on FF - seems slower) then the following happens:
1. `L.Draggable._onDown` sets the global `L.Draggable._dragging = true;`
2. `mousemove` reaches my code and at this point:
   - I haven't received 'dragstart' yet. 
   - the mouse is far enough for me to decide to remove the marker
3. I remove the marker and `L.Draggable._onUp` is never called leaving `L.Draggable._dragging` rot in its sorry state forever.

Obviously the offending consequence is that nothing can be dragged ever.
Understanding what's cooking I have a workaround, so no rush with this.

To see for youself:
https://playground-leaflet.rhcloud.com/qaha/1/edit?html,output

start dragging the marker and do not stop until it disappears. When it disappears the map is not draggable/panable.
## What behaviour I'm expecting and which behaviour I'm seeing

I would expect the code be more resilient to this scenario - more specifically:
- if a draggable is being removed amidst a drag it should clear `L.Draggable._dragging`

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by remster** [comment]
There you go: https://playground-leaflet.rhcloud.com/qaha/1/edit?html,output

start dragging the marker and do not stop until it disappears. When it disappears the map is not draggable/panable.

**Comment by IvanSanchez** [comment]
#5065 should fix this, see https://playground-leaflet.rhcloud.com/qeha/1/edit?html,output

**Comment by Dexus** [comment]
This "fix" dont worth anything, because if i try it the marker is gone while drag...

**Comment by perliedman** [comment]
@Dexus if you're talking about @IvanSanchez playground above (qeha), that's because the test removes the marker a short while after you start dragging, that's part of the test:

```js
    marker.on("dragstart", function() {
      setTimeout(function() {
        map.removeLayer(marker);
      }, 100); 
    });
```

or did you mean something else is wrong with the fix?

**Comment by landonreed** [comment]
@perliedman, I think this bug fix might cause unintended results for some users of Leaflet.  Is my understanding correct that if the marker being dragged is changed while dragging the `this` reference will no longer equal `L.Draggable._dragging` and cause `finishDrag` to fire?

I've been working on updating to Leaflet 1.0.2 and think this bug fix is the source of some issues I'm running into.  Should I open a new issue?

**Comment by IvanSanchez** [comment]
@landonreed Please open a new issue, *clearly explaining what you mean* by "unintended" and "some issues I'm running into". Reproducible examples, etc.
