### ISSUE TITLE
New Tooltip from Leaflet 1.0.0 not working on mobile devices

### ISSUE THREAD

**Issue by bujulia** [Leaflet/Leaflet#5069]
## How to reproduce
- Leaflet version I'm using: 1.0.0
- Browser (with version) I'm using: any
- OS/Platform (with version) I'm using: Android or iPhone

## What behaviour I'm expecting and which behaviour I'm seeing
As with touch devices, the "hover" or "mouse-in, mouse-out" functions obviously don't work. So, a tooltip (which by default is only shown when hovering over a marker) probably wouldn't make sense on your mobilephone. Therefore, I'd expect it not to show at all. BUT: when combining a Tooltip (nonPermanent) and a PopUp (onClick), both of them appear when clicking the marker on the mobile device. Wished behaviour: Only PopUp showing and ignoring the Tooltip

## Minimal example reproducing the issue
http://playground-leaflet.rhcloud.com/bule/1/edit?html,output

**Comment by yohanboniface** [comment]
I don't think this behavior should be Leaflet default (see https://github.com/Leaflet/Leaflet/issues/4741 for example).
I think it's the implementer responsibility not to add the tooltip in mobile mode if they does not want them.
I'm closing because I consider no action is needed from our side. But the discussion is still open. We'll reopen if we decide action is needed.

**Comment by bujulia** [comment]
Thanks for the quick answer. I'm pretty new to programming, so I don't know much about "mobile mode" and just expect everything to work as I would imagine.

So your tip would be to somehow disable the tooltip whenever the webpage is openede from a mobile device and not do so on desktop? Is there an easy function for that?

Greetings, Julia
________________________________
Von: Yohan Boniface [notifications@github.com]
Gesendet: Mittwoch, 2. November 2016 15:34
An: Leaflet/Leaflet
Cc: Burgermeister Julia; Author
Betreff: Re: [Leaflet/Leaflet] New Tooltip from Leaflet 1.0.0 not working on mobile devices (#5069)


I don't think this behavior should be Leaflet default (see #4741<https://github.com/Leaflet/Leaflet/issues/4741> for example).
I think it's the implementer responsibility not to add the tooltip in mobile mode if they does not want them.
I'm closing because I consider no action is needed from our side. But the discussion is still open. We'll reopen if we decide action is needed.

**Comment by yohanboniface** [comment]
You may deal with this kind of flags to decide whether or not to add the tooltip: http://leafletjs.com/reference-1.0.0.html#browser-touch

**Comment by bujulia** [comment]
I'll check that and see if it helps for my problem or not. Will try to just not add the Tooltip on the mobile version.
________________________________
Von: Yohan Boniface [notifications@github.com]
Gesendet: Mittwoch, 2. November 2016 16:40
An: Leaflet/Leaflet
Cc: Burgermeister Julia; Author
Betreff: Re: [Leaflet/Leaflet] New Tooltip from Leaflet 1.0.0 not working on mobile devices (#5069)


You may deal with this kind of flags to decide whether or not to add the tooltip: http://leafletjs.com/reference-1.0.0.html#browser-touch

**Comment by perliedman** [comment]
A word of warning that there are plenty of laptops that support touch, but still most likely use mouse/touchpad as primary device. It's very annoying with sites that assume your device is a phone/tablet just because it supports touch.

Ideally you'd want to detect that the device has touch and _doesn't_ have a mouse or similar, but to my knowledge there's no way to do that.

**Comment by tormi** [comment]
@bujulia, try this:

```
    marker.bindPopup("<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. Suspendisse urna nibh, viverra non, semper suscipit, posuere a, pede.</p><p>Donec nec justo eget felis facilisis fermentum. Aliquam porttitor mauris sit amet orci. Aenean dignissim pellentesque felis.</p>");
    
    if (L.Browser.mobile != true) {
        marker.bindTooltip("Tooltip");
    }
```
http://playground-leaflet.rhcloud.com/tuxe/edit?html,output
