### ISSUE TITLE
Tile layers in EPSG 4326 

### ISSUE THREAD

**Issue by MortenHofft** [Leaflet/Leaflet#5072]
## How to reproduce
- Leaflet version I'm using: 1.0.1
- Browser (with version) I'm using: chrome Version 53.0.2785.143
- OS/Platform (with version) I'm using: mac os X el capitan
- create a map with crs 4326
- add a tile layer
- inspect coordinates

## What behaviour I'm expecting and which behaviour I'm seeing
I might be doing something wrong, but here goes:
I would expect the tile layer to match my baselayer and coordinates (as it did in 0.7). But the tiles do not align with the wms map and coordinates provided on mouseover. 

## Minimal example reproducing the issue
I have the same code in Leaflet 0.7 and 1.0.1
One works as expected, the other doesn't. Is there a new setting or is it a bug?
using 1.0: http://codepen.io/hofft/pen/gLYEzW
using 0.7: http://codepen.io/hofft/pen/LbPadV/

**Comment by IvanSanchez** [comment]
[Minimal playground here](https://playground-leaflet.rhcloud.com/ray/edit?html,output).

Leaflet 1.0.x complies with the [TMS way of doing EPSG:4326](https://wiki.osgeo.org/wiki/Tile_Map_Service_Specification#global-geodetic):

> This scaling allows an initial zoom level that consists of 2 256x256 pixel tiles covering the whole earth, with an <Origin> of (-180,-90).

Configure your tilesets accordingly. The 0.7.x way of doing it (with the tile origin at Null Island) was a hackish way of indexing tiles, and you should consider deprecating it.

**Comment by timrobertson100** [comment]
Thanks @IvanSanchez 

I think it would be good to make this abundantly clear in docs as a non-backwards compatable behavioural change.  I get why, and it's great that finally there is some clarity on this but I suspect it's going to break a ton of stuff (like existing CartoDB overlays, arctic connect polar.js and all our tile pyramids we've built etc).

Is there a workaround that won't involve rebuilding terabytes of tile pyramids you know of please?

**Comment by IvanSanchez** [comment]
If you have a good idea on how to put this in the docs, suggestions (and patches) are welcome. We've got a bunch of other stuff we consider a bit more important right now, I'm afraid.

**Comment by IvanSanchez** [comment]
> Is there a workaround that won't involve rebuilding terabytes of tile pyramids you know of please?

You *should* be able to tweak the tilelayer's `getTileUrl` method so it applies a custom shift to the tile coordinates - shift the zoom by `-1`, and the `x` and `y` by `+2^zoom` or something like that.

**Comment by timrobertson100** [comment]
Thanks @IvanSanchez - I used your words from this issue

**Comment by perliedman** [comment]
Note also it shouldn't be too complicated to port 0.7's `L.CRS.EPSG4326` to 1.0. Without having checked the code, I'd assume to difference i mainly the CRS's transform.
