### ISSUE TITLE
map getZoom() not working 

### ISSUE THREAD

**Issue by EarthInnovation** [Leaflet/Leaflet#5081]
In Leaflet 1.0.1 getZoom() does not update and returns contant values (4 in my case)

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by IvanSanchez** [comment]
No more information has been provided, and a few weeks have passed. We'll assume this issue is no longer relevant and/or there is no interest to make a better report.
