### ISSUE TITLE
Canvas renderer click events have unexpected propagation

### ISSUE THREAD

**Issue by jbccollins** [Leaflet/Leaflet#5091]
## How to reproduce

- Leaflet version I'm using: https://leafletjs-cdn.s3.amazonaws.com/content/leaflet/master/leaflet-src.js
- Browser I'm using: Chrome
- OS/Platform I'm using: Windows 10

## What behaviour I'm expecting and which behaviour I'm seeing
Related to: #5082 which was resolved by @perliedman and @IvanSanchez.

I expect that when two features render with overlapping pixels (which does not necessarily mean overlapping geometries) the feature that renders on top will be the only feature to receive click events. The default SVG renderer handles overlapping features in this way. The canvas renderer triggers click events on all layers that contain the clicked point.
Here are two .gif's demonstrating the differences in behaviour. In both gifs "mouseover" on a feature will color it blue and "click" on a feature will color it black.

SVG (expected):
![click_expected](https://cloud.githubusercontent.com/assets/8915552/20223810/43b913b0-a809-11e6-86b5-576be7ffc01e.gif)

Canvas: (unexpected)
![click_unexpected](https://cloud.githubusercontent.com/assets/8915552/20223817/4a683754-a809-11e6-9466-288b949d82d9.gif)

## Minimal example reproducing the issue
http://jsfiddle.net/jcollin6/rvk38ga5/2/

**Comment by perliedman** [comment]
I should have seen this one coming, I guess the click logic is very similar to the old hover logic. I will look into it as soon as I can find the time.

**Comment by jbccollins** [comment]
@perliedman yeah, sorry, I hate to be a bother. Hopefully the click/hover logic is similar enough that this won't be too much trouble for you.

**Comment by jbccollins** [comment]
Thanks guys! Any idea when the next npm version that will contain these changes is scheduled to be deployed?
