### ISSUE TITLE
Zoom button on printable-version

### ISSUE THREAD

**Issue by theel0ja** [Leaflet/Leaflet#5095]
- [x] I'm reporting a bug, not asking for help
- [x] I've looked at the [documentation](http://leafletjs.com/reference-1.0.0.html) to make sure the behaviour is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: Leaflet 1.0.1
- Browser (with version) I'm using: Chrome 54.0.2840.100 (64-bit)
- OS/Platform (with version) I'm using: Linux Mint 18 Cinnamon
- Open [this example at leafletjs.com](http://leafletjs.com/examples/quick-start/example.html) or any other Leaflet-map.
- Open print menu (ctrl + p) and see those plus and minus buttons.

## What behaviour I'm expecting and which behaviour I'm seeing

Plus and minus buttons are not needed in print, because you can't press them (paper)...

![Plus and minus buttons on Leaflet print](https://cloud.githubusercontent.com/assets/5832930/20240743/ff5c28a8-a928-11e6-8bbe-38f0bae5f7ef.png)

**Comment by jbccollins** [comment]
> I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using 

IMHO I don't think this is really an issue that Leaflet should solve. If you have a use case where you want to hide/show controls when printing I'd suggest you implement an independent solution. Give your controls classes/id's and on window.matchMedia or beforePrint/afterPrint hide/show the controls.

**Comment by perliedman** [comment]
I agree with @jbccollins, printing is outside Leaflet's scope,

Also, although it might often be the case that print shouldn't show controls, it's not necessarily true for all use cases, and given that we don't really care about print, it feels odd to add this to core.

It is easy for any application to override this with local CSS rules, like @jbccollins also says.

**Comment by Heshyo** [comment]
For anyone interested, something like the following could work

```
@media print {
	// To only hide controls at the top (usually where the zoom buttons are).
	.leaflet-top {
		display: none;
	}

	// To hide all controls, not just the ones at the top (this would hide the scale 
	// if it's display on the bottom left for example).
	.leaflet-control-container {
		display: none;
	}
}
```
