### ISSUE TITLE
Rendering Mapbox GL Style as base layer

### ISSUE THREAD

**Issue by dshakya** [Leaflet/Leaflet#5102]
## How to reproduce

- Leaflet version I'm using:1.0.1
- Browser (with version) I'm using: Firefox 49.0.2
- OS/Platform (with version) I'm using: Windows 7 Enterprise
- step 1: Created Mapbox Style in Mapbox Studio
- step 2: Added the tile normally using L.tilelayer()
- step 3: Map appears in the browser but few of the layers are not rendered completely. Only partial render and not at all most of the times.

When I load the same Mapbox style using Mapbox GL API (mapbox-gl-js), the layers load fine.

## What behaviour I'm expecting and which behaviour I'm seeing

All layers of the map to be rendered properly with L.tilelayer()

## Minimal example reproducing the issue

Using Leaflet API: http://playground-leaflet.rhcloud.com/vaxe
Same base map with using Mapbox GL API.: http://playground-leaflet.rhcloud.com/naxil

**Comment by perliedman** [comment]
As far as I can see, this is not Leaflet issue, Leaflet correctly displays the images returned by Mapbox's API. Any differenes you see is a difference in how Mapbox render the styling depending on if its done in the browser (Mapbox GL) or on Mapbox's servers (Leaflet). You should report this to Mapbox.

**Comment by dshakya** [comment]
Thanks @perliedman . Will report it to Mapbox.

**Comment by dshakya** [comment]
I have now posted it here for cross-reference.

https://github.com/mapbox/mapbox-gl-js/issues/3630

**Comment by dshakya** [comment]
For the sake of completeness, the issue was fixed by adding @2x for retina display.

https://www.mapbox.com/api-documentation/#retina
