### ISSUE TITLE
Colliding/overlapping tooltips with {permanent: true}

### ISSUE THREAD

**Issue by tomchadwin** [Leaflet/Leaflet#5104]
- [x] I'm reporting a bug, not asking for help (more a feature request than a bug)
- [x] I've looked at the [documentation](http://leafletjs.com/reference-1.0.0.html) to make sure the behaviour is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: 1.0.0
- Browser (with version) I'm using: Chrome 54.0.2840.99 m
- OS/Platform (with version) I'm using: Win7 x64

- add a point layer with high point density
- enable tooltips
- use tooltip option `permanent: true`

## What behaviour I'm expecting and which behaviour I'm seeing
- I would hope for (not expect) an option to prevent overlapping tooltips
- I see overlapping tooltips

## Minimal example reproducing the issue
http://playground-leaflet.rhcloud.com/zohe/edit?html,output

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

A plugin existed to hide colliding features, and an issue was raised in the Leaflet.Label repo to adapt for pre-Leaflet1.0.0 labels, but I don't believe it was implemented:

https://github.com/Leaflet/Leaflet.label/issues/128
https://github.com/MazeMap/Leaflet.LayerGroup.Collision/issues/1

Any plans to implement something for the new Leaflet1 tooltips?

**Comment by perliedman** [comment]
While I agree this would be nice, I think handling label collision is too complex to fit in Leaflet's core.

I would suggest you look into this plugin, which sounds like it could be useful in your use case: https://github.com/yakitoritabetai/Leaflet.LabelTextCollision

**Comment by IvanSanchez** [comment]
Or https://github.com/MazeMap/Leaflet.LayerGroup.Collision .

**Comment by tomchadwin** [comment]
Ah, many apologies for not having found that plugin. Yes, that look like it's exactly what I need. Thank you so much.

**Comment by tomchadwin** [comment]
@IvanSanchez Yes, I linked to the issue on that, but not sure if it was ever implemented for labels/tooltips. Thanks.

**Comment by IvanSanchez** [comment]
@tomchadwin I designed it for markers and `DivIcon`s, but I'm sure it could be upgraded to support tooltips.

**Comment by tomchadwin** [comment]
@IvanSanchez Yes, I'm sure you're right. Whether I can understand it well enough to do that is another question...

@perliedman I'm not sure about Leaflet.LabelTextCollision:

- it operates at the renderer level, which is not at all user-friendly
- it loses all the native `L.tooltip` functionality
- no label formatting (yet)

So perhaps Leaflet.LayerGroup.Collision is the best approach - hopefully its use of rbush should be good for performance, which is the concern with solving this issue.

Thanks, both - much appreciated.

**Comment by Shadowman4205** [comment]
@tomchadwin Hello, did you find solution with this?

**Comment by tomchadwin** [comment]
@Shadowman4205 No, I've not implemented any solution to this myself. However, you should take a look at @JamesMilnerUK's Labelgun:

https://github.com/Geovation/labelgun

I believe that's a perfect solution to the issue, but I've not understood it well enough yet to implement it.

**Comment by geobde** [comment]
@tomchadwin i use react-leaflet(https://react-leaflet.js.org) and i want to avoid tooltip collision did you find any solution  compatible with react-leaflet ?

Here is my render function:

 <Map useFlyTo={true} zoomControl={false}>
      <ZoomControl />
      <TileLayer />
      <MarkerClusterGroup>
        {Markers()}
      </MarkerClusterGroup>}
   </Map>
