### ISSUE TITLE
Panning map no longer works after removing marker via touchscreen input

### ISSUE THREAD

**Issue by Ceremony64** [Leaflet/Leaflet#5105]
Take a look at the following code and the corresponding live example: http://jsbin.com/vipitimuzo
```javascript
var map = L.map('map').setView([50, 10], 10);

L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);

map.on("click", function (x) {
  L.marker(x.latlng, {
    draggable: true
  }).on("dblclick contextmenu", function (e) {
    this.remove();
  }).addTo(map);
});
```

Clicking on the map adds a marker, rightclicking/pressing or doubleclicking/doubltapping it removes it. This works flawlessly on desktop (with mouse) in both Chrome and Firefox.

On mobile, however both in Firefox and Chrome on Android (7.0), once a marker gets removed, you can no longer pan the map. you can zoom, both double-tapping and pinching, but panning with a single finger is no longer possible.

This issue does not occur when the marker are not draggable or the user is no longer touching the screen when the marker gets remove (e.g. adding a delay with setTimeout)

**Comment by IvanSanchez** [comment]
This is with Leaflet 1.0.1, right?

**Comment by Ceremony64** [comment]
Yes

**Comment by IvanSanchez** [comment]
Please include the Leaflet version in your bug reports, it's important info :-)

Can you try with the latest code from `master` branch? There's a chance that the changes from https://github.com/Leaflet/Leaflet/pull/5065 might have fixed this already. (Hint: `<link href="https://leafletjs-cdn.s3.amazonaws.com/content/leaflet/master/leaflet.css" rel="stylesheet" type="text/css" /><script src="https://leafletjs-cdn.s3.amazonaws.com/content/leaflet/master/leaflet-src.js"></script>`)

**Comment by Ceremony64** [comment]
Yep, its fixed in the master. Guess that was it 👍

**Comment by IvanSanchez** [comment]
Nothing to do here, then :smile:
