### ISSUE TITLE
Touchevents in Chrome Beta & Dev for Android do not fire

### ISSUE THREAD

**Issue by Ceremony64** [Leaflet/Leaflet#5107]
Take a look at http://jsbin.com/dehupokofu/2/edit and click on the triangle.
```javascript
var map = L.map('map').setView([51.5, -0.09], 13);

L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);

var polygon = L.polygon([
    [51.509, -0.08],
    [51.503, -0.06],
    [51.51, -0.047]
]).addTo(map).on("mousedown touchstart", function (e) {
  window.alert(e.type)
})
```

On my android device (running Nougat 7.0):
Firefox (Stable, Beta & Aurora) fires a mousedown event, no touchstart event though.
Chrome (Stable) fires a mousedown event, no touchstart event though.
Chrome (Beta & Dev) doesn't fire any events.

I guess chrome broke backward compatibility by not firing mouse events anymore and touchevents don't seem to be supported natively by LL?

P.S. Example uses LL 1.0.1 and I also tested LL-master with the same results

**Comment by Caramelo18** [comment]
@Ceremony64 I am running Nougat 7.0 and Chrome Beta 55.0.2883.63 and I have tested your link. Tried to click on the triangle and got a mousedown event. Is there anything I am missing? Can you test again?

**Comment by Ceremony64** [comment]
Seems to have been fixed with the new versions of Chrome! Thanks!
