### ISSUE TITLE
On IE ToolTip is not removed when layer when using bring to front in mouseover (v1.0.1)

### ISSUE THREAD

**Issue by tmfrnz** [Leaflet/Leaflet#5108]
## How to reproduce

- Leaflet version I'm using: 1.0.1
- Browser (with version) I'm using: IE Edge, IE 9
- OS/Platform (with version) I'm using: Windows 7 Pro
- use example https://playground-leaflet.rhcloud.com/yari/1/edit?html,output
- hover over polygons

## What behaviour I'm expecting and which behaviour I'm seeing
Tooltip should be removed on mouseout (as it does on Chrome and Firefox) even when layer is brought to front in mouseover function

## Minimal example reproducing the issue
- https://playground-leaflet.rhcloud.com/yari/1/edit?html,output

```js
    polygon.on({
      mouseover  : function (e) {
        polygon.bringToFront();
        polygon.bindTooltip("polygon 1").openTooltip()
      },
      mouseout  : function (e) {
        polygon.closeTooltip()
       },
    })
```

**Comment by billjoe** [comment]
issue still exists in 1.51.1

**Comment by johnd0e** [comment]
Unable to reproduce
