### ISSUE TITLE
On IE10 and earlier ToolTip is flickering on mouseover (v1.0.0)

### ISSUE THREAD

**Issue by tmfrnz** [Leaflet/Leaflet#5109]
## How to reproduce

- Leaflet version I'm using: 1.0.0
- Browser (with version) I'm using: IE10 and earlier
- OS/Platform (with version) I'm using: Win 7 Professional
- use example ~~https://playground-leaflet.rhcloud.com/joje/1/edit?html,output~~ https://playground-leaflet.rhcloud.com/mow/1/edit?html,output
- hover over marker

## What behaviour I'm expecting and which behaviour I'm seeing
ToolTip should show until `mouseout` event (as on IE Edge, Chrome Firefox), instead it flickers as if the tooltip's own mouseover triggers mouseout for the layer it is bound to

It could be related to the use of absolute positioning of the tooltip in IE 10 and earlier instead of css transform.

## Minimal example reproducing the issue

- ~~https://playground-leaflet.rhcloud.com/joje/1/edit?html,output~~ https://playground-leaflet.rhcloud.com/mow/1/edit?html,output

```js
    var marker = new L.Marker(myCenter)
    .bindTooltip('marker',{
              direction : 'center',
              sticky:true,
            })
```

**Comment by yohanboniface** [comment]
@tmfrnz: the playground seems broken, can you have a look?

**Comment by tmfrnz** [comment]
@yohanboniface my apologies, here a corrected version https://playground-leaflet.rhcloud.com/mow/1/edit?html,output

**Comment by jonkoops** [comment]
Closing this issue as we have decided to drop support for Internet Explorer in a future version of Leaflet (see #6136).
