### ISSUE TITLE
How to create App with leaflet-map ...

### ISSUE THREAD

**Issue by Baumhaus12** [Leaflet/Leaflet#5111]
Hey there,
i´m trying to create a App for a fun park. 
The users shoult see a map (i´ll create the data on my on with QGIS). The map should enable: 
* Navigation on the own Network of path by keyword (rollercoaster, toilett..) and by setting a marker on the map
* Current Position of the user

Is this possible with leaflet and QGIS Server? (prefere OpenSource) ore are there any better ways to go on with this Project? I don´t know how leaflet can route on my own data with own keywords (not adresses from OSM or something..)..

Thanks for any help!

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by Baumhaus12** [comment]
ok THX
