### ISSUE TITLE
content editable div in map popup causing error in leaflet 1.0.1

### ISSUE THREAD

**Issue by rikkitikkitumbo** [Leaflet/Leaflet#5113]
- Leaflet version I'm using: 1.0.1
- Browser (with version) I'm using: chrome Version 54.0.2840.90 (64-bit)
- OS/Platform (with version) I'm using: linux

Hey,  made a content editable div in a leaflet popup.  Everything seems to work fine (I'm able to type things with no errors) until I press enter... then I get this message:

```
leaflet101.js:formatted:854 Uncaught TypeError: Cannot read property 'lat' of undefined(…)
```

I believe it's this line in the code (on line 854):
```
, n = Math.max(Math.min(i, t.lat), -i)
```

from:
```
o.Projection.SphericalMercator = {
        R: 6378137,
        MAX_LATITUDE: 85.0511287798,
        project: function(t) {
            var e = Math.PI / 180
              , i = this.MAX_LATITUDE
              , n = Math.max(Math.min(i, t.lat), -i)
              , s = Math.sin(n * e);
            return new o.Point(this.R * t.lng * e,this.R * Math.log((1 + s) / (1 - s)) / 2)
        },
```  

For whatever reason, something becomes undefined when I press enter in the content editable div.  I tried the same thing in an input type='text' and I get the same error.  I don't get this error in leaflet .77

Any ideas?

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by rikkitikkitumbo** [comment]
sure: https://rightnowportland.com

just click anywhere on the map and then in the textbox (after 'Right
now...'), hit enter.

**Comment by IvanSanchez** [comment]
[Minimal, Complete, Verifiable example](https://stackoverflow.com/help/mcve), please. And using `leaflet-src.js` instead of `leaflet.js`. Debugging your application is not my job. Isolating a reproducible bug is not my job.

**Comment by rikkitikkitumbo** [comment]
ok, sorry

**Comment by IvanSanchez** [comment]
Listen: this might be a Leaflet bug (I'm suspecting it might even be related to #4960), but you've got to show me the bug, nice and clear. What I see right now is a web application that misbehaves.

First you've gotta **convince me** that this is a Leaflet bug. This is not asking for much, right? And to convince me that there is a bug, you've gotta [show the bug clearly to me](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

If you're sure that «content-editable `<div>`s cause problems in popups», show me exactly that, and not more.
