### ISSUE TITLE
_getPathPartStr returns undefined inside getPath for polygon when adding a polygon to a feature group

### ISSUE THREAD

**Issue by stmparker** [Leaflet/Leaflet#5119]
I will create steps to reproduce if this is not something that is known, or I'm not doing something obviously wrong or If this is not enough information... but when I have a custom Polygon Class that I'm trying to add to a feature group.  On Layeradd I'm getting the error:

```
angular.js:13920 TypeError: Cannot read property 'appendChild' of undefined
    at NewClass.onAdd (leaflet-src.js:4506)
    at NewClass._layerAdd (leaflet-src.js:2225)
    at NewClass.addLayer (leaflet-src.js:1683)
    at NewClass.addLayer (leaflet-src.js:4261)
    at NewClass.addLayer (leaflet-src.js:4375)
    at NewClass.addLayer ((index):37)
```

I traced it down to _getPathPartStr on L.Polyline definition:

L.Path.VML is undefined.  I'm not sure why I need this or what it is though.  That's as far as I could get debugging.  If I can provide any more information please let me know

----

## How to reproduce

- Leaflet version I'm using: '0.7.7'
- Browser (with version) I'm using: Chrome 54.0.2840.99 m
- OS/Platform (with version) I'm using: Windows 10

**Comment by stmparker** [comment]
Actually, it looks like a missing var on string

	_getPathPartStr: function (points) {
		var round = L.Path.VML;

		for (var j = 0, len2 = points.length, str = '', p; j < len2; j++) {
			p = points[j];
			if (round) {
				p._round();
			}
			str += (j ? 'L' : 'M') + p.x + ' ' + p.y;
		}
		return str;
	},

**Comment by IvanSanchez** [comment]
You're using Leaflet 0.7.7 inside Angular... Can you reproduce this with vanilla leaflet, without angular? 
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

Considering that we're on 1.0.1, we don't really work on the 0.7.x series unless a bug affects a lot of people/browsers. This seems like an edge case.

**Comment by stmparker** [comment]
ah. thanks. I'm gonna try updating before I do anything else, If I can't
fix it with updates, I'll try repro-ing the problem inside a pen.

There was a reason I was using that version... I believe it was because of
the compatibility with leaflet draw. I haven't looked into that in a while
though.

 FWIW I'm not using any of the "angular-ness" with this part of the code
that's breaking.  I've extended polygon with some custom functionality for
saving them and some additional app specific project data and tried adding
it to a vanilla feature group and ran into this issue.


Thanks for getting back to me.

**Comment by stmparker** [comment]
I updated to all the recent versions of leaflet and leaflet draw. In trying to reproduce my issue outside of angular & ui-leaflet discovered that my problem is not in either Leaflet or Leaflet draw.  This issue can be closed, it's not relevant to Leaflet.

thanks again
