### ISSUE TITLE
Prefetch Offmap Tiles

### ISSUE THREAD

**Issue by Miserlou** [Leaflet/Leaflet#512]
I suggest that the map should prefetch the tiles off the sides of the current location.

Once a user beings moving the map in a certain direction, tiles should continue to be prefectched off the edge of the map in that same direction (up to n+1, where n is the amount to prefetch.)

This would vastly improve experience of the map, as there would be far, far less moments of waiting for data to load.

**Comment by hy9be** [comment]
I feel this will be very beneficial when we use leaflet in hybrid mobile app. Users usually pan the map much faster on touch screen device than in a desktop browser. In this case, prefetching will significantly improve the perceived performance of the map. Can we re-evaluate this suggestion? @mourner

**Comment by mourner** [comment]
I think prefetch can be implemented as a drop-in plugin for Leaflet, it's not necessary to add this in the core.

**Comment by IvanSanchez** [comment]
@hy9be, it is possible to work around your issue right now, with some of the [plugins for tile loading](http://leafletjs.com/plugins.html#tile-load) - if you use my PouchDB-cached tilelayers, you can (re)seed the cache on every moveend to pre-load stuff around the screen and in ±1 zoom level.

**Comment by hy9be** [comment]
@IvanSanchez Thanks a lot! I will give it a try.
