### ISSUE TITLE
Disable keyboard navgiation by default on mobile devices

### ISSUE THREAD

**Issue by pke** [Leaflet/Leaflet#5122]
I recently run into a bug in my app, when the `.remove()` of a leaflet map was not called. Then the keyboard listeners where still capturing chars like "6" and "-" even when on the new screen an input field had the focus. Since those keydown events are prevented by leaflet to bubble up, the keys never reached the focused input field and users where unable to type in "6" and "-".

This bug only manifested itself on iOS 10. It did not happen on iOS 9 and Android. I guess they changed something in the may removed DOM nodes and events are handled.

I then wondered why the `keyboard` option defaults to `true` regardless of the device. How much sense does it make have keyboard handling enabled on mobile devices in the first place? Can this even be used without the softkeyboard being visible?

Since leaflet has mobile device checks for some rendering options would you accept a PR to default `keyboard=false` on mobile devices?

**Comment by IvanSanchez** [comment]
@pke I guess this is a simple matter of editing `src/map/handler/Map.Keyboard.js` and replacing

```
keyboard: true
```

with

```
keyboard: !L.Browser.mobile
```

Could you make a PR for that, and see if it solves your use case? I don't think we've got an iOS 10 device laying around to test this :-(

**Comment by pke** [comment]
Sure, I can provide such PR.

**Comment by perliedman** [comment]
Wouldn't it be better to properly fix so that the handlers are removed properly?

I'm not sure how exact the test for `mobile` actually is, but given the array of weird units out there, I'd be surprised if there isn't one with a hardware keyboard _and_ the ability rotate the screen (which is a criteria for setting `L.Browser.mobile`).

**Comment by pke** [comment]
@perliedman yes the source of the bug described was fixed by properly removing the map as a whole (which removes the listeners). But in favour of not wasting resources the keyboard listeners should not even be enabled on mobile devices.
`L.Browser.mobile` is sufficient for so many other places in leaflet, why not use it here also (as the default). If you experience issues with that on particular devices, one could always enable keyboard handling on this device. But the default is to disable it for all mobile devices.

**Comment by IvanSanchez** [comment]
@perliedman `L.Browser.mobile` relies on user-agent sniffing. And, at least in mobile chrome and mobile FFX, the end-user can hit an option called "request desktop site" which will just change the UA temporarily.

Also, when a map is `remove()`d:
* `L.Map._clearHandlers()` is called
* That calls `this._handlers[i].disable()`
* That calls `L.Map.KeyboardHandler.removeHooks()`
* That calls `L.Map.KeyboardHandler._removeHooks()`
* That calls `L.DomEvent.off(document, 'keydown', this._onKeyDown, this);`

So I fail to see why the event handler for the `document` is not removed.

@pke I don't think that a keyboard event handler will be much overhead for a mobile browser, anyway. Are there any benchmarks about that?

**Comment by pke** [comment]
@IvanSanchez I have no numbers to support my claim. Although I think less pollution with useless even listeners is not a bad thing.

**Comment by danzel** [comment]
Mobile devices can have keyboards. You can connect a bluetooth keyboard to an ipad as an example.
Not sure this would be a common use case however.

**Comment by perliedman** [comment]
@IvanSanchez mobile mode will also always be enabled if `window.orientation` is defined: https://github.com/Leaflet/Leaflet/blob/master/src/core/Browser.js#L31, but also via user agent sniffing.

I think this is really an edge case and it probably doesn't matter what we do. My thinking is that if we change to disable keyboard on mobile, we will instead end up with another issue like "Keyboard doesn't work in browser X och platform Y".

**Comment by pke** [comment]
@perliedman Maybe you are right. If its that difficult to detect a keyboard. Could I instead decide not even compile/include the keyboard plugin for my particular app where I don't want to have *any* keyboard support in leaflet. Just to reduce the apps deploy/runtime size

**Comment by perliedman** [comment]
@pke not sure about keyboard support in particular, but things like that might be possible when we switch to ES6 modules and rollup, that could at least in theory remove code you don't use.
