### ISSUE TITLE
L.control.layers collapses after first mouse hover

### ISSUE THREAD

**Issue by falqn** [Leaflet/Leaflet#5126]
- Leaflet version I'm using: 1.0.2
- Browser (with version) I'm using: Chrome
- OS/Platform (with version) I'm using: Win7

I'm initializing the map with 'collapse:false' option. After first mouse hover, the control collapses, but it should stay expanded at all times.

https://playground-leaflet.rhcloud.com/bipo/edit?html,output

**Comment by perliedman** [comment]
The problem lies in that this line is executed even when `collapsed: true` is set.
