### ISSUE TITLE
Null Reference passing object to LatLngBounds.contains

### ISSUE THREAD

**Issue by PlaidPhantom** [Leaflet/Leaflet#5132]
## How to reproduce

- Leaflet version I'm using: 1.0.1 & 1.0.2
- Browser (with version) I'm using: Firefox 49.02 and Edge 25
- OS/Platform (with version) I'm using: MacOS 10.11.6 for Firefox/Windows 10 for Edge
- call LatLngBounds.contains with an object-style LatLng, e.g. `{lat:0,lon:0}`

## What behaviour I'm expecting and which behaviour I'm seeing

expecting: the function to return true or false
seeing: a null reference exception

## Minimal example reproducing the issue

http://codepen.io/plaidphantom/pen/YpVZap

I noticed this issue originally while using 1.0.1, but putting together the CodePen I tested it with 1.0.2 and get identical behavior.

According to the [LatLng](http://leafletjs.com/reference-1.0.0.html#latlng) documentation i think this should work, as there's nothing "noted otherwise" on [.contains](http://leafletjs.com/reference-1.0.0.html#latlngbounds-contains)

**Comment by IvanSanchez** [comment]
#5135 should do the trick.
