### ISSUE TITLE
getBoundsZoom with option "inside?" does not always set zoom to inside the bounds

### ISSUE THREAD

**Issue by tonny747** [Leaflet/Leaflet#5136]
## How to reproduce

- Leaflet version I'm using: 1.0.2 (issue occurs from rc.1)
- Browser (with version) I'm using: Chrome 55
- Set zoom level using getBoundsZoom(bounds, true) where bounds is a different aspect ratio to the map.
   - For example bounds of (-85,-180), (85,180) with a map of 600x400 px

## What behaviour I'm expecting and which behaviour I'm seeing

When using getBoundsZoom with the option "inside" set to true I expect the zoom level to be set such that the map view is entirely inside the bounds set as per the [documentation](http://leafletjs.com/reference-1.0.0.html#map-getboundszoom).
When using version of leaflet >= 1.0.0-rc1 this is not always the case.

## Minimal example reproducing the issue

Note I added a polygon to the map to showing the bounds.

Using Leaflet version 1.0.2 the view is outside bounds: https://playground-leaflet.rhcloud.com/yaca/edit?html,output

Same for Leaflet Version 1.0.0-rc.1: https://playground-leaflet.rhcloud.com/juc/edit?html,output

However in version 1.0.0-beta.2 it works as expected with the view completely contained within the bounds: https://playground-leaflet.rhcloud.com/tom/1/edit?html,output

**Comment by IvanSanchez** [comment]
A `git bisect` points to https://github.com/Leaflet/Leaflet/commit/3fde3c0390e03c6d0187ede1c9418c3c57fd1765

**Comment by IvanSanchez** [comment]
Should be fixed by #5137. That PR could use a unit test or two, though.

**Comment by tonny747** [comment]
Sweet, that PR fixes this problem for me.
