### ISSUE TITLE
Map tile not loading in ios webview

### ISSUE THREAD

**Issue by arminghm** [Leaflet/Leaflet#5141]
Hi,

Im using react native.
This is my map.html file :

```javascript
<html>
  <head>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.2/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.0.2/dist/leaflet.js"></script>
  </head>
  <body>
    <div id="map" style="height: 100%;">
    </div>
    <script>
        var osmUrl = 'https://{s}.tile.osm.org/{z}/{x}/{y}.png',
        osmAttrib = '&copy; <a href="http://openstreetmap.org/copyright">OpenStreetMap</a> contributors',
        osm = L.tileLayer(osmUrl, {
              maxZoom: 18,
              attribution: osmAttrib
            });
        var map = L.map('map').setView([19.04469, 72.9258], 12);
        map.addLayer(osm);
    </script>
  </body>
</html>

```

and Im loading map.html into webview : 

```javascript
import React, { Component } from 'react';
import {
  WebView
} from 'react-native';

export default class MapScreen extends Component {
  render() {
    return (
      <WebView style={{flex:1}} javaScriptEnabled={true} source={require('./map.html')}/>
    );
  }
}
```

But the tile not loading in ios simulator, but its fine in android emulator.
This is what I see in ios simulator : 
![simulator screen shot nov 23 2016 11 31 41 pm](https://cloud.githubusercontent.com/assets/11267514/20576891/0d41d760-b1d5-11e6-8d0e-be1f26be20c2.png)

**Comment by perliedman** [comment]
Hi, this issue involves React, WebView and the iOS simulator. The Leaflet team does not work with, or support these tools, so I'm afraid we can't help you with this one.

Given the very simple example, it's pretty apparent that the problem does not lie in Leaflet itself, but rather how it interacts with one of the other components.

We are open to making changes to Leaflet the make it work better with other tools, but unfortunately do not have the resources to work out issues in other frameworks or tools.

If you can provide a failing example using just Leaflet, JavaScript and HTML/CSS, we're of course very open to working with this.

**Comment by arminghm** [comment]
Thank you for reply.

I was because of http requests, and when I disabled the ATS ( App Transport Security ) it works fine and the tiles are loaded. But as you know disabling the ATS is not the solution.

According to the @F1LT3R answer in the issue [Streaming Leaflet Tiles over HTTPS / SSL #3186](url) we can use https for loading tiles and changing the osm to openstreetmap in the tile url ( ```http://{s}.tile.osm.org/{z}/{x}/{y}.png``` -> ```https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png ```).

**Comment by Sergo7** [comment]
@arminghm, thanks a lot, it works for me :)

**Comment by GninninwokyOuattara** [comment]
Thanks @arminghm, it worked for me too !
