### ISSUE TITLE
Broken Leaflet 1.0.2 map for basic ionic2 app

### ISSUE THREAD

**Issue by thomashrabe** [Leaflet/Leaflet#5146]
LeafletJS - 1.0.2 
Chrome  54.0.2840.98 / Safari 10.0.1 (12602.2.14.0.7)
Mac Sierra 10.12.1

Expecting to see a good map, getting weird tile assembly , incoherent, with gaps between tiles and and shuffled around tiles. I observed it with all map sources I tried.

<img width="961" alt="map" src="https://cloud.githubusercontent.com/assets/3632672/20690201/0f58b8b4-b57e-11e6-8d5a-5edcf72607fe.png">

I added a new page to my ionic2 blank page project

```
ionic start myBlank blank --v2 
cd myBlank

npm install leaflet --save
npm install @types/leaflet --save

ionic g page custom-view
```

Code in two new files
`custom-view.ts`
```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import * as Leaflet from 'leaflet';

/*
  Generated class for the CustomView page.

  See http://ionicframework.com/docs/v2/components/#navigation for more info on
  Ionic pages and navigation.
*/
@Component({
  selector: 'custom-view',
  templateUrl: 'custom-view.html'
})
export class CustomViewPage {

  private map: any;

  constructor(public navCtrl: NavController) {}

  ionViewDidLoad() {
    this.loadMap();
  }

  loadMap(){
    this.map = Leaflet.map('map').setView([32, -120], 14);
    Leaflet.tileLayer("http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}", {attribution:""}).addTo(this.map);
  }

}
```

```
custom-view.html
```
```
<ion-header>

  <ion-navbar>
    <ion-title>custom-view</ion-title>
  </ion-navbar>

</ion-header>


<ion-content padding>
   <div id="map" style="width: 100%; height: 100%"></div>
</ion-content>
```

**Comment by auronsan** [comment]
I try it at ionic blank with import java script and the maps work normally 
![test212](https://cloud.githubusercontent.com/assets/5324340/20693534/f0c6b184-b619-11e6-85ff-d8f18c7a6ac1.jpg)

**Comment by thomashrabe** [comment]
Hi, 

what’s the command and required module to import java-script?
Can you please send the code excerpt?

Sorry for the noob question, transitioning to Typescript here.

Thanks,
Thomas

> Am 28.11.2016 um 17:55 schrieb Ahsanul <notifications@github.com>:
> 
> import java script

**Comment by auronsan** [comment]
Include Leaflet CSS file in the head section of your document:

 <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.2/dist/leaflet.css" />
Include Leaflet JavaScript file:

 <script src="https://unpkg.com/leaflet@1.0.2/dist/leaflet.js"></script>


just include the css and java script on src/index.html

**Comment by kaynz** [comment]
Try this out:

```
  ionViewDidLoad() {
    setTimeout(this.loadMap.bind(this), 100);
  }
```

Check your package version if you have following versions installed (minimum):
`
"rxjs": "5.0.0-beta.12".
"ionic-angular": "2.0.0-rc.3",
"zone.js": "0.6.26"
`

**Comment by auronsan** [comment]
Oh I got the problem just need import css on your src/index.html

**Comment by perliedman** [comment]
This doesn't look related to Leaflet itself, but rather how you work with Ionic. Closing for now, please add more info if you believe this is a Leaflet issue.

**Comment by AIRUNGU** [comment]
<ion-app></ion-app>
  
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.2/dist/leaflet.css" />
  <script src="https://unpkg.com/leaflet@1.0.2/dist/leaflet.js"></script>


The above code actually works, just make sure they are below the <ion-app></ion-app>  tags
