### ISSUE TITLE
TileLayer/GridLayer requesting tiles outside of specified bounds

### ISSUE THREAD

**Issue by mrMetalWood** [Leaflet/Leaflet#5149]
## How to reproduce

- Leaflet version I'm using: 1.0.2
- Browser (with version) I'm using: Chrome 54.0.2840.98
- OS/Platform (with version) I'm using: macOS Sierra 10.12

- Add a tile layer with bounds to the map.

## What behaviour I'm expecting and which behaviour I'm seeing

I would expect that only tiles inside the bounding box are requested and displayed.
Instead there are tiles requested and displayed that are outside the boundingbox. More specific tiles that are located near "The International Date Line".

![bildschirmfoto 2016-11-29 um 14 53 25](https://cloud.githubusercontent.com/assets/2902795/20712316/c9d73178-b643-11e6-8c94-a874cb7f67cd.png)

## Minimal example reproducing the issue

In the example there are tiles requested and displayed that are located inside the red box and are not part of the bounds.
There has already been some conversation with @IvanSanchez in the leaflet Gitter channel about this topic on November 24, 14:05.
Most likely its some kind of issue that has to do with coordinates being wrapped around the date line and not correct boundingboxes being returned from a private GridLayer function. Here the concluding quote from Ivan:

> The L.GridLayer._tileCoordsToBounds private method is not returning good bboxes for tiles with a x-coordinate of -1

https://playground-leaflet.rhcloud.com/lulic/1/edit?html,output

**Comment by IvanSanchez** [comment]
Note: That playground shows the expected bounds of the `{x: -1, y: 1, z: 2}` tile in red, and the actual in blue.

**Comment by mrMetalWood** [comment]
I think the other way around. Actual bounds in red, expected in blue.

**Comment by IvanSanchez** [comment]
@mrMetalWood Ahem.

```js
    // Actual tile bounds of a tile with a x-coordinate of -1 (red)
    // i.e. {x: -1, y: 1, z: 2}
    var tileRect = L.rectangle(
      position._tileCoordsToBounds(L.point({x: -1, y: 1, z: 2})),
      {color: 'blue', weight: 5}
    ).addTo(map);
    

    // Expected tile bounds of a tile with a x-coordinate of -1 (blue)
    // i.e. {x: -1, y: 1, z: 2}
    var tileRect = L.rectangle(
      [[0,-180],[66.51326044311188,-270]],
      {color: 'red', weight: 1}
    ).addTo(map);
```

I made a mistake in the comments, so actual = blue, expected = red.

**Comment by DiogoMCampos** [comment]
I have been looking into this and, as @mrMetalWood said, there is a wrapper that converts the coordinates to fit a specific range  (file /core/Util.js, line 102):

```javascript
wrapNum: function (x, range, includeMax) {
	var max = range[1],
	    min = range[0],
	    d = max - min;
	return x === max && includeMax ? x : ((x - min) % d + d) % d + min;
}
```
This function is called here with the default range [-180, 180] (file /geo/crs/CRS.js, line 100):

```javascript
wrapLatLng: function (latlng) {
	var lng = this.wrapLng ? L.Util.wrapNum(latlng.lng, this.wrapLng, true) : latlng.lng,
	    lat = this.wrapLat ? L.Util.wrapNum(latlng.lat, this.wrapLat, true) : latlng.lat,
	    alt = latlng.alt;

	return L.latLng(lat, lng, alt);
}
```
@IvanSanchez Correct me if I'm wrong, but I think this would force the GridLayer to be within the International Date Line range.

A possible, albeit probably undesired, solution would be to stop enforcing this wrapper for this particular scenario. I'm going to experiment with it tomorrow and will follow up if I get any interesting results.
