### ISSUE TITLE
Crash when fitBounds() to a zero-area bounds on uninitialized map

### ISSUE THREAD

**Issue by emirdeliz** [Leaflet/Leaflet#5153]
## How to reproduce

- Leaflet version I'm using: 1.0.2
- Browser (with version) I'm using: Chrome
- OS/Platform (with version) I'm using: OS

## What behaviour I'm expecting and which behaviour I'm seeing

I discovered a bug when running the method fitBounds and use same bounds. After running i get the message: **Uncaught Error: Invalid LatLng object: (NaN, NaN).**

The problem occur in method getBoundsZoom in `var scale = Math.min(size.x / boundsSize.x, size.y / boundsSize.y);`. This return Infinity and cause the error

## Minimal example reproducing the issue

```js
    var map = L.map('map', {zoom: 15});
    map.fitBounds([[42.897968, -83.25632], [42.897968, -83.25632]]);
```

Stack trace looks like:

```
Error: Invalid LatLng object: (NaN, NaN)  leaflet-src.js:1609:9
	L.LatLng https://unpkg.com/leaflet@1.0.0/dist/leaflet-src.js:1609:9
	L.Projection.SphericalMercator.unproject https://unpkg.com/leaflet@1.0.0/dist/leaflet-src.js:2019:10
	L.CRS.pointToLatLng https://unpkg.com/leaflet@1.0.0/dist/leaflet-src.js:2062:10
	L.Map<.unproject https://unpkg.com/leaflet@1.0.0/dist/leaflet-src.js:2877:10
	L.Map<._getBoundsCenterZoom https://unpkg.com/leaflet@1.0.0/dist/leaflet-src.js:2451:16
	L.Map<.fitBounds https://unpkg.com/leaflet@1.0.0/dist/leaflet-src.js:2470:16
```

[https://jsfiddle.net/emirdeliz/27a1hrvy/](https://jsfiddle.net/emirdeliz/27a1hrvy/
)

**Comment by jbccollins** [comment]
Question: What use case exists for wanting to fit the map bounds to a point when setView exists?

**Comment by emirdeliz** [comment]
Yes, same error

**Comment by emirdeliz** [comment]
This is my workaround before set bounds in map

bounds._northEast.lat += 0.000000000001;
bounds._northEast.lng += 0.000000000001;

**Comment by IvanSanchez** [comment]
Heh.

This happens because @emirdeliz is calling `fitBounds()` passing a **zero**-area bbox, **before** the map has a value for its `maxZoom` option.

I bet that if the tilelayer is added to the map before the call to `fitBounds()`, the problem will magically disappear.

**Comment by emirdeliz** [comment]
Really, this fixed the problem after set maxZoom=15. Thanks

**Comment by IvanSanchez** [comment]
So https://github.com/Leaflet/Leaflet/pull/4916 (introduced in 1.0.2) makes it possible to set the initial map's zoom to `Infinity`, and that it will get clamped when adding a layer with a `maxZoom` option (such as the default `L.TileLayer`.

**Comment by IvanSanchez** [comment]
So with #5157, the call to `_getBoundsCenterZoom` will return the proper center and a zoom of `Infinity`, and together with #4916 everything works for this edge case.
