### ISSUE TITLE
Leaflet + noWrap option not working in above 1.x version

### ISSUE THREAD

**Issue by rajinikumar** [Leaflet/Leaflet#5154]
- I am working in leaflet map chart. I tried to implement the nowrap option but its not working.
-When i am using this theme "http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" its working but when i tried to use dark theme not working. same code working in 0.x version.

```js
var map = L.map('map', {
    worldCopyJump: true,
    inertia: false
}).fitWorld();

//  OSM tiles
//http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png
// L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
L.tileLayer('http://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png',
{
     maxZoom: 18,
   //  continuousWorld: false,
     noWrap: true
}).addTo(map);
```

Using http://jsfiddle.net/rajinikumarr/JKFgD/46/.

**Comment by IvanSanchez** [comment]
So with those options, Leaflet is asking the following tiles:

```
http://a.basemaps.cartocdn.com/dark_all/0/-2/0.png (404)
http://a.basemaps.cartocdn.com/dark_all/0/-1/0.png (404)
http://a.basemaps.cartocdn.com/dark_all/0/0/0.png (OK)
http://a.basemaps.cartocdn.com/dark_all/0/1/0.png (OK)
http://a.basemaps.cartocdn.com/dark_all/0/2/0.png (OK)
```

So the `noWrap` behaviour is working as expected: the X tile coordinate does not wrap around the earth. The fact that the CartoDB tiles work for positive Xs and return 404s for negative Xs is a particular of that tileserver, and not a Leaflet bug.

I'd rather go using the `maxBounds` option for this.

Leaflet code working as expected → closing.

**Comment by IvanSanchez** [comment]
Also note that `continuousWorld` is not a valid option in Leaflet >= 1.0.0.

**Comment by Kostanos** [comment]
Why this issue is closed? I still have it too:

```
    var map = L.map('map').setView([0, 0], 3);

    L.tileLayer('http://localhost:9103/{z}/{x}/{y}.png', {
      minZoom: 1,
      maxZoom: 6,
      tms: true,
      noWrap: true,
    }).addTo(map);
```

some time asking, while scrolling and zooming: 
```
http://localhost:9103/1/-1/1.png
http://localhost:9103/1/-1/0.png
...
```

**version: 1.1.0**

**Comment by perliedman** [comment]
@Kostanos read [@IvanSanchez reply](#issuecomment-264126408) carefully, it explains why this issue is closed. If you set `noWrap` to `true`, coordinates will not wrap, and you will get requests like the one you described.

**Comment by Kostanos** [comment]
I think independently if noWrap is on or off, Leaflet should not ask tiles out of boundary.

If map expected to be size: 64x64, it doesn't make any sense Leaflet asking for *-1 tile*

**Comment by perliedman** [comment]
@Kostanos but from the code example you posted above, you haven't told Leaflet about the bounds. How should it know that -1 is outside your bounds?
