### ISSUE TITLE
typeListeners.count never initialized

### ISSUE THREAD

**Issue by pke** [Leaflet/Leaflet#5159]
This line initializes all type listeners:
https://github.com/Leaflet/Leaflet/blob/a97b87d0333fdc4b0c18d7b2ee9c15b393ae76ff/src/core/Events.js#L98

However this line will always try to increment `NaN` because `count` is never initialised. 
https://github.com/Leaflet/Leaflet/blob/a97b87d0333fdc4b0c18d7b2ee9c15b393ae76ff/src/core/Events.js#L117

I can only assume this is a leftover, because the `count` is never referenced again somewhere, is it?

**Comment by perliedman** [comment]
You are right, this is a leftover from some older version of event handling, and it should be removed.
