### ISSUE TITLE
How can I do panch-/stretch-zoom to current map center

### ISSUE THREAD

**Issue by Daniil-Pabolkov** [Leaflet/Leaflet#5163]
I need zoom map to current center. On desktop screen I set scrollWheelZoom to 'center', but touchZoom property maybe true or false only, and zooming on touch screens via stretch change map center.
How can I zoom to center on mobile devices and other touch screens?

**Comment by IvanSanchez** [comment]
Please read http://leafletjs.com/reference-1.0.2.html#map-touchzoom

Also, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

**Comment by Daniil-Pabolkov** [comment]
Thanks for help. 
And sorry, that I send question here.
