### ISSUE TITLE
Feature request: additional @4x ratio for retina

### ISSUE THREAD

**Issue by PascalReintjens** [Leaflet/Leaflet#5169]
Hello,

This is a feature request for an additional @4x retina ratio. 

Leaflet already is able to deliver tiles in @2x, but since some of the high end smartphones now already have WQHD displays and UHD displays should be coming soon, @2x doesn't seem to be enough anymore.

If you look at http://mydevice.io/devices/ you can see that there are already devices out there with a pixel ratio of 4 (for example Galaxy S6 and LG G5).

So I think there should be at least an option to expand retina by delivering @4x tiles additionally to the @2x tiles. Even better / future proof would be an option to define custom retina levels at choice, but I don't know if that is doable.

Thanks for your work

**Comment by IvanSanchez** [comment]
Are there any tileservers with `@4x` tiles right now?

**Comment by PascalReintjens** [comment]
> Are there any tileservers with @4x tiles right now?

That is a good question, spontaneously I found https://maps.wikimedia.org which delivers 1.0, 1.3, 1.5, 2, 2.6, 3 at least - for example: https://maps.wikimedia.org/osm-intl/16/10436/23444@3x.png (they use Leaflet too)

I am using MapTiler (http://www.maptiler.com/ - and host the tiles for myself), and since you can define different retina sizes with it as you like, you can already generate and use @4x easily.

So I believe there are use cases, although they may still be few. And I'm positive that this will gain more support soon, as I said UHD smartphones are on their way

**Comment by cherniavskii** [comment]
You can use tiles with different ratio - see working example for `@3x` tiles https://next.plnkr.co/edit/Hs4wThtMWzJWVkOS
