### ISSUE TITLE
L.Canvas not redrawing properly on non-animated map pan

### ISSUE THREAD

**Issue by manubb** [Leaflet/Leaflet#5170]
I report several problems in L.Canvas implementation: using map.setView without animation causes geometries to be drawn twice even when they should not be displayed at all.
This is shown in http://playground-leaflet.rhcloud.com/yuxo/2/edit?html,console,output

**Comment by IvanSanchez** [comment]
Example given is not minimal, the bug can be reproduced with just 

```
    var map = L.map('map', {preferCanvas: true}).setView([51.505, -0.09], 13);
       
    var polygon = L.polygon([
	    [51.509, -0.08],
	    [51.503, -0.06],
	    [51.51, -0.047]
		]).addTo(map);
    
    setTimeout(function() {
      map.setView([0, 0], 13);
    }, 5000);
```

https://playground-leaflet.rhcloud.com/zigu/1/edit?html,output

Also with something like

```
      map.panBy([-601, 0], {animate: false});
```
As long as the distance panned is *greater* than the map size

This is Leaflet 1.0.2 and current `master`.

cc @perliedman Something to do with the new way of clearing the canvas redraw bboxes?

**Comment by IvanSanchez** [comment]
@manubb This is a good catch on a bug, but next time please try to [be more specific](http://www.catb.org/~esr/faqs/smart-questions.html#bespecific) when writing the title. If I read "L.Canvas bugs" I have to assume that the bug report is incomplete or missing enough detail.

**Comment by manubb** [comment]
@IvanSanchez Sorry for the unspecific title

Note that my example shows two distinct problems: 
-geometries can be displayed in cases where it should not
-geometries are drawn twice (watch "drawing poly" in the console)

The first problem does not occur when changing zoom in setView.

**Comment by IvanSanchez** [comment]
I think you're reading a bit too far in the analysis. I'll let @perliedman have a look, as he changed some canvas stuff related to canvas redraws, and I don't know which sequence of map `resetview` or `moveend` events trigger a canvas refresh. With a bit of luck all the related problems will go away at the same time.

**Comment by perliedman** [comment]
This bug is present in 1.0.0 as well, so it's not related to the recent changes. It's not reproducible in 0.7.7, however.

I'll try to have a look, but can't promise anything short term, since I will be travelling the next couple of days.

**Comment by IvanSanchez** [comment]
I've had a look at this. It seems that the problem relies on the calculation on the projected pixel coordinates of the canvas path - they are only updated when the `L.Renderer` calls `layer._reset()`. This only happens at the *end* of the `viewreset` event.

Meanwhile, the `moveend` event and the *start* of the `viewreset` event trigger the canvas' `_update` which triggers a redraw **with the stale pixel coordinates of the paths**.

**Comment by IvanSanchez** [comment]
OK, I've made #5171 and #5172 as possible solutions for this.

I have **not** tested them throughoutly. There might be some other edge case (vector animations, etc) that might glitch.

@perliedman @manubb I'll appreciate a review. In my head, the order of the `L.Renderer` update logic is a scary piece of code, and I'm afraid of introducing some regression somewhere.

**Comment by perliedman** [comment]
Agree a lot of the update logic for canvas is scary, especially since we have no tests that cover this, and it would be a pretty large effort to get started on testing it.
