### ISSUE TITLE
SVG is over-layered by the map today.

### ISSUE THREAD

**Issue by HyemiSong** [Leaflet/Leaflet#5174]
SVGs are over-layered by part of tiles from leaflet map today. 

Location: Boston/Cambridge area.

Yesterday, I did not find this error.

![screen shot 2016-12-07 at 1 16 52 pm](https://cloud.githubusercontent.com/assets/1608824/20983200/93fe4e6e-bc89-11e6-8e25-ca28145a219c.png)
@michael @kshepard @palewire @naehrstoff @klaftertief

**Comment by IvanSanchez** [comment]
@HyemiSong You have to be more specific. In which page is this error happening? How can it be reproduced? Are you sure it's a problem in core Leaflet?

**Comment by perliedman** [comment]
Closing this for now, feel free to add more information if you still believe this is an issue.
