### ISSUE TITLE
Map Renderer breaks L.Circle

### ISSUE THREAD

**Issue by kaynz** [Leaflet/Leaflet#5175]
Hey,

here's the fiddle: https://playground-leaflet.rhcloud.com/fuy/1/edit?html,output

As soon as you provide renderer: L.Canvas in MapOptions, you'll get errors while adding L.Circle to the map.

**Comment by IvanSanchez** [comment]
The `renderer` option of `L.Map` must be an **instance** of `L.Canvas` or `L.SVG`, and **not** a reference to a class constructor.

e.g.:
```
    var map = new L.Map('map', {renderer: L.canvas() });
```

or even
```
    var map = new L.Map('map', {renderer: new L.Canvas() });
```

and **not**:
```
    var map = new L.Map('map', {renderer: L.Canvas });
```

If this is unclear, please consider sending a pull request to amend the documentation (read the contributing guide first, as it has important info about how to make changes in the docstrings)
