### ISSUE TITLE
Prevent panning out of the picture

### ISSUE THREAD

**Issue by yuanting0505** [Leaflet/Leaflet#5183]
![image](https://cloud.githubusercontent.com/assets/2976630/21091646/a7151404-c082-11e6-87f5-5f22cd534aee.png)

Is there any way to prevent panning the map out of the edge? I understand the option of `maxBounds`. But instead of bouncing back to the centre, I hope leaflet just blocks the panning when it reaches the limit.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by asleepwalker** [comment]
Leaflet's bouncing back was made for velocity. However, if you wanna change this behavior and add fixed bounds, you can use my tiny plugin: https://github.com/asleepwalker/leaflet.hardbounds
