### ISSUE TITLE
Alternative to SpliceLatLngs

### ISSUE THREAD

**Issue by JoeMatulka** [Leaflet/Leaflet#5196]
This might not be an issue but I can't seem to find it in the documentation anywhere...

I posted this question on stackoverflow: http://stackoverflow.com/questions/40595393/leaflet-1-0-upgrade-splicelatlngs-alternative

My issue is that I can't find a proper way to splice a latLng into a polyline at a certain index in the object.

I used spliceLatLng before and tried writing my own. I've read through a lot of the documentation and through the code and can't find a probable alternative. :frowning_face: 

Thank you in advance

**Comment by perliedman** [comment]
Hi, while this is not a good place for questions, preferably use Stackoverflow like you already did, you can just use [`Array.splice`] to accomplish the same thing. See the example: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/splice
