### ISSUE TITLE
panTo() fails when _mapPane position set to non 0

### ISSUE THREAD

**Issue by ptasior** [Leaflet/Leaflet#5198]
Hi all,

I'm still on leaflet 0.7 but the code seems to be unchanged in 1.*
Browser: QWebkitWidget (Qt 5.3)
Other plugins: Leaflet.D3SvgOverlay (which I guess changes the position of _mapPane)

Issue:
When calling `panTo(position)` periodically with small distance changes the center of a map drifts from given coordinates.

Analysis:
In function `_getCenterLayerPoint` a call to `this.containerPointToLayerPoint()` substracts `_getMapPanePos()` from `getSize()/2` while `_getMapPanePos()` apparently should be divided by 2 as well.

My solution:
In
`_getCenterLayerPoint: function() {`
Change return value to:
`return L.point(this.getSize()._divideBy(2)).subtract(this._getMapPanePos()._divideBy(2));`
Simply moving `._divideBy(2)` outside `containerPointToLayerPoint()` reverts the direction of drift rather than fixing it...

Am I missing something or have I found a bug?

Thanks

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by ptasior** [comment]
I'll try to but Monday or Tuesday is the earlies possible time for me.

**Comment by perliedman** [comment]
Closing this since monday or tuesday is long gone :stuck_out_tongue_winking_eye: 

Please add some more info and preferably a live example if this is still an issue!
