### ISSUE TITLE
Pinch zoom problem

### ISSUE THREAD

**Issue by wotgl** [Leaflet/Leaflet#5205]
Hi!

## How to reproduce

- Leaflet version I'm using: 1.0.2
- Browser (with version) I'm using: Google Chrome 55.0.2883.79 / Safari on Ipod Touch 5 gen
- OS/Platform (with version) I'm using: iOS 9.3.4
- I use latest [tangram](https://github.com/tangrams/tangram) for WebGL map (vector tiles)
- I use latest leaflet-routing-machine: 3.2.4

## What behaviour I'm expecting and which behaviour I'm seeing

I'm using the latest version of the library, but faced with the problem like https://github.com/Leaflet/Leaflet/issues/3919 or https://github.com/Leaflet/Leaflet/issues/3798 

Everywhere it is written that the bug is closed, but I don't know what I'm doing wrong?)

Screenshots: http://imgur.com/a/n6EiW
The first picture is no zoom, in the second picture using pinch zoom. You should pay attention that the marker remains in the right place. But the line moves across the screen.

## Minimal example reproducing the issue

https://jsfiddle.net/a5007q4c/

P.S.
Asked friends to check remotely on Android Chrome - the same problem.

**Comment by perliedman** [comment]
This appears to be an issue with Tangram rather than Leaflet itself. The exact same code, but with the Tangram layer replaced with an normal OSM tile layer, works as expected: https://jsfiddle.net/a5007q4c/1/

Please file an issue with Tangram, or add more information if you still believe this is an issue with Leaflet itself.

**Comment by bcamper** [comment]
@perliedman I do believe there is a Tangram issue at play here, which I am planning to address.

However, I noticed that Leaflet itself exhibits the originally reported issue (overlay appears to pan/zoom at different rate than base map) with a plain raster layer when `zoomAnimation: false`: https://jsfiddle.net/a5007q4c/2/

Is this expected?

**Comment by wotgl** [comment]
I created the issue at Tangram repo https://github.com/tangrams/tangram/issues/476
`zoomAnimation: false` doesn`t solve the problem
