### ISSUE TITLE
map.getCenter() and map.getBounds().getCenter() differ

### ISSUE THREAD

**Issue by pke** [Leaflet/Leaflet#5211]
- Leaflet version I'm using:
1.0.2

- Browser (with version) I'm using:
Chrome 5.0.2883.87 m

- OS/Platform (with version) I'm using:
Windows 8.1

## What behaviour I'm expecting and which behaviour I'm seeing

I was expecting `map.getCenter()` returns the same as `map.getBounds().getCenter()` but it does not.

`center = L.LatLng {lat: 52.52084307601789, lng: 13.404779434204103}`
`bounds.getCenter()
L.LatLng {lat: 52.520842915091805, lng: 13.404779434204102}`

Is this a bug or expected behaviour?

**Comment by IvanSanchez** [comment]
This is expected with the current implementation.

Besides the sub-pixel errors, the code for `L.LatLngBounds.getCener()` does a very naïve calculation: it just returns the average of the latitudes of the bounds. What you expect is the average of the *projected* latitudes (then unprojected back into a `LatLng`).

Unless this is causing any problems, I don't think it'll be worth working on it.

**Comment by pke** [comment]
Not a problem, thanks for clarifying. I was just about to find out the best way to save a map view accross devices and screen resolutions. So that I can give a URL with coords/bounds/zoom to somebody else with a different screen/browser resolution and she would see the exact same part of the map as I did. At least when the orientation of the screen matches.
