### ISSUE TITLE
L.stopPropagation not working as expected in Leaflet 1.0.2

### ISSUE THREAD

**Issue by rgdonohue** [Leaflet/Leaflet#5217]
- [ ] I'm reporting a bug, not asking for help
- [ ] I've looked at the [documentation](http://leafletjs.com/reference-1.0.0.html) to make sure the behaviour is documented and expected
- [ ] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: Leaflet 1.0.2.
- Browser (with version) I'm using: Chrom
- OS/Platform (with version) I'm using: Mac Sierra

This solution appears not to work:

```js
  var control = L.control({position: 'topright'});

  control.onAdd = function (map) {

      return L.DomUtil.create('div', 'div-test');

      L.DomEvent.on('.div-test', 'mousedown', function (ev) {
        L.DomEvent.stopPropagation(ev);
      });

  };

  control.addTo(map);
```

## What behavior I'm expecting and which behavior I'm seeing

Basemap tiles should not move or respond to dragging on the div element placed with the L.Control.

## Minimal example reproducing the issue

Code example [here](http://playground-leaflet.rhcloud.com/bomi/edit?html,output)

![stopprop-fail](https://cloud.githubusercontent.com/assets/1952205/21471813/02815d48-ca8d-11e6-8223-3c6252959a10.gif)

**Comment by yohanboniface** [comment]
Sounds like you want to use [disableClickPropagation](http://leafletjs.com/reference-1.0.0.html#domevent-disableclickpropagation) and disableScrollPropagation instead.

**Comment by danierod** [comment]
Can someone confirm if with [disableClickPropagation](http://leafletjs.com/reference-1.0.0.html#domevent-disableclickpropagation) worked? I'm using this code:
`function _disableClickPropagation(element) {
        if (!L.Browser.touch || L.Browser.ie) {
            L.DomEvent.disableClickPropagation(element);
            L.DomEvent.on(element, 'mousewheel', L.DomEvent.stopPropagation);
        } else {
            L.DomEvent.on(element, 'click', L.DomEvent.stopPropagation);
        }
    }`

And I'm having the same issue.

**Comment by perliedman** [comment]
@danierod yes, it works. It's used internally in Leaflet in a lot if places: https://github.com/Leaflet/Leaflet/search?utf8=%E2%9C%93&q=disableClickPropagation&type=

Please open a new issue with a minimal test case reproducing the issue if you've found it doesn't work as expected under some condition.

**Comment by grid-100** [comment]
> Can someone confirm if with [disableClickPropagation](http://leafletjs.com/reference-1.0.0.html#domevent-disableclickpropagation) worked? I'm using this code:
> 
> ```
> function _disableClickPropagation(element) {
>         if (!L.Browser.touch || L.Browser.ie) {
>             L.DomEvent.disableClickPropagation(element);
>             L.DomEvent.on(element, 'mousewheel', L.DomEvent.stopPropagation);
>         } else {
>             L.DomEvent.on(element, 'click', L.DomEvent.stopPropagation);
>         }
> }
> ```
> 
> And I'm having the same issue.

When upgrading the code using the similar function as above ( Chrome Version 80.0.3987.163 (Official Build) (64-bit) ), just found out:
```
console.log(L.Browser.touch) //<-- return undefined in leaflet 0.7.7
console.log(L.Browser.touch) //<-- return true in leaflet 1.4.0
```
@danierod, try to swap/copy `L.DomEvent.on(element, 'mousewheel', L.DomEvent.stopPropagation);` after else statement. I'm adjusting my custom leaflet control to work with newer version of leaflet and it works
