### ISSUE TITLE
Missing documented feature: Polyline.spliceLatLngs

### ISSUE THREAD

**Issue by hanzo2001** [Leaflet/Leaflet#5218]
- [x] I'm reporting a bug, not asking for help
- [x] I've looked at the [documentation](http://leafletjs.com/reference-1.0.0.html) to make sure the behaviour is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: `1.0.2`
- Browser (with version) I'm using: `any`
- OS/Platform (with version) I'm using: `any`
- step 1: simply call `spliceLatLngs` on any `polyline` object throws an exception:

> EXCEPTION: (some_polyline_object).spliceLatLngs is not a function

## I'm expecting a method on Polyline that is not there
Polyline has a documented method `spliceLatLngs` that should work like `Array.spliceLatLngs`. It is documented as such but after debugging an object (Firefox `console`) and perusing the source code I noticed it is not implemented.

## Minimal example reproducing the issue

No example required... the method just isn't available

**Comment by perliedman** [comment]
I believe you're wrong here, but feel free to point to the docs for `spliceLatLngs` in the docs _for 1.0_.

`spliceLatLngs` exists in Leaflet 0.7, so it's also in the docs for 0.7 (http://leafletjs.com/reference.html#polyline-splicelatlngs) - I think you might just be reading the wrong docs.

**Comment by hanzo2001** [comment]
I don't understand. Are there two sets of docs?

The docs I'm reading describe the `spliceLatLngs` method under **Polyline**. The source code shows that no such method exists (version `1.0.2`). Debugging a created polyline in the console throws an error which also shows me that there is an inconsistency between the docs I'm reading and the source code.

Am I reporting this wrong? I am quite new to GitHub Issues
