### ISSUE TITLE
Bug - In _removeIcon if icon a "TypeError: Cannot read property 'parentNode' of null" occurs

### ISSUE THREAD

**Issue by htveranger** [Leaflet/Leaflet#5221]
P.t. The code is like this:

```js
                L.DomUtil.remove(this._icon);
                this.removeInteractiveTarget(this._icon);
```

Should be:

```js
            if (this._icon) {
                L.DomUtil.remove(this._icon);
                this.removeInteractiveTarget(this._icon);
                this._icon = null;
            }
```

**Comment by perliedman** [comment]
Hi there,

* can you provide an example when you see this problem?
* which Leaflet version is this referring to?

**Comment by perliedman** [comment]
Ok, I'm reluctant to add null checks without seeing why this problem happens. From looking at the code, the only place `_removeIcon` is called without a `null` check for `this._icon` is in [`onRemove`](https://github.com/Leaflet/Leaflet/blob/863cf744616cba2d3cf4e8b28c825bcea1edd2e4/src/layer/marker/Marker.js#L97). So the question is why `_icon` is not set when you're removing the marker?

I'm closing for now, but I'm happy to reopen if we can get more information to investigate this problem.

**Comment by apastuhov** [comment]
I got the same issue when I reinitialized `_leaflet_id`. As example:
```
group = new GeoJSON(undefined, { // <<<<< note that you need 2 such groups
    onEachFeature: (feature, layer) => {
      layer['_leaflet_id'] = feature.id;      // <<<<<<<<<<<<<<<<<<< here is a root cause of the issue.
    },
    pointToLayer: (feature, latlng) => {
      return new Marker(latlng, { icon: this.getIcon(feature) });
    },
  });
// And do not forget to add data to GeoJSON
```
So when I tried to remove the map data (navigation out of the page/clear data/etc) - I got same error. If ID is not unique (even between different layer-groups) - we get the error that Leaflet tries to remove object, which was already removed. I added unique prefix to the ID - and it worked

**Comment by perliedman** [comment]
You should never alter an object's `_leaflet_id`, it is used for internal tracking and Leaflet relies on it being unique and never changed after initialization.

If you need to track a feature id in the layer, you are free to do so, just set any property except `_leaflet_id`. Having said that, you know that `layer.feature` is already initialized with the feature, so you can use `layer.feature.id` to to get the id.

**Comment by apastuhov** [comment]
I totally understand, but:
1 - It is a use case how to get such crash :)
2 - This is the only way to find a layer/feature for specific entity by `layerGroup.getLayer(entity.id)` in approximately O(1). Getting all layers and looking for a feature-property, or keeping a Map is overhead, because we already have such "map" inside of Leaflet.
