### ISSUE TITLE
Does someone know how  layer._radius works?

### ISSUE THREAD

**Issue by mopetite** [Leaflet/Leaflet#5222]
I want to drow circle in my own way.But it can't change its size automatically when map zooms.I found that the layer._radius can change itself when map zooming.Does someone know how it works?Teach me please.

**Comment by perliedman** [comment]
Hi and thanks for using Leaflet!

Please note that this is our issue tracker, where bugs and feature requests and posted and discussed. For questions on how to use Leaflet and other support, you're better off using [stackoverflow](https://stackoverflow.com/) or [gis.stackexchange.com](https://gis.stackexchange.com/).

Depending on what you want, using [`setRadius`](http://leafletjs.com/reference-1.0.0.html#circle-setradius) is probably preferable to modifying `_radius` directly.
