### ISSUE TITLE
Display labeled UTM grid on OSM using leafletJS

### ISSUE THREAD

**Issue by SAR-squad** [Leaflet/Leaflet#5223]
Hi all,

I am using leafletJS with OSM. No problem so far, its working like a charm!
:-)

As I am making this map for an SAR-Team, I must display an UTM grid over the map,
something like they are doing it here:
 * https://www.netzwolf.info/ol2/utmgrid

They use OpenLayer, but I must use leafletJS - unfortunately, this is not discussable ... :-(

Unfortunately, I did not found anything fitting my needs on the leafletJS site,
neither in plugins  or google resources. Can it really be possible, that this may not possible?
Am I the first one needing this? 
*wonder* ...

So how can i afford to display UT grid on a leafletJS OSM map?

Any help is highly appreciated.
:-)

**Comment by perliedman** [comment]
Hi and thanks for using Leaflet!

Please note that this is our issue tracker, where bugs and feature requests and posted and discussed. For questions on how to use Leaflet and other support, you're better off using [stackoverflow](https://stackoverflow.com/) or [gis.stackexchange.com](https://gis.stackexchange.com/).

Having said that, I think you can do this by building a [custom layer](http://leafletjs.com/examples/extending/extending-2-layers.html) and using [Proj4js](https://github.com/proj4js/proj4js).
