### ISSUE TITLE
Zooming causes lag in drawing geoJSON

### ISSUE THREAD

**Issue by atdiff** [Leaflet/Leaflet#5227]
Using Leaflet 1.0.2, there appears to be a drawing lag when zooming (using the zoom controls, double clicking, and other means).  I have a basic map with geoJSON of counties visible on it in a layer.  When zooming, the map itself will zoom appropriately, but the county shapes get drawn on a second or so later.  There is a very visible lag and not a smooth transition in zooming.

Example: http://jsfiddle.net/difftech/0zukqqb7/3/

This isn't an issue with 0.77 but is with 1.0.2.  It occurs in both IE and Chrome.

**Comment by nathancahill** [comment]
It looks like you're using CSS from 0.7.7 and JS from 1.0.2. Removing your CSS and adding this file to the HTML fixes your issue:

```html
<link rel="stylesheet" type="text/css" href="http://cdn.leafletjs.com/leaflet/v1.0.2/leaflet.css">
```
