### ISSUE TITLE
Open popup at cursor position instead of LineString center

### ISSUE THREAD

**Issue by HugoHeneault** [Leaflet/Leaflet#5235]
## How to reproduce
- Leaflet version I'm using: 1.0.2
- Browser (with version) I'm using: Chrome 55
- OS/Platform (with version) I'm using: Win7

### Steps
- Add a popup to a LineString geojson
- Hover it 

## What behaviour I'm expecting and which behaviour I'm seeing
I want the popup to open at my cursor position, but the popup opens at the center of the linestring

## Minimal example reproducing the issue
http://jsfiddle.net/wuu8Lv2t/1/

**Comment by perliedman** [comment]
You can achieve this by creating a new popup and adding at the desired location, instead of binding it. Since a bound popup can be opened by other means than a mouse click, it can't know where to open.

See here for a modified example: http://jsfiddle.net/uwdnvfy6/

**Comment by HugoHeneault** [comment]
This is short and very clear. Thank you for your answer!
