### ISSUE TITLE
Fractional zoom doesn't work on Leaflet 1.0.2 and 1.1-dev

### ISSUE THREAD

**Issue by vitaliyhayda** [Leaflet/Leaflet#5236]
- [x] I'm reporting a bug, not asking for help
- [x] I've looked at the [documentation](http://leafletjs.com/reference-1.0.0.html) to make sure the behaviour is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: 1.0.2 and 1.1-dev
- Browser (with version) I'm using: Chrome
- OS/Platform (with version) I'm using: OS X latest
- See this http://jsfiddle.net/erqwqctf/1/ 

## What behaviour I'm expecting and which behaviour I'm seeing
Fractional zoom doesn't work on versions 1.0.2 and 1.1-dev, but same code works if leaflet version is leaflet-1.0.0-b1.
In my example, changing from zoom from 13.6 to 14.3 would do nothing, but should of done incremental zooms.

## Minimal example reproducing the issue
http://jsfiddle.net/erqwqctf/1/

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by waynegm** [comment]
You need to set the option [zoomSnap](http://leafletjs.com/reference-1.0.2.html#map-option) to 0
