### ISSUE TITLE
Add a precision argument to toGeoJSON method

### ISSUE THREAD

**Issue by hrishiballal** [Leaflet/Leaflet#5237]
- [x] I'm reporting a bug, not asking for help
- [x] I've looked at the [documentation](http://leafletjs.com/reference-1.0.0.html) to make sure the behaviour is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: 1.0.2
- Browser (with version) I'm using: Firefox / Chrome 
- OS/Platform (with version) I'm using: Mac

This is a feature request. It would be nice to have a optional precision argument to the toGeoJSON() methods. The IETF [spec](https://tools.ietf.org/html/rfc7946#section-11.2) recommends 6 decimals but Leaflet usually gives more than 6 for co-ordinates. It will be nice to be able to specify a precision argument with the default being 6.

**Comment by Loufylouf** [comment]
I second that, in files with a lot of features, the extra-precision cause the size of the file to way too big, while it's not needed.  6 decimals means that at most latitudes and longitudes, the precision is under the meter, which is more than enough for most applications.

**Comment by dudu84** [comment]
Hi there! Can I work on this?

**Comment by ghybs** [comment]
Hi @dudu84,

In case you do work on that issue, make sure you take into account PR https://github.com/Leaflet/Leaflet/pull/5492, besides the PR #5444 that is referenced above.

**Comment by perliedman** [comment]
Fixed by #5444, which is now merged.

@dudu84 sorry, @mattgrande beat you to it, but you're more than welcome to take on one of the other issues with the "Help wanted" label!

**Comment by dudu84** [comment]
@perliedman thanks! I will take a look at other issues so.
