### ISSUE TITLE
ZoomAnimEvent isn't included in the docs, but is in Events.leafdoc

### ISSUE THREAD

**Issue by danzel** [Leaflet/Leaflet#5243]
ZoomAnimEvent is in Events.leafdoc:
https://github.com/Leaflet/Leaflet/blob/db7482a5619e1aa9c865870370b6500e85ef9c2c/src/core/Events.leafdoc#L130-L134

But doesn't appear after DragEndEvent in the live docs:
http://leafletjs.com/reference-1.0.2.html#dragendevent

cc @IvanSanchez

**Comment by IvanSanchez** [comment]
I can confirm, and cannot find an obvious cause for this. Fiddling with that file and changing order of events and such doesn't seem to help.

(One of this days I should go back to Leafdoc and fix these kinds of things) :disappointed:

**Comment by IvanSanchez** [comment]
Fixed in 007a63ab. That typo was **hard** to see.

**Comment by danzel** [comment]
haha, good find :)
