### ISSUE TITLE
Map does not update view after removing layers

### ISSUE THREAD

**Issue by ssilwa** [Leaflet/Leaflet#5252]
I am using the leaflet extension of the heatmap.js library to draw some layers on a map. I initialize the map with 
````javascript 
  var baseLayer = L.tileLayer(
          'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{
            attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://cloudmade.com">CloudMade</a>',
            maxZoom: 18
          }
        );


      var map = new L.Map('map', {
          center: new L.LatLng(42.38,- 71.12),
          zoom: 13,
          layers: [baseLayer]

        });

````
Then, I add a layer:
````javascript
mylayer.addTo(map);
````
After the user enters an input, I remove the layer:
````javascript
 map.removeLayer(heatmapLayer);
````
However, the view of the map does not update. Is there a method to redraw the map with the removed layer? Thanks!

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by ssilwa** [comment]
@IvanSanchez 
Ah, I figured out this issue! We can use layer groups (as shown in this excellent 
[tutorial](http://leafletjs.com/examples/layers-control/)) to show exactly the layers that we want!
