### ISSUE TITLE
Markers not resize with zoom

### ISSUE THREAD

**Issue by riqui99** [Leaflet/Leaflet#5260]
Hello,

First of all sorry for my english, I'm using a map with custom markers and when i zooming sometimes the markers do not resize while zooming. And when zoom stops the markers do not in his position. I think that this happens when some "onclick" in marker fires while zooming, after this event, it's more easy reproduce the issue.

I'm using leaflet 0.7.7, the problem is only appears in iphones (Safari or chrome) but not in Android.

I link a video that shows the effect. ;)
http://drive.talentiagestio.com/index.php/s/NWYJuyWqfL7SBx0

Thanks for advance.

**Comment by IvanSanchez** [comment]
Hi, Riqui,

We consider 0.7.x to be deprecated and will not handle bugs for those versions unless there is a really breaking bug. And without a reproducible case we can see, it's impossible to know what's wrong.

If you are *really* sure that this is a bug in leaflet, please: 
* [ ] Provide a reproducible case (e.g. a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) ) that displays this behaviour...
* [ ] ...which uses Leaflet 1.0.2
* [ ] [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

---

Hola, Riqui,

Consideramos que las versiones 0.7.x están obsoletas, y no gestionamos bugs para esas versiones a no ser que rompan algo muy serio. Y si no proporcionas un ejemplo reproducible, no hay manera de saber qué está pasando.

Si estás completamente seguro de que esto es un bug en Leaflet, entonces por favor: 

* [ ] Proporciona un caso reproducible (p. ej. fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/)) que muestre este comportamiento...
* [ ] Y que use Leaflet 1.0.2
* [ ] [Refrasea todo esto para hacer que suene como un buen bug report]((http://www.chiark.greenend.org.uk/~sgtatham/bugs.html))

P.D. Discúlpame por el castellano, pero es que yo catalán no controlo :-P

**Comment by riqui99** [comment]
Hola Ivan,

Muchas gracias por la rápida respuesta, intentaré esta noche de actualizar a la 1.0.2, y ver si con eso se resuelve directamente. Pero ami me da que es un problema de eventos solapados. Ya que todo funciona correctamente hasta que (no se cómo) mientras haces zoom y te posicionas sobre un marker, en alguna ocasión salta el popup que tengo en su trigger. Y a partir de allí los marcadores se vuelven un poco loco con el zoom. No se si de alguna manera poder desactivar todos los eventos de los markers mientras se hace zoom (como opción)?? o si recrear los eventos (hacer un removeEventListener y volver a crearlo) en cuanto se detecten otros eventos?? El caso es que parece ser mas un comportamiento de iOS ya que en android no he sabido reproducirlo. Pero creo que con alguna simple comprobación lo podríais tener arreglado.

Si puedo harcerte un código donde reproducir-lo lo subo, sino accediendo directamente al código donde me esta pasando imagino que ya serviría? te paso el link, un user i un password?

Saludos y muchas gracias!!!!!!

**Comment by IvanSanchez** [comment]
Es que tal y como me lo estás contando, esto tiene toda la pinta de ser una condición de carrera en cómo estás tú manejando los eventos. Y, lamentablemente, mi cerebro tiene poca paciencia para este tipo de "no me funciona, no te enseño cómo lo he hecho, pero arréglamelo gratis", espero que entiendas mi punto de vista.

Para esto hay que ver qué eventos estás gestionando, y cómo. Si realmente es un problema que sucede sólo en un navegador, sería posible acotarlo. (Pero te aviso que si usas algún framework tipo Cordova o Ionic o Angular, normalmente ignoramos ese tipo de bugs porque normalmente los introduce el framework).

Así que acota y aisla el bug, y publica algo un ejemplo **reproducible** y **mínimo** en un fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) o lo que quieras. Pero que todo el mundo lo pueda ver (así puede haber más ojos mirando el problema).

**Comment by riqui99** [comment]
Te he comentado que intento reproducirlo cuando llegue a casa por la noche en algún sitio (fiddle/codepen/playground) que puedas encontrarlo. Como tu (imagino) no saco nada de esto y hasta que no salga del trabajo no puedo intentar de trasladarlo. Yo, que me acuerda de memoria no gestionava ningun tipo de evento fuera de los mismos que proporcionáis con la API de leaflet.

Un saludo

**Comment by riqui99** [comment]
Que manera de hacer perder el tiempo, lo siento, actualizar versión y a la primera -.-'

Nota mental mirar version del master antes de abrir nada 

Gracias!

**Comment by IvanSanchez** [comment]
Ainssss. Creo que no sobra un "te lo dije" :stuck_out_tongue:
