### ISSUE TITLE
dblclick with pointer event doesn't work with retranslated events

### ISSUE THREAD

**Issue by life777** [Leaflet/Leaflet#5262]
Hi,

I'm using Leaflet with maps under my own svg layer. I catch all events on my svg and retranslate them down on the map with dispatchEvent method. It perfectly works with all events and in all browsers exept dblclick event in Edge browser (it doesn't support pure dblclick event, but I am talking about the same behavior with pointer events). 
I debugged  this issue and found out that Leaflet counts pointerevents in "L.DomEvent._pointersCount" for Edge browser and checks if there are more than 1 pointer then it can't be a dblclick (https://github.com/Leaflet/Leaflet/blob/master/src/dom/DomEvent.DoubleTap.js).

The counter "_pointersCount" is updated on capturing phase on the "document.documentElement" elements (https://github.com/Leaflet/Leaflet/blob/master/src/dom/DomEvent.Pointer.js).
Each "pointerdown" increments this counter, Each "pointerup" or "pointercancel" decreases this counter. The problem is that it doesn't check pointerId (that has to be unique for each pointer). It means "_pointersCount" counter can have wrong value (more than it should be) in case when someone retranslates the same pointer event with the same pointerId (like me).

The fix for this problem is quite easy: don't change "_pointersCount" value for the same pointer event.

## How to reproduce

- Leaflet version I'm using: latest
- Browser (with version) I'm using: Edge
- OS/Platform (with version) I'm using: Windows

Steps:
1) Add a leaflet with some map on the page
2) Add any element over the map
3) Add two event listeners on the element for "pointerdown" and "pointerup"
4) In handlers for this event add this code:

```js
let rootMapElement = docuemnt.querySelector("[[ map element selector ]]")
let newEvent = new PointerEvent(origEvent.type, {
    pointerId: origEvent.pointerId,
    bubbles: true,
    cancelable: true,
    detail: origEvent.detail,
    tiltX: origEvent.tiltX,
    tiltY: origEvent.tiltY,
    pressure: origEvent.pressure,
    pointerType: origEvent.pointerType,
    width: origEvent.width,
    height: origEvent.height,
    isPrimary: origEvent.isPrimary,
    screenX: origEvent.screenX,
    screenY: origEvent.screenY,
    clientX: origEvent.clientX,
    clientY: origEvent.clientY,
    button: origEvent.button,
    buttons: origEvent.buttons,
    relatedTarget: rootMapElement,
    view: window
});
rootMapElement.dispatchEvent(newEvent);
```

5) try to dblclick on the element that is over the leaflet map.

## What behaviour I'm expecting and which behaviour I'm seeing

Map should be zoomed in, but it doesn't because "_pointersCount" will be equal 2 in onTouchStart method (https://github.com/Leaflet/Leaflet/blob/master/src/dom/DomEvent.DoubleTap.js). 
It's wrong because we use the same pointerId and retranslated event should be treated as the same pointer (not the second one).

Thanks in advance

**Comment by IvanSanchez** [comment]
Probably related to #5180. Will wait a bit until we test the fixes for #5180 properly, then see if this is still reproducible.

**Comment by IvanSanchez** [comment]
@life777 The code for pointerevents has changed (#5180 is now merged into `master`). Can you please try again and see if this is still reproducible?

**Comment by life777** [comment]
@IvanSanchez  Yes, it's fixed. Thanks a lot

**Comment by IvanSanchez** [comment]
@life777 Thanks for checking :-)
