### ISSUE TITLE
Map isn't removed from memory on map.remove() - Causes memory leak

### ISSUE THREAD

**Issue by abishekreddy** [Leaflet/Leaflet#5263]
## How to reproduce

- Leaflet version I'm using: Leaflet 1.0/1.0.2
- Browser I'm using: Chrome Version 55.0.2883.87 
- OS/Platform (with version) I'm using: Windows 10
- Repro steps:
  a) Render map using GeoJSON.
  b) On button click - remove the existing map using map.remove() and initialize the map again (Using existing GeoJSON/new GeoJSON).
  c) Browser memory usage spikes every time the map is cleared and initialized again. (Check Windows Task Manager)

## What behavior I'm expecting and which behavior I'm seeing

- Expected behavior: The old map should be disposed and the browser shouldn't hold the memory that was allocated for the old map.
- Actual behavior: Browser memory usage spikes/stacks every time the map is re-initialized

## Minimal example reproducing the issue

- Link to JSFiddle: https://jsfiddle.net/6wu97g1L/
- Repro steps:
  a) Open JSFiddle link in new browser window.
  b) Check initial browser memory usage in Task Manager
  c) Click on "Color map" button (2-3 times).
  d) Check Chrome browser memory usage in Task Manager after every click.
  e) Repeat steps (c) & (d)

Memory on initial load:

![image](https://cloud.githubusercontent.com/assets/24618556/22031055/8527cd24-dd05-11e6-9dbd-243f57117089.png)

Memory after 2 clicks:

![image](https://cloud.githubusercontent.com/assets/24618556/22031065/90a774d8-dd05-11e6-8cb0-6eddbfaf1fb2.png)

Memory after 4 clicks:

![image](https://cloud.githubusercontent.com/assets/24618556/22031079/9a31d9f8-dd05-11e6-93c4-e7fbe552c929.png)

**Comment by perliedman** [comment]
Using the Chrome Task Manager (`Shift+Esc`), I can see memory growth, but not as dramatic as the screenshots above. I clicked 20-30 times and got the jsfiddle tab up to 130MB or so.

I guess the way to really tell what's going on would be to profile in dev tools - just looking at memory consumption can be misleading because of caches and a lot of other things.

**Comment by IvanSanchez** [comment]
There are a bunch of detached nodes around - most notably, the `HTMLCanvasElement`s, as they eat up a nice bunch of memory.

PR in the way.
