### ISSUE TITLE
Error while adding a Circle to map - probably error in L.bounds method

### ISSUE THREAD

**Issue by cnsgithub** [Leaflet/Leaflet#5269]
Hi, i've attached a chrome-debugger screenshot, where you can see what is going on. 

Initial call:

![image](https://cloud.githubusercontent.com/assets/13161711/22107367/ab0b14ee-de4d-11e6-83a5-2383b5dcd6e9.png)

Actual problematic line:

For some reason instanceof doesn't work - causing the if to fail and returning a new L.Bounds with undefined b

![image](https://cloud.githubusercontent.com/assets/13161711/22107332/6f3c7e12-de4d-11e6-8d0b-09766cc32603.png)

Hope this is enough as i didn't find a way to strip down the whole code for showing an example where it fails.

Used versions:
-Chrome Browser on Windows (newest versions)
-jQuery JavaScript Library v1.11.3
-Leaflet 1.0.2
-Leaflet Omnivore v 0.3.1

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by IvanSanchez** [comment]
Also, is this bug reproducible *without* Omnivore?

**Comment by cnsgithub** [comment]
Sorry it seems to be some error caused by a method which ran before the leaflet js files were completely loaded :(  So i'm closing it
