### ISSUE TITLE
Cann't listen to mousedown event

### ISSUE THREAD

**Issue by hon** [Leaflet/Leaflet#5272]
- [ ] I'm reporting a bug, not asking for help
- [ ] I've looked at the [documentation](http://leafletjs.com/reference-1.0.0.html) to make sure the behaviour is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [ ] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce
- Leaflet version I'm using: 0.7.7
- Browser (with version) I'm using: Chrome 55.0.2883.87 m (64-bit)
- OS/Platform (with version) I'm using: Window 10
- step 1
```javascript
document.addEventListener('mousedown', function() {
  console.log('mousedown')
})
```
- step 2
Click the map area, see console in debug tool

ps:
map.on('mousedown') works well. But that's not I want.

## What behaviour I'm expecting and which behaviour I'm seeing
It should print 'mousedown' when I click the map area.
## Minimal example reproducing the issue

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

Using http://playground-leaflet.rhcloud.com/ or any other jsfiddle like site.

**Comment by IvanSanchez** [comment]
Cannot reproduce with https://playground-leaflet.rhcloud.com/xapi/edit?html,output with Leaflet 1.0.2.

It's possible that the 0.7.x series are preventing propagation of events on the map container, but I don't think it's worth it to backport a fix.
