### ISSUE TITLE
Сan not scroll list of layers in Google Chrome

### ISSUE THREAD

**Issue by temapanf** [Leaflet/Leaflet#5277]
- Leaflet version I'm using: 1.0.2
- Browser (with version) I'm using: Chrome & FF
- OS/Platform (with version) I'm using: Windows 10

I can not scroll list of layers in layers control. Error in chrome 55, but all is well in Firefox 50. View gif.  In Leaflet 0.7.3 works fine.

Chrome 
![](http://savepic.ru/12723681.gif)

Firefox 
![](http://savepic.ru/12716513.gif)

**Comment by IvanSanchez** [comment]
This might be related to the troublesome `PointerEvent` logic of #5180.

Just in case, can you try with Leaflet 1.0.3?

**Comment by temapanf** [comment]
Screen from http://leafletjs.com/examples/layers-control/example.html, which is used 1.0.3

**Comment by IvanSanchez** [comment]
Can confirm. I've left a playground at https://playground-leaflet.rhcloud.com/vifa/edit?html,output

**Comment by IvanSanchez** [comment]
According to https://dom.spec.whatwg.org/#dispatching-events , step 18.1, the behaviour that Chrome>=55 exhibits is the right one: if any DOM parent of a element runs `preventDefault()` on the event while it is bubbling up (which is steps 12-13), an event flag is set, and that flag must (or *should*) be checked *at the end* of the browser's event handling logic.

**Comment by IvanSanchez** [comment]
A simple example like at http://jsbin.com/mefojojugi/edit?html,output displays the proper behaviour in other browsers, so I don't know which parts of Leaflet made this work until now. :confused:

**Comment by wladich** [comment]
I think this is beacause scroll propagation is disabled only for not-touch browsers:
https://github.com/Leaflet/Leaflet/blob/v1.0.3/src/control/Control.Layers.js#L166

But in last chrome version L.Browser.touch is true for desktop version.

This is sad as this flag is used in many places. For example zoom control is now enlarged in desktop Chrome (see gifs in issue)

**Comment by IvanSanchez** [comment]
Good catch! I was able to make a cleaner PR.

Regarding `L.Browser.touch` in Chrome, do read https://github.com/Leaflet/Leaflet/issues/5266 and https://github.com/Leaflet/Leaflet/issues/3944
