### ISSUE TITLE
L.Transformation factory

### ISSUE THREAD

**Issue by anetz89** [Leaflet/Leaflet#5278]
Hi there,

first of all - great job with your 1.0 release! I really appreciate your work!

As I use custom, projected maps with my own CRS, I have to dig deeply into your code and found out, that there's currently no factory function for L.Transformation like it is for custom elements like L.marker() for L.Marker.

Do you have plans to include factory functions like these? In case of the L.Transformation it would be helpful to also allow a passed array.

Currently I do it in my code, but maybe it is helpful for others, too?

    L.transformation = function(a, b, c, d) {
        if (L.Util.isArray(a)) {
            return L.transformation.apply(this, a);
        }
        return new L.Transformation(a || 1, b || 0, c || -1, d || 0);
    };

Regards
Markus

**Comment by perliedman** [comment]
Hi, and thanks for this suggestion. Although maybe not the most common thing, it looks like a nice improvement of the API.

One thing: if we add this to Leaflet, the array logic should go into the constructor, and not only the factory, right?

Feel free to submit a pull request, and ideally add a unit test for this!

**Comment by anetz89** [comment]
Added the array logic to the constructor. There might be some documentation issue with b, c and d as they get optional when an array is passed although they should not be optional when no array is passed. That's why I added default properties for a, b, c and d (corresponding to CRS.Simple).

I'm also not sure about the test, as it's quite basic. Feel free to adjust the code the way you like!

Please see: https://github.com/Leaflet/Leaflet/pull/5282

**Comment by jieter** [comment]
@perliedman Seems this can be closed since #5282 is merged
