### ISSUE TITLE
Make a hole based on a circle

### ISSUE THREAD

**Issue by vegarsc** [Leaflet/Leaflet#528]
I've been trying for some time now to make a hole in a polygon based on a circle - wihout any luck. Normally, to create holes, I've used  the "array of arrays of latlngs" trick, but this seems impossible to accomplish with circles, as they don't have any arrays of latlngs.

Any suggestions to what I can do?

Regards
Vegar

**Comment by Itemshopp** [comment]
After a lot of researches I couldn't find a way to make this work. 
I suppose `myPolygon = L.polygon([polygonCoords, circleCoords], myOptions).addTo(map);` should work but how do you retrieve circleCoords from initial `L.circle(circleCenter, circleOptions)`?

Actually, I read nothing about this in the Leaflet documentation

I hope I'm a really bad reader, thanks for your enlightments
