### ISSUE TITLE
Disabling context menus allows map to drag with right mouse button

### ISSUE THREAD

**Issue by hanginwithdaddo** [Leaflet/Leaflet#5284]
- [x] I'm reporting a bug, not asking for help
- [x] I've looked at the [documentation](http://leafletjs.com/reference-1.0.0.html) to make sure the behaviour is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

----

Add the following code snippet to the the Leaflet 1.0 example, which disables context menus allows you to drag the map using the right mouse button, but shouldn't.

Starting code:
http://leafletjs.com/examples/quick-start/example.html

Add the following just after the mymap.on() method invocation:
	mymap.getContainer().addEventListener("contextmenu", function(domEvent) {
		domEvent.stopPropagation();
		domEvent.preventDefault();
	}, true);

- Leaflet version I'm using: 1.0.3
- Browser (with version) I'm using: Chrome Version 55.0.2883.95 (64-bit
- OS/Platform (with version) I'm using: OSX

With the above snippet of code to disable all context menus, including any browser based context menu, you can drag the map using the right mouse button. I would think one should only be allowed to drag the map with the left mouse button. Adding the same snippet of code to the 0.7.7 example exhibits the behavior I would expect.

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by hanginwithdaddo** [comment]
The same is true with the following code snippet which replaces the display of the browser context menu with a map-specific message:
	mymap.getContainer().addEventListener("contextmenu", function(domEvent) {
		domEvent.preventDefault();
		var popup = L.popup()
			.setLatLng(mymap.mouseEventToLatLng(domEvent))
			.setContent('<p>Hello world!<br />This is a nice popup.</p>')
			.openOn(mymap);
	}, true);

**Comment by Malvoz** [comment]
Not able to reproduce in v1.8.0.

**Comment by Ruhrev** [comment]
Too bad, that was a feature if anything.
