### ISSUE TITLE
Second time clicking the same marker does not open the popup Window.

### ISSUE THREAD

**Issue by danielsamfdo** [Leaflet/Leaflet#5285]
## How to reproduce

- Leaflet version I'm using: 1.0.3
- Browser (with version) I'm using: Chrome Latest
- OS/Platform (with version) I'm using: Mac OS X
- Click on the marker once, popup will open
- Click on the marker again, the popup does not open
JS Fiddle to repro : https://jsfiddle.net/danielsamfdo/hsarnL0n/

Older Fiddle of Leaflet.js that works fine with the same piece of code : http://jsfiddle.net/danielsamfdo/gq5Wf/63/

## What behaviour I'm expecting and which behaviour I'm seeing
Expected behaviour openPopup should open the popup window.

## Minimal example reproducing the issue

JS Fiddle to repro issue : https://jsfiddle.net/danielsamfdo/hsarnL0n/

Older Fiddle of Leaflet.js that works fine with the same piece of code : http://jsfiddle.net/danielsamfdo/gq5Wf/63/

**Comment by IvanSanchez** [comment]
This is a bug in your code, not in Leaflet. By opening the popup manually on the `click` event, Leaflet then reacts with the default event handler and closes it again.

**Comment by danielsamfdo** [comment]
ok Thanks so i need not call it manually. It is automatically called the next time onwards. Thanks for the help
