### ISSUE TITLE
How to detect when new markers have been added to the map?

### ISSUE THREAD

**Issue by elbasan** [Leaflet/Leaflet#5287]
Hello,

May i ask how to I add a event listener to the map to detect when a marker has been added to the map?
In the docs, it says that we can use the "add" event, but how do I actually use it?
http://leafletjs.com/reference.html#marker

I have tried:

```
map.on(marker,'add', function() { // Throws a error "marker is not defined"
    console.log('marker added')
}); 
```

```
map.on(marker,'add', function() { // doesn't do anything
    console.log('marker added')
}); 
```

Any help?

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
