### ISSUE TITLE
Zoom >= 19 seems to be not working

### ISSUE THREAD

**Issue by rudyryk** [Leaflet/Leaflet#5289]
I noticed that www.openstreetmap.org by itself provides zoom up to 19, but with Leaflet I can't get zoom more than 18. As I can see from debug console tiles are not requested.

**Zoom = 18 with Leaflet - OK**
http://playground-leaflet.rhcloud.com/japa/1/edit?html,output

**Zoom = 19 with Leaflet - ERROR, just grey area**
http://playground-leaflet.rhcloud.com/kara/2/edit?html,output

**Zoom = 19 on OpenStreetMap - OK**
http://www.openstreetmap.org/note/875043#map=19/50.50000/30.51000&layers=N

**Comment by IvanSanchez** [comment]
See the default value for the `maxZoom` option of `L.Tilelayer`s at http://leafletjs.com/reference-1.0.3.html#tilelayer-maxzoom .

Not a bug.

**Comment by rudyryk** [comment]
@IvanSanchez I see, thank you! Then probably this statement in docs should be corrected?

http://leafletjs.com/reference-1.0.3.html#map-maxzoom
`Maximum zoom level of the map. Overrides any maxZoom option set on map layers.`

**Comment by IvanSanchez** [comment]
That means that the maximum zoom level of the map will be 19, regardless of the maximum zoom level of the tile layers.

I tried to fix this confusion by writing a tutorial at https://github.com/Leaflet/Leaflet/commit/04732631b08ef33732ad78c8b609a78bd263c1a2 , but left it unfinished. If you could spare the time to finish that up (and are interested), it would be greatly appreciated.

**Comment by pannz** [comment]
I'm still facing this problem, I have set the maxZoom as 19 (or tried greater), but when zoom to 19, it get gray. 
This is a the declaration and definition in my project. the layer url is same with OSM official tile layer url.

```
this.map = L.map(this.leafletMap, {
      layers: [theLayer],
      attributionControl: false,
      zoomControl: false,
      maxZoom: 19,
      minZoom: 0
    })
```
