### ISSUE TITLE
Change "children" to "child" in API description for createPane

### ISSUE THREAD

**Issue by RickMohr** [Leaflet/Leaflet#5292]
- [x] I'm reporting a doc issue, not asking for help

Change "children" to "child" (twice) in the API description for `createPane` in versions 1.0.0-1.0.3:
* https://github.com/Leaflet/Leaflet/blob/master/docs/reference-1.0.0.html#L1166-L1167
* https://github.com/Leaflet/Leaflet/blob/master/docs/reference-1.0.2.html#L1202-L1203
* https://github.com/Leaflet/Leaflet/blob/master/docs/reference-1.0.3.html#L1201-L1202

**Comment by jieter** [comment]
This docs are generated from the source code, so it has to be changed there too:

https://github.com/Leaflet/Leaflet/blob/703ae02aa8cbd0b87be5b01e77754b83ad732267/src/map/Map.js#L729

**Comment by danzel** [comment]
PR sent to fix ^^
