### ISSUE TITLE
Dragging path is not working in Chrome 55 with latest version (1.0.3)

### ISSUE THREAD

**Issue by peppierre** [Leaflet/Leaflet#5298]
## How to reproduce

- Leaflet version I'm using: 1.0.3
- Browser (with version) I'm using: Chrome55
- OS/Platform (with version) I'm using: Android
- Leaflet.Path.Transform version: 1.0.2
- Leaflet.Path.Drag version: 1.0.6

## What behaviour I'm expecting and which behaviour I'm seeing
Note that both Transform and Drag plugin (in this order) is referred.
Prior to Chrome 55 and using v1.0.2, Drag plugin's _onDragStart() handler is called when a path is started to be dragged, as it is expected. In Chrome55, dragging paths doesn't work due to Chrome's newly introduced pointer events, I guess.
Unfortunately, updating to v1.0.3 did not fix this behavior in Chrome 55, dragging of path still doesn't work because event handler above is simply not called anymore.

**Comment by IvanSanchez** [comment]
This looks like a bug in Leaflet.Path.Drag, not in core Leaflet. Please open a bug report at https://github.com/w8r/Leaflet.Path.Drag/issues instead.

cc @w8r
