### ISSUE TITLE
Bug on animate the tooltip

### ISSUE THREAD

**Issue by wahisoufiane** [Leaflet/Leaflet#5300]
- I've looked at the [documentation](http://leafletjs.com/reference-1.0.0.html) to make sure the behaviour is documented and expected
- I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- I've searched through the issues to make sure it's not yet reported
-----
- Leaflet version I'm using: Leaflet 1.0.2
- Browser (with version) I'm using: Latest Chrome
- OS/Platform (with version) I'm using: Windows 7
-----
I need to animate tooltip binded permanently to marker (using transition CSS3), the marker is animated well but the tooltip is animated at the first time from the top left map to the marker. How to avoid this behavior?

[Demo of the issue](http://playground-leaflet.rhcloud.com/vize/edit?html,css,console,output)

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
