### ISSUE TITLE
Chrome>55 highlights SVG paths on tap

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#5302]
As seen in https://stackoverflow.com/questions/42011444/how-to-avoid-leaflet-path-from-getting-selected-on-touch-devices

Environment: Chrome >= 55, latest Leaflet code from master.

How to reproduce: 
* Create a map with at least one SVG path or marker
* Use a touchscreen device, or Chrome's device emulation
* Click on the path, or make a drag less than 3 pixels (easier if no popups or interactions on the path)
* Somehow the interaction gets registered as a selection of the SVG path, highlighting it

![screenshot_20170203_094007](https://cloud.githubusercontent.com/assets/1125786/22585285/5befec8a-e9f7-11e6-9bc1-7c32214dbca3.png)

**Comment by nfantone** [comment]
Great feedback and response. Thanks for the effort!

(I'm the original author of the SO question).
