### ISSUE TITLE
End point of geojson layer connected to second layer leaflet

### ISSUE THREAD

**Issue by marie15** [Leaflet/Leaflet#5305]
Hi, I'm trying to add two geojson layers on the map, that is done but the end point of the first layer connected to the second layer, and I want to display each layer without beeing connected. Do you have any idea why that is happening? Any help is appreciated.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
