### ISSUE TITLE
Long-press and drag on buttons drags the map, but shouldn't

### ISSUE THREAD

**Issue by hanginwithdaddo** [Leaflet/Leaflet#5308]
- [x] I'm reporting a bug, not asking for help
- [x] I've looked at the [documentation](http://leafletjs.com/reference-1.0.0.html) to make sure the behaviour is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce
Long-press and move the mouse around within any button (e.g., the zoom buttons) and you will see the map move underneath button as though you were dragging the map. This should not happen. This happens with native Leaflet buttons, leaflet-draw buttons (which are like native buttons, using anchors not true buttons), and leaflet-easy-button buttons (which are true buttons).

- Leaflet version I'm using: 0.7.7 and 1.0.3
- Browser (with version) I'm using: Chrome Version 55.0.2883.87 m
- OS/Platform (with version) I'm using: Windows 7

## What behaviour I'm expecting and which behaviour I'm seeing
Map should not drag/move, but it does.

## Minimal example reproducing the issue
See above.
- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

Using http://playground-leaflet.rhcloud.com/ or any other jsfiddle like site.

**Comment by perliedman** [comment]
Hi,
thanks for reporting. These problems comes from not properly disabling propagation of `mousedown` and `click` events from those controls.

For the zoom buttons, I've submitted #5318 to address this, but we can't do much about the controls in other plugins: these plugins must disable click propagation themselves, and you should open issues on the individual plugins.

**Comment by hanginwithdaddo** [comment]
Isn't disabling event propagation dangerous? For example, stopping the propagation of pointerdown events causes problems for Leaflet 1.0.3's management of pointer events. Wouldn't a better solution be to change the map's mousedown listener to see if the target matches the map div and only act on it if the two match.

**Comment by perliedman** [comment]
@hanginwithdaddo hm, no, disabling propagation from controls is standard, and is already done by almost all controls. In this specific case, the zoom control didn't disable all the necessary events, though.

Leaflet's event design relies on events propagating from child elements to the map container in _a lot_ of cases - in fact, having a mouse event with the map div (the container) as target is almost impossible, since you will almost always have multiple child elements covering the entire container (tile pane, vector overlay pane, etc.). So ignoring events with another target will not work.

Exactly what `pointerdown` stop problems are you referring to?

**Comment by IvanSanchez** [comment]
@perliedman I see that the [current implementation of `DomEvent.disableClickPropagation()`](https://github.com/Leaflet/Leaflet/blob/689b71e2803fa1e1fa5e43f732f36ae33a466c20/src/dom/DomEvent.js#L189) stops `mousedown` and `touchstart`, but does not stop `pointerdown` - maybe this is causing some issues?

**Comment by perliedman** [comment]
@IvanSanchez I noticed the same thing and thought about adding `pointerdown` - I didn't see any issues on Chrome 55/Ubuntu with a touch enabled laptop, though.

**Comment by hanginwithdaddo** [comment]
I just know that in integrating our stuff with Leaflet 1.0.3, Leaflet's internal pointer logic got messed up when I stopped the propagation of pointer events. This was running Leaflet 1.0.3 under the latest version of Chrome (Version 56.0.2924.87 (64-bit)) on both OSX and Windows See the following methods:

	_globalPointerDown: function (e) {
		this._pointers[e.pointerId] = e;
		this._pointersCount++;
	},

	_globalPointerMove: function (e) {
		if (this._pointers[e.pointerId]) {
			this._pointers[e.pointerId] = e;
		}
	},

**Comment by hanginwithdaddo** [comment]
I would think checking the target in the map's mousedown handler to see if it matches the map (or draggable element) would be a better solution since it's more central and would take care of the problem for buttons, including 3rd party plug-ins (i.e., in Draggable._onDown() -- I think this is the place).

**Comment by perliedman** [comment]
Yes, stopping propagation of _all_ `pointerdown`/`pointermove` events will certainly break a lot of stuff, since a lot of the event logic is built under the assumption that events will propagate to the map container; in this particular case however, that is exactly what we want to prevent: we do not want the map to assume this is a drag event on the map.

I don't know how familiar you are with the Leaflet event handling, but you should read up on #3307 for some of the reasoning behind the current implementation - quite a lot of thought has gone into this, so while we're of course happy to see suggestions for improvement, we're also a bit reluctant to change this critical piece.

**Comment by hanginwithdaddo** [comment]
Have you tested your change (stopping the propagation of only mousedown events) with Chrome Version 56.0.2924.87? Just curious, because I believe it was between versions 55 and 56 that Chrome changed to fully support pointer events, dispatching pointerdown, followed by mousedown for non-touch devices, and pointerdown, touchdown, and mousedown for touch devices.

Yes, I do understand that stopping the propagation of pointerdown/pointermove events will cause problems, which is why I raised my concerns earlier. The area where I know we caused problems for Leaflet was stopping the propagation of pointerdown events on SVGs when we didn't want the map to respond to the pointerdown events. All of this was at the raw DOM event level, not the leaflet level, similar to the mousedown solution that you've implemented under #5318.
Thanks for the additional reference.

**Comment by hanginwithdaddo** [comment]
I tested the mousedown/touchdown change using a class that we have sitting on top of the EasyButton() support and this works (stops the map from dragging). Looks like we don't need to stop the propagation of pointerdown events. Sorry for any confusion/raising additional concerns.

**Comment by hanginwithdaddo** [comment]
I tested your solution of stopping the propagation of just the mousedown/touchdown events using Chrome Version 56.0.2924.87 and a class that we have on top of the EasyButton plugin support  and it works. There is no need to stop the propagation of the pointerdown events. Sorry for causing any additional concern/confusion.

**Comment by hanginwithdaddo** [comment]
For IE, pointerdown events must be stopped as well. mousedown/touchdown are sufficient for Chrome and Firefox.
You need to apply a similar change to the layer widget, since long-pressing the layer widget as it is expanded causes the same problem.
