### ISSUE TITLE
Two-finger dragging on Chrome>=55

### ISSUE THREAD

**Issue by psxde** [Leaflet/Leaflet#5310]
## How to reproduce

- Leaflet version I'm using: 1.0.3+ed36a04
- Browser (with version) I'm using: Android/Chrome 55.0.2883.91
- OS/Platform (with version) I'm using: Android
- Initialize map with dragging: !L.Browser.mobile to prevent one finger scrolling on the map to be able to scroll the page on mobile devices
- Try to scroll with two finger or try pinch zooming

## What behaviour I'm expecting and which behaviour I'm seeing
- Doesn't really work on Android, sometimes the map recognizes parts of the move but it's not really usable. Also the page scroll with two fingers and not the map
- Does work on iOS devices

## Minimal example reproducing the issue
```
<html>
  <head>
    <link href="https://unpkg.com/leaflet@1.0.2/dist/leaflet.css" rel="stylesheet"/>
    <script src="https://unpkg.com/leaflet@1.0.2/dist/leaflet.js"></script>
  </head>
  <body>

  <p>Text[...]</p>
    <div id="mapid" style="width: 600px; height: 400px;"></div>
  <p>Text[...]</p>

    <script>
      var mymap = L.map('mapid', {center: [48,9], zoom:8,  dragging: !L.Browser.mobile, layers: [L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png')]});
    </script>
  </body>
</html>
```

- [X] this example is as simple as possible
- [X] this example does not rely on any third party code

Relates on http://stackoverflow.com/questions/41622980/how-to-customize-touch-interaction-on-leaflet-maps

**Comment by IvanSanchez** [comment]
Most probably related to the `PointerEvent`s of Chrome >=55. For some reason the browser fires `pointercancel` events when performing the pinch gesture.

**Comment by Ghalko** [comment]
Can this be prevented by some setting with `touch-action` in CSS?

**Comment by psx01de** [comment]
Does someone know if that can bee prevented through the touch-action idea from @Ghalko? Is there a workaround to use the map as described in this issue? I want to switch from Google Maps to OSM with Leaflet but this issue prevents this because the webapp would not be really usable with this issue :(

**Comment by druncore** [comment]
A workaround for Chrome 55+ that worked for me was setting pointer to false in L.Browser. It's likely possible to make it more elegant than this though:

Added at row 737 in leaflet-src.js:
`	if (chrome && touch) { pointer = false; } `

**Comment by feerglas** [comment]
@druncore nice finding. But not really an option. Leaflet is putting a double-tab listener on the map. This listener will throw an error if your hack is applied:

`L.extend(L.DomEvent, {

	_touchstart: L.Browser.msPointer ? 'MSPointerDown' : L.Browser.pointer ? 'pointerdown' : 'touchstart',
	_touchend: L.Browser.msPointer ? 'MSPointerUp' : L.Browser.pointer ? 'pointerup' : 'touchend',

	// inspired by Zepto touch code by Thomas Fuchs
	addDoubleTapListener: function (obj, handler, id) {
		var last, touch,
		    doubleTap = false,
		    delay = 250;

		function onTouchStart(e) {
			var count;

			if (L.Browser.pointer) {
				if ((!L.Browser.edge) || e.pointerType === 'mouse') { return; }
				count = L.DomEvent._pointersCount;
			} else {
				count = e.touches.length;
			}
`

This code starts at line 11385 in leaflet-src.js

So, would be nice if this bug could be fixed by leaflet.

**Comment by HugoHeneault** [comment]
Any found a way to achieve the two finger scroll?

**Comment by feerglas** [comment]
@HugoHeneault yes we have a workaround. We hope the issue gets fixed inside the library, but for the time being we use this hack. Here is how we do it:

We require leaflet as a module and store it into variable:
```this.leaflet = require('leaflet');```

Then we check for touch devices. We use modernizr and the navigator object for this:
``var isTouchDeivce = Modernizr.touchevents || navigator.maxTouchPoints```

Then we can hack around the problem ;-)
```
if (this.leaflet.Browser.chrome && this.leaflet.Browser.touch && isTouchDevice) {
    this.leaflet.Browser.pointer = false;
}
```

As said, this is a hack. I'm not sure what consequences this has on older Android devices. Feel free to try it out and come back to me if you have any questions.

**Comment by johnd0e** [comment]
Test page updated with latest leaflet: https://gist.githack.com/johnd0e/cf9492df70a91e2263de0febe949d987/raw/issue-5310.html
