### ISSUE TITLE
Circle scaling improperly and not repositioning when setLatLng used during pinch zooming and "move" event

### ISSUE THREAD

**Issue by hughlomas** [Leaflet/Leaflet#5321]
## How to reproduce

- Leaflet version I'm using: 1.0.3
- Browser (with version) I'm using: Chrome for Android 55.0.2883.91
- OS/Platform (with version) I'm using: Android 6.0.1; Nexus 5 Build/M4B30Z
*same issue on coworker's iphone with ios 9 Safari*

I'm just trying to make a circle that always stays in the center of the viewport. No matter where you move the map, the circle should be centered.

Updating a circle position using setLatLng in the "move" during pinch zooming causes the circle to scale improperly relative to the map.

It also does not move the circle until the pinch zoom is complete.

## What behaviour I'm expecting and which behaviour I'm seeing

This seems to only be a problem when pinch zooming. 
Basically the circle should remain in the proper scaling proportions relative to the surrounding terrain, and should move the center during the pinch zoom.

In the minimal example https://jsfiddle.net/00xprfaw/7/show where the position has been changed using setLatLng, you can see that the circle changes scale at an improper ratio.  It should remain static to the relative zoom scale of the map.

Note a feature of the map that the circle lines up with and then pinch zoom. The radius will appear to change and no longer line up with that feature, because of the improper scaling. 

Also note that the circle's center does not actually update until after the pinch zoom is released, despite setting the latLng.

**Expecting**
Fiddle without the issue (where setLatLng is not used), note the circle scaling is proper while pinch zooming
https://jsfiddle.net/00xprfaw/8/show

## Minimal example reproducing the issue
**Try my minimal example on a mobile device.**

These fiddles use leaflet js 1.0.3 and leaflet css 1.0.3 and no third-party code

https://jsfiddle.net/00xprfaw/7/show 
https://jsfiddle.net/00xprfaw/7/

```javascript
var radius = 1000;
var lat = 51.505;
var lng = -0.09;

var map = L.map('map').setView([lat, lng], 13);
L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png').addTo(map);

var circle = new L.circle([lat, lng], radius);
map.addLayer( circle );

map.on("move", function(){
  var center = map.getCenter();
  circle.setLatLng( center );
});
```

## Notes

This may apply to all geometry, polygons, paths, etc. My example uses a circle, I have not checked the others.

Thank you

**Comment by yafred** [comment]
I don't think you should use layers for this purpose. Layers are part of the map.

If you want to draw a shape in the center of you map container, just use html and css. For example this will draw a 30 pixel circle just with css

```
#mapCenter {
	position: absolute;
	top: 50%;
	left: 50%;
	margin-left: -15px; 
	margin-top: -15px;
	height: 30px;
	width: 30px;
	border-radius: 50%;
	opacity: 0.2;
	background-color: black;
	z-index: 550;
	pointer-events: none;
}
```
For more complex shapes,  use svg. For example this will draw a 100 pixels cross

```
<svg id="mapGrid">
<path d="M50 0 L50 100 M0 50 L100 50" />
</svg>
```

Example: http://www.franceimage.com/map/

my 2 cents

**Comment by IvanSanchez** [comment]
> Basically the circle should remain in the proper scaling proportions relative to the surrounding terrain, and should move the center during the pinch zoom.

Not possible with the current `L.Canvas` or `L.SVG` renderers. If you need something that doesn't scale and redraw at every zoom level, use a marker with a `L.DivIcon` instead.

**Comment by hughlomas** [comment]
@yafred The circle should be a layer of the map. If I have a 30 mile fixed radius circle, it should remain 30 miles in scale to the map when zooming.
The basic problem is that the render cycle is out of sync with the event cycle when pinch zooming.
I did end up solving my problem with an SVG circle (outlined below), but the key part is that the radius needs to be accurately reflected no matter what the zoom is.

@IvanSanchez I do need something that scales while zooming, the way it works in the provided example without repositioning the circle on the "move" event. If it's impossible with the current renderers, then so be it. Thank you for looking. 


To anyone else that comes across this with a similar issue, my solution to this problem was to draw an SVG circle in the center of the container, positioned over the map (be sure to use `pointer-events: none`) element, and then use projection to modify the circle's radius after a move event.

This makes use of mapbox's cheapRuler, though any library that will calculate an endpoint lat/lng given a distance and bearing will work.

```javascript
getRadiusInPixels: ( radiusMeters ) => {
    let center = this.map.getCenter();
    //calibrate cheapRuler
    let ruler = cheapRuler( this.state.lat, "meters");
    //get a lat/lng that is the desired distance away, on the x axis (90 deg bearing)
    let radiusEnd = ruler.destination( center.toArray(), radiusMeters, 90 );
    //get the screen coordinates relative to the map
    let centerPoint = this.map.project( center );
    let endPoint = this.map.project( radiusEnd );
    //return the pixel distance between the center and the generated point
    return endPoint.x - centerPoint.x;
}
```

**Comment by perliedman** [comment]
I looked a bit closer at this a couple of weeks ago, and at the core of the problem is the fact that the circle's [`_project` method](https://github.com/Leaflet/Leaflet/blob/master/src/layer/vector/Circle.js#L68), which is called when radius and center is changed, relies on some values that are not updated during a pan, for example the pixel origin; this causes erratic positioning and sizing.

I found some fixes, but the result still wasn't perfect, and I had to abandon it for the time being; I should put the code somewhere, though. Will try to find it.

**Comment by perliedman** [comment]
FWIW, I pushed the work-in-progress changes I made while debugging this issue here: https://github.com/Leaflet/Leaflet/tree/fix-circle-while-zooming

**Comment by derwaldgeist** [comment]
I am facing a similar problem on iOS when doing pinch zooming. I wanted to create something like `leaflet-user-marker` (a marker that shows the current position of the user, including an accuracy circle around it), but based on `react-leaflet`.

I managed to put the accuracy circle on the map, and it auto-scales perfectly on desktop devices when zooming in or out with the mouse wheel.

But if I run the same code on iOS using pinch zoom, the circle jumps around erratically and sometimes ends up to being placed where it definitely doesn't belong (i.e. away from its correct position).

Has the fix you mentioned been already been included in recent Leaflet versions?

**Comment by perliedman** [comment]
@derwaldgeist no, I haven't done any work on that. But if you're not updating the position and/or radius while zooming, it should be irrelevant anyway.

If you can make an example reproducing the problem (without React), feel free to open a new issue so we can have a look.

**Comment by derwaldgeist** [comment]
Ok, thanks for the info. No, I am not changing the position or radius while zooming. I more or less re-implemented `leaflet-user-marker` on top of `react-leaflet`, and in the original version, the position is only reset if the marker is being moved.
