### ISSUE TITLE
how to disable animate globally

### ISSUE THREAD

**Issue by hon** [Leaflet/Leaflet#5322]
- [ ] I'm reporting a bug, not asking for help
- [ ] I've looked at the [documentation](http://leafletjs.com/reference-1.0.0.html) to make sure the behaviour is documented and expected
- [ ] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: 1.0.2
- Browser (with version) I'm using:  55.0.2883.87 m (64-bit)
- OS/Platform (with version) I'm using: win10
- step 1
Drag or zoom the map
- step 2
The map is animated

## What behaviour I'm expecting and which behaviour I'm seeing
Globally disable animate effect. after I stop drag or wheel, the map goes to somewhere directly.
panTo(), setZoom() works fine, but they only set some point to point, or zoom level to zoom level.

## Minimal example reproducing the issue

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

Using http://playground-leaflet.rhcloud.com/ or any other jsfiddle like site.

**Comment by perliedman** [comment]
Hi and thanks for using Leaflet!

Please note that this is our issue tracker, where bugs and feature requests and posted and discussed. For questions on how to use Leaflet and other support, you're better off using [stackoverflow](https://stackoverflow.com/) or [gis.stackexchange.com](https://gis.stackexchange.com/).

Having said that, look at map animation options: http://leafletjs.com/reference-1.0.0.html#map-fadeanimation
