### ISSUE TITLE
leaflet-src.js not found -- bower.json

### ISSUE THREAD

**Issue by djozen** [Leaflet/Leaflet#5326]
Hi,

I'm reporting a bug, not asking for help

In file bower.json it have this :

"main": [
"dist/leaflet.css",
"dist/leaflet-src.js"
],

But it have no file leaflet-src.js in dist directory.
I want use bower, but i can't because it have not js files.

Thank you.

**Comment by danzel** [comment]
Built versions are only shipped in version tags
for example:
https://github.com/Leaflet/Leaflet/tree/v1.0.3/dist

**Comment by djozen** [comment]
Thank you.
