### ISSUE TITLE
Provide access to map._getBoundsCenterZoom

### ISSUE THREAD

**Issue by ptbrowne** [Leaflet/Leaflet#5333]
Hi,

I generate static maps through [Mapbox API](https://www.mapbox.com/api-documentation/#retrieve-a-static-map-image). In my static maps, I usually have an overlay that I want to fit entirely in the map. Since Mapbox's API takes only center and zoom, I need to calculate the center and zoom that will fit these bounds. So I have written : 

```js
const getCenterZoomFromWidthHeightBounds = function (width, height, bounds) {
  const div = document.createElement('div');
  div.style.opacity = 0;
  div.style.position = 'absolute';
  div.style.width = width + 'px';
  div.style.height = height + 'px';
  document.body.appendChild(div);
  const map = L.map(div).fitBounds(bounds);
  ret = { center: map.getCenter(), zoom: map.getZoom() };
  div.parentNode.removeChild(div);
  return ret;
};
```

[Example code that uses this code](http://jsbin.com/gikalusege/edit?js,console,output)

It seems a bit inefficient to have to create a new map for this and to have to create a new div etc...

Looking at the code for [Map](https://github.com/Leaflet/Leaflet/blob/b997839fe73397330c292dcac1e5a65cb3ea8fdb/src/map/Map.js), the code that is used by fitBounds is pretty coupled to the map.

I wonder if it would be worth it to decouple the code to compute the center/zoom from the map and then to provide it as an util. Or maybe there is a better way of doing what I do that I did not think of ?

I would open to do a PR if you think that is useful.

Thanks

**Comment by IvanSanchez** [comment]
You already have `getBoundsZoom`, and calculating the center should be easy enough, even if you have to transform the lat-lng coordinates to EPSG:3857 via `map.options.crs.project()`. I see no need to expose a new public method in `L.Map`.

> It seems a bit inefficient to have to create a new map for this and to have to create a new div etc...

Please remember that Leaflet is a map *display* library. If you are using it for geodesic calculations, then you probably are using the wrong tool :-P

If I were you, I would also get in touch with Mapbox and request that feature from their API.

**Comment by IvanSanchez** [comment]
> I meant exposing the method as a util like BoundsUtil or something like that.

It *might* be useful to move the code to `L.CRS`, but that function still needs a size in pixels from the map. Unfortunately I'm not sure it can be refactored easily.

**Comment by ptbrowne** [comment]
Understood. Thanks :)
