### ISSUE TITLE
Tool Tip for heatmap layer

### ISSUE THREAD

**Issue by JKeeru** [Leaflet/Leaflet#5334]
Hello,
is there anyway to bind tooltip for each individual points on heat layer...? 
or 
any way to show the value of intensity on heat layer...??

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
