### ISSUE TITLE
ZoomOut Of Big Size Images

### ISSUE THREAD

**Issue by JKeeru** [Leaflet/Leaflet#5335]
Hi ,
I'm using leaflet heat map with image overlay.
setting the map div width and height to the original image width and height.
If the image size is bigger(more than 2000x2000 dimension) then if i do Zoom out**(-)**  of the image the image is going somewhere else i can't see the image on map.

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by JKeeru** [comment]
if i click on zoom out (-) the image is going somewhere to see i have to use scroll or drag

fiddle here:   https://jsfiddle.net/12svpgx7/  

the image used here is of dimension 1920x1080

**Comment by IvanSanchez** [comment]
You are modifying the size of the map's container for no good reason at all...

```
document.getElementById("map").style.height = height + "px";
document.getElementById("map").style.width = width + "px";
```

So the center of the map is off-screen. Notice the scrollbars in your browser. Things work as expected [when the map is not resized to the size of the image](https://playground-leaflet.rhcloud.com/woyi/edit?html,output).

Not a Leaflet bug.

**Comment by JKeeru** [comment]
I'm modifying the size of the maps container because if heat points are there then these points are coming out of image , if i fix the map container size to original image size then the heatpoints are shown properly on images at exact position.

https://playground-leaflet.rhcloud.com/pogi/edit?html,output

**Comment by IvanSanchez** [comment]
So? That's because you are (for some strange reason) using the map size to recalculate the heat points, instead of using the image size.

https://playground-leaflet.rhcloud.com/wapi

Your original problem is really a [XY problem](https://meta.stackexchange.com/questions/66377/what-is-the-xy-problem), and this is definitely not a Leaflet bug.

**Comment by JKeeru** [comment]
Yes  i understood the problem thanks :)
