### ISSUE TITLE
Help: draw polyline across dateline without using worldCopyJump

### ISSUE THREAD

**Issue by chew0904** [Leaflet/Leaflet#5340]
- im not sure where to get help on this, sorry if this issue has been raised before.

----
1. i need to show marker across map, drag sideway will have the marker show without hiding the previous one
* worldCopyJump will replicate but previous map marker will gone

2. i need to limit maxbound only to top and bottom, not sideway.
i couldnt use code below to 
`var maxSouthWest = L.latLng(-85, -180);`
`var maxNorthEast = L.latLng(85, 180); `
`var maxBounds = L.latLngBounds(maxSouthWest, maxNorthEast);`

3 can the latitude and longitude to be correct even crossing map dateline

4. i need to draw shortest polyline route which similar to google map. (refer to image)

![capture1](https://cloud.githubusercontent.com/assets/25839958/23057988/b9687206-f52d-11e6-8322-61de57e25cac.PNG)

![capture2](https://cloud.githubusercontent.com/assets/25839958/23057994/c0009d3c-f52d-11e6-9f87-0aaa2b99d9d8.PNG)

google map can drag map across dateline smoothly, below is my working copy

![capture3](https://cloud.githubusercontent.com/assets/25839958/23057999/c6cedb56-f52d-11e6-84df-9569b9258e37.PNG)

i need to calculate and draw the shortest route which not like image above

![capture4](https://cloud.githubusercontent.com/assets/25839958/23058008/cb52eb7c-f52d-11e6-8ba0-46cd6f26af62.PNG)
* this will hav the longitude more than 180 (240 example), which i want it to be in correct lat lng

Greatfully thanks to anyone that could help.

Ralph

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

Specifically regarding this, see https://stackoverflow.com/questions/38820724/how-to-display-leaflet-markers-near-the-180-meridian/ and https://stackoverflow.com/questions/40532496/wrapping-lines-polygons-across-the-antimeridian-in-leaflet-js/

**Comment by IvanSanchez** [comment]
And see also the plugins list, there is a plugin for calculating geodetic lines

**Comment by chew0904** [comment]
thanks @IvanSanchez 
will continue to search for that
