### ISSUE TITLE
Source map for minified leaflet.js

### ISSUE THREAD

**Issue by robert-m-johnson** [Leaflet/Leaflet#5341]
There is a source map for the non-minified leaflet-src.js, but nothing for the minified leaflet.js. Even if such a source map simply mapped back to leaflet-src.js rather than the "true" source I would still find it useful, as I'm sure would many others.

**Comment by IvanSanchez** [comment]
I don't think it is that useful. Also, offering a sourcemap would make the browser pull it from the network, defeating the purpose of a minified build. Developers' needs are covered by `leaflet-src.js`.

I'll close this as "wontfix".

**Comment by robert-m-johnson** [comment]
> Also, offering a sourcemap would make the browser pull it from the network...

This is only true if developer tools are open and source maps are enabled. Providing a source map for `leaflet.js` would allow library users such as myself to use the minified version in both dev and production, but still allow us to step into the original source if desired.

**Comment by IvanSanchez** [comment]
Any reason why you don't minify the whole bundle (including deps like leaflet) for the production build? I'm doing that myself in some projects, it just works, and I can control the sourcemaps for the minified bundle.

**Comment by robert-m-johnson** [comment]
Could do yeah, reason why we haven't done so yet is simply lack of time. 

I have no difficulty in seeing why a source map for the minified distribution is a low priority. However it seems a shame to close this issue - unless this would be sure to negatively impact the build process in some noticeable why, what's the harm in leaving this issue open?

**Comment by danzel** [comment]
If you are pointing your live site at `leaflet.js` hosted on a CDN then having a sourcemap would be really useful rather than having to switch to use the `-src` version to see what is going on.

I think this will be useful, and it's easy, PR incoming... so reopening

**Comment by blq** [comment]
Maybe I misunderstand something, but although source maps are provided for both leaflet.js and leaflet-src.js now, only -src actually have it referenced from the js using "sourceMappingURL"?
