### ISSUE TITLE
dynamicLayer proxy

### ISSUE THREAD

**Issue by fawadsh1** [Leaflet/Leaflet#5342]
Hi,

I am using proxy map server to create dynamic layers on top the map.
I set the proxy by providing proxy url when creating the dynamic layer.
For example

**hazardLayer = esri.dynamicMapLayer({
            url: 'some map url',
            opacity: 0.7,
            useCors: false,
            minZoom: 4,
            proxy: 'http://someserver.com/proxy.ashx'
        });**

When i add this hazard layer to map, the first request goes to the proxy server and returns the map related info in json format. esri again calls for png file which will create the map layer. It does not use the proxy server. 

**My question is. Is there anyway i can make leaflet esri to use proxy server for all request.**

Regards,

Fawad

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features **on the Leaflet core only**. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

For questions/bugs/feature requests about `esri-leaflet`, please go to https://github.com/Esri/esri-leaflet
