### ISSUE TITLE
How to disable single finger dragging on touch devices

### ISSUE THREAD

**Issue by lijunray** [Leaflet/Leaflet#5343]
- [ ] I'm reporting a bug, not asking for help
- [x] I've looked at the [documentation](http://leafletjs.com/reference-1.0.0.html) to make sure the behaviour is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported
----

## How to reproduce

- Leaflet version I'm using: leaflet
- Browser (with version) I'm using: Safari
- OS/Platform (with version) I'm using: iOS 10

## What behaviour I'm expecting and which behaviour I'm seeing
When user is dragging the page on mobile browsers, it acts like scrolling but when it comes to the map and user's finger is within the map, leaflet's dragging event is fired and scrolling is not. We want to disable single finger dragging but keep double fingers dragging so that user can drag map with 2 fingers while scroll the page with 1 finger. 
Question: Is there any ways to do this above?

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
