### ISSUE TITLE
Attribution text is combined when using multiple layers

### ISSUE THREAD

**Issue by stefaang** [Leaflet/Leaflet#5355]
- [x ] I'm reporting a bug, not asking for help
- [x ] I've looked at the [documentation](http://leafletjs.com/reference-1.0.0.html) to make sure the behaviour is documented and expected
- [x ] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x ] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: 1.0.3
- Browser (with version) I'm using: Chrome Mobile 56.0 and Firefox 51.0 64bit Ubuntu
- OS/Platform (with version) I'm using: Android and Ubuntu
- step 1: create 2 tileLayers (each with attribution) and a map with these layers as in the tutorial example.
- step 2: create a layers control and addTo map.

## What behaviour I'm expecting and which behaviour I'm seeing
Current: On map load, the attribution text is the combination of both. When changing the layers with the control, the correct attribution is shown.

Expected: On map load, the attribution text matches the current layer. (Not both)

## Minimal example reproducing the issue

- [x ] this example is as simple as possible
- [x ] this example does not rely on any third party code

http://playground-leaflet.rhcloud.com/kiwo/edit?html,css,output
https://gist.github.com/anonymous/6d2e92909c37a1f4c9a499df4680f60b

**Comment by IvanSanchez** [comment]
You're adding both tile layers to the map, so attribution for both is shown. When using the layers control for the first time, one of the tile layers is removed.

Leaflet is behaving as expected here.

Leaflet does *not* check exclusivity of layers in the "baselayers" group of a `L.Control.Layers` when the control is instantiated/added to the map, see https://github.com/Leaflet/Leaflet/issues/4925

**Comment by stefaang** [comment]
Okay I see... I used 2 baselayers (light and dark) while the tutorial uses a baselayer and a markerlayer in the map constructor. Thanks for clearing that up!
