### ISSUE TITLE
pointerup not firing when app with leaflet map is in an iframe.

### ISSUE THREAD

**Issue by tpneumat** [Leaflet/Leaflet#5356]
## How to reproduce
- Leaflet version I'm using:
1.0.2 or 1.0.3 (NOTE: .7x does not have this problem)
- Browser (with version) I'm using:
Chrome version 55.x (on mobile devices)
- OS/Platform (with version) I'm using:
Android 6.0.1
- step 1
Setup a leaflet map inside an iframe.

- step 2
Setup a toggle tabs inside the iframe to show/hide the map. 

## What behaviour I'm expecting and which behaviour I'm seeing

When map is in an iframe, and furthermore, inside a hidden div that is occasionally shown/hidden, clicking around fires pointerdown (leaflets _globalPointerDown)  but fails to fire pointerup (_globalPointerUp) and thus _pointers don't get deleted/decremented (start to build up) causing map touches to fail or act unpredictable on next use. 

## Minimal example reproducing the issue

Sorry--didn't have time to put this together since I found work-around.

**Work-around, every time we tab to map, I clear out pointers like this.**
L.DomEvent._pointers={};                    
L.DomEvent._pointersCount=0;

**Comment by IvanSanchez** [comment]
This is going to be tricky to debug (specially if we don't have a easy-to-see reproducible example). I'd personally wait until a future "`PointerEvent`s first" whole refactor.

**Comment by perliedman** [comment]
I'm going to close this as there's nothing we can do with this bug description until we have a test case that reproduces the problem. Happy to reopen once we have something to work with!
