### ISSUE TITLE
Bounds calculation

### ISSUE THREAD

**Issue by pronebird** [Leaflet/Leaflet#5357]
- [X] I'm reporting a bug, not asking for help
- [X] I've looked at the [documentation](http://leafletjs.com/reference-1.0.0.html) to make sure the behaviour is documented and expected
- [X] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [X] I've searched through the issues to make sure it's not yet reported

----

Hi,

There are lots of mentions of bounds across documentation but there is no mention how to calculate them. It's very trivial with Circle, i.e:

```
const c = Leaflet.circle(position, {radius:50}).addTo(map);
const bounds = c.getBounds();
c.remove();
```

But the problem with it is that it's a visual component that has to be attached to the map. Is it absolutely necessary to calculate bounds? Is there any utility that can be used to calculate bounds given center point + radius / zoom? 

I exclusively need this to feed it into React-leaflet so I can do everything within single pass without running unnecessary animations. Also, I use `paddingBottomRight` that's why I need to calculate bounds otherwise I'd simply stick to `center`.

It would be great to include relevant example in documentation.

**Comment by IvanSanchez** [comment]
> Is it absolutely necessary to calculate bounds?

Yes, specially for circles, since that has a hard dependency on the map's CRS. No map = no CRS = no way to do stuff with radius in meters (or map units).

> within single pass without running unnecessary animations.

Adding and removing a Leaflet layer to/from a map within a single frame will not trigger any animations.

**Comment by IvanSanchez** [comment]
If you need to calculate `LatLngBounds` without adding stuff with a Leaflet map, you'll have to resort to solving the [first geodetic problem](https://en.wikipedia.org/wiki/Geodesy#Geodetic_problems) a couple of times. Things like [cheap-ruler](https://github.com/mapbox/cheap-ruler) or [GeographicLib](http://geographiclib.sourceforge.net/html/js/)

**Comment by pronebird** [comment]
Thanks @IvanSanchez, cheap-point's bufferPoint looks like what I need to calculate bbox.
