### ISSUE TITLE
Post Rollup plugin compatibility

### ISSUE THREAD

**Issue by hyperknot** [Leaflet/Leaflet#5358]
The big rollup commit broke https://github.com/mapzen/leaflet-geocoder, and possibly other plugins. The actual error message in that case is with `L.Mixin.Events`:

```
Uncaught TypeError: Cannot read property 'Events' of undefined
```

My question is:
1. Is it a change by design, and if so, is there a guideline for porting plugins to Leaflet 1.0.4 (or 1.1) so we can contribute to some common plugins to fix their issues?
2. If not, please consider this a bug report.

Minimal example:
https://playground-leaflet.rhcloud.com/qatu/1/edit?html,output

**Comment by IvanSanchez** [comment]
Hey @hyperknot! :-D

The problem (from my point of view) is that `L.Mixin` is an *old* and undocumented bit that got refactored away in Leaflet 1.0.0. Leaflet 0.7.x had some `L.Mixin.Events` as a way to specify the mixins to be added to a prototype that would handle events. Now we simply do `L.Evented.extend({...})`.

Note how the API docs for Leaflet 1.0.0 do *not* make any reference to `L.Mixin`. From my point of view, `L.Mixin` is deprecated since 1.0.0.

What the Rollup refactor did was take away that bit. The [last commit where `L.Mixin` appears](https://github.com/Leaflet/Leaflet/blob/3ac37c29a4aa5fe144173bf6f76fb72eb77bff5b/src/core/Events.js#L289) looks like this:

```
L.Mixin = {Events: L.Evented.prototype};
```

So you can keep compatibility by doing something like 

```
L.Mixin = L.Mixin || {Events: L.Evented.prototype};
```

Or, you can simply replace any occurences of `L.Mixin` with `L.Evented.prototype`, or you can use `L.Evented.extend({})` instead.

Do you think it will be useful to keep that in the post-rollup releases? Do we know how many plugins are affected?

**Comment by jgravois** [comment]
> Do we know how many plugins are affected? 

i spent a few minutes snooping and found these:
- [X] [`Leaflet.draw`](https://github.com/Leaflet/Leaflet.draw/blob/818af15d667dcb86d3cc42ad548b24a7358af3d4/src/draw/handler/Draw.Feature.js#L8) 
- [X] [`Leaflet.label`](https://github.com/Leaflet/Leaflet.label/blob/0a4e3a6422c9e5a799a9cde106de5bcfdb5ab741/dist/leaflet.label-src.js#L30)
- [X] [`react-leaflet`](https://github.com/PaulLeCam/react-leaflet/blob/a1b70b0465d85e997ca354df75e316b502ccca2c/__mocks__/leaflet.js#L66)

**Comment by hyperknot** [comment]
I think potentially many plugins are affected, and many of those definitely won't be upgraded in time for the next release.

What are our options?
- Call it Leaflet 1.1, since we are breaking compatibility.
- If possible, provide a backwards compatibility with something like `L.Mixin = {Events: L.Evented.prototype};` for at least 1.1-s lifetime.
- Now the tricky big: try to detect the first time L.Mixin is called and display a console.log depreciation warning. I think limiting it to the first time is required, some plugin might use it in a loop or something, and we'd ruin performance by thousands of console.logs. I don't know what's the best way to detect usage of something like this, and how to count it, but I'm sure others have ideas for this.
- Write an upgrade notice for 1.1, mentioning what plugin authors should do.

Just my ideas.

**Comment by perliedman** [comment]
Wow, did not know about this!

As I see it, we can't remove `L.Mixin.Events` without calling it 2.0: if we left it in 1.0.0, we can't remove it now. It doesn't matter much if it's documented or not: it was the documented way in 0.7 (and lots of versions before that), and at least I haven't seen any text mentioning it's deprecated.

As @jgravois says, a lot of large plugins would break, and I would add to that list just about any Leaflet plugin or app I've written, I expect the same for a lot of other people. That does not sounds like something you would like for a 1.1 release.

I think 2 and 3 of @hyperknot's suggestions are the way to go. I guess we could just add a cludge to `L.Class`'s `include` functionality and check if it's `L.Mixin.Events` that is being included, and log a deprecation notice: the includes are done once per class declaration (https://github.com/Leaflet/Leaflet/blob/master/src/core/Class.js#L50), so it shouldn't be a performance issue.

**Comment by IvanSanchez** [comment]
I'd like to add the `L.Mixin = {Events: L.Evented.prototype};` "backwards compatibility kludge™", and open issues in the repos of the affected plugins instead. Shift the burden to the plugins instead of worrying about deprecation notices.

**Comment by hyperknot** [comment]
If it's as simple as a console.log statement in `include`, I'd definitely print a warning line. That way not only plugin authors but developers get a feedback as well.

// It's one of the things that Django does really well. They print a warning line about every depreciated feature you are using, with a clear message about when will it be removed.

**Comment by danzel** [comment]
I think you can call `leaflet.label` deprecated as we now have label support in core leaflet

**Comment by louh** [comment]
Hey there - thanks for the heads-up in `mapzen/leaflet-geocoder` on this, and I appreciate having the shim and the deprecation notice on `L.Mixin.Events` in the short term. I think that was definitely the right move here. Now that we are aware it is deprecated in v1, we will update leaflet-geocoder soon to use the new functionality.

**Comment by hyperknot** [comment]
Nice work, good to see this solved so smoothly! Are we calling next release
1.1?

**Comment by IvanSanchez** [comment]
@hyperknot I think that the Rollup modules are a feature instead of a bugfix, and we love [semver](http://semver.org/), so yeah. Nevertheless I'd love to get some feedback on https://github.com/Leaflet/Leaflet/pull/5290 for 1.1.0. *wink wink nudge nudge* ;-) Or at least a 1.0.0-rc1 or something.

**Comment by louh** [comment]
We've just published https://github.com/mapzen/leaflet-geocoder/releases/tag/v1.8.0, which should resolve our compatibility with this (anyone mind giving it another test?)

**Comment by hyperknot** [comment]
@louh I'll have a look.
