### ISSUE TITLE
Anchor popup window based on top-left corner

### ISSUE THREAD

**Issue by epschmidt** [Leaflet/Leaflet#536]
Instead of having the popup window show centered above the marker, I'd like it to popup to the right, with an arrow pointing into the marker. I've attached 2 screenshots. The anchor for the window is the center of the window, will I need to make a set width for the popup window? Or is their another way to anchor the window based on it's top left corner, or something like that?

https://skitch.com/eschmidt/8rwpx/leaflet-popup

https://skitch.com/eschmidt/8rwp6/leaflet-popup2

**Comment by bypotatoes** [comment]
As I [see](https://github.com/CloudMade/Leaflet/blob/master/src/layer/Popup.js#L212) for now there's possibility to move popup with `offset`. E.g. move popup 120px left:
```
const popup = this.L.popup({
     offset: L.point(120, 0)
});
```
or
```
const popup = this.L.popup({
     offset: {
        x: 120,
        y: 0,
     }
});
```
