### ISSUE TITLE
zoomAnim event firing

### ISSUE THREAD

**Issue by scgrant327** [Leaflet/Leaflet#5366]
The zoomAnim event is not being fired after the map has loaded, and an area is being zoomed to using leaflet-control-boxzoom...

Even if an area is scroll-zoomed to, then BoxZoomed, the zoomAnim event is not fired for the BoxZoom zoom.

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by scgrant327** [comment]
My apologies, I am unable to create a test at this time, as it would require tons of retyping/manual copying from a  non-connected system.

Basically, adding in the BoxZoom control to an existing LeafLet map causes this behavior. This happens on the FIRST time the BoxZoom is used.

**Comment by perliedman** [comment]
@scgrant327 when you say "BoxZoom control", do you mean the built-in box zoom that is enabled by holding down Shift and dragging a rectangle on the map, or are you using a plugin control?

If this is a behaviour you're seeing in a plugin, you should file an issue with that plugin instead.

**Comment by scgrant327** [comment]
Yeah, it's a plugin:
https://github.com/gregallensworth/L.Control.BoxZoom

I'll post an issue to GitHub and update here when I get a response.

**Comment by perliedman** [comment]
Ok, closing for now.
