### ISSUE TITLE
bindPopup not working with GeoJSON multipolygon

### ISSUE THREAD

**Issue by brambow** [Leaflet/Leaflet#5367]
Leaflet v 1.0.3

bindPopup() doesn't appear to be working properly with GeoJSON.  In my particular case, my GeoJSON is a Multipolygon, but I'm not sure that makes a difference.

Here's my code:

```
regionsGeojson = L.geoJson(geojsonObj, {
          onEachFeature: function(feature,layer) {
            layer.bindPopup(feature.properties.region_name);
          },
          style: {
            color: '#000096',
            weight: 1,
          }
        })
        .addTo(map)
          .on('load', function () {
          map.fitBounds(regionsGeojson.getBounds());
 });
```

In the browser console, I can see the popup is getting properly generated, but when I move the mouse over the feature and click nothing happens.

When I revert to 0.7.5 the popup works as expected.

**Comment by perliedman** [comment]
Hi,
I tried reproducing this with your code, and it seems to work as expected: http://playground-leaflet.rhcloud.com/woku/edit?html,output

Please provide an example reproducing the problem you're seeing if you believe this is a problem with Leaflet, and I'll re-open.
