### ISSUE TITLE
Broken links in WMS tutorial 

### ISSUE THREAD

**Issue by MikiDi** [Leaflet/Leaflet#5368]
Hi,

I wanted to let you know that the WMS-server ('http://demo.opengeo.org') used in the [WMS tutorial](http://leafletjs.com/examples/wms/wms.html) seems to be no longer available.

for reference: PR introducing WMS tutorial: #4349

Michaël

**Comment by IvanSanchez** [comment]
This requires changing `http://demo.opengeo.org/geoserver/ows?` into `http://suite.opengeo.org/geoserver/ows?`, and updating the WMS layer names and screenshots.

**Comment by IvanSanchez** [comment]
According to some people at Boundless, it seems that it's a temporary failure and the demo server should be back up soon. Let's wait on this a few days, hope it fixes itself.

**Comment by MikiDi** [comment]
Everything seems to be working as supposed now (fixed itself) :-)
