### ISSUE TITLE
CSS scale map div

### ISSUE THREAD

**Issue by Hyno** [Leaflet/Leaflet#5370]
When using css transform: scale(x) to make sure the same part of the map is always shown, no matter what the size is, it brings a problem. When zooming in for example, the map does not zoom in at the point you were zooming. Also if a marker is placed on a certain latlng, after zooming the markers' position changes. Is there a way to get around this issue, or is it a bug?

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by danzel** [comment]
This is what they mean at a guess:
https://playground-leaflet.rhcloud.com/xirum/edit?html,output
I just added `transform: scale(2);` to the map styles.

Dupe #2795

**Comment by IvanSanchez** [comment]
Duplicate, closing in favour of #2795
