### ISSUE TITLE
Debug examples do not work post-Rollup

### ISSUE THREAD

**Issue by hyperknot** [Leaflet/Leaflet#5373]
The debug examples do not work post-Rollup release.

Some problems:

1. They are looking for `../../build/deps.js` but this file is no longer present.
2. They are looking for `../leaflet-include.js`, which is a symlink to 

```
leaflet-include.js -> leaflet-rollup-src.js
```

where `leaflet-rollup-src.js` is not present.

3. There is an example `map/rollup.html`, which I thought demonstrates the usage, but is also linking to the non-existent `leaflet-rollup-src.js`.

**Comment by cherniavskii** [comment]
I have the same problem, deps.js doesn't exist, so examples in /debug folder are not working

**Comment by IvanSanchez** [comment]
OK, then somebody please grep those files and remove the references to `deps.js`.

**Comment by hyperknot** [comment]
@IvanSanchez I'm happy to do all the fixes. Can you make one example (like map.html) the way it's supposed to be? It's not clear to me how it should work, with `leaflet-rollup-src.js` not present.

**Comment by IvanSanchez** [comment]
@hyperknot See https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md#using-rollupjs - if you run `npm run-script watch`, you'll find `leaflet-rollup-src.js` in the right place.

**Comment by hyperknot** [comment]
@IvanSanchez thanks, then the problem is that `rollup` or `build` does not create that file, only `watch` does. The docs mention "rollup or watch", and I totally believe we should create that file upon `rollup`. I think watch shouldn't be needed for simply opening an html file.

**Comment by hyperknot** [comment]
As I see the watch config is almost the same as the build one. Can we just use `dist/leaflet-src.js` in examples instead?

**Comment by mourner** [comment]
One note is I think we should rename `debug/leaflet-rollup-src` to `dist/leaflet-src.js` to be consistent with the `build` script. **update** @hyperknot beat me to it.

**Comment by IvanSanchez** [comment]
@hyperknot Please feel free to tinker with the build scripts. The one thing I wanted to care about in the `watch` builds is to add a timestamp, to let the developer know that the bundle might be old.

Maybe you want to experiment with something more refined, like loading a small JS file that appends a `<script>` pointing to `dist/leaflet-src.js` and managing the timestamps. I'm very open to suggestions or new ways to do the debug builds.

**Comment by mourner** [comment]
@IvanSanchez I don't think we should overcomplicate this. Never cared about build timestamps in all my projects and it all worked fine.
