### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'fn' of undefined" when add/remove layer

### ISSUE THREAD

**Issue by kolesoffac** [Leaflet/Leaflet#5375]
![bug-with_fire](https://cloud.githubusercontent.com/assets/11459507/23656069/35a593a2-0349-11e7-8c6a-4627e02697fd.png)

Here len > listeners.length because l = undefined.

Why so?

Leaflet v1.0.3

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by kolesoffac** [comment]
I have difficulty reproduce error without my self data, but the essence of rewriting len.

**Comment by IvanSanchez** [comment]
Then, I'm closing this because there is no reproducible case. I'll reopen if a reproducible case is provided.

**Comment by perliedman** [comment]
I think I've encountered this when migrating applications from Leaflet 0.7 to 1.0. The solution has always been making sure layers do not extend `L.Class` (which was fine in 0.7), but inherit from `L.Layer` instead.
