### ISSUE TITLE
Draw parallel lines inside polygon using Leaflet

### ISSUE THREAD

**Issue by marie15** [Leaflet/Leaflet#5377]
I want to add parallel lines to map inside a polygon, for now I can add one parallel line. How Can I iterate throught length of polygon to add this lines inside it. the screenshot of desird result is below. Any help is much appreciated. Thank you.

![paralell_lines](https://cloud.githubusercontent.com/assets/14139375/23698363/2fd5cf74-03e3-11e7-8ec2-64a3dbc5c587.JPG)

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
