### ISSUE TITLE
Mobile Code not working when other layers are added?

### ISSUE THREAD

**Issue by PushingFoward** [Leaflet/Leaflet#5382]
var map = L.map('map').fitWorld();

    var baselayer = L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
    maxZoom: 18,
    attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
    }).addTo(map);
	var layer = L.layerGroup(markers).addto(map);
	var markers = L.marker([41.8781,87.6298])
		var markers = L.markerClusterGroup({ animateAddingMarkers : true });
	function onLocationFound(e) {
    	var radius = e.accuracy / 2;
    	var marker = L.marker(e.latlng).addTo(map)
        .bindPopup("You are within " + radius + " meters from this point").openPopup();
    	L.circle(e.latlng, radius).addTo(map);
}
    	function onLocationError(e) {
    	alert(e.message);
}
    	map.on('locationfound',onLocationFound);
   		map.on('locationerror', onLocationError);
map.locate({setView: true, maxZoom: 16});

**Comment by perliedman** [comment]
Please clarify what the actual problem you're seeing here is.

What is "mobile code", and what's not working?

**Comment by IvanSanchez** [comment]
Hi, I'm closing this issue because the quality is not good enough. I suggest reading ["How To Ask Questions The Smart Way"](http://www.catb.org/esr/faqs/smart-questions.html) and ["How to Report Bugs Effectively"](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) so you can make good bug reports.
