### ISSUE TITLE
Calculate altitude using Leaflet

### ISSUE THREAD

**Issue by marie15** [Leaflet/Leaflet#5383]
Hi, I want to calculate altitude of a marker but I didn't find any solution in Leaflet. Do you have idea how to do that? Thank you.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
