### ISSUE TITLE
Load new map layer

### ISSUE THREAD

**Issue by thomashrabe** [Leaflet/Leaflet#5388]
I am trying to change the map type on user selection.

Here's my code (it's Typescript in Ionic2 parsed to JS):

```
LeafletView.prototype.changeMap = function (mapURLs) {
            for (var _i = 0, _a = this._currentMapLayers; _i < _a.length; _i++) {
                var currentLayer = _a[_i];
                this._map.removeLayer(currentLayer);
            }
            this._currentMapLayers = [];
            for (var url in mapURLs) {
                var newLayer = __WEBPACK_IMPORTED_MODULE_2_leaflet__["tileLayer"](url);
                this._map.addLayer(newLayer);
                this._currentMapLayers.push(newLayer);
            }
        };
```

After running this function, the map is empty / gray. I tried refreshing the map within the code `this._map._onResize();` but that didn't help...

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
