### ISSUE TITLE
WKWebView performance degradation and out of sync issue

### ISSUE THREAD

**Issue by ThorConzales** [Leaflet/Leaflet#5389]
I have an Ionic 2 (Cordova based) app and I'm using Leaflet in it. I recently upgraded from UIWebView to WKWebView and I noticed that when the map has lots of (100+) markers on it then pinch-zoom performance was much worse than before with the UIWebView. With only few markers on the map it worked perfectly as before. I also noticed that quite occasionally the map bugged out, basically map zoom level and marker layer zoom levels managed to get out of sync when pinch-zoom gesture was performed rapidly. Zooming using controls worked as expected. So I figured that with the WKWebView it must be using some newer technologies that is not available in UIWebView and that something new does not play well with WKWebView. So I tried out disabling hardware accelerated 3D CSS transformations and it helped. After disabling acceleration it performed the same way as in UIWebView and didn't bug out any more. So it's not a real issue for me since I can continue using it without the hardware acceleration on iOS but just letting you know that WKWebView does not play well with hardware acceleration and lots of markers.

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.
