### ISSUE TITLE
marker dblclick event fails to fire

### ISSUE THREAD

**Issue by azyth** [Leaflet/Leaflet#5391]
- Leaflet: leaflet@1.0.3 
- Browser : Chrome Version 56.0.2924.87 (64-bit)
- OS/Platform (with version) I'm using: Ubuntu 16.04 LTS
         Ionic 2 android application run in Chrome with `ionic serve`

Issue:
I have an event bound to my markers and wish it to fire on "dblclick" event listed as an [option](http://leafletjs.com/reference.html#marker-dblclick). It fails. If i change the "dblclick" =>"click" it fires.

typescript: 
```typescript 
var marker = L.marker([+lat,+lon],{
          icon: this.selIcon,
          title: e.serial_number,
          clickable: false
        });
        marker.on("dblclick", (event)=>{//FIXME "dblclick" =>"click" works
          console.log ("doubleclick");
          this.toggleSelectedEgg(e);
        });
      marker.addTo(this.markers);
```
This appears to be a bug to me with the event not being recognized. I have reviewed the documentation and do not find anything indicating you must do something different for a non-single-click event. 

Thanks

**Comment by perliedman** [comment]
Hi there,
I tried to reproduce this with the code you supplied, but it works as expected: http://playground-leaflet.rhcloud.com/zeke/edit?html,output

Please try to provide an example that shows the problem.

**Comment by perliedman** [comment]
Closing for now, happy to re-open when we get more information on the issue!
