### ISSUE TITLE
Option to disable autozoom on Layer by minZoom 

### ISSUE THREAD

**Issue by genofire** [Leaflet/Leaflet#5393]
## How to reproduce

Platform:
- Leaflet version I'm using: v1.0.3
- Browser (with version) I'm using: Chrome
- OS/Platform (with version) I'm using: Linux

Reproduce:
- create a Layer and add `minZoom` as option.
- switch the baselayer 
- map change zooming to `minZoom` of layer

## What behaviour I'm expecting and which behaviour I'm seeing
- create a Layer and add `minZoom` as option.
- switch the baselayer 
- keep current zooming

I would like to have a option during creating a Layer
to switch off this auto zooming.
I only want use `minZoom` to disable the showing for clearness reason of this Layer.

dependent lines:
https://github.com/Leaflet/Leaflet/blob/v1.0.3/src/layer/Layer.js#L268 

## Minimal example reproducing the issue

We got this problem on https://github.com/ffrgb/meshviewer/pull/85 and thinking about the parameter
 `ownMinZoom` and disable the rendering on the layer.
Or overwrite `beforeAdd` with a empty function.

**Comment by IvanSanchez** [comment]
Sounds like you should be using the map's `minZoom` option instead (or in addition to) the layer's `minZoom` option.

As you map has no explicit `minZoom`, switching layers with a `minZoom` option will update the map's `minZoom`. This is behaviour as expected.

**Comment by genofire** [comment]
we done it already,  sry  i have not closed this issue
