### ISSUE TITLE
Zoom control and paddingTopLeft sidebar

### ISSUE THREAD

**Issue by xf-** [Leaflet/Leaflet#5395]
## How to reproduce

- Leaflet version I'm using: 1.0.3
- Browser (with version) I'm using:  Firefox 55.0a1 (2017-03-13) (64-bit)
- OS/Platform (with version) I'm using: Linux
- step 1 Add a fitBounds with paddingTopLeft
- step 2 Use zoom control (key or button)

## What behaviour I'm expecting and which behaviour I'm seeing
Zooming is not in middle of fitfounds and no option to add a padding for zooming. I expect the map correctly configured to zoom in middle of the visible area.

## Minimal example reproducing the issue

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

http://playground-leaflet.rhcloud.com/yaz/edit?html,output

**Comment by IvanSanchez** [comment]
`fitBounds` performs one zoom operation, it does not modify the behaviour of later zoom operations. This is behaviour as expected right now.

For the looks of it, seems that you need the leaflet-active-area plugin, or one similar to it.
