### ISSUE TITLE
Map.flyTo does not respect Pan options noMoveStart

### ISSUE THREAD

**Issue by smremde** [Leaflet/Leaflet#5396]
Map.flyTo does not respect Pan options noMoveStart

```
map.on('movestart', function () { console.log('should not be called') })
map.flyTo([1,1],16, {noStartMove: true})
```

when map is valid, console the event will be triggered and log to the console.

https://github.com/Leaflet/Leaflet/blob/b997839fe73397330c292dcac1e5a65cb3ea8fdb/src/map/Map.js#L417 is the offending line, should check the options first.

**Comment by xsanda** [comment]
The same issue occurs with Map.panTo, when no animation is set, with the offending line: https://github.com/Leaflet/Leaflet/blob/b997839fe73397330c292dcac1e5a65cb3ea8fdb/src/map/Map.js#L200

**Comment by dimkirt** [comment]
I tried to recreate your issue and it seems you got wrong your options object
[Link to Docs](http://leafletjs.com/reference-1.0.0.html#pan-options-nomovestart)

This should work:
`map.flyTo([1,1],16, {noMoveStart: true})`

**Comment by mfainshtein2** [comment]
Hello, I am new. I would like to know if this is still an ongoing issue.

**Comment by bringking** [comment]
I am seeing this on `setView` as well. It does not respect `noMoveStart` with version 1.3.4

**Comment by Chivano** [comment]
#6685 i posted a PR for the problem with Map.panTo not respecting the option "noStartMove". The panTo function uses setView so it will hopefully solve @bringkings comment aswell.

**Comment by fiatlucy** [comment]
> Hello, I am new. I would like to know if this is still an ongoing issue.

Same! Is this something I can take a stabbing effort at?

**Comment by dnasir** [comment]
Any progress on this?

**Comment by aniss** [comment]
This should be fixed!
