### ISSUE TITLE
Error when adding paths in groups before map view has been set

### ISSUE THREAD

**Issue by mishal153** [Leaflet/Leaflet#5401]
## How to reproduce

- Leaflet version I'm using: 1.0.3
- Browser (with version) I'm using: chrome
- OS/Platform (with version) I'm using: windows 8.1
step1: Create new map with a tile layer 
step2: create a  feature group
step3: Create and add one circle to the feature group and add feature group to map.
step4: Create another circle and add directly to map.
step5: Call map.setview()
All options are default.

## What behaviour I'm expecting and which behaviour I'm seeing
exception 'Cannot read property 'intersects' of undefined' in Circlemarker._empty
Circles don't get drawn

## Minimal example reproducing the issue
http://playground-leaflet.rhcloud.com/qiy/edit?html,console,output
- [x ] this example is as simple as possible
- [ x] this example does not rely on any third party code

I am debugging the issue for better understanding and will add comments if I can put my finger on something

Update1: The issue doesn't happen if map.setView() is invoked with just the tile layer and other layers get added afterwards.

**Comment by IvanSanchez** [comment]
At first sight this seems to be a race condition in the renderers, which don't populate the private `_bounds` property until *after* the first `update()` has run entirely. A simple sanity check should fix this.

**Comment by IvanSanchez** [comment]
Hhhhhmmmm. It seems that we changed something between 1.0.3 and `master`, and the symptoms are different (undefined `_rootGroup` at `L.SVG._addPath`)
