### ISSUE TITLE
Error on server side prerendering using leaflet (Window undefined)

### ISSUE THREAD

**Issue by ste4net** [Leaflet/Leaflet#5402]
## How to reproduce

- Leaflet version I'm using: 1.0.3
- Browser (with version) I'm using: Chrome
- OS/Platform (with version) I'm using: Angular2 + webpack + server side prerendering with angular2-universal
- Just trying to import 'leaflet' in a component crash the pre-rendering process.

## What behaviour I'm expecting and which behaviour I'm seeing
I expect to have no crash during pre-compilation neither if window does not exist serverside. I have the error just adding the import sentence because it is no checked if window (or document) is undefined.

## Other info.
I am trying with this workaround applied to leaflet-src.js and i have no more error during pre rendering compilation. 

**Line 29 (add check)**
``
if(window === null) return null;
``

**Line 13250**
**from:**
``}(window, document));``
**to:**
``
}(typeof window !== 'undefined' ? window : null, typeof document !== 'undefined' ? document : null));
``

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.

**Comment by ayyash** [comment]
it's weird, because I do exclude the maps on ssr environment, yet the ssr produced, the window.requestAnimationFrame is reached in nodejs, how? looks like there is code running the minute an import is requested... it should wait until code initiates a setup explicitly may be?
