### ISSUE TITLE
Map.flyToBounds does not rerender geojson layers until animation end

### ISSUE THREAD

**Issue by mmoutenot** [Leaflet/Leaflet#5403]
## How to reproduce

- Leaflet version I'm using: 1.0.0
- Browser (with version) I'm using: Chrome 56.0.2924.87
- OS/Platform (with version) I'm using: OSX 10.12

- Render a map with a GeoJSON layer
- `flyToBounds`of that layer with a far out starting zoom.

## What behaviour I'm expecting and which behaviour I'm seeing
- As zoom occurs, the background map tiles are recalculated and loaded as the zoom occurs. I expect the same to happen to the geojson. It looks like those polygons are simplified to display when zoomed way out, but they are not rerendered until the zoom finishes.

![mar-22-2017 09-35-25](https://cloud.githubusercontent.com/assets/339996/24200693/4531781c-0ee4-11e7-822b-97ca6fcc6208.gif)

## Minimal example reproducing the issue

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

http://jsfiddle.net/jsanz/Pe5xU/

**Comment by IvanSanchez** [comment]
No, vector layers are only re-rendered on `zoomend`, *by design*, to prevent slowdowns. No way around this.

Do have a look at https://github.com/Leaflet/Leaflet.VectorGrid/ , though.

**Comment by mmoutenot** [comment]
Okay, thanks for passing along. A good UX workaround for now is to hide the geojson layer at start of fly, and on zoomend. Thanks Ivan.
