### ISSUE TITLE
Render L.Control with Canvas?

### ISSUE THREAD

**Issue by pedrovsra** [Leaflet/Leaflet#5409]
Hey guys, a little help needed here. I don't even know if this is a real issue, so my apologies in that case.

I'm with a demand to export a map in a image file and I'm using this plugin: http://mapbox.github.io/leaflet-image/

The thing is, while it's easy to save my layers (using L.featureGroup), since they can be rendered with Canvas with a single option on map creation (preferCanvas: true), I can't save my legend for the map (created using L.Control with a custom html template).

I wonder if its possible to render my L.Control layers with Canvas, of if you guys have other ways to do what I'm trying.

Thanks by now,

Pedro

**Comment by IvanSanchez** [comment]
No, this should be a bug report in https://github.com/mapbox/leaflet-image instead. You want leaflet-image to handle `L.Control`s, and that is out of the scope of the core leaflet repo.

And, quoting their docs:

> This library does not rasterize HTML because browsers cannot rasterize HTML. Therefore, L.divIcon and other HTML-based features of a map, like zoom controls or legends, are not included in the output, because they are HTML.
