### ISSUE TITLE
Leaflet 1.0.3 and Polymer 2. Tiles rendering issue

### ISSUE THREAD

**Issue by hpenav** [Leaflet/Leaflet#5413]
## How to reproduce

- Leaflet version I'm using:
- Browser (with version) I'm using:
- OS/Platform (with version) I'm using:
- step 1
- step 2

## Minimal example reproducing the issue

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

Using http://playground-leaflet.rhcloud.com/ or any other jsfiddle-like site.

**Comment by hpenav** [comment]
Hi, I am trying to integrate leaflet with Polymer 2. The issue I am having is that map tiles are not rendering correctly and the map is not contained in the div container. I was trying to use leaflet-map but it was for Polymer 1.x so it is not compatible with Polymer2 . The leaflet version I am using is 1.0.3 Let me know if you need more iformation
![image](https://cloud.githubusercontent.com/assets/15762503/24343052/9fa1ba96-1281-11e7-8289-48899bc6862e.png)

![image](https://cloud.githubusercontent.com/assets/15762503/24343089/dbfbddfa-1281-11e7-8009-42cd1e693352.png)

**Comment by hpenav** [comment]
Hi,
Checking the leaflet-map code, I realized that the issue was related to css not included in shadow dom. So I am closing this ticket

Thanks

**Comment by zhen1991** [comment]
Hi,
please i want to know if didi u solve  this problem??

**Comment by zhen1991** [comment]
and what did you do??

**Comment by zhen1991** [comment]
Hi!
did you fix the map is it working now ??
i think is it working on firefox and IE but not in chrome!
thnx for helping:)

**Comment by JoceM** [comment]
I am having the same problem. In Chrome, tiles are only partially rendered. Has anyone found a solution to this ?
![capture](https://user-images.githubusercontent.com/7259387/38688658-f15e6da0-3e79-11e8-81e4-a257da2fe6c2.JPG)

**Comment by zhen1991** [comment]
Hi!
i fix mine in polymer by writing the style tag inside the <dom-module id="my-view1"> tag !
and it should be fix !
i hope i helped you:)

**Comment by JoceM** [comment]
Hi zhen1991
I tried what you said, but I get the same issue. Do you mind sharing some code (or print screen) so that I can see how you did it ?

**Comment by JoceM** [comment]
I solved my issue by lazy-loading the leaflet element on the main page.

**Comment by shibasish** [comment]
> Hi,
> Checking the leaflet-map code, I realized that the issue was related to css not included in shadow dom. So I am closing this ticket
> 
> Thanks

Hey, for me CSS is included in the shadow dom. But it's still not working. The full description of the issue is in [SO](https://stackoverflow.com/questions/53872322/leaflet-polymer-2-map-loading-with-distorted-tile-however-works-with-non-polym). I am using Polymer 2 with leaflet v1.3.4. Can there be any version support issue?
Also, would appreciate if you could have a look. 
Thanks.
