### ISSUE TITLE
leaflet centres the map not correct round the markers

### ISSUE THREAD

**Issue by Joppla** [Leaflet/Leaflet#5419]
## How to reproduce
Since I updated from leaflet 0.7.3 to 1.0.3. I have a problem with centring the map round the markers. 
![screenshot - 28-03-17 - 11 09 17](https://cloud.githubusercontent.com/assets/25467829/24406928/e3599044-13c9-11e7-8b53-13dfecbc0b34.png)

Only after resizing the windowbrowser the map is shown correct.

In leaflet 0.7.3 there isn't a problem.

Additional information:
http://stackoverflow.com/questions/43065090/leaflet-map-does-not-centre-correct/43068409?noredirect=1#comment73223830_43068409
http://stackoverflow.com/questions/36246815/data-toggle-tab-does-not-download-leaflet-map

- Leaflet version I'm using: leaflet 1.0.3
- Browser (with version) I'm using: firefox and chrome
- OS/Platform (with version) I'm using: xubuntu 14.04
- step 1
- step 2

## Minimal example reproducing the issue

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

Using http://playground-leaflet.rhcloud.com/ or any other jsfiddle-like site.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by Joppla** [comment]
Hi Ivan,
Indeed leaflet is very nice. 
What I understand from my discussion on SO between leaflet 0.7.3 and 1.0.3 there is something changed in leaflet with "handling of the container" that I have now anywhere a bug. In my opinion - because the other part - webtrees 1.7.9 - is still the same, the bug is in leaflet. That's why I reported it here.

**Comment by IvanSanchez** [comment]
Can you post a minimal reproducible example which fails with 1.0.x but works with 0.7.x?

**Comment by Joppla** [comment]
Hi Ivan,
That is a bit difficult, because for that you need to have also webtrees. Or do you want to test it in webtrees?

**Comment by IvanSanchez** [comment]
What is "webtrees"?

**Comment by Joppla** [comment]
webtrees is genealogical webbased software :) [webtrees.net](http://webtrees.net)

**Comment by IvanSanchez** [comment]
Then this falls under the standard "no frameworks" blanket response.

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.

**Comment by Joppla** [comment]
Hi, that was a standard answer, I'm sure that you are not able to type so fast :-) 

I will made a report at webtrees.
