### ISSUE TITLE
mapbox GL JS V0.32.1 Marker's popup wont work on IOS 

### ISSUE THREAD

**Issue by sasidharlanka** [Leaflet/Leaflet#5420]
Hi All, I am using mapbox GL JS V0.32.1. I have developed an ionic app. The Markers Works fine in android as well as in safari. The same wont work on simulated or on iPhone  device, it doesn't work.

Please look into the issue and help me resolve it.

**Comment by IvanSanchez** [comment]
This is the repo for Leaflet, not the repo for mapbox-gl-js.
