### ISSUE TITLE
L.control.layers don't fire "baselayerchange, overlayadd, overlayremove" events after setPosition()

### ISSUE THREAD

**Issue by siimots** [Leaflet/Leaflet#5421]
## Setup
- Leaflet version I'm using: Leaflet 1.0.3
- Browser (with version) I'm using: latest Chrome, Firefox
- OS/Platform (with version) I'm using: macOS Sierra
- Open: https://playground-leaflet.rhcloud.com/yame/1/edit?html,output

## How to reproduce
1. Change layers -> events are fired and logged 🆗
2. Click "change pos" button `layerControl.setPosition('bottomright') `-> layercontrol is moved to bottom-right. 🆗
3. Change layers -> events don't fire anymore and aren't logged ⛔

## URL
https://playground-leaflet.rhcloud.com/yame/1/edit?html,output

**Comment by IvanSanchez** [comment]
Can reproduce. This deserves a good look.

**Comment by danzel** [comment]
I'll take a look

**Comment by danzel** [comment]
In `Control.Layer.onRemove` we remove the event listeners from the layers:
https://github.com/Leaflet/Leaflet/blob/master/src/control/Control.Layers.js#L115-L117
But we don't add them again in onAdd.

I think we just need to add them in onAdd.... fiddling...

**Comment by danzel** [comment]
Introduced in #4214 / #4213. Will update the tests, pretty certain it is still bugged a bit atm.

**Comment by danzel** [comment]
See #5422
