### ISSUE TITLE
a coding problem in the file of /src/control/Control.js?

### ISSUE THREAD

**Issue by gongwg** [Leaflet/Leaflet#5427]
In the file /src/control/Control.js, there may be a coding problem in the function of setPosition. In this function, I find there is a segment of code below:

		if (map) {
			map.removeControl(this);
		}

		this.options.position = position;

		if (map) {
			map.addControl(this);
		}

It first references the "removeControl" property of "map" object, which indicates that "map" must not be NULL. However, in the below code, the if statement's condition contains "map" again, which checks wether the "map" is NULL or not. I think this operation may be redundant logically and this segment of code could be rewrote as below to be more logical:
 
                if (map) {
                        map.removeControl(this);
                        this.options.position = position;
                        map.addControl(this);
                } else {
                        this.options.position = position;
                }

**Comment by IvanSanchez** [comment]
I don't think refactoring that tiny bit of code offers any tangible benefit.
