### ISSUE TITLE
Weird grey gaps on my leaflet maps

### ISSUE THREAD

**Issue by ZihengSun** [Leaflet/Leaflet#5429]
I created a tab container with two tabs. I want a Leaflet Map shows when I activate tab #2. I can see the map pops up but with very weird grey gaps like this:

![image](https://cloud.githubusercontent.com/assets/17322987/24554565/129907f2-15fc-11e7-94c2-eaa36c54cae8.png)

- Leaflet version I'm using: Leaflet 1.0.3
- Browser (with version) I'm using: Google 57.0.2987.110 (64-bit)
- OS/Platform (with version) I'm using: Win7

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

I suspect you have some kind of margin in the CSS rules for your images.

**Comment by ZihengSun** [comment]
I create a fiddle with different version of code and the problem cannot be reproduced. Have no idea. 
https://jsfiddle.net/ehw725pr/1/
I avoid this problem by using setTimeout to let the DOM have more time to stablize.
