### ISSUE TITLE
I find a coding contradiction problem in the file of Leaflet-1.0.3/dist/leaflet-src.js.

### ISSUE THREAD

**Issue by qjas** [Leaflet/Leaflet#5434]
In the function L.DomUtil.preventOutline, I find there may be a coding contradiction in the codes below:

    while (element.tabIndex === -1) {
      element = element.parentNode;
    }
    if (!element || !element.style) { return; }

The codes first execute "element.tabIndex"(show that element is not NULL), then execute "!element" in the condition of if stmt(check whether the element is NULL or not). It is a contradiction. 
I think since the element must not be NULL(otherwise the execution of  "element.tabIndex" would be wrong) when the while stmt finishes, the next if stmt doesn't need to check the element like "!element" again. Checking the element.style is already enough:)

**Comment by IvanSanchez** [comment]
Care to send a pull request to fix it by removing the check? The source code for that is in `/src/dom/DomUtil.js`.

**Comment by qjas** [comment]
@IvanSanchez 
I am glad to do this of course:)  
I have send the pull request in https://github.com/Leaflet/Leaflet/pull/5435/commits/87c123a58a32c0168e164b2c53e213f69bdc2089

**Comment by IvanSanchez** [comment]
Looks good, thanks!

By the way, if you had written something like "fixes #5434" in the PR, that tells github to link the PR with this bug, and the bug closes automatically. There are a few tricks like that that save some time :-)

**Comment by IvanSanchez** [comment]
Closed by #5435

**Comment by qjas** [comment]
Oops, I am not familiar with PR before really. Thanks for your advice!

**Comment by IvanSanchez** [comment]
As [xkcd says](https://www.xkcd.com/1053/):

![](https://imgs.xkcd.com/comics/ten_thousand.png)
