### ISSUE TITLE
Associating error data to tileerror object

### ISSUE THREAD

**Issue by albanm** [Leaflet/Leaflet#5437]
## How to reproduce

- Leaflet version I'm using: 1.0.2
- Browser (with version) I'm using: not relevant
- OS/Platform (with version) I'm using: not relevant
- Add a TileLayer instance to a map pointing to a custom tile server
- Have this tile server serve HTTP errors

## What behaviour I'm expecting and which behaviour I'm seeing

I expect to get some useful information associated to a tileerror event. I want for example to be able to distinguish 404, 429 and 500 errors to trigger the matching display to my users.

This bit of code https://github.com/Leaflet/Leaflet/blob/v0.7.3/src/layer/tile/TileLayer.js#L578 seems to indicate that nothing at all is kept from the error.

## Minimal example reproducing the issue

I don't have a public server that responds with some errors.

**Comment by IvanSanchez** [comment]
Please do not point to the source code of the 0.7.3 release. Point to the [current source code instead](https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/TileLayer.js#L132).

Leaflet detects tile load errors by listening to the [DOM `error` event](https://developer.mozilla.org/en-US/docs/Web/Events/error) on the instance of [`HTMLImageElement`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement) which failed to load. That instance of `ErrorEvent` gets passed to whatever error handler you configure via `tilelayer.on('tileerror', handler);`.

Note that, at this stage, the web browser is **not** assuming HTTP (nor HTTPS) transport for the images. The image might come from http(s), from a `blob:`, from some localstorage, dumped from an offscreen `<canvas>`, from your local filesystem, from an ftp server, or for what I care it might even come from gopher.

*If* you want to access the [DOM `error` event](https://developer.mozilla.org/en-US/docs/Web/Events/error) that Leaflet 1.0.x piggybacks, check its target `<img>`, check its `src` attribute, check if that fits a http URL, then (re)try loading that URL and check the specific error, be our guest. But adding all that in the Leaflet core won't be that useful.

**Comment by albanm** [comment]
Ok, that's fair. Thanks for the quick reply !

**Comment by IvanSanchez** [comment]
No prob. I know it's a reasonable request, but the architecture and the way browsers work mean it's next to impossible.
