### ISSUE TITLE
leaflet.css in CDN, It is down.

### ISSUE THREAD

**Issue by ky0ncheng** [Leaflet/Leaflet#5439]
http://cdn.leafletjs.com/leaflet-0.7.7/leaflet.css

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>B6F496C33E11CA74</RequestId>
<HostId>
+ejry8DDWuEySxUW09Esmm4YgJEms4DNoF9ebvteHxdKx1JNVSv5OHoYnCSo6L5lpi1tp5rgT74=
</HostId>
</Error>

**Comment by IvanSanchez** [comment]
We recommend `unpkg` as a CDN now. See https://unpkg.com/leaflet@0.7.7/ and https://unpkg.com/leaflet@1.0.3/
