### ISSUE TITLE
option "interactive": changing value has no effect

### ISSUE THREAD

**Issue by ppete2** [Leaflet/Leaflet#5441]
Please have a look at: [https://ppete2.github.io/Leaflet.PolylineMeasure/demo_metric.html](https://ppete2.github.io/Leaflet.PolylineMeasure/demo_metric.html)
If you click on the left "Polyline Measure" control you can draw+measure a Polyline. After finish to draw a polyline (by doubleclicking on last point or pressing "ESC"-key) the last point colors red.

During drawing each of the circle markers was created with option **"interactive: true"**. After finish of drawing line each of the circle markers should become **non-interactive**. There i set the marker's options to  **"interactive: false"**. But this has no effect. The mouse cursor still changes into a hand-icon if hovering the green or any black dot. Just the red dot is non-interactive because it was drawn already during instantiation with option "interactive: false"

**Comment by perliedman** [comment]
Hi there,
unfortunately, there's no way for Leaflet to know that you've updated the options, so it will not magically understand that the layer is no longer interactive. This applies to most options, just changing them will not automatically trigger Leaflet to do something. For some options it can _appear_ to work, but only when Leaflet actively reads the option's current value.

Also, there is currently no way to alter the `interactive` state of an `InteractiveLayer`.

Your best bet is to re-create the markers with `interactive: false` once you know they should no longer be interactive. (An idea in this particular case would be to remove the markers altogether once they're not interactive, to make it very clear the line can no longer be edited, but just my opinion.)

**Comment by perliedman** [comment]
I added a feature suggestion in #5442 that would improve this.

**Comment by ppete2** [comment]
Hi Per! I think I'm indeed using your sugestion to re-create the markers with interactive: false

The markers are still needed after drawing to see the intermediant points of the Polyline (imagine a Polyline consist of 2 sectors which have exact the same direction, eg. from North to South. Without the black dot we wouldn't see where exaclty the 1st sector ends and 2nd sector starts).

Just as an idea: Without re-creating the markers: Would it be possible to deactivate the change of the cursor icon, for example by altering the CSS-"cursor" property of the DOM-Elements of the black dots?

**Comment by perliedman** [comment]
@ppete2 ok, good to hear you have a reasonable way forward here! 

Yes, it should be possible to change the cursor using CSS; accessing the underlying SVG element can be done through the private (undocumented) property `_path` on your `LineString`.
