### ISSUE TITLE
Remove Start and End location from Routing control

### ISSUE THREAD

**Issue by weetrax** [Leaflet/Leaflet#5443]
Hello, I wanted to know how to remove these two input and just not disabled it:

![capture](https://cloud.githubusercontent.com/assets/17180151/24852877/5f682cc2-1dd9-11e7-90f3-f2f570871e54.PNG)

Thanks in advance.
Stefano

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by perliedman** [comment]
@weetrax additionally, it looks like you're asking about Leaflet Routing Machine (a plugin to Leaflet), not Leaflet itself.

If you remove the `geocoder` option, the inputs will go away.

**Comment by weetrax** [comment]
When i remove the geocoder option it remove also the reverse route button. I want to keep it.
Is it possible ?

**Comment by perliedman** [comment]
@weetrax as @IvanSanchez mentioned, this is not a question forum, please don't reply to this thread, bring it up in the right place.
