### ISSUE TITLE
L.Mixin.Events has a 'constructor' property

### ISSUE THREAD

**Issue by luiscamachopt** [Leaflet/Leaflet#5451]
Since https://github.com/Leaflet/Leaflet/issues/2280 L.Mixin.Events now includes a constructor property. 
This means that if I use:
`myChildClass = L.Control.extend({includes: L.Mixin.Events});`
then 
`myChildClass.prototype.constructor` is (unexpectedly) `L.Evented`

http://playground-leaflet.rhcloud.com/juw/edit?html,console,output

**Comment by perliedman** [comment]
For context, see discussion here: https://github.com/Leaflet/Leaflet/issues/2280#issuecomment-285310903
