### ISSUE TITLE
How to know point for marker if know start and end position, start time and speed?

### ISSUE THREAD

**Issue by stojankukrika** [Leaflet/Leaflet#5458]
How to know point for marker if know start and end position, start time and speed?
start possition is sl_lat:"18.8782296", sl_long:"79.4623518", finish possition is fl_lat:"28.5748740", fl_long:"77.2558594", speed: 10km/h, start time: 10:00AM, now time is: 15:00h
How to know where is the object on map?

**Comment by danzel** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
