### ISSUE TITLE
photo contains non-free color calibration profile

### ISSUE THREAD

**Issue by jonassmedegaard** [Leaflet/Leaflet#5460]
Hi,

The photo docs/docs/images/2016-04-18-madrid-leaflet-864px.jpg contains an embedded color calibration profile, which is copyright Hewlett Packard without free licensing.

Please strip the ICC profile - that is better for web-served images anyway.

**Comment by jonassmedegaard** [comment]
One way to check for licensing of embedded ICC profiles (if you do not wish to generally strip them) is with the commandline tool exiftool, part of Perl module Image::ExifTool (e.g. "apt install libimage-exiftool-perl" or "cpanm Image::ExifTool").

**Comment by IvanSanchez** [comment]
We are not really concerned about this issue. IIRC we took the photo with a HP compact camera, did a bit of GIMPing on it, and copied it around.

> that is better for web-served images anyway.

How is that *better*, exactly?

> Please strip the ICC profile

We have enough trouble dealing with web browser quirks and crazy javascript, so if you want to fix this, I strongly suggest you submit the changes in the form of a PR yourself.

**Comment by jonassmedegaard** [comment]
Quoting Iván Sánchez Ortega (2017-04-18 10:55:15)
> We are not really concerned about this issue. IIRC we took the photo 
> with a HP compact camera, did a bit of GIMPing on it, and copied it 
> around.
>
>> that is better for web-served images anyway.
>
> How is that *better*, exactly?

No ICC profile → Smaller image → faster download.

The ICC profile most likely declares the "sRGB" color space, which is 
the default for images served via web.  You therefore save space by 
simply stripping the ICC profile.


>> Please strip the ICC profile
>
> We have enough trouble dealing with web browser quirks and crazy 
> javascript, so if you want to fix this, I strongly suggest you submit 
> the changes in the form of a PR yourself.

Sorry, I will not provide a Github PR, since I do not trust the Github 
Terms of Service: 
http://joeyh.name/blog/entry/what_I_would_ask_my_lawyers_about_the_new_Github_TOS/

Fine with me if you choose to violate that copyright problem.  I just 
wanted to make you aware, in case it matter to you to respect copyright 
of others (in this specific case Hewlett Packard).

For now, Debian will redistribute your project _without_ that image.  
That is only a small hassle for us, and a small hassle for those of our 
users wanting to verify that we indeed use your project uncompromised as 
basis for our redistribution. users especially concerned about security 
(they need to manually compare your pristine tarball against the derived 
one we redistribute).

Kind regards, and thanks a lot for your super great project,

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by IvanSanchez** [comment]
> No ICC profile → Smaller image → faster download

Yeah, but that image is not part of the release bundles, so the gain is negligible.

> For now, Debian will redistribute your project _without_ that image. 

No problem with that. 

I get your point, but Leaflet users are (in general) *very* lax about security. See e.g. https://github.com/Leaflet/Leaflet/issues/5457 , HTTP-only CDNs, and so on. We don't even GPG-sign the commits, FFS. I highly doubt that mismatching tarball hashes will ever be a problem (and if/when it becomes a problem, then we'll address it).
