### ISSUE TITLE
Generate integrity hashes during build

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#5466]
Problem: Leaflet can be subject of a script injection attack on the CDNs (see https://github.com/Leaflet/Leaflet/issues/5457 ). And, as https://github.com/Leaflet/Leaflet/issues/5460 points out, some users can be very security-conscious.

Solution: Calculate [subresource integrity hashes](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) during the build process, and put those in the download page of the website.

e.g. instead of 

```html
<script src="https://unpkg.com/leaflet@1.0.3/dist/leaflet.js"></script>
```

tell users to use something like 

```html
<script src="https://unpkg.com/leaflet@1.0.3/dist/leaflet.js" integrity="sha384-abcdefghijklmnopq"></script>
```

The [MDN page on integrity hashes](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) has some recipes to calculate the hashes on a CLI.

* [ ] Calculate integrity hashes on a build and output them
* [ ] Make the release script modify `docs/_config.yml` to overwrite the value of the latest release, and the latest integrity hash
* [ ] Modify `docs/download.md` to put the integrity hash somewhere

Ideally hashes should be provided for the uglified and non-uglified flavours of `leaflet.js` and `leaflet-src.js`; hopefully this won't add much more noise to the download webpage.

**Comment by IvanSanchez** [comment]
Of course this could all be rendered moot because https://github.com/Leaflet/Leaflet/issues/3748 and https://github.com/isaacs/github/issues/156, but still would be better than nothing.

**Comment by danzel** [comment]
HTTPS doesn't fix issues if your CDN gets hacked, and the file on the CDN replaced.
I'd like to see this now that it has been mentioned :+1:

**Comment by perliedman** [comment]
I'm also :+1:, great idea.
