### ISSUE TITLE
Map to image using Html2Canvas - image is cut if map is moved 

### ISSUE THREAD

**Issue by LioraC** [Leaflet/Leaflet#5469]
## How to reproduce

- Leaflet version I'm using: 1.0.0-rc.1
- Browser (with version) I'm using: Chrome (latest)
- OS/Platform (with version) I'm using: Windows 7 / 10

- Move map
- Use Html2Canvas to save map 
- Display the canvas

## What behaviour I'm expecting and which behaviour I'm seeing
We expect to see the full map, however - the map appears cut, as seen in the attached screenshot.
![html2canvas_cut](https://cloud.githubusercontent.com/assets/27775898/25190403/c3920bfc-2534-11e7-83d5-aa19094ffeec.png)

Please advise, is there a way around this, or another suggested way to render the map as image?

Thanks a lot.

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.
