### ISSUE TITLE
Calculate the bounding box with a given center and zoom without actually zooming

### ISSUE THREAD

**Issue by ahskaus** [Leaflet/Leaflet#5472]
I am basically looking for the opposite of getBoundsZoom() function. I am trying to figure out what the resulting bounding box be if I press the zoomIn button.

Or more generally, given a center and a zoom level, what would be the resulting bounding box.

**Comment by perliedman** [comment]
To my knowledge, there's currently no such method. However, you can have a look at how [`_limitCenter`](https://github.com/Leaflet/Leaflet/blob/master/src/map/Map.js#L1437-1439) calculates the bounds:

```js
		var centerPoint = this.project(center, zoom),
		    viewHalf = this.getSize().divideBy(2),
		    viewBounds = new Bounds(centerPoint.subtract(viewHalf), centerPoint.add(viewHalf)),
```

That will give the bounds in projected coordinates, so you'll have to unproject those to get back to `LatLng`s.
