### ISSUE TITLE
Problems with outline

### ISSUE THREAD

**Issue by HarelM** [Leaflet/Leaflet#5473]
- [x] I'm reporting a bug, not asking for help;
- [x] I've looked at the [documentation](http://leafletjs.com/reference-1.0.3.html) to make sure the behaviour is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

## How to reproduce
It's tricky.
I started a migration from 0.7 to 1.0.
Most of the migration was trivial (Kudos) but I'm experiencing a problem with the `preventOutline` and `restoreOutline`.
What I have is a drawing control that when a user want to draw he clicks on a pencil icon and the control stretches to show more drawing capabilities.
In previous version I highlighted the pencil to indicate the user is drawing and the currently selected drawing method.
After the migration to leaflet 1.0.3 the highlight (using leaflet-active class) stopped working well.
It might collide with Angular but I'm sure this change is related to the migration to 1.0.3.

This might be by design but my element is getting a `style=outline:none`, I can't override this behavior easily. I think that if this is by design the way to do it will be by adding a class to the element for example `no-outline` and define it in the css `.no-outline { outline: none; }` so that I'll be able to override it.

I'll see if I can create my site with leaflet 0.7 and 1.0.3 to better show the difference.

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by HarelM** [comment]
http://playground-leaflet.rhcloud.com/nayod/1/edit?html,output
Click the new control - it should have orange frame after clicking.

**Comment by HarelM** [comment]
Clicking the pencil on the right on the following sites:
This is how it should behave - still using 0.7.7:
http://israelhiking.osm.org.il/
This is how it behaves with 1.0.3:
http://israelhiking.osm.org.il/test/
But the above playground captures the issue as far as I can tell.

**Comment by perliedman** [comment]
Here's a version of the example, but with Leaflet 0.7.7, and it does indeed give an orange border when clicked: http://playground-leaflet.rhcloud.com/bemo/edit?html,output

**Comment by perliedman** [comment]
The problem is that the `mousedown` event propagates to the map, which tries to disable outlines: https://github.com/Leaflet/Leaflet/blob/master/src/map/Map.js#L1306

You can work around this by preventing the event from bubbling:

```
L.DomEvent.disableClickPropagation(container);
```

See here: http://playground-leaflet.rhcloud.com/voma/edit?html,output

**Comment by HarelM** [comment]
Thanks for the quick response!
Worth mentioning this in some sort of upgrade instructions between 0.7 and 1.0 as this is a breaking change.
