### ISSUE TITLE
L.Bounds methods and parameters

### ISSUE THREAD

**Issue by dom1n1k** [Leaflet/Leaflet#5475]
Docs: http://leafletjs.com/reference-1.0.3.html#bounds

Factory:

`L.bounds(<Point> topLeft, <Point> bottomRight)` [link](http://leafletjs.com/reference-1.0.3.html#bounds-l-bounds)

But in methods:

`getBottomLeft()` - Returns the bottom-left point of the bounds [link](http://leafletjs.com/reference-1.0.3.html#bounds-getbottomleft)
`getTopRight()` - Returns the top-right point of the bounds [link](http://leafletjs.com/reference-1.0.3.html#bounds-gettopright)

Why not `getTopLeft` and `getBottomRight`? I think this is inconsistent.

**Comment by ghybs** [comment]
Hi,

I think this is similar to https://github.com/Leaflet/Leaflet/pull/5059

I.e. actually you can pass whatever points / "corners" to `L.bounds` factory (not just `topLeft`, `bottomRight`, could be `topRight` and `bottomLeft`), and it will just re-order the coordinates to get:

- the smaller `x` in `min.x` (i.e. left-most),
- the higher `x` in `max.x` (i.e. right-most),
- the smaller `y` in `min.y` (i.e. top-most) and
- the higher `y` in `max.y` (i.e. bottom-most).

**Comment by perliedman** [comment]
@ghybs is right here, in practice it makes no difference: as long as you pass min and max for x as well as y, the order is insignificant.

Having said that, I have to agree that the naming is weird, and goes against what I think is established conventions. We should fix this.

Just renaming the factory/constructor parameters `bottomLeft` and `topRight` seems right. Contribution to address this very welcome!

**Comment by ghybs** [comment]
Maybe `corner1` and `corner2` like in #5059 would be closer to the functionality, even though farther from conventions?

BTW, we could even push further the refinement by directly accepting an indefinite length of point arguments - i.e. corners (instead of a single array or 2 points), by replacing `points` by `arguments` if we detect more than 1 argument (or if the 1st one is not an array). Same applies for `L.LatLngBounds`.

**Comment by perliedman** [comment]
@ghybs :+1: consistency with #5059 seems like a good idea, updated suggestion above.

**Comment by dom1n1k** [comment]
Maybe add 2 extra methods `getTopLeft` and `getBottomRight`? Additional, not instead.
In `LatLngBounds` there are methods for all 4 corners:
http://leafletjs.com/reference-1.0.3.html#latlngbounds
And 4 bounds.

**Comment by perliedman** [comment]
@dom1n1k sounds good, making `Bounds` and `LatLngBounds` have the same API makes a lot of sense.
