### ISSUE TITLE
L.disableClickPropagation not working

### ISSUE THREAD

**Issue by danierod** [Leaflet/Leaflet#5483]
## How to reproduce

- Leaflet version I'm using: 1.0.1
- Browser (with version) I'm using: Google Chrome Version 57.0.2987.133 (64-bit)
- OS/Platform (with version) I'm using: Linux Manjaro 

## What behaviour I'm expecting and which behaviour I'm seeing
When doubleClicking the test div the map zoom event is triggered.

## Minimal example reproducing the issue

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

Check the example [here](http://playground-leaflet.rhcloud.com/raz/edit?html,output).

Is something wrong  with my code?

Thanks.

**Comment by IvanSanchez** [comment]
Related to #5217

**Comment by perliedman** [comment]
@danierod hi there,
I looked at your example, and in fact it looks like there is an issue with your code.

To get hold of the created `div`, you use `getElementById`, but you haven't assigned an `id` to the div, so you end up passing `null` as element to `disableClickPropagation`.

I highly recommend _always_ looking at the console output when something weird happens. In your case, you can clearly see your call to `disableClickPropagation` causing the error `Uncaught TypeError: Cannot read property '_leaflet_events' of null`.

A fixed version of your code can look something like this: http://playground-leaflet.rhcloud.com/huw/edit?html,output
