### ISSUE TITLE
Replace reference.html symlink with redirect

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#5491]
The [current method](https://github.com/Leaflet/Leaflet/pull/5490) of symlinking `reference.html` to `reference-1.0.3.html` might be suboptimal for SEO and other scenarios.

The idea is to follow the instructions at https://help.github.com/articles/redirects-on-github-pages/ , and create a `reference.html` file like:

```
---
redirect_to: reference-1.0.3.html
---
```

Extra points if the `latest_leaflet_version` variable from `_config.html` can be used in `reference.html`'s frontmatter to update this automatically.

**Comment by perliedman** [comment]
Closed by #5493.
