### ISSUE TITLE
Adding an empty L.Polyline to a canvas rendered map causes errors

### ISSUE THREAD

**Issue by steve9164** [Leaflet/Leaflet#5497]
## How to reproduce

- Leaflet version I'm using: 1.0.3
- Browser (with version) I'm using: Chrome 57
- OS/Platform (with version) I'm using: OS X 10.11
1. Create `L.Polyline` with empty `latlngs`
2. Add that layer to an `L.Map` with `preferCanvas: true`

## What behaviour I'm expecting and which behaviour I'm seeing
Nothing should be displayed, but it should run without console errors.

## Minimal example reproducing the issue

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

https://codepen.io/steve9164/pen/dWzdVW

**Comment by perliedman** [comment]
Hi there and thanks for reporting.

I think I disagree with the conclusion that this is a bug: in general, if you create vector features in Leaflet without specifying coordinates, it will not work. Like in your example, you also can't create a marker without specifying a `LatLng` and have it as an "empty" marker - it will throw errors. If you don't have any coordinates, then don't add a polyline to the map.

**Comment by steve9164** [comment]
That sounds reasonable.

Some additional details that I should have originally included are that:
- It currently works without error if you're using the SVG renderer, and
- This used to work in Leaflet 0.7.3 (although that is a major version away with various large changes, so obviously not all behaviour is mirrored)

**Comment by perliedman** [comment]
Alright, actually sounds a bit convincing 😄. It also turned out to be a pretty simple fix, so I submitted #5498 that addresses this.
