### ISSUE TITLE
Marker events fired when zooming causing markers to move to preceding offset, then to the correct screen location.

### ISSUE THREAD

**Issue by james-gould** [Leaflet/Leaflet#5505]
## How to reproduce

- Leaflet version I'm using: 1.0.3
- Browser (with version) I'm using: Chrome
- OS/Platform (with version) I'm using: W10

0. Zoom between 14-16 to see this effectively.
1. Create a new marker with default settings. To make life easier, create this marker on a click event.
2.  As the marker is created, zoom out 1 level. The marker should jump to the preceding screen offset, and then adjust itself to the current zoom level.

This may take a few tries. I've noticed it occuring semi-frequently when pinging new markers to my Leaflet app from a TCP server. When a new location arrives from the server, a marker is created and then added to the map. Zooming out anywhere in this process causes it to jump.

**Comment by IvanSanchez** [comment]
Does this mean that the bug happens whenever a marker is added to the map **during** a zoom animation?

**Comment by james-gould** [comment]
I believe so. I'm finding it hard to properly debug it but that seems to be the behaviour. I'm away from my normal dev machine at the moment, I'll put up a visual demonstration/jsfiddle of the behavior in the next few hours.

**Comment by kojoa** [comment]
Also encountered this bug. When marker is added during zooming animation it is first drawn to wrong location and then quickly jumps to where it should be.

Here is a jsfiddle to demonstrate the issue: https://jsfiddle.net/kojoa/peunkas4/
Just click run and quickly zoom back & forth while markers are added every 500ms.

Fiddle uses Leaflet 1.0.3. Tested on Mac OS Sierra 10.12.3 with Chrome 58.0.3029.110 and Safari 10.0.3.

**Comment by james-gould** [comment]
Oops, completely forgot to make the demo. Thanks @kojoa! That's the behaviour I was experiencing, except it as moving the marker rather than adding it.

**Comment by FadilEldin** [comment]
Markers do move to their final destination when you zoom in or out, as demonstrated in jsfiddle provided by @Kojoa. 
I do not understand what is the problem with that behavior?
