### ISSUE TITLE
URL hash is dropped by redirect from reference.html

### ISSUE THREAD

**Issue by perliedman** [Leaflet/Leaflet#5508]
After #5493, we use redirects for pointing `reference.html` to the latest version (like `reference-1.0.3.html`). Unfortunately, the redirection mechanism currently drops the URL hash, so for example linking to http://leafletjs.com/reference.html#icon ends up just redirecting to http://leafletjs.com/reference-1.0.3.html, not the section about [`L.Icon`](http://leafletjs.com/reference-1.0.3.html#icon).

This affects many links from the tutorials, among other things.

**Comment by cherniavskii** [comment]
Fixed by #5824
