### ISSUE TITLE
Event not removed from the map when removing a TileLayer

### ISSUE THREAD

**Issue by idawave** [Leaflet/Leaflet#5514]
Hi guys.

Just switched to Leaflet 1.0.3 (previously on 0.7.3).

I encountered a problem when removing a TileLayer from the map, some of the events do not seem to be removed, especially the one bound the map, like "zoomanim".
Thus, after removing a TileLayer, you cannot zoom anymore because two errors are triggered:

```
- Uncaught TypeError: Cannot read property 'project' of null at NewClass._updateLevels (VM4131 leaflet-src.js:4999)
- Uncaught TypeError: Cannot read property 'getCenter' of null at NewClass._resetView (VM4131 leaflet-src.js:5127)
```

The errors are triggered because the map is firing a _zoomanim_ event, and handlers for the removed TileLayer still exist, but the TileLayer is not on the map anymore (thus this._map returns null).

Try it there: http://playground-leaflet.rhcloud.com/wiwiv/1/edit?html,output

I wonder if I am missing something here.
Of course, for the time being I added fallback like `if (this._map) {...}` but this is not clean as no old handler (that should not be there anymore) is removed this way.

Should I go for a good old `this._map.off("zoomanim", ...)` (will need to do that for all the other events as well)?

I guess this problem might be happening with all the classes implementing the `getEvents `method.

Br,
Vincent

**Comment by perliedman** [comment]
I think you're seeing this problem because you're calling `positron.clearAllEventListeners();` before removing the layer. This will remove the layer's cleanup logic (which is in an event listener) before you remove it: so the listeners will not be cleaned up.

Removing that line from your example seems to make it run without problems. Or am I missing something?

**Comment by idawave** [comment]
Yeah seems legit to me, to be honest I don't remember why there is a clearAllEventListeners there.
I was mislead by the name `clearAllEventListeners `, which is thought would be in fact removing (unbinding) all the events attached by the TileLayer.

Thanks for fast answer.
