### ISSUE TITLE
Lateral movement when user zoom out using scrollwheel

### ISSUE THREAD

**Issue by dzegarra** [Leaflet/Leaflet#5531]
### Environment

Leaflet version: 1.0.3
Browser: Tested in Chrome and Firefox
OS: Ubuntu, Windows

### Instructions to reproduce the bug

1. Set the `zoomSnap` option to 4
3. Set `minZoom` option to 2
3. Use the scroll wheel to zoom out the map

## What behaviour I'm expecting

I have expected one of these two behaviors when the user use the scroll-wheel:

1. Zoom out until get to the minimum zoom level and stop there. Once the map is at the minimum zoom level the zoom out actions with the scroll-wheel should be ignored.
2. Zoom out until the the zoom level could not be reduce more without become lower than the minimum zoom level. Remember each zoom level should be a multiple of the `zoomSnap` option.

## Which behaviour I'm seeing
When the `zoomSnap` is high and `minZoom` is more than 1 the zoom-out action fired by scroll-wheel actions will use the `setView()` function to apply the zoom change because, if `scrollWheelZoom == true`, the zoom changes will use the coordinates of the cursor over the map to zoom-in or zoom-out from that geographic position. 

The result is a change in the position of the map without a zoom chaning the zoom because the new zoom level passed to setView() is ignored.

## Minimal example reproducing the issue

http://playground-leaflet.rhcloud.com/kohe/edit?html,output

This is the configuration that you can use to reproduce the bug:
```javascript
var myCenter = new L.LatLng(50.5, 30.51);
var map = new L.Map('map', {
    center: myCenter, 
    zoom: 5,
    minZoom: 2,
    zoomSnap: 4,
    //scrollWheelZoom: true // change this to 'center' avoid the bug for now
});
```

**Comment by perliedman** [comment]
Hi,
I've looked at the linked example, but I couldn't really see any problem. Maybe I got the instructions wrong?

I'm zooming out using the scroll wheel, until the outermost zoom, and then I should see the map moving without actually zooming more, yes? Any step I'm missing, or am is there some other problem I don't see?

I've run this on Chrome 58 on Ubuntu.

**Comment by dzegarra** [comment]
Seems like the Jsbin link I pasted was pointing to an WIP example. 
I copy&paste the configuration that recreate the bug. Just try to zoom out using the scrollwheel.
http://playground-leaflet.rhcloud.com/kohe/edit?html,output

**Comment by perliedman** [comment]
Oh, yes, that's pretty wild! Confirmed bug.

**Comment by FadilEldin** [comment]
The link (http://playground-leaflet.rhcloud.com/kohe/edit?html,output) does not exists
@dzegarra Can you recreate the problem in https://jsfiddle.net/

**Comment by dzegarra** [comment]
Sorry @FadilEldin . This issue is very old. I don't work on this project anymore nor I remember what this bug was about.

**Comment by FadilEldin** [comment]
Should be closed
