### ISSUE TITLE
Icon.Default.detectIconPath can throw TypeError: path is null

### ISSUE THREAD

**Issue by williamscs** [Leaflet/Leaflet#5534]
The line is specified at this link:
https://github.com/Leaflet/Leaflet/blob/master/src/layer/marker/Icon.Default.js#L52

`DomUtil.getStyle` has the ability to return null, but there is no check for this in the calling method.

This can occur in a few scenarios, but specifically occurs if you are using the leaflet.js library, but the DOM hasn't loaded yet.

In my situation, in Firefox (not IE or Chrome) leaflet is loading in an iframe that is in a separate tab. I'm not sure why, but when the `detectIconPath` attempts to create the div with the class, the rule is not loaded and there is no background-image.

Due to this, even if I override the options with a new imagePath, the check still attempts and throws the exception since there isn't a check.

Current workaround is to assign `L.Icon.Default.imagePath` directly so that method is not called.

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by williamscs** [comment]
Please run this plunkr in Firefox: http://embed.plnkr.co/v2exze56bEigI3tUTJNU/

**Comment by IvanSanchez** [comment]
Can confirm.

Hhhmmm, apparently `window.getComputedStyle` is returning `null` when running the query in the hidden iframe. This is quite unexpected for me, as the [docs for `getComputedStyle`](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle) don't mention that. This is puzzling.

Maybe you can submit a PR to set a default value of empty string to `path` in the `detectIconPath` method? That'd speed things up.

Unless, of course, you know how to fetch the CSS styling of the hidden iframe. That'd be extra nice, ut I doubt if it can be done in a clean way.

**Comment by williamscs** [comment]
Yep, that's the fix I have now. Working on an automated test for it now.

**Comment by williamscs** [comment]
https://github.com/Leaflet/Leaflet/pull/5535

**Comment by chpio** [comment]
Is there no other way to pass configuration directly to leaflets js code, reading css is an *unusual* way passing config to a js lib?

[Map](https://github.com/Leaflet/Leaflet/blob/f8e09f993292579a1af88261c9b461730f22e4e6/src/map/Map.js#L1123) seem to break too when the js code gets executed before the css can take effect.

**Comment by perliedman** [comment]
@chpio you can set [`L.Icon.Default.prototype.options.imagePath`](https://leafletjs.com/reference-1.6.0.html#icon-default-imagepath).
