### ISSUE TITLE
Bounds restricting tile loading around world

### ISSUE THREAD

**Issue by jwest-rms** [Leaflet/Leaflet#5536]
## How to reproduce

- Leaflet version I'm using: 1.0.3
- Browser (with version) I'm using: Chrome
- OS/Platform (with version) I'm using: Mac OS 10.11
- Define layer with bounds options to limit tile loading
- Pan around the world so that base layer starts to duplicate
- Top layer does not load on top of duplicates of the base layer due to bounds check

## What behaviour I'm expecting and which behaviour I'm seeing
Bounds should be transformed across the multiple copies of the base layer.

I believe the issue is [here](https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/GridLayer.js#L742). The bound's lat/lng are wrapped, but the return value is not stored.  Changing the above to appears to fix the issue:

`bounds = map.wrapLatLngBounds(bounds);`

**Comment by ghybs** [comment]
Hi,

What about map's [`worldCopyJump`](http://leafletjs.com/reference-1.0.3.html#map-worldcopyjump) option?

> With this option enabled, the map tracks when you pan to another "copy" of the world and seamlessly jumps to the original one so that all overlays like markers and vector layers are still visible.

**Comment by perliedman** [comment]
@jwest-rms from your description, it sounds like `worldCopyJump` is indeed the fix here. Can you verify that this works?

Otherwise, please provide a running example of the issue on JSFiddle, [Leaflet Playground](http://playground-leaflet.rhcloud.com/) or similar.

**Comment by jwest-rms** [comment]
I was updating from .7 and this was a difference. Looking at the code referenced, I cant see where `map.wrapLatLngBounds(bounds)` would be modifying the passed in bounds object so if the wrapped bounds aren't being returned, why is that function being called?  To me it just seemed like a simple typo vs an intentional change.

`worldCopyJump` does work, but just felt too jumpy and as I said, the behavior in .7 was different.

**Comment by perliedman** [comment]
@jwest-rms wow, yes, thanks for insisting this is an issue!

I see the problem now, it was introduced in 059a722b5be57a6f591a2ab69494021be992af34 while fixing #5149, and does indeed look like a typo.

Updating `bounds` with the value from `wrapLatLngBounds` is certainly correct.

@jwest-rms care to make a pull request to address this?
