### ISSUE TITLE
How to use leaflet-indoor plugin in leaflet.1.0.3

### ISSUE THREAD

**Issue by shantilal-narola** [Leaflet/Leaflet#5539]
## How to reproduce

- Leaflet version I'm using: 1.0.3
- Browser (with version) I'm using: crome
- OS/Platform (with version) I'm using: Mac

## What behaviour I'm expecting and which behaviour I'm seeing
leaflet-indoor plugin compatible with leaflet.1.0.3 version. 

when i am using leaflet 0.7.7 then leaflet-indoor is working perfactly.
but when I updated Leaflet to v 1.0.3 in and now leaflet-indoor is not working. Rather, leaflet itself is throwing an error like Uncaught TypeError: Cannot read property 'call' of undefined(…).
Can you help for leaflet-indoor plugin so it works?

**Comment by perliedman** [comment]
Hi and thanks for using Leaflet!

This looks like a question about a specific plugin, and not an issue with Leaflet itself. You should contact the plugin author and ask or raise an issue on their project. Leaflet Indoor is not maintained by the Leaflet core team, so we have no knowledge of how it works or what Leaflet versions it supports. Sorry!
