### ISSUE TITLE
Supporting WFS

### ISSUE THREAD

**Issue by gharibi** [Leaflet/Leaflet#5541]
**Currently `leaflet` doesn't support WFS**. There is a workaround for it, which is to invoke the WFS as GeoJSON and consume it.

Is there anyway to get this implemented?

**Comment by IvanSanchez** [comment]
[As I told you already](https://stackoverflow.com/questions/44250336/adding-wfs-layers-to-leafletjs#comment75522154_44250336), go to leafletjs.com/plugins.html and search for WFS there.

**Comment by gharibi** [comment]
Sorry I just saw your message on StackOverFlow. I tried various frameworks and **Leaflet-WFST** is quite interesting [https://github.com/Flexberry/Leaflet-WFST/blob/master/README.md](url). Thank you anyway.
