### ISSUE TITLE
Can I   add shadows for leaflet polyline ?

### ISSUE THREAD

**Issue by chm74** [Leaflet/Leaflet#5543]
## How to reproduce

- Leaflet version I'm using:
- Browser (with version) I'm using:
- OS/Platform (with version) I'm using:
- step 1
- step 2

## Minimal example reproducing the issue

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

Using http://playground-leaflet.rhcloud.com/ or any other jsfiddle-like site.

**Comment by perliedman** [comment]
Hi and thanks for using Leaflet!

Please note that this is our issue tracker, where bugs and feature requests and posted and discussed. For questions on how to use Leaflet and other support, you're better off using [stackoverflow](https://stackoverflow.com/) or [gis.stackexchange.com](https://gis.stackexchange.com/).

You could possibly emulate shadows by adding multiple polyline's with the same coordinates but different styles. Also search for plugins that could help with this.
