### ISSUE TITLE
Operation aborted errors under IE 11

### ISSUE THREAD

**Issue by hyperknot** [Leaflet/Leaflet#5548]
I'm getting lots of Sentry error messages from users, 100% using IE 11, under Windows 7, 8.1 and 10. Leaflet version is 1.0.3 official.

Most important thing: I have no idea how to reproduce it. I don't even know if it's a harmless warning or a critical error with broken map or something.

All what they says is: `Error Operation aborted`, only under IE 11.

The stacktrace always ends with:

```
_addTile: function (coords, container) {
		var tilePos = this._getTilePos(coords),
		    key = this._tileCoordsToKey(coords);
		var tile = this.createTile(this._wrapCoords(coords), L.bind(this._tileReady, this, coords));
```

=>

createTile
```
		tile.setAttribute('role', 'presentation');

		tile.src = this.getTileUrl(coords);

		return tile;    <----- this line
	},
```

**Comment by perliedman** [comment]
Hi @hyperknot ! :wave: 

I guess your Google skills are as good as mine, but I found this info on this error in IE11: https://www.nczonline.net/blog/2008/03/17/the-dreaded-operation-aborted-error/ (also https://stackoverflow.com/questions/26890842/operation-aborted-javascript-error-in-ie-11)

Any chance those are applicable to the app you're seeing this error in?

**Comment by hyperknot** [comment]
Hi @perliedman!

So I tried googling before posting here, but I couldn't really find any recent information, except for the old IE versions. The one you posted from StackOverflow might be useful, however my script is already direct child of <body> so in theory it doesn't apply.

So I don't really know anything, except that some users are experiencing this error with createTile in IE11. I hope it's not a critical error, but just a message I'm receiving, but if anyone else has any ideas I'm happy to follow them.

**Comment by jonkoops** [comment]
Closing this issue as we have decided to drop support for Internet Explorer in a future version of Leaflet (see #6136).
