### ISSUE TITLE
Using HTTP POST for WMS service??

### ISSUE THREAD

**Issue by kunalbhatt** [Leaflet/Leaflet#5549]
Hello!

We've been using leaflet version 0.7.7, and the WMS service we use doesn't use the traditional HTTP Get method but rather uses POST. We had this shim to help with this 

```
  var TileLayerSoils = L.TileLayer.WMS.extend({
    options: {
      sld_body: ''
    },
    createTile: function _loadTile(tile, tilePoint) {
      tile._layer = this;
      tile.onload = this._tileOnLoad;
      tile.onerror = this._tileOnError;
      this._adjustTilePoint(tilePoint);
      const xhr = new XMLHttpRequest();
      const splitUrl = this.getTileUrl(tilePoint).split('?');
      xhr.open('POST', splitUrl[0]);
      xhr.responseType = 'blob';
      xhr.onload = function xhrLoadCallback() { tile.src = window.URL.createObjectURL(this.response); };
      xhr.send(splitUrl[1]);
      this.fire('tileloadstart', {
        tile: tile,
        url: tile.src
      });
    },
    getTileUrl: function getTileUrl(tilePoint) {
      const map = this._map;
      const tileSize = this.options.tileSize;
      const nwPoint = tilePoint.multiplyBy(tileSize);
      const sePoint = nwPoint.add([tileSize, tileSize]);
      const nw = this._crs.project(map.unproject(nwPoint, tilePoint.z));
      const se = this._crs.project(map.unproject(sePoint, tilePoint.z));
      const bbox = this._wmsVersion >= 1.3 && this._crs === L.CRS.EPSG4326 ?
        [se.y, nw.x, nw.y, se.x].join(',') :
        [nw.x, se.y, se.x, nw.y].join(',');
      let url = L.Util.template(this._url, {s: this._getSubdomain(tilePoint)});
      const params = [];
      for (const key in this.wmsParams) {
        if (Object.prototype.hasOwnProperty.call(this.wmsParams, key)) {
          params.push(key.toUpperCase() + '=' + this.wmsParams[key]);
        }
      }
      url = url + ((!url || url.indexOf('?') === -1) ? '?' : '&') + params.join('&');
      return url + '&BBOX=' + bbox + '&SLD_BODY=' + this.options.sld_body;
    },
  });
```

Now after updating to the latest the loadtile method has been deprecated and I can't seem to figure out what method to attach this shim to. After I successfully add a way to use HTTP Post shim for a WMS service ill submit a pr as I think it can be useful.

**Comment by kunalbhatt** [comment]
Had a stroke of genius/luck right after posting this. For those who are wondering you must manipulate the `createTile` function in order to achieve the desired results.

**Comment by perliedman** [comment]
Hi!

As I understand it, this is more a question of how to use Leaflet than an actual issue?

If this is something that is useful to more people (I don't know how common WMS which requires POST instead of GET is), I suggest publishing a plugin for this. It is not likely to be included in Leaflet itself, since it's after all covering a niche use case with a non-standard service.

I'll close this for now, but feel free to add more information if you think this should be reopened.

**Comment by dr-mohamed-benkhalifa** [comment]
@kunalbhatt Could you please suggest a plugin to implement POST, the idea is to pass the tilelayer options to the body of the request, instead of using the leaflet default tileLayer method that uses query params

**Comment by luisbello30** [comment]
https://anitagraser.com/2010/06/09/getmap-from-geoserver-using-http-post/

**Comment by benboughton1** [comment]
Anyone got code example of this working?

**Comment by NickSavin** [comment]
I have met the same problem with a huge Get request. I took the solution of @kunalbhatt and modified it a little bit to add an ability to abort the long running requests on map zooming.

```
import * as L from 'leaflet';

export const BetterWMS = L.TileLayer.BetterWMS = L.TileLayer.WMS.extend({

    createTile: async function (coords, done) {
        var tile = document.createElement('img');

        tile.abortController = new AbortController();

        L.DomEvent.on(tile, 'load', L.Util.bind(this._tileOnLoad, this, done, tile));
        L.DomEvent.on(tile, 'error', L.Util.bind(this._tileOnError, this, done, tile));

        if (this.options.crossOrigin || this.options.crossOrigin === '') {
            tile.crossOrigin = this.options.crossOrigin === true ? '' : this.options.crossOrigin;
        }

        /*
         Alt tag is set to empty string to keep screen readers from reading URL and for compliance reasons
         http://www.w3.org/TR/WCAG20-TECHS/H67
        */
        tile.alt = '';
        tile.src = L.Util.emptyImageUrl;

        /*
         Set role="presentation" to force screen readers to ignore this
         https://www.w3.org/TR/wai-aria/roles#textalternativecomputation
        */
        tile.setAttribute('role', 'presentation');

        this._loadTile(coords, tile);

        return tile;
    },

    _loadTile: function (coords, tile) {
        const fullUrl = this.getTileUrl(coords);
        const [url, urlparams] = fullUrl.split("?");

        fetch(url, {
            method: "POST",
            body: urlparams,
            headers: {
                "Content-type": "application/x-www-form-urlencoded",
            },
            signal: tile.abortController.signal
        }).then((response) => {
            if (response.ok) {
                response.blob().then((blobData) => {
                    tile.src = window.URL.createObjectURL(blobData);
                });
            }
        });

    },

    // stops loading all tiles in the background layer
    _abortLoading: function () {
        for (const i in this._tiles) {
            if (this._tiles[i].coords.z !== this._tileZoom) {
                const tile = this._tiles[i].el;
                if (!tile.complete) {
                    tile.abortController.abort();
                }
            }
        }
        L.TileLayer.WMS.prototype._abortLoading.call(this);
    },

    _removeTile: function (key) {
        const tile = this._tiles[key];
        if (!tile) {
            return;
        }
        if (!tile.el.complete) {
            tile.el.abortController.abort();
        }
        L.TileLayer.WMS.prototype._removeTile.call(this, key);
    },

});

export const betterWms = L.tileLayer.betterWms = function (url, options) {
    return new L.TileLayer.BetterWMS(url, options);
};
```

**Comment by jibinmannanal** [comment]
> I have met the same problem with a huge Get request. I took the solution of @kunalbhatt and modified it a little bit to add an ability to abort the long running requests on map zooming.
> 
> ```
> import * as L from 'leaflet';
> 
> export const BetterWMS = L.TileLayer.BetterWMS = L.TileLayer.WMS.extend({
> 
>     createTile: async function (coords, done) {
>         var tile = document.createElement('img');
> 
>         tile.abortController = new AbortController();
> 
>         L.DomEvent.on(tile, 'load', L.Util.bind(this._tileOnLoad, this, done, tile));
>         L.DomEvent.on(tile, 'error', L.Util.bind(this._tileOnError, this, done, tile));
> 
>         if (this.options.crossOrigin || this.options.crossOrigin === '') {
>             tile.crossOrigin = this.options.crossOrigin === true ? '' : this.options.crossOrigin;
>         }
> 
>         /*
>          Alt tag is set to empty string to keep screen readers from reading URL and for compliance reasons
>          http://www.w3.org/TR/WCAG20-TECHS/H67
>         */
>         tile.alt = '';
>         tile.src = L.Util.emptyImageUrl;
> 
>         /*
>          Set role="presentation" to force screen readers to ignore this
>          https://www.w3.org/TR/wai-aria/roles#textalternativecomputation
>         */
>         tile.setAttribute('role', 'presentation');
> 
>         this._loadTile(coords, tile);
> 
>         return tile;
>     },
> 
>     _loadTile: function (coords, tile) {
>         const fullUrl = this.getTileUrl(coords);
>         const [url, urlparams] = fullUrl.split("?");
> 
>         fetch(url, {
>             method: "POST",
>             body: urlparams,
>             headers: {
>                 "Content-type": "application/x-www-form-urlencoded",
>             },
>             signal: tile.abortController.signal
>         })
>             .then(response => {
>                 return response.blob();
>             })
>             .then(blobData => {
>                 tile.src = window.URL.createObjectURL(blobData);
>             })
>             .catch(() => { });
> 
>     },
> 
>     // stops loading all tiles in the background layer
>     _abortLoading: function () {
>         for (const i in this._tiles) {
>             if (this._tiles[i].coords.z !== this._tileZoom) {
>                 const tile = this._tiles[i].el;
>                 if (tile.src === L.Util.emptyImageUrl) {
>                     tile.abortController.abort();
>                 }
>             }
>         }
>         L.TileLayer.WMS.prototype._abortLoading.call(this);
>     },
> 
>     _removeTile: function (key) {
>         const tile = this._tiles[key];
>         if (!tile) {
>             return;
>         }
>         if (tile.el.src === L.Util.emptyImageUrl) {
>             tile.el.abortController.abort();
>         }
>         L.TileLayer.WMS.prototype._removeTile.call(this, key);
>     },
> 
> });
> 
> export const betterWms = L.tileLayer.betterWms = function (url, options) {
>     return new L.TileLayer.BetterWMS(url, options);
> };
> ```

I used this code and I am getting 
TypeError: Cannot read property 'baseVal' of undefined

this error

**Comment by jawak** [comment]
> > I have met the same problem with a huge Get request. I took the solution of @kunalbhatt and modified it a little bit to add an ability to abort the long running requests on map zooming.
> > ```
> > import * as L from 'leaflet';
> > 
> > export const BetterWMS = L.TileLayer.BetterWMS = L.TileLayer.WMS.extend({
> > 
> >     createTile: async function (coords, done) {
> >         var tile = document.createElement('img');
> > 
> >         tile.abortController = new AbortController();
> > 
> >         L.DomEvent.on(tile, 'load', L.Util.bind(this._tileOnLoad, this, done, tile));
> >         L.DomEvent.on(tile, 'error', L.Util.bind(this._tileOnError, this, done, tile));
> > 
> >         if (this.options.crossOrigin || this.options.crossOrigin === '') {
> >             tile.crossOrigin = this.options.crossOrigin === true ? '' : this.options.crossOrigin;
> >         }
> > 
> >         /*
> >          Alt tag is set to empty string to keep screen readers from reading URL and for compliance reasons
> >          http://www.w3.org/TR/WCAG20-TECHS/H67
> >         */
> >         tile.alt = '';
> >         tile.src = L.Util.emptyImageUrl;
> > 
> >         /*
> >          Set role="presentation" to force screen readers to ignore this
> >          https://www.w3.org/TR/wai-aria/roles#textalternativecomputation
> >         */
> >         tile.setAttribute('role', 'presentation');
> > 
> >         this._loadTile(coords, tile);
> > 
> >         return tile;
> >     },
> > 
> >     _loadTile: function (coords, tile) {
> >         const fullUrl = this.getTileUrl(coords);
> >         const [url, urlparams] = fullUrl.split("?");
> > 
> >         fetch(url, {
> >             method: "POST",
> >             body: urlparams,
> >             headers: {
> >                 "Content-type": "application/x-www-form-urlencoded",
> >             },
> >             signal: tile.abortController.signal
> >         })
> >             .then(response => {
> >                 return response.blob();
> >             })
> >             .then(blobData => {
> >                 tile.src = window.URL.createObjectURL(blobData);
> >             })
> >             .catch(() => { });
> > 
> >     },
> > 
> >     // stops loading all tiles in the background layer
> >     _abortLoading: function () {
> >         for (const i in this._tiles) {
> >             if (this._tiles[i].coords.z !== this._tileZoom) {
> >                 const tile = this._tiles[i].el;
> >                 if (tile.src === L.Util.emptyImageUrl) {
> >                     tile.abortController.abort();
> >                 }
> >             }
> >         }
> >         L.TileLayer.WMS.prototype._abortLoading.call(this);
> >     },
> > 
> >     _removeTile: function (key) {
> >         const tile = this._tiles[key];
> >         if (!tile) {
> >             return;
> >         }
> >         if (tile.el.src === L.Util.emptyImageUrl) {
> >             tile.el.abortController.abort();
> >         }
> >         L.TileLayer.WMS.prototype._removeTile.call(this, key);
> >     },
> > 
> > });
> > 
> > export const betterWms = L.tileLayer.betterWms = function (url, options) {
> >     return new L.TileLayer.BetterWMS(url, options);
> > };
> > ```
> 
> I used this code and I am getting TypeError: Cannot read property 'baseVal' of undefined
> 
> this error
@jibinmannanal remove async in createTile
work for me
