### ISSUE TITLE
A weird problem during Loading Tiles-- disorder tiles   

### ISSUE THREAD

**Issue by stefaniesun555** [Leaflet/Leaflet#5550]
As a beginer,I get leaflet 1.0.3 version.When I load a map and get an problem below:

OS:Window 7
WebServer:IIS
Broser:chorme

Code from the   [http://leafletjs.com/index.html](http://leafletjs.com/index.html)

```
<!DOCTYPE html>
<html>
<head>
	<title>Quick Start - Leaflet</title>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" type="image/x-icon" href="docs/images/favicon.ico" />
	<link ref ="stylesheet" href = "./leaflet.css"  />
	<script src = "./leaflet.js"></script>
</head>
<body>

<div id="map" style="width: 800px; height: 450px;"></div>
<script>
var map = L.map('map').setView([51.505, -0.09], 13);

L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);

L.marker([51.5, -0.09]).addTo(map)
    .bindPopup('A pretty CSS3 popup.<br> Easily customizable.')
    .openPopup();
</script>

</body>
</html>
```

The snapshot below:

![qq 20170607104139](https://user-images.githubusercontent.com/5064279/26860315-e7217f42-4b6f-11e7-9181-45a0c6f24be8.png)

![qq 20170607110221](https://user-images.githubusercontent.com/5064279/26860471-ad0208c6-4b70-11e7-957b-36ff68a81363.png)

**But When I use the leaflet.js from the CDN,there is no the problem.**

I want to know why this situation happens.

**Comment by perliedman** [comment]
Hi,
I'm pretty sure this is an issue with not loading Leaflet's CSS correctly, or possibly overriding the CSS with some other rules.

Check that your example loads Lealfet's CSS without errors. Check any extra CSS rules you add.

If the problem persists, please provide a running example illustrating the issue so we can have a closer look.

**Comment by stefaniesun555** [comment]
Thanks a lot!

You are right.As what you say, loading css with a problem.
