### ISSUE TITLE
Could not display the default blue Icon of Marker

### ISSUE THREAD

**Issue by GetHugWuSheng** [Leaflet/Leaflet#5553]
## Environment 
- Leaflet   : 1.0.3+master.162276e
- Browser : Chrome Version 55.0.2883.87 (64-bit)
- OS/Platform : Ubuntu 16.04

## Issue
Could not display the Leaflet's default blue Icon of Marker.
The source code in src/layer/marker/Icon.Default.js as below

```
        var path = DomUtil.getStyle(el, 'background-image') || DomUtil.getStyle(el, 'backgroundImage'); 
        document.body.removeChild(el);
        if (path === null || path.indexOf('url') !== 0) {
            path = '';
        } else {
            path.replace(/^url\([\"\']?/, '').replace(/marker-icon\.png[\"\']?\)$/, '');
        }
```

For the replaced result string didn't store back to path variable, the Icon got a wrong URL.
The last line should be replaced by
```
     path =  path.replace(/^url\([\"\']?/, '').replace(/marker-icon\.png[\"\']?\)$/, '');
```

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by ghybs** [comment]
https://playground-leaflet.rhcloud.com/fiwo/1/edit?html,output

From PR https://github.com/Leaflet/Leaflet/pull/5535

**Comment by ghybs** [comment]
Fixed by PR https://github.com/Leaflet/Leaflet/pull/5580
