### ISSUE TITLE
Modal Bootstrap Leaf

### ISSUE THREAD

**Issue by fernandomorse** [Leaflet/Leaflet#5565]
I need to put the map in modal bootstrap. Someone could give an example. Code that I am implementing.

Example:  https://jsbin.com/lukanef/2/edit?html,console,output

**Comment by perliedman** [comment]
Hi and thanks for using Leaflet!

Please note that this is our issue tracker, where bugs and feature requests and posted and discussed. For questions on how to use Leaflet and other support, you're better off using [stackoverflow](https://stackoverflow.com/) or [gis.stackexchange.com](https://gis.stackexchange.com/).
