### ISSUE TITLE
Wrong link in documentation for Control.Layers

### ISSUE THREAD

**Issue by RayBB** [Leaflet/Leaflet#5567]
## How to reproduce

- Leaflet version I'm using: N/A
- Browser (with version) I'm using: N/A
- OS/Platform (with version) I'm using: N/A
- step 1: Go to http://leafletjs.com/reference-1.0.3.html#control-layers
- step 2: Click " detailed example"

## What behaviour I'm expecting and which behaviour I'm seeing
I expect to be taken to the layer groups example (http://leafletjs.com/examples/layers-control/)
But Instead I'm being taken to an error page.

**Comment by IvanSanchez** [comment]
Good catch!

Could you please edit https://github.com/Leaflet/Leaflet/blob/master/src/control/Control.Layers.js#L13 and send a pull request with the change? That'll speed things up.

**Comment by perliedman** [comment]
Closed by #5568.
