### ISSUE TITLE
Any way to track what layer a user is currently viewing?

### ISSUE THREAD

**Issue by dhoff002** [Leaflet/Leaflet#5569]
Is there anyway with the layer control to determine what layer is currently active for a user.  Say for example the user selected and is using the grayscale layer or for example the user selected and is using the streets layer?  How could you do this in this example: http://leafletjs.com/examples/layers-control/

I need to track which layer a person is actively viewing for my code.  

Thank you so much in advance!  

Dan

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by dhoff002** [comment]
Thank you this is not a bug, I posted this is the wrong location.
