### ISSUE TITLE
why does not setView function have the callback ?

### ISSUE THREAD

**Issue by Jerry-goodboy** [Leaflet/Leaflet#5570]
setView(<LatLng> center, <Number> zoom, <Zoom/pan options> options?), why does not it have a callback , like this, setView(<LatLng> center, <Number> zoom, <Zoom/pan options> options?, <Function> callback?), because I want to capture a screenshot, but the map's setView is not ready, I can not get the final state of the map, while the "moveend" or "zoomend" does not work properly, only the first operation is triggered correctly.
if this method has a callback, the world will be better.
I use the version 1.0.3.

**Comment by Jerry-goodboy** [comment]
@michael @kshepard @palewire @naehrstoff @klaftertief

**Comment by perliedman** [comment]
Hi,
there's no such callback since we already have `moveend` and other events, as you mention. If you have a case where those events don't "work properly" as you say, I think you should open a new issue describing exactly what isn't working, as well as an example illustrating the problem.
