### ISSUE TITLE
location frequency [question]

### ISSUE THREAD

**Issue by Revo86** [Leaflet/Leaflet#5571]
Is there any way to decrease location update time from ~5000ms to ~1000 ms? Does leaflet use a different location api than openlayers?

**Comment by kaynz** [comment]
Hi,
Leaflet is using the Geolocation API, which allows you to set a timeout and maximumAge.

You can configure these over the locateOptions https://github.com/Leaflet/Leaflet/blob/b23d83f46416c404874ff57d1819646340297cb7/src/map/Map.js#L579

Please note that this is an issue tracker, where bugs and feature requests are posted and discussed. For questions on how to use Leaflet and other support, you're better off using stackoverflow or gis.stackexchange.com.

**Comment by IvanSanchez** [comment]
What @kaynz just said.
