### ISSUE TITLE
1.1 release candidate

### ISSUE THREAD

**Issue by kofronpi** [Leaflet/Leaflet#5576]
Hello,

Is it possible to release a release candidate of the 1.1 version ? Some packagers (e.g rails-assets) need a valid tag/branch to use it.

Thanks for the hard work on Leaflet !

**Comment by perliedman** [comment]
We're in the final stages of releasing 1.1.0, so a release candidate feels unnecessary at this point.

**Comment by kofronpi** [comment]
@perliedman sorry about that, I didn't know.

**Comment by perliedman** [comment]
Oh, no problem at all, of course.

Sorry for being a bit terse in my reply, things have been a bit hectic every now and then lately.

Given the long time to the 1.1.0 release, a release candidate a month or so ago would have made a lot of sense.
