### ISSUE TITLE
Support for "SingleTile" WMS layers

### ISSUE THREAD

**Issue by thefab** [Leaflet/Leaflet#558]
WMS layers are tiled in leaflet. It's perfect for basemaps and/or for public access. 

But it's not good for some use cases :
- realtime business layers
- private access with custom WMS servers
- layers animations (it's difficult to synchronize tiles animations)

It's implement in openlayers as a "singleTile" option :
http://openlayers.org/dev/examples/single-tile.html

In this mode, the GetMap WMS request must request :
- the exact bounding box of the visible map
- the exact width, height of the visible map

Thanks :-)

**Comment by birdage** [comment]
@sheppard :+1:

**Comment by zuoyangyang** [comment]
Thank you @fnicollet That  SingleTileWMSLayer  is exactly what I need and I have made some change on the "onRemove" method.I think we shoud reset "_imagesCreated "status for the next adding. Here is the code.
```
onRemove: function (map) {
        // super()
        L.ImageOverlay.prototype.onRemove.call(this, map);
        // add
        if (this._imageSwap){
            map.getPanes().overlayPane.removeChild(this._imageSwap);
        }
        //reset _imagesCreated status
        this._imagesCreated = false;
        map.off('moveend', this._onViewReset, this);
        map.off('zoomanim', this._onZoomAnim, this);
    }
```
By the way, I use 

> Leaflet 

version@0.7.7
