### ISSUE TITLE
Jumpy zooming by mouse wheel on IE

### ISSUE THREAD

**Issue by mohammadamin46bd** [Leaflet/Leaflet#5582]
There is a jumpy map zooming on IE (tested on IE 11) by mouse wheel. 
 Tested the map on IE from the below page:
http://leafletjs.com/

**Comment by IvanSanchez** [comment]
What does "jumpy" mean?

**Comment by perliedman** [comment]
This is a bit blurry capture of mouse wheel zooming in IE11 on my virtual Win7 machine running on Ubuntu. Even then it looks totally acceptable:

![leaflet-ie11-2017-06-26t12-31-29-297011000z](https://user-images.githubusercontent.com/1246614/27539343-822bd18e-5a7c-11e7-83a9-183b0cd51e84.gif)

I would suspect something weird with your setup if this causes trouble.
