### ISSUE TITLE
Newest Leaflet Version not working correctly with GoJS

### ISSUE THREAD

**Issue by n0gare** [Leaflet/Leaflet#5584]
Hello,

I am using Leaflet in combination with GoJS. I noticed that the example: http://gojs.net/latest/samples/leaflet.html seems to be outdated, because it is not working for the newest version of Leaflet. Dragging GoJS nodes will also drag the map which makes it difficult to reposition any nodes.
Check my fiddle https://jsfiddle.net/axp4cpc9/

I hope you can help me out!

Best Regards

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.
