### ISSUE TITLE
Documentation Link Broken in GitHub Pages

### ISSUE THREAD

**Issue by cnatis** [Leaflet/Leaflet#5585]
## How to reproduce
Go to http://leafletjs.com/ click "Docs" link in heading

## What behaviour I'm expecting and which behaviour I'm seeing
I am seeing a 404, I expect the documentation page as before

http://leafletjs.com/reference-1.0.3.html

**Comment by IvanSanchez** [comment]
Looking at this.

**Comment by IvanSanchez** [comment]
I don't understand. https://github.com/Leaflet/Leaflet/blob/master/docs/reference-1.0.3.html is still there.

**Comment by cnatis** [comment]
@IvanSanchez at least I can still view them for now in the repo, maybe an issue with github pages, but this was working yesterday before the 1.1.0 update

**Comment by IvanSanchez** [comment]
Yeah, I don't see any problem on the repo side of things. Please use http://leafletjs.com/reference-1.1.0.html in the meantime.

**Comment by IvanSanchez** [comment]
We've updated the link in the header to point to `1.1.0`, but the `1.0.3` docs still show a 404 error. I'll leave this open for a while to see if github pages magically decides to behave.

**Comment by cnatis** [comment]
Thank you for the quick response! Great work!

**Comment by ghybs** [comment]
As for the `1.0.3` broken page, could it be related to the missing Jekyll front matter in `1.1.0` page?
https://help.github.com/articles/configuring-jekyll/#front-matter-is-required

**Comment by IvanSanchez** [comment]
The front matter in 1.1.0 is fixed already at https://github.com/Leaflet/Leaflet/commit/11d716f0964d8bc0d058ca09e9ba8003451b4b8d , but the 1.0.3 docs still are a 404 :-( 😖

**Comment by ghybs** [comment]
I guess there is no specific Jekyll error message in the repo settings?
https://help.github.com/articles/viewing-jekyll-build-error-messages/#viewing-jekyll-build-failure-messages-in-your-repository

Might try to re-commit the file with a dummy modification?

**Comment by ghybs** [comment]
before attempting this blind fix, what about temporarily switching the GitHub pages settings to use a `gh-pages` branch again, see if it makes any difference?
Then we can switch back to `master/docs`?

**Comment by ghybs** [comment]
Here you go: https://github.com/Leaflet/Leaflet/tree/gh-pages
We can remove that branch again later on obviously…
Should we give it a try?

**Comment by flother** [comment]
The 'API documentation' link on the home page is broken too. That links to http://leafletjs.com/reference.html, which [exists in the repo as a redirect page](https://github.com/Leaflet/Leaflet/blob/master/docs/reference.html), but GitHub Pages returns a 404.

**Comment by perliedman** [comment]
@ghybs anything is worth a try right now, as far as I can tell...

I don't get any page build warnings from GitHub either, so I don't know what's going on. It's all very weird since we didn't really change anything except add a few pages, AFAIK.

**Comment by ghybs** [comment]
@perliedman I would try first to switch the settings for GH pages to `gh-pages` if you have not already (I do not have that permission obviously)

I have prepared the `gh-pages` branch a few minutes ago, it replicates the current `/docs` folder content.

**Comment by perliedman** [comment]
@ghybs oh, right. I've done it now. Unfortunately doesn't appear to change anything for me, `reference.html` still 404s, as well as `reference-1.0.3.html`.

Meanwhile, I also tried running Jekyll locally, and everything looks as expected, no 404s and the redirect works.

Thinking contacting GitHub support is probably the next sensible thing to do.

**Comment by perliedman** [comment]
@ghybs I've switched the setting back to `master/docs`, just to make everything set as we want it. I'll have to tend to family business for a while, but I'll try to revisit this later tonight.

**Comment by ghybs** [comment]
Ok then I will send the dummy PR on `reference-1.0.3.html`; if you want to give it a try, just merge it…

**Comment by perliedman** [comment]
I've contacted GitHub support, lets hope they can give some help on what's happening.

**Comment by perliedman** [comment]
This was resolved by GitHub support:

> I couldn't find anything on our end either so I rebuilt the site again just as a test and both those pages work as expected now
> [...]
> It is possible there was some congestion or something on our end that caused the build to not complete successfully.
> Please let us know if it happens again.

Thanks to all here for reporting and working to fix this!
