### ISSUE TITLE
Logic to remove Leaflet's double tap listener for dispatching simulated dbclick events presumes that such a listener exists, when it might not.

### ISSUE THREAD

**Issue by hanginwithdaddo** [Leaflet/Leaflet#5588]
## How to reproduce

- Leaflet version I'm using: 1.0.3 and 1.1.1
- Browser (with version) I'm using: Microsoft Edge on a Windows 10 Tablet
- OS/Platform (with version) I'm using: Windows 10 Tablet

The logic to remove Leaflet's double tap listener for dispatching simulated dbclick events presumes that such a listener exists, when it might not. Leaflet 1.0.3 and Leaflet1.1.0 only add such a listener if the browser is not a pointer-based browser and is not Chrome, however the removal logic fails to take this into account, resulting in Javascript errors.

See lines 2234 and 2281 and of Leaflet 1.1.0/leaflet-src.js

Line 2234, inside function addOne():
	} else if (touch && (type === 'dblclick') && addDoubleTapListener &&
	           !(pointer && chrome)) {
		// Chrome >55 does not need the synthetic dblclicks from addDoubleTapListener
		// See #5180
		addDoubleTapListener(obj, handler, id);

Line 2281, inside function removeOne():
	} else if (touch && (type === 'dblclick') && removeDoubleTapListener) {
		removeDoubleTapListener(obj, id);

Line 2281 is missing the pointer and chrome conditions from line 2234. This leads to Javascript errors when removing client-based dblclick listeners for pointer-based browsers, such as Microsoft Edge.

## Minimal example reproducing the issue

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

Using http://playground-leaflet.rhcloud.com/ or any other jsfiddle-like site.

**Comment by perliedman** [comment]
Can you please post code showing what steps that reproduce this problem?

Also, the line numbers you have refer to the built Leaflet files - I think I can find out, but for the future it's a lot less trouble if you refer to the source files in question instead.

**Comment by hanginwithdaddo** [comment]
I can't really post an example. Just look at the addOne() and removeOne() methods used to add the double tap listener. The extra condition is missing from the removeOne() method. I added this locally to my copy of the Leaflet 1.0.3 source and the crash went away.

**Comment by hanginwithdaddo** [comment]
The reason I can't post a simple example at the moment is that I ran into this using the Leaflet Draw plugin running on a Windows 10 tablet using Microsoft Edge, and I don't have this device in my possession at the moment. The earliest I would be able to do this will be next Wednesday. I will try to find the exact source module where this change needs to be made, however.

**Comment by hanginwithdaddo** [comment]
The sections of Leaflet 1.1.0 code you need to look at are in srce/DomEvent.js. The first if statement, which contains the correct (new) logic is at line 90 in the addOne() method.

	} else if (Browser.touch && (type === 'dblclick') && addDoubleTapListener &&
	           !(Browser.pointer && Browser.chrome)) {
		// Chrome >55 does not need the synthetic dblclicks from addDoubleTapListener
		// See #5180
		addDoubleTapListener(obj, handler, id);

The second if statement, which is missing the !(Browser.pointer && Browser.chrome) condition, is at line 137 in the removeOne() method.

	} else if (Browser.touch && (type === 'dblclick') && removeDoubleTapListener) {
		removeDoubleTapListener(obj, id);
I don't have the original source for Leaflet 1.0.3, but a similar problem exists there, but the method names are _on() and _off() respectively, and I believe in the same source module.
I hope this helps. Please let me know if you would still like me to take the time to create a simple example with which you can test this change.
Thanks again for looking into this issue!
Dave

**Comment by perliedman** [comment]
Ok, thanks, I think I follow along now. I've submitted #5598 that will hopefully take care of this. If you have the opportunity, it would be a great help if you could verify this fixes the issue.

**Comment by hanginwithdaddo** [comment]
I'll be glad to test this on Wednesday when I'm back in the office and get access to the Windows 10 tablet. Thanks again for making this change!

**Comment by hanginwithdaddo** [comment]
For some reason, I can't seem to build Leaflet. Running jake produces the output below, which seems ok, but when I look in the "dist" directory, the only thing present is the images directory and leaflet.css.

See the output below. What am I doing wrong (feeling kind of stupid)?
[jake.txt](https://github.com/Leaflet/Leaflet/files/1115313/jake.txt)

**Comment by perliedman** [comment]
You're using the old way to build. These days, run `npm run build` to build, or `npm run watch` if you want to build a continuously re-build for changes in the Leaflet source.

Some more details in the contribution guide: https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md#using-rollupjs

**Comment by hanginwithdaddo** [comment]
I just ran: npm run-script rollup
since all I need are the combined .js files, but I am now seeing the errors in the following log file for some reason.

[npm-debug.txt](https://github.com/Leaflet/Leaflet/files/1115611/npm-debug.txt)

Feeling really stupid again. :O(

Also, you might consider updating the comment at the top of Jakefile.js, since it still refers to the old way of "building" ... it also refers to a build/build.html file that no longer seems to exist.
Sorry for all the trouble.

**Comment by hanginwithdaddo** [comment]
@perliedman I apologize for not getting back to you sooner. I've been away for a number of weeks and finally had a chance to go back to this. I looked at your change it is the same that I made locally to a copy of Leaflet 1.0.3 and I know works. Given that I found this while using the Leaflet.Draw plugin, I can't test this until "Fix non-extendable objects regression of 1.1.0 #5658" gets pushed out as part of an official build. The draw plugin chokes because or #5658. At this point, I suggest merging this change into master so that it is available for the next release. Again, please accept my apologies.
Dave
