### ISSUE TITLE
L.DomEvent.disableScrollPropagation returns nothing

### ISSUE THREAD

**Issue by Eschon** [Leaflet/Leaflet#5594]
## How to reproduce

- Leaflet version I'm using: 1.1.0
- Browser (with version) I'm using: Chrome Version 59.0.3071.109
- OS/Platform (with version) I'm using: Mac OS X 10.11.6

I came across this problem when using a modified version the [Rrose Plugin](https://github.com/erictheise/rrose).
I reduced the code as much as possible for a reproduction example:
http://playground-leaflet.rhcloud.com/bijew/edit?html,console,output

The part of the code that causes the Problem is this:
```
L.DomEvent
    .disableClickPropagation(wrapper)
    .disableScrollPropagation(this._contentNode)
    .on(wrapper, 'contextmenu', L.DomEvent.stopPropagation);
```

Changing it to 
```
L.DomEvent
    .disableClickPropagation(wrapper)
    .disableScrollPropagation(this._contentNode);
L.DomEvent.on(wrapper, 'contextmenu', L.DomEvent.stopPropagation);
```
fixes the Problem. 

Prior to 1.1.0 this worked and the [Documentation](http://leafletjs.com/reference-1.1.0.html#domevent) states that `disableScrollPropagation` should return this (which should be `L.DomEvent`).

**Comment by IvanSanchez** [comment]
Looks like we missed a `return this` during the rewrite to ES2015 modules, see https://github.com/Leaflet/Leaflet/blob/v1.1.0/src/dom/DomEvent.js#L182 and `disableClickPropagation` a few lines below.

This looks like an easy fix. @Eschon would you like to submit a pull request?

**Comment by Eschon** [comment]
@IvanSanchez Thanks for the quick reply!  
Sure I can try to make a PR.

**Comment by IvanSanchez** [comment]
Thanks for the PR :-D

I think there is a bigger issue here - in a ES2015 module, `this` doesn't have any meaning as far as I recall. Chaining stuff will not be possible using modules :-/

**Comment by perliedman** [comment]
@IvanSanchez not sure I follow - when do we / would we want to chain using modules? Chaining seems to me to be something you do with an object's methods, where `this` has meaning, but I guess I'm missing some possible new feature here?

Anyway, I hope it's ok to close this and open a new issue if module chaining (or the lack of it) is something we need to discuss further.

**Comment by perliedman** [comment]
@IvanSanchez disregard my comment above. Reviewing #5601, it dawned on me what you mean, since `DomEvent` is not really a class any more, but actually a module with exported functions. This is indeed something to think about going ahead.

**Comment by lasersox** [comment]
https://github.com/yafred/leaflet-responsive-popup

This issue breaks responsive.popup plugin.
