### ISSUE TITLE
有没有判断此面的范围在地图范围之间的函数

### ISSUE THREAD

**Issue by Jerry-goodboy** [Leaflet/Leaflet#5603]
leaflet的版本是 1.0.3
我现在需要这样的一个功能，就是根据地图不同的缩放级别来动态的显示面状要素的遮罩层（也是一个地图服务图层），目前的思路是，根据zoomend事件来动态的请求后端的地图服务，将该面状要素的范围extent或者是bounds返回来，再获取当前地图的范围extent或者是bounds，然后再比较两者的大小，目前我急需要的是这个比较大小的函数，我在API文档中并未找到此类函数

**Comment by Jerry-goodboy** [comment]
@michael @kshepard @palewire @naehrstoff @klaftertief

**Comment by perliedman** [comment]
Sorry, but issues have to be written in english to be considered.
