### ISSUE TITLE
Leaflet maps return fragment zoom level with zoomSnap  = 1

### ISSUE THREAD

**Issue by omerh86** [Leaflet/Leaflet#5605]
Hi,
leaflet version 1.0.3
platform Android , IOS.

Im getting fragment zoom levels when calling getZoom().
I have tried using zoomSnap = 1 and most of the times(95%) i get an integer, however sometimes the zoom sets to be a fragment. 
Is there a way using leaflet configuration to prevent getting by all means fragment zoom property?

Thanks Omer

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by IvanSanchez** [comment]
Oh, and I see this is cross-posted as https://stackoverflow.com/questions/44921459/is-leaflet-maps-can-work-only-with-integer-zoom-level

**Comment by omerh86** [comment]
This is a link to palyground, it is dosnt occur in browsers only on devices such as Android, IOS.
basically I am not doing more then call getZoom() on the "moveend" event.
as i said before it happens rarely  (around 5% of the times of pinching out and in).

https://playground-leaflet.rhcloud.com/sobi/1/edit?html,console,output

Thanks

**Comment by IvanSanchez** [comment]
What about using the `zoomend` event instead?

**Comment by omerh86** [comment]
zoomend works fine.
not exactly what i need but i will handle. 
Thanks
