### ISSUE TITLE
markerZoomAnimation = false does not work as expected on mobile browser

### ISSUE THREAD

**Issue by dnasir** [Leaflet/Leaflet#5606]
## How to reproduce

- Leaflet version I'm using: 1.1.0
- Browser (with version) I'm using: Chrome for Android 50.0.2661.89
- OS/Platform (with version) I'm using: Android 6.0.1
- step 1 Load a map with 400 markers
- step 2 Start pinch to zoom

## What behaviour I'm expecting and which behaviour I'm seeing
- Expected - Markers should disappear during pinch duration
- Reality - Markers do not disappear, but instead shifts around during pinch duration

## Minimal example reproducing the issue

[Video demonstrating the issue](https://goo.gl/photos/XnYH6U5ipC6x46aL9)

**Comment by dnasir** [comment]
I suspect it's due to `.leaflet-zoom-anim` class being added **after** the touch events have ended.

**Comment by perliedman** [comment]
Zoom animation does not turn of markers during pinch zoom. Zoom animation affects the CSS animation when the map is zoomed using the zoom controls, keyboard zoom or mouse wheel zoom. Pinch zoom is not done using the same CSS animation, so it will not be affected.

I'm not sure from just seeing your example, but it looks like something weird is going on - might it for example be that you have a CSS `transition` property set that affects Leaflet's markers?

Test pinch zooming in this example, which at least for me performs differently: http://playground-leaflet.rhcloud.com/wekav

**Comment by dnasir** [comment]
@perliedman Yes, I have a marker style that handles marker movement animation. Specifically `transition: transform 0.5s linear`. I need this to make sure the marker moves smoothly across the map when a new set of coordinates is set.

I've tried turning this off, and yes, it did solve the issue. But then my markers are jumping from one spot to another. Any ideas on how I can maintain the smooth transition, whilst also fixing the problem?

**Comment by perliedman** [comment]
The first idea that comes to mind is just adding the transition class when you're actually moving the markers. That's pretty much what Leaflet does with the `leaflet-zoom-anim` class - add it when a zoom animation is ongoing.

You could possibly do this by inheriting from `L.Marker` and overriding its `setLatLng` method to achieve this.

Anyway, closing since I don't think this is a Leaflet bug but rather a question on how to use Leaflet from here on.
