### ISSUE TITLE
Cancel tile requests in _onTileRemove

### ISSUE THREAD

**Issue by jbccollins** [Leaflet/Leaflet#5609]
## How to reproduce

- Leaflet version I'm using: 1.1.0
- Browser (with version) I'm using: Google Chrome
- OS/Platform (with version) I'm using: Windows 10

## What behaviour I'm expecting and which behaviour I'm seeing

My jsfiddle demonstrates the issue. You can see what I'm talking about if you open up the network tab of the developer console and disable browser caching.

The zoomend event in my fiddle will trigger a url change for the tile layer (toggle between normal osm tiles and greyscale osm tiles). Despite the tile url changing the requests for tiles using the old url are not canceled.  While this is not a huge issue when using osm tiles (osm is super fast and caching is done well) it affects my production use case where our tiler uses dynamic tiling to generate "up to the minute" tiles. Tile generation is not cached and is kinda slow (which is outside of my control unfortunately) and stacking these kind of tile requests puts a burden on our server. If you examine the network tab when using my jsfiddle you will see that on zoomend both the greyscale and normal osm tile requests are completed although one of them will not be necessary.

Right now Leaflet currently will cancel some tile requests via the [_abortLoading](https://github.com/Leaflet/Leaflet/blob/6bfa764cb08d1010c13dc71b2050e457a4c0ad3d/src/layer/tile/TileLayer.js#L230) function by overriding the src attribute of the tile png when conditions dictate that a tile is no longer visible. I propose changing the _onTileRemove function in TileLayer.js to do something similar.

```javascript
  _onTileRemove: function (e) {
    e.tile.onload = null;
    e.tile.setAttribute('src', L.Util.emptyImageUrl); // add this line
  },
```

## Minimal example reproducing the issue
http://jsfiddle.net/yzsgdq13/3/
- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by perliedman** [comment]
Hi, thanks for reporting. This does indeed sound reasonable: there is no reason to continue loading tiles when settings a new URL.

From a quick look, it looks like setting a new URL with `setUrl` normally causes a `redraw` - although your suggested change looks reasonable, perhaps `redraw` should call `_abortLoading` (if available), since there is no reason to continue loading if the tiles should be requested again (as the docs for `redraw` says).

Anyway, I would be open to merging this change if you supply a pull request!

**Comment by jbccollins** [comment]
@perliedman The conditions that ` _abortLoading` checks are not conditions that will be triggered by this particular edge case. I could try to dig deeper and modify ` _abortLoading` to handle all cases where we want to abort a tile but imo that would probably be overkill and outside the scope of what ` _abortLoading` was written to do. Would you be opposed to me changing ` _removeTile` in GridLayer.js to be

```javascript
  _removeTile: function (key) {
    var tile = this._tiles[key];
    if (!tile) { return; }

    tile.el.setAttribute('src', L.Util.emptyImageUrl); // Add this line
    DomUtil.remove(tile.el);

    delete this._tiles[key];

    // @event tileunload: TileEvent
    // Fired when a tile is removed (e.g. when a tile goes off the screen).
    this.fire('tileunload', {
      tile: tile.el,
      coords: this._keyToTileCoords(key)
    });
  }
```

instead of putting that line in `_abortLoading` or `_removeTile`?

**Comment by perliedman** [comment]
Ok, thanks for the analysis. I think we can go with a PR like that, probably just add a comment that this line exists to abort loading removed tiles.

**Comment by perliedman** [comment]
Closing this since #5615 was merged!
