### ISSUE TITLE
Tiles are pruned when map zoom is smaller than tile/grid zoom

### ISSUE THREAD

**Issue by hauke76** [Leaflet/Leaflet#5611]
## How to reproduce

- Leaflet version I'm using: 1.0.3+ed36a04
- Browser (with version) I'm using: Chrome 59.0.3071.115
- OS/Platform (with version) I'm using: Win 10
- Step 1: Create a L.map() with minZoom = -2.
- Step 2: Add a L.tileLayer() (GridLayer) with minZoom = 1

## What behaviour I'm expecting and which behaviour I'm seeing
When I zoom out and have a negative map zoom value, I would like to retain the already existing low res tiles. Instead the tiles are pruned and nothing is rendered anymore.

I have traced the behavior to GridLayer._pruneTiles().

The first part of that function prunes tiles which are not within the current zoom level.
```javascript
var zoom = this._map.getZoom();
if (zoom > this.options.maxZoom ||
  zoom < this.options.minZoom) {
  this._removeAllTiles();
  return;
}
```

Switching this to
```javascript
var zoom = this._map.getZoom();
if (zoom > this._map.getMaxZoom() ||
  zoom < this._map.getMinZoom()) {
  this._removeAllTiles();
  return;
}
```
results in the expected behavior.

I am asking here before I create a pull request since I am not sure if this change would break other use cases.

**Comment by perliedman** [comment]
Hi,
that change does not look like it's going to work: the layer should follow its own `maxZoom` and `minZoom`, not its associated map: a layer can well have other limits than the map (for example when you have several layers with different available zoom levels).

It sounds like what you want is the [`minNativeZoom` option](http://leafletjs.com/reference-1.1.0.html#gridlayer-minnativezoom), which allows you to keep zoomed out versions of tiles from inner zoom levels.

**Comment by hauke76** [comment]
Hi Per,

thanks for pointing out minNativeZoom. I totally overlooked that option and it works like a charm.

Thanks,
Hauke
