### ISSUE TITLE
Geojson path was rendered at wrong position!

### ISSUE THREAD

**Issue by wanqiuchansheng** [Leaflet/Leaflet#5623]
- Leaflet version :"^1.1.0"
- Browser: Chrome 57.0.2987.133 (64-bit)  and MS edge
- OS/Platform: Windows 10
I want to add geojson paths on the map but it was likely rendered at the wrong position.

this is my code
```javascript
        import L from "leaflet"
          import wtrshed from "./assets/ch_wtrshed.json"
          let myMap = L.map("mapid",
                {zoomDelta: 0.5, zoomSnap: 0, zoomControl: false}
            ).setView([22, 98], 7);
            
//tile
            let tile = L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
                maxZoom: 18,
                attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, ' +
                '<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
                'Imagery © <a href="http://mapbox.com">Mapbox</a>',
                id: 'mapbox.streets',
                attributionControl: false,
            })
            tile.addTo(myMap);
            //this is geojson
            let geoJson = wtrshed.features
            L.geoJSON(geoJson, {
                style: {
                    "className": "basin-area"
                },
                onEachFeature: function (feature, layer) {
                    layer.on({
                        click: function () {
                            console.log(feature.properties.WRRNM)
                        }
                    })
                }
            }).addTo(myMap);
```
this is result
![image](https://user-images.githubusercontent.com/9635433/28066858-4d8b5340-6671-11e7-9ced-119cc9bc1adf.png)

when I zoom, there seems to be a constant offset in pixels.
![9 8 ddm2 1 l0u5p 5](https://user-images.githubusercontent.com/9635433/28067136-917c2ef2-6672-11e7-8b0a-aa410d6aed31.png)

**Comment by ghybs** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by perliedman** [comment]
Closing for now, happy to re-open when we get more information on the issue!

**Comment by mvl22** [comment]
Your data in `ch_wtrshed.json` is almost certainly in the wrong co-ordinate projection, resulting in the offset. Ensure it it is WGS84, and everything is then likely to line up. Not a leaflet bug.
