### ISSUE TITLE
Problem with leaflet

### ISSUE THREAD

**Issue by giorgim** [Leaflet/Leaflet#5624]
I have react project with leaflet.
All was going ok, till I removed the project from my PC and cloned it again.
Now after running npm install and npm start I get following errors in web console:

> 
> Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead. Error
>     at checkDeprecatedMixinEvents (http://localhost:3000/static/js/bundle.js:34989:48)
>     at Function.Class.extend (http://localhost:3000/static/js/bundle.js:34917:4)
>     at http://localhost:3000/static/js/bundle.js:194065:2039
>     at Object.<anonymous> (http://localhost:3000/static/js/bundle.js:194066:30421)
>     at __webpack_require__ (http://localhost:3000/static/js/bundle.js:556:30)
>     at fn (http://localhost:3000/static/js/bundle.js:87:20)
>     at Object.<anonymous> (http://localhost:3000/static/js/bundle.js:33846:2)
>     at __webpack_require__ (http://localhost:3000/static/js/bundle.js:556:30)
>     at fn (http://localhost:3000/static/js/bundle.js:87:20)
>     at Object.<anonymous> (http://localhost:3000/static/js/bundle.js:33276:16)

> 
> Uncaught TypeError: Can't add property segmentsIntersect, object is not extensible
>     at Object.extend (bundle.js:34619)
>     at bundle.js:194066
>     at Object.<anonymous> (bundle.js:194066)
>     at __webpack_require__ (bundle.js:556)
>     at fn (bundle.js:87)
>     at Object.<anonymous> (bundle.js:33846)
>     at __webpack_require__ (bundle.js:556)
>     at fn (bundle.js:87)
>     at Object.<anonymous> (bundle.js:33276)
>     at __webpack_require__ (bundle.js:556)

Could someone help?

**Comment by mourner** [comment]
Thanks for the report! Can you please set up a minimal test case that reproduces the issue? Currently there is not enough information to indentify and fix it (if it's on Leaflet side, which is unlikely).

**Comment by giorgim** [comment]
@mourner It seemed to be inconsistency of versions of leaflet and leaflet.draw.

Currently I am using these versions and it is working OK

    "leaflet": "1.0.3",
    "leaflet-draw": "0.4.10",
