### ISSUE TITLE
Improve L.Draggable event binding on DOM

### ISSUE THREAD

**Issue by idawave** [Leaflet/Leaflet#5630]
I've run into a situation where I have to instanciate a **L.Map** into a container (a \<div>) that I do not master, and which is given to me by an SDK.

The issue is that the container already come with some events, and one is a `mousemove` which is doing an `event.stopPropagation()` in its handler.
It results with this behaviour: as long as the mouse is over the container, map panning does not work.
I found out that this is due to the fact the **L.Draggable**, responsible for map panning, only binds its events to the `document` element.
Of course in my case, trying to modify/remove event handlers on the container is not an option.

This is happening with **Leaflet 1.0.3**.

However, I consider this behaviour as very specific, but still it might happen to some other persons in the future.
For this matter, I have enhanced the **L.Draggable** (and **L.Map.BoxZoom**) to overcome the issue described above.
You can find it there: https://github.com/idawave/Leaflet.DraggableEnhancer
The concept is pretty neat, **L.Draggable** binds events on both document and L.Map._container, then some side-effects are handled here and there.

I would have submitted this as an "Suggested Evolution" if I could.
Do you think it is worthy to try a pull request?

Cheers.
Vincent

**Comment by perliedman** [comment]
Hi,
interesting use case and really cool that you managed to solve it without too many hacks! I must say it sounded more or less impossible after reading your introduction.

I would suggest you add this to the plugin page as it is now. Given that this solves a quite narrow use case, I'm reluctant to change the design of a core part of Leaflet like this: it would require a lot of testing to see what consequences this would have for other apps, browsers and use cases.

**Comment by idawave** [comment]
Ok works for me.

I'll PR my workaround and add it to the plug-in list.

Cheers.
Vincent
