### ISSUE TITLE
The map will drift when I click on the largest layer of the mouse

### ISSUE THREAD

**Issue by shanligang** [Leaflet/Leaflet#5632]
The map will drift when I click on the largest layer of the mouse

**Comment by ghybs** [comment]
Hi,

If you still have your problem and you are sure this is a bug in Leaflet, please open a new issue and make sure you comply with all requirements in the issue template.

In particular, please provide steps to reproduce your problem, ideally provide a live test case (e.g. using Leaflet [playground](http://playground-leaflet.rhcloud.com/)) and specify your OS and browser with versions.
