### ISSUE TITLE
Remove sourceMappingUrl line from dist/leaflet.js file

### ISSUE THREAD

**Issue by RhinoDevel** [Leaflet/Leaflet#5642]
To avoid browser trying to load leaflet.js.map file,
do not include following line in leaflet.js file for release/dist build:

//# sourceMappingURL=leaflet.js.map

Tested with Windows 10 and Firefox 54.0.1.

**Comment by ghybs** [comment]
Hi,

Thank you for your suggestion.

This sounds like a direct conflict with https://github.com/Leaflet/Leaflet/issues/5341.

> To avoid browser trying to load leaflet.js.map file

but (from https://github.com/Leaflet/Leaflet/issues/5341#issuecomment-280721002):

> The browser only pulls the map from the network if devtools are open

That statement seems like a good compromise to me, unless it is not true?

**Comment by RhinoDevel** [comment]
@ghybs Thanks for your comment.

I just confirmed that the browser really loads source maps only,
if the developer tools are open (as written here: [html5rocks.com](https://www.html5rocks.com/en/tutorials/developertools/sourcemaps/).
I used Firefox and Chrome.

Sorry for the noise - my fault!
