### ISSUE TITLE
how do I overlap tiles inside map one after another tile with margin of -10px each side

### ISSUE THREAD

**Issue by Akshay-Hegde** [Leaflet/Leaflet#5645]
Hi ! I am creating marker tiles (276x276) run time, as I got so many points to show, client side rendering hangs browser, and marker cluster doesn't fit my application, I even tried wms single tile layer, which has issue while adding multiple image overlay.

Sso here is my issue, its working very well except point symbols close to tile **edges are cut**, I referred issue on SO : https://gis.stackexchange.com/questions/198450/need-clarification-on-geoserver-meta-tile and tried to create tiles with extra space, my problem is **how do I overlap tiles inside map one after another tile with margin of -10px each side**, yellow color represents actual tilesize, and red color is after adding 10px to each side

You are welcome, if you have any better solution for my problem, only symbols close tile edges are cut, as you can see below (  **with gutter = 0** )
![map_0_gutter](https://user-images.githubusercontent.com/7464492/28366906-4178067a-6cac-11e7-9885-d105a8a10a50.png)

(  **with gutter = 20, This is what I tried, generated tiles of 276x276** )
![map](https://user-images.githubusercontent.com/7464492/28366485-938b83bc-6caa-11e7-9145-753f9c6a05f1.png)
![map_edge](https://user-images.githubusercontent.com/7464492/28366497-a15cc03c-6caa-11e7-81ce-779d788b0cbe.png)

**Below tile is of 276x276**
![7](https://user-images.githubusercontent.com/7464492/28366696-797f92a0-6cab-11e7-82dc-a7544c553c4b.png)

**Comment by ghybs** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in Leaflet, or a feature request, please [change the wording to make it look like a bug report / feature request](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by Akshay-Hegde** [comment]
@ghybs Oh thank you, I modified title as you suggested
