### ISSUE TITLE
Mouse events not passed to underlying layer when using DivIcon

### ISSUE THREAD

**Issue by a1an77** [Leaflet/Leaflet#5648]
## How to reproduce

- Leaflet version I'm using: 1.1.0
- Browser (with version) I'm using: FF 50.1.0
- OS/Platform (with version) I'm using: Windows7 Pro
Add a divIcon with text to a marker
add the parker to a map over a polygon with event handlers (mouseover,mouseout)
hover on the marker's text

## What behaviour I'm expecting and which behaviour I'm seeing
I am trying to use a Marker which lets events through it (especially mouseover) so that the event is caught by an underlying polygon but It seems the event does not get through. It is probably due to the divIcon inside the marker wich should either also support bubblingMouseEvents or inherit behaviour from the marker holding it.

## Minimal example reproducing the issue

https://jsfiddle.net/A1an/8d7cehkr/

Marker is added to map on mouseover and removed on mouseout, when hovering over the text the events are not passed on to the underlying polygon (the marker disappears from the map)

**Comment by perliedman** [comment]
Hi!

You can easily work around this by using `pointer-events: none` on the HTML elements in your `DivIcon`, so that they do not catch the events themselves.

See my modified version of your sample: https://jsfiddle.net/azwd47qx/

**Comment by a1an77** [comment]
pointer-events: none will affect all events, I am looking for a way to pass on certain events (mouseover) but catch other events (click) on the marker.
