### ISSUE TITLE
in 1.1.0 all objects are non extendable

### ISSUE THREAD

**Issue by calvinmetcalf** [Leaflet/Leaflet#5650]
summing up #5643 and #5589, due to how the exports are done with the switch to rollup the leaflet objects are now all non extendable, so no plugin can add a new method to `L` or `L.Util`. 

Suggestions: republish 1.0.3 as 1.1.1 ASAP, this will prevent things from breaking, then either publish 1.1.0 as 2.0.0 or redo the switch to rolllup avoiding using `import * as foo from 'bar'` and `export * from 'foo'`;

**Comment by calvinmetcalf** [comment]
republishing 1.0.3 as 1.1.1 is the new version of unpublished which you really aren't allowed to do anymore.

**Comment by perliedman** [comment]
@mourner @IvanSanchez any input on the ES6 changes here, and what our best options going forward are? I can see there was a lot of discussion in #4989, is this something you considered?

**Comment by mourner** [comment]
@perliedman haven't realized we would have this problem. I think we should do a patch 1.1.1 release, but maybe we could do away with a simpler hack than rewriting all export hack? One thing I would try is redefining `Object.freeze` before the rollup modules code do be noop and then restoring it after.
