### ISSUE TITLE
what algorithm goes leaftlet use for drawing polygon ?

### ISSUE THREAD

**Issue by Atulvermaon18** [Leaflet/Leaflet#5656]
## How to reproduce

- Leaflet version I'm using:
- Browser (with version) I'm using:
- OS/Platform (with version) I'm using:
- step 1
- step 2

## Minimal example reproducing the issue

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

Using http://playground-leaflet.rhcloud.com/ or any other jsfiddle-like site.

**Comment by perliedman** [comment]
Hi there! I'm not sure I understand the question. Leaflet uses the concept of a "renderer" to draw its vector features, built-in renderers use either SVG or Canvas, so exactly how polygons are drawn is up to the browser's SVG or Canvas implementation.

Also, please note that this is an issue tracker for bugs and new features, not a support forum. If you have questions on using Leaflet, you're better off asking on Stackoverflow or GIS Stackexchange.
