### ISSUE TITLE
Map scale bar should be mandatory/default in all maps!

### ISSUE THREAD

**Issue by eMPee584** [Leaflet/Leaflet#5657]
Ok sorry to violate your bug reporting rules, but this makes me really _angry_.
It was a stupid idea when Google removed scales from embedded maps, and regardless of who else it does, it is still an incredibly stupid idea.
**PLEASE**. Stop the madness. Put the scale bar back on every embedded map.

**Comment by eMPee584** [comment]
Oh. Sorry. This actually is a google map. It just has a leaflet overlay or something.
So, you probably can't do anything about this.
#### google for this ####™ - .

**Comment by eMPee584** [comment]
Ok, so this is not only for Google Maps. No scale on a leaflet OpenStreetMap: https://www.reparatur-initiativen.de/widgets/map.php
Maps without scale = unacceptably crippled & just _wrong_. How could this ever become default?

**Comment by eMPee584** [comment]
Rational?

**Comment by perliedman** [comment]
@eMPee584 hi, I can sympathize with a scale bar being pretty useful in a lot of cases. On the other hand, it's pretty apparent this is far from always the case, especially for casual web mapping.

Leaflet does include a scale control that can very easily be included for those that like it in their maps, but it's not something we will enforce.
