### ISSUE TITLE
Pass through mouse events to leaflet causes errors in chrome

### ISSUE THREAD

**Issue by Qrokqt** [Leaflet/Leaflet#5663]
## How to reproduce

- Leaflet version I'm using: both 1.0.3 and 1.1.0
- Browser (with version) I'm using: Works in Firefox, broken in Chrome
- OS/Platform (with version) I'm using: Windows
- Click and drag in the grey box

## What behaviour I'm expecting and which behaviour I'm seeing
I'd expect to be able to drag the map around through the box. This works in firefox but not chrome.

## Minimal example reproducing the issue
https://jsfiddle.net/e4ypxher/1/ leaflet 1.0.3
https://jsfiddle.net/e4ypxher/2/ leaflet 1.1.0

**Comment by perliedman** [comment]
Hi and thanks for reporing!

However, I fail to see how this is a Leaflet issue. It looks like the canvas and event handling only use direct browser functionality, and nothing specific to Leaflet. 

Could you be a bit more specific on what you think the issue with Leaflet is here?

**Comment by Qrokqt** [comment]
I'm getting this error in chrome but not in firefox:

```
LatLng.js:28 Uncaught Error: Invalid LatLng object: (NaN, NaN)
    at LatLng (LatLng.js:28)
    at Object.unproject (Projection.SphericalMercator.js:33)
    at Object.pointToLatLng (CRS.js:37)
    at NewClass.unproject (Map.js:933)
    at NewClass._onTouchMove (Map.TouchZoom.js:90)
    at handler (DomEvent.js:81)
    at _handlePointer (DomEvent.Pointer.js:110)
    at HTMLDocument.onMove [as _leaflet_touchmovetouchmove54_24] (DomEvent.Pointer.js:118)
    at HTMLCanvasElement.canvas.addEventListener ((index):98)
```

**Comment by Qrokqt** [comment]
It seems like the `pointerdown` event doesnt trigger `_onTouchStart` which the `pointermove` event requires before it can work?

**Comment by Qrokqt** [comment]
Turned out I was using the wrong event Interface for touches and pointers, which Firefox fixed for me behind the scenes. Here's the working example: https://jsfiddle.net/dzx0vqc6/1/
