### ISSUE TITLE
Please provide Marker/Popup 's style

### ISSUE THREAD

**Issue by tomsue** [Leaflet/Leaflet#5666]
Please provide Marker/Popup's style,

I need to implement change Popup's backgroundColor. but leaflet no this properties. please improve it.

`<Marker position={XX} style={{backgroundColor:"yellow"}}>{yellow no working}
      <Popup style={{backgroundColor:"blue"}}> {blue no working}
                <div>
                       <div>{"2008:08:08"}</div>
                       <div style={{backgroundColor:"white"}}>{item.status}</div>
                </div>
       </Popup>
  </Marker>`

![image](https://user-images.githubusercontent.com/5195809/28708498-11f73916-73af-11e7-88a8-eee217073da9.png)

**Comment by yohanboniface** [comment]
Hi,

Thanks for using Leaflet.
If I understand you correctly, you want to change the popup style. This is done very easily with css.
You can either add css rules for the `.leaflet-popup` class, or add a custom css class when needed using the [className](http://leafletjs.com/reference-1.1.0.html#popup-classname) option.

**Comment by tomsue** [comment]
it's no right.

it's internal class(.leaflet-popup-content-wrapper) ; i can't use className to using my css.

`<Marker>
                                    <Popup className={"leaflet-popup-content-wrapper-gray"}>
                                        <div>
                                            <div><strong  style={{color: "white"}}>{item.time}</strong></div>
                                            <div style={{backgroundColor:"white", textAlign:"center"}}><strong>{item.status}</strong></div>
                                        </div>
                                    </Popup>
                                </Marker>`


![image](https://user-images.githubusercontent.com/5195809/28711328-df787882-73b9-11e7-85aa-ae855775ebd6.png)
 



![bb](https://user-images.githubusercontent.com/5195809/28711594-b065ff50-73ba-11e7-89e3-47f7d3e5b058.png)

**Comment by tomsue** [comment]
please reopen

**Comment by yohanboniface** [comment]
This issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

As an example for you to dig in, see http://playground-leaflet.rhcloud.com/covos/edit?html,output

**Comment by tomsue** [comment]
if I use overwrite style, I just implement one style on one page. But I need to manually using my style. One page need some  popup  in another style. For example one popup backgroudColor is red...blue...yellow etc..... I can't implement.
