### ISSUE TITLE
TileLayer url documentation rendered misses some text

### ISSUE THREAD

**Issue by jieter** [Leaflet/Leaflet#5668]
While looking into a retina issue at leaflet-providers, I noticed that part of the text of the `L.TileLayer` documentation is missing.

[the rendered html looks like this](http://leafletjs.com/reference-1.1.0.html#tilelayer-url-template):

> A string of the following form:
> ```
> 'http://{s}.somedomain.com/blabla/{z}/{x}/{y}{r}.png'
> ```
> You can use custom keys in the template, which will be evaluated from TileLayer options, like this:
> ```
> L.tileLayer('http://{s}.somedomain.com/{foo}/{z}/{x}/{y}.png', {foo: 'bar'});
> ```

but the entire [line 29](https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/TileLayer.js#L29) is missing.

@IvanSanchez probably a leafdoc issue?

**Comment by ghybs** [comment]
Hi,

Nice catch!

Indeed it seems that "`@`" (configured to be the leading character for [leafdoc](https://github.com/Leaflet/Leafdoc)) in the docstring makes the entire line being ignored.
A simple workaround for now is to replace it by an equivalent HTML entity, e.g. "`&commat;`"

**Comment by ghybs** [comment]
@jieter opened https://github.com/Leaflet/Leafdoc/issues/33 to follow up this issue on Leafdoc.

Notifying in case you are interested in participating or subscribing.
