### ISSUE TITLE
geoJson resetStyle is not working in leaflet version 1.0

### ISSUE THREAD

**Issue by astridx** [Leaflet/Leaflet#5674]
I use [geojson-resetstyle]( http://leafletjs.com/reference-1.1.0.html#geojson-resetstyle ) in my map.
I like to see a different style, when I hovering the layer. This works well. 
But the reset after mouseout does not work.

Is this a bug or do I make a mistake?

http://playground-leaflet.rhcloud.com/kexo/1/edit?html,output

**Comment by perliedman** [comment]
Hi!

You should use `e.layer` instead of `e.target` for this, except for this your code is correct!

**Comment by perliedman** [comment]
An updated version of your example: http://playground-leaflet.rhcloud.com/vubi/edit?html,output

**Comment by yohanboniface** [comment]
`e.target` is the geojson layer itself, you should use `e.layer` instead:

```javascript
geoJsonLayer.on('mouseout', function(e) {
    geoJsonLayer.resetStyle(e.layer);
});
````

**Comment by yohanboniface** [comment]
Oops, late to the party ;)

**Comment by astridx** [comment]
Thank you very much.
