### ISSUE TITLE
Feature Request: 3D support via WebGL or Babylonjs?

### ISSUE THREAD

**Issue by ajmas** [Leaflet/Leaflet#5675]
This is a feature request.

The current version of Leaflet on supports 2D rendering, though it would be of interest to have 3D support either directly or via an optional module. I have looked around, but didn't see if there were any plans to add WebGL support to Leaflet? 

From what I can see it could be either achieved via [WebGL](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API) directly or via the [BabylonJS](babylonjs.com) library. The latter works on multiple modern platforms.

**Comment by perliedman** [comment]
Hi!

There has been some work with plugins using WebGL, like @IvanSanchez's [Leaflet.TileLayer.GL](https://gitlab.com/IvanSanchez/Leaflet.TileLayer.GL) and [Leaflet.GLMarkers](https://gitlab.com/IvanSanchez/Leaflet.GLMarkers), but that's not for 3D.

There is also [OSMBuildings](https://osmbuildings.org/) which uses Leaflet when adding 3d buildings (at least last time I checked).

I know @IvanSanchez also made significant work to make Leaflet WebGL based at some point, but that involves a lot of changes and is a major project that I'm far from sure anyone will ever complete.

In general, 3D is outside the scope of Leaflet's core at this point, and not something we will actively develop, although we're very happy to see plugins for adding 3D and WebGL.
