### ISSUE TITLE
please reopen issue

### ISSUE THREAD

**Issue by tomsue** [Leaflet/Leaflet#5680]
reopen this issue https://github.com/Leaflet/Leaflet/issues/5666#issuecomment-319534453

**Comment by ghybs** [comment]
Hi, great to hear that you find Leaflet useful!

As explained in #5666, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
