### ISSUE TITLE
Website is not working on Chrome (CORS refused)

### ISSUE THREAD

**Issue by carlsmith** [Leaflet/Leaflet#5692]
## How to reproduce

- Browser (with version) I'm using: **Chrome 59.0.3071.115 (Official Build) (64-bit)**
- OS/Platform (with version) I'm using: **macOS Sierra 10.12.6**

The library is not loading, so the map does not appear on the homepage.

```
index.html:1
  Access to CSS stylesheet at 'data:text;charset=utf-8,' from origin 'null' has
  been blocked by CORS policy: Invalid response. Origin 'null' is therefore not
  allowed access.

index.html:1
  Access to Script at 'data:text;charset=utf-8,' from origin 'null' has been blocked
  by CORS policy: Invalid response. Origin 'null' is therefore not allowed access.

index.html:298
  Uncaught ReferenceError: L is not defined
```

**Comment by designgears** [comment]
Sounds like you're including leaflet from the cdn? If so make sure you copy the url exactly as it is on the download page. http://leafletjs.com/download.html

**Comment by perliedman** [comment]
@carlsmith looking at a playground example using the sample code from Leaflet's website, this works as expected: http://playground-leaflet.rhcloud.com/vuni/edit?html,output

I'm going to close this, but if you believe this is really an issue with Leaflet, please provide:

* exact code you're using to load Leaflet
* preferably a running example on for example Leaflet Playground

**Comment by carlsmith** [comment]
When I visit the homepage (http://leafletjs.com/index.html), the map does not appear. There's a large, empty, white div with a light grey, 1px border that presumably should contain a map. If it's working for everyone else, it must be Tampermonkey or something at my end that is causing it, but I don't think it's my system.

**Comment by perliedman** [comment]
I've tried it in Chrome as well as Firefox on Ubuntu, and also Chrome on Windows, and it works without problem, it looks ok.

Lets see if anyone else has problems with this.

**Comment by themre** [comment]
Do you have any additional plugins installed in Chrome? (e.g. some CORS extension).

**Comment by carlsmith** [comment]
My bad. I went through my extensions, and it was caused by an ad blocker, [Stands][1]. I whitelisted your site, and the map is working fine. Sorry guys.

[1]: https://www.standsapp.org
