### ISSUE TITLE
unwanted animation if drawing polylines in Chrome

### ISSUE THREAD

**Issue by ppete2** [Leaflet/Leaflet#5694]
Please take a look at the following demo of Leaflet's plugin "PolylineMeasure".
[Demo](https://ppete2.github.io/Leaflet.PolylineMeasure/demo1.html)

 In **Firefox** the lines are drawed without any notable delay - OK!
But if drawing lines in **Chrome** it seems that some kind of "animation" effect is active during drawing. This laggy behaviour is very disturbing. 

My question: Is this animation effect introdeced by Leaflet itself and how can I turn it off for Chrome? Or is this because the plugin is to complex for Chrome browser and overstrain the browser and thwarting it?

**Comment by perliedman** [comment]
Hi there!

I looked quickly at that demo using Chrome on Ubuntu, and I didn't see any lag or animation that disturbed me. I also compared to Firefox, but didn't see any noticable difference. Might it be something local on your system?

I'm not aware of any animations related to PolyLines in Leaflet.

BTW, cool plugin, looks nice! :smile:

**Comment by ppete2** [comment]
Thanks for testing. I now tried with it on Chrome using an older Win7-Laptop. There it works without lags, strange. Then I **disabled** "use hardware acceleration" within Chrome settings on my PC and now there are no lags like in Firefox. Strange - in Firefox it works even if I enabled "hardware acceleration".
