### ISSUE TITLE
add attribute selectedPoints & selectedPoint to Polyline as mouse event's parameter

### ISSUE THREAD

**Issue by tomsue** [Leaflet/Leaflet#5699]
1. add attribute "selectedPoints"  to Polyline as mouse event's parameter?   selectedPointsis array(size=2), selectedPoints(startPosition and endPosition) from Polyline when mouse over it's any line ?

example: I need to get a line point(startPosition and endPosition) from Polyline when mouse over it's any line ?         like taxi ,i want to change line color for last 10 point when mouse over.

2.add attribute "selectedPoint"  to Polyline's any point as mouse event's parameter?  it show any point's detail information.
example: I need to get a point's detail information when mouse over to Polyline's positions's any point?

**Comment by perliedman** [comment]
Hi there,
thanks for reporting!

This is a bit application specific. When there's a mouse event on a Polyline, the pointer is not necessarily directly over a one of the line's vertices, so exactly how the matching would work would depend on how you use it.

Also, for complicated lines, figuring out the coordinate might be computationally expensive, so especially for `mouseover` this could turn out to be a performance issue.

In total, while I see the use case, not something I'd consider adding to Leaflet's core at this point. It's fairly straight forward to add this to your application code, or even build a plugin for it.
