### ISSUE TITLE
Feature request: Show popup text on fixed location on map 

### ISSUE THREAD

**Issue by bomberblue07** [Leaflet/Leaflet#5702]
It would be nice to have the option for popup text to be shown in a fixed location, i.e the upper left of the map, rather than always above the feature when clicked.

**Comment by perliedman** [comment]
Hi, thanks for the suggestion. However, this quickly turns very application specific. If you want this functionality, you can add/show whatever DOM element you need in your application, and you can have full control over where it will appear, etc.

If you want it inside the map, but in a corner, it sounds like you should look at making a [control](http://leafletjs.com/reference-1.1.0.html#control), which can easily be added. In fact, I would not be surprised if there is a plugin that already does something like that.

**Comment by theashyster** [comment]
And to add to what @perliedman said it is fairly easy to just specify some custom CSS rules for the default popup and put it in a fixed position wherever you like on the map.

**Comment by bomberblue07** [comment]
You're right, using a control worked for me. For reference, I ended up doing something similar to this example (in case anyone needs something similar): http://leafletjs.com/examples/choropleth/
