### ISSUE TITLE
Exception after remove Layer from Leaflet

### ISSUE THREAD

**Issue by bozzwin** [Leaflet/Leaflet#5703]
## How to reproduce

- Leaflet version I'm using: 1.2.0 or 1.1.0
- Browser (with version) I'm using: Last version of Chrome
- OS/Platform (with version) I'm using: Windows 7
- step 1
- step 2

## What behaviour I'm expecting and which behaviour I'm seeing

When I am trying remove layer from leaflet I am getting a exception in a console like below:

```
core.es5.js:1020 ERROR TypeError: Cannot create property '_leaflet_id' on number '11020'
    at n (eval at webpackJsonp.../../../../script-loader/addScript.js.module.exports (http://localhost:4200/scripts.bundle.js:63:8), <anonymous>:1:534)
    at e.removeLayer (eval at webpackJsonp.../../../../script-loader/addScript.js.module.exports (http://localhost:4200/scripts.bundle.js:63:8), <anonymous>:3:770)
    at http://localhost:4200/main.bundle.js:2677:43
```
The same code run perfectly on leaflet version 1.0.3. There is something in new version that break my app.

**Comment by perliedman** [comment]
Hi!

It would be great if you could provide a running example of the problem, for example using http://playground-leaflet.rhcloud.com/?html,output - this makes it a lot easier to find, understand and debug the problem. As reported now, there's nothing we can do to track down this issue.

**Comment by perliedman** [comment]
Closing as we have no more info to investigate this.
