### ISSUE TITLE
es6 import nevertheless exposes the whole library 

### ISSUE THREAD

**Issue by germsb** [Leaflet/Leaflet#5704]
- Leaflet version I'm using: >1.1.0

In the release note you say:  

> For users upgrading to this release, this change should not make a difference, while it offers the possibility to import individual parts of Leaflet individually if your app is built with ES6.

Ok, let's go.

`import {Map} from 'leaflet'; //npm package`
`let map = new Map(id,{zoom:0, center:{lat:0,lng:0}});`

It works but in the browser console, i see the global L with all features and when I build my app (webpack), the whole library is injected.

It seems to me that the objective is to reduce the size by eliminating the features that one does not need, I'm wrong ?

**Comment by perliedman** [comment]
Hi, thanks for reporting.

This is ongoing work that is not yet completely finished. The main problem at the moment is making sure people _can_ use Leaflet with module imports, but still also use Leaflet plugins that wasn't written with modules or any bundler in mind. That quickly gets tricky.

I'm going to close this for now, and direct you to the discussion in #5620, which hopefully will resolve the issue you're seeing. A similar point is also made in https://github.com/Leaflet/Leaflet/issues/5489#issuecomment-313845806.
