### ISSUE TITLE
Detect map resizes via invisible <object> or ResizeObserver

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#5705]
One of the current issues with the current implementation of the map's `resize` event is that it is unable to detect resizes under certain circumstances, e.g. changing the CSS class of a parent of the map container.

Apparently, there is an old (2013) workaround for this:
http://www.backalleycoder.com/2013/03/18/cross-browser-event-based-element-resize-detection/

The technique relies on adding an invisible `<object>` as a child of the map container (set to 100% width and height) and using its `onresize` event handler.

Apparently the technique still works, even though there is a more performant technique that doesn't work in all browsers. See https://github.com/wnr/element-resize-detector/ .

See also https://github.com/WICG/ResizeObserver for a "future-proof" way of observing element resizes. That's an upcoming API similar to the DomMutationObserver API. Quoting https://github.com/WICG/ResizeObserver/blob/master/explainer.md :

>Others use clever hacks to approximate resize event. The best hacks all use a similar absolute child trick: insert an absolutely-positioned child into the component, and craft the child in such a way that it emits a scroll event, or a window.resize when parent's size changes. The absolute child method will not work in ShadowDOM, or frameworks such as React.
>
>None of these approaches are desirable. They fail in correctness, code complexity, and performance.

--

So, feature request: 
* Replace the current `resize` event of the map with the "invisible object resize" technique.

and/or

* Future-proof the `resize` functionality with the `ResizeObserver` API (requires an experimental flag in Chrome 55+, see https://developers.google.com/web/updates/2016/10/resizeobserver )

**Comment by PSF1** [comment]
This feature has a big impact on Drupal's modules:

leaflet module:
Drupal 7 issue: https://www.drupal.org/project/leaflet/issues/2845418
Drupal 8 issue: https://www.drupal.org/project/leaflet/issues/3155885

leaflet_widget module:
Drupal 8 issue: https://www.drupal.org/project/leaflet_widget/issues/3113024

**Comment by Malvoz** [comment]
Closing in favor of https://github.com/Leaflet/Leaflet/issues/8222.

**Comment by kom177** [comment]
Вот здесь вроде бы решили
https://github.com/Leaflet/Leaflet/issues/5705
Проверено на планшете переносом таба с картой на второе место. Эффекта не наблюдается.
