### ISSUE TITLE
Events firing twice when interfering with moving map

### ISSUE THREAD

**Issue by tgelz** [Leaflet/Leaflet#5708]
I'm not entirely sure if this is intended or a bug, but when setting the view to a different point on the map while the map is still moving, the `moveend` event is triggered, followed by another `movestart` event. The following Fiddle demonstrates this when you drag the map and, while the inertia is still going, click the reset button.

https://jsfiddle.net/dg20f7tm/

This example might not be too relevant, but in my specific case, I use the `once()` function to only trigger the `moveend` event when clicking the button. Due to the cycled events, `moveend` will trigger, followed by `once()` removing the event handler and then `movestart` being the last event to fire, causing my logic to break.

https://jsfiddle.net/dg20f7tm/1/

I fixed this by utilizing `stop()` before setting the event handler, but I thought I'd mention it, in case the behavior is not intended.

**Comment by perliedman** [comment]
Hi, thanksfor reporting!

Yes, the event order in these types of situations can be a bit tricky to get right. However, I do think this is how it is intended to work: you can see the inertia as a map movement that is first stopped when you call `setView`, and then a new movement starts.

I guess you could also work around it by listening to `movestart` and adding the `moveend` handler in there instead.

**Comment by tgelz** [comment]
Thanks for the tip!

I like that solution even better. Since I'm using the code in an extended `L.Control`, I can easily use internal flags to check whether `movestart` should create such an event.
