### ISSUE TITLE
Leaflet: Mouseover/Mouseout events -  overlapping between geojson objects

### ISSUE THREAD

**Issue by Fozando** [Leaflet/Leaflet#5710]
Hi everybody!!  

I'm experimenting an overlapping problem between a couple of geojson layers in Leaflet.

One of these layers has polygon objects and the other one has linestring objects. Both layers have mouseover and mouseout events and I want to keep the layer with the linestring objects always over the polygons, but when the mouseover event and the following mouseout event are fired on the polygon layer, the objects of the linestring layer always stay under the polygons, beeing impossible to select them.

I think that bringToFront() and bringToBack methods could solve the problem, but after doing some test I'm unable to keep the linestring objects always over the polygons.

Has someone experimented the same issue?

Thanks for the answers

**Comment by perliedman** [comment]
Hi there,
it's really hard to say anything about this without an example.

You can use `bringToFront`/`bringToBack` to control the layer order, but another possibity is also to use panes to control the order, see this tutorial: http://leafletjs.com/examples/map-panes/; you could add your linestring layer to a separate pane that is always on top of the normal overlay pane, for example.

**Comment by Fozando** [comment]
Thanks for answering perliedman.

Finally I solved the problem usign bringToFront/bringToBack options.
