### ISSUE TITLE
about coordinates 

### ISSUE THREAD

**Issue by zhuyinjing** [Leaflet/Leaflet#5717]
## How to reproduce

- Leaflet version I'm using:1.1.0
- Browser (with version) I'm using:chrome
- OS/Platform (with version) I'm using:
- step 1 Ubuntu
- step 2

## What behaviour I'm expecting and which behaviour I'm seeing
when i used freeDraw.on('markers', event => { console.log(event.latLngs); });
it shows based on the coordinates of the canvas，and i want to be based on the coordinates of the picture.
how should i do ? thanks!
## Minimal example reproducing the issue

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

Using http://playground-leaflet.rhcloud.com/ or any other jsfiddle-like site.

**Comment by perliedman** [comment]
Hi and thanks for using Leaflet!

Please note that this is our issue tracker, where bugs and feature requests and posted and discussed. For questions on how to use Leaflet and other support, you're better off using [stackoverflow](https://stackoverflow.com/) or [gis.stackexchange.com](https://gis.stackexchange.com/).
