### ISSUE TITLE
Leaflet view blank on Drupal 8

### ISSUE THREAD

**Issue by jestinijames** [Leaflet/Leaflet#5718]
## How to reproduce

- Leaflet version I'm using: Latest
- Browser (with version) I'm using: Chrome
- OS/Platform (with version) I'm using: Windows 10

## What behaviour I'm expecting and which behaviour I'm seeing

I am working with drupal vm. I use geofield to display leaflet location. While the content by itself is displaying properly, the view which shows all map locations is coming blank. While debugging, I see that the js file is not being detected. Is there something specfic i need to do? I just activated the module using drush

## Minimal example reproducing the issue

- [ ] this example is as simple as possible

Using http://playground-leaflet.rhcloud.com/ or any other jsfiddle-like site.

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.

**Comment by jestinijames** [comment]
But this has been used and tested on drupal 7 for years. It is just not working on D8

**Comment by IvanSanchez** [comment]
Once again: this is for stand-alone Leaflet. I do not care about Drupal. Bugs for the drupal-leaflet interaction go in https://www.drupal.org/project/issues/leaflet .
