### ISSUE TITLE
Так должно быть или это ошибка в коде?

### ISSUE THREAD

**Issue by Darkarhey** [Leaflet/Leaflet#5723]
Hello! Exscuise me.
Далее на русском.

При попытке вставить изображение во всплывающее сообщение (Popup) маркера, его ширина не увеличивалась более 50 пикселей, увеличить получилось вот так:
"ObjEv.popup.options.minWidth = 700;
 ObjEv.popup.update();"
Далее посмотрел  код в исходнике:
"//кусок кода из исходника Leaflet:
// @namespace Popup
var Popup = DivOverlay.extend({

	// @section
	// @aka Popup options
	options: {
...
	var container = this._contentNode,
		    style = container.style;

		style.width = '';
		style.whiteSpace = 'nowrap';

		var width = container.offsetWidth;
		width = Math.min(width, this.options.maxWidth); //it error? - это ошибка?
		width = Math.max(width, this.options.minWidth); //it error? - это ошибка?
..."
Это ошибка или как?

Ещё раз извините...

**Comment by perliedman** [comment]
Hi! Thanks for using Leaflet. Sorry to say, but the maintainers can only handle bug reports written in english. Happy to re-open once you rewrite the issue in english! Thanks.
