### ISSUE TITLE
So it should be or is it a bug in the code?

### ISSUE THREAD

**Issue by Darkarhey** [Leaflet/Leaflet#5724]
Hello!
Excuse me, write over translate.

When you try to insert an image into a popup message (Popup) of the marker, its width did not increase more than 50 pixels, you can increase it like this:
``` 
ObjEv.popup.options.minWidth = 700;
ObjEv.popup.update();
```
I looked at the Leaflet source code:
```
// @namespace Popup
var Popup = DivOverlay.extend({

	// @section
	// @aka Popup options
	options: {
...
	var container = this._contentNode,
		    style = container.style;

		style.width = '';
		style.whiteSpace = 'nowrap';

		var width = container.offsetWidth;
		width = Math.min(width, this.options.maxWidth); //It's error?
		width = Math.max(width, this.options.minWidth); //Tt's error?
```
Is it a mistake or something?

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by yohanboniface** [comment]
@Darkarhey you need to set the img element width/height iirc.

**Comment by Darkarhey** [comment]
function doImageMonSell(ObjEv)
		{
			var version = "LATEST"
			var format = "Image"
			var url = gatewayURL + "?height=360&width=670&Key=" + ObjEv.popup._source.options.alt;
			var blob = new Blob([objXHR.response],{type: "image/png"});
			try
			{
				objXHR.open("GET", url, true);
				objXHR.withCredentials = true;
				objXHR.responseType = "blob";
				objXHR.onload = function() {
					 
					blob = (objXHR.response);
					 					
					ObjEv.popup.setContent("<img src=" + window.URL.createObjectURL(blob) + ">");
					
					ObjEv.popup.options.minWidth = 700;
					ObjEv.popup.update();

				};
				ObjEv.popup.options.minWidth = 50;
				ObjEv.popup.setContent("Загрузка...");
				ObjEv.popup.update();
				objXHR.send();
				
			}
			catch (e)
			{
				alert(e);
			}
			
		}

**Comment by Darkarhey** [comment]
Thank you, no longer relevant.
