### ISSUE TITLE
Error with panning in Edge browser?

### ISSUE THREAD

**Issue by lesiano** [Leaflet/Leaflet#5726]
Hi,

I'm having a problem with Edge. I have a map inside a div and its working properly in Chrome and Firefox. The problem with Edge is when I try to move the map to left, right, up or down, it's seems that i'm moving an image. It's not moving as Chrome or Firefox. I tried to move with the keyboard and its work, and also if I double click its working but then its make a zoom in. Is there a problem with Edge? Or something missing from my side?

Thanks.

**Comment by perliedman** [comment]
Hi @lesiano!

Is this problem only reproducible in your own application, or does this happen with any Leaflet map i Edge? For example, can you pan the map on http://leafletjs.com/ ?

From a quick check, I can see no problem on Leaflet's own site when using Edge.

For us to be able to dig into this, we need a minimal example reproducing the problem.

**Comment by lesiano** [comment]
Another thing I just checked, If I do the right click its work normally.. It is possible to move the map, but with left click no. In Chrome works with left and right click. 

Hi @perliedman  thanks for helping me. I can pan the map on  [ http://leafletjs.com/] with left click, and with the right click it shows some options.

**Comment by perliedman** [comment]
@lesiano ok, so then there's something happening in you app that causes this. Right click should normally trigger the context menu, as you see on the Leaflet site.

**Comment by lesiano** [comment]
@perliedman  Yes, seems like that. Do you know any option that could do that?

**Comment by perliedman** [comment]
Sorry, it's very hard to tell without seeing the application. Typically, I would check any CSS changes your app makes, also listeners etc. that could override this, or other libraries you have loaded that might interfere with Leaflet.

I'm going to close this for now, but if you still have this issue and think it's a problem with Leaflet itself, please create a minimal test case that reproduces the problem, and we can have a look.
