### ISSUE TITLE
How to disable mouse events on geoJson feature ? i am creating boundaries on the countries using geoJson and i want to disable mouse events on some countries.

### ISSUE THREAD

**Issue by bhavikboricha009** [Leaflet/Leaflet#5728]
## How to reproduce

- Leaflet version I'm using:
- Browser (with version) I'm using:
- OS/Platform (with version) I'm using:
- step 1
- step 2

## Minimal example reproducing the issue

- [x] this example is as simple as possible
- [ ] this example does not rely on any third party code

Using http://playground-leaflet.rhcloud.com/ or any other jsfiddle-like site.

**Comment by bhavikboricha009** [comment]
I am using geoJson coordinates for creating boundaries around the countries. 

i am also filling the country with some colors. and then showing marker on those countries which has data.

my concern is, can i disable mouse events on some countries(feature) which doesn't have data.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
