### ISSUE TITLE
GeoJSON properties: url link to other directory

### ISSUE THREAD

**Issue by Fozando** [Leaflet/Leaflet#5729]
Good night:

I have an amount of elements into a geoJSON file where one of their properties is "url": "link to a HTML file".

The problem that I have is that the HTML files aren't on the same directory as the geoJSON file.
 
I'm trying to do the link using the characters ".." from HTML to go up one level on the directories structure but it doesn't work.

Can someone tell me what is the correct form to go up on the directories structure?

Thanks for answering :)

**Comment by SirenHound** [comment]
This doesn't sound like a Leaflet or GeoJSON issue, but more one of how you are implementing your URL string or whatever software is reading and using it, (maybe a browser?) you could try a global url, but again, not a Leaflet issue.

**Comment by Fozando** [comment]
Thanks for your answer SirenHound

The property url is going to appear on a popup of a GeoJSON object implemented on a Leaflet map, that's the reason why I asked this question here.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by Fozando** [comment]
No it isn't a Leaflet's bug report. 

Sorry for writing the consult on the wrong place. :)
