### ISSUE TITLE
marker/circle bugged after adding more markers

### ISSUE THREAD

**Issue by peslis** [Leaflet/Leaflet#5735]
I have a leaflet map on my website in which i have a main marker which saves the position to my database for every user. It has also have a circle around the main marker which goes with it even when dragged. Now what i want is that when a user clicks the player-search button a function is called and we recieve with ajax all the positions from all users and with a for loop , add the markers on the map . That isnt happening. Map becomes bugged , if you zoom out or in the marker and the circle goes crazy ,other markers appear everywhere .I have tried everything so i assume this is a leaflet issue....  (note: database is working fine and i get all the correct values as tested! . for example response[0] has latlng(....,...) of a user )
## How to reproduce

- Leaflet version I'm using:
- Browser (with version) I'm using: chrome latest version
- OS/Platform (with version) I'm using: windows 10
- make same ajax request with button and a database with latlng[] values

here is my html code
```
<div id="map"></div>
<div id="distance-selector-block">
        <form>
           <select id="distance-selector" >
              <option value="">Select distance:</option>
              <option value="1">500m</option>
              <option value="2">1km</option>
              <option value="3">5km</option>
              <option value="4">10km</option>
              <option value="5">50km</option>
           </select>
        </form>
</div>
        <div id="player-button-block">
               <input type='button' id="player-button" value='Find Nearby Players' >
        </div>
```

here is my script code
```
<script>
    
    $(document).ready(function(){
       var mymap = L.map('map').setView([51.505, -0.09], 13);
       L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=xxx', {
    attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
    maxZoom: 18,
    id: 'mapbox.streets',
    accessToken: 'xxx'
}).addTo(mymap);

var marker;
var circle;
var all;
          $("#player-button").on('click', function() {
                $.ajax({   
                      type: "GET",
                      url: "homesearchplayers.php",            
                      dataType: "json",                
                      success: function(response){                     
                      for ( var i = 0; i < response.length; i++) {
                      marker = new L.marker(response[i]).addTo(mymap);
                      }
                          }
                 });
          });
});
});
</script>
```

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

> I have tried everything so i assume this is a leaflet issue

No. You haven't tried **isolating** the problem. If it's a leaflet bug, it must be reproducible with an example that doesn't involve network requests, or signing up anywhere.
