### ISSUE TITLE
Multiple canvas renders not binding popups

### ISSUE THREAD

**Issue by jaymmartin** [Leaflet/Leaflet#5739]
## How to reproduce

- Leaflet version I'm using: 1.2.0
- Browser (with version) I'm using: Chrome 61, Firefox 55
- OS/Platform (with version) I'm using: Windows 10

Steps 
1. Add a vector layer to the map using a specified canvas renderer and bind a popup to it
2. Add another vector layer to the map using a different canvas renderer and bind a popup to it

## What behaviour I'm expecting and which behaviour I'm seeing
I expect that the popup bound on the layer from step 1 to open when clicked, but it does not. The popup bound to layer 2 does work, however. 

The cursor pointer also does not change to indicate the step 1 layer is clickable.

## Minimal example reproducing the issue
https://codepen.io/jaymmartin/pen/yoQJzw

**Comment by perliedman** [comment]
Hi!

Thanks for reporting this. The issue is that a canvas renderer acts as a layer covering the whole map container. Although the canvas is transparent (except for what's drawn on it), it will in fact swallow pointer events. So, putting two canvases on top of each other, only the topmost will receive the pointer events.

This is not something specific to Leaflet, but rather a fact of how the browser's DOM works.

BTW, I have a kludge workaround for this that you can have a look at: https://gist.github.com/perliedman/84ce01954a1a43252d1b917ec925b3dd

**Comment by jaymmartin** [comment]
I see now. 

Multiple canvas renderers are useful, as redraw performance is much better if you can segment the layers on different canvases. For my case, I am using mouseover/mouseout, so that workaround will not work.

What about a solution where a canvas object forwards an event to the Map object, which then forwards it to the next canvas object? L.Map would need to track all of its canvas renderers and order in the DOM if it doesn't already. I'll see if I can get something out of this and update here.

```javascript
// L.Canvas
onAdd: function () {
	Renderer.prototype.onAdd.call(this);

	// register with map as canvas
	this._map.registerCanvasRenderer(this);

	// Redraw vectors since canvas is cleared upon removal,
	// in case of removing the renderer itself from the map.
	this._draw();
}

_handleMouseHover: function (e, point) {
	var layer, candidateHoveredLayer;

	for (var order = this._drawFirst; order; order = order.next) {
		layer = order.layer;
		if (layer.options.interactive && layer._containsPoint(point)) {
			candidateHoveredLayer = layer;
		}
	}

	if (candidateHoveredLayer !== this._hoveredLayer) {
		this._handleMouseOut(e);

		if (candidateHoveredLayer) {
			DomUtil.addClass(this._container, 'leaflet-interactive'); // change cursor
			this._fireEvent([candidateHoveredLayer], e, 'mouseover');
			this._hoveredLayer = candidateHoveredLayer;
		}
	}

	// if no layer was found, forward it to the next canvas renderer if it exists
	if (!candidateHoveredLayer) {
		this._map.forwardCanvasEvent(this, e, point);
	}
	if (this._hoveredLayer) {
		this._fireEvent([this._hoveredLayer], e);
	}
},


// L.Map
registerCanvasRenderer: function(layer) {
	this._canvasRenderers.push(layer);
}

forwardCanvasEvent: function(layer, e, point) {
	for(var i = 1; i < this._canvasRenderers.length; i++) {
		if (this._canvasRenderers[i-1] == layer) {
			// would really need to figure out which event happened here 
			// maybe pass it off to a method in L.Canvas, or have this 
			// method be told what to call
			this.canvasRenderers[i]._handleMouseHover(e, point); 
		}
	}
}
```

I can see this solution messing with separation of concerns. I wouldn't want L.Map to be so involved in the intricacies of L.Canvas. So maybe generalizing the pattern would be helpful. Something like event forwarding/notification of sibling layers? I don't know the Leaflet codebase well enough to know how this plays into the event framework.
