### ISSUE TITLE
Autopan fires Moveend event

### ISSUE THREAD

**Issue by rsaenen** [Leaflet/Leaflet#5740]
## How to reproduce

- Leaflet version I'm using: 1.2.0
- Browser (with version) I'm using: Chrome 60.0.3112.113
- OS/Platform (with version) I'm using: W7

## What behaviour I'm expecting and which behaviour I'm seeing

In the documentation, the event moveend is fired when the center of the map changes and my callback works nicely.
However, the autoPan option of a popup fires the event moveend, the description of this event doesn't include pan or fly animations like it's described in the event move for example.

Is the documentation ambigous or a bug ? 

## Minimal example reproducing the issue

- [x] this example is as simple as possible
- [ ] this example does not rely on any third party code

**Comment by mourner** [comment]
Indeed, when autopan happens, the map moves and eventually stops, marking the end of map movement with `moveend`. If you'd like to see a less ambiguous wording in the docs for that, we'd welcome a pull request!

**Comment by rsaenen** [comment]
Thanks for reply, I guess I'll have to discriminate which action fired this event.

**Comment by shauravg** [comment]
Sorry to comment on an old issue, but is there an example of how to discriminate between the action that fires the moveend event? I have autoPan: true for popups that user can invoke by clicking on markers. New markers are fetched when the user moves the map so what ends up happening:

1. User clicks on marker to show popup
2. If the popup causes the map to move, then new markers are fetched and added to map
3. This causes the popup to close
4. user clicks on popup again and it works since by now the map is already in the right position

**Comment by hoetmaaiers** [comment]
Hi @jbelien , this feels like it is half the solution. What do you use for setting the autopan flag to false? I can't find a autopanend event...

**Comment by jbelien** [comment]
> Hi @jbelien , this feels like it is half the solution. What do you use for setting the autopan flag to false? I can't find a autopanend event...

I use the `movend` event.
You can have a look here : https://github.com/jbelien/osm-report/blob/master/src/map/init.ts#L52

**Comment by hoetmaaiers** [comment]
Ok thank you @jbelien  for providing this insight into the `moveend` and `autopanstart` event, this solved my problem.

Is there a reason why we have no `autopanend` event?

**Comment by malun22** [comment]
`autopanend` would indeed be very helpful.

**Comment by TheMangoTrain** [comment]
A core variable for this, as suggested above, would be convenient of course.

In any case, this is how I discern user-movement vs auto-movement; so far it works well for pan/zoom.

Roughly like this:

**In map component data()**
`autoMovementOccurring: false`

**In methods**
In any function that does auto-movement, change state first before your logic
```
myFunctionThatDoesAutoPans() {
    this.autoMovementOccurring = true

   // ...
}
```

**In the listener for Leaflet's moveend, I check the state**
```
this.map.on('moveend', () => {

    // Check state
    if (!this.autoMovementOccurring) {
        // Tell parent component user-movement occurred
        this.$emit("heyUserMovementHappened")
    }
    // Reset state
    this.autoMovementOccurring = false
})
```
