### ISSUE TITLE
I want to Clip the imageOverlay,but I can not get canvas,what should I do ?

### ISSUE THREAD

**Issue by yezhanpeng201314** [Leaflet/Leaflet#5746]
I want to Clip the imageOverlay,but I can not get canvas,what should I do ?  thanks 
var imageUrl = 'http://www.lib.utexas.edu/maps/historical/newark_nj_1922.jpg',
    imageBounds = [[40.712216, -74.22655], [40.773941, -74.12544]];
var test = L.imageOverlay(imageUrl, imageBounds).addTo(map);
///var canvas = test._canvas ;     ------like this
 //var ctx = _canvas.getContext('2d');
//ctx.fillStyle='#FF0000';
 //ctx.fillRect(0,0,80,100);

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
