### ISSUE TITLE
L.circle on Mobile phone  when map Max level

### ISSUE THREAD

**Issue by yamateH-ch** [Leaflet/Leaflet#5747]
I used L.circle to draw two circles, on the mobile phone and IE to see, the map to the maximum level, when the slide is very card, stroke not move, PC end will not so, how to solve this problem, the main code is as follows

- Leaflet version I'm using:1.2.0
- Browser (with version) I'm using: Mobile phone &IE11 

```
`	var map = L.map('mapid').setView([23.13, 113.33], 9);
	var url = 'xxx';
         L.tileLayer(url, {
			subdomains: "1234"
			}).addTo(map);`
         L.circle([23.172398, 113.454404], {fill: false,weight: 2,dashArray: "5, 10",radius:100000,color: "#ff0000"}).addTo(map);
       L.circle([23.172398, 113.454404], {fill: false,weight: 2,dashArray: "5, 10",radius: 300000,color: "#eb2c37"}).addTo(map);
```

**Comment by perliedman** [comment]
Hi @yamateH-ch! Thanks for using Leaflet and thanks for submitting an issue.

I have a bit of trouble understanding exactly what problem you are describing here. Could you please specify:

* what are you expecting to see
* what do you see in practice
* which browser shows this problem (IE or phone)?

Ideally, also make a running example of the issue on http://playground-leaflet.rhcloud.com/

Might it be that this is really the same issue as #5315, circles with very large radius are rendered incorrectly?

**Comment by yamateH-ch** [comment]
@perliedman 
 yes，I may not be specific enough ， I  added a few circles on the map ，when I  Put to map Maxlevel， on  my phone （android 5.1.1） or IE11  ,Slide the map with my hands ,At this time, the map slide is no small level, so smooth .
  http://playground-leaflet.rhcloud.com/buza/edit?html,console,output
Please open it with your cell phone. Slide the map manually at the default level and at the maximum level, which is clearly comparable

**Comment by perliedman** [comment]
The playground example is unfortunately lost since the playground itself has disappeared. :disappointed: 

I'm closing this for now, but will happily re-open if we can get a new example to show the issue.
