### ISSUE TITLE
Make popup content with angular2 component

### ISSUE THREAD

**Issue by chuduyunhuan** [Leaflet/Leaflet#5750]
Hi, 
Can I use angular2 directives such as "*ngFor" when I am making a popup in an angular app which contains leaflet map?

code may be like:

var htmlStr = `
    <div *ngFor="let name of names">{{name}}</div>
`;
var popup = L.popup()
    .setLatLng(latlng)
    .setContent(htmlStr)
    .openOn(map);

I found that it can't understand angular grammer. Will you please give some advice? 
Thanks.

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.

**Comment by chuduyunhuan** [comment]
Got it. Thanks all the same.
