### ISSUE TITLE
Ionic @types/leaflet problems

### ISSUE THREAD

**Issue by Hexagoo** [Leaflet/Leaflet#5753]
Heeeey

I'm using Leaflet for Ionic 3 and some errors suddenly coming when I build my project.
This errors concerns the @types/leaflet librairies.

`typescript: node_modules/@types/leaflet/index.d.ts, line: 583`

...I've like 50 errors which are linked to index.d.ts file

OS : Mac OSX Sierra
types/leaflet : 1.2.0
leaflet : 1.0.3

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.
