### ISSUE TITLE
Updating popup location or content pans it into view

### ISSUE THREAD

**Issue by endquote** [Leaflet/Leaflet#5755]
## How to reproduce

- Leaflet version I'm using: latest dev version
- Browser (with version) I'm using: Chrome 60
- OS/Platform (with version) I'm using: macOS 10.12.16

- create a popup
- pan the map away from the popup
- update the popup with `popup.setContent` or `popup.setLatLng`
- the map pans the popup into view, even though `keepInView` is `false`

## What behaviour I'm expecting and which behaviour I'm seeing

Don't ever pan a popup into view if `keepInView` is `false`

## Minimal example reproducing the issue

http://playground-leaflet.rhcloud.com/xodez/1/edit?html,output

Note that if you comment out the last line, you're in San Francisco.

**Comment by perliedman** [comment]
Hi!

`keepInView` prevents the user from panning away from the popup, but you also have the [`autoPan`](http://leafletjs.com/reference-1.2.0.html#popup-autopan), enabled by default, which will pan the map when the popup is opened or updated. So you need to disable `autoPan` to prevent the map from panning.

An updated version of your example: http://playground-leaflet.rhcloud.com/xocod/edit?html,output

**Comment by endquote** [comment]
Thanks for the reply. Setting `autoPan` to false does solve the problem, but I did actually like that the popup was panned into view when opened. I just don't want the map to force it to stay in view, and it seems like setting `keepInView` to false would prevent that.
