### ISSUE TITLE
When an SVG file is used as an image overlay, expose its DOM to the browser

### ISSUE THREAD

**Issue by endquote** [Leaflet/Leaflet#5756]
I want to use an SVG file as an image overlay. This works fine, however Leaflet creates it as an `img` tag, which means I cannot access the DOM of the SVG file from code.

A way around this would be to use an `object` tag and nest it in there.

**Comment by endquote** [comment]
I'm not sure if this PR will get accepted, so here's a monkey-patch way to achieve the same thing.

```
const overlay = L.imageOverlay('maps/map.svg', [[0, 0], [-height, width]]).addTo(this.map);

// Super-janky way of replacing the SVG <img> tag with an <object> tag that embeds it.
const layers = overlay._image.parentNode;
overlay._image.parentNode.removeChild(overlay._image);
const obj = document.createElement('object');
obj.data = overlay._url;
obj.type = 'image/svg+xml';
overlay._image.classList.forEach(c => obj.classList.add(c));
obj.setAttribute('style', overlay._image.getAttribute('style'));
layers.appendChild(obj);
overlay._image = obj;

// In Chrome, the object tag needs to be redrawn after a zoom for some reason.
// This causes an unfortunate one-frame flicker.
if (L.Browser.chrome) {
  this.map.on('zoomend', () => {
    overlay._image.style.display = 'none';
    overlay._image.style.display = 'block';
  });
}
```

**Comment by perliedman** [comment]
As @IvanSanchez mentioned in response to #5757, the best way to achieve this is probably to inherit from `ImageOverlay` like `VideoOverlay` does, this way you can make the DOM accessible anyway you want. Avoid monkey patching if you can.

**Comment by endquote** [comment]
Agreed that a new type of overlay like L.VideoOverlay makes much more sense. Thanks for tolerating the new guy.
