### ISSUE TITLE
Polyline tooltips seem inconsistent

### ISSUE THREAD

**Issue by endquote** [Leaflet/Leaflet#5758]
Here are a bunch of polylines with tooltips bound to them:
https://www.dropbox.com/s/1bwladr9kmr128e/leaflet-polyline-tooltip.mov

Note that the tooltips appear at the top-left of rectangular polylines, but at the center-left-ish? of non-rectangular ones.

I was trying to set the `offset` of tooltips to be the center of the polylines, but since the offset added to the default position of the tooltip, and that default position seems inconsistent, it's hard to add to.

Related, it looks like the `tooltip.offset` option is meant to be in pixels, but that means you need to change it after every pan/zoom? Seems like it should be a lat/long instead, then it could be set once per layer.

**Comment by IvanSanchez** [comment]
> Note that the tooltips appear at the top-left of rectangular polylines, but at the center-left-ish? of non-rectangular ones.

I bet that's the first defined point in your dataset.

> I was trying to set the `offset` of tooltips to be the center of the polylines

What do you mean by "center"? Centroid? Midpoint (point at the middle lf the length of the line? Something else? Please be specific, the vocabulary here is confusing.

**Comment by endquote** [comment]
The centroid would be ideal, but I was trying to put it at the center point of the geometry's bounding box. I was struggling to do that because it's not clear what the `offset` property is relative to.

It seems like it would be easier to work with if you could just set its absolute position, like `L.Popup.setLatLng`.

I'm generating these polylines in maybe a weird way, by getting a Path element from an SVG DOM, and collecting points along its length. I guess if the first point in my list is the "origin" I could figure it out based on that?

```
const points = [];
const len = path.getTotalLength();
let j = 0;
while (j < len) {
  const point = path.getPointAtLength(j);
  points.push([-point.y, point.x]);
  j += 1;
}

const opts = { smoothFactor: 1 };
const polyline = L.polyline(points, opts).addTo(this.map);
polyline.bindTooltip('stuff')
```

**Comment by IvanSanchez** [comment]
> The centroid would be ideal

No, you don't want to use centroids for polylines, as the centroids will most probably be *far away* from the polyline. Polygons are a bit better, but do check https://blog.mapbox.com/a-new-algorithm-for-finding-a-visual-center-of-a-polygon-7c77e6492fbc

> It seems like it would be easier to work with if you could just set its absolute position, like `L.Popup.setLatLng`.

Hhhmm, something similar but for tooltips makes a lot of sense. Perhaps @perliedman can shed some light on why the tooltip interface doesn't have that?

**Comment by perliedman** [comment]
Not entirely sure why it isn't in the docs, but since `Tooltip` as well as `Popup` inherits `DivOverlay`, they both do have `setLatLng`. Example: http://playground-leaflet.rhcloud.com/tuta/edit?html,output

Having said that, for this case interaction doesn't really work as I would expect. It sounds like a `latLng` option or similar would be good.

@yohanboniface do you have any input on this, I think you put some thought into the tooltip API, but perhaps this use case didn't come up?

**Comment by yohanboniface** [comment]
Tooltip are positionned with latlng like other divoverlays, yes.
You basically have:
- position, in latlngs (comes from getCenter/getLatlng at the moment, see below for a suggestion)
- anchor in px and depends on the layer it self (comes from _getAnchor, only used for Markers)
- offset in px, and depends on the tooltip itself

It should be totally possible to use setLatlng on the tooltip.
One option I'm thinking of now is to allow passing the latlng as an option of `bindTooltip`, so it's easier to set it (instead of needed to create the tooltip by hand).

**Comment by yohanboniface** [comment]
As workaround, have you tried something like (not tested):

```javascript
layer.bindTooltip('xxx').openTooltip(layer, yourlatlng)
```

**Comment by endquote** [comment]
I decided I'd rather have the tooltip at the mouse position, and follow the mouse. I was able to get that working.
https://www.dropbox.com/s/ph7i6aiy6u3rezu/leaflet-polyline-tooltip-follow.mov

So really this bug should be "how do I position a tooltip with absolute coordinates?", and the answer is "use `openTooltip(<LatLng> latlng?)`". It just took a while to figure it out.

```
if (!this.tooltip) {
  if (this.defaultZoneLayer) {
    this.tooltip = this.defaultZoneLayer.bindTooltip('', { direction: 'right' });
  }
}

if (this.tooltip) {
  if (hits.length) {
    this.tooltip.setTooltipContent(hits.join('<br>'));
    const pos = { clientX: e.clientX + 10, clientY: e.clientY };
    this.defaultZoneLayer.openTooltip(this.map.mouseEventToLatLng(pos));
  } else {
    this.defaultZoneLayer.closeTooltip();
  }
}
```

**Comment by perliedman** [comment]
Ok, good discussion.

It sounds to me like this has been cleared up now. Can we close, or are there things in Leaflet that should be addressed?

**Comment by endquote** [comment]
Seems like it could be closed, but it might be worth considering unifying the tooltip/marker APIs, since they're conceptually so similar.

**Comment by perliedman** [comment]
Agreed, I think further unification would be cool, even though they're already pretty close.

I'm closing this issue now, since contains quite a lot of noise. Let's open a new issue if we have actionable suggestions for improving the tooltip/popup APIs.

**Comment by ghybs** [comment]
Hi @endquote,

For the use case where you want the Tooltip to follow the mouse, it seems to me that the [`sticky`](http://leafletjs.com/reference-1.2.0.html#tooltip-sticky) option might be what you need:
http://playground-leaflet.rhcloud.com/wele/1/edit?html,output

```javascript
myShape.bindTooltip('tooltipText', {
  sticky: true // If true, the tooltip will follow the mouse.
});
```

You may also use it in combination with `offset` and `direction` options.
