### ISSUE TITLE
"At each zoom level, each [tile's] size doubles"

### ISSUE THREAD

**Issue by phil294** [Leaflet/Leaflet#5760]
Concerning [zoom-levels](https://github.com/Leaflet/Leaflet/blob/master/docs/examples/zoom-levels/index.md):

> At each zoom level, each tile is divided in four, and its size doubles (in other words, the width and height of the world is 256·2zoomlevel pixels):

If a tile is divided in four sub-tiles, its size does not double, it quadruples. It is the length of its edges that doubles. This had me totally confused right now. I think you should correct this typo. Cheers

**Comment by IvanSanchez** [comment]
That depends whether you consider that the size of a tile is the length of one of its edges, or its area.

I do agree that the wording can be confusing, but this should be alleviated by the fact that our documentation specifies the `tileSize` option of `L.GridLayer`s as the length of the edge, not as the area.

If you can come up with better wording, by all means please submit a pull request with changes to the tutorial files!
