### ISSUE TITLE
@types/leaflet 1.2.0 missing options

### ISSUE THREAD

**Issue by sgentile** [Leaflet/Leaflet#5761]
The type definition file for leaflet is missing sortLayers property on the options.  This causes Typescript errors when building the project

 ( https://www.npmjs.com/package/@types/leaflet )

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* ...etc

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo. In this case, you might want to head on to https://github.com/DefinitelyTyped/DefinitelyTyped , as the typescript definitions for leaflet are hosted at https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/leaflet

We do not use nor handle typescript defs ourselves in this repo.
