### ISSUE TITLE
rotate the map

### ISSUE THREAD

**Issue by zhuyinjing** [Leaflet/Leaflet#5762]
## How to reproduce

- Leaflet version I'm using:1.2.0
- Browser (with version) I'm using:chrome  59.0.3071.115
- OS/Platform (with version) I'm using:Ubuntu
- step 1
- step 2

## What behaviour I'm expecting and which behaviour I'm seeing
# I want rotate the map . how can i do? Does leaflet have plugin to rotate map?not rotate imageOverlay.
Thank you very much!
## Minimal example reproducing the issue

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

Using http://playground-leaflet.rhcloud.com/ or any other jsfiddle-like site.

**Comment by yohanboniface** [comment]
See #268
