### ISSUE TITLE
deepzoom with leaflet 

### ISSUE THREAD

**Issue by zhuyinjing** [Leaflet/Leaflet#5763]
## How to reproduce

- Leaflet version I'm using:1.2.0
- Browser (with version) I'm using:chrome
- OS/Platform (with version) I'm using:ubuntu
- step 1
- step 2

## What behaviour I'm expecting and which behaviour I'm seeing
# hi,i use leaflet to show deepzoom picture,and i want to get coordinate based on picture,not latlng,how can i transform??? unproject??project??
how can i do?
thank you so much!!

## Minimal example reproducing the issue

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

Using http://playground-leaflet.rhcloud.com/ or any other jsfiddle-like site.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
