### ISSUE TITLE
Map not able to drag after creating second map

### ISSUE THREAD

**Issue by BLGEric** [Leaflet/Leaflet#5765]
Leaflet Version :1.0.3
Browser: Chrome & Edge (Others may have same problem)

![1](https://user-images.githubusercontent.com/17487737/30151178-0dac2aea-93e1-11e7-963a-6a13f642ef71.PNG)

When page loads, js creates a leaflet map and works well.
However, if I click the "District/Town" label, which will create a second map under the first map like the picture below, the first map will be stuck and unable to zoom, drag....etc.
My code is very easy, I create a div and append 2 maps to this div, but the second map will only be created after clicking the "District/Town" label.

![2](https://user-images.githubusercontent.com/17487737/30151179-0daf0094-93e1-11e7-8d2c-bc6b8241d653.PNG)

**Comment by yohanboniface** [comment]
Hi @BLGEric 

Thanks for reporting this.
Can you please create a minimal testcase (without any external dependency) reproducing the issue, using for example http://playground-leaflet.rhcloud.com/ ?

**Comment by BLGEric** [comment]
https://jsfiddle.net/fsj2zbcx/
plz help, thanks.

**Comment by danzel** [comment]
It is because you change the DOM like this:
`document.getElementById('chartareapanel').innerHTML += "<div id='chart-area' style='height: 600px; margin-top:1.5%;'></div></div>";`

You need to use `append` / `appendChild` or something instead
