### ISSUE TITLE
Numeral 6 key causes zoom out

### ISSUE THREAD

**Issue by tumbo** [Leaflet/Leaflet#5766]
## How to reproduce

- Leaflet version I'm using: 1.0.3
- Browser (with version) I'm using: Chrome Version 60.0.3112.113 (Official Build) (64-bit)
- OS/Platform (with version) I'm using: OSX 10.11.3 

Go to [Leaflet home](http://leafletjs.com/)
Click on the map of London
Hit number 6 key 
map zooms out which seems unintended

## What behaviour I'm expecting and which behaviour I'm seeing
I wouldn't expect anything to happen in the map when hitting 6.  The minus key is intended for zooming out.  This is creating a problem with a form in which I can't enter the number 6 where as I can enter any other number or text.

**Comment by IvanSanchez** [comment]
This is a feature, not a bug. In french AZERTY keyboards one cannot tell apart between the `-` in the numeral 6, and a numeral 6 in any other keyboard.

See https://github.com/Leaflet/Leaflet/issues/3362 

If we didn't have this, french users get angry. If this is really a problem for you, please consider looking into a solution about and https://github.com/Leaflet/Leaflet/issues/3367 - taking extra care for old Safari versions.

**Comment by tumbo** [comment]
@IvanSanchez Thanks for the explanation and tip about a workaround.

**Comment by ivdekov** [comment]
I'm not quite sure what the workaround for this feature is. How can I remove "54" (number 6 on the keyboard) from the list of keys that trigger a zoom out?

**Comment by EugenRakhimov** [comment]
It may be a feature for the French keyboards, but for our users it feels like a bug - basically when they type in autocomplete number 6, it zooms instead of showing number 6, which is a pain. Is there a decent solution for disabling this behaviour for the cases where you don't expect a lot of people with French keyboards and expect a lot of people typing number 6?
