### ISSUE TITLE
CSS with `img { max-height: 100%; }` breaks rendering

### ISSUE THREAD

**Issue by idanen** [Leaflet/Leaflet#5775]
## How to reproduce
- Leaflet version I'm using: 1.2.0
- Browser (with version) I'm using: Chrome 60
- OS/Platform (with version) I'm using: Max OS 10.12.6
- step 1: Add the leaflet css and js
- step 2: Add the minimal markup
- step 3: Add a css rule to set all `img` tags `max-height` to 100%

## What behaviour I'm expecting and which behaviour I'm seeing
The map does not render.
The expected behavior is to render the map.
Possible solution is to "reset" the `max-height` the same as done for `max-width`, but I think the better solution would be to reset those values in the same place the size is being set.

## Minimal example reproducing the issue

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code (besides MapBox to render a map)

Using [codepen](https://codepen.io/idanen/pen/zEYBKg) to demonstrate.

I don't mind submitting a PR if someone more familiar with this library will point me to the relevant file(s).

**Comment by ghybs** [comment]
Hi,

Thank you for the detailed report!

It is indeed unfortunate to have to shield Leaflet against other libraries and app styling too many things, but anyway as you figured out, it is already done for `max-width`.

Please could create a PR on `dist/leaflet.css`?
https://github.com/Leaflet/Leaflet/blob/v1.2.0/dist/leaflet.css#L42-L50

**Comment by idanen** [comment]
Sure.
I'll do it later today.
