### ISSUE TITLE
Infinite loop on bad relative errorTileUrl

### ISSUE THREAD

**Issue by fetis** [Leaflet/Leaflet#5776]
## How to reproduce

- Leaflet version I'm using: 1.2.0
- Browser (with version) I'm using: Chrome
- OS/Platform (with version) I'm using: MacOs

Steps
1. Specify incorrect url for .tileLayer options, e.g. `https://example.com/{z}/{x}/{y}.png`
1. Specify incorrect _relative_ `errorTileUrl` option, e.g. `fake.png`

## What behaviour I'm expecting and which behaviour I'm seeing
I expect that load stops after the second 404 request. But actually I have infinite loop of request s trying to get error tile image.

## Minimal example reproducing the issue

I've created bin for demonstration
https://playground-leaflet.rhcloud.com/deye/1/edit?html,output

This issue is actually unfinished #5176. The problem is in TileLayer.js:191 
```
_tileOnError: function (done, tile, e) {
  var errorUrl = this.options.errorTileUrl;
  if (errorUrl && tile.src !== errorUrl) {      // <-- here
    tile.src = errorUrl;
  }
  done(e, tile);
},
```
`tile.src` and `errorUrl` don't match if you have  relative URL

**Comment by perliedman** [comment]
Huh, interesting. Did not know the `src` property was automatically expanded to an absolute URL. Thanks for reporting. We'll have to look into this.

Any help you can provide is of course very welcome!
