### ISSUE TITLE
Canvas bringToFront() not working

### ISSUE THREAD

**Issue by Zahma** [Leaflet/Leaflet#5777]
Is there any way to bring the canvas flows to the front ? I have 2 sets of objects, geojsonLayers and canvas lines. I tried to use bringToFront() but it seems its not implemented for Canvas elements.
I read in a forum that there is this solution:
mapInstance.getPanes()['tilePane'].style.zIndex = 2147483647;
but I don't think it works neither for Canvas elements.

**Comment by perliedman** [comment]
Hi!

It would be great if you could provide a running example of the problem, for example using [Leaflet Playground](http://playground-leaflet.rhcloud.com/?html,output) - this makes it a lot easier to find, understand and debug the problem.

`bringToFront` _is_ implemented in Leaflet since a few versions ago, so please tell which version you're seeing this in.

You can set `z-index` of panes, but if you have a single canvas, it will still be in the same pane, so changing the `z-index` will not re-arrange the layers within that canvas.

**Comment by Zahma** [comment]
hello, thank you for the help, in fact, the problem i'm facing is related to this plugin : https://github.com/jwasilgeo/Leaflet.Canvas-Flowmap-Layer

But when I draw polygons, they are drawn on the top of the flow lines. I tried to bring the geojson (polygon) layer to the back but doesn't seem to work

**Comment by perliedman** [comment]
@Zahma unfortunately, it is impossible for me to say what the problem might be: I'm not familiar with the plugin, and don't know how your code works.

Please note that `bringToFront` only works _within_ a renderer: from what you're writing, it might well be that your polygons are in separate renderer compared to the canvas layer, which would explain why `bringToFront` does not make any difference. Again, impossible to say without seeing what your code is actually doing.

For us to be able to help out, we need to see some code that reproduces the issue.

**Comment by Zahma** [comment]
@perliedman here is a link to see what I'm talking about:

http://playground-leaflet.rhcloud.com/xopi/1/edit?js,output

thank you

**Comment by perliedman** [comment]
Ok, so this is more or less like what I described above:

* You have three renderers active on your page: two canvas renderers and one SVG; one canvas is used by the flowmap plugin, and the borders you've added use the SVG renderer; the seconds canvas appears to be empty
* All three renderers are placed in Leaflet's overlay pane, all of them with `z-index: 100`, so the order of DOM elements determine their ordering, where the SVG renderer happens to be on top
* As mentioned above, `bringToFront` only re-orders layers _within a renderer_, so it will not have any effect on the different renderers ordering

To resolve this, you could for example place your country borders (the GeoJSON layer) in a separate pane which you assign a `z-index` lower than the default for Leaflet's overlay pane (which is 400). See the pane tutorial for an example on how to this.

Hope this helps!
