### ISSUE TITLE
TouchZoom Disable causes dragging to not work correctly

### ISSUE THREAD

**Issue by ChristopherTotty** [Leaflet/Leaflet#5779]
## How to reproduce

- Leaflet version I'm using: 1.2.0
- Browser (with version) I'm using: Chrome Version 61.0.3163.79 (Official Build) (64-bit)
- OS/Platform (with version) I'm using: Windows 10

Call map.touchZoom.disable(); and then begin panning the map using touch events.

## What behaviour I'm expecting and which behaviour I'm seeing
Expect panning the map to continue to work the way it does before touchZoom is disabled.
Instead, the map moves a few pixels and then a pointer cancel event causes the pan to stop.
If you do not have a touch screen, you may open Chrome developer tools and toggle the device toolbar to select a mobile device and simulate touch events with a mouse.

## Minimal example reproducing the issue
http://jsfiddle.net/3jprmbjv/

**Comment by ChristopherTotty** [comment]
This is probably a terrible, horrible, no good, very bad idea, but as a temporary workaround I attempted to set L.Browser.pointer = false, which would not stick for some reason, so I am instead setting window.PointerEvent = null before the app starts up.  With minimal testing, it seems to be working for my needs.

**Comment by srandhawaim8** [comment]
I've managed to solve this issue which affected mobile chrome browsers. You need to edit leaflet.css, add the following to .leaflet-container at line 243.
`-ms-touch-action: none;
    touch-action: none;`

Fixed it for me!
