### ISSUE TITLE
Will leaflet support setting popup direction?

### ISSUE THREAD

**Issue by chuduyunhuan** [Leaflet/Leaflet#5780]
Hi, 
I know the tooltip has achieved the goal, but i still want to know whether the popup will support it too some day?
Maybe a little inappropriate to mention this request, but I think it will be more convinent for us to customize our business needs.
Thanks and look forward to your reply.

**Comment by perliedman** [comment]
Hi @chuduyunhuan,

no plans on implementing this anytime soon in Leaflet core, and I think it's unlikely we would add it to Leaflet core, which we try to keep small.

However, I think you should look at the [Rrose plugin](http://erictheise.com/rrose/) which seems to do something similar. Might be other plugins that does this as well.
