### ISSUE TITLE
Flipped coordinates for circle when using toGeoJSON

### ISSUE THREAD

**Issue by ivanjaros** [Leaflet/Leaflet#5782]
I am preserving layer daya with toGeoJSON() method and I have noticed that when I want to recreate Circle layer I have to reverse the coordinates. For polygon, this is not an issue, only for circle.

**Comment by yohanboniface** [comment]
Hi @ivanjaros can you make a simple example showing the issue (for example using http://playground-leaflet.rhcloud.com/) ? Thanks!

**Comment by OlmoDalco** [comment]
[geoJSON spec: ](http://geojson.org/geojson-spec.html#positions)The order of elements must follow x, y, z order (easting, northing, altitude for coordinates in a projected coordinate reference system, or longitude, latitude, altitude for coordinates in a geographic coordinate reference system). 
--> geojson coordinates: [lon/lat]

Circle-layers are using [lat/lon] coordinates.

**Comment by perliedman** [comment]
As @yohanboniface said, this will be much easier if you provide actual code that illustrates the problem. This is why we mention this in the issue template. It saves time for everyone.

Here's an example that creates a `Circle`, adds it to the map, and logs the output of the `toGeoJSON` method: http://playground-leaflet.rhcloud.com/genim/

In this example, the coordinates are indeed output in lng/lat order, as expected:

```JSON
{"type":"Feature","properties":{},"geometry":{"type":"Point","coordinates":[30.51,50.5]}}
```

Please provide example code if you see something else.

**Comment by perliedman** [comment]
Closing since there hasn't been any activity or more info.
