### ISSUE TITLE
Request to remove Guggenberger Airport in Sartell, MN that no longer exists

### ISSUE THREAD

**Issue by pavlovagency** [Leaflet/Leaflet#5795]
![when did we get an airport in sartell](https://user-images.githubusercontent.com/20447325/30714740-9959dea4-9ed9-11e7-971e-be955990c7ea.PNG)

## How to reproduce

- Leaflet version I'm using: 1.2
- Browser (with version) I'm using: Chrome Version 60.0.3112.113 
- OS/Platform (with version) I'm using: Mac OSX
- Zoom to Sartell, Minnesota (northwest of St. Cloud, MN)
- See Guggenberger Airport included in the map

## What behaviour I'm expecting and which behaviour I'm seeing

Guggenberger Airport no longer exists and should not be included on the map.

Leaflet displays Guggenberger Airport in Sartell, Minnesota. We request that it be removed for accuracy.

## Minimal example reproducing the issue

See attached screenshot

- [ X ] this example is as simple as possible
- [ X ] this example does not rely on any third party code

Using http://playground-leaflet.rhcloud.com/ or any other jsfiddle-like site.

**Comment by yohanboniface** [comment]
Leaflet is just a tool to display maps on a browser, it has no idea about the map nor the data behind the map.

In this case, it seems this is a map build on top of openstreetmap, which is editable by anyone, even by you: http://www.openstreetmap.org/about, so you can fix the issue yourself, great! :)
