### ISSUE TITLE
how to have pegman (street view icon) in leaflet map?

### ISSUE THREAD

**Issue by Rakshya18** [Leaflet/Leaflet#5796]
The street view icon (pegman) is default in google map but is not visible in leaflet maps. I would like to drag the pegman on the map to view the street view of particular location.
Thank you

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
