### ISSUE TITLE
Tapping on map doesn't blur previous focused element

### ISSUE THREAD

**Issue by cherniavskii** [Leaflet/Leaflet#5798]
Why event in [`_onDown`](https://github.com/Leaflet/Leaflet/blob/master/src/map/handler/Map.Tap.js#L41) function is `preventDefault`'ed? Is there any reason for that?

I'm asking, because I have troubles with touch events on mobiles and this line is actually making those troubles.

**Comment by cherniavskii** [comment]
Sorry for omitting issue template. It started as a question, but now I'm sure it's a bug.

- Leaflet version I'm using: 1.2.0
- Browser (with version) I'm using: Chrome in mobile mode
- OS/Platform (with version) I'm using: Linux

**Steps to reproduce**:
1. Open https://jsbin.com/yozoda/edit?html,output in Google Chrome browser
2. Open a Live Preview (to make sure map will not be in `iframe`)
3. Open Chrome devtools and enable mobile mode (Ctr l+ Shift + M)
4. Focus an input under the map
5. Tap on the map

**Expected behavior**:
Input looses focus.

**Actual behavior**:
Input stays focused.
![peek 2017-09-22 21-41](https://user-images.githubusercontent.com/13808724/30761520-d39bdbf2-9fde-11e7-92eb-09f9dec95319.gif)

**Comment by cherniavskii** [comment]
I found the problem - it's right [here](https://github.com/Leaflet/Leaflet/blob/master/src/dom/DomEvent.Pointer.js#L63).
All pointer events except those from `TAG_WHITE_LIST` are `preventDefault`'ed.
Before [adding that white list](https://github.com/Leaflet/Leaflet/pull/4371) all events were `preventDefault`'ed. Why do we need to `preventDefault` those events?

**Comment by daverayment** [comment]
Hi. I haven't had chance to confirm, but I think the issue may be with line 58. Instead of:

`if (e.pointerType !== 'mouse' && e.pointerType !== e.MSPOINTER_TYPE_MOUSE && e.pointerType !== e.MSPOINTER_TYPE_MOUSE) {`

It should be:

`if (e.pointerType !== 'mouse' && e.MSPOINTER_TYPE_MOUSE && e.pointerType !== e.MSPOINTER_TYPE_MOUSE) {`

As it stands, I suspect the IE11-specific code is being called for non-IE browsers.

**Comment by perliedman** [comment]
This is the original commit with the conditional `preventDefault`: https://github.com/Leaflet/Leaflet/commit/c60fd1d17b55af8815274cbcfcaf1f8ecb3fa32f

Before that, all events in there where `preventDefault`ed, see this: https://github.com/Leaflet/Leaflet/commit/dbced20543af251d0a87089e0bcef5e12c625fa0 (fixing #2000). So, touch devices with IE8 seems to be the original reason - as a side note I would bet we haven't too many of them these days...

This code is full of workarounds for all sorts of browser weirdness, so at least I find it very hard to reason about what is "reasonable". Unfortunately, it's also lacking comments, so it's hard to tell what is necessary and why it looks the way it does...

**Comment by daverayment** [comment]
This PR seems to be relevant for the line I mentioned above:

[https://github.com/Leaflet/Leaflet/pull/5185](url)

I'm not sure why it was subsequently changed to check `e.pointerType !== e.MSPOINTER_TYPE_MOUSE` twice, but I suspect that's a typo.

Sorry I can't be more help; as you say, the workarounds for browser idiosyncrasies make it difficult to diagnose.

**Comment by perliedman** [comment]
Hm, yes, you're right! Good catch. That's a typo introduced in 703ae02aa8cbd0b87be5b01e77754b83ad732267, it just checked the existence of `MSPOINTER_TYPE_MOUSE` before that. Should be safe to revert to that behaviour!

**Comment by daverayment** [comment]
Thanks, @perliedman. I'm not really a github regular, but I've tried to do a PR for this myself: https://github.com/Leaflet/Leaflet/pull/5817.
