### ISSUE TITLE
Base layer (map) and overlay in different projections (CRS)

### ISSUE THREAD

**Issue by petrovnn** [Leaflet/Leaflet#5801]
I want to display an overlay with an elliptical projection (coverage area of the cellular network) over OSM.

Is this possible?

Found an option
`map.options.crs = L.CRS.EPSG3395`
which switches the entire map to a new projection mode, but in this mode, the OSM tiles (substrate) are displayed with an offset.

Tried to set this option for the overlay, but it looks like it does not work
```
var mts_lte = new L.TileLayer('http://tiles.mts.ru/LTE_New/{z}/{x}/{y}', {
  isElliptical : true,
  subdomains: 'abc'
});
mts_lte.options.crs = L.CRS.EPSG3395; // NOT WORKING (no this options for overlays?)
```
Does `L.CRS` work only for the base layer? or is there a way to apply for an overlay separately?

Here's Jsfiddle, showing the problem:
http://jsfiddle.net/petrovnn/3j6jtxfy/21/

**Comment by perliedman** [comment]
Hi and thanks for using Leaflet!

Please note that this is our issue tracker, where bugs and feature requests and posted and discussed. For questions on how to use Leaflet and other support, you're better off using [stackoverflow](https://stackoverflow.com/) or [gis.stackexchange.com](https://gis.stackexchange.com/).

Having said that, what you want is to reproject your overlay data from its current projection to the map tiles' projection (OpenStreetMap tiles are in EPSG 3857 and you can't easily change that). You might want to look at [Proj4Leaflet](https://github.com/kartena/Proj4Leaflet/) that can do on the fly reprojection of GeoJSON data, or [reproject](https://github.com/perliedman/reproject/).
