### ISSUE TITLE
Draw point in canvas grid layer, it's position offset.

### ISSUE THREAD

**Issue by linghuam** [Leaflet/Leaflet#5802]
## How to reproduce

- Leaflet version I'm using: leaflet 1.0.0
- Browser (with version) I'm using: chrome 61
- OS/Platform (with version) I'm using: windows 7
- step 1
Open the [example](https://linghuam.github.io/test/20170922/index.html) in Google Chrome browser
- step 2
Zoom the map 

## What behaviour I'm expecting and which behaviour I'm seeing
**Problem Description：**
I inherit from 'L.TileLayer' and modify the method 'createTile' to create each tile use an canvas element. 
In 'createTile' method,I send an ajax to get each tile's data, which is a collection of latlngs.
In ajax callback, I get the data and translate the canvas's origin point. 
Finally, I use 'latLngToLayerPoint' to transform the latlng and draw it in canvas.

**Expected behavior:**
I expect to see the point is drawn on canvas and it's position is correct. 

**Actual behavior:**
I zoom the map , its position has offset.

## Minimal example reproducing the issue

- [X] this example is as simple as possible
- [ ] this example does not rely on any third party code

http://playground-leaflet.rhcloud.com/puguy/embed?html,css,js,output
``` js
    // custom tile layer (asynchronous)
    var ShipCanvasTileLayer = L.TileLayer.extend({
        createTile: function (coords, done) {
            var tile = L.DomUtil.create('canvas', 'leaflet-tile');
            var size = this.getTileSize();
            tile.width = size.x;
            tile.height = size.y;

            // get tile latlngBounds
            var tilebounds = this._tileCoordsToBounds(coords);
            var topleft = this._map.latLngToLayerPoint(tilebounds.getNorthWest());
            console.log('coords:[' + coords.x + ',' + coords.y + ',' + coords.z + ']');
            console.log('topleft:[' + topleft.x + ',' + topleft.y + ']');

            // send ajax (This is a test.In fact, I want to get data by each tile's latlngbounds! )
            $.getJSON('./data/test.json', function () {
                var ctx = tile.getContext('2d');
                ctx.clearRect(0, 0, tile.width, tile.height);
                ctx.save();
                ctx.font = 'normal 36px Verdana';
                ctx.fillStyle = "#F00";
                ctx.fillText(coords.x + ',' + coords.y + ',' + coords.z, 250, 250);
                ctx.strokeRect(0, 0, 512, 512);
                // translate the origin point
                ctx.translate(-topleft.x, -topleft.y);
                var test_latlng = L.latLng(39, 116);
                if(tilebounds.contains(test_latlng)) {
                    L.marker(test_latlng).addTo(this._map);
                    var point = this._map.latLngToLayerPoint(test_latlng);
                    console.log('layerPoint:['+ point.x + ',' + point.y + ']');
                    ctx.arc(point.x, point.y, 6, 0, Math.PI*2);
                    ctx.fill();
                }
                ctx.restore();
                done(null, tile);
            }.bind(this));
            return tile;
        }
    });
    // add layer
    new ShipCanvasTileLayer('', { tileSize: 512 }).addTo(map);
```

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
