### ISSUE TITLE
Alternative ways to show leaflet contribution

### ISSUE THREAD

**Issue by treecon** [Leaflet/Leaflet#5803]
This is not a Leaflet issue but I suppose I can only ask here.

I use Leaflet in a hybrid app I build and I would like to add some custom menus that would probably hide Leaflet contribution (bottom-right). Of course, I wouldn't want to hide the contribution, I respect the job that has be done and the fact that is been given free to us.

The question is: could I hide the contribution and clearly declare in the 'About' tab that the maps are shown using Leaflet (with a link to Leaflet website)? Would you approve this? If no, I understand that I have to show it the "traditional" way.

Thank you!

**Comment by perliedman** [comment]
Hi there!

I guess we're talking about the attribution which by default displays the "Leaflet" link in the lower right corner? In that case, there's absolutely no obligation to show this message, it's just a nice default that give the library some publicity. You're free to remove it by just setting the option `attributionControl: false` when creating the map.

Note however that you might be required to show attribution for the map data / tiles you use, and we can't say anything about that: depending on your map provider, you might still be required to show a copyright notice or similar within the map. So I advice you to double check what attribution rules you have for the map data.
