### ISSUE TITLE
Something confused about worldCopyJump

### ISSUE THREAD

**Issue by chuduyunhuan** [Leaflet/Leaflet#5811]
Hi, I met a problem about worldCopyJump option these days. It may be described as below.

"When some sites are located in the Eastern Hemisphere and some other sites in the Western Hemisphere, and the dateline is near the center of the view, only some of the sites will be shown."

My target is to show all the sites if it's location is in screen range. So, is there any solution to this problem?

Look forward to your reply.
Thanks.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
