### ISSUE TITLE
Custom map (CRS) - how to convert JPG to TileLayer tiles

### ISSUE THREAD

**Issue by reissr** [Leaflet/Leaflet#5816]
I need your assistance with an easy (I think..) one.

I have a JPG file with a map which isn't in a real scale, and can't be represented by real geographical latitude and longitude, so I so the Leaflet CRS solution and this seems like the way to go.

The problem is that the map file (JPG) size is ~30MB and can't be loaded in a single request, so I read a bit more and found the TileLayer solution.
I even found a demo (the code is also provided below) :)

Now, my only problem is how can I take the JPG file and convert it to layers? Is there an online / offline tool for that? As far as I understand, all I need is to split the large image to 256px x 256px tiles, place it in directories in my server and TileLayer will do the rest?

**Comment by perliedman** [comment]
Hi and thanks for using Leaflet!

Please note that this is our issue tracker, where bugs and feature requests and posted and discussed. For questions on how to use Leaflet and other support, you're better off using [stackoverflow](https://stackoverflow.com/) or [gis.stackexchange.com](https://gis.stackexchange.com/).

Having said that, I think you might find gdal2tiles useful: http://www.gdal.org/gdal2tiles.html
