### ISSUE TITLE
Bounds on TileLayer Ignored

### ISSUE THREAD

**Issue by jambonrose** [Leaflet/Leaflet#5818]
## How to reproduce

- Leaflet version I'm using: 1.2.0
- Browser (with version) I'm using: Chrome 61, Firefox 55
- OS/Platform (with version) I'm using: macOS 10.11
- Create a `TileLayer` with `bounds` option set (https://jsfiddle.net/z39w65vd/)
- Zoom out

## What behaviour I'm expecting and which behaviour I'm seeing

When specifying `bounds` on a `TileLayer`, I expect that tiles will only be loaded within those bounds (as per the [documentation](http://leafletjs.com/reference-1.2.0.html#tilelayer-bounds): 'If set, tiles will only be loaded inside the set LatLngBounds').

Instead, I find that the bounds are not respected. At first load, tiles outside of the bounds are loaded (but that could be a floating point error?). However, when zooming out the bound area grows unexpectedly.

Possibly related to #5536

## Minimal example reproducing the issue

I could not get playground-leaflet.rhcloud.com to load, and instead created a [jsfiddle](https://jsfiddle.net/z39w65vd/). To illustrate the bounding box, I created two markers at the corners.

**Comment by cherniavskii** [comment]
Hey, @jambonrose 
I checked your jsfiddle and looks like it works as expected - map loads tiles inside bounds. In your case there's always only one tile loaded.
![peek 2017-10-03 18-43](https://user-images.githubusercontent.com/13808724/31137388-6c775bb4-a86b-11e7-844a-0d2e117fb7c0.gif)

**Comment by jambonrose** [comment]
Thanks for the quick response! Oh dear, I'm sorry about that. I misunderstood the feature - I was expecting that only the box between the two markers would ever have a map. If you could point me in the right direction to do that, I'd appreciate it.

**Comment by ghybs** [comment]
Hi @jambonrose,

If my understanding is correct, you would like to show only a small map portion, possibly smaller than a single tile.

In that case, you would probably be interested in that post:
https://gis.stackexchange.com/questions/174868/how-to-hide-leaflet-base-map/174869#174869

The general solution is to use the [TileLayer.BoundaryCanvas](https://github.com/aparshin/leaflet-boundary-canvas) plugin. You can use arbitrary boundaries, not just a rectangle.

Hope this helps.

**Comment by jambonrose** [comment]
Hi @ghybs, The BoundaryCanvas plugin appears to do the trick! Thanks very much!
