### ISSUE TITLE
Tile rendering on retina displays

### ISSUE THREAD

**Issue by fredleefarr** [Leaflet/Leaflet#582]
I've been looking at ways to sharpen the display of tiles on retina displays (e.g iPhone & new iPad) with Leaflet and have found out something interesting. 

If I create a tile which is 512 x 512 pixels instead of 256 x 256, and add the path to this tile size in exactly the same way as would with normal tiles, Leaflet handles it perfectly. On IOS my tiles are rendered with no anti-aliasing at all, and look stunning.

Very impressed. I'm wondering if this behaviour is by design, or if this 'feature' might break in future releases?

Obviously this technique has performance implications, especially with the larger tile sizes generated.

If anyone would like to see a demo URL, let me know and I can post one here.

**Comment by anselmdk** [comment]
http://leafletjs.com doesn't seem to display any retina map...

**Comment by taozhi8833998** [comment]
detectRetina option for TileLayer
