### ISSUE TITLE
Sidebar doesn't overlay with Leaflet 1.2.0

### ISSUE THREAD

**Issue by JellisHeRo** [Leaflet/Leaflet#5829]
In utilizing two different versions of leaflet (1.2.0 vs 0.7.7), I realized 1.2 does not allow for the me to overlay a sidebar on the leaflet map as does the 0.7.7 version. More specifically, with 1.2.0, it is my leaflet map that overlays everything else in the `<body>`.  I use either Chrome version 61.0.3163.100  or Microsoft Edge to view my maps, and the code below is how my HTML template looked upon utilizing the different leaflet versions, for observed consistency. I dont know if something changed between the two Leaflet versions, but I figured this has got to either be a bug or there is some new method of overlaying HTML objects over the leaflet. Any clues on what is happening here?

```
<!DOCTYPE html>
<html>
  <head>
    <title>Leaflet with a Side Panel </title>

    <!-- CSS Imports -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.2.0/dist/leaflet.css" />
     <style type="text/css">
        #map{
            position: absolute;
            top: 0;
            height: 100%;
            right: 0;
            left:0;
        }
      </style>

  </head>

  <body>

    <!-- Map -->
    <div id="map"></div>

    <!-- Sidebar -->
    <div class="sidebar">
      <div id="sidebar_top">
        <h2 class="Slide-title">THIS IS A SIDEBAR</h2>
        <p class="Slide-text">by Author</p>
      </div>
      <div id= "sidebar-bottom">
        <h3 id="data-attribution">
          Data: Whatever the data source is.
        </h3>
      </div>
    </div>

    <!-- Javascript Imports -->
    <script src="js/leaflet.js"></script>   <!-- HERE I WOULD JUST SWITCH THE VERSIONS IN THE DIRECTORY -->

    <script>
       
        var map = L.map('mapContainer',{zoomControl:false}).setView([40.7128, -74.0059], 11); // initiating map
        var layer = L.tileLayer('https://cartodb-basemaps-{s}.global.ssl.fastly.net/dark_all/{z}/{x}/{y}.png', { 
            maxZoom: 18, 
            attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a>, &copy; <a href="https://carto.com/attribution">CARTO</a>' // Give credit where its due.
          }
        ).addTo(map); 
    </script>


  </body>
</html>
```

**Comment by cherniavskii** [comment]
Hey @JellisHeRo,
Please provide description of actual and expected behavior, as well as links to bug reproduction on JSbin or other playground.
In the future, do not ignore issue template when reporting bugs. Also, take a look at [Reporting bugs](https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md#reporting-bugs) section of Contributing guide.

**Comment by simon1tan** [comment]
I had this issue with a different sidebar. I added a z-index to the map and it works now.
