### ISSUE TITLE
SCSS support

### ISSUE THREAD

**Issue by fox91** [Leaflet/Leaflet#5832]
It seems to me that CSS code is written directly into [dist](https://github.com/Leaflet/Leaflet/blob/master/dist/leaflet.css).
There are plans to transform the source into SCSS or similar?

**Comment by IvanSanchez** [comment]
The answer is "no".

See also #4586

**Comment by fox91** [comment]
But my purpose wasn't size savings like in #4586, but having variables in SCSS to simplify writing plugins style.
