### ISSUE TITLE
Legend issue on Chrome: with many colours only first is visible

### ISSUE THREAD

**Issue by Robinlovelace** [Leaflet/Leaflet#5841]
Apologies for the lack of code but this is a bug affecting a deployed website that hundreds of people are using to help plan better cycling infrastructure. A few months ago we got a report of a broken scale bar and now I suspect it's quite widespread as many people upgrade to the latest version of Chrome (it didn't seem to be an issue with older versions).

## How to reproduce

- Leaflet version 1.0.3 but just double checked and it also affects the latest version 1.2.0
- With a recent version of Chrome on Windows (seems to work on Linux although there are still issues with alignment) go to our website: http://www.pct.bike/
- Alternatively you can reproduce this bug downloading this [repo ](https://github.com/npct/pct-shiny)and opening the file `pct-shiny-master/regions_www/la-map.html` in your browser, if you've got the right one...
- Browser (with version) I'm using: Google Chrome 61.0.3163.100
- OS/Platform (with version) I'm using: Windows

## What behaviour I'm expecting and which behaviour I'm seeing

I expect to see this (on Firefox): 

![image](https://user-images.githubusercontent.com/1825120/31574722-1c5e3ed0-b0cd-11e7-9fac-d444b1a42a58.png)

I see this:

![image](https://user-images.githubusercontent.com/1825120/31574729-2de2b2c6-b0cd-11e7-8f76-97f94068c8ae.png)

I thought it may have been due to our use of rstudio/leaflet (I'm an R guy) but that front page map was put together by @nikolai-b and @usr110 with js so I suspect it may be a bug with Chrome/Leaflet. Potentially useful to people here, hence posting.

We would be very grateful for any advice as we're a little stumped as you'll see on this long-standing issue on our issue tracker: https://github.com/npct/pct-shiny/issues/635

**Comment by cherniavskii** [comment]
Hi @Robinlovelace,
Leaflet has nothing to do with your custom controls.
If you are really sure this is a Leaflet bug - please provide minimal example reproducing this issue, without third-party plugins/libraries.

**Comment by Robinlovelace** [comment]
Ok thanks for clarifying. Guess the next step is to discover which 3rd party plugin is responsible.

**Comment by ghybs** [comment]
Hi @Robinlovelace,

For the sake of debugging, have you tried disabling Chrome hardware acceleration setting?
https://stackoverflow.com/questions/46778354/leaflet-legend-colours-not-showing-in-chrome

**Comment by Robinlovelace** [comment]
I've not tried that - will take a look asap. @usr110 and @nikolai-b are you up for taking a look? Thanks for the link and suggestion.

**Comment by Robinlovelace** [comment]
That fixed it: 
![image](https://user-images.githubusercontent.com/1825120/31811273-d71b5b56-b576-11e7-9407-1f5e37be0198.png)

Furthermore I think it is an issue with Leaflet although it looks like an issue with Chrome. Is there a more appropriate place to report this?

**Comment by ghybs** [comment]
Please provide a minimal code example that reproduces the issue.
Otherwise I doubt we will be able to work on it.

Chrome has also a [bug tracker](http://dev.chromium.org/for-testers/bug-reporting-guidelines).
