### ISSUE TITLE
GridLayer's test fail

### ISSUE THREAD

**Issue by cherniavskii** [Leaflet/Leaflet#5844]
[This test](https://github.com/Leaflet/Leaflet/blob/master/spec/suites/layer/tile/GridLayerSpec.js#L631) fails in Chrome / Firefox (didn't test other browsers) since #4704 was merged.
The reason it's failing is [this change](https://github.com/Leaflet/Leaflet/pull/4704/files#diff-f1e6be67599c594731fff6191c710420L579) in `_onMoveEnd` method.
GridLayer unloads 12 tiles instead of 16 (doesn't unload those 4 in bounds). 

@yohanboniface can you take a look on this?
For me it looks like test should be updated to check 12 unloads instead of 16.
But there is possibility it's a bug.

**Comment by cherniavskii** [comment]
PR mentioned above also broke those tests:
[Loads map, moves forth by 512 px, keepBuffer = 0](https://github.com/Leaflet/Leaflet/blob/master/spec/suites/layer/tile/GridLayerSpec.js#L831)
[Loads map, moves forth and back by 512 px, keepBuffer = 0](https://github.com/Leaflet/Leaflet/blob/master/spec/suites/layer/tile/GridLayerSpec.js#L856)

**Comment by cherniavskii** [comment]
@yohanboniface friendly ping :)

**Comment by yohanboniface** [comment]
Sorry, missing more notifications than ever since last update on Github notifications management.
I'll try to have a look this week, but no guarantee.

**Comment by cherniavskii** [comment]
@yohanboniface cool, thanks ;)

**Comment by ghybs** [comment]
Fixed by PR's https://github.com/Leaflet/Leaflet/pull/6199 and https://github.com/Leaflet/Leaflet/pull/6202
