### ISSUE TITLE
ImageOverlay: if add/remove/add it doesn't fire the "load" event anymore.

### ISSUE THREAD

**Issue by fmarzocca** [Leaflet/Leaflet#5852]
Today I have experienced this issue: if I remove an ImageOverlay layer  (with `map.removeLayer(ovr_layer)`) and then add it back, the "load" event is not fired again. This is not happening with TileLayers.

**Comment by fmarzocca** [comment]
As a workaround, together with `removeLayer` I had to delete the `_image` option in the ImageOverlay:

```
map.removeLayer(ovr_layer);
ovr_layer._image='';
```

Now it fires the `load` event when added back.

**Comment by cherniavskii** [comment]
Hi Fabio,
Thanks for using Leaflet!

Please do not discard issue template when reporting bugs - it is there for a purpose. It helps us to investigate a bug.
Please provide minimal example reproducing the issue.
You can create a fork from this JSFiddle https://jsfiddle.net/puvx6L66/.
