### ISSUE TITLE
Performance for highlighting features

### ISSUE THREAD

**Issue by exotfboy** [Leaflet/Leaflet#5860]
I have almost 10K+ polygon features (inside the viewport) to be added to the map, and I have two ideas:

1 Add them all to the map with opacity of `0`, then the features are invisible, then add `mouseover` and `mouseout` event to each feature, set the opacity to `1` when hovered.

2 Load the features in memory without adding to the map, and listen the `mousemove` event and detect if the  mouse is inside a polyogn, if yes add the feature to the map dynamically, also I have to remove it accordingly.

Which is better?

**Comment by perliedman** [comment]
Hi and thanks for using Leaflet!

However, please do not just discard the issue template - it's there for a reason. Specifically, this clearly is not an issue, but rather a question on how to use Leaflet. Note that this is our issue tracker, where bugs and feature requests and posted and discussed. For questions on how to use Leaflet and other support, you're better off using [stackoverflow](https://stackoverflow.com/) or [gis.stackexchange.com](https://gis.stackexchange.com/).
