### ISSUE TITLE
Wheel events don`t set originalEvent

### ISSUE THREAD

**Issue by rshadow** [Leaflet/Leaflet#5884]
## How to reproduce

- Leaflet version I'm using: 1.2.0
- Browser (with version) I'm using: Firefox 57
- OS/Platform (with version) I'm using: Debian GNU Linux
- Add listeners on `zoom` and `move` events
- Scroll mouse whell on map
- See event object in browser debugger

## What behaviour I'm expecting and which behaviour I'm seeing
I expect event.originalEvent field filled of original event object. But it`s missing.

## Minimal example reproducing the issue
```js
var m = L.map(...);        
m.addEventListener('zoom', function(event){
    // 'zoom', Object, undefined
    console.debug('zoom', event, event.originalEvent);
});
m.addEventListener('move', function(event){
    // 'move', Object, undefined
    console.debug('move', event, event.originalEvent);
});
```

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by rshadow** [comment]
I want to separate events made by the user from internal events. For example, raise `fitBounds` when receive new data (markers, tracks, etc.). But if the user himself moved the map, then do not automatically raise `fitBounds`.

**Comment by IvanSanchez** [comment]
This is behaviour as expected.

If you read http://leafletjs.com/reference-1.2.0.html#event-objects carefully, you'll see that only `KeyboardEvent` and `MouseEvent` implement the `originalEvent` property. Check the list of map events at http://leafletjs.com/reference-1.2.0.html#map-event to see that `zoom` and `move` are neither a `KeyboardEvent` nor a `MouseEvent`.

**Comment by IvanSanchez** [comment]
As a feature request, this could be considered a duplicate of https://github.com/Leaflet/Leaflet/issues/2934 , so no reason to keep this open.

**Comment by rshadow** [comment]
So. Leaflet use `mousewhell` events but is`t not `MouseEvent`. Maybe need write issue for this?

**Comment by rshadow** [comment]
Ok. Thanks.

**Comment by IvanSanchez** [comment]
> So. Leaflet use `mousewhell` events but it is not `MouseEvent`. Maybe need write issue for this?

Yeah. Leaflet will listen to either `mousewheel` *or* `wheel` depending on [browser support](https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent#Browser_compatibility). And while currently Leaflet wraps `mousedown`, `touchstart` and `pointerdown` DOM events as a single `mousedown` event, it does not the same for `wheel`.

Having a `wheel` event at `L.Map` makes some sense. Feel free to open a issue for that. Keep in mind that such a `wheel` event would not necessarily imply any zoom events.

**Comment by gideongrossmanHome** [comment]
> I want to separate events made by the user from internal events. For example, raise `fitBounds` when receive new data (markers, tracks, etc.). But if the user himself moved the map, then do not automatically raise `fitBounds`.

@rshadow 
Did you ever find a solution. I am in the same exact conundrum.

**Comment by rshadow** [comment]
> Did you ever find a solution. I am in the same exact conundrum.

It was a long time ago. But I looked at the code and write about what I was doing.

```
# contructor:
self.manualzoom = false;
...

MyMap.prototype.fitAll = function( force ){
    var self = this;
    if( ! force &&   self.manualzoom )   return;
    ...
    # self.leaflet.fitBounds(...);
}

self.leaflet.on('zoom move', function( event ){
            if( ! event.originalEvent ) return;
            self.manualzoom = true;
});
```

and use `self.fitAll(true)` if user force show all data on map. Or `self.fitAll()` for background updates.

Sorry I can’t remember exactly the problem. I hope it helped at least something.
