### ISSUE TITLE
Tile layer allows setting crossorigin true but doesn't let you set crossorigin property

### ISSUE THREAD

**Issue by desean1625** [Leaflet/Leaflet#5891]
## How to reproduce
Have a tile server that requires credentials 
- Leaflet version I'm using:1.2.0
- Browser (with version) I'm using:Firefox 45 and chrome 50

## What behaviour I'm expecting and which behaviour I'm seeing
Need to specify anonymous or use-credentials invalid or empty string is handled as anonymous per https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes

I can fork and make a PR if needed.

**Comment by IvanSanchez** [comment]
Yes, I think a PR would be the best way. That way it's possible to comment and provide some feedback on the approach.

Maybe the easiest way is to let the user use either a `boolean` or a `string` for the `crossOrigin` option.

**Comment by desean1625** [comment]
Yes I was just going to make the option false or string then pass the string in as the crossorigin value
