### ISSUE TITLE
img render fail by ImageOverlay ,in IOS 11.0.3

### ISSUE THREAD

**Issue by Fatty-Shu** [Leaflet/Leaflet#5895]
## How to reproduce

- Leaflet version I'm using:[leaflet1.2.0](https://unpkg.com/leaflet@1.2.0/dist/leaflet.js)
- Browser (with version) I'm using:Safair
- OS/Platform (with version) I'm using:IOS 11.0.3

initialize the map on the "map"
add a ImageOverlay layer to map 
I tested it,this phenomenon appear because  use translate3d. Use translate,this phenomenon disappear

## What behaviour I'm expecting and which behaviour I'm seeing
page loaded,but the imageOverlay's layer don't  full display.

***I'm seeing:***

<img width="350" src="https://user-images.githubusercontent.com/26493779/174797129-1ac4e5d9-3c0d-4353-9e7e-6a970405be6a.PNG">

***I'm expecting:***  

<img width="350" src="https://user-images.githubusercontent.com/26493779/174797196-2e529e4a-bd99-44d6-bece-3ab313172aa5.png">

## Minimal example reproducing the issue
```html
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.2.0/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.2.0/dist/leaflet.js"></script>
    <style type="text/css">
      html,body{
        width: 100%;
        height: 100%;
        margin: 0;
        overflow: hidden;
        padding: 0;
      }
    </style>

  <div id="map" style="width: 100%;height: 100%;"></div>
  <script type="text/javascript">
      var imageUrl = 'http://www.lib.utexas.edu/maps/historical/newark_nj_1922.jpg',
          imageBounds = [[23.163088509988,113.40087890625], [23.16592930413,113.406372070313]];
      var map=L.map("map",{
          center:[23.164508907059002, 113.4036254882815],
          zoom:16
      })
      L.imageOverlay(imageUrl, imageBounds).addTo(map);
  </script>
```

**Comment by IvanSanchez** [comment]
This rather looks like the map container is not using 100% of the viewport height. What's the CSS being applied to your `<body>`?

**Comment by Fatty-Shu** [comment]
all code 
```html
<!DOCTYPE HTML>
<html>  
  <head>

    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <title>IOS 11.0.3</title>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.2.0/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.2.0/dist/leaflet.js"></script>
    <style type="text/css">
      html,body{
        width: 100%;
        height: 100%;
        margin: 0;
        overflow: hidden;
        padding: 0;
      }
    </style>
  </head>
<body>
  <div id="map" style="width: 100%;height: 100%;"></div>
  <script type="text/javascript">
      var imageUrl = 'http://www.lib.utexas.edu/maps/historical/newark_nj_1922.jpg',
          imageBounds = [[23.163088509988,113.40087890625], [23.16592930413,113.406372070313]];
      var map=L.map("map",{
          center:[23.164508907059002, 113.4036254882815],
          zoom:16
      })
      L.imageOverlay(imageUrl, imageBounds).addTo(map);
  </script>
</body>
</html>
```
I'm sure,the container height is 100%

**Comment by davidgil** [comment]
Hi, i seen this also with ios devices and "leaflet": "1.0.3", not always, only sometimes, probably with big images.

**Comment by perliedman** [comment]
Does setting [`L_DISABLE_3D`](http://leafletjs.com/reference-1.2.0.html#global-switches)` = true` fix this issue for you?

It sounds like a browser bug; if it is, we should think about if there's a sensible way to detect it and disable `transform3d` for `ImageOverlay`s for this case.

**Comment by sheppard** [comment]
I am experiencing this issue when running Leaflet in a UIWebView on iOS 11.  Setting `L_DISABLE_3D=true` solves the issue.  When running in the iOS 10 UIWebView, or in iOS 11 Safari (which presumably uses WKWebView), the issue does not appear for me - even though 3d appears to be enabled in both cases (`L.Browser.any3d == true`).

**Comment by barrycarter** [comment]
Random babbling that may or may not be helpful:

I added one line to the setTransform() function in DomUtils.js for debugging:


```
export function setTransform(el, offset, scale) {
	var pos = offset || new Point(0, 0);


// when scale is 256, image is mangled; when scale is 512 or higher, image disappears
console.log("BETA: called, setTransform ", el, offset, scale);

	el.style[TRANSFORM] =
		(Browser.ie3d ?
			'translate(' + pos.x + 'px,' + pos.y + 'px)' :
			'translate3d(' + pos.x + 'px,' + pos.y + 'px,0)') +
		(scale ? ' scale(' + scale + ')' : '');
}


```
As the comments note, the scale value is 256, the image is mangled, but still shows. When the scale value is 512, the image disappears entirely.

What's causing this? I believe that, under the hood, Leaflet is calling HTML5's canvas native zoom method, and, as https://stackoverflow.com/questions/6081483/maximum-size-of-a-canvas-element notes, browsers have (different) inherent zoom limits.

I think this problem is related to https://github.com/Leaflet/Leaflet/issues/4686 which warns that the browser isn't going to display everything. As the issue notes, you can defeat the warning, but you can't actually change the behavior.

**Comment by jonkoops** [comment]
This issue seems to have been resolved in recent versions of Safari (see https://github.com/Leaflet/Leaflet/issues/6322#issuecomment-1301197444). Closing this issue.

**Comment by Fatty-Shu** [comment]
您的邮件已收到，我会尽快处理。谢谢！
 
舒佳锦
