### ISSUE TITLE
invalidateSize method docs

### ISSUE THREAD

**Issue by cherniavskii** [Leaflet/Leaflet#5896]
`Zoom/Pan options` in [`invalidateSize` method](http://leafletjs.com/reference-1.2.0.html#map-invalidatesize) docs should be clickable (like in [`setView` method docs](http://leafletjs.com/reference-1.2.0.html#map-setview)).
It can be fixed right [here](https://github.com/Leaflet/Leaflet/blob/cf518ff1a5e0e54a2f63faa144aeaa50888e0bc6/src/map/Map.js#L512).
Feel free to open a PR :)

**Comment by IvanSanchez** [comment]
This seems to be a trivial uppercase/lowercase problem in the docs. The proper identifier will cause the documentation to create links automatically. See the [correct docstrings](https://github.com/Leaflet/Leaflet/blob/v1.2.0/src/map/Map.js#L173) and compare to the [ones that need to be fixed](https://github.com/Leaflet/Leaflet/blob/cf518ff1a5e0e54a2f63faa144aeaa50888e0bc6/src/map/Map.js#L512). 

And don't forget to read [how to build Leaflet documentation](https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md#improving-documentation).

**Comment by LTiger14** [comment]
Hey guys, just opened a PR for this issue. The invalidateSize was the only occurrence of this problem I could find. Cheers!
