### ISSUE TITLE
output map couldn't show entirely in Jupyer Notebook R kernel

### ISSUE THREAD

**Issue by babybear1992** [Leaflet/Leaflet#5897]
- [ ] I'm reporting a bug, not asking for help
I use Leaflet in jupyter notebook with R kernel, however, the output map couldn't show entirely in the cell, only a small part of. I checked the **html_widget container**, which indicates that the width is as fixed as 200px, that's why I couldn't see the entire map.

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.

**Comment by miguelgcg** [comment]
@babybear1992 I am facing the same issue when trying to display a map with leaflet in jupyter notebook (using R kernel). Can you elaborate on how you changed the html_widget container settings?
