### ISSUE TITLE
can I attach custom property to leaflet layers?

### ISSUE THREAD

**Issue by giorgim** [Leaflet/Leaflet#5902]
Is it OK to attach custom properties to leaflet layers? e.g.
```

let layer =  L.geoJSON(geojsonFeature);
layer.myCustomProp = 123; // is this OK?
console.log(layer.myCustomProp);
```

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by perliedman** [comment]
Also, see #4001 and possibly #5629.

**Comment by giorgim** [comment]
@perliedman as I grasp from the threads, it seems short answer is that it is allowed?

**Comment by perliedman** [comment]
@giorgim short answer: yes. Not necessarily the best idea, though.
