### ISSUE TITLE
Blue marker image showing broken image link.

### ISSUE THREAD

**Issue by smitty1788** [Leaflet/Leaflet#5907]
I am using the Leaflet draw functions. When I draw a singular point, the blue mark is showing a broken image link. I am using leaflet draw 0.4.2. This problem occurs on all browsers that I've tested and I am on a windows 7 machine. Full code is below as well as a sample image of the broken link.

![capture](https://user-images.githubusercontent.com/20954933/32677662-4bca16c4-c62d-11e7-89d3-587f46a91ddd.PNG)

` <!DOCTYPE html>
<html>

<head>

    <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no' />

    
    <script src='https://api.tiles.mapbox.com/mapbox.js/v1.6.2/mapbox.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox.js/v1.6.2/mapbox.css' rel='stylesheet' />

    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/0.4.2/leaflet.draw.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/0.4.2/leaflet.draw.js"></script>

    <style>
        body {
            margin: 0;
            padding: 0;
        }
        #map {
            position: absolute;
            top: 0;
            bottom: 0;
            width: 100%;
        }
        #delete, #export {
            position: absolute;
            top:50px;
            right:10px;
            z-index:100;
            background:white;
            color:black;
            padding:6px;
            border-radius:4px;
            font-family: 'Helvetica Neue';
            cursor: pointer;
            font-size:12px;
            text-decoration:none;
        }
        #export {
            top:90px;
        }
        .leaflet-map-pane {
       z-index: 2 !important;
    }
    </style>
</head>

<body>

    <div id='map'></div>
    <div id='delete'>Delete Features</div>
    <a href='#' id='export'>Export Features</a>

    <script>
        var map = L.mapbox.map('map')
            .setView([38.904722, -77.016389], 13);
        
        var osmLink = '<a href="http://openstreetmap.org">OpenStreetMap</a>';
        
        var osmUrl = 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
            osmAttrib = '&copy; ' + osmLink + ' Contributors';

        var osmMap = L.tileLayer(osmUrl, {attribution: osmAttrib});

        // Add layers to the map
        L.control.layers({
            'Open Street Map': osmMap.addTo(map),
            'Satellite Map': L.mapbox.tileLayer('bobbysud.map-l4i2m7nd', {
                detectRetina: true
            })
        }).addTo(map);

        var featureGroup = L.featureGroup().addTo(map);

        var drawControl = new L.Control.Draw({
            edit: {
                featureGroup: featureGroup
            }
        }).addTo(map);

        map.on('draw:created', function(e) {

            // Each time a feaute is created, it's added to the over arching feature group
            featureGroup.addLayer(e.layer);
        });

        // on click, clear all layers
        document.getElementById('delete').onclick = function(e) {
            featureGroup.clearLayers();
        }

        document.getElementById('export').onclick = function(e) {
            // Extract GeoJson from featureGroup
            var data = featureGroup.toGeoJSON();

            // Stringify the GeoJson
            var convertedData = 'text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(data));

            // Create export
            document.getElementById('export').setAttribute('href', 'data:' + convertedData);
            document.getElementById('export').setAttribute('download','data.geojson');
        }
    </script>

</body>

</html>`

**Comment by cherniavskii** [comment]
Hi @smitty1788,
this is Leaflet issue tracker, the project you are looking for is [Leaflet.draw](https://github.com/Leaflet/Leaflet.draw). Please submit an issue there.

P.S. Do not ignore issue templates when reporting bugs - they are for a purpose.
