### ISSUE TITLE
Build from source

### ISSUE THREAD

**Issue by shadeland** [Leaflet/Leaflet#5908]
Running `jake build` won't generate any file in `/dist`. contrary to what has been described  [here](https://github.com/Leaflet/Leaflet/blob/master/docs/download.md).

also running `npm run rollup` only creates `/dist/leaflet-src.js` and  `dist/leaflet-src.js.map` 
and not `dist/leaflet.js`. contrary to what has been described [here](https://github.com/Leaflet/Leaflet/blob/master/docs/download.md)

I think it should be changed to `npm run build` in the documentation. I would be happy to fix it in  documentation if you think it's necessary

**Comment by cherniavskii** [comment]
Hi Adel,
Indeed, docs are a bit outdated, there should be `npm run build` instead of `jake build`.
Also, there is no need to install `jake` globally, so `npm install -g jake` line should be removed.
Feel free to open a PR ;)

**Comment by shadeland** [comment]
Hi Andrew, 
Thanks for your response, just opened a PR to fix the download page.
