### ISSUE TITLE
Switching leaflet overlay layers shows white blinks

### ISSUE THREAD

**Issue by fmarzocca** [Leaflet/Leaflet#5909]
Hi!
I am switching between image overlay layers upon user entry (through a slider) with the sample code herein attached.
Every time users get into this loop, a fast blink (with white background) is displaying, meaning that the old layer is removed before the new one finished rendering. I was relying on the "load" event, but it seems not affordable. It looks like the "load" event (fired by the added overlay image) is fired before the load completes.

## How to reproduce

- Leaflet version I'm using: 1.2.0
- Browser (with version) I'm using: Safari/Firefox/CHrome
- OS/Platform (with version) I'm using: Mac/Linux
- step 1  create a map and overlay an image
- step 2 step through several image overlays (by adding/removing them)

## What behaviour I'm expecting and which behaviour I'm seeing
No blinks

## Minimal example reproducing the issue

```
    mymap.addLayer(overlay[newlyr]);
    overlay[newlyr].once("load",function() { 
        mymap.removeLayer(overlay[oldlyr]); 
        });
```

- [X] this example is as simple as possible
- [X] this example does not rely on any third party code

**Comment by cherniavskii** [comment]
Hi Fabio,
could you provide a link to minimal example reproducing the issue?
You can use http://leafletjs.com/edit.html to create it.

**Comment by fmarzocca** [comment]
It is very complicated as it does not happen with local files. It happens
when I am accessing the image overlays from the net, and the load function
does not wait for image loading from remote.


Il giorno sab 11 nov 2017 alle 18:51 Andrew <notifications@github.com> ha
scritto:

**Comment by cherniavskii** [comment]
I understand, but we can't do anything until we can reproduce the issue.
You can use some image hosting sites for images.

**Comment by cherniavskii** [comment]
I'm closing this for now, feel free to reopen when bug reproduction example is ready
