### ISSUE TITLE
Leaflet in salesforce touch event

### ISSUE THREAD

**Issue by sundusSab** [Leaflet/Leaflet#5912]
Hi, 
touch events for markers does not work on touch screens ( if I click on marker nothing happened) and also for custom buttons I added to map, clicking on touch screen does not work.

dragging map, panning, zooming and clicking on zoom buttons all are works fine with touch

is there something should I do when adding markers and custom buttons ??

I tried examples in leaflet website and it works fine but on salesforce it sometimes  produce an error of illegal invocation

**Comment by sundusSab** [comment]
at least please give me line numbers of the code responsible for touch events handling for markers and its equivalent click event handlers

**Comment by perliedman** [comment]
Hi and thanks for using Leaflet!

Please note that this is our issue tracker, where bugs and feature requests and posted and discussed. For questions on how to use Leaflet, in particular how to use it together with other technologies like Salesforce, and other support, you're better off using [stackoverflow](https://stackoverflow.com/) or [gis.stackexchange.com](https://gis.stackexchange.com/).

If you really believe this is a bug, we need more information on exactly how it's triggered. If you can provide a running example that reproduces the problem, that significantly increases the chance of anyone being able to do something about it.
