### ISSUE TITLE
I would like to use a map based on OSM data, which i can go offline or save hefty mobile charges on my holiday

### ISSUE THREAD

**Issue by fssrepository** [Leaflet/Leaflet#5913]
Leaflet is helping MapBox business, but i would like to create a p2p map based on OSM to make it more accessible for everyone, at least the basics, which can be used when you are going for holiday also, where there is no internet. I have shared my research, and codes.

Even if you are not interested, you can see hundreds of cheat sheets on the mapping area.
It contains lots of improvements, algorithms etc., how it can be reached.

https://github.com/fsrepository/fms - https://github.com/fsrepository/fms-design

**Comment by perliedman** [comment]
Hi, I'm going to close this, since it's not an issue with Leaflet, unless I misunderstood. I'm not really sure why you posted this here, but if you're looking for contributors and/or to promote your project, I think you should consider other channels to do so.

**Comment by fssrepository** [comment]
No worries. Any idea, where i can promote to make some traction? There are guys who already liked the idea. It's related to the Leaflet also. The aim is to create distributed mapping solution without server (the idea already has codes and 27 pages), which is more accessible for individual developers and small businesses and independent from companies. Cloud has got lots of restrictions and non-free , switch-to-osm solutions cumbersome and sucks (OSM also pays only for lawyers and conferences sitting on 200K (look at the financial report), but every software is outdated, just waste of time). I wouldn't promote just tiny project ideas for individual purpose, that's why i have made a shot here also, and in different places. There is a common interest simply. Mapbox is too restrictive (it's a trojan horse of the OSM community), Google is binding the mapping solution to his ecosystem. So you can decide not to use map and you save money on other services also, or use the map but you pay 70% of your income to Google for VAT and for banks, and you take the whole risk also. (this load count by user view is very tricky - you have been forced to match your business idea to something irrelevant) You can make free android apps, but you hardly will buy anything from it.
