### ISSUE TITLE
Calling map.fitBounds() is not changing the bounds of the map in certain situations

### ISSUE THREAD

**Issue by bromeostasis** [Leaflet/Leaflet#5914]
## How to reproduce

- Leaflet version I'm using: 1.0.3
- Browser (with version) I'm using: Android WebView
- OS/Platform (with version) I'm using: Android 7.0, Cordova 7.0
- Trying to call fitBounds works most of the time, but recently, I've been running into a strange situation where calling fitBounds does not change the bounds of the map.
- Unfortunately, I've only been able to reproduce it in my app, but I'm happy to take suggestions on how I might be able to reproduce it in other places.
- I'm hoping the code provided should be enough to at least prove that this is a problem.

## What behaviour I'm expecting and which behaviour I'm seeing

**Expected:** Calling map.fitBounds on a LatLngBounds object would increase the bounds of the map to fit the bounds given.

**Actual:** In certain situations, the bounds remain unchanged.

## Minimal example reproducing the issue

I will work on this, but I wanted to get it documented for now to see if anyone has run into anything similar or has any thoughts. I understand that a live example is preferable, but 

Code example from a test location:

```
map.getBounds()
1. o.LatLngBounds {_southWest: o.LatLng, _northEast: o.LatLng}
    1. _northEast:o.LatLng {lat: 42.338244963350846, lng: -84.3684768676758}
    2. _southWest:o.LatLng {lat: 42.21097372118299, lng: -84.49207305908205}
    3. __proto__:Object
var newPosition = L.latLng(41, -80)
undefined
bounds.extend(newPosition)
_northEast: o.LatLng {lat: 42.3316448, lng: -80}
_southWest: o.LatLng {lat: 41, lng: -84.40134619999998}

map.fitBounds(bounds)
e {options: {…}, _container: div#mapcanvas.noClickTarget.tempTransitionOn.leaflet-container.leaflet-touch.leaflet-retina.leaflet-…, _leaflet_id: 2, _containerId: 3, _fadeAnimated: true, …}
map.getBounds()
1. o.LatLngBounds {_southWest: o.LatLng, _northEast: o.LatLng}
    1. _northEast:o.LatLng {lat: 42.338244963350846, lng: -84.3684768676758}
    2. _southWest:o.LatLng {lat: 42.21097372118299, lng: -84.49207305908205}
    3. __proto__:Object
```

Code example from a real location:

```
map.getBounds()
1. o.LatLngBounds {_southWest: o.LatLng, _northEast: o.LatLng}
    1. _northEast:o.LatLng {lat: 42.347126562355115, lng: -83.04402351379396}
    2. _southWest:o.LatLng {lat: 42.315337337451076, lng: -83.07492256164552}
    3. __proto__:Object
bounds
1. o.LatLngBounds {_southWest: o.LatLng, _northEast: o.LatLng}
    1. _northEast:o.LatLng {lat: 42.2806078, lng: -78.6938041}
    2. _southWest:o.LatLng {lat: 35.8887078, lng: -83.7467016}

map.fitBounds(bounds)
1. e {options: {…}, _container: div#mapcanvas.noClickTarget.leaflet-container.leaflet-touch.leaflet-retina.leaflet-fade-anim.leaflet…, _leaflet_id: 2, _containerId: 3, _fadeAnimated: true, …}
map.getBounds()
1. o.LatLngBounds {_southWest: o.LatLng, _northEast: o.LatLng}
    1. _northEast:o.LatLng {lat: 42.347126562355115, lng: -83.04402351379396}
    2. _southWest:o.LatLng {lat: 42.315337337451076, lng: -83.07492256164552}
    3. __proto__:Object
```

**Comment by perliedman** [comment]
Hi,
if you're only able to reproduce this in your app, but not in a simpler test case, I think you should stop and ask yourself why that is - might it actually be that something else happens in your app that prevents `fitBounds` from working?

As stated now, I don't see how we can move forward debugging this - you say `fitBounds` sometimes doesn't work, but can't show under which conditions. How should we, who can't even see this ever happening, be able to figure out why this happens?

Please realize that we have very limited time to spend on Leaflet issues, so spending that time just guessing what's going on without a clear case on how to reproduce, is very unlikely.

**Comment by marcagba** [comment]
Hi, it might be related to #3249, doesn't it ?

**Comment by bromeostasis** [comment]
@perliedman I definitely understand, and appreciate your response! I did eventually find the root cause of this in our app. I'm not sure if it's super relevant to this discussion, but we had an extra call to `map.setView` that was redirecting the map. Previously, the operation that called `fitBounds` took longer and so these two calls never coincided.

Recent changes brought these two calls closer together, and so as @marcagba mentioned, I believe this is similar to #3249 . I was just thrown off because I was literally stepping through line by line in the debugger and seeing the bounds of the map not responding to `fitBounds`.

Thanks again, I'll go ahead and close this!

**Comment by alexandis** [comment]
For me, this does not work at all, I always see a whole world map:

```
  onMapReady(map: AgmMap) {
    const bounds = new window['google'].maps.LatLngBounds();
    for (const marker of this.markers) {
      bounds.extend(new window['google'].maps.LatLng(marker.lat, marker.lng));
    }
    map.fitBounds = bounds;
  }
```

Bounds are correct.

Could it be because Google Cloud billing is NOT enabled? I just want to test API so far, but without features like `fitBounds` the component is useless...
