### ISSUE TITLE
Defining window.L conflicts with other libraries

### ISSUE THREAD

**Issue by disaacson** [Leaflet/Leaflet#5915]
I hope this helps but I understand it is probably obvious and I won't feel bad if you just close it as won't do. Defining window.L easily conflicts with other libraries once they are minified, such as [Google One Tap sign-in/sign-up](https://developers.google.com/identity/one-tap/web/overview)

Using a different name, like Leaflet, would greatly reduce this issue.

## How to reproduce

- Leaflet version I'm using: v1.2.0
- Browser (with version) I'm using: Chrome 62
- OS/Platform (with version) I'm using: Linux
- Create a Leaflet map
- Use Google One-tap 

## What behaviour I'm expecting and which behaviour I'm seeing
Several map features do not work because window.L has been overwritten by Google One Tap.

## Suggestion
Avoid global variable conflicts by using a more unique name for the global Leaflet object.

Here is where I reported it to the official [Google One-tap tag on Stackoverflow](https://stackoverflow.com/questions/47292011/google-one-tap-declares-global-variable-l)

They obviously should change their library too, but this could still benefit Leaflet.

This is a giant change and for the Leaflet ecosystem I understand and could only be done in a major new release. Reporting just in case it helps.

**Comment by cherniavskii** [comment]
Hi Derrick,
take a look at [L.noConflict](http://leafletjs.com/reference.html#noconflict) - it will solve your problem ;)

**Comment by disaacson** [comment]
Thanks. I had not seen that.

We had to do another workaround for two reasons.
1. We are using other leaflet libraries [Leaflet MarkerCluster](https://github.com/Leaflet/Leaflet.markercluster) that are relying on L to be leaflet.
2. We are downloading Leaflet using npm.

We did something similar though and got it to work.
