### ISSUE TITLE
Add console output to Extending Leaflet example page

### ISSUE THREAD

**Issue by cherniavskii** [Leaflet/Leaflet#5920]
Console output is missing in one code block in [Extending Leaflet example page](http://leafletjs.com/examples/extending/extending-1-classes.html). Would be cool to add it ;)

![screenshot_10](https://user-images.githubusercontent.com/13808724/32908389-b1510aae-cb03-11e7-8934-7714e4ca381b.png)

Source file is here: `docs/examples/extending/extending-1-classes.md`

**Comment by andyyaldoo** [comment]
I'll help :)
