### ISSUE TITLE
Remove touch based click tolerance for canvas renderer

### ISSUE THREAD

**Issue by perliedman** [Leaflet/Leaflet#5921]
The use of `L.Browser.touch` to increase click tolerance when using the canvas renderer (https://github.com/Leaflet/Leaflet/blob/master/src/layer/vector/Path.js#L143) is confusing and produce incorrect events for features close to each other (#5339, #5144, probably more).

As [suggested by @IvanSanchez](https://github.com/Leaflet/Leaflet/pull/5339#issuecomment-280316123), it would probably be better to have the extra tolerance as an option settable in `Canvas`, and defaulting it to 0 (which is how it works with the SVG renderer anyway).

**Comment by iPrytz** [comment]
Also related to [5921](https://github.com/Leaflet/Leaflet/issues/5921)
