### ISSUE TITLE
Images as Data URLs

### ISSUE THREAD

**Issue by cherniavskii** [Leaflet/Leaflet#5926]
Since we don't support IE8-, I would like to bring up images Data URL topic again (#979).
We can use [rollup-plugin-url](https://github.com/rollup/rollup-plugin-url) to import images and convert them to data URLs.

Pros:
- get rid of all magic related to images path detecting
- it will work properly in any build environment (webpack/browserify/rollup etc.)
- no need to include images folder into dist
- supported in IE8+ [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs)

Cons:
- increased js file size (from 38Kb to ~47Kb)
- all images will be included regardless of images are used or not

We could also use data URLs only for marker icons & shadow and leave layers images as is (in CSS).

**Comment by ghybs** [comment]
Hi,

In the cons I would add the higher performance penalty issue when there are lot of markers with inlined image v.s. standard image, as [profiled](https://github.com/Leaflet/Leaflet/issues/4968#issuecomment-322422045) by @perliedman.

**Comment by ghybs** [comment]
> We could […] leave layers images as is (in CSS).

Sounds very reasonable to me in any case, since the Layers Control images use a very standard CSS `url()` that does not depend on the Leaflet path detection magic. Therefore it is in the standard usage that build tools expect (typically webpack).

**Comment by cherniavskii** [comment]
Hi,
thanks for commenting.
Performance and size are crucial here, so I think it isn't worth it.
Also, I noticed that we still support IE 7 ;)
