### ISSUE TITLE
Some points have non-zero distance to themselves

### ISSUE THREAD

**Issue by jussimattas** [Leaflet/Leaflet#5932]
If `x` is e.g. `[60.1882535, 24.8300111]`, then `L.latLng(x).distanceTo(x)` -- which is expected to give zero -- gives 0.09493529796600342, i.e. ~10cm. If you change the latitude a bit, say, to 60.1882537, then the formula gives zero. Several other random points have this property, too (this exact same non-zero value for `L.latLng(x).distanceTo(x)`). For some values of `x` the distance is 0.13425878593145293. These are the only two non-zero values I've seen in this context.

Leaflet version: 1.2.0 stable.

JSFiddle to check distance of random points to themselves: https://jsfiddle.net/egrqg3qa/4/

Reproduced on Windows 10 with
- Chrome Version 62.0.3202.94 (Official Build) (64-bit)
- Firefox 57.0 (64-bit)
- Microsoft Edge 40.15063.674.0

**Comment by jussimattas** [comment]
Just noticed that the numbers are related: `0.13425878593145293 === Math.sqrt(2) * 0.09493529796600342`.

**Comment by IvanSanchez** [comment]
This is also reproducible by doing:

```
let x = [60.1882535, 24.8300111];
console.log( L.CRS.Earth.distance(L.latLng(x), L.latLng(x)) );
```

(Note that `L.LatLng.prototype.distanceTo()` calls `L.CRS.Earth.distance()` under the hood)

This might as well be an artifact of the distance approximation used by the `L.CRS.Earth.distance` method, don't know if it's worth changing that.

**Comment by perliedman** [comment]
The important code is this:

```
Math.sin(lat1) * Math.sin(lat2) +
Math.cos(lat1) * Math.cos(lat2) * Math.cos(lng2- lng1)
```

will evaluate to 1 when lat1=lat2 and lng1=lng2 for infinite precision, causing a calculated angle of 0, in turn causing the distance to be 0. With floating point math, the result of this calculation is only approximately 0 (for the coords supplied above, it evaluates to `0.9999999999999999` for me), so the angle will only be close to 0.

I'd say this is ok - I don't think you should use Leaflet (or WGS84) if you need precision under a meter, it's not what we design for.

(Above I assume `lat1`, `lat2`, `lng1` and `lng2` are in radians already.)

**Comment by jussimattas** [comment]
Yes, it seems that this behavior is due to the arccosine function being unstable at argument value 1 (its graph is vertical there). There is an alternative version of the Haversine formula used to calculate the distance which uses arctangent instead (JS implementation copied from https://www.movable-type.co.uk/scripts/latlong.html):

```
var R = 6371e3; // metres
var φ1 = lat1.toRadians();
var φ2 = lat2.toRadians();
var Δφ = (lat2-lat1).toRadians();
var Δλ = (lon2-lon1).toRadians();

var a = Math.sin(Δφ/2) * Math.sin(Δφ/2) +
  Math.cos(φ1) * Math.cos(φ2) * Math.sin(Δλ/2) * Math.sin(Δλ/2);
var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));

var d = R * c;
```

This alternative formula does not give non-zero distances of a point to itself. Don't know if there's some other trade-off, though.
