### ISSUE TITLE
add EventListener to child element of Popup

### ISSUE THREAD

**Issue by Kiiiwiii** [Leaflet/Leaflet#5934]
Browser: Chrome Version 62.0.3202.94 (Official Build) (64-bit),
                Safari Version 11.0 (11604.1.38.1.7)
OS:          Mac OS X EI Captain version 10.11.6
Leaflet version:   "leaflet": "^1.2.0"

Reproduce:
1.  `let popup = L.popup() .setContent('<p>Hello world!<br />This is a nice popup.</p>');`
2.  bind it to a marker `marker.bindPopup(popup);`
3. add a eventListener to **p element** inside of popup when popup is open.(It exists at that time)
```
popup.on('add', (e) => { 
      .....queryselector('p'),
      p.addEventListener('click', () => {...});
} 
```
4. add two markers and bind thier popup. (two markers and their correspondent popup on the map)
**Result:**
5. click markerA, popup comes out, click the p element on the popup. (works fine).
6. click marker B immediately, popup of B comes out, click the p (Not work! No event listener!)
7. click the map, or close popup, then click marker B and click the p element on its popup. (works fine again)

It seems that if you click directly from one marker to another, event listener on the p element doesn't work. However, if you click one marker, then close it explicitly, then click another marker. It works fine again.

Another way to solve the problem: 
https://stackoverflow.com/questions/13698975/click-link-inside-leaflet-popup-and-do-javascript

the answer of Asad solves the problem. and the answer of semiomant describes exactly this issue.
I'm wondering whether it is a bug or not.

**Comment by IvanSanchez** [comment]
No, this is not a Leaflet bug, but rather looks like a race condition in how you're attaching the event handlers. Count how many times your `addEventListener()` runs, and which element it's being applied to.

**Comment by Kiiiwiii** [comment]
I attach the eventlistener to p element inside of popup only when it exists (on condition **popupopen**). If you close the popup, all the content should be removed from DOM and addEventlistener should also be cleaned. 

It's really strange, because if you click the map first, then click marker A, it works.
(the popup-content created by leaflet is removed and then added to DOM) 
//
But if you click marker A and then click marker B, the popup in marker B doesn't register the event.
(the div element of popup-content created by leaflet is only transformed to the marker B in this case)
// so all the time, there is only one popup-content inside of DOM??
@IvanSanchez

**Comment by gauravAtProptiger** [comment]
@Kiiiwiii  @IvanSanchez I am facing the same problem. How did you solve the problem?
