### ISSUE TITLE
Map click event

### ISSUE THREAD

**Issue by Vecxinnt** [Leaflet/Leaflet#5939]
So, I have a couple of path/vector on my map and a 'click' event on that map:
`map.on('click', function(e){
		console.log(e.target);
	});`

The problem is that the event triggers also when I click on a vector.
Is there a way to detect if I'm clicking on something that is not the map?

**Comment by perliedman** [comment]
Hi and thanks for using Leaflet!

Please note that this is our issue tracker, where bugs and feature requests and posted and discussed. For questions on how to use Leaflet and other support, you're better off using [stackoverflow](https://stackoverflow.com/) or [gis.stackexchange.com](https://gis.stackexchange.com/).
