### ISSUE TITLE
Markers/Polygons/features disappear after autopanning around the globe

### ISSUE THREAD

**Issue by jguthrie100** [Leaflet/Leaflet#5946]
When dragging a marker with autoPan enabled, the map pans around, but when it gets to the same spot again after a 360° rotation of the 'globe', you would expect the same features and polygons etc to come back into focus, but its just a blank globe.

Would it not be better to have a _true_ pan, whereby when the features drop off the Eastern side of the map whilst panning West, they come back onto the map on the Western side once the 360° spin is nearly complete?

I tried to set up an example on jsfiddle ( http://jsfiddle.net/L1Lbeo9f/3/ ), but for some reason the autoPan doesn't work at all (another bug?)

Instead, if you load up the `marker-autopan.html` page in the debug examples of the Leaflet sourcecode, and then drag the draggable marker around the globe, you'll notice that the polygon and 2nd marker are no longer over Africa after one globe rotation.

**Comment by IvanSanchez** [comment]
Use the `worldCopyJump` option, see http://leafletjs.com/reference-1.2.0.html#map-worldcopyjump
