### ISSUE TITLE
"TypeError: el.className is undefined" when dragging too fast 

### ISSUE THREAD

**Issue by michaelhornak** [Leaflet/Leaflet#5950]
Hi, after releasing new Firefox version, we started to experience this old issue [https://github.com/Leaflet/Leaflet/issues/3349](https://github.com/Leaflet/Leaflet/issues/3349) again. I have example page where this error occurs. We're using Leaflet 1.2.0. It takes some time while the error appears, but with 5 minutes of quick moving, paning, zooming I have managed to throw the error 5-6 times.

[http://tangram_error.ai-maps.com/](http://tangram_error.ai-maps.com/)

**Comment by cherniavskii** [comment]
@michaelhornak Hi,
could you set up minimal example reproducing this issue?

**Comment by michaelhornak** [comment]
@cherniavskii  in the link at the end of my first post is reproducable example of the issue

**Comment by cherniavskii** [comment]
@michaelhornak we don't have time to debug applications / third party software. If you are sure it's a Leaflet bug - please provide a *minimal* example reproducing the issue.

**Comment by cherniavskii** [comment]
Feel free to reopen when you'll be able to provide an example or more info
