### ISSUE TITLE
Markers should always have an alt attribute, even if it is empty

### ISSUE THREAD

**Issue by andymantell** [Leaflet/Leaflet#5953]
## How to reproduce

- Leaflet 1.2.0
- Chrome 62 / Ubuntu
- Inspect the marker with dev tools and look at the `alt` attribute on the marker image (or absence thereof)

## What behaviour I'm expecting and which behaviour I'm seeing

When adding a marker to the map, if you don't specify any alt text, it does not render the `alt` attribute on the image. This can cause assistive tech such as screenreaders to read out the full path to the marker image `src` which is not a great experience. Automated accessibility checkers will flag this as a failure.

Images which are "decorational" should have an empty alt text such as `<img alt="">`. It is important that the `alt` attribute is _present_, and _empty_ in order to classify as a decorational image. The corresponding WCAG guideline can be found here:

https://www.w3.org/WAI/tutorials/images/decorative/

## Minimal example reproducing the issue
https://codepen.io/andymantell/pen/QOPXvR

**Comment by andymantell** [comment]
I have tracked the problem down to this piece of code in Marker.js

```js
if (options.alt) {
    icon.alt = options.alt;
}
```

Because empty string casts to boolean false, the alt text never gets set. A temporary workaround when creating the marker is to pass in the following object as alt text:

```js
var altText = {}
altText.toString = function () {
      return ''
}

altText.valueOf = function () {
    return true
}

L.marker( ... , { alt: altText })
```

This tricks leaflet into displaying the alt text, because the valueOf method returns true. But then when the alt text is rendered, the toString method returns an empty string.

Ideally the if(options.alt) line in Marker.js would be removed so that this little hack isn't necessary, but for anyone struggling with this in the meantime, this should help.

**Comment by IvanSanchez** [comment]
Looks like a simple change around https://github.com/Leaflet/Leaflet/blob/f0c31c169125d5c47c7d27439dfb78e23263f39d/src/layer/marker/Marker.js#L206

Any takers?

Also I'm not sure what the behaviour should be for `DivIcon`s in this case. I think the current code adds an `alt` attribute to them too, which might not be the right thing to do.

**Comment by IvanSanchez** [comment]
@andymantell Your approach would be simpler with something like 

```
icon.alt = options.alt || "";
```

(If `options.alt` evaluates to a falsy value, then the `options.alt || ''` expression will evaluate into a empty string)

Due to Leaflet having `Icon`s and `DivIcon`s, I'd be partial to a private `_setAlt()` method in `Icon` and `DivIcon`. For `DivIcon`s it maybe should just ignore the input.

**Comment by andymantell** [comment]
@IvanSanchez the little "hack" I posted is code that you can use with the _current_ setup to work around the issue. I'm not proposing that it be put into Leaflet like that! :-)

**Comment by IvanSanchez** [comment]
@andymantell Never mind then O:-)
