### ISSUE TITLE
How to get elevation from current latitude and longitude using leafltejs OR mapbox javascript API

### ISSUE THREAD

**Issue by magu81** [Leaflet/Leaflet#5954]
I am working with leafletjs.com and added MAP. I want to get elevation from current latitude and longitude or current place only, but it will return whole path elevation.

var el = L.control.elevation();
el.addTo(map);
var gjl = L.geoJson(geojson,{
     onEachFeature: el.addData.bind(el)
}).addTo(map);
map.addLayer(service).fitBounds(bounds);

How can I find the elevation with either mapbox or leafletjs.

-  	 
	
elevation of current place only, above code return elevation of whole json data

-
 
	
I want like this
https://developers.google.com/maps/documentation/javascript/examples/elevation-simple

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
