### ISSUE TITLE
wrong hover effect on controls when using touch events

### ISSUE THREAD

**Issue by ArminMueller** [Leaflet/Leaflet#5955]
When using maps on a mobile and click the zoom control the button is changing the background to light gray. This color change stay after finishing the task (see screenshot).
![unbenannt](https://user-images.githubusercontent.com/20238047/33674804-e1d764e0-dab0-11e7-98e0-1188c8989d83.PNG).
You can try it with the map on  http://leafletjs.com/

**Comment by cherniavskii** [comment]
@ArminMueller Hi,
what behavior do you expect?

P.S. Please do not discard our issue template

**Comment by ArminMueller** [comment]
The same behavior i have on desktop. After finishing zoom the button should not be colored. This means for me that the button is activated and i can zoomin or out until i click the button a second time

**Comment by cherniavskii** [comment]
If I understand correctly, it's just about UI and zooming in/out works as expected on touch devices?
In this case it doesn't look like an issue to me - `hover` on touch devices is applied until element is in focused state.
