### ISSUE TITLE
Find position of point (pixelic) on the map

### ISSUE THREAD

**Issue by ronikar** [Leaflet/Leaflet#5961]
Hi,
How can I find the position of point on the map? (left, top in pixelic)
For example:
map element width : 400 px.
map element height : 400 px.
map bound: [[0, 0], [20,20]]

I want to know where is [15,5] on the screen (offestTop and offestLeft from the location of the map will help me too), base on the fact that earth is geoid, and leaflet uses this fact when it projects element on the map.

Thanks

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
