### ISSUE TITLE
Tiles disappear on zoom after upgrading to 1.2

### ISSUE THREAD

**Issue by eavidan-0** [Leaflet/Leaflet#5962]
## How to reproduce

- Leaflet version I'm using: 1.2.0
- Browser (with version) I'm using: Chrome 44
- OS/Platform (with version) I'm using: Windows 7

Steps:
- Create map with tileLayer
- Zoom in hard using mouse wheel

## What behaviour I'm expecting and which behaviour I'm seeing
In leaflet 0.7.7, existing tiles were kept and a smooth user experience was produced.
Since upgrading, there are a few moments of seeing a blank screen

## Minimal example reproducing the issue
(Typing this from my phone...)

```javascript
L.map('map', {
     center: [[0, 0], [1,1]], 
     zoom: 6,
     crs: L.CRS.EPSG4326,
     layers: [L.tileLayer(url)]
}
```

And compare in both versions of leaflet

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

Using http://leafletjs.com/edit.html or any other jsfiddle-like site.

**Comment by IvanSanchez** [comment]
This is behaviour as expected. Please check the documentation about [the `zoomAnimationThreshold` option for a `L.Map`](http://leafletjs.com/reference-1.2.0.html#map-zoomanimationthreshold)

**Comment by eavidan-0** [comment]
I've tried using it, however even after disabling 'fadeAnimation' there is a split second of nothingness

**Comment by ghybs** [comment]
Sounds like a duplicate of https://github.com/Leaflet/Leaflet/issues/5622
