### ISSUE TITLE
How can i implement Leaflet js in native android app

### ISSUE THREAD

**Issue by kocokolo** [Leaflet/Leaflet#5964]
I am a newbie in android. I am making an android application which requires all features that Leaflet js provides on the web. Is there is such library or SDK available for android by which I can get all the features of Leaflet js I am trying to make an android application which used to draw lines, draw shapes on layers without affecting original image.Also I don't want to implement web view. I viewed many solutions like Use leaflet in an android application to show online map but neither helps. Thanks

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
