### ISSUE TITLE
version 1.2.0 does not work with IE8

### ISSUE THREAD

**Issue by zhurc** [Leaflet/Leaflet#5978]
- Leaflet version I'm using:  1.2.0
- Browser (with version) I'm using: Chrome, Firefox, Opera ,IE-9+ worked nicely, but when tested with IE-8,  it does't work
- OS/Platform (with version) I'm using: windows 8 

To see how, open below url  ，use the code inside to create a  local html file and open it with IE-8

## example 

https://plnkr.co/edit/A32GoTcJydB64c1AvP7x?p=preview

### with IE-9
![ie9](https://user-images.githubusercontent.com/30788815/34433791-9ba30f4c-ecbc-11e7-8332-5a546ff9f793.png)

### with IE-8
![ie8](https://user-images.githubusercontent.com/30788815/34433808-b31012e2-ecbc-11e7-85c3-71b726881803.png)

**Comment by cherniavskii** [comment]
@zhurc could you try current master branch?
Here's same example as yours, but with current master build:
https://plnkr.co/edit/OD3txwQ48R59yodPQpVT?p=preview

**Comment by zhurc** [comment]
It worked!  @cherniavskii  thank you  for your reply  .  I'm looking forward to the next release.

**Comment by IvanSanchez** [comment]
Already fixed by https://github.com/Leaflet/Leaflet/pull/5731 , closing.
