### ISSUE TITLE
markers shared by multiple layers member of L.Control.Layers are disabled even if the remaining layers include them

### ISSUE THREAD

**Issue by rgeissert** [Leaflet/Leaflet#598]
In leaflet 0.3.1, when the same marker is added to more than one layer, all of which are added to L.Control.Layers as overlays, and one of the overlays is disabled, the marker is disabled.

e.g.

``` javascript
var groupA = new L.LayerGroup(),
    groupB = new L.LayerGroup();

map.addLayer(groupA).addLayer(groupB);

var overlays = {
 "A features": groupA,
 "B features": groupB,
};

map.addControl(new L.Control.Layers(null, overlays));

var marker = new L.Marker(new L.LatLng(1.0, 1.0));
groupA.addLayer(marker);
groupB.addLayer(marker);
```

Now, whenever the "A features" overlay is disabled, the marker is removed, even if the "B features" overlay is still enabled. Disabling and re-enabling "B features" does re-add the marker.

**Comment by RinkAttendant6** [comment]
@MaxiPigna I think the workaround is in the cross-referenced commit here: https://github.com/rgeissert/Leaflet/commit/e273f1bb0aeef485d07c2814429a28ea9ea07474
