### ISSUE TITLE
Draggable popups position is resetted on zoom

### ISSUE THREAD

**Issue by erikfroseth** [Leaflet/Leaflet#5982]
Hello!

This might not be a bug, since I suspect that this isn't really supported... However:

I'm trying to make a popup draggable by using L.Draggable. It works perfect until I zoom the map. When I zoom, the position of the popup is set back to where it originally was opened. Should this work?

I've made an example here: https://plnkr.co/edit/sRpx2kBNmYj2YP9sQktq?p=preview

How to reproduce using the example:
1) Click anywhere on the map to open a popup
2) Move the popup by dragging it
3) Pan the map to see that it's working
4) Then zoom the map, and watch the position of the popup is changed.

**Comment by synonymousz** [comment]
Hello @erikfroseth 
I added a very few lines of code for you beginning on line 26:
https://plnkr.co/edit/S1GPRm6sNwGDkD6oSCHs?p=preview

Now everytime you dragged the popup, it will save the position to it, so that you can zoom.

Greetings
