### ISSUE TITLE
CoordinatedImagePreview plugin is not updating images when zooming / moving a map

### ISSUE THREAD

**Issue by mngorny** [Leaflet/Leaflet#5985]
Hi Everybody

Could you please check if there is a bug in this plugin (Leaflet.CoordinatedImagePreview)?
https://github.com/utahemre/Leaflet.CoordinatedImagePreview

It's showing the coordinated images from geojson properly but when moving or zooming a map the list of images is not updating. It looks like it is showing all the images from geojson, not only these which are in current map bounds.
According to the specification is should refresh image list

I have this problem in my project but appearently the same problem is in the demo:
https://utahemre.github.io/coordinatedimagepreviewdemo.html

So I guess there is a problem in the code??

The problem appears in firefox, chrome and opera. I tested it also from local folder with JQuery 1.11.3 and both Leaflet 0.7.3 and Leaflet 1.0 as in the plugin specification.

Thanks in advance!

**Comment by cherniavskii** [comment]
@mngorny Hi,
Please note that this issue tracker is used for **Leaflet** bugs.
We can not debug your application or third-party software for you.
Please submit an issue in Leaflet.CoordinatedImagePreview repo.
