### ISSUE TITLE
Leaflet with Google Maps Places + Place Details

### ISSUE THREAD

**Issue by TheMangoTrain** [Leaflet/Leaflet#5986]
Is there an existing plugin for this, or is it not recommended?

Example: In a typical instance of Google Maps, when you see something of interest on the map, be it a marker or label (e.g. a park, a cafe, etc), which may or may not be part of your search results, when you click it you get a details pane show up as a sidebar. In fact, if you click ANYWHERE on the map you get a details sidebar. The place you clicked on the map could be in the middle of the wilderness, and Google will still at least show raw lat/long.

As far as I can tell, any typical instance of Leaflet doesn't have this capability without a plugin. The data has to come from somewhere obviously.

Google has a javascript API for its Place data:
https://developers.google.com/places/javascript

There's a Leaflet plugin to integrate the Places autocomplete search box onto a Leaflet map. This is nice, but it doesn't address the above concern (browsing the map as opposed to searching for something specific). https://github.com/Twista/leaflet-google-places-autocomplete

How can I render Google's clickable place labels and icons within a Leaflet map?

Currently I'm using Leaflet with Mapbox tiles. I'd rather keep going with my setup as I integrate with a database. Worst case scenario I'll do a second map page which is 100% Google stuff.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

The closest you're gonna get to Google data is (to the best of my knowledge) https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant . I don't think there is currently anything that works against the Google Place API, but you'll be welcome to create such a Leaflet plugin.

**Comment by perliedman** [comment]
Also, I would guess Google's license would not allow you to show their place data on other maps than their own, but I'm not sure.

You could look at the [Leaflet underneath](https://github.com/perliedman/leaflet-underneath) plugin, but it doesn't use Google Places.

**Comment by IvanSanchez** [comment]
Yeah, that's right. Section 10.4.e of https://developers.google.com/maps/terms states:

> _No use of Content with a non-Google map._ You must not use the Content in a Maps API Implementation that contains a non-Google map.
