### ISSUE TITLE
Distinguish click from dblclick

### ISSUE THREAD

**Issue by michael** [Leaflet/Leaflet#599]
I'm working on a map annotation editor based on Leaflet. I'm wondering if I could distinguish between double click events (as used for zooming into the map) and click events (just one click).

In my scenario a click should drop a new map annotation, as opposed to a double click, which should just do the zooming. However, a double click triggers two click events. Maybe this should change?

Let me know what you guys think.

Thanks,

Michael (MapBox)

**Comment by mikila85** [comment]
+1

**Comment by Sergio1C** [comment]
+1
