### ISSUE TITLE
Touch event handlers not being cleared down when the map is removed

### ISSUE THREAD

**Issue by Searlon** [Leaflet/Leaflet#5990]
## How to reproduce

- Leaflet version I'm using: 1.2.0
- Browser (with version) I'm using: Google Chrome v 64.0.3282.71
- OS/Platform (with version) I'm using: Windows
- Step 1:
Create and remove a map, then double click on the element, an error will be received. This is best monitored within the browsers developers tools.

I've done my best to see if this issue has already been reported, and didn't find anything.

It may not seem like much of a problem, but we allow users to swap API's on the map between Leaflet and Google. Doing so clears down the map and re-uses the same DOM element for the map. This becomes a problem as after swapping to the Google API and attempting to use the map, I get leaflet based errors. (As a side note, I'm currently looking at upgrading from version 0.7.5 to 1.2.0)

After digging around I found a few touch based event handlers are left behind. There are even a couple more left behind if you use the leaflet-draw plug in (which I do, and you only need a single click, not double to get an error), but it appears to be a core leaflet issue. Possibly purely down to the naming convention of the touch event handlers.

This may or may not help, but I've been looking around at functions "_addPointerStart" and "removePointerListener", could be a quick starter for 10.

## Minimal example reproducing the issue
I've created the most basic solution here: https://jsfiddle.net/a0swn1f8/
- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by cherniavskii** [comment]
@Searlon 
looks like it's already fixed on current master: https://jsfiddle.net/a0swn1f8/1/
I updated your example to use latest master and cannot reproduce the issue

**Comment by Searlon** [comment]
Ah great, I'll take a look at the master branch and try and pull out the fix. 
Thanks for the reply.

**Comment by cherniavskii** [comment]
@Searlon 1.3.0 will be released soon, so you'll be able to get it from NPM too ;)
