### ISSUE TITLE
Touch support for last chrome version on mobile

### ISSUE THREAD

**Issue by DispatchCode** [Leaflet/Leaflet#5992]
Hello,

I suspect that this is a bug with last mobile Chrome version. You can follow this link to an issue of FreeDraw: https://github.com/Wildhoney/Leaflet.FreeDraw/issues/109
I think that the problem is in Leaflet and not in FreeDraw, but I'm not sure (I'm here for that). 

Basicly: with Chrome < 62 it work, but with new versions the event it dosen't occur.

Thanks in advance!

Best regards,
Marco

**Comment by cherniavskii** [comment]
@DispatchCode 
Hi,
from linked issue i see that drawing is not working on mobile Chrome, but it's functionality provided by Leaflet.FreeDraw, not Leaflet.
We have limited time to work on Leaflet and can't spend it on debugging code, which involves third-party libraries.

If there's a Leaflet bug - please submit new bug report with details and minimal example

**Comment by cherniavskii** [comment]
@DispatchCode 
P.S. check out [Leaflet.Draw](https://leaflet.github.io/Leaflet.draw/docs/leaflet-draw-latest.html), which works well on mobile Chrome, maybe you'll find solution there
