### ISSUE TITLE
contextmenu event on a (circlemarker on a canvas) doesn't prevent browser default menu to appear

### ISSUE THREAD

**Issue by fchabouis** [Leaflet/Leaflet#5995]
## How to reproduce

- Leaflet version I'm using: 1.2.0
- Browser (with version) I'm using: firefox 57.0.1
- OS/Platform (with version) I'm using: Ubuntu 16.04
- create a leaflet map, rendering on a canvas
- add a circle marker
- right click on it

## What behaviour I'm expecting and which behaviour I'm seeing
I'm expecting to see nothing
What I see is the browser context menu
If I don't render the marker on a canvas, I see nothing as expected.

The doc says that the browser menu should not appear
![image](https://user-images.githubusercontent.com/15341118/34837205-55d94d30-f6fa-11e7-8e2b-af9fd31eff4f.png)

## Minimal example reproducing the issue

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

https://plnkr.co/edit/LKmHDcuYCEVhrI7xGkHR?p=preview

**Comment by apdevelop** [comment]
I can confirm it on latest Leaflet 1.3.1 [JSFiddle demo](https://jsfiddle.net/apdevelop/05zfzrhx/) (using Firefox 56 and Chrome 65 on Windows 7).
The only workaround I can suggest is subscribing to `contextmenu` event of marker:
```js
L.circleMarker([0, 0], { ... })
  .on('contextmenu', function(e) {
    console.log('there was a right click on marker')
    //L.DomEvent.stopPropagation(e); // if needed
  })
  .addTo(map);
```

**Comment by johnd0e** [comment]
Here is the underlying code: https://github.com/Leaflet/Leaflet/blob/e8c28b996179373447dde1df479898576a508579/src/map/Map.js#L1423-L1425

It checks all the listeners including 'propagated' to parents (which may include any `FeatureGroup` **but** not `map` itself).
It would be easy to check map too, but I not sure that this is really necessary.
