### ISSUE TITLE
New markers not appearing if an old marker removed.

### ISSUE THREAD

**Issue by p59crw** [Leaflet/Leaflet#6000]
## Using

- Leaflet version I'm using: 1.2.0
- Browser (with version) I'm using: Chrome
- OS/Platform (with version) I'm using: Linux 18

## What behaviour I'm expecting and which behaviour I'm seeing:
I created a method that adds markers to the map. I then, on button click, delete certain markers. All this works fine so far. I can add markers and remove them without issue.

Here's where the issue comes in. Once I delete a marker, whenever a new marker is added, it doesn't appear on the map. I expected the markers to be able to be added and removed in any order and appear properly.

Also, not sure if this issue is related, but when I leave the page containing the map and return to it, the map is greyed out and no tilelayers appear, even though I specified which tilelayers to add to it.

I receive no errors in my console.

Upon calling initMap() the first time, when there are no markers added, the map loads correctly and I have no issues, but once markers have been added or removed, the map greys out upon returning to it from another page on my site. This did not happen before until I added the ability to remove markers. 

Here's my code:

    var markers = [];
    var layerGroup = [];

    initMap() {
        const baseMaps = {
          'Basic': basic,
          'Light': light,
          'Satellite': satellite,
          'Detail': streets
        };

      map = L.map('map', { layers: [basic, light, satellite, streets] });
      map.fitBounds(this.mapBoundsService.getBounds());

      map.addControl(searchControl);

      L.control.layers(baseMaps).addTo(map);

      map.maxZoom = 100;
      }

    addMarkers(startLong, startLat, destLong, destLat) {
        const marker1 = L.marker([startLong, startLat], {
            icon: L.icon({
            iconUrl: iconURL
            })
      }).bindPopup(popupContentStart);

      const marker2 = L.marker([destLong, destLat], {
        icon: L.icon({
          iconUrl: iconURL
        })
      }).bindPopup(popupContentDest);

      // this.markers.push([marker1, marker2]);
      this.layerGroup.push(L.layerGroup([marker1, marker2]));
      console.log(this.layerGroup);
      this.layerGroup[this.tasks.length - 1].addTo(map);
      // this.markers[this.tasks.length - 1][0].addTo(map);
      // this.markers[this.tasks.length - 1][1].addTo(map); // Commented parts is code I tried, but got same result from.
    }

    removeMarkers(index: number) {
        // this.layerGroup[index].clearLayers();
        this.layerGroup[index].remove();
        // this.markers[index][0].remove();
        // this.markers[index][1].remove();
        // Commented lines are ones I tried but same issue occurred.
      }

I wonder if this has something to do with either 1) how layers/markers are handled in Leaflet, or 2) my map's container state.

Any ideas would be appreciated.

**Comment by cherniavskii** [comment]
@p59crw could you create minimal example reproducing your issue?

**Comment by p59crw** [comment]
@cherniavskii I'm having a lot of trouble setting up an example in Plunkr at the moment. I'll keep trying, but in the meantime, any ideas or suggestions are appreciated.

**Comment by cherniavskii** [comment]
@p59crw try to make this example as simple as possible

**Comment by p59crw** [comment]
@cherniavskii I solved the issue. It was an error in my arrays which was throwing the index off but wasn't throwing an exception.

The markers work as expected. You can close this.
