### ISSUE TITLE
Mouse events coordinates are wrong on CSS3 scaled map

### ISSUE THREAD

**Issue by yarsky-tgz** [Leaflet/Leaflet#6002]
## How to reproduce

- Leaflet version I'm using: current master
- Browser (with version) I'm using: Chrome 63.0.3239.84
- OS/Platform (with version) I'm using: Win 10

## What behaviour I'm expecting and which behaviour I'm seeing

Expected that coordinates of mouse click or wheel scrolling shall be the same as actual pointer position. 

But if map is scaled by CSS3 transform they are different.

## Minimal example reproducing the issue

Try to click the map

https://leaflet-scaling-reproduce.herokuapp.com/old.html

## Fix

#5997

**Comment by yarsky-tgz** [comment]
@cherniavskii look wider. 
It's repdroducable if the map is located not at the top left corner of the page.

**Comment by yarsky-tgz** [comment]
@cherniavskii just look at the 

https://github.com/Leaflet/Leaflet/blob/master/src/dom/DomEvent.js

lines 228-229

event.clientX is divided by scaleX. And that's wrong. Because not overall page is scaled, but block.

**Comment by cherniavskii** [comment]
@yarsky-tgz I think you're right, I'll try to review your PR tomorrow
