### ISSUE TITLE
PopUp open more and close all

### ISSUE THREAD

**Issue by ItFutzin** [Leaflet/Leaflet#601]
Hi Vladimir,

i´d need the following behaver 

Situation: their are more than one icons on the map

User Interaction:
1. When user clicks an icon it opens a popup. When another popUp is already open it stays open!
1. When the user clicks on the map where no popup or icon is all open popups are closed
2. When the user clicks one X one one particular popup, this popup is closed

Solution?
1 is done with changing the code from openPopup to
L.Map.include({
openPopup:function(a){return this,
this._popup=a,this.addLayer(a),this.fire("popupopen",{popup:this._popup}),this},
closePopup:function(){
return this._popup&&(this.removeLayer(this._popup),this.fire("popupclose",{popup:this._popup}),this._popup=null),this}}
)
2. only the last is closed and i don´t know how to access the others?

3.same proplem is in 2 only the last opened is closed but not the others can not be closed.

To changed to this behaver was easy with version before 14.2, we changed to the new version as we would like the zoom to work on Andriod 3.0. Have you got any idea to fix this.

thanx in advance
gertie

**Comment by catbadger** [comment]
Where are all the popups closed from in RC3? I don't see iteration in any calls to closePopup
