### ISSUE TITLE
TileLayer - After using setUrl, load event is fired on every individual tile loaded

### ISSUE THREAD

**Issue by mo-ian-watkins** [Leaflet/Leaflet#6014]
Headline - If using Leaflet for animations of raster tile data, relying on load events (all tiles now loaded), these will now be broken. In my case, animations run away out of control with the browser becoming unresponsive and eventually crashing out.

Root cause appears to be a change made at 1.3.0 release

## How to reproduce

- Leaflet version I'm using: 1.3.0 & 1.3.1
- Browser (with version) I'm using: Chrome 63.0.3239.84
- OS/Platform (with version) I'm using: Windows 7

- Load a TileLayer onto a map
- On say a button click, use layer.setUrl to change the tile server endpoint

## What behaviour I'm expecting and which behaviour I'm seeing

Before and after using setUrl I'd expect to see a GridLayer.tileload event fired for every individual tile that is loaded and a GridLayer.load event fired only when all tiles are loaded.

What I'm seeing is after the setUrl is used to change the tile server endpoint, that GridLayer.tileload AND GridLayer.load is being fired for every individual tile that is being loaded.

## Minimal example reproducing the issue

In both cases, open the browser console to see the tileload and load events:

How I would expect it to work, using Leaflet 1.2.0: [Working Demo](https://mo-ian-watkins.github.io/leaflet-tileload-load/demo-1.2.0.html)

How it now works using Leaflet 1.3.0: [Broken Demo](https://mo-ian-watkins.github.io/leaflet-tileload-load/demo-1.3.1.html)

**Comment by cherniavskii** [comment]
git bisect points to #5615

Looks like there is an extra "set" of `load` and `tileload` events after proper "set" of `load` and `tileload` events was fired
![peek 2018-01-18 20-42](https://user-images.githubusercontent.com/13808724/35117831-1de2ee9a-fc90-11e7-9403-5e99f24999c1.gif)

**Comment by kwankong** [comment]
One behaviour of setUrl I find odd is that suppose you have tiles=tileLayer(url) loaded, when you run tiles.setUrl(url), the tiles would flicker, which suggests the tiles were removed and then reloaded, even if you use the same url.  But if you have image=imageOverlay(url) loaded, image.setUrl(url) does not cause the image to flicker at all.  Does anyone notice this?  Why would setUrl behave differently when applied toward tileLayer?

**Comment by perliedman** [comment]
@kwankong hi, and thanks for your interest in Leaflet! However, please do not just start adding comments to issues, especially closed ones. It adds a lot of noise for people: all people previously involved in this issue are pinged, although what you're writing doesn't really relate to it.

Also, comments on closed issues easily get lost, so if you want attention, please open a new issue (following the guidelines for submitting issues).
