### ISSUE TITLE
_getWrapTileNum is not a function

### ISSUE THREAD

**Issue by gabeta** [Leaflet/Leaflet#6023]
I can't use getWrapTileNum function with leaflet 1.2.5.
Help me to solve this problem thanks.

## Environment
- Leaflet version I'm using: 1.2.5
- Browser (with version) I'm using: Google Chrome 62.0
- OS/Platform (with version) I'm using: Ubuntu 17.10

**Comment by IvanSanchez** [comment]
That function was available in the 0.7.x series, and is no longer available in 1.x.x (since https://github.com/Leaflet/Leaflet/pull/2247).

Not being able to use `_getWrapTileNum` is now behaviour as expected.
