### ISSUE TITLE
iOS: Several symbols are blocked after tapping on leaflet map

### ISSUE THREAD

**Issue by lentyaishe** [Leaflet/Leaflet#6024]
Hi,

The bug I'm reporting here reproduces on:
- ALL versions of Leaflet starting `0.7.7` up until the most recent one - `1.3.1`;
- ALL versions of `iOS` starting `9.0` up until `11.2.2`, the most recent one currently available.

I'm using `cordova` for hybrid applications development.

The bug is extremely easy to reproduce:
1. Add an input element of type `text` to the page and a leaflet map.
2. Open this page on `iOS`.
3. Do not touch the map and try to input `6` (six symbol) to the input. It will succeed.
4. Press/tap anywhere on the leaflet map.
5. Try to enter `6` to the input. This will be blocked. The input element even does not get a `keyPress` event.

Symbols that are blocked after step 4: `6`, `-`, `+`, `=`, `_`, `^`. All these symbols are a bit interconnected. `^` is `Shift`+`6`, `_` is `Shift`+`-`, `+` is `Shift`+`=`.

It seems there is some logic that runs on the leaflet map that blocks these keys and does not recover. 

Unfortunately, there is no way to provide an example of such behavior since it reproduces on `iOS` only.

It would be great if this issue could be addressed.

Thanks in advance

**Comment by cherniavskii** [comment]
@lentyaishe is this reproducible on iOS in web (*without* cordova)?

**Comment by IvanSanchez** [comment]
Related to https://github.com/Leaflet/Leaflet/issues/5766 . I suggest disabling the keyboard map handler as a workaround.

Can't tell how keyboard events to an `<input>` can be messing up keyboard events to the map without a webpage to test this in.

**Comment by lentyaishe** [comment]
@IvanSanchez Thanks for the reference. Actually our app does not use any keyboard inputs for the map so disabling the keyboard map handler is a good workaround in case it works. But the question is how to do it? I didn't find it in the references tickets.

**Comment by cherniavskii** [comment]
@lentyaishe 
```
map.keyboard.disable();
```

**Comment by IvanSanchez** [comment]
http://leafletjs.com/reference-1.3.0.html#map-keyboard

Once again: is this reproducible in a web browser (specifically Safari in iOS) without Cordova?

**Comment by lentyaishe** [comment]
@cherniavskii Thanks! And it worked! Hooray!

**Comment by lentyaishe** [comment]
@IvanSanchez On a regular Safari this behavior does not reproduce. At least checked an a basic `plunkr`.

**Comment by joewoodhouse** [comment]
We have found this issue, using the latest cordova and leaflet. Had to implement the workaround as suggested of immediately disabling the keyboard controls.
