### ISSUE TITLE
how to show no-repeat image when load jpg?

### ISSUE THREAD

**Issue by zhuyinjing** [Leaflet/Leaflet#6026]
## How to reproduce

- Leaflet version I'm using: 1.2.0
- Browser (with version) I'm using:
- OS/Platform (with version) I'm using:
- step 1
- step 2

## Minimal example reproducing the issue

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

Using http://leafletjs.com/edit.html or any other jsfiddle-like site.

hey,when i load jpg , the small image, the image area show repeat image.

How to show no-repeat image when load  jpg????

thanks so much!

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
