### ISSUE TITLE
Feature request: map.panInside

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#6029]
As reported in https://stackoverflow.com/questions/48450191/have-leaflet-panto-not-center , there is currently no API way of panning the map so that a given point just falls within the map viewport.

There is `map.panTo()` which resets the center of the map to the given `LatLng`, and there is `map.panInsideBounds()`, which needs a `LatLngBounds`. But there is no `panInside()` which could take just a `LatLng`.

**Comment by jbccollins** [comment]
Thought this was a fun problem. Here's a possible approach (with pretty messy code):

```javascript
  panInside: function (latlng, options) {
    var bounds = this.getBounds();
    if (!bounds.contains(latlng)) {
      this._enforcingBounds = true;
      var center = this.getCenter();
      var pixelCenter = this.project(center);
      var pixelPoint = this.project(latlng);
      var pixelBounds = this.getPixelBounds();
      var sw = pixelBounds.getBottomLeft();
      var ne = pixelBounds.getTopRight();
      var l = sw.x
      var t = ne.y
      var w = ne.x - sw.x
      var h = sw.y - ne.y
      var x = pixelPoint.x
      var y = pixelPoint.y
      var nearestPoint = getNearestPointInPerimeter(l, t, w, h, x, y);
      var nearestPixelPoint = L.point(nearestPoint.x,nearestPoint.y)
      var diffPixelPoint = nearestPixelPoint.subtract(pixelPoint);
      var newPixelCenter = pixelCenter.subtract(diffPixelPoint);
      var newCenter = this.unproject(newPixelCenter);
      if (!center.equals(newCenter)) {
        this.panTo(newCenter, options);
      }
      this._enforcingBounds = false;
    }
    return this;
  }
```

getNearestPointInPerimeter from https://gist.github.com/dwtkns/d5b9b60285b8b0067c53

So the idea is that given a point 'P' that we want to invoke panInside() on our first step is to find the closest point on the rectangle that bounds that map. Once we have the closest point on this rectangle (call it cP) we take the difference between P and cP and pan our map center by that difference.

Right now the point will be right on the edge of the bounding box so maybe a parameter like 'padding' would be a nice usability thing to make sure the point remains a certain distance from the edge of the map.

**Comment by perliedman** [comment]
Closing since #6054 was merged!
