### ISSUE TITLE
Difference in map click event with overlaying polyline between 0.7.7 (works) and 1.3.1 (doesn't)

### ISSUE THREAD

**Issue by davidearl** [Leaflet/Leaflet#6035]
## How to reproduce

- Leaflet version I'm using: 1.3.1 (behaving differently from 0.7.7)
- Browser (with version) I'm using: Chrome 63
- OS/Platform (with version) I'm using: Windows 10
- step 1 see example
- step 2

## What behaviour I'm expecting and which behaviour I'm seeing

This example shows a rubber band line, as a repeatedly removed and added polyline. I want to catch a map click at the point at the end of the polyline.

In 0.7.7 a click on the map fires the map.on('click'...) event, but in 1.3.1 it doesn't. 

If I comment out adding the polyline as a layer, the click fires, so presumably the polyline is capturing the click. However it is set as clickable: false. If I set it clickable: true and add a click handler to the polyline, that doesn't fire either (if it did I could just call the same event handler).

## Minimal example reproducing the issue

1.3.1: [https://plnkr.co/edit/SRCi4gqu6jwwrt2urrQI?p=preview](https://plnkr.co/edit/SRCi4gqu6jwwrt2urrQI?p=preview)

0.7.7: [https://plnkr.co/edit/Ew3KL8DDqLC1h4zrZPwT?p=preview](https://plnkr.co/edit/Ew3KL8DDqLC1h4zrZPwT?p=preview)

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

Using http://leafletjs.com/edit.html or any other jsfiddle-like site.

**Comment by IvanSanchez** [comment]
In Leaflet v1.0.0 and later, the `clickable` option does not exist, and you have `interactive` instead, check the API docs.

With that in mind, what is wrong with the behaviour in 1.3.x?

**Comment by davidearl** [comment]
Thanks, that's the difference. If I use interactive:false, the click does fire (my problem, as I said, was the map click event wasn't firing in the later version).

It's almost impossible to locate a minor non-upward compatible change by reading a mass of documentation. Sorry I missed that. Is there a list of breaking changes between versions anywhere? I can't immediately see one.

**Comment by IvanSanchez** [comment]
No, unfortunately we never got around writing down a document about the changes between 0.7.x and 1.0.0. :-/

Closing this one as invalid.
