### ISSUE TITLE
Striuglnbg to access exported globals when using Typescript definition for leaflet

### ISSUE THREAD

**Issue by parky128** [Leaflet/Leaflet#6037]
Firstly, sorry for posting here as it's probably more an SO question. I have posted this here but not yet had any response so thought I'd ask here.

I am struggling to get a reference to any of the exported namespacse for the [leaflet][1] type definitions in my TypeScript project.

After installing the types using `npm install --save @types/leaflet` my TS compiler (I am using VS Code) is able to find some of the exported classes and interfaces in the type definition file, e.g. Transformation, Class, but I am unable to access any of the namespaces exported.

I need to be able to reference the `L` global so I can make calls to the leaflet API, but the compiler is not picking this up for me.

I did try using an import statement in my TS file I am trying to use leaflet in, e.g.

````import * as L from 'leaflet'````

But again, I can still only access the classes\interfaces this time on my imported alias, e.g. `L.Transformation`

I cannot initialise a new map, e.g by using `L.map(...)` since `L` is not accessible for me - [map][2] is an exported function in the type definition file

So I am unsure how to reference and use the `L` global for leaflet in my project.

Can anyone assist please?

Thanks

  [1]: https://www.npmjs.com/package/@types/leaflet
  [2]: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/leaflet/index.d.ts#L1385

**Comment by cherniavskii** [comment]
Hi Rob,
Thanks for using Leaflet!
However, we do not maintain TypeScript type definitions for Leaflet.
As you mentioned above - it's more SO question (or ).

That being said, I see [`L` namespace export](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/leaflet/index.d.ts#L8) in `@types/leaflet`, which should do the trick. But I'm not familiar with TypeScript.
Also, there's [similar question in DefinitelyTyped FAQ](https://github.com/DefinitelyTyped/DefinitelyTyped#should-i-add-an-empty-namespace-to-a-package-that-doesnt-export-a-module-to-use-es6-style-imports) - maybe this can help.
