### ISSUE TITLE
How to do clustering of polygons on the map?

### ISSUE THREAD

**Issue by psyapathy** [Leaflet/Leaflet#6040]
Hello. How to do clustering of polygons on the map? I'm new(
On example:
![default](https://user-images.githubusercontent.com/29089769/35804874-9a7ff04e-0a8a-11e8-9b7d-534ef8aaa21a.png)

Wanted result:
![default](https://user-images.githubusercontent.com/29089769/35804879-a472a786-0a8a-11e8-9173-e4b22c4e3d4d.png)

Questions:

1. Can this be implemented? Those show an example please

2 How always show a polygons grid? And not when you hover

3. Possible to use geojson polygons?

4. Thank you!!!

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
