### ISSUE TITLE
Tile Layer not show when zoom out just in Chrome

### ISSUE THREAD

**Issue by AndersonSchmidt** [Leaflet/Leaflet#6042]
I have a dynamic layer in leaflet and only shows when the zoom is very close, when I zoom out, it just disappears. But that only happens in Google Chrome, in Mozila works fine! I used this: (L_DISABLE_3D) and it works in google Chrome!! But the problem is that when I L_DISABLE_3D, the map get really lag.

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?
