### ISSUE TITLE
Renderer not completing shapes

### ISSUE THREAD

**Issue by MikeLeicester** [Leaflet/Leaflet#6043]
leaflet: 1.3.1
Browser: Firefox 58, chrome chrome 64
OS: Windows 10 : 1709, Windows Server 6.3

i have a map displaying GeoJson as follows 
![map full](https://user-images.githubusercontent.com/35689257/35967676-84adacf8-0cb9-11e8-8765-34db2390c0d1.PNG)

the map initially works perfect but after some time scrolling around it suddenly stops rendering all features
![map 1](https://user-images.githubusercontent.com/35689257/35967765-c7da8244-0cb9-11e8-9612-ec6a5a3ac3ce.PNG)
![capture 2](https://user-images.githubusercontent.com/35689257/35967769-ca1eda96-0cb9-11e8-9013-c37097106d99.PNG)
 
only this issue occurs the map will no longer render any new shapes until the browser is refreshed, once a refresh has been done the map resumes working normally for a time then again ceases to render

i can't predict when the error will occur so providing an snippet isn't workable but the issue happens consistently

this is the code i'm using to generate the GeoJSON layer (clipped for size

```
var geoJson = L.geoJSON(null, {
    style: style,
    onEachFeature: function(feature, layer) {
        if (feature.properties.form)
            layer.bindPopup(feature.properties.form);
    }
});
data.layers[layer.name] = {
    def: layer,
    config: {
        visable: false
    },
    json: geoJson
}
```

then add the features as so

```
data.layers[layer.name].json.clearLayers();
$.each(FeatureCollection, function(idx, feature) {
    data.layers[layer.name].json.addData(feature)
});

```
the blue line in the map has been added with exactly the same code as the red polygon but doesn't seem to be affected by what ever is affecting the red polygons

Given the fact that refreshing the page temperately fixes the issue i think that it has to be a memory leak, either the clearLayers() function is not breaking the links with the removed objects or something in the renderer is keeping a reference 

here are the results of the firefox element inspection before the issue occurs

`<div class="leaflet-pane leaflet-overlay-pane"><svg pointer-events="none" class="leaflet-zoom-animated" width="1152" height="720" style="transform: translate3d(-1145px, 1595px, 0px);" viewBox="-1145 1595 1152 720"><g><path class="leaflet-interactive" stroke="#000080" stroke-opacity="1" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" fill="none" d="M-1145 2282L-1129 2273L-1031 2238L-902 2116L-898 2114L-720 1960L-709 1963L-690 1950L-607 1900L-606 1898L-426 1788L-381 1788L-373 1785L-307 1728L-192 1595"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M-854 1751L-852 1743L-847 1735L-846 1729L-841 1726L-843 1722L-843 1715L-840 1710L-829 1700L-825 1689L-825 1662L-814 1633L-814 1628L-818 1623L-814 1618L-816 1610L-815 1601L-817 1597L-815 1595L-809 1593L-615 1593L-611 1596L-630 1656L-634 1673L-639 1685L-649 1730L-666 1790L-671 1803L-695 1891L-715 1892L-716 1894L-697 1897L-713 1954L-716 1950L-719 1952L-719 1954L-724 1953L-722 1985L-728 2005L-803 2020L-806 2009L-814 1958L-802 1956L-796 1953L-798 1950L-798 1942L-796 1942L-794 1939L-794 1937L-797 1934L-795 1926L-807 1913L-811 1912L-814 1909L-815 1903L-824 1899L-827 1896L-827 1892L-833 1889L-836 1883L-847 1873L-846 1868L-849 1861L-844 1861L-843 1859L-845 1857L-842 1852L-837 1835L-830 1822L-830 1818L-831 1814L-839 1802L-851 1797L-855 1793L-859 1784L-864 1778L-865 1772L-860 1769L-854 1762L-854 1752zM-659 1775L-634 1692L-610 1677L-608 1678L-596 1697L-642 1784z"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M-849 2032L-752 2012L-741 2016L-737 2030L-750 2071L-756 2074L-778 2078L-774 2099L-828 2112L-849 2035zM-765 1957L-765 1955L-762 1952L-758 1952L-752 1947L-738 1951L-727 1952L-724 1954L-722 1985L-728 2005L-803 2020L-806 2009L-814 1958L-802 1956L-796 1953L-792 1958L-784 1952L-779 1956L-775 1955L-772 1957L-768 1957L-766 1959L-765 1957z"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M-700 1963L-703 1955L-708 1956L-710 1953L-694 1897L-675 1897L-673 1894L-692 1892L-659 1775L-642 1784L-596 1697L-562 1739L-575 1754L-567 1759L-556 1745L-549 1753L-536 1762L-570 1822L-560 1828L-641 1924L-678 1965L-683 1964L-687 1961L-699 1963z"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M-527 1809L-524 1805L-501 1821L-497 1822L-466 1780L-429 1793L-430 1798L-429 1793L-458 1783L-462 1780L-465 1780L-497 1822L-503 1820L-524 1805L-527 1809z"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M-360 1783L-372 1747L-372 1743L-347 1711L-324 1697L-290 1767L-314 1781L-304 1797L-306 1799L-321 1806L-338 1811L-351 1813L-359 1787z"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M-532 1801L-545 1789L-546 1786L-534 1765L-519 1773L-516 1765L-495 1775L-478 1779L-418 1784L-411 1786L-414 1786L-417 1789L-417 1795L-420 1796L-447 1792L-452 1790L-463 1781L-465 1781L-496 1823L-502 1823L-531 1801zM-416 1786L-416 1786z"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M-179 1667L-174 1675L-165 1696L-185 1704L-203 1715L-224 1723L-230 1727L-243 1742L-256 1762L-259 1769L-261 1783L-263 1786L-275 1793L-299 1741L-291 1735L-278 1729L-275 1726L-278 1723L-268 1714L-269 1713L-202 1713L-269 1712L-282 1688L-295 1689L-294 1692L-300 1695L-320 1697L-325 1687L-298 1682L-300 1673L-310 1670L-313 1663L-336 1671L-355 1646L-334 1635L-321 1633L-317 1609L-267 1613L-263 1615L-258 1611L-259 1609L-257 1608L-232 1600L-230 1603L-197 1595L-199 1603L-188 1618L-175 1663L-176 1665z"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M-726 2027L-730 2028L-728 2020L-711 2023L-719 2026zM-737 2030L-742 2015L-733 2019L-737 2029zM-731 2014L-742 2012L-743 2010L-729 2007L-730 2012zM-438 1819L-441 1820L-441 1823L-434 1824L-441 1856L-453 1853L-456 1864L-436 1870L-436 1944L-442 1944L-478 1934L-501 1926L-515 1918L-545 1958L-545 1960L-549 1963L-556 1975L-560 1979L-560 1981L-568 1990L-568 1992L-578 2003L-554 2014L-560 2024L-562 2066L-585 2067L-591 2077L-592 2082L-594 2085L-597 2086L-601 2080L-604 2069L-606 2067L-611 2053L-620 2051L-623 2052L-626 2048L-631 2049L-635 2047L-636 2044L-640 2042L-639 2033L-641 2031L-644 2032L-648 2026L-652 2028L-659 2024L-666 2017L-676 2013L-685 2013L-687 2011L-692 2003L-696 1990L-701 1988L-701 1972L-699 1969L-700 1964L-687 1961L-683 1964L-676 1965L-582 1855L-560 1828L-570 1822L-552 1789L-536 1799L-527 1808L-498 1828L-496 1828L-464 1784L-458 1789L-448 1794L-417 1799L-419 1806L-426 1814L-433 1815L-438 1819z"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M-1142 2178L-1127 2182L-1106 2181L-1095 2178L-1073 2167L-1033 2204L-1049 2264L-1054 2277L-1055 2285L-1056 2288L-1061 2291L-1069 2319L-1147 2271L-1147 2197L-1142 2181z"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M-1142 2178L-1141 2177L-1134 2180L-1123 2182L-1108 2181L-1097 2178L-1073 2167L-1068 2170L-1033 2204L-1050 2267L-1055 2280L-1055 2285L-1056 2288L-1059 2289L-1062 2293L-1069 2319L-1087 2309L-1105 2296L-1146 2271L-1147 2197L-1142 2181z"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M-320 1698L-321 1697L-317 1696L-296 1694L-294 1692L-295 1689L-282 1688L-268 1714L-278 1723L-275 1726L-278 1729L-294 1736L-294 1738L-299 1741L-318 1702z"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M-320 1698L-317 1696L-296 1694L-294 1692L-295 1689L-282 1688L-268 1714L-278 1723L-275 1726L-278 1729L-294 1736L-299 1741L-318 1702z"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M-893 2078L-886 2115L-886 2125L-951 2126L-988 2130L-1010 2117L-1010 2089L-993 2090L-973 2094L-934 2085L-893 2078z"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M-497 1828L-517 1816L-536 1799L-552 1789L-536 1763L-538 1760L-549 1753L-567 1734L-593 1702L-609 1677L-566 1651L-552 1658L-487 1666L-486 1668L-480 1667L-434 1673L-429 1671L-429 1662L-422 1662L-417 1666L-416 1665L-421 1660L-420 1654L-471 1647L-495 1663L-553 1655L-568 1645L-587 1622L-593 1606L-595 1604L-595 1593L-591 1593L-590 1607L-581 1627L-561 1648L-498 1609L-486 1614L-480 1619L-480 1621L-475 1621L-475 1634L-440 1640L-423 1639L-417 1635L-382 1620L-379 1627L-371 1627L-357 1650L-332 1683L-324 1697L-347 1711L-372 1742L-372 1746L-361 1779L-363 1781L-380 1790L-412 1788L-414 1789L-415 1798L-417 1800L-451 1793L-463 1784L-465 1784L-496 1828zM-398 1650L-397 1651L-388 1649L-376 1642L-379 1630L-400 1638zM-409 1698L-415 1698L-431 1702L-439 1711L-441 1733L-438 1768L-431 1775L-402 1773L-387 1770L-382 1764L-383 1727L-380 1707L-379 1685L-376 1681L-376 1668L-382 1653L-401 1658L-408 1664L-411 1671L-412 1679L-412 1683L-410 1686L-410 1697zM-360 1671L-361 1684L-363 1689L-355 1691L-353 1682L-358 1680L-357 1667L-359 1655L-361 1655L-360 1670zM-546 1785L-545 1789L-528 1804L-501 1823L-497 1823L-493 1820L-478 1797L-465 1781L-460 1783L-452 1790L-420 1796L-417 1795L-417 1789L-414 1786L-411 1786L-417 1784L-473 1780L-495 1775L-516 1765L-519 1773L-534 1764L-546 1784zM-426 1692L-424 1693L-424 1691L-425 1692z"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M-999 2238L-960 2276L-932 2322L-982 2330L-977 2289L-1006 2274L-1012 2286L-1052 2271L-1033 2204L-999 2237z"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M-909 2128L-932 2130L-957 2129L-961 2131L-982 2131L-994 2133L-1026 2143L-1070 2166L-1072 2164L-1032 2143L-996 2131L-979 2128L-952 2126L-887 2125L-885 2128L-889 2127z"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M-642 1701L-643 1700L-640 1687L-636 1679L-611 1594L-607 1593L-631 1680L-631 1687L-627 1686L-631 1689L-633 1688L-637 1700L-665 1794L-692 1892L-674 1894L-675 1897L-694 1897L-722 1994L-721 2005L-725 2005L-728 2015L-709 2022L-710 2024L-728 2020L-743 2074L-751 2097L-791 2243L-805 2287L-809 2285L-802 2257L-758 2109L-750 2071L-733 2019L-752 2012L-743 2010L-743 2012L-731 2014L-728 2007L-722 1985L-724 1954L-720 1954L-717 1950L-713 1954L-697 1898L-716 1894L-715 1892L-696 1891L-657 1759L-642 1701z"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M-884 2130L-887 2147L-886 2161L-888 2170L-888 2183L-885 2196L-912 2169L-889 2173L-887 2155L-923 2148L-925 2166L-936 2164L-930 2130L-904 2128L-888 2128L-885 2130z"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M-969 2056L-850 2032L-829 2110L-825 2117L-825 2124L-885 2124L-893 2078L-962 2091zM-848 1871L-848 1873L-836 1884L-834 1890L-830 1890L-828 1892L-828 1896L-825 1899L-819 1901L-815 1905L-815 1909L-806 1915L-795 1927L-800 1939L-799 1949L-797 1953L-802 1956L-814 1958L-804 2020L-984 2057L-991 2056L-985 2041L-1004 2040L-1004 2056L-1026 2052L-1028 2046L-1036 1990L-1008 1984L-990 1973L-981 1972L-987 1942L-956 1934L-954 1922L-951 1920L-948 1914L-853 1877L-850 1862L-847 1866L-848 1871z"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M-124 1593L-121 1608L-90 1599L-68 1602L-12 1601L-8 1603L1 1613L16 1624L17 1644L23 1671L45 1695L13 1712L-7 1727L-21 1697L-29 1658L-29 1651L-33 1650L-89 1659L-92 1679L-148 1690L-165 1696L-174 1675L-179 1667L-175 1664L-188 1618L-199 1603L-196 1593zM-132 1661L-125 1658L-125 1648L-122 1645L-137 1643L-138 1649zM-130 1665L-129 1665z"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M-700 1963L-699 1968L-701 1971L-701 1988L-696 1990L-689 2008L-701 2020L-708 2024L-711 2021L-728 2015L-725 2005L-721 2005L-722 1994L-711 1956L-703 1956L-701 1963z"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M-700 1963L-699 1968L-701 1971L-701 1988L-696 1990L-689 2008L-701 2020L-708 2024L-711 2021L-728 2015L-725 2005L-721 2005L-722 1994L-711 1956L-703 1956L-701 1963z"></path></g></svg></div>`

and after
`
<svg pointer-events="none" class="leaflet-zoom-animated" width="1152" height="720" style="transform: translate3d(-1239px, 1589px, 0px);" viewBox="-1239 1589 1152 720"><g><path class="leaflet-interactive" stroke="#000080" stroke-opacity="1" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" fill="none" d="M-1184 2309L-1134 2275L-1031 2238L-902 2116L-898 2114L-720 1960L-709 1963L-690 1950L-607 1900L-606 1898L-426 1788L-381 1788L-373 1785L-307 1728L-187 1589"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M0 0"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M0 0"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M0 0"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M0 0"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M0 0"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M0 0"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M0 0"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M0 0"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M-1142 2178L-1127 2182L-1106 2181L-1095 2178L-1073 2167L-1033 2204L-1049 2264L-1054 2277L-1055 2285L-1056 2288L-1061 2291L-1069 2319L-1151 2269L-1150 2209L-1142 2181z"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M-1142 2178L-1141 2177L-1134 2180L-1123 2182L-1108 2181L-1097 2178L-1073 2167L-1068 2170L-1033 2204L-1050 2267L-1055 2280L-1055 2285L-1056 2288L-1059 2289L-1062 2293L-1069 2319L-1087 2309L-1105 2296L-1151 2268L-1150 2269L-1150 2209L-1142 2181z"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M0 0"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M0 0"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M-893 2078L-886 2115L-886 2125L-951 2126L-988 2130L-1010 2117L-1010 2089L-993 2090L-973 2094L-934 2085L-893 2078z"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M0 0"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M-999 2238L-960 2276L-932 2322L-982 2330L-977 2289L-1006 2274L-1012 2286L-1052 2271L-1033 2204L-999 2237z"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M-909 2128L-932 2130L-957 2129L-961 2131L-982 2131L-994 2133L-1026 2143L-1070 2166L-1072 2164L-1032 2143L-996 2131L-979 2128L-952 2126L-887 2125L-885 2128L-889 2127zM-1184 2064L-1185 2035L-1183 2033L-1183 2045L-1180 2046L-1179 2049L-1182 2065L-1180 2092L-1183 2092L-1184 2064z"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M0 0"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M-884 2130L-887 2147L-886 2161L-888 2170L-888 2183L-885 2196L-912 2169L-889 2173L-887 2155L-923 2148L-925 2166L-936 2164L-930 2130L-904 2128L-888 2128L-885 2130z"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M-969 2056L-872 2036L-872 2125L-885 2124L-893 2078L-962 2091zM-872 2034L-984 2057L-991 2056L-985 2041L-1004 2040L-1003 2055L-1015 2055L-1027 2051L-1036 1990L-1008 1984L-990 1973L-981 1972L-987 1942L-956 1934L-954 1922L-951 1920L-948 1914L-872 1884z"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M0 0"></path><path class="leaflet-interactive" stroke="#ff0000" stroke-opacity="0.6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="#ff0000" fill-opacity="0.3" fill-rule="evenodd" d="M0 0"></path></g></svg>`

happy to provide any additional information

**Comment by MikeLeicester** [comment]
note will there are no errors reported in the console there will be a warning that says

Will-change memory consumption is too high. Budget limit is the document surface area multiplied by 3 (814400 px). Occurrences of will-change over the budget will be ignored.

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by MikeLeicester** [comment]
as i said in the post as i can't predict when the error will occur, which makes pinpointing exactly which elements will cause the issue to occur difficult also the JSON i'm working with is privileged client data so can't be exposed publicly for legal reasons, but i will if i can figure out an example

**Comment by MikeLeicester** [comment]
as i said in the post as i can't predict when the error will occur, which makes pinpointing exactly which elements will cause the issue to occur difficult also the JSON i'm working with is privileged client data so can't be exposed publicly for legal reasons, but i will if i can figure out an example
