### ISSUE TITLE
Scrolling behaviour in position fixed container on touch devices

### ISSUE THREAD

**Issue by tschopo** [Leaflet/Leaflet#6045]
## How to reproduce

- Leaflet version I'm using: latest stable (1.3.1)
- Browser (with version) I'm using: Firefox for Android 58.0.1
- OS/Platform (with version) I'm using: Android 6.0.1
- step 1 put leaflet map in fixed wrapper and container with overflow auto.
- step 2 Scroll on touch device (outside of map)

## What behaviour I'm expecting and which behaviour I'm seeing

Observed behaviour: When scrolling on touch device, the map tiles (and markers) scroll faster than the rest of the page.

## Minimal example reproducing the issue

https://jsfiddle.net/t3703u0f/10/

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

Using http://leafletjs.com/edit.html or any other jsfiddle-like site.

**Comment by ghybs** [comment]
To test easily in a mobile browser: https://jsfiddle.net/t3703u0f/10/embedded/result/

This is reproducible since version `1.0.0-beta.1`: https://jsfiddle.net/t3703u0f/11/embedded/result/

But not in `0.7.7`: https://jsfiddle.net/t3703u0f/12/embedded/result/

**Comment by fergonco** [comment]
Run into this bug myself. Here some animated gif showing the problem: https://gis.stackexchange.com/questions/280044/leaflet-map-scrolled-when-dragging-the-page-on-mobile

Two things worth noting: (1)  If elmarquis/Leaflet.GestureHandling is active, their informative panel also moves (second animation). (2) selecting text makes the problem go away in my case.

**Comment by IvanSanchez** [comment]
According to the information at the stackexchange question, it can also be reproduced when the map container looks like 
```
<div style="position: fixed; top:30%; bottom:30%; overflow: auto">
  <div> Lorem ipsum ... </div>
  <div id="mapid" style="width: 600px; height: 400px;"></div>
  <div> Lorem ipsum ... </div>
</div>
```

The original bug report also specifies a value for the `overflow-y` CSS property. I'm gonna make a wild guess and say this is related to the browser's default behaviour on touch drag. Maybe it's worth testing is a `preventDefault` on the touch handlers would help? Maybe the map has to `preventDefault` drag-related events so they don't bubble up to a `overflow: auto` parent container?

**Comment by johnd0e** [comment]
Unable to reproduce the issue in any modern browser
