### ISSUE TITLE
Preventing change of map center upon `invalidateSize`

### ISSUE THREAD

**Issue by SylvainCorlay** [Leaflet/Leaflet#6051]
(With the latest leaflet.js and earlier versions, all browsers and platforms)

`invalidateSize` causes the `center` to change even when passing `{pan: false, animate: false}` as options. This happens upon the firing of the `moveend` event in the end of the implementation of `invalidateSize`.

Is there a means to get the tiles to be downloaded accordingly when the map container is resized without changing the `center`?

The motivation is for the integration of leafletjs with JupyterLab. Multiple views of the same map model can be displayed. Model data includes zoom level and center, while the views may have different sizes. Invalidating the size of one view causes the center to change and events to bounce from one view to another until the call stack becomes too big. Ideally, one should be able to `invalidateSize` without changing the center.

![views](https://user-images.githubusercontent.com/2397974/36124266-b67206be-104f-11e8-9efe-c99b5dd731c2.gif)

**Comment by SylvainCorlay** [comment]
This is related to https://github.com/Leaflet/Leaflet/issues/1919

In short, is there a means to invalidate the size without changing the center?

**Comment by Malvoz** [comment]
See also https://github.com/Leaflet/Leaflet/issues/5008.

**Comment by Falke-Design** [comment]
Doesn't happen in v1.9.2 anymore.
