### ISSUE TITLE
Layers.png not set at bower.json

### ISSUE THREAD

**Issue by AndersonSchmidt** [Leaflet/Leaflet#6056]
The icon image to change the layers (layers.png) is not defined at bower.json:
```json
  "main": [
    "dist/leaflet.css",
    "dist/leaflet-src.js"
  ]
```
I guess Leaflet's bower.json has to look like this: (This is Leaflet Draw's bower.json and it's just an example)
```json
  "main": [
    "dist/leaflet.draw.js",
    "dist/leaflet.draw.css",
    "dist/images/spritesheet-2x.png",
    "dist/images/spritesheet.png",
    "dist/images/spritesheet.svg"
  ]
```

**Comment by Falke-Design** [comment]
@mourner @jonkoops do we still support bower?

**Comment by jonkoops** [comment]
Support for Bower was removed in https://github.com/Leaflet/Leaflet/pull/6635. The images were removed from Bower before that in https://github.com/Leaflet/Leaflet/pull/4481, as it was not allowed to have these kind of assets in the config file.

Closing this issue as it is no longer relevant.
