### ISSUE TITLE
WMS examples not working

### ISSUE THREAD

**Issue by anahi-src** [Leaflet/Leaflet#6057]
I am not sure if I am reporting this in the right place, so apologies if that is the case. None of the WMS examples on the Leafletjs website appear to be working (http://leafletjs.com/examples/wms/wms.html)

**Comment by IvanSanchez** [comment]
This is a temporary failure on the WMS servers used for the demo. The responses are just a base64-encoded XML string like:

```XML
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE ServiceExceptionReport SYSTEM "https://demo.boundlessgeo.com/geoserver/schemas/wms/1.1.1/WMS_exception_1_1_1.dtd"> <ServiceExceptionReport version="1.1.1" >   <ServiceException>
      java.lang.OutOfMemoryError: Java heap space
Java heap space
</ServiceException></ServiceExceptionReport>
```
I'll let the Boundless folks about this. A restart of the service should fix everything.

**Comment by IvanSanchez** [comment]
Fixed now, as per https://www.twitter.com/boundlessgeo/status/963846129132679168
