### ISSUE TITLE
Elevation Charts & Bridges

### ISSUE THREAD

**Issue by JCarnes1000** [Leaflet/Leaflet#6061]
Hi. I work for the New York City Marathon and the upcoming NYC Half. We depend on Leaflet and the RTRT results platform to provide our runners with an interactive map of our races. One of the features we love is the elevation chart that comes from mapping out a course. However, we've recently noticed that Leaflet does not account for bridges when it comes to calculating elevation charts. It measures them as being at sea level.

My question is: How come Leaflet doesn't take bridges into account when calculating elevation charts? 

All the best,
-John

**Comment by ghybs** [comment]
Hi John,

Thank you for your message and for the example of an exciting usage of Leaflet!
Please feel free to share the link to your map!

I am not aware of a feature in Leaflet core that provides elevation chart / computation.

It sounds like your app integrates Leaflet library with 3rd party code that retrieves elevation data from an external source. That source sounds to lack data at some points like bridges.

Therefore it seems to me that the cause of the issue you describe is not in Leaflet.
