### ISSUE TITLE
Drawing SVG (or polylines) at large scales drifts north.

### ISSUE THREAD

**Issue by jwbrogden** [Leaflet/Leaflet#6063]
I'm trying to use leaflet to plot some radar data on a map. The radar data is supplied as a SVG file. Knowing the center and the bounding box of the radar image, I tried to plot the data with imageOverlay. The radar center was too far north once it was drawn.

I created a very simple test to show the problem I'm having. I've created a simple SVG of a red X. If I plot the red X with imageOverlay, it also has it's center too far north. Drawing a box with L.polyline() correctly boxes in the bounding box. However, using L.polyLine() to draw a 'X' from corner to opposite corner also causes the polylines to drift north.

Plotting polylines from corner to computed center to opposite corner does go through the center.  The computed center of the bounding box is the correct location for this radar. I get the same results from chrome or firefox. Using leaflet 1.3.1 down to 1.0.3 doesn't affect things either.

https://jsfiddle.net/J_W_B/w8ktku7x/

I'm not sure if I am doing something wrong, or if there is a problem with both SVG via imageOverlay and L.polylines()? The radar dataset covers a 600km X 600km bounding box. If I reduce that to 60km X 60km, then the center is closer to being correctly placed, but still north.

Any help would be appreciated!

**Comment by ghybs** [comment]
Hi,

Sounds like you are simply seeing the effect of the Web Mercator projection.

If your radar image is not in the same projection as the map and tiles, it will be impossible to perfectly align it.

You should have plenty resources about that online, and in particular on GIS Stack Exchange. You can also ask questions there.

**Comment by jwbrogden** [comment]
I can accept that the radar data needs to be projected correctly (I don't even know what projection they used, but can find out.)

What I don't understand is why drawing a line from the NorthWest corner to the SouthEast corner using L.polyline() doesn't pass through the center point of the bounding box?

**Comment by ghybs** [comment]
As for the polylines, unfortunately that is a technical limitation. Circles have been corrected, but for lines the code would require a more complex algorithm to compensate for the projection. PR welcome!

For now, if you absolutely need lines to follow great circles, there should a plugin listed on the plugin page that does that. It actually splits lines in a bunch of segments.
