### ISSUE TITLE
Map Tile layer is not rendered properly in a tabpanel

### ISSUE THREAD

**Issue by andresk159** [Leaflet/Leaflet#6065]
## How to reproduce

- Leaflet version I'm using:  1.3.1
- Browser (with version) I'm using: Chrome versión 63.0.3239.132
- OS/Platform (with version) I'm using: Windows 7 Professional
- Initialize a map instance in  the second tab  of a tabpanel.

## What behaviour I'm expecting and which behaviour I'm seeing
Expected: Map Tile Layer is rendered normally.
Seeing: the map tile layer is not rendered properly when it's in the second tab of a tabpanel (in the first tab the behavior is completly normal)

## Minimal example reproducing the issue

- Open https://jsfiddle.net/rusyv1fp/19/
- Go to the second tab and check the map

**Comment by cherniavskii** [comment]
Hi,
There's nothing wrong with Leaflet. You are experiencing resizing issue (map container size is 0 when map is initialized). Use `map.invalidateSize` method (see https://github.com/Leaflet/Leaflet/issues/5207#issuecomment-267898185 for more info)

**Comment by andresk159** [comment]
Thanks so much, it fixed the problem
