### ISSUE TITLE
Blurry Maps 

### ISSUE THREAD

**Issue by LittleHamster** [Leaflet/Leaflet#6068]
## How to reproduce

- Leaflet version I'm using: Latest version
- Browser (with version) I'm using: Chrome
- OS/Platform (with version) I'm using: MacOS

## What behaviour I'm expecting and which behaviour I'm seeing
Blurry maps

I noticed this issue in several topics but all of them were closed, is it me or leaflet maps are blurry? 

here is the example from the site: 
http://leafletjs.com/examples/geojson/

<img width="725" alt="image" src="https://user-images.githubusercontent.com/10330481/36576185-221578f4-181d-11e8-8db3-864c34128813.png">

here is an example from mapbox:
https://www.mapbox.com/maps/light-dark/

<img width="774" alt="image" src="https://user-images.githubusercontent.com/10330481/36576235-5b72fe50-181d-11e8-9e5a-2024797f8a06.png">

clearly the leaflet map is blurry, 
is this a known issue? any way to fix this?

**Comment by IvanSanchez** [comment]
What's your exact tile source and [DevicePixelRatio](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio)?

**Comment by LittleHamster** [comment]
@IvanSanchez 
I am on Macbook Pro Retina

**Comment by brianreavis** [comment]
Chrome seems to have changed _something_ under the hood which is causing this along with sporadic other leaflet-related issues for me (need to dig more and I'll post if there's anything relevant). 

The blurriness stems from a fractional transform on `leaflet-map-pane`:

![image](https://user-images.githubusercontent.com/118480/36633465-7b5933ce-1953-11e8-8ee0-0b0d227d53d0.png)

P.S. `window.devicePixelRatio` is `2`

**Comment by cherniavskii** [comment]
You are comparing *raster* tiles used in Leaflet example with *vector* in Mapbox.

Of course, raster tiles are blurry on retina screens.
Use `TileLayer`'s [`detectRetina`](http://leafletjs.com/reference-0.7.7.html#tilelayer-detectretina) option to avoid that.

**Comment by brianreavis** [comment]
@cherniavskii You're oversimplifying the problem, here. I'm using 512x512px raster tiles that have always looked just fine on retina (and non-retina, for that matter). The fractional `translate` causes interpolation, which causes blurring even on a non-retina screens.

**Comment by brianreavis** [comment]
![image](https://user-images.githubusercontent.com/118480/36634696-97421684-1965-11e8-9fe2-0e88114d9252.png)
This can also lead to subtle seam artifacts, depending on how you've panned.

**Comment by cherniavskii** [comment]
@brianreavis Well, TS provided link to Leaflet geojson example, which has `detectRetina` disabled by default.
Looks like you are experiencing different issue, since it affects also non-retina screens. If so, please open a new issue

**Comment by brianreavis** [comment]
Fair enough – didn't realize the reference point of this issue was comparing to vector maps.

**Comment by LittleHamster** [comment]
@cherniavskii 
if I set `detedRetina` to true the text becomes small

so here is an example map with retina set to true
![image](https://user-images.githubusercontent.com/10330481/36636142-02ad85e8-198e-11e8-9a83-06e39b96bcdb.png)

sample map without retina:
![image](https://user-images.githubusercontent.com/10330481/36636150-247507c8-198e-11e8-91b9-7b2dcdeba9d1.png)


http://jsfiddle.net/dm93f059/1/

**Comment by brianreavis** [comment]
@LittleHamster This is expected. If you don't want blurriness and don't want small text (caused by tiles being scaled to achieve retina screen dpi), you need a tile provider that supports high-resolution tiles (512x512px instead of 256x256px). This isn't a problem with leaflet.

**Comment by gabrielpeixoto** [comment]
@LittleHamster Did you resolve that?

**Comment by MikaelEdebro** [comment]
We're also seeing this behaviour. Here is a screenshot comparing on the same screen:
1. The map in QGis
2. The WMS tile opened in new tab
3. The map in leaflet

Notice how #3 is more blurry than the others.

![leaflet-blurry](https://user-images.githubusercontent.com/7080577/51039761-36da0600-15b6-11e9-9666-0daec53d64c6.png)

The screenshots are in Edge, but we're seeing the same result in Chrome, Firefox and IE as well.

**Comment by kasper747** [comment]
The problem is still there. 
with  
{tileSize: 512,
            zoomOffset: -1,
            detectRetina:true}
 the labels are too small.
Without it - the size is ok, but it is blurry. 
I am using mapbox as a provider.

**Comment by MathieuSchopfer** [comment]
I experience the same issue on 1.7.1 with OpenStreetMap (Map Box is acceptable). Either the tiles are neat but with a (too) small font size, or pixelated if I change the tile size with the following option:
```
{
    tileSize: 512,
    zoomOffset: -1
}
```

Has someone found a solution/workaround ?

**Comment by realfresh** [comment]
I think I found a simpler solution with mapbox. Remove `detectRetina` from your tileLayer config. Change the Tile API URL to look like this `https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}@2x?access_token={accessToken}`

Note the `@2x` after `{y}`. This renders a 1024px image instead of 512px which seems to remove the blurriness from the map while maintaining zoom and text site.
