### ISSUE TITLE
L.Class.include() removes inherited options

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#6070]
I noticed a bug when trying out https://github.com/Leaflet/Leaflet.TileLayer.NoGap with the latest Leaflet. 

The [minimally reproducible example](https://plnkr.co/edit/YuFXdvAzObSEIiBQd0OX?p=preview) is:

```
L.TileLayer.include({
  options: {
    MyCustomOption: 'myCustomValue'
  }
});
```

This crashes because during initialization of a `TileLayer`, `this.getPane()` gets called. That call tries to look for the value of `this.options.pane`, which is empty. Setting a debug breakpoint there and looking into `this.options` shows that only the options of the `TileLayer`  exist (options that should be inherited from `GridLayer` do not!!).

This breaks the `NoGap` plugin, and potentially more plugins out there.

Problem appears at least with Leaflet 1.3.1 in Chrome 64 and Firefox 58 on Linux. Looks like a browser-independent bug, so I haven't tested more platforms. I haven't bisected the problem yet.

**Comment by IvanSanchez** [comment]
Another [minimal(er) example](https://plnkr.co/edit/3UfF8ZbOPgGigOQFEn0j?p=preview):

```
var Foo = L.Class.extend({
  options: {foo: 'Foo!'}
});

var Bar = Foo.extend({
  options: {bar: 'Bar!'}
});

Bar.include({
  options: {quux: 'Quux!'}
})

var bar = new Bar();

console.log(bar.options);
document.write(JSON.stringify(bar.options));
```

That should log an object with three properties, but only the one from the `include()` call is there.

I've tried bisecting this, and happens way back to 1.0.0. Maybe this is related to newer browser versions after all??!

**Comment by johnd0e** [comment]
> L.TileLayer.include({
>   options: {
>     MyCustomOption: 'myCustomValue'
>   }
> });

I do not think that this ever should work in such way.
I suppose better handle such cases with [`mergeOptions`](https://leafletjs.com/reference-1.6.0.html#class-mergeoptions) and [`addInitHook`](https://leafletjs.com/reference-1.6.0.html#class-addinithook).

**Comment by johnd0e** [comment]
> I think this refers to 7458 and the PR 7459

No, dis does not.
