### ISSUE TITLE
L.TileLayer.MVTSource Can't load vector tiles in .Pbf format published by GeoServer

### ISSUE THREAD

**Issue by githubhanjunjun** [Leaflet/Leaflet#6073]
Leaflet version I'm using: 0.7.7
Browser (with version) I'm using: Google Edition 63.0.3239.132（Formal version） （32 Bit）
S/Platform (with version) I'm using: Win10 professional edition

issue:
 1、The vector tiles of the polygon type .Pbf format is published in GeoServer
 2、Loading through L.TileLayer.MVTSource
 Result: 
![1519710604 1](https://user-images.githubusercontent.com/27795864/36712761-36e75d8c-1bc5-11e8-9434-a5fd6f86f8b5.jpg)
![1519710628 1](https://user-images.githubusercontent.com/27795864/36712762-3753f028-1bc5-11e8-8d40-d7138add7755.jpg)

But the L.vectorGrid.protobuf method can be loaded successfully. Hope to solve this problem

**Comment by ghybs** [comment]
Hi, great to hear that you find Leaflet useful!

Please note that current Leaflet version is [`v1.3.1`](https://github.com/Leaflet/Leaflet/releases/tag/v1.3.1) (see also the [releases page](https://github.com/Leaflet/Leaflet/releases)).
There is currently little chance maintainers will provide support for version < 1.x

Furthermore, your issue sounds to be within a plugin ([Leaflet.MapboxVectorTile](https://github.com/SpatialServer/Leaflet.MapboxVectorTile)?).
Therefore you should raise your issue on their tracker first.

**Comment by githubhanjunjun** [comment]
Thank you very much for your reply@ghybs
