### ISSUE TITLE
Doesn't capture L.tileLayer.wms

### ISSUE THREAD

**Issue by JePedrosa** [Leaflet/Leaflet#6074]
Hello, 

I am currently using a plugin to make a map capture and print it and if I do it with a background layer L.tileLayer does it all without problem, the bad thing is when I try to do it with a background layer that is L.tileLayer.wms It hangs and does not capture me. For this I am using domtoimage.toPng, could someone help me? I do not mind using any plugin or library

The code used is:
```
	domtoimage.toPng(plugin.mapContainer, {
		width: parseInt(widthForExport),
		height:parseInt(this.mapContainer.style.height.replace("px")) 
	}).then(function (dataUrl) {
		var blob = plugin._dataURItoBlob(dataUrl);
		if (plugin.options.exportOnly) {
		    saveAs(blob, plugin.options.filename + '.png');
		} 
		plugin._toggleControls(true);
		    $('#select').show();
		    $('#inicio_fin_sesion').show();
		})
```

- Leaflet version I'm using: 1.3.1
- Browser (with version) I'm using: Firefox and Chrome
- OS/Platform (with version) I'm using: Windows

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?

**Comment by JePedrosa** [comment]
Everything is included in the HTML including the library that is used for printing. 
If you need it I can pass the code for printing in a way that is more readable

https://jsfiddle.net/JesusPedrosa/qu5d43wL/

**Comment by rowanwins** [comment]
Hi @JePedrosa 

This issue is related to the leaflet-easyPrint addin and you've already got an [issue open over there
](https://github.com/rowanwins/leaflet-easyPrint/issues/67).

This can be closed @IvanSanchez as it's not related to leaflet itself.

**Comment by ghybs** [comment]
Hi @rowanwins,

Thank you for your help and for your Leaflet plugins!
