### ISSUE TITLE
GeoJSON Polygons Disappearing and Reappearing on Pan

### ISSUE THREAD

**Issue by NicoleMeganMoore** [Leaflet/Leaflet#6075]
I have some geojson layers in my map, and for some reason (and not all the time) some of the polygons just disappear when I am panning around. It only happens on the polygons I have changed the style on for their "selected" state. This was just done by the setStyle function on that particular feature upon click. 

This happens with or without a basemap so it is not a z-index issue. It also only happens with polygons and not the points or lines, from what I have experienced. 

Here is a gif of what I am seeing: 

![polygon_disappearance_glitch](https://user-images.githubusercontent.com/32103307/36758657-56ef3e1c-1bd2-11e8-99db-1ac92c2c1ce7.gif)

## How to reproduce

- Leaflet version I'm using: 1.3.1 (does the same thing with 1.2.0)
- Browser: Chrome Version 63.0.3239.132 (Official Build) (64-bit)
- OS/Platform (with version) I'm using: Windows 8.1 64bit

**Comment by perliedman** [comment]
@NicoleMeganMoore Hi! Really hard to tell what's going on here without seeing some more of the code you're using.

Ideally, put up an example on Plnkr or similar: http://leafletjs.com/edit.html

**Comment by NicoleMeganMoore** [comment]
I tried to duplicate the problem here with some sample polygons but it won't happen again. 
https://jsfiddle.net/NicoleMeganMoore/3cv0vwh0/26/

There is quite a bit of data in my original app, which may be causing the problem to occur there and not in the fiddle. I'm not sure where to go from here.

**Comment by perliedman** [comment]
Hm, you say "vector tiles", but don't use it in the fiddle... How are you displaying vector tiles, if you're using them?

Polygons cut in half etc. is normal _while_ panning and zooming, since Leaflet clips geometry when displaying them, but they shouldn't stay that way after you stop panning/zooming. If you have a lot of geometry, this process might of course take longer time.

If you want, you could e-mail me the link to per@liedman.net, and I'll try to have a look.

**Comment by NicoleMeganMoore** [comment]
Sorry I just made the assumption that leaflet uses some sort of vector tile system in the background. I am not using it directly in my app. 

They do disappear permanently. After hours they do not come back unless I pan in the right spot or zoom to the right zoom level, depending on what it feels is the right level at the time...

I would love to, thank you! You should be receiving it shortly. To reproduce this, I just click on a bunch of different areas and zoom around and pan around. It usually happens upwards of 30 seconds of doing that.

**Comment by ghybs** [comment]
Hi @NicoleMeganMoore,

Does it also happen when using the map's [`preferCanvas`](http://leafletjs.com/reference-1.3.0.html#map-prefercanvas) option?

**Comment by NicoleMeganMoore** [comment]
I have switched it over and we are problem free - so far. I'll get a few people to vigorously test it out, but it looks promising!!

**Comment by cherouvim** [comment]
I experience something similar. I have a very simple map with ~100 Rectangle and ~100 Circle elements. After some fast zooms and pans (can't 100% reproduce the exact combination) my Rectangle elements start appearing and disappearing (and at the boundaries of this behavior they may appear half as well) as if leaflet thinks that it's in a different zoom/pan state and has to show/hide elements for performance reasons. While inspecting I can see that the `d` attribute for the `path` representing Rectangles turns to `M0 0`.

![leaflet](https://user-images.githubusercontent.com/743305/40415833-7bb36896-5e84-11e8-8c0a-05f9a2a3fc6c.gif)

My code is in react (also using react-leaflet, but don't this is what is causing problems) and looks like this:
```javascript
render() {
  return (
    <Map className="MapNavigator" zoom={8} center={[38,23]}>
      <TileLayer url="https://a.tile.openstreetmap.org/{z}/{x}/{y}.png" />
      {this.state.cities.map((city, index) => 
        <Rectangle
          key={"city-bounds-" + index}
          bounds={[[city.corner_1_lat, city.corner_1_lon], [city.corner_2_lat, city.corner_2_lon]]}
          color={"black"}
          weight="2"
        />
      )}
      {this.state.cities.map((city, index) => 
        <Circle
          key={"city-center-" + index}
          center={[city.location_lat, city.location_lon]}
          radius={1000}
        />
      )}
    </Map>
  );
}
```
Note that the react state never changes, thus the only thing that happens on the application is my zooms and pans. Nothing else.

The exact versions I use are:

    "leaflet": "^1.3.1",
    "react": "^16.3.2",
    "react-dom": "^16.3.2",
    "react-leaflet": "^1.9.1",

**Comment by ghybs** [comment]
Hi @cherouvim,

Please can you provide a reproduction example **without** react?
For example you can use https://leafletjs.com/edit.html

Otherwise I doubt we will be able to investigate.
Please also specify your OS, browser and their versions.

**Comment by TaviGherman** [comment]
I experience the same problem with Angular and Leaflet:
"leaflet": "^1.3.1",
"@angular/core": "^5.2.2"
Refreshing the map with clearLayers() and redraw them it's not helping;
I created the polygons with L.geoJson, then their respective labels with L.marker. Only the polygon are disappearing the labels remains visible, but the labels are visible on pan also, while the polygons are redrawn on pan ended.  
I am loading hundreds of polygons but doesn't seams to be related to  the amount of data loaded (sometime is working fine with over a thousand).
The old project with Angular 1 and Leaflet 0.7.2 it's working fine.

**Comment by ghybs** [comment]
Hi @TaviGherman,

Please can you provide a reproduction example **without** Angular?
For example you can use https://leafletjs.com/edit.html

Otherwise I doubt we will be able to investigate.
Please also specify your OS, browser and their versions.

**Comment by TaviGherman** [comment]
I am using Google Chrome Version 66.0.3359.181 in Windows 10, 64 bit.
The problem seams to happens regardless the browser used. 
I have tried the preferCanvas option, but same results. I suspect something about the events priority.
Unfortunately I cannot provide a reproduction example given the fact is part of a bigger project and the code is scattered in  several places.

**Comment by plepe** [comment]
Happens to me too, but I have not been successful in providing a simple reproduction example. It happens after panning for some time.

![openstreetbrowser - leaflet issue 6075](https://user-images.githubusercontent.com/249012/48191471-7e89aa80-e345-11e8-88f5-4ef5800ae75e.gif)

There are actually three types of polygons visible on this map: Buildings, created either as via L.polygon (closed ways) or L.geoJSON (multipolygons) and Arrow Heads on the magenta dashed lines, created via the leaflet-polylinedecorator module (filled polygons). All of these are affected.

What I find very interesting, that the polygons get cropped, like Leaflet would think the lower viewport boundary would be shifted. I haven't noticed yet, that the polygons would vanish from the top.

I've noticed this problem with different browsers (at least Firefox and Chromium on Ubuntu Linux). This problem exists for some time now, right now I'm using Leaflet 1.3.4, Chromium 70.0 on Ubuntu 16.04.5.

I hope this has been helpful ...

**Comment by hashamhabib** [comment]
Facing same issue. I am using polymer 3 and leaflet@1.3.4

**Comment by perliedman** [comment]
@plepe and @hashamhabib just reiterating what @ghybs said earlier:

> Please can you provide a reproduction example without Angular (Polymer / ...)?
> For example you can use https://leafletjs.com/edit.html

> Otherwise I doubt we will be able to investigate.

As it stands now, we have no way to reproduce this, just a screen cap indicating something might be wrong. Please realize that it is impossible for us to just guess our way to a solution, especially given the very limited resources we have for Leaflet maintenance.

**Comment by msimcha** [comment]
I am seeing this happen with geoJson polygons (I am using the continents) that has a stroke on it with either a hex color or a transparency. They aren't disappearing on polygons without strokes, or strokes where the color value is default or 'black'.

**Comment by perliedman** [comment]
@msimcha the default polygon has a stroke with a hex color, so this does not make sense, it should be reproducible for any polygon.

Do you have a running example that we can look at?

**Comment by astupak** [comment]
So the problem appears when polygon wieght is set to a string value. 
https://codepen.io/astupak/pen/XoXJZW?editors=1010 
To reproduce open snippet, zoom into polygon, pan furiously out of polygon bounds, zoom out and see that polygon is gone.
Works fine if weight is set to a number.

**Comment by perliedman** [comment]
@astupak huh, that is a very interesting find!

Looking quickly into this, and although I could not track down the actual error, given that this ends up with broken clipping, I would assume something after this line: https://github.com/Leaflet/Leaflet/blob/master/src/layer/vector/Polygon.js#L125

Note that we pick the polygon's `weight` and then make a point from it, which ends up having `x` and `y` components which are strings. Given how JavaScript handles addition of strings and numbers, this could potentially be a problem in some case.

I would suggest making sure a `Point`'s components are always casted to `Number` and see if that fixes the problem.

**Comment by plepe** [comment]
Good catch, thanks! I can confirm, that if `weight` is a number, the problem does not occur.

**Comment by johnd0e** [comment]
Close in favor of #6072
