### ISSUE TITLE
OSM tile URLs: https everywhere?

### ISSUE THREAD

**Issue by rzoller** [Leaflet/Leaflet#6081]
## How to reproduce

- Leaflet version I'm using: 1.3.1
- Go to http://leafletjs.com/ and copy the first example
- Go to https://codepen.io/pen/
- Paste the example
- Add required map div and css
- Add leaflet js / css

## What behaviour I'm expecting and which behaviour I'm seeing

Expected: working example
Actual: Console full of mixed-content warnings because the example I copied uses an http URL for OSM tiles.

## Minimal example reproducing the issue

See https://codepen.io/anon/pen/JpqQad

## Suggested fix

I would be happy to do a PR in order to use:

- `https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png` instead of `http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png` or `http://{s}.tile.osm.org/{z}/{x}/{y}.png` everywhere
- `https://www.openstreetmap.org/copyright` instead of `http://osm.org/copyright` everywhere (for attribution)

Edit: ok, I'm on it.

**Comment by IvanSanchez** [comment]
> I would be happy to do a PR in order to use:

Sure, that sounds good!!
