### ISSUE TITLE
the vectorgraph of the L.geoJSON painting and then the L.tileLayer.wms

### ISSUE THREAD

**Issue by yamateH-ch** [Leaflet/Leaflet#6084]
## the vectorgraph of the L.geoJSON painting and then the L.tileLayer.wms

- Leaflet version I'm using:  1.2.0
- Browser (with version) I'm using:chrome
- OS/Platform (with version) I'm using:win10

my code
 $.getJSON('test.json').then((json) => {
                    let areaInBorder 

= L.geoJSON(json, {
                        style: {
                            'color': '#fff',
                            'weight': 1,
                            'opacity': 1,
                            'fill': false
                        }
 }).addTo(map);
let sbMap = L.tileLayer.wms(url, {
                        version: '1.1.0',
                        layers: 'cite:test',
                        transparent: true,
                        format: 'image',
                        srs: 'EPSG:3857',
                        opacity: 1,
                        zIndex: 99,
}).addTo(map);

and result 
![test](https://user-images.githubusercontent.com/15885021/37096329-47da5380-2253-11e8-8ff0-b5abc916cead.png)
the areaInBorder  zindex > sbMap  zindex
I want to areaInBorder  zindex [<]([url](url)) sbMap  zindex

**Comment by IvanSanchez** [comment]
Hi,

Please read http://leafletjs.com/examples/map-panes/
