### ISSUE TITLE
Touching map marker binds map drag to mouse

### ISSUE THREAD

**Issue by tmcintire** [Leaflet/Leaflet#6085]
## How to reproduce
- Leaflet version I'm using: 0.7
- Browser (with version) I'm using: Chrome
- OS/Platform (with version) I'm using: Windows 10
- step 1 Touch a marker with a finger
- step 2 Try to move the mouse

## What behaviour I'm expecting and which behaviour I'm seeing
The mouse is permanently bound to the map drag until I touch with my finger again on another place of the map.  I'm looking to see if anyone else has experience this same issue.

**Comment by ghybs** [comment]
Hi,

Could not reproduce with Win10 Pro, Chrome 65.
Tried with Markers with or without Popup attached, with Leaflet 1.3.1 (currently latest) and also with 0.7.7, although we will likely not provide support for that version.

If you still experience your bug, please provide a reproduction case with Leaflet 1.3.1 and I will re-open.
For example you can use http://leafletjs.com/edit to build the case.
