### ISSUE TITLE
Moveable Marker

### ISSUE THREAD

**Issue by yusufcoban** [Leaflet/Leaflet#6087]
Hey guys.

I now have a map and get the basic of the map from a geoJSON file.

Now i have a websocket and sent always positions from 3 different people. So how can i add a marker , which i can move to another location?

I tried to change map._layers[*]._latlngs after adding a marker but it only changes position when i zoom out or move the map.How can i render it by myself, without zooming?

Sry

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
