### ISSUE TITLE
map.removeLayer not working

### ISSUE THREAD

**Issue by Zahma** [Leaflet/Leaflet#6091]
I'm trying to remove all layers that I stored in an array, but its seems that leaflet only removes the last drawnlayer, here is my code:

this.mergedLayersDictionary.forEach((element) => {
            console.log("___ Removing Layers ___");
            console.log(element.drawnLayer);
            console.log(this.map.hasLayer(element.drawnLayer));
            this.map.removeLayer(element.drawnLayer);
            debugger;
        });

map.hasLayers always returns true, which means that the layer is found.

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?

**Comment by Zahma** [comment]
its long code I need to do a lot of modification because it is developed in angular.
but I uploaded these pictures :
So first, I make a merge of many features and get 1 layers and then I display it using L.geojson.
In my example I did 2 merges.

this is the initial state: 
https://pasteboard.co/HbIZAM2.png

this is what I get in my console:
https://pasteboard.co/HbJ0nee.png

this is the final result I get:
https://pasteboard.co/HbIYU9A.png

as you can see only 1 merge was deleted because this.map.removeLayer didn't work on the second layer.
as you can see this.map contains the layers since it returns true. But why doesn't it remove it.

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.
