### ISSUE TITLE
t.className.startsWith is not a function

### ISSUE THREAD

**Issue by WoShiSunWuKong** [Leaflet/Leaflet#6092]
- Leaflet version 1.3.1
- chrome 65
- windows 10
 
 when click the feature,the browser console will print err infomation

![image](https://user-images.githubusercontent.com/16789187/37381916-d56a683a-277a-11e8-96ed-26a10d2a13b1.png)

**Comment by siimots** [comment]
Does not look like Leaflet bug.

More like malware/broken addon on your computer.

Where is this selection.js file?

**Comment by IvanSanchez** [comment]
Might be a misbehaving browser add-on. I agree with @siimots : where does `selection.js` come from?

**Comment by IvanSanchez** [comment]
I see the string `"saladict-frame"` in the screenshot above. I'm gonna point my finger at the "Saladict" chrome extension. Digging a bit deeper it seems that the error originates from https://github.com/crimx/ext-saladict/blob/0fd29cead6e9d1149a7f79b9ccb41bd23d6d5d1a/src/selection/index.ts#L67

Not a leaflet bug, but rather a saladict bug. Closing.
