### ISSUE TITLE
Markes leaves their position on two-finger zoom on IOS

### ISSUE THREAD

**Issue by ikhudo** [Leaflet/Leaflet#6099]
Leaflet 1.3.1
IOS 11,
Browser: Safari

it is only reproducible with `zoomAnimation: false` parameter

![leaflet 2](https://user-images.githubusercontent.com/35076442/37661426-11a4ebde-2c55-11e8-8df2-dfca3f50882a.gif)

[JSFiddle](http://jsfiddle.net/igorko82/4v6Luacz/11/)

Run it on IOS device and try to zoom in/out with pinch gesture.

**Comment by designgears** [comment]
This seems to be an issue with canvas, even with zoomAnimation: true while panning if you touch a second finger to the screen to perform a pinch to zoom the markers do the same thing as in your gif.

**Comment by manubb** [comment]
Apparently there are two different bugs reported in this issue. PR #6126 only solves one of them.
The line:
```js
setPosition(this._mapPane, new Point(0, 0));
```
in `Map.prototype._resetView` causes problem with `zoomAnimation: false`. I will open a new PR for this.

**Comment by IvanSanchez** [comment]
This seems to be a tricky scenario. @manubb How do you feel about creating a reproducible, *automatic* example of this behaviour using `prosthetic-hand`, like at https://github.com/Leaflet/Leaflet/blob/master/debug/tests/touch-shake.html ? That should make a bit easier to track down the pinch-zoom code that relies on the `zoomAnimation` option; I'm curious about why it impacts pinch-zoom at all.

**Comment by mourner** [comment]
Please check out the latest beta https://github.com/Leaflet/Leaflet/releases/tag/v1.8.0-beta.3 and see if everything's resolved?
