### ISSUE TITLE
Geolocation doesn't find my position but doesn't throw error

### ISSUE THREAD

**Issue by cmarqu** [Leaflet/Leaflet#61]
At http://hikebikemap.de/m.html, I am using code similar to the
Mobile example, which normally works great, so thank you very much
for Leaflet.

However, in an environment without geolocation available (ie. no
WLAN card etc.), when I choose "Share Location" in my browser, I get
no tiles loaded and no error message. (I get the error popup when I
choose not to share my location.) Can this be handled in Leaflet
(with a timeout maybe?) or is it a geolocation API problem?

I'm using Firefox 3.6.13 under both CentOS 4.6 and Windows Server 2003.

**Comment by karlcow** [comment]
The relevant Mozilla bug
https://bugzilla.mozilla.org/show_bug.cgi?id=675533
