### ISSUE TITLE
Change of cursor

### ISSUE THREAD

**Issue by JePedrosa** [Leaflet/Leaflet#6102]
Good, I'm trying to change the cursor according to the layer that happens but I can not, this is because I have a layer that is a large polygon, and inside this polygon I have drawn points and lines in different layers, that is, I have one layer for the polygons, another for the points and another for the lines, but I do not want the cursor to change when it is over the pointers, but only change when it is over the lines and points. Somebody could help me?

## How to reproduce

- Leaflet version I'm using: 1.3.1
- Browser (with version) I'm using: Firefox and Chrome

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
