### ISSUE TITLE
if not load tileLayer

### ISSUE THREAD

**Issue by JarekSour** [Leaflet/Leaflet#6104]
I'm using like this if not load the tile

    L.tileLayer('assets/mapa/{z}/{x}/{y}.png', { maxZoom: 13, minZoom: 1, errorTileUrl:'http://tile.openstreetmap.org/{z}/{x}/{y}.png' }).addTo(this.map)

how i can pass "{z}/{x}/{y}" to the errorTileUrl, cuz i receive that in console

    https://tile.openstreetmap.org/%7Bz%7D/%7Bx%7D/%7By%7D.png

**Comment by ghybs** [comment]
Hi,

If I understand correctly, you would like to replace the tile source by another one (OSM in this case) if the first one reports a 404 error for a given tile.

In that case, this sounds to me like a duplicate of https://github.com/Leaflet/Leaflet/issues/5810

**Comment by JarekSour** [comment]
@ghybs exactly, i'm sorry but forget to mention i'm using angular5, any idea?? thx!
