### ISSUE TITLE
Content security policy on data uri

### ISSUE THREAD

**Issue by mushishi78** [Leaflet/Leaflet#6105]
You use a data uri for the `emptyImageUrl`:

https://github.com/Leaflet/Leaflet/blob/d9655a1e9a3488110fabaddf5d382124493368ba/src/core/Util.js#L198

I'm writing a stricter Content-Security-Policy on my app and this came up because according to [MDN CSP:img-src](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/img-src), allowing data URIs should be done with caution. I think it just means using them for the `script-src` option, and they've reused the description for `img-src`, but I thought I'd flag it up as something that might be helpful to avoid if possible.

**Comment by cherniavskii** [comment]
Try this https://github.com/Leaflet/Leaflet/issues/6113#issuecomment-377593348

**Comment by ghybs** [comment]
Closing in favour of #6113
