### ISSUE TITLE
Extending TileLayer with TypeScript, cannot access parent getTileUrl

### ISSUE THREAD

**Issue by acgillette** [Leaflet/Leaflet#6108]
## How to reproduce

- Leaflet version I'm using: 1.3.1 
- Browser (with version) I'm using: Google Chrome
- OS/Platform (with version) I'm using: Unix

## What behaviour I'm expecting and which behaviour I'm seeing
I am trying to extend the L.TileLayer class with a custom getTileUrl function. The extended class should be able make a call to the parent TileLayer getUrlFunction with the new coordinates. However TypeScript is unable to find the getTileUrl function that is part of the TileLayer class.

This seemed to be an issue with the typings not including the function, but when I added in a getTileUrl declaration it still could not find the function during compilation and threw an error. I should be able to extend and override the getTileUrl class and be able to access the parent method.

## Minimal example reproducing the issue

        class StaticLayer extends L.TileLayer {
            public getTileUrl(coords) {
                coords.x = (coords.x > 9 ? coords.x : "0" + coords.x);
                coords.y = (coords.y > 9 ? coords.y : "0" + coords.y);

                return L.TileLayer.prototype.getTileUrl.call(this, coords);
            }
        }

Using http://leafletjs.com/edit.html or any other jsfiddle-like site.

**Comment by kklimczak** [comment]
Did you try use
```
return super.getTileUrl.call(this, coords);
```
instead of:
```
return L.TileLayer.prototype.getTileUrl.call(this, coords);
```
?

**Comment by acgillette** [comment]
Yes, I had attempted to use super as well. I believe it stems from the @types/leaflet definition files not having declaration for getTileUrl function https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/leaflet/index.d.ts#L509

I did eventually find a workaround by extending the TileLayerOptions interface and passing in custom options which I used to manually construct the url in a complete overriding getTileUrl function which worked.

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.
