### ISSUE TITLE
Fractional zoom level in PhantomJS

### ISSUE THREAD

**Issue by sds-dubois** [Leaflet/Leaflet#6111]
I've been trying to use fractional zoom levels in PhantomJS and couldn't figure out exactly why it was explicitly disabled since it seemed to me it should work properly. When testing I changed the user agent in PhantomJS (to trick Leaflet's PhantomJS detection) and it actually worked perfectly fine, so maybe this should be enabled?  

## How to reproduce

Can reproduce with Leaflet 1.2.0 & 1.3.1 and PhantomJS 2.1.1.
[Here](https://gist.github.com/sds-dubois/6486187f3b6ff5425e673bd95d846ed9) is a simple gist with a leaflet map and a targeted zoom level of `12.5`, and the [rendered page here](https://rawgit.com/sds-dubois/6486187f3b6ff5425e673bd95d846ed9/raw/c5c98b141e9c74b22657a8ec6a0715c784ef305b/leaflet_fractional_zoom_demo.html).

Try to take a screenshot with PhantomJS and the [rasterize.js](https://github.com/ariya/phantomjs/blob/master/examples/rasterize.js) script:
```
phantomjs rasterize.js 'https://rawgit.com/sds-dubois/6486187f3b6ff5425e673bd95d846ed9/raw/c5c98b141e9c74b22657a8ec6a0715c784ef305b/leaflet_fractional_zoom_demo.html' test_phantom.png '800px*650px'
```

![test_phantom](https://user-images.githubusercontent.com/7746635/38050782-033d2e76-3281-11e8-8c0c-1b252ed9c67c.png)

## Useful links

- [PR to disable 3D CSS transforms in PhantomJS](https://github.com/Leaflet/Leaflet/pull/1501)
- [PR for fractional zoom controls](https://github.com/Leaflet/Leaflet/pull/3523), `zoomSnap` is forced to 1 when browser doesn't support 3D CSS transformations
- [3D CSS transform issue in PhantomJS](https://github.com/ariya/phantomjs/issues/12779)

## Expected behaviour

Even though 3D tranformations seem to be an issue in PhantomJS, 2D transformations work fine and that's all what should be needed for fractional zoom levels (right?).

I noticed that `L.DomUtil.setTransform` [uses a simple translate](https://github.com/Leaflet/Leaflet/blob/fe9e0f2333888e8c02b9e7f83bf337d91006ed0a/src/dom/DomUtil.js#L208) for IE, so I tried using this behaviour for PhantomJS: a simple fix is to modify [rasterize.js](https://github.com/ariya/phantomjs/blob/master/examples/rasterize.js) by setting an IE 10 user agent
```
page.settings.userAgent = 'Mozilla/5.0 (compatible; MSIE 10.6; Windows NT 6.1; Trident/5.0; InfoPath.2; SLCC1; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; .NET CLR 2.0.50727) 3gpp-gba UNTRUSTED/1.0';
```

Now try again
```
phantomjs rasterize.js 'https://rawgit.com/sds-dubois/6486187f3b6ff5425e673bd95d846ed9/raw/c5c98b141e9c74b22657a8ec6a0715c784ef305b/leaflet_fractional_zoom_demo.html' test_ie10.png '800px*650px'
```
and you'll get the screenshot with the right zoom level.

![test_ie10](https://user-images.githubusercontent.com/7746635/38050791-0a3e62b2-3281-11e8-9e0a-ee6daed4a0c6.png)

**Comment by Falke-Design** [comment]
@mourner @jonkoops I close this because PhantomJS is not used in tests anymore and it is also not a supported Browser
