### ISSUE TITLE
Why leaflet needs to add invisible pixel on page?

### ISSUE THREAD

**Issue by techsin** [Leaflet/Leaflet#6113]
## How to reproduce

- Leaflet version I'm using: 1.3.1
- Browser (with version) I'm using: Chrome 65
- OS/Platform (with version) I'm using: Win10
- step 1: Enable Strict CSP policy
- step 2: Load the page with leaflet library and map.

## What behaviour I'm expecting and which behaviour I'm seeing
No errors.

Leaftlet wants to add image like this

`data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=`

this is the code in minified file that adds it

```
    var Qt = Object.create || function() {
        function t() {}
        return function(i) {
            return t.prototype = i,
            new t
        }
    }()
      , ti = 0
      , ii = /\{ *([\w_-]+) *\}/g
      , ei = Array.isArray || function(t) {
        return "[object Array]" === Object.prototype.toString.call(t)
    }
      , ni = "data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs="
      , oi = 0
      , si = window.requestAnimationFrame || p("RequestAnimationFrame") || m
      , ri = window.cancelAnimationFrame || p("CancelAnimationFrame") || p("CancelRequestAnimationFrame") || function(t) {
        window.clearTimeout(t)
    }
```

Why? before I make an exception for this I want to know why leaflet needs to add invisible pixel.

**Comment by cherniavskii** [comment]
Hi,
We use it for removing uneccessary images from memory

https://github.com/Leaflet/Leaflet/blob/d9655a1e9a3488110fabaddf5d382124493368ba/src/core/Util.js#L194-L198

**Comment by techsin** [comment]
ok i understand but it conflicts with csp policy and as far as I know, I can't simply whitelist this data uri. 
any ideas.

only thing i've got is to put data: in img-src for CSP policy.

**Comment by cherniavskii** [comment]
You can set CSP to `img-src 'self' data:` (see https://content-security-policy.com/ for more details).
I don't see a better solution for now.

**Comment by ghybs** [comment]
Hi,

A possible workaround would be to provide your own "empty" / dummy image that you can whitelist, and replace Leaflet's `emptyImageUrl` value by the path to that image.

Unfortunately since Leaflet is built by rollup, it is much more difficult to modify this value while using the officially built file.
You now have to override all methods that use this value (2x in GridLayer and 1x in TileLayer).

Live demo: https://plnkr.co/edit/vJc0QNqMozn6EQqypR9E?p=preview

It uses an "`emptyImage.gif`" file which path is referenced in the 3 overridden methods in `modifyEmptyImageUrl.js` script.

**Comment by techsin** [comment]
@ghybs  thanks ill go with this.

**Comment by techsin** [comment]
@cherniavskii that kinda defeats the purpose of csp policy though. But I do get that's it's a trade and an option.

**Comment by phil9001** [comment]
We are facing the same problem and found this issue, but I can see it is closed. I can't seem to get the script working with the latest versions of Leaflet though. Would it be possible to find a permanent solution that can be bundled with the package itself?
