### ISSUE TITLE
Wrong layerControl height

### ISSUE THREAD

**Issue by bummm26** [Leaflet/Leaflet#6134]
I am using Leaflet to display geographical data. I implemented the layerControl example in my own page but I always get worng height of layers control. I have been working on this problem for a day but I can't figure out the probelm. I attached my problem:

![image](https://user-images.githubusercontent.com/32642115/38615848-65a25da4-3d92-11e8-976d-74fde39a042a.png)

I use Leaflet in Bootstrap 3 environment.

**Comment by cherniavskii** [comment]
Here's Leaflet example without Bootstrap - http://leafletjs.com/examples/layers-control/example.html

Your issue is caused by Bootstrap, which overrides leaflet styles

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.
