### ISSUE TITLE
Add custom bindTooltip class

### ISSUE THREAD

**Issue by bummm26** [Leaflet/Leaflet#6135]
I am trying to add custom class to my bindTooltip but the new class do not show up. My method based on [this](https://gis.stackexchange.com/questions/212820/overriding-leaflet-tooltip-style) question. 

My custom popup class is working fine but if I want to overwrite the tooltip class than it is now working. 

**My JS code:**

```
 var PopupClass={'className': 'class-popup'}
 var TooltipClass={'className': class-tooltip'}

L.marker([46.17319713, 21.34458608],{icon: OnlineMarker}).bindPopup('Test Popup', PopupClass).bindTooltip('Test Tooltip',{direction: 'top', permanent: true, offset: [10,0]}, TooltipClass).addTo(MyMap)
```
**My CSS code:**

```
/* popup-class*/
.class-popup .leaflet-popup-content-wrapper {
  background:#2980b9;
  color:#fff;
  font-size:10px;
  line-height:10px;
  }

.class-popup .leaflet-popup-content-wrapper a {
  color:#2980b9;
  }
.class-popup .leaflet-popup-tip-container {
  width:40px;
  height:20px;
  }
.class-popup .leaflet-popup-tip {
  background:#2980b9;
  }

/* tooltip-class*/ 

.class-tooltip{
  background: green;
  border: 2px solid cyan
}
.leaflet-tooltip-left.class-tooltip::before {
  border-left-color: cyan;
}
.leaflet-tooltip-right.class-tooltip::before {
  border-right-color: cyan;
}
```

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
