### ISSUE TITLE
In geolocation event handler view bounds are calculated incorectly

### ISSUE THREAD

**Issue by wladich** [Leaflet/Leaflet#6139]
In Map._handleGeolocationResponse value of Coordinates.accuracy is interpreted as diameter of "confidence circle", but it should be radius.
Error is at line https://github.com/Leaflet/Leaflet/blob/master/src/map/Map.js#L659:
`
bounds = latlng.toBounds(pos.coords.accuracy),
`
LatLng.toBounds according to manual:
> Returns a new LatLngBounds object in which each boundary is sizeInMeters/2 meters apart from the LatLng.

But after reading the definition of Coordinates.accuracy  from MDN https://developer.mozilla.org/en-US/docs/Web/API/Coordinates/accuracy
> The Coordinates.accuracy read-only property is a strictly positive double representing the accuracy, with a 95% confidence level, of the Coordinates.latitude and Coordinates.longitude properties expressed in meters.

and accuracy term in wikipedia https://en.wikipedia.org/wiki/Accuracy_and_precision I'm sure Coordinates.accuracy should be the radius of "confidence circle"

I attached demo illustrating wrong behavior of Map._handleGeolocationResponse:
https://jsfiddle.net/4zjLzqv1/

Here blue circle radius equals `Coordinates.accuracy` and red circle radius equals `Coordinates.accuracy / 2`.
Blue circle is larger then view bounds and can be seen only when zoomed out one step.

Conclusion:
Line https://github.com/Leaflet/Leaflet/blob/master/src/map/Map.js#L659 should be
`
bounds = latlng.toBounds(pos.coords.accuracy * 2),
`

Error was introduced in first commit of geolocation support:
https://github.com/Leaflet/Leaflet/blame/e87e010e7ddb4acec5088362a43f5e9227e0a9eb/src/map/ext/Map.Geolocation.js#L63

**Comment by IvanSanchez** [comment]
Sounds like an easy fix. Care to send a pull request?

**Comment by spmsupun** [comment]
+1

**Comment by wladich** [comment]
#6140

**Comment by ghybs** [comment]
Fixed by #6140
