### ISSUE TITLE
When I place markers on the map, after going past the world, they dissapear. Have to go back from the other side to see them again.

### ISSUE THREAD

**Issue by mmezian** [Leaflet/Leaflet#6144]
## How to reproduce

Leaflet V 1.3.1

Chrome latest version 

Windows 

Placing markers on all major cities in France, US and China

Scrolling left, until I get past the limits, and get back to the same countries

The pins dissapear. I have to scroll right again to see them.

## What behaviour I'm expecting and which behaviour I'm seeing

France Pins should be in France even if I get past over the limits of the world. Otherwise, then tell me how to block the map so people can't go past the limits, and they have to go back the other side.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

And remember to look at the Leaflet API documentation, specifically about the `worldCopyJump` option and the `maxBounds` options for your `L.Map`.

**Comment by mmezian** [comment]
Hi

Isn't this a bug? To have markers dissapear when the users scrolls past the world????
