### ISSUE TITLE
Mouseup not firing after dragend in Firefox 59.0.2 when hovering over rectangle

### ISSUE THREAD

**Issue by krdyke** [Leaflet/Leaflet#6145]
## How to reproduce

- Leaflet version I'm using: 1.3.1
- Browser (with version) I'm using: Firefox 59.0.2 (64bit)
- OS/Platform (with version) I'm using: Windows 10 Enterprise

## What behaviour I'm expecting and which behaviour I'm seeing
I have an interface where, while the map is dragged, a rectangle is drawn on the map. 

![rectangle during drag](https://i.stack.imgur.com/cXVAr.gif)

This appears to work okay in Chrome and Internet Explorer. In FF, if you click and drag the map, and release the mouse button while hovering over the rectangle, the map does not fire a mouseup event. This means that if you hover over the toolbar on the right of the plunkr, you won't see the expected hover behavior until you click somewhere on the toolbar.

![leaflet2](https://user-images.githubusercontent.com/666141/39434625-bb284ede-4c5e-11e8-9e5c-31367c0d3fec.gif)

A helpful [StackOverflow](https://stackoverflow.com/questions/50070003/leaflet-js-displaying-a-moving-rectangle-during-drag) user suggested using a timeout when removing the rectangle, which seems to correct the problem. I'm aware this is a rather edge case, so maybe this solution is enough!

## Minimal example reproducing the issue

- [x ] this example is as simple as possible
- [x ] this example does not rely on any third party code

Using http://leafletjs.com/edit.html or any other jsfiddle-like site.

I've created a minimal example using Plunkr.
https://plnkr.co/edit/lwkaMUPnrxUndaYVcQMM?p=preview

**Comment by johnd0e** [comment]
Indeed, the things are going slightly different in FF.
In your planker the rectangle get removed from map before `mouseup` get a chance to finish bubbling, so `setTimeout` is decent solution.

Another (even simpler one) is to specify `{interactive: false}` as polygon option.
