### ISSUE TITLE
ImageOverlay clarity issues

### ISSUE THREAD

**Issue by HMKola** [Leaflet/Leaflet#6146]
## How to reproduce

- Leaflet version I'm using:  1.3.1
- Browser (with version) I'm using: Chrome
- OS/Platform (with version) I'm using: Win 10
- step 1 : Add Large size image like (2500x5000) in ImageOverlay.
- step 2 : Tray to Zoom Out (its loose picture clarity even image size is not reach upto (2500x5000)

## What behaviour I'm expecting: ImageOverlay image should maintain its clarity. 
 which behaviour I'm seeing :ImageOverlay image zoom and blur on zoom out/In

Thanks In Advance
Haresh Kola

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?

**Comment by IvanSanchez** [comment]
See also https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering

**Comment by HMKola** [comment]
https://jsfiddle.net/user2314737/Lfzrqvet/ 
just replace any Large size image like  this https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/ESC_large_ISS022_ISS022-E-11387-edit_01.JPG/4096px-ESC_large_ISS022_ISS022-E-11387-edit_01.JPG
