### ISSUE TITLE
Enable and Force HTTPS on the leafletjs.com website

### ISSUE THREAD

**Issue by theel0ja** [Leaflet/Leaflet#6147]
HTTPS has been released for Github Pages custom domains:
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

Geolocation examples are not currently working because the site is using http.

Edit 2018-05-03: added explanation for linked blog post.

**Comment by mourner** [comment]
Yeah. We should do this eventually, but it's not trivial because GitHub doesn't support HTTPS on its custom-domain websites. We'd need to set up some kind of proxy, e.g. with CloudFlare.

**Comment by ghybs** [comment]
Hi @mourner,

Actually if I understand correctly the blog post linked by @theel0ja, GitHub just added support of HTTPS for custom domains, hence why @theel0ja opened this Feature Request?

**Comment by mourner** [comment]
Damn, apparently I had a case of selective blindness. Sorry! Yes, we should definitely do this now. @JasonSanford the blog says the DNS config should be updated with new IPs, can you take a quick look?

**Comment by theel0ja** [comment]
@ghybs Yes, I sent the feature request because Github added HTTPS support for custom domains.

**Comment by JasonSanford** [comment]
I just updated the A records to point to

```
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153
```

The previous TTL was 30 minutes so hopefully soon we'll be hitting the new IP addresses, then we can ✅ it hopefully.

**Comment by mourner** [comment]
@JasonSanford thanks a lot Jason!

Hmm, I'm seeing leafletjs.com resolving to the new IP addresses, but the browsers still say "Not secure". Here are details from Safari for example:

![image](https://user-images.githubusercontent.com/25395/39585747-2646c168-4efe-11e8-9dc3-dfe4be06f268.png)

No idea how to resolve this — I'm really bad at security stuff. Any clues?

**Comment by mourner** [comment]
Let me try something now...

**Comment by theel0ja** [comment]
Mixed content should be fixed.

![image](https://user-images.githubusercontent.com/5832930/39586582-0f2b65cc-4f00-11e8-8113-07c0cf9acc62.png)

**Comment by mourner** [comment]
@theel0ja great! It started working for me for https://leafletjs.com, but for some reason https://www.leafletjs.com times out. Is this an issue on the GitHub side or with our configuration?
Let's fix the mixed content thing — want to do a PR?

**Comment by theel0ja** [comment]
@mourner www.leafletjs.com is directed to a Namecheap IP address.

https://iplookup.theel0ja.info/?host=www.leafletjs.com

**Comment by mourner** [comment]
@JasonSanford does the above mean we should add some records on the DNS config side for www specifically?

**Comment by JasonSanford** [comment]
That sounds right. Let me look in the DNS config.

**Comment by JasonSanford** [comment]
The DNS settings had the www subdomain redirecting to http, not https. I've changed this and it should be propagating now.

**Comment by mourner** [comment]
@JasonSanford hmm, will a redirect work with https? It seems that it wouldn't. Could we just add records for www to point to GitHub IPs just like for the core domain?

**Comment by theel0ja** [comment]
https://github.com/Leaflet/Leaflet/pull/6150

**Comment by mourner** [comment]
Merged the mixed content fixes. https://www.leafletjs.com is still not working — let's wait for a fix to that, and then I'll be able to turn on "enforce https" in the settings.

**Comment by JasonSanford** [comment]
I mess around with DNS about once a year and always struggle. What I've got below is apparently not working. Anyone have ideas?

![image](https://user-images.githubusercontent.com/220341/39598726-8df08428-4ee7-11e8-803f-26a5a5dc3797.png)

**Comment by JasonSanford** [comment]
Here's the rest of the records for reference.

![image](https://user-images.githubusercontent.com/220341/39598828-d79cc0d2-4ee7-11e8-9934-87d8d907cbd6.png)

**Comment by mourner** [comment]
@JasonSanford found [this GitHub help page](https://help.github.com/articles/setting-up-a-www-subdomain/) which suggests pointing CNAME to the GitHub domain, e.g. leaflet.github.io — not sure if it's applicable in our case but maybe worth a try.

**Comment by mourner** [comment]
We're now enforcing https, and also www.leafletjs.com redirects to https://leafletjs.com, which is good enough to close this issue. The only remaining thing is that https://www.leafletjs.com doesn't work, but let's leave it at that and maybe find a solution later.

**Comment by mourner** [comment]
Hmm suddenly https://www.leafletjs.com started to work — no idea what changed (maybe some cache updated) but great :) @JasonSanford no further action needed then.
