### ISSUE TITLE
ionic 3 on device map image not load 

### ISSUE THREAD

**Issue by bhumin3i** [Leaflet/Leaflet#6148]
```

initMap(geoJsonUrl) {
  this.map = L.map('map', {
    center: this.centerCordinates,
    zoom: 16
  });
  //Add tile layer
  L.tileLayer('http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', {
  }).addTo(this.map);
  this.setPolygon(geoJsonUrl)
  //this.map.setView([-10, 25500], 4);
}
setPolygon(geoJsonUrl){
  if(this.layer != undefined){
    this.layer.remove()
  }
  console.log('geoJsonUrl',geoJsonUrl);
  console.log('L.geoJSON()',L.geoJSON());
      //Read JSON DATA and use it for velocity layer
      this.http.get(geoJsonUrl).map(res=>{return res.json();}).subscribe(data => {
        console.log('data',data);
        this.layer = L.geoJSON(data, {
          style: function (feature) {
            console.log('feature',feature);
              return {color: '#169CFF'};
          }
      }).bindPopup(function (layer) {
        console.log('layesr',layer);
        if(layer.feature.properties.NAME != null){
          return layer.feature.properties.NAME;
        }else{
          return 'No Name';
        }
        
      }).addTo(this.map);
    
        });
}
```

output: 

![screen shot 2018-05-03 at 7 26 06 pm](https://user-images.githubusercontent.com/25737987/39581307-e27eaf76-4f08-11e8-9668-80c148bb356b.png)

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.

**Comment by IvanSanchez** [comment]
And double check that you're loading the `leaflet.css` file, that tile misalignment is a typical symptom of missing CSS.
