### ISSUE TITLE
ImageOverlay of an animated gif does not loop on Chrome mobile only on Incognito

### ISSUE THREAD

**Issue by neavilag** [Leaflet/Leaflet#6155]
## How to reproduce

- Leaflet version 1.3.1
- Chrome 66 on Android

check my approach here [http://climaya.com/leaflet/leaflet_imageoverlay.html](http://climaya.com/leaflet/leaflet_imageoverlay.html)

The animated gif is working and loops if you check it con Chrome Desktop 66 but if you test in Android the gif does not loop

**Other Tests:**
Tested on Firefox on Android and works fine (gifs loops)
Testes on Chrome on Android in Incognito Mode and works fine (gifs loops)

**Comment by cherniavskii** [comment]
Can't reproduce on Android Chrome 66.0.3359.126.

Please note, that looping parameters are encoded into GIF itself, so IMHO we have nothing to do with that on Leaflet side

**Comment by neavilag** [comment]
Thank you for your response, so to confirm you where able to see the looping gif in Chrome Android ? if that is the case is not the gif, the same gifs loops fine in google maps image overlay
