### ISSUE TITLE
Map doesn't load on window size expansion

### ISSUE THREAD

**Issue by advancedits** [Leaflet/Leaflet#6156]
## How to reproduce

- Leaflet version I'm using:
Leaflet 1.3.1

- Browser (with version) I'm using:
Chrome
Version 66.0.3359.139 (Official Build) (64-bit)

- OS/Platform (with version) I'm using:
MAC OS

Steps to reproduce the error:

1. Make browser size small

2. go to
https://www.nwfsc.noaa.gov/data/map

3. then maximize window and see gray bars around the map.

## What behaviour I'm expecting and which behaviour I'm seeing
What happens is when the window maximizes

I was expecting the map to reload or expand onto the areas that were not previously loaded due to the window size.

## Minimal example reproducing the issue

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

Using http://leafletjs.com/edit.html or any other jsfiddle-like site.

**Comment by jgravois** [comment]
Leaflet has a dedicated method for this.

> [`map.invalidateSize()`](https://leafletjs.com/reference-1.3.0.html#map-invalidatesize) Checks if the map container size changed and updates the map if so — call it after you've changed the map size dynamically.

**Comment by advancedits** [comment]
@jgravois  so upon detecting that the browser window size has changed, call map.invalidateSize()?

**Comment by advancedits** [comment]
That did the trick...thank you @jgravois
