### ISSUE TITLE
setUrl causes tiles loaded with tileLayer to flicker

### ISSUE THREAD

**Issue by kwankong** [Leaflet/Leaflet#6158]
One behaviour of setUrl I find odd is that suppose you have tiles=tileLayer(url) loaded, when you run tiles.setUrl(url), the tiles would flicker, which suggests the tiles were removed and then reloaded, even if you use the same url.  But if you have image=imageOverlay(url) loaded, image.setUrl(url) does not cause the image to flicker at all.  Has anyone noticed this?  Why would setUrl behave differently when applied toward tileLayer?

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?

**Comment by kwankong** [comment]
Okay, Ivan,
I have a couple of demos set up using
(1) imageOverlay: https://plnkr.co/edit/sa74aFv4u2jgsFBU93G6?p=preview
(2) tileLayer: https://plnkr.co/edit/nxnga7MqeC3bgUEM07Dz?p=preview

**Comment by perliedman** [comment]
Looking at the code, I can see this:

* Calling `TileLayer.setUrl` will always cause a `redraw` unless the second argument to `setUrl` is `true`: https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/TileLayer.js#L117
* `ImageOverlay.setUrl` will update the `img` element's `src` attribute, which I assume the browser is smart enough to optimize into a no-op if `src` is the same

We could quite easily add the same optimization in `TileLayer.setUrl`, checking first if the new URL differs from the old. The only downside I can see is if someone relies on `setUrl` to always make a redraw.

**Comment by kwankong** [comment]
A couple of questions:
1. When TileLayer.setUrl is called, does it redraw only the visible tiles or all the tiles, for all zoom levels?
2. Is it possible to update the src attribute in TileLayer similar to how it is done in ImageOverlay?

**Comment by IvanSanchez** [comment]
> When TileLayer.setUrl is called, does it redraw only the visible tiles or all the tiles, for all zoom levels?

It redraws only visible tiles (but will use the new URL template for future tiles)

Keep in mind that (in the default CRS), for a zoom level `z`, there are `4^z` tiles. That's like 17 thousand million for zoom level 17, and no browser is loading (nor reloading) that amount of tiles, ever.

> Is it possible to update the src attribute in TileLayer similar to how it is done in ImageOverlay?

Yes, it is. But no one has written the code for it yet.

**Comment by JackNeus** [comment]
Hi, I took a shot at fixing this in #6313. Let me know if this change is still needed, and if my approach is appropriate!

**Comment by Malvoz** [comment]
Confirmed fixed since v1.4.0 (https://github.com/Leaflet/Leaflet/pull/6313).
