### ISSUE TITLE
Map breaks when created dynamically in combination with disabled worldCopyJump

### ISSUE THREAD

**Issue by tgelz** [Leaflet/Leaflet#6165]
I've come across a strange issue when creating the map container in JS, appending it to a wrapper and setting the map size at a later time. This only occurs when worldCopyJump is disabled, however.

https://jsfiddle.net/2w6apqxy/

The map tiles are partially broken and the map center is at an incorrect position. When appending the container before `L.map()` (https://jsfiddle.net/2w6apqxy/1/) or after `L.tileLayer()` (https://jsfiddle.net/2w6apqxy/2/), the issue isn't present. When enabling worldCopyJump, the issue isn't present either, regardless of when the container is appended to the wrap.

Is this a bug related to how the map dimensions are determined when worldCopyJump is disabled vs. enabled, or is this expected behavior?

**Comment by perliedman** [comment]
Hi!

Thanks for a thorough report. I can reproduce this, and from what you're saying, it clearly sounds like a bug.

I investigated for a short while, but didn't find why this is happening, so some further investigation is going to be necessary.

**Comment by cherniavskii** [comment]
@ghybs your solution seems reasonable 👍

**Comment by tgelz** [comment]
@ghybs thanks for the explanation. Your solution works in my implementation as well 👍

**Comment by ghybs** [comment]
Hi @alex2wong,

Your screenshot and description look like a totally different issue from what OP described.

I suspect your case to be similar to:
https://stackoverflow.com/questions/38835758/leaflet-drawing-tiles-disjointly/38836996#38836996
