### ISSUE TITLE
when create polyline using L.polyline, there is a error,while I has use leaflet in  vue component

### ISSUE THREAD

**Issue by rayxc** [Leaflet/Leaflet#6168]
Hello, I am currently working on a leaflet project for gis. The front-end framework is vue and I have a problem. First of all, I have encapsulated a map vue component (abbreviated as a map component), another vue component contains different icon information (abbreviated as the drawing component), and a method to listen to the map click event drawing points, lines, faces. When the map component is mounted, send the initialized map as a parameter to the event bus, listen to events in the drawing component, obtain the map object, and click the different icons of the drawing component to draw points, lines, and faces in the map. In the component, it is normal to draw points and faces, and there are errors when drawing lines.
here is my code:
drawPolylineImpl(latlng, arrs, fillColor) {
                arrs.push([latlng.lat, latlng.lng]);
                if(arrs.length > 2){
                    console.log(arrs);
                    if(this.tempGeometry){
                        this.drawFeatures.removeLayer(this.tempGeometry);
                    }
                    this.tempGeometry = L.polyline(arrs);
                    this.tempGeometry.addTo(this.map);
                }
 }
here is theerror:
Uncaught TypeError: Cannot read property 'x' of undefined            leaflet-src.js?5636:1021
    at Bounds.intersects (leaflet-src.js?5636:1021)
    at NewClass._clipPoints (leaflet-src.js?5636:8059)
    at NewClass._update (leaflet-src.js?5636:8104)
    at NewClass._reset (leaflet-src.js?5636:7614)
    at NewClass.onAdd (leaflet-src.js?5636:7562)
    at NewClass._layerAdd (leaflet-src.js?5636:6401)
    at NewClass.whenReady (leaflet-src.js?7f7c:4367)
    at NewClass.addLayer (leaflet-src.js?7f7c:6549)
    at NewClass.addLayer (leaflet-src.js?5636:6612)

why that error arised?

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.

**Comment by imudin** [comment]
@rayxc did you find a solution?
