### ISSUE TITLE
Any plans to add two-finger touch panning informational overlay?

### ISSUE THREAD

**Issue by tger** [Leaflet/Leaflet#6169]
On our mapping services we have two-finger touch panning enabled on mobile devices. While fairly standard (popularized by Google Maps I think) we show an informational overlay when the user supposedly tries to pan using one finger (which we use to scroll the web page instead). Demo [here](https://www.havochvatten.se/hav/samordning--fakta/havsplanering/havsplaner/forslag-till-havsplaner/vagledning-om-mest-lamplig-anvandning-i-havsplanerna.html#plankarta).

This was easy to implement in iOS using standard touch event handlers. On Android it was much more problematic since the browser seems to receive more or less raw touch sensor data (in particular the DOM event `touches` array always seem to contain one element, and firing two events instead of a one event with a `touches` array of length 2 when panning using two fingers).

Any plans to add support for such an overlay to Leaflet (and in particular make sure it works well on Android)?

**Comment by IvanSanchez** [comment]
No, there are no plans, because [there's a plugin for that](https://github.com/elmarquis/Leaflet.GestureHandling/) already.
