### ISSUE TITLE
L.Control Layer image change

### ISSUE THREAD

**Issue by Naksta** [Leaflet/Leaflet#6170]
Hello all,

I'm currently working on a map at the following website : https://www.conanexilesmap.com/

Right now, I am trying to change the icons for the layer controls at the top right so users will be able to differentiate between them based on looking at them. Right now, I am stuck using the same image for all three.

My questions is, is there a way to intercept the CSS that's being applied to the layer control and apply a different icon? I am not able to figure this out :(

Thank you!

You can view the source for the project here : 
https://github.com/Naksta/mapconan

Preview of the icon's I would like to control : 
![image](https://user-images.githubusercontent.com/1343858/40572933-f828bdec-6085-11e8-9697-6d9d678022ed.png)

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by ghybs** [comment]
Might be the same question on SO:
https://stackoverflow.com/questions/50544217/change-leaflet-layer-control-icons
