### ISSUE TITLE
map.tap.disable(); gives ERROR in console but works! BUG!?

### ISSUE THREAD

**Issue by Allmedialab** [Leaflet/Leaflet#6174]
Hi,
When I add: "map.tap.disable();" to my script to make OpenStreetMaps scroll able on the iPad and iPhone I get an error, but it works!  tap: false, does nothing.
 In the console: "Uncaught TypeError: Cannot read property 'disable' of undefined".
Is this a Leaflet error or a code error?
Regards & Thanks,
David

` var map = L.map('map').setView([50.9697271, 6.1235902], 15);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', 
     {
      attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors">MassGIS</a>',
      maxZoom: 17,
      minZoom: 9
    }).addTo(map);
L.marker([50.9697271, 6.1235902]).addTo(map)
    .bindPopup('Galabau<br>Resenberger')
    .openPopup();
map.scrollWheelZoom.disable();
map.dragging.disable();
map.tap.disable();`

**Comment by jbccollins** [comment]
"tap" is not a defined map interaction handler (unless you're using some version of leaflet with extensions). "disable" is only applicable for the interaction handlers defined in the docs.
https://leafletjs.com/reference-1.3.0.html#handler-disable

Effectively you are trying to do
```
map.SomeRandomUndefinedThing.disable()
```
Which breaks.

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?
