### ISSUE TITLE
L.PosAnimation() doc usage exemple is not working

### ISSUE THREAD

**Issue by laurentdebricon** [Leaflet/Leaflet#6175]
In the doc : 
```
Usage example
var fx = new L.PosAnimation();
fx.run(el, [300, 500], 0.5);
```
sadly leaflet will crash, asking for the function newPos.subtract  , so the correct syntax is Point(300,500)
```
var fx = new L.PosAnimation();
fx.run(el, Point(300,500), 0.5);
```

We could provide a better exemple , for exemple a bounce effect of a marker on click on it :

```
var myPositionMarker = L.marker([48.864716, 2.294694]).addTo(map);

myPositionMarker.on("click", function(){
	var pos = map.latLngToLayerPoint(myPositionMarker.getLatLng())
	pos.y -= 25;
	var fx = new L.PosAnimation();

	fx.once('end',function(){
		pos.y += 25;
		fx.run(myPositionMarker._icon, pos, 0.8);
	});

	fx.run(myPositionMarker._icon, pos, 0.3);

});

```

**Comment by perliedman** [comment]
👍 Good catch. Care to make a PR with these changes?

If you don't already know, the example in question comes from a code comment located here: https://github.com/Leaflet/Leaflet/blob/master/src/dom/PosAnimation.js#L6
