### ISSUE TITLE
Vector layer with a raster overlay (raster overlay not visible)

### ISSUE THREAD

**Issue by nijs9** [Leaflet/Leaflet#6178]
## How to reproduce

- Leaflet version I'm using: 1.3.1
- Browser (with version) I'm using: Latest Chrome
- OS/Platform (with version) I'm using: Windows 10
- Create a leaflet map and use a vector layer with leaflet mapbox gl. Add a second raster overlay

## What behaviour I'm expecting and which behaviour I'm seeing

I expect raster overlay is projected over the vector layer, but raster layer isn't visible anymore. Is this a bug?

```js
var Lmap = L.map('map', {

    maxBounds: L.latLngBounds(L.latLng(49.4227, 2.2749), L.latLng(51.6633, 6.5815)),
    minZoom: 8,
    maxZoom: 18
});

var gl = L.mapboxGL({
    attribution: '<a href="http://www.openmaptiles.org/" target="_blank">© OpenMapTiles</a> <a href="http://www.openstreetmap.org/about/" target="_blank">© OpenStreetMap contributors</a> <a href="https://www.maptiler.com/license/maps/" target="_blank">© MapTiler</a>',
    accessToken: 'not-needed',
    style: 'https://maps.tilehosting.com/styles/topo/style.json?key=xxx'
});

var network_overlay = L.tileLayer('https://xxx.com/geoserver/gwc/service/gmaps?layers=nodemapp-public-with-cache&zoom={z}&x={x}&y={y}', {

    opacity: 0.7

});

gl.addTo(Lmap);
network_overlay.addTo(Lmap);
```

**Comment by mourner** [comment]
This is by design — please see this tutorial https://leafletjs.com/examples/map-panes/
