### ISSUE TITLE
[Feature request] Upscale tiles on high resolution displays

### ISSUE THREAD

**Issue by NopMap** [Leaflet/Leaflet#6187]
## How to reproduce

- Use a map created for a standard resolution display (e.g. 100 DPI monitor) with leaflet on a high resolution display (e.g. 300 DPI Retina Handy, 4K monitor)

## What behaviour I'm expecting and which behaviour I'm seeing

- What I see: Technically, the map is displayed as expected, but due to the high resolution all texts, icons and details on standard resolution map tiles are so small that they are unreadable/unrecoginzably.
- Feature request: Add a mode that upscales tiles (sort of the opposite of detectRetina): When a high resolution display is detected, scale all tiles up to quadruple size, showing only one forth of the number of tiles. The upscaling would compensate for the high resolution and make the map appear in the same way as it was intended on standard resolution devices. The map becomes readable and usable again.

**Comment by IvanSanchez** [comment]
There's no need to implement this. It can already be done by doubling up the tile size and using the `zoomOffset` option, like:

```
var upscaled = L.tileLayer(
  'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
	  'attribution': 'Map data © <a href="http://openstreetmap.org">OpenStreetMap</a> contributors',
	  tileSize: 512,
	  zoomOffset: -1
}).addTo(map);
```

See https://plnkr.co/edit/LTnq4djAdV1UefuUwiLL?p=preview to see it live.

**Comment by mbirth** [comment]
Is there a way to show tiles the "retina" way until max zoom and then switch to upscaling automatically?

**Comment by cristan** [comment]
It works, but I don't like it: it also makes all text twice as small. A better solution would be to use [High resolution tiles](https://wiki.openstreetmap.org/wiki/High-resolution_tiles) which are actually rendered for a high res screen.

**Comment by NopMap** [comment]
Actually, it does not make text smaller, the doubling of the tiles size maintains the text size at double resolution.

High resolution tiles are a nice thing, of course, but providing those is a server side feature and out of scope for a map client like leaflet.
