### ISSUE TITLE
Some tiles not loading

### ISSUE THREAD

**Issue by Danielhiversen** [Leaflet/Leaflet#6188]
## How to reproduce

- Leaflet version I'm using: 1.3.1
- Browser (with version) I'm using: Chrome  67.0.3396.87
- OS/Platform (with version) I'm using: Mac
- step 1
Open https://plnkr.co/edit/bkf5Dd0TfTxN5gH8eLa7?p=preview
- step 2
Zoom in.

Not all the tiles are loaded, but shows as gray parts

## Minimal example reproducing the issue
https://plnkr.co/edit/bkf5Dd0TfTxN5gH8eLa7?p=preview

<img width="1606" alt="skjermbilde 2018-06-17 kl 15 34 03" src="https://user-images.githubusercontent.com/650502/41508370-04d7ee30-7244-11e8-8a9f-4b919755982c.png">

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by mourner** [comment]
Not reproducible for me — all the tiles are loading correctly. If they weren't, this was likely an issue on the WMS server side, not Leaflet.
