### ISSUE TITLE
retina @2x urls requested for stamen watercolor, that doesnt provide them

### ISSUE THREAD

**Issue by JLuc** [Leaflet/Leaflet#6193]
Leaflet's url sheme for stamen tiles has changed recently and now features `{r}` = the retina option : 
`url: 'https://stamen-tiles-{s}.a.ssl.fastly.net/{variant}/{z}/{x}/{y}{r}.{ext}',`

That's fine for some stamen layers, but watercolor doesnt provide any retina tiles (see https://github.com/stamen/maps.stamen.com/issues/56 ) When requested, the map appears empty.

The stamen watercolor provider should be described in such a way that it doesnt requests retina tiles (either with a dedicated option or as a separate provider ?)

**Comment by IvanSanchez** [comment]
I don't think that the core Leaflet repo has any references to the Stamen watercolor tiles. Maybe you meant to make this bug report in https://github.com/leaflet-extras/leaflet-providers ?

**Comment by JLuc** [comment]
ok

**Comment by JLuc** [comment]
See https://github.com/leaflet-extras/leaflet-providers/issues/283
