### ISSUE TITLE
retina not acurate

### ISSUE THREAD

**Issue by JLuc** [Leaflet/Leaflet#6195]
## How to reproduce

- Leaflet version I'm using: 1.3.1 but also on http://leaflet-extras.github.io/leaflet-providers/preview/
- Browser (with version) I'm using: Firefox 60.0.2 or Chromium  66.0.3359.181 
- OS/Platform (with version) I'm using: Ubuntu 17.10

## What behaviour I'm expecting and which behaviour I'm seeing

Documentation says "detectRetina : If true and user is on a retina display, it will request four tiles of half the specified size and a bigger zoom level in place of one to utilize the high resolution."

But it's not used to compute `L.Browser.retina` (true for browsers on a high-resolution "retina" screen.)
`var retina = (window.devicePixelRatio || (window.screen.deviceXDPI / window.screen.logicalXDPI)) > 1;`

On my screen, `window.devicePixelRatio` is 2 when browser display is zoomed to 200%
so `L.Browser.retina` is true as soon as display zoom is > 100% and false when browser zoom is < 100%

That is not what "retina" is meant to be.

## Minimal example reproducing the issue

- Open browser, zoom display to 150% (this is browser display, not map zoom)
- Browse to http://leaflet-extras.github.io/leaflet-providers/preview/
- Choose `Stamen toner` or another provider with retina tiles
- Open developer 's javascript console
- See the value for L.Browser.retina
- See the value for window.devicePixelRatio
- Open "Network" tab and see the uploaded tiles : they are @2x version
- Unzoom browser (dont unzoom the map, but the browser display, using its menu)
- See values...

Window has to be refreshed CTRL+F5 after browser display zoom has changed; so retina value is computed anew

**Comment by ghybs** [comment]
Hi,

You might confuse the Tile Layer [`detectRetina`](https://leafletjs.com/reference-1.3.0.html#tilelayer-detectretina) option and the `{r}` in Tile Layer [urlTemplate](https://leafletjs.com/reference-1.3.0.html#tilelayer-url-template) argument, which adds `@2x` when `L.Browser.retina` flag is `true`, as you have noticed.

While these 2 features target "retina" / high DPI devices (or when a user has increased their browser native zoom display as you noticed), they provide 2 different mechanisms (which can be combined, even though it might not be desirable):
- `detectRetina` is a simple workaround for tile sources that _do not_ offer the `@2x` alternative tiles. The drawback is that lines and text is also decreased. It is `false` by default, i.e. it does not play any role in http://leaflet-extras.github.io/leaflet-providers/preview/ examples.
- `{r}` in urlTemplate takes advantage of tile sources that _do_ offer the `@2x` alternative tiles, like Stamen in your case. If you pay close attention, Stamen toner and Stamen toner lite are almost the only one listed in http://leaflet-extras.github.io/leaflet-providers/preview/ that make use of this `{r}` feature, hence which offer these alternative tiles for high DPI devices.

Hope this helps.

**Comment by ghybs** [comment]
Hum if I understand correctly, this probably follows your issue https://github.com/Leaflet/Leaflet/issues/6193.
What do you mean by "_That is not what "retina" is meant to be._"?

**Comment by JLuc** [comment]
#6193 has been fixed with  https://github.com/leaflet-extras/leaflet-providers/commit/975977fe0146b4c84ecb861c2d848aa01ef254aa

BUT there there is an issue with L.Browser.retina since my screen is not retina and retina tiles should never have been requested.

As the documentation states it, L.Browser.retina is supposed to reflect a high-resolution "retina" screen 
but AMOF it doesnt : it only reflects when the browser display zoom > 100%. 

i suggest to reopen this issue

Did you try the reproduce-steps ?

**Comment by ghybs** [comment]
The steps and result you describe are the expected behaviour.

Although the flag is called "retina", it targets high DPI, and the case of a natively zoomed browser window is also considered in that category. Now this may be argued upon, but it seems to me that this is for a reason and it does not harm much in any case: why do you absolutely want not to load @2x tiles when your browser window is zoomed? That provides with crisper graphics, instead of blurry zoomed images.

**Comment by JLuc** [comment]
Ok I understand. You're right about avoiding blurry images.

What now might be improved is the wording and the explanation : both "retina screen" and "high DPI" (dot per inch = screen property) are not fit to describe what L.Browser.retina realy is.

I propose https://github.com/Leaflet/Leaflet/pull/6203
