### ISSUE TITLE
Update polygon color in real time via a server side script(NodeJS).

### ISSUE THREAD

**Issue by EdwardDeaver** [Leaflet/Leaflet#6204]
I have an server application that has 5000 web socket connections and those are all tied to polygons on a map in name only right now. 

I can create a few ws connection client side and have leaflet working great changing the map polygons according the ws messages. 

Why am I looking for server side solutions? Chrome does not allow 5000 ws connections client side. 

From what I've read it doesn't seem like you can do it. 

Is there any documented way to modify leaflet elements server side in real time? 

Edit: I don't see how to assign a label to this issue, but I'd put it under "Help Wanted".

**Comment by IvanSanchez** [comment]
Pal, assign a unique ID to each polygon and use just WS.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
