### ISSUE TITLE
Memory leak on leaflet server-side

### ISSUE THREAD

**Issue by eommer** [Leaflet/Leaflet#6209]
## How to reproduce

- Leaflet version I'm using: 1.3.1
- Browser (with version) I'm using: None (NodeJS Server-side app with JSDOM and node-canvas)
- OS/Platform (with version) I'm using: Ubuntu 14.04 (heroku Cedar-14)
- step 1 : Open the app on Glitch
- step 2 : Click on "Logs" button on the left of the Glitch project page to show the console
- step 3 : Wait that multiple processes ended to see the memory leak that seems to happened

## What behaviour I'm expecting and which behaviour I'm seeing

- Hi, I setted up a batch on my Heroku server to generate some images of leaflet maps. The program works fine but I noticed that the memory of my Heroku server is increasing rapidly.
-----------
- Expected behavior: The map and the DOM container should be remove after each image generation and the memory should be free.
-----------
- Actual behavior: The memory is not completely free after each image generation. The issue force me to restart the server one or several times a day.
-----------
- PS : I tried to create a unique leaflet map and just remove every layers and reset each of them for each image generation. But it seems that removeLayer still doesn't completely free the memory and the problem is still here (even if the memory use increase less quicker with this manner to do).
I'm pretty sure that the problem doesn't come from the image creation (leaflet-image) because I tried to set it in comment and the issue still remains.

## Minimal example reproducing the issue

- [x] this example is as simple as possible
- [ ] this example does not rely on any third party code

Link to the example : https://glitch.com/edit/#!/snow-sofa?path=server.js

![alt text](https://image.noelshack.com/fichiers/2018/26/3/1530098346-capture-d-ecran-2018-06-27-a-13-18-46.png "Memory leak Heroku")

* The memory use which is displayed on my example seems to be unstable but I think we can see that it increase.

**Comment by IvanSanchez** [comment]
I'm tempted to say this is a duplicate of https://github.com/Leaflet/Leaflet/issues/5774 - that's the only memory leak we're aware of at the moment. Focusing the efforts there should show improvements in your headless environment.

**Comment by eommer** [comment]
Thanks for your quick response. I indeed tried most of the solutions post on this issue but none of them seemed to prevent the memory leak I have.

**Comment by eommer** [comment]
It seems that the leak is coming from the map.setSize(height, width) method of leaflet-headless. When I was using a unique map for all my paths but I was still resizing the size for each element. The memory leak disapear when I set the size of the map once, at the initialization of the map.

So, it's not an issue with leaflet but with the headless plugin i'm using.
