### ISSUE TITLE
L.tileLayer.wms   passing a colors parameter prevents layer from displaying

### ISSUE THREAD

**Issue by MappingSupport** [Leaflet/Leaflet#6210]
## How to reproduce
I am using a WMS server that understands special  parameters named **size, symbols and colors**.  I can pass the size and symbols parameters OK but passing colors parameter causes the layer to not display.

This example does not have the colors parameter and works fine.  The triangles are satellite hotspots used for fire detection.
[https://mappingsupport.com/leaflet/bugs/leaflet_wms_no_colors.html](https://mappingsupport.com/leaflet/bugs/leaflet_wms_no_colors.html)

This example shows the problem.
I added a **colors:** parameter to the WMS call.  This example does not display the WMS layer.
[https://mappingsupport.com/leaflet/bugs/leaflet_wms_with_colors.html](https://mappingsupport.com/leaflet/bugs/leaflet_wms_with_colors.html)

- Leaflet version I'm using: 1.3.1
- Browser (with version) I'm using: Firefox 61.0
- OS/Platform (with version) I'm using: Windows 10

I am another Google map API dev converting to Leaflet.  Passing the 'colors' parameter to this WMS server works fine in my Google map.

**Comment by IvanSanchez** [comment]
This is not a bug, it's a feature.

What's going on here is that the *value* of your `colors` parameter contains plus signs, and Leaflet runs `encodeURIComponent` on them, replacing your string `255+165+0` into `255%2B165%2B0`, **as expected**.

Now, the WMS server is returning an error, which reads "Parameter (color) expects 3 values.".

Also, a `+` is the URI-encoding of a space character. So what's going on here is that the WMS server expects a `colors` parameter like `255 165 0`, that can be URI-encoded as both `255+165+0` and `255%20165%200` (check http://tools.ietf.org/html/rfc3986 for detailed info). You probably copy-pasted code from a library that doesn't URI-encode WMS parameters, Leaflet is a tiny bit overzealous about that, and you end up URI-encoding the `255 165 0` string *twice*.

Just use `colors: '255 165 0'` and you'll be fine.

Other than amending the API documentation where it reads " they will be sent to the WMS server as extra parameters in each request URL." to add that each parameter is run through `encodeURIComponent()` (feel free to send a PR about that!), there is no action to be taken here.

**Comment by IvanSanchez** [comment]
@MappingSupport I can also see in https://firms.modaps.eosdis.nasa.gov/web-services/ that NASA's documentation explicitly mentions `+` signs, and this is wrong. I encourage you to get in touch with the people responsible for that WMS service and point them to this bug report, so they can be aware of the URI-encoding of their parameter and amend **their** documentation.

**Comment by IvanSanchez** [comment]
Also, note how the raw WMS URLs `https://firms.modaps.eosdis.nasa.gov/wms/?...colors=255%20165%200&...` and `https://firms.modaps.eosdis.nasa.gov/wms/?...colors=255+165+0&...` produce the same result.

**Comment by MappingSupport** [comment]
Ivan - Thanks!
colors: '255 165 0' works perfect.

Today is my first day with Leaflet and you have given me a warm reception.

**Comment by MappingSupport** [comment]
I pinged NASA and they have already tweaked their documentation.

**Comment by IvanSanchez** [comment]
@MappingSupport Cool :+1:
