### ISSUE TITLE
Duplicate events when clicking polyline on map

### ISSUE THREAD

**Issue by NopMap** [Leaflet/Leaflet#6213]
## How to reproduce

- Leaflet version I'm using: 1.3.1
- Browser (with version) I'm using: Firefox 60.0.2
- OS/Platform (with version) I'm using: Windows 7 x64
- Create a map and add an interactive polyline
- Click on the polyline

## What behaviour I'm expecting and which behaviour I'm seeing

Expected:
- click event on polyline is fired

Observed:
- click event on polyline is fired
- click event on map canvas is also fired

Notes:
- Leaflet 0.7.3 in Firefox 60.0.2 works as expected
- Always reproducible and reported to me by users of my website

## Minimal example reproducing the issue

Can't get jsfiddle to work, will follow up with example.
Real-life use case is the route editor on www.wanderreitkarte.de. Clicking on a line will both split the line (polyline action) and add a new and invalid line to the clicked location (map canvas action).

**Comment by IvanSanchez** [comment]
This is behaviour as expected. Any events fired on a vector path will propagate up to its renderer, and also to the map.

If this is annoying, then use `L.DomEvent.stopPropagation()` and the like.

**Comment by NopMap** [comment]
How can this be an intended behaviour if it worked differently in 0.7 and 0.7.3? Was there an intentional, breaking change of behaviour here?

**Comment by NopMap** [comment]
That might have any number of unwanted effects. Reverted to the last known working version.

**Comment by NopMap** [comment]
Btw: Closing issues immediately before a discussion has happened let alone is complete looks a lot like you want to suppress discussions... :-(

**Comment by barbalex** [comment]
Same problem here: Somehow onClick is triggered twice (maybe because a Layer is loaded?). Which in some cases leads to the second event returning wrong latLng!!! (the first event returns the correct ones).

So I tried to call `L.DomEvent.stopPropagation()`. Event though inspection on step before stopping propagation reveals `L.DomEvent.stopPropagation` exists I get an error message:
```
leaflet-src.js:2740 Uncaught (in promise) TypeError: Cannot read property 'stopPropagation' of undefined
    at Object.stopPropagation (leaflet-src.js:2740)
    at NewClass.onDblclick (index.js:378)
    at NewClass.fire (leaflet-src.js:593)
    at NewClass._fireDOMEvent (leaflet-src.js:4373)
    at NewClass._handleDOMEvent (leaflet-src.js:4330)
    at HTMLDivElement.handler (leaflet-src.js:2653)
```

**Comment by barbalex** [comment]
Got it: You need to pass in the event like this: `L.DomEvent.stopPropagation(event)`
