### ISSUE TITLE
Feature Request: `move` event for layers after setLatLngs()

### ISSUE THREAD

**Issue by codeofsumit** [Leaflet/Leaflet#6214]
As a [plugin](https://leafletpm.now.sh) author I need a way to react to layer changes triggered via `setLatLngs()`. The Marker class has a `move` event for this. While I don't necessarily need a `move` event for layers, I would like _some_ event that is triggered when `setLatLngs()` is used (`move` or anything else that makes sense).

Example usecase: 
My plugin puts markers on a layers vertexes. If the user manually updates the layer coordinates via `setLatLngs()` I can't reposition the markers as there is no event to catch this.

The result is this:
![image](https://user-images.githubusercontent.com/2399810/42181040-bb68cc0e-7e39-11e8-8908-9c226b967d01.png)

For Reference: this was raised as a bug [here](https://github.com/codeofsumit/leaflet.pm/issues/308). To resolve this I'd an event to listen to.

**Comment by cherniavskii** [comment]
Hi,
I've found a really old issue, which seems to describe same problem:
https://github.com/Leaflet/Leaflet/issues/2235

Can you confirm that adding `change` event will solve your issue?

**Comment by codeofsumit** [comment]
yes, confirmed 👍

**Comment by cherniavskii** [comment]
@codeofsumit would you like to submit a PR?

**Comment by codeofsumit** [comment]
@cherniavskii I would love to - never messed with the leaflet codebase so it might take a bit though 🤞
Hope to find time this week to start

**Comment by cherniavskii** [comment]
Closing in favour of #2235
