### ISSUE TITLE
longitude latitude precision with more than 5 decimals

### ISSUE THREAD

**Issue by JoostdeBos** [Leaflet/Leaflet#6216]
I have an array with dataobjects and longitude and latitude, with 8 decimals.
But leaflet is rounding all values to 5 decimals, is it possible to use more decimals in leaflet?

https://stackoverflow.com/questions/15965166/what-is-the-maximum-length-of-latitude-and-longitude

	L.marker([52.291945138888885, 4.713058333333334]).addTo(mymap);
	L.marker([52.29194560185185, 4.713057561728395]).addTo(mymap);
	L.marker([52.29194591049382, 4.713060725308642]).addTo(mymap);
	
	
	L.marker([52.292785108024695, 4.716113966049383]).addTo(mymap);
	L.marker([52.292785339506175, 4.716113966049383]).addTo(mymap);
	
	L.marker([52.29305632716049, 4.715002083333333]).addTo(mymap);
	L.marker([52.29305655864197, 4.715002314814814]).addTo(mymap);
	
	L.marker([52.29333503086419, 4.715283179012346]).addTo(mymap);
	L.marker([52.29333503086419, 4.715281018518518]).addTo(mymap);

displayed as 4 markers with same location:

Should be 9 markers with slighty differences!

**Comment by ghybs** [comment]
Hi,

The coordinates you share have less than a meter difference:
https://plnkr.co/edit/tv56zDvhdPe6WIXGppxt?p=preview
(open your console to see the actual distance in meter)

> But leaflet is rounding all values to 5 decimals

it **is not**.

> displayed as 4 markers with same location

Leaflet _does_ display all 9 of them, but if you do not zoom in enough, they just overlap.
In the above demo, I have set the map [`maxZoom`](https://leafletjs.com/reference-1.3.0.html#map-maxzoom) option to 30 to let you zoom in further.

Note that most Tile Servers will stop rendering above zoom 18 or 20.

And the default EPSG3857 CRS might not be very appropriate for sub-meter precision.
See also https://github.com/Leaflet/Leaflet/issues/4675 and https://github.com/Leaflet/Leaflet/issues/5932#issuecomment-346046996.

**Comment by munrocket** [comment]
Hi, @ghybs I think you will find usefull double.js library for extended precision. It's extreamly fast.
