### ISSUE TITLE
Adding mousemove handler on marker causes map mousemove event to report marker latlng instead of mouse latlng 

### ISSUE THREAD

**Issue by ZhangYiJiang** [Leaflet/Leaflet#6217]
## How to reproduce

- Leaflet version I'm using: 1.3.1 (latest) 
- Browser (with version) I'm using: Firefox 60 latest 
- OS/Platform (with version) I'm using: Ubuntu 16.04 

Steps:

1. Visit https://jsfiddle.net/s42ort36/14/
2. Mouse over the marker on the left - note the latlng equals to latlng of the location of the mouse 
3. Mouse over the marker on the right - note the latlng changes to the marker's latlng and stays that way until the mouse is outside the marker   

Code: 

``` js 
const mymap = L.map('mapid')
  .on('mousemove', (e) => {
    document.getElementById('latlng').textContent = JSON.stringify(e.latlng, null, 2);
  })
  .setView([51.505, -0.09], 13);

const markerA = L.marker([51.5, -0.09])
  .on('mousemove', () => {
  	// Dummy event handler - does nothing
      // BUG: Adding this event handler causes the map's mouseover event 
      // to report this marker's latlng instead of the mouse's latlng
  })
  .addTo(mymap);
  
const markerB = L.marker([51.5, -0.098])
  .addTo(mymap);
``` 

## What behaviour I'm expecting and which behaviour I'm seeing

Expected behavior: map's mouseover `event.latlng` should not refer to different things depending on whether the marker the mouse is over has its own mouseover handler 

This seems to be caused by https://github.com/Leaflet/Leaflet/blob/8c3eaaf3e8f4a532cdff122f7eb9e9db3bab7aed/src/map/Map.js#L1368 taking the first target and https://github.com/Leaflet/Leaflet/blob/8c3eaaf3e8f4a532cdff122f7eb9e9db3bab7aed/src/map/Map.js#L1378 adding a special check for Marker objects 

## Minimal example reproducing the issue

- [X] this example is as simple as possible
- [X] this example does not rely on any third party code

Using http://leafletjs.com/edit.html or any other jsfiddle-like site.

**Comment by threat123** [comment]
This annoying behavior still exists in version 1.7.1

**Comment by johnd0e** [comment]
`mousemove` is not listed as supported events for markers in docs:
https://leafletjs.com/reference-1.7.1.html#interactive-layer-mousedown

So no surprise that it results in undefined behavior.

Question is how do you actually use `mousemove` for markers?

**Comment by johnd0e** [comment]
Closed due to lack of feedback.
