### ISSUE TITLE
Horizontal lines in popup when scrolling is activated

### ISSUE THREAD

**Issue by cccruzr** [Leaflet/Leaflet#6218]
## How to reproduce

- Leaflet version I'm using: 1.3.1
- Browser (with version) I'm using: Firefox 61 / Chrome 64
- OS/Platform (with version) I'm using: Windows 10

## What behaviour I'm expecting and which behaviour I'm seeing
I'm not really sure if this is a bug of Leaflet CSS, that's why I'm asking...

Since I'm trying to code "mobile-first", I made my popup scrollable with:

`layer.bindPopup(popupLayout, {
                    maxWidth: 300,
                    maxHeight: 400,
                    closeOnClick: true
});`

However when the content is large, I'm getting the following horizontal lines:

[![enter image description here][1]][1]

Compared with a normal non-scrollable popup:

[![enter image description here][2]][2]

Any idea on how to get rid of those ugly lines?

  [1]: https://i.stack.imgur.com/P0tGw.jpg
  [2]: https://i.stack.imgur.com/hy1yg.jpg

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?

**Comment by cccruzr** [comment]
This is the [webmap](https://cccruzr.github.io/LideresSociales/)
Here you can find the [code of the map](https://github.com/cccruzr/LideresSociales/blob/master/docs/js/d3_map.js#L73)

Thanks for your help!

**Comment by Malvoz** [comment]
The lines you're seeing are borders:

https://github.com/Leaflet/Leaflet/blob/2a60e29ad6f5b11b3ce6be90c34c8f1910a88804/dist/leaflet.css#L538-L542

We should consider removing them.

**Comment by Malvoz** [comment]
> Any idea on how to get rid of those ugly lines?

@cccruzr add the following to your CSS:

```css
.leaflet-popup-scrolled {
  border: 0;
}
```
