### ISSUE TITLE
How to customize the popup close function?

### ISSUE THREAD

**Issue by GravityMsc** [Leaflet/Leaflet#6220]
## How to reproduce

- Leaflet version I'm using:1.3.1
- Browser (with version) I'm using:latest Chrome
- OS/Platform (with version) I'm using:windows 10
- step 1: Click marker, then open the popup and set a new marker style.
- step 2: Close that popup, I need to set a new marker style again.

## What behaviour I'm expecting and which behaviour I'm seeing
I'm new for this awesome lib and I have tried to find the method in its doc but failed.
I wonder whether it has an access to customize the popup close function, when I close the opend popup and set a new marker style.
## Minimal example reproducing the issue

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code
I think this issue doesn't need jsfiddle.
```
L.marker(latLon, { icon: new DefaultIcon() })
        .addTo(this.map)
        .bindPopup('markerPopupContent')
        .on('click', (e) => {
          e.target.setIcon(new ClickedIcon());
          e.target.openPopup();
        });
```
Using http://leafletjs.com/edit.html or any other jsfiddle-like site.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
