### ISSUE TITLE
judge whether a moving point is on a line

### ISSUE THREAD

**Issue by Lucahan** [Leaflet/Leaflet#6223]
I am now using Leaflet.MovingMarker，and i want to know when the marker is moving，how to judge it whether on a given polyline.

**Comment by cherniavskii** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
