### ISSUE TITLE
Navigating using keyboard causes overflowing parent to scroll along.

### ISSUE THREAD

**Issue by Malvoz** [Leaflet/Leaflet#6229]
## How to reproduce

1. Go to https://leafletjs.com/
2. Tab until the map recieves focus, pan down using the arrow key.
3. Observe how the parent element (`<body>` in this case) which has an overflow (on the Y-axis) scrolls along until the map is no longer in view.

## What behaviour I'm expecting and which behaviour I'm seeing

As I failed to find any intructions on basic navigation for keyboard-only users I would assume just pressing any of up/right/down/left key on the keyboard would allow me to navigate the map and cause no issues. 

However as I press the down key the overflowing parent scrolls aswell, which leads to a bad user experience. I noticed holding `shift` while pressing any arrow key I got the desired effect. Is this the preferred method of navigating the map using only keyboard?

This is a major accessibility concern and I would consider this a bug, are there any reasons using only the arrow keys would not have the same behavior as when also holding `shift`?

**Comment by cherniavskii** [comment]
Hi,
Thanks for raising this issue, it's a bug indeed!
