### ISSUE TITLE
ReferenceError: L is not defined adter upgrading to 1.3.2

### ISSUE THREAD

**Issue by petrot** [Leaflet/Leaflet#6238]
- Leaflet version I'm using: 1.3.2
- Browser (with version) I'm using: Chrome  67.0.3396.99
- OS/Platform (with version) I'm using: OSX

I have a working Angular/Ionic app with leaflet map. After upgrading from 1.3.1 to 1.3.2, I got this error.

**Comment by cherniavskii** [comment]
Huh, that's weird :/
Code looks fine here: https://unpkg.com/leaflet@1.3.2/dist/leaflet-src.js
Also, https://leafletjs.com uses leaflet@1.3.2 and it works.

Could you create and example?
Maybe it's related to Ionic?

**Comment by LouisMazel** [comment]
Hi,
Same bug with VueJs (2.x) App

**Comment by petrot** [comment]
I found, that MarkerCluster has the problem:

working clusters with 1.0.2: https://jsfiddle.net/petrot81/wdcrof2m/

fails with 1.3.2: https://jsfiddle.net/petrot81/zg3Lxyow/

**Comment by cherniavskii** [comment]
@petrot 

You are passing wrong integrity hash.
New hash for 1.3.2 is `sha512-0flgjCHSUHlf04m3KVuWvgVFS9aDNe64Nb1jON/7buKd1FDIyBypqAByD8vpA5G9zwAD7jMfltDSnYGBBCPC5w==`, you're probably using integrity has from older version

**Comment by cherniavskii** [comment]
Can you confirm it works with new integrity hash?

**Comment by petrot** [comment]
@cherniavskii I've just updated the source, but the css fails.

**Comment by cherniavskii** [comment]
@petrot css also needs to use proper integrity hash.

But...

Looks like the real issue is that bundlers now use `pkg.module` (added in #6020), and there's no window.L global assign.
I'm investigating the issue

**Comment by jgeiger-cr** [comment]
I'm also getting "L is not defined" with 1.3.2 from npm

**Comment by dh3wr** [comment]
+1

**Comment by WilliamDASILVA** [comment]
Having the same issue `L being undefined`.
We had the following error on our side:
```
node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js 16:25 Uncaught ReferenceError: L is not defined
```

And after some searches, I saw the new Leaflet version on npm.
We previously had on our package.json:
```json
"leaflet": "^1.3.1",
"leaflet.markercluster": "^1.3.0",
```

We fixed our version to `1.3.1` in our package.json in the meantime, since it worked as expected with that version.

**Comment by callumacrae** [comment]
We're having the same issue. Fixing to 1.3.1 and it works again.

Using from npm.

**Comment by arnaupc** [comment]
+1

**Comment by mourner** [comment]
Hey everyone, we're working on a solution — please stay tuned! See #6239 for discussion.

**Comment by cherniavskii** [comment]
Leaflet 1.3.3 is already available!
https://leafletjs.com/2018/07/18/leaflet-1.3.3.html

Thanks for a fast feedback!
