### ISSUE TITLE
Leaflet circle resize vertex are not moving when updating circle center

### ISSUE THREAD

**Issue by Harpreet90** [Leaflet/Leaflet#6244]
## How to reproduce

- Leaflet version I'm using: Leaflet.draw 1.0.2,
- Browser (with version) I'm using: Chrome - Version 62.0.3202.75 (Official Build) (64-bit)

- OS/Platform (with version) I'm using: Ubuntu 16.04
Create a circle on map using for e.g:
 circle = new L.Circle([lat, lon], {
                                radius: radiusMap,
                                weight: 2,
                                fillColor: "#ff6600",
                                fillOpacity: 0.5,
                                opacity: 1,
                                color: "#000000",
                                editable: true,
                            }).addTo(map);
2.Now, you want to move circle based on marker new lat lng position. for e.g below code
 marker.on("move", function () {    
 circle.setLatLng(marker.getLatLng());   
  }.bind(this));

3. Circle has updated center but it does not move edit vertex along with center. They remain at old position. Please see below screenshot.

Also If you try to remove circle using circle.remove(), it does not work properly.Always throws error "can not read property length of null"

![1](https://user-images.githubusercontent.com/15616542/42945250-81c968e2-8b85-11e8-924b-d106aeeb7964.png)

## What behaviour I'm expecting and which behaviour I'm seeing
Circle edit vertex should be updated as per new center.

## Minimal example reproducing the issue

- [ x] this example is as simple as possible
- [ x] this example does not rely on any third party code

Using http://leafletjs.com/edit.html or any other jsfiddle-like site.

**Comment by ghybs** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features of Leaflet **core**.

For bugs related to plugins, please refer to their respective repo and issue tracker.
In the case of Leaflet.draw: https://github.com/Leaflet/Leaflet.draw

**Comment by froemken** [comment]
@Harpreet90 

After calling `setLatLng()` you will only update the center `LatLng` of the circle, but not the vertex of the outer circle. If you call `reset()` just the center vertex will be moved, too, but the outer vertex is still at old position. I cost me nearly two hours to solve that, and here is the solution:

```
marker.setLatLng([lat, lng]);
marker.editor.updateResizeLatLng();
marker.editor.reset();
```

1. Update internal LatLng for center and move just the circle to new position
2. Re-Calculate the new position of the outer vertex and update LatLng internally
3. Start redrawing all vertexes based on the updated internal LatLngs

Stefan
