### ISSUE TITLE
Bugfix #6025 introduces exception in GridLayer._tileReady - a parameter check is missing

### ISSUE THREAD

**Issue by devinfluencer** [Leaflet/Leaflet#6245]
Leaflet 1.3.2/1.3.3 has a fix that does not check a parameter for null/undefined and crashes in my scenario because GridLayer._tileReady(coords, err, tile) gets called with tile = null.

By fix [#6025](https://github.com/Leaflet/Leaflet/pull/6025) GridLayer.js line 845 is changed to:
`if (!this._map || tile.getAttribute('src') === Util.emptyImageUrl) { return; }`
but tile is not checked.
I propose fixing this by
`if (!this._map || (tile && tile.getAttribute('src') === Util.emptyImageUrl)) { return; }`

I fear I can't give a fiddle because I have a complicated scenario involving a subclassed leaflet.vectorgrid. The code worked fine with Leaflet 1.3.1 that didn't have the second condition in the if statement.

**Comment by mo-ian-watkins** [comment]
I concur with this, same situation, running Leaflet 1.3.3 with Leaflet.VectorGrid.

Works fine in 1.3.1 and 1.2.0

**Comment by nikolauskrismer** [comment]
Same problem here in combination with the leaflet plugin "Leaflet.TileLayer.PouchDBCached"

**Comment by ashleysommer** [comment]
Any idea if there will be a release soon incorporating this fix?

**Comment by alex2wong** [comment]
Finally find this.. expect for next release.

**Comment by cherniavskii** [comment]
Leaflet 1.3.4 is out! :rocket: 
https://github.com/Leaflet/Leaflet/releases/tag/v1.3.4
