### ISSUE TITLE
How to determine that the point is in the polygon?

### ISSUE THREAD

**Issue by krogal1985** [Leaflet/Leaflet#6251]
How to determine that the point is in the polygon?

**Comment by IvanSanchez** [comment]
https://github.com/mapbox/leaflet-pip and http://turfjs.org/docs/

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
