### ISSUE TITLE
CSS with `img { max-width: 100%; }` breaks rendering in custom panes

### ISSUE THREAD

**Issue by jerekshoe** [Leaflet/Leaflet#6253]
## How to reproduce

- Leaflet version I'm using: 1.3.3
- Browser (with version) I'm using: Chrome 68
- OS/Platform (with version) I'm using: Ubuntu 16.04
- 1. Create custom pane
- 2. Add TileLayer to custom pane
- 3. Add img { max-width: 100% } to CSS

## What behaviour I'm expecting and which behaviour I'm seeing
Expected: I expect the map to rendered like it is when adding the TileLayer without specifying a pane.
Actual: Layer is not visible because all img tags have max-width: 100%.

## Minimal example reproducing the issue

- [X] this example is as simple as possible
- [X] this example does not rely on any third party code  

[codepen](https://codepen.io/anon/pen/bjodBg)

This is basically the same issue as #5775, however with custom panes.
I'm using a third party vendor that uses the above CSS. 
I've seen in the leaflet.css file that there are safeguards intended to correct the behavior 
that I am seeing, however this only applies to <img> in default panes, but does nothing for <img> in custom panes.

**Comment by IvanSanchez** [comment]
I think this could be worked around by adding one more selector to the rule at https://github.com/Leaflet/Leaflet/blob/87ebb534c9c0e910adf4efcb630ee22f0f3f996d/dist/leaflet.css#L43

Kinda

```
.leaflet-container .leaflet-tile {
    max-width: none !important;
    max-height: none !important;
}
```

Could you please test that out, and make a pull req for it?
