### ISSUE TITLE
maxNativeZoom can cause flickering

### ISSUE THREAD

**Issue by happicow** [Leaflet/Leaflet#6259]
Hello,

I am finding that if you have two map layers (with different zIndexes) and one of them has maxNativeZoom set to the same value as it's maxZoom, the map will flicker between the two layers when panning.

Here is an example of the problem.  All you need to do is pan the map left and right and you will see the layers flicker:

https://codepen.io/happicow/pen/WKXazR

Mitigation techniques:
- If you remove the maxNativeZoom value the issue resolves.
- If you set maxNativeZoom to a value greater than maxZoom (6 for example) the issue resolves.
- If you downgrade to Leaflet v1.0.0 the issue resolves.  (v1.0.3 seems to be when this bug appeared)

This has been tested on the latest versions of Firefox, Chrome and Safari on both Windows and MacOS with the same results.

Thanks.

**Comment by IvanSanchez** [comment]
Actually, you don't need to `TileLayer`s to reproduce the problem. If I remove the OSM tile layer from your example, the bug still reproduces.

I think that this might be a regression from https://github.com/Leaflet/Leaflet/commit/3c3f23f33918f6105d354bf0261586cce05036e6 , as this doesn't take into account an edge case that you point out:

> If you set maxNativeZoom to a value greater than maxZoom (6 for example) the issue resolves.

I suggest making the checks for `maxNativeZoom` before clamping the zoomlevel - in other words, pushing this line

https://github.com/Leaflet/Leaflet/blob/f55170cc51a2ee2e90c99534ce091022c950b464/src/layer/tile/GridLayer.js#L547

into an `else` branch of the `if` conditional that's a couple of lines below that. That should check for `maxZoom` *first*, and *then* clamp the zoom according to `min`/`maxNativeZoom`.

Pull reqs welcome :smile: Remember to run the automated tests, and to actually test your code against this bug report and against https://github.com/Leaflet/Leaflet/issues/3814 (to prevent any further regressions)

**Comment by mjguru** [comment]
I am trying to fix this using #6263 but I believe I haven't quite got it. Can you give me more pointers? Also, I am having trouble testing it locally.

**Comment by Sumbera** [comment]
have the same problem with wms layers and continuous zoom , however I haven't used native maxNativeZoom, only maxZoom and minZoom. And I can reproduce it on 1.0.0. version too.

**Comment by Sumbera** [comment]
@robertbernardbrown  thanks for your fix ! works well on my side ! I can remove my local dirty patch :) hope it will be soon on the main branch.
