### ISSUE TITLE
Tutorial: explicitly note attribution

### ISSUE THREAD

**Issue by pietervdvn** [Leaflet/Leaflet#6260]
Hello,

I noticed that people new to OSM and needing a map often follow the leaflet tutorial, but remove the attribution from the map because it is 'an unwanted advertisement' or 'visual noise'. It would help that [the quick-start](https://leafletjs.com/examples/quick-start/) would explicitly note the obligation to have attribution.

This could for example be done with an extra paragraph in *setting up the map*, such as

> Keep in mind that, when using anything based on OpenStreetMap, an attribution is obligatory as per the [copyright notice](https://www.openstreetmap.org/copyright). Most other tile providers, such as [MapBox](https://www.mapbox.com/help/how-attribution-works/), [Stamen](http://maps.stamen.com/) or [Thunderforest](https://www.thunderforest.com/terms/), require you to attribute them too, together with the OpenStreetMap attribution. Make sure to give credit where credit is due.

**Comment by IvanSanchez** [comment]
That would be https://github.com/Leaflet/Leaflet/blob/master/docs/examples/quick-start/index.md , around line 64. Pull reqs are welcome!

**Comment by pietervdvn** [comment]
Aha, that's where I can find the guide. I looked around but didn't find it, hence the issue. Pull request incoming in five minutes!

**Comment by pietervdvn** [comment]
See https://github.com/Leaflet/Leaflet/pull/6261

I'm closing this issue, as the PR supersedes this.
