### ISSUE TITLE
Map not shown in Safari

### ISSUE THREAD

**Issue by sharess** [Leaflet/Leaflet#6262]
Simple notice, 
changing the dimensions map div, any layer painted on map disappear. 
Only on  Safari browser.
No error is signed on console.
There is a mode devolp to solve or is a bug ?
Thanks
Franz

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?

**Comment by sharess** [comment]
https://plnkr.co/edit/8l7RFGlGpozDLalW0DWY?p=preview

Go in Fullscreen then return in small window and clusters disappear.

Thanks a lot
Fra

**Comment by ghybs** [comment]
Cross posted on SO: https://stackoverflow.com/questions/51776716/leaflet-fullscreen-clustermarker-disappear

Your Plunker works fine for me on Safari 11.1.2 (macOS 10.13.6)

**Comment by ghybs** [comment]
Closing due to inability to reproduce the issue and lack of activity.

**Comment by idubinets** [comment]
I am facing the same issue now. what information I can share to help to fix it?

**Comment by ghybs** [comment]
Hi @idubinets,

Please open a new issue, you will have issue template with required fields.

Thank you!

**Comment by Gouet** [comment]
Have the same issue.

**Comment by Falke-Design** [comment]
@Gouet can you please describe what are you doing and create a sample www.leafletjs.com/edit.html - We need both else we can't help you

**Comment by Gouet** [comment]
Ok I have found why it didn't work FOR ME.

I was using calc in my css for the height.

I was doing that :
`height: calc(100% - 60px);`

The solution was :
`height: calc(100vh - 60px);`

Don't know if it helps but I put my solution here.

**Comment by ibrahimkholil** [comment]
leaflet map is not showing in safari with elementor
