### ISSUE TITLE
"The page can't load Google maps correctly" 

### ISSUE THREAD

**Issue by Jacquilin** [Leaflet/Leaflet#6265]
When I tried to load google map using Leaflet,the above mentioned error  message was displayed.
How can I detect the error event from my script file??
I read the documentation.But couldn't find any way??

Please help.
- Leaflet version I'm using:       0.7.7
- Browser (with version) I'm using:Chrome 58
- OS/Platform (with version) I'm using: Ubuntu 16

**Comment by IvanSanchez** [comment]
Are you using just Leaflet, or some plugin to load Google Maps stuff?

**Comment by Jacquilin** [comment]
I am using the plugin 'angular-leaflet-directive' along with  'Leaflet ' 0.7.7

**Comment by Jacquilin** [comment]
Actually I want to use L.Util to detect the error event that is occurring i.e; the google maps loading  is failing because of api's error response.

**Comment by matkoniecz** [comment]
Can you publish a fiddle/codepen/plunkr that displays this behaviour?

**Comment by IvanSanchez** [comment]
No more information has been provided, and more than a few weeks have passed. We'll assume this issue is no longer relevant and/or there is no interest to make a better report.
