### ISSUE TITLE
consider listing openstreetmap.org in "Trusted by the best"

### ISSUE THREAD

**Issue by matkoniecz** [Leaflet/Leaflet#6271]
## How to reproduce

- Leaflet version I'm using: trunk
- Browser (with version) I'm using: not applicable
- OS/Platform (with version) I'm using: not applicable 
- step 1 see https://github.com/Leaflet/Leaflet/blob/master/docs/index.html#L39
- step 2 ctrl-f for openstreetmap

## What behaviour I'm expecting and which behaviour I'm seeing

I would expect openstreetmap.org to be listed (note, I am highly biased)

## Minimal example reproducing the issue
not applicable

**Comment by ghybs** [comment]
Closed by #6360
