### ISSUE TITLE
Zoom Level Accuracy

### ISSUE THREAD

**Issue by NicoNovi** [Leaflet/Leaflet#6273]
I'm analysing GPS location data derived from a 'clickable' online map used by the public to register sightings of a type of shark.

Unfortunately users were able to log locations regardless of zoom level which has resulted in some questionable results; and, as far as I can tell, there is no reliable way of telling which data points are inaccurate.

I have noted that many of the questionable longitudinal coordinates end in '02' or '04', which I gather refer to the corresponding map tiles but beyond that I'm at a loss.

Is anyone aware of the issue and, if so, how I might differentiate between good (accurate, zoomed in) and bad (unreliable, zoomed waaayyy out) coordinates? Or put another way, is there any way of knowing the zoom level at which each datapoint was created?

## How to reproduce

- Leaflet version I'm using:
- Browser (with version) I'm using:
- OS/Platform (with version) I'm using:
- step 1
- step 2

## Minimal example reproducing the issue

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

Using http://leafletjs.com/edit.html or any other jsfiddle-like site.

**Comment by IvanSanchez** [comment]
> I have noted that many of the questionable longitudinal coordinates end in '02' or '04', which I gather refer to the corresponding map tiles but beyond that I'm at a loss.

Or they might rather be artifacts due to floating point arithmetic.

> Or put another way, is there any way of knowing the zoom level at which each datapoint was created?

By storing the zoom level the user was at when they clicked on the map, d'oh.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
