### ISSUE TITLE
Some tiles not drawn when panning map with SVG filter

### ISSUE THREAD

**Issue by jasonoverland** [Leaflet/Leaflet#6275]
I'm using latest release Leaflet 1.3.3 on Chrome/Electron on Mac/Windows/Linux. This only seems to happen on Chrome (not Firefox or Safari).

If I have an SVG filter applied to a leaflet-tile-pane (i.e. TileLayer), not all tiles are drawn when panning/zooming the map. Zooming out on this example does it pretty consistently for me:

https://jsfiddle.net/gqbu8jwo/10/

As soon as I drag the map just a hair the tiles pop in.

If I move the SVG filter to leaflet-tile-container instead, the problem goes away, and the brightness changes (Huh?).

Is there a recommended way of applying filters to TileLayers?

**Comment by IvanSanchez** [comment]
I can only see some glitching *during* the zoom animations. And I'm gonna guess this is going to be nigh-impossible to debug properly, as it's browser-dependant and only shows during animations.

I'd say you might want to look at https://gitlab.com/IvanSanchez/Leaflet.TileLayer.GL , if you're comfortable with WebGL (also, https://thebookofshaders.com/). Look at the hue rotation example in particular. It's a bit more work on your part, but the behaviour is more consistent across browsers AFAIK.

**Comment by jasonoverland** [comment]
Thanks for the quick response.

Interesting that you're not seeing it. I've seen it on multiple machines and OS's; I wonder what could be different (...network load timing? It seems to occur more often on non-cached tiles). If I repeatedly zoom out on that example, I am bound to see tiles that aren't drawn. Now that I'm inspecting it, I had assumed it was individual tiles not showing - but it seems to be regions of the map independent of tiles. Odd.

As far as during the animation, maybe your eyes are better than mine because I'm not seeing anything unusual. Or we're just seeing different things.

I found that toggling any style in the dev console causes the missing areas to draw. It seems there is a long and storied history of telling Chrome 'no really, please repaint': https://stackoverflow.com/questions/3485365/how-can-i-force-webkit-to-redraw-repaint-to-propagate-style-changes. So I have a workaround: toggling a style property on the layer when load() is fired. Strange, but seems to work.

GL is intriguing for us in the future, but probably out of scope for us in addressing this relatively minor nuisance of a bug.

**Comment by IvanSanchez** [comment]
OK, so if you have a workaround, I'll be closing this then.
