### ISSUE TITLE
May I know can I plot some geometry on the image overlay and retrieve it pixel coordinate relative to the image pixel size?Anyone can answer me I am appreciate.Thank you. 

### ISSUE THREAD

**Issue by tmh12345** [Leaflet/Leaflet#6276]
## How to reproduce

- Leaflet version I'm using 1.3.3:
- Browser (with version) I'm using google chrome version 11:
- OS/Platform (with version) I'm using window 8:
- step 1
- step 2

## Minimal example reproducing the issue

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

Using http://leafletjs.com/edit.html or any other jsfiddle-like site.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by IvanSanchez** [comment]
Also, I think you're just looking for https://github.com/commenthol/leaflet-rastercoords.

**Comment by tmh12345** [comment]
Hi IvanSanchez. 
I get the accurate pixel coordinate using L.crs.simple. Any idea?

**Comment by ghybs** [comment]
Hi @tmh12345,

Indeed, some simple functions on top of Leaflet can be enough for your usage, instead of using the rastercoords plugin.

You may be interested in that post on SO:
https://stackoverflow.com/questions/44054833/how-to-use-leaflet-flyto-with-unproject-and-geojson-data-on-a-large-raster-i/44063119#44063119

**Comment by tmh12345** [comment]
@ghybs 
Thank for your reply. Indeed what I want to know.
