### ISSUE TITLE
Quickstart example doesn't work

### ISSUE THREAD

**Issue by ygoe** [Leaflet/Leaflet#6280]
## How to reproduce

- Leaflet version I'm using: 1.3.3
- Browser (with version) I'm using: Firefox 61
- OS/Platform (with version) I'm using: Windows 10
- Follow the [quickstart guide](https://leafletjs.com/examples/quick-start/)

## What behaviour I'm expecting and which behaviour I'm seeing

I'd expect to see a map but instead I get a grey div with zoom buttons but no map in it. Browser console says nothing.

## Minimal example reproducing the issue

See https://leafletjs.com/examples/quick-start/

**Comment by perliedman** [comment]
Hi!

This page is an actual copy of the quick start guide: https://leafletjs.com/examples/quick-start/example-basic.html, and it works (at least for me).

I guess something must have gone wrong following the instructions - unfortunately, it's not possible for me to tell what's wrong given the information above. So, we need some more information, for example a copy of the code you use, if we should investigate this further.

**Comment by ygoe** [comment]
Here's a preview of that page: https://ov-b33.de/v2018/ov

**Comment by perliedman** [comment]
Looks like you're not adding a tile layer, so there's just not anything to display on the map.

In other words, you are missing this step from the quick start guide:

> Next we’ll add a tile layer to add to our map, in this case it’s a Mapbox Streets tile layer. Creating a tile layer usually involves setting the URL template for the tile images, the attribution text and the maximum zoom level of the layer. In this example we’ll use the mapbox.streets tiles from Mapbox’s “Classic maps” (in order to use tiles from Mapbox, you must also request an access token).

```js
L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
    attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
    maxZoom: 18,
    id: 'mapbox.streets',
    accessToken: 'your.mapbox.access.token'
}).addTo(mymap);
```

I'm closing this for now, give a shout if you still think there's an error.

**Comment by ygoe** [comment]
Oh, it wasn't clear to me that this is also required. Since they need an API key and a whole new account with a company I don't know yet, I'll just stay with Google instead.

**Comment by IvanSanchez** [comment]
Related to #6268 - apparently the mapbox tokens are confusing more people.

**Comment by ygoe** [comment]
Just a short follow-up for interested readers: After hours of searching and experimenting, lots of unrelated and random error messages, broken management systems, I came to the point where I found that Google has a quota of 1 map load per day for their Maps JavaScript API. With API key. But without billing. I've given up on custom maps, they only work for enterprises. The basic embeddable map from Google will have to do for me.

**Comment by perliedman** [comment]
@ygoe you don't have to use Mapbox, you can add a tile layer using for example `https://tile.openstreetmap.org/{z}/{x}/{y}.png` as long as it's for testing / small scale usage (see [Tile Usage Policy](https://operations.osmfoundation.org/policies/tiles/)).

**Comment by heliosnarcissus** [comment]
LeafletJS was made with good intentions but it's hard to use as you have to setup MapBox and other shenanigans. You have to know where to get "access_token" , "mapid" also got me stuck, no idea where to get it.

Where as Google Maps JS is straightforward - get an API_KEY from dev console, and voila, maps is working.

I'm up to write a better guide for newbies when I get LeafletJS working on my end. Currently, it's frustrating to use.

**Comment by AbdenourBout** [comment]
2 years later I had the same hiccup, it would've been easier if it used openstreetmap just like the example on the overview page. keep it up ^^
