### ISSUE TITLE
Racist place names in lower manhattan

### ISSUE THREAD

**Issue by mrkutly** [Leaflet/Leaflet#6284]
Found this on the Bolt Bus website. Looks like a troll might have slipped a pull request by.

![img_1148](https://user-images.githubusercontent.com/36522106/44066177-f33547ce-9f3c-11e8-8cc7-dae67b5d92e9.PNG)

**Comment by perliedman** [comment]
Hi! Thanks for noting and reporting. However, how unfortunate this might be, this is outside the control of Leaflet's maintainers. Leaflet is merely a library to display maps in a browser, the maps themselves and their underlying geographic data come from other sources outside our control.

I suggest reporting this to the app in question - it looks like an OpenStreetMap map, but looking at OpenStreetMap doesn't show these names (https://www.openstreetmap.org/search?query=new%20york#map=12/40.7338/-73.8998)

**Comment by IvanSanchez** [comment]
Duplicate of #3896, #4661, #4332, #4819, #5056. Leaflet is a map visualization library independent of the maps used.

What you're looking at is most probably some vandalism in openstreetmap - see the same area in www.osm.org. See https://wiki.openstreetmap.org/wiki/Vandalism and https://wiki.openstreetmap.org in general.

In particular, see OSM node https://www.openstreetmap.org/node/61785451/history and OSM changesets https://www.openstreetmap.org/changeset/61555047 and https://www.openstreetmap.org/changeset/61556105 - looks like the name changes in the dataset were already reverted.
