### ISSUE TITLE
Is there a way to only render a certain area of the map?

### ISSUE THREAD

**Issue by VVNoodle** [Leaflet/Leaflet#6286]
This is not an issue and more of a question from a novice (title). I'm trying to make a lost/found web app which involves displaying my school's map. I think it's unnecessary to render the rest of the surrounding locations as it requires more bandwidth. Is there any way to do this? I've also set maxBoundary to within my campus only.

Thanks in advance!!!

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by IvanSanchez** [comment]
Also please note that there is no `maxBoundary` option. There's `maxBounds` for `L.Map` **and** for `L.TileLayer`s. Read the API documentation. Experiment with both.

**Comment by zorun** [comment]
Note that there's also a plugin to do this: https://github.com/aparshin/leaflet-boundary-canvas

See the demo: http://aparshin.github.com/leaflet-boundary-canvas/examples/canvas-boundary-edit.html

However I don't think it will save that much tile loading work, compared to just setting a tight `maxBounds`.
