### ISSUE TITLE
Broken reference to the Leaflet UserVoice page

### ISSUE THREAD

**Issue by zstadler** [Leaflet/Leaflet#6288]
The [Getting Involved](https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md#getting-involved) section of CONTRIBUTING.md refers to the [Leaflet UserVoice page](http://leaflet.uservoice.com/), but the link seems to be broken

![image](https://user-images.githubusercontent.com/1304610/44140998-80430488-a084-11e8-965f-b185b2ae476b.png)

Please correct or delete this reference, as appropriate.

**Comment by mourner** [comment]
> Hello,
> It looks like you haven’t used your UserVoice account, leaflet.uservoice.com, in the past 365 days. We will delete it and all data on August 12, 2018 unless you log in within 10 days.
> If you are still using UserVoice, simply log in as the Owner and it will renew your free account for the next year.
> Your account URL is leaflet.uservoice.com
> If you are no longer using UserVoice, you don’t need to do anything. The account will be deleted on August 12, 2018 and all data permanently deleted.

Welp, it looks like the account with all the suggestions got deleted. And I only found out because of your ticket because e-mail notifications were filtered away. :) We should remove all references to it on both contributing.md and the website. Would you want to submit a PR for that?
