### ISSUE TITLE
Leaflet release notifications

### ISSUE THREAD

**Issue by cherniavskii** [Leaflet/Leaflet#6295]
# Want to receive notification when new Leaflet release is available?

:point_right: Click the "[**Subscribe**](https://help.github.com/articles/subscribing-to-and-unsubscribing-from-notifications/)" button on the right column of this thread and you'll get a notification/email every time Leaflet release is out! 🍃

**Comment by IvanSanchez** [comment]
I thought one could subscribe to a RSS feed like https://github.com/Leaflet/Leaflet/releases.atom in order to keep up with releases?

**Comment by cherniavskii** [comment]
Yes, but apparently RSS feeds are not so obvious, and require installing an app or browser extension.
Clicking Subscribe button is way easier.

**Comment by cherniavskii** [comment]
Leaflet 1.3.4 is out! :rocket: 
https://github.com/Leaflet/Leaflet/releases/tag/v1.3.4

**Comment by cherniavskii** [comment]
Closing in favor of https://twitter.com/github/status/1067483957573373952
