### ISSUE TITLE
TypeError: Cannot read property '_layerAdd' of null

### ISSUE THREAD

**Issue by LeCaoDat** [Leaflet/Leaflet#6297]
I using
`leaflet v1.3.3`
`jest v 22.4.3`

## My code
```
import L from 'leaflet'

describe('TEST', () => {
  it('Circle', () => {
    const mapElement = document.createElement('div')
    mapElement.setAttribute('id', 'map')
    document.body.appendChild(mapElement)
    let map = L.map('map', {
    }).setView([35.65484,  139.75481], 14)
    L.circle([35.65484,  139.75481]).addTo(map)
    expect(123).toBe(123)
  })
})
```

## Run `yarn test`

The results here:

```
TypeError: Cannot read property '_layerAdd' of null

       8 |     let map = L.map('map', {
       9 |     }).setView([35.65484,  139.75481], 14)
    > 10 |     L.circle([35.65484,  139.75481]).addTo(map)
      11 |     expect(123).toBe(123)
      12 |   })
      13 | })

      at NewClass.addLayer (node_modules/leaflet/src/layer/Layer.js:158:14)
      at NewClass.getRenderer (node_modules/leaflet/src/layer/vector/Renderer.getRenderer.js:21:9)
      at NewClass.beforeAdd (node_modules/leaflet/src/layer/vector/Path.js:80:24)
      at NewClass.addLayer (node_modules/leaflet/src/layer/Layer.js:169:10)
      at NewClass.addTo (node_modules/leaflet/src/layer/Layer.js:52:7)
      at Object.addTo (spec/javascript/abc.spec.js:10:38)
```
When I use `L.circle` or `L.polyline` it will get this error.

**Comment by IvanSanchez** [comment]
What's the environment? Is there a (headless) web browser, or nodejs with domjs?

**Comment by LeCaoDat** [comment]
I write that test with VueJs + leaflet + jest. Any tips for me?

**Comment by IvanSanchez** [comment]
It's possible that you need to wait for Vue to mount containers and such things.

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.

**Comment by mkondur** [comment]
I had the same problem, angular 6 + leaflet 1.3 + jest
I solved this issue setting map options `preferCanvas: true`
and in jestGlobalMocks config define canvas getContext to fix Error: Not implemented: HTMLCanvasElement.prototype.getContex from jsdom module
```
Object.defineProperty(HTMLCanvasElement.prototype, 'getContext', {
  value: () => {
    return {
      fillRect: function() {},
      clearRect: function(){},
      getImageData: function(x, y, w, h) {
          return  {
              data: new Array(w*h*4)
          };
      },
      putImageData: function() {},
      createImageData: function(){ return []},
      setTransform: function(){},
      drawImage: function(){},
      save: function(){},
      fillText: function(){},
      restore: function(){},
      beginPath: function(){},
      moveTo: function(){},
      lineTo: function(){},
      closePath: function(){},
      stroke: function(){},
      translate: function(){},
      scale: function(){},
      rotate: function(){},
      arc: function(){},
      fill: function(){},
      measureText: function(){
          return { width: 0 };
      },
      transform: function(){},
      rect: function(){},
      clip: function(){},
    }
  } 
});
```

**Comment by xiel** [comment]
What I can recommend for testing is the following, just mock leaflet using this in your test file, that is rendering the map component:
`jest.mock('leaflet')`

And then you place this leaflet mock you can find in react-leaflet into the jest mocks folder ("__mocks__/leaflet.js", download current file from: https://github.com/PaulLeCam/react-leaflet/blob/master/__mocks__/leaflet.js)

**Comment by kentr** [comment]
Adding this in case it helps someone.

If you don't want to mock Leaflet for whatever reason and want to continue using the SVG renderer, another fix for this error is to [add a stub function for `createSVGRect` in the test environment, as suggested by Vadim Gremyachev](https://stackoverflow.com/a/54384719).

**Comment by eric-burel** [comment]
@kentr It did help someone, works perfect.

**Comment by selankon** [comment]
The mock file `__mocks__/leaflet.js` no longer exists

**Comment by alvinycheung** [comment]
I'm also looking for the leaflet mock

**Comment by charlieforward9** [comment]
This issue still persists with vite, vitest and react-leaflet setup with `_leaflet_id`

**Comment by charlieforward9** [comment]
I found the [mentioned](https://github.com/Leaflet/Leaflet/issues/6297#issuecomment-499809735) mock file on previous branches, this probably just needs some tweaks to work in v4

https://github.com/PaulLeCam/react-leaflet/blob/v2/__mocks__/leaflet.js
