### ISSUE TITLE
Add a method to grab the Leaflet object from a DOMNode

### ISSUE THREAD

**Issue by tristanleboss** [Leaflet/Leaflet#6298]
This is a feature request.

Indeed, it would be great to be able to grab the Leaflet object of an existing map if you only know it's class/id and so, if you have its DOMNode.

```
var my_map = document.getElementById("mymap");
L.getMap(my_map).getCenter()

```

**Comment by IvanSanchez** [comment]
I don't think this is feasible right now - the implementation of `_initContainer` in `L.Map` does not store a reference to the `L.Map` instance in the `HTMLElement`. Furthermore, there is no namespace-wide index of map instances to their container `HTMLElement`s.

I'm also afraid that such a feature might create regressions about memory leaks, i.e. circular references from a map to its container and #5774 all over again.

What's the use case for this?

**Comment by tristanleboss** [comment]
We wanted to work with a map which was initialized by a WordPress plugin (code we can't edit) inside a closure (nowadays, due to jQuery and co, almost everything is thanksfully done in closures). In such a situation, there is no way to access the Leaflet object.

**Comment by tristanleboss** [comment]
For example, Vue.js stores its object in DOMNode `__vue__` property. This way, you can acccess the object using a simple `document.getElementById('MY_ID').__vue__`.

**Comment by ghybs** [comment]
Hi @tristanleboss,

You would probably be interested in that post on SO:
https://stackoverflow.com/questions/45412056/find-leaflet-map-object-after-initialisation/45435508#45435508
The idea is to setup a map initialization hook where you can store a reference to the map.

In your case where you want to store the reference on the DOM node itself, you could do:
```javascript
L.Map.addInitHook(function () {
  // Store a reference of the Leaflet map object on the map container,
  // so that it could be retrieved from DOM selection.
  // https://leafletjs.com/reference-1.3.4.html#map-getcontainer
  this.getContainer()._leaflet_map = this;
});
```
Live example: https://plnkr.co/edit/iCgbRjW4aymAjoVoicZQ?p=preview

As explained by @IvanSanchez, unfortunately generalizing this approach might create memory leaks in certain use cases, especially on older browsers.
Therefore I do not think we will be able to implement such feature in Leaflet core, and I am closing this Feature Request as such.

But feel free to use it for your particular case: if you never remove the map, you should not face the memory leak issue.
Or more simply, use a global variable, as done in the linked SO post, to avoid circular references.
