### ISSUE TITLE
Asking for reviews of old PRs?

### ISSUE THREAD

**Issue by manubb** [Leaflet/Leaflet#6300]
Hello Leaflet Team,
i've submitted two PRs in april that are still waiting for reviews:

https://github.com/Leaflet/Leaflet/pull/6126
https://github.com/Leaflet/Leaflet/pull/6133

Can a Leaflet maintainer have a look at them? (especially the first one)
Thanks!

**Comment by mourner** [comment]
Will get to them when we can — no need to submit issues about that.
