### ISSUE TITLE
Custom map image stretching issue in leaflet.js

### ISSUE THREAD

**Issue by Dhimandpk** [Leaflet/Leaflet#6305]
I am using leaflet.js in my xamarin navigation app project for custom map. but when i assign the custom map image with respective bounds then image is stretching and automatically width is assigned. I don't want to stretch my map image.

Original image:
![test_trailmapfinal 2](https://user-images.githubusercontent.com/39083088/44447857-2923e400-a607-11e8-8e5b-7fc50d77ab40.jpg)

Stretched Image
![capture2](https://user-images.githubusercontent.com/39083088/44447858-29bc7a80-a607-11e8-977f-e47c4ae0d24e.JPG)

Is there any way in leaflet.js where i can avoid this stretching ?

**Comment by IvanSanchez** [comment]
You're not using the right bounds.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
