### ISSUE TITLE
Use unicode "×" symbol instead of close icon

### ISSUE THREAD

**Issue by lexer** [Leaflet/Leaflet#631]
You can use this symbol "×" instead of close icon. Pure css rocks! =)

**Comment by QuantumInformation** [comment]
What about ❌ or ✖?

**Comment by akmil** [comment]
or this one '✕'

**Comment by mariapazz** [comment]
Whats the unicode for that one?

**Comment by ghybs** [comment]
@mariapazz http://www.amp-what.com/
