### ISSUE TITLE
Only Subset of Panels Loading

### ISSUE THREAD

**Issue by dschinkel** [Leaflet/Leaflet#6315]
I've got the following **Vue.js** component.  The problem we see is that panels are not all loading and it's bizarre.  Not sure why:

```js
<template>
    <div id="map"></div>
</template>

<script>
  import registerStore from '../utils/registerStore';
  import L from 'leaflet';

  export default {
    name: "FencePolygon",
    components: {

    },
    extends: registerStore(),
    props: {
    },
    data() {
      return { map: null }
    },
    mounted() {
      this.map = L.map('map', {
        center: [51.505, -0.09],
        zoom: 14
      });

      L.tileLayer('http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png').addTo(this.map);
    },
    computed: {
    },
    methods: {
    },
    watch: {
    }
  }
</script>
```
![screen shot 2018-08-27 at 3 34 10 pm](https://user-images.githubusercontent.com/338798/44684426-ae940380-aa0e-11e8-8590-e1cc01e8d03a.png)

**Comment by ghybs** [comment]
Hi, great to hear that you find Leaflet useful!

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* Angular / AngularJS
* Leaflet for R
* Joomla
* WordPress
* Drupal
* Rails
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* etc.

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.

**Comment by ghybs** [comment]
Missing Leaflet CSS
https://stackoverflow.com/questions/38835758/leaflet-drawing-tiles-disjointly/38836996#38836996
