### ISSUE TITLE
Polyline and Bounds across the International Date Line

### ISSUE THREAD

**Issue by PiTiLeZarD** [Leaflet/Leaflet#6321]
Hey,

Sorry if this has been reported/solved before I searched a while but couldn't find anything. Here goes nothing:

I'm doing an app to records ham radio contacts. I live in Brisbane Australia, so I do contacts over the IDL quite often.

[Here is how they look](https://imgur.com/qwXF1sH)

It might be a misunderstanding on my part but is there a way to use the shorter path for both the line and the map bounds?

Cheers for all your efforts, after fiddling with GMaps for a while, it was such a relief to find something that works immediately without fussing around!

**Comment by cherniavskii** [comment]
Hi Jonathan,
Good to hear that you find Leaflet useful!

AFAIK this issue is resolved by [Leaflet.Antimeridian plugin](https://github.com/briannaAndCo/Leaflet.Antimeridian).

**Comment by PiTiLeZarD** [comment]
Oh sweet!!! Couldn't find that on my own, cheers! I'll try this and close this issue then. Thanks heaps!
