### ISSUE TITLE
Leaflet map.flyTo on L.videoOvelay in IE 11  is not smooth

### ISSUE THREAD

**Issue by jeudaya** [Leaflet/Leaflet#6323]
In IE 11, map.flyTo function on L.videoOverlay is very terrible. Please give a solution for this. Its working fine with imageOverlay but not with videoOverlay.

**Comment by IvanSanchez** [comment]
I don't think there is a way to achieve smooth graphics operations on IE11, at all. IE11 might be choking at the CSS transforms done during a `flyTo()` animations, and there's no way to change that (that I know of).

Closing as "won't fix, browser limitations"
