### ISSUE TITLE
Leaflet doesn't play nice with a server-side environment due to window references in utils

### ISSUE THREAD

**Issue by tstirrat15** [Leaflet/Leaflet#6331]
## How to reproduce
`import L from 'leaflet'` in a nodejs environment. Because there are naked references to [window](https://github.com/Leaflet/Leaflet/blob/9fda888df2791ca0df6f182a9d91d393ee49034c/src/core/Util.js#L214) [attributes](https://github.com/Leaflet/Leaflet/blob/9fda888df2791ca0df6f182a9d91d393ee49034c/src/core/Util.js#L217) in the [utils file](https://github.com/Leaflet/Leaflet/blob/9fda888df2791ca0df6f182a9d91d393ee49034c/src/core/Util.js#L218), this will throw an error.

## What behaviour I'm expecting and which behaviour I'm seeing
It makes sense that this library is oriented around the browser, since that's typically where you're going to find this code, and the functionality doesn't make sense if you're running it in a Node environment.

However!

This makes things very difficult for server-side rendering using things like `react-leaflet`, since simply importing the package is enough to make this throw errors.

## Minimal example reproducing the issue
`import L from 'leaflet'` in a nodejs environment.

**Comment by IvanSanchez** [comment]
Closing because #6332.
