### ISSUE TITLE
Canceled tiles with  new Chrome version 69.0.3497.92

### ISSUE THREAD

**Issue by mariusisac** [Leaflet/Leaflet#6339]
![leaflet_chrome_issue](https://user-images.githubusercontent.com/6637005/45550676-3f067c80-b834-11e8-9294-2d23b1b5d32f.jpg)

Environment : Chrome 69.0.3497.92, Widows 10.

It seems that the new version of chrome cancels some tiles from downloading making the transition when pan and zooming appear not as smooth as before. I was able to reproduce the issue on the main site https://leafletjs.com/. A lot of times tiles are missing.

Firefox and IE seem to work fine.

**Comment by mourner** [comment]
Are you sure tiles are missing at the end of the animation, and the cancelled tiles are not simply the tiles that are no longer needed? I just tried browsing leafletjs.com on Chrome 69 and everything works fine.

**Comment by mariusisac** [comment]
Sorry my mistake, it seems it is related to the tile server, I can reproduce the issue on Firefox.

Chrome: 
![image](https://user-images.githubusercontent.com/6637005/45752310-b6b21e00-bc1d-11e8-919b-845d1fe2547a.png)
Firefox :
![image](https://user-images.githubusercontent.com/6637005/45752351-d2b5bf80-bc1d-11e8-8657-dac7d9482680.png)

**Comment by IvanSanchez** [comment]
Looks like it's not due to Leaflet issue but rather related to your network.
