### ISSUE TITLE
Critical bug compiling AOT

### ISSUE THREAD

**Issue by putchi** [Leaflet/Leaflet#6340]
I'm reporting a critical bug when trying to compile with AOT.

angular version: 4.1.3
version i'm using is: 1.2.11 (latest)

stacktrace:
Error: Error at ../node_modules/@types/geojson/index.d.ts:69:34: Generic type 'Feature<G, Geometry, P, GeoJsonProperties>' requires 4 type argument(s).
Error at ../node_modules/@types/geojson/index.d.ts:69:44: Generic type 'FeatureCollection<G, Geometry, P, GeoJsonProperties>' requires 4 type argument(s).
Error at ../node_modules/@types/geojson/index.d.ts:154:58: ',' expected.
Error at ../node_modules/@types/geojson/index.d.ts:154:72: ',' expected.
Error at ../node_modules/@types/geojson/index.d.ts:175:68: ',' expected.
Error at ../node_modules/@types/geojson/index.d.ts:175:82: ',' expected.
Error at ../node_modules/@types/geojson/index.d.ts:177:21: Generic type 'Feature<G, Geometry, P, GeoJsonProperties>' requires 4 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:400:20: Generic type 'LayerGroup<P, any>' requires 2 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:616:56: ',' expected.
Error at ../node_modules/@types/leaflet/index.d.ts:616:65: ',' expected.
Error at ../node_modules/@types/leaflet/index.d.ts:616:77: ',' expected.
Error at ../node_modules/@types/leaflet/index.d.ts:616:87: Property 'MultiLineString' does not exist on type 'typeof "../node_modules/@types/geojson/index"'.
Error at ../node_modules/@types/leaflet/index.d.ts:616:104: Cannot find name 'P'.
Error at ../node_modules/@types/leaflet/index.d.ts:616:108: Cannot find name 'any'.
Error at ../node_modules/@types/leaflet/index.d.ts:616:113: Expression expected.
Error at ../node_modules/@types/leaflet/index.d.ts:616:126: ';' expected.
Error at ../node_modules/@types/leaflet/index.d.ts:617:5: Cannot find name 'constructor'.
Error at ../node_modules/@types/leaflet/index.d.ts:617:17: Cannot find name 'latlngs'.
Error at ../node_modules/@types/leaflet/index.d.ts:617:24: ',' expected.
Error at ../node_modules/@types/leaflet/index.d.ts:617:26: 'LatLngExpression' only refers to a type, but is being used as a value here.
Error at ../node_modules/@types/leaflet/index.d.ts:617:47: 'LatLngExpression' only refers to a type, but is being used as a value here.
Error at ../node_modules/@types/leaflet/index.d.ts:617:69: Cannot find name 'options'.
Error at ../node_modules/@types/leaflet/index.d.ts:617:77: Expression expected.
Error at ../node_modules/@types/leaflet/index.d.ts:617:79: 'PolylineOptions' only refers to a type, but is being used as a value here.
Error at ../node_modules/@types/leaflet/index.d.ts:618:5: Cannot find name 'toGeoJSON'.
Error at ../node_modules/@types/leaflet/index.d.ts:618:16: ';' expected.
Error at ../node_modules/@types/leaflet/index.d.ts:618:26: Property 'Feature' does not exist on type 'typeof "../node_modules/@types/geojson/index"'.
Error at ../node_modules/@types/leaflet/index.d.ts:618:39: '(' expected.
Error at ../node_modules/@types/leaflet/index.d.ts:619:5: Cannot find name 'getLatLngs'.
Error at ../node_modules/@types/leaflet/index.d.ts:619:17: ';' expected.
Error at ../node_modules/@types/leaflet/index.d.ts:620:5: Cannot find name 'setLatLngs'.
Error at ../node_modules/@types/leaflet/index.d.ts:620:16: Cannot find name 'latlngs'.
Error at ../node_modules/@types/leaflet/index.d.ts:620:23: ',' expected.
Error at ../node_modules/@types/leaflet/index.d.ts:620:25: 'LatLngExpression' only refers to a type, but is being used as a value here.
Error at ../node_modules/@types/leaflet/index.d.ts:620:46: 'LatLngExpression' only refers to a type, but is being used as a value here.
Error at ../node_modules/@types/leaflet/index.d.ts:620:69: 'LatLngExpression' only refers to a type, but is being used as a value here.
Error at ../node_modules/@types/leaflet/index.d.ts:620:92: ';' expected.
Error at ../node_modules/@types/leaflet/index.d.ts:621:5: Cannot find name 'isEmpty'.
Error at ../node_modules/@types/leaflet/index.d.ts:621:14: ';' expected.
Error at ../node_modules/@types/leaflet/index.d.ts:621:16: Cannot find name 'boolean'.
Error at ../node_modules/@types/leaflet/index.d.ts:622:5: Cannot find name 'getCenter'.
Error at ../node_modules/@types/leaflet/index.d.ts:622:16: ';' expected.
Error at ../node_modules/@types/leaflet/index.d.ts:623:5: Cannot find name 'getBounds'.
Error at ../node_modules/@types/leaflet/index.d.ts:623:16: ';' expected.
Error at ../node_modules/@types/leaflet/index.d.ts:624:5: Cannot find name 'addLatLng'.
Error at ../node_modules/@types/leaflet/index.d.ts:624:15: Cannot find name 'latlng'.
Error at ../node_modules/@types/leaflet/index.d.ts:624:21: ',' expected.
Error at ../node_modules/@types/leaflet/index.d.ts:624:23: 'LatLngExpression' only refers to a type, but is being used as a value here.
Error at ../node_modules/@types/leaflet/index.d.ts:624:42: 'LatLngExpression' only refers to a type, but is being used as a value here.
Error at ../node_modules/@types/leaflet/index.d.ts:624:61: ';' expected.
Error at ../node_modules/@types/leaflet/index.d.ts:626:5: Cannot find name 'feature'.
Error at ../node_modules/@types/leaflet/index.d.ts:626:13: Expression expected.
Error at ../node_modules/@types/leaflet/index.d.ts:626:23: Property 'Feature' does not exist on type 'typeof "../node_modules/@types/geojson/index"'.
Error at ../node_modules/@types/leaflet/index.d.ts:626:36: '(' expected.
Error at ../node_modules/@types/leaflet/index.d.ts:627:5: Unused label.
Error at ../node_modules/@types/leaflet/index.d.ts:627:14: 'PolylineOptions' only refers to a type, but is being used as a value here.
Error at ../node_modules/@types/leaflet/index.d.ts:630:106: Generic type 'Polyline<T, geojson, LineString>' requires 3 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:632:24: ',' expected.
Error at ../node_modules/@types/leaflet/index.d.ts:632:26: Type parameter name cannot be 'any'
Error at ../node_modules/@types/leaflet/index.d.ts:632:39: Generic type 'Polyline<T, geojson, LineString>' requires 3 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:636:130: Generic type 'Polygon<P, any>' requires 2 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:638:26: ',' expected.
Error at ../node_modules/@types/leaflet/index.d.ts:638:28: Type parameter name cannot be 'any'
Error at ../node_modules/@types/leaflet/index.d.ts:638:41: Generic type 'Polygon<P, any>' requires 2 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:643:93: Generic type 'Rectangle<P, any>' requires 2 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:649:29: ',' expected.
Error at ../node_modules/@types/leaflet/index.d.ts:649:31: Type parameter name cannot be 'any'
Error at ../node_modules/@types/leaflet/index.d.ts:651:18: Generic type 'Feature<G, Geometry, P, GeoJsonProperties>' requires 4 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:658:15: Generic type 'Feature<G, Geometry, P, GeoJsonProperties>' requires 4 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:661:88: Generic type 'CircleMarker<P, any>' requires 2 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:663:23: ',' expected.
Error at ../node_modules/@types/leaflet/index.d.ts:663:25: Type parameter name cannot be 'any'
Error at ../node_modules/@types/leaflet/index.d.ts:663:38: Generic type 'CircleMarker<P, any>' requires 2 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:669:82: Generic type 'Circle<P, any>' requires 2 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:670:98: Generic type 'Circle<P, any>' requires 2 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:701:27: ',' expected.
Error at ../node_modules/@types/leaflet/index.d.ts:701:29: Type parameter name cannot be 'any'
Error at ../node_modules/@types/leaflet/index.d.ts:707:18: Generic type 'FeatureCollection<G, Geometry, P, GeoJsonProperties>' requires 4 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:707:73: Generic type 'Feature<G, Geometry, P, GeoJsonProperties>' requires 4 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:761:15: Generic type 'FeatureCollection<G, Geometry, P, GeoJsonProperties>' requires 4 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:761:70: Generic type 'Feature<G, Geometry, P, GeoJsonProperties>' requires 4 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:767:71: Generic type 'LayerGroup<P, any>' requires 2 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:773:29: ',' expected.
Error at ../node_modules/@types/leaflet/index.d.ts:773:31: Type parameter name cannot be 'any'
Error at ../node_modules/@types/leaflet/index.d.ts:773:44: Generic type 'LayerGroup<P, any>' requires 2 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:799:49: Generic type 'FeatureGroup<P, any>' requires 2 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:801:29: ',' expected.
Error at ../node_modules/@types/leaflet/index.d.ts:801:31: Type parameter name cannot be 'any'
Error at ../node_modules/@types/leaflet/index.d.ts:801:49: Generic type 'Feature<G, Geometry, P, GeoJsonProperties>' requires 4 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:803:35: ',' expected.
Error at ../node_modules/@types/leaflet/index.d.ts:803:37: Type parameter name cannot be 'any'
Error at ../node_modules/@types/leaflet/index.d.ts:817:33: Generic type 'Feature<G, Geometry, P, GeoJsonProperties>' requires 4 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:831:13: Generic type 'StyleFunction' requires 2 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:843:29: Generic type 'Feature<G, Geometry, P, GeoJsonProperties>' requires 4 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:856:29: Generic type 'Feature<G, Geometry, P, GeoJsonProperties>' requires 4 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:869:24: ',' expected.
Error at ../node_modules/@types/leaflet/index.d.ts:869:26: Type parameter name cannot be 'any'
Error at ../node_modules/@types/leaflet/index.d.ts:869:39: Type 'typeof FeatureGroup' is not a constructor function type.
Error at ../node_modules/@types/leaflet/index.d.ts:874:30: ',' expected.
Error at ../node_modules/@types/leaflet/index.d.ts:874:32: Type parameter name cannot be 'any'
Error at ../node_modules/@types/leaflet/index.d.ts:874:50: Generic type 'Feature<G, Geometry, P, GeoJsonProperties>' requires 4 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:874:104: Generic type 'GeoJSONOptions<P, any>' requires 2 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:908:24: ',' expected.
Error at ../node_modules/@types/leaflet/index.d.ts:908:26: Type parameter name cannot be 'any'
Error at ../node_modules/@types/leaflet/index.d.ts:908:40: Generic type 'Feature<G, Geometry, P, GeoJsonProperties>' requires 4 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:908:110: Generic type 'Feature<G, Geometry, P, GeoJsonProperties>' requires 4 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:910:60: Generic type 'GeoJSONOptions<P, any>' requires 2 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:922:14: Generic type 'GeoJSONOptions<P, any>' requires 2 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:932:27: ',' expected.
Error at ../node_modules/@types/leaflet/index.d.ts:932:29: Type parameter name cannot be 'any'
Error at ../node_modules/@types/leaflet/index.d.ts:932:77: Generic type 'GeoJSONOptions<P, any>' requires 2 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:932:97: Generic type 'GeoJSON<P, any>' requires 2 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:1439:45: ',' expected.
Error at ../node_modules/@types/leaflet/index.d.ts:1452:27: Generic type 'Icon<T, IconOptions>' requires 2 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:1458:45: Generic type 'Icon<T, IconOptions>' requires 2 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:1469:30: Generic type 'Icon<T, IconOptions>' requires 2 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:1476:12: Generic type 'Icon<T, IconOptions>' requires 2 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:1488:23: ',' expected.
Error at ../node_modules/@types/leaflet/index.d.ts:1488:25: Type parameter name cannot be 'any'
Error at ../node_modules/@types/leaflet/index.d.ts:1490:18: Generic type 'Feature<G, Geometry, P, GeoJsonProperties>' requires 4 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:1494:19: Generic type 'Icon<T, IconOptions>' requires 2 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:1501:15: Generic type 'Feature<G, Geometry, P, GeoJsonProperties>' requires 4 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:1504:76: Generic type 'Marker<P, any>' requires 2 type argument(s).
Error at ../node_modules/@types/leaflet/index.d.ts:1537:57: ',' expected.
Error at ../node_modules/@types/leaflet/index.d.ts:1537:59: '>' expected.
Error at ../node_modules/@types/leaflet/index.d.ts:1537:61: Expression expected.
Error at ../node_modules/@types/leaflet/index.d.ts:1537:63: Cannot find name 'dest'.
Error at ../node_modules/@types/leaflet/index.d.ts:1537:67: ')' expected.
Error at ../node_modules/@types/leaflet/index.d.ts:1537:69: Cannot find name 'D'.
Error at ../node_modules/@types/leaflet/index.d.ts:1537:69: Left side of comma operator is unused and has no side effects.
Error at ../node_modules/@types/leaflet/index.d.ts:1537:72: Cannot find name 'src'.
Error at ../node_modules/@types/leaflet/index.d.ts:1537:76: Expression expected.
Error at ../node_modules/@types/leaflet/index.d.ts:1537:78: Cannot find name 'S1'.
Error at ../node_modules/@types/leaflet/index.d.ts:1537:80: ';' expected.
Error at ../node_modules/@types/leaflet/index.d.ts:1537:81: Declaration or statement expected.
Error at ../node_modules/@types/leaflet/index.d.ts:1537:83: Cannot find name 'D'.
Error at ../node_modules/@types/leaflet/index.d.ts:1537:87: Cannot find name 'S1'.

**Comment by mourner** [comment]
This does not appear to be an issue with Leaflet — either something in TypeScript typings (which we don't officially maintain — please contact their author instead), or an issue with your Angular code.
