### ISSUE TITLE
How can i add css class to zoomIn and zoomOut buttons? 

### ISSUE THREAD

**Issue by djary** [Leaflet/Leaflet#6351]
Hi 
I have two css class "mapzoom-in" and "mapzoom-out" for zoom in and zoom out controls
But I do not know how to add classes to the buttons
Does anyone have an idea?

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by djary** [comment]
Buttons do not have a specific id  Which uses DomUtil.

for ex : <a class="leaflet-control-zoom-in" href="#" title="Zoom in" role="button" aria-label="Zoom in">+<div></div></a>

https://stackoverflow.com/questions/52550949/how-can-i-add-css-class-to-zoomin-and-zoomout-buttons-leaflet-map
