### ISSUE TITLE
map.fitBounds() / map.getBoundsZoom() BROKEN after resizing map?

### ISSUE THREAD

**Issue by Superslub** [Leaflet/Leaflet#6353]
https://jsfiddle.net/MaxHeadroom/s6h40xrn/

If you resize the map, the zoom level should be adapted to always show the orange rectangleat maximum possible size

But map.fitBounds seems to be broken after resizing the map. Same problem with map.getBoundsZoom().
(The zoom level set in the actual rendered view and the zoom level returned by map.getZoom() seem to differ!)

To reproduce the buggy behaviour, start with a small map size - increase it and decrease it then. You can check the console output too.

**Comment by IvanSanchez** [comment]
This is at https://gis.stackexchange.com/questions/297664/leaflet-map-fitbounds-map-getboundszoom-broken-after-resizing-map , so...

---


Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by Superslub** [comment]
OK, done here:
https://github.com/Leaflet/Leaflet/issues/6354

Hope, it's valid now.
