### ISSUE TITLE
The non-minified version of leaflet is included in the web-pack bundle

### ISSUE THREAD

**Issue by metric152** [Leaflet/Leaflet#6357]
## How to reproduce

- Leaflet version I'm using: 1.3.1
- Browser (with version) I'm using: Chrome
- OS/Platform (with version) I'm using: OSX 10.12.6

## What behaviour I'm expecting and which behaviour I'm seeing
I'm using Angular 5 to build a small project using leaflet. When I look at what's included in the vendor.bundle.js file it looks like the non-minified version of the file is included in package.json.
https://github.com/Leaflet/Leaflet/blob/master/package.json#L33

Should this be:
```
"main": "dist/leaflet.js",
// instead of
"main": "dist/leaflet-src.js",
```

## Minimal example reproducing the issue

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

Using http://leafletjs.com/edit.html or any other jsfiddle-like site.

**Comment by mourner** [comment]
This is working as intended — the main entry point doesn't have to be minified, and usually it isn't. If you want it minified, minify the full bundle on your end.
