### ISSUE TITLE
WMS layer staying on map after removal

### ISSUE THREAD

**Issue by ladal1** [Leaflet/Leaflet#6384]
## How to reproduce

- Leaflet version I'm using: 1.3.4
- Browser (with version) I'm using: Chrome 69, same on firefox and edge though
- OS/Platform (with version) I'm using: Windows 10
- step 1
https://stackoverflow.com/questions/52985155/switching-between-two-overlays-in-leaflet-js
this is layer 1/2 - 2 is the same just with layers:"KN_I"
```
let katastrLayer = new L.TileLayer.WMS(
        'http://services.cuzk.cz/wms/local-KM-wms.asp?',
        {
            layers: "KN",
            format: 'image/png',
            transparent: true,
            minZoom: 16,
            maxZoom: 21,
            crs: L.CRS.EPSG4326
        }
    );
```
- step 2
When switching the LayerX off with layer2 active (negative - white outlines of buildings/text) both should disappear and layer1 be added to the map

## What behaviour I'm expecting and which behaviour I'm seeing
LayerX is removed, but now the map has both layer1 and layer2 enabled on top of each other

## Minimal example reproducing the issue
https://next.plnkr.co/edit/scGTMqKkFDgBDHSj
Zoom in, enable layer1, then turn on and off LayerX. When you now disable layer 1, white layer 2 is still on the map. If you just look through layers on the map, layer2 will be missing, yet it is still shown

**Comment by IvanSanchez** [comment]
Not a leaflet bug. Use instead

```
let wmsLayers = {
		"LayerX": zmcuzkLayer,
		"layer1": layer1
};
let layer_selector = new L.Control.Layers(wmsLayers, {});
```

**Comment by ladal1** [comment]
The solution proposed does not get the desired outcome (single button showing different overlay based on underlying map) - And leaflet map showing a layer after it should have been deleted
