### ISSUE TITLE
Map not shows

### ISSUE THREAD

**Issue by aribs** [Leaflet/Leaflet#6386]
Hi, is not possible for me, charge a map, only charges map controls.
Leaflet version is 1.3.4
Example:
[https://codepen.io/aribs/pen/ZqwLRX](url)

Any idea?
Thanks

**Comment by jbccollins** [comment]
Add a tile layer:
https://codepen.io/jbccollins/pen/xyMYMd

And stackoverflow is probably a better place for questions like this.
