### ISSUE TITLE
Very long tile loading

### ISSUE THREAD

**Issue by vaydich** [Leaflet/Leaflet#6393]
Hi!

I'am using osm tile server `http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png` but tiles loading to long. Even it can't be loaded with 504. I'm in Russia. 
Can you explain what am i doing wrong or give one of the fastest tile server?

![osm](https://user-images.githubusercontent.com/12065515/47642851-cb69c600-db7a-11e8-93ac-68a849eceb2d.png)

![osm](https://user-images.githubusercontent.com/12065515/47642939-0d930780-db7b-11e8-901a-29fcb24076c3.png)

**Comment by mourner** [comment]
Leaflet has nothing to do with this — contact the maintainers of the OSM tile server.
