### ISSUE TITLE
Problem adding leaflet map object with dynamically appended div

### ISSUE THREAD

**Issue by spider58** [Leaflet/Leaflet#6394]
Hello. 

I'm facing many problems with dynamically appenden div's which using for leaflet map

for example

```
$(document).body.append("<div id='map2'></div>");

var map2;

  var cartodbUrl = 'https://cartodb-basemaps-{s}.global.ssl.fastly.net/dark_all/{z}/{x}/{y}{r}.png',
      cartodb = L.tileLayer(cartodbUrl, {
        maxZoom: 7
      }),
      map2= new L.Map("map2", {
        center: new L.LatLng(51.505, -0.04),
        zoom: 7
      }),
      drawnItems = L.featureGroup().addTo(map2);

    L.control.layers({
      "osm": L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: 'osm'
      }),
      'cartodb': cartodb.addTo(map2),
      "google": L.tileLayer('http://www.google.cn/maps/vt?lyrs=s@189&gl=cn&x={x}&y={y}&z={z}', {
        attribution: 'google'
      })
    }, {
      'drawlayer': drawnItems
    }, {
      position: 'bottomleft',
      collapsed: true
    }).addTo(map2);

    map2.on('click', onMapClick2);
```
Tehere is no problem to seeing map on screen. New map seems good. But when i need to access map2 object im getting **undefined** error.

I have no problem with non dynamically created divs. I can see those divs as map object on console.

for example (dynamically appended div)

**function onMapClick2(e) {
    console.log(map2);    // map2 is undefined... Why? i defined it and created a map pobject before.

}**

**Comment by spider58** [comment]
hello. I didn't see you answer because i was working on a jsfiddle sample

http://jsfiddle.net/h50k1gmn/

Can you check this sample please. 

-- click create new map button
--  click on a map
and press f12 and lokk to console.

you can see map2 is not map object. because i created it programmatically.

**Comment by spider58** [comment]
sorry i edited my answer. i wrote wrong jsfiddle link.

**Comment by cherniavskii** [comment]
@spider58 there are *multiple* map instances in the fiddle, but your issue seems to describe the issue related to dynamically created div for *single* map.
Looks like you've mixed up two issues together.

**Comment by spider58** [comment]
@cherniavskii hi.

I want to define map events such as mouseclick, mouseover etc. one time and use them for all map objects.

So, i  have 2 or more map instance thats depends on clients choice. I must append new div for leaflet map object and convert them to a map object when client needs new map.

do you have a solution for this issue? because we cannot acces map features because of divs cannot being map object. Working good on screen, we can see map but as i said we cannot access map features

thanks inadvance

**Comment by cherniavskii** [comment]
Please ask questions on [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you believe it's a Leaflet bug - feel free to submit an issue with good description and example which reproduces the issue.

Regarding fiddle you've provided - not a Leaflet bug.
You've written `onMapClick` function to always add marker to first map (`.addTo(map)`).

**Comment by spider58** [comment]
@cherniavskii problem is not adding marker to map. problem is map2 object is not map object

**Comment by cherniavskii** [comment]
`map2` is reference to DOM node with the same id (that's how DOM works). Try to name variables with names other than container id - and the issue will gone.

But again, that's not specific to Leaflet, it's how JavaScript works.

**Comment by spider58** [comment]
@cherniavskii 

http://jsfiddle.net/h50k1gmn/3/

can you check updated link please. i changes variable name from map2 to **mapxx** . at this time im getting "mapxx is not defined" error on console. console.log(mapxx);

Thanks inadvance

**Comment by spider58** [comment]
@cherniavskii 

i want to add a marker to map which i clicked with mouse. how can i do that.

**Comment by spider58** [comment]
@cherniavskii 

i found problem, codes must be in a function and variables must defined outside ot this function.

worked fiddle here

http://jsfiddle.net/h50k1gmn/4/

thanks
