### ISSUE TITLE
Polygon briefly changes size on first Drag+Zoom using touch

### ISSUE THREAD

**Issue by JoshrlNZ** [Leaflet/Leaflet#6395]
### Versions

- Leaflet version I'm using: 1.3.4
- Browser (with version) I'm using: Chrome 69.0.3497.92
- OS/Platform (with version) I'm using: Ubuntu 18.04.1

This issue also occurs on my Android mobile using Chrome 70.0.3538.64 and on desktop using Firefox 62.0.3.

### Steps to reproduce

1. Load the map. 
2. On a touch device, put one finger down onto the map.
3. Drag the map without lifting your finger.
4. Place another finger on the map.
5. Pinch-zoom with your two fingers.
6. Take both fingers off of the screen.
7. The polygon should transition back to its original size before changing back to its proper size.

## What behaviour I'm expecting and which behaviour I'm seeing

This behaviour only occurs once after the map has loaded. Every time after that occurs how I'd expect.
I'm expecting the polygon to stay at its proper size and transition properly with the map, instead it transitions into a larger size before snapping back to proper size.

## Minimal example reproducing the issue

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

[Here is a Plunker that uses prosthetic-hand to drag and zoom the map.](https://plnkr.co/edit/JUigoRvIfNZg1G4yUXug?p=preview) Click the button below the map to start.

**Comment by cherniavskii** [comment]
Seems very similar to #3798

**Comment by johnd0e** [comment]
> This behaviour only occurs once after the map has loaded.

After #7029 the same behavior can be observed on every pan+pinchzoom: https://gist.githack.com/johnd0e/dd2c9e32a1378b7d0d527d5f7fe9c624/raw/issue-6395.html
(but prosthetic-hand does not function there)

**Comment by johnd0e** [comment]
As appeared, this issue is also reproducible on desktop, with mouse only.

(citation from #6133)
> -press left button and perform some panning
> -use the scrollwheel to change zoom while keeping left mouse button pressed

Perhaps the roots of this issue are common with #7072 and #6099.

**Comment by johnd0e** [comment]
In current the same behavior can be observed on every pan+pinchzoom, see #7401.
