### ISSUE TITLE
load GML on the map

### ISSUE THREAD

**Issue by JePedrosa** [Leaflet/Leaflet#6396]
- Leaflet version I'm using: 1.3.1
- Browser (with version) I'm using: Firefox and Chrome
- OS/Platform (with version) I'm using: Windows

Hello, I want to upload a GML file on the map but I can not find how to do it, could someone help me? Thank you

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
