### ISSUE TITLE
On Firefox, one-finger drag released outside browser causes second drag to zoom

### ISSUE THREAD

**Issue by pjr11** [Leaflet/Leaflet#6401]
## How to reproduce

- Leaflet version I'm using: 1.3.4
- Browser (with version) I'm using: Firefox 63.0.1
- OS/Platform (with version) I'm using: Windows 10 on Microsoft Surface
- Open https://leafletjs.com, scroll down if necessary so you can see the map
- With one finger, touch the map, drag to a point outside the browser window, and release
- Touch with one finger and drag again - this time the map zooms in and out as you drag

## What behaviour I'm expecting and which behaviour I'm seeing

The second drag should just drag the map. Instead the map behaves as for a pinch zoom.

Chrome, Edge and IE11 all behave correctly.

## Minimal example reproducing the issue

As above.

**Comment by johnd0e** [comment]
@pjr11 
Are you still own Surface?
I'd like to fix the issue.

**Comment by johnd0e** [comment]
@adrian-ci @pjr11
Could you check if the issue can be resolved by #7029?

**Comment by Falke-Design** [comment]
Tested with Microsoft Surface Pro 2017 and Firefox 93.0. Is working with the newest master and with the old 1.3.4 version (Video)
https://user-images.githubusercontent.com/19800037/139717422-f4ae69d3-2dd8-4477-9063-0c43804bd77e.mp4
