### ISSUE TITLE
Delete a custom pane and recreate it with Geojson

### ISSUE THREAD

**Issue by zogs** [Leaflet/Leaflet#6408]
## How to reproduce

- Leaflet version I'm using: 1.3.1
- Browser (with version) I'm using: Chrome79
- OS/Platform (with version) I'm using: WIN10
- create a custom pane
- add geojson to it
- remove pane
- recreate pane
- add geojson to it
- no geojson is drawn

## What behaviour I'm expecting and which behaviour I'm seeing

The geojson is not drawn after i deleted the pane and re-created it
(note that with a simple Marker it is normaly drawn) 

## Minimal example reproducing the issue

            let pane = map.createPane('custom');
            L.geoJson(geojson, {pane: 'custom'}).addTo(map);

            L.DomUtil.remove(pane);

            map.createPane('custom');
            L.geoJson(geojson, {pane: 'custom'}).addTo(map);

**Comment by cherniavskii** [comment]
Hi,
The reason why geojson is not rendered second time is that there's an old pane renderer stored in map.
It means that removing pane node from DOM *does not equal* removing the pane from map.

As workaround, you can remove pane renderer from map:
```js
delete map._paneRenderers.custom
```

Maybe adding `removePane` method to map would help, but right now I don't see any use cases for re-adding removed pane back to map.
Feel free to open a feature request with described use cases if applicable.

**Comment by Beuthmaster** [comment]
For me it worked with removing `custom` from `_panes` property like this:
`
delete map._panes.custom
`
To remove the custom pane completely you should also remove it from `_paneRenderers` property:

```
delete map._panes.custom
delete map._paneRenderers.custom

```
