### ISSUE TITLE
Request (documentation) - New simple multi-layers map example

### ISSUE THREAD

**Issue by saturdaywalkers** [Leaflet/Leaflet#6414]
Add a second (simpler) multi-layers map example in the documentation on this page https://leafletjs.com/examples/layers-control/

create 3 layers
create a layers control, add the 3 layers to it,
create a map with the first layer
add the layers control to the map

(why? following the existing layers + overlays example, i'd added all 3 layers to the map at the same time, causing a lot of unnecessary tile requests. It was only the concatanated attributions that eventually alerted me to this)

**Comment by cherniavskii** [comment]
Hi,
Thanks for suggestion, but can you explain how adding 3 layers (your use case) is different than adding 2 layers (current tutorial use case)

**Comment by saturdaywalkers** [comment]
Being new to leaflet (google maps price changes!), I followed the current example to try and create a map with 3  possible layers (A or B or C).
It seemed to work, but I'd managed to add 3 layers to the map all at the same time, causing 3 x (tile requests), with layer 1 hiding layers 2 and 3. 
Hence a suggestion of  a simple 3 layers map example for people to copy, with no overlays (e.g. road / satellite / terrain)

**Comment by johnd0e** [comment]
I believe that current example is good enough.
