### ISSUE TITLE
[Doc] Mistake in SVG documentation

### ISSUE THREAD

**Issue by thib-ack** [Leaflet/Leaflet#6418]
Hello,

There is a little mistake in the SVG section of the documentation.
The same sentence is **written twice**

https://leafletjs.com/reference-1.3.4.html#svg

In the text:
> Although SVG is not available on IE7 and IE8, these browsers support VML (a now deprecated technology), and the SVG renderer will fall back to VML in this case. Although SVG is not available on IE7 and IE8, these browsers support VML, and the SVG renderer will fall back to VML in this case. 

Thanks,
Thibaut.

**Comment by patrickdemers6** [comment]
I have never contributed to a project but am going to try to figure it out and fix this.

**Comment by cherniavskii** [comment]
Surę, go ahead!
This may help https://github.com/Leaflet/Leaflet/pull/6420#pullrequestreview-180243014

**Comment by cherniavskii** [comment]
Closed by #6448
