### ISSUE TITLE
With redraw (), the tiles are not requested again

### ISSUE THREAD

**Issue by longroad1128** [Leaflet/Leaflet#6422]
## How to reproduce

- Leaflet version I'm using: 1.3.4
- Browser (with version) I'm using: chrome 40
- OS/Platform (with version) I'm using: window 10
- step 1
add tileLayer
`    var test=L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
        maxZoom: 18,
        attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' +
        '<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
        'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
        id: 'mapbox.streets'
    }).addTo(mymap);`
- step 2
use redraw()
` setTimeout(function(){
        test.redraw();
    },5000);`
## What behaviour I'm expecting and which behaviour I'm seeing
 the tile are requested  once
![image](https://user-images.githubusercontent.com/17473876/49364846-2e252300-f720-11e8-83cf-3a26a07923fe.png)
if i use redraw(), the tiles should be requested twice

## Minimal example reproducing the issue
`    var mymap = L.map('mapid').setView([51.505, -0.09], 13);

    var test=L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
        maxZoom: 18,
        attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' +
        '<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
        'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
        id: 'mapbox.streets'
    }).addTo(mymap);

 
    setTimeout(function(){
        test.redraw();
    },5000);`
- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

Using http://leafletjs.com/edit.html or any other jsfiddle-like site.

**Comment by songyumeng** [comment]
L.TileLayer.Test = L.TileLayer.extend({
        getTileUrl: function(coords) {
            return L.TileLayer.prototype.getTileUrl.call(this,coords)+"?_t="+new Date().getTime();
        }
    });
    
    var l = new L.TileLayer.Test('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png');


Try it , with a timestamp. But this may not be the best solution.

**Comment by HETCHIT** [comment]
@songyumeng Thx! Yes, it works but a rather unusual solution 🤔

**Comment by Malvoz** [comment]
Is this bug report still accurate? In:

> [Link](https://plnkr.co/edit/t7gs3Ad3PhKDgfquDdwh?p=preview). Request does not start again.

I see that redrawing does in fact re-request tiles. Even in the screenshot in the initial bug report it looks like the tiles have been re-requested.
