### ISSUE TITLE
Question: can't popup info when click marker 

### ISSUE THREAD

**Issue by ghost** [Leaflet/Leaflet#6423]
English is not my native language, please forgive my typo or grammar

## How to reproduce

- Leaflet version I'm using: leaflet Stable version 1.3.4
- Browser (with version) I'm using: Google Chrome 70.0.3538.110
- OS/Platform (with version) I'm using: win10
- step 1 Include leaflet-beautify-marker-icon.js , use L.BeautifyIcon.icon as L.marker icon. Such as:
```
var myIcon= {
    html : '<i class="fa fa-podcast fa-2x faa-flash animated faa-slow"></i>'
}
L.marker(latlng, {icon: L.BeautifyIcon.icon(myIcon)});
```
- step 2
Click the marker  generated by BeautifyIcon
At the moment,browser will output:
```
leaflet-src.js:752 Uncaught TypeError: Cannot read property 'x' of undefined
    at Point._add (leaflet-src.js:752)
    at Point.add (leaflet-src.js:747)
    at NewClass._updatePosition (leaflet-src.js:9453)
    at NewClass.update (leaflet-src.js:9381)
    at NewClass.onAdd (leaflet-src.js:9316)
    at NewClass.onAdd (leaflet-src.js:9574)
    at NewClass._layerAdd (leaflet-src.js:6531)
    at NewClass.whenReady (leaflet-src.js:4398)
    at NewClass.addLayer (leaflet-src.js:6593)
    at NewClass.openPopup (leaflet-src.js:9797)
```
## What behaviour I'm expecting and which behaviour I'm seeing
click the marker can popup info

## How do I solve problems?
I added the code in line 9448
```
if(anchor==undefined || anchor==null){
    anchor = new Point(0,0);
}
```

## Minimal example reproducing the issue

- [x] this example is as simple as possible
- [ ] this example does not rely on any third party code

Using http://leafletjs.com/edit.html or any other jsfiddle-like site.

**Comment by Geek4zD** [comment]
Before version 1.0.3, there was no such problem

**Comment by cherniavskii** [comment]
Closing, since issue author's account has been deleted and it doesn't look like a Leaflet issue.

**Comment by neoacevedo** [comment]
I have a similar issue with the version 1.3.4:
_TypeError: t is null     leaflet.js:5:24340_
I am also using BeautifyIcon, and I add html content to bindPopup method:
`Marker.addTo(map).bindPopup(html).openPopup();`
If I don't set BeautifyIcon inside the marker, the popup simply doesn't show.
