### ISSUE TITLE
Marker.unbindPopup appears to remove DOM node associated with it

### ISSUE THREAD

**Issue by laacz** [Leaflet/Leaflet#6424]
## How to reproduce

- Leaflet version I'm using: 1.3.4
- Browser (with version) I'm using: Chrome
- OS/Platform (with version) I'm using: Windows 10
- Starting with bindPopup(element), not string
- After unbinding #popup element is removed from DOM, which is not desired action if I'd like to reuse it.

## What behaviour I'm expecting and which behaviour I'm seeing

Shouldn't it remain in DOM?

## Minimal example reproducing the issue

https://codepen.io/laacz/pen/pQBgjZ

**Comment by laacz** [comment]
OK, I've made a simpler example: https://codepen.io/laacz/pen/ZmZOjo

1. Click on the button (it binds popup and opens it) any number of times, popup shows up well.
2. Close last popup with "x".
3. Click on the button (no content, since `#popup` is non-existent).

It looks like a design solution (poor, yet understandable) to remove popup content's element from DOM. If that's so, feel free to close this issue.

**Comment by cherniavskii** [comment]
It works as expected.

Instead of adding popup to DOM and querying it, create it in JS and keep reference to it.
Working example: https://codepen.io/anon/pen/rQEEPz
