### ISSUE TITLE
StopLocate () is not valid in the WeChat built-in browser

### ISSUE THREAD

**Issue by liuy666** [Leaflet/Leaflet#6427]
- [ ] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [ ] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [ ] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- step 1
Call the geographic location API locate()
- step 2
set Locate options {watch: true}
- step 3
Call stopLocate() to stop the watch

**Expected behavior**

Expect to stop watch correctly

**Current behavior**

The actual API method is not valid, and it still watching of location changes

**Environment**
- Leaflet version: 1.3.4
- Browser (with version): WeChat built-in browser and WeChat App version 6.7.4
- OS/Platform (with version): iOS 12 in the mobile terminal

**Additional context**

**Minimal example reproducing the issue**

Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

**Comment by cherniavskii** [comment]
Hi,
can you reproduce it in iOS Safari browser?

**Comment by Falke-Design** [comment]
WeChat is not in the supported Browser list and there was no response, so I close this issue
