### ISSUE TITLE
Ability to access placeId parameter from google.maps.api on click event

### ISSUE THREAD

**Issue by damianofusco** [Leaflet/Leaflet#6429]
**Is your feature request related to a problem? Please describe.**
Yes, currently unable to get the placeId parameter when user clicks on a POI icon on the map, as the event returned is always MouseEvent and not IconMouseEvent as described here: https://developers.google.com/maps/documentation/javascript/reference/map#IconMouseEvent
and here
https://developers.google.com/maps/documentation/javascript/examples/event-poi

**Describe the solution you'd like**
The event returned with click by leaflet should include placeId in addition to latLng (see leaflet _fireDOMEvent)

**Describe alternatives you've considered**
Could not find any

**Additional context**
https://developers.google.com/maps/documentation/javascript/examples/event-poi

**Comment by mourner** [comment]
What you are linking to is Google Maps documentation. Leaflet is a different product.

**Comment by damianofusco** [comment]
"You can add the Google Maps API as a Leaflet layer with the GoogleMutant plugin"
https://github.com/Leaflet/Leaflet/blob/master/FAQ.md

Leflet is wrapping the events and somehow only passing MouseEvent instead of IconMouseEvent

**Comment by damianofusco** [comment]
Thank you for the suggestion. I am not sure where the issue is yet.

**Comment by damianofusco** [comment]
This might be related, i'll dig more into that https://stackoverflow.com/questions/46103259/can-default-google-map-click-and-hover-behaviors-be-preserved-when-used-in-leafl

Thank you
