### ISSUE TITLE
chrome:scale blurred

### ISSUE THREAD

**Issue by DYMFbigdata** [Leaflet/Leaflet#6437]
scale(0.85)
![](http://thyrsi.com/t6/637/1545274128x2890174202.png)

scale(1)
![](http://thyrsi.com/t6/637/1545274292x2890174202.png)

**Environment**
- Leaflet version:
- Browser (with version):chrome62
- OS/Platform (with version):

**Comment by IvanSanchez** [comment]
I don't really know what you mean here. Can you please be more specific?

**Comment by Malvoz** [comment]
I think this can be closed due to a lack of response. It may also be a duplicate of https://github.com/Leaflet/Leaflet/issues/6232.
