### ISSUE TITLE
[GridLayer] redraw doesn't draw tiles properly after changing maxNativeZoom

### ISSUE THREAD

**Issue by IvannaBabchanik** [Leaflet/Leaflet#6438]
- [X] I've looked at the [documentation](https://leafletjs.com/reference-1.3.4.html#gridlayer) to make sure the behavior is documented and expected
- [X] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Angular)
- [X] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- Scroll in to level where data is not available. For example somewhere on AtlanticaOcean
- When get "Map data not available" picture set maxNativeZoom to smaller and call TileLayer.redraw() function.

**Expected behavior**
TileLayer redraw all tiles: 
![image](https://user-images.githubusercontent.com/18304028/50282589-f2969280-045b-11e9-8672-7de550c12198.png)

**Current behavior**
TileLayer redraw partly: 
![image](https://user-images.githubusercontent.com/18304028/50282566-d85cb480-045b-11e9-8fdb-2a9c292146db.png)

**Environment**
- Leaflet version: 1.3.4 
- Browser (with version): Chrome 70.0.3538.110 (Official Build) (64-bit)
- OS/Platform (with version): Win 10

**Comment by IvannaBabchanik** [comment]
Please try this [https://plnkr.co/edit/swWcT1Ols0ru14KhZyXh?p=preview](https://plnkr.co/edit/swWcT1Ols0ru14KhZyXh?p=preview)
Steps:
1) Press + button
Observed: Map data not available
2) Press Redraw layer button
Observed: tiles layers not redraw correctly

**Comment by cherniavskii** [comment]
Yup, git bisect points to 1010451a666d5525430c4fbecb2bd870380a31e3
