### ISSUE TITLE
CORS policy: No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by denethor96** [Leaflet/Leaflet#6441]
Hi,

I got this error when I was try to use the API for the map recently:
![captura de pantalla 2018-12-20 a la s 21 05 33](https://user-images.githubusercontent.com/22660639/50317582-1c22de80-049b-11e9-9afe-a6bff46b33ab.png)

Anyone know about this error ?

Cheers !

**Comment by cherniavskii** [comment]
Something with your environment, not a Leaflet issue.
