### ISSUE TITLE
How to use map plugins (via Import) LEAFLET (angular 7) if the api script is dynamically loaded

### ISSUE THREAD

**Issue by novakand** [Leaflet/Leaflet#6444]
How to use map plugins (via Import) LEAFLET (angular 7) if the api script is dynamically loaded and the npm package is not used
Here is the plugin: https://github.com/Leaflet/Leaflet.Editable, don’t know how to use error L

**Comment by cherniavskii** [comment]
Hi!

We use GitHub as an issue tracker.
For usage and support questions, please check out resources below:

1. Read Leaflet documentation: https://leafletjs.com
2. For support questions like "How can I do X with Leaflet?" please search or ask questions on StackOverflow or StackExchange using Leaflet tag:
  - https://stackoverflow.com/questions/tagged/leaflet
  - https://gis.stackexchange.com/questions/tagged/leaflet

Thanks!
