### ISSUE TITLE
[Support] How leaflet send HTTP request to get the tile image?

### ISSUE THREAD

**Issue by baoqger** [Leaflet/Leaflet#6446]
I studied the source code of leaflet and want to know how this works? 
When the zoom level of center of the map changed, new tile image files will be requested. But I didn't find out corresponding code for this function, so how it works? Thanks

**Comment by cherniavskii** [comment]
Here's the corresponding code:
https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/TileLayer.js#L136-L161

Please note, that we use GitHub as an issue tracker.
For usage and support questions, please check out resources below:

1. Read Leaflet documentation: https://leafletjs.com
2. For support questions like "How can I do X with Leaflet?" please search or ask questions on StackOverflow or StackExchange using Leaflet tag:
  - https://stackoverflow.com/questions/tagged/leaflet
  - https://gis.stackexchange.com/questions/tagged/leaflet

Thanks!

**Comment by cherniavskii** [comment]
Also, there's a Gitter chat https://gitter.im/Leaflet/Leaflet
