### ISSUE TITLE
Feature request: Add a 'pane' option to divicon

### ISSUE THREAD

**Issue by MappingSupport** [Leaflet/Leaflet#6453]
My use case.
I want to have a polyline with a **divicon label on top of the polyline**.
The polylines will show a grid for UTM coordinates or MGRS/USNG coordinates.
The lines and labels should be on top of everything except popups.

My attempted solution:
Make a pane for the polylines and give it a zIndex of 675.  
Make a pane for the divicons and give it a zIndex of 676. 

Problem:
The polylines are on top of the divicon labels since **divicon does not recognize 'pane' as an option**.

**API feature request:**
Add a 'pane' option for divicons

My workaround:
Make a pane for the polylines and give it a zIndex of 599.
Since the divicon labels go into the default zIndex of 600, the divicon labels are now on top of the lines.

Now I just need to remember to move any tooltips to a zIndex below the lines and divicons.

**Comment by IvanSanchez** [comment]
No need. Use the pane option on the marker, not on the divicon for the marker.

See https://plnkr.co/edit/xOZiCXuW05zrv0tg2vsk?p=preview

![image](https://user-images.githubusercontent.com/1125786/50598651-aca1eb80-0eab-11e9-8062-65a89d5abc5e.png)

**Comment by MappingSupport** [comment]
Thanks Ivan.
