### ISSUE TITLE
4326坐标系，获取的坐标不对

### ISSUE THREAD

**Issue by danranshizhi** [Leaflet/Leaflet#6456]
要实现室内定位地图，采用imageOverlay，替换底图。文档中，4326坐标系对应wgs84坐标系，通过点击底图上的任意一点，获取该点的经纬度坐标，获取的经纬度坐标为71.53135941850933,-166.376953125，当前位置对应的百度坐标为31.051714,121.241002，请问，这种情况是哪里需要设置吗，新手使用，还请指导一下

**Comment by cherniavskii** [comment]
Hi, please submit issues in English.
Also, please use issue template :)

**Comment by danranshizhi** [comment]
To achieve indoor location map, image Overlay is used to replace the base map. In the document, 4326 coordinate system corresponds to WGS84 coordinate system. By clicking on any point on the bottom map, we can get the longitude and latitude coordinates of the point. The longitude and latitude coordinates obtained are 71.53135941850933, -166.376953125, and the Baidu coordinates corresponding to the current position are 31.051714, 121.241002. Excuse me, where do you need to set up this situation, novice use it, please give us some guidance？
