### ISSUE TITLE
leaftlet 1.4.0 loads out of bound images

### ISSUE THREAD

**Issue by arturaslt** [Leaflet/Leaflet#6461]
>     var mapSW = [0, 4096];
    var mapNE = [4096, 0]

    var map = L.map('map').setView([0, 0], 3);

    L.tileLayer('maps/worldmap/{z}/{x}/{y}.png', {
        minZoom: 3,
        maxZoom: 4,
        continuousWorld: false,
        noWrap: true,
        crs: L.CRS.Simple
    }).addTo(map);

    var bounds = new L.LatLngBounds(
        map.unproject(mapSW, map.getMaxZoom()),
        map.unproject(mapNE, map.getMaxZoom())
    );

    map.setMaxBounds(bounds);

    map.on('drag', function () {
        map.panInsideBounds(bounds, { animate: false });
    });
    // var refmarker = L.marker(map.unproject([1500, 1500], map.getMaxZoom()), {
    //     draggable: true
    // }).addTo(map).bindPopup('');

    var refmarker = L.marker([70, -180], {
        draggable: true
    }).addTo(map).bindPopup('');

    refmarker.on('dragend', function (e) {
        refmarker.getPopup().setContent('Pixels ' + map.project(refmarker.getLatLng(), map.getMaxZoom().toString())).openOn(map);
    });

    var marker_heroes = L.marker(map.unproject([1500, 1500], map.getMaxZoom())).bindPopup('<b>Som heroes!</b>');

    var marker_heroe2 = L.marker(map.unproject([1700, 1800], map.getMaxZoom())).bindPopup('<b>Som heroes2!</b>');

    var lg_units = L.layerGroup([marker_heroe2]);
    var lg_locat = L.layerGroup([marker_heroes]);

    var overlays = {
        "Creatures": lg_units,
        "Locations": lg_locat
    }

    L.control.layers(null, overlays).addTo(map);

    //DEBUGGER
    // map.on('click', function (e) {
    //     alert(e.latlng);
    // });

It loads negative images from left and right, but not top and bottom ? 
any solution to fix this, seems I can't find anything around this issue

**Comment by cherniavskii** [comment]
I'm closing this, because the quality is not enough. Please use our issue template when submitting a bug report.
