### ISSUE TITLE
Automatic security check finds potential XSS

### ISSUE THREAD

**Issue by tswistak** [Leaflet/Leaflet#6465]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework, I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
We had to perform automatic security tests of all libraries used in our code through Checkmarx software. It has found that attribution text is inserted directly into HTML through innerHTML property (_update function in Attribution class). 
I haven't still tested it if it's possible to perform XSS through this way, but it doesn't prevent the automatic tool from finding an issue here, which it prioritizes as a Medium priority issue (for us it means, we can't ignore it).

**Expected behavior**
It would be nice if automatic security checking tools wouldn't find this issue because due to restriction in some environments, the library can't be used. 

**Current behavior**

**Environment**
- Leaflet version: 1.3.4 ESM
- Browser (with version): -
- OS/Platform (with version): -

**Additional context**
Screenshots from Checkmarx's report:
![image](https://user-images.githubusercontent.com/9076255/50892014-d2744680-13fd-11e9-9589-f0400278fd3c.png)
![image](https://user-images.githubusercontent.com/9076255/50892066-f20b6f00-13fd-11e9-92df-70cbd7583a90.png)

**Comment by ghybs** [comment]
Hi,

Thank you for sharing this report!
It is nice to see no other security issue raised by that tool.

As for the reported one, I am not sure I understand exactly the given description.

The mentioned Leaflet Attribution Control [`addAtribution`](https://leafletjs.com/reference-1.4.0.html#control-attribution-addattribution) method does indeed get a string as argument, which is then inserted in DOM using `innerHTML`. This in itself is a standard practice for UI libraries that empower consumer developers to include formatted content.

As for potential XSS attack, I guess that would require that string to be arbitrary content provided by the attacker, e.g. should it come unsanitized from a user `<input type="text" />`, as suggested by the report message ("_gets user input for the text element [...] without being properly sanitized or validated_").

Let's note first that Leaflet does not provide such user text input at all.

Next, in most cases this method is called with app hard-coded value, e.g.:
```javascript
L.tileLayer('urlTemplate', {
    // Below formatted content string is passed to Attribution Control addAttribution method
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
});
```
...therefore the content is 100% under control of the consumer developer.

As such, it seems to me that it is the consumer developer's responsibility how they use Leaflet library and call such Leaflet method with data sanitized at app level, in the rare case where this data comes from arbitrary source (e.g. end user text input or fetched from remote service).

**Comment by tswistak** [comment]
@ghybs Yes, that's also what I was thinking about. Since it's not something user gets access to, it doesn't need to be sanitized in any way. Especially, that if we would sanitize, we won't be able to set attributions with HTML tags. 

BTW. The tool also found a false-positive division by zero in performZoom: `d4 = snap ? Math.ceil(d3 / snap) * snap : d3`. However, it prioritetizes it as a low priority, so we don't need to take care about it.

**Comment by Falke-Design** [comment]
gyhbs described it good. 

I will close this, if someone thinks this should be re-opened, let us know.
