### ISSUE TITLE
Zoom / move / fit animation fires bad moveend events

### ISSUE THREAD

**Issue by drafu** [Leaflet/Leaflet#6466]
'moveend' event fires after zoom animation ends, but animation handler does not break when we move map WHILE animation is still visualizing.

Quick example:
1. Map initially in BBOX0
2. map.fitbounds(BBOX1); // BBOX1 is close enough to BBOX0
3. Map starts zooming / panning animation
4. (While animation is still in process) map.fitbounds(BBOX2); // BBOX2 is distant, so no animation happens
5. Triggers 'moveend' for BBOX2
6. Timer for BBOX1 animation expires
7. Triggers 'moveend' animation for BBOX1

This causes some troubles.

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?

It's not clear why the `moveend` event for the BBOX2 fires if that animation doesn't happen.

**Comment by IvanSanchez** [comment]
Possibly related to (veyr old) #1289

**Comment by IvanSanchez** [comment]
No more information has been provided, and more than a few weeks have passed. We'll assume this issue is no longer relevant and/or there is no interest to make a better report.
