### ISSUE TITLE
Uncaught TypeError: Cannot create property '_leaflet_id' on number '1'

### ISSUE THREAD

**Issue by OsamaShabrez** [Leaflet/Leaflet#6472]
LayerGroup has a function `hasLayer` which expects either an object or a number documented here: https://leafletjs.com/reference-1.4.0.html#layergroup-haslayer but still querying the function with a number returns an error.

**Steps to reproduce**
1. Create a LayerGroup
2. Call hasLayer with a number which is not within layer ids

**Expected behavior**
A boolean result

**Current behavior**
An error:
```javascript
Uncaught TypeError: Cannot create property '_leaflet_id' on number '1'
    at n (leaflet.js:5)
    at e.hasLayer (leaflet.js:5)
    at <anonymous>:1:5
```
**Environment**
- Leaflet version: 1.4.0
- Browser (with version): Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)
- OS/Platform (with version): Windows 10 Pro 64bit 1803 build 17134.472

**Minimal example reproducing the issue**
https://plnkr.co/edit/Qj6MILR7GplmVaQV3yGl

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by OsamaShabrez** [comment]
I decided to use `getLayer` https://leafletjs.com/reference-1.4.0.html#layergroup-getlayer which returns the layer with the given id or undefined.

**Comment by kumbraGrr** [comment]
Same problem here...

**Comment by OsamaShabrez** [comment]
@kumbraGrr you can use getLayer https://leafletjs.com/reference-1.4.0.html#layergroup-getlayer.

**Comment by aricooperdavis** [comment]
This should be a pretty easy fix, but is definitely a bug - see the [`LayerGroup Methods`](https://leafletjs.com/reference-1.6.0.html#featuregroup-haslayer) documentation.
