### ISSUE TITLE
Leaflet 1.4.0 in Maven-Repository

### ISSUE THREAD

**Issue by tademeit** [Leaflet/Leaflet#6475]
Hello together,

do you know when the version 1.4.0 will be in the global maven repository? The current version there is still 1.3.1?

Greetings,
Timo Nohe

**Comment by IvanSanchez** [comment]
The Leaflet maintaiers handle downloads on leafletjs.com, and the NPM packages. We're not responsible for stuff uploaded to the global maven repo.
