### ISSUE TITLE
Map container not found

### ISSUE THREAD

**Issue by mueedahmed1** [Leaflet/Leaflet#6476]
` L.map('map').setView([40,-4], 6);`

Error occur in above line it is define in typescript file in angular component

html div with id is already define 
`<div leaflet 
[leafletOptions]="options"
id="map"
style="height: 50vh;">`

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.

**Comment by asif986** [comment]
In angular 11  you use the  plain  leaflet  js lib.

*1. make sure your div id is same as you can implement the ts code. for example

  <div id="map"></div>
      let mymap = L.map('map').setView(latLong, 13);
 (pass the latlang array in that) or simply add - var mymap = L.map('mapid').setView([51.505, -0.09], 13);

2.Remember make sure you can define the height so, that why your map can show in your page.

Thank you leaflet
