### ISSUE TITLE
1.4.0 wrapping(?) problem 

### ISSUE THREAD

**Issue by ThreeStepsAhead** [Leaflet/Leaflet#6481]
I've created an interactive map using leaflet and its working fine using xampp on my localhost. Today I registered a domain and uploaded everything to a webspace and suddenly the map starts repeating itself on the x-axis for half it its size on the left side before the 'real' map starts. 
The image size is 4096x4096 and is loaded as follows:
`var mapSW = [0, 4096],
    mapNE = [4096, 0];
var map = L.map('map').setView([0,0],1);
L.tileLayer('maps/emptyGrid/{z}/{x}/{y}.png', {
  minZoom: 1,
  maxZoom: 4,
  continousWorld: false,
  noWrap:true,
  crs: L.CRS.Simple,
}).addTo(map)

map.setMaxBounds(new L.LatLngBounds(
  map.unproject(mapSW, map.getMaxZoom()),
  map.unproject(mapNE, map.getMaxZoom())
  ));`
**After hours of try and error I downgraded from 1.4.0 to 0.7.7 and it works as intended.**

**Comment by IvanSanchez** [comment]
The `crs` option belongs to the map, not to the tilelayer. Read the documentation again.

**Comment by YinYongHongYork** [comment]
> I've created an interactive map using leaflet and its working fine using xampp on my localhost. Today I registered a domain and uploaded everything to a webspace and suddenly the map starts repeating itself on the x-axis for half it its size on the left side before the 'real' map starts. The image size is 4096x4096 and is loaded as follows: `var mapSW = [0, 4096], mapNE = [4096, 0]; var map = L.map('map').setView([0,0],1); L.tileLayer('maps/emptyGrid/{z}/{x}/{y}.png', { minZoom: 1, maxZoom: 4, continousWorld: false, noWrap:true, crs: L.CRS.Simple, }).addTo(map)
> 
> map.setMaxBounds(new L.LatLngBounds( map.unproject(mapSW, map.getMaxZoom()), map.unproject(mapNE, map.getMaxZoom()) ));` **After hours of try and error I downgraded from 1.4.0 to 0.7.7 and it works as intended.**

how to deploy leaflet on Xampp?
