### ISSUE TITLE
Control.Layers not working with many maps in 1.4.0

### ISSUE THREAD

**Issue by jjimenezshaw** [Leaflet/Leaflet#6482]
Since Leaflet 1.4.0, if you have many maps with Control.Layers, the radio button from one map is deselected when selecting a layer on the other map

- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- Create two maps, both with Control.Layers
- Select one layer in map 1
- Check what happened with the radio buttons on map 2

**Expected behavior**
Radio buttons on other maps are not affected

**Current behavior**
Radio buttons on the other map are deselected.

**Environment**
- Leaflet version: 1.4.0
- Browser (with version): Chromium 71.0.3578.98
- OS/Platform (with version): Ubuntu 16.04

**Additional context**
Looks like after #6380 , the context of the radio buttons is not the form in each Control.Layers (so they are independent), but a global one. Then name="leaflet-base-layers" is not specific per control.

**Minimal example reproducing the issue**
https://next.plnkr.co/edit/Q5ofJZJZLrOwAyZg

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by josegus** [comment]
Same here, using the simple quickstart is not working
