### ISSUE TITLE
getBounds() for GeoJSON Feature?

### ISSUE THREAD

**Issue by VladimirKalachikhin** [Leaflet/Leaflet#6484]
`polyline.getBounds()` - it's OK
`polyline.toGeoJSON().getBounds()` produce a error:
_TypeError: polyline.toGeoJSON(...).getBounds is not a function_

About polyline [doc](https://leafletjs.com/reference-1.4.0.html#polyline) say:
"toGeoJSON() | ... | Returns a GeoJSON representation of the polyline (as a GeoJSON LineString or MultiLineString Feature)."
but about GeoJSON.getBounds() doc say:
"getBounds() | ... | Returns the LatLngBounds of the Feature Group"

Ok, Feature is not a Feature Group, but that polyline.getBounds() is ok, but polyline.toGeoJSON().getBounds() is not ok - no good by my opinion.

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?

**Comment by VladimirKalachikhin** [comment]
https://next.plnkr.co/edit/xXvcjapPHdc157ZL?preview

**Comment by IvanSanchez** [comment]
`toGeoJSON` returns a [GeoJSON representation](http://geojson.org/) of the polyline, **not** an instance of `L.GeoJSON.`. This is behaviour as expected.
