### ISSUE TITLE
Removing map that has a tileLayer with minZoom set causes an error - undefined is not an object (evaluating 'el.style')

### ISSUE THREAD

**Issue by bradcrawford** [Leaflet/Leaflet#6486]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
https://codesandbox.io/s/ywn94996wj

1. Zoom out to the point where the high res tileLayer (url set to cloudfront) disappears due to it's minZoom setting.
2. Click the Hide button.
3. Error (see image below)
4. Remove `minZoom: 18`
5. Repeat steps 1 & 2 above
6. No error

**Expected behavior**
When using a tileLayer with minZoom set and the map zoomed out beyond the value of minZoom, removing the map should not cause an error

**Current behavior**
When using a tileLayer with minZoom set and the map zoomed out beyond the value of minZoom, removing the map causes an error

<img width="488" alt="screen shot 2019-01-22 at 9 41 46 pm" src="https://user-images.githubusercontent.com/558730/51522584-95449580-1e8e-11e9-8953-baf6373f2073.png">

**Environment**
- Leaflet version: 1.4.0
- Browser (with version): Safari 11.0.1
- OS/Platform (with version): Mac OS Sierra 10.12.6

**Additional context**
Uncovered while using ReactLeaflet, initial bug report here - https://github.com/PaulLeCam/react-leaflet/issues/551. Further investigation revealed that it appears to be a Leaflet issue.

**Minimal example reproducing the issue**

https://codesandbox.io/s/ywn94996wj

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by bradcrawford** [comment]
I don't believe so @IvanSanchez. I get the same error in the console in all 3 browsers. This gif is from chrome.

![steps-to-reproduce](https://user-images.githubusercontent.com/558730/51562967-f781b280-1eef-11e9-9fc5-78c991223787.gif)

Here is a slightly simpler example that errors for me in both Chrome 71 and Firefox 60 - https://plnkr.co/edit/T4qExnzu7KzbDJkIZlJK?p=preview

**Comment by cherniavskii** [comment]
I confirm.

Looks like `_destroyAnimProxy` gets called before `zoomend` handler:

**Comment by tkurki** [comment]
This is pretty bothersome, as it will kill an unsuspecting (=not expecting errors from a normal operation) React app hiding/removing a React Leaflet Map: https://github.com/PaulLeCam/react-leaflet/issues/625

This is the simplest reproduction I can think of in case it is any help: https://codepen.io/tkurki/pen/XWWNBmr

**Comment by Malvoz** [comment]
> This is the simplest reproduction I can think of in case it is any help: https://codepen.io/tkurki/pen/XWWNBmr

Not able to reproduce using v1.8.0: https://plnkr.co/edit/SudJnPOVbG7Y901P?preview
