### ISSUE TITLE
Zoom animation for multiple TileLayer overlays is not synchrone on IE and Edge

### ISSUE THREAD

**Issue by occcy** [Leaflet/Leaflet#6490]
I created a map with two different TileLayer overlays:

```html
<div id="map" style="width: 100%; height: 800px"></div>
```

```javascript
    var map = L.map("map").setView([51, 9], 13);
    var layer1 = L.tileLayer("",   //<- URL1
        {
            maxZoom: 18
        }).addTo(map);
    var layer2 = L.tileLayer("",  // <- URL2
        {
            maxZoom: 18
        }).addTo(map);
```

When I zoom the map the zoom animation for the first TileLayer works like expected. The animation for the second TileLayer playes lagged.

It seems that this problem relates only to IE (Version 11) and Microsoft Edge (Version 42). Also tested with Google Chrome (Version 59), here works everything fine...

No special options or any stylesheet modifications.

**Comment by jonkoops** [comment]
Closing this issue as we have decided to drop support for Internet Explorer in a future version of Leaflet (see #6136).
