### ISSUE TITLE
Mouseover event (sometimes) not fired with circleMarker and Firefox 64.0.

### ISSUE THREAD

**Issue by jcoupey** [Leaflet/Leaflet#6493]
**Steps to reproduce**
1. Check out [this fiddle](http://jsfiddle.net/fcas8k2m/4/)
2. Drag the map to change its center
3. Roll the mouse over the circle marker

**Expected behavior**
An alert should be displayed via the `mouseover` event handler.

**Current behavior**
No alert is displayed, and the pointer shape does not change as it usually does with mouse over.

**Environment**
- Leaflet version: 1.4.0
- Browser (with version): firefox 64.0
- OS/Platform (with version): Ubuntu 18.04

**Additional context**
- This does not happen using chromium.
- This does not always happen with other marker coordinates.
- This does not happen if you skip step 2.
- The unexpected behaviour disappears when zooming out or in.

**Minimal example reproducing the issue**
http://jsfiddle.net/fcas8k2m/3/

**Comment by IvanSanchez** [comment]
Can confirm. Might be an upstream bug, worth isolating further.

**Comment by jcoupey** [comment]
> Duplicate of #5773 (and #5967).

Sorry I didn't find those while browsing the existing issues.

> This is already fixed in Firefox (works in Nightly) and will be released with Firefox 65.

Great news, thanks for the work in the mentioned tickets, closing here.
