### ISSUE TITLE
How can i auto load the Symbols every time i put a new json file

### ISSUE THREAD

**Issue by ppaulerrol** [Leaflet/Leaflet#6495]
guys need help! im a beginner in using the Leaflet.. 
I need to Auto load the symbols when every time i put a new Json file. 
and not be able to click the Reload the page.. sorry for my english.
and also when i zoom the map it will not go back at the default zoom.

**Comment by ppaulerrol** [comment]
this is my codes.
```
<script>
function init(){
    var osmAttr = '&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>';    
    var OSM = L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {maxZoom: 25, attribution: osmAttr}),
        latlng = L.latLng(12.8797,121.7740);
    var map = L.map('map', {center: latlng, zoom: 5, layers: [OSM]});

    var iconSize = {"C":15,"D":20,"E":25,"F":30,"G":35,"H":40,"I":45};

    L.geoJson(situation, {
        pointToLayer: function (feature, latlng) {
        
            var mysymbol = new ms.Symbol(
                feature.properties.SIDC,{
                    size:iconSize[(feature.properties.SIDC).charAt(11)],
                    uniqueDesignation:feature.properties.name
                })
                
            var myicon = L.divIcon({className: '', 
                html : mysymbol.asSVG(), 
                iconAnchor: new L.Point(mysymbol.getAnchor().x, mysymbol.getAnchor().y)});
                
            return L.marker(latlng,{icon:myicon, draggable:false});
        }
    }).addTo(map);
}
</script>
```

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
