### ISSUE TITLE
Invalid LatLng after pan

### ISSUE THREAD

**Issue by lossius30** [Leaflet/Leaflet#6506]
- I've looked at the documentation to make sure the behavior is documented and expected
- I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- I've searched through the issues to make sure it's not yet reported
- I don't know if it's an real issue or just a normal behavior

**Steps to reproduce**
- Go https://leafletjs.com/examples/quick-start/example-basic.html
- Open dev tools
- Write : mymap.setZoom(1)
- Write : mymap.getCenter()
Object { lat: 51.505, lng: -0.09 }
- Pan to WEST many times
- Write : mymap.getCenter()
Object { lat: -34.30714385628803, lng: 4283.437500000001 }

**Expected behavior**
Get the "real" coordinates

**Current behavior**
Returned lat is not as expected (or it's normal ?)

**Environment**
- Leaflet version:  1.4.0 

Sorry if normal behavior, but in this case how to get the coordinates before pan ?

**Comment by IvanSanchez** [comment]
Behaviour as intended. Use the [`worldcopyjump` option](https://leafletjs.com/reference-1.4.0.html#map-worldcopyjump).

**Comment by ebrensi** [comment]
Why the #@%^$ would anyone want the default behavior? It took me a while to figure out what was wrong here.  Anyway whatever.  Thanks for bringing this up @lossius30.
