### ISSUE TITLE
Can't get your simple quickstart running

### ISSUE THREAD

**Issue by heliosnarcissus** [Leaflet/Leaflet#6510]
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>title</title>
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.4.0/dist/leaflet.css"
        integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA=="
        crossorigin=""/>

         <!-- Make sure you put this AFTER Leaflet's CSS -->
        <script src="http://unpkg.com/leaflet@1.3.1/dist/leaflet.js"></script>
        <script src="js/leaflet-providers.js"></script>
  </head>
  <body>
        <div id="mapid"></div>

     <script>
        var mymap = L.map('mapid').setView([51.505, -0.09], 13);
                    L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
                attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
                maxZoom: 18,
                id: 'heliosnarcissus.l937n12c',
                accessToken: 'pk.eyJ1IjoiaGVsaW9zbmFyY2lzc3VzIiwiYSI6ImNqczBjZDYxOTFpNGg0M284dWloa2IybmUifQ.09Dlr4KVxDg1-8yoPBEpzA'
            }).addTo(mymap);

      </script>
        <style>
           #mapid { height: 180; }
       </style>

  </body>
</html>
```

All I'm getting is Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by IvanSanchez** [comment]
* You're referring to a local JS file at `js/leaflet-providers.js` which may not exist
* CSS [length](https://developer.mozilla.org/en-US/docs/Web/CSS/length) properties (i.e. [`height`](https://developer.mozilla.org/en-US/docs/Web/CSS/height)) must have an unit (e.g. `180`**`px`**)
* Beware using custom map IDs for mapbox (i.e. `heliosnarcissus.l937n12c`). Your code works using `mapbox.streets`, which is mentioned in the quickstart. (See https://jsbin.com/vuxeyuyema/edit?html,output ). For issues using mapbox raster tiles with custom map IDs, refer to mapbox support.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by josegus** [comment]
I've used leaflet before, but now the current version is not working. Using the cdn (no, my cdn is not broken) i get the following:
![image](https://user-images.githubusercontent.com/13947849/53700147-c7b6ac00-3dc5-11e9-8351-d3a8b9885708.png)

No console errors, controls not working, tile not working (i'm using the quick start OSM tile demo)
