### ISSUE TITLE
Canvas mouseover issue with line weight on horizontal and vertical lines

### ISSUE THREAD

**Issue by Jadaw1n** [Leaflet/Leaflet#6514]
- [X] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [X] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [X] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- Create Canvas Map with GeoJSON Layer with some lines
- Add mouseover/mouseout events to GeoJSON objects
- The mouseover function makes lines thicker / mouseout makes them thinner

**Expected behavior**
As long as the mouse is on the line, even when it is thicker, the mouseover Event should stay active.

**Current behavior**
For the diagonal lines it works well. Horizontal and vertical lines lose their mouseover status as soon as the mouse goes out of the original (thinner) line.
QuickEdit: I just found out that the problem arises as well when going over the ends of the lines. This happens on all the lines.

**Environment**
- Leaflet version: 1.4.0
- Browser (with version): Chrome 71 and Firefox 65
- OS/Platform (with version): Win 10

**Additional context**
Depending on the thickness there's an additional problem that the thicker line isn't fully erased when going back to thin again (see example).

**Minimal example reproducing the issue**
http://jsfiddle.net/a6eLkdbc/6/

- [X] this example is as simple as possible
- [X] this example does not rely on any third party code

**Comment by IvanSanchez** [comment]
Can confirm.

Hhhmmm, that's some weird behaviour you've uncovered. :thinking:
