### ISSUE TITLE
the leaftlet map not reload new coordinat on modal

### ISSUE THREAD

**Issue by adjieq77** [Leaflet/Leaflet#6515]
this is my problem I was explained in stackoverflow

[link](https://stackoverflow.com/questions/54702061/the-leaftlet-map-not-reload-new-coordinat-on-modal)

Thanks! for help

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
