### ISSUE TITLE
ReferenceError: L is not defined (but only on first load)

### ISSUE THREAD

**Issue by taewookim** [Leaflet/Leaflet#6518]
i'm using leaflet as part of an embedddable widget on 3rd party sites

The first page load shows console error: 

> ReferenceError: L is not defined (but only on first load)

However, when I refresh the page, the error goes away.

Example:

(please copy/paste this URL into browser after enabling chrome developer mode)
https://www.firedamagedproperties.com/fire-stats/widget/

Any ideas what I did wrong?

The non-compressed version of the embed widget JS: https://www.firedamagedproperties.com/map/widget.uncompressed.js

**Comment by IvanSanchez** [comment]
Smells like a race condition. Ensure the resources are loaded before using them.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
