### ISSUE TITLE
mobile: map click event temporary not firing when map leaved and reenter

### ISSUE THREAD

**Issue by Arnaud49** [Leaflet/Leaflet#6519]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
Create a map on mobile device.
Push a new page and then go back to the main page with the map.
The map click event is not firing for a couple of sec, but you can interact with the map and move it.
The movestart and moveend event work perfectly.
The markers click event is not firing as well.

**Expected behavior**
The map click event should be firing.
The marker click event should be firing.

**Current behavior**
The map click event is not firing for 2sec and then works properly.
The marker click event is not firing for 2sec and then works properly.

**Environment**
- Leaflet version: 1.4.0
- Browser (with version): working fine
- OS/Platform (with version): ios and android with ionic cordova

**Additional context**
I tried with 1.3.x same problem.

**Minimal example reproducing the issue**
The bug is only reproductible on mobile device.

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

**Comment by Arnaud49** [comment]
no one to help me ?

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.

**Comment by IvanSanchez** [comment]
We put the "I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)" checkbox for a reason, and it seems that your problem happens only in Ionic/Cordoba but not on browsers.
