### ISSUE TITLE
Error about API

### ISSUE THREAD

**Issue by applibs** [Leaflet/Leaflet#6523]
I used last version 1.4.0 with this plugin.
https://github.com/ranelpadon/ckeditor-leaflet

I used is in CKEditor like plugin and when I search address, it will not search and it generate this erroro URL.
I nowhere found how to resolve my problem.

https://developers.google.com/maps/documentation/javascript/error-messages?utm_source=places_js&utm_medium=degraded&utm_campaign=keyless#api-key-and-billing-errors

What am I dooking wrong?

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.

**Comment by IvanSanchez** [comment]
Problem might be related to https://github.com/ranelpadon/ckeditor-leaflet , but not to Leaflet itself.
