### ISSUE TITLE
openPopup doesn't correct work if you create popup in on click listener

### ISSUE THREAD

**Issue by ZhukDmitry** [Leaflet/Leaflet#6527]
Hi.
I create popup on the fly (by ajax request).
I create marker, and add listener on click, get by ajax details what I need to do on click.
For example, I need to open Popup. In this case I create popup and show it. 
All work correctly, but I don't need to do ajax every time, ie I saved what I have to do (open popup), and the next click I just tries to open popup.

The code like (I create for example simple code)

 

	marker.zhomPlacemarkConfigLoaded = 0;
	
	marker.on('click', function(event) {
		
		if (this.zhomPlacemarkConfigLoaded == 1)
		{
			this.openPopup();
			// uncomment to see popup
			//alert("Popup here");
		}
		else
		{
		// here ajax request and create popup
			this.bindPopup("Hello world<br />Hello world<br />Hello world<br />Hello world<br />Hello world<br />Hello world<br />Hello world<br />Hello world<br />!");
			this.openPopup();
			this.zhomPlacemarkConfigLoaded = 1;
		}
	});

If I bind popup before on("click"),  and in listener just set its content and open popup - all works, but I can't apply popup style (it can be different for deffirent markers), but there is no any method to change popup style.

I fixed this problem by binding popup every time (save got parameters from ajax in marker attributes) and bind it in first part of my IF.
But it is not correct way
**Expected behavior**
Second click on marker just show popup

**Current behavior**
Popup appeared and dismissed, you can only see when stop thread, for example alert or error

**Environment**
- Leaflet version: 1.3.4

**Comment by IvanSanchez** [comment]
That code has race conditions and an unclear context (an un clear value of `this` during the event handler). Not a leaflet bug.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by ZhukDmitry** [comment]
OK. Lets try again.

BugReport v#2

- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using
- [x] I've searched through the issues to make sure it's not yet reported
- [x] I've spended 3 days "танцев с бубном"

**Steps to reproduce**
Bind popup in on("click") event listener

**Expected behavior**
Popup opens each time

**Current behavior**
Popup opens only first time (first click)

**Minimal example reproducing the issue**
_Documentation says_: bind it and you'll get
[Here example](https://jsfiddle.net/DmitryZhuk/xwLnqp7a/) like in docs
It works as expected.

_Real world says_: you'll get what you want, only when click on it. It means scenario
1 - user click on placemark
2 - ajax request gets action, which should be executed
3 - lets it will be show popup
4 - on next click there is no need to execute ajax again, all we have

I removed "this" for your clear context.
I omit ajax request, only show binding popup.

[Here example](https://jsfiddle.net/DmitryZhuk/gdb45qv9/) like I mean

In my real development, I got correct work if I unbind popup in case second call and bind again, but I can't reproduce it in example. Probably, little delays in code.
And when prepared examples **finally** I just add little (can be 0) delay, and code works as expect

[Here example](https://jsfiddle.net/DmitryZhuk/f5u16j3L/) with delay, I set it to 5 miliseconds just to clearance that it is not 0, but with 0 it works too.

And I think it is bug, because popup dismissed unexpectedly, and only adding asynchronious call popup works. But this call doesn't do anything, just delays. And value 0 give us just little time (initialize its structures and code), but enough to your code.

PS I like when users explain me why they use my tools this way and not that. It helps not only to understand, but also create more flexible solution.

Best wishes
Che ;)

**Comment by IvanSanchez** [comment]
This is, impressively enough, expected behaviour.

In a code path like this:

```js
marker.on('click', function(event) {
  if (marker.popupBinded == 0) {
		marker.bindPopup("Hello world!");
    marker.popupBinded = 1;
  }
  marker.openPopup();
});
```

The following things happen:

- A `click` event fires on the marker
- The `click` event handler for the marker runs
- The popup opens
- The `click` event bubbles up to the map
- The `click` event handler for the map runs
- Because the [`closepopuponclick` option on the map](https://leafletjs.com/reference-1.4.0.html#map-closepopuponclick) is still the default `true`, the popup immediately closes.

Either stop event propagation with `L.Util.stop(event)` while inside the click handler for the marker, or set that option to `false`.

Not a bug.

**Comment by IvanSanchez** [comment]
Related: https://github.com/Leaflet/Leaflet/issues/5285

**Comment by ZhukDmitry** [comment]
I added and it fixed.
BUT!
In documentation propagation described only in DomEvent.
I definetely tried 
L.DomEvent.preventDefault
L.DomEvent.stopPropagation
L.DomEvent.stop
And it doesn't work.

L.Util.stop doesn't described.

**Comment by ZhukDmitry** [comment]
I added for map onClick event

https://jsfiddle.net/DmitryZhuk/gdb45qv9/

As you can see, if you click on map - it's fired

But if you click on marker - it is not fired, ie it is not propagated

I added "closePopupOnClick" with false

And it doesn't work.

I think it is BUG :)

**Comment by IvanSanchez** [comment]
> But if you click on marker - it is not fired, ie it is not propagated

It **is** propagated - to the default popup click-on-marker handler, which then stops further propagation to your click-on-map event handler:

https://github.com/Leaflet/Leaflet/blob/93e77bd377badb582c1dd70ad3d5ba22a7c8b061/src/layer/Popup.js#L505-L506

If you bind a popup *during* an event handler, the default click-on-marker handler does not run and therefore does not stop the event. Still behaviour as expected.

**Comment by ZhukDmitry** [comment]
DomEvent.stop(event);   // Works, not described in docs!

L.DomEvent.stop(event);   // [Described in docs](https://leafletjs.com/reference-1.4.0.html#domevent-stop), but doesn't work!

L.Util.stop(event);    // Works, not described in docs!

OK. Lets close discussion, I will use as in your code _DomEvent.stop(event);_

Thanks, 
Dmitry
