### ISSUE TITLE
Tile url on click

### ISSUE THREAD

**Issue by thumbsized** [Leaflet/Leaflet#6529]
I am trying to get the tile url when users clicks on one but after quite a lot of time and googling I haven't found a solution. I tried various combinations of mouseEvenTo..., layer.getTileUrl, projecting and whatnot but neither combination produced valid url so far.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by gorenje** [comment]
Is there a solution other than continuing searching? I too have looked and searched for a simple solution for getting the url for a tile where a click occured and all I can get is the latlng and containerPoint but not mapping to the url of the underlying tile.

Ideally something like this would work:

```
	var popup = L.popup();

	function onMapClick(e) {
		popup
			.setLatLng(e.latlng)
			.setContent("You clicked the map at " + e.latlng.toString() + ' on a tile with url: ' + map.getPanes().tilePane.getTileUrl(e.containerPoint))
			.openOn(map);
	}

	map.on('click', onMapClick);
```
but that doesn't work because `tilePane` is a HTMLElement and not an object of [TileLayer](https://leafletjs.com/reference.html#tilelayer). Doing `map.getPane(map.getPanes().tilePane)` gives me the same HTMLElement

---

In the end, I used `map.project(..)` and a lookup table:

```js
	const coordToFileNameLookup = {}

	const map = L.map('map', {
		center: [0, 0],
		zoom: 0,
	    minZoom: 0,
	    maxZoom: 32,
		tileSize: 256
	});

	L.GridLayer.DebugCoords = L.GridLayer.extend({
		createTile(coords, done) {
			const tile = document.createElement('div');

			var tileSize = this.getTileSize();
	        tile.setAttribute('width', tileSize.x);
	        tile.setAttribute('height', tileSize.y);

			setTimeout(async () => {
	            const img = document.createElement('img')
				let resp = await fetch(`//localhost:1880/leaflet/getimagename/${coords.x}/${coords.y}/${coords.z}`)

				coordToFileNameLookup[coords.x] ||= {}
				coordToFileNameLookup[coords.x][coords.y] = resp.headers.get("location").split("/").reverse()[0]

				img.src = resp.headers.get("location")
				img.width = tileSize.x
				img.height = tileSize.y
				img.style.width = `${tileSize.x}px`
				img.style.height = `${tileSize.y}px`
				img.style.position = "absolute"
				
				tile.appendChild(img)

				done(null, tile); // Syntax is 'done(error, tile)'
			}, 500 + Math.random() * 1500);

			
			return tile;
		}
	});
	
	L.gridLayer.debugCoords = function (opts) {
		return new L.GridLayer.DebugCoords(opts);
	};

	const debugCoordsGrid = L.gridLayer.debugCoords({ 
		tileSize: map.options.tileSize,
    	maxZoom: map.options.maxZoom,
	    minZoom: map.options.minZoom,
		noWrap: true
	});

	map.addLayer(debugCoordsGrid);

	var popup = L.popup();

	function onMapClick(e) {
		let crd = map.project(e.latlng, map._zoom)
		let xCoord = Math.floor(crd.x / map.options.tileSize) 
		let yCoord = Math.floor(crd.y / map.options.tileSize) 

		let filename = coordToFileNameLookup[xCoord] && coordToFileNameLookup[xCoord][yCoord]

		popup
			.setLatLng(e.latlng)
			.setContent(`looking at ${filename}`)
			.openOn(map);
	}

	map.on('click', onMapClick);
```
