### ISSUE TITLE
[BUG] Base map loses selection with two or more maps

### ISSUE THREAD

**Issue by JanLoebel** [Leaflet/Leaflet#6533]
Hi there,

it seems that there is a bug in 1.4.0 with the Layer.Controls. If I have two maps on one page, the base layer can only be selected in one of the two maps. If I click on it on the other map, it get's deactivated. With 1.3.4 this wasn't the case. I've created a jsfiddle to reproduce the error easily.

**Steps to reproduce**
- Create two maps on one page with two base layers in the Layers.Control (see jsfiddle below)

**Expected behavior**
- Each Layers.Control handle it base layers separately.

**Current behavior**
- The base layer seems to interfere with each other.

**Environment**
- Leaflet version: 1.4.0
- Browser (with version): Safari/Chrome/Firefox
- OS/Platform (with version): OSX 10.14

**Minimal example reproducing the issue**

- Example 1.4.0 (broken):
  https://jsfiddle.net/3yLj8adz/7/

- Example: 1.3.4 (works):
  https://jsfiddle.net/3yLj8adz/8/

**Comment by siimots** [comment]
Duplicate: https://github.com/Leaflet/Leaflet/issues/6482

Fixed in: https://github.com/Leaflet/Leaflet/pull/6483

Wait for new release or use old one for awhile.

**Comment by JanLoebel** [comment]
Great, Thanks!
