### ISSUE TITLE
"pane" options doesn't work for geoJSON whose type is "Point"

### ISSUE THREAD

**Issue by yxfcn** [Leaflet/Leaflet#6536]
I found the "pane" option doesn't work for L.geoJSON whose type is "Point".
The source codes of L.geoJSON doesn't pass "options" when create L.marker
```
export function geometryToLayer(geojson, options) {
.....
switch (geometry.type) {
	case 'Point':
		latlng = _coordsToLatLng(coords);
		return pointToLayer ? pointToLayer(geojson, latlng) : new Marker(latlng); // lose options parameter

	case 'MultiPoint':
		for (i = 0, len = coords.length; i < len; i++) {
			latlng = _coordsToLatLng(coords[i]);
			layers.push(
				pointToLayer ? pointToLayer(geojson, latlng) : new Marker(latlng);// lose options parameter
			);
		}
		return new FeatureGroup(layers);
....
```
 I think it should be:

```
export function geometryToLayer(geojson, options) {
.....
switch (geometry.type) {
	case 'Point':
		latlng = _coordsToLatLng(coords);
		return pointToLayer ? pointToLayer(geojson, latlng) : new Marker(latlng,options);

	case 'MultiPoint':
		for (i = 0, len = coords.length; i < len; i++) {
			latlng = _coordsToLatLng(coords[i]);
			layers.push(
				pointToLayer ? pointToLayer(geojson, latlng) : new Marker(latlng,options)
			);
		}
		return new FeatureGroup(layers);
....
```

**Comment by ronikar** [comment]
I looked at the code and I think that you wrong. The options in this case is [GeoJSON options](https://leafletjs.com/reference-1.4.0.html#geojson-option).
I don't understand why `Polyline` and `Polygon` get this options, and I think it's incorrect. 
I suggest that `GeoJSON options` will contain a field for `Marker | Point | Polygon` options.

**Comment by yxfcn** [comment]
@ronikar The [ GeoJSON options](https://leafletjs.com/reference-1.4.0.html#geojson-pane) contains "pane" which inherited from [Layer](https://leafletjs.com/reference-1.4.0.html#layer). The "pane" option will not work before I modified the source code.

**Comment by yxfcn** [comment]
@ronikar You're right. I read the document about the [geojson layer](https://leafletjs.com/examples/geojson/). The doucment has descripted "pointToLayer":
"Points are handled differently than polylines and polygons. By default simple markers are drawn for GeoJSON Points. We can alter this by passing a pointToLayer function in a GeoJSON options object when creating the GeoJSON layer."
Here's a example:
```
var geojsonMarkerOptions = {
    radius: 8,
    fillColor: "#ff7800",
    color: "#000",
    weight: 1,
    opacity: 1,
    fillOpacity: 0.8
};

L.geoJSON(someGeojsonFeature, {
    pointToLayer: function (feature, latlng) {
        return L.circleMarker(latlng, geojsonMarkerOptions);
    }
}).addTo(map);
```

**Comment by ronikar** [comment]
@yxfcn I am happy for you, but still I don't like `options` passes to `Polygon` and `Polyline`. It's confusing and unclear. I prefer to pass a function that will return options for `Marker`, `Polygon` and `Polyline`  in `GeoJSON options`.
