### ISSUE TITLE
Prevent map from panning after adding a new marker (circle)

### ISSUE THREAD

**Issue by thzois** [Leaflet/Leaflet#6537]
Hello, 

I am using Leaflet.js with Angular 7 and I am encountering a weird behaviour with map and markers. I have a map where I spawn multiple markers and I update their location every 5 seconds. The problem is that after I zoom a lot in one of the markers (within those 5 seconds) in the point that I am "losing" every other marker from the map, whenever I update marker's location the map loses the panning and drives me to the last updated marker.

The first thing that I do is to create the map. Then, I call the generateMapMarkers every 5 seconds to update the markers.

```typescript
  ngOnInit() {
    this.generateMap();

    // Execute every 5 seconds and generate the markers on the map
    this.subscription = timer(0, 5000).subscribe(val => {
      this.generateMapMarkers();
    });
  }


  generateMap() {
    // Min and max zoom levels
    map = new L.Map('map', {
      minZoom: this.minZoom,
      maxZoom: this.maxZoom
    });

    if (position) {
      // Current position view
      map.setView([position.coords.latitude, position.coords.longitude], this.locationZoom);
    } else {
      // World view
      map.setView([48.50, 10.55], this.minZoom);
    }

    // Map tile server
    //L.tileLayer('http://localhost/tile/{z}/{x}/{y}.png',
    L.tileLayer('https://c.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      attribution: '© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);

    // Disable map scroll zoom
    map.scrollWheelZoom.disable();
  }


  // Create new markers only once
  // Update the location multiple times
  generateMapMarkers() {
    this._deviceService.list().subscribe(devices => {
      this.devices = devices;

      if (this.devicesHaveMarkers === false) {
        // Generate the marker
        const marker = new L.circle([device.location.latitude, device.location.longitude], {
          name: 'device',
          id: device.id,
          color: 'red',
          fillColor: 'red',
          fillOpacity: 0.5,
          latitudeDeviation: device.location.latitudeDeviation,
          longitudeDeviation: device.location.longitudeDeviation
        }).setRadius(1000).addTo(map);

        // Create the popup window for each marker
        // it has the device name
        const popup = new L.popup({
          autoClose: false,
          closeOnClick: false,
          keepInView: false
        }).setContent(device.name);

        // Bind popup to marker
        marker.bindPopup(popup).openPopup();

      } else {
        // Update marker position and color
        map.eachLayer(function (layer) {
          // Get the specific marker
          if (layer.options.name === 'device' && layer.options.id === device.id) {
            layer.setStyle({ color: 'green', fillColor: 'green' });
            layer.setLatLng([device.location.latitude, device.location.longitude]);
          }
        });
      }
    });
  }
```

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.

**Comment by thzois** [comment]
Hello,

It turned out that it was not a bug. The solution is to add to the popup the option autoPan: false. By default its true. Even if I was creating the popups only at start, it was causing the map to pan to the last created marker.
