### ISSUE TITLE
White lines between tiles

### ISSUE THREAD

**Issue by nijs9** [Leaflet/Leaflet#6541]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

EDIT: this issue is reported for years, but I can't find a solution (except a css hack, but tiles become blurry when using that). I've tested in latest version (1.4.0), problem is still present.

**Steps to reproduce**

View a Leaflet map in Chrome or Safari on a Mac

**Expected behavior**

A clean view of map without white lines.

**Current behavior**

White lines between tiles appear.

**Environment**
- Leaflet version: 1.3.1 (also tested in 1.4.0)
- Browser (with version): Chrome v72.0.3626.119
- OS/Platform (with version): macOS Mojave (10.14.2)

**Additional context**

Example:

![schermafbeelding 2019-03-04 om 11 07 34](https://user-images.githubusercontent.com/10425157/53726499-5a128a80-3e6e-11e9-9b89-8c69dbfdb050.png)

**Comment by siimots** [comment]
Duplicate: https://github.com/Leaflet/Leaflet/issues/3575

**Comment by IvanSanchez** [comment]
Closing as duplicate.
