### ISSUE TITLE
Add doughtnut/torus to the list of vector layers

### ISSUE THREAD

**Issue by xpleria** [Leaflet/Leaflet#6542]
I want to add a doughnut shaped object to the map. There is an options to add a polygon with a hole defined by another polygon. But the same does not exist for a circle.

It would be great to have a function to add a doughnut shaped path to the map. The doughnut could be described by two circles: inner and outer. Each having a radius, stroke and fill (maybe inner and outer stroke in case of outer circle).

Of course a quick-and-dirty solution for this would be using two circles and adding them to a feature group, but in this case, the fill would overlap. This can't be used when for example, the fill of the inner circle should be transparent or when the two circles have a fill with 0 < opacity < 1; the colours would get mixed.

**Comment by IvanSanchez** [comment]
I'm gonna guess you wanted to submit this feature request to Leaflet.Draw - but you just sent it to the core Leaflet repo.

Please send it to the appropriate place.

**Comment by xpleria** [comment]
I actually meant to  post this in the core Leaflet repo itself.

Under **Leaflet/src/layer/vector/** there are the base geometry class files. To this, maybe a Doughtnut.js could be added?

When I meant draw, I didn't mean from user input, but programatically. So, this applies to the core leaflet repo rather than Leaflet.Draw

**Comment by IvanSanchez** [comment]
Ooooh, OK, I misunderstood that.

This is challenging, since [SVG circles](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/circle) cannot be specified so that they have a hole in the middle, as far as I'm aware. This might require more complex specification of the SVG shape.

**Comment by xpleria** [comment]
This can be quite easily done using a mask:

```
<svg width="200" height="200" style="background: '#339'">
  <defs>
    <mask id="hole">
      <rect width="100%" height="100%" fill="white"/>
      <circle r="50" cx="100" cy="100" fill="black"/>
    </mask>
  </defs>

  <circle id="donut" r="100" cx="100" cy="100" mask="url(#hole)" />
    
</svg>
```

Above code from [stackoverflow](https://stackoverflow.com/a/22581434/1393400)

**Comment by stharvey** [comment]
Hello,

I needed this function too and with a little fiddling around have managed to get it to work based on the previous suggestion by @xpleria - thanks for that :-)

I am not familiar with writing Leaflet plugins and currently am working to a deadline but when I get a little more time I will put this into a plugin.

You can see my result here: [Doughnut Circle Shape](https://www.pebbls.com/test/img/doughnut.jpg)

Basically I created 3 circles (2x small and 1x large) with the same center point - I then used javascript to move one of the smaller circles into a `<mask>` tag (after creating a `<defs>` tag) - I then used jQuery to add `mask="url(#hole)"` to the bigger circle.

It took a bit of fiddling to make the doughnut draggable and to remain visible during map panning but it's now working really well.

I'll post back here once I get the chance to put a plugin together.

**Comment by Falke-Design** [comment]
I created a [L.Donut Plugin](https://github.com/Falke-Design/L.Donut). 
[Demo](https://falke-design.github.io/L.Donut/)

![grafik](https://user-images.githubusercontent.com/19800037/139536038-b0d85d7d-461c-490f-94a9-5956677bab0b.png)

I will close this Feature Request. If it is not the expected result please feel free to write and we will reopen it.
