### ISSUE TITLE
tooltip rendering issue

### ISSUE THREAD

**Issue by baslr** [Leaflet/Leaflet#6545]
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
go to
https://plnkr.co/edit/XD0Ox8yQZ1qWDy38rftB?p=preview
and click a good sized triangle
if you move the cursor, you can see three green lines which go from the middle of one segment to the mouse positon. The last line has a tooltip. The tooltip is rendered without calling openTooltip().
If you uncomment line 64 and draw a new triangle you can see that the green line 1 and 2 have there tooltip at the markers position as expected. The last tooltip renders at the green line middle.
If you hover over one marker, the tooltip from the last line is positioned correctly.

**Expected behavior**
The last tooltip should be positioned at the marker from the green line.

**Current behavior**
The last tooltip is positioned at the middle of the last green line. If mouse is hovered over one marker the tooltip is positioned correctly.

**Environment**
- Leaflet version: 1.4
- Browser (with version): firefox 65.1
- OS/Platform (with version): Mac 10.12

**Additional context**
code is computing the distance between line segment and mouse position. Distance is show in the tooltip.

**Minimal example reproducing the issue**
https://baslr.github.io/leaflet-bug/
https://plnkr.co/edit/XD0Ox8yQZ1qWDy38rftB?p=preview

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by johnd0e** [comment]
There is nothing wrong in Leaflet, it is code issue.
Either use `permanent: true` tooltips, or bind them to markers (not lines).
