### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by ilostit** [Leaflet/Leaflet#6552]
Hi,

i have this issue after update reactivemaps "@appbaseio/reactivemaps"
leaflet 1.4.0

XXX/node_modules/leaflet/dist/leaflet-src.js:7
typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :
^
ReferenceError: window is not defined
at XXX/node_modules/leaflet/src/core/Util.js:217:24
at version (XXX/node_modules/leaflet/dist/leaflet-src.js:7:65)
at Object. (XXX/node_modules/leaflet/dist/leaflet-src.js:10:2)
at Module._compile (internal/modules/cjs/loader.js:689:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
at Module.load (internal/modules/cjs/loader.js:599:32)
at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
at Function.Module._load (internal/modules/cjs/loader.js:530:3)
at Module.require (internal/modules/cjs/loader.js:637:17)
at require (internal/modules/cjs/helpers.js:20:18)

any idea ?

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.

**Comment by HoraceShmorace** [comment]
This error isn't specific to any framework. It merely shows up in those frameworks because of the Leaflet dependency.

This is happening when trying to include Leaflet as a dependency in a _universal_ web app, which gets server-side rendered first (SSR). This is a standard SEO requirement for any content-based site.

This error occurs when simply including the `leaflet` dependency in an SSR app (in my case, via npm), and is happening because Leaflet is trying "to do stuff" that depends on the window object before an instance is even instantiated, which is a bad practice. Initialization should be explicit, via the constructor (or some other explicitly executed closure).

**Comment by IvanSanchez** [comment]
Let me quote myself, emphasis mine:

> Please understand that we only have the time and energy to test Leaflet **in plain web browsers**.

If you want to work around stuff so that you can load Leaflet in a browserless environment, PRs are welcome. In particular, you'll need to check for `window` in all of `core/Browser.js` and work around the polyfills.

Keep in mind that Leaflet's priority as of now is that the code works without modifications in MSIE9, not that it works with the fanciest latest framework/editor/transpiler thing.

**Comment by yog3sha** [comment]
I was getting this issue with nuxt because in nuxt.config.ts file I had mentioned 'leaflet' in modules.
modules: [
        "nuxt-leaflet",
        "leaflet"
    ],
Error went away after removing that 'leaflet'

**Comment by bradgreens** [comment]
I hit this problem using a NextJs stack and it makes complete sense window is not [yet] defined at the time of import. NextJs documentation had a clear solution for this.
https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr

For other React stacks, one could try `useScript` inside of `componentDidMount` or `useEffect`/`useLayoutEffect` as well.
https://usehooks.com/useScript/

**Comment by DaSchTour** [comment]
This just shows, that leaflet is an ancient times library that should not be used anymore as it hardly depends on globals and is not side effect free which is bad practice already for a long time. Importing the library already calls methods on window and breaks. It's not suitable for modern development.

**Comment by rhernandog** [comment]
What @bradgreens suggested works just fine for Next.

Just create a separate component (lets call it `Map.js`) and use the dynamic import for that and import the leaflet package in it.

```jsx
import { useRef, useEffect } from "react";
import L from "leaflet";

const Map = () => {
  const locationMap = useRef(null);
  
  useEffect(() => {
    const myMap = L.(locationMap.current).setView([0,0], 13);
    // rest of your map code here
  }, []);

  return <div className="map-container" ref={locationMap} />
};

export default Map;
```

```jsx
const Map = dynamic(() => import("./components/Map"), { ssr: false });

const PageName = () => {
  return (
    <div>
      <Map />
    </div>
  );
}

export default PageName;
```

**Comment by amr8644** [comment]
> 

Mine shows an error that says:
`Server Error
ReferenceError: dynamic is not defined`
What should I do?

**Comment by JoueBien** [comment]
there is definitely something nasty going on. Things like new LatLng hang with the same window definition issue. Which I can get around with:
```
export const castTupleToLatLng = (tuple: LatLngTuple) => {
  const ret = {
    lat: tuple[0],
    lng: tuple[1]
  }
  return ret as LatLng
}
```
The libraries is great but it feel really dated to work with - the web has moved on.

**Comment by L53c** [comment]
> 
You just need to import it. Keep in mind that dynamic is part of next.js, in case You are mistakenly using just react, regards.

`import dynamic from 'next/dynamic'`

**Comment by JoueBien** [comment]
> > 
> 
> You just need to import it. Keep in mind that dynamic is part of next.js, in case You are mistakenly using just react, regards.
> 
> `import dynamic from 'next/dynamic'`

which only works with react components if it is a plane old class or function your SOL.

**Comment by asyahubar** [comment]
I had a similar problem to [yog3sha](https://github.com/yog3sha). My nuxt application has to be server-side rendered and none of the solutions above worked for me.
What I skipped installing leaflet as a dependency and imported it via <script> in <head> of my layout similar to instructions written in the [Leaflet Quick Start Guide](https://leafletjs.com/examples/quick-start/).
First I tried to import the script only in the page where I was using it but than would result in bugs too so I opted out for a more global import.
As for the marker, I just used my own icon and imported it like in [the documentation](https://leafletjs.com/reference.html#icon).

**Comment by Huasito-Appel** [comment]
Hello there, having the issue here working with svelte kit, not sure what happend but i was developing just fine and without changes to the code it stopped working lol.

here is a snippet i anyone can find what was going on.

``` 
<script lang=ts>
  import { onMount } from 'svelte';
  
  /**
	  * @type {WebSocket}
	  */
  
  onMount(async() => {
	  const L = (await import('leaflet')).default;
	  var map = L.map('map').setView([-33.4, -70.5], 11);
  
	  <some code here>
  });
</script>

**Comment by raul-potor** [comment]
Just encountered the same problem and with the help of ChatGPT I came to this solution which works in NextJS 13. This way you are able to use the components from `react-leaflet`

```javascript
import React, { useEffect } from "react";
import dynamic from "next/dynamic";

// Dynamic import of react-leaflet components
const MapContainer = dynamic(
  () => import("react-leaflet").then((module) => module.MapContainer),
  {
    ssr: false, // Disable server-side rendering for this component
  }
);
const TileLayer = dynamic(
  () => import("react-leaflet").then((module) => module.TileLayer),
  {
    ssr: false,
  }
);
const Marker = dynamic(
  () => import("react-leaflet").then((module) => module.Marker),
  {
    ssr: false,
  }
);
const Popup = dynamic(
  () => import("react-leaflet").then((module) => module.Popup),
  {
    ssr: false,
  }
);

const MapComponent = () => {
  useEffect(() => {
    import("leaflet").then((L) => {
      const map = L.map("map").setView([37.7577, -122.4376], 8);
      L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
        attribution:
          '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
      }).addTo(map);
    });
  }, []);

  return (
    <div id="map" style={{ width: "100%", height: "400px" }}>
      <MapContainer
        center={[37.7577, -122.4376]}
        zoom={8}
        style={{ width: "100%", height: "100%" }}
      >
        <TileLayer
          url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
          attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        />
        <Marker position={[37.7577, -122.4376]}>
          <Popup>User Post Location</Popup>
        </Marker>
      </MapContainer>
    </div>
  );
};

export default MapComponent;
```

**Comment by JoueBien** [comment]
@raul-potor That's already been suggested (see the comments from Jun 9, 2022). It works only for the parts of the library that are react components.  dynamic does not work with parts of the library that are provided as classes
