### ISSUE TITLE
White sides at markers popup

### ISSUE THREAD

**Issue by xpowert** [Leaflet/Leaflet#6554]
Hello, I like Leaflet a lot. But I want to ask how to remove white sides in the popup ? I manage to turn of padding but it only removed top and bottom, but sides still stand. I will insert a image and it will be easier to understand. 

![popup](https://user-images.githubusercontent.com/12520158/54189047-a9356c80-44b9-11e9-8d41-5a681c014aad.PNG)

I mark sides with yellow color and I need to delete them and (x) close button should be on image.  What am I doing wrong here ?  

Thanks for this awesome JS plugin.

**Comment by siimots** [comment]
We use GitHub as an issue tracker. For usage and support questions, please check out resources below:

Read Leaflet documentation: https://leafletjs.com
For support questions like "How can I do X with Leaflet?" please search or ask questions on StackOverflow or StackExchange using Leaflet tag:
https://stackoverflow.com/questions/tagged/leaflet
https://gis.stackexchange.com/questions/tagged/leaflet
Thanks!
