### ISSUE TITLE
icon options doesn't work in ionic 3

### ISSUE THREAD

**Issue by hazem-saeed** [Leaflet/Leaflet#6556]
- [yes ] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [yes ] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [yes ] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- step 1
  create an empty ionic 3 project, and install leaflet js through npm.. import it in the ts file of the html 
  where the map is... everything should work fine and the map loads and the marker is present

- step 2
  follow the documentation on how to change the marker icon inside your function.

**Expected behavior**
   the marker icon should change from the default blue icon, to whatever you image you linked to it.

**Current behavior**
   nothing changes!!!

**Environment**
- Leaflet version:
- Browser (with version): chrome Version 72.0.3626.121
- OS/Platform (with version): windows 10

**Additional context**

**Minimal example reproducing the issue**

Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.

- [yes] this example is as simple as possible
- [yes] this example does not rely on any third party code

**Comment by siimots** [comment]
Ionic problem, not Leaflet.

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.
