### ISSUE TITLE
Set specific subdomain for spesific zoom levels

### ISSUE THREAD

**Issue by bongobongo** [Leaflet/Leaflet#6558]
I want to make it so that a zoom level and/or set a spesific subdomain or a range of subdomains for the tiles.

So if the map provided to the end-user (browser), is supporting zoom-level 1 - 12, then I would like to make leaflet use the following rules for the subdomains (or similar):

Zoom level 1-8:  subdomain: a
Zoom level    9:  subdomain: b
Zoom level  10:  subdomain: c
Zoom level  11:  subdomain: d,e
Zoom level  12:  subdomain: x,y

Could be implemented by allowing use of new options for the tileLayer, where the value can be set similar to the subdomains option today:

subdomainsZoomLevel_1: 'a',
subdomainsZoomLevel_2: 'a',
subdomainsZoomLevel_3: 'a',
...
...
subdomainsZoomLevel_9: 'b',
subdomainsZoomLevel_10: 'c',
subdomainsZoomLevel_11: ['d','e']
subdomainsZoomLevel_12: ['x','y']

I have searched around, both here and on Google, to see how I can control this, but with no luck. 
If someone knows how to control this using javascript by e.g. extending a class in leafletjs (or some other workaround), please let me know. If not possible to control this now, it would be nice to see that such an option is added to this great project.

**Comment by siimots** [comment]
We use GitHub as an issue tracker. For usage and support questions, please check out resources below:

Read Leaflet documentation: 
https://leafletjs.com
For support questions like "How can I do X with Leaflet?" please search or ask questions on StackOverflow or StackExchange using Leaflet tag:
https://stackoverflow.com/questions/tagged/leaflet
https://gis.stackexchange.com/questions/tagged/leaflet
Thanks!

Create layergroup.
Create 10 or whatever layers with different zoomlevels and subdomains.
Add those layers to layergroup.
Add layergroup to map.

**Comment by bongobongo** [comment]
Tanks for the quick answer. 
Will use the recommended forums in the future.
