### ISSUE TITLE
MovingMarker Future in Angular7

### ISSUE THREAD

**Issue by VinodkumarPachimadla** [Leaflet/Leaflet#6562]
Hi ,

I want to use L.Moving marker in in Angular 7 Project ,but i am unable to find the ,L.Marker.moving marker (it's undefined )can you help me out on this .
thank you 

below is the sample which i am trying to achive
> var myMovingMarker = L.Marker.movingMarker([[48.8567, 2.3508], [50.45, 30.523333]],
          [20000]).addTo(this.map);
        myMovingMarker.start();

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.

**Comment by IvanSanchez** [comment]
And do check https://leafletjs.com/plugins.html first
