### ISSUE TITLE
Seeking Suggestion (Hurricane Tracker)

### ISSUE THREAD

**Issue by prasanjitdash** [Leaflet/Leaflet#6563]
Hi LL community,

This is not 'an issue' but I'm unsure where to put such questions, hence posting it here.

Can anyone suggest me a leaflet plugin for Hurricane Tracker, something similar to what is below also using leaflet:
https://www.usatoday.com/pages/interactives/storm-tracker/
(from the dropdown, one can choose a name to see the path and the cone of influence)

However, the above link does not offer any opensource plugin and perhaps is a commercial sub-company who use LL for USA Today Newspaper. It is a good example of the usefulness of LL. They seem to be using the data directly from the National Hurricane Center as well, but any JSON/geoJSON input example would be fine.

Thanks

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
