### ISSUE TITLE
How to put marker to left side of the map for Australia

### ISSUE THREAD

**Issue by ashishdhyani** [Leaflet/Leaflet#6565]
Presently i am making a line between Austraila and US.
Australia is currently at the right side in the map and USA is at the left side.

How to put marker at the left side for Australia and at the right side for US so that we have the shorter line between these countries.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by IvanSanchez** [comment]
https://stackoverflow.com/questions/38820724/how-to-display-leaflet-markers-near-the-180-meridian/
