### ISSUE TITLE
Zoom In and Out not working on mobile while dragging with fingers

### ISSUE THREAD

**Issue by Scharnhorst** [Leaflet/Leaflet#6567]
I have a leaflet map running. Having created a map, when I try to run it on phone, often the zoom in and out stop working while using my fingers to zoom. Double tap still works and so does zoom control. Only there is no response while trying to zoom with fingers. Could someone give me suggestions as to why this is happening.

**Comment by IvanSanchez** [comment]
What's your leaflet version? There was something similar in 1.1.0 IIRC, that was fixed already.

**Comment by Scharnhorst** [comment]
Sorry for the late reply
Version is 1.3.4
Could you give me the issue number where it was solved. I have tried a few and none worked.
