### ISSUE TITLE
On load event is not invoking callback method with defaults (with center) being passed

### ISSUE THREAD

**Issue by kishoremkumar** [Leaflet/Leaflet#6569]
on 'load' event is not fired when we wrap statements into a method. However, it works if I use simple alert.

I had searched through several posts, but there was no mention of defaults being passed.

Code:
```javascript
const defaults = {
      center: [-33.8650, 151.2094],
      zoom: 3,
      layers: [],
      };

// Create the map
var map = L.map('map', defaults).on('load', function(e){
alert('Map Loaded');
});

// Set up the OSM layer
L.tileLayer(
  'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    maxZoom: 18
  }).addTo(map);

// add a marker in the given location
L.marker(defaults.center).addTo(map);
```

**Expected behavior**
Callback that is passed is invoked.

**Current behavior**
Callback method is not invoked

**Environment**
- Leaflet version: 1.4.0
- Browser (with version): Chrome 72.0.3626.121
- OS/Platform (with version): Windows

**Minimal example reproducing the issue**

https://jsfiddle.net/cse2p8wt/4/

**Comment by IvanSanchez** [comment]
You're attaching the event handler after the `load` event fires - that happens because you're passing a center and initial zoom to the map, so it loads before the instantiation call ends.

This is behaviour as expected.

**Comment by kishoremkumar** [comment]
Thanks Ivan.

However, the following works fine 
https://jsfiddle.net/grwqzxh0/

The only difference instead of wrapping alert into a method, I added it directly.

Am I missing something?

**Comment by IvanSanchez** [comment]
See https://stackoverflow.com/questions/35428801/leaflet-marker-event-fires-at-wrong-time/35429902#35429902
