### ISSUE TITLE
Chrome on Android events propagation after pinch zoom

### ISSUE THREAD

**Issue by 7Ds7** [Leaflet/Leaflet#6572]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- Open https://codepen.io/binaryunit/pen/OqdbyP 
- Click the image and pinch to zoom it
- Close the modal
- Pinch zoom on map
- Click image again and try to pinch zoom it again it does NOT receive any events

**Expected behavior**
Pinch Zoom / touch events should work on other elements after pinch zooming on the leaflet map

**Current behavior**
Touch Events are not properly propagated on other elements once you zoom on the map

**Environment**
- Leaflet version: 1.3.2
- Browser (with version): Chrome
- OS/Platform (with version): Android

**Additional context**
I am using other frameworks and components but i isolated them and reproduce the issue here
https://codepen.io/binaryunit/pen/OqdbyP it was very tricky to understand what was going on, but at least now i can reproduce it flawlessly every time.
Please note that this only happens on Chrome/Mobile and not any other Desktop/Mobile browser that i had tried (FF, Safari)

- [x] this example is as simple as possible
- [ ] this example does not rely on any third party code 
(i am using [viewerjs](https://github.com/fengyuanchen/viewerjs) but since it only happens after on pinch zooming on leaflet map i am assuming it is something that leaflet does to the global events after pinch zooming, keep in mind that pan or any other interactions do not cause this behaviour.

I looked into the several options as well as repo issues namely [#5310](https://github.com/Leaflet/Leaflet/issues/5310) which seem to be the closest behaviour but that was not it, any directions to follow or solutions would be greatly appreciated.

**Comment by 7Ds7** [comment]
After some investigation looking at the touch event handler
https://github.com/Leaflet/Leaflet/blob/master/src/map/handler/Map.TouchZoom.js#L29

if we change the on off methods to the map container instead of document it seems that it fixes the issue, not so sure what would be the implications though.

```
	_onTouchStart: function (e) {
		...

		DomEvent.on(this._map._container, 'touchmove', this._onTouchMove, this);
		DomEvent.on(this._map._container, 'touchend', this._onTouchEnd, this);

...
	},

	_onTouchMove: function (e) {
           ...
	},

	_onTouchEnd: function () {
		...
		DomEvent.off(this._map._container, 'touchmove', this._onTouchMove);
		DomEvent.off(this._map._container, 'touchend', this._onTouchEnd);
                ...

```

**Comment by IvanSanchez** [comment]
@7Ds7 Thanks for tracking this down! Would you mind creating a pull request for that? It'll make easier to see the changes.

Unfortunately this is one of this issues that can be either deceptively simple or it can have different behaviours on different platforms (browsers/OSs). This will just need testing on different devices.

**Comment by 7Ds7** [comment]
Thank you for the reply @IvanSanchez , added the pull request here 

https://github.com/Leaflet/Leaflet/pull/6578

And regarding the different devices that is exactly why i asked, tried to follow the blame of those lines but got lost in the git history.

I can say that it is working on the following Mobile Browsers, Chrome, FireFox, Safari, not so sure about the rest or other implications it might make. It would be great to have a insight on why was it added to the document and not the container itself in the first place.

**Comment by johnd0e** [comment]
Updated libs
https://codepen.io/johnd0e-the-bashful/pen/dyojYgr
