### ISSUE TITLE
Leaflet CSS not working when imported in component.scss

### ISSUE THREAD

**Issue by RonCan** [Leaflet/Leaflet#6573]
I'm working on an Ionic 4 application. When I import the Leaflet CSS in my `component.scss` file like this:

    @import "~leaflet/dist/leaflet.css";

The map tile does show up but broken with a lot of grey areas which never get filled. This is how it looks

[![This is how it looks][1]][1]

The same map loads perfectly fine when the css is imported in the `index.html` of the project using [this link][2]:

        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.4.0/dist/leaflet.css"
          integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA=="
          crossorigin=""/>

And looks like this

[![Fine][3]][3]

Which is the intended behavior

What's interesting to note here is, the exact same css when loaded from `node_modules` inside `index.html` exhibits the same behavior as loaded inside `component.scss`.

  [1]: https://i.stack.imgur.com/k7aaZ.png
  [2]: http://%20%20%20%20%3Clink%20rel=%22stylesheet%22%20href=%22https://unpkg.com/leaflet@1.4.0/dist/leaflet.css%22%20%20%20%20%20%20%20%20%20%20%20integrity=%22sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA==%22%20%20%20%20%20%20%20%20%20%20%20crossorigin=%22%22/%3E
  [3]: https://i.stack.imgur.com/xWNms.png

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.
