### ISSUE TITLE
Add stat_density2d   (Heat map that doesnt move) 

### ISSUE THREAD

**Issue by orlandoandradeb** [Leaflet/Leaflet#6574]
Hello everybody 
I have been triying to make heat maps using leaflet such a map base. 
I made some good advances with leaflet.extras and the function addheatmaps 
but I dont like that it doesnt produce a fixed heat map.   That´s why I  looked to generate with stat_density2d which uses kernel density to produce  the map. 
 
The thing is that I just can´t add the function to leaflet  the code is the follow: 

stat_density2d(aes(x = stop_lat, y =stop_lon , fill = ..level.., alpha = ..level..),
               size = 1, bins = 20, data = stops,
               geom = "polygon")

Can somebody help me ? 
thank you guys

**Comment by mourner** [comment]
Hi! Unfortunately this is not the right place to ask this question — it seems like it is related to the RStats Leaflet plugin, and this repo is for reporting issues with the Leaflet JavaScript library itself.
