### ISSUE TITLE
Layer Control - touch clicks first layer

### ISSUE THREAD

**Issue by UnsterblichMedic** [Leaflet/Leaflet#6579]
Using a touchscreen and tapping the layers icon opens the list of layers but clicks (or deselects) the first layer checkbox. I just want to touch (click) to expand. I was trying to see how to disable the expand on mouse hover feature but cant find anything about it. The docs say for the L.control.layers option of collapsed, its default is true and will expand on mouse hover or touch.

**Comment by jorgelf** [comment]
I've been experiencing this problem with a touch screen monitor, and I think it's related to the _mouseenter_ and _mouseleave_ events, not to the _hover_ one. I'm specifically pointing towards [this code in _Control.Layers.js_, method __initLayout_,](https://github.com/Leaflet/Leaflet/blob/master/src/control/Control.Layers.js#L190-L194) as responsible:
```javascript
			if (!Browser.android) {
				DomEvent.on(container, {
					mouseenter: this.expand,
					mouseleave: this.collapse
				}, this);
			}
```

Obviously _Browser.android_ only returns _true_ for mobile browsers under normal circumstances, so the control doesn't behave as expected with other touch screen devices. I'm not sure there is even a way of detecting touch screen devices explicitly from the browser, thus I'm currently using this code as a workaround for manually disabling the _mouseenter_ and _mouseleave_ events, hope it works for you as well:

```javascript
var control = L.control.layers(baselayers, overlays, {position: 'bottomright'});
control.addTo(map);
L.DomEvent.off(control._container, {
    mouseenter: control.expand,
    mouseleave: control.collapse
}, control);
```

It works fine with our touch screen after this change, though if you use a mouse you must click onto the layers icon before being able to change layers.

**Comment by johnd0e** [comment]
The issue is introduced in 8b742a024ec23c692c7d51187572b86b83de0d0c.
Definitely it should not be android specific.
Even more: it should not be touchscreen-specific, because there could be mouse attached too.

**Comment by johnd0e** [comment]
But what is interesting: for me the issue is reproducible in 1.6.0 but not in latest `master`.

**Comment by johnd0e** [comment]
> The issue is still reproducible in latest Firefox.

Unable to reproduce anymore with recent Firefox.
