### ISSUE TITLE
Show / hide a lot of geojson layer

### ISSUE THREAD

**Issue by FredO81** [Leaflet/Leaflet#658]
Hy ! I'am a new user of leaflet and I have a problem !:p

With a lot of html input checkbox, I would to add / remove  geojson layer.
The name of each layer javascript vars must be like  layer_01, layer_02 ...

The question is :How to create dynamicaly javascript vars ?
Or, it is possible with leaflet to get a layer by id ?

This code not work but it is for the principe.

<code>
function add_layer( id ){
     var 'layer' + id= new L.GeoJSON();
     'layer'+id.on('featureparse', function(e) {
       // do something with e.layer depending on e.properties
      });
      'layer'+ id.addGeoJSON(geojsonObj);
      map.addLayer('layer' + id);
}

function remove_layer( id ){
    removeLayer( 'layer' + id );
}
 </code>

**Comment by chriszrc** [comment]
No, "eval is evil" :

https://javascriptweblog.wordpress.com/2010/04/19/how-evil-is-eval/

You can do the same thing without eval, use a global variable to hold the layers:

```
var id = "Id07"
var layers = {};
layers["layer"+id] = new L.GeoJSON();
console.log(layers.layerId07);
console.log(layers["layer"+id]);
```
