### ISSUE TITLE
Zoom gets freezed on multiple loading in phone

### ISSUE THREAD

**Issue by Scharnhorst** [Leaflet/Leaflet#6581]
I created a page which then transfers to map on a click on a div. After going to the map, I come back to original page and goto the map once again. After doing this 2-3 times, the pinch zoom in and out hangs. However the double tap zoom and button zoom keeps working fine. Could anyone tell me a solution to this.

**Comment by mdorda** [comment]
It seems to happen only on iOS 12.2.

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?
