### ISSUE TITLE
tile error

### ISSUE THREAD

**Issue by romandiller** [Leaflet/Leaflet#6582]
Good day. I need some help, if a've got a "tileerror" event, how can I reload a tile that did not load?

`this.map.addLayer(this.someLayer);

        this.pkk5.on('tileerror', (e) => {

            let target = e.target;

            // how to reload target

        });`

Thanks!

**Comment by MaRaSu** [comment]
I have the same question. Google gave https://stackoverflow.com/questions/30307522/how-to-reload-tile-which-is-not-loaded-in-leaflet-js however have not yet tested with new Leaflet versions and wonder how sustainable it is. 

(App and) tile servers I use reasonably often fail on loading individual tiles however practically always work when retrying immediately. However have not found a mechanism in Leaflet how to configure it to be a bit more persistent in trying to reload failed tiles.

For such a great component this is a bit strange gap in functionality.

**Comment by barryhunter** [comment]
I believe the 'e' event you get with the layer, will contain `e.tile` which is the individual tile that failed. 
It's the actual <img> tag itself. Also get `e.coords` which can be used with `getTileUrl` to get the original url. 

... so can do something with that. 

    someLayer.on('tileerror', (e) => {
        var tileurl = someLayer.getTileUrl(e.coords);
        e.tile.src = tileurl + "&rnd=".Math.rand();
    });

... that just blindly adds a param to retry. Not recommended! Might want to handle that better. Eg with a setTimeout to return, and exponential backoff. So as not to just keep blindly retrying quickly if the server really is down!

    var failures = 0;

    someLayer.on('tileerror', (e) => {
        failures = failures+1;
        var tileurl = someLayer.getTileUrl(e.coords);
        setTimeout(function() {
            e.tile.src = tileurl + "&rnd=".Math.rand();
        }, Math.pow(failures,3));
    });

https://leafletjs.com/reference-1.3.4.html#tileerrorevent

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
