### ISSUE TITLE
Loading offline map incorrectly

### ISSUE THREAD

**Issue by liulanghaitun** [Leaflet/Leaflet#6584]
`When` I load an offline map, the actual load is not my own offline map, but a computed map. so  I can't load the map correctly.

The environment I use is Win7 64, chrome 74.0.3724.8

The code is as follows:
<html>
<head>
    <meta charset="utf-8">
	<script language="javascript" type="text/javascript" src="qwebchannel.js"></script>
	<script src="./leaflet/leaflet-src.js"></script>
    <link href="./leaflet/leaflet.css" rel="stylesheet"/>
    <style>
		#left{
		  width: 60%;
          height: 100%;
		  float: left;
		}
		#right{
		  width: 40%;
          height: 100%;
		  float: right;
		}
        #mapOne {
          width: 50%;
          height: 50%;
		  float: left;
        }
		#mapTwo {
          width: 50%;
          height: 50%;
		  float: left;
        }
		#mapThree {
          width: 50%;
          height: 50%;
		  float: left;
		  clear:left;
        }
		#mapFour {
          width: 50%;
          height: 50%;
		  float: left;
        }
		#mapFive {
          width: 100%;
          height: 100%;
		  float: right;
        }
    </style>
</head>
<body>
	<div id="main">
		<div id="left">
			<div id="mapOne"></div>
			<div id="mapTwo"></div>
			<div id="mapThree"></div>
			<div id="mapFour"></div>
		</div>
		<div id="right">
			<div id="mapFive"></div>
		</div>
	</div>
</body>
<script>
var positron= new L.TileLayer("satellite/{z}/{x}/{y}.jpg",{tileSize: 256});
var mapcenter = new L.latLng(114.677129,22.638796);
var map = new L.Map("mapOne", {    
            center:mapcenter,   
            zoom: 10,           
            layers: [positron],  
            minZoom: 9,         
            maxZoom: 13,        
            opacity: 0.1,       
			attributionControl: false,
        });
</script>
</html>

My offline map path is:
satellite\10\837\445.jpg
satellite\10\837\446.jpg
satellite\10\837\447.jpg

But the actual loading map is:
satellite/10/575/0.jpg
satellite/10/576/0.jpg

After debugging, I found that:

In leaflet-src.js, when the _update method is called and then the _pxBoundsToTileRange method is called, the number of tiles generated is satellite/10/575/0.jpg and satellite/10/576/0.jpg. Therefore, the tiles can not be found, and the map can not be loaded correctly. 

How do I load the correct offline map? I hope to get your help.thanks.

**Comment by IvanSanchez** [comment]
This is not a leaflet bug, closing.

You should check your [browser's platform](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorID/platform) and use that information to set either `/` or `\` as the path separator.

**Comment by liulanghaitun** [comment]
offline map path is:
E:\radar_fuse\build-radar_fuse-unknown-Debug\debug\satellite\10\837\445.jpg
E:\radar_fuse\build-radar_fuse-unknown-Debug\debug\satellite\10\837\446.jpg
E:\radar_fuse\build-radar_fuse-unknown-Debug\debug\satellite\10\837\447.jpg

actual map path is:
file:///E:/radar_fuse/build-radar_fuse-unknown-Debug/debug/satellite/10/575/0.jpg 

Should not be the reason for browsers.
