### ISSUE TITLE
Wrong URL generated (infamous %22)marker-icon.png)

### ISSUE THREAD

**Issue by mbrucher** [Leaflet/Leaflet#6585]
I put all the code in the following gist: https://gist.github.com/mbrucher/4d7932690c8402c24c4e485a446fd4a1

- [ X] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [X ] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [ ] I've searched through the issues to make sure it's not yet reported

The issue seems to be related to #4968, which has been closed.

**Steps to reproduce**
npm run watch generates the required files in a `static` folder (flask usual static folder) which is then served online.

**Expected behavior**
The marker icon should be linked to the png.

**Current behavior**
The name of the png has %22)marker-icon.png appended to it.

**Environment**
- Leaflet version: 1.4.0
- Browser (with version): Same with all of them
- OS/Platform (with version): All

**Additional context**

**Minimal example reproducing the issue**
https://gist.github.com/mbrucher/4d7932690c8402c24c4e485a446fd4a1

Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.

- [ X] this example is as simple as possible
- [ ] this example does not rely on any third party code

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.

**Comment by IvanSanchez** [comment]
In this particular case webpack counts as a build framework we don't handle.

**Comment by mbrucher** [comment]
Sorry, but this means that leaflet is basically unusaable for anyone. And once again, this is the same bug as #4968 that was handled here, so closing it without any question is not great when the issue is interaction with a pretty basic piece of JS infrastructure.

**Comment by IvanSanchez** [comment]
> Sorry, but this means that leaflet is basically unusable for anyone. [...] you don't expect people to use leaflet in production

No, pal. I think you're trying to grab maintainers' attention by making the problem appear more serious than it is, [which is not a good move](http://www.catb.org/~esr/faqs/smart-questions.html#urgent).

Leaflet is usable in production without needing any build framework, period. You seem to think that *nobody* can use it because it doesn't work under *your specific* circumstances, and I find that arrogant at best.

> so closing it without any question is not great

Let me reiterate a very specific sentence from above: **Please understand that we only have the time and energy to test Leaflet in plain web browsers**.

So, yes, we maintainers choose to close without question issues related to webpack, rollup, AMD, UMD, commonjs, require.js, grunt, gulp, gobble, babel, bublé, coffeescript, typescript, or whatever else. We target browsers, not build systems.

**Comment by mbrucher** [comment]
Same html as my link, except:
```
  <script src="{{ url_for('static', filename='leaflet.js') }}" type="text/javascript"></script>
  <script type="text/javascript">
let map = new L.Map('map-canvas');

// create the tile layer with correct attribution
let osmUrl='http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
let osmAttrib='Map data © <a href="http://openstreetmap.org">OpenStreetMap</a> contributors';
let osm = new L.TileLayer(osmUrl, {minZoom: 8, maxZoom: 20, attribution: osmAttrib});

navigator.geolocation.getCurrentPosition((position) => {
    map.setView(new L.LatLng(position.coords.latitude, position.coords.longitude), 14);
  }
)

map.addLayer(osm);

let set_one_marker = () => {
  let marker;
  let popup = L.popup();

  map.addEventListener('click',
                        event => {
    if(marker) {
      map.removeLayer(marker);
    }
    marker = L.marker(event.latlng).addTo(map);
  })
}
set_one_marker();
```
No webpack, nothing, just served from a different path than where the css/js is located. Still served by flask (I think this still qualifies as in a target browser?).
