### ISSUE TITLE
L.Util.formatNum round 

### ISSUE THREAD

**Issue by inkstak** [Leaflet/Leaflet#6586]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Environment**
- Leaflet : 1.3.1 & 1.4.0
- Browser : Firefox 66 & Chrome 73

**To reproduce**
```
L.Util.formatNum(1.005, 2)
> 1
// Returns 1 instead of 1.01

L.Util.formatNum(-1.4837191022531273, 18) 
> -1.4837191022531275
// Returns -1...75 instead of -1...73
```

The way `formatNum` performs rounding can result in unexpected changes to coordinates.
For example :

```
L.GeoJSON.latLngToCoords({  lng: -1.4837191022531273, lat: 43.49222084042808 }, 18)
> [-1.4837191022531275, 43.49222084042808]
```

The precision argument for `latLngToCoords` is not documented, but it may be.
I play with french cadastre, and such approximation leads to various mistakes.

**Solution**

According to this article on [stackoverflow](https://stackoverflow.com/questions/11832914/round-to-at-most-2-decimal-places-only-if-necessary), this rounding method should be better :
```
L.Util.formatNum = formatNum

function formatNum(num, digits) {
  return +(Math.round(num + ('e+' + digits)) + ('e-' + digits))
}
```

**Comment by IvanSanchez** [comment]
> I play with french cadastre, and such approximation leads to various mistakes.

That error between -1.4837191022531273 and -1.4837191022531275 is roughly equal to... *checks notes*... one tenth of an atom. I know that cadastre applications rely on precision, but I don't think one needs *that much* precision.

In all seriousness now: I acknowledge that it can lead to misdetection of features with the same coordinates.

If you could make that suggestion into a pull request, and see it all the unit tests still pass nicely, I don't think there should be any problem making the change.

**Comment by inkstak** [comment]
> is roughly equal to... checks notes... one tenth of an atom

Sure ! But maths dont lie : Geos & Postgis are really sensible.
Take two polygons that touch, side by side. Sending the GeoJson to a back-end app by changing the 16th decimal, I'll fall into one polygon or another.

![parcelles](https://user-images.githubusercontent.com/474554/55355836-b0a0d200-54c9-11e9-9e17-297b83af5fde.png)

Pull request in progress.

**Comment by johnd0e** [comment]
Just for completeness:

#6587 was reverted because of performance issues, but there also was [reported](https://github.com/Leaflet/Leaflet/issues/6668#issuecomment-547613966) more serious flow with numbers in scientific notation:
```js
var line = L.polyline([[0,-7.993322e-10],[10,20],[20,30]]);
L.geoJson(line.toGeoJSON());//errors on NaN
L.Util.formatNum(-7.993322e-10); //Returns NaN
```

But you may consider "2nd best" approach with epsilon:
```js
  function formatNum_epsilon(num, digits) {
  	var pow = Math.pow(10, (digits === undefined ? 6 : digits));
  	return Math.round((num + Math.sign(num) * Number.EPSILON) * pow) / pow;
  }
```
With this function we get almost same precision as in your original PR:
```js
L.Util.formatNum(1.005, 2) === 1.01
L.Util.formatNum(-1.005, 2) === -1.01
L.Util.formatNum(1.555, 2) === 1.56
L.Util.formatNum(-1.555, 2) === -1.56
L.Util.formatNum(-7.993322e-10, 16) === -7.993322e-10
L.Util.formatNum(-1.4837191022531273, 18) === -1.4837191022531275 // Round-off error
```
Performance is great: https://jsperf.com/leaflet-issue-6668/2
