### ISSUE TITLE
Default attribution links to non https leafletjs.js website

### ISSUE THREAD

**Issue by WillSelway** [Leaflet/Leaflet#6589]
- [ X] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected (specifically https://leafletjs.com/reference-1.4.0.html#control-attribution)
- [X ] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework
- [ X] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- Load a map with default settings

**Expected behavior**
The default attribution link should link to HTTPS not HTTP, or their should be at least an easy way to set it to HTTPS when creating a new map.

**Current behavior**
Its links to HTTP.

**Additional context**
We have fixed this by doing the below:

```
map.attributionControl._container.innerHTML = '<a href="https://leafletjs.com" title="A JS library for interactive maps">Leaflet</a> | Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors';
```

This is an issue for us as linking to non-https sites breaks almost every SEO/general web audit tool.

**Comment by IvanSanchez** [comment]
Could you please turn that change into a pull request? Looks like a simple enough thing to do.
