### ISSUE TITLE
Create tooltips in asynchronous way

### ISSUE THREAD

**Issue by garrappachc** [Leaflet/Leaflet#6595]
I like the way leaflet handles creating tooltips via callbacks.
Consider the following code:
`L.marker([0, 0]).bindTooltip(() => return document.createElement('div'));`

This is great, because the function will get executed only when I actually need the tooltip to be shown, thus not creating _n_ tooltips for _n_ markers beforehand. But what if I need to display data that is retrieved from async context? I'm forced to prefetch required data or see the tooltip being resized fraction of a second right after it is rendered. It would look much better if I could write the following:

```
L.marker([0, 0]).bindTooltip(async () => {
  const data = await fetchData();
  return `<div>${data}</div>`;
});
```

I think leaflet could handle creating tooltips in asynchronous way, using Promises. The tooltip won't be shown until the promise is resolved and thus there will be no needlessly resized tooltip.

I'm sorry if I went ahead of the project coding style, I don't know what approach for async calls does leaflet use, as I use it mainly from _ngx-leaflet_. The code above is a general idea.

**Comment by IvanSanchez** [comment]
Create an empty element and return it, while scheduling the async call to fill it up.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by hsablonniere** [comment]
@IvanSanchez Hey, I have a similar situation. Reading your suggestion, I was wondering if the position is updated based on the new size of the container.
