### ISSUE TITLE
.off(): unexpected behavior

### ISSUE THREAD

**Issue by johnd0e** [Leaflet/Leaflet#6596]
**`.off()` method unexpectedly removes listeners of the parent object**

- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- create any `layer` and add it Layers control
- attach on 'overlayadd' event listener to `map`
- remove listeners from `layer` (https://leafletjs.com/reference-1.4.0.html#layergroup-off)

**Expected behavior**

Only listeners **directly** attached to `layer` should be removed

**Current behavior**

`map` listeners get removed too, unexpectedly

**Environment**
- Leaflet version: 1.4
- Browser (with version): Chrome 73.0.3683.103 (Official Build) (32-bit)
- OS/Platform (with version): Windows 10 (32-bit)

**Additional context**

It can appear that this behavior is by current leaflet design.
In this case we should at least document it explicitly and in detail!

**Minimal example reproducing the issue**
```
var map = mymap;
var layer = L.layerGroup();
L.control.layers({},{layer:layer}).addTo(map);

map.on('overlayadd',()=>map.openTooltip('map event',map.getCenter()));

// uncomment this to see the issue:

//layer.off()
```

https://jsfiddle.net/johnd0e/jy84gsL2/16/

**Comment by johnd0e** [comment]
Current behavior is highly undesirable in my setup, because:
* map listeners is bound in main script
* layer(s) is processed in independent plugin(s)

So I'd prefer if plugin'd not affect main script base functionality.

**Comment by IvanSanchez** [comment]
> Expected behavior

> Only listeners **directly** attached to `layer` should be removed

I disagree. The point of `.off()`is to remove *all* event listeners, no matter where they were attached from.

> In this case we should at least document it explicitly and in detail!

I agree with this. This should be a simple case of changing the wording at...

https://github.com/Leaflet/Leaflet/blob/3f5979bb688e975a2d6dee0d9a663116c55dbdff/src/core/Events.js#L68

...and adding something like "This includes implicitly attached events". Not sure what the best wording would be.

**Comment by johnd0e** [comment]
> The point of `.off()`is to remove _all_ event listeners, no matter where they were attached from.

I can agree with this.
But then it would be convenient to have also more 'safe' version of `.off`, which unbind only explicit listeners.

**Comment by IvanSanchez** [comment]
But there is no way to tell apart "implicit" versus "explicit" event listeners in the code.

**Comment by johnd0e** [comment]
Well, I suppose we can improve the code. Like, add owner to every listener as a property.

**Comment by lancebendo** [comment]
[#6619](url)

**Comment by lancebendo** [comment]
1a50bd81dac84ce1f6368540cb8d6b240374a09c
