### ISSUE TITLE
DivOverlay methods are not documented

### ISSUE THREAD

**Issue by johnd0e** [Leaflet/Leaflet#6597]
[DivOverlay](https://leafletjs.com/reference-1.4.0.html#divoverlay) manual section documents options, events, but not methods.

- Some of methods are mentioned in [Popup](https://leafletjs.com/reference-1.4.0.html#popup-getlatlng) section
- Some documented wrong: https://github.com/Leaflet/Leaflet/blob/d5201acee0234ff4239cc8cbfa59c687286a2692/src/layer/DivOverlay.js#L104
- [Tooltip](https://leafletjs.com/reference-1.4.0.html#tooltip) section does not mention those methods, but from code it's obvious that L.Tooltip has the same methods

I suppose part of Popup methods documentation should be moved to DivOverlay, and then Popup and Tooltip linked to DivOverlay methods description.

**Comment by wigsters52** [comment]
I would love to work on this. Would that be okay?
