### ISSUE TITLE
Layers are not selected in layer control

### ISSUE THREAD

**Issue by bferreira** [Leaflet/Leaflet#660]
Hi,

I'm using tile layers (WMS). My problem is that, although the layers are visible when I open my map, they are not selected in the Layers control.
Then if I choose to select a layer in the Layers control, the map will finally reflect what is selected and what is not.

I don't think this is working properly.

Regards,
Barbara

**Comment by ppKrauss** [comment]
hi @mourner ,  seems the same problem with me: there are no "set default" or "selected"  for  first layer.
The [example at docs](https://leafletjs.com/examples/layers-control/) not show how to say "!!THIS IS THE DEFAULT LAYER!!",

```js
var baseMaps = {
    "Grayscale": grayscale,   // how to say this is default
    "Streets": streets
};
```
... as in HTML `<select>` or `checked` in HTML checkbox.
