### ISSUE TITLE
countries support

### ISSUE THREAD

**Issue by alirezaseif28** [Leaflet/Leaflet#6603]
What are the countries that are close to the map leaflet servers?
thanks

**Comment by IvanSanchez** [comment]
Leaflet is not coupled to a particular set of map servers.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by alirezaseif28** [comment]
Hi @IvanSanchez .
Thanks
