### ISSUE TITLE
Maps missing tiles on Android devices

### ISSUE THREAD

**Issue by jmaynardgit** [Leaflet/Leaflet#6606]
take a working app (Fine on iOS browser, iOS Cordova, MacOS browser)
Run on Android device - as Cordova App, or just HTML (with identikits tidal code as iOS)
- ...

**Expected behavior**
Map to be displayed fully

**Current behavior**
Only some tiles are displayed (usually just the top part of any map)

**Environment**
- Leaflet version: 1.04
- Browser (with version): Safari (Mac); Silk (Android)
- OS/Platform (with version): iOS 12; Fire OS 5.6.1.0 (same issue on users' Google devices)

**Comment by IvanSanchez** [comment]
Which tile servers are you running? Are you logging tile errors and network traffic?

**Comment by IvanSanchez** [comment]
Or is this the dreaded "I forgot to run `map.invalidateSize()` when the container changed size so only the top-left part displays properly" problem?

**Comment by jmaynardgit** [comment]
I have two versions of the app using the same code base. The main version has the map tiles embedded in teh app; if the app detects the tiles folder is missing the maps are drawn by reference to OSM. Both versions work fine in any Mac browser and as an iOS app and as a MacOS app. Both versions do not work as an app on Android (same issue with built in and OSM tiles) only some tiles are drawn. If I point a browser at the HTML it works fine on Mac or iOS but not on Android (or Amazon Fire). If you PM me at jeff@jeffmaynard.com I can point to the code for you to try...
Thanks for your attention to this

**Comment by IvanSanchez** [comment]
I'm gonna go with "public demo which consistently reproduces the bug or it didn't happen". Asking to switch to a private conversation is bad etiquette here.

I suggest reading ["How To Ask Questions The Smart Way"](http://www.catb.org/esr/faqs/smart-questions.html) and ["http://www.chiark.greenend.org.uk/~sgtatham/bugs.html"](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html)

**Comment by jmaynardgit** [comment]
I only wanted a PM to avoid posting a private web link in a public forum…
