### ISSUE TITLE
Leaflet 怎么把 D3 渲染的结果能都跟地图叠加准确

### ISSUE THREAD

**Issue by wo4861069** [Leaflet/Leaflet#6608]
<!DOCTYPE html>
<html>

<head>
    <title>d3 path</title>
</head>
<link rel="stylesheet" type="text/css" href="https://unpkg.com/leaflet@1.4.0/dist/leaflet.css">
<link rel="stylesheet" href="http://iclient.supermap.io/dist/leaflet/iclient9-leaflet.min.css"/>
<script type="text/javascript" src="https://unpkg.com/leaflet@1.4.0/dist/leaflet.js"></script>
<script src="https://d3js.org/d3.v4.min.js"></script>
<script src="https://d3js.org/d3-color.v1.min.js"></script>
<script src="https://d3js.org/d3-hsv.v0.1.min.js"></script>
<script src="JS/jquery-1.12.4.min.js"></script>
<script src="lib/d3-contour.js"></script>
<script type="text/javascript" src="http://iclient.supermap.io/dist/leaflet/iclient9-leaflet.js"></script>
<script src="http://iclient.supermap.io/libs/leaflet/plugins/leaflet.d3Layer/leaflet-d3Layer.min.js"></script>

<style>
    html,
    body {
        margin: 0;
        padding: 0;
    }

    #map {
        width: 100%;
        height: calc(100vh)
    }
</style>

<body>  
    <div id="map"></div>
    <script type="text/javascript">
        var mymap = L.map('map').setView([35.998, 121.98670782], 4);
        L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            maxZoom: 18,
            noWrap: true
        }).addTo(mymap);

        var svg = d3.select(mymap.getPanes().overlayPane).append('svg')
            .attr('class', 'svgTransform')
            .attr("id", "d3_svg");  
       // mymap.on("zoom", resetView)

        function resetView() {
                    d3.selectAll("#pointMove").remove()
                    addPath()
                } 
        function addPath() {
            var i0 = d3.interpolateHsvLong(d3.hsv("#96f3ff"), d3.hsv("#fffa00")),
            i1 = d3.interpolateHsvLong(d3.hsv("#fffa00"), d3.hsv("#ff7300")),
            i2 = d3.interpolateHsvLong(d3.hsv("#ff7300"), d3.hsv("#8200a0")),
            interpolateTerrain = function(t) {
                    if(t<0.5)
                    {
                    return i0(t * 2);
                    }
                    else if(t>0.5||t<1)
                    {
                    return i1((t - 0.5) *2.5)
                    }else{
                    return i2((t - 1) * 2)
                    }
                },
            color = d3.scaleSequential(interpolateTerrain).domain([0, 190]);
          
        d3.json("data/2019041510_AQI.json", function(error, volcano) {
        if (error) throw error;
        var header = volcano[0].header,
        data = volcano[0].data
         var pointmin = mymap.latLngToLayerPoint(new L.LatLng(54, 73));
         var pointmax = mymap.latLngToLayerPoint(new L.LatLng(18, 136));
         console.log(pointmax.x-pointmin.x)
         console.log(pointmax.y-pointmin.y)
        // console.log(point);//x: 211, y: 609
        // d3.select('svg').attr('transform','translate('+point.x+',' +point.y+')')
        var d3Layer = L.supermap.d3Layer(function(sel,proj){
           sel.selectAll("path")
           .data(d3.contours()
                .size([header.nx, header.ny])
                .thresholds(d3.range(0, 250, 5))
            (data))
            .enter().append("path")
            .attr("d", d3.geoPath(d3.geoIdentity().scale(630 / header.nx)))
            .attr("transform",function(d){
                return "translate(" + pointmin.x + ","+ pointmin.y + ")";
            })
            .attr("fill",function(d){
                return color(d.value); 
            })

        });
         d3Layer.addTo(mymap);
        }); 
        }

        function initial() {
            svg.attr("width", 630)
                .attr("height", 360);
            addPath(); 
        }
        initial()
    </script>
</body>

</html>

代码是这样求指点一下谢谢了 我的QQ 361458994

--------------^ Click "Preview" tab for a nicer view!

We use GitHub as an issue tracker.
For usage and support questions, please check out resources below:

1. Read Leaflet documentation: https://leafletjs.com
2. For support questions like "How can I do X with Leaflet?" please search or ask questions on StackOverflow or StackExchange using Leaflet tag:
  - https://stackoverflow.com/questions/tagged/leaflet
  - https://gis.stackexchange.com/questions/tagged/leaflet

Thanks!

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.
