### ISSUE TITLE
How to get list of visible markers on viewport map ?

### ISSUE THREAD

**Issue by matp5** [Leaflet/Leaflet#6612]
Hello, I need to display markers on leaflet map from api and next to map list of them. I want to make: If I zoom map, the list of markers should display only these which are currently on viewport of map. Like [here](https://www.airbnb.co.uk/s/Croatia/homes?refinement_paths%5B%5D=%2Fhomes&query=Croatia&checkin=2019-04-18&checkout=2019-04-28&adults=0&children=0&infants=0&guests=0&toddlers=0&search_type=UNKNOWN&allow_override%5B%5D=&zoom=8&search_by_map=true&sw_lat=42.500684712387056&sw_lng=13.59894624609376&ne_lat=45.91316276368805&ne_lng=17.09809175390626&s_tag=daBYQt_R)

I tried with: [Get a list of markers/layers within current map bounds in Leaflet](https://stackoverflow.com/questions/22081680/get-a-list-of-markers-layers-within-current-map-bounds-in-leaflet) but it doesnt work or I did something wrong

Working snippet: https://stackoverflow.com/questions/55741456/how-to-get-list-of-visible-markers-on-viewport-map-in-leaflet-osm

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
