### ISSUE TITLE
Want to have multiple geoJson Overlay

### ISSUE THREAD

**Issue by meteoDaniel** [Leaflet/Leaflet#6615]
Dear all, 

based on  folium Timestamped GeoJSON macro i want to have 2 geoJSON Layer on one map to have it selectable via the layerControl. But actually it creates two time sliders and it is not selectable via the layerControl. 

On the following way both layers were added to the map: 
```
L.timeDimension.layer.geoJson(geoJsonLayer,
                {updateTimeDimension: false,
                }).addTo(base_map)
```
The existend folium code is now taken `layer_name` and the layer object of all children from the parent map (`base_map`),  And to have the geoJSON as an overlay I guess I need to define a `layer_name`. But this property is not available 
Any ideas or solutions?

![Bildschirmfoto vom 2019-04-21 17-57-53](https://user-images.githubusercontent.com/27021858/56472532-ebaa7b80-645f-11e9-8251-7fa5eb7e28f7.png)

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by meteoDaniel** [comment]
@IvanSanchez than please change the settings of the tracker board and delete the `Support` category.
