### ISSUE TITLE
Missing tiles on android 

### ISSUE THREAD

**Issue by jmaynardgit** [Leaflet/Leaflet#6617]
I have two versions of an app using the same code base. The main version has the map tiles embedded in the app; if the app detects the tiles folder is missing the maps are drawn by reference to OSM. Both versions work fine in any Mac browser and as an iOS app and as a MacOS app. Both versions no longer work as an app on Android (same issue with built in and OSM tiles) only some tiles are drawn. If I point a browser at the HTML it works fine on Mac or iOS but not on Android (or Amazon Fire). 

Thanks for your attention to this

Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.
I would have to point you to the full app code but do not want to put a link on a public forum...

**Comment by jmaynardgit** [comment]
PS same problem on Windows (using VMWare)

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?

**Comment by jmaynardgit** [comment]
> Can you publish a fiddle/codepen/plunkr that displays this behaviour?

I'm not sure I can do that - the offending page has 43 JS files and a dozen CSS files needed to function. I ran some more tests this morning using Chrome (Windows and Mac) - no Console messages are shown although the map only draws the top few tiles; however, slightly resizing the window causes the entire map to draw...

does this suggest anything that you can suggest to try for a fix?
thanks

**Comment by IvanSanchez** [comment]
> does this suggest anything that you can suggest to try for a fix?

Not really. Sounds like a case of not using `invalidateSize()`, which is *not* a Leaflet bug.

**Comment by jmaynardgit** [comment]
> Not really. Sounds like a case of not using invalidateSize(), which is not a Leaflet bug.

That led me to a solution...
so, thanks anyway
