### ISSUE TITLE
Disable auto center adjust after change marker coordinates programmatically

### ISSUE THREAD

**Issue by ckristhoff** [Leaflet/Leaflet#6620]
Hi everyone
after change marker coordinates programatically leflet auto adust the center map. My app track device location but user can focus in other markers.

My map losses the marker focus each time user moves.

How disable this behavior?

Example [http://angular-ui.github.io/ui-leaflet/#!/examples/dragging-markers](http://angular-ui.github.io/ui-leaflet/#!/examples/dragging-markers)

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
