### ISSUE TITLE
How to detect map unload

### ISSUE THREAD

**Issue by patolax** [Leaflet/Leaflet#6621]
I want to save selected overlay layers on layers control to local storage so that I can preselect them when the user reloads the map next time.

I tried using leafletMap.on('overlayremove') and overlayadd methods to cache the selected layers, however, the same methods are been called when the map unloads so I end up with an empty list at the end.

Is there a way to detect leaflet map is about to be unloaded, so that I can grab selected layers before they are been removed.

**Comment by johnd0e** [comment]
> I tried using leafletMap.on('overlayremove')

```
leafletMap.on('unload', function() {
  leafletMap.off('overlayremove')
})
```
It's just an idea, untested

**Comment by nielswitte** [comment]
I've tested this, but `overlayremove` was called for each visible layer before `unload` of the map.

> > I tried using leafletMap.on('overlayremove')
> 
> ```
> leafletMap.on('unload', function() {
>   leafletMap.off('overlayremove');
> });
> ```
> 
> It's just an idea, untested

**Comment by johnd0e** [comment]
@nielswitte 
In current code I see that `unload` is fired **before** any layers removing.
Please confirm that you still suffer from the issue.

**Comment by nielswitte** [comment]
> @nielswitte
> In current code I see that `unload` is fired **before** any layers removing.
> Please confirm that you still suffer from the issue.

I don't know, haven't looked at this for a while. 

I'm using another way to allow restoring visible layers of a previous session.
In my case I am using Angular with ngx-leaflet, showing and hiding layers is now done by using `*ngIf` on the dom element containing the layer:

i.e.:
```html
<div *ngIf="overlay1.enabled" [leafletLayer]="overlay1.layer"></div>
<div *ngIf="overlay2.enabled" [leafletLayer]="overlay2.layer"></div>
<div *ngIf="overlay3.enabled" [leafletLayer]="overlay3.layer"></div>
```
The value of `overlay1.enabled` is stored in localstorage in the `onDestroy()` of the component and restored in the `ngOnInit()`

**Comment by Falke-Design** [comment]
This is no problem anymore:

https://github.com/Leaflet/Leaflet/blob/0b8ce652ba7b519d52851aed443c11c8afe8df90/src/map/Map.js#L777-L787
