### ISSUE TITLE
Best practices when multiple Leaflet libraries are loaded

### ISSUE THREAD

**Issue by drwelby** [Leaflet/Leaflet#6624]
Users of Jupyter Notebooks and JupyterLab are running into problems when using multiple extensions that each try to load their own Leaflet libraries.

Examples:

https://github.com/jupyter-widgets/ipyleaflet/issues/337
https://github.com/jupyter-widgets/ipyleaflet/issues/294

I tried this as a solution here:

https://github.com/jupyter-widgets/ipyleaflet/pull/295

which fixed the problem in my Jupyter Notebooks use case but did not work in the case of the 337 issue above. It is not known if this is due to 337 using JupyterLab versus Jupyter or something else, such as the extension loading order.

Most problems see to revolve around plugins disappearing, so for example the first Leaflet load adds the Leaflet.Draw extension, then the second Leaflet loaded takes over the L global and the extension can't be found.

Both extensions are using `require` to load Leaflet.

Is there a pattern that Jupyter extension developers can adopt to load Leaflet safely that isolates each library?

**Comment by IvanSanchez** [comment]
I think the problem resides not in the several Leaflet instance, but in how the plugins (i.e. Leaflet Draw) attach themselves to the Leaflet instance.

Most plugins are written in such a way that they *assume* the `L` global variable to be defined (or `window.L`). That's the case of Leaflet.Draw, which code starts with `L.drawVersion = "1.x"` - that assignment assumes that Leaflet is available as a global variable.

Any other pattern would make plugins more cumbersome to develop and load :-|

> Is there a pattern that Jupyter extension developers can adopt to load Leaflet safely that isolates each library?

There are a couple dirty javascript tricks that can be useful:

- Shamelessly reassign the `L` global to the "active" instance before loading a plugin
- Add more tooling to wrap the plugin code in a [IIFE](https://en.wikipedia.org/wiki/Immediately_invoked_function_expression), kinda:

```
var myLeafletInstance = require('leaflet');
(function(L) {
    /* plugin code goes here */
})(myLeafletInstance);
```

There's nothing that we can do in core Leaflet to improve this, short of revamping the whole architecture and taking on the maintenance of plugins :-(
