### ISSUE TITLE
I want to display specific country map

### ISSUE THREAD

**Issue by saileshkush95** [Leaflet/Leaflet#6627]
I'm new to leaflet and I'm try to build web application based on location base. Initially it display all the map including other country.  What is want is to display only one country map  boundary based on geojson data. Please help me out Thanks,
Example pic:
![Screenshot from 2019-04-28 23-07-32](https://user-images.githubusercontent.com/28560875/56867860-97c50700-6a0a-11e9-92f4-b07963bb869f.png)

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
