### ISSUE TITLE
Zooming on map within iframe causes Samsung Galaxy to freeze map

### ISSUE THREAD

**Issue by nomadkj** [Leaflet/Leaflet#6632]
**Situation**
We need the map to capture pointer events to interact with 6.000+ canvas shapes, plotted on a Grid layer. We need to check for click events, mouse moves, etc. on the canvases.
All works fine when the map is not loaded within an iframe.

To capture pointer events, we have set:

`	.leaflet-tile-container{
		pointer-events:visiblePainted;
		pointer-events:auto
	}
`

However, when the map is displayed within an iframe (with pointer-events set to auto) Samsung Galaxy devices cause the map to freeze after zooming in / out after a while (fast zooming causes the map to freeze quickly)

On all other touch devices, except for Samsung devices, the map works just fine (also within an iframe). We have tested multiple Android and iOS devices (HTC One, OnePlus, iPhone 5, iPhone7 etc.)

**Steps to reproduce**
- Step 1: Test on a Samsung Galaxy
- Step 2: Open https://onlinebikelight.com/galaxy.html
- Step 3: Start zooming in / out fast
- ... Map freezes

**Expected behavior**
Expected behavior: Map shouldn't freeze.
When the map is not loaded in an iframe but directly in the browser, like here:
https://onlinebikelight.com/map.html
The map won't freeze on a Samsung Galaxy 

**Current behavior**
The map freezes when loaded within an iframe on a Samsung Galaxy, with pointer-events set to auto.

**Environment**
- Leaflet 1.4.0
- Browser: Chrome (all recent versions), Samsung stock browser
- OS: Android (all recent versions)
- Devices: Samsung Galaxy (tested on Galaxy S6, S8, S9)

**Minimal example reproducing the issue**
_IMPORTANT: Test on Samsung Galaxy!_
Works perfectly fine when zooming in / out in browser:  https://onlinebikelight.com/map.html
However, map freezes when embedded in iframe:  https://onlinebikelight.com/galaxy.html

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**UPDATE**
When the map is displayed in an iframe on a Samsung Galaxy device, but within **FireFox** instead of **Chrome** or **Samsung stock browser**, the map won't freeze.

So the issue really has to do with:

- Leaflet map with `pointer-events: auto;`
- loaded within an `<iframe>`
- on a **Samsung Galaxy** device
- within **Chrome** or the **Samsung stock browser**

**Comment by IvanSanchez** [comment]
Weird. Does this happen as well on a non-samsung phone/tablet?

**Comment by nomadkj** [comment]
No, it doesn't happen on non-samsung phones/tablets..

On HTC / OnePlus / iPhone, everything works just fine..

We've been working on this for days now, but can't find anything.

**Comment by nomadkj** [comment]
Also, when the map is displayed within an iframe on a Samsung Galaxy device, but within FireFox instead of Chrome, the map won't freeze.

So the issue really has to do with:

- Leaflet map loaded within an iframe, with `pointer-events: auto;`
- on a Samsung Galaxy device
- within a Chrome browser

**Comment by tomchadwin** [comment]
Can't reproduce, but with an *old* Galaxy:

S4 mini
Chrome 72.0.3626.121
Android 4.4.2 (preinstalled Samsung version)

It lags a tad, but that's not surprising, given the age of the phone.

**Comment by nomadkj** [comment]
Weird.. on newer Galaxy's the map definitely does freeze, eventually.
(Sometimes soon, sometimes after a little while of zooming/panning).

**Comment by johnd0e** [comment]
I can reproduce this on non-Samsung device, using Samsung browser (https://play.google.com/store/apps/details?id=com.sec.android.app.sbrowser)

**Comment by johnd0e** [comment]
It's pretty easy to connect with DevTools and reproduce the issue using long continuous pinch-zoom (back and forth).
It seems that pointers eventually 'disappers', in the middle of action, without proper `touchend` or `touchcancel`. Thus our pointer counter does not decrease after release, and on next touch it increases to value > 2, preventing all gestures.

Perhaps this is browser's bug. Best I can propose - apply #7029.
