### ISSUE TITLE
npm install deprecation warnings

### ISSUE THREAD

**Issue by rheh** [Leaflet/Leaflet#6633]
- git clone the master branch
- run npm install
- ...

**Expected behavior**
Clean install with no deprecation warnings

**Current behavior**
The following warnings: some projecting braking changes
```
npm WARN deprecated rollup-watch@4.3.1: rollup-watch functionality is now included in Rollup itself
npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm WARN deprecated formatio@1.1.1: This package is unmaintained. Use @sinonjs/formatio instead
npm WARN deprecated samsam@1.1.2: This package has been deprecated in favour of @sinonjs/samsam
npm WARN deprecated samsam@1.1.3: This package has been deprecated in favour of @sinonjs/samsam
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
```

**Environment**
- 1.4.0,
- Browser not relevant
- OS/Platform Windows 10 home edition with ubuntu bionic beaver installed

**Additional context**
None

**Minimal example reproducing the issue**
Not relevant as not a bug with leaflet, just some issues regarding source code and build chain

**Comment by IvanSanchez** [comment]
Is any particular dependency causing this?

**Comment by rheh** [comment]
Dependency causing the above are:

rollup-watch: is directly included in the package.json
istanbul: This is a dependency of karma-coverage
formatio:  This is a dependency of sinon
samsam:  This is a dependency of sinon
graceful-fs:  This is a sub-dependency of phantomjs-prebuilt
circular-json:  This is a sub-dependency of eslint
natives:  This is a sub-dependency of leafdoc

Command used to show tree:

```
npm la <package-name>
```

That does imply some are downstream, but, one wonders whether these are because the packacge.json is using an older version?

**Comment by jonkoops** [comment]
We are up-to-date with all the latest so this should no longer be an issue.
