### ISSUE TITLE
Getting a search result based on area or country - Additional feature

### ISSUE THREAD

**Issue by emc420** [Leaflet/Leaflet#6638]
**Is your feature request related to a problem? Please describe.**
I was working in a project where I wanted the users to search all the places based on a keyword within a country or an area. For e:g if some one wants to search for all the 7 11 stores or IKEA stores or airports may be in a particular country or area. 

**Describe the solution you'd like**

**Describe alternatives you've considered**
I have tried using the auto suggest feature where i fetched the result based on the keyword and plotted them on the map. But the problem is it is random and not based on a specific country and even if we can it can plot maximum upto 20 points. Is it possible that we could do something like this to get all possible results based on a country or area.  

**Additional context**

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
