### ISSUE TITLE
PhantomJS is Unmaintained

### ISSUE THREAD

**Issue by ossdev07** [Leaflet/Leaflet#6643]
**Is your feature request related to a problem? Please describe.**
PhantomJS is an unmaintained project, and it will be good to replace it with some maintained alternatives.

**Describe the solution you'd like**
I would like to ask the team if they will be interested in dropping phantomjs as browser testing dependency.

**Describe alternatives you've considered**
karma-chrome-launcher could be the best alternative to use in replacement to karma-phantomjs-launcher.

**Additional context**
It will be a delight to see phantomjs removed from the package, I will be happy to provide a PR with the proposed changes. Please share your views on this.

**Comment by ossdev07** [comment]
@mourner Sure We can use chrome headless.
In my view puppeteer, does not support all the architectures like aarch64.
I am currently trying to use chrome headless as it provides a headless environment to run the test suite and support different architectures as well, although I am facing issue in 7 test cases with chrome headless please have a look:

```
HeadlessChrome 73.0.3683 (Ubuntu 0.0.0) Marker.Drag drag in CSS scaled container drags a marker with mouse, compensating for CSS scale FAILED
        Error: Uncaught TypeError: Cannot read property 'dispatchEvent' of null (node_modules/prosthetic-hand/dist/prosthetic-hand.js:1071)
..............................................................................
HeadlessChrome 73.0.3683 (Ubuntu 0.0.0) Canvas #events should not fire click when dragging the map on top of it FAILED
        Error: Uncaught Error: expected true to equal false (node_modules/expect.js/index.js:102)
...........................................................
WARN: 'Deprecated use of _flat, please use L.LineUtil.isFlat instead.'
.
WARN: 'Deprecated use of _flat, please use L.LineUtil.isFlat instead.'
................................................................................
..................................................
HeadlessChrome 73.0.3683 (Ubuntu 0.0.0) Map.Drag mouse events change the center of the map FAILED
        Error: Uncaught Error: expected 0 to be within 21.943..21.9431 (node_modules/expect.js/index.js:102)
......
HeadlessChrome 73.0.3683 (Ubuntu 0.0.0) Map.Drag touch events change the center of the map FAILED
        Error: Uncaught Error: expected 0 to be within 21.943..21.9431 (node_modules/expect.js/index.js:102)
.
HeadlessChrome 73.0.3683 (Ubuntu 0.0.0) Map.Drag touch events reset itself after touchend FAILED
        Error: Uncaught Error: expected { lat: 0, lng: 0 } to sort of not equal { lat: 0, lng: 0 } (node_modules/expect.js/index.js:102)
.............
HeadlessChrome 73.0.3683 (Ubuntu 0.0.0) Map.TouchZoom Increases zoom when pinching out FAILED
        Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
HeadlessChrome 73.0.3683 (Ubuntu 0.0.0) Map.TouchZoom Decreases zoom when pinching in FAILED
        Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
HeadlessChrome 73.0.3683 (Ubuntu 0.0.0): Executed 676 of 679 (7 FAILED) (skipped 3) (28.274 secs / NaN secs)
```

I will be really glad if you could have a look at these and revert if you have any input.

**Comment by ossdev07** [comment]
@mourner I was successfully able to replace the phantomjs with Firefox browser.
I have raised pull request for the same https://github.com/Leaflet/Leaflet/pull/6665 , Please have a look and do let me know if you have any concerns.

**Comment by johnd0e** [comment]
I believe that we should not retire PhantomJS:
a. Leaflet anyway should be tested on a variety of configurations including legacy ones.
b. it is much lighter than any other alternative (compare with 250MB required for Chromium)
c. so it's great for quick-test.

Any extra browser also need to be tested, if installed.
