### ISSUE TITLE
how to input scale get map zoom number in leaflet  ？

### ISSUE THREAD

**Issue by liuvigongzuoshi** [Leaflet/Leaflet#6649]
## how to input scale(1:1000/etc) get map zoom number in leaflet  ？

See a plugin "leaflet.ScaleFactor"(Display a Scale Factor (1:50,000) for Leaflet maps)

[leaflet.ScaleFactor/leaflet.scalefactor.js](https://github.com/MarcChasse/leaflet.ScaleFactor/blob/master/leaflet.scalefactor.js)

But how to use a scale get zoom number ?

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
