### ISSUE TITLE
Leaflet 1.5.1 has wrong sha-512 integrity hashes

### ISSUE THREAD

**Issue by vassilaros** [Leaflet/Leaflet#6650]
I install 1.5.0 and it works perfect. The hosted version from CDN. I try to install the 1.5.1 and it doesn't work. 
![error](https://user-images.githubusercontent.com/1454155/57431439-7f8b8e00-723b-11e9-8f21-fa04cb89f692.png)

**Comment by IvanSanchez** [comment]
@cherniavskii The sha-512 integrity hashes from https://github.com/Leaflet/Leaflet/commit/80edb4e9680795ab170ce8eb0f2e9dea36ff0408 don't match 1.5.1 for whatever reason :-| Perhaps you can run `build/integrity.js` again and see if the values differ?

See https://plnkr.co/edit/SiftZTQzSpTkUZ5aiQve?p=preview
