### ISSUE TITLE
SVGOverlay not working

### ISSUE THREAD

**Issue by bengaid** [Leaflet/Leaflet#6653]
**Steps to reproduce**
Just testing SVGOverlay example given in https://leafletjs.com/reference-1.5.0.html#svgoverlay with the a simplified quick start example https://leafletjs.com/examples/quick-start/example.html

**Expected behavior**
It is expected to get the correct rendering of the svg example on the map.

**Current behavior**

The following error is displayed on console, with no rendering
```
Uncaught TypeError: Cannot read property 'baseVal' of undefined
    at gi (leaflet.js:5)
    at di (leaflet.js:5)
    at pi (leaflet.js:5)
    at i._initImage (leaflet.js:5)
    at i.onAdd (leaflet.js:5)
    at i._layerAdd (leaflet.js:5)
    at i.whenReady (leaflet.js:5)
    at i.addLayer (leaflet.js:5)
    at i.addTo (leaflet.js:5)
    at hello-world-leaflet-svg-layer.html:36
```

**Environment**
- Leaflet version: 1.5.1
- Browser (with version): Google Chrome 74.0.3729.131
- OS/Platform (with version): Windows 7 64 bits SP1

**Minimal example reproducing the issue**

[see example on plnkr](https://plnkr.co/edit/zK6Ync2o23viZxSugBoX?p=preview)

**Comment by cherniavskii** [comment]
Actually that code example is wrong, `SVGOverlay` itself works just fine.

**Comment by bengaid** [comment]
Thank you @cherniavskii 
Fixed doc example works well
