### ISSUE TITLE
bower.json missing in version 1.5.x

### ISSUE THREAD

**Issue by NielsHolt** [Leaflet/Leaflet#6654]
bower.json was removed in version 1.5.0
Please put it back again :-)

**Comment by IvanSanchez** [comment]
We consider bower to be deprecated, that's why it was removed in https://github.com/Leaflet/Leaflet/pull/6635

**Comment by NielsHolt** [comment]
Hi
Bower is still maintained and use by many people. I dont think it is the job of leaflet to deside how the user include leaflet. That is not the open source spirit! 
In this case it is ONE small json-file that need NO maintenance, so why not just leave it there??

**Comment by IvanSanchez** [comment]
![image](https://user-images.githubusercontent.com/1125786/57603314-a3174700-7561-11e9-92e2-cde005a0e9f3.png)

Bower is telling users to not use bower since *checks notes* 1½ years ago. At this point I don't think it's wrong to disencourage bower users.

**Comment by NielsHolt** [comment]
But why delete a file that require no maintenance????
