### ISSUE TITLE
API not working after dojo.js

### ISSUE THREAD

**Issue by pcuisinaud** [Leaflet/Leaflet#6655]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
Include the dojo.js BEFORE leaflet.js, the API is not working and the map is not visible !
Include the dojo.js AFTER leaflet.js, the API is working fine and the map is visible...

**Expected behavior**
The Map is visible even if a dojo.js is included before

**Current behavior**
The browser logs the following error :
```
Uncaught ReferenceError: L is not defined
```

**Environment**
- Leaflet version: 1.4.0
- Browser (with version): Chrome (74.0.3729.131), Firefox (61.0.1), IE 11
- OS/Platform (with version): Windows 7 SP1

**Additional context**

**Minimal example reproducing the issue**

https://jsfiddle.net/pcuisinaud/2nayovur/

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/dojo/1.7.1/dojo.js"></script>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css" />
<script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"></script>

<div id="mapid" style="width: 600px; height: 400px;"></div>
```

```
var mymap = L.map('mapid').setView([47, 2], 5);
L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=' + token, {
  id: 'mapbox.streets'
}).addTo(mymap);
```

- [x] this example is as simple as possible
- [ ] this example does not rely on any third party code

**Comment by IvanSanchez** [comment]
It seems that Dojo sets up global `define` and `require` functions, thus acting as a AMD loader. The Leaflet code notices there is a global `define` and assumes it's being loaded from a AMD loader.

So, not a bug but actually intended behaviour (and a throwback to the times before good JS bundlers like webpack and rollupJS). Do read https://dojotoolkit.org/documentation/tutorials/1.10/modules/index.html , and consider loading Leaflet as a AMD if you are going the Dojo way:

```js
require({
    packages: [
        { name: "leaflet", location: "https://unpkg.com/leaflet@1.5.1", main: "dist/leaflet-src" },
    ]
}, ['leaflet'], function(L){
    
  var map = new L.Map(....); 
  
});
```

See a working example at https://plnkr.co/edit/bBG4YV4cuwiIH2LoWy3v?p=preview
