### ISSUE TITLE
Load GeoJSON as TileLayer

### ISSUE THREAD

**Issue by antoniolarasarabia** [Leaflet/Leaflet#6657]
I would like to be able to load a regular GeoJSON as a TileLayer, and not to have it in a GeoJSON layer.
Or to be able to transformn between one and the other kind.
So we could be able to load some  layers like countries borders for example.

There's an old plugin which does something similar*:
https://github.com/brandonxiang/leaflet-geojson-vt
*Even though this plugin does not gives us a tile layer, is kind of a custom tile layer.

**Comment by IvanSanchez** [comment]
https://github.com/Leaflet/Leaflet.VectorGrid/
