### ISSUE TITLE
Error when calling Path.setStyle before added to the map. Reopen #6516

### ISSUE THREAD

**Issue by NielsHolt** [Leaflet/Leaflet#6662]
Hi
Update L.Polyline's _pxBounds when their stroke weight changes was changed in #6516
In version 1.5 Path.setStyle now calls this._updateBounds() if stroke is set in options
But it fails it setStyle is called before the path is added to the map
this._updateBounds using _rawPxBounds witch isn't set before _project is called

I think that the fix is to call this._project() instead of this._updateBounds() in setStyle

**Comment by cherniavskii** [comment]
Hi @NielsHolt 
Can you fill our issue template?
Thanks.

**Comment by NielsHolt** [comment]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
Steps to reproduce the behavior:
```
var polyline = L.polyline([[45.51, -122.68],[37.77, -122.43],[34.04, -118.2]]);
polyline.setStyle({color: 'red', weight: 4});
polyline.addTo(map);
```

**Expected behavior**
In version 1.4 the above code adds a red polyline to map

**Current behavior**
In version 1.5.1 it fails calling `_updateBounds()`

**Environment**
- Leaflet version: 1.5.1
- Browser (with version): Chrome
- OS/Platform (with version): Windows

**Additional context**
HOW TO FIX IT:
In \src\layer\vector\Path.js line 104
```
setStyle: function (style) {
...
    if (this.options.stroke && style.hasOwnProperty('weight')) {
        this._updateBounds();
}
```
Replace with
```
    if (this.options.stroke && style.hasOwnProperty('weight')) {
        this._project();  //<-

```

**Minimal example reproducing the issue**

Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by IvanSanchez** [comment]
@NielsHolt Please make a pull request with the proposed fix, it's easier to review & merge.

**Comment by NielsHolt** [comment]
Hi @IvanSanchez 
I have created a pull request that should fix both #6662 and #6664

**Comment by fodor0205** [comment]
The original description does not seem to be correct:
> But it fails it setStyle is called before the path is added to the map

The described error only occurs with the following order:

1. Polyline added to the map
2. `setStyle()` called with weight

No error occurs the other way around: when `setStyle` is called before `addTo()`.

**Comment by johnd0e** [comment]
> Steps to reproduce the behavior:
> 
> ```
> var polyline = L.polyline([[45.51, -122.68],[37.77, -122.43],[34.04, -118.2]]);
> polyline.setStyle({color: 'red', weight: 4});
> polyline.addTo(map);
> ```

Unable to reproduce.
https://github.com/Leaflet/Leaflet/pull/6941#issuecomment-763472329
