### ISSUE TITLE
Inaccessible anchors in documentation

### ISSUE THREAD

**Issue by johnd0e** [Leaflet/Leaflet#6666]
Some parts of documentation refers to inherited options/events/methods.
That parts are in collapsed sections.

Definitions in that parts have own anchors, and it makes sense.
Unfortunately such anchors are mostly inaccessible while related sections are collapsed.

Sample:
https://leafletjs.com/reference-1.6.0.html#geojson-bindtooltip

Perhaps js part of docs can be improved to not collapse section which is referred in url.

**Comment by mourner** [comment]
cc @IvanSanchez for Leafdoc

**Comment by FadilEldin** [comment]
Modiefied provided example to the current version https://leafletjs.com/reference-1.6.0.html#geojson-bindtooltip
Should be closed as non issue
