### ISSUE TITLE
Leaflet loose compatibility with ionic on v1.5.1

### ISSUE THREAD

**Issue by rorp24** [Leaflet/Leaflet#6667]
On v1.5.1, leaflet don't work on ionic (the css is not loaded). So we have to go back to 1.4.0 to "fix" the problem

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.
