### ISSUE TITLE
Close custom popup fixed position

### ISSUE THREAD

**Issue by Noud63** [Leaflet/Leaflet#6672]
Hello,
I'm a javascript beginner.
I've created a custom popup on a fixed position on the left side of the (Leaflet)map. However when I close a popup the next popup I click  won't open. What to do?
Any help would be appreciated. 

`var redFlag = L.icon({
    iconUrl: 'images/mapmarker2.png',
    iconSize: [34, 34],
    iconAnchor: [17,34]
});

const myLayer = L.geoJSON(art, {
        pointToLayer: function (feature, latlng) {
              return L.marker(latlng, {icon: redFlag});
        
},
    onEachFeature: function ( feature, layer) {
        layer.on('click', function(e){
   
            var getWrap = document.getElementById('wrapper');
            var wrap = getWrap.appendChild(document.createElement('div'));
            wrap.className = 'wrapper';
            wrap.innerHTML =  
                `<div class="close">X</div>`+ 
                `<div class="popUpContent" style="background-color:#e8f4ff">` +
                `<div class='pic'><img src = "images/${feature.properties.image}"></div>`+ 
                `<div class="puName"><span class="puName">${feature.properties.name}</span><br>`+
                `<span class="puTitle">"${feature.properties.title}"</span><br>` + 
                `<div class="extra3">${feature.properties.extra}</div></div>`+ 
                `</div>`;
         
        if(!feature.properties.title){
            wrap.innerHTML =  
                `<div class="close">X</div>`+
                `<div class="popUpContent" style="background-color:#e8f4ff">` +
                `<div class='pic'><img src = "images/${feature.properties.image}"></div>`+ 
                `<div class="puName"><span class="puName">${feature.properties.name}</span><br>`+ 
                `<div class="extra3">${feature.properties.extra}</div></div>`+ 
                `</div>`;
             }

                document.querySelector('.close').addEventListener( 'click', closePopup);
          function closePopup(e){
                
                  if(event.target.matches('.close')){
                     document.querySelector(".wrapper").style.display='none'
                 }else if(document.querySelector(".wrapper").style.display='block'){
                     document.querySelector(".wrapper").style.display='none';
                 }
        }

         });
    }
    
});
mymap.addLayer(myLayer)`

**Comment by barryhunter** [comment]
Well your click handler seems to just be replacing the content of the `wrapper` element with new content. (although its slightly odd that it is adding **another** div with id of `wrapper` inside the existing element!  ie using **inner**HTML) 

... dont know exactly what your 'close' function does, to hide the element, but if it adds something like 'display:none' to the element, this code will replace the content, but the element will simply remain hidden. Will need to undo that. 


Note also that tracker is for reporting issues/suggestions on the core Leaflet library. FOr general programming questions, suggest something like https://stackoverflow.com/questions/tagged/leaflet instead.

**Comment by Noud63** [comment]
Yes, that was a little odd the double div, changed that. Also added the eventListener. It opens a popup clicking a marker, I'm able to close the popup and open another one clicking a different marker then I'm stuck. The popup wrapper remains open and only changes it's content when clicked on a marker?? Not able to close the popup??

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
