### ISSUE TITLE
Wrong order of coords tuple in onEachFeature callback of FeatureLayer

### ISSUE THREAD

**Issue by JulianKowalczuk** [Leaflet/Leaflet#6675]
As in topic, nothing more to add.
Found this issue while trying to use map.getBounds().contains(layer.feature.geometry.coordinates), where layer is first arg of onEachFeature callback.

**Comment by IvanSanchez** [comment]
Axis order of `L.LatLng` and GeoJSON coordinates is as expected.

https://macwright.org/lonlat/

**Comment by IvanSanchez** [comment]
BTW this was a crappy bug report, so I'm gonna drop the links to ["How To Ask Questions The Smart Way"](http://www.catb.org/esr/faqs/smart-questions.html) and ["How to Report Bugs Effectively"](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) over here.

**Comment by JulianKowalczuk** [comment]
That's right, it's crappy. Like my code now.

So You are trying to say, that instead of this:
```js
this.features = [];

    const mapBounds = this.props.leafletMap.getBounds();

    this.layer.eachFeature(({ feature }: { feature: DataLayerFeature }) => {
      const isFeatureInMapBounds = mapBounds.contains(feature.geometry.coordinates);

      if (isFeatureInMapBounds) {
        this.features.push(feature);
      }
    });
```
I should go with:
```js
this.features = [];

    const mapBounds = this.props.leafletMap.getBounds();

    this.layer.eachFeature(({ feature }: { feature: DataLayerFeature }) => {
      const [lng, lat] = feature.geometry.coordinates;

      const isFeatureInMapBounds = mapBounds.contains({ lat, lng });

      if (isFeatureInMapBounds) {
        this.features.push(feature);
      }
    });
```

**Comment by IvanSanchez** [comment]
Yeah, that should work. See also the [utility methods in `L.GeoJSON`](https://leafletjs.com/reference-1.5.0.html#geojson-function).

Your algorithm is also naïve, in the sense that it will skip features that cross over the map's bounding box without having any vertex inside (think a vertex just outside to the west and a vertex just outside to the east). See https://turfjs.org/docs/#intersect and https://leafletjs.com/reference-1.5.0.html#lineutil-clipsegment .
