### ISSUE TITLE
SVGOverlay does not respect className option

### ISSUE THREAD

**Issue by escornwell** [Leaflet/Leaflet#6677]
**Steps to reproduce**
Modify the SVGOverlay example in the docs to specify a class:
`L.svgOverlay(svgElement, svgElementBounds, {className: 'myClass'}).addTo(map);`

**Expected behavior**
SVG element will include the class `myClass`

**Current behavior**
SVG element class attribute is only `class="leaflet-image-layer leaflet-zoom-animated"`

**Environment**
- Leaflet version: 1.5.1
- Browser (with version): Safari 12.1.1, Chrome 74.0.3729.157
- OS/Platform (with version): macOS 10.13.6

**Minimal example reproducing the issue**
I'm new to Plunker, but perhaps this link works? https://embed.plnkr.co/XhNXdVoUypvgXHieGi56/

**Comment by IvanSanchez** [comment]
Nice catch, this seems like an overlook from when VideoOverlay was added.
