### ISSUE TITLE
Leaflet Map not loading when used with other providers

### ISSUE THREAD

**Issue by linuxoid** [Leaflet/Leaflet#6678]
I need multiple maps on my page: 2Gis and [LocationIQ](https://locationiq.com/docs-html/index.html#desktop-maps-with-leaflet). Both the 2Gis and LocationIQ (Unwired) are based on the Leaflet library. The 2Gis is working fine. But the Leaflet works only without the 2Gis. Together with 2Gis it throws an error: "TypeError: Leaflet.tileLayer.Unwired is not a function" at this line:

`var myLeafletStreets = Leaflet.tileLayer.Unwired({ // <- ERROR HERE`

Looks like there's a conflict between the 2 but I can't pin point where.

Here's a fiddle: https://jsfiddle.net/tL31gnxz/

If you remove the 2Gis bit:

```
DG.then(function() {
    InitTwoGisMap();
});

```
the Leaflet map loads fine.

I'm using

`var Leaflet = L.noConflict();`

but it doesn't seem to help.

**Comment by IvanSanchez** [comment]
Don't open a bug report when you've already asked at https://stackoverflow.com/questions/56302314/javascript-leaflet-map-not-loading
