### ISSUE TITLE
BindPopUp polygons not working after being rendered in canvas

### ISSUE THREAD

**Issue by troy0401** [Leaflet/Leaflet#6680]
After i loaded the coordinates through ajax, i rendered a circle marker using a plugin to increase performance in rendering of circle markers in canvas. I used {preferCanvas: true} upon loading the map. I noticed an increase in performance in circle markers if i zoom in and zoom out. However, when i loaded polygons together with circle markers both rendered in canvas, the bindpopup function for polygons is not responding after i click the area covered by the polygons. By the way, i used @oliverheilig's leaflet marker booster

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?

**Comment by oliverheilig** [comment]
I can reproduce it. It's a problem of the plugin (which highjacks the canvas prototypes) and not leaflet itself.

**Comment by oliverheilig** [comment]
Ok, 

i have fixed it in https://github.com/oliverheilig/leaflet-marker-booster/blob/master/leaflet-marker-booster.js#L85-L87

Keep in mind that this plugin viciously overrides the internal leaflet methods. You have to use it at your own risk and cannot expect support from the leaflet team.

`var circle = L.circle([51.508, -0.11], {
    color: 'red',
    fillColor: '#f03',
    fillOpacity: 0.5,
    radius: 50000
}).addTo(map);
circle.bindPopup("I am a circle!");`

**Comment by IvanSanchez** [comment]
This tracker is for core Leaflet bugs only. Report plugin bugs to the appropriate repo.

**Comment by Luzexiao** [comment]
I have the same problem.

**Comment by oliverheilig** [comment]
This issue is closed. It is not a leaflet bug. If you are using 

https://github.com/oliverheilig/leaflet-marker-booster

make sure to get the latest version. If the problem persists pleaser create an issue at the marker-booster project.

**Comment by troy0401** [comment]
I removed leaflet-marker-booster plugin to boost circle markers rendering in canvas. I now used L.canvas to render circle markers using leaflet default canvas layer. Even though circle markers that are rendered within L.polygons are not clickable. Markers outside of the polygons are those that is still clickable. It's like the markers underneath polygons are not clickable.

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour? And remember: no plugins.

**Comment by troy0401** [comment]
https://plnkr.co/edit/QafPWUsVT1WGxlqiqoXi?p=preview
