### ISSUE TITLE
请问一下 有离线下载的接口吗? 支持在小程序里使用吗？

### ISSUE THREAD

**Issue by yangyang158** [Leaflet/Leaflet#6684]
--------------^ Click "Preview" tab for a nicer view!

We use GitHub as an issue tracker and **do not provide support here**.
For usage and support questions, please check out resources below:

1. Read Leaflet documentation: https://leafletjs.com
2. For support questions like "How can I do X with Leaflet?" please search or ask questions on StackOverflow or StackExchange using Leaflet tag:
  - https://stackoverflow.com/questions/tagged/leaflet
  - https://gis.stackexchange.com/questions/tagged/leaflet

Thanks!

**Comment by ultimate-tester** [comment]
Am I right in understanding you want to integrate leafletjs into a native application? There's no libraries to render leafletjs to, for example, a C# application. What language are you using to program your application? If you're using C#, have a look at http://www.osmsharp.com/
