### ISSUE TITLE
maxNativeZoom broken

### ISSUE THREAD

**Issue by johnd0e** [Leaflet/Leaflet#6688]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- create map with `maxZoom` > 18
- add tile layer with `maxNativeZoom` = 18
- set zoom 18

**Expected behavior**

Layer should stay on map.

**Current behavior**

Layer dissapears (leaflet-tile-container empty)

**Environment**
- Leaflet version: `1.5.1`
- Browser (with version): `Google Chrome Version 74.0.3729.169 (Official Build) (32-bit)`
- OS/Platform (with version): `Windows 10 (32-bit)`

**Minimal example reproducing the issue**

https://jsbin.com/rafikinike/edit?html,output

This sample is equivalent to official https://leafletjs.com/examples/quick-start/example.html, except `maxNativeZoom` is used for layer instead of `maxZoom`.

**Comment by IvanSanchez** [comment]
That example is not setting the `maxZoom` of the `L.TileLayer` and, consequently, the `L.TileLayer` is inheriting the **default** of 18.

This is behaviour as expected.

**Comment by johnd0e** [comment]
Ok, it's not a bug, you are right.
But I still believe that current behavior can be enhanced: 

`maxZoom` is useful to define available zoom levels.
But when our map is explicitly set to higher zoom level, than is it really useful for **any** layer to just disappear?

Well, I can imagine one use case: when we have several layers with similar data but for different zoom levels.
(But I really doubt that it is typical use)
