### ISSUE TITLE
Leaflet geometry library with spherical methods

### ISSUE THREAD

**Issue by britisharmy** [Leaflet/Leaflet#6689]
I have looked at several libraries with leaflet and i still cant locate one with this function https://developers.google.com/maps/documentation/javascript/reference/geometry#spherical.computeHeading

that can be found when using google maps.  Anyone point to a library that has such a function.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by IvanSanchez** [comment]
https://geographiclib.sourceforge.io/
