### ISSUE TITLE
drawControl setDrawingOptions works only partially

### ISSUE THREAD

**Issue by TangaMenison** [Leaflet/Leaflet#6695]
It looks like setDrawingOptions doesn't allow to change many of the attributes, f.e. it doesn't allow to create / hide a button. I've modified a very simple example:

https://jsfiddle.net/hej31atu/

```
let options = {
  draw: {
    circle: false,
  }
};

map.drawControl.setDrawingOptions({
    circle: true    // <-- this does nothing
});
```

In the fiddle, when zooming the color of the polygon is changed to red, but circle option does not appear. The similar issue I found is that the marker icon cannot be changed dynamically with setDrawingOptions method.

**Comment by ghybs** [comment]
Hi,

Thank you for your interest in Leaflet!

Should not this issue be reported in [Leaflet.draw](https://github.com/Leaflet/Leaflet.draw) plugin repository instead?

**Comment by Gil-Epshtain** [comment]
Related issue in Leaflet.Draw:
https://github.com/Leaflet/Leaflet.draw/issues/369
