### ISSUE TITLE
Missing stopImmediatePropagation on L.DomEvent

### ISSUE THREAD

**Issue by SuperPat45** [Leaflet/Leaflet#6698]
- [X] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [X] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [X] I've searched through the issues to make sure it's not yet reported

L.DomEvent class does not have any stopImmediatePropagation method.
JQuery and the standard event system have this feature 

**Environment**
- Leaflet version: latest
- Browser (with version): Firefox 67
- OS/Platform (with version): Windows 10

**Comment by IvanSanchez** [comment]
> and the standard event system have this feature

Then use the [native implementation](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopImmediatePropagation). It works all the way back to MSIE9, so I don't see a reason why Leaflet should provide a polyfill for that.
