### ISSUE TITLE
The mouseover event for D3.js does not work in Leaflet

### ISSUE THREAD

**Issue by liruifengv** [Leaflet/Leaflet#6701]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- I used a Leaflet to draw a GeoJSON map.
- Create a node in svg using D3
- Bind the mouseover event to the node, but it does not take effect

**Expected behavior**
Expect the mouseover event of D3.js to work properly in Leaflet

**Current behavior**
The mouseover event for D3.js does not work in Leaflet

**Environment**
- Leaflet version:1.5.1
- D3.js v5
- Browser (with version):Chrome 75.0.3770.80
- OS/Platform (with version):Windows 10

my example code is https://github.com/liruifengv/leaflet/blob/master/test.html

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.
