### ISSUE TITLE
flyTo not working correctly when zoom is above 3

### ISSUE THREAD

**Issue by AmazingBite** [Leaflet/Leaflet#6702]
Hi,

My problem is simple, when the zoom of the map is above 3, the flyTo function doesn't work correctly.
It first start zooming to the location but quickly stop and go somewhere on the middle of the map.
The flyTo function perfectly works when my zoom is equal or under 3.

Where's my code :
The initialization :
```
var bounds = new L.LatLngBounds(new L.LatLng(86.0, -190.0), new L.LatLng(-86.0, 190.0));
var osm = L.tileLayer(osmUrl);
	map = new L.Map('map', {
		attributionControl: false,
		center: bounds.getCenter(),
		minZoom: 1,
		maxZoom: 16,
		zoom: 2,
		layers: [osm],
		maxBounds: bounds,
		maxBoundsViscosity: 1
	});
map.on('click', hide_display);
```

And this is the call to flyTo :
```
latitude = data.lat;
longitude = data.lon;
map.flyTo([latitude, longitude]);
```

Any idea where the problem could come from?

**Comment by IvanSanchez** [comment]
[Works for me](https://plnkr.co/edit/lJNMQHorVfF0uQJmUGIl?p=preview).

All I notice is that the flyTo is getting stopped when hitting the map's bounds, and it's stopping suddently because of the viscosity, but that is expected behaviour.
