### ISSUE TITLE
noConflict not working

### ISSUE THREAD

**Issue by HydrogenPan19** [Leaflet/Leaflet#6703]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**

```html
<script src='libs/l.js'></script>
<!-- L points to some other library -->
<script src='leaflet.js'></script>
<!-- you include Leaflet, it replaces the L variable to Leaflet namespace -->
<script>
var Leaflet = L.noConflict();
// now L points to that other library again, and you can use Leaflet.Map etc.
</script>
```

**Expected behavior**

L points to other library again

**Current behavior**

L points to Leaflet still

**Environment**
- Leaflet version:  1.5.1

**Minimal example reproducing the issue**

https://embed.plnkr.co/wDnXeS3p7ufWdUvjenv6/

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**reason**

`factory((global.L = {})`

**Comment by ghybs** [comment]
Hi,

Good catch!

Hum unfortunately the header code comes from Rollup build, I am not sure how we could easily modify it to account for Leaflet legacy noConflict management... :sweat:
Please feel free to share your ideas for solution!

**Comment by alexboia** [comment]
Had the same issue and came up with a pretty dumb fix that doesn't require me fiddling with leaflet's source code. I'm including this snippet before including leaflet:

```js
(function() {
    "use strict";
    
    var leaflet3rdParty = window.L;
    window.myLeafletNoConflict = function() {
        var currentL = window.L;
        window.L = leaflet3rdParty;
        return currentL;
    }
})();
```

Then, right after including leaflet, in lieu of `L.noConflict()`, just call `window.myLeafletNoConflict()`. Sample output:

```
L.version
"1.5.1+HEAD.2e3e0ff"
LeafletJS.version
"1.6.0+HEAD.0c81bdf"
```

Everything's cool and the gang, works nicely. 
One can include it as an inline snippet or separate file.

**Comment by Malvoz** [comment]
Fixed in https://github.com/Leaflet/Leaflet/pull/7855.
