### ISSUE TITLE
Changing radius of the Earth

### ISSUE THREAD

**Issue by jolyonralph** [Leaflet/Leaflet#6704]
When using non-Earth maps (eg https://www.openplanetary.org/opm-basemaps/opm-moon-basemap-v0-1 ) Leaflet assumes a default projection for the Earth. 

This isn't necessarily a bad thing because at the scale of accuracy of these planetary projections the default Leaflet projection is "good enough"

Except that when adding something such as the Scale control, it shows the scale based on the Earth rather than the Moon. 

Google maps provides an option to specify the Radius when adding an ImageMapType (see https://developers.google.com/maps/documentation/javascript/examples/maptype-image ) and it would be really useful to be able to provide the same functionality within Leaflet without having to create custom coordinate projection systems. 

Alternatively, it may be simpler just to be able to override the planetary radius in the Scale control, which would be simple and effective.

**Comment by IvanSanchez** [comment]
> ... and it would be really useful to be able to provide the same functionality within Leaflet without having to create custom coordinate projection systems.

Nope.

Creating such a custom coordinate system is literally a one-liner:

```
L.CRS.MoonSphericalMercator = L.extend({}, L.CRS.EPSG3857, {R: 1737000});
```

Which is exactly the same amount of code a user would need in order to user such a proposed "change the radius" feature.

[See a working example](https://plnkr.co/edit/OFzzbSbSXhEO3p5t2RKA?p=preview).

**Comment by jolyonralph** [comment]
Thank you - I couldn't find example code to explain this anywhere.
