### ISSUE TITLE
panTo not centering the map when dimensions have changed

### ISSUE THREAD

**Issue by JacopoSciampi** [Leaflet/Leaflet#6707]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x ] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
I've initializated a map in a div having width and height of 500px. Then, I've implemented a click handler to call the panTo function to center the map and works fine. If I modify the div dimensions, the same funcion is not centering the map because, I think, it "doent't know" that the div dimensions have changed.

**Expected behavior**
The panTo should always center the map by its container dimensions.

**Current behavior**
The panTo is not centering the map when dimensions have changed.

**Environment**
- Leaflet version: 1.3.1
- Browser (with version): Chrome  75.0.3770.100 64 bit
- OS/Platform (with version): Windows 10

- [ ] this example is as simple as possible
- [x ] this example does not rely on any third party code

**Comment by IvanSanchez** [comment]
Behaviour as expected. See [`invalidateSize()`](https://leafletjs.com/reference-1.5.0.html#map-invalidatesize).
