### ISSUE TITLE
Get drawn map bounds, similar to what DOM getClientBoundingRect does

### ISSUE THREAD

**Issue by wonderwhy-er** [Leaflet/Leaflet#6711]
**Is your feature request related to a problem? Please describe.**
We use leaflet to draw various custom maps, and we give it a rectangle to be drawn in.
Map has its aspect ratio.
Together that means that when rectangle and map do not have same aspect ratio empty space will be present, of when not enough space is given map will be cut off.
Like here not enough space was given to the left map + too much vertical space
https://gyazo.com/0000a5afc3f2d9ef3b2cf1ba6a6dfbb2

**Describe the solution you'd like**
I would like a solution that would return bounding rect of drawn map, 
similar to how DOM getClientBoundingRect return drawn object size.
There already exists getPixelBounds() but it returns something else.
Alternatively making _pxBounds object on Layer accessible trough public API getter would allow us calculating it ourselves. See more info below.

**Describe alternatives you've considered**
Using getClientBoundingRect on resulting svg element would do for us but when canvas is used to render a map it would not work.

Other options we are considering is trying to understand aspect ratio of the map from csr but it is not ideal for many reasons too. 

What I found is that instance has eachLayer method and layers have private _pxBounds object.
If I reduce layers pxBounds to a containing bounds it does give me size I seem to want to know.
For example for the map to the right gives when I reduce layer px bounds:
max: Point {x: 277.5, y: 391.25}
min: Point {x: 2.5, y: 207.5}
And such if I use getPixelBounds on map instance:
max: Point {x: 278, y: 401}
min: Point {x: -3, y: -197}

You can see that second bounds is quite larger and seem to match whole rect size more or less, while first looks like size of them map. But we can't really rely on private property.

**Comment by IvanSanchez** [comment]
`map.layerPointToContainerPoint(layer.getBounds().getNorthWest())` and `map.layerPointToContainerPoint(layer.getBounds().getSouthEast())`.

**Comment by wonderwhy-er** [comment]
Thanks @IvanSanchez 
Code you provided did not work out but pointed in right direction. Other conversion method was needed. Instead of layerPointToContainerPoint it was latLngToContainerPoint

In case someone stumbles on this issue here is code that worked for me

```
let layers = [];
map.eachLayer(l => layers.push(l));
layers.filter(l => !!l.getBounds).map(l => {
    let latLong = l.getBounds();
    let topLeft = map.latLngToContainerPoint(latLong.getNorthWest());
    let bottomRight = map.latLngToContainerPoint(latLong.getSouthEast());
    return {left: topLeft.x, top: topLeft.y, right: bottomRight.x, bottom: bottomRight.y};
}).reduce((rect, layer) => {

    rect.left = Math.min(rect.left, layer.left);
    rect.top = Math.min(rect.top, layer.top);
    rect.right = Math.max(rect.right, layer.right);
    rect.bottom = Math.max(rect.bottom, layer.bottom);

    return rect;
});
```
