### ISSUE TITLE
Crashed on chrome v49.0.2623.87

### ISSUE THREAD

**Issue by zedweein** [Leaflet/Leaflet#6714]
Im using chrome v49.0.2623.87 , when im loading the whole page include leaflet, the chrome crashed! how can i resolved the issue, thanks!

**Comment by zedweein** [comment]
By the way , the version i used is v1.3.1 ,but i tried the whole version list ,such as v0.77 , v1.00, v.1.2, v1.51 and so on, not solved the issue .

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?
