### ISSUE TITLE
Zoomlevel 19just shows grey tiles

### ISSUE THREAD

**Issue by FrontierDK** [Leaflet/Leaflet#6724]
I have noticed that when allowing past zoomlevel 18, Leaflet just shows a grey area when trying to zoom past level 18. I have the many tiles on my own server, and when viewing the log files on my server, it shows that Leaflet never requests any tiles past 18...despite zoomLevel being set to 19.

**Comment by IvanSanchez** [comment]
Behaviour as expected, default `maxZoom` of a `L.Tilelayer` is 18.
