### ISSUE TITLE
create my imagine map

### ISSUE THREAD

**Issue by meteerogl** [Leaflet/Leaflet#6725]
Hey I want to create my world map in leaflet. There is no real borders or countries. I want to create my counties. Actually my imagine world. Can ı do. Can ı change borders or something in leaflet. Actually I am asking for is it sensible using leaflet for this work. Thanks for answer :)

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by IvanSanchez** [comment]
Do have a look at https://www.opengeofiction.net/#map=6/40.007/-2.488 and https://leafletjs.com/examples/crs-simple/crs-simple.html , though.
