### ISSUE TITLE
Leaflet in constrained module framework

### ISSUE THREAD

**Issue by JAzzaz** [Leaflet/Leaflet#6726]
Hi all,

I am currently trying to use Leaflet inside a constrained framework. this framework uses RequireJS with its own configuration.

I was able to load the module by encapsulating the leaflet source file :
`define("./HelloMapWidget2/js/lib/leafmap",
		function(){

//leaflet source

return L;
}
);
`

But L is still undefined.

I'm new to the use of modules but I wonder if there is a way to properly exposed leaflet and use it in such a constrained framework ?

Thanks in advance.

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.
