### ISSUE TITLE
Error when extending L.geoJson

### ISSUE THREAD

**Issue by quentinlamamy** [Leaflet/Leaflet#6729]
Hi,

I am actually extending leaflet for a project, it work well but when trying to extend the geoJson object it seems that it's not extendable.

Is that an issue or it's normal that i can't extend this object ?

**My code**

```js
L.wbLine = L.geoJson.extend({
     toto:function(){
          this.options.color = yellow;
     }
});
```

**Output**

`TypeError: L.geoJson.extend is not a function`

**Comment by IvanSanchez** [comment]
From https://leafletjs.com/examples/extending/extending-1-classes.html :


> ### Factories
> 
> Most Leaflet classes have a corresponding factory function. A factory function has the same name as the class, but in lowerCamelCase instead of UpperCamelCase:
> 
> ```
> function myBoxClass(name, options) {
>     return new MyBoxClass(name, options);
> }
> ```
