### ISSUE TITLE
Close icon for popups?

### ISSUE THREAD

**Issue by i-schuetz** [Leaflet/Leaflet#6735]
Is it possible to replace the default "x" to close the popups with a custom icon? I searched in the documentation and it doesn't seem to be the case. If not, would this be considered as feature request?

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by IvanSanchez** [comment]
See also https://gis.stackexchange.com/questions/285588/why-does-the-classname-option-of-a-leaflet-popup-change-only-the-outside-of-the
