### ISSUE TITLE
event.originalEvent is of type MouseEvent when touching

### ISSUE THREAD

**Issue by dahannes** [Leaflet/Leaflet#6739]
- [x ] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x ] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [ x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- setup a basic map like [jsfiddle](https://jsfiddle.net/7ufmzdo8/4/)
- open with **touch device** and tap on the (empty) map
- inspect browser console logs

**Expected behavior**
The logged `event.originalEvent` should be of type `TouchEvent` as documented [here](https://leafletjs.com/reference-1.5.0.html#mouseevent-originalevent)

**Current behavior**
The logged `event.originalEvent` is of type `MouseEvent`

**Environment**
- Leaflet version: 1.5.1
- Browser (with version): iOS Safari 12.3.1
- OS/Platform (with version): iOS

**Additional context**

**Minimal example reproducing the issue**
[jsfiddle](https://jsfiddle.net/7ufmzdo8/4/)

Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.

- [x ] this example is as simple as possible
- [x ] this example does not rely on any third party code

**Comment by IvanSanchez** [comment]
Behaviour as expected. In that jsfiddle you're listening for the `click` event, which is always a `MouseEvent`, as per https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event . Compare with https://developer.mozilla.org/en-US/docs/Web/API/Element/touchstart_event

I suggest watching the "getting touchy" presentation to understand why touch-only stuff fire mouse events: https://invidio.us/watch?v=bBdQkhm1DvI and https://patrickhlauke.github.io/getting-touchy-presentation/#

**Comment by dahannes** [comment]
@IvanSanchez The leaflet docs says that [click-event](https://leafletjs.com/reference-1.5.0.html#map-click) is a Leaflet `MouseEvent` which should point to `The original DOM MouseEvent or DOM TouchEvent that triggered this Leaflet event.` and that is obviously not the case. After all I cannot listen to a 'touchstart' event on the leaflet map, but I need the actual `DOM Touchevent` to check for the `Touch.touchType`

**Comment by IvanSanchez** [comment]
> The leaflet docs says that click-event is a Leaflet MouseEvent [...] and that is obviously not the case.

Yes it is. The DOM `click` event is what triggers the Leaflet `click` event.

Whenever you tap on a touchscreen, there are several DOM events going on there (in different order depending on the browser):

- `mousedown` → triggers a Leaflet `mousedown` event
- `touchstart` → doesn't trigger any map event
- `pointerdown` → doesn't trigger any map event
- `click` → triggers a Leaflet `click` event
- `mouseup` → triggers a Leaflet `mouseup` event
- `touchend` → doesn't trigger any map event
- `pointerup` → doesn't trigger any map event

So A, B, C, D, E happen at once, and C triggers F, and F has a reference to C. And you say "But I want F to have a reference to B instead!", to which the answer is "no, that's no how things work".

Seriously, "getting touchy". Watch it.

> I need the actual DOM `TouchEvent` to check for the `Touch.touchType`

Then `L.DomEvent.on(map.getContainer(), 'touchstart touchmove touchend', handler)`.

**Comment by dahannes** [comment]
Thank you very much for the feedback @IvanSanchez. `L.DomEvent.on(map.getContainer(), 'touchstart touchmove touchend', handler).` is what I was looking for.
