### ISSUE TITLE
Stop immediatePropagation not working

### ISSUE THREAD

**Issue by ksrb** [Leaflet/Leaflet#6741]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…) - **well I'm pretty sure but not 100%**
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
https://codesandbox.io/s/trusting-dust-ji174

Attach 2 click handlers to the map and attempt to `stopImmediatePropagation` on the first handler and see if the 2nd handler gets prevented.

**Expected behavior**
Second handler should not to be called.

**Current behavior**
Second handler is called.

**Environment**
- Leaflet version: 1.5.1
- Browser (with version): Chrome 75
- OS/Platform (with version): Windows 10

**Related issues**
https://github.com/Leaflet/Leaflet.VectorGrid/issues/93
https://github.com/Leaflet/Leaflet/issues/6698

**Additional Context**
So this is admittedly somewhere between a question and possibly a issue, but after trying several combinations to `stopImmediatePropagation` and creating a sandbox I started thinking it might be more of a issue.

The reason why we need this is because we're using some 3rd party code to render Markers with images in canvas, see https://github.com/lycheelin/react-leaflet-canvas-markers/blob/22adc80053c46fc8a52a34138b530ec2f71b068f/src/leaflet.canvas-markers.js. 

The code is definitely questionable and we'll probably rewrite it at some point. However, the basic concepts seems to be correct, in essence the code uses the cursor position to figure out what marker was clicked on in the canvas layer. This requires the addition of a map click listener see https://github.com/lycheelin/react-leaflet-canvas-markers/blob/22adc80053c46fc8a52a34138b530ec2f71b068f/src/leaflet.canvas-markers.js#L107.

However our own code originally had click listeners on each marker, 'moving' these listeners to the map as the canvas-marker code requires, results in some conflicting behavior. We are trying to mitigate this behavior by preventing the event from propagating to other listeners.

All this being said, the basic example in the [sandbox](https://codesandbox.io/s/trusting-dust-ji174) should still work?

**Comment by wang1212** [comment]
I have also encountered such a problem. Finally, I took a compromise solution to solve it.

```
map.scrollWheelZoom.disable();

# do something...

map.scrollWheelZoom.enable();
```

see : https://leafletjs.com/reference-1.5.0.html#handler

I hope to be useful to you.

**Comment by johnd0e** [comment]
@wang1212 that is probably unrelated to original issue

**Comment by johnd0e** [comment]
@ksrb there is no bug in leaflet.
Mentioned 3rd-party code itself introduces this issue.

**Comment by user073** [comment]
@johnd0e

> there is no bug in leaflet.

There is a bug in leaflet.

> Mentioned 3rd-party code itself introduces this issue.

The sandbox @ksrb shared does not contain 3rd-party code.

***

Please see this sandbox:

[![Edit quirky-frost-946z7](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quirky-frost-946z7?fontsize=14&hidenavigation=1&theme=dark)

# stopImmediatePropagation of leaflet event

Two leaflet event listeners are added to the left map in this sandbox.

```js
map1.on("click", (e) => {
  e.originalEvent.stopImmediatePropagation();
  console.log("Leaflet event 1");
});
map1.on("click", (e) => {
  console.log("Leaflet event 2");
});
```

`stopImmediatePropagation` is called on the originalEvent in the first listener.

## Expected behavior

Only "Leaflet event 1" is printed to the console when the left map is clicked.

## Actual behavior

"Leaflet event 1" and "Leaflet event 2" are printed to the console when the left map is clicked.


# stopImmediatePropagation of DOM event

Two DOM event listeners are added to the right map in this sandbox.

```js
mapElm2.addEventListener("click", (e) => {
  e.stopImmediatePropagation();
  console.log("DOM event 1");
});
mapElm2.addEventListener("click", (e) => {
  console.log("DOM event 2");
});
```

`stopImmediatePropagation` is called on the event in the first listener.

## Expected behavior

Only "DOM event 1" is printed to the console when the right map is clicked.

## Actual behavior

Only "DOM event 1" is printed to the console when the right map is clicked.

***

Can this issue be reopened?

**Comment by johnd0e** [comment]
> There is a bug in leaflet.

All is possible. But your sandbox does not contain related code, so I do not see how to reproduce the issue.
Also: please make sample as shorter as you can.

**Comment by user073** [comment]
The sandbox link has been fixed. Please let me know if the sample should be shorter.

**Comment by johnd0e** [comment]
DOM events are NOT equal to Leaflet events.
So no surprise that their processing is different.

We have these 2 methods only for Leaflet events.
https://leafletjs.com/reference-1.7.1.html#domevent-stoppropagation
https://leafletjs.com/reference-1.7.1.html#domevent-preventdefault

`stopImmediatePropagation` is not implemented.
Sure you can use it directly (as in your sample), but this case is not supported.

**Comment by user073** [comment]
OK. It would be useful in some cases to be able to stop immediate propagation of a Leaflet event. Can a feature request be made for an `L.DomEvent.stopImmediatePropagation` method for Leaflet events? If so, where should this feature request be made?

**Comment by johnd0e** [comment]
Sure you can made request, describing possible use cases in details.

Related: #6787
