### ISSUE TITLE
Shouldn't this._icon existence be tested in Marker._setpos ?

### ISSUE THREAD

**Issue by BenTalagan** [Leaflet/Leaflet#6743]
Hi, this feature request (which is some kind of a bug fix), is linked to a race condition I got today in a complex situation involving updating a marker coordinates, while it was spiderfied and animated by the MarkerCluster plugin. It's a bit complicated to give a test case, but I don't think it's useful since the discussion is actually pretty simple.

Before [this line](https://github.com/Leaflet/Leaflet/blob/e793eba9a09895a11711e4d0804b2619de91b21b/src/layer/marker/Marker.js#L290), `this._icon` is not tested (whereas just after `this._shadow` is tested). Shouldn't it be legit to call _setpos on a Marker even if it has no _icon ? Thus, shouldn't a `if(this._icon)` be added?

In my specific case this patch solves the issue (which would be very hard to fix upstream).

Thanks for reading!

**Comment by cherniavskii** [comment]
Closed by #6743
