### ISSUE TITLE
wrong coordinates get,using geoJson

### ISSUE THREAD

**Issue by zhongbodong** [Leaflet/Leaflet#6744]
I am using geoJson to create a maker like this:
` var geojsonFeature = {
            "type": "Feature",
            "properties": {
                "name": "lgd",
                "amenity": "education",
                "popupContent": "I'm here!"
            },
            "geometry": {
                "type": "Point",
                "coordinates": [30.679849, 114.44767]
            }
        };
        L.geoJSON(geojsonFeature).addTo(mymap);`
but it coordinates  has became like this:
![image](https://user-images.githubusercontent.com/28446826/62355561-d0143e00-b541-11e9-97b8-07f4348f263d.png)

i dont know why ,hope somebody can get it 
Thanks!

**Comment by IvanSanchez** [comment]
I'm gonna bet your map is centered on [30.679849, 114.44767]. Looks like another case of https://macwright.org/lonlat/
