### ISSUE TITLE
L.geoJSON() requires explicit typing

### ISSUE THREAD

**Issue by tuckergordon** [Leaflet/Leaflet#6746]
The following example from the Leaflet documentation

```
const geojsonFeature = {
  type: 'Feature',
  properties: {
    name: 'Coors Field',
    amenity: 'Baseball Stadium',
    popupContent: 'This is where the Rockies play!'
  },
    geometry: {
    type: 'Point',
    coordinates: [-104.99404, 39.75621]
  }
};

L.geoJSON(geojsonFeature).addTo(map);
```
throws a type error:
```
Argument of type '{ type: string; properties: { name: string; amenity: string; popupContent: string; }; geometry: { type: string; coordinates: number[]; }; }' is not assignable to parameter of type 'GeoJsonObject'.
  Types of property 'type' are incompatible.
    Type 'string' is not assignable to type '"Feature" | "Point" | "MultiPoint" | "LineString" | "MultiLineString" | "Polygon" | "MultiPolygon" | "GeometryCollection" | "FeatureCollection"'.ts(2345)
```
unless you explicitly type `geojsonFeature: Feature`:
```
import { Feature } from 'geojson';

const geojsonFeature: Feature = {
  type: 'Feature',
  properties: {
    name: 'Coors Field',
    amenity: 'Baseball Stadium',
    popupContent: 'This is where the Rockies play!'
  },
    geometry: {
    type: 'Point',
    coordinates: [-104.99404, 39.75621]
  }
};

L.geoJSON(geojsonFeature).addTo(map);
```
This seems like a bug to me but maybe I'm missing the thinking behind the architecture?

**Comment by IvanSanchez** [comment]
That's typescript.

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.
