### ISSUE TITLE
Invalid integrity for leaflet.css & leaflet.js 1.5.1

### ISSUE THREAD

**Issue by asalopez** [Leaflet/Leaflet#6747]
Hello!

I'm using version 1.5.1 of the plugin (CDNs) but from today console prints me the next error:

![image](https://user-images.githubusercontent.com/33123192/62443538-74250180-b75b-11e9-846c-041a7fe5cba0.png)

**Comment by IvanSanchez** [comment]
[Works for me](https://plnkr.co/edit/tByGKFm4zVoEcW6CKqms?p=preview), so closing this bug. Double-check https://leafletjs.com/download.html . 

What CDN are you using? If the integrity hashes mismatch, you should `diff` those files against the downloadable ones to look for changes.
