### ISSUE TITLE
adding geojson layer results in a grey background which covers base map

### ISSUE THREAD

**Issue by virgilxw** [Leaflet/Leaflet#6750]
**Steps to reproduce**
-  Go to https://virgilxw.github.io/Singapore_Election_1955/
-  Click on the top right button on the map
- click on "data"
- click on "constituencies"

**Expected behavior**
Polygons should overlay base map

**Current behavior**
base map covered by grey-colored layer

<blockquote class="imgur-embed-pub" lang="en" data-id="a/PcJJ2GX"><a href="//imgur.com/a/PcJJ2GX"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>
<blockquote class="imgur-embed-pub" lang="en" data-id="a/dnpraZK"><a href="//imgur.com/a/dnpraZK"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Environment**
- Leaflet version:1.51.1
- Browser (with version):
- OS/Platform (with version):

**Additional context**
``

```
// Default base Map
map.addLayer(LayerOSM);

// Add geojson
var Layer1955Wards = new L.GeoJSON.AJAX("data/wards1955.geojson");

// Styled Layer Control
var baseMaps = [
	{
		groupName: "Base Maps",
		expanded: true,
		layers: {
			"OneMap": LayerOneMapSG_Default,
			"OSM": LayerOSM
		}
	}];

var overlays = [
	{
		groupName: "data",
		expaned: "true",
		layers: {
			"Constituencies": Layer1955Wards
		}
	},
	{
		groupName: "Map Overlays",
		expanded: "true",
		layers: {
			"1953 Topological": Layer1953Topo,
			"1953 Aerial Photographs": Layer1953Aerial
		}
			}];

var styledLayerControlOptions = {
	container_width: "300px",
	container_maxHeight: "350px",
	group_maxHeight: "80px",
	exclusive: false
};

var styledLayerControl = L.Control.styledLayerControl(baseMaps, overlays, styledLayerControlOptions);
map.addControl(styledLayerControl, overlays);
```
```

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
