### ISSUE TITLE
Print Leaflet map on PDF as-is

### ISSUE THREAD

**Issue by 1kastner** [Leaflet/Leaflet#6751]
**Is your feature request related to a problem? Please describe.**
I want to convert websites containing leaflet maps into PDFs for archiving purposes.
To be precise, I want to save Jupyter Notebooks with Folium maps (they use leaflet under the hood) as PDFs. Alternatively TIFF images would be (more or less) acceptable as well.

Somehow the PDFs I generate are often messed up, like when printed the maps show up at wrong places and wrong tiles are printed, some markers and lines do not appear where expected.

One way of how to re-create this is the following command (in case Chrome is installed):
```
& "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --headless --print-to-pdf="/my/path/to/output.pdf" --delay=15000 --disable-gpu --enable-logging --v=1 "https://python-visualization.github.io/folium/quickstart.html"
```
Somehow still some tiles are not fully loaded in headless mode.

**Describe the solution you'd like**
This I want to do on great scale, and because of that I want to use some automated solution.
I could e.g. start headless browsers and print out the pages. I do not care which browser to use. I could do this either on Windos or Linux. But I can barely change the source code of the website. It should be a stable and reliable solution.

**Describe alternatives you've considered**
I thought about taking screenshots of the maps and save them as images. I did not find a good way of how to do this in batch processing.

**Additional context**
I tried to find help at:
-  https://bugs.chromium.org/p/chromium/issues/detail?id=986740#c3
-  https://superuser.com/questions/1463819/print-fully-loaded-website-as-pdf-with-chrome-in-headless-mode
-  https://github.com/Szpadel/chrome-headless-render-pdf/issues/54

Either there were no answers or they were not satisfying.

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.

**Comment by IvanSanchez** [comment]
That said: if you could *isolate* the problem, and provide a HTML+JS -only use case that fails to print to PDF, we could handle that as a bug. As your problem is worded, the scope is just too big, and the bug too imprecise, i.e. ...

> Somehow the PDFs I generate are often messed up, like when printed the maps show up at wrong places and wrong tiles are printed, some markers and lines do not appear where expected.

Is there a pattern to the mess-ups? Are there any `@media print` CSS queries messing stuff up? Are the tiles shifted in any particular way? Does the same map with the same data print alright when taken from the folium output and into its own HTML file without any extraneous stuff?

---

OTOH: I would like to encourage you to export the *data* instead of the visualization. Get that data into e.g. qgis or geoserver or whatever, and [automate that](https://www.qgistutorials.com/en/docs/automating_map_creation.html). Leaflet is a tool for web browsers, not an archiving tool... maybe you're trying to use the wrong tool here.

**Comment by 1kastner** [comment]
Thanks for the fast response. I will work on an example that fulfills your requirements.

About the archiving process, there are laws and regulations made by others. I need to archive Jupyter Notebooks as they have been created by other authors. The visualization must be the same what the authors saw at the moment of creation. Therefore, using other software like you suggested is out of scope as that would serve another purpose.

**Comment by 1kastner** [comment]
Well, I saw that there are indeed big differences, such as the iframe approach for folium etc.
I printed https://leafletjs.com as a PDF and saw that the issues are not as big as with my folium examples at https://github.com/python-visualization/folium/issues/1196 - for the changed visualization just see [leaflet_page.pdf](https://github.com/Leaflet/Leaflet/files/3485241/leaflet_page.pdf)
