### ISSUE TITLE
Strange editing behavior on drawn features

### ISSUE THREAD

**Issue by spatselcci** [Leaflet/Leaflet#6754]
I've noticed that when I draw a new polygon on a Leaflet map, the editing behavior is different than it is for polygon's I've added to the map in other ways. 

I'll try to describe the problem here:
<img width="214" alt="leaflet-issue" src="https://user-images.githubusercontent.com/47788886/62643664-754e5e00-b916-11e9-97d1-24a18ac564ee.PNG">

In the above polygon, I tried to move the top left point closer to the center of the polygon (the line _inside_ the polygon was not originally there). 

Normally, I would expect the point to simply move wherever I drag it. However, for polygons I've drawn, it seems two new additional points (so three total) are created below the first point I can drag. (Note: the more opaque points behave "normally").

I've searched extensively for anyone else running into this issue. Is this behavior intentional? Is there a setting I can add to negate it? Why does it happen for polygons I've drawn but not on other polygons?

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.

**Comment by IvanSanchez** [comment]
That seems to be about leaflet.draw, not about just leaflet.

**Comment by Gilson401** [comment]
> I've noticed that when I draw a new polygon on a Leaflet map, the editing behavior is different than it is for polygon's I've added to the map in other ways.
> 
> I'll try to describe the problem here: <img alt="leaflet-issue" width="214" src="https://user-images.githubusercontent.com/47788886/62643664-754e5e00-b916-11e9-97d1-24a18ac564ee.PNG">
> 
> In the above polygon, I tried to move the top left point closer to the center of the polygon (the line _inside_ the polygon was not originally there).
> 
> Normally, I would expect the point to simply move wherever I drag it. However, for polygons I've drawn, it seems two new additional points (so three total) are created below the first point I can drag. (Note: the more opaque points behave "normally").
> 
> I've searched extensively for anyone else running into this issue. Is this behavior intentional? Is there a setting I can add to negate it? Why does it happen for polygons I've drawn but not on other polygons?

Hi. I got the same error. Do you got a solution?
