### ISSUE TITLE
show/hide graticule or controls

### ISSUE THREAD

**Issue by xavirayo** [Leaflet/Leaflet#6762]
Hi!
I'm trying to create a function to show/hide the graticule of my leaflet map.
I want the user to be able to do it just using a checkbox, but can't find how to do it.
I load the graticule with the map and want to be unloaded when I decide it with the checkbox.
This is my simple function, but I can't find what I'm doing wrong.
I've tried it also with Jquery but no succes.

_Function myFunction() {
  var checkBox = document.getElementById("myCheck");
  if (checkBox.checked == true){
     L.map.removeControl(L.latlngGraticule) 
  } else {
      document.write("hola")
     L.map.removeControl(L.latlngGraticule)
        }
}_

Thanks you very much in advanced

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by IvanSanchez** [comment]
Also: https://leafletjs.com/examples/layers-control/
