### ISSUE TITLE
polyline dynamic coords

### ISSUE THREAD

**Issue by VCodepp** [Leaflet/Leaflet#6763]
Hi everyone

I have polyline and I made an edit mode. this mode drags the start and end points. In this process I want to change the coordinates of the polyline using turf.js. I could not find a management of it.

**Comment by perliedman** [comment]
Hi, you can change the coordinates of a `Polyline` with [`setLatLngs`](https://leafletjs.com/reference-1.0.3.html#polyline-setlatlngs).
