### ISSUE TITLE
tooltipAnchor has limited or no effect for some Tooltip directions

### ISSUE THREAD

**Issue by Istador** [Leaflet/Leaflet#6764]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
> The coordinates of the point from which tooltips will "open", relative to the icon anchor.
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- Define an Icon with the `tooltipAnchor` option with a non-zero value for x.
- Create a Marker using that Icon, that has a Tooltip bound with an `top`, `bottom` or `center` direction.

**Expected behavior**
The anchor of the Tooltip should move relative to the `iconAnchor` according to the values defined in the `tooltipAnchor`. It should have the same behavior as `popupAnchor` according to the documentation, e.g. if given the same values it should position itself at the same position as the Popup.

**Current behavior**
`tooltipAnchor.x` has no effect for the directions `top`, `bottom` and `center`.
`tooltipAnchor.y` has no effect for the `bottom` direction.

**Environment**
- Leaflet version: 1.5.1
- Browser (with version): Chrome 76.0.3809.100, Waterfox 56.2.12
- OS/Platform (with version): Windows 7 (6.1 Build 7601), Ubuntu 18.04

**Additional context**
Source code responsible for the issue:
https://github.com/Leaflet/Leaflet/blob/1e0d43b11d477e0c89de4dace33123aa871c76b8/src/layer/Tooltip.js#L144-L156

**Minimal example reproducing the issue**
https://jsfiddle.net/590jt8fx/
```js
const map = L.map('map').setView([0.0, 0.0], 12)

const icon = L.icon({
  iconUrl: 'https://leafletjs.com/docs/images/logo.png',
  iconSize: [120, 31.8], // (600 x 159)/5
  iconAnchor: [60, 15.9], // center
  popupAnchor: [50, -15.9], // top right
  tooltipAnchor: [50, -15.9], // top right
})

L.marker([0, 0], { icon } )
  .bindPopup("popup is working correctly")
  .bindTooltip("tooltipAnchor.x has no effect", { direction: 'top' })
  .addTo(map)
  
L.marker([-0.02, 0], { icon } )
  .bindTooltip("offset is needed", { direction: 'top', offset: [50, 0] })
  .addTo(map)
```

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by vangenechtenbert** [comment]
same here

**Comment by johnd0e** [comment]
@Istador 
@vangenechtenbert 

Is it fixable by #6116?

**Comment by Istador** [comment]
> @Istador
> @vangenechtenbert
> 
> Is it fixable by #6116?

No, it's even more broken than before.

---

For comparison, this is the current behavior of my minimal example back then when I created the issue. The most recent master branch version shows the same behavior.

**Hovering the first image:**
![Hovering the first image](https://user-images.githubusercontent.com/8825444/82498918-0f237800-9af1-11ea-877c-91fc1975079a.png)

**Hovering the second image:**
![Hovering the second image](https://user-images.githubusercontent.com/8825444/82498928-121e6880-9af1-11ea-99e8-a1a684035aa6.png)

---

And this is the behavior of the latest commit 20784d7fbd7ef934e5c205caa4c98b891404eea6 from pull request #6116 with my minimal example code.

**Hovering the first image:**
![Hovering the first image](https://user-images.githubusercontent.com/8825444/82499153-7ccfa400-9af1-11ea-88eb-3e7ee6130b95.png)

**Hovering the second image:**
![Hovering the second image](https://user-images.githubusercontent.com/8825444/82499168-8527df00-9af1-11ea-9519-3200258c6dd9.png)

**Comment by johnd0e** [comment]
Can you provide own PR to fix this issue?

**Comment by johnd0e** [comment]
@Istador 
Isn't this issue already fixed by #7155?

**Comment by Istador** [comment]
Yes, you're correct. I wrongly assumed my commit 5b30f7d34461a5bca7927ff368547abe516a8de8 would auto close this issue when being merged (I wrote too much in the first sentence of the commit message).

**Comment by bloodykheeng** [comment]
// Fix marker icon issue in Leaflet with Webpack
delete (L.Icon.Default.prototype as any)._getIconUrl;

const markerIcon2x = "/react-leaflet-images/marker-icon-2x.png";
const markerIcon = "/react-leaflet-images/marker-icon.png";
const markerShadow = "/react-leaflet-images/marker-shadow.png";

L.Icon.Default.mergeOptions({
  iconRetinaUrl: markerIcon2x,
  iconUrl: markerIcon,
  shadowUrl: markerShadow,

  iconAnchor: [12, 41],        // the point of the icon which will correspond to marker's location (tip of pin)
  popupAnchor: [1, -34],       // point from which the popup should open relative to the iconAnchor
  tooltipAnchor: [12, -41],    // center the tooltip above the tip of the marker
  shadowSize: [41, 41],        // size of the shadow
  shadowAnchor: [12, 41]       // anchor point of the shadow (align with marker tip)
});
