### ISSUE TITLE
using 'inheritance' of L.ImageOverlay not displaying the image...

### ISSUE THREAD

**Issue by progman1** [Leaflet/Leaflet#6771]
I'm using what I believe is best practice in simulating inheritance in JS (mozilla docs I think):

myoverlay.prototype = Object.create( L.ImageOverlay.prototype );
myoverlay.prototype.constructor = myoverlay;

function myoverlay(bounds, image, map)
{
       // as I understand things it is not possible to invoke the inherited class's constructor when it requires parameters, hence doing it retrospectively:
        L.ImageOverlay.call(this, image, bounds,{opacity:0.2, errorOverlayUrl:'no-data.png'})
        this.addTo(map);
}

with the above I see no overlay. 
but doing this:

function myoverlay(bounds, image, map)
{
        this.x =L.imageOverlay(image, bounds,{opacity:0.2, errorOverlayUrl:'no-data.png'});
        this.x.addTo(map);
}

does work.
I see that the execution of .addTo() creates a number of instance variables, either under 'this' with the former code, under 'this.x' with the latter:
_zoomAnimated: true
_map: e
_mapToAdd: e
_leaflet_id:
_events: ...

Except this:
_image: ...
which only appears with the latter.
I would guess that it is this lack in the former case which accounts for no overlay!
but why is it not there?  is the retrospective 'call' to the L.ImageOverlay constructor with parameter arguments, in fact NOT equivalent to a 'new ...' invocation ?
or is it a bug?!

**Comment by IvanSanchez** [comment]
Please refer to https://leafletjs.com/examples/extending/extending-1-classes.html . Leaflet uses an old implementation of inheritance and can be a bit picky.

**Comment by progman1** [comment]
I previously tried this and have just repeated the attempt and no luck.
and the _image variable is again missing. why should that be?
```
var myoverlay = L.ImageOverlay.extend({
        initialize: function(bounds, image, map){
        L.ImageOverlay.prototype.initialize.call(this, image, bounds,{opacity:0.2, errorOverlayUrl:'no-data.png'})
  ...
}
});
```

**Comment by progman1** [comment]
and I put the onAdd function in there too, that does the .addTo(map)

**Comment by progman1** [comment]
I added to myoverlay.onAdd:
```
L.ImageOverlay.prototype.onAdd.call(this); 
```
 which forced the creation of _image.
but this raises some questions:
1) why is this not called when 
```
 L.ImageOverlay.prototype.addTo.call(this,map);
```
is called from myoverlay.initialize?

2) why is
```
 L.ImageOverlay.prototype.XYZ.call(...);
```
required to call an inherited class method instead of this.XYZ ?!
