### ISSUE TITLE
Bad tile position

### ISSUE THREAD

**Issue by josesaranda** [Leaflet/Leaflet#6773]
Demo: https://recordit.co/9gGY06So1X

**Steps to reproduce**
Copy paste the example in https://leafletjs.com/

**Expected behavior**
See map correctly

**Current behavior**
Map works bad

**Environment**
- Leaflet version: 1.5.1
- Browser (with version): 76.0.3809.87 (Official Build) (64-bit)
- OS/Platform (with version): MacOS Mojave 10.14.6

**Comment by IvanSanchez** [comment]
You forgot the CSS. https://stackoverflow.com/questions/38835758/leaflet-drawing-tiles-disjointly/38836996#38836996

**Comment by josesaranda** [comment]
Thanks you save my day!
