### ISSUE TITLE
Latlng.wrap() rounding error

### ISSUE THREAD

**Issue by NielsHolt** [Leaflet/Leaflet#6774]
In some cases the LatLng.wrap method have a rounding error in the result

- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**

`var lng = 2*360 + 9 + 1/3;`
`console.log( lng ); //729.3333333333334`
`console.log( L.latLng(0, lng).wrap().lng ); //9.333333333333371`
 

**Expected behavior**

`729.3333333333334`
`9.3333333333334`

**Current behavior**

`729.3333333333334`
`9.333333333333371`

**Environment**
- Leaflet version: 1.5
- Browser (with version): Chrome
- OS/Platform (with version): Windows 10

**Additional context**

Suggestion for new version of `wrapNum`
```
function wrapNum(x, range, includeMax) {
	var max = range[1],
	    min = range[0],
	    d = max - min;
	return x === max && includeMax ? x : x - Math.floor((x - min) / d) * d
}

```

**Minimal example reproducing the issue**
https://plnkr.co/edit/j2ZJ9piF3z4KwSGYUFnc?p=preview
- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by IvanSanchez** [comment]
```
> console.log(lng - 720)
9.333333333333371
```

This is behaviour as expected, [believe it or not](https://developer.mozilla.org/en-US/docs/Glossary/Number). See also https://floating-point-gui.de/
