### ISSUE TITLE
class extends ImageOverlay can not open tooltip when mouseover

### ISSUE THREAD

**Issue by Coder-JJ** [Leaflet/Leaflet#6780]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- const overlay = L.imageOverlay(url, bounds)
- overlay.bindTooltip(L.tooltip())
- mouseover the overlay

**Expected behavior**

Tooltip open at the center of overlay just like Rectangle, there should be a getCenter method.

**Current behavior**

An error is occured.

**Environment**
- Leaflet version:1.5.1
- Browser (with version):Chrome 76.0.3809.100
- OS/Platform (with version):Win10

**Additional context**

**Minimal example reproducing the issue**

Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

**Comment by neon-ninja** [comment]
Here's a codepen illustrating this problem - https://codepen.io/neonninja/pen/oNLvGqB

**Comment by AndreasAtakan** [comment]
I'm still getting this same error in v1.7.1.
Is it updated in source?

**Comment by jonkoops** [comment]
@AndreasAtakan You can try out the version that is currently in development by getting it from the [downloads](https://leafletjs.com/download.html) page. If the issue still is not fixed there feel free to let us know.

**Comment by AndreasAtakan** [comment]
Thanks @jonkoops ! I'll give it a shot, cheers!

**Comment by neon-ninja** [comment]
v1.7.1 is from Sep 04, 2020. The fix was applied after that (Oct 7, 2020). Looks like the Leaflet dev team is aware of the need for the release of 1.8.0 (https://github.com/Leaflet/Leaflet/issues/7810). I just tested and it looks like it works fine in 1.8.0

**Comment by jonkoops** [comment]
Great, thanks for verifying this @neon-ninja!
