### ISSUE TITLE
How to find the areas (or) coordinates within the 'X" range of the Route in  Map using Leaflet?

### ISSUE THREAD

**Issue by mahesh963** [Leaflet/Leaflet#6781]
I'm trying to get the coordinates of the areas that presents within the range of some **X** feet for the Route in Maps

**Environment**
- Leaflet version: 1.5.1
- Browser (with version): Chrome
- OS/Platform (with version): IOS(Version 10.14.5)

Here, I'm attaching the sample image please check it once.
![Screenshot 2019-08-26 at 4 02 22 PM](https://user-images.githubusercontent.com/20550553/63746491-91fd0680-c8c2-11e9-9704-49c1614a00b1.png)

Here, I need to get the coordinates (or) the areas that are surrounded within some 500feet range of that **Purple Line** (Route) in the Map using.
Can, Anyone help me how to resolve this issue in Leaflet.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by IvanSanchez** [comment]
https://turfjs.org/docs/#buffer
