### ISSUE TITLE
Can I add shadows for leaflet polyline or polygon ? 

### ISSUE THREAD

**Issue by xiaobc1234** [Leaflet/Leaflet#6782]
**Is your feature request related to a problem? Please describe.**
Indoor maps have hierarchical relationships and need to be shaded to distinguish them. (canvas render)

**Describe the solution you'd like**
Polyline or Polygon adds shadow attributes

**Describe alternatives you've considered**

**Additional context**

**Comment by NielsHolt** [comment]
We have made a extention: https://github.com/FCOO/leaflet-polyline that perhaps solves your problem

**Comment by perliedman** [comment]
Hi, not built in, but you can accomplish this effect in several ways, for example with @NielsHolt's plugin.

Simply adding the same line-geometry with different widths and colors can also create a shadow-like effect, see for example https://github.com/perliedman/leaflet-multi-style.
