### ISSUE TITLE
Memory leak on simple implementation

### ISSUE THREAD

**Issue by xtassin** [Leaflet/Leaflet#6784]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- Navigate to https://leafletjs.com/
- Start Chrome devTools Performance recording
- Pan and zoom map for some time

**Expected behavior**
Recovered memory after GC

**Current behavior**
Slight increase in JS heap size after GC

![image](https://user-images.githubusercontent.com/296572/63968514-3b4d2380-caa0-11e9-8697-a1c0bbc120e7.png)

**Environment**
- Leaflet version: 1.5.1
- Browser (with version): Chrome 76.0.3809
- OS/Platform (with version): Windows 10

**Comment by enorvaisa** [comment]
Might be related to #6814

**Comment by Malvoz** [comment]
Testing this again for v1.8.0:

- https://leafletjs.com/examples/quick-start/:

  ![leaflet-perf-test2](https://user-images.githubusercontent.com/26493779/174501114-1eaa2834-3f5c-4dff-8156-116ad8d443fc.png)

- https://leafletjs.com/examples/quick-start/example.html:

  ![leaflet-perf-test](https://user-images.githubusercontent.com/26493779/174501172-c12b13fd-357b-4298-8264-3c79ec975279.png)

@xtassin I don't have much experience in this area, but these look stable compared to the 1.5.1 test. What's your take on this?

**Comment by xtassin** [comment]
Can not reproduce or observe increasing memory consumption any more, with the simple use case on version 1.8
