### ISSUE TITLE
Error: Cannot read property 'lat' of undefined

### ISSUE THREAD

**Issue by sjacobi** [Leaflet/Leaflet#6789]
Code:

```
<link rel="stylesheet" href="/js/leaflet/leaflet.css" />
<script src="/js/leaflet/leaflet-src.js"></script>
<script src="https://unpkg.com/leaflet.vectorgrid@latest/dist/Leaflet.VectorGrid.bundled.js"></script>
```

```
var map = L.map('leafletmap', {
        center: [53.38877, 85.0988],
        zoom: 5,
    });

let key = 'sk.eyJ1Ijoic2VyZ2V5amFjb2JpIifjrut8mNrMDRwZ2IyeTJxdTUzZ3E5OGl6dXVvNWgifQ.h6YnuwoH9qFHjrEY5EFsBg';

var layerSatellite = L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}?blankTile=false', {
        maxZoom: 10,
        id: 'mapbox.satellite',
    }).addTo(map);

var url = 'https://api.mapbox.com/v4/sergeyjwee.3j31gq5r/' + '{z}/{x}/{y}.vector.pbf?access_token=' + key;

L.vectorGrid.protobuf(url, {
        // rendererFactory: L.canvas.tile,

        vectorTileLayerStyles: {
            'firedata-7i4kge': {
                weight: 1,
                color: '#ff0000',
                fillOpacity: 1,
                fill: true,
            }
        },

        subdomains: "abcd",
        interactive: true,	// Make sure that this VectorGrid fires mouse/pointer events
        getFeatureId: function(f) {
            console.log(f);
            return f.properties.id;
        }
"pk.eyJ1Ijoic2VyZ2V5amFjb2JpIiwiYSI6ImjFc4iDBrc2pmNXpxdWEifQ.ylwO6LsTScejbc-SlrDk2w"
    }).on('click', function(e) {

        L.popup()
            .setContent('проверка')
            .setLatLng(e.latlng)
            .openOn(map);

    }).addTo(map);
```
Error in chrome:

```
Projection.SphericalMercator.js:24

[Uncaught TypeError: Cannot read property 'lat' of undefined
    at Object.project (Projection.SphericalMercator.js:24)
    at Object.latLngToPoint (CRS.js:28)
    at NewClass.project (Map.js:992)
    at NewClass.latLngToLayerPoint (Map.js:1014)
    at NewClass.latLngToContainerPoint (Map.js:1071)
    at NewClass._fireDOMEvent (Map.js:1433)
    at NewClass._handleDOMEvent (Map.js:1396)
    at HTMLDivElement.handler (DomEvent.js:79)](url)
```

I got no bind onlick action. what to do with it?

**Comment by johnd0e** [comment]
> what to do with it?

1. Remove all unnecessary parts from your code.
   Leave only minimum to reproduce core issue.
2. Setup some sandbox (like jsfiddle) to show the issue.

**Comment by IvanSanchez** [comment]
There's a reference to `L.VectorGrid` there - make sure whether the apparent bug is in core leaflet or in VectorGrid.

**Comment by sadafzohra19** [comment]
I'm getting this error Cannot read property 'lat' on adding point mvt layer as an overlay. Polygon and polyline are working fine

**Comment by grid-100** [comment]
Got the same issue here with pbf coming from geoserver vector tiles. My layer consists of land parcels polygon, electricity network line, and distribution transformer poles as points. The polygon and line composition is working fine. Once i add point layer, the browser logs `Cannot read property 'lat' of undefined`.
Probing clickedLayer value from the scope of Leaflet.VectorGrid without firing Leaflet.GridLayer events: `this._fireEvent([clickedLayer], e);` and `this._handleMouseHover(e, point);` show that clickedLayer has correct properties and all chrome errors are gone.
```
	_onClick: function (e) {
		var point = this._map.mouseEventToLayerPoint(e).subtract(this.getOffset()), layer, clickedLayer;

		for (var id in this._layers) {
			layer = this._layers[id];
			if (layer.options.interactive && layer._containsPoint(point) && !this._map._draggableMoved(layer)) {
				clickedLayer = layer;
			}
		}
		if (clickedLayer)  {
			L.DomEvent.fakeStop(e);
			console.log(clickedLayer);
			//this._fireEvent([clickedLayer], e);
		}
	},

	_onMouseMove: function (e) {
		
		if (!this._map || this._map.dragging.moving() || this._map._animatingZoom) { return; }
		var point = this._map.mouseEventToLayerPoint(e).subtract(this.getOffset());
		//this._handleMouseHover(e, point);
	},
```
Also please take a look at this [236](https://github.com/Leaflet/Leaflet.VectorGrid/issues/236) issue. I found weird number from Leaflet.VectorGrid `getOffset()` at fractional zoom. Looks like the number has been incorrectly multiplied by the scaling.

**Comment by grid-100** [comment]
Well, I just found the solution. This code works for me (See original [answer](https://stackoverflow.com/questions/58072432/popup-window-for-points-using-leaflet-vectorgrid-error-lat-of-undefined)). Hope it helps others.
```
_createLayer: function(feat, pxPerExtent, layerStyle) {
    var layer;
    switch (feat.type) {
    case 1:
        layer = new PointSymbolizer(feat, pxPerExtent);
        // [YB 2019-10-23: prevent leaflet from treating these canvas points as real markers]
        layer.getLatLng = null;         
        break;
    case 2:
        layer = new LineSymbolizer(feat, pxPerExtent);
        break;
    case 3:
        layer = new FillSymbolizer(feat, pxPerExtent);
        break;
    }

    if (this.options.interactive) {
        layer.addEventParent(this);
    }

    return layer;
}
```

**Comment by IvanSanchez** [comment]
Please forward that to the Leaflet.Vectorgrid repo, propose a PR.

**Comment by rzagha1** [comment]
> Well, I just found the solution. This code works for me (See original [answer](https://stackoverflow.com/questions/58072432/popup-window-for-points-using-leaflet-vectorgrid-error-lat-of-undefined)). Hope it helps others.
> 
> ```
> _createLayer: function(feat, pxPerExtent, layerStyle) {
>     var layer;
>     switch (feat.type) {
>     case 1:
>         layer = new PointSymbolizer(feat, pxPerExtent);
>         // [YB 2019-10-23: prevent leaflet from treating these canvas points as real markers]
>         layer.getLatLng = null;         
>         break;
>     case 2:
>         layer = new LineSymbolizer(feat, pxPerExtent);
>         break;
>     case 3:
>         layer = new FillSymbolizer(feat, pxPerExtent);
>         break;
>     }
> 
>     if (this.options.interactive) {
>         layer.addEventParent(this);
>     }
> 
>     return layer;
> }
> ```

where did you put this? which source code and on what line?

**Comment by DALIHILLARY** [comment]
Ensure that the data the script is consuming exists ie do null-checks on all coordinate pairs and other necessary data

**Comment by AdarshSrikanth** [comment]
This does not seem to be fixed yet. Any ETA on the fix?

Adding the following simple check to src/map/Map.js works:
`const isMarker = target.getLatLng && **target._latlng** && (!target._radius || target._radius <= 10);`
