### ISSUE TITLE
Leaflet can end up in state where it receives document keyboard events even when it's blurred (Firefox)

### ISSUE THREAD

**Issue by olzraiti** [Leaflet/Leaflet#6790]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**

If you append the leaflet container to another node while the map is focused, a blur event isn't sent even though `document.activeElement` isn't any leaflet node anymore  (it's `body`). This happens only on Firefox, Chrome sends a `blur` event correctly.

- Focus the leaflet map
- Append the node containing leaflet to a new node
- `document.activeElement` is `body`, but a `blur` even't wasn't sent. If you now e.g. start typing in a text input, '+' and '-' keys will be grabbed by leaflet and will zoom the map since leaflet taps into document keyboard events while the map is considered focused.

**Expected behavior**
If Leaflet map is focused and later on the `document.activeElement` is an element that isn't a child of the leaflet container, a blur event should have been fired.

Since this is really a Firefox bug, it's not directly solvable since we can't observe when the container node changes. Maybe we should provide a `setRootElem()` method, that would send a Leaflet blur event and then change the container?

**Environment**
- Leaflet version: 1.4.0
- Browser (with version): Firefox 68.0.2
- OS/Platform (with version): Linux 4.15.0-58-generic #64-Ubuntu

**Additional context**

**Minimal example reproducing the issue**

Demopage: https://plnkr.co/edit/daARGARUv5SmzsMgyhYh?p=preview

The demo appends a new HTML node to body and appends the leaflet container to the new node after a timeout. `focus` and `blur` events are logged to console.

- Navigate to the demo on Firefox https://plnkr.co/edit/daARGARUv5SmzsMgyhYh?p=preview
- Open console
- Click the map within 4 secs in order to focus it, 'focus' is outputted to console
- Wait for the timeout (4s)
- The active element is outputted, which is 'body'. However, 'blur' isn't in console output.

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by perliedman** [comment]
Hi,
as you mention, this really sounds like a Firefox bug, not an issue with Leaflet. Have you filed a bug with Firefox?

Also, might I ask what the use case for moving the Leaflet container around in the DOM is? I'm sure there is some cases where the user would want to do that, but it occurs to me as a pretty unusual niche-case that we might not want to build a specific API for, especially to work around what sounds like a browser bug.

**Comment by Malvoz** [comment]
> this really sounds like a Firefox bug, not an issue with Leaflet

Indeed: https://bugzilla.mozilla.org/show_bug.cgi?id=559561
