### ISSUE TITLE
geojson Boundary line cannot be displayed

### ISSUE THREAD

**Issue by FlyDanKe** [Leaflet/Leaflet#6793]
version 1.5.1   
geojson Boundary line cannot be displayed
code
    let myStyle = {
        "color": "#ff7800",
        "weight": 5,
        "opacity": 0.65
    };
    let boundslayer = L.geoJSON(JSON.parse(json),{style: myStyle}).addTo(map);
    map.flyToBounds(boundslayer);

**Comment by FlyDanKe** [comment]
import leaflet-src.js It can be displayed normally.  
import leaflet.js cannot be displayed

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?

**Comment by FlyDanKe** [comment]
Sorry, it can only appear in certain circumstances, I can't reproduce it. You can look at the screenshots, which may be caused by the software of my computer.
screenshots:http://49.235.245.61/map/map.jpg
code:http://49.235.245.61/map/map.html
