### ISSUE TITLE
Problem to use the draw component in some browsers as PWA app

### ISSUE THREAD

**Issue by Isaquedanielre** [Leaflet/Leaflet#6796]
Hello, we are developing a application for farmers evaluate their land and in the  map component we are using the leaflet map component to draw the plots location. 

Our application is a PWA and runs the draw component perfectly in firefox. 

However the draw map component in the google chrome, brave, opera doesn't work. 

There any type of configuration to do? or it seems as a bug?

If you are interested in try:

1 - access the http://dapp.agryo.com
2 - install as a PWA app 
3 - close the browser and enter by the pwa icon in the mobile. 

Try in firefox and google crhome/brave/opera and others.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
