### ISSUE TITLE
WMS layer not rendering in Firefox

### ISSUE THREAD

**Issue by Abbe98** [Leaflet/Leaflet#6805]
**Steps to reproduce**
- open the minimal example provided below in Firefox
- if you see blue and orange icons the WMS layer is rendering

**Expected behavior**

The WMS layer should render as it does in Chromium(77).

**Current behavior**

While the WMS layer is rendering in Chromium it's not rendering in Firefox nor does it execute any HTTP calls to the WMS service.

**Environment**
- Leaflet version: 1.5.1
- Browser (with version): Firefox 69 
- OS/Platform (with version): Ubuntu 19.04

**Additional context**

**Minimal example reproducing the issue**

https://plnkr.co/edit/VTSSGtb1hGM21y4MjgrB?p=preview

**Comment by langer-man** [comment]
https://www.npmjs.com/package/easy-drawing 
another view

**Comment by IvanSanchez** [comment]
Can't reproduce using Firefox 69 on Debian.

![image](https://user-images.githubusercontent.com/1125786/65391043-8cc99500-dd64-11e9-83f9-5a54e8f05330.png)
