### ISSUE TITLE
3D View

### ISSUE THREAD

**Issue by desmeit** [Leaflet/Leaflet#6810]
How can I display a map in 3D View? Just as you know it from GPS navigation.
I dont want to have 3D cities or something. I just want to change the perspective of a map.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by IvanSanchez** [comment]
See CesiumJS.
