### ISSUE TITLE
Leflet Map Rotate

### ISSUE THREAD

**Issue by pravinmitta** [Leaflet/Leaflet#6811]
Hi Team,

i want to rotate my leaflet map in mobile device after placing the overlay on top of the map.And i've used Hammerjs to rotate. I'm not able to rotate with the below code

    var div = document.getElementById('map');
    var element = new Hammer.Manager(div);
    var Rotate = new Hammer.Rotate();

	// add the recognizers
	element.add(Rotate);
 
  element.on('rotate',function(e){
    // alert('rotate event');
    let rotation = Math.round(e.rotation);
    element.style.transform = 'rotate('+rotation+'deg)';
  })

**Comment by IvanSanchez** [comment]
Duplicate of #268

**Comment by pravinmitta** [comment]
How we can rotate in mobile with pinching and zooming
