### ISSUE TITLE
How to set default language (English) for different countries visitors.

### ISSUE THREAD

**Issue by sungraiz** [Leaflet/Leaflet#6816]
Hi,

I read your documentation properly but I am unable to find a way to set the **default language for all** kind of users.

For now, it shows the **map only in localize language** but some users want to show the **map only in English for all**.

Please let me know if this can be doable or guide me through any procude if it is already available.

Thanks for the great work though.

Regards,

**Comment by IvanSanchez** [comment]
See https://stackoverflow.com/questions/18589621/setting-map-language-to-english-in-openstreetmap-with-leafletjs

**Comment by sungraiz** [comment]
Hi,

I am familiar with the above thread. But why there is no **simple setting** provided in **Leaflet Script** which user can use to set their desired language?

Don't you feel that the thread you shared is complex and not for every user?

Please let me know if there is any built-in setting in Leaflet or any easy way of doing it.

Regards,

**Comment by upadhyay-shubham** [comment]
There are lots of tile servers available based on OSM, you can choose the one that fits your requirement.
Visit : http://leaflet-extras.github.io/leaflet-providers/preview/

Hope this solves your issue.
