### ISSUE TITLE
Generate Static Maps

### ISSUE THREAD

**Issue by williehallock802** [Leaflet/Leaflet#6819]
Google, for example, supplies a way to generate static maps based on marker locations.

https://developers.google.com/maps/documentation/maps-static/intro

It would be nice if, in addition to the excellent interactive and dynamic maps that leaflet is capable of generating, it could also generate static maps saving all of the overhead of providing interactivity where it is not required.

(if this is already possible, I would be interested in learning how it can be done.)

**Comment by perliedman** [comment]
Hi,
this is generally out of scope for Leaflet, which aims to make interactive maps in the browser. Compared to Google Maps, which is a lot of things: a browser API. a world-covering data set, satellite imagery, several server APIs, and so on, Leaflet is just client-side JavaScript. It sounds like you envision some server-side API, which I don't think would suite Leaflet very well.

Having said that, I know there was at least at some point a plugin to make static images from a Leaflet map, you might want to check that.

**Comment by secretgspot** [comment]
> this is generally out of scope for Leaflet, 
not sure how that's out of scope when there are many situations where you want to present static version that doesn't need to load tons of tiles or waste resources

**Comment by auspex** [comment]
I'd agree. I have code that generates interactive maps with leaflet. Occasionally, I just want the same thing in a static image. Most particularly, when I have a printable view of a map, I've yet to find a way to _guarantee_ that all layers get printed completely. Even if I wait for the `onload` event of the base layer, I routinely find that not all tiles get printed! If  a static image could be generated by essentially the same code as the interactive map, my printed maps would always be complete.
