### ISSUE TITLE
A way to add many points (scatter plot or smilar)

### ISSUE THREAD

**Issue by bjornasm** [Leaflet/Leaflet#6832]
**Is your feature request related to a problem? Please describe.**
I see no description in the docs on how you can add several points other than writing code for each individual point. This is extremely frustrating as almost no data analysis is done on data small enough to plot every single point.
**Describe the solution you'd like**
Either an implementation or atleast documentation on how to plot >100 points (as basemap does with scatter plots).

**Comment by perliedman** [comment]
Hi, 
I hope I am not missing some detail here, but I think you should convert you data to GeoJSON, and you can add as many points as you like with a single call, no need to write code for each.
