### ISSUE TITLE
Please make double right-click do _something_ -- either zoom out or show a help message

### ISSUE THREAD

**Issue by unforgettableid** [Leaflet/Leaflet#6835]
# Background

In Leaflet (and on the openstreetmap.org homepage), double right-click currently does nothing.  This is by design:  please see the related discussion in #1378.

# Why it's good to allow double right-click

In general, when writing map software, it's good to allow users to zoom out using double right-click.  This is because:

1.  It's more discoverable than Shift + double-click.
2.  Google Maps supports double right-click, but doesn't support Shift + double-click.  So, if you support double right-click, frequent Google Maps users can take advantage of muscle memory and use the same shortcut when using both Google Maps and Leaflet.

# My two requests

If users do a double right-click, please either:

**Option A)**  Zoom out.  Here's [a code snippet](https://github.com/Leaflet/Leaflet/issues/1378#issuecomment-443198028) designed to do exactly that.

**Option B)**  Or, if you really insist that users should use Shift + double-click instead, please show a help message on-screen:  "To zoom out, please use Shift + double-click."

# Conclusion

I wonder if you'd be willing to please implement either option A or B, or to consider accepting a future pull request which implements one of them?

P.S.  Thank you for maintaining Leaflet!

**Comment by perliedman** [comment]
Hi,
thanks for your detailed and well-presented suggestion! As you mention, this has already been discussed and turned down in #1378, and I don't think we will reconsider the decision at this point. I might also add that I don't think it's necessarily a good thing to mimic Google Maps in every way: as mentioned, quite a few other popular mapping APIs already support the Shift+doubleclick that we do.

Displaying on-screen messages is outside what we usually do in Leaflet: we leave that up to the app that's using it. The same goes for implementing double right-click to zoom out: it should be easy to add to an app, or write a plugin to do it.
