### ISSUE TITLE
Getting error  "Argument 1 of Node.appendChild..." when clicking marker.

### ISSUE THREAD

**Issue by sagarpreet-chadha** [Leaflet/Leaflet#6840]
- [ ] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [ ] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [ ] I've searched through the issues to make sure it's not yet reported

I have various maps on my page which fetched data from some provider and shows them as markers on screen. 
Only the last map in the screen is able to open popups on clicking the markers, rest of the maps gives error : **"Argument 1 of Node.appendChild does not implement interface Node"** in the console.

You can look at this link to reproduce the error: https://publiclab.org/notes/sagarpreet/10-06-2019/testing-new-inline-maps?_=1570390795

**Expected behavior**
The markers on all maps should open.

**Current behavior**
Only the markers on last map on the screen are able to open popups.

**Environment**
- Leaflet version: Latest
- Browser (with version): Chrome and Mozilla
- OS/Platform (with version): MacOS

**Minimal example reproducing the issue**

 https://publiclab.org/notes/sagarpreet/10-06-2019/testing-new-inline-maps?_=1570390795

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

**Comment by sagarpreet-chadha** [comment]
Console error:

```
Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at NewClass._updateContent (LeafletEnvironmentalLayers.js:21428)
    at NewClass.update (LeafletEnvironmentalLayers.js:21371)
    at NewClass.onAdd (LeafletEnvironmentalLayers.js:21308)
    at NewClass.onAdd (LeafletEnvironmentalLayers.js:21562)
    at NewClass._layerAdd (LeafletEnvironmentalLayers.js:18527)
    at NewClass.whenReady (LeafletEnvironmentalLayers.js:16407)
    at NewClass.addLayer (LeafletEnvironmentalLayers.js:18589)
    at NewClass.openPopup (LeafletEnvironmentalLayers.js:21785)
    at NewClass.openPopup (LeafletEnvironmentalLayers.js:21893)
    at NewClass._openPopup (LeafletEnvironmentalLayers.js:21968)

```

**Comment by ghybs** [comment]
Closed as explained in https://github.com/Leaflet/Leaflet/pull/6838#issuecomment-542854125

> Therefore it seems to me that the bug you are trying to solve is specific to your app and caused by incorrect usage of Leaflet API.

**Comment by sagarpreet-chadha** [comment]
Umm, i have double checked the use of API, i am passing HTML everytime.

**Comment by ghybs** [comment]
Hi @sagarpreet-chadha,

If you still think there is an issue in Leaflet (it might very well be the case), please make sure to provide more details of how you use it, and in particular a _minimal_ reproduction example, so that we can properly investigate.

**Comment by sagarpreet-chadha** [comment]
Okay, i will investigate more and try to reproduce the error in a minmal example. Thanks!
