### ISSUE TITLE
Include a function to determine if exists a Layer with same LatLngs of an array of LatLngs

### ISSUE THREAD

**Issue by Will17** [Leaflet/Leaflet#6849]
I would like to suggest a function that would be great in my case. I have a LayerGroup of Polygons (4 points for each Polygon) added to the map, and i would like to know, using 4 LatLng points, if they are the same points of one (or more) already present in the LayerGroup's polygons.

What i tried is this: 
1) Get LatLngs array with `LayerGroup.getLayers()`
2) Get string-formatted LatLngs points with `layer.getLatLngs().toString()`
3) Compared it with `latlngs.toString()`

```
// Created a LayerGroup with a Polygon inside with points (10,11) and (11,12)
var lg = new L.LayerGroup([new L.Polygon([new L.LatLng(10,11),new L.LatLng(11,12)])]);
var points = [new L.LatLng(10,11),new L.LatLng(11,12)];

function checkPointsInLayerGroup(lg,pts){
    var layers = lg.getLayers();
    for(var i=0;i<layers.length;i++){
        if(layers[i].getLatLngs().toString() == pts.toString()){
            // The points are already taken by a polygon in the layerGroup specified
            return true;
        }
    }
    return false;
}

console.log(checkPointsInLayerGroup(lg,points));
```
I know that of course comparing strings is not the best solution, but it would be useful if there would be a function that does the trick.

**Comment by Falke-Design** [comment]
@johnd0e @mourner I think we don't want to implement something like, I'm correct? Everyone can make this easy by him self
