### ISSUE TITLE
Why is the circle I painted is not a perfect circle?

### ISSUE THREAD

**Issue by sytana** [Leaflet/Leaflet#6857]
![image](https://user-images.githubusercontent.com/11701135/66636930-add72480-ec44-11e9-9b7f-c2f2c9af21fc.png)

```js
L.circle([lat, lng], {
	radius: 200
})
```

Thanks!

**Comment by sytana** [comment]
Yes, `crs: L.CRS.EPSG4326`, sorry, I can't post it on the codepen, Because the tile service I use is intranet.

```js
window.zxmap = L.map('zxmap', {
	center: {lng: defaultCoordinate.lng, lat: defaultCoordinate.lat},
	zoom: defaultCoordinate.zoom,
	crs: L.CRS.EPSG4326,
	layers: [L.tileLayer(mapTiles[useMapTile].url, {zoomOffset: 1})]
	})
```

Thanks!

**Comment by IvanSanchez** [comment]
Then this is behaviour as expected, as per https://github.com/Leaflet/Leaflet/pull/2345
