### ISSUE TITLE
Markers disapper after bounding box change in Angular6

### ISSUE THREAD

**Issue by JacopoSciampi** [Leaflet/Leaflet#6863]
- [x ] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [ x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [ x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- Import leaftlet in angular.json (or in the index.html file).
- Create a function that simply draw some markers around the map.
- zoom on a Marker, then move the pan for a while, zoom to see a better view, zoom again the marker.

**Expected behavior**
I should see every markers I've drawn.

**Current behavior**
Some markers disappeard. (Photo attached).

![image](https://user-images.githubusercontent.com/32507291/66843398-05d79900-ef6d-11e9-91ab-e68a7a0bfc23.png)
![image](https://user-images.githubusercontent.com/32507291/66843442-1720a580-ef6d-11e9-8f4b-dc35e476070c.png)

In this case I just zoomed out one tick. The markers on the right disappeard for no reason. 
Note that the same code works perfectly in a common .html file.

**Environment**
- Leaflet version: Leaflet v1.3.1+HEAD.ba6f97f (tried even with the newest)
- Browser (with version): Chrome 77.0.3865.90
- OS/Platform (with version): Elementary OS (is not releated to the OS)

- [x] this example is as simple as possible
- [x ] this example does not rely on any third party code

**Comment by ghybs** [comment]
Hi, great to hear that you find Leaflet useful!

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* Angular / AngularJS
* Leaflet for R
* Joomla
* WordPress
* Drupal
* Rails
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* etc.

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.
