### ISSUE TITLE
How to get Lat and Lng from District names stored in database table

### ISSUE THREAD

**Issue by IntegrityFoundation** [Leaflet/Leaflet#6874]
I have a master table called Districts which stores district Id and District Name. I dont have Lat and Lng for displaying the markers on the map. So how should I get the lat and lng from district names to use them as lat and lng in leaflet while creating a map. I will be using leaflet js. I am using Yii2 framework

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
