### ISSUE TITLE
Code blocks are broken in the docs

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#6878]
https://leafletjs.com/examples/quick-start/

Just noticed that code blocks on the website are broken — they have a redundant indentation at the beginning and no syntax highlighting. I wonder what might have broken this. cc @simon04 maybe something in your changes?

**Comment by yozaam** [comment]
I think we should add the hljs class in addition to the javascript class to get back the background but for the syntax highlighting let me look at the code

**Comment by mourner** [comment]
Still doesn't appear to be fixed :(

**Comment by mourner** [comment]
Nope, seems to be a hiccup in the GH pages build. All good now.
