### ISSUE TITLE
Can Tile layer be rendered using <canvas>?

### ISSUE THREAD

**Issue by sytana** [Leaflet/Leaflet#6879]
Wouldn't there be a problem with rendering tiles using canvas? #6101 

So, I think LeafletJS should at least provid canvas rendering scheme.

This issue should be taken seriously because it makes the experience bad.

like OpenLayers:
![image](https://user-images.githubusercontent.com/11701135/68261745-0f3fb700-007c-11ea-9580-d12ee7b7ea9d.png)

**Comment by marlo22** [comment]
Hi there, we've prepared something similiar. Maybe it will help you? https://github.com/GIAPspzoo/L.TileLayer.Canvas
