### ISSUE TITLE
Deploying Leaflet JS with Java EE

### ISSUE THREAD

**Issue by Khal15107** [Leaflet/Leaflet#6880]
Hello everyone,
I'm looking for a solution to make a traffic car simulation using a certain map.
So by using Leaflet and exactly with Java EE is it possible ?
is it possible to generate cars which moves randomly on the map ?
and if yes... how is that possible ?
Thank you

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
