### ISSUE TITLE
Issue with L.marker position created with L.divIcon

### ISSUE THREAD

**Issue by lavruxa** [Leaflet/Leaflet#6883]
The lib adds "margin-top:-16px" to icon style by default, should it be -32px(icon image height)?

**Minimal example reproducing the issue**

https://plnkr.co/edit/pzVHHlMpAN8Eo4Kk0ClE?p=preview

**Comment by jjimenezshaw** [comment]
I guess it should be half height (as it is)

See your example, with to lines crossing at this point:
https://plnkr.co/edit/pTo0PdIJh5TuCYDBgzRY?p=preview

**Comment by johnd0e** [comment]
> should it be -32px(icon image height)?

It depends on https://leafletjs.com/reference.html#icon-iconanchor
