### ISSUE TITLE
Pan with vh/vw dimensions

### ISSUE THREAD

**Issue by cwewells** [Leaflet/Leaflet#6886]
I've noticed there is an issue with leaflet where starting to pan will change dimensions of other items on a page. I've run into the issue when using a parent element with vh/vw dimensions for width and height in a CSS grid.

**Comment by FadilEldin** [comment]
If this is still valid, Can you please provide instruction of how to reconstruct the issue?

**Comment by Malvoz** [comment]
Is it time to close this? I attempted to reproduce with the limited info, but was unable to.

**Comment by Falke-Design** [comment]
Yep
