### ISSUE TITLE
Double-tap is not working in iPhone IOS 13.

### ISSUE THREAD

**Issue by necheporenko** [Leaflet/Leaflet#6889]
**Map Zoom - Double Tap**

**Issue:**
On some versions of iPhones you can double-tap on the map, and the map zooms in. However, on some iPhones, the double-tap has no action on the map.

**Steps to reproduce:**
Load the map on a phone
Double tap on the map

**Actual Results:**
The map does not zoom in one place on place tapped.
Tested working this way on:
iPhone XR version 13.1.3;
iPhone SE version 13.1.3.

**Expected Results:**
The Map zooms in one place on place tapped.
Tested working this way on:
iPhone 6 Plus, using version: 12.4.2;
Android 9 .

**Comment by mourner** [comment]
This should be fixed after #6855 — this will be included in the next release (which is just around the corner — #6892).
