### ISSUE TITLE
`Added non-passive event listener to a scroll-blocking 'touchstart' event.`

### ISSUE THREAD

**Issue by iamandrewluca** [Leaflet/Leaflet#6893]
```
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event.
Consider marking event handler as 'passive' to make the page more responsive.
See https://www.chromestatus.com/feature/5745543795965952
```

**Comment by Frikki** [comment]
Why did you close this issue, @iamandrewluca? This is still an issue in leaflet v1.6.0?

**Comment by iamandrewluca** [comment]
@Frikki I don't know if it still a issue. Closed it because, the PR and the issue didn't get any attention. Now PR as I see has conflicts, because it's 5 months old.

**Comment by Frikki** [comment]
I see. Sad. It's not fixed.

**Comment by Malvoz** [comment]
See https://github.com/Leaflet/Leaflet/pull/7008.

**Comment by Frikki** [comment]
Great to know it's coming. However, faster minor releases would be appreciated.

**Comment by johnd0e** [comment]
See #7052.
