### ISSUE TITLE
Marker with .png Icon rendering issues on iOS 13.2.2 with Safari

### ISSUE THREAD

**Issue by kovapatrik** [Leaflet/Leaflet#6895]
**Steps to reproduce**
- I don't know if it can be reproduced.

**Expected behavior**
I have 4 types of marker with different images. I have some filter options which selects specific objects from a database and create a marker from it's lat-lng data. I can choose, which layer be shown on the map.

**Current behavior**
If I switch a layer off, then on, the image for the ping isn't loaded (maybe a quarter of it) or random markers will be rendered (not that ones, which is selected). If I switch to an other application on my phone, then back to Safari, the markers are fully loaded.

![Before](https://user-images.githubusercontent.com/44952801/69015415-df55b500-0993-11ea-9e35-be2ebd4175b6.jpg)
![After](https://user-images.githubusercontent.com/44952801/69015416-df55b500-0993-11ea-9a0a-4266ec4d679b.jpg)

**Environment**
- Leaflet version: 1.6.0
- Browser (with version): Safari
- OS/Platform (with version): iOS 13.2.2

**Additional context**
It works in Chrome on iOS, so it's some kind of Safari-Leaflet problem. I don't have a lot of markers, about 130 pieces. The png files size are: 30KB and 300KB.

**Comment by mourner** [comment]
Unfortunately we'll need a minimal live test case to be able to diagnose the issue — screenshots and description are not enough.

**Comment by kovapatrik** [comment]
Here is the website: [Live test](https://olcsosor-git-testing.gopear.now.sh/)

You can turn off/on the layers in the bottom left corner by clicking on the colored squares.

**Comment by kovapatrik** [comment]
I solved the problem with replacing my .png files with much lower resolution ones.
