### ISSUE TITLE
Zoom/pan not working on Windows 10 Touch in Chrome and Edge

### ISSUE THREAD

**Issue by sveine** [Leaflet/Leaflet#6896]
The fix #6855 had some side effects on Windows 10 Touch in Chrome and Edge. In Chrome and Edge zoom scales page. Pan works in Edge, but does nothing in Chrome. Firefox is OK.

**Comment by max-collomb** [comment]
I think this is related with `L.Browser.pointer` that is now `false` where it used to be `true` on my chrome on windows (with no touch).

**Comment by sveine** [comment]
On my Windows 10 Surface PC - Chrome, Firefox and Edge are working on the touch screen with this fix, except when I detach the screen it is very hard to zoom in Firefox. I think this is a minor problem. I think most people are using Edge or Chrome on touch screen. I could not find out how to fix this.

**Comment by plepe** [comment]
Same problem, Chromium 78 on Ubuntu Linux 18.04. Zooming via touch gestures works with Leaflet 1.5.1, but not with 1.6.0. `L.Browser.pointer` is `false` on 1.6.

Touch gestures work with Firefox 70 with Leaflet 1.5.1 and 1.6.0.

**Comment by ivangermanov** [comment]
Touch events on Chrome desktop (79.0.3945.79) not working here (Leaflet 1.6.0). I think it's something to do with how Leaflet internally checks if the browser supports touch. L.Browser.touch=undefined for me on a Windows 10 Surface Pro.

**Comment by Peetz0r** [comment]
I can confirm this on Linux (Chromium 79 on Fedora 31) too. Touch on my convertible works on 1.5.1, broken on 1.6.0.

Firefox seems to not be affected, both 1.5.1 and 1.6.0 behave the same and touch works fine.

**Comment by ETJ9914** [comment]
Still affected by this in Chrome using Leaflet 1.6.0, any idea when will it be fixed? Or other workarounds since L.Browser.touch is readonly so cannot be set manually.

**Comment by johnd0e** [comment]
Dirty hack: set `window.ontouchstart="true"` before loading Leaflet.

But better go and up-vote #6977

**Comment by sveine** [comment]
I had manually patch Leaflet 1.7.1 with my fix. Other fix did not solve this problem.

**Comment by johnd0e** [comment]
> I had manually patch Leaflet 1.7.1 with my fix. Other fix did not solve this problem. 

What is 'your fix'?

**Comment by sveine** [comment]
> 
> 
> > I had manually patch Leaflet 1.7.1 with my fix. Other fix did not solve this problem.
> 
> What is 'your fix'?

[Zoom/pan not working on Windows 10 Touch in Chrome and Edge](https://github.com/sveine/Leaflet/commit/2e34bda4d1e926379e3ea3e088cc27f724c7c97a)

"...|| Browser.edge" seems not necessary anymore

**Comment by johnd0e** [comment]
@sveine 
I suppose this will help too: https://github.com/Leaflet/Leaflet/pull/7029/commits/7187e12bf5c4a4e1ab096bcf41f1850cddf5e6fd

**Comment by sveine** [comment]
> 
> 
> @sveine
> I suppose this will help too: [7187e12](https://github.com/Leaflet/Leaflet/commit/7187e12bf5c4a4e1ab096bcf41f1850cddf5e6fd)

Yes it worked!

A side effect of "touch=true" setting is that the touch-panel is slow on pinch/unpinch zoom.

**Comment by johnd0e** [comment]
> A side effect of "touch=true" setting is that the touch-panel is slow on pinch/unpinch zoom. 

Could you provide more details?
And have you applied this single commit, or whole #7029?

**Comment by sveine** [comment]
> 
> 
> > A side effect of "touch=true" setting is that the touch-panel is slow on pinch/unpinch zoom.
> 
> Could you provide more details?
> And have you applied this single commit, or whole #7029?

Only replaced line 1911 in leaflet-src.js 1.7.1 with 
var touch = !window.L_NO_TOUCH && (pointer || 'ontouchstart' in window || window.TouchEvent);

(If you has a patched leaflet-src.js I can test)

**Comment by sveine** [comment]
> 
> 
> > A side effect of "touch=true" setting is that the touch-panel is slow on pinch/unpinch zoom.
> 
> Could you provide more details?
> And have you applied this single commit, or whole #7029?

The touchpad zooms on integer levels with touch=false, decimal with touch=true. With touch=true a two finger zoom in/out is OK on fast finger move. Tried Google Maps. It is very smooth on both touchpad, screen zooming and mouse - so it is somehow possible to make it work.

**Comment by johnd0e** [comment]
> The touchpad zooms on integer levels with touch=false, decimal with touch=true. With touch=true a two finger zoom in/out is OK on fast finger move. Tried Google Maps. It is very smooth on both touchpad, screen zooming and mouse - so it is somehow possible to make it work.

That are valuable details. Could you open separate issue for this problem?

**Comment by sveine** [comment]
> 
> 
> > (If you has a patched leaflet-src.js I can test)
> 
> Sure I have: https://gist.githack.com/johnd0e/3ad393c73b12b24af7e947711a87b7a4/raw/leaflet-src.js
> 
> And here are 2 test pages (for unrelated issues) but with same "patched" leaflet:
> https://gist.githack.com/johnd0e/3ad393c73b12b24af7e947711a87b7a4/raw/issue-6632.html
> https://gist.githack.com/johnd0e/3ad393c73b12b24af7e947711a87b7a4/raw/issue-5969.html

The leaflet-src.js her works fine.
You do not have zoomSnap: 0 in your example. Setting this to 0 is a must - not to make map jump to next/prev zoom on screen zooming. When zoomSnap is set, I think touchpad zoom should have a factor based on zoomSnap.

**Comment by johnd0e** [comment]
> You do not have zoomSnap: 0 in your example. Setting this to 0 is a must - not to make map jump to next/prev zoom on screen zooming. When zoomSnap is set, I think touchpad zoom should have a factor based on zoomSnap.

Are we already talking about #7476?

**Comment by sveine** [comment]
> Are we already talking about #7476?

Mostly for #7476. But testing touch in your pages without zoomSnap:0 may not be relevant. https://github.com/Leaflet/Leaflet/issues/7476#issuecomment-783531470

**Comment by johnd0e** [comment]
Here is sample with ` zoomSnap:0`;
https://gist.githack.com/johnd0e/3ad393c73b12b24af7e947711a87b7a4/raw/issue-7476.html

**Comment by sveine** [comment]
> 
> 
> Here is sample with ` zoomSnap:0`;
> https://gist.githack.com/johnd0e/3ad393c73b12b24af7e947711a87b7a4/raw/issue-7476.html

It's working :-)

**Comment by johnd0e** [comment]
> It's working :-)

Could you describe which of mentioned here issue are fixed there?

**Comment by sveine** [comment]
> 
> 
> > It's working :-)
> 
> Could you describe which of mentioned here issues are fixed there?

Zoom does not scale the page, but zooms the map

**Comment by johnd0e** [comment]
That is weird anyway, because both Chrome and Firefox support pointer events, so neither your, nor your fix should not change anything: when `L.Browser.pointer` is `true` - `L.Browser.touch` gets `true` as well.

So:
1. Make sure that you are using latest leaflet (vanilla, without any fixes)
2. Open dev console and check both values

**Comment by sveine** [comment]
> 
> 
> That is weird anyway, because both Chrome and Firefox support pointer events, so neither your, nor your fix should not change anything: when `L.Browser.pointer` is `true` - `L.Browser.touch` gets `true` as well.
> 
> So:
> 
>     1. Make sure that you are using latest leaflet (vanilla, without any fixes)
> 
>     2. Open dev console and check both values

Read the first comment in this issue.

**Comment by johnd0e** [comment]
> Read the first comment in this issue.

Mentioned there bug was fixed in #7010 (by me).
So if you still can observe same (wrong) behavior with latest leaflet - it is different bug.

**Comment by sveine** [comment]
> 
> 
> > Read the first comment in this issue.
> 
> Mentioned there bug was fixed in #7010 (by me).
> So if you still can observe same (wrong) behavior with latest leaflet - it is different bug.

Long tap on iOS is not working 1.7.1. 
By setting var pointer = !webkit && !!(window.PointerEvent || msPointer);, long tap is working.
and then by setting:
  var touch = !window.L_NO_TOUCH && (pointer || 'ontouchstart' in window || navigator.maxTouchPoints > 0 || navigator.msMaxTouchPoints > 0 ||
  		(window.DocumentTouch && document instanceof window.DocumentTouch));

Zoom/pan is working on Windows 10 Touch in Chrome and Edge"

**Comment by sveine** [comment]
> 
> 
> > Long tap on iOS is not working 1.7.1.
> 
> You can test #7026 and/or #7029.
> 

Can you please create a page for testing?

**Comment by johnd0e** [comment]
7026: there is test page in description
7029: see [upper](https://github.com/Leaflet/Leaflet/issues/6896#issuecomment-783458056) post

**Comment by sveine** [comment]
> 
> 
> 7026: there is test page in description
> 7029: see [upper](https://github.com/Leaflet/Leaflet/issues/6896#issuecomment-783458056) post

They are not working. Element on map is selected. Your test page the '+' sign is selected (contextmenu event is triggered)

**Comment by johnd0e** [comment]
contextmenu event is triggered == they are working (7026)
And [as far as I know](https://github.com/Leaflet/Leaflet/issues/7394#issuecomment-753310977), after 7029 + sign should not be selected

**Comment by sveine** [comment]
> 
> 
> contextmenu event is triggered == they are working (7026)
> And [as far as I know](https://github.com/Leaflet/Leaflet/issues/7394#issuecomment-753310977), after 7029 + sign should not be selected


https://user-images.githubusercontent.com/367125/110366946-51e61a80-8047-11eb-84ff-4b3e79c30a75.mp4

**Comment by johnd0e** [comment]
Have you followed the [link](https://github.com/Leaflet/Leaflet/issues/7394#issuecomment-753310977) that was mentioned?

I have no gist where both 7026 and 7029 are applied, that's why you still observe + selection.

**Comment by sveine** [comment]
> I have no gist where both 7026 and 7029 are applied, that's why you still observe + selection.
OK! I can test if a gist is created

**Comment by johnd0e** [comment]
https://gist.githack.com/johnd0e/eea9cf6cab9070600dae5397fcfe06be/raw/test.html

**Comment by sveine** [comment]
Same as for https://github.com/Leaflet/Leaflet/issues/6896#issuecomment-792987541.
I cleared cache, tried for Safari, Chrome and Edge (for iOS/iPhone). iOS 1.4, iPhone 12

**Comment by johnd0e** [comment]
Could check `L.Browser.touchNative` value?

**Comment by sveine** [comment]
> 
> 
> Could check `L.Browser.touchNative` value?

L.Browser.touchNative = true

**Comment by johnd0e** [comment]
Ok, try one more time.

**Comment by sveine** [comment]
> 
> 
> Ok, try one more time.

![20210309_073204000_iOS](https://user-images.githubusercontent.com/367125/110435048-d28e3080-80b2-11eb-8ddc-cb6dcb85df80.png)

**Comment by johnd0e** [comment]
It seems that I've found the root of issue.
Compare these 2 pages. If I'm right only one of them works right (without selecting controls).

https://gist.githack.com/johnd0e/3ad393c73b12b24af7e947711a87b7a4/raw/test.html

https://gist.githack.com/johnd0e/3ad393c73b12b24af7e947711a87b7a4/raw/test_tap_true.html

**Comment by sveine** [comment]
Good! This page worked: https://gist.githack.com/johnd0e/3ad393c73b12b24af7e947711a87b7a4/raw/test_tap_true.html

**Comment by johnd0e** [comment]
> Good!

Not so good: https://github.com/Leaflet/Leaflet/issues/6872#issuecomment-793763621
