### ISSUE TITLE
Is there a way to force a map to re-render, or to load more tiles in advance?

### ISSUE THREAD

**Issue by michaelbelt** [Leaflet/Leaflet#690]
The topic kinda says it all - is there a way to either force the map to re-render, or to load some tiles in advance?

When the page loads, we sometimes change the size of the map using javascript.  When this happens, we wind up using all of the available tiles that were initially loaded.  Then if you try to scroll the map, you wind up with a big chunk of gray until you scroll MORE than the amount of the size change.   If that doesn't make sense, you can try it yourself in Chrome here:  http://swstage.anchormediaworks.com/  You might have to do FB Connect to see the problem in action.

I considered quickly zooming in (and then zooming right back out) as one solution, but was wondering if there were a more elegant one.

**Comment by mcahornsirup** [comment]
Nice!

**Comment by RayGone** [comment]
Thanks. This is helped me in 2019.. 👍 👍 👍

**Comment by TravnikovRN** [comment]
Doesn't helps to update Control name

**Comment by iamtekson** [comment]
Thanks, Really great idea.

**Comment by jauschalley** [comment]
Thank you! I've seen so many crazy answers for this but this was exactly what I needed. @mourner

**Comment by jp-programmer1** [comment]
This is helped me in 2023 :smile:

**Comment by olivier3lanc** [comment]
> `map.invalidateSize()`

This helped me so much thank you!

**Comment by ecomnazar** [comment]
Just remove <StrictMode>, it's helped me)

**Comment by nickliliakides** [comment]
> map.invalidateSize()

This is still very useful!!!

**Comment by RayGone** [comment]
> This is helped me in 2023 :smile: 

Don't steal my comment! 😂
