### ISSUE TITLE
GeoJson should inherit from Interactive Layer in the documentation

### ISSUE THREAD

**Issue by trygveaa** [Leaflet/Leaflet#6900]
As far as I can see, GeoJson should be documented as inheriting from Interactive Layer. If you create a GeoJson object, it will be interactive by default, and it also supports the interactive option to make it non-interactive.

This also affects the typescript types, but I see that is not maintained in this repo.

The bug template doesn't really fit since this is about the documentation, so I removed it.

**Comment by MarkFalconbridge** [comment]
Looking at the code the options object is passed directly on to the Polygon/Polyline/Marker which all inherit from InteractiveLayer so I agree with @trygveaa the documentation is lacking in this respect.

**Comment by johnd0e** [comment]
@trygveaa Try #7763
