### ISSUE TITLE
Add option to prefer nearest-neighbour filtering beyond maxNativeZoom

### ISSUE THREAD

**Issue by baryluk** [Leaflet/Leaflet#6901]
**Is your feature request related to a problem? Please describe.**

I do use `tileLayer`, with `L.CRS.Simple`. The tiles were generated from huge (approx. 60000 x 60000 px) `png` file and converted to tiles using `gdal2tiles.py` and then to lossless `webp` format using `cwebp` and `GNU parallel`. The max zoom and the zoom level for base tiles is zoom level 8.

I do have a map tiles (standard 256x256 px) that I wish user to zoom in beyond max zoom (that is zoom beyond 1 pixel from map tile mapping to just one pixel on screen). So I did setup `maxZoom` and `maxNativeZoom` appropriately (12, and 8 respectively).

I use the standard renderer (SVG, not canvas), but I think the renderer only really affect vector layers, not raster tiles, as I only see `img` elements in the DOM tree anyway.

However the web browser uses bilinear filtering by default for scaling images. There are two issues with bilinear filtering of base tiles:

1. The pixels on the edge of the tile do not have proper information to interpolate seamlessly with neighbouring tiles. So it is quite easy to spot discontinuity. The same or even worse would show up with bicubic interpolation.

2. The type of tiles I do use actually look better on itself (not just the edge) with nearest neighbour filtering, because they come from the huge screenshot (or set of screenshots) from the game that is mostly pixel art.

**Describe the solution you'd like**

1. I would like to set an option for tileLayer that uses non-standard filtering. A CSS attributes I would like to see used are:

```css
  image-rendering: optimizeSpeed;
  image-rendering: -moz-pixelated;
  image-rendering: -o-pixelated;
  image-rendering: -webkit-optimize-contrast;
  image-rendering: -webkit-pixelated;
  image-rendering: pixelated;
  -ms-interpolation-mode: nearest-neighbor;
```

2. Even better (alternative or as secondary method, which is complementing above) implement bilinear interpolation on the edge of the tile in the leaflet library itself using some pixel manipulation (be sure to do that in linear color space, not sRGB!), so discontinuities are not visible. Because leaflet would only do interpolation on edges and corners taking into account neighbouring tiles edges, the number of sample lookups (less ~1000 pixels out of 65536 pixels, so about 1%), would be small and performance of doing it in JS directly would be completely sufficient. The interpolated edges (or input pixels) could also be cached in custom cache, so they do not need to be recomputed on every pan operation.

**Describe alternatives you've considered**

1. Setting `maxZoom` to be equal to `maxNativeZoom`. Just avoid the problem at the loss of functionality.

2. Using custom CSS:

```css
img.leaflet-tile[src*="tilesdir-webp/8/"]
  image-rendering: optimizeSpeed !important;
  image-rendering: -moz-pixelated !important;
  image-rendering: -o-pixelated !important;
  image-rendering: -webkit-optimize-contrast !important;
  image-rendering: -webkit-pixelated !important;
  image-rendering: pixelated !important;
  -ms-interpolation-mode: nearest-neighbor !important;
}
```

The `src` attribute selector part could be removed, as using nearest-neighbour will still work pretty well if not almost perfect (but not perfect when using fractional zoom levels!) for lower zoom levels. But to be specific I do use this `src` attribute selector, unfortunately it requires knowing URL form and `maxNativeZoom` level ahead of time.

I needed to use `!important`, otherwise the CSS properties are not picked by the proper `img` elements used by leaflet. There probably is some other way do to it tho in CSS.

Almost all browsers do support it in one form or another, and if they don't, fallback to default behaviour (which will happen if the browser simply do not understand any of the above values), is perfectly acceptable. So that requires no extra handling or browser detection in leaflet code.

**Additional context**

Default behaviour:

![maxZoom-bilinear-edge-discontinuity](https://user-images.githubusercontent.com/110322/69136265-73b63980-0ab2-11ea-95fb-968118b6687d.png)

![maxZoom-bilinear-edge-discontinuity-2](https://user-images.githubusercontent.com/110322/69138702-0c4eb880-0ab7-11ea-8920-887e3c117416.png)

Notice visible and distracting discontinuity between base tiles:

Preferred behaviour:

![maxZoom-nearest-neighbour](https://user-images.githubusercontent.com/110322/69136276-7749c080-0ab2-11ea-9cd9-25111be5a829.png)

![maxZoom-nearest-neighbour-2](https://user-images.githubusercontent.com/110322/69138716-11ac0300-0ab7-11ea-97d1-204108aebdf6.png)

Tested in Firefox 68.0.2esr and Chromium 78.0.3904.97.

Using `leaflet` 1.6.0

**Comment by Malvoz** [comment]
Looks like the same feature request as https://github.com/Leaflet/Leaflet/issues/5883.
