### ISSUE TITLE
Building in ubuntu docker container

### ISSUE THREAD

**Issue by ggcaponetto** [Leaflet/Leaflet#6902]
- [ x] I've looked at the [documentation](https://github.com/Leaflet/Leaflet/blob/master/docs/download.md) to make sure i didn't miss any building step
- [x ] I'm sure this is a Leaflet docs issue.

**Steps to reproduce**
- spin up a docker container running ubuntu:latest
- follow the build instuctions

**Expected behavior**
Leaflet distribution files are build in the `dist` folder without errors.

**Current behavior**
Leaflet distribution files are build in the `dist` folder but the process exits with error:
```
ERROR [phantomjs.launcher]: /Leaflet/node_modules/phantomjs-prebuilt/lib/phantom/bin/
phantomjs: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file
 or directory
```

**Environment**
- Leaflet version: 1.6.0
- docker: ubuntu:18.04

**Comment by spmsupun** [comment]
This is nothing to do with leaflet

**Comment by ggcaponetto** [comment]
@spmsupun The Leaflet repository has instructions, which i followed, to build Leaflet from source. There is a hidden dependency (libfontconfig) used by phantomjs that prevents users to build Leaflet on certain linux distributions. In my opinion it should be mentioned in the documentation or README.md. Why do you think this issue is not related to Leaflet?

**Comment by spmsupun** [comment]
This is actually docker related issue, would you mind sharing Dockerfile?
