### ISSUE TITLE
'"contextmenu"' is not assignable to parameter of type '"tileunload" | "tileloadstart" | "tileload"'.

### ISSUE THREAD

**Issue by mrhoran54** [Leaflet/Leaflet#6906]
The error is as reads above.
 I recently upgraded to the latest version of Leaflet, 1.6.0. I never had this issue before using the contextmenu. Here is the code snippet:

this.Map.on('contextmenu', (event: MouseEvent) =>
 {                
this.dropPinLatLong = event["latlng"];
 const content: HTMLElement = this.DomUtil.create('div', 'DropPin');
//content stuff here
 this.MapLayer.RawLayer.bindPopup(content, {
                        closeButton: false,
                        minWidth: 0,
                        maxWidth: 0
                    });
});

The error again:
Argument of type '"contextmenu"' is not assignable to parameter of type '"tileunload" | "tileloadstart" | "tileload"'.

- I believe this is a Leaflet code issue, not an issue with my own code because I have checked over the new documentation and it looks like they did not change the syntax around the context menu.
- I've haven't seen this error documented which is why I figured I would post.
-It could be related to a new environment issue, as I recently upgraded to Angular 8.

Steps to reproduce:
upgrade Leaflet from version 1.3.1 to 1.6.0

Any help is greatly appreciated. Thanks

**Comment by mourner** [comment]
Can you please provide a minimal reproducible live test case (e.g. on JSFiddle), preferably without external dependencies like Angular? This doesn't seem to be an issue on the Leaflet side.

**Comment by mrhoran54** [comment]
thanks for getting back to me! I'll work on that live test case. If I do solve it in the meantime I will post what I did to resolve it.

**Comment by mrhoran54** [comment]
Fix:
1.  npm install @types/leaflet@latest 
2. change code according to new types

So the issue here was the fact that leaflet is a javascript library and because I am using TypeScript when I upgraded leaflet I needed to make sure the types were upgraded as well. In my case I neglected to do upgrade this, not fully understanding how Typescript came in here.

**Comment by kevinleary** [comment]
I'm having the same issue here... recently upgraded to angular 7 on a project and then starting getting the same error above. I `npm i @types/leaflet@latest =` and `npm i @types/leaflet-draw@latest` 

Also just upgraded the project to TS 3.5.3. Could this be part of the issue? 

Also not really sure where I am supposed to upgrade types
