### ISSUE TITLE
Bug on IOS(12-13) - null is not an object (evaluating 't._leaflet_id')

### ISSUE THREAD

**Issue by necheporenko** [Leaflet/Leaflet#6907]
I get this error only on IOS, after any manipulation with the map.

I use the latest versions. 
Leaflet v.1.6.0

Any idea why this is happening and how to solve it?
![a9a611f0-f6aa-45ed-a2bd-f182492055a0](https://user-images.githubusercontent.com/20722449/69342897-2c2bdb00-0c75-11ea-83c7-5940a66a41e6.jpg)

**Comment by mourner** [comment]
It's not clear from the screenshot alone (seems to have something to do with the Fullscreen Control). Can you provide a minimal reproducible live test case?

**Comment by IvanSanchez** [comment]
No more information has been provided, and more than a few weeks have passed. We'll assume this issue is no longer relevant and/or there is no interest to make a better report.

**Comment by Aarbel** [comment]
@necheporenko same issue here.

Did you found a way to fix it ?

**Comment by Aarbel** [comment]
![image](https://user-images.githubusercontent.com/25119847/75490181-f5700a00-59b3-11ea-92cd-4d3485a443be.png)

**Comment by Aarbel** [comment]
Ok i fixed it with removing all fullscreen options for leaflet and upgrading to last versions of leaflet.

Maybe last version of webviews handles Fullscreen with a different API, so it makes the map crash.

Did you fixed it in the same way @necheporenko ?

**Comment by necheporenko** [comment]
> Did you fixed it in the same way @necheporenko ?

No, I just removed the logic which produces this error.
