### ISSUE TITLE
Keyboard issue with Chrome and Firefox in mobile devices with an input element inside L.Control (version 1.6)

### ISSUE THREAD

**Issue by guiveg** [Leaflet/Leaflet#6916]
Hello, I've migrated from Leaflet 1.5.1 to 1.6. I'm using a custom html form with an input element within a Leaflet map control. In the previous version (1.5.1) it was possible to type anything in the input element. However, this is not working with version 1.6 when using an Android device with Chrome or Firefox => the issue is that the virtual keyboard is not showing when clicking the input element (it looks this element does not get the focus)

**Steps to reproduce**
- Create a map control in Leaflet
- Create a div with an input element and assign it to the map control container
- Use an Android device with Chrome or Firefox and click on the input element => the virtual keyboard is not showing

**Expected behavior**

The virtual keyboard should pop up, allowing the user to introduce some text

**Current behavior**

The virtual keyboard does not pop up

**Environment**
- Leaflet version: 1.6
- Browser (with version): Chrome 78.0.3904.108
- OS/Platform (with version): Android 9

**Additional context**

**Minimal example reproducing the issue**
Check this fiddle:
https://next.plnkr.co/edit/8M2c7fGnacCpys2j?preview

**Comment by mmapping** [comment]
Have replicated this, seems to be browser agnostic (same behaviour on mobile Chrome and Firefox) and also affects button elements.

**Comment by Krulvis** [comment]
Confirmed on DuckDuckGo, Lightning on LineageOS. (doesn't work in 1.6 but does work in 1.5.1).

**Comment by johnd0e** [comment]
It appeared that the issue is caused by `tap` handler, which replace native click with simulated one (which seems not handled by browser). 

Solution: apply `tap: false` map option.
