### ISSUE TITLE
wms examples page not work

### ISSUE THREAD

**Issue by gdbd** [Leaflet/Leaflet#6927]
**Steps to reproduce**
- open examples page https://leafletjs.com/examples/wms/wms.html

**Expected behavior**
demos display wms layers on the map

**Current behavior**
demos does not display wms layers on the map

**Environment**
- Leaflet version: 1.5
- Browser (with version): chrome 78, firefox 70
- OS/Platform (with version): manjaro

**Additional context**
seems that used wms services are down

**Minimal example reproducing the issue**
https://leafletjs.com/examples/wms/wms.html

**Comment by IvanSanchez** [comment]
If you can provide the address of a publicly-available WMS server, then we can update the tutorial to use that one.

**Comment by gdbd** [comment]
@IvanSanchez sorry i dont know any available wms server
i am created issue just for note for note that example page not work

**Comment by mahadevans87** [comment]
Hi,
I found a free set of WMS sources here - https://mrdata.usgs.gov/wms.html
Can I go ahead and update the docs and submit a PR?
