### ISSUE TITLE
Problem mixing EPSG4326 WMS layer with tile-based one

### ISSUE THREAD

**Issue by ajsanchez** [Leaflet/Leaflet#693]
I'm trying to create a Map with two layers: a WMS one using L.CRS.EPSG4326 and another, tile-based one. The problem is that the second one, which I guess uses L.CRS.EPSG3857, is shown displaced. Why is the SRS/CRS bound to the Map instead of each layer? Is there a way to fix this, or Leaflet need to be refactored to allow different-CRS layers on a single map?

**Comment by dmitry** [comment]
I've also stuck with the same issue.

Thank you @ajsanchez for the link. It's a hack, but can be used if it's really required to be made.
@PoqueiraWeb have you found any solution?

**Comment by dmitry** [comment]
One more possible solution: http://jsfiddle.net/GpG4G/8/
