### ISSUE TITLE
[Native support] Marker rotate for angle

### ISSUE THREAD

**Issue by borit22** [Leaflet/Leaflet#6932]
**Is your feature request related to a problem? Please describe.**
leafet don't have native support for rotate marker.

**Describe the solution you'd like**
like here https://github.com/bbecquet/Leaflet.RotatedMarker

**Describe alternatives you've considered**
https://github.com/bbecquet/Leaflet.RotatedMarker

**Comment by IvanSanchez** [comment]
If there's a plugin, then there's no immediate need for support in core Leaflet.

**Comment by borit22** [comment]
> If there's a plugin, then there's no immediate need for support in core Leaflet.

plugin may obsolete and don't support new api Leaflet in future

**Comment by justinbeatz** [comment]
Is there a workaround for this? 
I'm using the code from the RotatedMarker in the latest version but is not working as expected.

**Comment by rafaellehmkuhl** [comment]
The mentioned plugin does not work anymore.

**Comment by jonkoops** [comment]
> Plugin may obsolete and don't support new API Leaflet in future.

Feel free to help the author maintain this library or create a new one that can accomplish this with future versions of Leaflet.

**Comment by jonkoops** [comment]
No problem! We can always add a new plugin to our plugin list if that helps.
