### ISSUE TITLE
Map dragging doesn't work for the example on https://leafletjs.com for Firefox 71 on Windows 7

### ISSUE THREAD

**Issue by TobiasWehrum** [Leaflet/Leaflet#6933]
When I open https://leafletjs.com, I cannot move the map by dragging in Firefox 71 on Windows 7. Moving by using the arrow keys works.

In Chrome I can move the map by dragging.

**Comment by mourner** [comment]
Interesting! Can you try out the example locally and see which versions are affected? Is it only 1.6.0, or 1.5.1 too?

**Comment by TobiasWehrum** [comment]
I have made a local copy of https://leafletjs.com/examples/quick-start/example.html and tried it with both https://unpkg.com/leaflet@1.5.1/dist/leaflet.js and https://unpkg.com/leaflet@1.6.0/dist/leaflet.js. Both have the same behaviour described in my opening post: No dragging in Firefox, fully working in Chrome.

**Comment by TobiasWehrum** [comment]
I went back a "little" further:
- 0.7.7 works fine!
- 1.0.1 - same broken behaviour as described in my opening post.

**Comment by adam-knights** [comment]
Dragging works in Firefox 71 on Mac for me, so likely Windows Firefox specific.

**Comment by johnd0e** [comment]
No issues with Firefox 74 + Leaflet 1.6.0 on Windows 10.

**Comment by TobiasWehrum** [comment]
Still doesn't work in with Firefox 82 + the current example on https://leafletjs.com (which might be Leaflet 1.7.1) on Windows 7 for me.

**Comment by TobiasWehrum** [comment]
For what it's worth, with Firefox 86 on Windows 10, the current example on https://leafletjs.com (still 1.7.1, I assume?) works for me.

**Comment by TobiasWehrum** [comment]
@johnd0e Considering that it was working fine on Windows 10 Firefox versions earlier too, it might be a weird Windows 7 FF vs Windows 10 FF thing.

**Comment by johnd0e** [comment]
Sure, feel free to debug that on windows 7, and reopen this issue if you need.
