### ISSUE TITLE
Build from source dependencies warnings (Windows10)

### ISSUE THREAD

**Issue by zipzit** [Leaflet/Leaflet#6934]
- [X] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [X] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [X] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**

Follow instructions for performing a clean build, ref: https://leafletjs.com/download.html   Scroll down to: 

> Building Leaflet from the Source
> 
> Leaflet build system is powered by the Node.js platform, which installs easily and works well across all major platforms. Here are the steps to set it up:
> 
> Download and install Node
> Run the following command in the command line:
> $ `npm install`
> Now that you have everything installed, run $ `npm run build` inside the Leaflet directory. This will combine and compress the Leaflet source files, saving the build to the dist folder.

**Expected behavior**

I'm expecting a `DIST` build from source

**Current behavior**

```
$ npm install
npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, fl                             atted is its successor.
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and                              will break at some point. Do not use it, and update to graceful-fs@4.x.

> phantomjs-prebuilt@2.1.16 install C:\temp\Leaflet\node_modules\phantomjs-prebuilt
> node install.js

Considering PhantomJS found at C:\Program Files\phantomjs\2_1_1\bin\phantomjs.EXE
Found PhantomJS at C:\Program Files\phantomjs\2_1_1\bin\phantomjs.EXE ...verifying
Writing location.js file
PhantomJS is already installed on PATH at C:\Program Files\phantomjs\2_1_1\bin\phantomjs.EXE
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN rollup-plugin-git-version@0.2.1 requires a peer of rollup@^0.41.4 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\karma-rollup-preprocessor\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}                             )
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}                             )

added 578 packages from 1611 contributors and audited 3122 packages in 257.444s
found 7 vulnerabilities (1 moderate, 5 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

(my computer) MINGW64 /c/temp/Leaflet (master)
$ npm audit fix
npm WARN rollup-plugin-git-version@0.2.1 requires a peer of rollup@^0.41.4 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}                             )
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\karma-rollup-preprocessor\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}                             )

up to date in 17.589s
fixed 0 of 7 vulnerabilities in 3122 scanned packages
  7 vulnerabilities required manual review and could not be updated



```
**Environment**
- Leaflet version:  `git clone git@github.com:Leaflet/Leaflet.git`    12/9/2019 3:30PM PST
- Browser (with version):  N/A
- OS/Platform (with version):  Windows 10 Home, ver. 1909, installed on 7/19/2019, OS Build: 18363.476

**Additional context**
$ npm --version
6.10.3

**Minimal example reproducing the issue**

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code
 
And just to be clear... the build process seems to run okay, but those npm install warnings always make me a bit crazy.  Certainly the ones that are included as dev dependencies in package.json.

Note, not to be ungrateful... many thanks to all of those who actively support this repo.

**Comment by ggcaponetto** [comment]
The installation process of the ``phantom-prebuild`` module fails because you already have an installed version in ``C:\Program Files\phantomjs\2_1_1\bin\phantomjs.EXE``, i guess. I would suggest you to delete the previously installed version of phantomjs and try again. If you are not getting support here, post this issue in [https://github.com/Medium/phantomjs](https://github.com/Medium/phantomjs). Good luck!

**Comment by zipzit** [comment]
Apologies.. I misunderstood... I was thinking the issue was related to wrong version of     "phantomjs-prebuilt": "^2.1.16", in package.json

Thank you for the followup.  Please close this issue.  Many thanks to the Leaflet team.

**Comment by zipzit** [comment]
Issue related to external phantomjs library installed on users drive.  I consider issue closed.  Thanks to ggcaponetto for the constructive feedback.
