### ISSUE TITLE
not all tiles loaded until resize window

### ISSUE THREAD

**Issue by ludinov-stuzo** [Leaflet/Leaflet#694]
all tiles loading properly only after window resize or manually trigger ._onResize()

**Comment by shankari** [comment]
Here's a screenshot of the problem (generated by @yw374cornell on one of the test phones).
![broken_tile_load](https://cloud.githubusercontent.com/assets/2423263/16902018/eb9084d2-4c07-11e6-9d28-a0c5b167b831.jpg)

**Comment by shankari** [comment]
@yw374cornell also reports that the `Reload Tiles` workaround works!
Now I just need to figure out how to make it work automatically.
That will happen post release `0.0.12`.

**Comment by mrigankpawagi** [comment]
> Resizing on windows resize works correctly, see this example: http://leaflet.cloudmade.com/debug/map/map-mobile.html
> 
> If you resize the map container manually, you need to call `map.invalidateSize()`.

You made my day. My map just wouldn't work right. None of the functions including ```setView```, ```flyTo```, ```panTo```, ```fitbounds``` would work properly. It would work sometimes, and sometimes not. I just couldn't understand **when it *did***. Then I saw it works when I resize the window, and after hours of useless R&D reached this thread.

Thanks a lot.

**Comment by gorhill** [comment]
I get the issue I described above without uBO, so not a uBO issue.
