### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by mo-ian-watkins** [Leaflet/Leaflet#6940]
[This package](https://www.jsdelivr.com/package/npm/leaflet) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by mondeja** [comment]
This issue is incorrect and should be closed because `package.json` [has the `main` field correctly defined](https://github.com/Leaflet/Leaflet/blob/master/package.json#L33).
