### ISSUE TITLE
Get image URL for imageOverlay

### ISSUE THREAD

**Issue by meersonv** [Leaflet/Leaflet#6943]
Is it possible?

**Comment by IvanSanchez** [comment]
https://leafletjs.com/reference-1.6.0.html#imageoverlay-getelement then https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/src

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by meersonv** [comment]
> https://leafletjs.com/reference-1.6.0.html#imageoverlay-getelement then https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/src

Thank you for the replay. The imageOverlay object should be already added to the map, otherwise getElement returns "undefined'.
