### ISSUE TITLE
Popup on top of static buttons

### ISSUE THREAD

**Issue by stigc** [Leaflet/Leaflet#6947]
Especially on mobile devices we need the ability to let popups render above a custom button/control layer. There can be mimic with some tricks (https://jsbin.com/niwakojubo/edit?html,output) but this should be native supported for better performance.

**Comment by elmatou** [comment]
Hi,
your example would work if you used a `L.Control` https://leafletjs.com/reference-1.6.0.html#control

of course if you want a specific position (not in corners) you'll need to extend the class and tweak `addTo` property.

**Comment by stigc** [comment]
Marker popups will render under the Controls layer, right?  We need popups to always be on top.

**Comment by anatel** [comment]
@stigc Did you eventually manage to achieve this behavior?
I also need it..

**Comment by stigc** [comment]
Yes, with the link from the post.

**Comment by johnd0e** [comment]
I'm afraid that we can't do much for this issue.
