### ISSUE TITLE
Setting custom long press touch duration (now fixed to 1 second)

### ISSUE THREAD

**Issue by TomazicM** [Leaflet/Leaflet#6959]
Currently long press touch duration ( firing `contextmenu` event on touch devices) is fixed to 1 second.

It would be very useful to be able to set the duration of long press touch duration, either by some touch interaction option like `longTouchDuration` or at least by some internal value in tape handler object (like `_longTouchDuration: 1000`) that could be easily changed by `L.Map.Tap.include`.

**Comment by elmatou** [comment]
I may be wrong, but it seems to me that this is a browser specific behavior.
and Leaflet mouse events just inherit from browser mouse events.

**Comment by johnd0e** [comment]
Well, currently when [tap handler](https://leafletjs.com/reference-1.6.0.html#map-tap) is enabled, we have this code:
https://github.com/Leaflet/Leaflet/blob/0d06c4256f4312a7122c23626c8bd36e14269d01/src/map/handler/Map.Tap.js#L62-L69

But in fact, currently we need this part for iOS only (see #6980), as other browsers successfully fire `contextmenu` on touch without any handlers.

And 1s is too big delay, as stadard is close to 0.5.
