### ISSUE TITLE
ES6 without importing Popup closePopup is not a function

### ISSUE THREAD

**Issue by pke** [Leaflet/Leaflet#6961]
**Steps to reproduce**

import the following packages:
```
import { map } from "leaflet/src/map"
import { icon } from "leaflet/src/layer/marker/Icon"
import { Marker } from "leaflet/src/layer/marker/Marker"
import { tileLayer } from "leaflet/src/layer/tile/TileLayer"
import "leaflet/src/layer/vector/Renderer.getRenderer"
```
With those imports one can render a marker on the map but not drag it.

**Expected behavior**

Clicking and dragging a marker works and does not crash.

**Current behavior**

A crash occurs cause it assumes a certain member function is present.

```
Marker.Drag.js:111 Uncaught TypeError: this._marker.closePopup is not a function
    at NewClass._onDragStart (Marker.Drag.js:111)
    at NewClass.fire (Events.js:190)
    at NewClass._onMove (Draggable.js:157)
    at HTMLDocument.handler (DomEvent.js:79)
```

**Environment**
- Leaflet version: 1.6.0

It would be better if the different classes would not depend on each other that much. I know it has historical reasons, but the whole idea of using ES6 import is to not import code one does not use.

The library would benefit from a cleaner separation of concerns/dependency injection.

In that particular case, couldn't the popup register a move listener on the marker itself and then close itself when this listener is called?

Are there any ES6 enabled specs, I could not find any. When all the specs are based on `window.L` then these kind of bug are hard to find.

**Comment by IvanSanchez** [comment]
> In that particular case, couldn't the popup register a move listener on the marker itself and then close itself when this listener is called?

That sounds like a sensible approach. Doing something like `this._marker.closePopup && this._marker.closePopup()` would work as well. Either way, there'll be a bit of coupling between the popup logic and the dragging logic :-/

> Are there any ES6 enabled specs, I could not find any. When all the specs are based on `window.L` then these kind of bug are hard to find.

There are none AFAIK; I don't how how difficult it would be to extend the test system to cover those cases as well.

**Comment by pke** [comment]
@IvanSanchez I also had the idea of simply protecting the call but I prefer the listener approach as a much cleaner, separation of concern approach. However for the time being we can go with this #6962 fix.
