### ISSUE TITLE
Zoom modifying tileSize not Scale

### ISSUE THREAD

**Issue by CallMarl** [Leaflet/Leaflet#6963]
Hello I'm very beginner in Javascript then also in leaflet library.

I would like to know if there is plugin, or something else, able to modify tileSize when zooming?

In my case y need à square map with spécifique number of squares. Then if I zoom out the size of square gone a be smaller. I'm actually using GridLayer.

Thank you.

**Comment by IvanSanchez** [comment]
Use `minNativeZoom`/`maxNativeZoom`.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by IvanSanchez** [comment]
See also https://gis.stackexchange.com/questions/332823/scaling-tiles-for-missing-zoom-levels-in-leaflet
