### ISSUE TITLE
Deprecated use of _flat, please use L.LineUtil.isFlat instead

### ISSUE THREAD

**Issue by dipika21** [Leaflet/Leaflet#6965]
Building code from Jenkins and facing below issue:

PhantomJS 2.1.1 (Linux 0.0.0) GridLayer min/maxNativeZoom option calls createTile() with minNativeZoom when map zoom is smaller FAILED
Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
WARN: 'Deprecated use of _flat, please use L.LineUtil.isFlat instead.'
WARN: 'Deprecated use of _flat, please use L.LineUtil.isFlat instead.'
PhantomJS 2.1.1 (Linux 0.0.0): Executed 672 of 683 (1 FAILED) (skipped 11) (16.624 secs / 13.984 secs)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leaflet@1.6.0 test-nolint: `karma start ./spec/karma.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leaflet@1.6.0 test-nolint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by IvanSanchez** [comment]
Those warnings are there because of two checks for proper backwards compatibility (see https://github.com/Leaflet/Leaflet/blob/17a1b6105bfd4d70959fcb865e7c495c3ead85d3/spec/suites/layer/vector/PolylineGeometrySpec.js#L61). Therefore, behaviour as expected and not a bug.
