### ISSUE TITLE
ImageOverlay causes lagging and slow map before switching layers

### ISSUE THREAD

**Issue by hopefeda** [Leaflet/Leaflet#6968]
**Steps to reproduce**
- Create a map
- Add multiple large image overlays as layers. In the example, I used (11042x6138, 7.5 MB, jpeg)
- Pan and zoom around

**Expected behavior**
The map should pan and zoom without lagging without the need to switch layers from the beginning

**Current behavior**
The map is lagging and slow. This however can be fixed (weird enough) by switching back and forth once between layers. In fact, simply turning an overlay layer on/off also seems to be sufficient.

**Environment**
- Leaflet version: 1.6.0
- Browser (with version): Chrome 79.0.3945.117 (Official Build) (64-bit)
- OS/Platform (with version): Linux Ubuntu 79.0.3945.117 (Official Build) (64-bit)

**Additional context**
I made a dirty fix in which I use JQuery to toggle a layer on/off in the beginning and for now this seems to do the trick.

**Minimal example reproducing the issue**
https://codepen.io/hope_feda/pen/bGNjxNJ

**Edit 1**
This doesn't seem to be an issue on Firefox 71.0 (64-bit) on the same OS

**Comment by ghybs** [comment]
Hi,

Thanks for the detailed report including live example!

It looks like you initially add all your base layers to your map, hence overloading browser memory.
The fact that using the Layers Control (either manually or programmatically) restores usability just shows that it properly removes the layer that is not selected.

So you should be good by adding to your map only the Layer that you want to be initially visible.

BTW you could also consider reworking your Image Overlay as a Tile Layer, as 7.5MB can take long to load.

**Comment by charlieforward9** [comment]
I would love to see an example of how to load an image with ImageOverlay vs TileLayer. Specificially when it needs to be within a specific bounds. The performance is of most interest to me.j
