### ISSUE TITLE
Markers broken for Chrome on Android

### ISSUE THREAD

**Issue by shgysk8zer0** [Leaflet/Leaflet#6972]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- Visit page with map & markers
- Click on a marker to open popup

**Expected behavior**

Marker should open popup
**Current behavior**

It doesn't open popup. If already opened by other means, "x" does not close.

Opening / closing via JavaScript does work.

**Environment**
- Leaflet version: 1.6.0
- Browser (with version): Chrome 79.0.3945.116
- OS/Platform (with version): Android 10

**Additional context**

- Works in all other browsers (including Desktop Chrome and Firefox for Android).
- Worked in Leafletjs 1.5.1 (changing version of module src still fixes, all else being the same)
- Possibly an issue when used inside of a ShadowDOM

Using custom element / web component built using `https://unpkg.com/leaflet@1.6.0/dist/leaflet-src.esm.js`.

**Minimal example reproducing the issue**
[CodePen](https://codepen.io/shgysk8zer0/details/wvBEQxj)
```
<!-- This is as simple as I can make it to still use in the same context -->
<script type="module">
	import HTMLOpenStreetMapElement from 'https://cdn.kernvalley.us/components/open-street-map.js';
	customElements.define(HTMLOpenStreetMapElement.tagName, HTMLOpenStreetMapElement);
</script>
<open-street-map center="35.755105,-118.424974" zoom="16">		
	<map-marker longitude="-118.424414" latitude="35.755369" slot="markers" title="Whiskey Flat Days Info Booth">
		<img src="https://cdn.kernvalley.us/img/octicons/info.svg" slot="icon" width="32" height="32">
		<div slot="popup">Whiskey Flat Days Info Booth</div>
	</map-marker>		
</open-street-map>
```
Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.

- [x] this example is as simple as possible
- [ ] this example does not rely on any third party code

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.

**Comment by shgysk8zer0** [comment]
Custom elements are not a framework.

Here. I took out all possible abstractions and left only fixed code to create a map and add a marker with a pop-up. See [pen](https://codepen.io/shgysk8zer0/full/wvBENgM). All 35 lines of JS are in there with nothing other than the a Leaflet module external.

Same thing happens. Click handlers just don't work for Chrome on Android from inside a shadow DOM.

**Comment by shgysk8zer0** [comment]
@IvanSanchez Updated issue with no external JS (other than Leaflet module).

This is pure, vanilla JS.

**Comment by IvanSanchez** [comment]
Thanks for updating the codepen to vanilla JS - saying "shadow DOM" instead of "custom elements" makes things easier to debug. Please be aware that, from our point of view, things like Polymer, React and Web Components look pretty much like the same frameworky thing.

But now this looks as a duplicate of #6705.
