### ISSUE TITLE
Problem with map move 

### ISSUE THREAD

**Issue by McSquizzi** [Leaflet/Leaflet#6973]
Steps to reproduce
 1. Open desktop Google Chrome wiht dev tools and turn on device format
 2. Try to move map

Expected
 Map move by dragging

Actual 
 Map don't move by dragging

Environment 

leaflet 1.6.0

Bug not reproduced in 1.5.1. 
Also I found reason of this problem - pointer event turn off for any browser on webkit (line 1905 in leaflet-src.js)

**Comment by stigc** [comment]
I have seen the same problem on my mobile phone (without dev tools that is), dragged didn't respond, unfortunately cannot reproduce it.

**Comment by McSquizzi** [comment]
As I saw mobile chrome work with mouse events but not pointer
