### ISSUE TITLE
SVGOverlay seems to use different coordinates than ImageOverlay

### ISSUE THREAD

**Issue by DOkgQdGE4V5naGuL** [Leaflet/Leaflet#6974]
Hello,

Attempt to put an SVGOverlay onto a map results in SVG appearing below the map (not in z-index but in being placed at a lower y-coordinate). I'm not able to explain why the svg overlay and the image overlay are using different coordinate systems.

You can try this code out to duplicate:

var bounds = [[0, 0], [1000, 1421]];
var map = L.map( "map", {
minZoom: 0.5,
maxZoom: 5,
zoomSnap: 0.05,
maxBounds: bounds,
crs: L.CRS.Simple,
attributionControl: false
} );

var image = L.imageOverlay( "https://i.imgur.com/wxVyhEi.jpg", bounds ).addTo( map );

var svgElement = document.createElementNS( "http://www.w3.org/2000/svg", "svg" );
svgElement.setAttribute( "xmlns", "http://www.w3.org/2000/svg" );
svgElement.setAttribute( "viewBox", "0 0 1152 1024" );
svgElement.setAttribute( "width", 1152 );
svgElement.setAttribute( "height", 1024 );
svgElement.innerHTML = '<title></title><g></g><path fill="#000" d="M160 704q66 0 113 47t47 113-47 113-113 47-113-47-47-113 47-113 113-47zM576 320q-66 0-113-47t-47-113 47-113 113-47 113 47 47 113-47 113-113 47zM512 496q0 66-47 113t-113 47-113-47-47-113 47-113 113-47 113 47 47 113zM576 704q66 0 113 47t47 113-47 113-113 47-113-47-47-113 47-113 113-47zM992 704q66 0 113 47t47 113-47 113-113 47-113-47-47-113 47-113 113-47zM960 496q0 66-47 113t-113 47-113-47-47-113 47-113 113-47 113 47 47 113z"></path></svg>';
var svg = L.svgOverlay( svgElement, [[0, 0], [1024,1152]] ).addTo( map );

// fit map
map.fitBounds( bounds );

Complete html that loads just leaflet is here: https://pastebin.com/29YeVN3S

Github doesn't seem to link the whole html file being posted. The code tags are broken, seems like.

Thanks!

**Comment by DOkgQdGE4V5naGuL** [comment]
Inspecting the output in chrome shows the following style is applied to the svg:
style="transform: translate3d(-381px, -732px, 0px); width: 1629px; height: 1448px;"

**Comment by IvanSanchez** [comment]
If I change the `bounds` in your example to be the same for the `ImageOverlay` and the `SVGOverlay`, then both of them overlap in the page:

![imagen](https://user-images.githubusercontent.com/1125786/72734298-b3c09800-3b99-11ea-9170-3b2769074355.png)
![imagen](https://user-images.githubusercontent.com/1125786/72734326-c20eb400-3b99-11ea-9cce-245d1fe6c0b9.png)

If the `ImageOverlay` has bounds `[[0, 0], [1000, 1421]]` and the SVGOverlay has bounds `[[0, 0], [1024,1152]]`, it's no wonder why they don't fit. I'm closing this bug unless another reproducible example *with the same bounding boxes* is provided.

> Why apply any transforms at all?

To offset the overlays from the pane's origin pixel. See the tutorials about creating your own layers for an explanation of that concept.
