### ISSUE TITLE
Can't apply EPSG:2169 with Leaflet

### ISSUE THREAD

**Issue by jcb81** [Leaflet/Leaflet#6979]
Hello all,

I'm trying to use Leaflet with a specific projection EPSG:2169 (Luref, or Luxembourg). I saw that if I don't use a "standard" projection like WGS84, I have to use Proj4Leaflet and reference it to the map.

That's what I did for now :

```
this.crs = new L.Proj.CRS('EPSG:2169',
'+proj=tmerc +lat_0=49.83333333333334 +lon_0=6.166666666666667 +k=1 +x_0=80000 +y_0=100000 +ellps=intl +towgs84=-189.681,18.3463,-42.7695,-0.33746,-3.09264,2.53861,0.4598 +units=m +no_defs');

this.map = L.map('map', {
  center: [ 74000, 96000 ],
  zoom: 3,
  crs: this.crs,
});
```

When I load the page with the map, the console gives me these errors :

```
Cannot read property '3' of undefined
Cannot read property 'x' of undefined
```

After some Googling, I found that I have to define "resolutions" option. I don't know exactly how it is used, but I took from a sample and here is now how looks the CRS :

```
this.crs = new L.Proj.CRS('EPSG:2169',
'+proj=tmerc +lat_0=49.83333333333334 +lon_0=6.166666666666667 +k=1 +x_0=80000 +y_0=100000 +ellps=intl +towgs84=-189.681,18.3463,-42.7695,-0.33746,-3.09264,2.53861,0.4598 +units=m +no_defs',
{
  resolutions: [8192, 4096, 2048, 1024, 512, 256, 128]
});
```

Now when the map is loaded, I have this error in console :

`TypeError: coordinates must be finite numbers`

And now I don't know what to do next. Anyone here already had this kind of issue ? Maybe with another projection ?

I already asked on StackOverflow and github of Proj4Leaflet, but no answer, so I hope to have more chance here :-D

Many thanks in advance.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
