### ISSUE TITLE
Marker Bug

### ISSUE THREAD

**Issue by Chazza** [Leaflet/Leaflet#6983]
**Steps to reproduce**
- Use preloaded data to create markers.
- Attempt to zoom in.
- ...

**Expected behavior**
Markers are scattered as they should.

**Current behavior**
Bugs out, they stay static in the screen.

**Environment**
- Leaflet version: v1.6.0
- Browser (with version): Brave (Chrome) - Latest
- OS/Platform (with version): Windows 10

**Minimal example reproducing the issue**
Please see a GIF at https://i.imgur.com/oj9rYKe.gifv

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?

**Comment by IvanSanchez** [comment]
No more information has been provided, and more than a few weeks have passed. We'll assume this issue is no longer relevant and/or there is no interest to make a better report.
