### ISSUE TITLE
How to set Max Zoom and Min Zoom that works with gestures [trackpad] as well?

### ISSUE THREAD

**Issue by shalawfatah** [Leaflet/Leaflet#6984]
I set the min and max zoom and it works perfectly when you set the zoomControl to true, but I can still zoom in and out beyond the determined numbers when I'm using my trackpad. Why? and How to fix it? Thanks. 
Here is my code.
https://codepen.io/shalaw1889/pen/ExaJEJb?editors=1010
Best,

**Comment by IvanSanchez** [comment]
We don't care about 0.7.x anymore.
