### ISSUE TITLE
the dynamically created array problem

### ISSUE THREAD

**Issue by hako2008** [Leaflet/Leaflet#6987]
I congratulate you for this amazing tool,
but i have to inform you about this serious bug:
when you create any object from a dynamically created array his bounds always being not valid.
and shows **Uncaught Error: Bounds are not valid** when you trying to fitBounds!!
give you example:
`var latlngs = [
            [45.51, -122.68],
            [37.77, -122.43],
            [34.04, -118.2]
        ];

var polyline = new L.Polyline([], {
            color: 'red',
            weight: 3,
            opacity: 0.5,
            smoothFactor: 1
        });

polyline.setLatLngs(latlngs);
polyline.addTo(mymap);
mymap.fitBounds(polyline.getBounds());`

this works just fine.
but when we try this:

`var latlngs = [
            [45.51, -122.68],
            [37.77, -122.43],
            [34.04, -118.2]
        ];

var polyline = new L.Polyline([], {
            color: 'red',
            weight: 3,
            opacity: 0.5,
            smoothFactor: 1
        });
positionsArray = jQuery.parseJSON(response);
$.each(positionsArray['Body'], function( index, value ) {
	latlngs.push(new Array(value['latitude'], value['longitude']));
	/*
		i have tried even
		latlngs.push([value['latitude'], value['longitude']]);
	*/
});
polyline.setLatLngs(latlngs);
polyline.addTo(mymap);
mymap.fitBounds(polyline.getBounds());`

gives you Uncaught Error: Bounds are not valid.

**Comment by IvanSanchez** [comment]
That's a race condition, not a bug. Think about when the call to `setLatLngs()` happens compared tothe calls to `push()`.

**Comment by hako2008** [comment]
i did not understand, how i supposed to do if i want to fit the bounds of my map when the coordinates aren't preknown!! like my example

**Comment by hako2008** [comment]
hi i managed to do it like this

```
bounds = L.latLngBounds();
var polyline = new L.Polyline([], {
            color: 'red',
            weight: 3,
            opacity: 0.5,
            smoothFactor: 1
        });
positionsArray = jQuery.parseJSON(response);
                $.each(positionsArray['Body'], function( index, value ) {
                    
                    polyline.addLatLng(new Array(value['latitude'], value['longitude']));
                    bounds.extend([value['latitude'], value['longitude']],[value['latitude'], value['longitude']]);
                    mymap.fitBounds(bounds);
                    
                });
polylines.push(polyline.addTo(mymap));
```
but still i didn't understand why i have this problem in first place!!!
the weird thing that if i log inside the loop i get valid bounds:
`console.log(bounds.isValid());`
but outside the loop it gives me false (not valid bounds).
