### ISSUE TITLE
Different controls size after update 1.5.1 -> 1.6.0

### ISSUE THREAD

**Issue by Azbesciak** [Leaflet/Leaflet#6988]
Hi, I have noticed that controls are different in size; also it comes from lack of `leaflet-touch` class on map, which was present in previous version - always as I assume.

This change is not documented in doc, also those controls now (map button with size 25 px? - padding is = 18px for icon?) are little bit too small IMO.

**Comment by johnd0e** [comment]
See and vote for #6977, #6978
