### ISSUE TITLE
formatNum doesn't round correctly

### ISSUE THREAD

**Issue by jscheffner** [Leaflet/Leaflet#6990]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
run `L.Util.formatNum(13.714814633131029, 15)`

**Expected behavior**
Since the number already has 15 decimal points I would expect it to stay the same.

**Current behavior**
It returns 13.714814633131027

**Environment**
- Leaflet version: 1.6.0
- Browser (with version): Chrome but verified it in Karma
- OS/Platform (with version): OSX Mojave

**Additional context**

**Minimal example reproducing the issue**

https://next.plnkr.co/edit/p8zxeYBVQiz0v0FH

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by IvanSanchez** [comment]
Errors from the 15th decimal on are within the expected precision of [IEEE 64-bit floating point numbers](https://en.wikipedia.org/wiki/Double-precision_floating-point_format). Won't fix.

See also https://github.com/Leaflet/Leaflet/issues/6668 and related.
