### ISSUE TITLE
Property '_getIconUrl' does not exist on type 'Default' (TypeScript)

### ISSUE THREAD

**Issue by geopic** [Leaflet/Leaflet#6991]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- Install `typescript` and create a new .ts file. In it, write the following:
- `import { Icon } from 'leaflet'`
- `delete Icon.Default.prototype._getIconUrl;`
- An error should appear during compilation with the message in this issue's title.

**Expected behavior**
`_getIconUrl` to be defined in the class `Default` in `index.d.ts`.

**Current behavior**
It isn't defined, therefore the message comes up. The way I've remedied this is to add `_getIconUrl?: string;` to the `Default` class on line 1843 but this needs fixing for everybody.

**Environment**
- Leaflet version: 1.6.0
- Browser (with version): N/A
- OS/Platform (with version): Arch Linux (5.5.2-arch1-1)

**Additional context**

This issue arose from following the code example to fix a bug in `vue2-leaflet`. URL to the relevant part of the documentation: https://vue2-leaflet.netlify.com/quickstart/#marker-icons-are-missing.

**Minimal example reproducing the issue**

N/A (I cannot reproduce the issue on JSFiddle or other sites, it involves the type declaration file).

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.

**Comment by geopic** [comment]
For any future viewers I checked and it's @types/leaflet.

**Comment by rhea-sys** [comment]
Thanks a lot for the remedy! @geopic
