### ISSUE TITLE
Draw Tools Remove Hooks Dragging Enable When clicking on rectangle and then circle without drawing

### ISSUE THREAD

**Issue by nirdeshmmi** [Leaflet/Leaflet#6992]
- [ ] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [ ] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [ ] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- step 1 : Click on Rectangle draw tool
- step 2: Click on Circle draw tool
-step 3: Draw on map
- ...

**Expected behavior**
Circle with expected radius should draw

**Current behavior**
Map keeps on dragging and circle is not drawn properly

**Environment**
- Leaflet version: 1.6
- Browser (with version): Chrome
- OS/Platform (with version):Windows

**Additional context**
I have already resolved this issue by modifying leaflet draw.js by changing remove hooks functionality and calling draggable as true at created event.

**Minimal example reproducing the issue**

Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

**Comment by IvanSanchez** [comment]
This is the bug tracker for Leaflet, not for Leaflet.draw.
