### ISSUE TITLE
Tiles disappear when zooming using Proj4Leaflet

### ISSUE THREAD

**Issue by Adrianod** [Leaflet/Leaflet#6994]
- [✔️] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [✔️] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [✔️] I've searched through the issues to make sure it's not yet reported

I've opened this bug in the Proj4Leaflet repo earlier but with no feedback so I'm trying here. Feel free to close this if this is wrong.

I have encountered a bug using the basic WMTS-example from https://github.com/kartena/Proj4Leaflet/tree/master/examples/wmts

**Steps to reproduce**
- Open https://tiles.calazoffice.biz/bug/ in a large browser window
- Zoom out one zoom level, then zoom in again

**Expected behavior**
Map tiles should appear as usual.

**Current behavior**
Tiles disappear completely, see video of bug: https://www.youtube.com/watch?v=AerPmtvXXXE

**Environment**
- Leaflet version: 1.6
- Browser (with version): All major browsers, Chrome 79, Safari 13, Firefox 73
- OS/Platform (with version): MacOS 10.14.6

**Additional context**
Inspecting the leaflet-tile-container-element after the tiles have disappeared it's styled as `translate3d(1.89185e+20px, 9.21292e+23px, 0px)`, which seems abnormal compared to when tiles appear as normal.

The bug does not seem to manifest itself using a smaller browser window. No error appears in the javascript console.

**Minimal example reproducing the issue**
https://tiles.calazoffice.biz/bug/

- [✔️] this example is as simple as possible
- [well, Proj4Leaflet] this example does not rely on any third party code

**Comment by IvanSanchez** [comment]
Damn, I clearly remember the addition of `transform3DLimit` at https://github.com/Leaflet/Leaflet/pull/3830 to prevent this specific problem.

On zoom end, the `moveend` event should fire, and the pixel origin reset should trigger... I wonder if there's something preventing that pixel origin reset, or if there's something in proj4Leaflet that is messing up the calculations of the pixel origin *after* the reset happens.

**Comment by daeehamid** [comment]
I've the same problem!
how can i fix this ?!

**Comment by daeehamid** [comment]
@Adrianod 
I found the solution
change your tilelayer.
for example change it to :
`//{s}.tile.osm.org/{z}/{x}/{y}.png`

**Comment by perliedman** [comment]
I had a look at this, and since the original example links to the minified version of Leaflet's source, I tried to recreate it on codesandbox: https://codesandbox.io/s/priceless-wildflower-uct8x?fontsize=14&hidenavigation=1&theme=dark

Weird thing is, I can no longer reproduce the issue altough it should be the same code.

@Adrianod could it be that you are using old versions of Proj4Leaflet and/or Proj4js? I lazily just chose latest versions of everything in the example above.

**Comment by Adrianod** [comment]
@perliedman I grabbed the latest proj4js and that seems to have solved it! Thanks!
