### ISSUE TITLE
Plugin TileLayer.Zoomify not working

### ISSUE THREAD

**Issue by jaelzamora** [Leaflet/Leaflet#7000]
Hi, I was using the TileLayer.Zoomify with an old leaflet version in my page. I have just updated leaflet to 1.6 and the plugin doesn't work anymore. This plugin has not been updated for 7 years but, my app's errors are caused by some methods that aren't in Leaflet 1.6.

**Steps to reproduce the behavior:**
- Use zoomify in Leaflet 1.6

**Expected behavior**
Zoomify tiles 

**Current behavior**
![Captura](https://user-images.githubusercontent.com/48295367/74829966-6fe4be00-5312-11ea-8102-87632583f70b.PNG)

**Environment**
- Leaflet version: 1.6
- Browser (with version): Chrome 80.0.3987.116
- OS/Platform (with version): Windows 10

**Comment by IvanSanchez** [comment]
This bug tracker is for the Leaflet core only - we don't handle this kind of compatibility issues.

And one of the forks [works for me out of the box](https://plnkr.co/edit/uMEso1TDX0c41zLF0qDV?p=preview). So consider sending a PR to change the link for this plugin.
