### ISSUE TITLE
watch coordinates chages via `watch` directive in vue.js creates memory leak 

### ISSUE THREAD

**Issue by Makapashev** [Leaflet/Leaflet#7005]
I'd like to change coordinates on by changing the app state, now i alredy have over 50k objects on the map, and when i enable `watch` directive in map component, using memory is commig up to over 1GB, but when i don't use the `watch` method, page uses 220Mb of memory. Do you have any solutions on how to solve this problem?

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.
