### ISSUE TITLE
Marker drifts if setLatLng() is called during a zoom animation

### ISSUE THREAD

**Issue by ChrisLowe-Takor** [Leaflet/Leaflet#7017]
Example: [jsfiddle](http://jsfiddle.net/cwad8p4m/1/)

**Steps to reproduce**
 - Add a marker with a custom icon (including iconSize and iconAnchor)
 - Update the markers position with `setLatLng` in an interval

**Expected behavior**
 - While zooming i'd expect the marker to maintain it's geographical position

**Current behaviour**
 - The marker drifts along it's screen position (similar to how a custom icon without setting an iconAnchor will drift).  It should be pretty apparent when you scoll wheel zoom in that fiddle.

**Additional context**
I'm writing a satellite overlay where the markers position changes rapidly and it needs a custom icon.

**Comment by ChrisLowe-Takor** [comment]
I figured a workaround.  Listen to the `zoomstart` and `zoomend` events and don't update the markers latlng during that period.  [fiddle](http://jsfiddle.net/8dybzc40/)

**Comment by IvanSanchez** [comment]
Interesting bug. I'm not sure if it can be even be fixed properly with the current code architecture. My bet is that the initial screen position for the zoom animation will stay in place.

**Comment by ChrisLowe-Takor** [comment]
> Interesting bug. I'm not sure if it can be even be fixed properly with the current code architecture. My bet is that the initial screen position for the zoom animation will stay in place.

That's a much more accurate title. Given that;
 - it's a pretty specific use case
 - there is a reasonable workaround and
 - it'll take architecture changes to fix
 
I'm happy with closing this.

**Comment by johnd0e** [comment]
Similar issues: #5181, #5505
