### ISSUE TITLE
No list of backwards-incompatible API changes (UPGRADING)

### ISSUE THREAD

**Issue by Chealer** [Leaflet/Leaflet#7031]
**Is your feature request related to a problem? Please describe.**
Our custom website is using Leaflet 0.7.7. We want to update Leaflet to the latest version, but I cannot find a list of backwards-incompatible changes to watch for. The best I found is [CHANGELOG.md](https://github.com/Leaflet/Leaflet/blob/master/CHANGELOG.md), which - for version 1.0-beta1 - lists "Other breaking API changes" (and it is not clear what breaking API changes that version brings other than those listed in "Other breaking API changes"). Unfortunately this seems to be the only version which contains such information.

**Describe the solution you'd like**
A "UPGRADING" document focused on breaking API changes would be best.

**Describe alternatives you've considered**
It would also be possible to have a "Backwards-incompatible API changes" section in each changelog entry.

**Comment by mourner** [comment]
v0.7.7 was released 6 years ago, so I don't think we should write a retroactive upgrade guide. We will definitely consider doing one for Leaflet v2 though.
