### ISSUE TITLE
Leaflet Map images URL's are not secure

### ISSUE THREAD

**Issue by das-devi** [Leaflet/Leaflet#7034]
At the time of map loading, leaflet is downloading the map images, and the images urls are not secure one, it is causing security issue(Mixed content), can these urls be converted to secure one(https)?.

sample map images url list

http://b.tile.osm.org/4/2/5.png?name=en
http://c.tile.osm.org/4/3/5.png?name=en
http://a.tile.osm.org/4/4/5.png?name=en
http://a.tile.osm.org/4/4/5.png?name=en

**Comment by johnd0e** [comment]
> and the images urls are not secure one

That url template is specified by you: https://leafletjs.com/reference-1.6.0.html#tilelayer

So it's your responsibility - just use `https` scheme.

**Comment by ab32972** [comment]
Thanks for the quick update.

**Comment by das-devi** [comment]
thanks for the quick update, closing the issue.
