### ISSUE TITLE
When adding control to map getting eror: corner is undefined 

### ISSUE THREAD

**Issue by Krulvis** [Leaflet/Leaflet#7035]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [ ] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
This only happens when I load the leaflet with require() from node-modules as shown below.
If I download the leaflet.js file, add it in the same folder and require('./leaflet.js') it works fine.
```
const L = Object.assign({}, require('leaflet'), require("leaflet-providers"));
const dark = L.tileLayer.provider('CartoDB.DarkMatterNoLabels'),
	light = L.tileLayer.provider('CartoDB.PositronNoLabels');

const map = L.map('map', {
	center: [52.092876, 5.104480],
	maxZoom: 17,
	minZoom: 2,
	preferCanvas: true,
	zoomControl: false,
	layers: [light]
});

const general = L.control({position: 'topcenter'});

general.onAdd = function () {
	const div = new L.DomUtil.create('div', 'info total');
	div.innerHTML = `<h1>HI</h1>`;
	return div;
};

general.addTo(map);
```

**Environment**
- Leaflet version: Tested with: 1.5.1 & 1.6.0
- Browser (with version): Firefox
- OS/Platform (with version): ArchLinux

Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.
I dont know how to make a fiddle with require() TS

- [X] this example is as simple as possible
- [X] this example does not rely on any third party code

**Comment by Krulvis** [comment]
![image](https://user-images.githubusercontent.com/21366036/77227871-8b4a1f80-6b83-11ea-8d1a-c8e7085e34aa.png)

**Comment by adasek** [comment]
Hi,
I'm just trying similar thing with leaflet 1.7.1
It seems to me that you provide incorrect position `topcenter` in your code.
According to the [Control#position documentation](https://leafletjs.com/reference-1.7.1.html#control-position) the correct values are only `topleft`, `topright`, `bottomleft` or `bottomright`.

I was able to adapt the code from [extending controls example](https://leafletjs.com/examples/extending/extending-3-controls.html#controls)

**Comment by johnd0e** [comment]
> It seems to me that you provide incorrect position `topcenter` in your code.

Indeed.
Related: #6935
