### ISSUE TITLE
Update the route drawing like a realtime GPS

### ISSUE THREAD

**Issue by Mehditeranee** [Leaflet/Leaflet#7045]
I coded something that moves a single marker every time a new geolocation is received. 

I coded also a route display between the current position, as i described above, and a marker previously put.

What I need, when the route is displayed, it is an automatic update of the route drawing depending of the current position marker moves.

Is it possible to manage this behavior ? And if yes, how ?

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by Mehditeranee** [comment]
@IvanSanchez https://stackoverflow.com/q/60883754/5990632
