### ISSUE TITLE
More options for L.Control position?

### ISSUE THREAD

**Issue by giswqs** [Leaflet/Leaflet#7048]
Based on the [Control documentation](https://leafletjs.com/reference-1.6.0.html#control-position), it seems the position can only be `bottomleft`, `bottomright`, `topleft`, or `topright`. Is it possible to add more options, such as `topcenter`, `bottomcenter`, or relative positon (e.g., %width, %height of the map) ? Thanks.

**Comment by johnd0e** [comment]
> `topcenter`, `bottomcenter`

Proposed in #6935 and similar PRs.

> or relative positon (e.g., %width, %height of the map)

Nothing similar is planned. But you can use css to override positions of existing corners.
