### ISSUE TITLE
Error (unexpected behavior) in projection of SVG image overlay

### ISSUE THREAD

**Issue by astridx** [Leaflet/Leaflet#7051]
I have a vector graphic. I would like to partially (only some layers) display this graphic as a basic map. I exported most of the layers of this vector graphic as PNG-file and created tiles using [Maptiler](https://www.maptiler.com/).

I saved the other layers as SVG-files and show them as an image overlay. 

The PNG and the SVG-files have the same size ratio and the same bounding box. The PNG is 9726px  7950px and the SVG 4863,5px x 3975.7 px.

    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="4863.5px" height="3975.7px" viewBox="0 0 4863.5 3975.7" style="enable-background:new 0 0 4863.5 3975.7;"
	 xml:space="preserve">

Unfortunately, the SVG files do not fit exactly over the tiles I created. There are small shifts. You can see it in the picture.

![Quick Start   Leaflet(1)](https://user-images.githubusercontent.com/9974686/77686563-71eb0e00-6f9d-11ea-9579-bb1f2d801942.png)

If I save the SVG-File as an PNG and load the PNG in the image overlay everything is fine!

I think there is something wrong with the projection. When creating the tiles, I tested with different coordinate systems. Among other things with EPSG:4326 (Bounding Box 7.088 51.401 7.365 51.541) and with EPSG:3857 (Bounding Box 789032.55 6692534.87 819868.05 6717554.10). 

This is my code:

    <script>
	var imageBounds = [[51.401, 7.088], [51.541, 7.365]];

	var tiles = L.tileLayer(
		'./tiles/{z}/{x}/{y}.png',
		{attribution: '<a href="...</a>',
			opacity: 1
		}
	);

	var map = L.map('mapid', {
		layers: [tiles],
		minZoom: 13,
		maxZoom: 15,
		maxBounds: imageBounds
	}).setView([51.45, 7.2], 14);

	var baseTree = [
		{
			label: 'Eigene Tiles',
			layer: tiles
		},
	];

	var overlaysTree = {
		label: 'Linien',
		selectAllCheckbox: 'Un/select all',
		children: [
			{
				label: 'NE',
				selectAllCheckbox: true,
				children: [
					{
						label: 'Neue SVG-Dateien',
						selectAllCheckbox: true,
						children: [
							{label: '159', layer: L.imageOverlay('159.svg', imageBounds)},
							{label: '344', layer: L.imageOverlay('344.svg', imageBounds)},
							{label: '345', layer: L.imageOverlay('345.svg', imageBounds)},
							{label: '353', layer: L.imageOverlay('353.svg', imageBounds)},
							{label: '355', layer: L.imageOverlay('355.svg', imageBounds)},
							{label: '365', layer: L.imageOverlay('365.svg', imageBounds)},
						]
			}
		]
	}]}

	var lay = L.control.layers.tree(baseTree, overlaysTree,
		{
			namedToggle: true,
			selectorBack: false,
			closedSymbol: '&#8862; &#x1f5c0;',
			openedSymbol: '&#8863; &#x1f5c1;',
			collapseAll: 'Collapse all',
			expandAll: 'Expand all',
			collapsed: false,
		});

	lay.addTo(map).collapseTree().expandSelected().collapseTree(true);  </script>

You can see a temporarily live demo here: https://fahrplan.astrid-guenther.de/

**Comment by IvanSanchez** [comment]
This is not a Leaflet bug, but rather an issue with the underlying data. Nothing to do here on the maintainers' part.

**Comment by astridx** [comment]
Thanks for your response. May I ask you something, as I do not understand:
What do you mean exactly? Do you mean: an SVG file in an image overlay is projected exactly like a PNG file and I didn't create the files correctly?
Or do you think that it is OK that an SVG file is projected differently than a PNG file?

**Comment by IvanSanchez** [comment]
I mean, it's normal that the streets don't match depending on the basemap or the dataset, and it's normal that map designers sway away from geographical accuracy in favour of readability (e.g. ignoring enclaves/exclaves, over/undersimplification, assuming a different stroke width or offset for the roads). All of those issues are real, but are out of the scope of what Leaflet does.
