### ISSUE TITLE
Native vector tile support

### ISSUE THREAD

**Issue by Creatium** [Leaflet/Leaflet#7054]
I am building a website which is based on a map. My very first choice was Google Maps, but now I decided to transfer to Leaflet which I chose based on its size (70kb is very very impressive) and features. Having said this, I am very sad that there is still no native support for vector tiles. I know there are several plugins that hack-around other platforms (like Mapbox GL) to enable vector tiles, but having to download additional 2-3 files of code very time user visits, that just diminishes any pros you can get from vector maps (I'm talking about loading performance).

I hope that native support for vector tiles is something that's coming to Leaflet in the near future. After all, it looks like vector is the future.

P.S. Again, very good job with Leaflet. I am very excited about it.

**Comment by plainheart** [comment]
That's great, but it seems a bit hard.

**Comment by IvanSanchez** [comment]
[Leaflet.VectorGrid](https://github.com/Leaflet/Leaflet.VectorGrid/) is the closest you'll get at this time, and you're free to bundle up the code (webpack/rollupjs/etc) if you feel that loading more files is a performance bottleneck.
