### ISSUE TITLE
Some leaflet elements cannot be displayed 

### ISSUE THREAD

**Issue by Fabian815** [Leaflet/Leaflet#7056]
**Problem**
First of all, my English is not very good. I got all of this through Google Translate. Please understand. The following is my question.I want to use react-native-web to display a map page developed with leaflet. As a result, the map can be displayed, but the lines and areas drawn on the map cannot be displayed. In addition, I opened my map page with the browser of the mobile phone simulator, and the page was able to display the line following the normal.
This is my first time asking questions, please understand if the way of question is not correct.

**Comment by plainheart** [comment]
Any errors in the browser console?

**Comment by Fabian815** [comment]
> Any errors in the browser console?

No.I eventually changed the rendering method to svg and solved the problem.

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.
