### ISSUE TITLE
Incorrect usage of changedTouches for touch events

### ISSUE THREAD

**Issue by keul** [Leaflet/Leaflet#7063]
Take a look at:

https://github.com/Leaflet/Leaflet/blob/95c436638180efff57e50d6356062be96925fcee/src/map/handler/Map.Tap.js#L89:L90

The code here is doing an assumption that the `changedTouches` list, if present, contains at least one element.

By looking at the specs from MDN:

> The touch point (or points) that were removed from the surface can be found in the TouchList specified by the changedTouches attribute.

The issue is that I can't create a working `touchend` event if I don't provide a `changedTouches` attribute, but this attribute can't be null (I get an exception if I try).

I think that the code here should be different and checking also if the array is not empty:

https://github.com/Leaflet/Leaflet/blob/95c436638180efff57e50d6356062be96925fcee/src/map/handler/Map.Tap.js#L87

```javascript
if (this._fireClick && e && e.changedTouches && e.changedTouches.length > 0) {
...
```

- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Comment by johnd0e** [comment]
> The issue is that I can't create a working `touchend` event if I don't provide a `changedTouches` attribute, but this attribute can't be null (I get an exception if I try).

I haven't understood what exact problem do you have with current code.
This `_onUp` method handles `touchend` event, which MUST contain `changedTouches` (according specs).
So what's wrong?

**Comment by keul** [comment]
@johnd0e forgive me, you are right. I was raising a `touchend` events with an empty changedTouches list which is not the way intended to be.
