### ISSUE TITLE
How to include Traffic Cameras Map into leaflet maps layers.?

### ISSUE THREAD

**Issue by Prateek-Kickdrum** [Leaflet/Leaflet#7070]
I want to use the Traffic Cameras Map which is shown as follows: 
https://maps.alk.com/developer/1.2/TrafficCameras

Into Leaflet plugin, 
Do we have any layer which I can use to fulfill my project requirement?

Thank you in Advance.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
