### ISSUE TITLE
Can it load a vector map as big as 200km x 200km?

### ISSUE THREAD

**Issue by fahad462** [Leaflet/Leaflet#7076]
I want to load a huge vector map as large as 200km x 200km. Can the library open it and remain smooth?

**Comment by IvanSanchez** [comment]
Maybe, or maybe not. Depends on the amount of data, the data format, and other factors. The usual answer to this is "try yourself before asking".

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by fahad462** [comment]
I tried it. Memory requirements for this is huge. For 3 geojson file memory uses were up to 500MB. And panning and zooming took literaly 10-20s thus makes the library not compatible with huge vector files

**Comment by johnd0e** [comment]
That's the exact reason why such plugins created: https://leafletjs.com/plugins.html#vector-tiles

**Comment by fahad462** [comment]
> That's the exact reason why such plugins created: https://leafletjs.com/plugins.html#vector-tiles

I understand. But there is still memory issue. Memory uses goes beyond 1 GB for a 100mb geojson file with 20k features.
