### ISSUE TITLE
Do not remap touch* to pointer* events

### ISSUE THREAD

**Issue by johnd0e** [Leaflet/Leaflet#7077]
https://github.com/Leaflet/Leaflet/blob/d843c3b88486713827d7e860b58bdba75bfbd5a2/src/dom/DomEvent.js#L91-L93

I really doubt that we should use this 'pointer transformation' for **every** pointer-capable browser.

Originally it meant to simulate touch for Windows mobile IE, which does not support touch events.

Previously preferring pointer events had some sense: smoother scrolling.
But now with passive touch listeners we have exactly good performance.

And one more consideration: there are use cases hardly achieved without real touch events. Among them - prevent `click` when it is not needed.

**Comment by johnd0e** [comment]
1. There is no reason to **fake** events. Such approach leads to subtle bugs which are hard to fix.
   See also #7064.
2. `touch*` events are not equivalent to their `pointer*` counterparts.
   `preventDefault()` may have different effect (or no effect) when called in `pointer*` handler.
   E.g.: 
   a.  only touch handler may prevent `click` (used in #7026).
   b.  only touch handler may prevent default browser action, such as page scrolling and pinch-zooming (at least in some cases, like  #5745, #5969).
   c.  Firefox Preview, or android Firefox with `dom.w3c_pointer_events.enabled=true` flag, has some issue with pinch zoom gesture: it is hard to start it.

**Comment by denschub** [comment]
Hey there. I'm working on Firefox, and we're seeing quite a few reports about broken maps in the new Firefox for Android. From this bug, it looks like you have already identified the cause, and are working on a fix. Is there a timeline for this to ship? Is there anything we can help you with? :)

**Comment by IvanSanchez** [comment]
@denschub We released 1.7.0/1.7.1 a few days ago (with some impactful changes regarding handling of `PointerEvent`s) and had some bug reports from Safari users (see #7255).

I'm not aware of any problems with FFX+Android yet - would you mind creating a new bug report including the versions of Leaflet and FFX needed to reproduce, and any links to upstream bugzilla? That'd be useful.
