### ISSUE TITLE
CQL_FILTER support in L.TileLayer.WMS

### ISSUE THREAD

**Issue by mariomartinezsz** [Leaflet/Leaflet#708]
I am learning to use Leaflet. Looks like a wonderful contribution. Thank you very much.

It would be great to have support for CQL_FILTER in L.TileLayer.WMS. At the moment I'm looking for a way to filter Geoserver results to display with Leaflet.

**Comment by CamMuller** [comment]
Hi Guys, sorry for posting this here but running out of options.

I am currently struggling to compile a cql_filter for Leaflet serving data with GeoServer. I am attempting to make a button with the following java-script code:

```
//Pylon Search Button
function updatePylons() {
var pylonFilter = DWITHIN("geom", GEOMETRYCOLLECTION(queryCollection("Inyaninga_243-198:proposed_pylons_3857","geom","id = ' '" + document.getElementById("Pylon").value + "'")), document.getElementById("distance").value + ', meters');
return proposed_pylons.setParams({CQL_FILTER: pylonFilter});
};
```
This function is passed to a button which accepts user input.

For some reason I cant get the DWITHIN parameters correct, any help would be greatly appreciated.

**Comment by IvanSanchez** [comment]
@CamMuller This is an issue tracker, not a support channel. You already wrote https://gis.stackexchange.com/questions/233340/leaflet-web-map-cql-filter , do not cross-post here.

Please also read http://catb.org/~esr/faqs/smart-questions.html while you're at it. In this particular case, it would help you to show more code, explain the symptoms, analyze stack traces and see how the requested URLs look like.
