### ISSUE TITLE
Legend distorted when viewed on chrome (MS Edge, tor browser ok)

### ISSUE THREAD

**Issue by aspiringguru** [Leaflet/Leaflet#7081]
When this github page is viewd in chrome incognito, the legend appears distorted
Distortion does not appear when page is loaded in microsoft edge or tor browser. 
https://github.com/aspiringguru/chloropleth_map_interactive/tree/master/leaflet_demo1

git repo 
https://aspiringguru.github.io/chloropleth_map_interactive/leaflet_demo1/

screenshots showing distorted and non distorted legends in different browsers here.
https://github.com/aspiringguru/chloropleth_map_interactive/tree/master/leaflet_demo1/screenshots

This is a very basic hellow world example from tutorials.

**Comment by johnd0e** [comment]
You should not dismiss bugreport template. Pay attention, that this bugtracker is not for general support, and you should be sure that you are reporting leaflet bug.

BTW, I do not see any issues there: https://aspiringguru.github.io/chloropleth_map_interactive/leaflet_demo1/

> This is a very basic hellow world example from tutorials.

I do not see any issues there either: https://leafletjs.com/examples/choropleth/
