### ISSUE TITLE
Reuse source

### ISSUE THREAD

**Issue by strarsis** [Leaflet/Leaflet#7086]
Four maps should show the same, just with slight center offsets.
However, as each Leaflet must use its own layer (which is also the tiles source as this doesn't seem to be separated in Leaflet), all four maps have to download the same tiles.
I don't see a way how the browser should cache the other three redundant requests because all four requests are emitted the same time like a race condition.
It would be nice if one tiles source can be used for all four map layers.

**Comment by IvanSanchez** [comment]
Won't do. Too much refactoring work needed to implement such a feature in core Leaflet.

I'd suggest going for an approach based on [service workers](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers), perhaps publishing that as a Leaflet plugin afterwards. IMO a Service Worker is the best place to handle caching of such network requests.

**Comment by strarsis** [comment]
I am sure using service workers and very elegant and efficient.
But I just want to instantiate four map instances and let them use the same source to prevent four times the downloads (in worst case). 😸
