### ISSUE TITLE
Leaflet shows world map when it set to current location

### ISSUE THREAD

**Issue by manojmsrit** [Leaflet/Leaflet#7087]
I have set map to current location as shown below. 

`var mymap = L.map('mapid', {doubleClickZoom: false}).locate({setView: true, maxZoom: 22});`

But sometimes map does not load to current location. It shows world map. ( Only sometimes ) Let me know how to solve this issue.

**Comment by hirunatan** [comment]
I have the same problem, and have found that is related to the change of security policies from Google geolocation API. These two questions are related to it:

https://stackoverflow.com/questions/39316859/google-maps-api-geolocation-not-working-in-firefox
https://stackoverflow.com/questions/61032115/unknown-error-acquiring-position-geolocationpositionerror-code-2-firefox-linux

Leaflet [uses geolocation API](https://github.com/Leaflet/Leaflet/blob/master/src/map/Map.js#L664) to get the user location. And apparently, now Google requires that you use https and provide a [valid API key](https://developers.google.com/maps/documentation/geolocation/get-api-key) to use navigator.geolocation.getCurrentPosition() function.

There is a local workaround, opening **about:config** in Firefox and setting one value, but only works in the browser you do this.

I think there is no way to fix this, extcept registering an API key for your project, or using a different mechanism to get the current location.

**Comment by hirunatan** [comment]
I have reproduced the problem with this code.

This returns the error "Unknown error acquiring position" in Firefox and "Network location provider at 'https://www.googleapis.com/' : No response received." in Chrome.

```html
<html>
<head>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
       integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
       crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"
       integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew=="
       crossorigin=""></script>
</head>
<body>
    <div id='mapid' style='height:400px;width:500px;'></div>
    <div id='actions'><a href='#' onClick="locateUser()">Find me!</a></div>
    <script>
        function initMap() {
            this.map = L.map('mapid').setView([51.505, -0.09], 13);

            L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
              maxZoom: 18,
              id: 'mapbox/streets-v11',
              tileSize: 512,
              zoomOffset: -1
            }).addTo(this.map);
        }

        function locateUser() {
            this.map.locate({setView : true})
              .on('locationfound', function(e) {
                  console.log("found at", e.latlng);
              })
             .on('locationerror', function(e){
                  console.error(e.message);
                  console.error(e);
              });
         }

        var map = null;

        initMap();

    </script>
</body>
</html>
```

**Comment by hirunatan** [comment]
Hi @IvanSanchez. I see you have closed this issue without any explanation. It seems still open to me. What was the problem? I think it's a real problem and it's relevant to leaflet. May I open a different issue better explained? Thanks.

**Comment by manojmsrit** [comment]
![image](https://user-images.githubusercontent.com/49993125/79500708-2ae8b980-802d-11ea-9173-2de7fb66a664.png)
![image](https://user-images.githubusercontent.com/49993125/79500713-2de3aa00-802d-11ea-8605-01de41615aaa.png)


Please look at these images. Sometimes Leaflet shows current location and sometimes it shows world map. Please suggest me solution. It is causing me my application to crash.

**Comment by IvanSanchez** [comment]
Use [`navigator.geolocation`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/geolocation) directly. If you're unable to get a geolocation with that API, then it isn't Leaflet's fault.
