### ISSUE TITLE
Broken GridLayer zoom animation in angular production build

### ISSUE THREAD

**Issue by t-denis** [Leaflet/Leaflet#7096]
In Angular production build zoom animation is broken (unfocused double image, hard to explain) if using mouse scroll.

![image](https://user-images.githubusercontent.com/5320360/79497639-b6b01500-8030-11ea-9864-ade9598deb51.png)

Looks like modern minification tools consider this call as a pure function with an unused result, and decide to remove these lines:
https://github.com/Leaflet/Leaflet/blob/984fedda1c48d141f018ca45ae06738872d7f5dd/src/layer/tile/GridLayer.js#L393-L394

Can be fixed by adding some side-effects to `offsetWidth` or `Util.falseFn`. For example:
```js
if (level.el.offsetWidth < 0) {
  console.log(level.el.offsetWidth);
}
```
```js
export function falseFn() {
  if (arguments.length < 0) {
    console.log(arguments.length);
  }
  return false;
}
```

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.

**Comment by IvanSanchez** [comment]
This rather looks like a bug in whatever minification tool you're using.

**Comment by t-denis** [comment]
@Ploppy3 Try to modify files in `dist` folder, not `src`.
Also note, that changes in `node_modules` can be lost after adding/removing/reinstalling packages.

**Comment by Ploppy3** [comment]
@t-denis Yeah thanks. Ended up forking leaflet modifying the files adding it to my project.

**Comment by danmana** [comment]
> @Ploppy3 Try to modify files in `dist` folder, not `src`.
> Also note, that changes in `node_modules` can be lost after adding/removing/reinstalling packages.

With [patch-package](https://www.npmjs.com/package/patch-package) you can make the changes in node_modules persistent.

1. `npm install --save-dev patch-package`
2. in `package.json` scripts add
```json
"scripts": {
    "postinstall": "patch-package && ngcc"
}
```

3. Modify `node_modules/leaflet/dist/leaflet-src.js` as suggested
```js
	function falseFn() {
		if (arguments.length < 0) {
			console.log(arguments.length);
		}
		return false;
	}
```
4. Run `npx patch-package leaflet`

Now everytime somebody does an install, patch-package will take care to apply the falseFn patch

**Comment by Ploppy3** [comment]
@danmana Quite interesting, I didn't know about this. Thank you very much.
