### ISSUE TITLE
Problem MouseMove Marker in MS Edge

### ISSUE THREAD

**Issue by JanLoebel** [Leaflet/Leaflet#7097]
Hi there,

I have a strange problem with dragging a marker in the Microsoft Edge Browser. I've made a stackblitz to show the problem.

https://stackblitz.com/edit/leaflet-ygrdpb

The Marker should follow the mouse but there is an offset which seems to be from the element above the map itself. With Chrome/Firefox the problem doesn't exist but the Edge Browser seems to have a problem there. Is this a bug in leaflet or a problem of my code?

**Comment by IvanSanchez** [comment]
What versions of Edge are affected?

**Comment by JanLoebel** [comment]
I'm using:

Microsoft Edge 44.17763.831.0
Microsoft EdgeHTML 18.17763

**Comment by JanLoebel** [comment]
Is any body else able to reproduce it? Or has anyone a workaround?

**Comment by johnd0e** [comment]
@JanLoebel 
I'm able to reproduce it, but before talking about of workarounds please try to provide some simple example without angular stuff.

**Comment by Malvoz** [comment]
> > What versions of Edge are affected?
> 
> Microsoft Edge 44.17763.831.0
> Microsoft EdgeHTML 18.17763

That's legacy Edge (the initial release of the Chromium-based version was 79.0.309), which Leaflet [no longer supports](https://github.com/Leaflet/Leaflet/pull/8455#discussion_r979249515).
