### ISSUE TITLE
Tests for GeoJSON functions required

### ISSUE THREAD

**Issue by johnd0e** [Leaflet/Leaflet#7099]
None of following [GeoJSON functions](https://leafletjs.com/reference-1.6.0.html#geojson-geometrytolayer) are covered with tests yet:
- [ ] `geometryToLayer`
- [ ] `coordsToLatLng`
- [ ] `coordsToLatLngs`
- [ ] `latLngToCoords`
- [ ] `latLngsToCoords`
- [ ] `asFeature`

Sample test (for `latLngToCoords`):
```js
describe("L.GeoJSON functions", function () {
	it("L.GeoJSON.latLngToCoords", function () {
		// todo: check alt too
		var arrLatLng = [-1.4837191022531273, 43.49222084042808];
		var arrLngLat = [arrLatLng[1], arrLatLng[0]];
		var latLng = L.latLng(arrLatLng);

		expect(L.GeoJSON.latLngToCoords(latLng)).to.eql([43.492221, -1.483719]);
		expect(L.GeoJSON.latLngToCoords(latLng, 0)).to.eql([43, -1]);
		// expect(L.GeoJSON.latLngToCoords(latLng, false)).to.eql(arrLngLat); // after #7100
	});

	// etc
});
```

**Comment by adriancerejo** [comment]
I am pretty new to open-source contributions but could I try adding one or few of these tests?

**Comment by phloose** [comment]
@johnd0e i opened a ready-for-review pull request that adds the respective tests.

**Comment by devadeka** [comment]
If this is still open could I have a crack at it for hacktoberfest?
Ta

**Comment by phloose** [comment]
i proposed a pull request (#7147) in may, which after an initial discussion did not get further attention. So maybe someone could review it?! @johnd0e @mourner ?
