### ISSUE TITLE
Double tap breaks zoom out on iOS

### ISSUE THREAD

**Issue by a-uz** [Leaflet/Leaflet#7106]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- Open https://leafletjs.com/
- Double tap on map
- Continuously tap on zoom out control

**Expected behavior**
Pressing on zoom out should zoom out

**Current behavior**
In the GIF below I'm double tapping on the map to zoom in and then pressing on the zoom out control multiple times. Notice how the zoom level changes unexpectedly. It starts by zooming in, then at some point switches to zooming out and again to zooming in.

![ezgif-2-f76aa56882eb](https://user-images.githubusercontent.com/6834140/79852843-e617a680-83cf-11ea-914a-76495eca7190.gif)

**Environment**
- Leaflet version: 1.5.1, 1.6.0 and whatever is used on https://leafletjs.com/
- Browser (with version): Safari
- OS/Platform (with version): iOS 13.4.1

**Comment by johnd0e** [comment]
@a-uz 
Try here https://gist.githack.com/johnd0e/12cb0d6c2aead30ea7f2e17c5f9991be/raw/test-doubletap.html

**Comment by a-uz** [comment]
@johnd0e This seems to work as expected:

![ezgif-2-6bd67ad079c0](https://user-images.githubusercontent.com/6834140/79859622-f59bed00-83d9-11ea-9ad9-716befcf121a.gif)

**Comment by johnd0e** [comment]
Ok, please also try this one: https://gist.githack.com/johnd0e/a3647bebc3a65440d2f7ea470998816b/raw/test.html

**Comment by a-uz** [comment]
@johnd0e This one zooms in and then on the last level switches to zoom out - zoom in loop:

![ezgif-2-b2ed3083f3c6](https://user-images.githubusercontent.com/6834140/79863111-de5ffe00-83df-11ea-94fe-1fc6af14e0c9.gif)

**Comment by johnd0e** [comment]
> This seems to work as expected:

On same test page please try double-tap on "-" button.

**Comment by a-uz** [comment]
@johnd0e Here I double tapped on the "-" button multiple times:

![ezgif-2-7705c6c57277](https://user-images.githubusercontent.com/6834140/79867396-f4bd8800-83e6-11ea-8445-c29c921f6a14.gif)

Here I double tapped on the map and then double tapped on the "-" button multiple times:

![ezgif-2-ab4bf4579856](https://user-images.githubusercontent.com/6834140/79867285-cd66bb00-83e6-11ea-8bee-318c8314b27f.gif)

**Comment by johnd0e** [comment]
> Ok, please also try this one: https://gist.githack.com/johnd0e/a3647bebc3a65440d2f7ea470998816b/raw/test.html

And the same on this page.
(No need to tap map, I'm interesting only in tapping on "-" control)

**Comment by a-uz** [comment]
@johnd0e Here you go:

![ezgif-2-806aff57f0ea](https://user-images.githubusercontent.com/6834140/79869566-38fe5780-83ea-11ea-8ef0-a6e758c39591.gif)

**Comment by johnd0e** [comment]
Please make sure that you are using proper test page: https://gist.githack.com/johnd0e/a3647bebc3a65440d2f7ea470998816b/raw/test.html
That one where you can see the bug unfixed. 

And tap as fast as at your original report, to force `dblclick` events.

**Comment by a-uz** [comment]
@johnd0e I did use the correct one. When double tapping the "-" button no map events are logged. Only as I double tap on the map and then double tap on the "-" they occur, as you can see below:

![ezgif-2-e3ae796b8b2b](https://user-images.githubusercontent.com/6834140/79872011-e58e0880-83ed-11ea-81b5-edcd3c8c5f58.gif)

**Comment by a-uz** [comment]
@johnd0e You can also notice that when I double tap on the "-" button, two `dblclick` events are triggered. In the first version for the test page I single tapped the "-" button.

**Comment by johnd0e** [comment]
So if you do not touch map - then tapping zoom control produces no events. 

But after map is double-tapped - on every zoom tap we see two `dblclick` logged. 

Right? 

(This looks extremely weird)

**Comment by johnd0e** [comment]
Ok, I've tracked the very root of the issue.
Zoom control buttons [should not](https://github.com/Leaflet/Leaflet/blob/1ae785b73092fdb4b97e30f8789345e9f7c7c912/src/control/Control.Zoom.js#L94) propagate neither of [`mousedown`, `touchstart`, `dblclick`](https://github.com/Leaflet/Leaflet/blob/1ae785b73092fdb4b97e30f8789345e9f7c7c912/src/dom/DomEvent.js#L185-L189).

But in current master `dblclick` can emitted [on `touchend`](https://github.com/Leaflet/Leaflet/blob/1ae785b73092fdb4b97e30f8789345e9f7c7c912/src/dom/DomEvent.DoubleTap.js#L34).

So we have 2 options here:
- either add `touchend` to 'stop list' too
- or adopt #7027 (preferred, in my opinion)

**Comment by a-uz** [comment]
In the app that I'm working (closed source) there are custom map controls/buttons inside the map node. Once you double tap the map, all the subsequent taps on the controls get hijacked by the double tap handler, so it's not just the "-" control. It seems that when you tap again on the map, it goes back to normal.
