### ISSUE TITLE
React-Static & Importing Leaflet Removes Dynamic Html Head on Build

### ISSUE THREAD

**Issue by TimMcCauley** [Leaflet/Leaflet#7107]
Greetings Leaflet community,

I am experiencing a rather weird situation using Leaflet in combination with react-static;  I have already [raised this question in the react-static repository](https://github.com/react-static/react-static/issues/1406) and the authors asked me to place the question here.
 
With react-static I am generating dynamic html information in the build stage to produce static html files which works absolutely fine however as soon as I import Leaflet which we would like to use in our contact form it removes the head information and I just do not understand why.

I have prepared a demo below and any hints would help me greatly as I am already in great despair.. 🆘 !

### Environment

```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 736.20 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v10.17.0/bin/npm
  Browsers:
    Chrome: 80.0.3987.163
    Safari: 13.0.4
``` 
### Steps to Reproduce the problem

1.  MVP can be found here ` git clone https://github.com/TimMcCauley/react-static-leaflet-head-bug.git`
2.  `yarn install`
3.  `yarn build && yarn serve`
4.  Check the markup after building with and without line 3 in `react-static-leaflet-head-bug/src/containers/Post.js`
5.  With will strip out the dynamic Head and without react-helmet will build the html perfectly.

### Expected Behavior

I would expect that importing leaflet would have no effect on the generation of the html head.

### Reproducible Demo

https://github.com/TimMcCauley/react-static-leaflet-head-bug

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.
