### ISSUE TITLE
`contains(latLng)` method for polygons

### ISSUE THREAD

**Issue by maximal** [Leaflet/Leaflet#7109]
It’s quite common situation when you need to determine whether a point is inside the given polygon. It would be very helpful if Leaflet allows us to do that.

I see that as a `contains(latLng|Point)` method of `Polygon` class, but implementation can be different.

Helpful links:
* https://stackoverflow.com/questions/16890294/leaflet-how-to-check-point-lies-inside-outside-of-polygon-or-rectangle
* https://gis.stackexchange.com/questions/208546/check-if-a-point-falls-within-a-multipolygon-with-python

**Comment by vulkd** [comment]
I could see this being useful to include in Leaflet though changing the existing `.contains` methods could introduce a breaking change for those using `.contains` to explicity check bounding boxes ( @mourner )?

TurfJS is helpful for utilities like this and their implementation also handles MultiPolygons w/ holes.
 -  https://turfjs.org/docs/#booleanPointInPolygon 
 - https://github.com/Turfjs/turf/blob/master/packages/turf-boolean-point-in-polygon/index.ts

**Comment by maximal** [comment]
Oh, sorry, I had missed existing method with the same name when I was creating the issue, although quickly checked the API.
Anyway, it can be named something different, like `point.isWithin(polygon)` or something.

**Comment by johnd0e** [comment]
See #4618
