### ISSUE TITLE
fitBounds problem in async initialize map in leaflet 1.6

### ISSUE THREAD

**Issue by powahftw** [Leaflet/Leaflet#7114]
Opening a new bug as #3031 is closed.

I just encountered the same issue while migrating from Promise to await/async 
Leaflet version: 1.6.0,

Snippet

Before
```Javascript
response.json().then((data) => {
  const a = data[`key1`];
  const b = data[`key2`];
  loadMap(a, b);
});
```

After
```Javascript
const data = await response.json();
const a = data[`key1`];
const b = data[`key2`];
loadMap(a, b);
```

Loadmap (Some omiss)
```Javascript
function loadMap(..., latLngs) {
 const mymap = L.map(`mapid`);
  L.tileLayer(...).addTo(mymap);

  const markers = [];
  latLngs.forEach((latLng) => {
    const marker = L.marker(latLng).addTo(mymap);
    markers.push(marker);
  });

  const group = L.featureGroup(markers);
  //mymap.fitBounds(group.getBounds().pad(0.5)) <- This doesn't work 
  setTimeout(() => mymap.fitBounds(group.getBounds().pad(0.5)));
}
```

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by powahftw** [comment]
This is a report of a regression of a previously reported bug. 
I've attached the steps to reproduce them in the comment!

**Comment by IvanSanchez** [comment]
> I've attached the steps to reproduce it in the comment!

No, that's not enough info to reproduce, since `async` function cannot appear in the top-level scope of a reproducible example. Show me a reproducible example [like this](https://plnkr.co/edit/wKwldJUALSNb10pD), and I'll believe that.
