### ISSUE TITLE
iOS 13.3.1 controls are hidden by map tiles

### ISSUE THREAD

**Issue by mybluedog24** [Leaflet/Leaflet#7131]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- 

**Expected behavior**

**Current behavior**
Controls are hidden by tile layers. Same as this video shown: https://www.youtube.com/watch?v=0wRubtO4y0U

**Environment**
- Leaflet version: 1.3.1
- Browser (with version): Safari
- OS/Platform (with version): iOS 13.3.1

**Additional context**
Everything works fine until I recently upgraded to iOS 13.3.1. I'm using ionic 3. If the map is on a page that is fixed and no scroll, the controls work fine. But once it's on a page that can scroll, the controls are hidden by tile layers. Exactly the same as the video shown above. After I investigated and found out that change the CSS `overflow` from `hidden` to `auto` seems fixed this issue:
```css
  .leaflet-container {
    overflow: auto; // hidden
}
```
I really don't know what caused this issue and not sure if it's the correct way to fix it... I'm using leaflet 1.3.1 but see that current version 1.6 also has this CSS set to hidden. So not sure if it's a bug for ionic only since I open leafletjs.com and view a few of those maps, they all work fine. If it's fixed please close it.

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.
