### ISSUE TITLE
How should CRS support EPSG :: 32451

### ISSUE THREAD

**Issue by yjgeek** [Leaflet/Leaflet#7132]
The crs of my geojson is "urn: ogc: def: crs: EPSG :: 32451", what do I need to do to support this projection

**Comment by IvanSanchez** [comment]
https://github.com/kartena/Proj4Leaflet

**Comment by IvanSanchez** [comment]
Also note that [RFC 7946](https://tools.ietf.org/html/rfc7946) states that GeoJSON shall be EPSG:4326 only.
