### ISSUE TITLE
Control containers are placed wrong when certain style is applied to divs

### ISSUE THREAD

**Issue by WebOSM** [Leaflet/Leaflet#7143]
Not so much a bug but it still bugged me. :)

I had some problems integrating Leaflet in an existing webpage.
The webpage is a single page and uses absolute positioning.
The left, right, top and bottom in that case were set to 0.

This causes the control containers to all be the size of the map and the content is all on the top.
For instance the 'contribution' that is normally on the right bottom moves to the top-right.

This link shows the problem and fix.
https://plnkr.co/edit/WDySumrDengB0gjs

I had this problem in version 1.5 and it is also the case with version 1.6.

**Comment by johnd0e** [comment]
Looks similar to #6843.
Not sure that it's worth "fixing" in Leaflet.

**Comment by Falke-Design** [comment]
The suggested change is to add following:
```
			.leaflet-left {
				right: unset;
			}
			.leaflet-right {
				left: unset;
			}
			.leaflet-top {
				bottom: unset;
			}
			.leaflet-bottom {
				top: unset;
			}
```

To unset the position of controls like the attribution control.
If the following CSS style for div is on the website, it causes the misplaced control:
```
			div {
				position: absolute;
				top: 0px;
				left: 0px;
				right: 0px;
				bottom: 0px;
			}
```

**Comment by johnd0e** [comment]
> The suggested change is to add following

Are you suggesting to add this to leaflet?

**Comment by Falke-Design** [comment]
If #6843 will be added to leaflet I see no reason why this should not added too. But I personally I have no opinion on this.

**Comment by johnd0e** [comment]
@IvanSanchez @mourner @jonkoops

**Comment by mourner** [comment]
Styling `img` in weird generic way, although a terrible practice, is at least a common occurrence, while I can't imagine us trying to anticipate ALL possible combinations of crazy CSS rules that could be applied where it doesn't make any sense, like the `div` example above. I think this is a `won't fix`.
