### ISSUE TITLE
Can not disable "inertia"

### ISSUE THREAD

**Issue by Nimdim** [Leaflet/Leaflet#7145]
Hello all! I'm using leaflet v1.6.0 as a npm package in my project. I can't disable pan inertia. I pass inertia: false to creation options according to docs (https://leafletjs.com/reference-1.6.0.html#map-inertia). But inertia is still working.
Please help me to solve the issue

**Comment by mondeja** [comment]
I can reproduce this issue with same Leaflet version.

**Comment by IvanSanchez** [comment]
Can't reproduce with 1.6.0 in e.g. https://plnkr.co/edit/olngBRbOBcI4wRf5

Is there any circumstance I'm missing here? What browser(s) are you using?

**Comment by mondeja** [comment]
My mistake, it's working as exepcted.

**Comment by Nimdim** [comment]
You both were right. **inertia** option worked as specified.
It was my misunderstand of docs. Now I understand that I was needed to disable **animation** option of fitBounds function.
Sorry and thanks for help. The solution for my issue was found. And it is Great!
