### ISSUE TITLE
"zoomControl":false does not appear to work

### ISSUE THREAD

**Issue by gggustafson** [Leaflet/Leaflet#7146]
In an animated map, I do not want to allow zooming. To that end, I wrote:

       map = L.map ( components.map, 
                    { 
                    "zoomControl":false,
                    "center":components.centered_at, 
                    "zoom":components.zoom 
                    } );

where components is an object containing various constants and HTML names. Thus components.map points to the map &lt;div&gt; on the HTML page; components.centered_at  contains the lat/long of the map center; and components.zoom contains the initial zoom value.

When I display the map, the plus/minus control still appears in the upper left of the graphic. 

Am I doing something wrong?

**Comment by IvanSanchez** [comment]
Works as expected, e.g. https://plnkr.co/edit/CAZHL2cPjYW3P0en . Problem must be at your end.
