### ISSUE TITLE
Precision of sf coordinates

### ISSUE THREAD

**Issue by mtennekes** [Leaflet/Leaflet#7148]
A leaflet map displaying `sf` data may become very large in file size. This can be reduced by setting the precision of the coordinates. E.g. `c(50.9823, 6.0540)` instead of `c(50.982320753504, 6.05402285163678)`.

The precision of `sf` objects can be set with `sf::st_set_precision`, which is correctly only used in `sf::st_as_binary`. However, this precision argument could also be useful when `sf` data is used in leaflet functions, such as `addPolygons`.

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.

**Comment by IvanSanchez** [comment]
AFAIK, `sf` means you're using R.
