### ISSUE TITLE
Leaflet circles sometimes don't render with custom properties.

### ISSUE THREAD

**Issue by AvdylKrasniqi** [Leaflet/Leaflet#7154]
Leaflet circles sometimes do not render as I specify the properties such as color, radius, etc.
Here is the example:
https://prishtinatrees.org/ (After the map loads, click on any polygon and the circles will be shown)

P.s I tried the circleMarker and it happens the same thing.
I tried from different browsers and it happens sometimes on the first time.
I also tried on the Edge browser and it loads perfect on the first time but after reload (NOT Hard Reload), circles do not render properly.

How it should be:
![image](https://user-images.githubusercontent.com/29227772/82517606-c7ffac00-9b1d-11ea-9961-2e7e8cec7116.png)

How it renders sometimes:
![image](https://user-images.githubusercontent.com/29227772/82517587-bc13ea00-9b1d-11ea-83d0-0c538fde8f94.png)

What may cause that?

**Comment by IvanSanchez** [comment]
Can't reproduce.

If it happens *sometimes* and *on first load* then it sounds like a race condition when fetching some resources.

But keep in mind that this bug tracker is for Leaflet bugs (the kind that can be reproduced with a minimal example), not for getting help debugging your map.

**Comment by AvdylKrasniqi** [comment]
To whoever read this page:

**The issue was not with leaflet...**
It was because I did **not** put `L.circle()` inside

```
 $(document.ready(){
//right there
})
```
so `L.cicrle()` was executed before the icon property was fully initialized. 😞
