### ISSUE TITLE
Error: "Map Container not found" when using ngfor 

### ISSUE THREAD

**Issue by argupta23** [Leaflet/Leaflet#7162]
**Environment:** 
Angular 9, 
Leaflet 1.6.0

**Background:** 
I can build multiple maps by creating individual "div" and "options" without any issue. -- commented portion of html
Get the above error when using ngfor to create multiple maps in same page.

**Code Snippet:**
**realtimedashb.component.html**
`

      

      <div *ngFor="let widget of widgets; let w = index" class="col-md-{{widget.width}}">
        <pre>{{widgets | json}}</pre>
        <div #id="map{{widget.name}}" >
      </div>
      </div>`

**realtimedashb.component.ts**

`import * as L from 'leaflet';

@component

 leafletoptions(widget){

_// this code works fine for hardcoded div's_
/*         const map = L.map('testmap').setView([50.6311634, 3.0599573], 4);
         L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
           attribution: 'Test Map',
           maxZoom: 12
         }).addTo(map);
         var marker = new L.Marker(new L.LatLng(40.6311634, 3.0599573), {
         });
         map.addLayer(marker);
        map.invalidateSize(true);
       const map2 = L.map('testmap2').setView([50.6311634, 3.0599573], 4);
         L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
           attribution: 'Test Map',
           maxZoom: 12
         }).addTo(map2);
         var marker = new L.Marker(new L.LatLng(40.6311634, 3.0599573), {
         });
         map2.addLayer(marker);
       map2.invalidateSize(true);
*/

_// Fails when I switch to ngfor and in this case parameter within L.Map is dynamic coming from backend, which is also used in the div._
    var testmap = L.map(String(widget.name)).setView([50.6311634, 3.0599573], 4);
        L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
          attribution: 'Test Map',
          maxZoom: 12
        }).addTo(testmap);
        var marker = new L.Marker(new L.LatLng(50.6311634, 3.0599573), {
        });
      // testmap.invalidateSize(true);
        testmap.addLayer(marker);
  }`

**ERROR reported in Console.**
Error: Map container not found.
    at NewClass._initContainer (leaflet-src.js:4097)
    at NewClass.initialize (leaflet-src.js:3131)
    at new NewClass (leaflet-src.js:301)
    at Object.createMap [as map] (leaflet-src.js:4718)
    at RealtimeDashbComponent.leafletoptions (realtimedashb.component.ts:1749)
    at RealtimeDashbComponent.setWidgetData (realtimedashb.component.ts:2076)
    at realtimedashb.component.ts:1718
    at Array.forEach (<anonymous>)
    at SafeSubscriber._next (realtimedashb.component.ts:1715)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:183)

I have also tried the following combinations
1. hardocded div and options -- works
2. hardcoded div and server derived options loop -- works
3. switching from hardcoded div to ngfor is where the problem occurs. I can see that the div is assigned to proper id passed in widget.name and is also reflected in the image below.

I have attached a snapshot from Chrome dev-tools which shows the state info. 
![leaflet_error](https://user-images.githubusercontent.com/39933836/83275806-4cdd6c00-a195-11ea-99bf-ae776e8f1590.png)

Any guidance in getting this resolved is greatly appreciated.

Thanks

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.
