### ISSUE TITLE
Should L.LatLngBounds( ) return an empty bounds?  (and update doc)

### ISSUE THREAD

**Issue by Leif-W** [Leaflet/Leaflet#7163]
Trying to create an empty bounds, I realized that

```
var bounds = L.LatLngBounds(); // unexpectedly returns undefined
```

whereas

```
var bounds = new L.LatLngBounds(); // returns the expected empty bounds
```

In file src/geo/LatLngBounds.js

```
export function LatLngBounds(corner1, corner2) { // (LatLng, LatLng) or (LatLng[])
	if (!corner1) { return; } // should this simply return new LatLngBounds() instead?
// ...
}
```

That would be less surprising behavior to return a newly constructed object rather than silently failing.  And also, an update to the documentation example for the case of the creation of empty bounds would be helpful, regardless of the decision here.

Perhaps this?

```
 * ```js
 * var corner1 = L.latLng(40.712, -74.227),
 * corner2 = L.latLng(40.774, -74.125),
 * bounds = L.latLngBounds(corner1, corner2);

 * var corner3 = LatLng( 42, -76 ),
 * bounds2 = L.LatLngBnds( );
 * bounds2.extend( corner1 );
 * bounds2.extend( corner2 );
 * bounds2.extend( corner3 );
 * ```
```

The use case is for iterating a list of coordinates supplied from a 3rd party in random order and of unknown range (i.e. store locator search results), to create markers for each on the map, then set the view with proper bounds and zoom using L.fitBounds( bounds ).  Thus the need to start with an empty bounds.

**Comment by johnd0e** [comment]
> That would be less surprising behavior to return a newly constructed object rather than silently failing.

It does not fail.
You just use it wrong.

Either use constructor form properly: `new L.LatLngBounds()`.
Or use factory form: `L.latLngBounds()`.

**Comment by Leif-W** [comment]
I would just like to state that I completely disagree.  The documentation shows only the factory form, not the constructor form.  Regardless which form is used, given two coordinates yields the same result whereas the factory form does not consider an empty list - the most common use case - as valid, nor does the documentation address this.  Surprising behavior for a common valid use case is a failure of either design or documentation.

While I would be willing to make contributions to improve the situation, it would be nice if the leadership were open to discussion and improvements rather than be dismissive and abrupt.

**Comment by IvanSanchez** [comment]
You're calling a constructor without the [`new` operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new), and that returns `undefined`. That's behaviour as expected (in Leaflet and anywhere else in JS), and there's not room for discussion or improvement over a documented quirk of ECMAscript.

You're free to feel angry at how ECMAscript prototypal inheritance and object instantiation works. And there's nothing we Leaflet folks we can do about it.
