### ISSUE TITLE
cdn.leafletjs.com is using cloudfront.net certificate

### ISSUE THREAD

**Issue by mikemcc** [Leaflet/Leaflet#7165]
https://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css

- [ ] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [ X] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [ ] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- step 1. point your browser at https://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css
- step 2. when you get a certificate error, view details.
- step 3. note that the TLS certificate used is a cloudfront.net certificate, not a leafletjs.com cert.

**Expected behavior**

expect correct TLS handshake.

**Current behavior**

TLS error in browser because of domain mismatch. Confirmed with safari, firefox, chrome.

**Comment by IvanSanchez** [comment]
We don't do handle anything regarding 0.7.x since four years ago, and the instructions on https://leafletjs.com/download.html don't say anything relative to https://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css as well.

Consider upgrading to 1.6.0 (using the unpkg.com CDN) or consider self-hosting.
