### ISSUE TITLE
detectRetina causes wild cursor behavior on Android

### ISSUE THREAD

**Issue by jguddas** [Leaflet/Leaflet#7166]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
Adding a `polyline` and having `detectRetina` enabled.

**Expected behavior**
The cursor should not jump all over the place

**Current behavior**
The cursor jumps all over the place, clicking even outside the window, opening new tabs, etc.

**Environment**
- Leaflet version: 1.6.0
- Browser (with version): Chrome for Android version 83.0.4103.83 and Firefox for Android version 68.8.1
- OS/Platform (with version): Android version 7.0

**Additional context**
It appears to only happen once the polyline is in view.

**Minimal example reproducing the issue**

source: http://bl.ocks.org/jguddas/d9708a1244bbe80574f939fb792dc023
demo: http://bl.ocks.org/jguddas/raw/d9708a1244bbe80574f939fb792dc023

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by johnd0e** [comment]
Not enough info to reproduce the issue.

Is it happening while you are dragging the map with mouse?
Or what 'cursor' do yo mean?

**Comment by jguddas** [comment]
1. Open Settings on the Android device.
2. Scroll to the very bottom of the menu and select ‘About phone’.
3. Scroll to the very bottom of the menu and select ‘Build number’ repeatedly. After the 7th or 8th click you should see a message telling you that you are a developer.
4. Click back to return to the main Settings menu.
5. There should be a new ‘Developer Options’ option above to ‘About phone’ option. Select ‘Developer Options’.
6. Under the ‘Input’ heading there is a ‘Show touches’ option. Selecting this will show all touch events on the screen including pinch to zoom gestures and so on.
7. Open http://bl.ocks.org/jguddas/raw/d9708a1244bbe80574f939fb792dc023 with chrome.
8. See a bunch of touch events (which are now shown as dots) flickering all over your screen and behaving like user input.

---

i can make a video but there does not seem to be much interest in this issue

**Comment by johnd0e** [comment]
Sorry, still unable to reproduce.

**Comment by jguddas** [comment]
Thanks, I will keep an eye out for what might be causing this on my phone.
