### ISSUE TITLE
Make in leaflet custom icons with different colors

### ISSUE THREAD

**Issue by PetroGromovo** [Leaflet/Leaflet#7167]
I make leaflet@1.6.0 custom icons from docs https://leafletjs.com/examples/custom-icons/
and I need to give possiblity for users  set select custom colors for these icons
and I wonder if there is a way to set colors to custom icons?
Like I do for markers :

```
      markers: [{
                    id: 1,
                    location: L.latLng(47.413220, -1.219482),
                    color: '#c11a1a',
                    strokeColor: '#d73534',
                    circleColor: '#590000',
                    content_text: ' <strong>content text</strong> #1',
                    opened: true
                },
```
?
If yes, how ?

Thanks!

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by IvanSanchez** [comment]
And yes, I've seen https://stackoverflow.com/questions/62167881/make-in-leaflet-custom-icons-with-different-colors . If you're not getting an answer there, do not expect an answer here.
