### ISSUE TITLE
With leaflet in bootstrap-vue remove default dialog popup on marker's click

### ISSUE THREAD

**Issue by PetroGromovo** [Leaflet/Leaflet#7169]
Hello,
In vue/ bootstrap-vue app with leaflet 1.6.0 I make custom modal dialog on marker clicking
and I can not remove default dialog popup. I do

```
                let nextMarker = this.leaflet.marker(
                    [nextLocationPoint.lat, nextLocationPoint.lng], {icon: markerIcon})
                    .addTo(locationsMap)
                    .bindPopup(nextLocationPoint.title)
                    .on('mouseover', this.locationMarkerOnMouseOver)
                    .on('click', this.locationMarkerOnClick)  

        methods: {

            locationMarkerOnClick(e) {
                console.log('locationMarkerOnClick e::')
                console.log(e)

                // e.stopPropagation()  // THIS RAISE ERROR
                // e.preventDefault()  // THIS RAISE ERROR
                
                e.cancelBubble = true
                window.event.cancelBubble = true  // NOTHING OF THESE METHODS
                window.event.preventDefault(e)
                window.event.stopPropagation()

                this.$bvModal.show('viewAdLocationModal')

                return false
            }, // locationMarkerOnClick(e) {

```

I know that in vuejs syntax like :
`<div @click.stop.prevent.self="">`
OR
`@click.prevent="handleClick"`
But if it can be used for my case with leaflet?

How to fix this issue?

```
    "bootstrap-vue": "^2.3.0",
    "vue": "^2.6.11",

```
Thanks!

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.
