### ISSUE TITLE
I found I cannot extend Event.js.I need to remove Many events functions

### ISSUE THREAD

**Issue by JokerSora** [Leaflet/Leaflet#7171]
Maybe We can add a new method which can remove events functions in a batch way.
so just like a new attributes 'offMany'  like that offMany(types, fns, context) 
the 'fns' is an array of functions.
or How can I use map.offMany by other ways (I don't want to user an imported function to do this)

**Comment by JokerSora** [comment]
or maybe we can allow the param 'fn' as an array of functions to avoid add new attribute,just by test the type of 'fn'

**Comment by johnd0e** [comment]
I do not think that such complication is necessary.
You can use something like this:
```
{fn1,fn2,fn3}.forEach(function (fn) {
  obj.off(type,fn);
});
```

**Comment by JokerSora** [comment]
> I do not think that such complication is necessary.
> You can use something like this:
> 
> ```
> {fn1,fn2,fn3}.forEach(function (fn) {
>   obj.off(type,fn);
> });
> ```

so I neet to write such code every time I need such function?
I already known I can write a function to import,but I think leaflet should support the batch way,just like arcgis api for js which has a lot of batch ways. 
or can we give a way for users to extent the Event.js?

**Comment by JokerSora** [comment]
leaflet has a lot of extension js ,however ,I found no extension of Event,so maybe we can give an access to users to extent the Event.js

**Comment by IvanSanchez** [comment]
> We can add a new method which can remove events functions in a batch way.

That's already implemented, and is documented as an overload of the [`.on`/`.off` methods](https://leafletjs.com/reference-1.6.0.html#evented-on) of any `Evented`:

> `on(<Object> eventMap)` | this | Adds a set of type/listener pairs, e.g. `{click: onClick, mousemove: onMouseMove}`
> `off(<Object> eventMap)` | this | Removes a set of type/listener pairs.

**Comment by JokerSora** [comment]
> > We can add a new method which can remove events functions in a batch way.
> 
> That's already implemented, and is documented as an overload of the [`.on`/`.off` methods](https://leafletjs.com/reference-1.6.0.html#evented-on) of any `Evented`:
> 
> > `on(<Object> eventMap)` | this | Adds a set of type/listener pairs, e.g. `{click: onClick, mousemove: onMouseMove}`
> > `off(<Object> eventMap)` | this | Removes a set of type/listener pairs.
could you tell me,how can I handle the status below?
I has threefunctions a1,a2,b to remove,but i want to remove the function starts with 'a',I don't want to remove all click functions.
I had known that I can find the target functions from map._events.click and filter the target functions to remove them,but I need an attributes which can accepts an array of functions.
so can you show me how to use the off(<Object> eventMap)?
`let a1=e=>{
        alert("a1");
      };
      let a2=e=>{
        alert("a2");
      };
 let b=e=>{
        alert("bbb");
      };
map.on('click',a1);
map.on('click',a2);
map.on('click',b);
map.off()?
use the off(<Object> eventMap)?
`

**Comment by IvanSanchez** [comment]
For that specific case, just iterate through the functions and call `.off()` in each iteration. There's gonna be no performance difference. Or call `map.off('click')` then re-attach `map.on('click', b)`. O see no clear use case for attaching/detaching an array of functions.

**Comment by JokerSora** [comment]
> For that specific case, just iterate through the functions and call `.off()` in each iteration. There's gonna be no performance difference. Or call `map.off('click')` then re-attach `map.on('click', b)`. O see no clear use case for attaching/detaching an array of functions.

my team worked together on the same map object. so the map events functions that we use have some name rules such as named as a prefix "a_" or a prefix "b_" ...
so,we meet a lot of status that we need to filter the functions to remove,
I said I known we can write a function to import ,however, I think leaflet should have a method to do this,or at least,we can extend Event.js to realize this.

**Comment by johnd0e** [comment]
> we can extend Event.js to realize this.

Sure you can: https://leafletjs.com/reference-1.6.0.html#class-include

**Comment by IvanSanchez** [comment]
> my team worked together on the same map object. so the map events functions that we use have some name rules such as named as a prefix "a_" or a prefix "b_" so, we meet a lot of status that we need to filter the functions to remove,

No; what you do is you provide some API hook or function call to attach or detach all the events that a piece of code is responsible of, so any other piece of code doesn't need to care about the internal naming of events; this is in accordance with the [loose coupling](https://en.wikipedia.org/wiki/Loose_coupling) principle.

**Comment by IvanSanchez** [comment]
> Sure you can: https://leafletjs.com/reference-1.6.0.html#class-include

Speaking of which:

```
L.Evented.include({
  offAllType(type, fns) {
    for (var i=0; i<fns.length; i++) {
      this.off.call(this, type, fns[i]);
    }
  }
})
```

**Comment by JokerSora** [comment]
> > Sure you can: https://leafletjs.com/reference-1.6.0.html#class-include
> 
> Speaking of which:
> 
> ```
> L.Evented.include({
>   offAllType: function offAllType(type, fns) {
>     for (var i=0; i<fns.length; i++) {
>       this.off.call(this, type, fns[i]);
>     }
>   }
> })
> ```
it works!
thank you very much, and then I have a good idea to handle a lot of event functions.I may wirte a leaflet plug-in to realize such status which has a lot of event functions

**Comment by JokerSora** [comment]
> > my team worked together on the same map object. so the map events functions that we use have some name rules such as named as a prefix "a_" or a prefix "b_" so, we meet a lot of status that we need to filter the functions to remove,
> 
> No; what you do is you provide some API hook or function call to attach or detach all the events that a piece of code is responsible of, so any other piece of code doesn't need to care about the internal naming of events; this is in accordance with the [loose coupling](https://en.wikipedia.org/wiki/Loose_coupling) principle.

I had a good idea to handle lots of events functions. Your opinion seems to suit current event handle function. I may identify a new way to realize event handle function to suit my team's events manage. After all,thank you very much!
