### ISSUE TITLE
Changing number of markers visible with different zoom

### ISSUE THREAD

**Issue by sergeynilov** [Leaflet/Leaflet#7172]
Hello,
With leaflet 1.6.0 I show listing of markers and some of them are featured(different custom icon)
and I need when setting zoom to low value to group several markers(by country) and show only one 
marker with visible label “Has 6 locations(2 featured)”. How can I do this?

I read about layergroup, but not sure how can I implement it ?

Example od what I want :
1) I have 5 markers for England(1 of them featured)
2) I have 4 markers for France(none of them is featured)

When zoom is reather small(like 7) I show all 9 markers on the map and they all looks good.
But if I change zoom to 2 then comman space of these 2 countries become small and these 9 markers
looks ugly . I need to show only 2 markers (1 for any of this countries) labels “5/1” and "4".
Clicking on one of these markers I need return to zoom 7 with markers of the selected country.

How can do it ?

Thanks!

**Comment by JokerSora** [comment]
I Think the issue you commit is no matter with leaflet self
whatever map js you may meet the issue
you can see this https://leafletjs.com/reference-1.6.0.html#map-zoomlevelschange
by watching zoomlevel change,you can filter the mark to show(default is random filter)
e ,the mark filter rule is another issue,you may search for it from google

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by IvanSanchez** [comment]
And start at https://leafletjs.com/plugins.html#clusteringdecluttering
