### ISSUE TITLE
Classic styles are no longer supported  #urgent

### ISSUE THREAD

**Issue by shahidul24** [Leaflet/Leaflet#7173]
Hi,
I am getting issue on using Leaflet js.
The issue is **{"message":"Classic styles are no longer supported; see https://blog.mapbox.com/deprecating-studio-classic-styles-d8892ac38cb4 for more information"}**

And the screenshot of browser 1. ( [https://prnt.sc/sxthdf](https://prnt.sc/sxthdf) ).   
2. [https://prnt.sc/sxtj0l](https://prnt.sc/sxtj0l)
Maps invisible. 

Thank you.

**Comment by IvanSanchez** [comment]
The issue is about the tile provider, not about Leaflet itself.
