### ISSUE TITLE
One finger panning on andriod sometimes breaks and the user has to default to two fingers

### ISSUE THREAD

**Issue by Ali-Shah-Vis** [Leaflet/Leaflet#7175]
- [ x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [ x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [ x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- Step 1: have a leaflet map on mobile with markers
-Step 2: Zoom in a lot and pan around with one finger
-Step 3: Eventually the panning with one finger will stop working and you have to use two fingers

**Expected behavior**
One finger panning works 100% of the time regardless of zoom level

**Current behavior**
One finger panning breaks, so does the ability to zoom in and out.

**Environment**
- Leaflet version:
- Browser (with version): Chrome
- OS/Platform (with version): Android

**Comment by johnd0e** [comment]
Unable to reproduce

**Comment by IvanSanchez** [comment]
Not enough info to reproduce (would need Leaflet version, browser version and, in this case, details about the hardware platform as well as making sure that this is vanilla Leaflet with no JS frameworks messing stuff up, and amount of time *or* zoom interactions *or* pinch interactions needed to trigger the issue).

**Comment by Ali-Shah-Vis** [comment]
Can you just tell me what options I need to have in order to ensure mobile leaflet 1 finger dragging works?

**Comment by IvanSanchez** [comment]
None, since https://leafletjs.com/reference-1.6.0.html#map-dragging is `true` by default.

At this point I must suggest reading https://www.chiark.greenend.org.uk/~sgtatham/bugs.html
