### ISSUE TITLE
Reducing z-index values for compatibility reasons

### ISSUE THREAD

**Issue by Socrapop** [Leaflet/Leaflet#7176]
### Is your feature request related to a problem? Please describe.
I don't understand why `.leaftlet-pane` has `z-index: 400;` and `.leaflet-top, .leaflet-bottom` has `z-index: 1000;`. It's easily breaking other elements on the page like a popup or overlay.

Is there an explanation? 

Bug report https://github.com/Leaflet/Leaflet/issues/6341#issue-360882745 is speaking about that too.

### Describe the solution you'd like
I'd like to see a less brutal z-index scale. Like from 1 to 100. Or even 1 to 20. For exemple:
```
.leaflet-pane {
    z-index: 2;
}
.leaflet-top, .leaflet-bottom {
    z-index: 10;
}
``` 

### Describe alternatives you've considered
Well, none, just close this ticket :) I didn't know if it was a feature or "we did not think of that" problem.
I also understand that it's hard to change this now, as a lot of leaflet plugins may use those `z-index` to add elements on the map.

**Comment by IvanSanchez** [comment]
No need. Set your own [stacking contexts](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context). The Leaflet stance about this issue so far is that users should decide whether the map container should be a separate stacking context or not (the default being not)
