### ISSUE TITLE
When can we expect a new release of leaflet?

### ISSUE THREAD

**Issue by NikoFoX** [Leaflet/Leaflet#7177]
Hello,
Since November '19 there wasn't any new release and using actual leaflet gives errors (e.g. https://github.com/Leaflet/Leaflet/issues/6981).
I'm sure I'm not the only one waiting for the fix.

Do you know when can we expect new release?

**Comment by simon04** [comment]
Version 1.7.1 has been released on 2020-09-04, this issue can be closed.
