### ISSUE TITLE
Populate Polygon Popup with ajax

### ISSUE THREAD

**Issue by nicksterFL** [Leaflet/Leaflet#7183]
How would I populate my popups on polygons via ajax?

What I'd like to do is populate the popup via ajax content onClick of the polygons.

I have the following:

var map = L.map("map", {maxZoom: 13});
L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}").addTo(map);

map.setView([27.4989278, -82.5748194], 10);

var mcg = L.markerClusterGroup({
  showCoverageOnHover: false
}).addTo(map);

var coverages = new L.LayerGroup();

mcg.on("animationend", function() {
	  coverages.clearLayers();
	  
	  mcg._featureGroup.eachLayer(function(layer) {
		  
		if (layer instanceof L.MarkerCluster && layer.getChildCount() > 1) {
		  //mcg._showCoverage({ layer: cluster });
		 var PolySet = L.polygon(layer.getConvexHull(),{color:'red'});

		  PolySet.bindPopup("<BR>test Pop <BR>"+ layer.getConvexHull());
		  
		  coverages.addLayer(PolySet);
		}
		coverages.addTo(map);
	  });
});

		var markers = L.markerClusterGroup();
		
		for (var i = 0; i < addressPoints.length; i++) {
			var a = addressPoints[i];
			var marker = L.marker(new L.LatLng(a[0], a[1]), {title: 'tester'});
			marker.bindPopup(title+' here').openPopup();
			L.marker(new L.LatLng(a[0], a[1])).addTo(mcg);
		}

	
mcg.fire("animationend");

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
