### ISSUE TITLE
map is not draggable after refreshing the map

### ISSUE THREAD

**Issue by darda-ergo** [Leaflet/Leaflet#7186]
![image](https://user-images.githubusercontent.com/61325474/85921596-17649500-b89f-11ea-99fb-2c1123a5d797.png)

I am using leaflet and react-leaflet both on react project which is based on mapping . I need to change state from react project and based on this state i need to refresh the map and change properties of map

**Comment by doplumi** [comment]
I also encountered this today on Safari in the beta of iOS 14

Can't reproduce on Android or iOS < 13

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.

**Comment by darda-ergo** [comment]
Understood
