### ISSUE TITLE
Is "thisLayerGroup.removeLayer(thisLayerID)" asynchronus?

### ISSUE THREAD

**Issue by mrtobie** [Leaflet/Leaflet#7188]
Hey there,

i currently struggeling as i first uploaded my Website. On Chrome it works perfectly, but on Edge it seems like the browser is too slow to remove the layer before the user can interact with the website again. Therefore i was thinking about adding a callback to my function.

-----------------------------
Little more detail:

I trigger showing of my Layer via checkboxes. 
Is the checkbox checked -> add the Layer (asynchronously added geoJSON-Data, works perfectly).
When unchecking the checkbox -> remove the Layer (stored in a layerGroup)

Now if a user fastly clickes the checkbox again after it was clicked to be unchecked, the layer gets added again on top but the old one was never removed.

----------------------------

Functions:

```
function showBorders(kreisID, kreiseArrIndex) {
    userWait(); //makes waitngscreen
    var xhr = new XMLHttpRequest();
    var path = "lib/leaflet/kreise/" + kreisID + ".geojson";
    xhr.open("GET", path);
    xhr.setRequestHeader("Content-Type", "application/json");
    xhr.onload = function () {
        if (xhr.status === 200) {
            var thisLayer = L.geoJSON(JSON.parse(xhr.responseText), {
                style: kreiseStyle,
            }).addTo(layerGroupKreise);
            var thisLayerID = L.stamp(thisLayer);
            kreisInformation[kreiseArrIndex].layerID = thisLayerID;
            userGo(); //disables waiting screen
        }
    };
    xhr.send();
}

function unshowBorders(layerID) {
    layerGroupKreise.removeLayer(layerID);
}
```

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
