### ISSUE TITLE
Docs of LatLngBounds.overlaps are wrong

### ISSUE THREAD

**Issue by DerZade** [Leaflet/Leaflet#7190]
The docs say, that the first and only parameter of `LatLngBounds.overlaps` is a Object of type `Bounds` ([see here](https://leafletjs.com/reference-1.6.0.html#latlngbounds-overlaps)) although the code expects a `LatLngBounds` Object ([see here](https://github.com/Leaflet/Leaflet/blob/e8c28b996179373447dde1df479898576a508579/src/geo/LatLngBounds.js#L201)), which makes a lot more sense. So this is - at least in my opinion - not a bug but wrong documentation.

- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- Create `LatLngBounds`-Object
- Create `Bounds`-Object
- Call `overlaps` of the `LatLngBounds`-Object with the `Bounds`-Object as parameter

**Expected behavior**
No error (at least according to the docs)

**Current behavior**
- `LatLngBounds.overlaps` fails when called with a `Bounds` Object:
   ![img](https://i.imgur.com/lfH0pUw.png)
- `LatLngBounds.overlaps` works fine when called with another `LatLngBounds`-Object as the parameter

**Environment**
- Leaflet version: 1.60
- Browser (with version): Chrome Desktop Version 83.0.4103.116
- OS/Platform (with version): Windows 10 Version 2004 (Build 19041.330)

```js
const latLngBounds = map.getBounds();
const bounds = map.getPixelBounds();

console.log(latLngBounds.overlaps(bounds))
```
[Example Link](https://plnkr.co/edit/hbeBKMzayRscrLBi)

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by DerZade** [comment]
I guess the docs are auto-generated from the comments within the code, but I'm not sure if that's actually the case. So if someone could confirm that I would be happy to open a PR.

**Comment by IvanSanchez** [comment]
The answer you seek is at https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md#api-documentation ;-)

**Comment by ronikar** [comment]
@DerZade , Did you fix the relevant comments?

**Comment by DerZade** [comment]
> @DerZade , Did you fix the relevant comments?

@ronikar Yep. A couple of line above your comment is [the merged PR](https://github.com/Leaflet/Leaflet/pull/7194).
