### ISSUE TITLE
Events that want to support the tablet

### ISSUE THREAD

**Issue by gutianxing** [Leaflet/Leaflet#7199]
Hi, thanks for using such a great plug-in, but I recently had a small problem. The click event of the tablet is not supported. Can you support it, such as pointerdown event, pointerup event and pointermove event? Thank you very much

**Comment by IvanSanchez** [comment]
Leaflet has support for `PointerEvent`s since https://github.com/Leaflet/Leaflet/pull/2066 (from 2013). 

If this is a bug, you'll have to be more specific.

**Comment by gutianxing** [comment]
Thank you for your answer.But what I mean is whether to add a pointer event to a binding event, specifically, to add a pointer event to the onoff function.For example :

onOff(this._container, 'click dblclick mousedown mouseup ' +
			'mouseover mouseout mousemove contextmenu keypress keydown keyup pointerdown pointermove pointerup', this._handleDOMEvent, this);

**Comment by johnd0e** [comment]
Duplicate of #5556

**Comment by IvanSanchez** [comment]
I see. But that would mean making sure that the logic for wrapping a `PointerEvent` in a data structure similar to https://leafletjs.com/reference-1.6.0.html#mouseevent works fine... and it's a **lot** of work to get it right.

I've written up #7200 - that's a catch-all issue for some work (that I believe to be necessary) to make sense of `PointerEvent`s.

**Comment by gutianxing** [comment]
Thank you very much.
