### ISSUE TITLE
Error: Map container is already initialized.

### ISSUE THREAD

**Issue by artsandrade** [Leaflet/Leaflet#7208]
Dear friends, I am testing the map using a recursive function to simulate a real-time update of a marker's map. I tried to search for all the alternatives in the forums but I didn't find anything that really worked and, every time I run the html file, I have the following error: Map container is already initialized.

Below is the code I'm testing:

<html>
  <head>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.3/dist/leaflet.css" integrity="sha512-07I2e+7D8p6he1SIM+1twR5TIrhUQn9+I6yjqD53JQjFiMf8EtC93ty0/5vJTZGF8aAocvHYNEDJajGdNx1IsQ==" crossorigin=""/>
    
    <style>
      #location-map{
        background: #fff;
        border: none;
        height: 540px;
        width: 100%;

        box-sizing: border-box;
        -webkit-box-sizing: border-box;
        -moz-box-sizing: border-box;
      }
    </style>
  </head>
  <body>
    <div id="location-map"></div>
    
    <script src="https://unpkg.com/leaflet@1.0.3/dist/leaflet.js" integrity="sha512-A7vV8IFfih/D732iSSKi20u/ooOfj/AGehOKq0f4vLT1Zr2Y+RX7C+w8A1gaSasGtRUZpF/NZgzSAu4/Gc41Lg==" crossorigin=""></script>

    <script type="text/javascript">
        
        var z=50;
        var x=2;

        
        
        var recursiva = function () {            
            zz = z + ((Math.random() * 50) - 25) / 50;
            xx = x + ((Math.random() * 50) - 25) / 50;

            var map = L.map('location-map').setView([zz, xx], 17);
            mapLink = '<a href="https://openstreetmap.org">OpenStreetMap</a>';
            L.tileLayer(
                'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                    attribution: 'Map data &copy; ' + mapLink,
                    maxZoom: 20,
                }).addTo(map);
            var marker = L.marker([zz, xx]).addTo(map);
            
            console.log(zz,xx);
            setTimeout(recursiva,2000);
        }
        recursiva();
        
      
    </script>
  </body>
</html>

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by IvanSanchez** [comment]
If Leaflet tells you "Map container is already initialized.", then it means that you're initializing a map in a container when a leaflet map already exists in that container. Do `L.map('location-map')` **once** instead.

**Comment by arcontechnologies** [comment]
Thanks for your feedback. I understand your point here. But in my use case I have an initialized Map with drawing controls and so on and at certain point of time the user can trigger "routing". So I'm expecting to use something like this :
`L.tripgoRouting.initialize(options).addto(mymap); or .addcontrol(L.tripgoRouting(options))`
Unfortunatly,  this not the case in TripgoRouting.js
