### ISSUE TITLE
Circle that represents a wifi hotspot coverage area

### ISSUE THREAD

**Issue by daniela-waranie** [Leaflet/Leaflet#7210]
Sorry, i am new to Leaflet and not a JavaScript expert.

What is the best way to place a Leaflet marker to represent a Wifi hotspot (theoretical) coverage area (Circle; not a polygon), that represents a diameter of 35m and scales according to the zoom level. So "big circle" on zoomed in (high zoom numbers; where you can see buildings) and "small circle" when zoomed out (low zoom numbers; where your city fills the viewport), maybe switch to a needle-icon when very-far zoomed out (country-view, world-view). Optionally with opacity (e.g. 33%) so that you can see where multiple wifi hotspots areas overlap (in theory).

Do you have a snippet to start with?

**Comment by daniela-waranie** [comment]
More interesting ideas are (but not yet requested; just for inspiration):
- adding an additional circle to alow to represent (good quality range, and acceptable quality range; theoretical)
- replacing a theorecital coverage circle by a (messured) polygon 
- draw "sliced circles" (degree + orientation of that "piece")

**Comment by daniela-waranie** [comment]
CircleMarker has no option to scale based on zoom level, or to do the correct caculation of the diameter based on zoom level and desired number of meters.

**Comment by IvanSanchez** [comment]
https://leafletjs.com/reference-1.6.0.html#circle-radius

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
