### ISSUE TITLE
Make the disabled state of zoom controls available to ATs

### ISSUE THREAD

**Issue by Malvoz** [Leaflet/Leaflet#7211]
The `leaflet-disabled` class is set on zoom controls:
https://github.com/Leaflet/Leaflet/blob/71f73785c91f50821cee4f590c41b14eeddf394c/src/control/Control.Zoom.js#L102-L104
and styles are applied to convey a "disabled" state:
https://github.com/Leaflet/Leaflet/blob/71f73785c91f50821cee4f590c41b14eeddf394c/dist/leaflet.css#L310-L314

the zoom controls remain operable however, and the [state](https://www.w3.org/TR/WCAG21/#dfn-states) is not available to assistive technologies such as screen readers. There are at least 3 ways to convey the disabled state of buttons:

- `tabindex="-1"` - [Bing Maps](https://maps4html.org/HTML-Map-Element-UseCases-Requirements/examples/create-map.html#bing-maps-embed) for example, uses this approach. Though it may be confusing to keyboard-only users, as the button is then removed from the tab order.
- The [`disabled`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled) attribute - Not applicable (Leaflet uses `<a role="button">` as opposed to `<button>`).
- [`aria-disabled="true"`](https://www.w3.org/TR/wai-aria/#aria-disabled) - May or may not be as well supported as a negative `tabindex` or the `disabled` attribute, it does seem to be [well supported](https://a11ysupport.io/tech/aria/aria-disabled_attribute#support-table-1) though.

Whether `tabindex="-1"` or `aria-disabled="true|false"` is used (I personally vote for the latter), it could be set _in addition_ to the `leaflet-disabled` class for backwards compatibility.

<hr>

Implementing this may satisfy (parts of) the WCAG 2.1 Success Criterion: [1.3.1 Info and Relationships](https://www.w3.org/TR/WCAG21/#info-and-relationships) and [4.1.2 Name, Role, Value](https://www.w3.org/TR/WCAG21/#name-role-value) for the zoom controls.

**Comment by mourner** [comment]
@Malvoz great suggestion! Let's go with `aria-disabled` in addition to the current class. Would like to submit a PR for this?

**Comment by Augani** [comment]
Hello @mourner , can i take this?

**Comment by Malvoz** [comment]
@mourner Sorry for the delay! I'm happy to defer this to @Augani.

**Comment by AkshataJ96** [comment]
If the issue is still available, can i start looking into this? @mourner

**Comment by IvanSanchez** [comment]
@AkshataJ96 Nobody seems to be working on this on the moment, feel free to pick it up.

**Comment by Malvoz** [comment]
Fixed in https://github.com/Leaflet/Leaflet/pull/7280.
