### ISSUE TITLE
How to change text inside popup dynamically???

### ISSUE THREAD

**Issue by skm2000** [Leaflet/Leaflet#7218]
Hey @Leaflet I am trying to change the text inside the color dynamically,but I m not getting how to do it?Please help me figure it out
`const MyCircles = (props) => {
  return (
    props.data.map((row, i) => {
      if (row[props.date] <= 0) {
        return;
      }
      if (row["Lat"] != null && row["Long"] != null) {
        return (
          <Circle
            key={i}
            center={[row["Lat"], row["Long"]]}
            radius={1000 * Math.sqrt(row[props.date])}
            fillOpacity={0.8}
            `fillColor={props.color}`
            stroke={false}
          >
          {console.log('hi',props.color)};
          <Popup>
                <h5>{row[props.date]}</h5>
          </Popup>
          </Circle>
          )
        }
      }
    )
  );
}`
Inside the Popup I have tried the following...
1.`<Popup>
                <h5 style={{color:'{props.color}'}>{row[props.date]}</h5>
   </Popup>`
2.`<Popup>
                <h5 style={{color:'(props.color)'}>{row[props.date]}</h5>
   </Popup>
`
None of them worked out.Please help me how can I set the color of the text inside the Popup div to the "props.color"..
"props.color" is printing the corrent color but it's not getting added to the text.Help me asap...
Thanks.

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.
