### ISSUE TITLE
It seems to me that the zoomend event is missing a tick

### ISSUE THREAD

**Issue by Vin4er** [Leaflet/Leaflet#7219]
We have a css transition on the polyline. This is a kind of vector, the animation of which shows the direction, from point A to point B.
play css transition on "zoomend" event.

I change
1. Map size
2. make fitBounds in two coordinates

If I play it without
1.setTimeout (() => {}, 10)
2.window.requestAnimationFrame (() => {})
I have an unfinished animation for resizing the map, which is why my animation is not calculated correctly for my polyline.

It seems to me that the zoomend event is missing a tick.

Leaflet.js 1.4
all browsers
macos\win\ubuntu

**Comment by IvanSanchez** [comment]
I don't understand the problem.

I don't know what you mean by "tick". Please explain further, add a reproducible example, test out with the latest available Leaflet version (1.6).
