### ISSUE TITLE
NativeScript support for Android & IOS

### ISSUE THREAD

**Issue by abbas001** [Leaflet/Leaflet#7220]
Do we have any plan to make Leaflet compatible with [NativeScript](https://nativescript.org) for mobile development as [Mapbox](https://github.com/Yermo/nativescript-mapbox) did for Android and IOS?

**Comment by IvanSanchez** [comment]
Current list of frameworks/integrations that we've been asked to support/debug :

* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium

And now:

* NativeScript

**Comment by abbas001** [comment]
**Thanks a lot for the replay**. 

Currently, I am using leaflet for vanilla web browsers app only but we are moving toward a concept of single code base for all platform that why I want to leverage the code of leaflet to [NativeScript](https://nativescript.org/). 

But I will find some other way for the [NativeScript](https://nativescript.org/).
