### ISSUE TITLE
Uncaught TypeError: Cannot read property 'baseVal' of undefined in SvgOverlay

### ISSUE THREAD

**Issue by filipjakov** [Leaflet/Leaflet#7221]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behaviour is documented and expected

- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)

- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- use svgOverlay with the first parameter set as an URL to the svg

**Expected behavior**
- svg should load via url

**Current behavior**
- error: "Uncaught TypeError: Cannot read property 'baseVal' of undefined"
- ImageOverlay has the ability to provide the url to the image. Since SVGOverlay extends ImageOverlay, i expect the same can be done

**Environment**
- Leaflet version: ^1.6.0,
- Browser (with version): any
- OS/Platform (with version): any

**Minimal example reproducing the issue**

` L.svgOverlay(url, bounds).addTo(map)`

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by IvanSanchez** [comment]
> use svgOverlay with the first parameter set as an URL to the svg

Show some Javascript code used to do that, please. It's not easy to debug something when there's no straightforward way to reproduce (i.e. load an example webpage which triggers the bug)

**Comment by filipjakov** [comment]
https://github.com/Leaflet/Leaflet/pull/6517#issuecomment-464656610

> Tried to improve it by loading an element with XHR, but i don't have much time now to wrap it all around.
I think it's better to keep it simple by now.

That solves it

**Comment by maximbroos** [comment]
I see this issue is closed, but I still bump into the same issue. I can't fully grasp @filipjakov his answer. 
`
L.svgOverlay("https://upload.wikimedia.org/wikipedia/commons/a/a5/Example_svg.svg", bounds, {pane: "imageOverlays",}).addTo(map)
 `
 This still throws the baseval error. What's the easiest workaround to work with xhr?
