### ISSUE TITLE
Hello, in Leaflet, given latitude and distance and Angle, how do you find another latitude and longitude point?

### ISSUE THREAD

**Issue by WebHero0544** [Leaflet/Leaflet#7224]
Hello, in Leaflet, given latitude and distance and Angle, how do you find another latitude and longitude point?

**Comment by IvanSanchez** [comment]
https://geographiclib.sourceforge.io/

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
