### ISSUE TITLE
Dispatch Wheel event

### ISSUE THREAD

**Issue by de-don** [Leaflet/Leaflet#7225]
https://github.com/Leaflet/Leaflet/blob/dd832105697c98c1fca5475616377cda66f876be/src/map/handler/Map.ScrollWheelZoom.js#L59

I need to catch `wheel` event on the map, to hide some external popovers.
I can't listen to the "wheel" event, because code of "leaflet" stops this event.

How can I get this event?

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by de-don** [comment]
I have solved my problem by adding additional listener for map element:
```javascript
    mapElement.addEventListener('wheel',  (e: WheelEvent) => {
      const target = <HTMLInputElement>e.target;
      if (target.parentElement !== null) {
        target.parentElement.dispatchEvent(new WheelEvent(e.type, e));
      }
    });
```
