### ISSUE TITLE
Tiles are not visible when using maxNativeZoom and fadeAnimation set to false

### ISSUE THREAD

**Issue by jfrankl** [Leaflet/Leaflet#7227]
Map tiles are not visible when using maxNativeZoom and `fadeAnimation: false` when zoomed past a certain level. The tiles seem to disappear at five zoom levels above the maxNativeZoom.

- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- Create a `tileLayer` with `maxNativeZoom: 0`
- Set `fadeAnimation: false`
- Zoom in on the map; after zooming in 5 levels, the tiles disappear on Chrome

**Expected behavior**
You should be able to zoom in without tiles disappearing.

**Current behavior**
Tiles disappear after zooming in approximately 5 levels.

**Environment**
- Leaflet version: 1.6.0
- Browser (with version): Chrome 84.0.4147.105
- OS/Platform (with version): Mac OS X 10.15.4

**Additional context**
- This issue seems to have been introduced in Chrome 84. I can't reproduce it in earlier versions
- The tiles are represented in the DOM, but they aren't visible on the screen

**Minimal example reproducing the issue**

<s>https://codepen.io/lknarf/pen/OJMeZEy</s>

- Zoom in as far as you can—zoom level 5—and tiles disappear
- Set `fadeAnimation: true` and the issue is fixed

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by rafaelgalani** [comment]
By debugging with your provided example, it looks like the reason behind the fix with the `fadeAnimation` flag is the CSS class added by it (`.leaflet-fade-anim`). 

```css
.leaflet-fade-anim .leaflet-tile {
	will-change: opacity;
	}
```

If the `will-change` property is setted on the `.leaflet-tile` elements, then this issue doesn't happen..

**Comment by Malvoz** [comment]
@jfrankl Your codepen was deleted. Are you able to reproduce this in v1.8.0?

**Comment by jfrankl** [comment]
@Malvoz I can't reproduce this in the latest version of Chrome, so I am going to close the issue.
