### ISSUE TITLE
 The Google Maps feature has stopped working.

### ISSUE THREAD

**Issue by wagnercasadriver** [Leaflet/Leaflet#7231]
Google maps feature has stopped working, can be tested in the full example from the official page https://leaflet.github.io/Leaflet.draw/docs/examples/full.html

- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**

After my source stopped working I went to the official page to validate it. https://leaflet.github.io/Leaflet.draw/docs/examples/full.html

**Expected behavior**
When clicking on the radio button Google should display the google map.

**Current behavior**
You are not displaying the map correctly.

**Environment**
- Leaflet version: Last version
- Browser (with version): Google Chrome 84.0.4147.105 64 bits
- OS/Platform (with version): Windows 10 Pro

**Minimal example reproducing the issue**
For testing, you can use the full example link on the official page https://leaflet.github.io/Leaflet.draw/docs/examples/full.html

- [x] this example is as simple as possible
- [ ] this example does not rely on any third party code

**Comment by johnd0e** [comment]
Wrong repo.
Open issue here: https://github.com/Leaflet/Leaflet.draw.
