### ISSUE TITLE
tileLayer "load" event fires before zoomAnimation is finished?

### ISSUE THREAD

**Issue by foundryspatial-duncan** [Leaflet/Leaflet#7234]
This is a bit hard to reproduce, but I have a setup where a Puppeteer (headless Chrome) takes a snapshot of the page as soon as the map's tile layer fires its "load" event, and the snapshots are showing the bottom-right map tile still grey/unloaded.

I wonder if this is because the fade in animation isn't complete yet? Or is the tile just not loading at all for some reason?

**Comment by gwillig** [comment]
Hey  foundryspatial-duncan ,

where you able to fix that issue?

**Comment by foundryspatial-duncan** [comment]
I haven't noticed it lately, but I don't think we did anything specific to work around it... Are you noticing it too? I can't say I'm confident that it's solved yet.

**Comment by gwillig** [comment]
What was your solution so far?

**Comment by foundryspatial-duncan** [comment]
When I initialize the map, I added these options:
```
            // disable animations
            fadeAnimation: false,
            zoomAnimation: false,
```
Since this is a static map that is just being used in Puppeteer, I didn't want any animations anyway. The ` fadeAnimation: false` option means the tiles will pop in as soon as they're loaded, with no fade transition.
I can use it with Puppeteer this way. But, if I left the animations on, I'd still like an event to fire after the animation finished!

**Comment by natBizitza** [comment]
> When I initialize the map, I added these options:
> 
> ```
>             // disable animations
>             fadeAnimation: false,
>             zoomAnimation: false,
> ```
> 
> Since this is a static map that is just being used in Puppeteer, I didn't want any animations anyway. The ` fadeAnimation: false` option means the tiles will pop in as soon as they're loaded, with no fade transition. I can use it with Puppeteer this way. But, if I left the animations on, I'd still like an event to fire after the animation finished!

Thank you! This was the case for me too.

**Comment by IvanSanchez** [comment]
Closing as "has workaround"
