### ISSUE TITLE
Render Incomplete leaflet map

### ISSUE THREAD

**Issue by chuanpham** [Leaflet/Leaflet#7238]
This is my code:
`import React, { Component } from 'react';
import { Map, TileLayer, Marker, Popup } from 'react-leaflet';

class MapComponent extends Component {

    constructor() {
        super();
        this.state = {
          lat: 51.505,
          lng: -0.09,
          zoom: 13,
        };
      }

    invalidateMap = () => {
        if (this.refs.map) {
            this.refs.map.leafletElement.invalidateSize();
        }
    }

   
    render() {
        const position = [this.state.lat, this.state.lng];
        return (
            <div>
                 <Map center={position} zoom={this.state.zoom} ref="map"  onDragEnd={this.invalidateMap()} >
                    <TileLayer
                    url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
                    attribution="&copy; <a href=&quot;http://osm.org/copyright&quot;>OpenStreetMap</a> contributors"
                    />
                    <Marker position={position}>
                    <Popup>
                        <span>A pretty CSS3 popup. <br/> Easily customizable.</span>
                    </Popup>
                    </Marker>
                </Map>
            </div>
           
        );
    }
}

export default (MapComponent);`

And this is what i get:
![image](https://user-images.githubusercontent.com/50976620/90357153-26381e80-e07c-11ea-94fd-d32a03f43fd0.png)

I have tried some available solutions but it didn't work out. How can i solve this problem, thanks very much!!!

**Comment by siimots** [comment]
CSS is missing.

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* NativeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.

**Comment by dwasil** [comment]
Hi!
I have the same problem, with using it inside the ES6 module.
Where aren't any errors in JS console.

**Comment by gx200918** [comment]
> Hi!
> I have the same problem, with using it inside the ES6 module.
> Where aren't any errors in JS console.

I got the same problem,  have you solved it ?

**Comment by dwasil** [comment]
> CSS is missing.
As siimots mentioned the problem was in CSS.
