### ISSUE TITLE
Using the LmageOverlay class in the zoom map is some zoom level does not show the image

### ISSUE THREAD

**Issue by WebHero0544** [Leaflet/Leaflet#7241]
hi, Using the LmageOverlay class in the zoom map is some zoom level does not show the image, I don't know why

**Steps to reproduce**

          var map = L.map(this.$refs.map, {
                center: [40.55777, 115.81333],
                zoom: 5,  //8
                minZoom: 3,
                maxZoom: 18,
                attributionControl: false,
                zoomControl: false
            })
            L.tileLayer('http://t{s}.tianditu.com/DataServer?T=ter_w&X={x}&Y={y}&L={z}&tk=b055e3a80de633c788f673dfcb164aa4',      {
                zIndex: 0,
                subdomains: ['0', '1', '2', '3', '4', '5', '6', '7']
            }).addTo(map)

           const range = {
                east: 125.156,
                north: 39.9097,
                south: 31.9522,
                west: 112.5
            }
            const bound = L.latLngBounds(L.latLng(range.south, range.west), L.latLng(range.north, range.east))
            const layer = L.imageOverlay(require('./img/radar.png'), bound, {
              zIndex: 100
            }).addTo(map)

**Expected behavior**
The image should always be displayed when the map is zoomed in and out

**Current behavior**
Using the LmageOverlay class in the zoom map is some zoom level does not show the image

**Environment**
- Leaflet version: 1.6.0
- Browser (with version): The chrome version is 84.0.4147.135
- OS/Platform (with version): windows10

**Additional context**
There are no issues in the 78.0.3904.108 version of Chrome

**Comment by WebHero0544** [comment]
![radar](https://user-images.githubusercontent.com/17270753/90762898-5ef42400-e318-11ea-947a-3de57a63c331.png)
I'm using this image. It doesn't show when the map is zoomed to level 11

**Comment by WebHero0544** [comment]
![bugpage](https://user-images.githubusercontent.com/17270753/90763126-bd210700-e318-11ea-9f73-908ce480f417.png)
The level 11 image is no longer displayed, but it is still in the DOM and has not been deleted

**Comment by Lorthiz** [comment]
You are not setting the `maxNativeZoom` for TileLayer. My guess is that this tile map has only 10 zoom levels and you are not setting option this option. It's inherited from GridLayer and according to docs: 

`Maximum zoom number the tile source has available. If it is specified, the tiles on all zoom levels higher than maxNativeZoom will be loaded from maxNativeZoom level and auto-scaled.`

Try:

```
        L.tileLayer('http://t{s}.tianditu.com/DataServer?T=ter_w&X={x}&Y={y}&L={z}&tk=b055e3a80de633c788f673dfcb164aa4',      {
            zIndex: 0,
            subdomains: ['0', '1', '2', '3', '4', '5', '6', '7'],
            maxNativeZoom: 10
        }).addTo(map)
```

**Comment by WebHero0544** [comment]
No, there is no problem with tileLayer, it is the imageOverlay in the new version of Chrome, using the above radar image, it does not show when scaling to level 11.I don't know why

**Comment by WebHero0544** [comment]
The new version of Chrome has this problem, while the previous version has no problem

**Comment by IvanSanchez** [comment]
> The new version of Chrome has this problem, while the previous version has no problem

What is "new version" and "previous version"? Use version numbers, please.

**Comment by WebHero0544** [comment]
Ok, using imageOverlay in Chrome with version 84.0.4147.135 won't be able to display images at some zoom level

**Comment by IvanSanchez** [comment]
I suspect the problem happens when any image has a size larger than 16384 pixels (powers of 2 tend to be limits when it comes to texture sizes and so on). Should check whether a plain image larger than that size renders correctly in Chromium without using Leaflet, to see if this is an upstream bug.

**Comment by Nyut0n** [comment]
Same issue here.
In Chrome 84 and 85, the imageOverlay disappears when zooming in far.
Issue doesn't exist in previous Chrome versions (83 and older).
Live example: https://livemap.feudal.tools/id/5449

**Comment by Nyut0n** [comment]
Rendering large scaled images without Leaflet works fine in Chrome as far as I can tell: https://jsfiddle.net/yLguev4m/

**Comment by jafin** [comment]
@WebHero0544 
I noted that ` 85.0.4183.102 (Official Build) (64-bit)` has the issue.
But Canary Chrome `Version 87.0.4262.0 (Official Build) canary (64-bit)`  works fine.
Chrome may have fixed this in 87+

**Comment by IvanSanchez** [comment]
Closing as "upstream bug, already fixed in the latest version"
