### ISSUE TITLE
How to get the latitude and longitude range of tileLayer?

### ISSUE THREAD

**Issue by wenjunzhangp** [Leaflet/Leaflet#7242]
The `leaflet` version I use is `1.3.4`.

I have a `tile layer`, superimposed on the map, I want to get the `latitude` and `longitude` range of the layer through the layer object, how to solve it? This is my `code`:

```
    const baseLayer = L.tileLayer('http://wprd01.is.autonavi.com/appmaptile?x={x}&y={y}&z={z}&lang=zh_cn&size=1&scl=1&style=7', {
        maxZoom: 24,
        unloadInvisibleTiles: true,
        detectRetina: true
    });
    const map = L.map("map",{
        center: [39.985071,116.414042],
        zoom: 9,
        zoomControl: true,
        attributionControl: true,
        dragging: true,
        layers: [baseLayer]
    });

    var layer = L.tileLayer(`http://39.100.50.217:8888/tiles/{z}/{x}/{y}.png?path=/usr/local/web/rssdata/file123_cog.tif`, {
        maxZoom: 24,
        unloadInvisibleTiles: true,
        detectRetina: true
    }).addTo(map);

    map.eachLayer(function(layer){
        //console.log(layer._map._lastCenter)
       // How to traverse all layers to get the `latitude` and `longitude` range through the layer object
        console.log(layer._map)
        console.log(map.getBounds().contains(layer._map._lastCenter))
    });
```

I did not find the corresponding `api` in the `official website document`, thank you for answering my doubts.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by IvanSanchez** [comment]
BTW, the default is that `TileLayer`s have the same bounds than the map's CRS.

**Comment by wenjunzhangp** [comment]
okay,Thank you for your reply and help, thank you~
