### ISSUE TITLE
Google map drags while dragging pegman in leaflet + google mutant library

### ISSUE THREAD

**Issue by amitagrawal11** [Leaflet/Leaflet#7245]
I am having a problem with pegman (street view) when picking it and dragging over google maps, so when dragging pegman, google map also gets dragged while pegman is not dropped.

**Expected Behavior:** google map should not move when dragging pegman on the map.

- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
1. Pick pegman (street view man in yellow )
2. Try to drag pegman over google maps (don't drop it)
3. Now you will notice google maps also move around with the pegman movement.

**Expected behavior**
Google map should not move when dragging pegman on the map.

**Current behavior**
Google map layer also is moving while dragging pegman on the map.

**Environment**
- Leaflet version: 1.0.1 (also tested with 1.6.0)
- Browser (with version): v84.0.4147.135 (Official Build) (64-bit)
- OS/Platform (with version): 10.15.6

**Minimal example reproducing the issue**
Demo Link to Replicate: https://plnkr.co/edit/87cFuRJ7iBKn1cTeVPb9?preview

**Comment by IvanSanchez** [comment]
I told you already at https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant/-/issues/113 .
