### ISSUE TITLE
Please remove !important in css

### ISSUE THREAD

**Issue by Mygod** [Leaflet/Leaflet#7248]
This is particularly bad as you are bundling it as a library. Please remove it.

**Comment by IvanSanchez** [comment]
Are you referring to...? https://github.com/Leaflet/Leaflet/blob/dd832105697c98c1fca5475616377cda66f876be/dist/leaflet.css#L53-L56

**Comment by Mygod** [comment]
Yes but in general I don't think a library should use `!important` anywhere in the CSS. :rofl:

**Comment by IvanSanchez** [comment]
If you can come up with a way to overcome https://github.com/Leaflet/Leaflet/issues/5775 in a way that doesn't conflict with CSS frameworks without using `!important`, then send a PR.

Until then, `!important` stays.
