### ISSUE TITLE
Marker and Circle/CircleMarker position to same LatLng not working

### ISSUE THREAD

**Issue by anjalirai2626** [Leaflet/Leaflet#7250]
I am trying to create Circle/CircleMarker and Marker at same position (LatLng) 
Referring to Leaflet documentation and codepen example -
https://leafletjs.com/reference-1.6.0.html#marker
https://leafletjs.com/reference-1.6.0.html#circlemarker
https://codepen.io/thomas_rager/pen/bWQWvv

**Steps to reproduce**
Using below code : -

```
import React from 'react';
import L from 'leaflet';
import icon from 'leaflet/dist/images/marker-icon.png';
import iconShadow from 'leaflet/dist/images/marker-shadow.png';
import {
  Circle,
  FeatureGroup,
  LayerGroup,
  LayersControl,
  Map,
  Marker,
  Popup,
  Rectangle,
  TileLayer
} from 'react-leaflet';
const { BaseLayer, Overlay } = LayersControl;
import styled from 'styled-components';
import 'leaflet/dist/leaflet.css';
let DefaultIcon = L.icon({
  iconUrl: icon,
  shadowUrl: iconShadow
});
L.Marker.prototype.options.icon = DefaultIcon;
export default function DCMap(props) {
  const { mapContainerStyle } = props;
  return (
    <div id="dcMap">
      <Map zoom={13} center={[40.39776, -105.07498]} style={mapContainerStyle}>
        <LayersControl position="topright">
          <BaseLayer checked name="OpenStreetMap.Mapnik">
            <TileLayer
              attribution='&amp;copy <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
              url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
            />
          </BaseLayer>
          <BaseLayer name="OpenStreetMap.BlackAndWhite">
            <TileLayer
              attribution='&amp;copy <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
              url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
            />
          </BaseLayer>
          <Overlay checked name="Marker with popup">
            <Marker position={[40.39776, -105.07498]}>
              <Popup>
                <span>
                  A pretty CSS3 popup. <br /> Easily customizable.
                </span>
              </Popup>
            </Marker>
          </Overlay>
          <Overlay checked name="Layer group with circles">
            <LayerGroup>
              <Circle
                center={[40.39776, -105.07498]}
                fillColor="blue"
                radius={200}
              />
              <LayerGroup>
                <Circle
                  center={[51.51, -0.08]}
                  color="green"
                  fillColor="green"
                  radius={100}
                />
              </LayerGroup>
            </LayerGroup>
          </Overlay>
        </LayersControl>
      </Map>
    </div>
  );
}
```

**Expected behavior**
Marker and Circle/CircleMarker should come on same position i.e.

<img width="474" alt="PositionExpected" src="https://user-images.githubusercontent.com/70639398/91975945-d3c65580-ed3d-11ea-88d9-0fdcd2469d30.png">

**Current behavior**
Marker and Circle/CircleMarker are not coming on same position, Please refer below image

<img width="1142" alt="PositionErr" src="https://user-images.githubusercontent.com/70639398/91975754-86e27f00-ed3d-11ea-8e3a-fa8c2e1803e2.png">

**Environment**
- "react": "^16.12.0"
- "react-leaflet": "^2.7.0"
- Chrome Version 80.0.3987.122 (Official Build) (64-bit)
- macOS 10.15.6

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* NativeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.

**Comment by IvanSanchez** [comment]
Do check your `iconAnchor` anyway.

**Comment by anjalirai2626** [comment]
Thanks @IvanSanchez 
Setting **iconAnchor** works for me 👍🏻

```
import icon from 'leaflet/dist/images/marker-icon.png';
import iconShadow from 'leaflet/dist/images/marker-shadow.png';
MarkerIcon = L.icon({
  iconUrl: icon,
  shadowUrl: iconShadow,
  iconAnchor: [12.5, 40],
  shadowAnchor: [12.5, 40]
});
L.Marker.prototype.options.icon = MarkerIcon;
```
