### ISSUE TITLE
When drawing a polyline on the map the intersection is bug and very large

### ISSUE THREAD

**Issue by leduardo99** [Leaflet/Leaflet#7253]
- [ ] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [X] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [X] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- Click to draw a new polyline. (I'm doing this dynamically).
- Click on the map to capture the first coordinate, right after the click, the intersection becomes very large and is very slow.

**Expected behavior**
The intersection should be smaller, with 8px. It has 20px and is locking and I shouldn't finish the drawing if I click on the same point.

**Current behavior**
The intersection is 20px and when I click on the same point, the drawing is concluded and this should not happen.

**Environment**
- Leaflet version: 1.6.0
- Leaflet Draw: 1.0.4
- Browser (with version): Google Chrome
- OS/Platform (with version): Win10

**Additional context**
This error is only happening when the application is in production, locally it is working perfectly.

**Prints**
Server: [link](https://prnt.sc/ubn9fd)
Local: [link](https://prnt.sc/ubnhim)

**Comment by IvanSanchez** [comment]
If you're using Leaflet.Draw, this is the wrong repo. Also, you're not providing a minimal reproducible example.
