### ISSUE TITLE
HTTPS : Cannot read property '_layerAdd' of null when add polyline to map

### ISSUE THREAD

**Issue by Run-Youngman** [Leaflet/Leaflet#7256]
- I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected

- I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- set up a basic map
- generate some latlngs for polyline
- add the polyline to map

**Expected behavior**
show the current polyline to the map

**Current behavior**
No polyline on the map & an error `Cannot read property '_layerAdd' of null`  reported on the console

**Environment**
- Leaflet version: 1.3.4
- Browser (with version): chrome  84.0.4147.125
- OS/Platform (with version): windows10

**Additional context**

Actually I have solved this problem temporarily, the reason for this error is because in https enviroment, it cannot detect if the current browser support SVG and return it didn't support.So, it should change the way to detect this condition, like `typeof SVGRect !== 'undefined'`. Also the original is `!(!document.createElementNS || !E("svg").createSVGRect)` and the function E will use http way to do detect which is not work well in https enviroment.Maybe it has a better way to solved the problem , Looking forward to your discussion.

**Comment by IvanSanchez** [comment]
This is unclear. Please explain how to reproduce, i.e. how can I set up a non-HTTPS environment in which SVG is not detected properly.

**Comment by IvanSanchez** [comment]
AFAIK [`createElementNS()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/createElementNS#Important_Namespace_URIs) has an explicit list of valid namespace URIs, and AFAIK those are treated as internal, meaning there are no network requests made.

**Comment by Run-Youngman** [comment]
> AFAIK [`createElementNS()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/createElementNS#Important_Namespace_URIs) has an explicit list of valid namespace URIs, and AFAIK those are treated as internal, meaning there are no network requests made.

Thank u for reply.It's not about createElementNS() function,when it detected it use the method as {return document.createElementNS("http://www.w3.org/2000/svg", t)} but HTTP request will not work well in HTTPS enviroment.

**Comment by IvanSanchez** [comment]
I still don't understand. How can I reproduce the bug?

**Comment by Run-Youngman** [comment]
> I still don't understand. How can I reproduce the bug?

First , need the HTTPS evironmnet
1. init a map, like var map = L.map('map', {zoom: 5,layers...}
2. define the latlngs  var latlngs = [
    [45.51, -122.68],
    [37.77, -122.43],
    [34.04, -118.2]
];
3. var polyline = L.polyline(latlngs, {color: 'red'}).addTo(map);
4. map.fitBounds(polyline.getBounds());

I just use the example on the Official website，[https://leafletjs.com/reference-1.7.1.html#polyline](https://leafletjs.com/reference-1.7.1.html#polyline)   ，the key is to be in the HTTPS environment

**Comment by IvanSanchez** [comment]
Cannot reproduce. https://plnkr.co/edit/H4pk0nS2fYDo26eg
