### ISSUE TITLE
Build error. Version number not updated in leaflet-src.js

### ISSUE THREAD

**Issue by blq** [Leaflet/Leaflet#7258]
The unminified code in leaflet-src.js from leaflet.zip download package for version 1.7.1 still uses 1.6.0 version and same 1.6.0 header and hash at the top.

**Comment by johnd0e** [comment]
Confirmed
```js
/* @preserve
 * Leaflet 1.6.0+Detached: bd88f73e8ddb90eb945a28bc1de9eb07f7386118.bd88f73, a JS library for interactive maps. http://leafletjs.com
 * (c) 2010-2019 Vladimir Agafonkin, (c) 2010-2011 CloudMade
 */
```

**Comment by IvanSanchez** [comment]
That git reference maps to https://github.com/Leaflet/Leaflet/commit/bd88f73e8ddb90eb945a28bc1de9eb07f7386118 , which is also the [`v1.7.1` tag](https://github.com/Leaflet/Leaflet/releases/tag/v1.7.1). Weirdly enough, the files committed to git seem to be labeled with `1.7.1`.

I guess this has something to do with the TravisCI build, which is what uploads stuff to `cdn.leafletjs.com`. AFAIK, @mourner set that pipeline looong ago, so I don't really know what might be going on right now.

**Comment by blq** [comment]
FYI, the file at unpkg CDN; https://unpkg.com/leaflet@1.7.1/dist/leaflet-src.js has correct version number and header

**Comment by mourner** [comment]
Fixed!
