### ISSUE TITLE
In 1.7.1 L.version has wrong version number stored

### ISSUE THREAD

**Issue by juedan** [Leaflet/Leaflet#7264]
Hello,

in version 1.7.1 of Leaflet L.version has stored the number of the previous Leaflet version.
console.log(L.version) gives "1.6.0" insteat of "1.7.1.".
Look herefore in line 12 of the file leaflet-src.js: var version = "1.6.0";

Best regards

- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Comment by johnd0e** [comment]
Duplicate of #7258
