### ISSUE TITLE
How to make polygon on mouse click?

### ISSUE THREAD

**Issue by victormongi** [Leaflet/Leaflet#7265]
Is there anyway to make polygon on mouse click?

**Comment by johnd0e** [comment]
We use GitHub as an issue tracker and **do not provide support here**.
For usage and support questions, please check out resources below:

1. Read Leaflet documentation: https://leafletjs.com
2. For support questions like "How can I do X with Leaflet?" please search or ask questions on StackOverflow or StackExchange using Leaflet tag:
  - https://stackoverflow.com/questions/tagged/leaflet
  - https://gis.stackexchange.com/questions/tagged/leaflet

Thanks!
