### ISSUE TITLE
Geojson layers use wrong clip area

### ISSUE THREAD

**Issue by pietervdvn** [Leaflet/Leaflet#7283]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

![image](https://user-images.githubusercontent.com/1466478/93722219-83e8ea80-fb95-11ea-9382-0b9a20083e93.png)
![image](https://user-images.githubusercontent.com/1466478/93722314-1be6d400-fb96-11ea-9365-f85d1d5e0cf5.png)

This is the expected correct view: 
![image](https://user-images.githubusercontent.com/1466478/93722337-5a7c8e80-fb96-11ea-8d8f-77d75443b44c.png)

When loading a geojson layer, it seems like the bounds are sometimes calculated incorrectly resulting in a wrong clipping. Panning slightly down will render everything, whereas panning up will hide _all_ the elements.

**Environment**
- Leaflet version: 1.7.1
- Browser (with version): Firefox 78.0.2; Chromiumn 85.0.4183.102 (Official Build) snap (64-bit)
- OS/Platform (with version): Kubuntu 19:10

**Comment by IvanSanchez** [comment]
Reproducible example, please?

**Comment by pietervdvn** [comment]
Very probably a duplicate of #6075

**Comment by pietervdvn** [comment]
This indeed is a duplicate of #6075. If I make sure that 'weight' is a number, the problem dissappears
