### ISSUE TITLE
Only leaflet.js file is version Leaflet 1.7.1 others are 1.6.0

### ISSUE THREAD

**Issue by WebOSM** [Leaflet/Leaflet#7289]
I have downloaded the latest version 1.7.1 from https://leafletjs.com/download.html

The zip file has a 1.7.1 version leaflet.js
All other files are 1.6.0.
I use the leaflet-src.esm.js file so i was suprised to find out it is version 1.6.0

Was there a mistake made when making the zip file or are the version variables and comments not updated?

**Comment by IvanSanchez** [comment]
Duplicate of #7258
