### ISSUE TITLE
Cannot override a DomUtil function

### ISSUE THREAD

**Issue by domlysz** [Leaflet/Leaflet#7290]
Hi,

I need to apply a specific css matrix transformation to my ImageOverlay but this property is overwritten by L.DomUtil.SetTransfo in order to set the image offset. So I would like to override this function to keep my matrix transformation when the css property is updated. Unfortunately the minify process has mangled this function name to a short generic name. So I can override SetTransfo but it has no effect because internally Leaflet uses another name.

Not sure if this behavior is per design or not.

**Steps to reproduce**
Assign a new function to  L.DomUtil.SetTransfo 

**Expected behavior**
the new implementation should be exec instead of the old one

**Current behavior**
the new implementation is not taking into account

**Environment**
- Leaflet version: 1.6.0
- Browser (with version): FF80
- OS/Platform (with version): Linux

**Minimal example reproducing the issue**
https://jsfiddle.net/1v8hdpk4/

**Comment by johnd0e** [comment]
It is by design
