### ISSUE TITLE
Webpack 5 warnings

### ISSUE THREAD

**Issue by olsgreen** [Leaflet/Leaflet#7293]
When compiling a project Webpack 5 the following warnings are raised:

    WARNING  Compiled with 1 warnings                                                                                                            10:38:57
    warning  in ./node_modules/leaflet/src/Leaflet.js
    Should not import the named export 'version' (reexported as 'version') from default-exporting module (only default export is available soon)

This is due to the way the package info is handled for the version export, a minor refactor is needed, a minor pull request is on the way...

**Comment by olsgreen** [comment]
Closing as from the limited research I've done, there's no easy way to fix this without breaking rollups tree shaking, we'll implement something internally to deal with this.

**Comment by IvanSanchez** [comment]
I suggest `import`ing from the ESM build (i.e. https://unpkg.com/browse/leaflet@1.7.1/dist/leaflet-src.esm.js); that might yield better results.

Thanks for the pull req anyway. I do appreciate the effort to provide a solution, even if it proved to be suboptimal.
