### ISSUE TITLE
Dynamically created map not responding to events until mouse leaves container

### ISSUE THREAD

**Issue by rhysstubbs** [Leaflet/Leaflet#7297]
I have a scenario whereby a map is only added to the DOM after a user clicks a button.

The button is removed from the DOM and the map put in its place. The users cursor has not moved.

If the user immediately starts trying to drag the map nothing happens. However, if the user then moves the cursor out of the map container and back in again, all map functionality performs as expected.

I have confirmed that none of the mouse events are being fired during that initial movement by the user, they're only fired once the cursor has left and returned again.

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?

**Comment by rhysstubbs** [comment]
@IvanSanchez Thanks for your response.

You can actually see the same issue here: thinkspain.com/property-for-sale/4742366

I can replicate the issue there.

-----------------------------------------------

On another note, I'm having issues giving mobile users a good experience using Leaflet and perhaps you can advise. I have what I think is quite a standard situation where mobile users are scrolling past a map and that's working ok, I've accomplished this using the options:

```javascript
{
  // ..
  dragging: !L.Browser.mobile,
  tap: !L.Browser.mobile,
  // ...
}
```

but the mobile/touch handling is quite poor when it comes to zooming/intercting with the map. Sometimes it works, sometimes it zooms the page, sometimes it scrolls etc. The best experience is with the above setting at their defaults but that stops mobile users being able to scroll past a tall map.

I guess my question is, am I the only one having these issues? I also use [Leaflet.GestureHandling](https://github.com/elmarquis/Leaflet.GestureHandling/) and It doesn't seem to be the plugin causing the issues but rather the dragging & tap options interferring with the touch handling.

**Comment by IvanSanchez** [comment]
Minimal isolated example, please. 

Also, I can not advise on UX matters.

**Comment by johnd0e** [comment]
@rhysstubbs?

**Comment by Malvoz** [comment]
> You can actually see the same issue here: https://www.thinkspain.com/property-for-sale/4742366
> 
> I can replicate the issue there.

> If the user immediately starts trying to drag the map nothing happens.

Unable to reproduce in Chrome 102.0.5005.115 and Firefox 101.0.1.

Click and drag pans the map - without moving the cursor after clicking the button - as expected.
