### ISSUE TITLE
Only on IPhone: Marker-Popups do not show after a simple tap on the Marker.

### ISSUE THREAD

**Issue by ArbnorZ** [Leaflet/Leaflet#7303]
Hi there,
I am currently working with Ionic and Leaflet to create an App. I use a Leaflet-Map with Markers on it.
I tested it on many PC-Browsers and Android-Devices and all the Markers open their Popups with one click/tap.
But the **Problem on IOS-Devices** is, that **after one simple click/tap on a marker, the popup shows and closes itselfs** in a second.
I have to long-tap on a Marker to open the Popup properly.
I hope you guys can help me out with this :)

Here is how I embedded the Map:
![image](https://user-images.githubusercontent.com/45542677/95020458-8c4c2580-066b-11eb-9ff1-f6e30842ba83.png)

And here you can see how I add all the Markers on the Map:
![image](https://user-images.githubusercontent.com/45542677/95020501-e947db80-066b-11eb-946d-6776ad86e662.png)

As I said it works on every other Device but not on IOS-Devices.

**Comment by ArbnorZ** [comment]
After actually reading 1min through other problems with ios and leaflet:
This `<script>L_DISABLE_3D = true;</script>` worked for me.
Thx 💯

**Comment by ArbnorZ** [comment]
Zooming on IOS is now glitchy...

**Comment by johnd0e** [comment]
Perhaps related to #7255
