### ISSUE TITLE
L is not defined on Wordpress 

### ISSUE THREAD

**Issue by COBNETCKNN** [Leaflet/Leaflet#7304]
Hello there leaflet... So I'm currently developing theme for university and for custom post type for campuses I made I want to display Leaflet Map, I went through documentation and upon wanting to display your map onto my site in console I get JS error **"Uncaught ReferenceError: L is not defined"** whcih directs me to my custom.js file where I've put code from your documentation just for testing purposes...

`var map = L.map('map').setView([51.505, -0.09], 13);`

If I put this code directly into the console, map shows up, but it won't if I put code into my .js file

This is how my functions.php looks like, I know problem isn't within Wordpress since CSS is loaded, I can see div in inspect elements with its CSS properties... 

```
function university_files() {

    wp_enqueue_script('leaflet.js', 'https://unpkg.com/leaflet@1.7.1/dist/leaflet.js', array(), false, true);
    wp_enqueue_script('custom.js', get_template_directory_uri() . '/src/app.js');
    wp_enqueue_script('main-university-js', get_theme_file_uri('/js/scripts-bundled.js'),
    NULL, microtime(), true);

    wp_enqueue_style('custom-google-fonts', '//fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700,700i|Roboto:100,300,400,400i,700,700i');
    wp_enqueue_style('font-awesome', '//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css');
    wp_enqueue_style('university_main_styles', get_stylesheet_uri(), NULL, microtime());
    wp_enqueue_style('leaflet.css', 'https://unpkg.com/leaflet@1.7.1/dist/leaflet.css');
    wp_enqueue_style('custom.css', get_template_directory_uri() . '/css/custom.css');
```

I know there is Leaflet plugin for Wordpress but upon installing, I realized it isn't that much client friendly... I want to make it more dynamic where I planned on making two new custom fields where user will put longitude and latitude and marker will be shown on the map...

**Comment by COBNETCKNN** [comment]
Goofed around and now new error is showing up in console

`Map.js:1103 Uncaught Error: Map container not found.`

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* NativeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.
