### ISSUE TITLE
How to save a Layer ? So, can see the layer after reloading the map.

### ISSUE THREAD

**Issue by MdAbuDarda** [Leaflet/Leaflet#7305]
![image](https://user-images.githubusercontent.com/50475070/95159733-97fd3080-07c0-11eb-80fe-d90f93fe864d.png)

I want to save the red draw. So I can see this draw even after when I reload the map.
partial code:
![image](https://user-images.githubusercontent.com/50475070/95160053-66389980-07c1-11eb-9e9b-98ecebeaa196.png)

**Comment by capan** [comment]
What are you trying to achieve is a little bit weird. You say you want to save a layer but in your example you seem to be wanted to save a polyline. There are many ways to do it. You can use leaflet draw to draw on map then export your drawings here is a good example; [check this one](https://bl.ocks.org/danswick/d30c44b081be31aea483). Or you can save your drawings to a database and retrieve your drawings next time you open the map. Here is a [tutorial]( http://duspviz.mit.edu/web-map-workshop/leaflet_nodejs_postgis/)

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
