### ISSUE TITLE
Problem with intergrating Rough.js

### ISSUE THREAD

**Issue by chakflying** [Leaflet/Leaflet#7307]
I am having some trouble upgrading an existing library to work with the latest version of Leaflet. When zooming in the map, the Rough.js lines which are used as fill would get cut off in some areas. The library basically extends `L.Canvas`, where the `_updatePoly` function would use  `L.SVG.pointsToPath()` to create an SVG string, then pass this string to the Rough.js renderer. I Iooked around and don't see anything that would be zoom-dependent. I checked and it shouldn't be a problem with map tiles getting a higher z-index, since the region where the fill disappear does not line up with tile boundaries.

Here's an illustration with jsfiddle:

![image](https://user-images.githubusercontent.com/3271800/95288064-14b00d80-089a-11eb-8aef-831ccd484017.png)

![image](https://user-images.githubusercontent.com/3271800/95287895-ac612c00-0899-11eb-8b0e-658a78e865f4.png)

https://jsfiddle.net/t0zwbh2j/
- Zoom in
- Move around the map

Don't know if this is the right place to get help, but seems like some insight into how the renderer works is needed.
Here's my working repo if anyone's interested:
https://github.com/chakflying/Leaflet.RoughCanvas

**Comment by IvanSanchez** [comment]
By testing Leaflet 1.7.1 with the latest available Leaflet-roughcanvas, I can see that the error is about an undefined `this._drawnLayers`, which was removed in https://github.com/Leaflet/Leaflet/pull/6324. By manually setting that to an empty obect (see https://plnkr.co/edit/RxDUc3x1b6EhrYpB), everything works.

So, of all the changes I see in https://github.com/zhuang-hao-ming/Leaflet.RoughCanvas/compare/master...chakflying:master?w=1 , you only need https://github.com/zhuang-hao-ming/Leaflet.RoughCanvas/compare/master...chakflying:master?w=1#diff-1c90ff38a08209f9ebd4d05d1e43358eL25 . I don't know why you are changing anything else.

**Comment by chakflying** [comment]
Thanks, I guess I really have no idea what's going on.
