### ISSUE TITLE
GeoJSON with lines is very slow

### ISSUE THREAD

**Issue by TimHaerkens** [Leaflet/Leaflet#7309]
I'm using L.GeoJSON to draw 32,623 lines on a Leaflet map. 
The lines have between 2 and 709 coordinates with an average of 14 coordinates. But having these loaded in makes the app unusable or at least very slow.

### Expected Behavior
More fluent dragging and zooming on the map.

### Current Behavior
When I drag or change zoom the application freezes for a bit and then after a second it continues but stutters a lot. When I release the drag it also freezes for a second. This makes quick short drags impossible to do.

**Screenshot:**
https://imgur.com/a/ZqgIGpA
Biggest part of the lines on the map and a zoomed in part to see the layout of the lines

**Animated GIF:**
https://gyazo.com/42dc8f76e1e33db055a4558455250ed4
In the GIF you see when I start dragging I move my mouse and only after a second or so the map goes with.
I'm currently working from home on a pc with an AMD Ryzen 9 CPU and 32GB of DDR4 RAM so on my work pc or any of my customers work pcs it would result in ever a slower reaction.

### Possible Solution
Removing listeners/interactivity at certain zoom levels maybe or optimizing code that runs when I start dragging.

### Steps to Reproduce
I use a Leaflet map with a TileLayer (Carto) and I load a GeoJSON with 32,623 features. The features have one property and that's the uuid of their linked object. When it's loaded it's incredibly slow when I START and STOP dragging. After the freeze it seems to work decently as long as I hold the mouse. When I'm all the way zoomed out though even dragging stutters a lot. But I could live with that.

### Environment

- **`Leaflet` version**:  1.7.1
- **Browser & Version**: Chrome 84.0.4147.135
- **OS & Version**:  Windows Microsoft 10 Pro v1909
- **Running Example**: n/a

**Comment by johnd0e** [comment]
> I'm using L.GeoJSON to draw 32,623 lines on a Leaflet map.

This is basically too much.
But you can try that with https://leafletjs.com/reference-1.7.1.html#map-prefercanvas option.

**Comment by IvanSanchez** [comment]
> I'm using L.GeoJSON to draw 32,623 lines on a Leaflet map.

Try adding 32 623 SVG elements on a webpage and measuring how long that takes to display.

**Comment by TimHaerkens** [comment]
> > I'm using L.GeoJSON to draw 32,623 lines on a Leaflet map.
> 
> Try adding 32 623 SVG elements on a webpage and measuring how long that takes to display.

I'm sorry but is this irony? Using L.GeoJSON is an alternative for using a plugin called Leaflet.PixiOverlay which uses Pixi's WebGL engine and that kind of works fine performance-wise but I'm having interactivity and graphical issues there.

**Comment by IvanSanchez** [comment]
> I'm sorry but is this irony?

No, it's not.

> A different solution could be to disable interactivity on lower zoom levels [...]

No, since 32 623 non-interactive SVG elements will take the same time to be drawn than 32 623 interactive SVG elements (hey, prove me wrong!).

Use VectorGrid or something if you want, but the "I'm adding 40000 elements to my map and it's slow" use case is *not* a Leaflet bug.

**Comment by TimHaerkens** [comment]
It seems to me you're stating the obvious to prove a point that it's not possible. I was hoping to find a work-around because I know it's asking a lot of the client to render everything at once and I'm not asking that you change some code so that it magically works. I was hoping someone could point me towards a solution I haven't thought of yet.

**Comment by IvanSanchez** [comment]
The workaround is VectorGrid.

**Comment by TimHaerkens** [comment]
> The workaround is VectorGrid.

I'll look into it. Thanks.
