### ISSUE TITLE
Unit Testing - Leaflet methods with custom component

### ISSUE THREAD

**Issue by at-webdev** [Leaflet/Leaflet#7315]
I am looking to create unit tests for component below mainly on checking addLayer and removeLayer being called,
```
function App (()=>{
    const marker = useRef<L.Marker | undefined>( undefined);
    const fg : L.FeatureGroup<any> = fg(); 
    
    useEffect(()=>{
    var myIcon = L.divIcon({className:'my-div-icon',html:renderToStaticMarkup(<ArrowRight/>)});
    marker.current = L.marker([50.5, 30.5], {icon:myIcon});
     if(fg) fg.addLayer(marker.current);
      <div>Text</div>;
    
     return (){
    if(marker.current && fg)
    {fg.removeLayer(marker.current);}
   
    } 
    },[fg]);
    
    });

```

RTL Test:
```
const mockAddLayer = jest.fn();
describe("Test Leaflet methods",()=>{
it("Test add Layer",()=>{
const {wrapper} = render (<App/>);
expect(wrapper.getByText('Text')).toBeTruthy();
expect(mockAddLayer).toBeCalled();
});
});
```
The above test is failing with
```
expect(jest.fn()).toBeCalled()
expected number of calls:  >= 1
received number of calls: 0
```
It is possible to test fg.addLayer() and fg.removeLayer() are being called? I am a beginner in unit testing with leafletjs. Any leads is appreciated

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
