### ISSUE TITLE
L.Util.throttle work not as expected

### ISSUE THREAD

**Issue by Falke-Design** [Leaflet/Leaflet#7319]
I want to use `L.Util.throttle` but it is not working as expected when it is used in a custom class. 

[Throttle Doc](https://leafletjs.com/reference-1.7.1.html#util-throttle)

[Throttle Src](https://github.com/Leaflet/Leaflet/blob/bc918d4bdc2ba189807bc207c77080fb41ecc196/src/core/Util.js#L68)

I want when the map is moveing, the `throttle()` function of my class is called and then the `L.Util.throttle` is execute, but the log is never outputted. If I call `L.Util.throttle` directly (same as my `throttle()` function) it works ...

It should be in a own function so I can remove the event from the map `map.off('move',this.throttle,this);` also then it would be possible to use the same throttle function in all extended classes of my class.  

```js
L.Test = L.Class.extend({
  log(){
  	console.log("throttle")
  },
  throttle(){
    L.Util.throttle(this.log, 1000,this)
  },
  classFnc(){
  	map.on('move',this.throttle,this);
  },
  direct(){
  	map.on('move',L.Util.throttle(this.log, 1000,this),this);
  },
});

x = new L.Test();
//x.classFnc(); // <-- Not Working
x.direct() // Working
```

[Example](https://jsfiddle.net/falkedesign/mrgfxv94/)

Maybe this is the normal behavior of throttle functions but it don't understand it. 

Can you explain why this is not working?

**Comment by mourner** [comment]
In `direct`, you're adding the result of `L.Util.throttle` (which is a function) as a listener, so it works as expected.
In `classFnc`, you're adding `this.throttle`, a function which does not execute `this.log` directly. `L.Util.throttle` returns a new (throttled) function that you don't use afterwards. This is a JavaScript issue on your end, not an issue with `throttle`.
