### ISSUE TITLE
make L.Marker work with canvas renderer

### ISSUE THREAD

**Issue by henrikmaa** [Leaflet/Leaflet#7321]
When adding high amount of markers to the map it is lagging (very common and understandable).
When using canvas renderer and all elements are canvas compatible it works like a charm. 

To make leaflet blasing fast with a lot of objects make it possible to use L.Marker with canvas.

I have already tried the [Leaflet.Canvas-Markers](https://github.com/eJuke/Leaflet.Canvas-Markers) plugin, but this does not work anymore.

Another solution would be to just use [markercluster](https://github.com/Leaflet/Leaflet.markercluster), but in my case I cant do that.

It would also be a possibility if it was possible in some way to add a icon to the circleMarker (as an hacky solution) but I have not managed to get this working. 

I have seen this has been an issue here multiple times and being closed. But now I add it as a feature request in hope that leaflet can become super fast with a lot of objects.

**Comment by johnd0e** [comment]
> I have already tried the [Leaflet.Canvas-Markers](https://github.com/eJuke/Leaflet.Canvas-Markers) plugin, but this does not work anymore.

You can try another fork: https://github.com/IITC-CE/Leaflet.Canvas-Markers

**Comment by henrikmaa** [comment]
as seen in #canvas

> > I have already tried the [Leaflet.Canvas-Markers](https://github.com/eJuke/Leaflet.Canvas-Markers) plugin, but this does not work anymore.
> 
> You can try another fork: https://github.com/IITC-CE/Leaflet.Canvas-Markers

I think I already tried this one, tried multiple forks. but will try again to make sure

**Comment by henrikmaa** [comment]
> > I have already tried the [Leaflet.Canvas-Markers](https://github.com/eJuke/Leaflet.Canvas-Markers) plugin, but this does not work anymore.
> 
> You can try another fork: https://github.com/IITC-CE/Leaflet.Canvas-Markers

@johnd0e 
I cant install it as npm, and if i just take the **leaflet.canvas-markers.js** file it does not work

```
// Adds a layer
    var ciLayer = L.canvasIconLayer({}).addTo(map);

// Marker definition
    var marker =  L.marker([58.5578, 29.0087]);

// Adding marker to layer
    ciLayer.addMarker(marker);
```

Is there a specific way you know about how to import? Specifically i'm confused about the **_full.js** file in regards of importing

**Comment by johnd0e** [comment]
> I cant install

Perhaps you've missed build step.
But that is severe offtopic here so if you need further assistance please open issue in corresponding repo.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
