### ISSUE TITLE
Popup+ FeatureGroups and isPopupOpen() on layers

### ISSUE THREAD

**Issue by Falke-Design** [Leaflet/Leaflet#7322]
If a popup is bound to a FeatureGroup and then it is opened, it opens on the last layer of a group.

When we call `isPopupOpen()` on the layer, which has the open popup, it returns false. This can be correct if we say the popup is bound to the group and so the popup is not opend on the layer, but it think it would be a good feature if the layer also returns true. (Same for Tooltips)
```
var group = L.featureGroup().addTo(map);
var marker = new L.Marker(map.getCenter()).addTo(group);
var marker2 = new L.Marker([40.75, -74.25]).addTo(group);
group.bindPopup("<p>Lorem ipsum</p>").openPopup();

console.log(marker.isPopupOpen());
console.log(marker2.isPopupOpen());
 ```
[Demo](https://jsfiddle.net/falkedesign/vLb3zy7d/)

And maybe we can discuss about, that if `openPopup()` on a group is called, that over all layers popups are opened.

Also `openPopup()` is not working on LayerGroups, this is described here: #5414 but I think this can easy fixed, like in my comment.

**Comment by johnd0e** [comment]
> And maybe we can discuss about, that if `openPopup()` on a group is called, that over all layers popups are opened.

All members of FeatureGroup share **single** popup instance. This is main feature.

> When we call `isPopupOpen()` on the layer, which has the open popup, it returns false

Popup always belongs to FeatureGroup, not to individual markers.
You can check current popup's source in it's private property `_source`.
So you can implement own more smart alternative of `isPopupOpen`.
