### ISSUE TITLE
TileLayer min/maxZoom and detectRetina fails to make any tile requests

### ISSUE THREAD

**Issue by bozdoz** [Leaflet/Leaflet#7326]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- TileLayer has identical minZoom and maxZoom with `detectRetina: true`

**Expected behavior**
Map fetches tile urls

**Current behavior**
Map does not fetch tile urls

**Environment**
- Leaflet version: 1.7.1

**Minimal example reproducing the issue**

https://codepen.io/bozdoz/pen/ZEOozZN?editors=0110

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by johnd0e** [comment]
> * TileLayer has identical minZoom and maxZoom with `detectRetina: true`

In this particular case `detectRetina: true` option is meaningless and you should not use it.

**Comment by johnd0e** [comment]
One more weird thing: <kbd>+</kbd> in Layers control gets enabled.
