### ISSUE TITLE
Unable to get the house number. 

### ISSUE THREAD

**Issue by danielNewb** [Leaflet/Leaflet#7332]
Hi,

I'm not able to find the house number. If I enter: Via Massimo D'Azeglio, 43 Este PD, Italia
that's the response:
boundingbox: (4) ["45.2278025", "45.228486", "11.6524049", "11.653776"]
class: "highway"
display_name: "Via Massimo D'Azeglio, Este, Padova, Veneto, 35042, Italia"
importance: 0.61
lat: "45.228486"
licence: "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright"
lon: "11.6524049"
osm_id: 31891758
osm_type: "way"
place_id: 93675746
type: "residential"

How to show on the address with house number (43) on the leaflet-popup-content?
Why the response does not contain this information?

Thanks!

**Comment by IvanSanchez** [comment]
This is not a bug in core Leaflet.

**Comment by kagan94** [comment]
Facing same issue, but with Greek address.
Most probably data provider doesn't have enough data about house numbers, therefore house number is absent.
