### ISSUE TITLE
tileLayer http wms over https site forces https request

### ISSUE THREAD

**Issue by Diferno** [Leaflet/Leaflet#7337]
- [X] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [X] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [X] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- step 1
 create a leftlet map and add a wms tileLayer that calls a http resource (not https)
- step 2
 deploy the site to a https domain
- step 3
  display the wms layer
 

**Expected behavior**
 the wms layer displays correctly

**Current behavior**
 the wms url protocol is changed to https because its running under a https site (the wms services doesn't support https) so we get a 404

**Environment**
- Leaflet version: 1.5.1
- Browser (with version): Chrome Versión 86.0.4240.198 (Build oficial) (64 bits)
- OS/Platform (with version): Windows 10Pro

**Additional context**
 Using vue2-leaflet v2.2.1

**Comment by IvanSanchez** [comment]
Can't reproduce (firefox 82 or chromium 83 on Linux), see https://plnkr.co/edit/KhJkFZh9ZHNjgFrT

![Screenshot_20201115_142731](https://user-images.githubusercontent.com/1125786/99186192-0681c680-274f-11eb-9b4a-8fce0d0eb069.png)

In any case, Leaflet is **not** changing the URL scheme of the WMS tiles.

**Comment by Diferno** [comment]
Hi, sorry to bother, but taking your Plnkr and using the WMS services that generated the issue, the protocol gets changed....  (wtf!)

[https://plnkr.co/edit/8UJNTNuJnkYkYNBa](https://plnkr.co/edit/8UJNTNuJnkYkYNBa)

![image](https://user-images.githubusercontent.com/710360/99223586-15b35380-27e5-11eb-80ef-1eb86c91779b.png)

**Comment by Nekzuris** [comment]
I think I encounter the same issue while trying to load this custom layer [http://ks3.repetto.org/hillshade_bilinear/{zoom}/{x}/{y}.png](http://ks3.repetto.org/hillshade_bilinear/%7Bzoom%7D/%7Bx%7D/%7By%7D.png) in https://www.openstreetmap.org/edit

I've tried multiple browsers without extensions, and even different devices, but the http is always changed to https. Other people have reported that it works fine for them.

Did you found a solution?
