### ISSUE TITLE
Popup offset

### ISSUE THREAD

**Issue by Uriel304** [Leaflet/Leaflet#734]
I want to modified the offset of a CircleMarker's popup (I use geojson datas)

``` js
var geojsonLayer = new L.GeoJSON(null, {
    pointToLayer: function (latlng){
        return new L.CircleMarker(latlng, {
            radius: 8,
            fillColor: "#ff7800",
            color: "#000",
            weight: 1,
            opacity: 1,
            fillOpacity: 0.8
        });
    }
});
geojsonLayer.on("featureparse", function (e) {
    var popupContent = e.properties.popupContent;
    e.layer.bindPopup(popupContent);
});
map.addLayer(geojsonLayer);
```

I didn't find where to add the offset : I tried in bindPopup (after popupContent) but it's not working.

``` js
e.layer.bindPopup(popupContent,(10,10));
```

Someone can help me?

**Comment by JasonFitz** [comment]
IS there a way to dynamically reset the offset? I am trying a variable for offset that is set on a map zoom, but it doesn't seem to work..thanks!

**Comment by lentyaishe** [comment]
@mourner  You just saved my day!!
