### ISSUE TITLE
Map Tiles are blurry on mobile device

### ISSUE THREAD

**Issue by NicoHood** [Leaflet/Leaflet#7341]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- Use your Phone
- Go to https://leafletjs.com/examples/quick-start/example.html
- The Map is displayed blurry

**Expected behavior**
Sharp picture (for map tiles)

**Current behavior**
Blurry map

**Environment**
- Leaflet version: 1.7.1
- Browser (with version): Firefox Klar 8.8.4
- OS/Platform (with version): Android 10

![Screenshot_20201119-195452](https://user-images.githubusercontent.com/6888294/99711052-9605dd00-2aa1-11eb-93da-2063c9a426e9.png)

This also happens with the chrome browser, but only on a mobile device. In my project I am using the 256px tiles from osm.org, but your example even uses the 512 higher resolution maps from mapbox, but they are still blurry. The rest of the page (and popups) are okay.

I think the issue might be caused, because the real DPR is 3, meaning the screen has 3 times more pixel, than what the website is rendered for. For example my phone has a pixel width of 1080. 1080/3=360, so the page is rendered as if it would have 360 pixel width (for the grid layout etc), but the actual text is rendered in a higher resolution. If I resize the map on desktop by factor 3 the exact same blurry effect and the exact same resolution comes out. So the blury effect comes from the resize. What we need is a resize that just tripples the pixel (like in pixel artwork)

We would need something like this:
https://css-tricks.com/almanac/properties/i/image-rendering/

Related issues:
https://github.com/Leaflet/Leaflet/issues/3575
https://github.com/Leaflet/Leaflet/issues/5883

**Comment by NicoHood** [comment]
I think the best solution is to enable `detectRetina`. Maps on mobile devices always seem to be a bit blurry, even google maps (without the app).

**Comment by johnd0e** [comment]
> We would need something like this:
> https://css-tricks.com/almanac/properties/i/image-rendering/

Make sense if you prefer tiles to have crisp edges (but still pixelated).
You can apply different rules in your css and chose what suits you better.

But to make tiles more detailed use `detectRetina`, as suggested.
