### ISSUE TITLE
DrawControl doesn't work on chrome / android.  DrawControl: True still drags on Android

### ISSUE THREAD

**Issue by pandabuilt** [Leaflet/Leaflet#7343]
- [ X ] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [ X ] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [ X ] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- step 1
- step 2
- ...

**Expected behavior**

Draw to work on Android.

**Current behavior**

Draw works on iOS safari and chrome, however, on Android drawControl: true drags maps.

**Environment**
- Leaflet version: 1.7.1
- Browser (with version): Chrome 
- OS/Platform (with version): Android

**Additional context**

**Minimal example reproducing the issue**

Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.

- [ ] this example is as simple as possible

`L.map('lawntracer-mapid', {
			drawControl: true,
		})`
- [ X ] this example does not rely on any third party code

**Comment by johnd0e** [comment]
Mentioned 'Draw' is not part of Leaflet.
