### ISSUE TITLE
Error en map after zoom operation in polyline and polygon

### ISSUE THREAD

**Issue by clmoscoso** [Leaflet/Leaflet#7353]
After of some zoom in our out operation all layers freeze, before november 21 error doesnt exists

![image](https://user-images.githubusercontent.com/22917029/100554878-e0d3e180-3265-11eb-907c-9f75cbf9099b.png)

and shows this error on console

![image](https://user-images.githubusercontent.com/22917029/100554883-f2b58480-3265-11eb-8f3e-87251175d5c3.png)

leaflet version 1.7.1
on chrome Versión 87.0.4280.66 (Build oficial) (64 bits)

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?

Did you do something specific in november 21st?

**Comment by clmoscoso** [comment]
nothing, i made test with a website published in november 13 and appears the same error

**Comment by IvanSanchez** [comment]
You'll have to provide a minimal example which reproduces the error, anyway.

**Comment by clmoscoso** [comment]
in the website i update position of company's vehicle in intervals of time, each marker dont have popup but when y execute Marker.setLatLng 

![image](https://user-images.githubusercontent.com/22917029/100661168-0f62c280-3321-11eb-9f78-856f50534642.png)

**Comment by johnd0e** [comment]
Your error occurs here: https://github.com/Leaflet/Leaflet/blob/c0bf09ba32e71fdf29f91808c8b31bbb5946cc74/src/layer/Popup.js#L503-L505

For some reason `this._popup` is `undefined`, and nobody can say why without seeing **your** code, sorry.

This issue is subject to close, unless more details will be unveiled.
