### ISSUE TITLE
Using objects as class properties results in shared references to these objects between all instances of the class

### ISSUE THREAD

**Issue by matafokka** [Leaflet/Leaflet#7354]
Hello, so problem is basically described at the title. Probably, this is not a bug, but it should be documented. To illustrate this better, please, take a look at examples below.

This is how I expect my code to look like (explanations in comments):
```JS
let MyClass1 = L.Class.extend({
	// I want to have an object property, so I simply instantiate my object here as I do in any object-oriented language
	myObject: { myValue: 1 }, // myObject: new Object() causes this behavior too

	// And later I want to modify this object. Object should be modified only in one particular instance of MyClass1 when I call setObjectValue().
	setObjectValue: function (value) {
		this.myObject.myValue = value;
	}
});

let instance1 = new MyClass1();
let instance2 = new MyClass1();

instance1.setObjectValue(2); // Here I expect myObject to be modified only in instance1
console.log(instance1.myObject.myValue, instance2.myObject.myValue); // Expected: "2 1", outputs: "2 2"
// However, as you can see, myObject has been modified in both instances

instance2.setObjectValue(3); // Same goes for any other instance of myClass
console.log(instance1.myObject.myValue, instance2.myObject.myValue); // Outputs "3 3"
```

At this point we understand that `myObject` is being shared among our instances instead of being recreated at each instantiation. Let's instantiate `myObject` in constructor to ensure that it will be recreated.

```JS
let MyClass2 = L.Class.extend({
	initialize: function () {
		this.myObject = { myValue: 1 };
	},

	setObjectValue: function (value) {
		this.myObject.myValue = value;
	}
});

instance1 = new MyClass2();
instance2 = new MyClass2();

instance1.setObjectValue(2);
console.log(instance1.myObject.myValue, instance2.myObject.myValue); // Outputs "2 1" as expected

instance2.setObjectValue(3);
console.log(instance1.myObject.myValue, instance2.myObject.myValue); // Outputs "2 3" as expected
```

And it works just fine!

I don't know if this is intended behavior or not, it doesn't seem fine in terms of OOP *(but fine in terms of prototype-based programming if you'll happen to have insight on how Leaflet classes internally work)*, but I think it should be documented.

In my case, this simple misunderstanding led to hours of debugging my fairly complex application.

**Comment by IvanSanchez** [comment]
> I don't know if this is intended behavior or not, it doesn't seem fine in terms of OOP *(but fine in terms of prototype-based programming if you'll happen to have insight on how Leaflet classes internally work)*

This is *expected* behaviour in javascript/ECMAscript prototypical inheritance.

> but I think it should be documented.

Since this behaviour is **not** specific to Leaflet (but rather applies to all prototypical inheritance language constructs, i.e. `class`), I don't think that documenting this *on the Leaflet docs* makes much sense.

**Comment by matafokka** [comment]
Thank you for replying to my issue.

> This is expected behaviour in javascript/ECMAscript prototypical inheritance.

Yes, if you know that Leaflet class system doesn't do any magic (i.e. re-instantiating objects) with passed literals as one might expects since classes are called classes and not prototypes.

> but rather applies to all prototypical inheritance language constructs, i.e. class

No, it's not, ES6 classes work as expected:

```JS
class MyClass {
	myObject = { myValue: 1 };

	setObjectValue(value) {
		this.myObject.myValue = value;
	}
}

let instance1 = new MyClass();
let instance2 = new MyClass();

instance1.setObjectValue(2);
console.log(instance1.myObject.myValue, instance2.myObject.myValue); // Outputs "2 1" as expected

instance2.setObjectValue(3);
console.log(instance1.myObject.myValue, instance2.myObject.myValue); // Outputs "2 3" as expected
```

I'm not saying that there should be complex examples or explanations on how prototypes work, but rather a small clarification like this: "Don't instantiate object properties in class body, do it in constructor because Leaflet treats passed object literals as, well, object literals and doesn't re-instantiate it's properties".

**Comment by IvanSanchez** [comment]
> I'm not saying that there should be complex examples or explanations on how prototypes work, but rather a small clarification

Consider sending a pull request to add such a clarification to https://github.com/Leaflet/Leaflet/blob/master/docs/examples/extending/extending-1-classes.md . I'm just not sure what's the best wording for it.

**Comment by matafokka** [comment]
Thank you, I've rephrased it to fit the documentation and created a pull request: https://github.com/Leaflet/Leaflet/pull/7355
