### ISSUE TITLE
Video overlay: `playsinline` attribute required for phones on iOS

### ISSUE THREAD

**Issue by Malvoz** [Leaflet/Leaflet#7357]
https://webkit.org/blog/6784/new-video-policies-for-ios/:

> - On iPhone, `<video playsinline>` elements will now be allowed to play inline, and will not automatically enter fullscreen mode when playback begins.
> `<video>` elements without `playsinline` attributes will continue to require fullscreen mode for playback on iPhone.

Might we worth to add the attribute by default. See the HTML [`playsinline` attribute](https://html.spec.whatwg.org/multipage/media.html#attr-video-playsinline) definition.

**Comment by IvanSanchez** [comment]
Sounds easy enough - init the property alongside https://github.com/Leaflet/Leaflet/blob/e76f97cba319d97482e395279000ac95de5a8d99/src/layer/VideoOverlay.js#L78 in a similar manner, set it to `true` and test it out.
