### ISSUE TITLE
noWrap=true,How to let it show whole map

### ISSUE THREAD

**Issue by litiangui555** [Leaflet/Leaflet#7360]
![image](https://user-images.githubusercontent.com/50727361/100950272-f20f3d80-3546-11eb-8485-83b1ca0ff1cc.png)

 when noWrap=true,the wrapped around the dateline value is between -180 and +180 degrees. how am I to change it, like pic.
for example:
         change the wrapped around the dateline value is between -160 and +200 degrees

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by IvanSanchez** [comment]
You can always define a new CRS with a different value for its `wrapLng` property.

**Comment by johnd0e** [comment]
> or a feature request

This actually looks like feature request.
BTW, we already have PR for (more or less) similar feature for case `noWrap=false`: https://github.com/Leaflet/Leaflet/pull/6723
