### ISSUE TITLE
when noWrap=true,the map cannot display completely

### ISSUE THREAD

**Issue by litiangui555** [Leaflet/Leaflet#7361]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x]  I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x]  I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- use your browser
- go to https://jsfiddle.net/cg625tr0/394/
- the map cannot display completely

**Expected behavior**
Sharp picture (for map tiles)

**Current behavior**
cannot display completely

**Environment**
- Leaflet version:1.7.1
- Browser (with version): google
- OS/Platform (with version): windows7
![image](https://user-images.githubusercontent.com/50727361/100960782-f003a980-355b-11eb-899e-768f5bb95b6e.png)

I think that it should display completely when set noWrap=true.

**Comment by IvanSanchez** [comment]
This is *behaviour as expected*. Leaflet does not have the capabilities to cut up images, so if a map provider gives a tile like `https://a.tile.openstreetmap.org/1/0/0.png`...

![](https://a.tile.openstreetmap.org/1/0/0.png)

, then that tile displays as a whole.

If this is critical, consider rolling out your own tile server and handle data near the antimeridian accordingly.
