### ISSUE TITLE
npm package contains dist/reference-1.6.0.html

### ISSUE THREAD

**Issue by simon04** [Leaflet/Leaflet#7370]
Starting with version 1.7.0, the npm package contains the following three files in `dist/`:
* https://unpkg.com/browse/leaflet@1.7.1/dist/reference-1.6.0.html
* https://unpkg.com/browse/leaflet@1.7.1/dist/reference-1.6.0-newleafdoc.html
* https://unpkg.com/browse/leaflet@1.7.1/dist/reference-1.6.0-oldleafdoc.html

Those files seem to be left-overs from testing or a former build.

**Comment by mourner** [comment]
Fixed!
