### ISSUE TITLE
v1.7.1 and previous: Tooltips marked permanent=true disappear on mouseout.

### ISSUE THREAD

**Issue by araJamieson** [Leaflet/Leaflet#7374]
- [ x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [ x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [ x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
1. Open a number of marker-related tooltips from Javascript, marking each as permanent as you do so.
2. This does indeed display all of the tooltips.  Now move the mouse over one of the owning markers.  As you move the mouse out of it again, the tooltip vanishes.

**Expected behavior**
I had assumed that the tooltip would remain visible until some program-level action was taken.  Not sure if that was the intention?

**Current behavior**
Tooltip vanishes on mouseout.

**Environment**
- Leaflet version: 1.71 (but also an issue in previous versions).
- Browser (with version): Firefox 83.0
- OS/Platform (with version): Win10 Pro

**Additional context**

**Minimal example reproducing the issue**

Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by johnd0e** [comment]
@araJamieson 
Please add code sample as per template:



> Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.
> 
> * [ ]  this example is as simple as possible
> * [ ]  this example does not rely on any third party code

**Comment by araJamieson** [comment]
Sorry about that -- haven't used one of these sites before.  Hopefully this link works: https://jsfiddle.net/araj1/s4vxrm7p/1/

**Comment by araJamieson** [comment]
Haven't used these sites before.  Does this link work, or do I need to copy the code directly?

https://jsfiddle.net/araj1/s4vxrm7p/1/

**Comment by johnd0e** [comment]
That is correct usage as per [docs](https://leafletjs.com/reference-1.7.1.html#layer-bindtooltip)
```js
marker.bindTooltip("This is a tooltip",{permanent: true});
// marker.openTooltip(); // no need to open explicitly
```

**Comment by araJamieson** [comment]
Thank you very much for looking into this.  I have to admit I’m still a little confused, however, so I wonder if I might ask a question.

 

The documentation regarding the ‘permanent’ option for tooltips says it controls ‘Whether to open the tooltip permanently or only on mouseover’.  Now in saying that it is certainly correct, in that if, under program control, you change the setting on a number of tooltips to be permanent=true, all of them appear, and do so irrespective of where the mouse is.

 

And admittedly the documentation doesn’t say what should happen to a tooltip marked as permanent=true if the owning marker receives a mouseout event.  It’s just that the word ‘permanent’ seems to imply that the tooltip will remain … well, permanently visible; when in fact it does not.  If you move the mouse over a marker which owns a tooltip – even a tooltip marked permanent=true – and then move the mouse out of the marker again, the tooltip vanishes.

 

Just wanted to confirm that I hadn’t been unclear in trying to describe what the issue was, and also that this really is the intended behaviour.

 

Thanks for your time.

 

ARAJ

**Comment by johnd0e** [comment]
> If you move the mouse over a marker which owns a tooltip – even a tooltip marked permanent=true – and then move the mouse out of the marker again, the tooltip vanishes.

Please setup fiddle to reproduce that issue.

**Comment by jabdinghoff** [comment]
> > If you move the mouse over a marker which owns a tooltip – even a tooltip marked permanent=true – and then move the mouse out of the marker again, the tooltip vanishes.
> 
> Please setup fiddle to reproduce that issue.

doesnt the fiddle do exactly that?
