### ISSUE TITLE
LeafletJS does not work as expected in an iFrame (mouse events problems)

### ISSUE THREAD

**Issue by ssijak** [Leaflet/Leaflet#7376]
**Steps to reproduce**

1. Add basic leafletjs map to an iframe
2. Clicking on the map throws error in Chrome and Firefox. In Safari it just silently dies. 
3. Panning, moving the map fails and other app features and other maps on the page die too.

**Expected behavior**
Leafletjs map should work in an iframe

**Current behavior**
Leafletjs map does not work in an iframe as expected

**Environment**
- Leaflet version: 1.7.1
- Browser (with version): Newest all browsers
- OS/Platform (with version): Tested on OSX

**Minimal example reproducing the issue**

[https://codesandbox.io/s/leafletjs-iframe-problem-forked-9of2g](https://codesandbox.io/s/leafletjs-iframe-problem-forked-9of2g)

**Reason**

Tracking it down it boils down to the same issue already reported in #6690.
This change would fix it [https://github.com/Leaflet/Leaflet/pull/6690/files/41719e2822915de3e35050011ef9f8c8d85d16ef](https://github.com/Leaflet/Leaflet/pull/6690/files/41719e2822915de3e35050011ef9f8c8d85d16ef)
Because the mouse event has touches array but it is empty `e.touches` is `[]`

**Comment by IvanSanchez** [comment]
> Add basic leafletjs map to an iframe

> https://codesandbox.io/s/leafletjs-iframe-problem-forked-9of2g

Whoa, that's not a "basic leafletjs map", there's a bunch of React thrown in as well.

Is this reproducible *without* any of the React stuff?

**Comment by johnd0e** [comment]
> Leafletjs map does not work in an iframe as expected

Bad report.
I suppose you mean "map is not dragging by mouse"?

> Because the mouse event has touches array but it is empty `e.touches` is `[]`

We need someone with OSX to confirm the issue (and track it down to its roots).

**Comment by IvanSanchez** [comment]
I'm interpreting the re-posting of this into https://stackoverflow.com/questions/65238359/leafletjs-does-not-work-when-rendered-inside-iframe-in-react-mouse-events-break as a lack of will to provide a react-less reproducible example.

**Comment by ssijak** [comment]
@IvanSanchez I've tried to reproduce it without React but could not reproduce the issue when using leaflet in just the <iframe />. That is why I reposted to SO because I'm not sure where exactly the issue is and can't nail it down, in how Leaflet registers the event handling or  if React messes something.

**Comment by skornel02** [comment]
Hi @ssijak, 
Have you found a workaround for this issue? I ran into a similiar problem in one my projects.

**Comment by ssijak** [comment]
@skornel02 No. I load the whole page where leaflet is in an <iframe> with src attribute pointing to that page. It works that way, but it is slower to load, because I load the whole page in that iframe. I could not make it work when I just stick a react component as iframe child as I showed in the previous comments.

**Comment by skornel02** [comment]
It seems strange, but reverting the Leaflet version to 1.6.0 seems to fix the TypeError, but it still does not work. 
It leads to a situation, where the dragging does not work inside the iFrame, but if you click inside the iFrame, and start dragging outside of the iFrame the map will move. I am inexperienced in the topic, nonetheless it seems to me this has to something with the event handlers, and the map's listeners being registered in the main window, not in the iFrame.
https://codesandbox.io/s/leafletjs-iframe-problem-with-older-leaflet-8pf9h

**Comment by JonatanRydh** [comment]
I think the issue could possibly be that leaflet bind events to `document` instead of `element.ownerDocument`.
