### ISSUE TITLE
Tooltip interactive disapear on mouseover

### ISSUE THREAD

**Issue by fredOpenscop** [Leaflet/Leaflet#7377]
Hello,

i just found an issue with the tooltip on leaflet 1.7.1, i'm almost sure it was working corectly in leaflet < 1.0

- [*] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [*] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [*] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
juste create a polygon with a tooltip with option interactive : true, when you try to mouseover the tooltip it will disapear.

**Expected behavior**
I expected to be able to have the mouse go over the tooltip just like when the interactive option if false.

**Current behavior**
The tooltip disapear when i try to mouseover it

**Environment**
- Leaflet version: 1.7.1
- Browser (with version): chrome 87.0.4280.88 & firefox 83.0 (64 bits)
- OS/Platform (with version): kunbuntu 20.04

**Minimal example reproducing the issue**
[codepen](https://codepen.io/fredOpenscop/pen/xxERYyj)

someone can confirm it is a bug? (I need this behavior for my current projet so that's why i found it)

Thanks for your time and this great library.

**Comment by Mansibisen** [comment]
@fredOpenscop  I will like to work on this issue.

**Comment by johnd0e** [comment]
I do not see any issue here, all works as expected.
Use `permanent` tooltips.
Or switch to popups.

**Comment by fredOpenscop** [comment]
> I do not see any issue here, all works as expected.
> Use `permanent` tooltips.
> Or switch to popups.

If i understand, if you want an interactive tooltip it need to be permanent?
I will use a third party module for the tooltip in that case, because i have tooltip with big content, if permanent it would occupy all the space ^^  

Thank for the reply.

**Comment by johnd0e** [comment]
> If i understand, if you want an interactive tooltip it need to be permanent?

Otherwise it will vanish on mouseover, which is expected.

Perhaps you'd like to have some delay before tooltip get closed (1), and leave it opened while it it under mouse pointer (2).
Special handling needed for such case.

If someone would implement this in PR, I suppose it'd have a pretty big chance to be accepted.

@fredOpenscop
You can open new Issue with this idea.

**Comment by Mansibisen** [comment]
@johnd0e  I will like to work on something like this
