### ISSUE TITLE
Circle/Polyline/Polygon disappears when preferCanvas:true

### ISSUE THREAD

**Issue by denyaalt** [Leaflet/Leaflet#7378]
Circle/Polyline/Polygon disappears when preferCanvas:true + replace baselayer + map.fitBounds()

**Steps to reproduce**
```
var google_terrain=L.gridLayer.googleMutant({type:'terrain'});
var google_road=L.gridLayer.googleMutant({type:'roadmap'});
var mapLayers={
  osm:L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',{attribution:'&copy; <a href="https://opentopomap.org">OpenTopoMap</a>'}),
  google:google_terrain,
};

var map=L.map('map',{tap:false,touchZoom:true,layers:[mapLayers['google']],preferCanvas:true}).setView([51.505, -0.09],5);
L.control.layers(mapLayers,{},{collapsed:false,bounceAtZoomLimits:false}).addTo(map);

var cicrle1,cicrle2,opt={direction:'center',permanent:true};

setTimeout(()=>{
  cicrle1=L.circle([50.5, 30.5],{radius:60000}).addTo(map).bindTooltip('1',opt).openTooltip(); 
  cicrle2=L.circle([40, 30.5],{radius:50000}).addTo(map).bindTooltip('2',opt).openTooltip();; 
  map.fitBounds(L.featureGroup([cicrle1,cicrle2]).getBounds());
},1000);
setTimeout(()=>{replaceBaselayer();},2000);
setTimeout(()=>{map.fitBounds(cicrle1.getBounds());},3000);
setTimeout(()=>{map.fitBounds(cicrle2.getBounds());},4000);

function replaceBaselayer() {map.removeLayer(google_terrain); map.addLayer(google_road);}
```

**Current behavior**
![test](https://user-images.githubusercontent.com/52670506/101931374-5cc91480-3bea-11eb-95d4-df4856eb2875.gif)

**Environment**
- Leaflet version: 1.7.1
- Browser (with version): Chrome 86.0
- OS/Platform (with version):

**Minimal example reproducing the issue**
[Example](https://playcode.io/452694)

**Comment by johnd0e** [comment]
Wrong repo chosen.
You may report to https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant/

**Comment by denyaalt** [comment]
I think this is a Leaflet bug.
Please change in the example, after the circle disappears, the base layer to osm and the circle will not appear.
The problem is not with GoogleMutant.

**Comment by johnd0e** [comment]
> I think this is a Leaflet bug.

Are you able to reproduce it without Googlemutant?
That post updated sample.

**Comment by IvanSanchez** [comment]
This is one of those "I wish people would check the browser's dev console and include relevant information gathered from there":

```
Uncaught TypeError: googleBounds is undefined
    _getLargeGMapBound Leaflet.GoogleMutant.js:481
    _pruneTile Leaflet.GoogleMutant.js:497
    setTimeout handler*_removeTile Leaflet.GoogleMutant.js:475
    _removeAllTiles GridLayer.js:458
    _invalidateAll GridLayer.js:468
    fire Events.js:190
    _resetView Map.js:1192
    setView Map.js:206
    fitBounds Map.js:295
    <anonymous> script.js:16
    setTimeout handler* script.js:13
```

**Comment by IvanSanchez** [comment]
Race condition on GoogleMutant due to the synthetic timeout introduced in https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant/-/merge_requests/25 (and how the timed-out callback runs when the mutant layer has been removed from the map). Tracking at https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant/-/issues/119 .

**Comment by denyaalt** [comment]
My console is clean!

![2020-12-13_17-50-34](https://user-images.githubusercontent.com/52670506/102015393-67abb280-3d6c-11eb-9c06-ca098209a73d.png)

**Comment by denyaalt** [comment]
> Race condition on GoogleMutant due to the synthetic timeout introduced in https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant/-/merge_requests/25 (and how the timed-out callback runs when the mutant layer has been removed from the map). Tracking at https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant/-/issues/119 .

The problem hasn't gone away. Please check the example.
What browser are you using? 
On my Windows 10 laptop, Chrome and Opera don't show any errors in the console.
