### ISSUE TITLE
Fetch all map-area tiles in one request

### ISSUE THREAD

**Issue by bongobongo** [Leaflet/Leaflet#7379]
When having the tiles in a database on the server (e.g. openmaptiles / tileserver), as it is now there is one request for each image, and each request cause open database, query one image in the database - and then return that single image (on the server). 

How about enable a load mode where e.g. after a pan end - leaflet send one request to server, and in this request there is data for doing one query against the database to get all the images needed to fill the map area (with tiles not allready visible in the map). In this mode leaflet get all the images in one response (e.g. json). 

The benefit for such a feature would be fever requests to server, fever processes (e.g. PHP) for each client on server, and fever queries on server. 
The downside would be a map where the adding of the tiles to the map is not so smooth as it is now, but there could be scenarios where less strain on the server is more important.

Does anyone know if there is a plugin which enable such a feature?
If not - maybe someone want to add it. 

If no plugin is available for this now, and someone could explain the basic way to implement such a feature in Leaflet, please feel free to do so.

**Comment by IvanSanchez** [comment]
This is a case of premature optimization. By narrowing down your definition of performance, you're forgetting about cases where no new tiles need to be requested (small movements on the map) or where few tiles are to be requested (your algorithm would re-request the entirety of the data fitting the viewport), and you're forgetting about HTTP/2, network caches, browser caches, tile caching proxies (I'm thinking mapproxy) and DB indexes, among other parameters.

I suggest you do a bit of research into WMS - both tiled and untiled; there are plugins for untiled WMS.

When it comes to performance problems, *measure* the performance bottlenecks, *then* think of an approach. Is the CPU overhead of more PHP processes/threads measurable in your system? What about the network overhead of non-keepalive HTTP TCP connections?
