### ISSUE TITLE
clickable map with neighbourhoods and streets and parcels

### ISSUE THREAD

**Issue by iwanneke** [Leaflet/Leaflet#7383]
I'm looking for a solution in regard of a map on which you are able to mark parcels, neighborhoods, parts of municipalities; municipalities; streets etc.

**Comment by johnd0e** [comment]
We use GitHub as an issue tracker and **do not provide support here**.
For usage and support questions, please check out resources below:

1. Read Leaflet documentation: https://leafletjs.com
2. For support questions like "How can I do X with Leaflet?" please search or ask questions on StackOverflow or StackExchange using Leaflet tag:
  - https://stackoverflow.com/questions/tagged/leaflet
  - https://gis.stackexchange.com/questions/tagged/leaflet

Thanks!
