### ISSUE TITLE
any3d misuse and other browser poking features

### ISSUE THREAD

**Issue by c-smile** [Leaflet/Leaflet#7385]
Name of this variable:
```var any3d = !window.L_DISABLE_3D && (ie3d || webkit3d || gecko3d) && !opera12 && !phantom;```
is misleading.

Lefalet is not using any 3D transformations actually as far as I can tell.

Instead ```any3d``` is used rather as ```hwaccelerated``` flag. But even in this case its use (as is-hw-accelerated flag) is not correct. In all browsers `translate(x,y)` and `translate3d(x,y,0)` use the same mechanism that is either H/W accelerated or is good enough for Leaflet purposes.

Please consider removal of browser feature testing using userAgent as [it is bad](https://css-tricks.com/browser-detection-is-bad/).

As far as I can tell Leaflet don't need anything more than [CSS.supports()](https://developer.mozilla.org/en-US/docs/Web/API/CSS/supports) can provide.

**Comment by IvanSanchez** [comment]
> Name of `var any3d` is misleading.

Not a reason good enough to introduce an API-breaking change. Plugins depends on this. Plus, it would impact fractional zoom support, iOS hacks, and a bunch of unit tests.

> Please consider removal of browser feature testing using userAgent as it is bad.

Won't do. Leaflet does feature detection, not user agent sniffing, as much as possible. Like, Leaflet is doing exactly what the article you linked to prompts devs to do.

(And yes we might consider dropping the remaining browser sniffing tests for Android v2-v3 at the same time we might drop IE8 support)

> As far as I can tell Leaflet don't need anything more than CSS.supports() can provide.

IE11 support, plus a bunch of weird engine-dependent stuff. My "favourite" example is https://github.com/Leaflet/Leaflet/blob/7db94fd1ec23f0967dd8b07a5e2e2b1554b6d8db/src/dom/DomEvent.DoubleTap.js#L62-L66

**Comment by c-smile** [comment]
I am running Leaflet on [Sciter.JS](https://sciter.com/sciter-js-runs-leafletjs-as-it-is/) - Sciter.JS is an ElectronJS replacement and uses its own HTML/CSS/JS implementations.

Problems:

1. Sciter.JS does not support ```translate3d()```  but does support ```translate()```.    
2. Sciter.JS uses H/W acceleration on all platforms.
3. It has its own ```navigator.userAgent``` that is different from browsers . 

In any case Leaflet fails to detect ```translate3d()``` support properly. That should be done

in CSS as : 
```css
@supports ( transform: translate3d(0,0,0) ) { 
   ...
}
```
and in JavaScript as 
```JavaScript
const supports3D = CSS && CSS.supports("transform", "translate3d(0,0,0)");
```

Current Leaflet browser feature detection approach will not allow it to work optimally on future browsers - not good.

**Comment by IvanSanchez** [comment]
At this point feel obliged to point you towards ["How To Ask Questions The Smart Way"](http://www.catb.org/esr/faqs/smart-questions.html) and ["How to Report Bugs Effectively"](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html), because this is a bad title for a bug report:

>  any3d misuse and other browser poking features

...while this would be a better one:

> L.Browser.any3d detection fails for Sciter.JS headless browser

Remember, explain the *problem*, not what you *wish* the solution would be.
