### ISSUE TITLE
Lazy loading for markers

### ISSUE THREAD

**Issue by mfcharaf** [Leaflet/Leaflet#7391]
**I'm new with leaflet so I'm still discovering features and I'm not sure if my request has already a solution in your project.**

**Is your feature request related to a problem? Please describe.**
I would like to load many markers on the map (talking about thousands) 

**Describe the solution you'd like**
An option to lazy load markers only when they are contained in the visual area of the map.

**Describe alternatives you've considered**
I thought using some sort of event when map is updated and only display markers on that zone and release hidden ones.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
