### ISSUE TITLE
Find reference to marker or polyline

### ISSUE THREAD

**Issue by fredleput** [Leaflet/Leaflet#7395]
Hi all,

I develop an app using react and leaflet. I try to fin a way to hightlight markers/polylines wwhen hovering elements out of my map.
I use React and i thought tant i could keep references of map, markers and polylines in a context but it causes an error (cyclic reference). I think these objects are too heavy to be stored in a context...
I tried to give my map a global reference (window.map) but it's ugly !

How is it possible from an element which is out of the map (a simple button for example, on which you have an id "marker-1234") to fire and event on the real marker ? the one on the map who have the id marker-1234.

I create marker the way :

```
// create start marker and add it to map
// generate a unique id based on etape id
// SM-id :  StartMarker-idEtape
var idDepart = 'SM-'+etape.id;
var markerDepart = L.marker(
  [etape.lieuDepart.lat, etape.lieuDepart.lng],
  {id: idDepart}
).addTo(window.map);
```

I would like to be able that when i mouseover dom element (item part of a listing side of map), who has a data-id equal to marker-1234, to change the marker (color, size anything)
```
// dom element that trigger the event
<li onMouseOver={highlight}>etape 1234<li>
```

```
// event listener
function hightlight(evt) {
  var idMarker = evt.target.dataset.id // marker-1234
  // highlight marker-1234 on map
}
```

Do i really need a global ref to map ?
Is there a good react / openlayer lib to manage this ? (didn't find her yet but i installed 4 of them)
Why cyclic reference when you try to store map object or event 1 marker in a react context ?

thx in advance, sure it's already have been done,
Fred, Brittany, France.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
