### ISSUE TITLE
Same page, one map is correct but the other map is displayed in broken map.

### ISSUE THREAD

**Issue by PerryWu** [Leaflet/Leaflet#7396]
- [O ] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [O ] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [ O] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- step 1. 
Please open the web page that have the issue, it is a blogger page trying to draw map. https://leaflettest.blogspot.com/p/leaflet-test.html
In that page, I have js codes in blogger page below. When someone open that page, it will run js code. And I have two map container, map-outer and map-inner.

```
<div id="map-inner"></div>

<link href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" rel="stylesheet"></link>
<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
<script>
function buildMap(idName)  {
    var mapId = idName + 'Id';
    document.getElementById(idName).innerHTML = "<div id='"+mapId+"' style='width: 100%; height: 400px;'></div>";
    var osmUrl = 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
                    osmAttribution = 'Map data © <a href="http://openstreetmap.org">OpenStreetMap</a>',
    osmLayer = new L.TileLayer(osmUrl, {maxZoom: 18, attribution: osmAttribution});
    var map = new L.Map(mapId);
    map.setView(new L.LatLng(24.804302033364856,120.9661604109331), 9 );
    map.addLayer(osmLayer);
}

</script>
<button id="ShowMapButton" onclick="buildMap('map-inner');">draw inner Map</button>
<button id="ShowMapButton" onclick="buildMap('map-outer');">draw outer Map</button>
```

- step 2
Click on "draw inner Map" button, the code will use leaflet to create map in inner page. It will show a broken map.
![image](https://user-images.githubusercontent.com/11898742/103481424-ebaa0500-4e15-11eb-8848-0bde18b17adb.png)

- step 3
Click on "draw outer Map", button, the code will use leaflet to create map in outer area. It will show correct map.
![image](https://user-images.githubusercontent.com/11898742/103481465-31ff6400-4e16-11eb-89ba-acd6772b76d9.png)

**Expected behavior**

The expected behavior is that Step 2 and Step3 should have correct map created.

**Current behavior**

In Step2, the map is displayed in broken map. Same code in step3 work well in outer area.

**Environment**
- Leaflet version:1.7.1
- Browser (with version): chrome 87.0.4280.88
- OS/Platform (with version): MacOS

**Additional context**

I have used map.invalidateSize(); in step 2 but no use.

**Minimal example reproducing the issue**

Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

**Comment by IvanSanchez** [comment]
[Cannot reproduce](https://plnkr.co/edit/fvZqMZ6NF5955jqz). (Do check your CSS rules)

**Comment by PerryWu** [comment]
Could you point out where I can find what kind of CSS rules might impact map creation, thanks?

**Comment by IvanSanchez** [comment]
https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_CSS , start with the misplaced tiles and then the map container. Look for non-leaflet rules being applied.
