### ISSUE TITLE
Pinch zoom defect: 1.7.x regression

### ISSUE THREAD

**Issue by johnd0e** [Leaflet/Leaflet#7401]
**Steps to reproduce**
- Open https://leafletjs.com/examples/quick-start/example.html
- Do some pinch zoom actions

**Expected behavior**
Drawn features should move and scale synchronously with map tiles

**Current behavior**
But they don't:
<details><summary>Video</summary>

https://user-images.githubusercontent.com/1838643/103991430-51dab300-519b-11eb-8150-e7974bdeab4c.mp4
</details>

**Environment**
- 1.7.1 as per https://leafletjs.com/examples/quick-start/example.html
- Webview or Chrome 87.0.4280.101
- Android 10 (but iOS is also affected)

**Additional context**
Leaflet 1.6.x does not have this issue

**Comment by johnd0e** [comment]
The issue is somehow similar to #6395 (but worse because it is observed permanently).
Anyway, steps to reproduce the issue in it's severest form are described there very well:
> * On a touch device, put one finger down onto the map.
> * Drag the map without lifting your finger.
> * Place another finger on the map.
> * Pinch-zoom with your two fingers.

https://user-images.githubusercontent.com/1838643/104015184-eefa1380-51bc-11eb-8265-5105098f9e9b.mp4

**Comment by johnd0e** [comment]
The issue is somehow similar to #6395, but reproduces just with pinch zoom gesture (without preliminary dragging).

**Comment by johnd0e** [comment]
ATM I have 2 alternative PRs that seems to solve this issue:
- #7029 ([example.html](https://gist.githack.com/johnd0e/dd2c9e32a1378b7d0d527d5f7fe9c624/raw/8f828dc7bb2ca172b35ec6aa8f854e85b6ec5de4/issue-7401.html))
- #7073 ([example.html](https://gist.githack.com/johnd0e/ef309a09cb37c444ad53ef28bd57f0f8/raw/issue-7401.html))

**Comment by johnd0e** [comment]
I have a PRs that solves this issue: #7073 (see [example.html](https://gist.githack.com/johnd0e/ef309a09cb37c444ad53ef28bd57f0f8/raw/issue-7401.html)).

**Comment by brienna** [comment]
> I have a PRs that solves this issue (well, it's rather workaround): #7073 (see [example.html](https://gist.githack.com/johnd0e/ef309a09cb37c444ad53ef28bd57f0f8/raw/issue-7401.html)).

Seems the issue still persists in the example? 

![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/9706870/135562377-81503554-3088-4eb5-9b02-ccded0ef895d.gif)

**Comment by Craigzyc** [comment]
Any resolution on this?

I have a not geographical map with polygons drawn on top. Zooming in or out on an iPhone causes the shapes to leave their coordinates, then snap upon release.

![image](https://user-images.githubusercontent.com/20641872/141200637-cc4d6c26-35f2-4326-8aec-25c0f8d8e6e5.png)
![image](https://user-images.githubusercontent.com/20641872/141200680-1bfc255c-c187-4dbf-bd0b-d48cd88fb1d9.png)
![image](https://user-images.githubusercontent.com/20641872/141200715-d400128c-fa6e-4380-9f38-34e46171e9ea.png)

I think its the same issue

**Comment by Craigzyc** [comment]
> Any resolution on this?
> 
> I have a not geographical map with polygons drawn on top. Zooming in or out on an iPhone causes the shapes to leave their coordinates, then snap upon release.
> 
> 
> I think its the same issue

Please disregard my comment. I did a major change to ensure this was leaflet, and realized it was an issue with the vue wrapper. 
After reimplementing it with the bare leaflet library I think I will just stick with that. 

Thanks

**Comment by brienna** [comment]
@Craigzyc you don't see this issue with the bare leaflet library? I'm using React, and I wonder if this is part of the problem.

**Comment by Craigzyc** [comment]
@brienna The issue of the polygon going in the wrong direction as its zoomed diverging away from its intended location as shown in my screen shots, and only redrawing correctly after releasing the screen is not present using leaflet in its bare form.
I'm not convinced the issues are related.

I do still have an issue where offscreen polygons are not drawn until the zoom or pan is released but thats not nearly as unusable as the polygon actually leaving its intended area.

**Comment by rasteiner** [comment]
Was this issue fixed "in the 1.7.1" release online? I have seen the "help wanted" label, but I'm unable to reproduce this issue on my device. (Pixel 5, Android 12, Chrome 97.0.4692.98)

https://user-images.githubusercontent.com/6684137/151982924-0627d527-49fd-468b-882c-ba17873b4352.mp4

**Comment by Falke-Design** [comment]
I'm able to reproduce the error and have already a fix but I need to check it again an then create the PR

**Comment by brienna** [comment]
@rasteiner it happens when I’m pressing down on a polygon while zooming - in your video, I’m not sure if I saw that action

**Comment by mourner** [comment]
I think I'll have some time to dig into this in the next few days during the beta period, perhaps we'll get a chance to fix this prior to v1.8.0.

**Comment by mourner** [comment]
Can you please check out the latest beta https://github.com/Leaflet/Leaflet/releases/tag/v1.8.0-beta.3 and see if everything's resolved?
