### ISSUE TITLE
Window scrolling stops working when CSS position: fixed and overflow-y: scroll

### ISSUE THREAD

**Issue by jan-drozen** [Leaflet/Leaflet#7404]
- [X] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [X] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
The issue appears if the DOM structure is like:

- topmost div with overflow-y: scroll
  - div of some height
    - absolute div
      - leaflet div with fixed position (map has disabled wheel scrolling, of course)

**Expected behavior**
You should be able to scroll the browser window away from the leaflet map.

**Current behavior**
If you now scroll down to the leaflet, click on the map then you are not able to scroll away anymore.

**Environment**
- Leaflet version: 1.7.1
- Browser (with version): Chrome 87, Edge
- OS/Platform (with version): Windows 10 x64

**Additional context**
The issue disappears when removing overflow-y: scroll from the topmost div or if you change the position: fixed to absolute.

**Minimal example reproducing the issue**

https://jsfiddle.net/Drozi/bp0g9src/36/

- [X] this example is as simple as possible
- [X] this example does not rely on any third party code

**Comment by Malvoz** [comment]
@jan-drozen This seems to be a CSS authoring issue, or potentially a browser bug.

If you remove the JS in your fiddle (and add `background: red;` to `#fixedContainer` to be able to see where to click) then follow the repro steps, you'll have the same issue. Entirely without a Leaflet map.

As such I'll close this issue. Feel free to continue discussing if you still think it's a Leaflet issue.
