### ISSUE TITLE
Drag + Pinch defect in canvas

### ISSUE THREAD

**Issue by johnd0e** [Leaflet/Leaflet#7407]
**Steps to reproduce**
- Open [example.html](https://gist.githack.com/johnd0e/0dae9ffafbee96b41ad2872a8764a847/raw/example.html), which is almost identical to https://leafletjs.com/examples/quick-start/example.html with only map options added: `{preferCanvas: true, tap: false};`
1) Drag the map with single touch in any direction (and keep touching).
2) Add second touch in any place, and observe unexpected shift of drawn features.
3) Release second touch and observe that drawn features returns to their proper places (animated).
4) Repeat steps 1-3 but in opposite direction, and observe same effects.
<details>

https://user-images.githubusercontent.com/1838643/104444070-f09e4f80-559f-11eb-805d-3e2077b6e1ba.mp4
</details>

As I can see, after 2nd touch canvas offset doubles (in the direction of initial move).

**Environment**
- Leaflet version: [1.0.0](https://leafletjs.com/examples/quick-start/example100.html) - 1.7.1
- Browser (with version): any
- OS/Platform (with version): Android 10 ( (but iOS is also affected))

**Comment by Falke-Design** [comment]
> Did PR #7965 fix #7407?
>_Originally posted by @stephenspol in https://github.com/Leaflet/Leaflet/issues/8117#issuecomment-1088262494_

@stephenspol yes this is also fixed. Thank you.

Here the example with the newest 1.8.0-beta.3: [example](https://gist.githack.com/Falke-Design/b07ece1a0363437e85974a8b75eedd54/raw/d1ab06a0ee1205bbc82a95c5b0b4cc30adc3f566/index.html)
