### ISSUE TITLE
Auxclick event handler not executed

### ISSUE THREAD

**Issue by terax6669** [Leaflet/Leaflet#7421]
**Steps to reproduce**
- `marker.on({auxclick: () => { console.log('Leaflet marker auxclick fired') }})`
- right/middle click on the marker

**Expected behavior**
Event handler is executed

**Current behavior**
Event handler is not executed

**Environment**
- Leaflet version: 1.7.1
- Browser: Firefox 84.0.2 (64-bit) / Chromium 88.0.4324.96 (Official Build) (64-bit)
- OS/Platform: Windows 10 Pro 20H2

**Minimal example reproducing the issue**

https://plnkr.co/edit/Rn26TJRayLvhggBh

```vue
<template>
	<div id="mapid" style="height: 600px; width: 800px"></div>
</template>

<script>
import * as L from 'leaflet'
import { Vue } from 'vue-class-component'

import 'leaflet/dist/leaflet.css'

export default class LeafletMap extends Vue {
	mounted() {
		const map = L.map('mapid').setView([51.505, -0.09], 13)
		const marker = L.marker([51.505, -0.09])
		marker.on({click: () => { console.log('Leaflet marker click fired') }})
		marker.on({auxclick: () => { console.log('Leaflet marker auxclick fired') }})
		map.addLayer(marker)
	}
}
</script>
```

**Comment by IvanSanchez** [comment]
Leaflet interactive layers [do not handle any `auxclick` event](https://leafletjs.com/reference-1.7.1.html#interactive-layer-event), so this is behaviour as expected.

(Note that Leaflet events are not the same as DOM events)
