### ISSUE TITLE
GeoJSON's latLngToCoords/latLngsToCoords do not accept Array form of LatLng

### ISSUE THREAD

**Issue by johnd0e** [Leaflet/Leaflet#7425]
https://leafletjs.com/reference-1.7.1.html#latlng

> All Leaflet methods that accept LatLng objects also accept them in a simple Array form and simple object form (unless noted otherwise)

But `L.GeoJSON.latLngToCoords`/`latLngsToCoords` do not accept Array form:
https://github.com/Leaflet/Leaflet/blob/436430db4203a350601e002c8de6a41fae15a4bf/src/layer/GeoJSON.js#L256-L263

That should be documented.
Or fixed (not sure whether it would be really useful).

**Comment by Rishabhraghwendra18** [comment]
@Relkfaw is this issue open ?If yes may I work on it ?

**Comment by johnd0e** [comment]
@Rishabhraghwendra18
What exactly are you going to do with it?

**Comment by Rishabhraghwendra18** [comment]
@johnd0e I am beginner to open source contribution 😅 . I found that this issue is open , good first issue something related to docs and no one has taken it . So I think I can contribute to it .

**Comment by johnd0e** [comment]
In fact #7436 can fix this issue too.
We haven't reviewed that yet, so I'm not sure.

**Comment by Rishabhraghwendra18** [comment]
Ok..no problem. Thanks
