### ISSUE TITLE
License missing from download and web page is not clear about which license is used

### ISSUE THREAD

**Issue by oskarb** [Leaflet/Leaflet#7426]
Please consider improving how the license is communicated.

I can't find any mention on leafletjs.com about the license. Maybe there is one, but my point is that it should be easy to find.

I did eventually find the LICENSE file in github, which is good, but it doesn't actually say which open-source license it is. Not knowing the text of all licenses exactly, I had to research and compare the text at https://opensource.org/licenses.

For example, the front page starts with this line currently:

> Leaflet is the leading open-source JavaScript library for mobile-friendly interactive maps. Weighing just about 39 KB of JS, it has all the mapping features most developers ever need.

This could be changed to insert this text after "open-source":

> (BSD 2-Clause license)

The text within parentheses would be a link to the LICENSE file in github.

Similar change could be made to the Readme in github.

Furthermore, the license stipulates that:

> Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

However, the download of leaflet.zip from leafletjs.com does not itself include the license. I think this is unfortunate, and that the download should include the LICENSE file to make it easier to comply with the terms of the license.

**Comment by jalajcodes** [comment]
@johnd0e Can I take this issue?

**Comment by johnd0e** [comment]
Sure

**Comment by HRSArgyropoulos** [comment]
Linked github license url after open-source text like this;

`... open-source (<a title="Leaflet's open-source license, BSD 2-Clause" href="https://github.com/Leaflet/Leaflet/blob/master/LICENSE">BSD 2-Clause license</a>) Javasript ...`

https://github.com/HRSArgyropoulos/Leaflet/commit/22c7b86277972e10d2ebf9580f00f411d606c031

**Comment by johnd0e** [comment]
@oskarb 
Are you happy with #7426?

**Comment by oskarb** [comment]
@johnd0e #7480 looks good to me. Will there also be a change to include the license file in the downloads?

**Comment by johnd0e** [comment]
> Will there also be a change to include the license file in the downloads?

Better ask @mourner, as I'm have now own interest in this subject.

**Comment by Falke-Design** [comment]
> Not necessary because GitHub exposes License information prominently:

_Originally posted by @mourner in https://github.com/Leaflet/Leaflet/issues/7480#issuecomment-985460197_
