### ISSUE TITLE
DomEvent functions not covered by tests

### ISSUE THREAD

**Issue by johnd0e** [Leaflet/Leaflet#7434]
We have some [DomEvent](https://github.com/Leaflet/Leaflet/blob/master/src/dom/DomEvent.js) tests here: https://github.com/Leaflet/Leaflet/blob/master/spec/suites/dom/DomEventSpec.js, but not all functions are covered.

Here the list of lacking tests:
1. `on(<HTMLElement> el, <String> types, <Function> fn, <Object> context?)` (where `types` has several events)
2. `on(<HTMLElement> el, <Object> eventMap, <Object> context?)`
3. `off(<HTMLElement> el, <String> types, <Function> fn, <Object> context?)` (where `types` has several events)
4. `off(<HTMLElement> el, <Object> eventMap, <Object> context?)`

Note: some `on`/`off` tests implemented in #7125.

5. `stop(<DOMEvent> ev)`
6. `getMousePosition(<DOMEvent> ev, <HTMLElement> container?)`
7. `getWheelDelta(<DOMEvent> ev)`

Ref: https://leafletjs.com/reference-1.7.1.html#domevent

Note:
When implementing required test cases consider minor refactoring in #7438 (which already has tests for `disableScrollPropagation` and `disableClickPropagation`).

---
Related:
- [x] `DomEvent.DoubleTap.js` is covered by #7027.
- [x] `DomEvent.Pointer.js` is covered by #7415.

**Comment by Crimson-riot** [comment]
Is this available to be worked on? If so I can work on it?

**Comment by johnd0e** [comment]
Sure, but base it on #7438

**Comment by Crimson-riot** [comment]
Will do!

**Comment by johnd0e** [comment]
See also #7126.

**Comment by Crimson-riot** [comment]
So I think I have the tests in a good place on https://github.com/Crimson-riot/Leaflet/tree/expand-DomEventSpec-onoff based on #7438 . Considering that is still out as a PR, how would you prefer that I create a pull request for this? Should I make a pr into johnd0e/improve-DomEventSpec?

**Comment by johnd0e** [comment]
> Should I make a pr into johnd0e/improve-DomEventSpec?

No, it is not necessary, you may make PR to `master` (but branch from `improve-DomEventSpec`).

**Comment by Crimson-riot** [comment]
Ok, #7453 is up and based on #7438 but it seems like I cannot link that PR to this issue
