### ISSUE TITLE
Map moves when handling a custom control with a draggable input ( input type="range" )

### ISSUE THREAD

**Issue by vump** [Leaflet/Leaflet#7456]
- [ x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [ ] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x ] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- Open codepen: https://codesandbox.io/s/brave-cherry-k690v
- Drag both controls in the upper right corner
- ...

**Expected behavior**
Map remains at it's current position, and the controls should be manipulated.

**Current behavior**
Custom material-ui component: Only works by clicking on the line ( dragging the handle doesn't work )
The default browser input is draggable, but the map moves with the mouse cursor

**Environment**
- Leaflet version: 1.7.1
- Browser (with version):Any 
- OS/Platform (with version): Any

**Additional context**

**Minimal example reproducing the issue**

Example: https://codesandbox.io/s/brave-cherry-k690v

- [ x] this example is as simple as possible
- [ ] this example does not rely on any third party code

**Comment by johnd0e** [comment]
Just use [disableClickPropagation](https://leafletjs.com/reference-1.7.1.html#domevent-disableclickpropagation).

**Comment by vump** [comment]
@johnd0e Thanks for the tip, but that doesn't work. I've tried it. It disables the clicks, but not the 'dragging'

**Comment by johnd0e** [comment]
Unfortunately we can't help you with React.

**Comment by vump** [comment]
@johnd0e I'm not asking for help with React. I wonder what happens to the HTML MouseEvent? 
It seems to get canceled or prevented or discarted? I want to figure out whats wrong.. so the problem can be fixed.
If any framework/user is attaching listeners to the window/rootnode level for performance reasons, things should not stop working?
I know you could simply add an event listener to the button itself and handle it that way, looks to me like using ducktape to fix a car.

**Comment by johnd0e** [comment]
> I'm not asking for help with React.

So are you able to reproduce the same issue without React or not?

**Comment by vump** [comment]
Took me a while to figure out their setup, but in plain vanillaJS
https://codesandbox.io/s/upbeat-cerf-04cjb

I've added the same slider component below the map to illustrate that it works there, but not in a Control 'container'

**Comment by johnd0e** [comment]
Now I see your issue.
This is expected by design.

Try `useCapture` with addEventListener.
