### ISSUE TITLE
Default Class options are changing

### ISSUE THREAD

**Issue by Falke-Design** [Leaflet/Leaflet#7458]
1. I create a rectangle
2. While creating, I call initHook and creating a new instance of a custom class (`L.Class.extend`)
3. I change the options of the class on the rectangle
4. The options of the prototype of the class are changed

**Expected behavior**
The options of the extended L.Class should never changed from outside

**Environment**
- Leaflet version: 1.7.1

**Test**
```
L.PM = L.Class.extend({
   options: {
  	test: 1,
        something: true
  }
})

function initRectangle() {
  this.pm = new L.PM(this);
}
L.Rectangle.addInitHook(initRectangle);


console.log(L.PM.prototype.options)

var rect = L.rectangle(map.getBounds()).addTo(map);
rect.pm.options.x = 'option changed'

console.log(L.PM.prototype.options)
```
https://jsfiddle.net/falkedesign/gwj6dphf/

When I add following the connection / reference between the options breaks:
```
var rect = L.rectangle(map.getBounds()).addTo(map);
L.setOptions(rect.pm,{a: 'xxx'})
rect.pm.options.x = 'option changed'
```

**Comment by johnd0e** [comment]
Perhaps it is fixed by #6766

**Comment by Falke-Design** [comment]
@johnd0e your PR doesn't fix it. I create one by my self

**Comment by johnd0e** [comment]
That's good.

I can confirm the issue, but your description is unclear, so here is my try: https://github.com/Leaflet/Leaflet/pull/7459#pullrequestreview-586639979
