### ISSUE TITLE
How to increase the precision of L.geoJson with more than 6 decimals

### ISSUE THREAD

**Issue by CityBelfast** [Leaflet/Leaflet#7462]
Hi, 
I've a  geometry with 16 decimal place coordinates. When I load the features via L.geoJson, leaflet is rounding all values to 5 or 6 decimals. Due to this, some of the coordinates are turn into same value in the coordinate list.  As a result, we are not getting the accuracy of the geometry.  is there any option where we can increase the decimal place in the leaflet while using L.geoJson?

**Original Coordinates in the geometry**
![image](https://user-images.githubusercontent.com/76213912/107414444-e96c5200-6b09-11eb-8f38-fde2ed3a194e.png)

**After loading into the layerGroup via L.geoJson** 
![image](https://user-images.githubusercontent.com/76213912/107414518-04d75d00-6b0a-11eb-89f6-08fe292bc02c.png)

**Comment by johnd0e** [comment]
Related: #6681

**Comment by CityBelfast** [comment]
The above mentioned link is the resolution for my issue  as I didn't get any idea how to resolve my issue after looking at #6681?

**Comment by johnd0e** [comment]
Please show sample of your code.
E.g., I do not see any problem using such:
```js
L.geoJson({"type": "Feature",
  "geometry": {
    "type": "Polygon",
    "coordinates": [ [ [1.123456789, 2.123456789], [3.123456789, 4.123456789], [5.123456789, 6.123456789] ] ]
  }
});
```

**Comment by CityBelfast** [comment]
Please see the blow Sample code of mine.

let lyrGroup = new L.featureGroup().addTo(map);

let data = { "type": "FeatureCollection", "features": [{ "type": "Feature", "geometry": { "type": "Polygon", "coordinates": [[[278657.8499999996, 187313.8000000007], [278652.4000000004, 187304.8499999996], [278652.1840000004, 187304.9810000006], [278650.7429999998, 187302.6699999999], [278649.426, 187302.159], [278646.4589999998, 187303.9460000005], [278646.2290000003, 187305.2449999992], [278646.216, 187305.3169999998], [278647.7000000002, 187307.6999999993], [278653.0999999996, 187316.6999999993], [278657.8499999996, 187313.8000000007]]] }, "properties": {} }] };
L.geoJson(data, {
       coordsToLatLng: function (coords) {        
            let r = GridToLatLng(coords);
        return r;
           },
    onEachFeature: function (feature, layer) {
        layer.bindContextMenu({
            contextmenu: true, contextmenuItems: [
                {
                    text: "Select", index: 0, callback: function () {

                        let fc = lyrGroup.toGeoJSON();
                        L.geoJson(fc, {
                            onEachFeature: function (feature, layer) {
                                fn.$LayerToMerge.addLayer(layer);
                                lyrGroup.clearLayers();
                            }
                        });

                    }
                }
            ]
        });
    }
}).addTo(fn.lyrGroup);


function GridToLatLng(xy) {
    let proj4LatLng = proj4("EPSG:27700", "EPSG:4326", xy);
    return L.latLng(proj4LatLng[1], proj4LatLng[0]);
}

**Comment by CityBelfast** [comment]
could I get any advice on this issue please?

**Comment by johnd0e** [comment]
> Please see the blow Sample code of mine.

Why not provide ready-to-run sample with all the required data included?

**Comment by johnd0e** [comment]
Here I do not see any problem:
```js
let lyrGroup = new L.featureGroup().addTo(map);
let lyrToMerge = new L.featureGroup().addTo(map);

let data = { "type": "FeatureCollection", "features": [{ "type": "Feature", "geometry": { "type": "Polygon", "coordinates": [[[278657.8499999996, 187313.8000000007], [278652.4000000004, 187304.8499999996], [278652.1840000004, 187304.9810000006], [278650.7429999998, 187302.6699999999], [278649.426, 187302.159], [278646.4589999998, 187303.9460000005], [278646.2290000003, 187305.2449999992], [278646.216, 187305.3169999998], [278647.7000000002, 187307.6999999993], [278653.0999999996, 187316.6999999993], [278657.8499999996, 187313.8000000007]]] }, "properties": {} }] };
L.geoJson(data, {
    onEachFeature: function (feature, layer) {
        debugger;
    }
}).addTo(lyrGroup);
```
What is done inside `proj4` - I do not know.
But it is not a part of Leaflet anyway.

**Comment by johnd0e** [comment]
Try this after your code:
```js
console.log(lyrGroup.toGeoJSON().features[0].geometry.coordinates[0]);
```
And compare output with this:
```js
console.log(lyrGroup.toGeoJSON(10).features[0].geometry.coordinates[0]);
```

**Comment by CityBelfast** [comment]
> > Please see the blow Sample code of mine.
> 
> Why not provide ready-to-run sample with all the required data included?
> And without any unrelated code

Proj4 just convert Actual coordinates into latlng coordinates.

**Comment by CityBelfast** [comment]
> ```js
> lyrGroup.toGeoJSON(10)
> ```

yeah sure , I will try passing precision argument in .toGeoJSON
