### ISSUE TITLE
Vector layers drift away on flyTo when zoomAnimation = false

### ISSUE THREAD

**Issue by Fischerfredl** [Leaflet/Leaflet#7466]
![drifting](https://user-images.githubusercontent.com/2673788/107643908-070afa00-6c77-11eb-9c73-97d42c4f124d.gif)

- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- create a map with option `zoomAnimation: false`
- create a vector layer (e.g a polygon) and add to map
- use map.flyTo() to pan to any point

**Expected behavior**
Vector layers follow the movement of the map.

**Current behavior**
Vector layers drift away while panning. When the target is reached they snap to their proper location. 
This is even more perceptible when the zoom levels between the current position and the target differ. 

**Environment**
- Leaflet version: 1.7.1
- Browser (with version): Firefox 85.0.1
- OS/Platform (with version): Ubuntu 20.10

**Additional context**
My current workaround is to set `mapInstance._zoomAnimated = true` before I add a layer and `map._zoomAnimated = false` right after. This way the animation handler will be registered in [src/layer/vector/Renderer.js](https://github.com/Leaflet/Leaflet/blob/620bc3e9c5d282090f429ac21d28d00fbffdb3db/src/layer/vector/Renderer.js#L76) while keeping the zoom animation disabled.

**Minimal example reproducing the issue**

https://plnkr.co/edit/qHqGIded24Z4MYtO

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by johnd0e** [comment]
Perhaps same roots as in #7072

**Comment by ebrensi** [comment]
Does this just happen with pinch-zoom/panning on a touchscreen?

**Comment by Fischerfredl** [comment]
> Does this just happen with pinch-zoom/panning on a touchscreen?

This happens by programmatically triggering the flyTo/flyToBounds method e.g. through a button. I experience this in Firefox and Chromium on a Laptop running Ubuntu. There is no built-in touchscreen.

**Comment by Fischerfredl** [comment]
I have got a more general applicable workaround that might help:

```javascript
const originalOnAdd = L.Renderer.prototype.onAdd
L.Renderer.prototype.onAdd = function () {
  originalOnAdd.call(this, arguments)
  L.DomUtil.addClass(this._container, 'leaflet-zoom-animated')
}
```

It specifically runs the excluded code path in [Renderer.js - onAdd](https://github.com/Leaflet/Leaflet/blob/234e00bcab0d89319f4c6874f3063ac311ce8cc6/src/layer/vector/Renderer.js#L54) method where the `leaflet-zoom-animated` class is set to the renderer-container. This fixes the difting layers while keeping other zoomAnimation effects disabled.

**Comment by johnd0e** [comment]
> I have got a more general applicable workaround that might help:

Cool!
May be you will be even able to fix the roots of the issue?

**Comment by Fischerfredl** [comment]
I can offer to investigate further as soon as I have the time. Could be next week.

**Comment by BasieP** [comment]
Any progress on this? we can still see this happening.. 
Anyone did investigate?
