### ISSUE TITLE
Is the 250ms delay in _animateZoom still necessary?

### ISSUE THREAD

**Issue by ebrensi** [Leaflet/Leaflet#7468]
**Is your feature request related to a problem? Please describe.**
I have been playing around with the Leaflet source code a little bit and found that I can make zooming by scroll-wheel and touchpad much smoother and nicer if I lower or get rid of the 250ms delay here:
https://github.com/Leaflet/Leaflet/blob/e76f97cba319d97482e395279000ac95de5a8d99/src/map/Map.js#L1695-L1696

It works fine for me in Chrome dev 89.0.xxx but I am concerned about making that part of my app's build.  Apparently that delay was put there to deal with a WebKit bug.  Is that still a problem?

**Describe the solution you'd like**
I would like to assess whether it is safe to lower or remove that delay without making LeafletJS not work for a lot of people.  I would like for that delay to be removed, or made into layer setting so that I can change it without having to use my own fork of Leaflet.

I want to get rid of the 250ms delay.  It makes zooming unpleasant.

**Describe alternatives you've considered**
I've tried using my own fork of Leaflet and it works great on the limited selection of browsers that I use.

**Additional context**

**Comment by johnd0e** [comment]
1st, you should describe your issue in detail, provide sample code (to let us to reproduce the same conditions), make make short video to illustrate issue.
Is it possible to reproduce with touchscreen?

Then we will be able to decide if this code line is needed or not (and under what conditions).

**Comment by ebrensi** [comment]
Meh, not worth it.  Also I think that may not be the bottleneck in my case.
