### ISSUE TITLE
Leaflet map fixing to zoom level exactly shows only world map view.

### ISSUE THREAD

**Issue by sgadiparthiui** [Leaflet/Leaflet#7474]
Hi Team,
Thanks for the great development and keep progressing on. Here, I have a challenge to display a map zoom level fix on certain area of the screen display.  let me know the properties to use to fix the zoom level map view in a certain level of the screen.
Thank you....

**Comment by johnd0e** [comment]
E.g. https://github.com/unbam/Leaflet.ZoomLabel

**Comment by sgadiparthiui** [comment]
Which should stick on to display 70% of the screen.

**Comment by johnd0e** [comment]
--------------^ Click "Preview" tab for a nicer view!

We use GitHub as an issue tracker and **do not provide support here**.
For usage and support questions, please check out resources below:

1. Read Leaflet documentation: https://leafletjs.com
2. For support questions like "How can I do X with Leaflet?" please search or ask questions on StackOverflow or StackExchange using Leaflet tag:
  - https://stackoverflow.com/questions/tagged/leaflet
  - https://gis.stackexchange.com/questions/tagged/leaflet

Thanks!

**Comment by johnd0e** [comment]
P.S.
I am not sur what do you want to achieve, may be you need https://leafletjs.com/reference-1.7.1.html#map-fitbounds, anyway here is not right place to discuss it further.
