### ISSUE TITLE
RemoveLayer function on map not working

### ISSUE THREAD

**Issue by neeraj43** [Leaflet/Leaflet#7486]
map.removeLayer(polyline) giving error:
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
but 
map.hasLayer(polyline) is giving true

- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- step 1
- step 2
- ...

**Expected behavior**

**Current behavior**

**Environment** 
<script src="vendor/leaflet/leaflet.js"></script>
this script is used
- Leaflet version:
- Browser (with version): Chrome
- OS/Platform (with version): Mac(Apple)

**Additional context**

**Minimal example reproducing the issue**

Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?

**Comment by neeraj43** [comment]
hello

it is getting generated in my code,and also its not happening every time,so
whats can be done in this case

**Comment by neeraj43** [comment]
how can we get this resolved

**Comment by johnd0e** [comment]
> how can we get this resolved

Most likely the culprit is somewhere in your own code.
Try to find exact way to reproduce the issue, then debug it.

There is no other way.
(Feel free to reopen)

**Comment by neeraj43** [comment]
can we connect for the issue
how is it possible that leaflet have layer but not able to remove it

**Comment by johnd0e** [comment]
> how is it possible that leaflet have layer but not able to remove it

Unable to say anything without seeing reproducible sample.

**Comment by neeraj43** [comment]
this is the code i am using with my map,i think it should work in all maps,
Map not able to remove its own layer and giving error that
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is
not a child of this node.

for(i in this.map._layers) {
if(this.map._layers[i]._path != undefined) {
this.map.removeLayer(this.map._layers[i]);
}
}

**Comment by johnd0e** [comment]
We can do nothing unless you provide some sample code to reproduce the issue.
Try to make it as short as you can, removing any unrelated parts.
You may want to use some online sandbox like plnkr, jsfiddle, etc.
