### ISSUE TITLE
Why does setUrl apparently "add more layers" into on("load", {}) event?

### ISSUE THREAD

**Issue by kwankong** [Leaflet/Leaflet#7488]
Is someone more familiar with the Leaflet codes able to explain this behavior of setUrl?

I have set up a Plunker to illustrate this behavior: https://plnkr.co/edit/LFQVaaUOugQ3ZBHn

In this example, I use imageOverlay to add a single image layer.  I have two buttons on top that would allow you to invoke setUrl to either reload its image, or to switch to another image.  I also have a function "setLoadEvent" that counts the number of layers loaded (nLayers), together with another variable nLayersLoaded that counts the number of layers inside an on("load", {}) event.

Why would nLayersLoaded be increased by one when either one of the buttons is clicked?  Note that both nLayers and nLayersLoaded are reset to zero when you click the buttons, but nLayersLoaded is still increased by one whenever one of the buttons is clicked and setUrl is invoked.

**Comment by johnd0e** [comment]
Note that do not provide support here (https://github.com/Leaflet/Leaflet/blob/master/.github/ISSUE_TEMPLATE/support.md).

> Why would nLayersLoaded be increased by one when either one of the buttons is clicked?

If you believe that this behavior does not conform to [docs](https://leafletjs.com/reference.html) - please open Issue describing the bug in details.
