### ISSUE TITLE
https://leafletjs.com/ is showing over map after some time

### ISSUE THREAD

**Issue by markoarula** [Leaflet/Leaflet#7491]
After some time (I'm not sure how much) https://leafletjs.com/ website appears over map.

Is there some option to turn that off and why is this happening after all.

![image-1](https://user-images.githubusercontent.com/27228538/109806510-17364980-7c25-11eb-94d9-8be8b75dd24e.jpeg)

**Comment by johnd0e** [comment]
> Is there some option to turn that off

There is no such feature in Leaflet.
But there is link to website in attribution control, and if someone  tapped on it..
If you observe this behavior without user interaction - it is not Leaflet bug.

BTW, attribution control can be turned off.

**Comment by IvanSanchez** [comment]
That's a... tourist information screen for the croatian city of [Omiš](https://en.wikipedia.org/wiki/Omi%C5%A1). Wow.

Must be a bug in whatever system they got to display a tourist map on that screen. Definitely not the responsibility of the Leaflet maintainers.
