### ISSUE TITLE
SVG renderer tolerance does not work for paths

### ISSUE THREAD

**Issue by nekromoff** [Leaflet/Leaflet#7494]
- [x ] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [ x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [ x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
use custom renderer:
```
var renderer=L.svg({ padding: 0.5, tolerance: 10 });
 var map = L.map('map', {
            center: core.options.center,
            zoom: core.options.zoom,
            zoomSnap: 0.5,
            zoomDelta: 0.5,
            tap: false, // fixes Safari issues with popups
            renderer: renderer,
...
});

add renderer to polylines:
```
var polyline_options = {
            renderer: renderer
        };
polyline = L.polyline([nodes], polyline_options);
```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->
Touch events working on the set tolerance, eg. +10 pixels

**Current behavior**
<!-- A clear and concise description of what is actually happening. -->
no tolerance, path only clickable dirctly on their `width`

**Environment**
- Leaflet version: 1.7.1
- Browser (with version): Firefox 86
- OS/Platform (with version): Ubuntu 20.04

**Comment by johnd0e** [comment]
https://github.com/Leaflet/Leaflet/blob/bc918d4bdc2ba189807bc207c77080fb41ecc196/src/layer/vector/Path.js#L143-L146

That was never meant to work with SVG, as you can see in comment.
So.. documentation should be corrected (e.g. we could add statement that the option requires support from renderer, and SVG lacks one).

**Comment by nekromoff** [comment]
Ok, thanks for the clarification, I didn't understand that from the docs.

**Comment by Hippl-Eric** [comment]
I can update the docs if this still needs to be completed.

**Comment by johnd0e** [comment]
> I can update the docs if this still needs to be completed.

Yes, this still do.
