### ISSUE TITLE
`.leaflet-active` may cause more than 1 component to be outlined simultaneously

### ISSUE THREAD

**Issue by Malvoz** [Leaflet/Leaflet#7499]
## Motivation

It seems that `.leaflet-active` may sometimes cause more than 1 component to be outlined simultaneously, this can be confusing because it is not clear which one is currently focused (and subject to input):

<img width="250" src="https://user-images.githubusercontent.com/26493779/110579131-679e3180-8166-11eb-90fc-f95f456833f6.jpg" alt>

## Additional context

In our `<mapml-viewer>` custom component we [fixed](https://github.com/Maps4HTML/Web-Map-Custom-Element/blob/cd14e28cee43a161579cb2f7d047cee40ec26300/src/mapml.css#L351-L355) this using the following CSS:

```css
.leaflet-active:not(:focus) {
  outline: unset !important;
}
```

**Comment by johnd0e** [comment]
> It seems that `.leaflet-active` may sometimes cause more than 1 component to be outlined simultaneously

1. What is 'sometimes'? Could you provide exact sequence of actions to reproduce that?
2. I see that `.leaflet-active` is used in `tap` handler, which is about to be withdrawn itself (see pinned issue).
So question is: do we still need processing of `.leaflet-active`?

https://github.com/Leaflet/Leaflet/blob/32ea41baaa93adcefd34006a12ebe3b4ee7fda7d/src/map/handler/Map.Tap.js#L59-L62

**Comment by Malvoz** [comment]
I say "sometimes" because it's not clear to me when this may occur, the attached image in my original comment is more than 6 months old as of today. The sequence of actions in that case was probably:
1. Activate fullscreen
2. De-activate fullscreen
3. Tap hold to open context menu

**Comment by johnd0e** [comment]
> 2\. used in `tap` handler, which is about to be withdrawn itself

https://github.com/Leaflet/Leaflet/pull/7026/commits/6f3f34cd796494d0447fb4dff4e53ceee255b267
