### ISSUE TITLE
rotated map inside an rotated page

### ISSUE THREAD

**Issue by bluelemonade** [Leaflet/Leaflet#7512]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

when rotating a div with an map inside, the touch movements didn;t change the direction of the finger movement, when the div is rotated 180° the  movement is mirrored.

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?

**Comment by bluelemonade** [comment]
https://codepen.io/fillthegap/pen/XWNQPOM

you can change the degrees, the leaflet api ist amazing, I use it on an multitouch table, several maps opened, clusters, works great, the only problem is this rotation issue, would be great to pass the rotation to the map an transform the events.

regards.

**Comment by bluelemonade** [comment]
I dived into your amazing code, there's no proble  to pass another option like extranlrotation to the map. I think the movement of the map is done in setPosition. 

I am not yet sure in which level this setPosition( el, point) takes place? on the complete map? somehow I would have to subtract the new postion from the current position and transform the x y differences with sin and cos, then add these correction values to the current point. I'll try it.

  // @function setPosition(el: HTMLElement, position: Point)
  // Sets the position of `el` to coordinates specified by `position`,
  // using CSS translate or top/left positioning depending on the browser
  // (used by Leaflet internally to position its layers).
  function setPosition(el, point) { 
	console.log("setPosition",  point, getPosition(el) );
  	/*eslint-disable */
  	el._leaflet_pos = point;
  	/* eslint-enable */

  	if (any3d) {
  		setTransform(el, point);
  	} else {
  		el.style.left = point.x + 'px';
  		el.style.top = point.y + 'px';
  	}
  }

**Comment by bluelemonade** [comment]
for me it works with setPosition, cluster points or markers works fine, borders and movement back when I reached the border of the map, everything works.

yesterday evening I checked with a rotation of 180 ° (the simplest problem) therefore the delta between currpoint and lastpoint is switched, and it works.

if I understand how I can get the external rotation into the map via options and have it available in setPosition, it should actually work.

**Comment by johnd0e** [comment]
> for me it works with setPosition [...]

Attach listener to map to log latlng of click

**Comment by bluelemonade** [comment]
ok, I see the problem. I deactivate the dragging and show some arraw buttons to move, when the mapis rotated on the table.

**Comment by stefanocudini** [comment]
in some use cases I think that this plugin can reduce the orientation UX problems
 https://github.com/stefanocudini/leaflet-compass
