### ISSUE TITLE
Is it possible to mark markers as viewed after click?

### ISSUE THREAD

**Issue by sabatale** [Leaflet/Leaflet#7517]
**Describe the solution you'd like**
Grey out or show a visual element indicating the market has already been clicked.

Ideally, marked elements would be cached in the browser.

**Describe alternatives you've considered**
Looking for the simplest way to do so.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
