### ISSUE TITLE
'southwest.latitude <= northeast.latitude': is not true. Error Flutter Polyline

### ISSUE THREAD

**Issue by BankySam** [Leaflet/Leaflet#7524]
This is the error i am getting after runing my project and selecting a destination and using my current location to zoom out the polyline  LatLng bounds.
'southwest.latitude <= northeast.latitude': is not true.
I am trying to set the location of my pick up and destination, poly line to fit on the map.

```
LatLngBounds bounds;

    if(pickLatLng.latitude > destinationLatLng.latitude && pickLatLng.longitude > destinationLatLng.longitude){
      bounds = LatLngBounds(southwest: destinationLatLng, northeast: pickLatLng);
    }
    else if(pickLatLng.latitude > destinationLatLng.longitude){
      bounds = LatLngBounds(
          southwest: LatLng(pickLatLng.latitude, destinationLatLng.longitude),
          northeast: LatLng(destinationLatLng.latitude, pickLatLng.longitude),);
    }
    else if(pickLatLng.latitude > destinationLatLng.latitude) {
      bounds = LatLngBounds(
          southwest: LatLng(destinationLatLng.latitude, pickLatLng.longitude),
          northeast: LatLng(pickLatLng.latitude, destinationLatLng.longitude));
    }
    else{
      bounds = LatLngBounds(southwest: pickLatLng, northeast: destinationLatLng);
    }

    mapController.animateCamera(CameraUpdate.newLatLngBounds(bounds, 70));

  }
```
[
<img width="1382" alt="Screen Shot 2021-03-24 at 8 56 13 AM" src="https://user-images.githubusercontent.com/24680223/112296931-93a4d100-8c95-11eb-988b-9df1999c989b.png">
](url)

**Comment by johnd0e** [comment]
Is it bug report?

If it is - please fill the template: https://github.com/Leaflet/Leaflet/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

If it isn't - see https://github.com/Leaflet/Leaflet/blob/master/.github/ISSUE_TEMPLATE/support.md

**Comment by johnd0e** [comment]
> I am trying to set the location of my pick up and destination, poly line to fit on the map.

Leaflet's [LatLngBounds](https://leafletjs.com/reference-1.7.1.html#latlngbounds) does not require to specify southwest/northeast explicitly, so it seems that your code is not relevant to Leaflet at all.

**Comment by BankySam** [comment]
Yeah i guess so 
I dont know why i am getting an error

**Comment by BankySam** [comment]
```
  LatLngBounds({required this.southwest, required this.northeast})
      : assert(southwest != null),
        assert(northeast != null),
        assert(southwest.latitude <= northeast.latitude);
```

**Comment by BankySam** [comment]
I think this might be a bug 
the error brings me to this line 
=> assert(southwest.latitude <= northeast.latitude);
in the location.dart file

**Comment by BankySam** [comment]
I think this might be a bug 
the error brings me to this line 
=> assert(southwest.latitude <= northeast.latitude);
in the location.dart file

**Comment by BankySam** [comment]
I think this might be a bug 
the error brings me to this line 
=> assert(southwest.latitude <= northeast.latitude);
in the location.dart file

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* NativeScript
* Flutter
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.

**Comment by IvanSanchez** [comment]
Furthermore, your error messages reference `google_maps_flutter_platform_interface` (https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter/google_maps_flutter_platform_interface/lib/src/types), which doesn't seem to be related to Leaflet whatsoever.

**Comment by BankySam** [comment]
Yes i made a mistake(my bad ) :] 
slept just woke up. and reviewed my script and found the typo in the code earlier.
This has nothing to do with Leaflet.
