### ISSUE TITLE
[SvgRenderer/CanvasRender - same issue] Support to render circleMarker on top of polylines. Polylines should not cross over circle markers.

### ISSUE THREAD

**Issue by vissharm** [Leaflet/Leaflet#7525]
As we cannot have interaction in multiple canvas/map-panes. One layer will block others. I don't want to go into the workarounds here. But at least can we have support to draw circle markers later than polylines. So click on the circle markers should not fire clicks on polylines. 
Also what about supporting drag on circle marker? Is there any way?

This issue exists with the SVG renderer also. CircleMarkers will be rendered first and then polylines. The canvas I want circle-markers to painted last to stay on top of polylines. This is a very genuine problem especially when the interaction between canvas layers is an issue.

**Comment by vissharm** [comment]
![Screenshot 2021-03-25 at 2 26 38 AM](https://user-images.githubusercontent.com/21159071/112382345-becd0600-8d11-11eb-9dd0-da65f6bab8bd.png)

**Comment by vissharm** [comment]
@perliedman +others - help needed... much important

**Comment by IvanSanchez** [comment]
I don't understand what you mean,but you should set the `interactive` option to `false` on your `L.Path`s (and stop telling other people how important this is for you, because that doesn't help at all).

**Comment by vissharm** [comment]
@IvanSanchez You misinterpreted the issue. I want interaction on polyline but you can see the polyline is rendered on top of circle-marker. So the line got clicked instead of the circle marker. Let me know if I am still bad at explanation. Please open the issue I verified it both with canvas and svg renderer.

**Comment by vissharm** [comment]
@Ivan-Perez Polylines and CircleMarkers rendered in the same leaflet layer and what I can see from rendering behaviour is that polylines are always rendered on top of circle marker. I am using react-leaflet and passing all the items at once. It just a wrapper around it so this must be something that is missing at leaflet i.e. to support user-defined order between polylines, circle-markers and other kinds of elements that exist at the same layer..

**Comment by vissharm** [comment]
I need to handle 3k to 15k markers and 3k to 20k polylines along with labels (that will be DOM elements and will make things slow anyhow). So having circle markers instead of div icon is the only way for me. But this is the issue I left with.

**Comment by vissharm** [comment]
@Ivan-Perez  This issue should have opened at the react-leaflet side. The draw order works fine, it's more of react doing something if I reference the array as children.

**Comment by Ivan-Perez** [comment]
> 
> 
> @Ivan-Perez This issue should have opened at the react-leaflet side. The draw order works fine, it's more of react doing something if I reference the array as children. Thanks.

Please mention @IvanSanchez, not me 😄

**Comment by perliedman** [comment]
@vissharm it's been too long for me to respond with any authority, but have you tried [`bringToFront`](https://leafletjs.com/reference-1.7.1.html#path-bringtofront)/`bringToBack` to order your layers like you want?

**Comment by vissharm** [comment]
@perliedman The issue is each layer is a separate canvas so if I put polylines in the back layer and circle markers on the front layer, interaction with both is still an issue. ???
