### ISSUE TITLE
touch outside the map blocks touch in marker or cluster

### ISSUE THREAD

**Issue by bluelemonade** [Leaflet/Leaflet#7558]
**Steps to reproduce**
open your example https://leafletjs.com/examples/quick-start/ on a windows multitouch system, touch on the white space around the map, and then try to touch a point.

**Expected behavior**
on a multitouch system I could touch everywhere and it should react.

**Current behavior**

**Environment**
- Leaflet version: 
- Browser (with version): Chrome / Fireworks...
- OS/Platform (with version): Windows 10 latest release

**Comment by johnd0e** [comment]
@bluelemonade
It is completely unclear what is your issue.
Please fill in 'Current bahavior' and 'Environment'.

**Comment by bluelemonade** [comment]
ok, 

windows 10, current browser, chrome, firefox, multitouch, minimal 2 points.
open your demo: https://leafletjs.com/examples/quick-start/ 
then touch where ever you want on a white area of the page AND hold down the finger on the page
then try to touch an icon on the map.
you can't touch whenever a finger is elsewhere on the page!

think of a kiosk system, the user scrolls a page with one finger and tries to touch inside a leaflet map, it didn't work. 

by the way, on an iPad it works, you can hold one touch and touch a marker on the map.

I think the leaflet version of your demo on your site is the latest one.

**Comment by johnd0e** [comment]
> then try to touch an icon on the map.
you can't touch whenever a finger is elsewhere on the page!

The same on Android.
The same is on Google Maps.

Two-toches gesture is reserved for the page pinch zoom, so I don't think that it's subject to fix.

Though, you by yourself could propose PR or plugin to achieve desirable behavior change.

**Comment by bluelemonade** [comment]
> > then try to touch an icon on the map.
> > you can't touch whenever a finger is elsewhere on the page!
> 
> The same on Android.
> The same is on Google Maps.
> 
> Two-toches gesture is reserved for the page pinch zoom, so I don't think that it's subject to fix.
> 
> Though, you by yourself could propose PR or plugin to achieve desirable behavior change.

ok, but why is a touch outside of the map area registered for pinch on touchstart? its ok to to move the touch outside the map when pinch, but I think it has to start inside the map.

how can I change this behaviour with an plugin? where can I start?

**Comment by bluelemonade** [comment]
I looked at the code, with a little help I should be able to reduce the pointers to the map area. Since it can happen on the 4k table that several maps are open, I would have to check for each event whether a certain card name appears in the path.

_ How can I pass my own option such as the card name via options to the map engine?

_ Which methods make sense to filter the pointers?

**Comment by johnd0e** [comment]
> _ Which methods make sense to filter the pointers?

No methods, just patch the source code.

Grep for `document.` to find places where Leaflet hooks to global document.
You should be able to hook to leaflet map container instead.

**Comment by bluelemonade** [comment]
ok, but how can I get the name of the map div container, is there a function to call.

**Comment by johnd0e** [comment]
https://leafletjs.com/reference.html#map-getcontainer

**Comment by bluelemonade** [comment]
Would be nice if the thread is not closed directly ...

thanks.

I found this document.addeventListener:

```
if (!_pointerDocListener) {
  		// we listen document as any drags that end by moving the touch off the screen get fired there
  		document.addEventListener(POINTER_DOWN, _globalPointerDown, true);
  		document.addEventListener(POINTER_MOVE, _globalPointerMove, true);
  		document.addEventListener(POINTER_UP, _globalPointerUp, true);
  		document.addEventListener(POINTER_CANCEL, _globalPointerUp, true);
  		_pointerDocListener = true;
  	}
```

then I checked for an parent with a static name in these functions.

```
     function _globalPointerDown(e) {
		if (isDescendant(e.target, "#map1") ){
			console.log("_globalPointerDown: OK");
			_pointers[e.pointerId] = e;
		}
	}

	function _globalPointerMove(e) {
		if (isDescendant(e.target, "#map1") ){
				if (_pointers[e.pointerId]) {
					_pointers[e.pointerId] = e;
				}
		}
  	}
```

it works with the zoom, I found this function that checks if the gesture is detected, that works now, I can put 20 fingers on the table and zoom inside the map, no problem.
_onTouchStart: function (e) {
  	

but the touch on a marker stops when I hold the finger down outside of the map, I searched around but couldn't find the right place to start.


and how can I transfer the name of the map into the map from the outside, it would be faster than looking for the name.
I tried to use getContainer() from _globalPointerDown, but I think that's not possible.

**Comment by johnd0e** [comment]
Sorry, I'm not going to assist you in every step, as I just have no free time for this.

**Comment by bluelemonade** [comment]
ok, I found the and onOff and the _handleDOMEvent function where I added the pointerdown and changed it to a click event, and now it works, 5 maps on one table, you can scroll and touch and zoom all at the same time. 

I will solve the problem with a dynamic name for the map with the help of stackoverflow. No idea why 2 simple hints are such a problem.

Have fun with your important work!

**Comment by johnd0e** [comment]
> with the help of stackoverflow

And you might help someone with similar issue, it you post your solution here.

**Comment by bluelemonade** [comment]
I'll do that, but first I have to test it, perhaps I fire the event not inside the onoff, maybe its better to do it in the touchdown.
