### ISSUE TITLE
Other views of the map features

### ISSUE THREAD

**Issue by mdziczkowski** [Leaflet/Leaflet#7559]
Hello. I would like to ask if there would be a feature with would give the possibility to add to the map layers to view on it  (or switch the view to):

- Satelite
- Street view
- Humanitarian
- Cycle map
- Transport map
- Terrain
- Culture
- Recreation
- Sport
- other

The above list are only examples of possible to add layers with would allow to expand the possibilities of Leaflet

It would be also great if there would be the legend included as default.

I want to add on the end that the leaflet gives already awsome features and possibilities and I hope that the mentioned by me above would join them as an standard

**Comment by IvanSanchez** [comment]
https://github.com/leaflet-extras/leaflet-providers
