### ISSUE TITLE
geojson is loaded successfully but no image is displayed

### ISSUE THREAD

**Issue by kikyoluka** [Leaflet/Leaflet#7561]
- [✓] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [ ] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [✓] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
I got a geojson through dwg conversion, Then i use the program to successfully load it, But my page is blank. I initially checked and thought it might be a problem with geojson data:
```
{
  "type": "FeatureCollection",
  "features": [{
    "type": "Feature",
    "geometry": {
      "type": "LineString",
      "coordinates": [
        [-2209825.8760752562, -247879.21591321751, 0.0],
        [-2209825.8760752562, -196674.33615582529, 0.0]
      ]
    },
    "properties": {
      "Layer": "DATE"
    }
  }]
}
```
Perhaps it is because the x and y of the data does not correspond to the actual longitude? Anyone who knows please help me and tell me whether it’s the data problem or something wrong with my operation, thanks.

**Expected behavior**

image is displayed normally 

**Current behavior**

Loaded successfully but the image is not displayed 

**Environment**
- Leaflet version: 1.7.1
- Browser (with version): edge 90.0.818.49
- OS/Platform (with version): windows10

**Comment by johnd0e** [comment]
> Perhaps it is because the x and y of the data does not correspond to the actual longitude?

So no surprises.

Please note that github issues is not for support.

**Comment by IvanSanchez** [comment]
See also https://tools.ietf.org/html/rfc7946#section-4 , and `L.CRS.Simple`.
