### ISSUE TITLE
loading wms service Notes disappear

### ISSUE THREAD

**Issue by MengQiu-zl** [Leaflet/Leaflet#7562]
- [ ] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [ ] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [ ] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
![企业微信截图_16196885712275](https://user-images.githubusercontent.com/79238238/116530313-76a49300-a910-11eb-9e64-4a145ee7effe.png)
![企业微信截图_16196885925039](https://user-images.githubusercontent.com/79238238/116530353-8328eb80-a910-11eb-83ac-93dbfefa26ca.png)

- step 1
- step 2
- ...

**Expected behavior**

**Current behavior**

**Environment**
- Leaflet version:
- Browser (with version):
- OS/Platform (with version):

**Additional context**

**Minimal example reproducing the issue**

Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

**Comment by 13230815385** [comment]
![Uploading 企业微信截图_16196886752630.png…]()

**Comment by johnd0e** [comment]
Please fill all the fields of issue template, otherwise your report makes no sense.

**Comment by Malvoz** [comment]
@MengQiu-zl If you're still having this issue, please fill in the necessary information to reproduce it, or file a new bug report.
