### ISSUE TITLE
Documentation error in Map Panes section

### ISSUE THREAD

**Issue by mz8i** [Leaflet/Leaflet#7564]
In the documentation section about Map Panes: 
https://leafletjs.com/reference-1.7.1.html#map-overlaypane

There seems to be an error in the descriptions of `shadowPane` and `overlayPane` - something seem to be mixed up. Comparing to a much older version of the documentation (https://leafletjs.com/reference-1.0.3.html#map-pane) it seems that perhaps there was a modification of the order of the panes, but the documentation was not updated correctly.

My guess is that the fix is to switch the values in the Pane column of the docs table - swapping `overlayPane` with `shadowPane` between rows

**Comment by answerquest** [comment]
I noticed the same! Anybody has an idea of where the source is of this documentation?
I see this: https://github.com/Leaflet/Leaflet/blob/master/docs/reference-1.7.1.html#L1711 
but is it a built output from somewhere else, or can a PR with the change done do the needful?

**Comment by Falke-Design** [comment]
@johnd0e this is already fixed and can be closed: #7349
