### ISSUE TITLE
Provide a method to check for active layers in the control menu

### ISSUE THREAD

**Issue by FieteO** [Leaflet/Leaflet#7573]
**Is your feature request related to a problem? Please describe.**
I would like to be able to check if a given layer in the control menu is currently active or not.

Context:  
I have defined a `hideLayersOnZoomLevel()` method to conditionally add or remove the layer in question based on zoom level. I register this as a callback for the `zoomend` event (`map.on('zoomend', () => hideLayerOnZoomLevel(myLayer)`).
``` typescript
  hideLayerOnZoomLevel(layer: L.Layer, zoomLevel = 12): void {
    let currentLevel = this.map?.getZoom();
    if (currentLevel && currentLevel < zoomLevel && this.map!.hasLayer(layer)) {
      this.map!.removeLayer(layer);
    }
    if (currentLevel && currentLevel >= zoomLevel && !this.map!.hasLayer(layer)) {
      this.map!.addLayer(layer);
    }
  }
```
The problem with this approach is, that it does not respect the current state of the layer (that is if the checkbox in the control menu is checked or not). Thus layers are added or removed irrespective of the current choices the user made in the layers control menu.

**Describe the solution you'd like**
I would like to be able to query the L.Controls.Layers object for active layers. I imagine this to be something like a `Control.Layers.isActive(layer: Layer)` method that I could use in the `if` check of my `hideLayerOnZoomLevel()` method to only add or remove the layer if it is currently active/selected.

**Describe alternatives you've considered**
I have found [StackExchange - getActiveLayers for LeafletJS](https://gis.stackexchange.com/questions/92677/getactivelayers-for-leafletjs) that describes alternatives, however I would have expected this to be a basic functionality for the controls.

**Additional context**

**Comment by johnd0e** [comment]
> I would like to be able to check if a given layer in the control menu is currently active or not.

'active' means present on map.
You can check that with `map.hasLayer();`

**Comment by FieteO** [comment]
I was able to track the state of the `Control.Layers` object before removing layers due to zooming with a typescript `Map`. Maybe this is useful to someone.
``` typescript
map: L.Map | undefined;
layersControl = L.control.layers();
// This saves which layers were active, when crossing the zoomLevel cut off (of hideLayersOnZoomLevel).
// Otherwise we wouldn't know, which layers to restore and - more importantly - which not.
activeLayersBeforeZooming = new Map<number, L.Layer>();

ngOnInit() {
    ...
    this.map.on('zoomend', () => this.hideLayerOnZoomLevel(myLayerGroup, 15));
    // trigger zoom level evaluation, all layers would be initially visible otherwise
    this.map.eachLayer(layer => this.map.fireEvent('zoomend', layer));
}

  /**
   * Use this as a callback function for Leaflet's `'zoomend'` event, e.g:
   *
   * `this.map.on('zoomend', hideLayerOnZoomLevel(myLayer, 12));`
   * @param zoomLevel the breakpoint for hiding the layer, defaults to 12 (lower -> longer visible)
   * @param layer the layer that should be hidden or visible
   */
  hideLayerOnZoomLevel(layer: L.LayerGroup, zoomLevel = 13): void {
    let currentLevel = this.map.getZoom();
    if (currentLevel < zoomLevel && this.map.hasLayer(layer)) {
      // remember this layer, so that it can be restored when we cross the zoom threshold again
      this.activeLayersBeforeZooming.set(layer.getLayerId(layer), layer);
      this.map.removeLayer(layer);
    }
    if (currentLevel >= zoomLevel && !this.map.hasLayer(layer)) {
      let layerId = layer.getLayerId(layer);
      // only re-add the layer if it is among the active but hidden layers
      // (opposed to those who are hidden because they are not active)
      if (this.activeLayersBeforeZooming.has(layerId)) {
        this.activeLayersBeforeZooming.delete(layerId);
        this.map.addLayer(layer);
      }
    }
  }
```
