### ISSUE TITLE
Tracing Support

### ISSUE THREAD

**Issue by andrewhodel** [Leaflet/Leaflet#7576]
**Is your feature request related to a problem? Please describe.**

Your library is included in complicated code and you expect people to submit samples that are 10 lines and work in jsfiddle. 

This is like submitting a libc or openssl bug without an strace. 

**Describe the solution you'd like**

A library wide option to enable or disable tracing output in the console. 

As JS is billed as asynchronous you should output each function call, it's parameters and the start and end time at the highest resolution possible. 

This would stop all of the frustration you have with requiring code samples and improve moral for your obviously angry issue handlers. 

**Describe alternatives you've considered**

**Additional context**

**Comment by andrewhodel** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Performance/now

Unlike other timing data available to JavaScript (for example Date.now), the timestamps returned by performance.now() are not limited to one-millisecond resolution. Instead, they represent times as floating-point numbers with up to microsecond precision.

**Comment by IvanSanchez** [comment]
> [...] your obviously angry issue handlers.

Antagonizing the maintainers won't help.
