### ISSUE TITLE
Zooming from z2 to z3 shifts the map

### ISSUE THREAD

**Issue by 18manfish** [Leaflet/Leaflet#7581]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using no framework
- [x] I've searched through the issues to make sure it's not yet reported

I created a custom map using tiles 512x512pixel. from z1 with 1^2 tiles to z7 with 7^2 tiles. The issue exists with every crs, since it's a game map i used the recommended L.CRS.Simple.

When zooming from z2 to z3 and so on. the center of the map is no longer in the position of the mouse cursor. while when zooming from z1 to z2 it stays centered. The same happens for markers placed. see the .gif for an example of this behaviour
https://abload.de/img/nu5u0nncz9mnj4c.gif
the image used to create the map was 3584x3584px large (7x512px). for each z value it was scaled down to z*512pixels in width and height. for example z6 = 6*512px x 6*512px  z5 = 5 *512px x 5*512px etc

**Steps to reproduce**
- step 1
- step 2
- ...

**Expected behavior**

The map should zoom in on the mouse pointer when changing from z2 to z3 etc.

**Current behavior**

The map shift to the upper left corner

**Environment**
- Leaflet version: "leaflet": "^1.7.1",
- Browser (with version): Firefox 88.0.1, Chrome 90.0.4430.212 (Official Build) (64-bit)
- OS/Platform (with version):  Windows 10
**Additional context**

**Minimal example reproducing the issue**
main.js
```
var mymap = L.map('mapid').setView([0, 0], 1);

L.tileLayer('../tiles/AeroFire/{z}/Tile_{x}_{y}.png', {
    crs: L.CRS.Simple,
    minZoom: 1,
    maxZoom: 7,
    boxZoom: true,
    doubleClickZoom: true,
    tileSize: 512,
    noWrap: true,
    defaultRadius:1,
    attribution: 'Map-Name',
    continuousWorld: 'true',
}).addTo(mymap);

L.marker([50.5, 30.5]).addTo(mymap);
```

index.html
` <div id="mapid"></div>`

main.css
`#mapid { 
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    background: black;
}`

- [x ] this example is as simple as possible
- [x ] this example does not rely on any third party code

**Comment by IvanSanchez** [comment]
> the image used to create the map was 3584x3584px large (7x512px). for each z value it was scaled down to z512pixels in width and height. for example z6 = 6512px x 6*512px z5 = 5 512px x 5512px etc

In Leaflet, zoom levels work on a power-of-2 basis. So you should try instead to do something like 1 tile high/wide at zoom level 0, 2 tiles wide/high at zoom level 1, 4 tiles w/h at z2, 8 tiles w/h at z3, etc etc.

If you *need* non-power-of-two zoom levels, do look into the internals of `L.CRS` and the default implementation of the `scale`/`unscale` methods. You'll need to create your own CRS for this.
