### ISSUE TITLE
How to connect the library to the Vue.js

### ISSUE THREAD

**Issue by dmitrymaslov99** [Leaflet/Leaflet#7583]
How to connect a vanilla library in a Vue.js and then connect plugins.
I know there is a library - https://vue2-leaflet.netlify.app/. But there is limited functionality and there are not all the necessary plugins.

I have a sandbox where I tried to connect both the map and the plugin - https://codesandbox.io/embed/busy-gagarin-6od2q?fontsize=14&hidenavigation=1&theme=dark

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
