### ISSUE TITLE
Drawing layer order changed with Control.Layers

### ISSUE THREAD

**Issue by olivbrau** [Leaflet/Leaflet#7587]
Hi,
I have noticed that when I use Control.Layers, if I deselect then reselect an item, it is drawn over the others, not respecting the order of drawing of the map.
It is very annoying, and against standard practice in every map software : the order of drawing is (almost) VERY important !
I'v tried the 'sortLayers' options, but it doesn't work.
I've tried to put my polyline/polygon in new panes (with 'pane' option) -> it now works, but my Canvas renderer is not used anymore, instead, a new SVG renderer seems to be used (cf. issue #7586)
Is there a way to bypass this limitation ?
Thanks in advance
Olivier

**Comment by johnd0e** [comment]
> I've tried to put my polyline/polygon in new panes (with 'pane' option) -> it now works,

That is the right way

**Comment by johnd0e** [comment]
P.S.
You may try something like this:
```js
// restore layers order
var order = [layer1, layer2, layer3];
map.on('overlayadd', function () {
	setTimeout(function () {
		order.forEach(function (layer) {
			if (map.hasLayer(layer)) {
				layer.remove();
				map.addLayer(layer);
			}
		})
	});
});
```
