### ISSUE TITLE
[q] display stream-type data (flatgeobuf) files in a streaming way 

### ISSUE THREAD

**Issue by kkdd** [Leaflet/Leaflet#7592]
Hello,
I have realized that Leaflet reads and displays stream-type data (i.e., [flatgeobuf](https://flatgeobuf.org/examples/leaflet)) not in a streaming way when reading local files. Isn't it the matter of leaflet, however?

See an example source examined:

* [Leaflet map: read flatgeobuf files by dropping-on](https://bl.ocks.org/kkdd/d18eb75331b2271ca9ab0b0e13be20d6) (bl.ocks.org)
* test file: [UScounties.fgb](https://github.com/flatgeobuf/flatgeobuf/blob/master/test/data/UScounties.fgb?raw=true) ([UScounties.fgb](https://github.com/flatgeobuf/flatgeobuf/blob/master/test/data/UScounties.fgb))

![output](https://user-images.githubusercontent.com/5372642/120999095-b12d0580-c7c3-11eb-83d4-a3325ea67efb.gif)

--------------^ Click "Preview" tab for a nicer view!

We use GitHub as an issue tracker and **do not provide support here**.
For usage and support questions, please check out resources below:

1. Read Leaflet documentation: https://leafletjs.com
2. For support questions like "How can I do X with Leaflet?" please search or ask questions on StackOverflow or StackExchange using Leaflet tag:
  - https://stackoverflow.com/questions/tagged/leaflet
  - https://gis.stackexchange.com/questions/tagged/leaflet

Thanks!

**Comment by IvanSanchez** [comment]
> I have realized that Leaflet reads and displays stream-type data

No it doesn't. The example you linked has the `flatgeobuf` deserializing a geobuf, then Leaflet just loads GeoJSON structures.

> not in a streaming way when reading local files.

I think you're just confusing the concept of "streaming" with the `.stream()` method of `File` (as per https://developer.mozilla.org/en-US/docs/Web/API/File ). By using a `ReadableStream` interface, your local file might be actually being streamed chunk by chunk to the browser as it's being read from the hard drives (e.g. one chunk per DMA operation). `flatgeobuf` might or might not wait for the whole file to be read before emitting GeoJSON structures.

**Comment by kkdd** [comment]
Thank you for your explanation.

Streamed-chunk-based reading and displaying are confirmed achieved when ```fetch```ing data of both [flatgeobuf](https://flatgeobuf.org/examples/leaflet) and ```new-line-deliminated geojson```  in Leaflet. 

What I am confusing is about mis-achievement seemingly when reading local files, however.
