### ISSUE TITLE
Pixels coordinates rounded

### ISSUE THREAD

**Issue by olivbrau** [Leaflet/Leaflet#7595]
Hi everybody,
I get this message on one of my map :
Projection.LonLat.js:20 Uncaught TypeError: Cannot read property 'lng' of undefined
After long investigation, I found that, in my case, it is due to the **combination** of 2 plugins : Leaflet.ArrowHead and Leaflet.PolylineOffset :
PolylineOffset has a 'bug' : if a segment is reduced to a point, it returns an empty geometry and then ArrowHead try to compute the angle of the empty segment to create the triangle arrow, which create, at the end, this error message ...
In fact, it is impossible for PolylineOffset to offset a segment that is an point ... (but it could have created an offset segment-point at the same location instead of empty geometry ... to avoid problem)

So I tried to understand why my segment was reduced to a point, and I discovered that latLngToLayerPoint() function use .round()
Why ? Why screen pixels coordinates should be integer ? As a matter of fact, some algorithms need to work on screen coordinates (like ArrowHead) and need floating point précision. For instance, even if there was not the PolylineOffset buf (empty geom), ArrowHead create bad arrow on a segment when the zoom is far because latLngToLayerPoint() transforms the segment to a point ! (and then ArrowHead use a fixed angle of 180° ...)

So my question is : why rounding pixels coordinates ? There is no gain (and it slows down latLngToLayerPoint() a little bit ...) and it can create issues with algorithms/plugins working directly on pixels coordinates.

I tried to "hack" this with :

	L.Map.include({
		latLngToLayerPoint: function (latlng) {
			var projectedPoint = this.project(L.latLng(latlng)); // no round()
			return projectedPoint._subtract(this.getPixelOrigin());
		},
	});
And now everything is working well.
But I wonder if the fact to not round coordinates, can create another bugs ?

**Comment by IvanSanchez** [comment]
> So my question is : why rounding pixels coordinates ?

Because subpixel offsets leads to bugs like https://github.com/Leaflet/Leaflet/pull/6240 https://github.com/Leaflet/Leaflet/issues/6069 and https://github.com/Leaflet/Leaflet/issues/3297
