### ISSUE TITLE
docs: main-page: marker-icon.png returns 404

### ISSUE THREAD

**Issue by refeed** [Leaflet/Leaflet#7607]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- Open https://leafletjs.com/index.html
- Scroll till you see the leaflet map example
- The marker isn't shown because https://leafletjs.com/images/marker-icon.png returns 404
![marker404](https://user-images.githubusercontent.com/20320125/123620991-f8dc0580-d834-11eb-8eff-0182b88d3e54.png)

**Expected behavior**
https://leafletjs.com/images/marker-icon.png should returns the marker image and the marker should be shown on the main page

**Current behavior**
The marker isn't shown in the main page

**Comment by Falke-Design** [comment]
Is working for me:
![grafik](https://user-images.githubusercontent.com/19800037/123837722-78d49f00-d90b-11eb-8ab8-9d80cc76dae8.png)

And the marker icon coming from: https://unpkg.com/leaflet@1.7.1/dist/images/marker-icon.png


@refeed can you please make a cache refresh and look if the marker is still not loading.

**Comment by refeed** [comment]
ah yes, it's because of my browser's cache. Thanks!
