### ISSUE TITLE
Automatically detect available (maximum) native zoom levels of tile layer source

### ISSUE THREAD

**Issue by LukasBommes** [Leaflet/Leaflet#7608]
**Is your feature request related to a problem describe? Please.**
I am building a web app for photovoltaics plant inspection and use ESRI world imagery tiles. I would like to load the tiles up to the maximum native zoom level available for any location and only afterwards interpolate the tiles. Setting MaxZoom and MaxNativeZoom options works, however, requires prior knowledge about the maximum native zoom level available at a location. I.e. I have sites in Germany where the maximum native zoom is 19 and others in south America where only tiles up to zoom level 17 are available.

**Describe the solution you'd like**
Ideally, one could set MaxNativeZoom to a value, e.g. -1, indicating that tiles should be loaded up to the maximum native zoom available for any location. No prior knowledge about the maximum zoom level available at a location would be needed. I assume, this would require some sort of "probing" the tile server for availability of tiles.
Of course, the same feature could be applied to the minimum native zoom level.

**Comment by ghybs** [comment]
Hi,

Sounds like use case for https://github.com/ghybs/Leaflet.TileLayer.Fallback
