### ISSUE TITLE
When using both divIcon() and L.Icon() causes bad performance and map freezes

### ISSUE THREAD

**Issue by besteenurk** [Leaflet/Leaflet#7610]
I need to show SVG and png icons together. Is there any way to show that? 
I used divIcon() for SVG icons and L.icon() for png icons. Both objects moving together for 10 seconds. For 10 seconds, I used a timer observable. 

I have a huge data density. This data folds every 10 seconds. I added These two icons as separate layers. 
Icons consisting of DivIcon() come when the map is first opened. If L.Icon (), then you want to open it by selecting it from the layer. And when it opens, this icon will move together. We can think of two icons as connected.

The problem is a performance problem when two icons are added together to the map. And L.Icon()'s progress by leaving the icon behind every 10 seconds.

The map is always frozen after a short time. Zooming performance is getting slow when data is up.
I wonder if the way that shows better performance with these two icons.  

If both icons were png, I was going to add another icon as an L.Icon()'s shadow. But because of the use of divIcon() with SVG, that possibility falls into the water. divIcon() also does not accept shadows.
I looked for use in this way, but I couldn't find it. I'm looking for a way to show two icons in a high-performance way.

**Also, why the map also cause freezes during zoom in&out?**

**For L.Icon();**
```
let _secondIcon= L.icon({
        className: 'img-type',
        iconUrl: this._imgType,
        iconSize: [10, -15],
        anchor: [0.2, -0.1]
      });

if (!this.secondIcon) {
this.secondIcon = marker([lat, lng]);
layerGroup.addLayer(this.secondIcon); }

this.secondIcon.setLatLng([lat, lng]);
this.secondIcon.setRotationOrigin('center center');
this.secondIcon.setIcon(_secondIcon);

```
**For divIcon();**
```
let _icon = divIcon({
      className: 'vehicle-icon',
      html: Util.template(movingMarker(obj), this.markerModel),
      iconSize: [20, 20],
      scale: 0.8,
    });
movingMarker() has svg.

if (!_marker) {
this._marker = marker([lat, lng]);
layerGroups.addLayer(this._marker); }

this._marker.setLatLng([lat, lng]);
this._marker.setRotationOrigin('center center');
this._marker.setIcon(_icon);

```

I added a screenshot of the problem.

![marker](https://user-images.githubusercontent.com/14995838/124081385-25219d00-da54-11eb-9775-e3b0988320f7.png)

The way it should be:

![marker_n](https://user-images.githubusercontent.com/14995838/124081516-51d5b480-da54-11eb-8780-e7cccac41004.png)

https://stackoverflow.com/questions/68033774/leaflet-how-can-i-remove-the-old-moving-markers-from-the-maps-background

**Environment**
I'm using Angular, ngx-admin template

Laeflet version: "1.5.1"

**Comment by johnd0e** [comment]
> **Environment**
> I'm using Angular, ngx-admin template

- [ ] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)

We are unable to provide support unless you will be able to reproduce the issue in vanilla leaflet.
Sorry.
