### ISSUE TITLE
Pause redraw or refresh when add lots of layer.

### ISSUE THREAD

**Issue by vutle** [Leaflet/Leaflet#7616]
I'm making ajax calls in a loop to compute and adds lots of layers to the map.  
Is there an option to pause the map redraw or refresh, and perform an update or refresh when the process is completed?

thanks

**Comment by johnd0e** [comment]
No way to pause map, but it should be possible defer the whole processing in your own code.

In either case, this bugtracker is not meant for such kind of support.
