### ISSUE TITLE
Missing type declaration inside leaflet-draw-src.js

### ISSUE THREAD

**Issue by gregoire31** [Leaflet/Leaflet#7621]
Hello, it seems you've forget to declare your "type" variable inside leaflet-draw/dist/leaflet-draw-src.js file
So L.Draw.Rectangle function is not working
The probleme is in the line  "3161" 
The bug is present in the version 1.0.4
You should replace 
" type = typeof isMetric; "

By

"let type = typeof isMetric;"

the rectangle draw function work correctly in the version 1.0.2

- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- step 1
- step 2
- ...

**Expected behavior**

**Current behavior**

**Environment**
- Leaflet version:
- Browser (with version):
- OS/Platform (with version):

**Additional context**

**Minimal example reproducing the issue**

Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.

- [ ] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by IvanSanchez** [comment]
> inside leaflet-draw/dist/leaflet-draw-src.js file

This is the bug tracker for Leaflet itself, not for Leaflet-Draw.
