### ISSUE TITLE
Black bar in hikeandbikemap.org map with hillshading 

### ISSUE THREAD

**Issue by samarutuk** [Leaflet/Leaflet#7624]
When hillshading is active, a black bar always appears in this (latitude) region:
![grafik](https://user-images.githubusercontent.com/46650176/126134429-e2751e43-ee94-4c48-a852-b52d24f0bd6c.png)

I don't know if the error already appears in the NASA data. It looks a bit as if the hillshading merges at this point and there is an overlap. However, it is not beautiful and it is surprising that nobody has noticed it yet. Maybe you can fix it if it has nothing to do with the NASA data.

**Comment by IvanSanchez** [comment]
See https://b.tiles.wmflabs.org/hillshading/14/8611/5556.png :

![](https://b.tiles.wmflabs.org/hillshading/14/8611/5556.png)

Not a Leaflet bug.
