### ISSUE TITLE
Does Leaflet have corresponding components that can convert the data parsed by dxf into geojson? 

### ISSUE THREAD

**Issue by kikyoluka** [Leaflet/Leaflet#7625]
I plan to import cad files on the web and then use Leaflet to render an editable map. Is there any component of Leaflet that can convert dxf data into geojson?

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
