### ISSUE TITLE
Circles going Opaque after a random time

### ISSUE THREAD

**Issue by chocolateimage** [Leaflet/Leaflet#7628]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- Have setup L_PREFER_CANVAS = true; before loading leaflet and {preferCanvas:true} in map creation
- Create many large circles (100)
- Make them transparent

**Expected behavior**

That the circles stays transparent.

**Current behavior**

The circles suddenly at a random time comes opaque

**Environment**
- Leaflet version: 1.7.1
- Browser (with version): Chrome 92.0.4515.107
- OS/Platform (with version): Windows 10 21H1 Build 19043.1110

**Additional context**

**Minimal example reproducing the issue**
https://plnkr.co/edit/IFi5XaqjauFrp0P4

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by wbhouston** [comment]
In the example you provide, the fillOpacity becomes negative before the opacity drops. A simpler minimal example is to create a circle with negative fillOpacity.

**Comment by wbhouston** [comment]
SVG handles it properly, but canvas does not:

[https://plnkr.co/edit/DYf0hJReMPnINnqh](https://plnkr.co/edit/DYf0hJReMPnINnqh)
