### ISSUE TITLE
zoomLevel 20 with OSM zooms beyond map tile data in Chrome while OSM data provides level 20

### ISSUE THREAD

**Issue by andrewhodel** [Leaflet/Leaflet#7629]
Steps to reproduce:

1. view zoom level 20 in chrome with OSM data
2. view OSM max zoom level of 20 here - https://wiki.openstreetmap.org/wiki/Zoom_levels

**Expected behavior**
Map tiles to not be greyed out.

**Current behavior**
Map tiles are greyed out, similar to when zoomed beyond a tile sets maximum zoom level.

**Environment**
- Leaflet version: 1.7.1
- Browser (with version): Chrome 92.0.4515.107 (Official Build) (arm64)
- OS/Platform (with version): macOS Big Sur Version 11.4, iMac M1

**Additional context**
Works in Safari with the same zoom level.

**Comment by IvanSanchez** [comment]
> while OSM data provides level 20

The default OSM *tile server* does **not** serve zoom level 20 tiles.

Not a Leaflet issue.

**Comment by andrewhodel** [comment]
Then why does safari automatically change it to 19 and chrome does not?

**Comment by andrewhodel** [comment]
It is correct to say that it will render a tile image if no error is returned, obviously.

I originally linked the osm project webpage noting the supported zoom levels, can you tell me where they specify that their public tileserver does not support zoom level 20 and that it provides an error via the http response?

@IvanSanchez

**Comment by andrewhodel** [comment]
We'll keep this here for future (historical at the time) reference.

<img width="1072" alt="Screen Shot 2021-07-29 at 2 00 40 PM" src="https://user-images.githubusercontent.com/741705/127550665-bfcc59dd-2f16-4796-ae04-29db663bcc9f.png">

**Comment by IvanSanchez** [comment]
> can you tell me where they specify that their public tileserver does not support zoom level 20 and that it provides an error via the http response?

https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#Tile_servers

**Comment by andrewhodel** [comment]
Cool, any plans to have tileservers publish 4 direction next max/min zoom and current x/y min/max zoom for missing tiles via http headers?



Thank You,
Andrew Hodel

**Comment by andrewhodel** [comment]
https://youtu.be/0rB8p63YXUg

I’ve experienced missing data.

4 direction gives you an average (like checkers) for the whole view area and what to expect outside the bounds without expecting to send 8/16/32 directions per tile or that the tileserver would calculate bounds. 




Thank You,
Andrew Hodel

**Comment by andrewhodel** [comment]
Then we can expect to zoom into a building (photos, drawings, AR, live camera) and smoothly pan across the street with anything that can render compressed images fast enough.

**Comment by IvanSanchez** [comment]
> Cool, any plans to have tileservers publish 4 direction next max/min zoom and current x/y min/max zoom for missing tiles via http headers?

Read the documentation about OSM's `renderd` and `mod_tile` yourself. This is theLeaflet bug tracker, and **just** the Leaflet bug tracker.
