### ISSUE TITLE
Uncaught Error: Map container is already initialized

### ISSUE THREAD

**Issue by fahimaltinordu** [Leaflet/Leaflet#7634]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported
I found some reports but still couldnot find a solution yet

**Steps to reproduce**
- it happens if i switch to other tabs in chrome and within every 3 seconds in mozilla without doing anything. 

**Expected behavior**

**Current behavior**

**Environment**
- Leaflet version: latest version 
- Browser (with version):
- OS/Platform (with version):

**Additional context**

**Minimal example reproducing the issue**

Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.

https://fahimaltinordu.github.io/cluster-map-leaflet/

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by IvanSanchez** [comment]
Issue with your own code, not a leaflet bug.

**Comment by fahimaltinordu** [comment]
Sorry @IvanSanchez i did not know.
Can you please help me what i am making wrong?
Best regards

**Comment by IvanSanchez** [comment]
Debug your code. Set a breakpoint in your `L.map()` line and see how many times that runs.
