### ISSUE TITLE
Polygons have `cursor:pointer` when there's no click events bound

### ISSUE THREAD

**Issue by nemosmithasf** [Leaflet/Leaflet#7636]
I'm not sure if this constitutes a bug or if its as intended, but I can't see any reason why we'd possible want a pointer when there are no clicking actions bound.

The problem manifests itself in elements that only have a `hover` event. There shouldn't be a pointer when we hover over these elements, and at the same time, we can't we the "disable interactivity" prop because that removes our ability to hover as well.

**Comment by IvanSanchez** [comment]
> The problem manifests itself in elements that only have a `hover` event.

No, it applies to layers with their `interactive` option set to `true`, independently of which events are bound. It's behaviour as intended (or as we use to say: "It's a feature, not a bug").

You're free to override this by setting a CSS `className` in your `L.Path`s and adding the appropriate CSS.

**Comment by nemosmithasf** [comment]
That's what I'm getting at, is there a reason why we should apply `pointer` to all interactive elements? Especially since we know that not all interactive elements are clickable (e.g. hovers), and by convention, pointers specifically indicates "click-ability".

**Comment by IvanSanchez** [comment]
But that's a deep rabbit hole to go into. It's `click` events, or `pointerdown`, or `mouseup`, or something else, or a combination of those, that should define "clickability"?

I'm fine with the current Leaflet status quo of "if it's interactive, it has a `cursor:pointer`". While you do have a point, I don't think that getting into all the casuistic is worth it.
