### ISSUE TITLE
API should expose the underlying OpenLayers Map.setTarget() method

### ISSUE THREAD

**Issue by marqdouj** [Leaflet/Leaflet#7644]
reference: https://openlayers.org/en/latest/apidoc/module-ol_Map-Map.html#setTarget

In my own custom OpenLayers code I use the map.setTarget() method. I wish to start using Leaflet but this method is not exposed by the API (at least I can't find it). It's counterpart getTarget() appears to be exposed using the Leaflet getContainer() method.

I find this method very useful in Blazor for resetting the container when the page is re-rendered.

**Comment by IvanSanchez** [comment]
This is Leaflet.... there is no underlaying openlayers code anywhere.

**Comment by marqdouj** [comment]
After reading the docs, my understanding was that Leaflet uses the OpenLayers map? 
In any case, what I am looking for is the counterpart to the getContainer method; I need a setContainer method.

**Comment by IvanSanchez** [comment]
>  Add a `map.setContainer` method as a counterpart to the `map.GetContainer` method

Nope, Leaflet's handling of the map container is too tightly integrated to allow for this.

**Comment by marqdouj** [comment]
That's too bad. Guess I'm stuck using OpenLayers due to how Blazor handles rendering.
