### ISSUE TITLE
[es6] Modern build tool

### ISSUE THREAD

**Issue by mathe42** [Leaflet/Leaflet#7648]
To modernize the code we need a new build setup / modify the existing one.

To compile js code to es3 there are 2 tools:
1. tsc (TypeScriptCompiler)
2. gcc (GoogleClosureCompiler)

gcc runs as a java application so this is a bigger problem. So I propose that we go with tsc. (This doesn't mean to write TypeScript! tsc can handle plain JS).

There are currently 3 builds:
1. `leaflet-src.esm.js` (ES-Module but es3 syntax)
2. `leaflet-src.js` (UMD-Bundle with es3 syntax)
3. `leaflet.js` (minified UMD-Bundle - with es3 syntax)

I additional propose to add a 4th file. A "modern esm build" that doesn't compile to es3 but to something like es2017.

I will call the file (for now) `leaflet-modern.esm.js` this would have the advantages that polyfills don't need to be added (and shiped!) if there is native support. The specific target can be disscused. I will go in a PR for es2017 (95% Browser support) but there are valid reasons for other targets.
When used in bundlers this file can be compiled to a lower target as needed.

**Comment by IvanSanchez** [comment]
I'm personally vetoing this, solely on the basis that "modern" is a [weasel word](https://en.wikipedia.org/wiki/Weasel_word).

Do not use the word "modern" as an argument for a change.
