### ISSUE TITLE
Click on popup text, event not catchable

### ISSUE THREAD

**Issue by Radamanf** [Leaflet/Leaflet#765]
I can do something wrong but. I've tried to create a click event listener on text (span tag) placed in PopUp and unable to catch click event in any browser, sometimes it does works, but most of the time it's not. If I change span to a tag it can start to work but for one popup first in list, and doesn't work for the rest. It's only me having this issue?

It's easy to open popup from my list of popup, but to open this list of popups from map (popup) is not possible currently.

Here is my code to open popup it works:

```
    $('.pointpopup').click(function(){
        var pointname = this.id;
        map.setView(point[pointname].getLatLng(),15);
        point[pointname].openPopup();
    });
```

Here is code to open list from popup, does not work, (test code to fire event):

```
    $('.map_popup').click(function(){
        //alert('Try to open Accordion ')
        console.log('Try to open Accordion' + $(this).attr('href'));
    })
```

**Comment by m314** [comment]
Here's an updated version of http://jsfiddle.net/M5Ntr/46/ using Leaflet 1.0 and JQuery 3.1: https://jsfiddle.net/myjkby8w/

**Comment by Jimi9** [comment]
Hello everybody,

I am facing an issue, I have a list of markers, each one populated with a popup. When I try to run a function in the <a> tag of the popup this one instead of running the function when clicked it runs the function for every marker and after that it doesn't allow to use it any longer.

As you can see here my popup is realized like so:

            function changeStatus(stationId, newStatus) {
                //console.log('ciao',stationId)
                const point = points.find(point => point.name === stationId);

                // If the point is found
                if (point) {
                    // Update the status of the point
                    point.status = newStatus;

                    // Find the marker for the point
                    const marker = point.marker;
                    //console.log('Before updating icon:', marker.options.icon.options.iconUrl);
                    //console.log('changStat',stationId,newStatus)
                    // Update the marker's icon based on the new status
                    switch (newStatus) {
                        case 0:
                            marker.setIcon(
                                L.icon({
                                    iconUrl: greyIcon,
                                    iconSize: [18, 18],
                                })
                            );
                            break;
                        case 1:
                            marker.setIcon(
                                L.icon({
                                    iconUrl: blackIcon,
                                    iconSize: [18, 18],
                                })
                            );
                            break;
                        case 2:
                            marker.setIcon(
                                L.icon({
                                    iconUrl: greenIcon,
                                    iconSize: [18, 18],
                                })
                            );
                            break;
                        case 3:
                            marker.setIcon(
                                L.icon({
                                    iconUrl: redIcon,
                                    iconSize: [18, 18],
                                })
                            );
                            break;
                    }


                    //console.log('After updating icon:', marker.options.icon.options.iconUrl);
                    point.marker = marker;

                    // Update the popup content based on the new status
                    marker.setPopupContent(`<br><strong>Name:</strong> ${point.name}
      <br><strong>Latitude:</strong> ${point.coordinates[0]}
      <br><strong>Longitude:</strong> ${point.coordinates[1]}
      
      <br><strong>Status:</strong><span id="status-popup" style="color: ${newStatus == 3 ? 'red' : newStatus == 2 ? 'green' : newStatus == 1 ? 'black' : 'grey'};">
        ${newStatus == 3 ? 'Shake detected' : newStatus == 2 ? 'OK' : newStatus == 1 ? 'Error (Data delay)' : 'Error'}</span>

      <br><strong>Link: </strong> <a id="linkId" href="#" @click="${fetchXMLData}" target='_blank' >Web-interface</a>`);//point.link
                } //http://${vm.$root.apiUrl}/admin/ in case you want to redirect to admin page

            }



Why is this happening and not following the click event? many thanks
