### ISSUE TITLE
Cannot read property of basVal

### ISSUE THREAD

**Issue by Chaitu15** [Leaflet/Leaflet#7652]
Trying to get tileLayer work using POST request, but end up in getting below error, can anyone please guide here

Error: TypeError: Cannot read property 'baseVal' of undefined
code:

import * as L from 'leaflet';

export const BetterWMS = L.TileLayer.BetterWMS = L.TileLayer.WMS.extend({

    createTile: async function (coords, done) {
        var tile = document.createElement('img');

        tile.abortController = new AbortController();

        L.DomEvent.on(tile, 'load', L.Util.bind(this._tileOnLoad, this, done, tile));
        L.DomEvent.on(tile, 'error', L.Util.bind(this._tileOnError, this, done, tile));

        if (this.options.crossOrigin || this.options.crossOrigin === '') {
            tile.crossOrigin = this.options.crossOrigin === true ? '' : this.options.crossOrigin;
        }

        /*
         Alt tag is set to empty string to keep screen readers from reading URL and for compliance reasons
         http://www.w3.org/TR/WCAG20-TECHS/H67
        */
        tile.alt = '';
        tile.src = L.Util.emptyImageUrl;

        /*
         Set role="presentation" to force screen readers to ignore this
         https://www.w3.org/TR/wai-aria/roles#textalternativecomputation
        */
        tile.setAttribute('role', 'presentation');

        this._loadTile(coords, tile);

        return tile;
    },

    _loadTile: function (coords, tile) {
        const fullUrl = this.getTileUrl(coords);
        const [url, urlparams] = fullUrl.split("?");

        fetch(url, {
            method: "POST",
            body: urlparams,
            headers: {
                "Content-type": "application/x-www-form-urlencoded",
            },
            signal: tile.abortController.signal
        })
            .then(response => {
                return response.blob();
            })
            .then(blobData => {
                tile.src = window.URL.createObjectURL(blobData);
            })
            .catch(() => { });

    },

    // stops loading all tiles in the background layer
    _abortLoading: function () {
        for (const i in this._tiles) {
            if (this._tiles[i].coords.z !== this._tileZoom) {
                const tile = this._tiles[i].el;
                if (tile.src === L.Util.emptyImageUrl) {
                    tile.abortController.abort();
                }
            }
        }
        L.TileLayer.WMS.prototype._abortLoading.call(this);
    },

    _removeTile: function (key) {
        const tile = this._tiles[key];
        if (!tile) {
            return;
        }
        if (tile.el.src === L.Util.emptyImageUrl) {
            tile.el.abortController.abort();
        }
        L.TileLayer.WMS.prototype._removeTile.call(this, key);
    },

});

export const betterWms = L.tileLayer.betterWms = function (url, options) {
    return new L.TileLayer.BetterWMS(url, options);
};

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by FloMueh** [comment]
Gm guys, 

mate i had the same issue and it took my hours to find out what the problem is.

problem is the **async** keyword.
`createTile: async function (coords, done) {`

remove the **async** keyword and access your async data via Promise.then(x => tile.src = x) and it will work perfectly. 

writing this comment for many guys from google 💯

**Comment by Beuthmaster** [comment]
@FloMueh Thank you so much! Your note successfullly finished two days of debugging 😅
