### ISSUE TITLE
Autodetection of L.Icon.Default.imagePath, getScript() inclusion

### ISSUE THREAD

**Issue by taes1g09** [Leaflet/Leaflet#766]
The method used to auto detect the correct path to the default marker and shadow images causes problems under two circumstances:

1) The search regex `/\/?leaflet[\-\._]?([\w\-\._]*)\.js\??/` also matches unintended similar files such as `leafletFooBar.js`, giving the markers the wrong relative path. Since only `leaflet.js` and `leaflet-src.js` need to be matched, `/\/?leaflet(-src)?\.js\??/` might work instead.

2) The nature of the method being used (search the page for the correct script tag) defeats the use of `getScript()` to include `leaflet.js` from another file, as in this case the desired script tag is not present in the page.

**Comment by knutole** [comment]
Getting this error when including leaflet.js in a minified/uglified script. I'll set manually, but perhaps this should be dealt with in `v0.8`.

**Comment by julienrf** [comment]
Same issue: when minified (and only when minified) I get this error too.

**Comment by leitasat** [comment]
I have just started experiencing the bug @knutole and @julienrf described (getting `Couldn't autodetect L.Icon.Default.imagePath, set it manually.` after minifying). The weird part is that it started after a couple of months of using leaflet. Not sure which update triggered it, if any. Also would be nice to mention this in the quick start guide. 
I'm loading `leaflet.draw` from mapbox's CDN.

**Comment by EricWVGG** [comment]
Also crashing into this with minified code.

**Comment by maxaudrin** [comment]
+1

**Comment by vinyll** [comment]
Same issue here after moving `<leaflet-map>` from the index file into a component (using Polymer here).

I had to set the path like this:

    ready() {
        L.Icon.Default.imagePath = '../bower_components/leaflet/dist/images/'
    }

**Comment by tjwebb** [comment]
Same issue using the leaflet npm module in React

**Comment by coltonbrugger** [comment]
+1 for more-graceful solution.

**Comment by jonasroessum** [comment]
@jsouthron or `console.warning`

**Comment by perliedman** [comment]
Also see #4605 for an improved detection method.

**Comment by infoitservit** [comment]
+1 but...why this issue is "Closed"? I've seen only workarounds...

**Comment by perliedman** [comment]
@infoitservit Leaflet tries its best to autodetect, and our opinion is that 1.0 is about as good as it's going to get (maybe with some possible improvements for Webpack users). If autodetection doesn't work, it's still easy to set `L.Icon.Default.imagePath`
