### ISSUE TITLE
HighlightOptions for CircleMarkers on R Package

### ISSUE THREAD

**Issue by ctedja** [Leaflet/Leaflet#7661]
For someone developing leaflet maps exclusively within R - when using addCircleMarkers(), would it be possible to also include highlightOptions() in the same way that we are able to for addCircles()?

I've looked in the R [documentation](https://cran.r-project.org/web/packages/leaflet/leaflet.pdf) but I saw that highlightOptions aren't included for addCircleMarkers() while they're there for addCircles(). I prefer use of addCircleMarkers() for a number of reasons, such as the way that the markers resize at different zoom levels.

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* NativeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.

**Comment by ctedja** [comment]
Thanks Ivan, noted.
