### ISSUE TITLE
EPSG4326 coordinate system origin looks off

### ISSUE THREAD

**Issue by PROgram52bc** [Leaflet/Leaflet#7666]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…) 
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
See demo
**Expected behavior**

EPSG4326 example should be centered at latlong 0,0

**Current behavior**

EPSG4326 example does not center at latlong 0,0 (it looks more like [0,90]).
I think this behavior should either be fixed to match the other coordinate system, or documented somewhere, but I haven't found any documentation about it.

**Environment**
- Leaflet version: 1.7.1
- Browser (with version): Chrome
- OS/Platform (with version): Ubuntu 18.04

**Additional context**

See [this issue](https://github.com/jupyter-widgets/ipyleaflet/issues/867)

**Minimal example reproducing the issue**
https://plnkr.co/edit/MFDB1waJnkr8mAGu?preview

Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by IvanSanchez** [comment]
Do not use EPSG:4326 tiles in a EPSG:3857 map. See #7198 and #5072.

**Comment by PROgram52bc** [comment]
Do you mean the map I created in the demo is a "EPSG:3857 map"? Is there a way I can create a "EPSG:4326 map"? I would appreciate more clarification on that. Thanks!

**Comment by IvanSanchez** [comment]
One of your maps is a EPSG:4326 map using EPSG:3857 tiles.

(Yes, I typoed hard there - I meant "do not use EPSG:3857 tiles in a EPSG:4326 map")

**Comment by PROgram52bc** [comment]
Thanks! Would you be able to point out for me how I can know whether a tile is in EPSG:3857 or EPSG:4326 system? For example, [the wiki page](https://wiki.openstreetmap.org/wiki/Tiles#Base_maps) doesn't seem to indicate that their tiles are exclusively for EPSG:3857.

**Comment by IvanSanchez** [comment]
Assume 3857 if there's no metadata on the contrary. Read the TMS spec and the WMTS spec to see how other tile pyramids look like.

**Comment by PROgram52bc** [comment]
I am still not convinced that it is a problem with the tiles that I used.
See [this example](https://plnkr.co/edit/MFDB1waJnkr8mAGu) which uses a different tile, but still has the same issue.
According to [EPSG4326](https://epsg.io/map#srs=4326&x=0.000000&y=0.000000&z=4&layer=streets) reference, (0,0) should point to the South Atlantic Ocean south west of Africa, but when EPSG4326 is specified in the leaflet `Map` object, the tiles seem to be rendered incorrectly.

**Comment by IvanSanchez** [comment]
Read https://en.wikipedia.org/wiki/Equirectangular_projection and https://en.wikipedia.org/wiki/Mercator_projection , then look at the tiles, then ask yourself what projection each tileset uses.
