### ISSUE TITLE
Download link broken

### ISSUE THREAD

**Issue by teo1978** [Leaflet/Leaflet#7667]
At https://leafletjs.com/download.html

I click on the first download link (v 1.7.1) and nothing happens.

In the javascript console this error shows up:

Mixed Content: The site at 'https://leafletjs.com/' was loaded over a secure connection, but the file at 'http://cdn.leafletjs.com/leaflet/v1.7.1/leaflet.zip' was loaded over an insecure connection. This file should be served over HTTPS. This download has been blocked. See https://blog.chromium.org/2020/02/protecting-users-from-insecure.html for more details.

**Comment by mathe42** [comment]
Note that it is not as easy as change the links to https as SSL is not properly configured:
https://cdn.leafletjs.com/leaflet/v1.7.1/leaflet.zip
The cert is not valid for that page.

**Comment by Jassi10000** [comment]
> Note that it is not as easy as change the links to https as SSL is not properly configured:
> https://cdn.leafletjs.com/leaflet/v1.7.1/leaflet.zip
> The cert is not valid for that page.

Yeah I guess SSL is not approved yet
