### ISSUE TITLE
Is it possible to use leaflet for visualizing high-resolution streaming images?

### ISSUE THREAD

**Issue by jmontoyam** [Leaflet/Leaflet#7674]
Hi,

first of all, thank you very much for keeping this amazing project up and running! ;).
I am a beginner JS user (but eager to learn more about JS and web technologies). In my use-case, I am interested in creating a web application that allows to visualize high-resolution streaming images acquired by an xray system (the server) while scanning objects on a moving conveyor belt. I would like to visualize the streaming raw images as the acquisition systems writes them to disk to check that the experiment is going well and the images are acquired as expected. Every "dt" milliseconds the acquisition system acquires a new "snapshop" and writes it to disk, this image is of dimension 64 x 10240. The number of images acquired during an experiment is variable (it could be thousands, tens-of-thousands, or even millions, it depends on the duration of the experiment). I am planning extending the acquisition systems such that not only write the raw images to disk, but also generate the image tiles to be used by leaflet. I would like to use leaflet for visualizing such stream of images while they are generated and exposed by the server (the acquisition system). At any given moment, the user can interact with the viewer (zoom-in/out, panning, etc), while the acquisition system continues streaming the new data. Do you guys think is it possible to use leaflet to accomplish such goal?

Thank you very much!

All the comments, suggestions and advices are truly welcome ;).

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by IvanSanchez** [comment]
I mean, the answer's probably gonna be [yes](https://strcat.de/questions-with-yes-or-no-answers.html), but you seem to be asking for advice on how to design a system.

Is Leaflet a tool that can be leveraged for this task? Probably yes. Is it the best option? Depends on the system constraints and the rest of the system components.

In any case, this is a bug tracker, not a place to get gratis system design advice.
