### ISSUE TITLE
Documentation bug: "id" option not listed under TileLayer options

### ISSUE THREAD

**Issue by arunlal-v** [Leaflet/Leaflet#7675]
Thanks for this wonderful library!

The "id" option looks to be a mandatory one when specifying [TileLayer options](https://leafletjs.com/reference-1.7.1.html#tilelayer), but it's not specified in the [documentation](https://leafletjs.com/reference-1.7.1.html#tilelayer-option) under the direct/inherited sections.

**Comment by IvanSanchez** [comment]
> The "id" option looks to be a mandatory one

No, it's not.

**Comment by arunlal-v** [comment]
@IvanSanchez, I apologize; I should have been a little more detailed.

1. When I specify "id" [(line number 20 here)](https://jsfiddle.net/L1pkbd2n/) in the TileLayer options, everything [works fine.](https://jsfiddle.net/L1pkbd2n/) Now, when I [comment out just the "id" option](https://jsfiddle.net/sxmn91cu/), the console throws ```"Uncaught Error: No value provided for variable {id}"```
2. The "id" option is nowhere specified in the [TileLayer documentation](https://leafletjs.com/reference-1.7.1.html#tilelayer-option)

**Comment by IvanSanchez** [comment]
See https://docs.mapbox.com/api/maps/raster-tiles/ and the bit in https://leafletjs.com/reference-1.7.1.html#tilelayer which says «You can use custom keys in the template, which will be evaluated from TileLayer options».

See also https://github.com/leaflet-extras/leaflet-providers / https://leaflet-extras.github.io/leaflet-providers/preview/ . Do not confuse Leaflet functionality with the parameters of a tile service.

**Comment by arunlal-v** [comment]
Got it. Thanks for sharing leaflet-providers resource. That helps.
