### ISSUE TITLE
Get id Corrdinate 

### ISSUE THREAD

**Issue by MohsenEs** [Leaflet/Leaflet#7679]
Hi, How can I get the ID I gave to a polygon by clicking?

`       var geojson = {
                   
                    "type": "FeatureCollection",
                    "features": [{
                        "postalAreaId": item.PostalAreaId,
                        "type": "Feature",
                        "properties": {
                            "name": "Coors Field",
                            "amenity": "Baseball Stadium",
                            "popupContent": "This is where the Rockies play!"
                        },
                        "geometry": {
                            "type": "Polygon",
                            "coordinates": []
                        }
                    }]
                };`

![2021-09-25_17-35-00](https://user-images.githubusercontent.com/46873097/134774326-e97aa033-454b-4def-9b10-4dc402602b07.jpg)
![2021-09-25_17-33-49](https://user-images.githubusercontent.com/46873097/134774327-4ac57043-cf7d-435a-86fb-762436b4c47e.jpg)

**Comment by johnd0e** [comment]
If you have a "How to" question, please use StackOverflow or StackExchange.

Leaflet Issues are meant for Bug reports and Feature requests only.
