### ISSUE TITLE
Improvements to the Readme of the repo

### ISSUE THREAD

**Issue by Jassi10000** [Leaflet/Leaflet#7681]
**Is your feature request related to a problem? Please describe.**

* Wouldn't it be more easy to include the installing instructions in the Readme of this repo as well alongside the website , if all the things are in a single place it becomes quite easy for devs .
* As LeafLet is quite a nice idea !! 🤘 I think a giphy of working of LeafLet on different devices in the Readme can be a great attention seaker for the repo
* As a dev I too expect that the Readme should be more attractive with nice buttons and links mentioned

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

If got a chance I would love to contribute to the repo

**Comment by mourner** [comment]
I don't think the readme should duplicate detailed information, demos and more on the official website, to which it links. Closing.
