### ISSUE TITLE
WMS GetFeatureInfo?

### ISSUE THREAD

**Issue by fabiopacheco18** [Leaflet/Leaflet#7683]
hello to team of leaflet.

do you plan to add a getfeatureinfo functionality in the next update?
We really need this functionality for an angular project ( version 8)

**Comment by IvanSanchez** [comment]
> do you plan to add a getfeatureinfo functionality in the next update?

No.

> We really need this functionality for an angular project ( version 8)

That's *your* problem, and you should look for Leaflet plugins for it.

Telling a maintainer that you *need* something and/or trying to create a sense of haste won't help.

**Comment by fabiopacheco18** [comment]
sorry, we didn't want to pressure you.
we just wanted to know if this feature will be added to the next realase.
we tryed to use the plugin "leaflet.wms" but we have issues to make it work.
