### ISSUE TITLE
FitBound method is taking too much time for setting the view

### ISSUE THREAD

**Issue by jpavansharma** [Leaflet/Leaflet#7684]
We are plotting 5k points (markers) using leaflet library. On passing bounding box coordinates to the FitBounds method for 5k stores, it is taking around 15 seconds to apply the bounds. 

We are using geoJson method of leaflet to plot the markers by inputting geoJson data.
Even this method is taking around 7-10 seconds for 5k points.

![image](https://user-images.githubusercontent.com/26058187/135605287-ca6e2fe1-fe35-43e7-b5d9-c01b44b3e747.png)

Please find the bounds provided by layer.bounds. 
![image](https://user-images.githubusercontent.com/26058187/135605349-9d50324e-56cb-4594-b595-435d9f8db371.png)

We are giving this as input to fitBounds method.
After calling fitBounds method providing above bounds as input, it is taking around 15 seconds to return from this method for 5k stores.
Please let us know if it is desired. 
If so, is there a way to overcome this.

Regards,
Pavan Kumar J

- [ ] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [ ] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [ ] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- step 1
- step 2
- ...

**Expected behavior**

**Current behavior**

**Environment**
- Leaflet version: 1.4
- Browser (with version): Google Chrome
- OS/Platform (with version): Windows 10

**Additional context**

**Minimal example reproducing the issue**

Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

**Comment by IvanSanchez** [comment]
Already in stackoverflow.
