### ISSUE TITLE
invalid latlng object: (undefined, undefined) 

### ISSUE THREAD

**Issue by Bradley-H** [Leaflet/Leaflet#7686]
I'm not sure what I'm doing wrong here. I checked the docs and either I overlooked this (which is probably the case), or something is wrong.

What I'm trying to do to is center the map at the long and lat that I got from an API and center the marker with it.

Here is the function I have currently

    async function getIPInfo(){
        try {
            let endpoint = `https://api.ipgeolocation.io/ipgeo?apiKey={KEY}ip=${$globalStore.searchTerm}`
            let response = await fetch(endpoint);
            let query = await response.json();
           let { ip, isp, state_prov, city, time_zone, latitude, longitude } = query; 
           let UTC = time_zone.offset;
           $globalStore.searchResults = {ip, isp, state_prov, city, UTC, latitude, longitude}
           let view = map.setView([lat, lng], 13);
           console.log(view);
           LatLng([lat, lng]);
        } catch (error) {
            console.log(error);
        }
}

yet I get the error, any help would be appreciated

EDIT: I'm using svelte for those who are curious. Furthermore, It "works" however, on my function call it gives me the error, on the second it sets the marker and the view.

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?

If it's not reproducible *without Svelte*, then it's not a Leaflet bug (and this is for bugtracking only, not for support)
