### ISSUE TITLE
How to build source code

### ISSUE THREAD

**Issue by Alim9100** [Leaflet/Leaflet#7687]
hello 
i want to build the source code of leaflet. How do I build it?
thanks

**Comment by mathe42** [comment]
1. git clone
2. npm i
3. npm run build

**Comment by Alim9100** [comment]
> 
> 
>     1. git clone
> 
>     2. npm i
> 
>     3. npm run build

thanks. Is this project developed with JavaScript or node.js?

**Comment by IvanSanchez** [comment]
https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md

**Comment by Alim9100** [comment]
thanks, i have another question. is it possible to use this codes as js scripts in browser instead of building it. if yes, what should i do?

**Comment by IvanSanchez** [comment]
This is a bug tracker, not a place for questions.
