### ISSUE TITLE
Mastodon account for this project

### ISSUE THREAD

**Issue by linux-lukas** [Leaflet/Leaflet#7692]
Would a Mastodon account for this project be possible?

**Comment by mourner** [comment]
Why would Leaflet need a Mastodon account?

**Comment by Lukas2112** [comment]
For project information and project announcements.

**Comment by IvanSanchez** [comment]
Given the amount and frequency of announcements, I don't think it's worth the hassle.

**Comment by thibaultmol** [comment]
(seems like Github doesn't show links to mentioned issues in discussions, so I'll link: https://github.com/Leaflet/Leaflet/discussions/9615 here)
