### ISSUE TITLE
How can we help the maintainers and keep Leaflet alive?

### ISSUE THREAD

**Issue by Falke-Design** [Leaflet/Leaflet#7704]
We all love Leaflet and appreciate the work of the maintainers (@mourner, @IvanSanchez, @johnd0e, ... ), thank you ❤️ 
The active contributors knows that the maintainers have a lot of work with Leaflet and it's getting less and less attention, which is completely understandable but deadly for the project.

#### The Problem of less attention
I can only write for me but I would love to make some PRs and fix issues or update some old PRs which would be very useful, but I'm losing interest because I know the chance to get the PR is merged is currently very low and if it is approved it is possible that  it will still not merged because no one clicks the merge button ... I would say that I'm not the only one who think like that.
I think this is a result of available time of the maintainers for Leaflet + less active maintainers + amount of Issues / PRs. But it won't get better if contributors like me, go away from Leaflet because they think it is not worth to help.
I don't want to accuse you of anything, this project is voluntarily and no one of you must do anything. I only want to show the problem.

## But how can we help to make it better?
I have not the perfect answer but maybe we find one together!
I will write here some thoughts:

#### 1. Organisation over Contributors
Let us (contributors) help to discuss on PRs / Issues and tag it with labels. The idea behind it is, that a PR can be tagged with "approved", "small", "needs maintainer help", "close", ... to make it easier for the maintainers to use their precious time for some useful / valuable things and not for something like #7562 that we contributors can do too. And also make it possibile to force some small PRs to get merged.

A way would be to grant on Github some contributors to add tags or to add Issues / PRs to a Github-Project. But I don't no if there is a way to do this without other permission granting.
Or other platforms. I only know Jira, but maybe there are some better ones out there

#### 2. Voting
Maybe a voting system can be included to show the desires of the community.
Can be done by voting with 👍 like in lodash (but the system are not understandable for newbies) or on a other platform.

#### 3. More maintainers / Junior-Maintainers
In my eyes it is a problem that the available time of the maintainers are not enough for Leaflet so it needs more maintainers. So my suggestions is to take some contributors into a Junior-Maintainer-Membership. They get step by step more permissions and can help you with some easy things but they also know that they get response and help from one of the maintainers. 

#### 4. Strategy
There are a few points which needs a decision how to go further with Leaflet.
For example:
 - #7128
 - Validation: In several comments was written that we should validate but how is not defined / decided
 - #7615
 - #7591
 - ...

#### 3. Slack / Discord?
I know from the OpenMapTiles project that it can sometimes helpful to have a channel where problems and other things can be discussed but I think that Leaflet is to large for this and also maintainers are needed for this.

#### 4. Every X months a meeting?
Maybe it would be a chance to decide some topics and go further with Leaflet. But for this are topics needed and the time of the maintainers. Maybe a Issue can be created "Topics for the Leaflet-Meeting" where topics are collected and if there are enough a meeting can be made.

### Updates / Releases
My suggestion would be to make more small releases. There are several bugs fixed in the master and the last Leaflet Release is older then a year (1.7.1 2020-09-04). It is always a huge step to make a big release so why not making multiple small ones in the year? Bugs are fixed earlier and there would be more contributors because their change is coming soon too.
One of the biggest issue since the last release is #7255 (2020-09-05) and the fix is still not released. (it is so much to read that I don't know if it is fixed, if not: ignore the last sentence 😄 )

### It would be very nice to have a good discussion with the maintainers and other contributors.

Important! I don't want to criticize the maintainers and I don't want to say that they are doing something wrong! I only want to show what are problems in my eyes.

**Comment by johnd0e** [comment]
I am not so optimistic about _Leaflet 2.0_.
It demands a lot of resources, but we just do not have so much.
Imagine: devs works so hard, but early version is still less stable, and lacks of important features.
And it may not survive API breaking, as there is too little gain for (thousands of) existent projects to adapt their sources to 2.0.

So I'd rather bet for evolutionary development, step by step. Discontinue IE<11 support, modernize/clean up code and css, deprecate polyfills, ...

**Comment by Falke-Design** [comment]
Yes I see this points problematic too. 
A suggestion: We can say with `2.0` we start a new evolution where we make this steps with each new version. We can create a Roadmap what we want to reach in which release. Instead of 1.9 we call it now 2.0 and make it with the major release visible that there will be changes.

Maybe we need first to create a summary what we think would be good to change

**Comment by johnd0e** [comment]
> * Getting rid of global switches (`L_NO_TOUCH` and `L_DISABLE_3D`)

Such switches could be still useful for debugging and testing.
Also related: #7335

> * Considering removal (or extraction into a plugin) of the Canvas renderer if it's not widely used given typical Leaflet use cases (no need for heavy vector rendering, where libraries like GL JS do much better), and performance advancements for SVG in browsers over the last decade.

SVG becomes too slow at (as low as) a thousand of objects. GL JS may be fast, but a way worse integrated into Leaflet than L.Canvas.
So it's too early to retire it.

**Comment by mourner** [comment]
> So I'd rather bet for evolutionary development, step by step. Discontinue IE<11 support, modernize/clean up code and css, deprecate polyfills, ...

That's exactly what I'm suggesting — focusing on things that make it easier to maintain and do evolutionary changes. Calling it Leaflet v2.0 is just a way to do a major breaking change like dropping IE<11.

**Comment by daniel-brenot** [comment]
The canvas renderer is important to me at the moment. Leaflet is already quite slow in our use case and svg would be a dealbreaker.

**Comment by mourner** [comment]
All right, keeping the canvas renderer! Just throwing ideas here, looking for potential things to drop for simplicity and easier maintenance.

**Comment by daniel-brenot** [comment]
I think having first-part support via .d.ts files would help the community a-lot. You wouldn't need to clutter your js with types, and people who like them can make them for the project.

Additionally, would this version remove the ".extend" syntax that existed before js had proper class support? It really shows the age of the library and i think a rewrite should deal with this issue.

**Comment by jonkoops** [comment]
Perhaps we can close this issue in favor of the discussion that has been started in #7729?

**Comment by Malvoz** [comment]
Another thing that may be helpful is to utilize [GH issue form templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) instead of the current [markdown issue templates](https://github.com/Leaflet/Leaflet/tree/master/.github/ISSUE_TEMPLATE).

The benefits are that information can be required (so maintainers don't have to ask "can you please <provide that thing that the template already told you to provide but you erased/ignored it>"). It also provides standard HTML inputs such as checkboxes and select drop downs (no more broken checkboxes such as `- []`, `- [ x]`) in issue reports.

More info: https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/.

**Comment by Malvoz** [comment]
Thanks everyone for your input.

> Perhaps we can close this issue in favor of the discussion that has been started in https://github.com/Leaflet/Leaflet/discussions/7729?

Just so we don't miss anything important (let me know if I did), here's a brief summary:

- [x] Scheduled/periodic meetings are not helpful to already overloaded maintainers!
- [x] Potential codebase modernization and other big breaking changes: https://github.com/Leaflet/Leaflet/discussions/7729.
- [x] "Automate as much release routine as possible". I believe there's been a lot of work done in this area already.
- [x] "More maintainers / Junior-Maintainers": @Falke-Design and I have since joined as collaborators.
- [x] Revisit the labeling system: https://github.com/Leaflet/Leaflet/discussions/8018.
- [ ] Sponsorship/crowdfunding may help, though [it's not clear how that would work in practice](https://github.com/Leaflet/Leaflet/issues/7704#issuecomment-953981734).
      (New issue/discussion to discuss separately?)
- [ ] Stale bot.
      (New issue/discussion to discuss details separately?)
- [ ] [Issue forms with YAML templates](https://github.com/Leaflet/Leaflet/issues/7704#issuecomment-981410604) can help people create better issues.
      (I'll open a separate issue.)
- [ ] "Gratis iPhone 15 and iMac" for @IvanSanchez's birthday
      (If you want more attention to your favorite bugs, please contact Ivan and make this a reality. 🙏🏼😄)

**Comment by Malvoz** [comment]
Again, thanks everyone for participating in this discussion.

I believe my previous [comment](https://github.com/Leaflet/Leaflet/issues/7704#issuecomment-1090818637) summarizes this issue well. If you've suggested a feature here that hasn't been posted in https://github.com/Leaflet/Leaflet/discussions/7729, please do so!

As long as there is a demand for Leaflet, it will be kept alive by the maintainers and the community together. You can help by [contributing](https://github.com/Leaflet/Leaflet/blob/main/CONTRIBUTING.md) to Leaflet directly, and also by [sponsoring](https://github.com/sponsors/Leaflet) this project. ❤
