### ISSUE TITLE
HABILITAR

### ISSUE THREAD

**Issue by Queens666** [Leaflet/Leaflet#7717]
https://console.cloud.google.com/marketplace/details/google-cloud-platform/cloud-run?project=acquired-winter-329112

**Comment by Falke-Design** [comment]
@mourner is it possible to block @Queens666? He creaes a lot of spam ... #7713, #7715, https://github.com/Leaflet/Leaflet/issues/7458#issuecomment-953298143

**Comment by mourner** [comment]
@Falke-Design Yep, blocked.
