### ISSUE TITLE
Failed to disable pointer events in recent Firefox versions

### ISSUE THREAD

**Issue by johnd0e** [Leaflet/Leaflet#7728]
After some of last changes in dependencies this setup is not working anymore:
https://github.com/Leaflet/Leaflet/blob/e3fde981e25dda3f90ab33de433a05be40f406a5/spec/karma.conf.js#L105-L125

Look here: 
https://github.com/Leaflet/Leaflet/blob/e3fde981e25dda3f90ab33de433a05be40f406a5/spec/suites/SpecHelper.js#L69-L70

E.g. if we run `npm test -- --browsers FirefoxTouch` - we should get:
```
L.Browser.pointer, false
L.Browser.touch, true
```

But we see `true` for both cases instead.

**Comment by jonkoops** [comment]
@johnd0e Is there a specific commit that is causing this that you know of?

**Comment by johnd0e** [comment]
> Is there a specific commit

I know only that 620bc3e9c5d282090f429ac21d28d00fbffdb3db was ok.

**Comment by mourner** [comment]
Maybe due to a newer Firefox headless version? I see the following prefs now:

![image](https://user-images.githubusercontent.com/25395/139874940-1a44c5d0-63d3-4217-a364-01126bac95fd.png)

**Comment by mourner** [comment]
Let's do a git bisect then.

**Comment by johnd0e** [comment]
> Maybe due to a newer Firefox headless version?

You are right.
Disabling touch is still OK, but I do not see any way to disable pointer events now(

**Comment by johnd0e** [comment]
Alternatively: put this into `before.js`:
```js
window.PointerEvent = undefined;
window.MSPointerEvent = undefined;
```
Unfortunately I've failed to find any way to do this _conditionally_, depending on currently used _customLauncher_ or `karma` argument.
