### ISSUE TITLE
Touchstart is not fired on layer while down and then moving

### ISSUE THREAD

**Issue by Falke-Design** [Leaflet/Leaflet#7753]
On a touch device when a `mousedown touchstart` listener is added to a layer, it will not fired if user clicks down and then start moving. If user is only clicking down `mousedown` is fired.
![touchstart_not_fired](https://user-images.githubusercontent.com/19800037/140658919-c99b1cd6-ef4f-4ee4-a8e9-b460bd8a1f55.gif)

**Expected behaviour:**
`mousedown / touchstart` is fired despite the move

The purpose behind it is to make the layer draggable. As workaround i added a listener to the DOM container of the layer instead of the layer self. But now is the problem, that this doesn't work for canvas renderer because it has only one DOM element. (My next step will be to reuse the code of `_onClick` in L.Canvas to get the clicked layer)

I haven't found the problem part in my first tries.
Maybe one following things:
- tap toleranz
- Missing touchevents: 
 https://github.com/Leaflet/Leaflet/blob/257ca098f1edfe091ec029bcead25f7f9ce2b676/src/map/Map.js#L1311-L1312

Used code (+ latest master):
```
  var rect = L.rectangle(map.getBounds()).addTo(map);
  rect.on('mousedown touchstart', (e) => {
    console.log(e);
    document.getElementById('content').innerHTML += 'Called ' + e.type + '<br>';
  });
  map.setZoom(15);
```

**Comment by johnd0e** [comment]
js bin?

**Comment by Falke-Design** [comment]
I tried to set it up with jsfiddle and plunker but both are not working well in the touch mode of the browser. 
I have now tried to get it running on jsbin but it throws a error in touchmode and dragging (this is not happening without fiddle framework)
https://jsbin.com/tifiwabuqa/edit?html,output

Here a test on my server but I will remove it in the next days: http://test.lagekarte.info/test.html

**Comment by johnd0e** [comment]
> http://test.lagekarte.info/test.html

Unable to reproduce

**Comment by Falke-Design** [comment]
This happens on Chrome with Touch, Firefox with Touch and on my Android Firefox.

Have you tried it on the phone?
There are only a few steps to do this:
1. Touch on the rectangle -> Console "mousedown"
2. Touch on the rectangle and hold it down and then move it -> Map is dragged and "mousedown" is not fired

**Comment by johnd0e** [comment]
> * Touch on the rectangle -> Console "mousedown"
> * Touch on the rectangle and hold it down and then move it -> Map is dragged and "mousedown" is not fired

This is expected.
In first case you see compatibility mouse event, produced on click.
https://www.w3.org/TR/pointerevents3/#compatibility-mapping-with-mouse-events

**Comment by johnd0e** [comment]
> * Missing touchevents:

Only these events are supported on Leaflet objects: https://leafletjs.com/reference.html#interactive-layer-click

> The purpose behind it is to make the layer draggable. As workaround i added a listener to the DOM container of the layer instead of the layer self.

See https://leafletjs.com/reference.html#draggable

> But now is the problem, that this doesn't work for canvas renderer because it has only one DOM element.

Yeah, the things are complicated.
