### ISSUE TITLE
Layer\_addZoomLimit not covered by tests

### ISSUE THREAD

**Issue by johnd0e** [Leaflet/Leaflet#7762]
https://github.com/Leaflet/Leaflet/blob/d03a2d09aab86481793836cc6a4b80dff19b32ca/src/layer/Layer.js#L238

First part of condition ignored - tests are passing with or without.
Ref: #7609. Related: #7761

**Comment by manassikri** [comment]
Hey, can you please explain a bit more about this bug? I am new to this and would like to work on this.

**Comment by Falke-Design** [comment]
The referenced code line is changed in #7609:
https://github.com/Leaflet/Leaflet/blob/17dcbe9b087c9fd16899bf8e0b27b72c34f7063e/src/layer/Layer.js#L229-L234

We want a test which checks if `this._updateZoomLevels();` is called when maxZoom or minZoom is set
