### ISSUE TITLE
Removed Marker is back after using Layers Control

### ISSUE THREAD

**Issue by antontranelis** [Leaflet/Leaflet#7774]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- Create LayerGroup
- Add Marker
- Remove Marker
- Use LayerControl to hide LayerGroup
- Use LayerControl to show LayerGroup again

**Expected behavior**
The removed marker should not be visible

**Current behavior**
The removed marker is visible

**Environment**
- Leaflet version: 1.7.1
- Browser (with version):  Firefox 94.0 / Chromium 95.0.4638.69
- OS/Platform (with version): Linux Mint 20.2 Cinnamon

**Minimal example reproducing the issue**

https://plnkr.co/edit/GNS5sWJPqfvKdrmH

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by johnd0e** [comment]
> The removed marker is visible

That is how that is supposed to work.
When you add LayerGroup (via tapping Layers control) - you add all the content of LayerGroup.

If you need any other behavior - extend LayerGroup to fit your needs.

**Comment by Falke-Design** [comment]
@antontranelis you need to remove the marker from the layergroup self: `littleton.removeFrom(cities);`
`

**Comment by antontranelis** [comment]
> @antontranelis you need to remove the marker from the layergroup self: `littleton.removeFrom(cities);` `

thank you very much! That works!
