### ISSUE TITLE
Extend `Layers Control` Tutorial with dynamic change of the layers 

### ISSUE THREAD

**Issue by Falke-Design** [Leaflet/Leaflet#7787]
I suggest to add a section in the [Layers Control tutorial](https://leafletjs.com/examples/layers-control/) where is described how can layers added and removed dynamically.

Docu: https://leafletjs.com/reference.html#control-layers-addbaselayer

PR is welcome.

**Comment by francoisblin** [comment]
Ok I would like to contribute to this issue !

**Comment by QuentinPhilipp** [comment]
Is this issue still open? I don't see an example of adding and removing layers dynamically in the documentation.

If so, I would like to contribute.

**Comment by Falke-Design** [comment]
@QuentinPhilipp yes would be nice
