### ISSUE TITLE
polyline rides 

### ISSUE THREAD

**Issue by tenkoff** [Leaflet/Leaflet#7791]
Hello,

I catch strange behavior with `polyline`

I use sample code from `https://leafletjs.com/examples/quick-start/example.html` and change coordinates to my own code is here https://gist.github.com/tenkoff/65d61070f762fa3cd1bb2f07f7f76ede

I got this in leaflet

![telegram-cloud-photo-size-2-5244659160593839500-x](https://user-images.githubusercontent.com/428849/142724891-361639b1-6ddf-48d1-b8a3-803df22bd4c3.jpg)

and this in google maps

![telegram-cloud-photo-size-2-5244659160593839520-y](https://user-images.githubusercontent.com/428849/142724904-591e91d9-74b6-4bbb-8449-ed7e555422ad.jpg)

**Comment by IvanSanchez** [comment]
See https://stackoverflow.com/q/40532496/4768502
