### ISSUE TITLE
Release Leaflet v1.8.0

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#7810]
We long overdue for a v1.8.0 release, and I've cleaned up the process so that it's much easier now. The remaining question is — which of the outstanding PRs we should definitely land for the release? @johnd0e @Falke-Design — I created a `v1.8` milestone, feel free to add must-have PRs to that it would be easier for me to review.

**Comment by Falke-Design** [comment]
Without #7026 we don't need to release 1.8. it is the number 1 issue 😄

**Comment by johnd0e** [comment]
> which of the outstanding PRs we should definitely land

Added also a couple of important but unresolved issues,

**Comment by Falke-Design** [comment]
Is ok for me but can you please create a milestone where we can move the issues / pRs for 1.8.1? To keep them on track, what we should check after 1.8.0

**Comment by mourner** [comment]
@Falke-Design good point, created a 1.8.1 milestone.

**Comment by Falke-Design** [comment]
@mourner can we keep merging the 1.8.0 milestone?
Ready to check would be: #7782, #7855

@johnd0e can you please go through the milestone and mark the PRs as "Ready for review" (not draft) and remove not necessary PRs.

**Comment by Falke-Design** [comment]
@mourner it would be nice if we can release 1.8 with march, what do you think? I remove as much as possible from the 1.8.0 milstone.

Fast and easy to check:
 -  #7763

Needs a decission:
 - #7302 (maybe it is enough to say if this topic is not important for 1.8.0)

Needs more time:
 - #7532
 - #7446
 - #7965

@IvanSanchez, @jonkoops, @johnd0e, @Malvoz help and approving PRs would be nice. Are you interesseted to make an appointment get rid of it?

**Comment by Malvoz** [comment]
> help and approving PRs would be nice

I'm mostly comfortable reviewing a11y-related PRs.

**Comment by mourner** [comment]
> it would be nice if we can release 1.8 with march, what do you think?

Yes! Maybe we could even release in the nearest weeks. Unless my home is invaded by Russia, but I truly hope not.

**Comment by mourner** [comment]
> * #7302 (maybe it is enough to say if this topic is not important for 1.8.0)

Moved to v1.8.1, this doesn't seem critical to fix — there are easy workarounds.

> * #7532

Resolved the conflicts there, @Falke-Design can you take another look at it to see if we can merge?

**Comment by Falke-Design** [comment]
If you have currently time there would be some other easy to merge PRs:
- #7814
- #7956
- #7914
- #7777

**Comment by Malvoz** [comment]
@nofx77 see https://github.com/Leaflet/Leaflet/issues/7810#issuecomment-1030904147.

**Comment by Falke-Design** [comment]
Only performance tests are open

Dragging, Moving map:
- #7446

Moving & zooming map (pinch zoom):
- #7965

@mourner @IvanSanchez any experience / suggestions how to make performance tests?

**Comment by mourner** [comment]
> any experience / suggestions how to make performance tests?

There are no easy ways to benchmark those, we'll have to profile and analyze manually.

**Comment by Falke-Design** [comment]
@mourner the last three open PRs are ready for review and merge.

**Comment by Falke-Design** [comment]
@mourner the Release 1.8 is near. Do we need to prepare something like blog entry or the changelog?

**Comment by mourner** [comment]
@Falke-Design we definitely need to prepare a changelog, and it might be a pretty massive undertaking — going through all PRs that landed in 1.5 years, sorting, categorizing and rewording them to reflect impact for users.

**Comment by mourner** [comment]
@jonkoops @Falke-Design the automated NPM publish works! 🎉 Just published `v1.8.0-alpha.0` by creating a version commit + tag with `npm version preminor --preid=alpha` and then pushing, that's it. `npm info leaflet` shows properly tagged releases (`alpha: 1.8.0-alpha.0,  latest: 1.7.1`), and the alpha is [available through unpkg](https://unpkg.com/browse/leaflet@1.8.0-alpha.0/).

The next step is to finish #8021, update `CHANGELOG.md`, tag the beta release, potentially add a link to the beta on the website, and make a call for public testing on Twitter.

**Comment by Falke-Design** [comment]
@mourner your are currently very active in the project so maybe you a time to go over the following things too:

- #7818 
- #7788 
- #7768 
- #7593 
- And some others which https://github.com/Leaflet/Leaflet/labels/needs%20decision

**Comment by mourner** [comment]
The beta version is released: https://github.com/Leaflet/Leaflet/releases/tag/v1.8.0-beta.0
We need to follow with cosmetic updates such as updating the website download page with a new row for the beta, and announce the release on Twitter. Then we'll watch for regression reports, and if there aren't any, release the final.

**Comment by Falke-Design** [comment]
@mourner I think we shoud add a thank you for @johnd0e to the Release notes. He refactored the touch events and DivOverlay without much help. Maybe I'm wrong but in my eyes kept @johnd0e Leaflet alive until we get a fresh wind in November.

**Comment by mourner** [comment]
@Falke-Design good point, added.

**Comment by mourner** [comment]
Added a few more names, so many of you deserve praise on this!

**Comment by Eschon** [comment]
Thanks for all your work!  
Would it be possible to release the beta to npm to make it easier for people to test it?

**Comment by mourner** [comment]
> Would it be possible to release the beta to npm to make it easier for people to test it?

@Eschon it is on NPM. `npm install leaflet@beta`.

**Comment by patrickarlt** [comment]
It looks like 1.8.0 does cause an issue with Leaflet.Editable. I've got a basic [recreation in this CodePen](https://codepen.io/patrickarlt/pen/ExoNOXa?editors=1000). Editing still seems to work but after clicking to complete a new shape the map you get this error:

```
Uncaught TypeError: can't access property "x", t is undefined
    _subtract Point.js:67
    subtract Point.js:63
    _panOnFocus Marker.js:397
    o DomEvent.js:108
    ki DomEvent.js:135
    S DomEvent.js:34
    _initIcon Marker.js:249
    onAdd Marker.js:120
    onAdd Leaflet.Editable.js:483
    _layerAdd Layer.js:114
    whenReady Map.js:1475
    addLayer Layer.js:172
    addLayer LayerGroup.js:47
    initialize Leaflet.Editable.js:478
    i Class.js:24
    addVertexMarker Leaflet.Editable.js:1051
    addLatLng Leaflet.Editable.js:1260
    newPointForward Leaflet.Editable.js:1266
    newPointForward Leaflet.Editable.js:1519
    processDrawingClick Leaflet.Editable.js:1305
    onDrawingClick Leaflet.Editable.js:932
    onMouseup Leaflet.Editable.js:268
    fire Events.js:203
    _fireDOMEvent Map.js:1450
    _handleDOMEvent Map.js:1399
    o DomEvent.js:108
    ki DomEvent.js:135
    S DomEvent.js:34
    _initEvents Map.js:1319
    initialize Map.js:142
    i Class.js:24
    map Map.js:1751
    <anonymous> index.html:63
Point.js:67:2
```

This error does not throw in [this recreation in 1.7.1](https://codepen.io/patrickarlt/pen/NWXbEBE?editors=1000)

It looks like Leaflet.Editable is no longer maintained but I thought I should mention it here in case anyone wanted to track it down and resolve it since people are probably still using Leaflet.Editable in the wild.

I'm going to switch our demos on Esri Leaflet to Leaflet Geoman to avoid this for now since it looks like @Falke-Design did a really nice job on it.

**Comment by Malvoz** [comment]
@patrickarlt There's a discussion for the v1.8.0-beta.0 here: https://github.com/Leaflet/Leaflet/discussions/8044. I think it'd be best to report any issues there - one comment for each issue, to which others can reply - discussions are much more easy to follow along that way. 👍🏼

**Comment by Falke-Design** [comment]
@mourner I think we should release 1.8 with the end of this week. What do you think?
There is no fast solution for #3575, which is in the 1.8 milestone

**Comment by mourner** [comment]
Releasing now. Checklist:

## Releasing a new version of Leaflet

- [ ] Ensure all https://github.com/Leaflet/Leaflet/labels/blocker issues and pull requests are resolved.
- [ ] Update [the changelog](https://github.com/Leaflet/Leaflet/blob/main/CHANGELOG.md) since last release and commit.
- [ ] Run `npm version <patch | minor | major>` (this will bump the version in `package.json` and create a new tag).
- [ ] Run `git push --follow-tags` to push the commit created by NPM to Github (together with the tag).
- [ ] Wait for the CI to complete and follow the logs to make sure it runs successfully.
- [ ] Verify that the release was correctly published to NPM by checking:
  - [ ] [Leaflet NPM package page](https://www.npmjs.com/package/leaflet)
  - [ ] files on [Leaflet unpkg page](https://unpkg.com/leaflet@latest/)
- [ ] Make a new release on [Leaflet's GitHub release page](https://github.com/Leaflet/Leaflet/releases/) with the most important parts of the changelog

### Updating docs after the release

- [ ] Make a new branch for the update
- [ ] Write a blog post about the new release and put it in `/docs/_posts`
- [ ] If necessary to preserve previous version's docs, rename `dist/reference.html` to `dist/reference-X.Y.Z.html` and add it to the list in `docs/reference-versions.html`
- [ ] Run `npm run docs` to generate the new `docs/reference.html`
- [ ] Run `npm run integrity` and make sure `docs/_config.yml` is updated with new hashes
- [ ] Update link to latest release in `docs/download.md`
- [ ] Update the announcement section in `docs/index.html`
- [ ] Commit all the changes and submit a PR for someone to review

**Comment by Malvoz** [comment]
@mourner We should make the flag in the attribution resizable with font-size. I'm about to send a PR, if it's worth waiting for it.

**Comment by mourner** [comment]
@Malvoz oops, too late :( Let's move to v1.8.1

**Comment by Malvoz** [comment]
That's alright, I'll open an issue for now.
