### ISSUE TITLE
Add a bundle size check in GitHub Actions

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#7811]
It would be nice to add a check to CI that shows how many bytes a PR adds to the JS bundle. Preferably as a text in GH checks rather than a comment bot. cc @jonkoops 

```
leaflet.js: 142kB (+35), 40kB gzipped (+15)
```

**Comment by mathe42** [comment]
https://github.com/siddharthkp/bundlesize#build-status-for-github would be a option for that. Or write a simple script for that.

If interessted I would add it to the workflow. No matter in wich way. Custom script is not that difficult would create it in a week or so.


As I'm a big fan of treeshaking I would propose to add a size check for a minimal Map-Example (just Map with 1 Marker) so we can keep an eye on that too. If that is a thing you are interessted in I can add this too.

**Comment by Falke-Design** [comment]
@mathe42 can you please setup the suggested changes?
