### ISSUE TITLE
Tests in workflow are failing

### ISSUE THREAD

**Issue by Falke-Design** [Leaflet/Leaflet#7824]
I don't know why but tests are often failing because the browser didn't start:
![grafik](https://user-images.githubusercontent.com/19800037/143787432-15fe09ff-fe57-4b3c-8510-3b1f0c0388cb.png)

@jonkoops @mourner Can we change something to fix this? Is it possible to run the tests on the contributer repo, so they can re-start the workflow?

**Comment by johnd0e** [comment]
It's possible to re-run the test manually. At least I have enough permissions and see such button.

**Comment by Falke-Design** [comment]
Yes I know that you can do this, but others like me can't. Instead of hoping that you re-start the workflow manually, it would be good to check if we can prevent it from failing.

**Comment by johnd0e** [comment]
> if we can prevent it from failing.

But we can't

**Comment by jonkoops** [comment]
Yeah, this is flaky but seems like it would be quite hard to fix, if it can really be fixed at all. We could try upping the retry count and timeout direction.

**Comment by Falke-Design** [comment]
@jonkoops I searched a little bit around and that is what I found:

Many posts are speaking of the Browser binary path is wrong, but I don't know if we have access to this: [link 1](https://github.com/karma-runner/karma/issues/1206#issuecomment-332377273), [link 2](https://stackoverflow.com/a/61522817/8283938)

A other attempt would be to increase the timeout: [doc](https://github.com/karma-runner/karma/blob/master/docs/config/01-configuration-file.md#capturetimeout), [link 3](https://github.com/karma-runner/karma-browserstack-launcher/issues/159#issuecomment-582837942), [link 4](https://github.com/karma-runner/karma/issues/598#issuecomment-44488403)

Or increase the retry count: [doc-retryLimit](https://github.com/karma-runner/karma/blob/master/docs/config/01-configuration-file.md#retrylimit)


I reopen this, because I think we should try if we can fix it with one of the suggested ways.
