### ISSUE TITLE
Not possible to calculate bounds for another zoom level reliably

### ISSUE THREAD

**Issue by johannesjo** [Leaflet/Leaflet#7828]
I am trying calculate the bounding box for a larger zoom level than the current. I tried 3 different approaches which imho should all yield the same results. But they don't. Also worth noting is that I was able to use the same approach with google maps, so while I am not sure if I am doing everything correctly, the general approach did work in another environment.

Please have a look at the plunkr:
https://plnkr.co/edit/sk6NRh51WZA2vpWP

Either I am misunderstanding something fundamental about leaflets projections or somewhere under the hub, there is something fishy going on (which I currently suspect and thus opening up this ticket).

**Environment**
- Leaflet version: 1.7.1
- Browser (with version): Chrome V 96
- OS/Platform (with version): Doesn't matter

**Minimal example reproducing the issue**
https://plnkr.co/edit/sk6NRh51WZA2vpWP

**Comment by IvanSanchez** [comment]
This is already at https://stackoverflow.com/questions/70115385/leaflet-get-scaled-bounding-box-by-zoom-level , so I'm closing this here.

**Comment by johannesjo** [comment]
Understandable, but I doubt that the question will ever get an answer, as it might turn out to be some internal bug. I already spent a ton of time working on this and I am open to work on this myself, but I would greatly appreciate a little guidance.
