### ISSUE TITLE
New Labels

### ISSUE THREAD

**Issue by Falke-Design** [Leaflet/Leaflet#7830]
@mourner I suggest to create new labels:

1. `small PR` to label some simple / small PRs that can easily merged without digging hard into the change. I think with that we (you) can close many PRs without much effort. #7480, #7630
2. `needs decision` can be added to issues / PRs that needs a decision from you and can't be discussed more than it already is. #6272
3. `ios` because we have a lot of IOS Issues and we have `android` too

**Comment by Malvoz** [comment]
It's not clear to me that "small PR" is useful in practice.
- It would clutter a lot of PRs
- It'd be time consuming to go through PRs just to add the label
- What's the definition of "small"?
- Isn't it better to highlight (in comments) when large PRs could be broken up to smaller PRs (e.g. https://github.com/Leaflet/Leaflet/pull/7927), although some PRs are just large by nature and can't/shouldn't be broken up into smaller PRs.

+1 on the other labels.

**Comment by Falke-Design** [comment]
with `small PR` I want a label which says that this PR has no big changes and don't need much time to go over it and check the changes. Maybe it was not the best label name 😄 something like `ready to merge`. With that label it would be possible to see all PRs which can be merged from a maintainer and already checked from us collaborators.

**Comment by Falke-Design** [comment]
I already thought about that, but mostley all of the current labeled PRs are not ready for a final review. We can remove the label from all this PRs and use it for the new ones.
In my eyes the current usage of `needs review` is not really useful, because every PR needs a review and the labeled ones are not different to others which are not approved.

**Comment by Malvoz** [comment]
I think of `needs review` as something to use when a PRs has been opened for a long time without review or any feedback comments. Maybe we should open a new [discussion](https://github.com/Leaflet/Leaflet/discussions) where we can have 1 comment per label and close this issue?

I also don't find `in progress` useful, that's what the draft status for PRs are for?

**Comment by Falke-Design** [comment]
Ok I will create a dicussion but after we finished the refactoring of the labels, I suggest to delete the discussion. I don't like the Github Discussion because they become messy if there are to much of them and they can't be closed and removed from the list like issues.

**Comment by Malvoz** [comment]
> they can't be closed and removed from the list like issues.

Another option is to just lock it when we're done with it, if keeping a historical record of the decisions is important/useful, so that it can't be bumped.

**Comment by Falke-Design** [comment]
I would like to keep it in an archiv but with locking it, it still is visible on the "first page" like a open issue. And if we get more and more dicussion the ["welcome page"](https://github.com/Leaflet/Leaflet/discussions) will filled with not necessary posts. 
It doesn't matter much for me, so we can keep it open too.

Linking: #8018
