### ISSUE TITLE
Feature or solution to stop Leaflet from processing unnecessary markers?

### ISSUE THREAD

**Issue by chrisjdixon** [Leaflet/Leaflet#7841]
My Leaflet map is receiving data asynchronously from Django from a DB of millions of entries and it appears Leaflet continues to process all markers unnecessarily until the browser lags out. The issue seems caused by two things:

- Leaflet processes markers outside of its boundary box
- I think my code might be allowing Leaflet to inappropriately process duplicate entries.

I've asked [this over on StackOverflow](https://stackoverflow.com/questions/70169402/how-to-make-leaflet-drop-or-stop-processing-markers-outside-of-its-bbox) and didn't get a response, which suggests I'm out of luck.

My code, adapted from @pauloxnet's [great tutorial:](https://www.paulox.net/2021/07/19/maps-with-django-part-2-geodjango-postgis-and-leaflet/#rendering-markers-incrementally)
```js
async function load_markers() {
const markers_url = `/api/markers/?in_bbox=${map.getBounds().toBBoxString()}`
const response = await fetch(markers_url)
const geojson = await response.json()
return geojson
}

async function render_markers() {
const markers = await load_markers();
L.geoJSON(markers)
    .bindPopup((layer) => layer.feature.properties.address)
    .addTo(map);
}

map.on("moveend", render_markers);
```
Is there a way to make Leaflet stop processing markers furthest away from its bbox if > n entries or similar? 

And might `.addTo(map)` be allowing duplicate entries? Is there a way to elaborate on this so that only new markers are added if they don't already exist?

I'm new to JS and programming so I'm sorry for the stupid questions. These questions seem conceptually simple so I'm thinking perhaps I've overlooked some basic feature. Please feel free to tell me to go away or ask elsewhere. Thank you so much for any help!

**Comment by mourner** [comment]
Leaflet can't do that automatically, but you can track duplicate markers with a JS [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) object with marker location (or id if provided by server) as key, and marker object as value. Hope this helps and sorry for not elaborating further — we have limited resources for JS questions here.
