### ISSUE TITLE
How to use docs offline

### ISSUE THREAD

**Issue by edgexie** [Leaflet/Leaflet#7844]
I want to use docs offline , when I run `http-server` in docs , I get the page without styles.

![image](https://user-images.githubusercontent.com/18474752/145237836-dc2fec79-6141-4a02-8bd3-39bb8529b64a.png)

**Comment by Falke-Design** [comment]
You need to install ruby like described in [CONTRIBUTING.md](https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md#improving-documentation).

Maybe you need to add `webrick` to, then you need to call `bundle add webrick`

Jekyll: http://jekyllrb.com/docs/#instructions

**Comment by edgexie** [comment]
@Falke-Design Can I build docs to a file， and open it with http-server？

**Comment by Falke-Design** [comment]
you need to run `npm run docs` not `npm run build`. A .html file will be generated but the styles are missing, so you have a text only html file. 
To render the style you need setup the server like described above

**Comment by edgexie** [comment]
@Falke-Design my describe has a mistake~ I really implement `npm run docs`，but I cant find a .html file in the dist/ directory.

**Comment by Falke-Design** [comment]
Ah, look into the `docs` folder maybe there is the `reference.html`. I will check it later and update the documentation

**Comment by edgexie** [comment]
@Falke-Design after I RUN `npm run docs` ，why the styles are missing in docs/index.html?

**Comment by edgexie** [comment]
@Falke-Design this is my docs folder
![image](https://user-images.githubusercontent.com/18474752/145954479-49f55465-6b44-4868-86a8-c1b9ddf4e47b.png)

when I open reference.html. the styles and Interact all are missing
![image](https://user-images.githubusercontent.com/18474752/145954621-7e12c7ac-c074-4554-8cd4-f2dc7dea5f0d.png)

**Comment by Falke-Design** [comment]
because we work with `jekyll`, it merges the different files together and adds the style while running a server on not the while generating the html file.

If you want to see the styles you need to start the jekyll server: [Docs](https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md#improving-documentation), [link](https://github.com/Leaflet/Leaflet/issues/7844#issuecomment-988935583). `localhost:4000`

**Comment by Malvoz** [comment]
@edgexie In case you initially missed a step, can you try the [new steps to serve docs](https://github.com/Leaflet/Leaflet/blob/main/CONTRIBUTING.md#improving-documentation) and see if that works better for you?
