### ISSUE TITLE
Browser contextmenu not showing anymore

### ISSUE THREAD

**Issue by Falke-Design** [Leaflet/Leaflet#7858]
The PR #7544 stops openeing the browser contextmenu. This is because we call for every `contextmenu` event `preventDefault()`:

https://github.com/Leaflet/Leaflet/blob/a9d7c4fe7d56a109eeba7d5c05b6dad93feb13e7/src/map/Map.js#L1427-L1429

But according to the docs it should only prevented if there are listeners on the target:
> Fired when the user pushes the right mouse button on the map, prevents default browser context menu from showing if there are listeners on this event. Also fired on mobile when the user holds a single touch for a second (also called long press).

https://leafletjs.com/reference.html#map-contextmenu

I think we should to keep the behavior "only preventing if there are listeners on the target"

**Comment by johnd0e** [comment]
But there is such code:
https://github.com/Leaflet/Leaflet/blob/a9d7c4fe7d56a109eeba7d5c05b6dad93feb13e7/src/map/Map.js#L1425

So it should work according docs.

**Comment by Falke-Design** [comment]
Plunkr with newest master: https://plnkr.co/edit/odU7aOGfa59wufzT

**Comment by Falke-Design** [comment]
Maybe Leaflet internal listeners

**Comment by johnd0e** [comment]
tapHold handler?

**Comment by johnd0e** [comment]
Ok, this is the issue source:
https://github.com/Leaflet/Leaflet/blob/a9d7c4fe7d56a109eeba7d5c05b6dad93feb13e7/src/map/Map.js#L1368-L1370
