### ISSUE TITLE
Rotatable Icons

### ISSUE THREAD

**Issue by Irokaiser** [Leaflet/Leaflet#7870]
**Is your feature request related to a problem? Please describe.**
I am using Leaflet to draw a position of an aircraft/drone in real time on a world map. 

**Describe the solution you'd like**
I would love the ability to be able to rotate an icon or shape to indicate the heading of the aircraft.

**Describe alternatives you've considered**
There is an extension to your library also on Github [here](https://github.com/bbecquet/Leaflet.RotatedMarker). However, I have been unable to get this extension to work, probably due to the fact that it was last updated 4 years ago. It would be really cool if you guys added this functionality to the base library.

**Comment by brunob** [comment]
@Irokaiser there's also this extension that does the job https://github.com/shramov/leaflet-plugins/blob/master/layer/Marker.Rotate.js

**Comment by jonkoops** [comment]
This is something that could be accomplished by using a plugin or by extending the marker code and adding the respective code. I don't think this is something that would need to be added to the core of Leaflet.

**Comment by jonkoops** [comment]
See also https://github.com/Leaflet/Leaflet/issues/143

**Comment by j-te** [comment]
This can be done with css via in-line or class: `transform: rotate(20deg);`. Animation can also be applied to this.

**Comment by GhadaAJIMI** [comment]
@Irokaiser how do we add that plugin in Angular? I installed it from npm but I don't find the module that I need to inclure in app.modules

**Comment by rafaellehmkuhl** [comment]
> This can be done with css via in-line or class: `transform: rotate(20deg);`. Animation can also be applied to this.

This won't work for `DivIcon`.

**Comment by jonkoops** [comment]
Closing this issue as we do not intend to implement this in Leaflet core.
