### ISSUE TITLE
Event drawvertex is triggering and other also, before contextmenu event get triggered

### ISSUE THREAD

**Issue by shivamsharmanps** [Leaflet/Leaflet#7879]
- I am drawing polygon and I don't want right-click so I used contextmenu event but as I enable polygon I am able to draw points through right-clicking as well and contextmenu trigger after drawvertex /mousedown. I am not able to stop right plz suggest valuable solution.

**Comment by Falke-Design** [comment]
1. How do you drawing a polygon?
2. `right-click` is `contextmenu`
3. Share your code
4. If it is not a bug please ask your question on [StackOverflow](https://stackoverflow.com/questions/tagged/leaflet) with the `leaflet` tag

**Comment by shivamsharmanps** [comment]
I am using leaflet drawer and after initialise polygon drawer and using method enable to start to draw then I tried with right-click on the map and I was able to draw then I went through the document and found 
`this.map.on('contextmenu', function(e) {
 event.preventDefault()l
})` to stop right-click events, it triggered late, and before that two more events had triggered i.e. drawvertex and mousedown.

**Comment by IvanSanchez** [comment]
1. "Leaflet drawer" is not a thing. I think you mean `leaflet.draw`, so please realize this is the wrong repo and bug tracker.
2. It's hard to understand what you've written, and we don't even know if this is a `leaflet.draw` bug or a problem on your side (we don't handle the later in the bugtrackers). I suggest reading ["How To Ask Questions The Smart Way"](http://www.catb.org/esr/faqs/smart-questions.html) and ["http://www.chiark.greenend.org.uk/~sgtatham/bugs.html"](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html)
