### ISSUE TITLE
Drag event is not working in rhel 8 chrome browser.

### ISSUE THREAD

**Issue by jlee28168** [Leaflet/Leaflet#7894]
- [ x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [ x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [ x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**

Step 1:  launch the example using a chrome browser in redhat - https://leafletjs.com/examples/quick-start/
Step 2: go to any map view, then select and drag.  (the feature is broken)

If you repeat this in a windows platform/firefox/Edge, it works.
- ...

**Expected behavior**

Expected select/drag to moves the map as it does in windows chome, firefox, edge

**Current behavior**

select/drag in redhat chrome just ignore the event;  However, if I emulate desktop touch browser, it then will work.   Looks like we missing mouse event in linux chrome?

**Environment**
- Leaflet version: 1.7
- Browser (with version): Version 97.0.4692.71 (Official Build) (64-bit)
- OS/Platform (with version): Red hat

**Additional context**

**Minimal example reproducing the issue**

Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.

The quick start examples fails too: https://leafletjs.com/examples/quick-start/

- [x ] this example is as simple as possible
- [x ] this example does not rely on any third party code

**Comment by Falke-Design** [comment]
Same issue as #7825? Look into https://stackoverflow.com/questions/69872483/leaflet-does-not-work-in-webengine-after-javafx-17/70300669#70300669

**Comment by jlee28168** [comment]
Maybe? Is there a easy way for me to test it out?  Currently we are pulling the package via yarn of version 1.7.   Do I need to download from the master branch to try this out?

Thanks!

**Comment by Falke-Design** [comment]
You can get the current master over https://leafletjs-cdn.s3.amazonaws.com/content/leaflet/master/leaflet-src.js

**Comment by jlee28168** [comment]
Just tested it with your version (master), and it is working with the latest chrome release in RHEL 8.   

Thanks!!
