### ISSUE TITLE
Site accessibility improvements

### ISSUE THREAD

**Issue by Malvoz** [Leaflet/Leaflet#7899]
I'm currently not set up with [Ruby](https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md#improving-documentation), so here are a few suggestions for leafletjs.com site accessibility improvements.

---

https://github.com/Leaflet/Leaflet/blob/e9bc85952d955347bbfd0a2d7909fdc51f08a48a/docs/_layouts/v2.html#L2

- [ ] `<html>` should have `lang="en"` (see MDN [`lang` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang)).

---

https://github.com/Leaflet/Leaflet/blob/e9bc85952d955347bbfd0a2d7909fdc51f08a48a/docs/_layouts/v2.html#L13-L14

- [ ] Add  `<meta property="og:image:alt" content="Leaflet">` (see [OGP `og:image:alt`](https://ogp.me/#:~:text=og:image:alt)).

---

https://github.com/Leaflet/Leaflet/blob/e9bc85952d955347bbfd0a2d7909fdc51f08a48a/docs/_layouts/v2.html#L61-L62

- [ ] These headings are repeated on every web page, they could be wrapped in [`<header>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header).
- [ ] `<h3>` should be changed to `<p>` (alternatively `<h2>`);<br>
      This would requires changing `h3.tagline` to `p.tagline` in: https://github.com/Leaflet/Leaflet/blob/e0c92a310cf0f0ab252b7ec0bae1f5624805106d/docs/docs/css/main.css#L183-L190 and https://github.com/Leaflet/Leaflet/blob/e0c92a310cf0f0ab252b7ec0bae1f5624805106d/docs/docs/css/main.css#L1006-L1009
      This is motivated by https://dequeuniversity.com/rules/axe/4.3/heading-order.
      (Although `<h3>` could be changed to `<h2>` to fix the issue, that would still be be h1 -> h2 -> h2 for next level headings in the `<div class="container">` element.)

---

https://github.com/Leaflet/Leaflet/blob/e9bc85952d955347bbfd0a2d7909fdc51f08a48a/docs/_layouts/v2.html#L64-L107

- [ ] `<ul class="nav">` is for navigation - the list should be wrapped in [`<nav>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav).
- [ ] (Optional but preferable: move the `<nav>` as last child of the new `<header>`.)

---

https://github.com/Leaflet/Leaflet/blob/e9bc85952d955347bbfd0a2d7909fdc51f08a48a/docs/_layouts/v2.html#L109-L124

- [ ] Change `<div class="container">` to `<main class="container">` (see MDN [`<main>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main));
- [ ] Move `<div class="footer">` out of (and below) `<main class="container">`;
- [ ] Wrap both `<div class="footer">` and `<nav class="ext-links">` in a [`<footer>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/footer).

---

Hopefully these small structural/element changes don't require much or any CSS changes. 😋

**Comment by Falke-Design** [comment]
Every task is fixed in #7901 except:
> (Optional but preferable: move the <nav> as last child of the new <header>.)

Because it is a optional task, I close this issue.

@Malvoz thank you for all you contribution in the accessibility topic! ❤️

**Comment by Malvoz** [comment]
@Falke-Design thanks for being patient with me 😄 I've double checked the changes on the live site, all looks good!

**Comment by Falke-Design** [comment]
@Malvoz thx, fixed it in #7906
