### ISSUE TITLE
Center positions for controls

### ISSUE THREAD

**Issue by kekscom** [Leaflet/Leaflet#791]
For UI controls in general, other positions than viewbox corners would be appreciated.
Suggestion: allo top, right, bottom, left as well. Especially on mobile, Zoom is best placed right, bottom right or bottom.

Addition: once multitouch has been detected, zoom controls could be removed - at least by some "auto" setting.

**Comment by williamjriley** [comment]
It would actually be very simple to add this functionality, by adding two lines to this code in leaflet.js:

Beginning at line 4900 I believe?
`t("top", "left"),`
`t("top", "right"),`
`t("bottom", "left"),`
`t("bottom", "right"),`

The two lines:
`t("top", "center"),`
`t("bottom", "center")`

This would allow for use of positions 'topcenter' and 'bottomcenter'

Then simply add css class for 'leaflet-center':
`.leaflet-center {`
`    left: 50%;`
`    transform: translate(-50%, 0%);`
`}`

**Comment by perliedman** [comment]
Hi, thanks for the suggestion.

However, this is not as simple as it might seem. See #5554, which is an attempt to add this. Unfortunately, we still support browsers that do not have CSS `transform`, so not easy to add at this point.

Also, for the future, please do not refer to line numbers in the build Leaflet file in `dist`, but preferably the actual source file.

**Comment by williamjriley** [comment]
Fair enough. Apologies for the line number, but I was in the middle of a work-day when I posted, so I didn't have time to go through the source. For my personal needs, we are not supporting IE < 9, and so I am okay with just making this change in a local copy and using it. I feel like it would still be good to add this functionality, and advise that the extra positions are only available in browsers that support transform, but that's only my opinion. Thank you for the response!
