### ISSUE TITLE
Register a DOI for Leaflet

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#7931]
It has been suggested that Leaflet registers for a DOI (persistent Digital Object Identifier) to make academic citations of Leaflet resilient (and indexed in some academic tools, and copies stored in vaults, etc).

This is purely a piece of administrative work over the repository and the github workflows, not a code issue.

Relevant stuff:
* OSGeo projects with DOI: https://wiki.osgeo.org/wiki/DOI
* Howto mit Screenshots: https://guides.lib.berkeley.edu/citeyourcode
* Youtube Howto Video: https://www.youtube.com/watch?v=A9FGAU9S9Ow
* Inclusion of a CFF and a JSON file in the codebase for automated GitHub-Zenodo integration: https://wiki.osgeo.org/wiki/Persistent_identifiers(pid)#Howto_2

**Comment by Malvoz** [comment]
There's also relevant info in the Github docs: https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

**Comment by Malvoz** [comment]
This seems pretty straight forward with Zenodo, following the GH docs.

Do we want to allow the following access?

![zenodo](https://user-images.githubusercontent.com/26493779/180953343-f1395edc-bde6-412c-992b-d7042f12deab.png)

Should I go ahead and attempt to set this up, or maybe you want to do it @IvanSanchez?

**Comment by IvanSanchez** [comment]
@Malvoz I don't see any immediate benefit, so feel free to go ahead.

**Comment by Malvoz** [comment]
Ok, automatic preservation has been enabled:

![leaflet-zenodo-doi](https://user-images.githubusercontent.com/26493779/200115130-036dccc5-02a4-4b4c-8421-3b2bc423e52f.png)

Will be able to add a badge to the README (if desired) after next release.

**Comment by Malvoz** [comment]
Let's keep this open until we have the actual DOI though.

**Comment by Malvoz** [comment]
The following markdown points to the latest released version:

```md
[![DOI](https://zenodo.org/badge/931135.svg)](https://zenodo.org/badge/latestdoi/931135)
```
Result:

[![DOI](https://zenodo.org/badge/931135.svg)](https://zenodo.org/badge/latestdoi/931135)

`7335490` is the <q>Concept DOI (all versions)</q> of the Leaflet repo, see https://help.zenodo.org/#versioning for more info. And here's the Zenodo record: https://zenodo.org/record/7335490.
