### ISSUE TITLE
Support a custom referrerPolicy option for TileLayer

### ISSUE THREAD

**Issue by natevw** [Leaflet/Leaflet#7943]
**Is your feature request related to a problem? Please describe.**

We recently updated our web framework [to Django 3.2 in case others hit a similar issue] and our [MapBox] tile provider API key stopped working.

It looks like Django 3.1 [made a change](https://chipcullen.com/django-3-referrer-policy-change/) to now send a `Referrer-Policy: same-origin` header by default (on the HTTP response for the page containing our Leaflet map). So the referer header that used to be sent with the tile fetch requests is no longer sent and the tile provider (which ties API tokens to specific domains) rejects the requests.

**Describe the solution you'd like**

I would like a new `referrerPolicy` option available on TileLayer. When set, the option's value would then be copied to the [`HTMLImageElement.referrerPolicy` property](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/referrerPolicy) of each image node that particular TileLayer creates. E.g.

```
L.tileLayer(myUrlTemplate, {
  referrerPolicy: 'strict-origin-when-cross-origin'
}).addTo(map);
```

IIUC, this explicit referrer policy would override the document's default policy and the fetch requests would be accepted as they were before.

**Describe alternatives you've considered**

We could change back the Referrer-Policy sitewide, but ideally we wouldn't have to do that just for one feature of the site. I.e. whether Django was right-or-wrong to make this change, ideally we should be able to tighten up the *default* policy for our pages like Django did to us, and then override it for some of the requests which Leaflet makes.

**Additional context**

There is already a conceptually similar [`crossOrigin`](https://leafletjs.com/reference.html#tilelayer-crossorigin) option available for TileLayer configuration: https://github.com/Leaflet/Leaflet/blob/911f578/src/layer/tile/TileLayer.js#L140

**Comment by natevw** [comment]
(I should be able to start a basic PR for this soon if the proposed feature is agreeable to the maintainers and if the client this is affecting doesn't request a different solution…)

**Comment by IvanSanchez** [comment]
I'm a bit torn about this issue.

On one hand, it's completely reasonable: Leaflet's `L.TileLayer`s already have a  `crossOrigin` setting that defines an attribute of the `<img>`s spawned, and `referrerPolicy` doesn't seem to have any backwards compatibility issues, and it should be just a dozen lines of code to make the change.

On the other hand, my cynicism has skyrocketed since the log4j debacle a few weeks ago, and I could argue that this is a framework (django) issue plus a tile provider (mapbox) issue. So the cynical side of me would really really like to see the mapbox support people devoting some company time to making this change, since they're the ones with something to lose (clients) in this situation.

**Comment by natevw** [comment]
> I could argue that this is a framework (django) issue plus a tile provider (mapbox) issue.

Perhaps, but I would counter-argue:

* we (and any other users) might want to tighten up our default referrer policy anyway — i.e. Django just happened to do it unexpectedly but we may have eventually done it ourselves anyway, so I don't consider this a bug on their part.
* it is users' interest to have an API key locked to only particular domains — i.e. if MapBox *didn't* check the domain it'd be much easier for another site to "steal" one of my tokens and rack up a big bill, so I consider their referrer check a feature and not a bug.

**Comment by Falke-Design** [comment]
A feature for a plugin?

**Comment by Falke-Design** [comment]
@natevw can you try if this works:
```
		L.TileReferrerLayer = L.TileLayer.extend({
			createTile(coords, done) {
				var tile = L.TileLayer.prototype.createTile.call(this, coords, done);
				if(this.options.referrerPolicy || this.options.referrerPolicy === ''){
					tile.referrerPolicy = this.options.referrerPolicy === true ? '' : this.options.referrerPolicy;
				}

				return tile;
			}
		});

		L.tileReferrerLayer = function(url, options) {
			return new L.TileReferrerLayer(url, options);
		};


var OSM_Mapnik = L.tileReferrerLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
			maxZoom: 19,
			attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',
			referrerPolicy: 'no-referrer|no-referrer-when-downgrade|origin|origin-when-cross-origin|unsafe-url'
		}).addTo(map);
```

**Comment by natevw** [comment]
@Falke-Design Thanks, your plugin version could be helpful for some who are stuck on the current official release.

I've also submitted a PR here for official support going forward since I think it will be at least (if not more) useful to others than the `crossOrigin` feature was.
