### ISSUE TITLE
BundleMon seems to fail intermittently

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#7946]
Here's a recent commit where `BundleMon` job fails: https://github.com/Leaflet/Leaflet/runs/4930516600?check_suite_focus=true

```
Error:  create commit record: bad project credentials
{"error":"GitHub action 1742977939 should be \"in_progress\" status"}
Error:  Failed to create commit record
Error:  Unhandled error
Error: Failed to generate report
    at /home/runner/work/Leaflet/Leaflet/node_modules/bundlemon/lib/main/index.js:32:15
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/Leaflet/Leaflet/node_modules/bundlemon/lib/main/index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Process completed with exit code 1.
```

Not sure what this means but probably worth investigating, or if it's expected, disabling the job if it can't run.

**Comment by jonkoops** [comment]
@LironEr do you have any idea what might be causing this exception?

**Comment by mourner** [comment]
Looks like it happens sporadically and for maintainer commits as well, not just contributors. Here's the latest occurrence: https://github.com/Leaflet/Leaflet/runs/4964248089?check_suite_focus=true

```
Error:  create commit record: bad project credentials
{"error":"GitHub action status should be \"in_progress\""}
Error:  Failed to create commit record
Error:  Unhandled error
Error: Failed to generate report
    at /home/runner/work/Leaflet/Leaflet/node_modules/bundlemon/lib/main/index.js:32:15
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/Leaflet/Leaflet/node_modules/bundlemon/lib/main/index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Process completed with exit code 1.
```

**Comment by LironEr** [comment]
One of the checks that the service does when running bundlemon in GitHub action (and without API key) is to check if the action that runs bundlemon is currently running ([code](https://github.com/LironEr/bundlemon/blob/master/service/src/controllers/utils/auth.ts#L57))

Since yesterday I added some logs to check GitHub response in those cases, and it looks like there is another status that I should allow.

I just deployed a [new code](https://github.com/LironEr/bundlemon/pull/85/files) that allows the new status and I will continue to monitor it.

**Comment by Falke-Design** [comment]
@jonkoops can we prevent running bundlemon without a PR?

**Comment by mourner** [comment]
Looks like it's working well now so we can close.

> @jonkoops can we prevent running bundlemon without a PR?

Why? This can be useful (e.g. checking for wins when you're experimenting in a branch but not yet ready to submit a PR yet).

**Comment by Falke-Design** [comment]
@mourner yesterday I get still the error, look into #7974, can you confirm that the error doesn't happen anymore since yesterday?

> This can be useful

In general yes, but not if most of the times the run fails

**Comment by jonkoops** [comment]
@Falke-Design might be useful to link the specific run here so we can inspect any exceptions.

**Comment by Falke-Design** [comment]
@jonkoops same as the other errors: https://github.com/Falke-Design/Leaflet/actions/runs/1802780798

**Comment by jonkoops** [comment]
> BundleMon GitHub app is not installed on this repo (Falke-Design/Leaflet)

This seems to be the issue, we can guard against this by adding a check. I've opened up a PR (#7983).
