### ISSUE TITLE
"Listener not found" warning when passing maxBounds option to map

### ISSUE THREAD

**Issue by natevw** [Leaflet/Leaflet#7951]
**Steps to reproduce**

1. Open the "debug/map/max-bounds.html" on current `main` branch
2. Look in the browser's JS console

**Expected behavior**

No error or warning messages should be present in the JS console.

**Current behavior**

A spurious "Listener not found" warning is logged by Leaflet. The warning is "harmless" in that it does not appear to break any map behavior, but it is noise for developers using Leaflet and a potential troubleshooting distraction to anyone else who might be peeking into the JS console on a project.

<img width="476" alt="Screenshot of demo map with the warning visible underneath via open developer tools pane" src="https://user-images.githubusercontent.com/265902/151248242-6c5ae1a6-af84-496a-81e8-7a832309f153.png">

**Environment**
- Leaflet version: testing at commit `409c17c` (which is unrelated to this issue, just happens to be at tip)
- Browser (with version): presumedly any, appears to be a logic issue
- OS/Platform (with version): presumedly any

**Additional context**

The warning and/or the conditions leading to it seem to have been introduced after the last official (1.7.1) release but I did not bisect to determine the exact commit.  It appears that the first call to `setMaxBounds` tries to unregister a `this._panInsideMaxBounds` listener before it has ever registered one.

**Minimal example reproducing the issue**

The "debug/map/max-bounds.html" example in this repo is sufficient.

**Comment by Falke-Design** [comment]
It was added with this commit https://github.com/Leaflet/Leaflet/commit/286f192ca963135ef769649b62830528c95ae3ae

**Comment by piotr-cz** [comment]
Warning started to show after upgrading 1.7.1 to 1.8.0 when map has maxBounds defined.
Apparently this has been added in https://github.com/Leaflet/Leaflet/pull/6958
