### ISSUE TITLE
Leaflet popup overlaying polygon blocks mouseover event

### ISSUE THREAD

**Issue by Elbargho** [Leaflet/Leaflet#7966]
example code: https://plnkr.co/edit/baMA0hrGq5XgG8Tb

I have a polygon that gets highlighted on mouseover. inside the polygon there is an icon and a popup bind to it.
The problem is: when I hover over the popup, the polygon's mouseout is triggered, thus its **not highlighted** although the cursor is still inside the polygon, I don't want that to happen

I tried: 
1. using the popup offset method (documented: https://leafletjs.com/reference.html#divoverlay)
2. using a specific css styling to the popup to prevent that

Is there a way to achieve that without using a plugin?

**Comment by IvanSanchez** [comment]
Any reason why you created https://stackoverflow.com/questions/70970960/leaflet-popup-overlaying-polygon-blocks-mouseover-event and then deleted it?

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
