### ISSUE TITLE
// write a click event handler and increment the bounds by [10,10] each click with a few pins, it's terrible

### ISSUE THREAD

**Issue by andrewhodel** [Leaflet/Leaflet#7970]
It's designed to move markers to certain areas and make the map show nothing with the examples saying, use a padding of 50 and them not respecting pixel sizes at any other value.

**Comment by mourner** [comment]
No idea what this means, please use the proposed bug template next time and try to describe your issue with clarity and a minimal live test case.

**Comment by andrewhodel** [comment]
That's not reasonable if you know Javascript.

You don't know what an event handler for the event 'click' is?

You don't know how to increment the values in an array by 10 on each click and apply the function setBounds using that argument?

It's absurd that you request a jsfiddle because the size of the map in that is so small that the bounds cannot be tested in a real usage situation.

**Comment by andrewhodel** [comment]
Do you not understand that this is a real problem?  You need to fix it, not close it.

**Comment by andrewhodel** [comment]
https://github.com/Leaflet/Leaflet/issues/7975

You're one of those guys that likes 90GB downloads huh.

**Comment by jonkoops** [comment]
@andrewhodel please refrain from being so rude to people providing you with free software. As mentioned before you are free to open up a new issue with actual steps to reproduce your problem, or to seek out other software that works better for you.

**Comment by mourner** [comment]
> As mentioned before you are free to open up a new issue with actual steps to reproduce your problem

Not anymore — blocked for violating our [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/). This kind of toxic behavior won't be tolerated in this community.

**Comment by jonkoops** [comment]
Nice, thanks! I was just going through the other issues where he was being very abusive so I was about to suggest the same.
