### ISSUE TITLE
Always getting error mails after push

### ISSUE THREAD

**Issue by Falke-Design** [Leaflet/Leaflet#7974]
After pushing into my repo I recieve a Mail that the worklfow runs in an error. This is because of bundlemon.

![grafik](https://user-images.githubusercontent.com/19800037/152690275-1993d9de-c794-4c10-8383-ca1f2e632598.png)

@jonkoops can we do something, that bundlemon is only running when a PR is made against the Leaflet repo

**Comment by Malvoz** [comment]
@Falke-Design see https://github.com/Leaflet/Leaflet/issues/7946.
