### ISSUE TITLE
setBounds doesn't respect real values for bounds[], it only works with [50,50]

### ISSUE THREAD

**Issue by andrewhodel** [Leaflet/Leaflet#7975]
**Steps to reproduce**

Create a fullscreen map with 4 markers that are each on a different continent.

This cannot be tested in a jsfiddle because the map size is too small.

Create a button with an event handler for the `click` event.  In that handler increment the values in an array by 10 with each click and apply the function `map.setBounds(boundsOfMarkers, [inc10,inc10])`.

Something like:

```
var bound = 0;

btn.addEventListener('click', function() {
  bound += 10;
  map.setBounds(boundsOfMarkers, [bound, bound]);
});
```

**Expected behavior**
You would expect that the bounds grow from 0 by 10 pixels each time, eventually moving all of the markers to a single visual point on an extremely zoomed out map (or whatever the maxZoom is).

**Current behavior**
The setBounds() function will make the markers and map do seemingly random things, at certain bounds it won't show any markers!

**Environment**
- Leaflet version: latest release
- Browser (with version): Chrome 98.0.4758.80 (Official Build) (x86_64)
- OS/Platform (with version): MacOS 12.1

**Comment by mourner** [comment]
You'll have to learn how to communicate respectfully in this community before you can post here again, but meanwhile you can study the docs on the matter closely, which will likely solve your problem: https://leafletjs.com/reference.html#map-fitbounds
