### ISSUE TITLE
Plus and minus  button pressed in form over map causes zoom

### ISSUE THREAD

**Issue by karldevinenetweather** [Leaflet/Leaflet#7981]
I've got a form input type=text floating over the map. If someone presses the plus or minus +- keys while typing in the box the map underneath zooms. 
Would only expect the zoom to occur if map was in focus.
Also need some way of disabling/reenabling the functionality if the form box is not being used as well

**Comment by Malvoz** [comment]
@karldevinenetweather are you able to fill in the bug template? At minimum, can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays the behavior?

**Comment by karldevinenetweather** [comment]
typically can't recreate on the latest version of leaflet so will close this. apologies
