### ISSUE TITLE
leaflet-geoman.min.js:1 Uncaught TypeError: L.PM.Utils._fireEvent is not a function

### ISSUE THREAD

**Issue by MaruschkaScheepers** [Leaflet/Leaflet#7989]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
We are on package 1.6. I have been trying to setup custom panes so that my polylines will always reflect above polygons. On debugging I constantly het this error. 

leaflet-geoman.min.js:1 Uncaught TypeError: L.PM.Utils._fireEvent is not a function
    at i.__fire (leaflet-geoman.min.js:1:53338)
    at i._fireButtonClick (leaflet-geoman.min.js:1:50750)
    at HTMLAnchorElement.<anonymous> (leaflet-geoman.min.js:1:65370)
    at HTMLAnchorElement.s (leaflet.js:5:22769)
__fire @ leaflet-geoman.min.js:1
_fireButtonClick @ leaflet-geoman.min.js:1
(anonymous) @ leaflet-geoman.min.js:1
s @ leaflet.js:5
leaflet-geoman.min.js:1 Uncaught TypeError: L.PM.Utils._fireEvent is not a function
    at i.__fire (leaflet-geoman.min.js:1:53338)
    at i._fireActionClick (leaflet-geoman.min.js:1:50495)
    at i.<anonymous> (leaflet-geoman.min.js:1:64798)
    at HTMLAnchorElement.s (leaflet.js:5:22769)
- ...

**Expected behavior**
Z index op polylinesPane should change

**Current behavior**
Nothing 

**Environment**
- Leaflet version: 1.6
- Browser (with version): Brave
- OS/Platform (with version): Windows 10

**Additional context**
I am a junior developer and new to this , however the error occurs with or without my code adjustments.

**Comment by Falke-Design** [comment]
@MaruschkaScheepers please share your code, else we can't understand what you are doing and what is causing this. 
And please post this issue in the [Leaflet-Geoman](https://github.com/geoman-io/leaflet-geoman) repo, I will help you there.

Have you tested it with Leaflet 1.7.1?
