### ISSUE TITLE
Setting custom markers when markers are defined by layer, not individually?

### ISSUE THREAD

**Issue by chrisjdixon** [Leaflet/Leaflet#7992]
[Already asked at SO](https://stackoverflow.com/questions/71063953/custom-leaflet-markers-when-markers-are-coded-as-a-layer-not-built-individually): how can we customize markers which are set by a layer like so:
```js
async function render_markers() {
const markers = await load_markers();
L.geoJSON(markers)
    .bindPopup((layer) => layer.feature.properties.name)
    .addTo(layerGroup);
}
```
[Leaflet markers documentation](https://leafletjs.com/examples/custom-icons/) doesn't seem to show anything on this either. Can markers be customized with [any of the nice solutions discussed here](https://stackoverflow.com/a/40870439/4107349) when written like this? All solutions seem to define markers manually, eg `L.marker([51.5, -0.09], {icon: greenIcon}).addTo(map);`. How can we set the markers of `L.geoJSON(markers)` to `{icon: greenIcon}`?

I'm new to JS so apologies if this is a stupid JS question but I'm at my wit's end here searching all afternoon not knowing how to figure this out after no response on SO.

**Comment by IvanSanchez** [comment]
Read https://leafletjs.com/examples.html , pal.

**Comment by Falke-Design** [comment]
Answered in SO
