### ISSUE TITLE
request add a circle arc in Leaflet

### ISSUE THREAD

**Issue by www2000** [Leaflet/Leaflet#8005]
**Is your feature request related to a problem? Please describe.**
I working with aviation data and one of the variable is a path that follow a arc that is a part of a circle.

**Describe the solution you'd like**
A function that produce a circle arc.
This can have the same structure as javascript arc.
and looks some thing like this:
arc(latlng,r,sAngle,eAngle,counterclockwise);
r: <float> radiuse of the circle
sAngle: <float> Start of the arc in degrees 
eAngle: <float> End of the arc in degrees
counterclockwise: <bool> If true the line is render counter clockwise else clockwise.

**Describe alternatives you've considered**
This is a basic function and i believe that need be include as a part of Leaflet.

**Additional context**
see info about arc function in html5/javascript canvas
https://www.w3schools.com/tags/canvas_arc.asp

**Comment by simon04** [comment]
You might want to use one of the following [plugins](https://leafletjs.com/plugins.html#markers--renderers):

- https://github.com/MAD-GooZe/Leaflet.Arc
- https://github.com/jjwtay/leaflet.arc

**Comment by jonkoops** [comment]
Personally I think this belongs in a plugin rather than in Leaflet Core. But I am curious if other maintainers think the same.

**Comment by Falke-Design** [comment]
I'm not against adding new features / shapes to Leaflet. This can be also a part of making it more modern. But for now there are existing plugins for this, so I close this.

- https://github.com/jieter/Leaflet-semicircle
- https://github.com/MAD-GooZe/Leaflet.Arc
- https://github.com/jjwtay/leaflet.arc
