### ISSUE TITLE
Taking down the website in support of Ukraine

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#8024]
On one hand, I'll start stating the obvious: @mourner is Ukrainian. As far as I'm aware, he's no longer in Kyiv and is taking his family to safety, for obvious reasons. I count myself among the people worrying about him.

On the other hand: One of the main QGIS folks, Alexander Bruy, is also Ukrainian and has taken down his repository of QGIS plugins, as per https://twitter.com/ealpv/status/1497345048752623616 . QGIS has followed suit with messages of support in the release notes.

I'm thinking on doing just as Alexander has done, and take down the leafletjs.com website (at least temporarily), replacing all content with (a) a message of support to @mourner and his compatriots, (b) a reminder that [international laws and treaties are being violated right now](https://politics.stackexchange.com/questions/71087/did-russia-violate-international-laws-in-ukraine-and-if-so-how), (c) a statement that the safety of Ukrainian civilians is the safety of Leaflet. This would include making the API docs and plugins list inaccessible at first; putting a copy under a different URL and forcing visitors to go through the message. That should be an acceptable balance between this being just a minor inconvenience and full disruption.

Before I use my repo admin powers to make an unilateral decision, I'd like to ping @Falke-Design @ghybs @Malvoz @johnd0e @tomchadwin and take a pulse on what you fellow devs/maintainers think. I'm *assuming* that @mourner would be OK with this, and I'm also assuming he has much bigger concerns right now so he might not be able to pay any attention to Leaflet issues.

**Comment by Falke-Design** [comment]
As long the doc is still available or at least is for a certain time not available, it is ok for me. I would like to support @mourner and all the others👍🏼

**Comment by Malvoz** [comment]
As I'm a fairly new collaborator, I don't know @mourner as well as the rest of you. But, I have a feeling he wouldn't want Leaflet to suffer. I've personally been monitoring events at https://liveuamap.com/ which uses Leaflet. Any open source resource can be used for good or bad, but don't think Leaflet should be made completely inaccessible.

I think forcing users through the message before making available the Leaflet site is a good approach.

**Comment by Malvoz** [comment]
> Would also consider (d) communicating some actionable ways for visitors to actively support, if there are some petitions or trustworthy funding pages? E.g. like https://github.com/denysdovhan/wtfjs#-ukraine-needs-your-help-now

Also https://mobile.twitter.com/Ukraine/status/1497294840110977024

**Comment by IvanSanchez** [comment]
#8025 has been merged.

**Comment by IvanSanchez** [comment]
@Falke-Design @Malvoz @ghybs A brief update: https://twitter.com/mourner/status/1497917517070798851

**Comment by tomchadwin** [comment]
Sorry to have missed the chance to comment. Most of you know @mourner much better than I do, and I think what you've done is entirely appropriate. I'm so pleased Vladimir has seen it. Thanks, all.

**Comment by jonkoops** [comment]
Excellent, as long as resources remain available I fully support this. Slava Ukraini! 🇺🇦

**Comment by oliviertassinari** [comment]
A side note, considering the traffic origne that Leaflet has,

<img width="431" alt="Screenshot 2022-02-28 at 23 05 38" src="https://user-images.githubusercontent.com/3165635/156066482-86db9619-f019-48de-a9d9-af3ba7886e47.png">

and the number of sessions, you could consider displaying small ads, as we do on Material UI's docs. Based on the SimilarWeb data I have, I think that a $3k/month would be a conservative realistic estimation. This could directly fund Ukraine. One idea 🤷‍♂️

**Comment by Falke-Design** [comment]
Maybe we don't change the mindset of the russians but they get confronted with the war:
![grafik](https://user-images.githubusercontent.com/19800037/156990452-c1eb7e3a-9670-41e7-a7c1-8e82be88ce00.png)
https://stackoverflow.com/q/71377758/8283938

**Comment by IvanSanchez** [comment]
@Falke-Design While I'll reckon that there might be room for a (very very complex) moral and political discussion, and that things are never perfectly black and white, I'll say that *right now* the attention should be put on the UN resolutions, the targeting on civilian facilities, and the alleged war crimes.

Choosing to selectively ignore those issues as a trolling technique is... amateurish, at best.

**Comment by mourner** [comment]
Don't mind the brainwashed Russians, there's no way of saving them. Ukrainians have 8 years of experience arguing with the likes. Complete waste of time.

**Comment by ikokostya** [comment]
https://waronfakes.com/
