### ISSUE TITLE
No fullscreen control??

### ISSUE THREAD

**Issue by php4fan** [Leaflet/Leaflet#8031]
Google Maps has a `fullScreenControl` option out of the box (for the map object). When set to true, it ads a fullscreen control, i.e. a fullscreen button that puts the map in fullscreen mode.

I can't find any such thing in Leaflet.

**Comment by IvanSanchez** [comment]
Look in the plugins list.

**Comment by Keelando** [comment]
For anyone else coming here, [here it is](https://github.com/Leaflet/Leaflet.fullscreen)
