### ISSUE TITLE
After clicking in the map and routing to another page using the useHistory hook textareas and inputs won't accept the letters, ^+-6= in safari

### ISSUE THREAD

**Issue by john-sausby** [Leaflet/Leaflet#8034]
After clicking in the map and routing to another page using the useHistory hook textareas and inputs won't accept the letters, ^+-6= in safari

**Steps to reproduce**

1. go to https://bymelding.no/
2. click 'Meld sak'
3. choose 'Badeplass'
4. click on 'Brygge/badetrapp'
5. click anywhere on the map in the Oslo area
6. click 'Meld inn feil'
7. scroll down to the 'Beskrivelse' textarea and try to type the number '6'

**Expected behavior**

All characters work in inputs after routing in inputs after click on the map in safari.

**Current behavior**

Nothing happens. Additional to that all the inputs and textareas now have the same issue, if you try to log in or go back to the start the inputs wont accept a some charaters, until a full refresh is performed.

**Environment**
- Leaflet version: 1.7.1
- Browser (with version): Safari both mobile and desktop
- OS/Platform (with version): iOS and MacOS

**Additional context**

I do a panto on click like this `map.panTo([e.latlng.lat, e.latlng.lng]);` when the user clicks on the map

**Comment by john-sausby** [comment]
I found the issue, I created a codesandbox where the actions were  the same as my solution, but it worked as expected, I checked the package versions I was using in my solution v the versions I had in my codesandbox and I had v3.1.0 in my solution and 3.2.5 in my codesandbox. I assume therefore this is only an issue before 3.2.4 as I have a maphandler in my code.
________________________________

**Comment by Malvoz** [comment]
@john-sausby I don't understand your last comment. Can you please clarify if this is (still) an issue with Leaflet, or was it an issue with your application that was resolved?

If you're still seeing this issue:

> Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?

**Comment by john-sausby** [comment]
this is not currently an issue with leaflet. I was using an older version of leaflet where this was the issue.
________________________________

**Comment by Falke-Design** [comment]
@john-sausby thank you for your response
