### ISSUE TITLE
Support alpha/beta NPM dist tags when publishing through Github Actions

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#8038]
Currently our Github Actions are set up so that we do `npm publish` which assigns `latest` NPM tag by default, regardless whether the version is stable (`v1.8.0`) or not (e.g. `v1.8.0-alpha.1`, `v1.8.0-beta.1`). We should parse out the word that comes after the version (e.g. `beta`) in the publish action, and use it as a tag if present (and otherwise `latest`). `npm publish --tag <tag>`. cc @jonkoops

**Comment by mourner** [comment]
Came up with a solution, will try it out now.

**Comment by jonkoops** [comment]
Awesome, feel free to add me as a reviewer @mourner

**Comment by mourner** [comment]
@jonkoops ready for review at https://github.com/Leaflet/Leaflet/pull/8039
