### ISSUE TITLE
Flaky CI tests on IE10

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#8041]
Currently IE10 tests on CI are flaky, failing the build very often. In particular, this test:

> IE 10.0 (Windows 10) TileLayer number of kittens loaded Loads 290, unloads 275 kittens on MAD-TRD flyTo() FAILED

We should investigate which tests are flaky, and either make them more robust, or introduce some kind of retry logic specifically for these tests on IE.

**Comment by jonkoops** [comment]
We might consider to simply drop IE10 from the test suite, I cannot even get it to list it's market share in [StatCounter](https://gs.statcounter.com/browser-version-partially-combined-market-share/desktop/worldwide/#monthly-202103-202202-bar) anymore.
