### ISSUE TITLE
Map drilling

### ISSUE THREAD

**Issue by chengjunjian2020** [Leaflet/Leaflet#8043]
How to realize map drilling

Is scaling used directly

I see a similar in the official website tutorial

https://leafletjs.com/SlavaUkraini/examples/choropleth/

![image](https://user-images.githubusercontent.com/40468022/157415427-745c950e-1986-4fae-9629-c8b96dcdb64d.png)

**Comment by mourner** [comment]
What do you mean by drilling? Can you describe what you expect to see and what you see instead?

**Comment by chengjunjian2020** [comment]
https://developer.amap.com/demo/loca-api/demos/districtlayer/loca_district_drilldown
[](https://fanyi.baidu.com/###)[](javascript:void(0);)
For example, after clicking Chongqing, it will automatically jump to all districts, counties and cities
Click the run button of the source code editor to see the test effect

**Comment by mourner** [comment]
I don't understand what's the issue as adding zoom in on click is described in the tutorial above, but in any case, this is not the place to ask for help with your app. It's for reporting issues with Leaflet itself. So closing.
