### ISSUE TITLE
Markers do not render: 403 Forbidden on cloudfront.net

### ISSUE THREAD

**Issue by SimonCoulombe** [Leaflet/Leaflet#8069]
Hi!
I am on a fresh install of Linux Mint and I can't display markers on a leaflet map. 

 Here is what I get when trying to run the [example code from Rstudio](https://rstudio.github.io/leaflet/)

**Steps to reproduce**
```
library(leaflet)
m <- leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=174.768, lat=-36.852, popup="The birthplace of R")
m
```
**Expected behavior**
I expect to get a map with a marker showing "the birthplace of R".

**Current behavior**
No marker appears.  If I guess where it is and click, the text pops up.
In my firefox browser I get a transparent square where the marker should be.  
Checking the consoles shows that I got a 403 Forbidden error when trying to download these two files:  
* https://d19vzq90twjlae.cloudfront.net/leaflet/v1.3.1/images/marker-icon-2x.png  
* https://d19vzq90twjlae.cloudfront.net/leaflet/v1.3.1/images/marker-shadow.png  

**Environment**
- Leaflet version:  2.1.0
- Browser (with version):  Mozilla Firefox for Linux  Mint 98.0.1
- OS/Platform (with version): Linux Mint 20.3  
- Rstudio 2022.02.0 build 443  
- R 4.1.3   
```

> sessioninfo::session_info()
─ Session info ────────────────────────────────────────────
 setting  value
 version  R version 4.1.3 (2022-03-10)
 os       Linux Mint 20.3
 system   x86_64, linux-gnu
 ui       RStudio
 language en_CA
 collate  en_CA.UTF-8
 ctype    en_CA.UTF-8
 tz       America/Toronto
 date     2022-03-15
 rstudio  2022.02.0+443 Prairie Trillium (desktop)
 pandoc   NA

─ Packages ────────────────────────────────────────────────
 package     * version date (UTC) lib source
 cli           3.2.0   2022-02-14 [1] CRAN (R 4.1.3)
 crosstalk     1.2.0   2021-11-04 [1] CRAN (R 4.1.3)
 digest        0.6.29  2021-12-01 [1] CRAN (R 4.1.3)
 fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.1.3)
 htmltools     0.5.2   2021-08-25 [1] CRAN (R 4.1.3)
 htmlwidgets   1.5.4   2021-09-08 [1] CRAN (R 4.1.3)
 jsonlite      1.8.0   2022-02-22 [1] CRAN (R 4.1.3)
 leaflet     * 2.1.0   2022-02-16 [1] CRAN (R 4.1.3)
 magrittr      2.0.2   2022-01-26 [1] CRAN (R 4.1.3)
 R6            2.5.1   2021-08-19 [1] CRAN (R 4.1.3)
 rlang         1.0.2   2022-03-04 [1] CRAN (R 4.1.3)
 sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.1.3)
 yaml          2.3.5   2022-02-21 [1] CRAN (R 4.1.3)

 [1] /home/simon/R/x86_64-pc-linux-gnu-library/4.1
 [2] /usr/local/lib/R/site-library
 [3] /usr/lib/R/site-library
 [4] /usr/lib/R/library
```
**Additional context**

Here's a screenshot with everything discussed.
![Screenshot from 2022-03-15 23-38-16](https://user-images.githubusercontent.com/23444900/158513055-0db67814-9665-40ec-bbfb-a50dfdfb6f96.png)

**Comment by IvanSanchez** [comment]
This is the bugtracker for Vanilla JS leaflet, not for the R integration. Note that the current version of Leaflet is 1.8.0-beta.0, and not 2.1.0 (that's the R integration).

The bugracker you're looking for is at https://github.com/rstudio/leaflet .

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* NativeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.

**Comment by SimonCoulombe** [comment]
Oh, I totally understand, my bad.
