### ISSUE TITLE
polylines and intersections

### ISSUE THREAD

**Issue by rittjom** [Leaflet/Leaflet#8070]
**Is your feature request related to a problem? Please describe.**
There is a big problem when encountering intersections when painting polylines. It is not clear whether the polyline leads to the left, to the right or straight ahead.
Google Maps solved this problem very elegantly (see my screenshot). The route itself has a small border. So you can see exactly where the route leads.

**Describe the solution you'd like**
You should clearly see in which direction the polylines lead. Of course, it would be best if it looked like this on google maps.

I know this is probably not that easy to solve because the browser's native polyline painting routines are being used.
But maybe someone else will come up with a very good idea.

![leaflet_gmaps](https://user-images.githubusercontent.com/13555220/158571834-59b5efac-2c39-4659-a253-af5af1ac21c6.png)

PS: First draw a thicker polyline and then a thinner one over it does not lead to the desired result. Because the polylines are painted as a whole.

**Comment by IvanSanchez** [comment]
> First draw a thicker polyline and then a thinner one over it does not lead to the desired result. 

Works for me: https://plnkr.co/edit/pAb78OnE5N1yN56Y

> Because the polylines are painted as a whole.

No, the polylines are not painted as a whole; each one has a separate SVG element or canvas drawing operation, and both of those respect the drawing order (a bit of info about SVG [here](https://stackoverflow.com/questions/17786618/how-to-use-z-index-in-svg-elements))

**Comment by rittjom** [comment]
> > First draw a thicker polyline and then a thinner one over it does not lead to the desired result.
> 
> Works for me: https://plnkr.co/edit/pAb78OnE5N1yN56Y
> 
> > Because the polylines are painted as a whole.
> 
> No, the polylines are not painted as a whole; each one has a separate SVG element or canvas drawing operation, and both of those respect the drawing order (a bit of info about SVG [here](https://stackoverflow.com/questions/17786618/how-to-use-z-index-in-svg-elements))



Your example does not correspond to usage in the real world.
A route consists of thousands of coordinates. I cannot split these into individual polyline arrays with two elements.

Here is your example extended to a simple "route" of four points.

https://plnkr.co/edit/rtYjZ0IWecKcGxPP

**Comment by rittjom** [comment]
> > I cannot split these into individual polyline arrays with two elements.
> 
> Yes you can.

you mean like this?
https://plnkr.co/edit/rtYjZ0IWecKcGxPP

**Comment by hash-rabbit** [comment]
> > > I cannot split these into individual polyline arrays with two elements.
> > 
> > 
> > Yes you can.
> 
> you mean like this? https://plnkr.co/edit/rtYjZ0IWecKcGxPP

LGTM
