### ISSUE TITLE
fitBounds is broken in 2.1.0

### ISSUE THREAD

**Issue by csiro-chris-m** [Leaflet/Leaflet#8072]
fitBounds in v. 2.1.0 only accepts actual values for the extents (eg lat1 = 10). Any attempt at using variables causes exception. Rolling back to 2.0.3 fixes it.

**Comment by IvanSanchez** [comment]
@Falke-Design I suspect Leaflet for R - see how https://github.com/Leaflet/Leaflet/issues/8069 reports using version 2.1.0

**Comment by csiro-chris-m** [comment]
Yes, leafet for R.


Chris Moeseneder

Senior Experimental Scientist
Oceans and Atmosphere  |  CSIRO

***@***.******@***.***>  |  07 3833 5946  |  0468 932 499

Queensland Bioscience Precinct, 306 Carmody Road, St Lucia, Qld 4067, Australia

[cid:04d6e3f8-314a-45e6-ac9d-85562c0875c4]

CSIRO Australia’s National Science Agency  |  csiro.au

________________________________

**Comment by IvanSanchez** [comment]
@csiro-chris-m Then the answer is the same as in https://github.com/Leaflet/Leaflet/issues/8069 .

**Comment by csiro-chris-m** [comment]
Alright. I hope you find the resources to support some of the other platforms. As nice as leaflet is, I can't roll out software if I'm stuck at a specific version.

________________________________
