### ISSUE TITLE
Chrome out of memory: Large number of polygons

### ISSUE THREAD

**Issue by iisri-vu** [Leaflet/Leaflet#8075]
**Environment**
- Leaflet version:   1.7.1
- Browser (with version):   Chrome, MS Edge any version

- OS/Platform (with version):  Windows 10

**Additional context**
Chrome, Edge will crash with an out-of-memory error when rendering lots of simple polygons e.g. 1million simple polygons.

**Minimal example reproducing the issue**
Go to:   https://jsfiddle.net/newluck77/jsoghrz4/

Paste the following code inside the Javascript window and click on run.

for (i = 0; i < 1000000; ++i)
{
var latlngs = [
        [37.786617, -122.404654],
        [37.797843, -122.407057],
        [37.798962, -122.398260],
        [37.794299, -122.395234]];
        
const polygon = L.polygon(latlngs, {color: 'red'}).addTo(map);

}

**Comment by IvanSanchez** [comment]
Won't fix - one million polygons means one million SVG elements in the DOM, and there's pretty much no way around that. Using `L.Canvas` might alleviate the issue, but it's still one million instances and one million draw calls.

This is a variant of the old "help, my browser is slow when I load 100000 markers" issue, which is the same but with non-SVG, HTML elements in the DOM.

**Comment by iisri-vu** [comment]
Is there a batch draw option? so that 1 million polygons can be drawn in 1 call?

**Comment by IvanSanchez** [comment]
> Is there a batch draw option? so that 1 million polygons can be drawn in 1 call?

That would be a multipolygon with **a lot** of outer hulls. The memory usage concern would be the same.
