### ISSUE TITLE
Dragging map returns map position to initial point

### ISSUE THREAD

**Issue by xavidram** [Leaflet/Leaflet#8076]
![e0aa08dc-7aaf-11e6-9e64-60a567603825](https://user-images.githubusercontent.com/1348719/159149635-f514ccf3-73ff-45a2-9726-824d3cd9bdcd.gif)

- [ x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [ ] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [ x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- step 1
- step 2
- ...

**Expected behavior**
When dragging across the leaflet map, the map moves.

**Current behavior**
Dragging the map causes the map to return to the initial position.

**Environment**
- Leaflet version: 1.7.1
- Browser (with version): Chrome
- OS/Platform (with version): Windows 10 1109

**Additional context**
This same issue has occurred before. If I remember correctly, back in leaflet pre v1.0.0 there used to be an `animate` boolean we could disable when creating the map. Only the `Zoom Control` and `Pan Control` have the animate option. This issue is caused by zone.js in angular as specified in the issue below. 
https://github.com/Leaflet/Leaflet/issues/4588#issuecomment-221424763

Has the animate Boolean been remove from the leaflet map initialization method all together?

EDIT: 

https://github.com/xavidram/LeafletRubberband

You can clone that sample to reproduce the issue.

**Comment by jonkoops** [comment]
Please provide a minimal reproducible example with steps to reproduce the issue.

**Comment by xavidram** [comment]
@jonkoops updated my initial answer. At the bottom you will see a repo with the reproducible example.

**Comment by IvanSanchez** [comment]
That's using angular. That's not a *minimal* example with vanilla Leaflet.

**Comment by IvanSanchez** [comment]
There's an `animate` option for the map in the 1.7.1 documentation.

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* NativeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.

**Comment by xavidram** [comment]
Just wanted to place a comment here. Figured out the issue. This is due to zone.js and how it handles change detection. All events in angular that need to be handled independently should be handled outsize of zone.js like the library ngx-leaflet. The use of [mapbox-gl-leaflet](https://github.com/mapbox/mapbox-gl-leaflet) and how it handles events caused the rubberbanding. Hope this helps anyone else who stumbles upon this issue.
