### ISSUE TITLE
Leaflet Marker Dragging enabled automatically after setIcon

### ISSUE THREAD

**Issue by SatishKumarPrajapati** [Leaflet/Leaflet#8077]
Leaflet Marker Dragging enabled automatically after setIcon
I am using leaflet 1.7.1 with my react application.
I am using leaflet marker with custom HTML with setIcon. I have disabled dragging disabled but sometimes marker dragging is enabled automatically and this is happening randomly. 
Marker dragging is not enabled all times but it happens randomly.
Marker & markerSetIcon is rendering dynamically on the basis of react application state.

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* NativeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.

**Comment by IvanSanchez** [comment]
If this is reproducible without any React stuff, I'd consider reopening. But I heavily suspect there's React shenanigans involved here.
