### ISSUE TITLE
CSS `scroll-padding-top` should only apply to reference.html

### ISSUE THREAD

**Issue by Malvoz** [Leaflet/Leaflet#8080]
I believe `scroll-padding-top`:

https://github.com/Leaflet/Leaflet/blob/7419c9c30e568db7751f820f73f27bbaac7f6cb4/docs/docs/css/main.css#L12-L13

is only used for sticky headings in reference.html, and should be scoped to that document (i.e. move the property to [`reference.css`](https://github.com/Leaflet/Leaflet/blob/main/docs/docs/css/reference.css)).

Example of the bug (too large padding top after visiting): https://leafletjs.com/SlavaUkraini/examples/quick-start/#setting-up-the-map

**Comment by Malvoz** [comment]
Fixed in https://github.com/Leaflet/Leaflet/issues/8080.

Thank you for the contribution @wyankush!

**Comment by wyankush** [comment]
Welcome!
