### ISSUE TITLE
popup cannot pop up 

### ISSUE THREAD

**Issue by MrCactusX** [Leaflet/Leaflet#8082]
**Graphics bound to events cannot pop up pop-up boxes**
The pop-up box event is bound to my graph. The pop-up box can pop up when I click it for the first time, but it cannot pop up when I click it again. I don't know why, can you tell me this problem

The English is not very good, maybe the description is not very clear, sorry!!!

leaflet version：1.7.0

```
 const popup = L.popup();
    GraphLayer.pointGraphicLayer.on("graphicsadd", function (e: any) {
      for (const iterator of e.Graphic) {
        iterator.on("click", (element: any) => {
          const item = iterator.getAttribute().type;
          mapModel.setHightLight(item, GraphLayer.flickerGraphicLayer);
          mapStore.changeClickYxgtInfo(item);
          console.log(item);
          // 开关类设备弹窗
          if (item.condition && item.condition.indexOf("kgzt") > -1) {
            popup
              .setLatLng([element.latlng.lat, element.latlng.lng])
              .setContent("例子")
              .openOn(map);
          }
        });
      }
    });
```

**Comment by IvanSanchez** [comment]
This is a problem with either your logic, or with the graphlayer stuff. This is not a bug in Leaflet.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
