### ISSUE TITLE
Polyline moves on pan / zoom

### ISSUE THREAD

**Issue by adam-lynch** [Leaflet/Leaflet#8089]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
1. Draw a polyline over a street
1. Zoom in close
1. Pan

**Expected behavior**
The polyline moves in sync with the map.

**Current behavior**

The polyline moves but out of sync with the map

![](https://user-images.githubusercontent.com/1427241/160274004-0f4fcc04-73cf-41ab-ad7e-48d8c02bda42.gif)

**Environment**
- Leaflet version: 1.7.1
- Browser (with version): Chrome 99.0.4844.83 (Official Build) (arm64)
- OS/Platform (with version): macOS 12.2.1

**Additional context**

I made some simple examples (based on MapTiler's examples):

- [Leaflet Mapbox GS](https://codepen.io/adam-lynch/pen/gOomJyb/61b76d8c96e9ae4aa2c5893f51bc6655). Broken ❌
- [MapLibre GS (no Leaflet)](https://codepen.io/adam-lynch/pen/XWVMwwq/738600ed462c3af4fba7301fe9ecf796). Works ✅, Note: this uses a simpler `LineString`.
- [Leaflet MapLibre GS](https://codepen.io/adam-lynch/pen/gOomNQW/a041444adf315c289e0bc2a3e316947d). Broken ❌

I couldn't quickly make an example without GS because the map tiles were gray when I zoomed in that far 🤷

(Original issue: https://github.com/adam-lynch/back-of-your-hand/issues/38)

**Minimal example reproducing the issue**

[Leaflet + Mapbox GS](https://codepen.io/adam-lynch/pen/gOomJyb/61b76d8c96e9ae4aa2c5893f51bc6655)

- [x] this example is as simple as possible
- [ ] this example does not rely on any third party code

**Comment by IvanSanchez** [comment]
Adding a debug tilelayer shows me that Leaflet is behaving properly - dragging the map moves the polyline as well as the tilelayer with no offset.

The issue might be at the leaflet-mapboxgl integration. Stuff was never designed to work reliably at zoom level 24 and further, anyway.

**Comment by adam-lynch** [comment]
Thanks for the quick reply. I'll go log an issue there. It's also broken when using MapLibre rather than Mapbox but as far as I know the MapLibre integration was forked from the Mapbox one so that could explain it.
