### ISSUE TITLE
HI i am using flutterMap that is inspired by leaflet. How can i get "moveend" event in flutter. I need a callback when user DragEnds/ScaleEnds/ZoomEnds on all these

### ISSUE THREAD

**Issue by UsamaAndroid** [Leaflet/Leaflet#8092]
Flexible(
                  child: GestureDetector(
                    // onHorizontalDragEnd: (t){print('here i am hshdsh');},
                    onScaleEnd: (t){print('here i am pan end');},
                    child:  FlutterMap(
                        mapController: widget.mapController,
                        options: MapOptions(
                          allowPanningOnScrollingParent: true,
                          controller: widget.mapController,
                          interactiveFlags: InteractiveFlag.doubleTapZoom |
                              InteractiveFlag.pinchZoom |
                              InteractiveFlag.drag |
                              InteractiveFlag.flingAnimation,
                          center: LatLng(33.680088056393814, 72.7987044426807),
                          zoom: AppVariables.defaultZoom,
                          minZoom: AppVariables.minZoom,
                          maxZoom: AppVariables.maxZoom,
                          slideOnBoundaries: true,
                          adaptiveBoundaries: true,
                          swPanBoundary: LatLng(
                              AppVariables.swPanLat, AppVariables.swPanLng),
                          nePanBoundary: LatLng(
                              AppVariables.nePanLat, AppVariables.nePanLng),
                          screenSize: MediaQuery.of(context).size,
                          onTap: (tapPosition, latLng) async {
                            popupLayerController.hideAllPopups();
                            if (widget.index != 3) {
                              widget.gpd!.isLoading.value = true;
                              _handleTap(latLng);
                              _animatedMapMove(latLng, widget.mapController.zoom);
                              final bounds = widget.mapController.bounds;
                              var bbox =
                                  '${bounds!.southWest!.longitude},${bounds.southWest!.latitude},${bounds.northEast!.longitude},${bounds.northEast!.latitude}';
                              widget.gpd!
                                  .fetchProductData(
                                      bbox: bbox,
                                      width: MediaQuery.of(context)
                                          .size
                                          .width
                                          .toInt(),
                                      height: MediaQuery.of(context)
                                          .size
                                          .height
                                          .toInt(),
                                      x: tapPosition.global.dx.ceil(),
                                      y: tapPosition.global.dy.ceil(),
                                      srs: 'EPSG:4326')
                                  .then((value) {
                                if (this.mounted) {
                                  if (widget.gpd!.isError.value) {
                                    showSnack(
                                        message:
                                            '${widget.gpd!.error.value.totalFeatures} place');
                                  }
                                }
                              });
                            }
                          },
                          onMapCreated: (s){},
                          onPositionChanged: (p,o) {
                          // Fill your stream when your position changes
                          print('xxxxxxxxxxxxxxx1 $o');
                          final zoom = p.zoom;
                          if (zoom != null) {
                            _streamController.sink.add(zoom);
                          }
                          // if(o){
                          //   print('xxxxxxxxxxxxxxx1 $o');
                          // }else{                            print('xxxxxxxxxxxxxxx1 $o');
                          // }
                        },
                          plugins: [
                            ScaleLayerPlugin(),
                          ],),
                        nonRotatedLayers: [
                          ScaleLayerPluginOption(
                            lineColor: Colors.blue,
                            lineWidth: 2,
                            textStyle:
                                TextStyle(color: Colors.blue, fontSize: 12),
                            padding: EdgeInsets.all(10),
                            gpd: widget.gpd
                          ),
                        ],
                        nonRotatedChildren: childLayerz,
                      ),

                  ),
                ),

**Comment by mourner** [comment]
This is a place for reporting Leaflet issues. Please use StackOverflow for asking help with your app.

**Comment by UsamaAndroid** [comment]
> Flexible( child: GestureDetector( // onHorizontalDragEnd: (t){print('here i am hshdsh');}, onScaleEnd: (t){print('here i am pan end');}, child: FlutterMap( mapController: widget.mapController, options: MapOptions( allowPanningOnScrollingParent: true, controller: widget.mapController, interactiveFlags: InteractiveFlag.doubleTapZoom | InteractiveFlag.pinchZoom | InteractiveFlag.drag | InteractiveFlag.flingAnimation, center: LatLng(33.680088056393814, 72.7987044426807), zoom: AppVariables.defaultZoom, minZoom: AppVariables.minZoom, maxZoom: AppVariables.maxZoom, slideOnBoundaries: true, adaptiveBoundaries: true, swPanBoundary: LatLng( AppVariables.swPanLat, AppVariables.swPanLng), nePanBoundary: LatLng( AppVariables.nePanLat, AppVariables.nePanLng), screenSize: MediaQuery.of(context).size, onTap: (tapPosition, latLng) async { popupLayerController.hideAllPopups(); if (widget.index != 3) { widget.gpd!.isLoading.value = true; _handleTap(latLng); _animatedMapMove(latLng, widget.mapController.zoom); final bounds = widget.mapController.bounds; var bbox = '${bounds!.southWest!.longitude},${bounds.southWest!.latitude},${bounds.northEast!.longitude},${bounds.northEast!.latitude}'; widget.gpd! .fetchProductData( bbox: bbox, width: MediaQuery.of(context) .size .width .toInt(), height: MediaQuery.of(context) .size .height .toInt(), x: tapPosition.global.dx.ceil(), y: tapPosition.global.dy.ceil(), srs: 'EPSG:4326') .then((value) { if (this.mounted) { if (widget.gpd!.isError.value) { showSnack( message: '${widget.gpd!.error.value.totalFeatures} place'); } } }); } }, onMapCreated: (s){}, onPositionChanged: (p,o) { // Fill your stream when your position changes print('xxxxxxxxxxxxxxx1 $o'); final zoom = p.zoom; if (zoom != null) { _streamController.sink.add(zoom); } // if(o){ // print('xxxxxxxxxxxxxxx1 $o'); // }else{ print('xxxxxxxxxxxxxxx1 $o'); // } }, plugins: [ ScaleLayerPlugin(), ],), nonRotatedLayers: [ ScaleLayerPluginOption( lineColor: Colors.blue, lineWidth: 2, textStyle: TextStyle(color: Colors.blue, fontSize: 12), padding: EdgeInsets.all(10), gpd: widget.gpd ), ], nonRotatedChildren: childLayerz, ),
> 
> ```
>               ),
>             ),
> ```

I am done with it thanks
