### ISSUE TITLE
Cover vector drift issue with tests

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#8117]
https://github.com/Leaflet/Leaflet/pull/8103 fixes a long-standing issue with vector drift on pinch zoom, but a test designed for it (from https://github.com/Leaflet/Leaflet/pull/7965) fails to reflect what happens in practice for some reason (quoting @Falke-Design):

> The best would be, if you checkout my PR #7965 and look what visually happens in my test.
> 
> 1. Go into Map.TouchZoomSpec
> 2. Comment out Line 15 `removeMapContainer(map, container);`
> 3. Go to [Line 65](https://github.com/Falke-Design/Leaflet/blob/205395d41ce70f94a1d5e57e6065b786285a2ca4/spec/suites/map/handler/Map.TouchZoomSpec.js#L65) and add `.only`
> 4. Replace `fastframe` with `frame` in [line 78](https://github.com/Falke-Design/Leaflet/blob/205395d41ce70f94a1d5e57e6065b786285a2ca4/spec/suites/map/handler/Map.TouchZoomSpec.js#L78)
> 5. If you then run the tests in the browser over the `spec/index.html` you see that the rectangle is still in the center while / after zooming. With your (this) PR the rectangle is moving away while zooming.

![rectangle_pinch](https://user-images.githubusercontent.com/19800037/161381712-1ed82dbe-0ce6-4776-9a2c-ddb7c5699f8e.gif)

We need to figure out why it fails and cover this properly. Creating a separate issue because I want to leave this as a follow up and merge the fix.

**Comment by stephenspol** [comment]
Is #7407 related?

**Comment by JohnGrisham** [comment]
I can take a look at this, would you be willing to assign me?
