### ISSUE TITLE
map.fitBounds throws: Invalid LatLng object: (NaN, NaN), but flyToBounds works well with the same bounds

### ISSUE THREAD

**Issue by carlshe** [Leaflet/Leaflet#8124]
I faced to the same issue as #5015 : https://github.com/Leaflet/Leaflet/issues/5015.

I happened to this issue with version 1.7.1, and then moved to 1.8.0 beta 1, but it still is there. 

I checked the bounds and feel it was well provided. This problem occurs in random. With the same bounds sometime it works well, sometime not. And then I changed the call from map.fitBounds to map.flyToBounds, it worked very well. But I don't like the animation so I prefer to fitBounds.

The code is as follow:
function FitToLayer(layer)
{
	if (layer==null)return;
	let ok=false;
	console.log('fit layer begin:');
	try{  
		let bounds = layer.getBounds();
		console.log(layer);
		console.log(bounds);
		TDMap.fitBounds(bounds); 
                ok=true; 
	}
	catch(err){ 
                ok=false; 
                console.log(err);
        }
	
	console.log('fit end:' + ok);
}

The detailed message is:
Error: Invalid LatLng object: (NaN, NaN)
    at new v (VM130 leafletFull.js:5:7120)
    at i.wrapLatLngBounds (VM130 leafletFull.js:5:13519)
    at i.wrapLatLngBounds (VM130 leafletFull.js:5:36694)
    at i._cellCoordsToBounds (VM130 leafletFull.js:3750:43919)
    at i._removeCell (VM130 leafletFull.js:3750:44206)
    at i._pruneCells (VM130 leafletFull.js:3750:40289)
    at i._setView (VM130 leafletFull.js:3750:41243)
    at i._resetView (VM130 leafletFull.js:3750:41023)
    at i.fire (VM130 leafletFull.js:5:5499)
    at i._resetView (VM130 leafletFull.js:5:38771)
	
	v	@	VM130 leafletFull.js:5
	wrapLatLngBounds	@	VM130 leafletFull.js:5
	wrapLatLngBounds	@	VM130 leafletFull.js:5
	_cellCoordsToBounds	@	VM130 leafletFull.js:3750
	_removeCell	@	VM130 leafletFull.js:3750
	_pruneCells	@	VM130 leafletFull.js:3750
	requestAnimationFrame(asynchronous)		
	x	@	VM130 leafletFull.js:5
	_createCell	@	VM130 leafletFull.js:3750
	_update	@	VM130 leafletFull.js:3750
	_onMoveEnd	@	VM130 leafletFull.js:3750
	r	@	VM130 leafletFull.js:5
	fire	@	VM130 leafletFull.js:5
	_move	@	VM130 leafletFull.js:5
	_resetView	@	VM130 leafletFull.js:5
	setView	@	VM130 leafletFull.js:5
	fitBounds	@	VM130 leafletFull.js:5

**Comment by IvanSanchez** [comment]
There's `_cellCoordsToBounds` in the error stack, which tells me that you're using esri-leaflet.

**Comment by carlshe** [comment]
Thanks! yes, you're right.
It should be of esri-leaflet. If map zoomed, the esri layer responded with mistake in random. If I switched esri layer off, it became ok.
