### ISSUE TITLE
Export Leaflet Layer as ESRI Shapefile

### ISSUE THREAD

**Issue by clavijojuan** [Leaflet/Leaflet#8126]
Hi, i have been trying along of time to export a leaflet layer as Esri Shapefile but I have not succeeded.

 I tried to use this [library ](https://github.com/mapbox/shp-write) but it doesn't works. So, i want to ask if is possible to add this feature or someone can help me.

Thanks

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
