### ISSUE TITLE
Popup should have a min-height

### ISSUE THREAD

**Issue by Falke-Design** [Leaflet/Leaflet#8131]
The close button overflows the popup container if the container is empty:

![grafik](https://user-images.githubusercontent.com/19800037/162693049-187cd57f-6e05-4ab6-af11-6f83da77e72c.png)

```
var marker = new L.Marker(latlng).addTo(map);
marker.bindPopup("");
```

**Comment by Falke-Design** [comment]
Hi @MassiGy,

thank you for your suggestion but it should be a "static" value in the leaflet.css file. 

The problem with your approach is that it needs to be explicit set, which will result in not adding the option because normally a popup has content and then the option `minHeight` is not needed. And if then the case happens that it has no content, the option `minHeight` is not set.

**Comment by Malvoz** [comment]
@MassiGy You could utilize the [`:empty`](https://developer.mozilla.org/en-US/docs/Web/CSS/:empty) pseudo-class. Also, the `min-height` doesn't have to be that excessive. Use the smallest `min-height` that would fix the issue.

@Falke-Design Is it really necessary to fix this? Seems like an enhancement for development only. If popups are empty in production that's the wrong use of a popup.

**Comment by Falke-Design** [comment]
It's not important but I think it would be good to have it, because it is clearly an UI topic which comes from Leaflet.

**Comment by ansh-ag** [comment]
Looks like a straight forward change, picking this up guys.
