### ISSUE TITLE
`data-` prefix `anchor` attribute in docs

### ISSUE THREAD

**Issue by Malvoz** [Leaflet/Leaflet#8137]
The OpenUI is working on standardizing popups for the web, and they're proposing an [`anchor`](https://open-ui.org/components/popup.research.explainer#anchoring-the-anchor-attribute) attribute.

It'd be best to [`data-`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*) prefix the "custom" attribute:

https://github.com/Leaflet/Leaflet/blob/c94faa201a916fbf48e30156179d78ab5620d2d5/docs/SlavaUkraini/docs/js/reference.js#L10

**Comment by KnightJam1** [comment]
Hi, @Malvoz could I help with this?

**Comment by Malvoz** [comment]
@KnightJam1 Is this not a suitable place for discussion? Also, before getting started, have you read [Contributing to Leaflet](https://github.com/Leaflet/Leaflet/blob/main/CONTRIBUTING.md)?

**Comment by KnightJam1** [comment]
Hi again, I've looked into data-* attributes, anchors and Element.setAttribute(), and have made a change (renaming 'anchor' to 'data-anchor') to try and solve the issue, but I'd like to test how it works. Following the guidance in CONTRIBUTING.md, I have run npm test, npm run rollup and looked at spec/index.html, however I'm not sure if these tests are testing the anchor script. Do you know how I might test it before staging any changes?
Thanks again!

**Comment by Malvoz** [comment]
@KnightJam1 The attribute is only used in the documentation at `reference.html`, so you'll only need to follow the [Improving documentation](https://github.com/Leaflet/Leaflet/blob/main/CONTRIBUTING.md#improving-documentation) steps. After making the change you can simply inspect the DOM of the document locally, using the "Elements" tab in your browser's devtools, to see if the change is reflected in that document.

**Comment by KnightJam1** [comment]
Thank you very much for the help! I've followed the steps, and it all seems to be working fine, as expected. I've staged the changes, but discovered I have a newer version of Karma. Should I install the older version to prevent merge conflicts?

**Comment by Falke-Design** [comment]
Yes use the same version as we have defined in the `package.json`. The `package.json` should not be changed (so revert it, if you changed it) and then run `npm install`. Then you should have the same version installed as Leaflet uses.

**Comment by KnightJam1** [comment]
Great, thanks!

**Comment by KnightJam1** [comment]
This worked, now only the reference.js file will be changed!
I will commit this and then submit a pull request, unless I missed a step?
Thank you very much for the help and guidance, and have a lovely day!

**Comment by Falke-Design** [comment]
Please don't generate / commit the `reference.html` file. This is done before publishing a release
