### ISSUE TITLE
Issues with loading and viewing `openstreetmap` tiles : Failed to load resource: the server responded with a status of 403 ()

### ISSUE THREAD

**Issue by raphael10-collab** [Leaflet/Leaflet#8142]
As I described in this `StackOverflow` question : https://stackoverflow.com/questions/71861153/leaflet-suddenly-im-getting-this-error-message-failed-to-load-resource-the?noredirect=1#comment126988321_71861153
I'm experiencing issues with loading and viewing `openstreetmap tiles`  : 

`Failed to load resource: the server responded with a status of 403 ()`

Based on the info here : https://operations.osmfoundation.org/policies/tiles/ the following are the requirements for the `openstreetmap` tiles usage: 

    Requirements
    
        Heavy use (e.g. distributing an app that uses tiles from openstreetmap.org) is forbidden without prior permission from the [Operations Working Group](https://wiki.osmfoundation.org/wiki/Operations_Working_Group). See below for alternatives.
        Clearly display [license](https://wiki.openstreetmap.org/wiki/License) attribution.
        Do not actively or passively encourage copyright infringement.
        Calls to /cgi-bin/export may only be triggered by direct end-user action. (For example: “click here to export”.) The export call is an expensive (CPU+RAM) function to run and will frequently reject when server is under high load.
        Recommended: Do not hardcode any URL at tile.openstreetmap.org as doing so will limit your ability to react quickly if the service is disrupted or blocked.
        Recommended: add a link to https://www.openstreetmap.org/fixthemap to allow your users to report and fix problems in our data.
    
    Technical Usage Requirements
    
        Valid [HTTP User-Agent](http://en.wikipedia.org/wiki/en:User_agent) identifying application. Faking another app’s User-Agent WILL get you blocked.
        If known, a valid [HTTP Referer](http://en.wikipedia.org/wiki/en:HTTP_Referer).
        DO NOT send no-cache headers. (“Cache-Control: no-cache”, “Pragma: no-cache” etc.)
        Cache Tile downloads locally according to HTTP Expiry Header, alternatively a minimum of 7 days.
        Maximum of 2 download threads. (Unmodified web browsers’ download thread limits are acceptable.)
    
    Note: modern web browsers in standard configuration generally pass all the above technical requirements.

As far as I understand, I do respect all of them

Here you can find a `reproducible live test case`:  https://github.com/raphael10-collab/LeafletElectronPlaying

Steps to reproduce:

1) git clone https://github.com/raphael10-collab/LeafletElectronPlaying.git
2) cd LeafletElectronPlaying
3) yarn
4) in one screen: yarn type-check
5) in another screen: yarn start

An Electron Window will open 

What perplex me is that this happens only for the `Basic Map Layer`:

![FailedToLoadResources](https://user-images.githubusercontent.com/70313067/163602118-4028cb84-284f-4c18-baf0-5d2b8f70433d.jpg)

With the `Topo Map Layer` the visualization seems fine : 

![FailedToLoadResourcesTopoMapLayer](https://user-images.githubusercontent.com/70313067/163602126-ef98a496-9ce1-49b2-8bc1-6d0ca8d6966e.jpg)

How to solve the issue?
Looking forward to your kind help

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* NativeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.

**Comment by raphael10-collab** [comment]
Hi @IvanSanchez ! I'm going to ask clues about this specific issue in the`react-leaflet` github repo.
If they say that it's a problem related to `leaflet` I will have to come back here
