### ISSUE TITLE
SVG images for marker and layer control

### ISSUE THREAD

**Issue by maciek-szn** [Leaflet/Leaflet#8158]
I'm not sure if it's intended or not - I couldn't find anything about that except for #7600. `src/images` folder contains SVG images for marker and layer control. However, v1.8.0 still uses PNG images.

**Comment by mourner** [comment]
It's intended. Why do you need SVG in place of images by default? Images work perfectly fine, they're better for performance, they don't need to be scaled, and they're supported by legacy browsers Leaflet still supports. You can still use custom SVG markers if needed.

**Comment by Malvoz** [comment]
I like SVGs, they look great, depending on the implementation they could be easily stylable, and might even save some byte size (e.g. [this icon](https://fonts.google.com/icons?selected=Material%20Icons%3Aplace%3A) is 300 bytes, versus current 1.43 kb).

Also, for v2 I think it's not inconceivable for default controls/icons to get a bit of a face lift? @maciek-szn do you want to suggest this feature in https://github.com/Leaflet/Leaflet/discussions/7729?

**Comment by Malvoz** [comment]
Closing per above comments, feel free to continue discussing here or in https://github.com/Leaflet/Leaflet/discussions/7729#discussioncomment-2599910.
