### ISSUE TITLE
Missing /leaflet/dist/leaflet.js in v1.8.0

### ISSUE THREAD

**Issue by elvinfucom** [Leaflet/Leaflet#8165]
I'm curious why  v1.8.0 doesn't have leaflet.js in dist folder?

**Comment by Falke-Design** [comment]
Where do you look? `leaflet.js` is existing:

From leaflet Downloads:
![image](https://user-images.githubusercontent.com/19800037/164155120-7b207711-ac54-45cc-86e7-8540d9ddfcfa.png)

[jsDelivr](https://www.jsdelivr.com/package/npm/leaflet?version=1.8.0&path=dist):
![image](https://user-images.githubusercontent.com/19800037/164155170-c59fe0c9-0bde-4b49-8537-178f9755a71a.png)

**Comment by elvinfucom** [comment]
![Uploading Screen Shot 2022-04-20 at 2.24.34 PM.png…]()
I downloaded the zip here.

**Comment by Falke-Design** [comment]
@elvinfucom uploading of the image worked not correctly

**Comment by Falke-Design** [comment]
@mourner In the [Github Release 1.8.0](https://github.com/Leaflet/Leaflet/releases/tag/v1.8.0) the dist files are missing.

**Comment by mourner** [comment]
GitHub Releases in general only provide the source code in downloads. I'm not sure whether we should change that. Leaflet distribution is officially available through NPM and download links on the website.

**Comment by elvinfucom** [comment]
Sometimes it is installed from git repo.

**Comment by davetapley** [comment]
This just caught me out: https://stackoverflow.com/a/73044271/21115
