### ISSUE TITLE
Missing file leaflet.js on directory dist

### ISSUE THREAD

**Issue by amadeumoromarques** [Leaflet/Leaflet#8169]
I'm trying to download the Leaflet using bower install... But when I downloaded the lib, I didn't see any JavaScript file on this folder... I just have the file "leaflet.css and images folder"... I'm using the newest version 1.8.0 and Angular JS

**Comment by mourner** [comment]
I'm surprised to learn Bower still exists (please use NPM instead!), but anyway, we can automate adding Leaflet distribution as a download to GitHub Releases (cc @jonkoops), but we're definitely not going back to committing the dist files to the repo for the release tags like we used to — it led to so many problems, and it's generally not how JavaScript libraries are distributed these years.

**Comment by jonkoops** [comment]
We have decided to drop support for Bower in v1.8.0 (see #7831). I'd recommend using NPM or another supported package manager instead.

**Comment by NielsHolt** [comment]
Well, calling 1.8 a minor update is a bit strange when it clearly is not compatible with 1.7.1
 Given the user 4 mounts to change from Bower is also short notice. 
The correct way to release all the new things would have been:
1.7.2 = All bug fixes
1.8.0 = All new features
2.0.0 = All re-coding, no Bower support etc.

**Comment by jonkoops** [comment]
It's unfortunate this is causing issues for those using Bower. However we always need to balance the needs of the project versus the needs of the community, and in this case we wanted to reduce the maintenance burden of the project.

In all honesty this should not come as a surprise, Bower has advertised it's own death for **years** now so I don't think the argument that this is a sudden change on our side holds up. It's simply a dead technology.

**Comment by NielsHolt** [comment]
True, but if Bower is doing the job for you, there are always more important problems to solve than to change something that works :-)

**Comment by Falke-Design** [comment]
The one thing is that we don't support bower anymore (which makes sense for me)  but I don't understand why we not simply add a new zip file to the release, which contains the source files ... this is no effort and solves the problem for the users.

@jonkoops @mourner why not simply change the Github Release zip file?
