### ISSUE TITLE
Bower does not include leaflet js files in dist folder

### ISSUE THREAD

**Issue by jthorpe80** [Leaflet/Leaflet#8171]
- [ x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [ x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [ x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- step 1
- Include "leaflet": "1.8.0" in the bower.json dependencies
- step 2
- run bower update
- 
**Expected behavior**
The files leaflet-src.js and leaflet.js are included

**Current behavior**
The leaflet project is downloaded into bower_components folder, but the leaflet-src.js and leaflet.js files are missing in the leaflet/dist folder.

**Environment**
- Leaflet version: 1.8.0
- Browser (with version): n/a
- OS/Platform (with version): Windows 10

**Additional context**

**Minimal example reproducing the issue**

Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.
N/A
- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

**Comment by Falke-Design** [comment]
Please look into https://github.com/Leaflet/Leaflet/discussions/8149#discussioncomment-2601603

**Comment by jthorpe80** [comment]
It would of been nice to see this listed in the breaking changes. It did break our build.
