### ISSUE TITLE
Extend eslint rules

### ISSUE THREAD

**Issue by Falke-Design** [Leaflet/Leaflet#8176]
We should extend the eslint rules to include following:

**1. Don't allow "concise methods":**
```
test() {
   //code
},
```
should be
```
test: function () {
   //code
},
```

Eslint rule:
"object-shorthand": ["error", "never"],

**2. Don't allow "arrow methods":**
```
var x = () => console.log('test');
```
should be
```
var x = function () {
	console.log('test');
}
```

**3. 4x-spaces should be a tab**  

@mourner I tried to extend your eslint-config but it didn't worked, maybe you can try it?

**Comment by exequiel09** [comment]
I only found this eslint config, https://github.com/Leaflet/Leaflet/blob/main/spec/.eslintrc so this task should add eslint rules on this file?

**Comment by jonkoops** [comment]
I am working on bumping our ESLint config at the moment, so this convention will likely no longer be required once we move to a more modern ES2015+ style.
