### ISSUE TITLE
Blog posts broke

### ISSUE THREAD

**Issue by Malvoz** [Leaflet/Leaflet#8191]
See e.g. https://leafletjs.com/2022/04/18/leaflet-1.8.0.html.

I think we didn't consider https://github.com/Leaflet/Leaflet/commit/dfbe5a884a5f61b74efd928199ea1a843cc6b69d in https://github.com/Leaflet/Leaflet/pull/8177. I'm not able to address this until maybe tomorrow.

/cc @Falke-Design, @mourner

**Comment by Falke-Design** [comment]
Sorry my fault ... but i can't fix it in the next 9 hours.

No the `/SlavaUkraini` folder cannot be removed because it contains the dialog logic and content of the dialog
