### ISSUE TITLE
Problem with polylines/polygons over the date line

### ISSUE THREAD

**Issue by ghost** [Leaflet/Leaflet#82]
Hi guys, when a polyline straddles the W180 line of longitude, crossing from one side to the other, the polyline does not continue on the other side of the W180 line, but is drawn back on the other side of the "current iteration" of the world.

Here is an example, polyline has 3 points draw from left to right. The first two polypoints are drawn on the left side of the W180 line, but the third which is meant to be just past the W180 line is not drawn to the right of the W180 line. It is being drawn back to the left where the current world begins:

http://fswidgets.com/beta/leaflet_test.html

**Comment by JoeMatulka** [comment]
I very much enjoy using Leaflet. I was wondering if there is any other work done on this issue other than the work around.

Keep up the good work! :smile:

**Comment by wmleler** [comment]
It was a while ago so I’m not sure, but I think they fixed this issue.  —wm

**Comment by RhezaBoge** [comment]
i'm sorry for my english.

there is a function that i found on leaflet 0.7.7  ("wrap" Conversion Methods). it has made me solved this problem with some additional code. 

but i can't run this function again on the newest leaflet (currently 1.0.1). i don't know why.. so for a while, i just use leaflet 1.0.1 but i change little bit code on "wrap function" (use leaflet 0.7.7 code). let me know if I missed anything or had some incorrect code for "wrap" methods on the newest leaflet. or maybe "wrap" methods has been removed or changed?

**Comment by callumacrae** [comment]
<img width="1263" alt="screen shot 2016-10-17 at 14 22 43" src="https://cloud.githubusercontent.com/assets/472830/19440148/a8b8a34c-9478-11e6-9738-079f77bd045d.png">

I'm getting this with leaflet 1.0.1. Looks similar to previous screenshots of this issue: https://github.com/mbostock/topojson/issues/242

**Comment by chrisregner** [comment]
I'm sorry, but I'm confused. @mourner said this:

> I removed LatLng wrapping/clamping by default alltogether (there's now an explicit LatLng wrap method for this). So all similar problems should be solved now in theory.

What I understood from this that I shouldn't need any work around. But I still experience the issue:
 
![image](https://user-images.githubusercontent.com/26005158/30159980-1d86b838-93fd-11e7-8b5f-069f0f772583.png)

So I tried doing the workaround he suggested:

>...the current workaround is to change the definition of points that are not drawing properly e.g. from this:
> `new L.LatLng(60, -150)`
> to this:
> `new L.LatLng(60, 210, true)`

Recreating [this "using d3 with Leaflet" tutorial](https://bost.ocks.org/mike/leaflet/), I had the similar part of code, but with dynamic values, so what I just tried adding the third `true` argument. And of course, that didn't work.

This is that specific part of my code

      function projectPoint(x, y) {
        const point = leafletMap.latLngToLayerPoint(new L.LatLng(y, x, true))

        this.stream.point(point.x, point.y)
      }

      // create a d3.geo.path to convert GeoJSON to SVG
      const transform = d3.geoTransform({ point: projectPoint })
      const path = d3.geoPath().projection(transform)

Here's the [gist](https://gist.github.com/chrisregner/dff1bd7a6fa053fd898d1ef70c451c88#file-map-js-L64( of my code (anchored to that particular line).

So my question is, how do I correctly apply the work around in my case? I can't use what @callumacrae has suggested because I want to keep Antartica.

Thanks.

**Comment by chrisregner** [comment]
For anyone who'll need it. I got a solution from https://github.com/topojson/topojson/issues/242#issuecomment-328310093.

**Comment by crowmagnumb** [comment]
The solution I came up with was to first collect all the LatLngs I was going to display in all objects and create a LatLng Mapper out of them. Then as I build the Leaflet objects I run the latlng through this mapper to decide if and how to convert the latlng before giving it to the leaflet object. Below is my solution in Typescript. I have not extensively tested this but it passes my basic test cases so far.

`class LatLngMapper {
    private identity: boolean = false;
    private narrow: boolean = false;

    constructor(latlngs: [number, number][]) {
        if (latlngs) {
            let posCount = 0;
            let maxLng = null;
            let minLng = null;
            for (const latlng of latlngs) {
                let lng = latlng[1];
                if (!maxLng || maxLng < lng) {
                    maxLng = lng;
                }
                if (!minLng || minLng > lng) {
                    minLng = lng;
                }
                if (lng >= 0) {
                    posCount++;
                }
            }

            const allSameSign = posCount == 0 || posCount === latlngs.length;
            if (allSameSign) {
                this.identity = true;
            } else {
                this.narrow = maxLng - minLng < 180;
            }
        } else {
            this.identity = true;
        }
    }

    convert(latlng: [number, number]) {
        if (this.identity) {
            return latlng;
        }

        if (this.narrow) {
            return latlng;
        } else {
            let lng = latlng[1];
            if (lng < 0) {
                return <[number, number]>[latlng[0], lng + 360];
            } else {
                return latlng;
            }
        }
    }
}
`
