### ISSUE TITLE
MouseEvent.mozPressure is deprecated

### ISSUE THREAD

**Issue by solaroptic** [Leaflet/Leaflet#8200]
Mozilla Dev Edition warning:
MouseEvent.mozPressure is deprecated. Use PointerEvent.pressure instead.
 it identified it occuring in util.js:15:3

**Steps to reproduce**
Using the main page simple version

**Expected/Current behavior**
Still functioned fine but eventually may not

**Environment**
main page 'create map' code

- OS/Platform (with version):
Mozilla Developer Edition 100.0b9

**Additional context**
I'm completely new to this (GIThub. Leaflet, Development), but it was identified as coming from Leaflet

**Minimal example reproducing the issue**
happened during modification of
L.marker

**Comment by IvanSanchez** [comment]
Duplicate of https://github.com/Leaflet/Leaflet/issues/7078

**Comment by pouemes** [comment]
with leaflet1.91 there is still this warning with firefox 105.0.1 64bits (last version)

**Comment by jonkoops** [comment]
@pouemes could you file this as a separate issue?

**Comment by IvanSanchez** [comment]
It's gonna be still a duplicate of #7078, so there's no point - this won't go away until a full revamp of decorated mouse/pointer events.

**Comment by jonkoops** [comment]
Got it, thanks @IvanSanchez.
