### ISSUE TITLE
Replace CSS color-adjust to print-color-adjust

### ISSUE THREAD

**Issue by olereidar** [Leaflet/Leaflet#8210]
Hello, based on the newest [update from autoprefixer](https://mobile.twitter.com/Autoprefixer/status/1520903101040975878?cxt=HHwWjICztf7TqpsqAAAA), the color-adjust shorthand is currently deprecated. 

Could `color-adjust` be replaced with `print-color-adjust` in the code below?

```
@media print {
	/* Prevent printers from removing background-images of controls. */
	.leaflet-control {
		-webkit-print-color-adjust: exact;
		color-adjust: exact;
		}
	}
```
source: https://github.com/Leaflet/Leaflet/blob/main/dist/leaflet.css#L658 

- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- use autoprefixer to prefix css

**Expected behavior**

Not the warning "autoprefixer: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated." to occur

**Environment**
- Leaflet version: 1.8.0

**Comment by nessor** [comment]
@mourner Can you release this fix soon? Currently our internal pipeline is failing because of this depreciation :( 

This would be a good fix without the need of building sth. around :)

**Comment by Falke-Design** [comment]
@nessor no there will be no release in the next days.
You can simply overwrite the css by adding this to your own css file:
```
.leaflet-control {
		-webkit-print-color-adjust: exact;
		print-color-adjust: exact;
		}
	}
```

**Comment by fjoho** [comment]
Still no patch release planned for this?

**Comment by existe-deja** [comment]
I don't think it should be closed :thinking:

**Comment by Falke-Design** [comment]
> I don't think it should be closed 🤔

@existe-deja We haven't released a new version since that but it is closed because we already fixed it. You can simple use the code from the repo und build your own source files, then the issue is solved for you.

**Comment by cravend** [comment]
> > I don't think it should be closed 🤔
> 
> @existe-deja We haven't released a new version since that but it is closed because we already fixed it. You can simple use the code from the repo und build your own source files, then the issue is solved for you.

That's not a solution to this issue and I'd also like to request that it be re-opened. Of course it's _theoretically_ possible to build the source files directly, but if you're using the code via NPM or a CDN (like literally everyone these days), then you're stuck with these build errors. Please release a patch ASAP!

**Comment by IvanSanchez** [comment]
You folks are treading the thin line between politely asking for a release and harassing the maintainers.

Bug reports are closed when the bug isn't reproducible on a build from the `main` branch, not when a release happens.
