### ISSUE TITLE
Using popup in Blazor app breaks autoPan

### ISSUE THREAD

**Issue by mu88** [Leaflet/Leaflet#8217]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
1. Create a [Blazor app](https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-6.0)
2. Create a very basic Blazor component
3. Add this Blazor component to a Leaflet popup:  
```js
let marker = L.marker([latitude, longitude]);
marker.bindPopup("<my-blazor-component></my-blazor-component>", {minWidth: 500});
marker.addTo(leafletMap);
```

**Expected behavior**
When opening the marker's popup, the map should automatically pan so that the popup`s complete content is visible. For example, it should look like this:
![image](https://user-images.githubusercontent.com/4560672/167296928-7f66de1b-3e21-440e-8b3c-1a3e9e275a81.png)

**Current behavior**
There is no panning of the map at all and therefore the popup opens outside the visible area:
![image](https://user-images.githubusercontent.com/4560672/167296923-746d82f0-fc49-48e2-959e-d0d17bd875a2.png)

**Environment**
- Leaflet version: 1.8.0 (problem exists with 1.7.1 as well)
- Browser (with version): Firefox (v100.0), Chrome (v101.0.4951.54)
- OS/Platform (with version): Windows 10 Pro 21H2

**Additional context**
Maybe it's something similar to https://github.com/tombatossals/angular-leaflet-directive/issues/741

**Minimal example reproducing the issue**
Since jsfiddle does not allow to use Blazor, there is no super-easy example. But you can simply clone and run my app: https://github.com/mu88/Project28/

Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* NativeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.

**Comment by mu88** [comment]
And what would be the appropriate repo? Blazor is working fine, so Microsoft won't do anything.

**Comment by IvanSanchez** [comment]
Then dissect whatever CSS properties and event handlers are being added to the Leaflet popup, replicate the problem *without* blazor but with using vanilla JS with those CSS properties and events, and open a new bug here.

Emphasis on the "dissect". What's the **minimal** amount of vanilla HTML+JS that you must add to a Leaflet popup in order to reproduce the problem?

**Comment by mu88** [comment]
That's impossible: I cannot disassemble a complete framework which does the heavy-lifting of rendering C# code in the browser. I opened an issue in the Blazor repo, but I'm pretty certain how the answer will look like.

**Comment by mu88** [comment]
@IvanSanchez please see Microsoft's answer https://github.com/dotnet/aspnetcore/issues/41577#issuecomment-1121300225:

> Check if there is a method you can trigger to update the popup to react to the size change when the render happens. 

Does Leaflet offer a way to trigger a redraw or autopan  after the fact?

**Comment by IvanSanchez** [comment]
> Does Leaflet offer a way to trigger a redraw or autopan after the fact?

Yup. The `update()` method of `L.Popup`'s parent class...

https://github.com/Leaflet/Leaflet/blob/9bfd4b9b0b0a333734f6706b60da31eae3974e6f/src/layer/DivOverlay.js#L170

...will call the logic to auto-pan the map so the popup is in view, which itself happens in an internal method at...

https://github.com/Leaflet/Leaflet/blob/9bfd4b9b0b0a333734f6706b60da31eae3974e6f/src/layer/Popup.js#L249

Don't forget to check https://leafletjs.com/reference

**Comment by mu88** [comment]
I solved it, [see here](https://github.com/dotnet/aspnetcore/issues/41577#issuecomment-1140268771)
