### ISSUE TITLE
Firefox 100: Clicking control fires ghost dblclick

### ISSUE THREAD

**Issue by pgrondelaers** [Leaflet/Leaflet#8225]
**Steps to reproduce**
- Click the control in the top right corner with Leaflet 1.7.1 activated
- Click the control in the top right corner with Leaflet 1.8.0 activated

**Expected behavior**
The map has a button in the top right corner and a text area in the bottom left. Clicking the button should toggle the area's visibility.

**Current behavior**
Clicking the button not only toggles the area's visibility, but also zooms in on the map. This only happens in Firefox, not in Chrome, since upgrading to leaflet 1.8.0.

**Environment**
- Leaflet version: 1.8.0
- Browser (with version): Firefox 100.0
- OS/Platform (with version): Windows 10

**Minimal example reproducing the issue**
~~See this JSFiddle: https://jsfiddle.net/petergrondelaers/pvk4hxmw/~~

https://jsfiddle.net/51bLtj9x/ or https://run.plnkr.co/preview/cl30e37zy0007206kqu0it63k/

**Comment by IvanSanchez** [comment]
I don't have a Firefox v100 at hand, but I must ask: Are you absolutely sure you're clicking, and **not double-clicking**, the button?

**Comment by jonkoops** [comment]
Thank you so much @pgrondelaers for including a reproducible example, this helps us greatly. I just checked this on Firefox 100 on Fedora 36 (Linux) and I can reproduce this issue.

**Comment by IvanSanchez** [comment]
Ugh. Sounds like a regression introduced by the changes in the 1.8.0 logic for touch doubleclick, in either #7027, #7059, #7084 or #7415. Paging @johnd0e.

This is going to need a fair bit of proper debugging, to see what events are being fired at the control, what events are being propagated to the map, and what events are synthetic events is Leaflet creating along the way.

**Comment by IvanSanchez** [comment]
I can **not** reproduce. Firefox 100.0-1 on Debian Linux. Laptop with no touchscreen. Using external USB mouse and touchpad.

My values for `L.browser.gecko`,  `L.browser.pointer` and  `L.browser.touch` are all `true`.

**Comment by jonkoops** [comment]
@[vanSanchez try using [this Fiddle](https://jsfiddle.net/51bLtj9x/) which includes the latest version of Leaflet.

**Comment by IvanSanchez** [comment]
Putting a [plunkr](https://plnkr.co/edit/jtIJIqvoqFwwZXVe) (also [standalone](https://run.plnkr.co/preview/cl30e37zy0007206kqu0it63k/)) here just because I like plunkr a tiny bit more than jsfiddle.

**Comment by IvanSanchez** [comment]
I think I have an idea of what's going on.

On one hand, Firefox is not fully compliant with the `PointerEvent`s spec. Specifically, a `click` event should be a `PointerEvent`, but current versions of Firefox handle it only as a `MouseEvent`. Therefore, this doesn't work as we would expect:

https://github.com/Leaflet/Leaflet/blob/9bfd4b9b0b0a333734f6706b60da31eae3974e6f/src/dom/DomEvent.DoubleTap.js#L41-L44

On the other hand: the reproducible example has both a `<input type='checkbox'>` and a `<label for='foobar'>`. Clicking on the checkbox triggers a `click` event on the label... even though the label is not a DOM parent of the checkbox element. **I believe this to be an upstream bug**, but I should re-read the DOM event propagation specs.

Then: since there are two `click` events fired on quick succession, Leaflet's `DomEvent.DoubleTap.js` translates that into a `dblclick`. Finally, that `dblclick` event is propagated to the map, and `handler/Map.DoubleClickZoom.js` zooms in.

**Comment by Falke-Design** [comment]
> Apparently this is normal event propagation behaviour.

@IvanSanchez where did you find that this is the normal behaviour? I always have troubles to find this web / browser definitions. My first attempt is always `mdn`.

**Comment by IvanSanchez** [comment]
> @IvanSanchez where did you find that this is the normal behaviour? I always have troubles to find this web / browser definitions. My first attempt is always `mdn`.

Firing up chromium and `console.log()`ing events happening at both the label and checkbox :shrug:

**Comment by Falke-Design** [comment]
Good idea 😄 

I found out that the second click event still has the coords of the orginal event but a different target. So we can use this as check:

```
// different target -> can't be a double click.
		// Happens when label propagate the event to the linked input over `for` #8225
		var preventDblClick = lastEvent && L.point(e.x, e.y).equals(L.point(lastEvent.x, lastEvent.y)) && e.target !== lastEvent.target;
		if (now - last <= delay && !preventDblClick ) {
			detail++;
			if (detail === 2) {
				handler(makeDblclick(e));
			}
		} else {
			detail = 1;
		}
		last = now;
		lastEvent = e;
```

**Comment by Falke-Design** [comment]
But the map `click` event is still firing twice.

```
map.on('click',(e)=>console.log(e))
```
![grafik](https://user-images.githubusercontent.com/19800037/167692338-68f1ff7d-67f3-4963-a299-fd007b2c8ae0.png)

**Comment by moll** [comment]
Hey! The fix in https://github.com/Leaflet/Leaflet/pull/8227/files does not seem to work when the `<label>` wrapping the `<input>` has no `for` attribute. The `for` is only useful if the `<label>` is besides the `<input>`.
