### ISSUE TITLE
Event.composedPath()

### ISSUE THREAD

**Issue by Th3AnG3L** [Leaflet/Leaflet#8226]
Hello i have been using leaflet.js for a months but now i receive error in web browser:

Deprecated Feature Used
'Event.path' is deprecated and will be removed in M109, around January 2023. Please use 'Event.composedPath()' instead. See https://www.chromestatus.com/feature/5726124632965120 for more details.

or maybe i need new version leaflet.js, can someone help me out with builded new one .js file.
Thank you.

**Comment by Falke-Design** [comment]
@Th3AnG3L you can use the already builded source files:
https://www.jsdelivr.com/package/npm/leaflet
```
<script src="https://cdn.jsdelivr.net/npm/leaflet@1.8.0/dist/leaflet-src.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet@1.8.0/dist/leaflet.css">
```

**Comment by Th3AnG3L** [comment]
> @Th3AnG3L you can use the already builded source files: https://www.jsdelivr.com/package/npm/leaflet
> 
> ```
> <script src="https://cdn.jsdelivr.net/npm/leaflet@1.8.0/dist/leaflet-src.min.js"></script>
> <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet@1.8.0/dist/leaflet.css">
> ```

Thank you i will download it and will take a look.

**Comment by Falke-Design** [comment]
@Th3AnG3L can you please set up a demo: https://leafletjs.com/edit

**Comment by Th3AnG3L** [comment]
i cant because its implemented as plugin in the system, but i can show live demo
https://resido.thesky9.com/properties/6007-applegate-lane
- when click zoom or out it shows this error
- by functions it reads directly leaflet.js codes and i had download the last one 1.8.0 and when make that zoom in zoom out pop ups in browser this error

**Comment by Falke-Design** [comment]
The error happens in Chromium Browsers while dragging the map. But to see the problem you need to open the issues Tab in the Developer Tools, the console is not enough (for me).

![grafik](https://user-images.githubusercontent.com/19800037/167694550-8becc504-8674-4275-bd32-1392bac38035.png)

**Comment by IvanSanchez** [comment]
Then this is the chromium equivalent of #7078, triggers when copying all properties of an event. Safe to ignore.

**Comment by Lookintothesoul** [comment]
Thanks Chrome, I spent an hour to figure out what was wrong and thanks, now I know where to look for chrome updates
