### ISSUE TITLE
leaflet-streetview plugin: bug with last mapillary API (11/2021)

### ISSUE THREAD

**Issue by astomas** [Leaflet/Leaflet#8232]
original issue : [https://github.com/Zverik/leaflet-streetview/issues/3](https://github.com/Zverik/leaflet-streetview/issues/3 )
since mapillary change of API, the mapillary URL call is unknown, see demo map for example:
[https://zverik.github.io/leaflet-streetview/index.html](https://zverik.github.io/leaflet-streetview/index.html)
Mapillary client Id fill (now pKey) has changed too with the new API.

**Comment by jonkoops** [comment]
We do not directly support Leaflet plugins as they are 3rd party code. If something is broken in a plugin please report the issue in their respective issue tracker.
