### ISSUE TITLE
Issue forms with YAML templates

### ISSUE THREAD

**Issue by Malvoz** [Leaflet/Leaflet#8233]
Originally suggested in https://github.com/Leaflet/Leaflet/issues/7704#issuecomment-981410604.

Issue forms can help people create better issues, which is helpful to maintainers.

Public repo to try the new templates out: https://github.com/Malvoz/test-issue-form-templ/issues/new/choose.

File as many issues as you want there, the repo will be deleted after it has served its purpose. The content in that repo is intended to replace the contents of [`.github/ISSUE_TEMPLATE/`](https://github.com/Leaflet/Leaflet/tree/main/.github/ISSUE_TEMPLATE/), if accepted.

If you think this is a good idea, please discuss any changes you'd like to see in the templates.

More info:
- [Issues forms beta for public repositories](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/)
- [Creating issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms)
- [Syntax for GitHub's form schema](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema)

/cc @mourner, @IvanSanchez, @Falke-Design, @jonkoops, @johnd0e, @perliedman, @yohanboniface, @cherniavskii

**Comment by IvanSanchez** [comment]
A couple of nitpicks:
- Links should open in a new tab/window
- OS/Platform should be pluralized in the same way as browsers, e.g. "affected OS(es)/platform(s)"
- Field for the REPL should be a bit more explicit about not using any frameworks

Consider:
- Add a field for input method(s) used (mouse/touchscreen/keyboard/all)
- Add a field for frameworks used (react, angular, etc), and fail if the field is not empty. Yes, this is trolly, but it's the user's fault for blindly checking the "I'm sure this is a Leaflet problem" checkbox.

**Comment by Malvoz** [comment]
Thanks for the feedback.

> - Links should open in a new tab/window

> - Text fields should be wider, to cover as much space as the textareas

I don't know if it's possible to control the width of the inputs, or the link targets.

**Comment by IvanSanchez** [comment]
> I don't know if it's possible to control the width of the inputs, or the link targets.

Looks like you're right. I'm reading https://stackoverflow.com/questions/41915571/open-link-in-new-tab-with-github-markdown-using-target-blank and it's discouraging.

Other than my nitpicks, I'm all for this.

**Comment by Malvoz** [comment]
> - OS/Platform should be pluralized in the same way as browsers, e.g. "affected OS(es)/platform(s)"
> - The placeholder text in OS/Platform should also display the hardware platform, e.g. "Win10 laptop, Android tablet"

Fixed in https://github.com/Malvoz/test-issue-form-templ/commit/db33346a6291016785b38898a4fa75c4e02afc5b.

> - Field for the REPL should be a bit more explicit about not using any frameworks

Fixed in the same commit, changed period to exclamation mark and bold text.

> Consider:
>
> - Add a field for input method(s) used (mouse/touchscreen/keyboard/all)

Added a multi-selectable dropdown in https://github.com/Malvoz/test-issue-form-templ/commit/eff4b8a1bd7d2f85c623d218528112b37cf0e3b4.

[Quick link to bug template](https://github.com/Malvoz/test-issue-form-templ/issues/new?assignees=&labels=bug&template=bug_report.yml) to try it out. Maybe I should've placed the dropdown for input methods as the last input, or perhaps move it up somewhere.

> - Add a field for frameworks used (react, angular, etc), and fail if the field is not empty. Yes, this is trolly, but it's the user's fault for blindly checking the "I'm sure this is a Leaflet problem" checkbox.

Lets hear what @mourner thinks?

> - Change the OS/platform/browser

Is this a suggestion to only have one input for OS/platform/browser as opposed to one for OS/Platform and another for browsers?

**Comment by Falke-Design** [comment]
Should we make **Steps to reproduce**, **Leaflet version** and **Browser** required too? That are important informations for a bug

**Comment by jonkoops** [comment]
Perhaps we can use Markdown for the links in the 'Support' section? That way it doesn't feel so text heavy.

![A screenshot of the Support section](https://user-images.githubusercontent.com/695720/168026233-a871889c-cef8-4d15-8f6f-41010c77a65c.png)

Ideally I would like to see the 'Minimal example' required for bug reports, but I understand if sometimes this is no viable.

**Comment by Malvoz** [comment]
> Should we make Steps to reproduce, Leaflet version and Browser required too? That are important informations for a bug

@Falke-Design Possibly. I just didn't want to be too restrictive. We could look at existing bugs, there may be cases where Steps to reproduce is not clear even to the reporter, for example?

**Comment by Malvoz** [comment]
> Perhaps we can use Markdown for the links in the 'Support' section? That way it doesn't feel so text heavy.

@jonkoops I did try that out, unfortunately it seems markdown links aren't supposed in [config.yml](https://github.com/Malvoz/test-issue-form-templ/blob/main/.github/ISSUE_TEMPLATE/config.yml). But I agree. Maybe we can trim the text down.

**Comment by mourner** [comment]
This is generally great! Thanks so much for working on this @Malvoz!

My initial intuitive reaction to the form is that it's currently overcomplicated. When a user sees such a huge and complex form (even though most fields are optional) they can be so overwhelmed that it can greatly discourage them from submitting  anything (which might be OK but only to a point). Let's try to strike a balance between helpful guidance and simplicity.

E.g. we could combine some of the fields. Instead of 4 separate text areas for Steps to reproduce, Expected behavior, Current behavior and Additional context (which I found overly verbose when reporting bugs in other projects myself), we could have 1 text area with bug description (where hints what it should include can be above the field). Environment fields could also be simplified — e.g. browser / OS / platform combined in one field, and removing Input method / Assistive technology in favor of people specifying this as additional context in the main description where applicable.

**Comment by Malvoz** [comment]
Thanks for the feedback @mourner.

If we're not explicit about each type of information that is desired, then we're likely not going to get that info. And as you say, people can choose not to fill in most inputs if that's troublesome for them.

Another concern for me if we're to simplify the form (even with describing all types of info that is desired in a single textarea vs multiple textareas) is that different bug reports will have a slightly different format/structure, so reading bug reports may take longer time as it's not immediately clear where to find a particular type of info.

I'll create a simplified version of the bug report, that way we can easily compare pro's and con's of each.

**Comment by mourner** [comment]
@Malvoz maybe we could find a balance — perhaps not a single text area, but at least not this many either. E.g. let's think which of the fields are unlikely to be filled out or are only relevant in a small minority of potential issues, and combine them (maybe into "Additional context"?)

**Comment by mourner** [comment]
And one more small nit — we should probably rephrase the checklist items so that they fit one line for clarity, e.g.:

<img width="728" alt="image" src="https://user-images.githubusercontent.com/25395/168063277-3cc839ed-d77e-46c6-8e6c-e52584b186e3.png">
vs:

<img width="816" alt="image" src="https://user-images.githubusercontent.com/25395/168062750-8cbd3b36-0116-4a07-8f1b-a7aa1c3b8092.png">

**Comment by Malvoz** [comment]
> rephrase the checklist items so that they fit one line for clarity

Agree, fixed in https://github.com/Malvoz/test-issue-form-templ/commit/e109d299ba966d196b30dcb21ed5ea2f73532c14.

**Comment by Malvoz** [comment]
> maybe we could find a balance — perhaps not a single text area, but at least not this many either. E.g. let's think which of the fields are unlikely to be filled out or are only relevant in a small minority of potential issues, and combine them (maybe into "Additional context"?)

We can start with removing the Assistive tech input?

**Comment by Malvoz** [comment]
> e.g. browser / OS / platform combined in one field, and removing Input method / Assistive technology in favor of people specifying this as additional context in the main description where applicable.

I've removed the Input method + Assistive tech fields in the existing [bug report form](https://github.com/Malvoz/test-issue-form-templ/issues/new?assignees=&labels=bug&template=bug_report.yml). Also added a further [simplified bug report form](https://github.com/Malvoz/test-issue-form-templ/issues/new?assignees=&labels=bug&template=bug_report_simplified.yml) which combines Browser/OS/Platform and removes the Additional Context textarea.

**Comment by Malvoz** [comment]
Maybe the simplified bug report should just have 1 textarea for Environment instead of one for Leaflet version and another for Browser/OS/Platform?

**Comment by Malvoz** [comment]
The only difference between the [bug report](https://github.com/Malvoz/test-issue-form-templ/issues/new?assignees=&labels=bug&template=bug_report.yml) and the [simplified bug report](https://github.com/Malvoz/test-issue-form-templ/issues/new?assignees=&labels=bug&template=bug_report_simplified.yml) now is that the former has separate fields for:

- Steps to reproduce
- Current behavior
- Expected behavior
- Additional context

whereas the simplified one only has 1 textarea named Bug description.

**Comment by Malvoz** [comment]
A few more iterations of simplifying, I think they're both looking pretty good now.
I personally prefer [`bug_report.yml`](https://github.com/Malvoz/test-issue-form-templ/issues/new?assignees=&labels=bug&template=bug_report.yml) over [`bug_report_simplified.yml`](https://github.com/Malvoz/test-issue-form-templ/issues/new?assignees=&labels=bug&template=bug_report_simplified.yml).

**Comment by mourner** [comment]
@Malvoz Love this! Let's go with the first one, it already looks much nicer than the initial iteration. 

One minor suggestion I'd add is perhaps we could remove the "Additional context" field and instead add a note in the description to current/expected behavior (e.g. "A clear and concise description of what is actually happening. Provide additional context if necessary (screenshots, video, links, etc.).".  But not a strong opinion. If we keep the additional context field, perhaps we should move it after the environment one?

**Comment by Malvoz** [comment]
> One minor suggestion I'd add is perhaps we could remove the "Additional context" field and instead add a note in the description to current/expected behavior (e.g. "A clear and concise description of what is actually happening. Provide additional context if necessary (screenshots, video, links, etc.)."

Done, in https://github.com/Malvoz/test-issue-form-templ/commit/441327480c64bbbf79a7d4c2d86feb26883103b2. I thought it'd be strange to repeat it, but I actually like it more this way.

Check it out: [bug_report.yml](https://github.com/Malvoz/test-issue-form-templ/issues/new?assignees=&labels=bug&template=bug_report.yml)

**Comment by Malvoz** [comment]
Other things to consider:

1. I rewrote the following checklist item, as emphasized:
  
   > - [ ] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior is<em>n't</em> documented and expected.

   as there would be no need to report a bug if it indeed _is_ documented and expected?

2. Should the bug report template include a link to [CONTRIBUTING.md#reporting-bugs](https://github.com/Leaflet/Leaflet/blob/main/CONTRIBUTING.md#reporting-bugs)?

   The existing checklist item:

   > - [ ] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).

   would essentially be covered by that link, though that aspect (not using frameworks) is really important and I don't want to change the wording of that checklist item, nor do I want to add more checkboxes. So perhaps not.

3. Should the templates use auto-labelling? (https://github.com/Leaflet/Leaflet/labels/bug, https://github.com/Leaflet/Leaflet/labels/feature, https://github.com/Leaflet/Leaflet/labels/docs).
  
   I've currently configured them that way - that's not the case for the live markdown templates. The question is then, should we start using the https://github.com/Leaflet/Leaflet/labels/accepted label to discern confirmed issues? Because I _think_ the current manual labelling of issues (adding e.g. https://github.com/Leaflet/Leaflet/labels/bug) acts like "accepted" in a way. OTOH, the example templates in the GH docs use the [`needs triage` label](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms#:~:text=needs%20triage), which would instead need to be removed when an issue is accepted (i.e. inverse of https://github.com/Leaflet/Leaflet/labels/accepted).

4. A [new template for Improving docs](https://github.com/Malvoz/test-issue-form-templ/issues/new?assignees=&labels=docs&template=improve_documentation.yml) (this addition can be deferred, but would be nice IMO because currently mostly blank issues are appropriate for docs issues).

5. Since we now have pre-defined values in the Environment textarea (to make it a list) we can't have placeholder text (as [suggested](https://github.com/Leaflet/Leaflet/issues/8233#issuecomment-1124025989)), but we could have example values in the description itself, similar to one of the [example GH docs templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms#yaml-issue-form-template):

    ```yml
    label: Environment
    description: |
      examples:
        - **OS**: Ubuntu 20.04
        - **Node**: 13.14.0
        - **npm**: 7.6.3
    ```

**Comment by mourner** [comment]
@Malvoz great work on the templates!

> 2\. Should the bug report template include a link to [CONTRIBUTING.md#reporting-bugs](https://github.com/Leaflet/Leaflet/blob/main/CONTRIBUTING.md#reporting-bugs)?

Not sure. It's also linked in the sidebar when creating an issue, although not very prominent, and we'd also like to avoid forcing people to read a ton of things before being able to report something. We can skip this for now.

> 3\. Should the templates use auto-labelling?

Definitely.

> 3\. OTOH, the example templates in the GH docs use the [`needs triage` label](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms#:~:text=needs%20triage), which would instead need to be removed when an issue is accepted (i.e. inverse of `accepted`)

I think this is preferable, because we want to be able to quickly list all issues that need a triage. Currently we can do that with "unlabeled" filter which I use often, but if issues are auto-labeled, we need a specific label for issues that weren't triaged.

> 4\. A [new template for Improving docs](https://github.com/Malvoz/test-issue-form-templ/issues/new?assignees=&labels=docs&template=improve_documentation.yml) (this addition can be deferred, but would be nice IMO because currently mostly blank issues are appropriate for docs issues).

Love this! Looks great. Let's definitely add this.

> 5\. but we could have example values in the description itself, similar to one of the [example GH docs templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms#yaml-issue-form-template)

Let's try it — if it doesn't look too crowded / verbose, we can add it.

> 6\. Should it be changed to:
>     > Please fill in the Leaflet [version](https://leafletjs.com/reference.html#version) and the name and versions of the affected browser(s), OS(es), and platform(s).

👍

**Comment by Malvoz** [comment]
- [x] Added `needs triage` labelling in https://github.com/Malvoz/test-issue-form-templ/commit/5bff026ff53bbdbb0928c5ad333c065e0efacf39.
- [x] Changed to use a link for "Leaflet version" in https://github.com/Malvoz/test-issue-form-templ/commit/fd539621a161cbdc7a46d2fed0193d9ad2f07c04
- [x] Added example for Environment in its description, in https://github.com/Malvoz/test-issue-form-templ/commit/b1ce1126ba5a4b44f483583cd196ac15e5550528, https://github.com/Malvoz/test-issue-form-templ/commit/c02bf6d5cc5f798aba69478c0385e2f1db6aa46d.
  Please take a look at the [bug report](https://github.com/Malvoz/test-issue-form-templ/issues/new?assignees=&labels=bug%2Cneeds+triage&template=bug_report.yml) to see if the example looks good or not.

**Comment by mourner** [comment]
@Malvoz looks great, let's do it!
