### ISSUE TITLE
Leaflet mobile view triggers "onClick" event only when double tap when there is custom layer - pixi.js

### ISSUE THREAD

**Issue by hadson172** [Leaflet/Leaflet#8236]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- Initialize leaflet map
- Add custom layer from pixi.js engine (this utils https://github.com/manubb/Leaflet.PixiOverlay)
- add `map.on("click") `event
- Open in responsive mode - mobile view (iphone).
- Refresh page (this step is important, to get fresh map on mobile because if this skipped everything works).
- tap
- on click event is not triggered
- double tab - onClick event is triggered

**Expected behavior**
On mobile onclick should be registered when single tap

**Current behavior**
On mobile onclick with custom layer is triggered only when double tap

**Environment**
- Leaflet version: 1.8.0
- Browser (with version): Firefox Windows, Safari iOS
- OS/Platform (with version): --

**Minimal example reproducing the issue**
https://codesandbox.io/s/gallant-perlman-7bf8qi?file=%2Fsrc%2Findex.js&resolutionWidth=320&resolutionHeight=675
- open in new window
- go to responsive view - mobile - iphone 13 mini
- referesh the page
- tap on the map
- on click console log is not triggered

Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.

- [x] this example is as simple as possible
- [ ] this example does not rely on any third party code

**Comment by IvanSanchez** [comment]
Able to reproduce on Firefox 100 + Linux. Using a REPL with no pre-bundled pixi, at https://plnkr.co/edit/yYbg8gNq8ZG5PvIR

I've tracked the root cause down to https://github.com/pixijs/pixijs/blob/f2c7e769e65d62df769e5842bb9d9a60197a94f0/packages/interaction/src/InteractionManager.ts#L1206-L1217 . For whatever reason, Pixi is preventing the default browser behaviour for `touchstart` events and, for whatever reason, responsive emulation means that the event's propagation is stopped, so it never reaches the Leaflet map container (and Leaflet's `_handleDOMEvent` never runs).

Maybe that can be worked around with pixi's `autoPreventDefault` option, but that task falls to the Leaflet.pixioverlay plugin.

Filing under "blanket response for being the framework's fault".

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* NativeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.

**Comment by hadson172** [comment]
@IvanSanchez 
To be honest i set autoPreventDefault = false and it seems that this fix a problem a little but it completly.
On windows browser it register onclick but on safari iOS iphone 8 still requires two click (not double click but two clicks).

This stuff worked at leaflet 1.7.1 for months but stopped working on leaflet 1.8.0. Are you sure it is plugin's fault ? Thanks

**Comment by IvanSanchez** [comment]
> This stuff worked at leaflet 1.7.1 for months but stopped working on leaflet 1.8.0.

If you read the [changelog](https://github.com/Leaflet/Leaflet/blob/main/CHANGELOG.md) you'll notice that Leaflet 1.8.0 changed the way that `TouchEvent`s are handled (at #7059, #7084, #7415)

So when you use a touchscreen the browser triggers both a `touchstart` and then a `pointerdown` event. In Leaflet we're trying to sloooowly deprecate `touchstart`/`touchmove`/`touchend` in favour of `pointerdown`/`pointermove`/`pointerend` (as per #7200). Then, Pixi is ignoring the `pointer*` events and using `touch*` events exclusively (from what I can tell).

On top of that, the behaviour of ipad touchscreens seems to be "if a `touch*` event has its default behaviour prevented, then do not fire the corresponding `pointer*` event", which is just plain weird.

> Are you sure it is plugin's fault?

It's nobody's and everybody's fault, I guess. There's three main moving pieces here (leaflet, pixi, browsers). Browsers implemented touch events in weird ways, so both Leaflet and Pixi had to write their own set of hacks to make stuff work across browsers. And by cleaning Leaflet's hacks, now the Pixi hacks and the browsers' quirks are misbehaving.
