### ISSUE TITLE
100s of events output to the console

### ISSUE THREAD

**Issue by tiimgreen** [Leaflet/Leaflet#8237]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- use "react-leaflet"

**Expected behavior**
No console output

**Current behavior**
100s of events output to the console. Completely clogs up the console making it hard to see my own outputs

**Environment**
- Leaflet version:
- Browser (with version):
- OS/Platform (with version):

**Additional context**
<img width="439" alt="Screenshot 2022-05-12 at 14 00 53" src="https://user-images.githubusercontent.com/4130574/168149292-29983067-ee88-4c0c-abc4-95007bc8b046.png">

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* NativeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.
