### ISSUE TITLE
Is there onmapclick(e) function for flutter plugin

### ISSUE THREAD

**Issue by halhwadi** [Leaflet/Leaflet#8240]
--------------^ Click "Preview" tab for a nicer view!

I tried to search if onmapclick(event) function is available in leaflet flutter plugin but I didn't find any reference 
please advise if its available, if yes, would you share one example please?

Best Regards

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* NativeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.
