### ISSUE TITLE
More smooth Zoom in map

### ISSUE THREAD

**Issue by KAMIKAZEUA** [Leaflet/Leaflet#8252]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Open http://gpx.studio which uses this framework, try to zoom map, notice it's chunky zoom steps, no smoothness. 

### Expected behavior

Nice smooth zoom like for example in Google Maps.

### Current behavior

Zoom "jumps" and chunky. 

### Environment

- Browser (with version): Safari 
- OS/Platform (with version): macOS 12.4

https://github.com/gpxstudio/gpxstudio.github.io/issues/162

![169052389-b7108906-9d1e-4a74-8b37-b2ebed77e51e](https://user-images.githubusercontent.com/3391456/169330647-8ae0c732-cca1-4acc-b2fd-0a068203da99.gif)

Greetings from Ukraine!

**Comment by IvanSanchez** [comment]
Behaviour as expected.

Feel free to experiment with the `zoomSnap`, `zoomDelta`, and `wheelPxPerZoomLevel` options.

**Comment by KAMIKAZEUA** [comment]
@IvanSanchez can u please take a look https://github.com/gpxstudio/gpxstudio.github.io/issues/162#issuecomment-1131868740 ?

Maybe you missed something?
