### ISSUE TITLE
Display circles of the exactly specified radius independent of their latitude

### ISSUE THREAD

**Issue by nakigoe** [Leaflet/Leaflet#8253]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

![earthquakes](https://user-images.githubusercontent.com/35993388/169466903-d4ea1394-a42d-4860-8a29-af6b926fbb63.png)
Can't show that to one's boss.

This issue was reported many times on many sites without any meaningful solution for years.
GreatCircle plugin does not solve the issue, since it deals with circles on the map, not on the layer. 
I want circles on a layer to be able to turn them off inside the layer control.

### Expected behavior

Consistent radius of drawn circles across the globe.

### Current behavior

![earthquakes](https://user-images.githubusercontent.com/35993388/169466903-d4ea1394-a42d-4860-8a29-af6b926fbb63.png)
I know that's been Leaflet's default behaviour for years.
But **to the site visitors that's certainly a BUG**, and they do not care about any Mercator projection.

I'm sure smart folks like You can solve the many years issue of drawing a normal circle on a layer inside Leaflet map under 90 minutes or less. Making this new circle thing the default behaviour would be a great idea, and then there could be added an option to switch to Mercator projection. I bet very little people would actually use Mercator projection when it comes to drawing live data related circles on a map. 

### Minimal example reproducing the issue

http://maps.nakigoe.org

### Environment

- Leaflet version: 1.8
- Browser (with version): all of them
- OS/Platform (with version): all of them

**Comment by IvanSanchez** [comment]
Use `L.CircleMarker`.
