### ISSUE TITLE
leaflet-measure plugin broken with v1.8.0

### ISSUE THREAD

**Issue by agishk** [Leaflet/Leaflet#8258]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Click on Map for Measure, Map also shift with the point when leaflet is updated with LATEST version 1.8.0

### Expected behavior

Earlier when using old version, when we click on map and try to measure the something, then the map was not moving when user clicks on second point to complete the measure.

### Current behavior

In Leaflet 1.8.0 the map immediately jumps to a new location each time the map is clicked to create a measurement point. This behavior is easily reproachable by updating the demo to Leaflet 1.8.0. 

### Environment

- Leaflet version: 
- Browser (with version): 
- OS/Platform (with version):

**Comment by agishk** [comment]
@jonkoops @mourner @Falke-Design @Malvoz @johnd0e Can anyone look into this bug ASAP?

**Comment by Falke-Design** [comment]
Hi @agishk,
we maintain the Leaflet project in our free time and we don't get paid for that. So we will not prioritize this issue only because you say you need it ASAP.

If this issue is so important for you, why do you not fill out all fields while creating the issue? Without a [demo](leafletjs.com/edit.html) we can't do anything.

> Click on Map for Measure, 

Leaflet don't has a built in measure tool, so this is pretty sure a bug from a other tool or your code.

**Comment by agishk** [comment]
@Falke-Design Here is the jsfiddle URL: https://jsfiddle.net/hoagies/wqj1tkur/5/

**Comment by Malvoz** [comment]
For clarity: 
- Plugin used: https://ljagis.github.io/leaflet-measure/
- Issue: https://github.com/ljagis/leaflet-measure/issues/171

**Comment by agishk** [comment]
> For clarity:
> 
> * Plugin used: https://ljagis.github.io/leaflet-measure/
> * Issue: [Does not work in Leaflet 1.8.0 ljagis/leaflet-measure#171](https://github.com/ljagis/leaflet-measure/issues/171)

Yes , this is the plugin that is being used

**Comment by mourner** [comment]
This looks like a serious issue if this plugin became unusable with v1.8.0. Might have to do with the new `stop`/`preventDefault` system — can't think of anything else that could be this breaking. cc @Falke-Design

**Comment by adamb111** [comment]
Hi @agishk,
Probably you need to add `autoPanOnFocus: false` in file leaflet-measure.js
```
this._captureMarker = L.marker(this._map.getCenter(), {
   clickable: true,
   zIndexOffset: this.options.captureZIndex,
   opacity: 0,
   autoPanOnFocus: false
}).addTo(this._layer);
```

**Comment by Falke-Design** [comment]
I close this because it is a problem of the plugin.

Workaround:
```
L.Control.Measure.include({
	// set icon on the capture marker
	_setCaptureMarkerIcon: function () {
		// disable autopan
		this._captureMarker.options.autoPanOnFocus = false;

		// default function
		this._captureMarker.setIcon(
			L.divIcon({
				iconSize: this._map.getSize().multiplyBy(2)
			})
		);
	},
});

var measure = L.control.measure({}).addTo(map);
```
