### ISSUE TITLE
Some source code not reflected in published version

### ISSUE THREAD

**Issue by Kapcash** [Leaflet/Leaflet#8265]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. On current github sources, there is this line of code:

https://github.com/Leaflet/Leaflet/blob/399ed2105220f10b79e69b57420597e03502e611/src/map/Map.js#L206

This code's version is coming from [PR#6685](https://github.com/Leaflet/Leaflet/pull/6685/files#diff-f7c61cee5bee8604986cfce68530ef8df7316a4e93ea6a2ddfb6e97fa4234421).

2. **On npm repository**, the `/src/map/Map.js` file **doesn't include this code** (neither does the built `/dist` file): https://unpkg.com/leaflet@1.8.0/src/map/Map.js

I also checked on older version like 1.7.1 and 1.6.0.

**It looks like this [PR#6685](https://github.com/Leaflet/Leaflet/pull/6685/files#diff-f7c61cee5bee8604986cfce68530ef8df7316a4e93ea6a2ddfb6e97fa4234421) has been merged to the github sources, but is never deployed to production?**

### Expected behavior

I expect the production version published on npm to included all source code from Github (in the /dist folder as well as /src folder).

### Current behavior

The current code published to npm doesn't reflect all the source code present on Github. In particular the code merged by [PR#6685](https://github.com/Leaflet/Leaflet/pull/6685/files#diff-f7c61cee5bee8604986cfce68530ef8df7316a4e93ea6a2ddfb6e97fa4234421)

### Environment

- Leaflet version: 1.8.0
- Browser (with version): Vivaldi 5.2.2623.48
- OS/Platform (with version): MacOS BigSur 11.6

**Comment by Falke-Design** [comment]
Thank you for taking time to report this. But when you look on the release date of [1.8.0](https://github.com/Leaflet/Leaflet/releases/tag/v1.8.0) you will see, that #6685 is merged after the release. So everthing is as expected. The change will be in the next release 1.9.0. 
The `main` branch is not in sync with the lastest release.

**Comment by Kapcash** [comment]
🤦‍♂️ I just looked at the PR creation date, which is 2019. So I assumed it has been merged long time ago haha

Sorry for the inconvenence, and thank you for this very quick reply!
