### ISSUE TITLE
leaflet v1.8.0" javascript module could not be built in skypack

### ISSUE THREAD

**Issue by WTVader** [Leaflet/Leaflet#8266]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Got to https://www.skypack.dev/view/leaflet
Click on "Open in CodePen"
See Error "[Package Error] 'leaflet@v1.8.0' could not be built. "

### Expected behavior

For v1.7.1 everything works as expected: https://cdn.skypack.dev/leaflet@1.7

### Current behavior

<img width="979" alt="grafik" src="https://user-images.githubusercontent.com/1490138/169909550-931664c6-ef56-4be3-8402-22674078e316.png">

### Environment

- Leaflet version: 1.8.0
- Browser (with version): Firefox 100.0.2
- OS/Platform (with version): macOS 12.3.1

**Comment by IvanSanchez** [comment]
Skypack doesn't give any useful debug output, so it's impossible to tell what's going on behind the scenes.
