### ISSUE TITLE
I don't get update from Leaflet's repository

### ISSUE THREAD

**Issue by JollyBanny** [Leaflet/Leaflet#8268]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. Start `npm install leaflet@latest`
2. Open `node_modules/leaflet/dist/leaflet.css`
3. Look at the `655 line`
4. You see `color-adjust: exact;color-adjust: exact;`
5. But in repository `print-color-adjust: exact;`

### Expected behavior

```
DONE  Compiled successfully in 8606ms 

  App running at:
  - Local:   http://localhost:8080/ 
  - Network: http://192.168.0.12:8080/

  Note that the development build is not optimized.
  To create a production build, run npm run build.
```

### Current behavior

```
WARNING  Compiled with 1 warning                                                                                                                                                                                       05:09:17

 warning  in ./node_modules/leaflet/dist/leaflet.css

Module Warning (from ./node_modules/postcss-loader/dist/cjs.js):
Warning

(655:3) autoprefixer: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.

  App running at:
  - Local:   http://localhost:8080/ 
  - Network: http://192.168.0.12:8080/

  Note that the development build is not optimized.
  To create a production build, run npm run build.
```

### Environment

- Leaflet version: 1.8.0
- Browser: no matter 
- OS/Platform: Windows 11 laptop

**Comment by Malvoz** [comment]
Leaflet v1.8.0 was released [2022-04-18](https://github.com/Leaflet/Leaflet/blob/main/CHANGELOG.md#180-2022-04-18) and [`color-adjust` was changed](https://github.com/Leaflet/Leaflet/pull/8211) afterwards. The change will be available in the latest stable version once v1.9.0 has been released.

**Comment by sumeyradavran** [comment]
When is the release going to be? @Malvoz

**Comment by Falke-Design** [comment]
@sumeyradavran in the next months. We can't say a exact date

**Comment by sumeyradavran** [comment]
Same issue

**Comment by camilo-mujica** [comment]
Same error here

**Comment by cravend** [comment]
Following. Just FYI, the new version of create-react-app uses Webpack 5, so this will impact anyone on CRA/react-scripts.

**Comment by HomiG** [comment]
It Blocks All CI CD.

**Comment by RRGT19** [comment]
I have the same problem, we need a hotfix version, would be awesome.

**Comment by Radik24** [comment]
Hi, I found it to be an issue too. Hotfix would be great! Thanks
