### ISSUE TITLE
Use semver

### ISSUE THREAD

**Issue by jasperdunn** [Leaflet/Leaflet#8269]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

In my package.json

`"leaflet": "^1.7.1"`

### Expected behavior

I expect no breaking changes because of semver, which isn't being used here.
Please either use semver properly, or add to your docs in BIG letters that you **don't** use semver, so that builds don't suddenly fall over randomly.

Leaflet `1.8` has broken my build, it shouldn't have.

https://docs.npmjs.com/about-semantic-versioning

### Current behavior

My build fails because of the breaking changes.

### Environment

- Leaflet version: 1.7.1
- Browser (with version): Chrome latest
- OS/Platform (with version): Mac latest

**Comment by mourner** [comment]
> Leaflet 1.8 has broken my build, it shouldn't have.

Since you haven't provided any details on your issue except "it's broken", there's no way to address this in any way or even understand what exactly was breaking v1.8. Please do better.
