### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'latLngToLayerPoint')

### ISSUE THREAD

**Issue by JollyBanny** [Leaflet/Leaflet#8270]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [x] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.

### Steps to reproduce

1. Click on different markers
2. Get errors

I use Vue 3
Auxiliary library: [vue-leaflet](https://github.com/vue-leaflet/vue-leaflet)

![image](https://user-images.githubusercontent.com/46781610/170506931-670180a8-e5c1-41ba-87bf-40e392b5db98.png)

![image](https://user-images.githubusercontent.com/46781610/170506806-733cd27b-52ca-4de8-9112-451302c61911.png)

### Expected behavior

without error

### Current behavior

If you press on different markers, then after that, when the map is enlarged, the markers float away

Console:
```
Uncaught TypeError: Cannot read properties of null (reading 'latLngToLayerPoint')
    at NewClass._updatePosition (Tooltip.js?aac7:181:1)
    at NewClass.fire (Events.js?f754:190:1)
    at NewClass._move (Map.js?aacc:1241:1)
    at NewClass._onZoomTransitionEnd (Map.js?aacc:1708:1)
    at NewClass._catchTransitionEnd (Map.js?aacc:1639:1)
    at HTMLDivElement.handler (DomEvent.js?fab0:92:1)
```
Before this error I get warning 
```
listener not found (Events.js?f754:180)
```

### Environment

- Leaflet version: 1.8.0
- Browser (with version): no matter 
- OS/Platform (with version): no matter

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* NativeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.
