### ISSUE TITLE
Error in button Leaflet Jquery Dialog - mobile device

### ISSUE THREAD

**Issue by dungla2011** [Leaflet/Leaflet#8271]
### Checklist

- [ ] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [ ] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [ ] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Help me pls:
1. Goto https://galaxycloud.vn/train/open-street-map/005-test-dialog.php
2. Click on TopRight icon on MAP to open dialog
3.Error: it work on PC, but not work on mobile (testing in android, chrome)

![image](https://user-images.githubusercontent.com/7878963/170631623-1655ea3b-8714-4d32-898a-9d5bb55f4bae.png)

### Expected behavior

I need " top right button to open dialog" work on mobile (testing in chrome, android)

### Current behavior

It work well on pc, but not on chrome mobile

### Minimal example reproducing the issue

https://galaxycloud.vn/train/open-street-map/005-test-dialog.php

### Environment

Help me pls:

Leaflet version: 1.7.1, 1.8.0-beta.0
Browser (with version): Chrome 99.0.4844.82, Firefox 98.0.1
OS/Platform (with version): Windows 10 laptop

1. Goto https://galaxycloud.vn/train/open-street-map/005-test-dialog.php
2. Click on TopRight icon on MAP to open dialog
3.Error: it work on PC, but not work on mobile (testing in android, chrome)

![image](https://user-images.githubusercontent.com/7878963/170631623-1655ea3b-8714-4d32-898a-9d5bb55f4bae.png)

**Comment by IvanSanchez** [comment]
That's an issue with https://github.com/gregallensworth/L.Control.jQueryDialog , not with core Leaflet.
