### ISSUE TITLE
Access to the open source program of Browserstack.com

### ISSUE THREAD

**Issue by Falke-Design** [Leaflet/Leaflet#8297]
I registered us for the open source program of Browserstack and I hope we get a positiv answer.

The reseaon for the registration are the issues #7403 and #3575. We have different results in different browsers.

https://www.browserstack.com/open-source
![grafik](https://user-images.githubusercontent.com/19800037/174446256-def91434-6722-4387-b31f-0b5b06e9390e.png)

FYI: @mourner @IvanSanchez @Malvoz @jonkoops

**Comment by Falke-Design** [comment]
@mourner do you know something about an existing access to Browserstack?

> ![grafik](https://user-images.githubusercontent.com/19800037/174559688-81388353-102d-4579-a1af-a1ff6b4bea20.png)

**Comment by mourner** [comment]
@Falke-Design nope, no idea. I never used Browserstack myself.

**Comment by mourner** [comment]
@Falke-Design the response is very confusing. Let me ping them on Twitter, maybe they can elaborate...

**Comment by muditlambda** [comment]
If you wanna explore LambdaTest.com 
feel free to ping me back 😁

or drop a mail at support@lambdatest.com

https://www.lambdatest.com/open-source

**Comment by Falke-Design** [comment]
@muditlambda first bug in my code already found over your test suite 😄 I think LambdaTest has all what we need and is worth a try. Can you get us in the open source sponsoring?

We can discuss more over my mail design.falke@gmail.com

**Comment by Falke-Design** [comment]
Browserstack responsed too:
![grafik](https://user-images.githubusercontent.com/19800037/174856964-085eabc7-fd45-4293-aa15-06d759085c67.png)

**Comment by bigomega** [comment]
@Falke-Design The confusion was primarily because of another registration and sponsorship on the name of [Leaflet](https://github.com/Leaflet/Leaflet) from `kustalex5-at-gmail.com` on `2022-04-23`. Currently, we do not verify the open-source project ownership of the developer requesting access. We believe anyone can, and should-be-able-to contribute to any open-source project, so we trust developer and give them access. 

Thanks for bringing this to our attention regardless. Glad we're able to resolve this.

**Comment by Falke-Design** [comment]
@bigomega thank you for solving this!

**Comment by bigomega** [comment]
@mourner Yes, dealing with this abuse of open-source support is an ongoing battle. The price is usually paid by genuine open source devs. TravisCI [stopped their support](https://earthly.dev/blog/migrating-from-travis/) for OSS because of crypto miners.
