### ISSUE TITLE
Leaflet.js showing "Uncaught Error: Invalid LatLng object: (NaN, NaN)" when trying to process the data from sessionStorage

### ISSUE THREAD

**Issue by ayush572** [Leaflet/Leaflet#8314]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

I have a data.json file stored with me locally. Now when I am fetching it through the fetch API and converting it to the geojson format for displaying on the map, then it is working fine. Below is the attached photo
![image](https://user-images.githubusercontent.com/102132891/176113286-6c674de6-b56f-4fe2-abac-7257b5a63394.png)

But when I am using the data that has been saved in sessionStorage, then it is giving me the:
"**Invalid LatLng object: (NaN, NaN)**" error.
Here is the picture for the string stored in the sessionStorage:
![image](https://user-images.githubusercontent.com/77055883/176115474-4f79a636-9cb4-4a02-a46b-9036b38dd484.png)

Then before using the same, I have parsed the JSON string from session storage using let **session_data = JSON.parse(sessionStorage.getItem('converted_data'))**

And then, converted it into the GeoJSON format by:
**session_data.forEach((element)=>{
            geojsondata.push({
              "type": "Feature",
              "geometry": {
                "type": "Polygon",
                "coordinates": [[[parseFloat(`${element.left}`),parseFloat(`${element.top}`)],[parseFloat(`${element.right}`),parseFloat(`${element.top}`)],
                              [parseFloat(`${element.right}`),parseFloat(`${element.bottom}`)],[parseFloat(`${element.left}`),parseFloat(`${element.bottom}`)]]]
              },
              "properties": {
                "num_of_points": parseInt(`${element.num_of_points}`),
                "F":parseInt(`${element.F}`),
                "H":parseInt(`${element.H}`),
                "L":parseInt(`${element.L}`),
                "P":parseInt(`${element.P}`),
              }
            });
          });** 
and finally passed the data to **L.geoJSON(geojsondata)**. 

But then its not working and giving the error **Uncaught Error: Invalid LatLng object: (NaN, NaN)**

Photos are attached below:
![image](https://user-images.githubusercontent.com/77055883/176117704-1a3d90d0-99d9-4706-9f3c-a22479033f37.png)

This above array is the "geojsondata" array that has been converted and taken from sessionStorage...

 
![image](https://user-images.githubusercontent.com/77055883/176116557-5bce347a-213c-40a5-b7d7-7e9a887f10ca.png)

Above snippet displays the error that it is giving me. Below are the snippets for the code and the file structure...

![image](https://user-images.githubusercontent.com/77055883/176118209-11959b89-a172-4628-8d04-1b35e5345f13.png)
![image](https://user-images.githubusercontent.com/77055883/176118231-bf799c08-1c33-45c6-8cf6-81636196e7da.png)
![image](https://user-images.githubusercontent.com/77055883/176118172-9c015c00-ca10-472b-b8b9-d7d3d5c781de.png)
![image](https://user-images.githubusercontent.com/77055883/176118252-af5caf12-e655-4525-ba3f-98a6f7494e9a.png)
![image](https://user-images.githubusercontent.com/77055883/176118265-4ac41c89-4928-41bc-89f9-40e9472cc906.png)

What shall I do in this case...? I am developing an application for the organization but I am unable to solve this error...Please help! It has to be submitted by tomorrow...

### Expected behavior

I want the program to be able to take the data from the sessionStorage in the same way that it is dealing with the data stored with me locally, and display the map.

### Current behavior

Currently when I am taking the json data from the sessionStorage, that has the exact same format as of the data stored in the sessionStorage, parsing both of the datas using JSON.parse() and working on it, then I am seeing that when the data is fetched through the data.json file stored locally, then its working perfectly, but when I am trying to implement the same using the sessionStorage, then it is giving me the **Uncaught Error: Invalid LatLng object: (NaN, NaN)**

### Environment

- Leaflet version: leaflet@1.7.1
- Browser (with version): Brave browser [Version 1.40.107 Chromium: 103.0.5060.53 (Official Build) (64-bit)](https://brave.com/latest/)
- OS/Platform (with version): Windows 10 Home Single Language, version 21H1

**Comment by Falke-Design** [comment]
Please post one entry of `geojsondata` after parsing the file and one after parsing sessionStorage

**Comment by jonkoops** [comment]
Closing this due to lack of response and no reproducible example.
