### ISSUE TITLE
bug map._move parameter supressEvent be assigned Accidently

### ISSUE THREAD

**Issue by AMDvsTMD** [Leaflet/Leaflet#8316]
https://github.com/Leaflet/Leaflet/blob/4e0e97a6311e721a46699ae6e51f2c81ab348863/src/map/handler/Map.TouchZoom.js#L100 the moveFn here expect supressEvent  to be undefind but the next line `this._animRequest = Util.requestAnimFrame(moveFn, this, true);` 
according to requestAnimationFrame function description :
The callback method is passed a single argument, a [DOMHighResTimeStamp](https://developer.mozilla.org/en-US/docs/Web/API/DOMHighResTimeStamp), which indicates the current time (based on the number of milliseconds since [time origin](https://developer.mozilla.org/en-US/docs/Web/API/DOMHighResTimeStamp#the_time_origin)).
so supressEvent  will be assign to the DOMHighResTimeStamp

maybe this is a bug

**Comment by Falke-Design** [comment]
@AMDvsTMD wow very nice catch!
It would be nice if you can add a PR for this.
Change
```
var moveFn = Util.bind(map._move, map, this._center, this._zoom, {pinch: true, round: false});
```
to
```
var moveFn = Util.bind(map._move, map, this._center, this._zoom, {pinch: true, round: false}, undefined);
```
