### ISSUE TITLE
Tiles can no longer be loaded due to CORB error

### ISSUE THREAD

**Issue by ma7moudat** [Leaflet/Leaflet#8336]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

I'm currently in the process of migrating from another maps library to leaflet after I've done some research and got a very good impression of it. During my research I was replicating some of the demos to an Angular project (consider it a reproduction):
https://github.com/ma7moudat/leaflet-demos

Starting today, when running the local server for development, the map tiles never load because of a Cross-Origin Read Blocking error. I've tried with different environments and map tile providers (the one we normally use is maptiler).

The map tiles from maptiler still load with our current maps library, but for some reason with leaflet it doesn't anymore.

### Expected behavior

Tiles should load locally.

### Current behavior

Request to map tile provider is canceled due a Cross-Origin Read Blocking error (CORB).

Here's a screenshot of a component showing both leaflet and the old map library, the upper half is leaflet after it failed to load the tiles while the lower half shows that the old library successfully load the tiles from the same URL. The devtools network tab show 2 requests, the one initiated by leaflet fails and the CORB error is show in the console.

![image](https://user-images.githubusercontent.com/3257360/179014789-49219d76-3a9d-4137-b7bf-23748d5a9744.png)

### Minimal example reproducing the issue

https://plnkr.co/edit/94goKEnWHWrbzX02

### Environment

- Leaflet version: 1.8.0
- Browser (with version): Chrome 103 / Firefox 101
- OS/Platform (with version): Windows 10 / MacOS 12.4

**Comment by IvanSanchez** [comment]
In your REPL you're providing the URL of a `.json` file (`L.TileLayer('https://openmaptiles.github.io/osm-bright-gl-style/style-cdn.json')`) instead of a template to images. This falls into the "PEBCAK" category of problems.

Note that Leaflet has no built-in support for mapbox-style vector tile stylesheets (which is, supposedly, what that `.json` file is)
