### ISSUE TITLE
Type alias 'Geometry' circularly references itself

### ISSUE THREAD

**Issue by viniciussousa** [Leaflet/Leaflet#8338]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Expected behavior

Run my ionic project.

### Current behavior

I run npm install and made this error : Type alias 'Geometry' circularly references itself. I search and find the dependency @types/geojson has this error. How to solve this case? Tks!

![image](https://user-images.githubusercontent.com/15222529/179319025-0c81f01a-6b50-4f0b-b2f8-baa11fb073f7.png)

### Environment

- Leaflet version: 1.7.1
- Browser (with version): Chrome
- OS/Platform (with version): Chrome

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* NativeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.

**Comment by IvanSanchez** [comment]
In particular, note that there is no typescript anywhere in this repo.
