### ISSUE TITLE
popups do not use style of custom elements

### ISSUE THREAD

**Issue by AronSchoffer** [Leaflet/Leaflet#8355]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. Go to the leaflet editor example given below
2. Click on the two markers
3. The custom element my-popup should have a red background

### Expected behavior

That popups show the style of custom elements as they do with regular html elements.

### Current behavior

Popups do not show the style of custom elements themselves.
Any styled elements attached to the shadowroot of the custom element do get styled however.
So wrapping all children of the shadowroot in a div and styling the div works for now.

### Minimal example reproducing the issue

https://plnkr.co/edit/l6I7wnX6YQVfur2Q

### Environment

- Leaflet version: 1.8.0
- Browser (with version): Chrome 103.0.5060.134
- OS/Platform (with version): Windows 10 laptop

**Comment by IvanSanchez** [comment]
This is behaviour as expected. The contents of the popup are different from the popup itself.

Do read https://gis.stackexchange.com/q/285588/ .

**Comment by AronSchoffer** [comment]
I think I didn't use the right terminology.
The question you linked talks about the style of the popup itself.
What I tried to show with the example above is that the popup content isn't being styled when you pass a styled custom element to bindPopup(). The popup content _is_ being styled however, when you pass a styled html element (not a custom element) to bindPopup().
![image](https://user-images.githubusercontent.com/25392059/180761294-e09915a7-b2f5-4d00-acf1-d29bb96278e1.png)
![image](https://user-images.githubusercontent.com/25392059/180761497-9365045b-5b9f-4474-82bd-20667fada0f2.png)

**Comment by Malvoz** [comment]
@AronSchoffer Your example with `<my-popup>` is reproducible without Leaflet, as such not a Leaflet bug. How come you're styling `<p>` in one scenario but not the other? Otherwise, change `<my-popup>` to `display: block`.

**Comment by AronSchoffer** [comment]
Ah you're right. Thanks and my apologies, should have looked into it more before raising an issue.
