### ISSUE TITLE
#close being appended to URL

### ISSUE THREAD

**Issue by aeallord** [Leaflet/Leaflet#8356]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

bindPopup to a marker, open it and close the popup.

This product uses Ext JS framework and routing so #page is extremely important to maintain when the popup is closed.

### Expected behavior

URL should remain https://animap.us/#animaps

### Current behavior

URL changes to https://animap.us/#close

### Environment

- Leaflet version: 1.8
- Browser (with version): Firefox (102.0.1), Safari (15.5)
- OS/Platform (with version): Mac OS Monterey 12.4

**Comment by Falke-Design** [comment]
Already fixed in #8160 and will be released with 1.9.0

**Comment by dvdnhm** [comment]
> Already fixed in #8160 and will be released with 1.9.0

any eta on 1.9 release?
