### ISSUE TITLE
The site's dialog should be moved to localStorage from sessionStorage

### ISSUE THREAD

**Issue by ChristopherWirtOfficial** [Leaflet/Leaflet#8359]
### Checklist

- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this change hasn't been suggested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Motivation

I personally support everything the message says, but opening links from the docs in a new tab means new session storage, so the message pops up again. Content of the message aside, this is a truly disruptive behavior. 

### Suggested changes

Even if the behavior is to bring it up on brand new visits, this behavior can be accomplished without new tabs surfacing the message again. 

But the simplest solution is to move the flag from sessionStorage to localStorage

**Comment by IvanSanchez** [comment]
Sounds very reasonable. If you can do a PR against https://github.com/Leaflet/Leaflet/blob/main/docs/dialog/dialog.js (after having tested that using `localStorage` works as expected), it should be no problem to merge that.

ping @Malvoz

**Comment by jonkoops** [comment]
This seems like a reasonable request, would you be willing to implement this @ChristopherWirtOfficial?

**Comment by ChristopherWirtOfficial** [comment]
@jonkoops I'll be honest, the repo is set up in such a bespoke way, I have no idea how I'd "build it". The fix is 100% a string replacement of `sessionStorage` to `localStorage` because they are the same interface for the purposes of the dialog. 

I made a PR, but it's untested. To test, I would simply check that the dialog ack timestamp is set into localStorage and retrieved properly by not showing on a subsequent refresh. This is honestly enough to check both aspects of the simple dialog timestamp mechanism

**Comment by IvanSanchez** [comment]
> I'll be honest, the repo is set up in such a bespoke way, I have no idea how I'd "build it".

There are some instructions at https://github.com/Leaflet/Leaflet/blob/main/CONTRIBUTING.md#improving-documentation .

**Comment by Malvoz** [comment]
Fixed in https://github.com/Leaflet/Leaflet/pull/8382.
