### ISSUE TITLE
Implement test for 'panTo' method of Map

### ISSUE THREAD

**Issue by jonkoops** [Leaflet/Leaflet#8365]

**Comment by anurag-dhamala** [comment]
Thank you @jonkoops .

**Comment by anurag-dhamala** [comment]
Hi @jonkoops ,
Quick question. 
When I try, 

`map.panTo([83, 27], {zoom: 15});
console.log(map.getZoom());
`
Shouldn't it log 15 to the console? 

If it is so, then I think it should look like: 

`	panTo: function (center, options) { // (LatLng)
		return this.setView(center, options.zoom, {pan: options});
	}
`

I haven't investigated it in detail what issue it may cause by changing the existing panTo function. It's just my opinion.

**Comment by anurag-dhamala** [comment]
#8390 
Also, Here's a PR test implementation of panTo method of Map.
