### ISSUE TITLE
Implement test for 'stop' method of Map

### ISSUE THREAD

**Issue by jonkoops** [Leaflet/Leaflet#8369]

**Comment by adeeb18** [comment]
Hi I am a first time contributor. Could I try this issue, or one of the other testing issues? Do you have any insight on how I should write these tests?

**Comment by jonkoops** [comment]
@adeeb18 Sure, I assigned the issue to you. Take a look at the other tests PRs, they should give you an idea .

**Comment by adeeb18** [comment]
@jonkoops Still working on this one, I tried the panBy method https://github.com/Leaflet/Leaflet/issues/8366 to get a feel for it

**Comment by victorpatru** [comment]
Hey @jonkoops I'm unsure whether the previous assignee is still working on this issue. 

Would love to try to solve this issue myself!

**Comment by Falke-Design** [comment]
@victorpatru you can work on this
