### ISSUE TITLE
Implement test for 'addHandler' method of Map

### ISSUE THREAD

**Issue by jonkoops** [Leaflet/Leaflet#8372]

**Comment by jmakhack** [comment]
I am interested in picking up this issue if it is still available.

**Comment by shtelzerartem** [comment]
@jmakhack I'm sorry that I didn't write here before working, it's my first contribution, I was just trying out.

**Comment by jonkoops** [comment]
Since @shtelzerartem already opened up a PR I will assign this issue to him. Feel free to sign up for any other interesting issues!
