### ISSUE TITLE
Implement test for 'unproject' method of Map

### ISSUE THREAD

**Issue by jonkoops** [Leaflet/Leaflet#8374]

**Comment by shivamchourasia4** [comment]
I would like to work on this. Can you please assign this to me?

**Comment by Satyabrat-Ojha** [comment]
I would also like to contribute, can you please assign it to me?

**Comment by jonkoops** [comment]
I'm sorry, but someone already claimed this issue.

**Comment by Falke-Design** [comment]
@jonkoops I would say we remove the assignment, because nothing has done in the last 8 days. 
@Satyabrat-Ojha I will assign it to you, you have 1 week to make a PR, else I will remove the assignment. If you think you will not work on that, please let us know.

**Comment by jonkoops** [comment]
Sounds good to me @Falke-Design.

**Comment by Satyabrat-Ojha** [comment]
@Falke-Design @jonkoops I am stuck in the issue, can you help me out by providing some resources on how to implement test

**Comment by jonkoops** [comment]
@Satyabrat-Ojha I'd recommend taking a look at test related PRs that have [been merged before](https://github.com/Leaflet/Leaflet/pulls?q=is%3Apr+label%3Atests+is%3Aclosed). Also, feel free to open up a PR that is a work in progress if you are looking for early feedback.
