### ISSUE TITLE
this._source is not defined  (leaflet 1.8)

### ISSUE THREAD

**Issue by chocho11** [Leaflet/Leaflet#8389]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

with leaflet 1.8 that raises an exception : 
**this._source is not defined**
With leaflet 1.7 it  works well !

` if (lyr instanceof L.Marker || lyr instanceof L.KMLMarker   ) {
        console.log(e);
        e.target.openPopup(lyr);
      } `

### Expected behavior

displaying this popup of my marker when i click on it

### Current behavior

with leaflet 1.8 it raises an exception : this_source is not defined

but with leaflet 1.7 it works !

### Environment

- Leaflet version: 1.8
- Browser (with version): firefox 78.3.0esr (64 bits)
- OS/Platform (with version):  centos 6.9

**Comment by Falke-Design** [comment]
Please share a demo: https://leafletjs.com/edit.html

**Comment by Falke-Design** [comment]
Closing because of no response
