### ISSUE TITLE
L.geoJSON doesn't allow array of GeoJson with typescript check

### ISSUE THREAD

**Issue by ClementLong** [Leaflet/Leaflet#8394]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

With typescript type checking 

Work
`L.geoJSON(OneGeojson).addTo(myMap)`

Doesn't work : typescript doesn't expect array 
`L.geoJSON(arrayOfGeojson).addTo(myMap)`

Work fine : consistent with the documentation and javascript behavior 
```
// @ts-ignore
L.geoJSON(arrayOfGeojson).addTo(myMap)
```

### Expected behavior

L.geoJSON first params should allow type : ```Array<geojson.GeoJsonObject> | geojson.GeoJsonObject | undefined```

### Current behavior

L.geoJSON first params allow only ```geojson.GeoJsonObject | undefined```

### Environment

- Leaflet version: ^1.8.0
- Browser (with version): Chrome
- OS/Platform (with version): Ubuntu

I expect it's the good repository for typescript issue ?

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* NativeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.

**Comment by IvanSanchez** [comment]
Note that the leaflet typescript definitions are not in this repository.
