### ISSUE TITLE
Artifact publishing is broken

### ISSUE THREAD

**Issue by jonkoops** [Leaflet/Leaflet#8414]
The uploading of artifacts is [broken on CI](https://github.com/Leaflet/Leaflet/runs/7960936219) due to access issues. Probably some kind of token has expired.

**Comment by jonkoops** [comment]
@mourner could you take a look at this? I think we might have to update the secrets with a new token.

**Comment by mourner** [comment]
@jonkoops updated the secrets but it's still failing — will try to figure out what's going on tomorrow, maybe new S3 security policies at Mapbox...

**Comment by mourner** [comment]
@jonkoops BTW, I wonder if there's any way we could get rid of our dependence on that external S3 bucket? Is the ["Download Leaflet"](https://leafletjs.com/download.html) option something people use very often in the era of CDNs, package managers and bundlers? For published versions, we also put the download in GitHub Releases — we could link those. And for the current "development" version, maybe we could just remove the download link? Or upload to some place GitHub provides for for Actions?

**Comment by mourner** [comment]
It got fixed on the bucket side, but long term in would be nice to get rid of the reliance on it. https://github.com/Leaflet/Leaflet/runs/8053138474

**Comment by jonkoops** [comment]
Yeah, I agree. It doesn't make sense to keep our own bucket around with the wide availability of CDNs. Perhaps we can incorporate this into the V2 as a breaking change?
