### ISSUE TITLE
Addition of a search-bar in the "Docs"

### ISSUE THREAD

**Issue by Adithya-Sr** [Leaflet/Leaflet#8417]
### Checklist

- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this change hasn't been suggested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Which documents need updating?

https://leafletjs.com/reference.html

### Motivation

![image](https://user-images.githubusercontent.com/97578285/186688127-9c929cb2-aee6-40a7-891e-ccb7589fdde1.png)

Adding a search-bar would reduce the  time taken to search the individual methods in the docs .

### Suggested changes

Addition of  a search-bar at the top of the "Docs" page.

**Comment by mourner** [comment]
Since the docs are all on one page, can't you just use Ctrl-F (the built-in browser search)?

**Comment by Adithya-Sr** [comment]
> Since the docs are all on one page, can't you just use Ctrl-F (the built-in browser search)?

Sry  my bad , didn't think about that .
