### ISSUE TITLE
How leaflex sets the zindex layer order for geojason layers

### ISSUE THREAD

**Issue by defineconst** [Leaflet/Leaflet#8421]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Expected behavior

set geojson layer down or up layer zindex

### Current behavior

setZIndex dont work 

### Environment

Leaflet version: 1.7.1, 1.8.0-beta.0
Browser (with version): Chrome 99.0.4844.82, Firefox 98.0.1
OS/Platform (with version): Windows 10 laptop

**Comment by Malvoz** [comment]
Please see https://stackoverflow.com/questions/39767499/how-to-set-the-zindex-layer-order-for-geojson-layers.

**Comment by Falke-Design** [comment]
Duplicate of #8071

I would not say that we never implement this, so let us keep open #8071
