### ISSUE TITLE
When used on a website with `require-trusted-types-for 'script'` in its CSP, Leaflet doesn't load.

### ISSUE THREAD

**Issue by ThatBlockyPenguin** [Leaflet/Leaflet#8423]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. Add Leaflet to a HTML page
2. Serve that page with a Content Security Policy containing `require-trusted-types-for 'script'`
3. Watch as Leaflet proceeds to do nothing

### Expected behavior

I would expect Leaflet to work, by using a [Trusted Type Policy](https://developer.mozilla.org/en-US/docs/Web/API/TrustedHTML).

### Current behavior

Leaflet throws errors to the console and fails.

### Minimal example reproducing the issue

https://plnkr.co/edit/cFNoZ4Tlon9T3P5U

### Environment

- Leaflet version: 1.8.0
- Browser (with version): Google Chrome 104.0.5112.102
- OS/Platform (with version): Windows 11 21H2 22000.856

**Comment by PaulKotrik** [comment]
Hello @ThatBlockyPenguin ,
to fix this, please change from:
		`<meta http-equiv="Content-Security-Policy" content="require-trusted-types-for 'script'">`
to
		`<meta http-equiv="Content-Security-Policy-Report-Only" content="require-trusted-types-for 'script'">`

Let me know if this works.

Kind regards,
Paul Kotrik - Web Dev

**Comment by mourner** [comment]
Is there something on the Leaflet side that could change to address this, or is this all on the page setup side? I guess we'd have to close if there's nothing we can do about this, but let me know if the solution above doesn't work and this should be reopened.

**Comment by jonkoops** [comment]
We should be avoiding `innerHTML` as much as possible, but it is indeed still used in several places in the code. Feel free to open up a PR to remove one or more of these cases.

**Comment by shgysk8zer0** [comment]
Hi @ThatBlockyPenguin

It's about 6 months after the issue was posted, and I hope you've already found a solution. But, here's what I've had to do...

Trusted Types can have a default policy which is used whenever an "injection sink" is used with a regular string. I use the [Sanitizer API](https://developer.mozilla.org/en-US/docs/Web/API/Sanitizer) to create my default policies (note: it doesn't support SVG... All non-HTML/invalid HTML just gets dropped).

```js
const sanitizer = new Sanitizer();

trustedTypes.createPolicy('default', {
  createHTML: input => {
    const el = document.createElement('div');
    el.setHTML(input, { sanitizer });
    return el.innerHTML;
  }
});
```

Using this works for me, though using `Sanitizer` is a bit limiting. You can create a default policy that fits your needs, though it might not be easy to get it exactly right.

**Comment by ronnievdc** [comment]
As of Chrome version 119 the `Sanitizer` is not included anymore: https://developer.chrome.com/blog/sanitizer-api-deprecation/
