### ISSUE TITLE
In the latest version, the canvas element is added to the map, and the map positioning effect appears when clicking on the element.

### ISSUE THREAD

**Issue by lhs1478** [Leaflet/Leaflet#8434]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1.First, I used the L.divIcon property to add the canvas element to the map, you can see this element in the map, even though the element is transparent (there will be a change in the gesture of moving the mouse into the element).
2.Once you find the element, move the center of the element out of the view area, then click on the element and you will see the map start to move, trying to move the center of the element back into view.
3.This problem does not occur in version 1.7.1.

### Expected behavior

My expected situation should be that if I don't do anything with the canvas element, no matter how I click on this element or double-click on this element, nothing will happen

### Current behavior

The current situation is that when I don't do anything with the canvas element, after I move the center of the element out of my view, click anywhere on the element, and the map will move, making the center of the element reappear in my view. in view

### Minimal example reproducing the issue

https://plnkr.co/edit/FUnUcVJUFTdEuIgN?preview

### Environment

- Leaflet version: 1.8.0
- Browser (with version): Chrome 105.0.5195.102 (official release) (64-bit)
- OS/Platform (with version): Windows 10 laptop

**Comment by Falke-Design** [comment]
Add `autoPanOnFocus: false` to your marker:
```
  L.marker([33, 121], {
    icon: myIcon,
    autoPanOnFocus: false
  }).addTo(map);
```
