### ISSUE TITLE
Tooltips throw exceptions when using vector shapes with the canvas renderer after #8247

### ISSUE THREAD

**Issue by alex4401** [Leaflet/Leaflet#8442]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. Use latest `main` (9d1a841 at the time of creating this issue)
2. Set up a map with canvas renderer and a vector shape, like a rectangle.
3. Bind a tooltip to the vector. _Check JS console._
4. Move mouse over the vector. _Check JS console._
5. Move mouse out of the vector. _Tooltip does not disappear._

### Expected behavior

Tooltip does not fail to initialise or when reacting to events. They do not require DOM elements to function.

### Current behavior

Exceptions thrown on: tooltip initialisation, mouse events due to `getElement` calls introduced in #8247 671ebdf on a canvas-rendered shape (`getElement` is defined on the class, but has no element to return).

### Minimal example reproducing the issue

https://codepen.io/alex4401/pen/XWqpKMW

### Environment

- Leaflet version: main `9d1a841`
- Browser (with version): Firefox 104.0.2, but got user reports from all other browsers
- OS/Platform (with version): Arch Linux

**Comment by IvanSanchez** [comment]
Can confirm.

**Comment by Malvoz** [comment]
Quite an oversight, should be fixed in https://github.com/Leaflet/Leaflet/pull/8251 by utilizing Canvas Sub DOM for accessible vectors:

![leaflet-canvas-sub-dom](https://user-images.githubusercontent.com/26493779/192141747-587c7399-8dcb-4fe6-a47a-d270c6818231.png)

/cc @alekzvik

**Comment by jonkoops** [comment]
This seems like something we might want to consider back-porting a fix for, WDYT? Also is `1.9.1` affected?

**Comment by alex4401** [comment]
> Also is `1.9.1` affected?

Yup: https://codepen.io/alex4401/pen/VwxrJaQ

**Comment by jonkoops** [comment]
Thanks for checking @alex4401.

**Comment by jonkoops** [comment]
@Malvoz do you think we could back-port #8369 and include only the fix for this issue, without also including the new functionality?

**Comment by moosetraveller** [comment]
I came across with a similar issue by using `addData` when using a canvas, a separate overlay pane, and a tooltip. I assume that the issue's origin is the same source than for this issue. If my assumption is correct and if #8490 will be fixed with the bugfix for this issue, please feel free to close #8490.

**Comment by alex4401** [comment]
Yeah, that's the exact same stack trace I had. Forgot to include it above.

**Comment by mourner** [comment]
@jonkoops should we release v1.9.2 without the fix, or wait until this gets resolved? Not sure how involved this would be.

**Comment by Falke-Design** [comment]
@mourner @jonkoops I will share tomorrow morning a fix

**Comment by mourner** [comment]
Just make a v1 PR, we can cherry-pick later

**Comment by Falke-Design** [comment]
@mourner @jonkoops I think 1.9.2 is ready

**Comment by jonkoops** [comment]
@Falke-Design Yeah, I am going to go ahead and prep the release.
