### ISSUE TITLE
npm install leaflet doesn't bring you the latest dist/leaflet.css file, making autoprefixer fail

### ISSUE THREAD

**Issue by bnthor** [Leaflet/Leaflet#8445]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

- Run `npm install -D leaflet` in a fresh project
- Open `node_modules/leaflet/dist/leaflet.css`
- Go to line **655** and
- see that there is `color-adjust` instead of `print-color-adjust` like this is the case in the github repo

### Expected behavior

We should have the latest CSS, with `print-color-adjust` on line 655

### Current behavior

Instead of which, we have `color-adjust`

### Environment

- Leaflet version: 1.8.0

**Comment by jonkoops** [comment]
This change has not been released yet, so that's why it's not present in the NPM package.
