### ISSUE TITLE
addCircleMarkers radius smaller than 1

### ISSUE THREAD

**Issue by jay-sf** [Leaflet/Leaflet#8449]
Hi, thanks for maintaining leaflet!

I wonder how I might get a better control of the circle radius. Depending on the zoom factor it can get pretty clumpy. How is it possible to get smaller circles, say 1/2 or 1/4 the size? I tried values smaller than 1, but decimal resolution doesn't seem to be possible. Please see example below.

![Rplot27](https://user-images.githubusercontent.com/32597794/191709884-0afb5c7c-5efa-4c64-a19a-2f6aa503c11a.png)

```
co <- replicate(20, c(-74.04456199608506, 40.68923184725649)) + replicate(20, rnorm(2, .0001, .0001))
m <- leaflet() %>% 
  addTiles("https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png") %>%
  setView(-74.045, 40.689, zoom=14)
m$x$options <- append(m$x$options, list("zoomControl"=FALSE))
m %>%
  addCircleMarkers(co[1, ], co[2, ], radius=1, color='white')

```

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* NativeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.

**Comment by IvanSanchez** [comment]
By the looks of it, you're using R, not vanilla javascript.

**Comment by jay-sf** [comment]
@IvanSanchez Ah, yes I am working R focused and didn't realize yet that Leaflet actually bases on Java Script. Thanks for taking the time to point me in the right direction.

**Comment by jay-sf** [comment]
I have moved this [there](https://github.com/rstudio/leaflet/issues/818#issue-1382276819).

**Comment by taniamendo** [comment]
Hi Ivan, Did you figure out how to make the radius smaller?
