### ISSUE TITLE
Leaflet 1.9.0 breaks Leaflet Markercluster

### ISSUE THREAD

**Issue by indigoxela** [Leaflet/Leaflet#8450]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Switching from Leaflet 1.8 to 1.9 breaks the Markercluster click event.

Nothing in the console, no errors, but no cluster-related event on the cluster marker. Instead it seems to have a "focus" event. But expanding a cluster doesn't work anymore.

I'm aware that this might eventually be a Markercluster bug, but at least it deserves some backwards compatibility considerations in Leaflet core.

### Expected behavior

Clicking on a Markercluster should expand it and zoom in.

### Current behavior

Nothing at all.

Note that with tabbing I can get a focus on that icon.

### Minimal example reproducing the issue

http://olga.indigofloat.at/bugdemo/demo.html

### Environment

- Leaflet version: 1.9.0
- Browser (with version): Firefox ESR (91.12.0esr), Chromium (104.0.51)
- OS/Platform (with version): Linux

**Comment by mourner** [comment]
Oh, definitely needs to be backwards-compatible — let us investigate and do a quick 1.9.1 with a fix.

**Comment by mourner** [comment]
Bisected — this was broken by #8161. @Falke-Design should we try to find a quick fix for this, or just revert the PR for v1.9.1?

**Comment by Falke-Design** [comment]
Let me look into it

**Comment by Falke-Design** [comment]
So far I found that it is because of the `listens` change.

Also I found that Markercluster overwrites the default function: https://github.com/Leaflet/Leaflet.markercluster/blob/cf09b65d77e88bbc7219aba0b947b97020a8db01/src/MarkerClusterGroup.js#L816

**Comment by Falke-Design** [comment]
Found the error, it is because of propagation and fallback for old versions:

https://github.com/Leaflet/Leaflet/blob/e4c8f645bef74aa76e91400f0481a73deeda92fb/src/core/Events.js#L219-L223

```
 if (typeof fn !== 'function' && propagate === undefined) { 
```

I will create tests and a PR in 4 hours, should be home then

**Comment by cptpiepmatz** [comment]
Even with the patch in 1.9.1 I still get the error in my angular application.
