### ISSUE TITLE
Leaflet 1.9 breaks Leaflet.heat

### ISSUE THREAD

**Issue by Sergiobop** [Leaflet/Leaflet#8451]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

First of all, thanks for your work!

The steps to reproduce the issue is just updating leaflet to 1.9 and use the leaflet.heat package. (https://github.com/Leaflet/Leaflet.heat)
I also use the @types/leaflet and @types/leaflet-heat packages.

### Expected behavior

This worked before 1.9.0:
```
import * as L from 'leaflet';
import 'leaflet.heat';
....

const heatmapLayer = L.heatLayer(data, { radius: 15, max: 10, minOpacity: 0.75 });

```

### Current behavior

The app breaks and produces the following error:
```
export 'heatLayer' (imported as 'L') was not found in 'leaflet' (possible exports: Bounds, Browser, CRS, Canvas, Circle, CircleMarker, Class, Control, DivIcon, DivOverlay, DomEvent, DomUtil, Draggable, Evented, FeatureGroup, GeoJSON, GridLayer, Handler, Icon, ImageOverlay, LatLng, LatLngBounds, Layer, LayerGroup, LineUtil, Map, Marker, Mixin, Path, Point, PolyUtil, Polygon, Polyline, Popup, PosAnimation, Projection, Rectangle, Renderer, SVG, SVGOverlay, TileLayer, Tooltip, Transformation, Util, VideoOverlay, bind, bounds, canvas, circle, circleMarker, control, default, divIcon, extend, featureGroup, geoJSON, geoJson, gridLayer, icon, imageOverlay, latLng, latLngBounds, layerGroup, map, marker, noConflict, point, polygon, polyline, popup, rectangle, setOptions, stamp, svg, svgOverlay, tileLayer, tooltip, transformation, version, videoOverlay)
```

### Environment

- Leaflet version: 1.9.0
- Browser (with version): All
- OS/Platform (with version): All

**Comment by Falke-Design** [comment]
@jonkoops can you look into this?

**Comment by jonkoops** [comment]
Sure, I'll take a look :+1:

**Comment by jonkoops** [comment]
I've created this [example project](https://github.com/Leaflet/Leaflet/files/9626850/leaflet-playground.zip) which reproduces the issue using Vite. The issue comes from the way Leaflet is imported:

```ts
import * as L from 'leaflet'
```

Since this imports all of the [named exports](https://github.com/Leaflet/Leaflet/blob/0716af266f5bde0aa9d7bdaa6bc1f51cb3e7dcea/src/LeafletWithGlobals.js#L2) APIs from Leaflet, but not the global [`L`](https://github.com/Leaflet/Leaflet/blob/0716af266f5bde0aa9d7bdaa6bc1f51cb3e7dcea/src/LeafletWithGlobals.js#L5) (which is the default export) `L.heatLayer` can not be found.

I managed to fix this issue by importing the default export instead:
```diff
-import * as L from 'leaflet'
+import L from 'leaflet'
```

**Comment by jonkoops** [comment]
This is still a backwards compatibility issue however, although I don't think there is a way we can fix this elegantly. The only way I can see this working is by removing the module entry point. There is no way to augment the [namespaced import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#namespace_import) from a module that imports it.

**Comment by jonkoops** [comment]
The way I see it we can resolve this two ways:

1. Add migration notes to our release for users that are using the namespaced import.
2. Remove the entrypoint to the ECMAScript module version from the package and release a patch.

I'm leaning towards the first, even though it's a breaking change for users of namespaced import. The reason for this is that it allows a migration path to the next major version, which will drop support for other module systems.

However, other core team members might feel differently. Especially if this ends up impacting too many users. @mourner @Malvoz @Falke-Design WDYT?

**Comment by mourner** [comment]
> I'm leaning towards the first, even though it's a breaking change for users of namespaced import. The reason for this is that it allows a migration path to the next major version, which will drop support for other module systems.

Yeah, I think it makes sense. The plugins working with a namespaced import is already a hack that shouldn't have been working in the first place, and gives the illusion of proper ES with tree-shaking even though it doesn't tree-shake at all.

I'd move the ESM changelog item under "Breaking changes" and add a note about plugin compatibility. But I don't really know how much of a pain point this would be so let's wait for other opinions.

**Comment by Falke-Design** [comment]
I see a little bit the problem with unmaintained plugins. What if we publish to sources like before with `.esm.js`?

**Comment by jonkoops** [comment]
Ahh, as in plugins that might be using the namespaced import method already? Yeah, those could indeed exist, but I have no idea how many. A lot of existing 'legacy' plugins all seem to rely on the global `L`, which should remain compatible (even in 2.0).

**Comment by mourner** [comment]
Should we do a quick v1.9.1 with the `listens` fix before we decide on this one, and do a v1.9.2 later if necessary? Or should we wait?

**Comment by Falke-Design** [comment]
https://github.com/search?q=%22import+*+as+L+from+%27leaflet%27%3B%22&type=code 

"import * as L from 'leaflet';" --> 12,945 code results 😶

**Comment by Falke-Design** [comment]
> Should we do a quick v1.9.1 with the listens fix before we decide on this one, and do a v1.9.2 later if necessary? Or should we wait?

Yes I think that would be good.
But if you guys think you find a solution in the next hours, it is also ok for me to wait. I need to go now, but I think you can handle this without me 😄

**Comment by jonkoops** [comment]
Yeah, let's do a quick release before we decide what to do here. Sounds good to me.

**Comment by mourner** [comment]
v1.9.1 released.

**Comment by jonkoops** [comment]
@Sergiobop could you verify that the fixes I mentioned above also work for you? I'd like to make sure that it's not just 'works on my machine'.

**Comment by Sergiobop** [comment]
Hey @jonkoops 

Option 1:
`import L from 'leaflet'` 

My IDE and app complains:
```
Module '"..../node_modules/@types/leaflet/index"' has no default export. 
```


Option 2:
`import 'leaflet';`

My IDE and app complains when i use L.
```
TS2686: 'L' refers to a UMD global, but the current file is a module. Consider adding an import instead.
```

**Comment by jonkoops** [comment]
Thanks for checking @Sergiobop. So the first problem is likely issue due to the fact that `@types/leaflet` not yet being updated to reflect the changes in Leaflet.

You might be able to work around this by following the instructions in https://github.com/Leaflet/Leaflet/issues/8467#issuecomment-1256294293.

**Comment by SamuelGaona** [comment]
Same with GeometryUtil from leaflet-draw

**Comment by Falke-Design** [comment]
@jonkoops @mourner what is the plan now? What should we do? I think it is not ok, to make that big breaking change in 1.9

**Comment by jonkoops** [comment]
We could revert this work in a patch release and then re-introduce it in 2.0. It looks like this is creating too much fallout.

**Comment by jonkoops** [comment]
For those impacted, could you try out the fix from #8493 and see if it works for you? Alternatively going into `node_modules/leaflet` and removing the `module` field from `package.json` should be enough to verify this fix.

**Comment by mourner** [comment]
@jonkoops do you want to do the v1.9.2 release some time soon?

**Comment by jonkoops** [comment]
Yeah, I'd like to do it ASAP. I don't have time to get to it today, so if someone wants to go ahead now feel free. Just make sure all the critical stuff is cherry-picked on `v1` (which I think I already did).

**Comment by VashJuan** [comment]
Not suggesting a change of approach here, just noting other options that some of us have resorted to.

For me, to get 1.9.x working, I searched on the error and came up with workaround:
[old] myMarkerCluster = L.markerClusterGroup()
[new] myMarkerCluster = new window.L.MarkerClusterGroup()

Best explained at:
https://stackoverflow.com/a/71574063/18004414

Other possibly relevant discussions:
https://stackoverflow.com/questions/48960970/using-umd-globals-with-modules-in-a-typescript-project
