### ISSUE TITLE
@types/leaflet@1.9.0 doesn't exist?

### ISSUE THREAD

**Issue by VashJuan** [Leaflet/Leaflet#8452]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

`npm update @types/leaflet`
doesn't do anything

### Expected behavior

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/leaflet
doesn't show a 1.9.0 version yet.

### Current behavior

Life is perfect - Leaflet is super! A new leaflet 1.9.0 is incredible news.

### Environment

- Leaflet version: 1.9.0
- Browser (with version): Chrome latest
- OS/Platform (with version): Windows 10 Pro

**Comment by mourner** [comment]
At the moment, the TypeScript types are maintained by the community, not the Leaflet team. I guess they will need a few days to catch up with the new release.
