### ISSUE TITLE
`FirefoxNoTouch` & ``FirefoxTouch` jobs are flaky

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#8454]
I had to rerun these jobs a bunch of times today — they seem to be extra flaky lately. Worth investigating.

**Comment by mourner** [comment]
Example failed job: https://github.com/Leaflet/Leaflet/actions/runs/3107063425/jobs/5034728955

**Comment by Falke-Design** [comment]
Or https://github.com/Falke-Design/Leaflet/actions/runs/3107093741/jobs/5034793690

```
Firefox 104.0 (Ubuntu 0.0.0) Popup "before each" hook in "Popup" FAILED
	done() called multiple times in hook <Popup "before each" hook in "Popup">; in addition, done() received error: Error: TypeError: el is undefined (src/LeafletWithGlobals.js:2538)
```

**Comment by mourner** [comment]
Most of the failures seem to be related to popup code for some reason. Here's another:

```
Chrome Headless 105.0.5195.102 (Linux x86_64) Popup L.Map#openPopup should not be closen when dragging map FAILED
	Error: Uncaught TypeError: Cannot read properties of undefined (reading '_leaflet_pos') (src/LeafletWithGlobals.js:2538)
```

**Comment by mourner** [comment]
Another common error looks like this:

```
Firefox 104.0 (Ubuntu 0.0.0) Popup L.Map#openPopup should not be closen when dragging map FAILED
	TypeError: el is undefined (src/LeafletWithGlobals.js:2538)
```

The intermittent failures are getting really bad, to the point that nearly any PR or commit will likely fail, so we have to do something about it. @Falke-Design @jonkoops any idea when it started doing this and how we can go about tracking this down?

**Comment by jonkoops** [comment]
Yeah, this is getting quite excessive. We'll have to get this stabilized ASAP.

**Comment by mourner** [comment]
It's possible that this is related to #8464 and could be fixed by #8478 🤞 At least all the tests surprisingly pass in that PR.

**Comment by mourner** [comment]
Looks like it's stable again now after #8478. Will reopen if it still happens

**Comment by jonkoops** [comment]
What a strange bug, I wonder why these animations impact the tests so much.
