### ISSUE TITLE
Typo in docs (lon -> lng)

### ISSUE THREAD

**Issue by vagran** [Leaflet/Leaflet#8461]
Seems like typo in reference doc:
```
< map.panTo({lon: 30, lat: 50})
> map.panTo({lng: 30, lat: 50})
```
https://github.com/Leaflet/Leaflet/blob/29606c37b42b40576da4c5a42747270312cacaf4/docs/reference.html#L19250

**Comment by jonkoops** [comment]
Feel free to open up a PR to fix this 😄

**Comment by plainheart** [comment]
I guess it might be not a typo but a tip for indicating it is also compatible with `lon`? See also https://github.com/Leaflet/Leaflet/blob/main/src/geo/LatLng.js#L131

**Comment by vagran** [comment]
> I guess it might be not a typo but a tip for indicating it is also compatible with `lon`? See also https://github.com/Leaflet/Leaflet/blob/main/src/geo/LatLng.js#L131

OK, I see. But in such case seems it should somehow be reflected in the documentation. Probably here:
https://github.com/Leaflet/Leaflet/blob/29606c37b42b40576da4c5a42747270312cacaf4/docs/reference.html#L19287
May be something like "`lon` property works as well which is alias for `lng`" or similar.

**Comment by jonkoops** [comment]
Hmmm, interesting. I am curious why we'd be transforming this, perhaps it's something we can remove for v2.

**Comment by Falke-Design** [comment]
Task: Replace `lon` with `lng`

**Comment by jonkoops** [comment]
This was actually a feature, not a typo in the docs. Regardless, if we remove the docs we should probably also remove the implementation, so I've created #8506 to take care of that.
