### ISSUE TITLE
Running tests locally on ChromeHeadless/Mac only runs half of them

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#8464]
When I'm running `npm test` locally on my Mac machine, it only runs half of the tests and acts as if that's OK:

```
Chrome Headless 105.0.5195.125 (Mac OS 10.15.7): Executed 527 of 1059 (skipped 8) SUCCESS (3.908 secs / 2.019 secs)
TOTAL: 527 SUCCESS
```

What's going on? There are no errors, no excessive skips, it just doesn't execute half the tests for some reason. When I run other browsers like `npm test -- --browsers Safari` it runs all of them, so it must be specific to `ChromeHeadless`. I'm not sure how long it's been this way but it's super confusing.

@Falke-Design @jonkoops any idea what's going on? Does it act like this for you too?

**Comment by Falke-Design** [comment]
Is working for me with the newest master:

![grafik](https://user-images.githubusercontent.com/19800037/191935449-018d6533-eac3-4234-9559-99658bee9826.png)

**Comment by mourner** [comment]
@Falke-Design I see you're on Windows... So it might be Mac-related.

**Comment by mourner** [comment]
I bisected this particular problem, surprisingly, to your #8433 @Falke-Design. Not sure what exactly triggers early exist from the test suite but I'll try disabling unit tests one by one to see which one does it.

**Comment by Falke-Design** [comment]
Not good to here :( 

Maybe the loop without a `done()` causes the break?

https://github.com/Leaflet/Leaflet/blob/509c655b8204052b20d4bd65e6cad24cb0b3b75c/spec/suites/geometry/LineUtilSpec.js#L144-L157

```
function check() { 
 		expect(layer.getCenter()).to.be.nearLatLng([50.49998323576035, 30.50989603626345]); 
 		i++; 
 		if (i < 30) { map.setZoom(i); } 
} 
map.on('zoomend', check); 
```

**Comment by mourner** [comment]
@Falke-Design looks like it's triggered by the `LineUtilSpec` tests, they're unstable — probably due to some race condition between `before/afterEach` and the custom remove/map init? There's also a lot of repetition. This needs to be refactored...

**Comment by mourner** [comment]
OK found a quick solution for now, committing...
