### ISSUE TITLE
`wheelPxPerZoomLevel` unit test always fails on Mac 

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#8479]
The last unit test in `Map.ScrollWheelZoomSpec.js` added by @Falke-Design always fails for me locally on Mac:

```
Firefox 105.0 (Mac OS 10.15) Map.ScrollWheelZoom changes the option 'wheelPxPerZoomLevel' FAILED
	Error: expected 1 to be above 1 (node_modules/expect.js/index.js:96)
```

We should figure out if it's expected to fail and fix either the behavior of the test, making it more platform-agnostic.

**Comment by mourner** [comment]
@Falke-Design Experimentally, the test only passes when you set `wheelPxPerZoomLevel = 13` on my Macbook. So should we do so, or does this test need more fundamental changes?

**Comment by Falke-Design** [comment]
@mourner can you share the output of the console of https://plnkr.co/edit/eecQ7iqySIccbB0X?preview after scrolling one step

**Comment by mourner** [comment]
@Falke-Design I don't have a mouse, but scrolling on a trackpad says this:

User-agent | 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Ap…KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36'
-- | --
Leaflet | '1.9.1'
Win | false
Gecko | false
Chrome | true
Edge | false
Safari | false
Retina | true
wheelDeltaY | 6
deltaMode | 0
deltaY | -2
deltaX | -2
deltaZ | 0
wheelDelta | 6
detail | 0
devicePixelRatio | 2
Zoom delta | 0

**Comment by Falke-Design** [comment]
Does it still fail in Firefox or only in Chrome?

> Firefox 105.0 (Mac OS 10.15) Map.ScrollWheelZoom

> Chrome Headless 105.0.5195.125 (Mac OS 10.15.7) Map.ScrollWheelZoom

**Comment by mourner** [comment]
@Falke-Design fails the same way in Firefox.
