### ISSUE TITLE
Github release does not include dist/ files

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#8492]
Spin off from discussion https://github.com/Leaflet/Leaflet/discussions/8491 .

### Expected behavior

The github release for 1.8.0 has a `.zip` file containing the `dist/` files (the rolled-up `leaflet-src.js`, etc):

![image](https://user-images.githubusercontent.com/19800037/192979625-b9a2aefe-1abb-485c-abf9-fc5587dba31d.png)

### Current behavior

The 1.9.x release does not:

![image](https://user-images.githubusercontent.com/19800037/192979720-13e9321e-9b60-4c08-b526-47ad04859791.png)

...and thus is confusing some users.

**Comment by IvanSanchez** [comment]
I recall some (old) release instructions that included branching and tagging for the release - and including the `dist/` files in that git branch+tag. Unfortunately my memory of that is a bit vague.

Not sure if we want to follow that model, or if we want to amend the release instructions to add the "put a `.zip` in the github release" instead.

**Comment by Falke-Design** [comment]
@mourner @jonkoops

**Comment by jonkoops** [comment]
We never had any automation to upload these artifacts, I believe that @mourner added these manually. These artifacts are exactly the same as the ones [uploaded to the site](https://leafletjs.com/download.html).

I've uploaded the files for the latest releases, which should avoid confusion for now. That said, I think we should stop doing this for the 2.0+ releases.

**Comment by jonkoops** [comment]
If anyone can update the release instructions with this extra step, I think we can then close this issue.

**Comment by Falke-Design** [comment]
>  That said, I think we should stop doing this for the 2.0+ releases.

What are the contra of adding it to the release, so that we don't want this anymore?
In my eyes the pros are:
- Each Github Release has any information which is needed to work with the release. The build files and the source files of the project
- Users are still using it for importing. (Is this bad practice?)

**Comment by jonkoops** [comment]
> What are the contra of adding it to the release, so that we don't want this anymore?

It's a manual step that duplicates something that already exists on the website.

> Users are still using it for importing. (Is this bad practice?)

If that works for them that's fine, even if there are better methods available.
