### ISSUE TITLE
Add a check to our CI to make errors in jekyll visible

### ISSUE THREAD

**Issue by Falke-Design** [Leaflet/Leaflet#8502]
![](https://user-images.githubusercontent.com/19800037/193394640-e7c1e197-ccbe-4a59-b25e-dc5957e01f4e.png)

[Local usage of jekyll](https://github.com/Leaflet/Leaflet/blob/main/CONTRIBUTING.md#improving-documentation)

**Comment by exequiel09** [comment]
@Falke-Design  Question on this issue, do you mean adding a check entry on PR requests like on this picture? 
![Screen Shot 2022-10-01 at 7 25 56 PM](https://user-images.githubusercontent.com/1289472/193407284-7a26fb2d-e912-4d0d-8455-fd58174399b3.png)

**Comment by Falke-Design** [comment]
yes exactly over github workflow

**Comment by exequiel09** [comment]
Can I take a stab on this?
