### ISSUE TITLE
Remove transformation of `lon` in `toLatLng()`

### ISSUE THREAD

**Issue by jonkoops** [Leaflet/Leaflet#8506]
The `toLatLng()` function [transforms objects](https://github.com/Leaflet/Leaflet/blob/87cbaf8a2d23c8296a863e30f57d597180f98bb0/src/geo/LatLng.js#L130) with a `lon` key to a `LatLng` instance. This seems like an edge case that was added and probably now be removed.

The documentation for this was already removed under #8461.

**Comment by jonkoops** [comment]
@mourner can I get your opinion on this? Not quite sure why this was added originally.

**Comment by mourner** [comment]
I think this was intentional, for compatibility, because it doesn't really hurt and "lon" is an extremely common way to designate longitude in various data. I think it's worth keeping.

**Comment by jonkoops** [comment]
Personally I am not a fan of this kind of implicit and undocumented behavior. But I guess we can keep it around if it helps keep things compatible. Closing.

**Comment by mourner** [comment]
We could document it better too

**Comment by mourner** [comment]
@jonkoops found the original discussion for this with some justification in #1412 (almost a 10-year-old ticket!)

**Comment by jonkoops** [comment]
> We could document it better too

Yeah, agreed. I've created #8509 to take care of it.
