### ISSUE TITLE
Document transformation of `lon` in `toLatLng()`

### ISSUE THREAD

**Issue by jonkoops** [Leaflet/Leaflet#8509]
The `toLatLng()` function [transforms objects](https://github.com/Leaflet/Leaflet/blob/87cbaf8a2d23c8296a863e30f57d597180f98bb0/src/geo/LatLng.js#L130) with a `lon` key to a `LatLng` instance. This behavior is undocumented and documentation should be written for it.

See #8506, #8461 and  #1412 for background information.

**Comment by brianferry** [comment]
I can take a look at this if you would like to assign it to me

**Comment by harshit-dugar** [comment]
If this is not yet resolved please assign me @jonkoops

**Comment by jonkoops** [comment]
I believe @brianferry is already working on this.

**Comment by mourner** [comment]
Fixed in #8524
