### ISSUE TITLE
Layer.control: background-color of the label

### ISSUE THREAD

**Issue by xGen** [Leaflet/Leaflet#851]
I need to paint Layer.control Labels in any colors. i don`t find it and made this:
L.Control.Layers = L.Control.extend({

```
_addItem: function (obj, onclick) {
    var label = document.createElement('label');
    label.setAttribute('style','background-color: '+this.options[obj.name]);
    ...
}
```

And when I call map.addControl, I add my Options
map.addControl(new L.Control.Layers({'Google':glmap},{'OSM':osmlmap, 'circle': CircleLayer}, {Google:'#FF0000', OSM:'#FFFF00', circle:'#FF00FF'}));

Maybe somebody take an advantage of this.

**Comment by valeriodeluca** [comment]
Hi mourner, hi guys,
I want to add more toggle layer.control and it's ok in this way:
var L1 = new L.control.layers(baseMaps,{..
var L2 = new L.control.layers({},{..
So now I'd like differnt image for each layer.control. I mean this png:
Leaflet-master\dist\images\layers.png
how can I set layer1.png, layer2.png,layer3.png for each control.layer?
Tks so much
best
valerio
