### ISSUE TITLE
Add Windows and MacOS to the testing matrix

### ISSUE THREAD

**Issue by Falke-Design** [Leaflet/Leaflet#8510]
I suggest to add new workflows:
- [ ] Running tests on Safari
- [ ] Running tests on Chrome + Mac
- [ ] Running tests on Chrome + Windows
- [ ] Running tests on a Retina screen (window.devicePixelRatio = 2)

**Why Chrome?**
Because the other Browsers already tested on a Linux system and with testing Chrome on Windows & Mac we include the biggest part of the users.

@mourner @jonkoops is this possible and do we want this?

**Comment by jonkoops** [comment]
I remember trying this and running into some issues, although I don't quite remember what was blocking. This should be possible by restoring the matrix for operating systems that was removed under #8264.

Perhaps we also want to test on Windows?

**Comment by Falke-Design** [comment]
> Perhaps we also want to test on Windows?

Good point. 

I added https://github.com/Leaflet/Leaflet/labels/hacktoberfest, maybe there are some devs with knowledge out there.

**Comment by jonkoops** [comment]
Sounds good to me :+1:

**Comment by sidverma32** [comment]
I am new to this repository, can i get a headsup like from where to begin? 
As per the above discussion what i understood is to add tests for windows and macos in this file (`.github/workflows/main.yml`). Correct me if am wrong or missing something? @Falke-Design

**Comment by Falke-Design** [comment]
We are runnning our tests with karma / mocha. For how to run tests look [here](https://github.com/Leaflet/Leaflet/blob/main/CONTRIBUTING.md#running-the-tests).

> add tests for windows and macos in this file `(.github/workflows/main.yml).`

Yes we need windows and macos and also Safari.


Have you experience with creating workflows?
