### ISSUE TITLE
Add Animation

### ISSUE THREAD

**Issue by ImArnoldDCODES** [Leaflet/Leaflet#8511]
### Checklist

- [X] I've searched through the [plugins](https://leafletjs.com/plugins.html) to make sure this feature isn't already available, or think it shouldn't require a plugin.
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this feature hasn't been requested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Motivation

It doesn't have any animation on scroll or when loaded

### Suggested solution

I will love to add animations when a user loads the web

**Comment by Falke-Design** [comment]
You can create a Plugin but we will not implement a loader animation.

Look into the [PLUGIN GUIDE](https://github.com/Leaflet/Leaflet/blob/main/PLUGIN-GUIDE.md).
