### ISSUE TITLE
Leaflet documentaion not available from Russia. I`m citizen of Kazakhstan.

### ISSUE THREAD

**Issue by anvarious97** [Leaflet/Leaflet#8515]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Expected behavior

Documentation is available.

### Current behavior

Documentation not available. I am not a soldier. Not military. I don't fight. Didn't kill any Ukrainian. Against any war. Against everything bad and for everything good. Why can't I access documentation?

### Environment

- Leaflet version: 
- Browser (with version): 
- OS/Platform (with version):

**Comment by Falke-Design** [comment]
We block no one, it must be your provider. Try it over the internet archiv: https://web.archive.org/web/20220930012052/https://leafletjs.com/reference.html

**Comment by anvarious97** [comment]
I`m sorry. Peace for everyone.

**Comment by frutik** [comment]
>  I`m citizen of Kazakhstan.

Is this excuse to work/contribute to russian economy?
