### ISSUE TITLE
Extract eslint configuration

### ISSUE THREAD

**Issue by krau5** [Leaflet/Leaflet#8530]
### Checklist

- [X] I've searched through the [plugins](https://leafletjs.com/plugins.html) to make sure this feature isn't already available, or think it shouldn't require a plugin.
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this feature hasn't been requested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Motivation

Hey there!

I like to spend my evening casually scrolling any repos that are seemed interesting to me.
And throughout my career I always thought that everything has its own goals and reasons.

What am I talking about? I am talking about `eslintConfig` inside of `package.json`.

As for me, `package.json` is a _package_ configuration file, not a _linter_ but a _package_ and there's a clear difference which shouldn't be explained.

### Suggested solution

I propose to extract ESLint configuration from `package.json` to a separate config without changing any of the rules. I want to be assigned to this issue, so that I can create a PR as soon as possible.

By the way, I want to ask, would you like to add any new rules?
Just in case, 'cause I do not know if you have any agreements regarding the code style.

Thanks for the attention!

**Comment by mourner** [comment]
No.

**Comment by krau5** [comment]
Okay

**Comment by jonkoops** [comment]
I do want to clean up the ESLint config over time, but that will come naturally with refactoring as we go.

**Comment by krau5** [comment]
It's fine :)
