### ISSUE TITLE
Dark mode extension

### ISSUE THREAD

**Issue by rjortikka** [Leaflet/Leaflet#8531]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. Download google chrome dark mode
2. Go to leaflet on google chrome
3. Put the dark mode extension on
4. The map goes black and nothing can be seen

### Expected behavior

I expected it to work normally with dark mode on.

### Current behavior

The map goes black

### Environment

- Leaflet version: 1.9.1
- Browser (with version): Google Chrome
- OS/Platform (with version): Windows 11

**Comment by Malvoz** [comment]
Which extension is that exactly? What goes black? The background? The controls? Everything? Icons should be inverted so that shouldn't be a problem.

Extensions can override pages' CSS, are you expecting Leaflet to override those injected styles?

**Comment by Malvoz** [comment]
https://github.com/Leaflet/Leaflet/issues/7577 is somewhat related, but it's about new default styles based on user preferences from the OS/UA settings.

**Comment by jonkoops** [comment]
I don't think we can account for what browser extensions might do to the map. If anything that is a bug in that specific extension, not Leaflet itself.

I'm closing this issue.

**Comment by Falke-Design** [comment]
@rjortikka please tell us anyway which extension it was. Also a Screenshot would be very helpful.

I would like to take a quick look, maybe I find something. And then I can inform the extension developer.

**Comment by rjortikka** [comment]
The extension:
https://chrome.google.com/webstore/detail/dark-mode/dmghijelimhndkbmpgbldicpogfkceaj
Also pictures of normal map and with extension on.

to 6. lokak. 2022 klo 13.00 Florian Bischof ***@***.***>
kirjoitti:
