### ISSUE TITLE
Crash on DivOverlay.js when using Leaflet as esm module

### ISSUE THREAD

**Issue by wwwouaiebe** [Leaflet/Leaflet#8533]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Go to the src file src/layer/DivOverlay.js at line 45 and remove the L. before LatLng so the complete line will be

if (options && (options instanceof LatLng || Util.isArray(options))) {...

Leaflet crash when directly imported using import directive.

### Expected behavior

Everything normal...

### Current behavior

The program crash...

### Environment

- Leaflet version: 1.9.2
- Browser (with version): Firefox Nightly 107
- OS/Platform (with version): Windows 10

**Comment by mourner** [comment]
Yeah, looks like this is an omission made in #7783 (@Falke-Design) — we shouldn't access any objects through the `L` global in the source, and this should be enforced at the lint level. cc @jonkoops
