### ISSUE TITLE
Incorrect marker popupopen event e.target reference

### ISSUE THREAD

**Issue by plarner30** [Leaflet/Leaflet#8558]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

[https://codepen.io/philiplarner/pen/zYjyGdY](https://codepen.io/philiplarner/pen/zYjyGdY)

1. Hover the red marker (A)

### Expected behavior

It should raise an alert referencing marker A as it does in older versions of leaflet? 

To see please adjust the leaflet version 1.7.1 ("Settings" in the header > "Pen Settings" > "JS" and adjust version number)

### Current behavior

The alert from marker A references marker B

### Minimal example reproducing the issue

https://codepen.io/philiplarner/pen/zYjyGdY

### Environment

- Leaflet version: 1.9.2
- Browser (with version): Chrome
- OS/Platform (with version): Windows 10

I think there is an issue with leaflet "popupopen" event starting at version 1.8.0. When you programmatically close a popup and open it, triggering the "popupopen" event on a specific marker when it opens: the event target doesnt match what the event was bound on? N.B this is when all markers share the same popup instance

**Comment by Belair34** [comment]
Looking into this a bit. In case it's useful to anyone, the problem arises between these 2 commits:
61eb5f1dcacac1a3bfe716dd74dbc9d5bfb75e32 - first bad
f018e2de2ce507ab9b070f382e6bded9b9311263 - last good
If the triage determines that this is indeed an issue, then I'd like to use it for a hackathon.

**Comment by jonkoops** [comment]
Yeah, this seems like a possible regression we should fix. @johnd0e it looks like the aforementioned commit was yours, do you have an idea what might be causing this?

**Comment by Belair34** [comment]
I think I have a solution with a test to back it up. If possible I'd like to save this issue for a student hackathon on November 5th, however I see there is a blocker tag so if this needs to be done ASAP I can make a PR right away.

**Comment by Falke-Design** [comment]
5th of November is quite long, so it would be better to have it earlier.

**Comment by plarner30** [comment]
> 5th of November is quite long, so it would be better to have it earlier.

@Falke-Design sorry for noise, just wondering if there might still be an update sooner than this date

**Comment by Falke-Design** [comment]
I hope so ... @jonkoops @mourner we should prepare the release 1.9.3 - a few cherry picks needs to be done

**Comment by jonkoops** [comment]
Yeah I think it's time. @Falke-Design could you create an issue to track the release?
