### ISSUE TITLE
Pan with keyboard and dragging with mouse gives different result when passing dateline

### ISSUE THREAD

**Issue by NielsHolt** [Leaflet/Leaflet#8560]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Hi
_If I add map1.on('moveend', function(event){  console.log('moveend lng=',this.getCenter().lng); });_
and drag the map passed the dateline (lng=180) I get (almost) the correct mapCenter, but if I pan the map using the keyboard I get lng > 180 if I pan west to east. See attached video

### Expected behavior

I would expect the resulting lng to be the same, and also < 180

### Current behavior

https://user-images.githubusercontent.com/11357972/195583584-02b474d7-eaf0-4572-bd69-299740b1fc87.mov

### Environment

- Leaflet version: 1.9.2
- Browser (with version): Chrome
- OS/Platform (with version): Windows

**Comment by Falke-Design** [comment]
This is the expected result.

You can enable [worldCopyJump](https://leafletjs.com/reference.html#map-worldcopyjump) to prevent this.

**Comment by Falke-Design** [comment]
This only happens if [worldCopyJump](https://leafletjs.com/reference.html#map-worldcopyjump) is enabled
