### ISSUE TITLE
Include option for Feedback and create an OSM Note

### ISSUE THREAD

**Issue by angoca** [Leaflet/Leaflet#8572]
### Checklist

- [X] I've searched through the [plugins](https://leafletjs.com/plugins.html) to make sure this feature isn't already available, or think it shouldn't require a plugin.
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this feature hasn't been requested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Motivation

Many web sites use Leaflet, and the map users/viewers could identify errors in the base map (invalid names, changed features). However, there is not an option for the user to report this issue directly into the map producer.

### Suggested solution

When the base map is OpenStreetMap, it would be a good idea to have the option for "feedback" or "report an error" option, like a link next to contributors text (currently next to the Ukranian flag).
Once clicked, a popup could appear to describe the error in the base map. Once click on send, the website calls the URL to the OSM API, by using: https://wiki.openstreetmap.org/wiki/API_v0.6#Map_Notes_API

Leaflet could add some extra information in the comment, like "Created by Leaflet" (similar to MAPS.ME or onosm.org), and other context stuff to help "note resolver people" better understand the context of the note (like the website name).

### Alternatives considered

This option could be developed from the website designer, but it is something related to all website.

**Comment by IvanSanchez** [comment]
As much as I love OSM (I was even in the board of OSMF back then!), I think this is out of the scope of Leaflet, and should be implemented by web authors instead. Or perhaps a plugin.

The current architecture of `L.TileLayer` does not welcome this kind of provider-specific behaviour. Please do remember that Leaflet is tile-provider-agnostic.
