### ISSUE TITLE
Allow for offset on center of map.

### ISSUE THREAD

**Issue by zzolo** [Leaflet/Leaflet#859]
Hi.  It would be super awesome to be able to offset the center of the map relative to the viewport.  My main use case is that I have a large box overlaying the map on the left, and would like the center of the map to be more to the right.  This means that when I do a pan or center, it would actually be offset a certain amount of pixels or percentage of viewport.  This would be a map level setting.

I have wanted this feature in many JS mapping libraries but have not found it yet.  Unfortunately, it needs to be pretty low level in the API.

Sorry, I don't have any code, was just thinking about and wanted to get it down.

Thanks for the awesome project!

**Comment by cazacugmihai** [comment]
Is there a solution also for the zoom in/out actions? 

I'm using something like this:

```javascript
        var MapCenterOffsetMixin = {
            getMapOffset: function() {
                console.log('getMapOffset');
                return [$('#left-panel').offset().left, 0];
            },
            getBounds: function(){
                console.log('getBounds');
                var offset = this.getMapOffset(),
                    bounds = this.getPixelBounds(),
                    sw = this.unproject(new L.Point(bounds.min.x + offset[0], bounds.max.y + offset[1]), this._zoom, !0),
                    ne = this.unproject(new L.Point(bounds.max.x, bounds.min.y), this._zoom, !0);

                return new L.LatLngBounds(sw, ne)
            },
            _oldLatLngToNewLayerPoint: L.Map.prototype._latLngToNewLayerPoint,
            _latLngToNewLayerPoint: function (latlng, newZoom, newCenter) {
                console.log('_latLngToNewLayerPoint');
                var offset = this.getMapOffset(),
                    targetPoint = this.project(newCenter, newCenter).subtract([offset[0] / 2, offset[1] / 2]);
                newCenter = this.unproject(targetPoint, newZoom);

                return this._oldLatLngToNewLayerPoint(latlng, newZoom, newCenter);
            },
            _getCenterLayerPoint: function () {
                console.log('_getCenterLayerPoint');
                var offset = this.getMapOffset();
                return this.containerPointToLayerPoint(this.getSize().divideBy(2).add([offset[0] / 2, offset[1] / 2]));
            },
            _oldResetView: L.Map.prototype._resetView,
            _resetView: function (center, zoom, preserveMapOffset, afterZoomAnim) {
                console.log('_resetView');
                var offset = this.getMapOffset(),
                    targetPoint = this.project(center, zoom).subtract([offset[0] / 2, offset[1] / 2]);
                center = this.unproject(targetPoint, zoom);

                this._oldResetView(center, zoom, preserveMapOffset, afterZoomAnim);
            }
        };
        L.Map.include(MapCenterOffsetMixin);
```
but it fails on zooming.

**Comment by cazacugmihai** [comment]
Here is the solution: https://github.com/Mappy/Leaflet-active-area. Brilliant! :)

**Comment by cduzan** [comment]
The 'map.fitBounds(bounds, topLeftPadding, bottomRightPadding)' function seems to be using values to adjust lat long, not pixels. So different levels of zoom will have different results on how far the map is adjusted. I'm sure there is a use case for this, but it seems like for the issue everyone is bringing up, a set size side-bar or top menu, that the adjustment shouldn't depend on zoom level. Is there a built-in leaflet function that adds padding based on pixels rather than coordinates?

**Comment by louh** [comment]
`topLeftPadding` and `bottomRightPadding` expect values in pixels: http://leafletjs.com/reference.html#map-fitboundsoptions

**Comment by cduzan** [comment]
For some reason that doesn't seem to be the case for me. To test this out I center a marker at a zoom level of 15 and then a run this command...
`map.fitBounds(pointsArray, {paddingTopLeft: [0,0], paddingBottomRight: [800,0], maxZoom: map.getZoom()});`
Then I set the zoom level to 19 and run it again. At level 15 it is almost unnoticeable the amount it shifts. However, at level 19, it shift over about half the page. Am I doing something wrong in my function call?
