### ISSUE TITLE
Tooltips are not added to dom, when moving the map (or later)

### ISSUE THREAD

**Issue by BasieP** [Leaflet/Leaflet#8591]
Hi there,

I want to report a bug.

We work with a realtime system, that adds markers (with sometimes tooltips) on the map based on incomming data.
A user reported a bug that sometimes items didn't have labels (tooltips), so we investigated.

Turns out, that markers that have a tooltip, don't add the tooltip when you are moving the map. The marker itself gets added, but the tooltip doesn't.
I have a simple testcase here (I abuse the moveend event to add a marker):
https://jsfiddle.net/76otz9bw/5/

The following code is the problem:
```
    _openTooltip: function (e) {
        if (!this._tooltip || !this._map || (this._map.dragging && this._map.dragging.moving())) {
            console.log('  leaving cause you are dragging... solong suckers');
            return;
        }
        this._tooltip._source = e.layer || e.target;

        this.openTooltip(this._tooltip.options.sticky ? e.latlng : undefined);
    }
```

The return statements gets hit, but there is no fallback scenario. It doesn't get added later as it should.

I can imagine a fix something along the lines of:

```
    _openTooltip: function (e) {
        if (!this._tooltip || !this._map) {
            return;
        }

        if (this._map.dragging && this._map.dragging.moving())) {
            this._map.on('zoomend', ()=> {
                this._openTooltip(e);
            });
        }
        this._tooltip._source = e.layer || e.target;

        this.openTooltip(this._tooltip.options.sticky ? e.latlng : undefined);
    }
```
(i know horrible code, but you get the idea)

**Comment by addy** [comment]
You could also bind the tooltip after you've added the marker to your map. I think there is a "race-condition" (based on current dragging state) that is occurring in your case.

Essentially, constructing the tooltip ahead of time should fix the issue.

```js
let marker;
let tooltip;
map.addLayer(L.marker(duesseldorf).bindTooltip('not a berlinner', ttOptions));
map.on('moveend', () => {
  if (marker) {
  	map.removeLayer(marker);
  }
  
  tooltip = L.tooltip(ttOptions).setContent('a berlinner');
  marker = L.marker(belowDuesseldorf);
  
  map.addLayer(marker);
  
  marker.bindTooltip(tooltip);
});
```

**Comment by addy** [comment]
> Well it's definitely not a race condition, since javascript is single threaded and the leaflet lib doesn't use async. see also https://en.m.wikipedia.org/wiki/Race_condition

That's why I had race-condition in quotes :P
