### ISSUE TITLE
Code smell - Lint configuration for unused function params

### ISSUE THREAD

**Issue by JohnnyMoonlight** [Leaflet/Leaflet#8598]
### Checklist

- [ ] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Not a bug, more a linting/readability issue: function calls with unnecessary parameters are allowed.

See this example:
GridLayer.js calls in line [399](https://github.com/Leaflet/Leaflet/blob/2daebbb4390b8e52c0b8c7bfc2074fe577f8bf73/src/layer/tile/GridLayer.js#L396) falseFn() with a parameter:
`Util.falseFn(level.el.offsetWidth);`

falseFn() das not expect a parameter Util.js, line [92](https://github.com/Leaflet/Leaflet/blob/2daebbb4390b8e52c0b8c7bfc2074fe577f8bf73/src/layer/tile/GridLayer.js#L396).
`export function falseFn() { return false; }`

The code works, but for clarity the usage of unnecessary parameters should be restricted through linting rules.

### Expected behavior

eslint should be configured to warn about function calls with unnecessary parameters.

### Current behavior

eslint ignores unnecessary parameteres in function calls.

### Environment

- Leaflet version 1.9.2

**Comment by mourner** [comment]
This code is written like this intentionally. We need to read `offsetWidth` to force relayout, without using the actual value and avoid any related linting rules or treeshaking removal.
