### ISSUE TITLE
Double click on an input element that is rendered on the leaflet map

### ISSUE THREAD

**Issue by nickbosland** [Leaflet/Leaflet#8631]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Perform a double click on the input element and move the mouse between the clicks within the input.

It might require a few tries to do it, but it should be fairly easy to reproduce

### Expected behavior

That the error does not happen

### Current behavior

An error is thrown in the console:

```
Permission denied to access property "bind"
```

Image of the error:

![image](https://user-images.githubusercontent.com/705345/199021032-918545ef-b0e4-4552-b2cc-38108ec72695.png)

### Minimal example reproducing the issue

https://codesandbox.io/s/amazing-oskar-c0cxuc

### Environment

- Leaflet version: 1.8.0, 1.9.0, 1.9.1, 1.9.2
- Browser (with version): Firefox >= 105
- OS/Platform (with version): Windows 11, MacOS 12.6.1

### Extra info

- This issue does not happen on Chrome/Edge

Edit: added the `Extra info` section

**Comment by IvanSanchez** [comment]
Can't reproduce on Linux (in either Firefox 106 and Chromium 106), Leaflet 1.9.2. I'm using https://plnkr.co/edit/NbRtpHyrzuotD3oV .

**Comment by IvanSanchez** [comment]
Problem's gotta be at:

https://github.com/Leaflet/Leaflet/blob/6b90c169d6cd11437bfbcc8ba261255e009afee3/src/dom/DomEvent.DoubleTap.js#L15-L18 

That's the same code that copies all properties of a native DOM event into a synthetic event, triggering #7078.

**Comment by Falke-Design** [comment]
Another solution would be to skip `originTarget` because it is only supported by Firefox and is still experimental.
https://developer.mozilla.org/en-US/docs/Web/API/Event/originalTarget
