### ISSUE TITLE
Locally built leaflet package does not initialize correctly

### ISSUE THREAD

**Issue by igorshmukler** [Leaflet/Leaflet#8647]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

0. switch to NodeJS version 16. [My guess other versions have the same issue. I was unable to build 1.9.2 with older [v12 and/or v14] versions of NodeJS.
1. execute `npm install`
2. execute `npm run build`
3. optionally execute `npm publish` after adding `publishConfig`to the registry and scoping the package name eg `@private/leaflet`

### Expected behavior

I expect to get a package similar to the one published to the npm registry. However, it seems that the package transpiled differently. Specifically, for Leaflet 1.9.2 from `npm`, the result is:
```
_updateCircle: function (layer) {
    var p = layer._point,
        r = Math.max(Math.round(layer._radius), 1),
        r2 = Math.max(Math.round(layer._radiusY), 1) || r,
        arc = 'a' + r + ',' + r2 + ' 0 1,0 ';

    // drawing a circle with two half-arcs
    var d = layer._empty() ? 'M0 0' :
        'M' + (p.x - r) + ',' + p.y +
        arc + (r * 2) + ',0 ' +
        arc + (-r * 2) + ',0 ';

    this._setPath(layer, d);
},
```
My package has the same function transpiled to:
```
_updateCircle(layer) {
    const p = layer._point,
        r = Math.max(Math.round(layer._radius), 1),
        r2 = Math.max(Math.round(layer._radiusY), 1) || r,
        arc = `a${r},${r2} 0 1,0 `;

    // drawing a circle with two half-arcs
    const d = layer._empty() ? 'M0 0' :
        `M${p.x - r},${p.y
        }${arc}${r * 2},0 ${
            arc}${-r * 2},0 `;

    this._setPath(layer, d);
},
```

### Current behavior

I don't really care about the ECMAScript version. Modern browsers understand both. My issue is with the package initialization. The package that leaflet built for me locally, fails to initialize. For example, I cannot import plugins. The below is the code:
```
import * as L from 'leaflet';

import 'leaflet-editable-marker';
import '@geoman-io/leaflet-geoman-free';
import 'leaflet-toolbar';

import '@geoman-io/leaflet-geoman-free/dist/leaflet-geoman.css';
import 'leaflet-toolbar/dist/leaflet.toolbar.min.css';
import 'leaflet/dist/leaflet.css';

console.log('leaflet editable marker:', L.EditableMarker);
```
Is working just fine with regular `1.9.2` and it prints:
```
leaflet editable marker: ƒ () {
      setOptions(this); // call the constructor

      if (this.initialize) {
        this.initialize.apply(this, arguments);
      } // call all constructor hooks


      this.callInitHooks();
```
When I use the homebrew package, it does:
```
Attempted import error: 'EditableMarker' is not exported from 'leaflet' (imported as 'L')
```
and
```
leaflet editable marker: undefined
```

### Environment

- Leaflet version: 1.9.2
- Browser (with version): Chrome 106.0.5249.119 (Official Build) (x86_64)
- OS/Platform (with version): MacOS 10.14.6

**Comment by igorshmukler** [comment]
@jonkoops 
would you consider the below reproducible example:
1. nvm use v16
2. git clone https://github.com/Leaflet/Leaflet.git
3. cd Leaflet
4. npm install
5. npm run build
6. npm publish

plus, please scope the below [unless you don't want to do the publish] with something:
```
import * as L from '@scope/leaflet';

import 'leaflet-editable-marker';
import '@geoman-io/leaflet-geoman-free';
import 'leaflet-toolbar';

import '@geoman-io/leaflet-geoman-free/dist/leaflet-geoman.css';
import 'leaflet-toolbar/dist/leaflet.toolbar.min.css';
import '@scope/leaflet/dist/leaflet.css';

console.log('leaflet editable marker:', L.EditableMarker);
```
It makes no difference whether the publish step is performed.

**Comment by jonkoops** [comment]
Right, but the environment matters, such as what build tool is used (and what version). Also if you aren't publishing the package or using `npm link`, then how does your custom Leaflet end up in the project?

Honestly, if I had to guess that is probably where the issue is.

**Comment by igorshmukler** [comment]
How come my build is transpiled into a different ECMAversion and what can I do to have the build work the same as one LeafletJS "team" uses for NPM? This is deterministic and completely unrelated to the URL or the package name I use for `npm publish`, right?

**Comment by IvanSanchez** [comment]
I must point out that is a cross-post of a [stackoverflow question](https://stackoverflow.com/questions/74366837/leaflet-linked-from-github-fails-to-initialize) from a few days ago. Posting on stackoverflow, not getting an answer, and then cross-posting as a bug report is a pattern that I frown upon.

The thing here is that the error is not within the Leaflet build, but about how a plugin (re-)uses the `L` namespace - which has been a problem (https://github.com/Leaflet/Leaflet/issues/7454, https://github.com/Leaflet/Leaflet/discussions/7729#discussioncomment-1577037). But instead of focusing on that and trying to debug it, OP has decided to rant on the build. This is not being productive right now and I'm tempted to just close the issue.

**Comment by igorshmukler** [comment]
Just puzzles me that nobody would want to see whether the main branch builds, yet not my business really.

In order for me to get the thing to build a valid package, I just needed:
```
  git clone https://github.com/Leaflet/Leaflet.git
  cd Leaflet/
  git checkout tags/v1.9.2 -b v1.9.2-branch
  nvm use v16
  npm i
  npm run build
  cp dist/leaflet-src.js ../maps-designer/node_modules/leaflet/dist/
  cp dist/leaflet-src.js.map ../maps-designer/node_modules/leaflet/dist/
  ```
  
  The main might be fixed now, or not. I was able to fork off 1.9.2 and take it from there.
