### ISSUE TITLE
Can't drag or transform polygon in Vue 3 project

### ISSUE THREAD

**Issue by rizypb** [Leaflet/Leaflet#8648]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

- Computer
  - MacOS BigSur 11.6.1
  - Ram 8 GB
- Version
  - vue: 3.2.41
  - leaflet: 1.7.1
  - leaflet-path-transform: 1.1.1

1. Go to leaflet js map on Vue 3 frontend 
2. Try to drag the polygon
3. Then an error will be thrown: 
```
Uncaught Error: Invalid LatLng object: (NaN, NaN)
```
<img width="664" alt="Screen Shot 2565-11-10 at 10 49 22" src="https://user-images.githubusercontent.com/81729843/200999534-39425aaa-032d-4f1a-8416-0befbc4003b9.png">

<img width="993" alt="Screen Shot 2565-11-10 at 10 49 16" src="https://user-images.githubusercontent.com/81729843/200999527-d4e46307-15cc-4fa8-bf53-3762fa184031.png">

4. If you try to resize / transform the polygon then another error will be thrown: 
```
Uncaught TypeError: Cannot read properties of null (reading ‘lat’)
```
<img width="495" alt="Screen Shot 2565-11-10 at 10 47 32" src="https://user-images.githubusercontent.com/81729843/200999673-81af3907-004b-46ec-9544-f6adc98c4444.png">

<img width="995" alt="Screen Shot 2565-11-10 at 10 47 23" src="https://user-images.githubusercontent.com/81729843/200999667-11d066fe-7eff-4b85-a267-6946e86607b3.png">

### Source Code
```
import L from 'leaflet';
import 'leaflet-path-transform';
import 'leaflet/dist/leaflet.css';

const map = L.map('map').setView([0, 0], 2);
  L.tileLayer('https://{s}.tile.openstreetmap.de/tiles/osmde/{z}/{x}/{y}.png', {
    attribution:
      '&copy; <a target="_blank" href="http://osm.org/copyright">OpenStreetMap</a> contributors'
  }).addTo(map);

  const poly1 = [
    [
      [-25, -35],
      [-25, 35],
      [25, 35],
      [25, -35]
    ]
  ];

  const polygon = new L.Polygon([poly1], {
    draggable: true,
    transform: true
  }).addTo(map);

  polygon.transform.setOptions({ rotation: false, scaling: true }).enable();
```

### Expected behavior

Users should be able to drag and resize / transform the polygon to get the correct lat, lng values.

### Current behavior

We are getting errors while dragging or transforming the polygon: 
### Drag
```
Uncaught Error: Invalid LatLng object: (NaN, NaN)
```
<img width="664" alt="Screen Shot 2565-11-10 at 10 49 22" src="https://user-images.githubusercontent.com/81729843/200999534-39425aaa-032d-4f1a-8416-0befbc4003b9.png">

<img width="993" alt="Screen Shot 2565-11-10 at 10 49 16" src="https://user-images.githubusercontent.com/81729843/200999527-d4e46307-15cc-4fa8-bf53-3762fa184031.png">

### Transform
```
Uncaught TypeError: Cannot read properties of null (reading ‘lat’)
```
<img width="495" alt="Screen Shot 2565-11-10 at 10 47 32" src="https://user-images.githubusercontent.com/81729843/200999673-81af3907-004b-46ec-9544-f6adc98c4444.png">

<img width="995" alt="Screen Shot 2565-11-10 at 10 47 23" src="https://user-images.githubusercontent.com/81729843/200999667-11d066fe-7eff-4b85-a267-6946e86607b3.png">

### Environment

- Leaflet version: 1.7.1
- Browser (with version): Google Chrome (107.0.5304.87)
- OS/Platform (with version): MacOS BigSur 11.6.1

**Comment by IvanSanchez** [comment]
Looks like a problem in `leaflet-path-transform`, not in core Leaflet.

In other words: you're filing the bug in the wrong repo.
