### ISSUE TITLE
Consider exposing `HTMLImageElement.decoding` for `ImageOverlay`

### ISSUE THREAD

**Issue by denschub** [Leaflet/Leaflet#8649]
### Motivation

Hi there! We at Mozilla see a quite a few Web Compatibility reports about various applications using an animated map layer on top of Leaflet, where the animation is flickering. For example: [there's this issue on firesmoke.ca](https://github.com/webcompat/web-bugs/issues/80232).

The primary issue here is a bit of a race between showing and decoding the image. When image tags are hidden, browsers may not decode the image files to save on memory and performance, and they'll defer decoding to when the image becomes visible. There are a couple of Leaflet plugins that use hiding and showing layers to achieve an animation effect, and that might result in flickering. Not just in Firefox, this *could* affect all browsers, and is highly dependent on the systems performance and the image decoders performance...

### Suggested solution

A reliable way to solve this is to add the `decoding="sync"` attribute to the `img` tag, or to set [`HTMLImageElement.decoding`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/decoding) to `sync` via the DOM API. This will force the browser to decode right away, which eliminates the possibility for flickering.

While I don't think setting the decoding mode to `sync` by default is a good idea, I'd love this to be exposed as an option to the `ImageOverlay`, so that libraries could set `sync` on layers they know will be animated. 

### Alternatives considered

Sites could probably workaround that by modifying the DOM themselves, but that's not a maintainable idea. Some sites we know of have monkey-patched Leaflet to always add the `sync` decoding flag, but that'll lock them out of easy Leaflet updates, and is also not something we'd consider. Browsers could improve their logic for deciding if something should be `sync` or `async`, but that's not easy, and I think that making the intentions clear on the image tag is a cleaner solution.

**Comment by IvanSanchez** [comment]
Sounds simple enough - #8650 should do the trick.

@denschub Do you know if it's only `ImageOverlay`s, or are `TileLayer`s also affected by the flickering?

I'm slightly concerned about performance issues here, since there's also users that want to delay loading any images in a Leaflet map until the user scrolls down the webpage and the map container becomes visible. I'm wondering about setting up some events to check when a map is scrolled into view, but that might be a bit overkill.

**Comment by jonkoops** [comment]
Perhaps we need to start thinking about an API for `ImageOverlay` that allows users to 'swap' the image. The process could involve loading in a new image element and waiting for the decode to happen before swapping the underlying image to avoid flickering.

**Comment by IvanSanchez** [comment]
> I'd prefer an implementation where the default value is unset (which would default to `auto`)

I've updated #8650 based on this.

Note that users should be able to do something like `myOverlay.getElement().decoding='sync'` with the current API. `getElement()` exposes the `HTMLImageElement` itself.

> Perhaps we need to start thinking about an API for `ImageOverlay` that allows users to 'swap' the image

Makes sense, but I guess that's out of the scope of this bug.

**Comment by denschub** [comment]
> Note that users should be able to do something like `myOverlay.getElement().decoding='sync'` with the current API. `getElement()` exposes the `HTMLImageElement` itself.

Oh that's good to know. We might be able to suggest that to site owners if they cannot update Leaflet for a reason or something!

> But maybe it had other reasons

Probably, yeah. Image loading on first load vs. adding images to the DOM at a later point is a different beast. Shameless plug: if you run into issues with any specific browser, file a bug on https://webcompat.com - there's also Safari people participating, not just us Mozilla folks! We're happy to debug that, even if that might be something Leaflet could address (like this feature request!)
