### ISSUE TITLE
Leaflet Markers: jump out of viewport when clicked. Issue goes away when browser is resized.

### ISSUE THREAD

**Issue by francofx2** [Leaflet/Leaflet#8653]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

I have setup a leaflet map in development environment and a staging site.

Whenever I load the page in the test site, the maps initializes sticking to the top left. Any click on a marker pushes the icon and the whole map out of view boundaries. The issue **goes away as soon as I resize the browser window**. This is true in both Safari and Firefox on Mac, and other Chrome users have reported similar issues. 

Video below shows the behaviour:

https://user-images.githubusercontent.com/81722620/201569503-400a8a56-4310-449c-a3aa-ebbd9b65a3bc.mp4

The issue can be seen in the test site

[https://junglapeumayen.cl/el-parque-test-mapa](https://junglapeumayen.cl/el-parque-test-mapa)

### Expected behavior

The issue is not seen in the codepen.io instance nor locally: the map initializes centered, and icons stay in place or pan slightly to show the whole popup whenever clicked. 

The whole code can be seen in the following codepen:

[https://codepen.io/francofx2/pen/XWYmgyd](https://codepen.io/francofx2/pen/XWYmgyd)

autoPan is set to "true" in the popup generator

### Current behavior

As explained in steps to reproduce. 

### Environment

- Leaflet version: 1.9.2
- Browser: Firefox 106.0.5, Safari 14.1.2 
- OS/Platform (with version):  MacOS Bigsur (11.6.7)

**Comment by IvanSanchez** [comment]
> The issue goes away as soon as I resize the browser window.

That means it should be covered by #8612. In the meantime use `invalidateSize()`.
