### ISSUE TITLE
Firefox is failing on CI

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#8664]
Since yesterday, all 3 Firefox jobs are failing on CI, both on `main` and in PRs:

```
> karma start ./spec/karma.conf.js --browsers FirefoxRetina

18 11 2022 16:58:04.550:ERROR [launcher]: Cannot start FirefoxHeadless
	Can not find the binary firefox
	Please set env variable FIREFOX_BIN
18 [11](https://github.com/Leaflet/Leaflet/actions/runs/3498709042/jobs/5859497355#step:4:12) 2022 16:58:04.604:ERROR [launcher]: FirefoxHeadless stdout: 
18 11 2022 16:58:04.605:ERROR [launcher]: FirefoxHeadless stderr: 
Error: Process completed with exit code 1.
```

Not sure what's going on here. cc @jonkoops @Falke-Design

**Comment by Falke-Design** [comment]
![grafik](https://user-images.githubusercontent.com/19800037/202794978-a8c65d64-e4c4-4eab-bb36-75da145ef0df.png)

I run the test on FirefoxHeadless local. First I get this errors and then a update window of Firefox appeared. After it was finished I don't get this errors anymore

**Comment by jonkoops** [comment]
Strange, almost seems like Firefox is no longer installed in the Github Actions runner.

**Comment by Falke-Design** [comment]
Yeah I thought that too. I searched in [Github-Feedback](https://github.com/community/community/discussions) and in Google but no one has the same problem.

**Comment by mourner** [comment]
@jonkoops found a discussion about it here: https://github.com/actions/runner-images/issues/6399#issuecomment-1284409180. While they're going to add Firefox back, for now we'd have to pin the image, setting `ubuntu-20.04` instead of `ubuntu-latest`.

**Comment by Falke-Design** [comment]
In my fork with the latest master it works fine ... https://github.com/Falke-Design/Leaflet/actions/runs/3500087433/jobs/5862462869

**Comment by jonkoops** [comment]
That's weird, perhaps they added it back but it hasn't rolled out to all runners yet?

**Comment by Falke-Design** [comment]
I restartet our workflow, maybe it works now ...
https://github.com/Leaflet/Leaflet/actions/runs/3500142707

**Comment by mourner** [comment]
Nope, weird...

**Comment by jonkoops** [comment]
Created #8670 to verify this still works on the older version of Ubuntu. We can upgrade when the time comes that Firefox is included by default.

**Comment by jonkoops** [comment]
I've added the same changes on the `v1` branch, so future patch releases can be tested.
