### ISSUE TITLE
IE failing on `v1` branch

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#8666]
IE tests on CI are failing on `v1` branch, including the v1.9.3 tag. [The logs](https://github.com/Leaflet/Leaflet/actions/runs/3499076639/jobs/5860259993) say there's a syntax error encountered, which means that some ES6 code likely slipped into `v1` through cherry picks. Let's address this with the following steps:

- [x] Determine whether the failures are only in the test code, or in v1.9.3 distribution build as well.
- [ ] Fix any errors.
- [ ] If it's in v1.9.3, we'll have to do a v1.9.4 to make sure `v1` doesn't break compatibility with IE.
- [ ] Harden ESLint rules on `v1` to make sure similar issues don't slip in in the future.

@Falke-Design can you take a look?

**Comment by Falke-Design** [comment]
I think I found the issue:
![grafik](https://user-images.githubusercontent.com/19800037/202790448-1d1de01a-4418-4d3d-860d-7d145ca1d74c.png)

No need to release `1.9.4` because it is only in the tests.
I will create a PR to fix it.

> Harden ESLint rules on v1 to make sure similar issues don't slip in in the future.

@mourner @jonkoops can you do this?

**Comment by mourner** [comment]
> Edit: do we really need this in eslint? Sure it would be helpful but the tests already make this visible. I think it would be better to discuss if we should stop the release process if a test fails

Yeah, good point — let's do that! Submitted #8668

**Comment by jonkoops** [comment]
Fixed by #8667
