### ISSUE TITLE
Migrate Bundlemoon from 1.x to 2.0

### ISSUE THREAD

**Issue by Falke-Design** [Leaflet/Leaflet#8673]
> Authentication changes (PR https://github.com/LironEr/bundlemon/pull/103, https://github.com/LironEr/bundlemon/pull/117)
>   - The old way of using project ID without an API key will stop working in a few months so it's important to upgrade.

https://github.com/LironEr/bundlemon/releases/tag/bundlemon%402.0.0

@jonkoops can you look into this?

**Comment by jonkoops** [comment]
@mourner could you make sure we gave all the access to the Github app as outlined in the [migration guide](https://github.com/LironEr/bundlemon/blob/bundlemon%402.0.0/docs/migration-v1-to-v2.md)? I don't have the permissions to do so.

**Comment by jonkoops** [comment]
I've put in a request to migrate our historical data as well, see https://github.com/LironEr/bundlemon/issues/125#issuecomment-1321122985.

**Comment by mourner** [comment]
> @mourner could you make sure we gave all the access to the Github app as outlined in the [migration guide](https://github.com/LironEr/bundlemon/blob/bundlemon%402.0.0/docs/migration-v1-to-v2.md)?

I think all is set:

<img width="519" alt="image" src="https://user-images.githubusercontent.com/25395/202929364-a9a00fe1-6400-4f1d-8972-43240e977a3f.png">
