### ISSUE TITLE
Document how to disable auto-panning

### ISSUE THREAD

**Issue by Pomax** [Leaflet/Leaflet#8677]
### Checklist

- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this change hasn't been suggested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Which documents need updating?

https://leafletjs.com/examples/quick-start/

### Motivation

I've been trying to make leaflet place markers and move them around _without_ automatically panning to whatever marker I'm updating, and I can't for the life of me figure out how to do that. Markers created with `autoPan:false` or `autoPanOnFocus:false` still pan the map, which means that for markers that get `setLatLng` called on a regular interval, it becomes impossible for a user to just drag the map around and keep it where they put it.

It would be a really good idea to update the first tutorial to not just show how to create markers, circles, and polygons, but also show how to make leaflet both center the map on them, _and_ how to make Leaflet explicitly *not* do that.

### Suggested changes

I don't actually know what code is required here, because I can't find anything in the tutorials or API docs that actually works, making it even more important to update the tutorial: if this can't be done, that's worth very explicitly mentioning, but if it _can_ be done, that's a basic behaviour people are going to expect to be able to write code for, and showing what that code is as part of the quick start tutorial will have super high value.

**Comment by anton-seaice** [comment]
Can you provide an example... ?

You need to set `autoPan:false` on your [popup](https://leafletjs.com/reference.html#popup), not the marker

**Comment by Pomax** [comment]
It turns out the code actually had a `map.setView` that shouldn't have been there. Apologies for the false report.
