### ISSUE TITLE
Add a CITATION.cff

### ISSUE THREAD

**Issue by Malvoz** [Leaflet/Leaflet#8679]
Follow-up of https://github.com/Leaflet/Leaflet/issues/7931.

We may want to decide if we should add the [Zenodo's DOI badge for the Leaflet repo](https://github.com/Leaflet/Leaflet/issues/7931#issuecomment-1322331360) to `README.md`, and/or [add a `CITATION.cff`](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) to this repo (the latter would allow people to <q>[Cite this repository](https://docs.github.com/assets/cb-230711/images/help/repository/citation-link.png)</q>).

**Comment by Falke-Design** [comment]
I would do both :+1:

**Comment by jonkoops** [comment]
I'd say let's add the citation file only. Folks that are explicitly looking of this (small dedicated audience) will probably already know the citation functionality of GitHub already.

Unless somehow the badge has more relevant info I think it will just add noise for 'regular' users.
