### ISSUE TITLE
Popup close button issue

### ISSUE THREAD

**Issue by steros76** [Leaflet/Leaflet#8688]
When I close popup with "x" close button, I experience strange issues in my page outside the map (i.e. click events programmed on buttons don't work anymore). If I close the popup clicking elsewhere there is no problem.
I notice that this strange behaviour is due to
`closeButton.href = '#close';`
Commenting this line all works correctly.
Why this line is present?

**Comment by Falke-Design** [comment]
Which Leaflet version do you use? This is already fixed in newer versions please use `v1.9.3` #8159

**Comment by steros76** [comment]
Sorry. I wasn't on last version.
I updated and I can confirm that it works.
Thanks.
