### ISSUE TITLE
L.imageOverlay projection issue with Large GeoTIFF Bounds

### ISSUE THREAD

**Issue by mttucl** [Leaflet/Leaflet#8689]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Hi,

When using imageOverlay with GeoTIFF covering a large area, there seems to be an alignment issue with map tiles (projection?). I'm using the GeoTIFF bounds to set the imageOverlay imagebound which comes from "EPSG:4326". See screenshot below. I also have the code and files in [my repo here](https://github.com/mttucl/testing-imageoverlay-leaflet). 

[With large area geotiff](https://raw.githubusercontent.com/mttucl/testing-imageoverlay-leaflet/main/screenshot-large-tiff.PNG)
[With smaller area geotiff](https://raw.githubusercontent.com/mttucl/testing-imageoverlay-leaflet/main/screenshot-small-tiff.PNG)

I don't think it is related to image file size but area size.

The code is similar for both files and there is nothing special about it. Here is the relevant code

```
              // create rgba for raster data function
              function color_array_to_canvas(array, width, height) {
                  var rgba = new Uint8ClampedArray(4*width*height);
                  for (var i = 0; i < width*height; i++) {
                      let colorVal = array[i] <0 ? [59, 82, 139] : [171, 220, 5]
                      rgba[4*i] = colorVal[0]
                      rgba[4*i+1] = colorVal[1]
                      rgba[4*i+2] = colorVal[2]
                      rgba[4*i+3] = 255;
                  }      
                  var imgData = new ImageData(rgba, width, height);
                  return imgData;
              }   
  
  // color image data
  let imagData = color_array_to_canvas(rasters[0], tiffWidth, tiffHeight);
  
  // create canvas and fill context with imagData
  let canvas = document.createElement('canvas');
  canvas.width = tiffWidth;
  canvas.height = tiffHeight;
  canvas.style.display = "none";
  let ctx = canvas.getContext("2d");
  ctx.putImageData(imagData, 0, 0);
  
  // raster bounds
  let imageBounds = [[extent[3], extent[2]], [extent[1], extent[0]]];

  // imageoverlay of raster
  let imageLayer = L.imageOverlay(canvas.toDataURL(), imageBounds, {opacity: 0.5});
```

If you go to my repo and check the example html files, you can see the raster data is mapped correctly for both files when you click on the map to get the values. 

I also saw geotiff libraries do the same as this code, except the canvas is the same size as the map and they transform the image and place at the top-left corner using pixel values calculated from the GeoTIFF bounds. The image aligns very well for them but they redraw the image again when zooming or panning which makes it slow with larger size files.

### Expected behavior

Alignment of L.imageOverlay with map tiles with large GeoTIFF bounds.

### Current behavior

misalignment with map tiles with large area GeoTIFF

### Minimal example reproducing the issue

[example](https://github.com/mttucl/testing-imageoverlay-leaflet)

### Environment

- Leaflet version: 1.9.3
- Browser (with version): Edge v107
- OS/Platform (with version): Win10

**Comment by IvanSanchez** [comment]
So you've got a vertical shift, as I've seen several times before - see e.g. https://gis.stackexchange.com/q/174216 and https://stackoverflow.com/questions/71489276/ . You're stretching data in EPSG:4326 onto a EPSG:3857 basemap, Leaflet is implicitly performing linear interpolation of coordinates, and as a result, only the top and bottom pixels of the image are aligned.

Read up on what a cylindrical projection is, if you haven't already (and tissot's indicatrix, and plot a graticule to see how the distance between parallels behaves). Warp your raster into EPSG:3857. I'd suggest using `gdal_warp` and reading https://gis.stackexchange.com/questions/174658/ .

**Comment by IvanSanchez** [comment]
Or, use ImageOverlay.Arrugator (https://gitlab.com/IvanSanchez/Leaflet.ImageOverlay.Arrugator/)

**Comment by mttucl** [comment]
Unfortunately, this one suffer from the same issue, I also tried imageTransform and imageOverlay.rotated but all have the same issue. The only ones working with imageOverlay are the ones I mentioned by transforming the image and calculating Topleft X&Y pixels to place the image at. Maybe ImageOverlay should do it this way natively. I see `leaflet-geotiff-2` do it this way
