### ISSUE TITLE
Layer.toGeoJson working but docs dont see

### ISSUE THREAD

**Issue by productdevbook** [Leaflet/Leaflet#8702]
### Checklist

- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this change hasn't been suggested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Which documents need updating?

https://leafletjs.com/reference.html#layer

### Motivation

```ts
  map.value.on('pm:create', ({ shape, layer }) => {
    console.log('pm:create', layer.toGeoJSON())

```

and working but dont see docs and some TS("@types/leaflet": "^1.9.0") dont add. 

![image](https://user-images.githubusercontent.com/38668796/205881408-bb972378-fac5-47e9-a5d4-d2d324d594c2.png)
 

### Suggested changes

I don't know what to do, since I don't know exactly what it is and I'm using TS.

**Comment by IvanSanchez** [comment]
The core Leaflet repo doesn't handle typescript definitions.

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* NativeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.

**Comment by productdevbook** [comment]
but this data is not written in doc but it has functions. https://leafletjs.com/reference.html#layer `toGeoJSON()` dont see

**Comment by Falke-Design** [comment]
@productdevbook you need to do a casting:

```
  map.value.on('pm:create', ({ shape, layer }) => {
  if(shape === 'Polygon'){
     (layer as Polygon).toGeoJSON();
  }
});
```
https://github.com/geoman-io/leaflet-geoman/discussions/949
