### ISSUE TITLE
Leaftlet js is drawing geometric forms in the wrong place in SF

### ISSUE THREAD

**Issue by AllanOricil** [Leaflet/Leaflet#8706]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

it will be hard for someone to debug this if the person does not know anything about Salesforce.

1. create a Trailhead account https://trailhead.salesforce.com/pt-BR/today
2. from trailhead, create a sandbox (free salesforce environment)
3. deploy these Salesforce Metadata to your sandbox. 

https://github.com/AllanOricil/salesforce-leaflet-bug/tree/no_plugins

But before you do so, add your map box key in this custom label

https://github.com/AllanOricil/salesforce-leaflet-bug/blob/no_plugins/force-app/main/default/labels/CustomLabels.labels-meta.xml

5. place the "customMap" lwc somewhere in a Lightning Page  
6. Enable Lightning Web Security (LWS), verify that the marker updates correctly when dragging and zomming in/out, but the Circle does not.
7. Disable LWS, clear any cache in the browser, refresh the page, and verify that now the circle position is transformed without a problem.

This Lightning Web Security that Salesforce created is breaking something in leaflet but I can't figure out what it is. I need help. Maybe you guys have some guess of what LWS is breaking in Leaflet. With this gues I can try to debug and see if I can create a fix that is applied only in Salesforce.

### Expected behavior

https://user-images.githubusercontent.com/55927613/206422256-8c1faa44-2372-409b-aaeb-47ecf0393467.mov

### Current behavior

https://user-images.githubusercontent.com/55927613/206422291-d18e509e-85ad-4abb-854c-37b545ac82fe.mov

### Minimal example reproducing the issue

https://github.com/AllanOricil/salesforce-leaflet-bug/tree/no_plugins

### Environment

- Leaflet version: 1.9.3 (the same bug happens in 1.7, so it is not a problem caused by the latest version)
- Browser (with version): chrome
- OS/Platform (with version): darwin-x64 AMD

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* NativeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.

**Comment by AllanOricil** [comment]
@IvanSanchez when I set `preferCanvas` to `true` in the map object, the circles no longer show up.
![image](https://user-images.githubusercontent.com/55927613/206432171-129ae24d-69c9-44f1-8b8f-90622f0f9f59.png)
![image](https://user-images.githubusercontent.com/55927613/206432257-a2a6bce9-3f9b-40d4-a57e-552118435589.png)

I will share your guess with the Salesforce support team and see what they have to say. Thank you
