### ISSUE TITLE
Need gesture handling, without any plugin

### ISSUE THREAD

**Issue by hosseinGanjyar** [Leaflet/Leaflet#8712]
### Checklist

- [X] I've searched through the [plugins](https://leafletjs.com/plugins.html) to make sure this feature isn't already available, or think it shouldn't require a plugin.
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this feature hasn't been requested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Motivation

I was disappointed when I needed an option for gesture handling like [Google Maps Gesture Handling](https://developers.google.com/maps/documentation/javascript/examples/interaction-cooperative) on this lib, but couldn't receive any solution. Indeed, I'm using an angular plugin  [Angular Leaflet Directive](https://github.com/tombatossals/angular-leaflet-directive) and I want to mix an option of a plugin called [Leaflet.GestureHandling](https://github.com/elmarquis/Leaflet.GestureHandling) into your lib. Have you any solution?

### Suggested solution

Add an option for **_Gesture Handling_** in your config.

**Comment by IvanSanchez** [comment]
If there's a plugin for it, then use that plugin.

You're not giving any compelling reasons why that should be core functionality.
