### ISSUE TITLE
Deprecated some of plugins

### ISSUE THREAD

**Issue by hosseinGanjyar** [Leaflet/Leaflet#8713]
### Checklist

- [x] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this change hasn't been suggested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Which documents need updating?

https://leafletjs.com/plugins.html

### Motivation

Your document about [plugins](https://leafletjs.com/plugins.html) has some of deprecated and also not updated plugins for some years that I think couldn't help us for develop. 

-  https://github.com/yagajs/leaflet-ng2
- https://github.com/CleverMaps/tiny-leaflet-directive
- https://github.com/grantHarris/leaflet-control-angular
- https://github.com/tombatossals/angular-leaflet-directive
- ...

### Suggested changes

I suppose that it's better to remove these plugins and replace with updated plugins as well.

**Comment by Falke-Design** [comment]
Thank you for bringing this up, but (for now) we will not remove plugins. Maybe they are not working anymore but they can be still helpful to make a own fork or to get ideas from it.

For better visibility I added a badge with the last commit https://leafletjs.com/plugins.html:
![grafik](https://user-images.githubusercontent.com/19800037/207932386-1df5bd29-5fd0-4269-a835-1bc0ec061769.png)
