### ISSUE TITLE
Optimize star / recency labels on the plugins page

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#8716]
Follow up to #8714 — while it's a huge improvement, visiting the plugins page now invokes 1000+ network requests and makes the page very slow, in addition to a bunch of errors (around 60 for me). 

As a temporary workaround, we should add `loading="lazy"` to badge images, but long-term, ideally we would do away with badges and instead fetch / calculate stars and other metadata in a GitHub Action and then use it for rendering the static page. One of the advantages is instant page load, but another one would be that we can then extend the functionality of the page further, for example, adding dynamic sorting by stars or recency per category, highlight the most popular plugins, and style the rows differently depending on recency.

cc @Falke-Design @jonkoops

**Comment by Falke-Design** [comment]
`lazy loading` makes totally sense! But I can't implement it until saturday, so maybe someone else can do it.

I had this things in my mind while adding the badges but I didn't find a good solution, so I decided to go first with the badges.

The problem with static pages are, if we don't update the docs, it will always keep the old data. If I think back to the 1.7.1 time, there was over 1,5 years no updates, so it wouldn't be updated. A regular refresh / update is very important for the `last commit` datestamp. But like you said, searching, sorting, etc. would be a nice feature. 

Maybe a middleway can work. @jonkoops is it possible to have a github action, that runs everyday and regenerates the docs with the newest repo data?

Github Repo data: https://api.github.com/repos/Leaflet/Leaflet

**Comment by jonkoops** [comment]
I can put some work in on adding the image lazy loading, let me take a look.

**Comment by IvanSanchez** [comment]
@jonkoops Kindly have a look at #8717 before you try doing that.

**Comment by mourner** [comment]
@Falke-Design I'm pretty sure I've seen an example of a GH Actions setup that regenerates the pages daily based on a schedule, will look for it when I have a chance.
