### ISSUE TITLE
Add warning if multiple copies of library imported

### ISSUE THREAD

**Issue by MartinSoderholm** [Leaflet/Leaflet#8725]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

This is not a bug report, but an issue that caused a lot of headache for us, which I believe could've been prevented easily.

### The bug in our app

We have a map with some custom markers, and when you click on them the map pans to the marker. For some reason, when you clicked on the map (on nothing/background), a click-handler for a specific marker was triggered (same one each time). We have multiple different maps in our app and this was the only small thing not working, so we first spent a day looking for the bug in our own code. Then yesterday I had to start looking at code in `react-leaflet` and `Leaflet`.

### Debugging

Setting some breakpoints I located the issue in `Map._findEventTargets`. The `src` variable was correctly set to the map container div, but for some reason it was still pushing one of the targets in `this._targets` into `targets` and returning that instead of `[this]`.

Looking closer I noticed that the `_leaflet_id` set for the map container div was 3, but in the `this._targets` object id 3 referred to one of the Marker objects, the one being triggered. I added a Proxy object for `this._targets` to pin down what was populating it, at which point I noticed that the `Layer.addInteractiveTarget` method being used was not the one in `dist/leaflet-src.js` but the one in `src/layer/Layer.js`.

### The issue

So basically, the issue was caused by a custom Marker implementation that used imports from `leaflet/src/*` instead of just `leaflet`.

I copied an example from SO a while ago, and it had these imports.

```ts
import * as Util from 'leaflet/src/core/Util';
import * as DomUtil from 'leaflet/src/dom/DomUtil';
import { toLatLng as latLng } from 'leaflet/src/geo/LatLng';
import { Marker } from 'leaflet/src/layer/marker/Marker';
```

Everything else in our app use below equivalent.

```ts
import { DomUtil, latLng, Marker, Util } from 'leaflet';
```

### Expected behavior

In earlier versions of React you would get a warning if you unexpectedly imported multiple copies of the library. If your library is written in a way that will cause it to fail in that scenario, this is the appropriate thing to do.

In Leaflet, the library depends on a `stamp()` util method which uses a package global `lastId`. This counter will fail if you use imports from both `leaflet` and `leaflet/src/*`. So I would expect a warning or exception.

For example. In `Layer.js` the map reference is set here:

```js
	_layerAdd: function (e) {
		var map = e.target;

		// check in case layer gets added and then removed before the map is ready
		if (!map.hasLayer(this)) { return; }

		this._map = map;
		...
```

If the constructor of `map` instance is not the same as the one imported, you could warn or throw an error.

```js
import {Map} from '../map/Map';
```

### Current behavior

Currently there is no warning or exception, and because the library mostly works anyway, it can take many hours to finally find the cause of  the issue.

### Environment

- Leaflet version: 1.9.3
- Browser (with version): Chrome 108.0.5359.98
- OS/Platform (with version): macOS 13.0.1

**Comment by jonkoops** [comment]
Starting from Leaflet 2 we will be adding an [`exports`](https://nodejs.org/api/packages.html#exports) field to the package, which will enforce that the only importable surface of the the API is the `'leaflet'` path (so no sub-paths).

This should essentially solve this issue as it would not longer be possible to make imports such as these:

```ts
import * as Util from 'leaflet/src/core/Util';
import * as DomUtil from 'leaflet/src/dom/DomUtil';
import { toLatLng as latLng } from 'leaflet/src/geo/LatLng';
import { Marker } from 'leaflet/src/layer/marker/Marker';
```
