### ISSUE TITLE
CORS error loading Leaflet from unpkg.com

### ISSUE THREAD

**Issue by NICEXAI** [Leaflet/Leaflet#8726]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Link: https://leafletjs.com/

### Expected behavior

Example shows normal.

### Current behavior

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/19580983/208881040-6b5301ab-fb8e-42f4-9cb5-32f7c70d0621.png">

### Environment

- Leaflet version: none
- Browser (with version): Chrome 107.0.5304.121
- OS/Platform (with version): MacOS 12.5

**Comment by IvanSanchez** [comment]
Can't reproduce with Chromium 108.0.5359.94 on Linux.

**Comment by mourner** [comment]
Maybe that's some kind of Chrome security extension? @NICEXAI anything you have installed that might have blocked those requests?

**Comment by jonkoops** [comment]
I am unable to reproduce this on the latest Firefox and Chrome on macOS.

**Comment by NICEXAI** [comment]
Thank you very much, access is now back to normal on my end, however I didn't do anything.
