### ISSUE TITLE
Fix `userSelect` on Safari

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#8740]
#8738 removed prefixing for `userSelect`, but Webkit (Safari on iOS and desktop) still has it prefixed (`WebkitUserSelect`) and doesn't support the non-prefixed version.

Let's bring it back and make sure we're more careful about this, checking support on MDN / CanIUse before making similar changes. No need to bring back #8739 — can be a simple ternary.

**Comment by jonkoops** [comment]
Hmmm, strange. Looks like the [compatibility table](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select#browser_compatibility) on MDN is wrong then. I'll create a PR to fix it.

**Comment by mourner** [comment]
@jonkoops doesn't look wrong to me, it points out that it's prefixed on Safari:

<img width="781" alt="image" src="https://user-images.githubusercontent.com/25395/209331321-2162dba9-b3d2-47cd-86a9-5bd4e7833ca1.png">

And I confirmed it with my local Safari on Mac:

<img width="262" alt="image" src="https://user-images.githubusercontent.com/25395/209331411-07210ed4-3de0-4db9-8472-8ff700acbc5d.png">

**Comment by jonkoops** [comment]
Ahhhh, my dark mode plugin is hiding the grey icons.

![Facepalm](https://media.tenor.com/fiRUfGX7JyUAAAAM/facepalm-star-trek.gif)

**Comment by jonkoops** [comment]
@mourner Just did some testing and it looks like Safari on iOS is broken, but also on the `v1` branch. Safari now supports the `selectstart` event so the check we are doing to see if this event works is actually passing. However, calling `preventDefault()` actually does not seem to prevent selection of text.
