### ISSUE TITLE
Leaflet 1.9.3 breaks dynamic popup binding in Esri Leaflet

### ISSUE THREAD

**Issue by patrickarlt** [Leaflet/Leaflet#8761]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. Open https://jsbin.com/cesazol/3/edit?html,output which uses Leaflet 1.9.3
2. Click any of the green earthquake areas:
    - Expected: popup opens
    - Actual: Error
3. Open https://jsbin.com/cesazol/3/edit?html,output which uses Leaflet 1.9.2
    - Expected: popup opens
    - Actual: popup opens

### Expected behavior

In Esri Leaflet we inherit from `Layer` in our `FeatureLayer` class so that users can do `someEsriLeafletFeatureLayer.bindPopup(...)` with a function to quickly bind a popup dynamically to every feature.

### Current behavior

It looks like the default behavior of this changed in 1.9.3 in https://github.com/Leaflet/Leaflet/pull/8571/files#diff-2b5b78f24babc48279b336b4e9d85623e3d1fd37c43fdfe5e7240e736d5fcf7aR425 which makes setting `this._popup._source` exclusive to `FeatureGroup`.

In contrast the previous version of this seemed to work just fine https://github.com/Leaflet/Leaflet/blob/4cbd3610cd30a955c99d1498a71db7224e41573b/src/layer/Popup.js#L470-L490 since this `this._popup._source` was always set.

### Minimal example reproducing the issue

https://jsbin.com/cesazol/3/edit?html,output

### Environment

- Leaflet version: 1.9.3
- Browser (with version): Any 
- OS/Platform (with version): Any

**Comment by patrickarlt** [comment]
I'm not entirely sure how to proceed. Since reverting #8571 would reintroduce #8558 but fix this issue.

Alternately we could port the old `bindPopup` behavior into Esri Leaflet directly and release a new version or rewrite our `FeatureLayer` to inherit from `FeatureGroup` but we have to make a note of the version incompatibility to our users.

@Belair34 @Falke-Design @IvanSanchez let me know how you want to proceed. I'm happy to fix this in Esri Leaflet but wanted to report the regression first.

**Comment by Falke-Design** [comment]
I will take a look into it tomorrow

**Comment by Falke-Design** [comment]
Hi @patrickarlt,

after digging into it, I'm not sure what is the best solution. The `FeatureLayer` is clearly working like a group, so it would make sense to extend the class from `FeatureGroup` but I also see that it might be useful to extend directly from `Layer`.

So for now I think the best way would be to implement custom `bindPopup` and `unbindPopup` methods. Instead of binding the popup to the `FeatureLayer` you bind on each individual layer the popup.

```
L.esri.FeatureLayer.include({
		bindPopup(content, options) {
			this.eachFeature(function(layer){
				layer.bindPopup(content, options);
			}, this);

			this._popupBinding = {
				content,
				options
			};

			return this;
		},
		createNewLayer: function (geojson) {
			var layer = L.GeoJSON.geometryToLayer(geojson, this.options);
			// trap for GeoJSON without geometry
			if (layer) {
				layer.defaultOptions = layer.options;
				if(this._popupBinding){
					layer.bindPopup(this._popupBinding.content, this._popupBinding.options);
				}
			}
			return layer;
		},
		unbindPopup() {
			this._popupBinding = undefined;
			this.eachFeature(function(layer){
				layer.unbindPopup();
			}, this);
			return this;
		},
	});
```
https://jsbin.com/yimimafutu/1/edit?html,output

**Comment by patrickarlt** [comment]
@Falke-Design thanks for taking a look. I'm going to close this and we will resolve this on our end.
