### ISSUE TITLE
NoWrap does not work when using WMSTileLayer.

### ISSUE THREAD

**Issue by KimJaKu1** [Leaflet/Leaflet#8762]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Although noWrap = {true} is literally used with WMSTileLayer, maps appear continuously.

``
<WMSTileLayer
                    layers='ne:NE1_HR_LC_SR_W_DR'
                    url="https://ahocevar.com/geoserver/wms"
                    noWrap={true}
                    />
``

### Expected behavior

It is expected that when noWrap={true}, only one map from -180 to 180 should appear.
However, this is not the case now, and several maps appear.

### Current behavior

![image](https://user-images.githubusercontent.com/118945992/210046953-e675576c-2994-4fcb-ae6f-fd9c12325829.png)

### Environment

- Leaflet version: "react-leaflet": "^4.2.0",
- Browser (with version): Chrom
- OS/Platform (with version): Window 10

**Comment by Falke-Design** [comment]
`noWrap` is working as expected but maybe the description needs to be updated. 
Wrapping converts the bounds for the tile to always the same coordinates, which should be then always available on the WMS-Server. If wrapping is disabled, Leaflet requests with the actual bounds which can be out of the range for the WMS-Server and then the wms tiles would be not visible anymore. 

**But** your WMS-Server supports serverside wrapping, this means you will always get tiles, doesn't matter if Leaflet converts the bounds or not. You can see this if you open this [demo](https://plnkr.co/edit/s2NAgRNXdW25TYfL), then open the network request tab in the developer tools and check `ahocevar.com`. Now click on the `Jump to next World` button and check again the request. The bounds are changed. If you now set `noWrap` to `false`, it will always request with the same bounds.

I think adding `bounds` to the WMSTileLayer can help you:

```
var bounds = new L.LatLngBounds(new L.LatLng(85, -180), new L.LatLng(-85, 180));
`new L.TileLayer.WMS("https://ahocevar.com/geoserver/wms", {bounds: bounds});`
``
