### ISSUE TITLE
layer.openPopup() not working as intended, can't find docs or error msg to troubleshoot why

### ISSUE THREAD

**Issue by chrisjdixon** [Leaflet/Leaflet#8765]
### Checklist

- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this change hasn't been suggested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Which documents need updating?

https://leafletjs.com/reference.html#layer

### Motivation

We can't figure out how to make a Leaflet popup open programmatically [(see SO question)](https://stackoverflow.com/q/74870683) and we're wondering if Leaflet's [docs on popups](https://leafletjs.com/reference.html#popup) or [layers](https://leafletjs.com/reference.html#layer) could better explain why adding `layer.Openpopup()` to the `onEachFeature()` fn (or anywhere else) in the eg in the SO question doesn't work as intended:
```js
        function onEachFeature(feature, layer) {
            if (feature.geometry.coordinates[1].toFixed(5) == myMap.getCenter().lat.toFixed(5) &&
                feature.geometry.coordinates[0].toFixed(5) == myMap.getCenter().lng.toFixed(5)) 
            {layer.openPopup();)}
        }
```
Could you please help us understand what else we might need to do, or what else we've done wrong? We know your GH isn't for support questions but we've already asked on SO, multiple chatrooms, asked friends, and have spent *days* fiddling with the code and just can't get this to work. We're sorry to ask like this but we're desperate!

### Suggested changes

Could you please better explain why this might not work in the way we've done it, or provide more reproducible examples in the docs for users to work off? Perhaps we've done this in a way that won't work, and this could be stated in the docs?

Also, no error message shows when `layer.openPopup()` doesn't seem to do anything, which seems to be [this issue](https://github.com/Leaflet/Leaflet/pull/8079). Could an error message be shown so we can better understand what we're doing wrong?

**Comment by Falke-Design** [comment]
The problem is that you are trying to open the popup before it is added to the map.

Answered in SO.
