### ISSUE TITLE
Layers Control on mobile devices is not working as expected with Leaflet 1.9.x

### ISSUE THREAD

**Issue by PedroVenancio** [Leaflet/Leaflet#8778]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. Open
https://pedrovenancio.github.io/tests/layerscontrol190.html
or 
https://pedrovenancio.github.io/tests/layerscontrol193.html
with Google Chrome on a mobile device (tested on Android) or using Chrome desktop simulating mobile viewport (Ctrl+Shift+i and then Ctrl+Shift+m). This is what you will see:
![imagem](https://user-images.githubusercontent.com/1331581/210242531-4ca28745-a3b3-453c-9587-a5332613c81c.png)

2. Click in Layers Control icon, to open the layers list. This click changes the default base layer (Satellite) to OSM layer, despite Satellite radio button keeps selected.
![imagem](https://user-images.githubusercontent.com/1331581/210243049-0b717a2a-bb59-402c-992e-58fbd08e3a4a.png)

3. This does not happen on Leaflet 1.7.1:
https://pedrovenancio.github.io/tests/layerscontrol171.html

### Expected behavior

The click to open the Layers Control should not produce a change in the layer selected, just like happens in this example:
https://pedrovenancio.github.io/tests/layerscontrol171.html

### Current behavior

It seems that when clicking to open the Layers Control, that click is at the same time applied to select the first layer in the list. It happens when the click coincides with radio button position.
It also happens on Firefox Beta 109.0b4 and Firefox 108.1.0 running on Android.

### Minimal example reproducing the issue

https://pedrovenancio.github.io/tests/layerscontrol193.html

### Environment

- Leaflet version: Leaflet >= 1.9.0.
- Browser (with version): Google Chrome for Android (tested on version 108.0.5359.128); Google Chrome for Windows with mobile viewport (108.0.5359.128); Firefox Beta for Android (109.0b4); Firefox for Android 108.1.0.
- OS/Platform (with version): Android 11; Windows 11.

**Comment by PedroVenancio** [comment]
Please let me know if some more information is needed for triage and testing. Thanks!

**Comment by jonkoops** [comment]
I can reproduce this issue in Google Chrome for Android, but not using the simulated device through the desktop browser. Not sure of the cause, but this is definitely a bug we need to take a look at.

I am currently overloaded with other work so have no time to look into this right now. If anyone wants to do some deeper investigation into this issue feel free to do so and report back here.

**Comment by IvanSanchez** [comment]
Possibly a regression from https://github.com/Leaflet/Leaflet/pull/8556, maybe??

I'm going to guess that replacing the `click` event with an [`input` event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event) right here...

https://github.com/Leaflet/Leaflet/blob/5c29d615563835d373a51b91fc3513a17907da96/src/control/Control.Layers.js#L337

... would possibly be an easy fix. In my experience, browsers with touchscreens behave... peculiar when it comes to `click`/`dblclick` events, and this looks like one of those moments.

**Comment by IvanSanchez** [comment]
> Is this something that would be resolved if we started using Pointer Events everywhere?

No, I don't think so. A `click` event should be a `PointerEvent` already; besides, the `L.Control.Layers` code doesn't use `mouse*` events anywhere.

**Comment by Falke-Design** [comment]
The problem is the `mouseenter` or better `mouseover` event. It is fired directly before the `click` event. So the control is expanded when the `click` is fired at this specific coords.

https://github.com/Leaflet/Leaflet/blob/5c29d615563835d373a51b91fc3513a17907da96/src/control/Control.Layers.js#L189-L192

`mousenter` will be mapped to `mouseover`:
https://github.com/Leaflet/Leaflet/blob/5c29d615563835d373a51b91fc3513a17907da96/src/dom/DomEvent.js#L94-L98

https://github.com/Leaflet/Leaflet/blob/5c29d615563835d373a51b91fc3513a17907da96/src/dom/DomEvent.js#L123-L132

**Comment by PedroVenancio** [comment]
Hi all

Do you think this can be fixed soon?

Thanks!
