### ISSUE TITLE
Incorrect map of India

### ISSUE THREAD

**Issue by DarkMortal** [Leaflet/Leaflet#8780]
### Checklist

- [X] I've searched through the [plugins](https://leafletjs.com/plugins.html) to make sure this feature isn't already available, or think it shouldn't require a plugin.
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this feature hasn't been requested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Motivation

Pakistan occupied Kashmir (PoK) is shown as a part of Pakistan.

### Suggested solution

Kindly fix it and use proper map of India.

**Comment by Falke-Design** [comment]
We are not providing any map tiles. For example the map tiles on our demo are provided by [OpenStreetMap](https://www.openstreetmap.org/).

**Comment by IvanSanchez** [comment]
Complete duplicate of https://github.com/Leaflet/Leaflet/issues/5056 .
