### ISSUE TITLE
Tooltip anchor locations are incorrect for small GeoJSON polygons in 1.9.x

### ISSUE THREAD

**Issue by michaelthoreau** [Leaflet/Leaflet#8783]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

This JSFiddle Illustrates the problem well: https://jsfiddle.net/michaelthoreau/ekafvph8/6/

This issue seems to only affect geojson polygons that are geographically small, regardless of pixel size when drawn.

### Expected behavior

Both tooltips should appear centered on the polygons. 

### Current behavior

The smaller polygon's tooltip appears in the wrong position. This behaviour does not appear in leaflet@1.8.0.

### Minimal example reproducing the issue

https://jsfiddle.net/michaelthoreau/ekafvph8/6/

### Environment

- Leaflet version: 1.9.3
- Browser (with version): 108.0.5359.124 (Official Build) (arm64)
- OS/Platform (with version): Mac OS 12.6

**Comment by Mushr0000m** [comment]
Any news about this ?

**Comment by Falke-Design** [comment]
We have already a PR (#8784) for this, but the PR needs first to be merged and then a Release is necessary. So this will take a while.

**Comment by Mushr0000m** [comment]
When you say a while you mean weeks ? months ? We can't use Leaflet for our new project due to this...

**Comment by Falke-Design** [comment]
You can use Leaflet `1.8.0` until the fix is released. 
I can't say you how fast the release will be done. I hope in the next 2 weeks but i can also take 2 months.

**Comment by IvanSanchez** [comment]
> We can't use Leaflet for our new project due to this...

That's *your* problem, not ours. Go read the "NO WARRANTIES" bit of the license file, and watch https://www.youtube.com/watch?v=Q187JGeXueA .

Pressuring maintainers by means of inducing guilt is not productive: it only burns maintainers out.

**Comment by Mushr0000m** [comment]
> > We can't use Leaflet for our new project due to this...
> 
> That's _your_ problem, not ours. Go read the "NO WARRANTIES" bit of the license file, and watch https://www.youtube.com/watch?v=Q187JGeXueA .
> 
> Pressuring maintainers by means of inducing guilt is not productive: it only burns maintainers out.

Sorry, I really didn't mean that at all 😥 ! I really appreciate the time/effort/quality of the work. I was meaning more "oh that is a pity we can't use the latest version because of this problem" but realy not in aggressive or bad way. Really sorry if I badly expressed myself as english is not my native language.

**Comment by IvanSanchez** [comment]
> I was meaning more "oh that is a pity we can't use the latest version because of this problem" but really not in aggressive or bad way. 

No problem then ;-)

**Comment by michaelthoreau** [comment]
@Falke-Design Thanks for the pull request! I was suspicious of something like rounding that but didn't do a great job of debugging due to unfamiliarity with the project structure. Looking forward to the release but using 1.8.0 until then. 

BTW we frequently use 7+ decimal places to annotate small objects... works well so far but hoping we dont run in to precision issues if we go much smaller.

**Comment by Dass7** [comment]
[click here](https://www.mysourcebook.com/2023/04/tooltip-anchor-locations-are-incorrect-for-small-geojson-polygons-in-1.9.x-in-leaflet.html)-this article may be solve this issue

**Comment by Falke-Design** [comment]
Issue fixed by #8784, will be in the next `v1` release

**Comment by foxymiles** [comment]
This is affecting us too. Thanks for the fix! We're looking forward to the next release.

**Comment by Falke-Design** [comment]
@foxymiles @michaelthoreau @Mushr0000m we just released `1.9.4` which includes the fix for this.

**Comment by foxymiles** [comment]
@Falke-Design Thanks for the update!
