### ISSUE TITLE
Full-window plugin

### ISSUE THREAD

**Issue by xingyuXXX** [Leaflet/Leaflet#8804]
### Checklist

- [X] I've searched through the [plugins](https://leafletjs.com/plugins.html) to make sure this feature isn't already available, or think it shouldn't require a plugin.
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this feature hasn't been requested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Motivation

my scenario is, I have a kind of big monitor, and I want to open 3 windows with different focus location on map at the same time. So full-screen plugin doesn't help here.

### Suggested solution

Can a plugin be developed, so a overleaf map can be zoomed to fit the whole window instead of the whole screen?

**Comment by IvanSanchez** [comment]
Apply CSS rules `height: 100vh` and `width: 100vw` to your map container.
