### ISSUE TITLE
Marker position not matching provided lat & lng

### ISSUE THREAD

**Issue by matbe81** [Leaflet/Leaflet#8807]
Despite the cote not having changed, one update move the marker position

Example:
https://epicside.be/experience/rallier-le-pain-de-sucre-en-telepherique/

The marker is position in the middle of the ocean while the lat and lng parameter are corrects:
https://www.google.com/maps/place/22%C2%B054'39.7%22S+43%C2%B012'33.7%22W/@-22.9110137,-43.2115614,17z/data=!3m1!4b1!4m5!3m4!1s0x0:0xb29731e9fb3ae0f1!8m2!3d-22.9110137!4d-43.2093727

Generated shortcode:
[leaflet-map zoom=4 lat=-22.91101370 lng=-43.20937270 maxbounds=-22.91101370,-43.20937270 detect-retina zoomcontrol dragging !scrollwheel !attribution !touchZoom !keyboard tileurl='https://stamen-tiles-{s}.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.jpg']

[leaflet-marker title='Boulders Beach' iconUrl='/wp-content/uploads/markers/epicside_icon_location_frontcolor_backwhite_framed_marker.svg' iconclass='marker_icon' iconSize='45.55,50' iconAnchor='21.195,50' shadowUrl='/wp-content/uploads/markers/epicside_icon_location_frontcolor_backwhite_framed_marker_shadow.svg' shadowSize='120.36,33.84' shadowanchor='10.466,33.536' maxWidth='150']Boulders Beach[/leaflet-marker]

[leaflet-marker title='Afrique du Sud' lat=-28.81662360 lng=24.99163900 iconUrl='/wp-content/uploads/flags/za.svg' iconSize='50,34' iconAnchor='25,17']Afrique du Sud[/leaflet-marker]

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?

**Comment by matbe81** [comment]
For sure. But using the wordpress plugin, i don't how how to insert the shortcode produced in plunker.

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* NativeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.

**Comment by matbe81** [comment]
OK. Thank you. Can you please instruct me on how to convert the WP shortcodes to plunker "plain browser" code ?

**Comment by IvanSanchez** [comment]
No idea. I don't know how the WP shortcodes work, in the same sense that I don't know how the Jupyter notebooks work, or the React hooks work, or where the TypeScript definitions are.
