### ISSUE TITLE
Disable single finger touch dragging on mobile devices

### ISSUE THREAD

**Issue by kgaba7** [Leaflet/Leaflet#8816]
### Checklist

- [X] I've searched through the [plugins](https://leafletjs.com/plugins.html) to make sure this feature isn't already available, or think it shouldn't require a plugin.
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this feature hasn't been requested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Motivation

I got a webpage, where I use the Leaflet map library. 
When I open the page on a mobile phone, the map takes up the whole screen, and since single finger dragging is not disabled, I cannot scoll down the page further.  

### Suggested solution

DIsable single finger touch dragging, use multi finger instead. That sould allow you to scroll normally on the webpage, and use the map as well, if you wish.

**Comment by jonkoops** [comment]
Duplicate of #4544
