### ISSUE TITLE
createTile() is passed coords which appear incorrect when transformed with layerPointToLatLng().

### ISSUE THREAD

**Issue by fadedbee** [Leaflet/Leaflet#8858]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. Create a custom layer, starting with:
```
      L.GridLayer.CanvasCircles = L.GridLayer.extend({
        createTile: function (coords) {
            var layer_lat_lng = window.map && window.map.layerPointToLatLng ? window.map.layerPointToLatLng(coords) : null;
            console.log("coords", coords, "layer_lat_lng", layer_lat_lng);
```
2. Navigate in the web browser to the Royal Observatory, Greenwich, London, England.
3. Look at the log output from the `console.log` line above.  (In the screenshot below.)

### Expected behavior

The coordinates passed into `createTile()` should yield a longitude very slightly less than zero.  i.e. East of the Greenwich Meridian.

### Current behavior

The longitude for the createTile() calls are all around 0.67 degrees, which is too far to the south-west, beyond Maidstone in Kent.

![image](https://user-images.githubusercontent.com/33653994/220606507-c533e269-7af1-467d-baf3-4ee4822e2620.png)

### Minimal example reproducing the issue

https://plnkr.co/edit/jUHSlGje2gNniEkE

### Environment

- Leaflet version: 1.5.1+build.2e3e0ff
- Browser (with version): Firefox 110.0 (64-bit)
- OS/Platform (with version): Ubuntu 18.04

**Comment by IvanSanchez** [comment]
You the same person from https://stackoverflow.com/questions/75530769/how-do-i-transform-between-points-and-layer-points ?

The way this issue is written is unfortunately insufficient - there's no clear declaration of what the expected output would be for *what input*.

Please update to 1.9, and pay attention to the code at https://github.com/Leaflet/Leaflet/blob/1fa85b6c3ce6e01c7a0cc40286a0bb2aee9a35e5/src/layer/tile/GridLayer.js#L732-L751

...as well as the `getTileUrl` method implemented in `L.TileLayer.WMS`.

**Comment by fadedbee** [comment]
I went to the trouble of creating https://plnkr.co/edit/jUHSlGje2gNniEkE which I assume uses the latest leaflet.

>  You the same person from https://stackoverflow.com/questions/75530769/how-do-i-transform-between-points-and-layer-points ?
Yes, but this is a different question.

**Comment by fadedbee** [comment]
Working now, thanks. https://plnkr.co/edit/E1tRQJ8mBT1kTYBK

**Comment by IvanSanchez** [comment]
Here:

```
L.GridLayer.DivCoords = L.GridLayer.extend({
	createTile: function (coords) {
		const bbox = this._tileCoordsToBounds(coords);
		
		const tile = document.createElement('div');

		tile.style.border = '1px solid black';

		const north = document.createElement('div');
		north.innerText = bbox.getNorth().toFixed(6);
		const south = document.createElement('div');
		south.innerText = bbox.getSouth().toFixed(6);
		const west = document.createElement('div');
		west.innerText = bbox.getWest().toFixed(6);
		const east = document.createElement('div');
		east.innerText = bbox.getEast().toFixed(6);

		north.style.background = 'rgba(255,255,255,70%)'
		north.style.position = 'absolute';
		north.style.top = 0;
		north.style.left = '50%';
		south.style.background = 'rgba(255,255,255,70%)'
		south.style.position = 'absolute';
		south.style.bottom = 0;
		south.style.left = '50%';
		west.style.background = 'rgba(255,255,255,70%)'
		west.style.position = 'absolute';
		west.style.top = '50%';
		west.style.left = 0;
		east.style.background = 'rgba(255,255,255,70%)'
		east.style.position = 'absolute';
		east.style.top = '50%';
		east.style.right = 0;

		tile.appendChild(north);
		tile.appendChild(south);
		tile.appendChild(west);
		tile.appendChild(east);

		return tile;
	},
});
```

Or: https://plnkr.co/edit/m8IAOnu2tXyP0jhN

> Yes, but this is a different question.

No it's not, pal. You're confusing tile coordinates with origin-pixel-relative pixel coordinates. Your problem is GIGO.

> The input is panning to Royal Observatory, Greenwich, London, England. It's a location of special significance as it is on the Greenwich Meridian and so should have a longitude of zero.

Actually it's about 300 meters away because of historical shifts to the datums.

**Comment by fadedbee** [comment]
Thanks for the information.  The garbage which came out was only a few miles away from what I expected, so I was confused.
