### ISSUE TITLE
map will be hidden when pinch in to move outside the display area, if the map setting CRS.Simple and negative minZoom value.

### ISSUE THREAD

**Issue by masa-kunikata** [Leaflet/Leaflet#8865]
### Checklist

- [x] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. Go to https://masa-kunikata.github.io/leaflet-pinch-zoom/#/ with devices with touch zoom enabled(smartphones).

2. Pinch in the map to a size smaller than the minimum zoom (-0.8) and move it outside the display area.

3. **there is no map displayed.**

4. if user pinch out or click [+] button to zoom, the map is displayed agin .

### Expected behavior

The map is displayed in the center of the display area at minimum zoom (-0.8).

### Current behavior

[pinch_zoom.webm](https://user-images.githubusercontent.com/11450563/221504963-af066a05-d44b-46ca-a73c-ce7ee0ef3317.webm)

### Minimal example reproducing the issue

https://masa-kunikata.github.io/leaflet-pinch-zoom/#/

### Environment

- Leaflet version: 1.9.3

iOS
- Browser (with version): Safari, Chrome 110
- OS/Platform (with version): iOS 15.6.1

Android
- Browser (with version): Brave 1.26, Chromium 91
- OS/Platform (with version): Android 10

---

sample repository
https://github.com/masa-kunikata/leaflet-pinch-zoom

Leaflet setting
https://github.com/masa-kunikata/leaflet-pinch-zoom/blob/main/src/components/LeafletNegativePinchZoom.vue#L24-L50

**Comment by IvanSanchez** [comment]
Is this reproducible *without* Vue?

**Comment by masa-kunikata** [comment]
Yes, this is reproducible withtout Vue. 

sample on Plunker
https://plnkr.co/edit/ULjCIReeqDxsA2Bt

**Comment by IvanSanchez** [comment]
This seems to be closely related to https://github.com/Leaflet/Leaflet/pull/8613#discussion_r1111985689 (behaviour of fractional `min`/`maxZoom`). I think it's not worth researching this bug any further, but rather focus on completing that PR and working from there.

A workaround for this is to have integer values for the `L.TileLayer`'s `minZoom` (e.g. `-1`), but fractional for the `L.Map` (e.g. `0.8`). See https://plnkr.co/edit/yuUE4VKM1WQR7JQO

**Comment by masa-kunikata** [comment]
@IvanSanchez 
Thank you for your reply.

The workaround settings you provided (in the table below) did not work.
With zoom level -0.8, the map does not show up on either a smartphone or a PC.
(possibly because the image URL for zoom level -1 does not exist)

|L instance|minZoom|
|:--:|:--:|
|TileLayer|-1|
|Map|-0.8|

Sample Plunker https://plnkr.co/edit/Da0Igq7DxeFIm9uf

---

I also tried the method of modifying GridLayer.redraw (monkey patch below) in reference to https://github.com/Leaflet/Leaflet/pull/8613#discussion_r1111985689 , but that did not work either.


```
import { GridLayer } from 'leaflet'

GridLayer.prototype.redraw = function(){
  console.log("patch redraw")
  if (this._map) {
    this._removeAllTiles();
    const tileZoom = Math.round(this._clampZoom(this._map.getZoom())); // <--- here
    console.log({tileZoom})
    if (tileZoom !== this._tileZoom) {
      this._tileZoom = tileZoom;
      this._updateLevels();
    }
    this._update();
  }
  return this;
}
```
