### ISSUE TITLE
Tooltip is not displayed at all

### ISSUE THREAD

**Issue by ZhukDmitry** [Leaflet/Leaflet#8866]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Hi
I moved from version 1.6 to the last 1.9.3 and my code is not work. It is like

  marker7.bindTooltip(hoverString7);
  marker7.on('mouseover', function(event) {
    marker7.openTooltip();
  });
  marker7.on('mouseout', function(event) {
    marker7.closeTooltip();
  });
  

The same reaction for polylines.
There is not any error, but tooltip too

### Expected behavior

Tooltip have to be displayed

### Current behavior

Tooltips for placemarks and polylines is not displayed, no any errors

### Environment

- Leaflet version: 1.9.3
- Browser (with version): Firefox, Chrome
- OS/Platform (with version): Windows

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?

**Comment by ZhukDmitry** [comment]
Preparing example, in pure case it works. I'll investigate where is my problem. In my joomla extension or try to reproduce full example with error. I'll write a little bit later

**Comment by ZhukDmitry** [comment]
Hi

I found out problem. It is default joomla template. It overrides CSS style for [role=tooltip]:not(.show){

I will write them to fix that problem. You can close my issue request. I willl write in my support forum about that problem and how to fix it temporary.
