### ISSUE TITLE
Points on the map are not being shown when zoomed in

### ISSUE THREAD

**Issue by makahmad** [Leaflet/Leaflet#8870]
### Checklist

- [ ] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [ ] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. go to https://www.webapps.nwfsc.noaa.gov/data/map
2. search for dover sole in the upper left species field
3. click on Trawl in the Layers menu then Catch
4. try to zoom in to any point that's shown 
5. As you zoom in the points vanish however when you click around that region, the tooltip for that point opens up with the data. So the points are there but invisible
6. 
<img width="1558" alt="Screenshot 2023-02-27 at 7 23 48 PM" src="https://user-images.githubusercontent.com/19351474/221745979-33b2fd3d-52ca-4310-9541-aac521fb3b10.png">
<img width="1196" alt="Screenshot 2023-02-27 at 7 23 37 PM" src="https://user-images.githubusercontent.com/19351474/221745986-0eefb572-6a2b-482d-aeaf-ce01271f8e08.png">
<img width="1310" alt="Screenshot 2023-02-27 at 7 23 25 PM" src="https://user-images.githubusercontent.com/19351474/221745991-3d1fa978-1283-4c86-9f0f-554c0ea9d9c3.png">

### Expected behavior

I expect to the see the points at the final zoom level when there's no aggregating. This used to work and suddenly stopped working.

### Current behavior

As you zoom in and the points expand, the individual points disappear

### Minimal example reproducing the issue

https://www.webapps.nwfsc.noaa.gov/data/map

### Environment

- Leaflet version: 1.3.1
- Browser (with version):  Chrome 110.0.5481.177 
- OS/Platform (with version): MacOS Ventura

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?

**Comment by makahmad** [comment]
@IvanSanchez to reproduce it, just go to https://www.webapps.nwfsc.noaa.gov/data/map and complete those steps above. 
The code is all public as well. You can go to https://www.webapps.nwfsc.noaa.gov/data/view2/view2.js and search for getPlotTrawlCatch as that's the function that plots the points in the error explained above.

**Comment by IvanSanchez** [comment]
That's not how bug reporting works. It's *your* responsibility to isolate the bug and be sure that (in this case) it's a Leaflet bug. That why we have the "I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.)." checkbox.

It is **not** within the maintainers' responsibilities to debug other people's application code.

**Comment by IvanSanchez** [comment]
@makahmad Y'know what, you seem new here and maybe you should go watch https://media.ccc.de/v/bucharest-322-the-secret-life-of-open-source-developers .

**Comment by makahmad** [comment]
@IvanSanchez I think perhaps this issue needs to be resolved in https://github.com/Esri/esri-leaflet-vector 
This app has been running for 10 years and suddenly the points are not showing anymore. Doesn't make sense.
