### ISSUE TITLE
click event with canvas

### ISSUE THREAD

**Issue by fredsun** [Leaflet/Leaflet#8884]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [ ] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. when  use the Leaflet.VectorGrid only,  gridLayer.on("click"...） method can work.
2. when  add leaflet.canvasmarker to map [leaflet.canvasmarker](https://github.com/eJuke/Leaflet.Canvas-Markers)
or add  glayers into map ![gLayers.Leaflet](https://github.com/Sumbera/gLayers.Leaflet)
the gridLayer.on("click"...) doesn't work. 

the canvaslayer will intercept all the click event? 
add "point-event" or "z-index" to penetrate the click? it seems doesn't work.
four pages answer from "https://stackoverflow.com/questions/tagged/leaflet ", user "canvas" and "click" as keykeywords also can't fix this.
from https://leafletjs.com/examples/map-panes/  , createPane and setzIndex=650 also doesn't work

### Expected behavior

gridLayer.on("click"...) & map.on("click"...) should work

### Current behavior

gridLayer.on("click"...) & map.on("click"...) doesn't work

### Environment

- Leaflet version: 1.9.3
- Browser (with version): chrome  111.0.5563.64
- OS/Platform (with version):  Windows 10 laptop

**Comment by IvanSanchez** [comment]
Hi @fredsun,

I see that English is not your first language. It is a bit difficult to understand you. I do not know if your problem is in (1) Leaflet, (2) Leaflet.CanvasMarker or (3) Leaflet.VectorGrid.

It's true that `L.GridLayer`s do not react to pointer events. That should be easy to implement, using `addInteractiveTarget` from `L.Layer`. (i.e. call `this.addInteractiveTarget(this._container);` in `GridLayer`'s `onAdd`)

**Comment by fredsun** [comment]
thanks for trying to understand my english!

the problem might be the influence of （2）Leaflet.CanvasMarker  on （3）Leaflet.VectorGrid.
it's a third party problem. I found stackoverflow and panes demo, but I still don’t know how to deal with the conflict between these two controls. 

here's the Minimal example. 
>https://plnkr.co/plunk/bhSwAAMRFzJ6ncBw

in `"index.js"`,
when using only this method `buildMapGrid();` which in line 47, 	
the grid item  can be click, and when the zoom >14, it can give me a popupwindow after click grid item. that's my expected behavior. 
![](https://github.com/fredsun/RES/blob/ab26ea4ef476bb6f54975c701664eb2bd4300fb6/demo-leaflet-canvas-click.png?raw=true)
but when i add the method `drawPlane();`  in line 48  to add a canvasMarkerLayer. 
the grid item can't be click . 
current behavior like this
![](https://github.com/fredsun/RES/blob/3e7c1cdb3c323816930c9989bdf4d1343d2bc8e8/demo-leaflet-canvas.png?raw=true)

i had already set the options `interactive` in line 56,107,111 of `"index.js"` . but it doesn't work

**Comment by Falke-Design** [comment]
The problem is that the plane-layer is overlapping the interactive grid layer. Just disable the pointer events on the plane-layer:
```
line 58: ciLayer._container.style.pointerEvents = 'none';
```
https://plnkr.co/edit/4ZolbwyV70aGWZiN
