### ISSUE TITLE
Stand-alone Tooltip with position sticky not moving with mouse position

### ISSUE THREAD

**Issue by plarner30** [Leaflet/Leaflet#8886]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. Add a standalone tooltip to the map, not bound to anything, with the option sticky: true. I think stanalone tooltips are fine as mentioned in the documentation

### Expected behavior

Tooltip should follow the mouse as has sticky option set

### Current behavior

Tooltip stays in original position

### Minimal example reproducing the issue

https://plnkr.co/edit/1BLeK6ZIFZ6YRDJT

### Environment

- Leaflet version: 1.9.3
- Browser (with version): Chrome 110
- OS/Platform (with version): Windows 10

**Comment by Falke-Design** [comment]
`sticky` only works together with a layer where the Tooltip is binded to.
![grafik](https://user-images.githubusercontent.com/19800037/230737805-403c9849-7b36-4901-a62c-7cf9f48726fd.png)


You need to create this by your self:
```
	var tooltip = L.tooltip(L.latLng([40.02531407536202,32.804961204528816]), { sticky: true, permanent: true }).setContent('test');
	tooltip.addTo(map);
	map.on('mousemove', (e)=>{
		tooltip.setLatLng(map.layerPointToLatLng(e.layerPoint));
	});
```
