### ISSUE TITLE
`LayerGroup.addLayer()` : the added layer is visible even though the layer group is disabled.

### ISSUE THREAD

**Issue by docentYT** [Leaflet/Leaflet#8894]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

```ts
let myGroup = L.layerGroup();
let overlayMaps = {
    "my group": myGroup 
}

let layerControl = L.control.layers(baseMaps, overlayMaps).addTo(map);
myGroup.addTo(map);

// The user disables the layer

myGroup.addLayer(some_random_layer);
```

### Expected behavior

Added `some_random_layer` will not be displayed.

### Current behavior

The `some_random_layer` is visible.

### Environment

- Leaflet version: `1.9.3`
- Browser (with version): Opera GX LVL4 (core: 96.0.4693.104)
- OS/Platform (with version):  Windows 11 Version 10.0.22621 Compilation 22621

**Comment by IvanSanchez** [comment]
Can't reproduce. See https://plnkr.co/edit/oCTl6f08Vq2r6EST .

**Comment by docentYT** [comment]
It appears that the problem only occurs with geojson.
https://plnkr.co/edit/NorMdAjtD7DlBwlZ
