### ISSUE TITLE
Use default mouse cursor for buttons

### ISSUE THREAD

**Issue by zdila** [Leaflet/Leaflet#8898]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Add a zoom control to the map.

### Expected behavior

Default (arrow) cursor should be used there. According to W3C the pointer cursor should only be used for links. 

See eg. https://ux.stackexchange.com/questions/105024/why-dont-button-html-elements-have-a-css-cursor-pointer-by-default/105027#105027

### Current behavior

Controls (eg. zoom control) uses `cursor: pointer` on buttons.

### Environment

- Leaflet version: 1.9
- Browser (with version): Chrome 111
- OS/Platform (with version): Linux

**Comment by Falke-Design** [comment]
Thank you for this information. 

If you read through the comments many people are thinking that this rule is outdated. Microsoft and Apple are both having in theier guidelines that only links should have a hand pointer, but they are not doing it on theier own website too.

I think we should keep the hand-pointer for interactive elements too, but I'm open for discussions.

@Malvoz maybe you want to add something?

**Comment by Vedant-Manjrekar** [comment]
The change of cursor from arrow to hand-pointer when hovered over the button gives a hint to the user that the following button is clickable. Hence I believe hand-pointer is fine for the buttons and should not be changed.

**Comment by Malvoz** [comment]
> According to W3C the pointer cursor should only be used for links.

The CSSWG's Author Requirements was changed to the following in https://github.com/w3c/csswg-drafts/commit/272dd50ed23ee2fa24bc8a58d25378fc12711c73 (emphasis mine):

> Authors should use pointer on links _**and may use on other interactive elements**_.

I personally agree with @Falke-Design and @Vedant-Manjrekar to keep `cursor: pointer`, for the reasons mentioned.

> Are these elements currently `button` elements? If not, I think that is the best semantic change we can do.

@jonkoops Agree! That's https://github.com/Leaflet/Leaflet/issues/7821.
