### ISSUE TITLE
Is it possible to sort multiple geoJSON layers

### ISSUE THREAD

**Issue by l406054531** [Leaflet/Leaflet#8899]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Expected behavior

I want to be able to set the display order of each geoJSON layer based on some action on the page, and have CircleMarker on each layer.

### Current behavior

At the moment I want to set the order of the layers based on certain actions on the page, but calling `setZIndex()` doesn't seem to work. `bringToFront()` does sort the selected layers to the top layer, but that's not what I want, I want each layer to be sorted according to the rules I set.

### Environment

- Leaflet version: 1.7.1
- Browser (with version): Google Chrome
- OS/Platform (with version): Windows10

**Comment by jonkoops** [comment]
When reporting an issue please use the latest version of Leaflet so that we can ensure this not a bug that has already been resolved. Also please provide a minimal example reproducing your issue, without it it is very unlikely that you will receive an answer.

**Comment by Falke-Design** [comment]
Only `ImageOverlay` and `GridLayer` has the function `setZIndex`. So it will not work with other layers.

You need to create your own ZIndex function for layers.
