### ISSUE TITLE
All maps should show a scale bar by default

### ISSUE THREAD

**Issue by eMPee584** [Leaflet/Leaflet#8902]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. Find an embedded map on some website where you want to check out how to get somewhere
2. After initial orientation, you wonder about the distances for the locations displayed to estimate travel length or whether it is in walking distance.
3. You notice that there is no scale bar and that you will have to open **another map** to find the scale information.

### Expected behavior

- Basic cartography: **every map, under all circumstances, should have a scale bar**.
- That gmaps made a bad precedent turning it off is a disaster, and copying it multiplies it.
- For an embedding-API, making this opt-out is passably acceptable behaviour.

### Current behavior

The scale bar control has to actively be enabled by each website developer.

### Minimal example reproducing the issue

https://plnkr.co/edit/xF0j1GyTWjsuOyB9

### Environment

- Leaflet version: current
- Browser (with version): any
- OS/Platform (with version): any

**Comment by jonkoops** [comment]
I don't see a convincing reason to enable this by default. We try to keep the defaults to a minimum in terms of UI and the user can choose to add what they believe is useful for their application.

**Comment by mourner** [comment]
> Basic cartography: every map, under all circumstances, should have a scale bar.

No, it shouldn't.

**Comment by eMPee584** [comment]
> "[I]ncluding a scale underneath **each** map is critical"

from the book "How to make maps -An introduction to theory and practice of cartography" (2021)

I already tried to give a convincing reason: leaflet maps are embedded in lots of travel-related applications. Without a scale bar, there is no way to estimate distances! That reduces the usability of a large percentage of embedded maps to near zero. Ok, city A is left of city B. I already *knew* that. To have any sense of the actual distance, I have to open up **another map application**?!
Not displaying it has no tangible benefit. Visual clutter? A scale bar is the most relevant part of the map! In a world of fake and folly, why dumb down even maps? 

From same book:
> ### Scale
> Including a map scale is important for most maps. **The scale becomes an even more
> critical element if the map is intended for navigation**, for which calculating distances
> to travel could be a key part of the map’s use. Many people who work in cartography
> consider scale bars to be non-negotiable, but you might notice that some of the maps
> in the map gallery lack a scale bar. Is this an important omission from that map? As you
> consider the question, remember to contemplate the purpose of the map, its audience,
> and the medium. **Would inclusion of a scale bar serve to help the map achieve its goal
> or clarify important information for readers?**

The minimum UI should include the scale bar. Please discuss this further in your team.

**Comment by eMPee584** [comment]
> The scale is **essential in most cases**, but it should be small and unob-
> trusive, in a corner of the map.

from _Practical Handbook of Thematic Cartography_ (2020)
