### ISSUE TITLE
Blend mode on leaflet tiles causes visual artifacts on overlap

### ISSUE THREAD

**Issue by joeberkovitz** [Leaflet/Leaflet#8905]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Add a custom `GridLayer` to a Leaflet map in which the tiles of the grid:
- are permitted to exceed tile boundaries by use of CSS `overflow: visible`
- have features whose visual representations overlap features in adjacent tiles

This is a valid use case for `GridLayer` instances that are displaying an underlying vector dataset of points, rather than a set of image tiles. In this case, each point in the dataset belongs to a single tile, but will be visually displayed as an icon of some kind whose extent will go outside the tile's boundary if the point is just inside the boundary. Thus clipping must be disabled in order for icons not to be truncated at tile borders.

### Expected behavior

Overlapping markers in adjacent custom GridLayer tiles should appear with expected colors:

<img width="98" alt="image" src="https://user-images.githubusercontent.com/165916/230160336-1289900a-ef4a-4d1b-9cb5-4686d6a8d349.png">

### Current behavior

Overlapping markers appear with improperly blended colors:

<img width="143" alt="image" src="https://user-images.githubusercontent.com/165916/230161877-7aec380a-3360-4324-9539-c260eb3b1ddc.png">

### Minimal example reproducing the issue

https://gist.github.com/joeberkovitz/6132abe9df80a8f114372ac3f44a1ab3

### Environment

- Leaflet version: main branch as of https://github.com/Leaflet/Leaflet/commit/0392b7f44481119169e3db4babe2eab39cf05b59 which appears to have introduced the problem
- Browser (with version): Chrome 112.0.5615.20, Safari 16.1 , Firefox 110.0.1
- OS/Platform (with version): MacOS Ventura, iOS 15

**Comment by joeberkovitz** [comment]
Note that it is the broad-brush CSS selector `.leaflet-container .leaflet-tile` that causes the problem with this use case, by applying CSS `mix-blend-mode: plus-lighter;`. The other selectors are restricted to `img` elements and don't trigger the bug.

**Comment by IvanSanchez** [comment]
This was obviously introduced in https://github.com/Leaflet/Leaflet/pull/8891 . I guess that changing the CSS selector to a slightly more specific one (applying only to `<img>`s and not to `<svg>`s) should work.

i.e. instead of 
```
.leaflet-container .leaflet-tile {
```

replace that with 

```
.leaflet-container img.leaflet-tile {
```

I guess I can prepare a PR for this by next monday.

**Comment by joeberkovitz** [comment]
Agree that the more restrictive selector looks right. In cases where the tile _is_ an image, the blend mode is applicable, but not in other cases.
