### ISSUE TITLE
Safari 16.4 preventOutline / tests not working anymore

### ISSUE THREAD

**Issue by Falke-Design** [Leaflet/Leaflet#8908]
The new Safari version 16.4, released on 27.03, breaks the `preventOutline` test. `currentcolor` is returned instead of `none` :

![grafik](https://user-images.githubusercontent.com/19800037/230736434-84fd4685-ef58-4217-862f-316c3b244f3b.png)

I tried to test it with BrowserStack but they have only version 16.3. 
Rlease notes: https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes

In [MDN Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/outline) I found: 
![grafik](https://user-images.githubusercontent.com/19800037/230736987-db01a062-2218-4442-a9f7-020b8cf4c10a.png)

We should also test if something has changed for the user.

**Comment by jonkoops** [comment]
Let me take a look at this, I have a Macbook collecting dust in the corner for just this reason.
