### ISSUE TITLE
fitBounds throws "Invalid LatLng object: (NaN, NaN)" when passed duplicated bounds

### ISSUE THREAD

**Issue by maxlath** [Leaflet/Leaflet#8953]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

```js
L.map('map').fitBounds([[51.505, -0.09], [51.505, -0.09]])
// throws "Error: Invalid LatLng object: (NaN, NaN)"
```

### Expected behavior

It should not throw an error

### Current behavior

It throws "Error: Invalid LatLng object: (NaN, NaN)"

```
Error: Invalid LatLng object: (NaN, NaN)"
    LatLng leaflet-src.js:1473
    unproject leaflet-src.js:1775
    pointToLatLng leaflet-src.js:1614
    unproject leaflet-src.js:4105
    _limitCenter leaflet-src.js:4670
    setView leaflet-src.js:3294
    fitBounds leaflet-src.js:3411
```

### Minimal example reproducing the issue

https://jsfiddle.net/ntqf3vhL/

### Environment

- Leaflet version:  1.9.3
- Browser (with version): Firefox 113.0
- OS/Platform (with version): Linux/Ubuntu 22.04.2

**Comment by Falke-Design** [comment]
In your demo, you are using Leaflet 1.0.0. With the newest Leaflet version it works fine.
https://jsfiddle.net/wreqLvfo/
