### ISSUE TITLE
Leaflet NPM Package contains different code than Github Repo does

### ISSUE THREAD

**Issue by Beamer92** [Leaflet/Leaflet#8954]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Using Leaflet's NPM package at version 1.7.1

- Create a Marker using `L.marker([xxx, yyy], options)` (bonus points for using a custom Icon or other options according to the documentation)
- Add it to the map
- Click on the Marker
- Observe (hopefully) an error pointing to the Marker.js for `this.options.icon.options` being undefined

It seems like if there was really a problem with Markers in 1.7.1 then someone would've pointed it out by now, but that makes it all the more baffling.

### Expected behavior

I can use Markers out of the box, with custom Icons or any other Marker options, without an error being thrown.

### Current behavior

I have a bug that concerns Markers, but points to a potential issue(?) in the Marker.js code from the NPM package. The jist of that is when I download the leaflet npm package (1.7.1 specifically, but it appears in 1.9.3 as well), I see in  `...\node_modules\leaflet\src\layer\marker\Marker.js` there is a _panOnFocus() function near the bottom of the file. 

However, looking at the repo here on github, that code isn't present. This isn't the only instance of extra code appearing in there but its the best example. 

That seems strange to me. Why is there extra code there?

The result of that, which I'm seeing as a bug with my Markers, is when I create a marker using `L.marker([xxxx, yyyy], options)` and click on it on my map, I get an error from _panOnFocus() pointing to `this.options.icon.options` where `this` appears to be a Marker. But `this.options` is just `true. Its not an object. Its just the boolean `true`. 

Then obviously it throws an error. And I'm just baffled as to why and what's going on to make that happen. There's something in there causing a problem and I'm not sure what it is. But mostly I'm not sure why its there at all.

However, if I just make a custom Marker myself by extending Layer and using the same Marker.js code as it appears here in Github (without the extra code npm has) then my Markers work beautifully. Other existing code that references `this.options.whatever....` all resolves fine. 

I do have other packages from npm for leaflet that I entertain could've been causing this but if I'm seeing this code in the leaflet node modules folder then it seems unlikely. 

package.json looks like this for leaflet modules. Yes its an old app.
```
  ...
  "leaflet": "^1.7.1",
    "leaflet-draw": "^1.0.4",
    "leaflet-editable": "^1.2.0",
    "leaflet-mouse-position": "^1.2.0",
    "leaflet.path.drag": "^0.0.6",
...
```

### Environment

- Leaflet version: 1.7.1
- Browser (with version): Chrome 113.0.5672.93
- OS/Platform (with version): Windows 11

**Comment by IvanSanchez** [comment]
I'm looking at https://unpkg.com/leaflet@1.7.1/dist/leaflet-src.js , and `_panOnFocus` is nowhere to be seen. I'm also looking at https://github.com/Leaflet/Leaflet/blob/v1.7.1/src/layer/marker/Marker.js , and there's no `_panOnFocus` either.

Please double-check your claim that the NPM package has different code.

**Comment by Beamer92** [comment]
It's not in the GitHub repo anywhere I've found. All the devs in my team can see it in the leaflet folder that gets loaded into node-modules when doing an npm install and that's the only time we've found it. Just bizarre.

Using the code as it is on GitHub and making our own Marker with it works beautifully. It just seems to be that the node module packing coming down is different than everything else we're seeing.

I will see if I can get a repro in a jsfiddle or something as well.

**Comment by Falke-Design** [comment]
`_panOnFocus` was not in 1.7.1 #8042

**Comment by IvanSanchez** [comment]
> All the devs in my team can see it in the leaflet folder that gets loaded into node-modules when doing an npm install and that's the only time we've found it. 

If your devs are running `npm install leaflet@1.7.1` and are getting something different than https://www.npmjs.com/package/leaflet/v/1.7.1?activeTab=code , then it sounds like a problem in your side.

**Comment by neoacevedo** [comment]
I have no clue if I'm wrong but the v1.9.4 in github and in bower, only have the css file and the images directory but npm has the css file, the images file, the js files and the js map files.

Maybe anything I can't see?
