### ISSUE TITLE
marker.options.draggable not working after create this marker

### ISSUE THREAD

**Issue by sunbeichen** [Leaflet/Leaflet#8973]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. I use a switch to control the draggable of a marker.
2. which is 
`<div class="form-check form-switch">`
                      `<input
                        class="form-check-input"
                        type="checkbox"
                        role="switch"
                        id="dragSwitch"
                      />`
`</div>`
3. I addeventlistener to this switch and let `marker.options.draggable = switch. Checked`
4. I use `console.log()` to show the `switch.check` and 'marker.options.draggable'. They do change synchronously. 

### Expected behavior

the marker should be draggable after I trigger the switch. However it cannot be dragged whatever I click the switch.

### Current behavior

I initial the marker using `new L.marker(map.getCenter(), { draggable: false }).addTo(map)` and it cannot be dragged whatever I click the switch.

### Environment

- Leaflet version: 1.9.3
- Browser (with version): edge 113.0. 1774.35
- OS/Platform (with version): win11 laptop
I also use the plugin of marker, which is 
    "name": "leaflet-rotatedmarker",
    "version": "0.2.0",
Maybe this is the reason. I don't know.

**Comment by sunbeichen** [comment]
Also, after I use `mark.dragging.enable()` and `mark.dragging.disable()`, it worked. But this is still a bug for leaflet.

**Comment by Falke-Design** [comment]
Leaflet don't support changing the `draggable` option after initializing. 
You need to init the marker with dragging and then disable it: 
```
const marker = L.marker(map.getCenter(), { draggable: true }).addTo(map);
marker.dragging.disable();
```

After clicking the checkbox, you can enable it:
```
document.getElementById('dragSwitch').addEventListener('click', ()=>{
	const checked = document.getElementById('dragSwitch').checked;
	if(checked){
		marker.dragging.enable();
	} else {
		marker.dragging.disable();
	}
})
```


https://plnkr.co/edit/xTWAu1yq5MPpTlfJ
