### ISSUE TITLE
Please tell me how to add JwtToken authentication when loading tile maps. 

### ISSUE THREAD

**Issue by lhs1478** [Leaflet/Leaflet#8976]
### Checklist

- [ ] I've searched through the [plugins](https://leafletjs.com/plugins.html) to make sure this feature isn't already available, or think it shouldn't require a plugin.
- [ ] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this feature hasn't been requested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Motivation

Hi, this is a help wanted post and not an error, please forgive me for asking for help here。
Please tell me how to add JwtToken authentication when loading tile maps. My side of the service adds token authentication to the map, and I set token authentication in the request to get the map tiles。
This is the token authentication I added to the ajax request that needs to be added to the request header, how do I add it to the request in the tile
   headers: {
      "Authorization": `Bearer ${.accessToken}`,
      "X-Token": .token,
      "X-Authorization": `Bearer ${refreshToken}`,
    }

### Suggested solution

Thank you all for your help and I'm sorry for this terrible idea here

**Comment by jonkoops** [comment]
We use GitHub as an issue tracker and do not provide support here. For general usage please refer to the [Leaflet documentation](https://leafletjs.com). For support questions like "How can I do X with Leaflet?" please search or ask questions on [StackOverflow](https://stackoverflow.com/questions/tagged/leaflet) or [StackExchange](https://gis.stackexchange.com/questions/tagged/leaflet).
