### ISSUE TITLE
Probable confusion between companies in the "Trusted by the best" on leafletjs.com

### ISSUE THREAD

**Issue by Rpnpif** [Leaflet/Leaflet#8993]
### Checklist

- [ ] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [ ] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

In the "Trusted by the best" companies list on https://leafletjs.com/, I think that a wrong confusion between ign.com and ign.fr.
Ign.com from https://fr.ign.com/ does not show maps from leaflet to my knowledge and work in the entertainment domain.
But IGN https://ign.fr/ is the French _Institut national de l’information géographique et forestière_ (National Institute of Geographic and Forest Information, a French public state administrative establishment.
I know that it is used intensively leaflet.
The logo on https://leafletjs.com should be changed by this: https://fr.wikipedia.org/wiki/Institut_national_de_l%27information_g%C3%A9ographique_et_foresti%C3%A8re#/media/Fichier:IGN_logo_2012.svg.

### Expected behavior

Only companies that work with leaflet should be shown on https://leaflet.com.
fr.ign.com should be replaced by ign.fr and its logo on https://leafletjs.com

### Current behavior

I think that the wrong companies is shown.

### Environment

- Leaflet version:  https://leafletjs.com
- Browser (with version): NA
- OS/Platform (with version): the website

**Comment by mourner** [comment]
I originally added specifically for the gaming media — it used Leaflet extensively for its interactive game world maps, particularly for open world games like Skyrim. I'm not following the current uses closely.
