### ISSUE TITLE
If a popup is open, then the map.panTo() does not work

### ISSUE THREAD

**Issue by denyaalt** [Leaflet/Leaflet#8994]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Hi,
If a marker popup is open, then the map.panTo() function does not work.
Thanks.

### Expected behavior

The function is expected to be executed.

### Current behavior

If a marker popup is open, then the map.panTo() function does not work.

### Environment

- Leaflet version: 1.9.4
- Browser (with version): any
- OS/Platform (with version): any

**Comment by IvanSanchez** [comment]
Cannot reproduce: https://plnkr.co/edit/s3hzWyOV3vPiWrEq
