### ISSUE TITLE
CanvasMarker adds an extra Canvas - How to use default leaflet Canvas instead?

### ISSUE THREAD

**Issue by albertoamohp** [Leaflet/Leaflet#8995]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [ ] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Hi, I'm using this library for generating Markers (with text) in a canvas:
https://gitee.com/panzhiyue/Leaflet-CanvasMarker (this library is a fork of this https://github.com/eJuke/Leaflet.Canvas-Markers)

### Expected behavior

Be everything in the same canvas in order to have all the events (click, etc) on the same.

### Current behavior

It renders 2 canvas:
`<canvas class="leaflet-zoom-animated" width="3410" height="2486" style="transform: translate3d(173px, 5px, 0px); width: 1705px; height: 1243px;"></canvas>`

`<canvas class="leaflet-canvas-icon-layer leaflet-layer leaflet-zoom-animated" width="1421" height="1036" style="transform: translate3d(314.969px, 109px, 0px); pointer-events: none;"></canvas>`

### Environment

- Leaflet version: 1.9
- Browser (with version): Last Chrome ver
- OS/Platform (with version): Windows 10

**Comment by albertoamohp** [comment]
what I have tried before was:
```
_initCanvas: function () {
    this._container = this._map.getRenderer(this)._container; // Get the Leaflet map's default canvas
    if (this.options.zIndex) {
      this._container.style.zIndex = this.options.zIndex;
    }
    var size = this._map.getSize();
    this._container.width = size.x;
    this._container.height = size.y;
    this._ctx = this._container.getContext('2d');
    var animated = this._map.options.zoomAnimation && L.Browser.any3d;
    L.DomUtil.addClass(this._container, 'leaflet-zoom-' + (animated ? 'animated' : 'hide'));
  },
```

But this overrides all the previous content and just keep my last content.

**Comment by Falke-Design** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
