### ISSUE TITLE
Accessibility issue:  the popup close button on the map is a link role instead of button role

### ISSUE THREAD

**Issue by johnli388** [Leaflet/Leaflet#9001]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. go to map
2. use keyboard to navigate to the map and trigger the popup
3. use screen reader to read the close button on the popup
4. listen to the announcement of the close button

### Expected behavior

The expected behavior should be reading "close button"

### Current behavior

The screen reader reads  "link" instead of "close button".

### Environment

- Leaflet version: 1.6.0
- Browser (with version): Chrome latest
- OS/Platform (with version): MacOS

**Comment by Malvoz** [comment]
Thanks for the bug report @johnli388, this issue was fixed in v1.8.0 (https://github.com/Leaflet/Leaflet/pull/7794).
