### ISSUE TITLE
trackResize does not work properly when DOM element is invisible

### ISSUE THREAD

**Issue by blutorange** [Leaflet/Leaflet#9010]
### Checklist

- [ ] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

* Goto https://leafletjs.com/examples/quick-start/example.html
* Set `display: none;` on the `leaflet-container` via the dev tools
* Reszie the browser window's width to e.g. 500 pixels
* Disable the `display: none;` style again

---

The `trackResize` features works great, but there is a small issue. It does not resize itself properly when the element containing the Leaflet widget is invisible on page load; or when the browser window is resized while the element is invisible.

Fortunately, there is a simple fix: In the resize observer callback, check if the element is currently visible. If not, simply return. In our application, I've disabled resize tracking via `{trackResize: false}` and registered a ResizeObserver myself that checks for this, that works nicely.

https://github.com/Leaflet/Leaflet/blob/main/src/map/Map.js#L1343

```js
	_onResize() {
               if (this._container.offsetWidth <= 0 || this._container.offsetHeight <= 0) {
                 return;
               }
		Util.cancelAnimFrame(this._resizeRequest);
		this._resizeRequest = Util.requestAnimFrame(
		        function () { this.invalidateSize({debounceMoveend: true}); }, this);
	},
```

### Expected behavior

The map should look as if the browser window had been resized with the map being visible . 

This is how it looks when resized while visible:

![image](https://github.com/Leaflet/Leaflet/assets/2456413/afa16d0d-7fb1-4086-9d38-cb18b9233b36)

### Current behavior

The map kinda displays, but its dimensions are wrong and the container element is not filled up.

This is how it looks when resized while invisible:

![image](https://github.com/Leaflet/Leaflet/assets/2456413/15d9796c-9e57-4f31-a799-c804a73370c8)

### Minimal example reproducing the issue

https://leafletjs.com/examples/quick-start/example.html

### Environment

- Leaflet version: 1.9.3
- Browser (with version): Version 114.0.5735.198 (Official Build) (64-bit)
- OS/Platform (with version): 

Distributor ID:	Ubuntu
Description:	Ubuntu 22.10
Release:	22.10
Codename:	kinetic

**Comment by Falke-Design** [comment]
Leaflet `v1` resizes triggered by the `resize` event on the window: https://github.com/Leaflet/Leaflet/blob/e7df4a55ac15ca2f3ebc24ff91fbaf7d9c1b9e66/src/map/Map.js#L1325C50-L1325C50

In `v2` we added ResizeObserver, which solves this issue: https://github.com/Leaflet/Leaflet/blob/b6b56f6e707142c177fad2f67827a5007e56736a/src/map/Map.js#L1329

**Comment by TimNZ** [comment]
For anyone else finding this, since v2 is not released yet,
calling .invalidateSize() on the underlying leaftlet reference when needed does the job.

```
mapRef.current?.invalidateSize()
```
