### ISSUE TITLE
Is it expected that a click on a circle does not prevent a click on map event to be fired ?

### ISSUE THREAD

**Issue by Andromelus** [Leaflet/Leaflet#9011]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Using the following code snippet:

```html
<script>
const map = L.map('map').setView([51.505, -0.09], 13);

const tiles = L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
    maxZoom: 19,
    attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
}).addTo(map);

const marker = L.marker([51.5, -0.09]).addTo(map)
    .bindPopup('<b>Hello world!</b><br />I am a popup.').openPopup();

const circle = L.circle([51.508, -0.11], {
    color: 'red',
    fillColor: '#f03',
    fillOpacity: 0.5,
    radius: 500
}).addTo(map);

circle.on("click", () => {console.log("click on circle")})

function onMapClick(e) {
    console.log("click on map")
}

map.on('click', onMapClick);
</script>
```

### Expected behavior

When clicking on the circle, the click should not be detected by the map and, thus, the `click` event of the map should not be fired.

### Current behavior

When clicking on the circle, there are two events fired:

```
click on circle
click on map
```

The click "goes through" the circle and is detected by the map, firing two events. However, I did not click the map "directly", but the circle.

### Minimal example reproducing the issue

https://plnkr.co/edit/MyAAttMrpNgnIfyZ

### Environment

- Leaflet version:  1.9.4
- Browser (with version): Microsoft Edge Version 112.0.1722.58
- OS/Platform (with version): Windows 10

**Comment by diogogalvao** [comment]
What you're describing is called [event bubbling](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#event_bubbling).

If you need to prevent the event from bubbling up to the map, it must be done explicitly:

```javascript
circle.on("click", (ev) => {
	L.DomEvent.stopPropagation(ev);
	console.log("click on circle");
});
```

You can find it documented on [Circle options inherited from Path](https://leafletjs.com/reference.html#circle-bubblingmouseevents).
