### ISSUE TITLE
Can't import leaflet on Stackblitz for Angular 16

### ISSUE THREAD

**Issue by fireflysemantics** [Leaflet/Leaflet#9017]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

I've documented it on Stackoverflow. 

https://stackoverflow.com/questions/76614477/importing-leaflet-in-angular-16-stackblitz

This is the error.

```
Could not find a declaration file for module 'leaflet'. '/turbo_modules/leaflet@1.9.3/dist/leaflet-src.js' implicitly has an 'any' type.
Try `npm i --save-dev @types/leaflet` if it exists or add a new declaration (.d.ts) file containing `declare module 'leaflet';`
```

### Expected behavior

It should import on Stackblitz.  It has worked in the past.  I assume that an explicit typing declarations has to be made.

### Current behavior

Leaflet causes Stackblitz to error ...

### Environment

See Stackblitz

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* NativeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.
