### ISSUE TITLE
geojson data not displaying on a leaflet map

### ISSUE THREAD

**Issue by wawerukaranja55** [Leaflet/Leaflet#9027]
### Checklist

- [ ] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [ ] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

 am trying to display the coordinates I have saved in JSON format on a leaflet map. Neither the marker of the coordinates is showing nor am I getting any error. here is my geojson data and the code that should display the records on the map. Where might I be doing it wrong? am using leaflet 1.9.4 cdn css and js links

here is the code in the script

              var defaultLocation = [-1.286389,36.817223]

        var map = L.map('map')
            .setView(defaultLocation, 13);
            //.center(defaultLocation);
        
        var tiles = L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
            maxZoom: 19,
            attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
        }).addTo(map);
    
        var marker = new L.Marker([-1.2787474907651892,36.821225881576545]);
        marker.addTo(map);
    
      var geoJsondata = {
            "type": "FeatureCollection",
            "features": [
                {
                    "type": "Feature",
                    "properties": {
                        "name": "Example 1",
                        "amenity": "Baseball Stadium",
                        "iconSize": [50, 50],
                        "locationId": 1,
                        "image": "https://images.unsplash.com/photo-1688976694262-89230d6133ba?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHw3fHx8ZW58MHx8fHx8&auto=format&fit=crop&w=500&q=60",
                        "popupContent": "This is where the Rockies play!"
                    },
                    "geometry": {
                        "type": "Point",
                        "coordinates": [-1.2822121651282061, 36.82157993316651]
                    }
                },
                {
                    "type": "Feature",
                    "properties": {
                        "name": "Example 2",
                        "amenity": "Baseball Stadium",
                        "iconSize": [50, 50],
                        "locationId": 2,
                        "image": "https://images.unsplash.com/photo-1688728981543-df24d24d0116?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwyNXx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
                        "popupContent": "This is where the Rockies play!"
                    },
                    "geometry": {
                        "type": "Point",
                        "coordinates": [-1.2842580516508735, 36.816703677177436]
                    }
                },
                {
                    "type": "Feature",
                    "properties": {
                        "name": "Example 3",
                        "amenity": "Baseball Stadium",
                        "iconSize": [50, 50],
                        "locationId": 3,
                        "image": "https://images.unsplash.com/photo-1688966838599-05e6cf6628cf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwzMnx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
                        "popupContent": "This is where the Rockies play!"
                    },
                    "geometry": {
                        "type": "Point",
                        "coordinates": [-1.2815256914612605, 36.81707382202149]
                    }
                }
                
            ]
        }

    L.geoJSON(geoJsondata).addTo(map);

### Expected behavior

it show the points on the map with an icon

### Current behavior

it doesn't display the points for the icons

### Environment

- Leaflet version: 1.9.4
- Browser (with version): chrome 
- OS/Platform (with version):  window 10

**Comment by Falke-Design** [comment]
Works fine, but you need to go to the correct location on the map. You can achieve this with `map.fitBounds(geoLayer.getBounds())`.

https://plnkr.co/edit/yXEWxXav52plEWh2
