### ISSUE TITLE
Adding margin to div of Leaflet map displaces Layers

### ISSUE THREAD

**Issue by samkunz** [Leaflet/Leaflet#9028]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. Create a simple Leaflet map
2. Add some simple geometries, e.g. Polyline (see linked example below for what I used)
3. Add a margin, e.g. `margin-top: 60px;` to the `div` containing the Leaflet map

### Expected behavior

I would expect to see a margin above the map, and I would expect the content of the map to be the same regardless of the margin.

In my example linked below, this means:
- a Marker at southern end of Columbus Ave (intersection of Columbus, Washington, Montgomery)
- a Polyline running along Market St
- a Polygon south of Market St

In linked example below, this is what you get if you remove the `margin-top` connected to the `div`. This is what I would expect the map to look like, expect with a margin above it that does not affect the map itself

![screenshot-03](https://github.com/Leaflet/Leaflet/assets/7915122/a5d1130e-5036-42d6-9c93-74425a5ae795)

### Current behavior

There is in fact a margin above the map, but I've noticed several behaviors that shouldn't happen. In summary: Layers are displaced to the point of making the map inaccurate. (See screenshot 1.)

More specifically:
- The various geometries are not overlaid in their geographically accurate position based on the coordinates provided. I tested Marker, Polyline, and Polygon, and all are overlaid incorrectly.
- The base map is displaced downward, which I'm guessing means the `TileLayer` is getting displaced. An effect of this is that there is a grayed out area on the top of the map, which I'm assuming is related to tile loading.
- If you zoom in or out, the geometries (e.g. Polyline) move relative to the base map. (See screenshot 2.)

Screenshot 1:
![screenshot-01](https://github.com/Leaflet/Leaflet/assets/7915122/a1574957-d048-4e81-8d33-35d8a207ec67)

Screenshot 2:
![screenshot-02](https://github.com/Leaflet/Leaflet/assets/7915122/893777e8-96e2-4e42-9ef6-b77255bd4157)

### Minimal example reproducing the issue

https://plnkr.co/edit/ROztqU5niAbfCi4h

### Environment

- Leaflet version: 1.9.4
- Browser (with version):
  - Note: I'm seeing the same issue on all of the below browsers
  - Chrome Version 114.0.5735.198 (Official Build) (x86_64)
  - Safari Version 15.6.1
  - Firefox 68.0.1 (64-bit)
- OS/Platform (with version): macOS Catalina 10.15.7

**Comment by Malvoz** [comment]
You're using a generic `div` selector to set the margin, Leaflet uses a lot of divs so it is bound to break something. Use a more specific selector instead (e.g. `.leaflet-map` in the example).
