### ISSUE TITLE
L.Marker new property - visible

### ISSUE THREAD

**Issue by peter1599** [Leaflet/Leaflet#9042]
### Checklist

- [X] I've searched through the [plugins](https://leafletjs.com/plugins.html) to make sure this feature isn't already available, or think it shouldn't require a plugin.
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this feature hasn't been requested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Motivation

It would be a lot it easier if L.Marker would have a a property callled: visible (a boolean property).
If you want to make a poi filtering with the Leaflet/marker.cluster you have to "hack" a lot to make it work.

### Suggested solution

The idea would be similar to google map javascript visible property:
- If you set the property false the marker disappears from the map and also from the cluster and not just via setting opacity to 0. If you set it true it comes back.
If you set a cluster all marker visible property to false the whole cluster would disappear from the map. 

So if you make a range filter for pois, would be way easier to set all the markers visible property to false and only set true for those markers which are in your range.

That way only the markers show in the cluster which you gave true property.
It would look like this:
( In the video im using google javascript map library with their marker clustering @googlemaps/markerclusterer )

https://github.com/Leaflet/Leaflet/assets/25458870/e9d1acc8-797b-4a8d-9996-c11777943c8b

**Comment by Azbesciak** [comment]
Can't you just add/remove markers, as we are doing from the beginning? There is not much hacking as you said necessary.

**Comment by peter1599** [comment]
> Can't you just add/remove markers, as we are doing from the beginning? There is not much hacking, as you said, necessary.

Sadly, no. No matter what I try to use removeLayer or remove or removefrom non of them seems to remove the markers from the cluster and my markers getting duplicated if I add them in the cluster.

**Comment by Azbesciak** [comment]
Clustering is a different story, you need to directly update the markera list in it

**Comment by peter1599** [comment]
> Clustering is a different story, you need to directly update the markers list in it

Can you please show an example of how would I do that?

**Comment by Azbesciak** [comment]
Just call `addLayers(yourMarkers)` and `removeLayers(theSameMarkers)` on the cluster.
You can also access them directly with the private API of the markers' cluster, but then I guess you need to manage refreshing.

**Comment by peter1599** [comment]
I get that I could use opacity but that only solves half of my problem. I quote myself "marker disappears from the map and also from the cluster and not just via setting opacity"

Markers c an overlap each other and if the user click on a visible marker there could be an invisible one nearby that marker he clicks on that and he doesn't know why it got zoomed in to an empty area on the map.

+ It would bring a totally different marker info window that could cause more confusion.

**Comment by jonkoops** [comment]
I don't quite understand why removing the markers you don't need isn't good enough here. What would be the advantage of a 'visibility' state? As far as I can tell from the proposed solution, this doesn't really provide much benefit.

**Comment by peter1599** [comment]
@jonkoops 

Sorry for very late response. As we get more markers, it will become slow. Look at this video for example:

https://github.com/Leaflet/Leaflet/assets/25458870/8d11b481-8d06-4b91-b162-a2b44f3b3097

You can see that im doing removing and adding one by one cause it has that delay for adding all the markers to map. Means more marker = that lag becomes more and more large.

The property and the way i said how it could be implemented that would solve this issue.

And i dont believe it that anyone else who is working with more then 1000 markers and if he is adding removing all the markers for filtering he doesnt have this "little lag" which will grow if you add more and more markers.
