### ISSUE TITLE
Drawn Shapes Can Become Disconnected If Layers Are Removed From Map

### ISSUE THREAD

**Issue by bcwhite-code** [Leaflet/Leaflet#9043]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. Create some map layers.
2. Draw some shapes on top of it.
3. Remove some map layers.
4. Zoom in and out.

### Expected behavior

The drawn shapes should stay in the same place as the map moves and zooms.

### Current behavior

After an underlying layer is removed, the drawn shapes attach themselves to different locations.

https://drive.google.com/file/d/1vi7u7gD0gKl-8EyfwPuDIVbyUmzM3AkJ/view?usp=drive_link

In the video, you can see rectangles and how they're attached to buildings on the map.  Zooming out and in is fine until it goes in far enough to obscure the lower-level map seen at the sides.

Logic in my app then removes the now fully-obscured TileLayer layer to reduce load on the browser as there could otherwise be many in the stack.  The exact call is: `this.map.removeLayer(layer)`

After that, zooming in and out shows that the drawn rectangles are now in a somewhat fixed location.  Even zooming out to the point where the background layer is no longer obscured (and is re-added) does not fix the issue.  It remains broken until the rectangles are removed and re-added in the correct locations.

I tried to create a minimal reproduction (linked below) but couldn't get the problem to show up.  If I disable in my app the optimization of removing obscured layers, I don't see the problem so I'm sure it's related to that.

Is there a way to completely turn off a layer without removing it?

### Minimal example reproducing the issue

https://plnkr.co/edit/PAvQI2X2BWeWloxl

### Environment

- Leaflet version: 1.9.3, 1.9.4
- Browser (with version): Chrome 114.0.5735.199 (Official Build) (64-bit)
- OS/Platform (with version): Windows 10 desktop

**Comment by IvanSanchez** [comment]
> I tried to create a minimal reproduction (linked below) but couldn't get the problem to show up.

Then keep digging. No reproducible case means we have no confidence this might be a bug in Leaflet at all (and it feels like it's a race condition in your end instead).

I do hope you've looked for errors in the browser's console.
