### ISSUE TITLE
Need help draggable Circle and rectangle 

### ISSUE THREAD

**Issue by MuhammadHashir28** [Leaflet/Leaflet#9047]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Expected behavior

https://pubgmap.cc/map/savage.html

Kindly look into this I need to draw a circle like this and rectangle , Please help me out on this one how so current the map dragging ?  can you share a code for this  ?

### Current behavior

(http://assistcenter.gg/map)

### Minimal example reproducing the issue

https://pubgmap.cc/map/savage.html

### Environment

- Leaflet version: Latest 
- Browser (with version): Chrome 
- OS/Platform (with version): Windows

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
