### ISSUE TITLE
Is it possible to make google map apply style mapid on leaflet

### ISSUE THREAD

**Issue by luckyboy1688888** [Leaflet/Leaflet#9056]
### Checklist

- [X] I've searched through the [plugins](https://leafletjs.com/plugins.html) to make sure this feature isn't already available, or think it shouldn't require a plugin.
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this feature hasn't been requested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Motivation

Is it possible to make google map apply style mapid on leaflet

### Suggested solution

Is it possible to make google map apply style mapid on leaflet

**Comment by thi-git** [comment]
I solved this use url :http://{s}.google.com/vt/lyrs=m&pb=!1m5!1m4!1i{z}!2i{x}!3i{y}!4i256!2m3!1e0!2sm!3i656397257!2m6!1e2!2smaps_api!5i1!9m2!1e4!2b1!3m17!2szh-TW!3sUS!5e18!12m4!1e68!2m2!1sset!2sRoadmap!12m3!1e37!2m1!1ssmartmaps!12m4!1e26!2m2!1sstyles!2zcy5lOmcuZnxwLmM6IzJlMmUyZSxzLmU6Zy5zfHAudjpvZmYscy5lOmx8cC52Om9uLH....nxzLmU6Zy5mfHAuYzojMjkyOTI5fHAudjpvbixzLnQ6NnxzLmU6bC50LmZ8cC5jOiNmZmZmZmZ8cC52Om9u!4e0!23i1376099!23i1379903

it work fine for me

**Comment by IvanSanchez** [comment]
See https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant/
