### ISSUE TITLE
Rectangular tiles

### ISSUE THREAD

**Issue by joric** [Leaflet/Leaflet#9057]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

I'm trying to use non-rectangular tiles for non-geographical maps.

### Expected behavior

It seems pretty straightforward, we just use tileSize: L.point(w,h) in the tile layer options and L.CRS.Simple for the map.

### Current behavior

Unfortunately it breaks zoom, looks like when going from zoom level 3 to 4 and back the map shifts one tile vertically. Does anyone know why?

https://github.com/Leaflet/Leaflet/assets/852547/7e5fe9d7-236d-458a-8ca9-07599eefdbda

### Minimal example reproducing the issue

I don't have an example ready to show, I ended with square tiles here https://joric.github.io/viva-games/

The only mention of rectangular tiles I found: https://stackoverflow.com/questions/19848587/can-i-use-leaflet-for-epsg4326-rectangular-map maybe there are examples that don't have this issue? It doesn't happen for square tiles.

I used a [modified slicer](https://gist.github.com/joric/2cf2a4c09aa9c9b23bfcd68e6ca1d67a) for the rectangular tiles and it seem to slice properly, I guess it's something with the leaflet code. It only shifts vertically, not horizontally. Or maybe slicer is off (256x192 px tiles, 128x132 grid, 6 levels).

### Environment

- Leaflet version: 1.9.1
- Browser (with version): chrome 115
- OS/Platform (with version): win 11

**Upd.** yea. it was slicer, or rather dimensions. It works with 128x128 grid, but 128x132 does not comply with integer division (132 - 66 - 33 - 16.5 - 8.25 - 4.125). Closing.

**Comment by Falke-Design** [comment]
> Upd. yea. it was slicer, or rather dimensions. It works with 128x128 grid, but 128x132 does not support integer division (132 - 66 - 33 - 16.5 - 8.25 - 4.125). Closing.
