### ISSUE TITLE
Tooltips get stuck while panning

### ISSUE THREAD

**Issue by BathoryPeter** [Leaflet/Leaflet#9059]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

If you have several objects with tooltip close to each other, the open tooltip and nearby tooltips will be stuck on the screen after panning the map.

1. Open JSFiddle link
2. Move cursore over the area with circle markers (a tooltip will pop up)
3. Pan the map
4. Repeat steps 2. and 3. a few times.

Nearby tooltips appears and stuck there.

![tooltip_sticks](https://github.com/Leaflet/Leaflet/assets/19800037/c7be1df0-fdc9-4160-9b0c-459ddc5dda55)

### Expected behavior

After panning, only the already opened tooltip should be seen.

### Current behavior

Several tooltips stuck on the screen.

### Minimal example reproducing the issue

https://jsfiddle.net/BathoryPeter/qztj41c3/2/

```
let markers = new L.FeatureGroup().addTo(map);

[...Array(20).keys()].map(i => {
	[...Array(30).keys()].map(j => {
    	let lat = 47 + i / 100;
      let lon = 19 + j / 100;
      
      L.circleMarker([lat, lon])
      	.bindTooltip(`${lat} ${lon}`)
        .addTo(markers);
    });
});

map.fitBounds(markers.getBounds());
```

### Environment

- Leaflet version: 1.9.4
- Browser (with version): Vivaldi 6.1.3035 (latest stable)
- OS/Platform (with version): Ubuntu 23.04

**Comment by dscarb21** [comment]
This seems to be a legit bug, has been replicated on:
Windows 10.0.19045
Chrome 115.0.5790.171

**Comment by HappyViki** [comment]
I was able to reproduce stuck tooltip with 2 markers. When wiggling the map with a tooltip over another marker with a hidden tooltip, it seems to open the tooltip on the other dragged over marker after letting go of the map.

Before wiggle:
![image](https://github.com/Leaflet/Leaflet/assets/14225943/e08457ec-f8d9-4056-b4c8-07399a983f38)
After wiggle:
![image](https://github.com/Leaflet/Leaflet/assets/14225943/25ced780-fb55-4379-b1eb-1cd3634ab826)
