### ISSUE TITLE
Leaflet rendering issue in mobile view in React

### ISSUE THREAD

**Issue by AndrejGajdos** [Leaflet/Leaflet#9073]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. Go to [this](https://leaflet-rendering-bug.web.app/login) url on a mobile browser
2. type whatever email and password and submit

### Expected behavior

The map shouldn't overflow and navbar should be visible.

### Current behavior

The map overflows and navbar is not visible. Plese check this [recording](https://imgur.com/a/KEK3Xtx). User needs to hit refresh to see the navbar.

### Minimal example reproducing the issue

https://github.com/AndrejGajdos/leaflet-ins

### Environment

- Leaflet version: 1.9.4
- Browser (with version): Safari
- OS/Platform (with version): iOS

**Comment by jonkoops** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* NativeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers in a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by AndrejGajdos** [comment]
This is the fix:

`<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />`
