### ISSUE TITLE
Basemaps not loading for Layer Groups tutorial

### ISSUE THREAD

**Issue by finnshort** [Leaflet/Leaflet#9077]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Go to https://leafletjs.com/examples/layers-control/ and use the layer selector to choose 'streets' or 'satellite'.

### Expected behavior

Expect basemap to change

### Current behavior

Basemap doesn't load so just see a grey box. 403 error from mapbox in the console.

![image](https://github.com/Leaflet/Leaflet/assets/3713996/f3815517-6919-49fa-a17b-e2dbd6770a9e)

### Environment

- Leaflet version: N/A
- Browser (with version): Chrome 116.0.5845.110, Firefox 102.14.0esr 
- OS/Platform (with version): Mac OS Ventura 13.5

**Comment by Falke-Design** [comment]
An old version of the website deployed. The latest version is now live and it works again.
Thank you for reporting

**Comment by finnshort** [comment]
Thanks!
