### ISSUE TITLE
GeoJSON data w/ MultiPolygons is not displayed on the map

### ISSUE THREAD

**Issue by samilaine** [Leaflet/Leaflet#9083]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

As a first optional step _validate_ [GeoJSON data with MultiPolygons](https://geo.stat.fi/geoserver/postialue/wfs?service=WFS&version=2.0&request=GetFeature&typeName=pno&outputFormat=json) and [GeoJSON data with Polygons](https://kartta.hel.fi/ws/geoserver/avoindata/wfs?service=WFS&version=1.1.0&request=GetFeature&maxFeatures=300&typename=avoindata:Kaupunginosajako&srsname=EPSG:4326&bbox=2655963.172645998,8360611.663801174,2881730.528285009,8510872.799001848,EPSG:3857&outputFormat=json), so that you can be properly assured the data loaded indeed is valid GeoJSON in both examples below. Feel free to use your favourite validator or [this online service](https://www.itb.ec.europa.eu/json/geojson/upload).

1. _Save_ file [broken.html.txt](https://github.com/Leaflet/Leaflet/files/12574907/broken.html.txt) to disk, rename it to "broken.html", and load it into your browser. The file contains a minimal example where [valid GeoJSON data with MultiPolygons](https://geo.stat.fi/geoserver/postialue/wfs?service=WFS&version=2.0&request=GetFeature&typeName=pno&outputFormat=json) is loaded, but nothing is displayed on the map.
2. _Save_ file [works.html.txt](https://github.com/Leaflet/Leaflet/files/12574908/works.html.txt)., rename it to "works.html", and load it into your browser. The file contains a minimal example where [valid GeoJSON data with Polygons](https://kartta.hel.fi/ws/geoserver/avoindata/wfs?service=WFS&version=1.1.0&request=GetFeature&maxFeatures=300&typename=avoindata:Kaupunginosajako&srsname=EPSG:4326&bbox=2655963.172645998,8360611.663801174,2881730.528285009,8510872.799001848,EPSG:3857&outputFormat=json) is loaded, and they're displayed on the map. Save the file and load it into your browser.
3. _Compare_ the two files provided, and note how they do not differ in any other way except the URI where GeoJSON is being loaded.
4. _Observe and verify_, by examining raw GeoJSON data loaded in both cases, that in both GeoJSON data sets _some_ shapes land within coordinates where map is centered when examples are loaded.

Note that the two GeoJSON data sets are _not_ the same data and they do _not_ contain the same shapes, though they do contain some shapes which land on the same geographical area. These specific data sets are chosen for illustration purposes because they're freely available.

### Expected behavior

Valid GeoJSON data with MultiPolygons in it produces shapes on the map just like valid GeoJSON data with Polygons does.

### Current behavior

Valid GeoJSON data with MultiPolygons in it produces no visible shapes on the map, albeit valid GeoJSON data with Polygons does.

### Minimal example reproducing the issue

Examples are attached into this issue.

### Environment

- Leaflet version: 1.9.4
- Browser (with version): Firefox 117.0, Safari 16.6 (18615.3.12.11.2)
- OS/Platform (with version): MacOS 13.5.1

**Comment by IvanSanchez** [comment]
The "broken" example loads non-compliant GeoJSON. The (latest) GeoJSON spec forces data to be in EPSG:4326 (i.e. "longitude-latitude"), whereas your example seems to be loading some UTM CRS.

In other words: The GeoJSON data is invalid and it's the WFS server's fault.
