### ISSUE TITLE
I would like support for setting up interactive maps on GitHub using Leaflet

### ISSUE THREAD

**Issue by warrenwoodhouse** [Leaflet/Leaflet#9090]
Hi Leaflet Development Team,

My name is Warren Woodhouse. My wiki from Fandom has been moved to GitHub. I would like to continue using Leaflet as it was already integrated into Fandom. I would like to use your mapping tool for creating interactive maps and placing them on my GitHub repository called Maps. Please can you give me some advice on setting it up so that it works correctly? I would greatly appreciate any support on this.

I look forward to reading your reply soon. I also look forward to seeing your continuation of a great tool and service.

Regards,

Warren Woodhouse

**Comment by nfreear** [comment]
Hi Warren,

Thanks for getting in touch.

Based on the [Leaflet quick-start guide](https://leafletjs.com/examples/quick-start/), I've created a [starter.html](https://gist.github.com/nfreear/acd036674d7ec82043f0c8593bfe52eb) example HTML page.

1. Copy `starter.html` into the [index.html in your repository](https://github.com/warrenwoodhouse/maps/blob/main/index.html).
2. Take a look at [GitHub Pages](https://pages.github.com/).
3. Visit your repository's `Settings` then → `Pages`.
4. Have a go at publishing your repository on Pages, using `Deploy from a branch`, with a branch of: `main`.

Are you able to post the `URL` of your old fandom site (even if it's no longer live)?

Let us know how you get on!

Yours,

Nick

**Comment by warrenwoodhouse** [comment]
Hi Nick,

Cheers. I’ll take a look at the starter page you’ve set up for me.

My fandom url seems to still be active but I’m unable to access the admin
dashboard nor am I able to edit my fandom site at all. I have requested
WikiTeam on GitHub to archive my entire wiki for me including images,
videos, pages, etc. into a massive archived zip folder for easy
installation, that’s already done and is on The Internet Archive ready for
installation on my GitHub. First off, set up interactive maps using
LeafletJS as that’s the same tool that was used on the fandom wiki, then
integrate my maps afterwards, that’s my plan. After that, I’ll transfer my
wiki to GitHub. I’ve set up pages using GitHub before, took a few minutes
to figure it out, wasn’t to difficult.
https://warrenwoodhouse.github.io/codes/colourchart , that colour chart is
one I’m currently transferring from my original colour chart that I’ve set
up on my old website before I imported it to fandom. My old fandom link is
https://warrenwoodhouse.fandom.com/wiki/Warren_Woodhouse_Wiki

I’ll definitely let you know how I get on once the starter page has been
set up and stuff. I might do it on the weekend.

Thanks again mate.

Humble Regards,

Warren

P.s.
I’ve decided to move my content from fandom to GitHub and I’ve decided to
move my blog from fandom to Tumblr, my Tumblr blog is at
https://warrenwoodhouse.tumblr.com/

**Comment by Falke-Design** [comment]
Hi,
issues are for bugs or feature requests of Leaflet core, so please ask the next time for support and help on Stackoverflow. 
This is the reason why I close this issue. But feel free to continue writting here with @nfreear in the closed issue.
