### ISSUE TITLE
Update Twitter logo and name

### ISSUE THREAD

**Issue by WebSnke** [Leaflet/Leaflet#9096]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Expected behavior

The Twitter logo and name should be updated.

### Current behavior

The website still uses the old logo and name.

### Environment

- Browser (with version): Firefox 116
- OS/Platform (with version): Fedora 38

**Comment by Utkarsh3128** [comment]
Can you tell me how to run the source code on local machine?

**Comment by WebSnke** [comment]
> Can you tell me how to run the source code on local machine?

Sure. You probably want to see the changes you made in your browser, right? Do you use VS Code or something else?

**Comment by Utkarsh3128** [comment]
Yes sir, that's the reason I asked. I use VS Code =.

**Comment by WebSnke** [comment]
> Yes sir, that's the reason I asked. I use VS Code.

Ok. I suggest that you install Live Server. It's a VS Code extension that allows you to start a local server to view your website with just one click.

Live Server:

![image](https://github.com/Leaflet/Leaflet/assets/94064167/f9db4e78-895a-4e56-ab2e-4e42a46b7a0d)


Once you installed the extension, just go back to your project and click on the 'Go Live' button in the info bar of VS Code.

![image](https://github.com/Leaflet/Leaflet/assets/94064167/75741817-ef46-4a47-8a5e-7fde18fc6c3e)

**Comment by ShambhavII-Singh** [comment]
Hi can you assign this issue to me? I would like to work on this.

**Comment by aialok** [comment]
Hey ! I have done the pull request with proper code and screenshot do merge it.

**Comment by love-sonkar** [comment]
hello can someone help me to run this project localy im using vs Code and i have install the live server but when i start live server i got this file .
![localhost](https://github.com/Leaflet/Leaflet/assets/82786865/38f54a25-8f87-4c5b-8fdf-df907a2d1364)

**Comment by aialok** [comment]
It wil not work with live server you need to install all the dependencies. Read contributing[dot]md. you will get there how to setup locally

**Comment by love-sonkar** [comment]
okay bro let me check

**Comment by PSS2134** [comment]
Hey can you assign me this?

**Comment by aialok** [comment]
Already this got resolved.

**Comment by love-sonkar** [comment]
okay but how do you setup this project locally because I'm not able to setup can you help me how i can setup this project locally i have installed all dependency but not able to run this project
