### ISSUE TITLE
scroll-up button

### ISSUE THREAD

**Issue by abrehan2** [Leaflet/Leaflet#9108]
### Checklist

- [X] I've searched through the [plugins](https://leafletjs.com/plugins.html) to make sure this feature isn't already available, or think it shouldn't require a plugin.
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this feature hasn't been requested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Motivation

While I was going through the website, I realized there might be a need for a scroll0-up button on the overview, tutorials, download, and blog pages

### Suggested solution

I will add a green scroll-up button on these pages which will help to enhance the user experience by 3%

**Comment by Kota-Karthik** [comment]
Hello @abrehan2  @michael  @kshepard  @palewire  @grossbart 
I am interested in solving this issue 
so kindly assign me this 
Thank You : )

**Comment by PSS2134** [comment]
Can you assign me this?

**Comment by S4JN** [comment]
working on it

**Comment by abrehan2** [comment]
You can't work on an issue until it is accepted.

**Comment by Falke-Design** [comment]
Everyone can work on it. The best PR will be merged.

A few must-haves:
- Working on mobile and desktop
- Always visible on the screen and not only in the bottom
- No library
- Additional: Only visible if scrolling up and hidden while scrolling down

**Comment by saikrishna7004** [comment]
Can I work on this issue under the Hacktoberfest 2023?
