### ISSUE TITLE
Update outdated logos on website

### ISSUE THREAD

**Issue by WebSnke** [Leaflet/Leaflet#9128]
### Checklist

- [X] I've searched through the [plugins](https://leafletjs.com/plugins.html) to make sure this feature isn't already available, or think it shouldn't require a plugin.
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this feature hasn't been requested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Motivation

Many of the logos in logos.png are outdated.

Screenshot:
![image](https://github.com/Leaflet/Leaflet/assets/94064167/426c4887-22d7-4a97-87c2-db24cbcae92f)

### Suggested solution

I suggest that we update them to make the website feel modern and up-to-date.

**Comment by UmerrAli** [comment]
I want to work on this issue.

**Comment by WebSnke** [comment]
> @WebSnke all the logos are looking up-to-date to me, can you please specify which one is outdated

Foursqaure, Facebook, Pinterest, Evernote, 500px and USA TODAY have new logos now.

**Comment by harshitkandpal** [comment]
@WebSnke  can i work on it ?

**Comment by WebSnke** [comment]
> @WebSnke can i work on it ?

Sure. No need to ask me for permission.
