### ISSUE TITLE
link in readme redirects to this domain is for sale site

### ISSUE THREAD

**Issue by umikali222** [Leaflet/Leaflet#9139]
the link at the start of the readme saying "in Poland" redirects to a this domain is for sale site.

**Comment by ARJ2160** [comment]
Should it redirect to the same site as it does in "in Romania" ?

**Comment by IvanSanchez** [comment]
Closed by https://github.com/Leaflet/Leaflet/commit/98180b120ad8e2cbcd896e5137222428893552b8
