### ISSUE TITLE
You are wrong 

### ISSUE THREAD

**Issue by Jay12456jj** [Leaflet/Leaflet#9140]
### Checklist

- [ ] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Why is my location showing in Poland on leafy maps. Seems I'm unable to update. I live in Atlanta, Ga. How do I  correct this issue? Maybe this is why I'm not receiving incoming text messages to my device. Please help my fix

### Expected behavior

Allow my map to show in right location. Stop moving my IP address all over the world. I'm in Atlanta Ga. I use TMobile towers with my carrier assurance wireless 

### Current behavior

No text messages or calls coming to my device. Other than spam medicare calls. What must I do to get decent service 
![Screenshot_20231021-145617](https://github.com/Leaflet/Leaflet/assets/148600497/51d968bc-7553-4a67-b148-971d0e24f880)

### Environment

- Leaflet version: 
- Browser (with version): 
- OS/Platform (with version):

**Comment by jonkoops** [comment]
Closing this as Leaflet is not responsible for determining locations, that is [handled by the browser](https://github.com/Leaflet/Leaflet/blob/3db042fcef041c269d489c3bf3e766df4a8771c5/src/map/Map.js#L645). Also, not sure what 'leafy maps' is, but if you are referring to [this plugin](https://bubble.io/plugin/leafy-maps-1562697922620x934462587697889300), we are not affiliated with that product.
