### ISSUE TITLE
Previously Appended HTML Event Listener in Layer Control is Overwritten When More Overlays Added

### ISSUE THREAD

**Issue by bethanywallace** [Leaflet/Leaflet#9149]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. Create the Layer Control object
2. Add baselayers
3. Create marker group overlay layer
4. Add it to the Layer Control with custom HTML e.g.
 `layerControl.addOverlay(layer, "<button id='"+buttonID+"'>Go To "+name+"</button> "+name);)`
6. Add a click event to the button e.g.
```
let button = document.getElementById(buttonID);
 L.DomEvent.on(button, 'click', function () {
		map.fitBounds(layer.getBounds()); // Assuming eventMarkerGroup has a getBounds method
	});
```
8. Label and button gets added correctly to layer control, works as expected
9. Make another overlay layer
10. Add it to the Layer Control as above
11. Removes the onClick event that was previously appended to the button from the previous layer

### Expected behavior

Each time an overlay is added, its button should be added next to the label and the button should work as expected.

### Current behavior

The first layer button is added, and then its functionality is removed when further layers are added, however the button itself stays. The end result is that none of the buttons onClick event work. When I just isolate the code to add one layer, it works as expected. 

### Minimal example reproducing the issue

https://plnkr.co/edit/MT9gbfKiOuz1U6Yq

### Environment

- Leaflet version: 1.7.1
- Browser (with version): Chrome 118.0.0.0
- OS/Platform (with version): Windows 11 Laptop

**Comment by HimanshuMahto** [comment]
const map = L.map('map', {
    preferCanvas: true
}).setView([0, 0], 1);

const osm = L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
    maxZoom: 24,
    maxNativeZoom: 19,
    attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
}).addTo(map);

const baseLayers = {
    'OpenStreetMap': osm
};

const layerControl = new L.Control.Layers(baseLayers).addTo(map);

function createLayerControlWithButton(layer, name) {
    let buttonID = name.replace(/\s/g, '') + 'Button';
    const buttonHTML = "<button id='" + buttonID + "'>Go To " + name + "</button> " + name;

    layerControl.addOverlay(layer, buttonHTML);

    // Add a click event to the button
    let button = document.getElementById(buttonID);
    L.DomEvent.on(button, 'click', function () {
        map.fitBounds(layer.getBounds());
    });
}

let markerGroupA = L.featureGroup();
let latLng1 = L.latLng(0, 0);
let marker1 = L.marker(latLng1);
let latLng2 = L.latLng(10, 100);
let marker2 = L.marker(latLng2);
marker1.addTo(map);
markerGroupA.addLayer(marker1);
marker2.addTo(map);
markerGroupA.addLayer(marker2);
createLayerControlWithButton(markerGroupA, 'Marker Group A');

let markerGroupB = L.featureGroup();
let latLng3 = L.latLng(0, -100);
let marker3 = L.marker(latLng3);
let latLng4 = L.latLng(-10, -100);
let marker4 = L.marker(latLng4);
marker3.addTo(map);
markerGroupB.addLayer(marker3);
marker4.addTo(map);
markerGroupB.addLayer(marker4);
createLayerControlWithButton(markerGroupB, 'Marker Group B');


I made this using the example  given is it ok

**Comment by bethanywallace** [comment]
> const map = L.map('map', { preferCanvas: true }).setView([0, 0], 1);
> 
> const osm = L.tileLayer('[https://tile.openstreetmap.org/{z}/{x}/{y}.png](https://tile.openstreetmap.org/%7Bz%7D/%7Bx%7D/%7By%7D.png)', { maxZoom: 24, maxNativeZoom: 19, attribution: '© [OpenStreetMap](http://www.openstreetmap.org/copyright)' }).addTo(map);
> 
> const baseLayers = { 'OpenStreetMap': osm };
> 
> const layerControl = new L.Control.Layers(baseLayers).addTo(map);
> 
> function createLayerControlWithButton(layer, name) { let buttonID = name.replace(/\s/g, '') + 'Button'; const buttonHTML = "Go To " + name + " " + name;
> 
> ```
> layerControl.addOverlay(layer, buttonHTML);
> 
> // Add a click event to the button
> let button = document.getElementById(buttonID);
> L.DomEvent.on(button, 'click', function () {
>     map.fitBounds(layer.getBounds());
> });
> ```
> 
> }
> 
> let markerGroupA = L.featureGroup(); let latLng1 = L.latLng(0, 0); let marker1 = L.marker(latLng1); let latLng2 = L.latLng(10, 100); let marker2 = L.marker(latLng2); marker1.addTo(map); markerGroupA.addLayer(marker1); marker2.addTo(map); markerGroupA.addLayer(marker2); createLayerControlWithButton(markerGroupA, 'Marker Group A');
> 
> let markerGroupB = L.featureGroup(); let latLng3 = L.latLng(0, -100); let marker3 = L.marker(latLng3); let latLng4 = L.latLng(-10, -100); let marker4 = L.marker(latLng4); marker3.addTo(map); markerGroupB.addLayer(marker3); marker4.addTo(map); markerGroupB.addLayer(marker4); createLayerControlWithButton(markerGroupB, 'Marker Group B');
> 
> I made this using the example given is it ok

Hey, the issue of the first button's functionality being removed is unfortunately still there

**Comment by bethanywallace** [comment]
Okay, this is due to the features for the layers still being added when the layer is added to the control I think. I have worked around it by not adding the event listeners until all layer functions have finished and their label with the button has been added to the control. Then I loop through the label buttons and add their onClick events. Unsure if this should now be closed or not, as the problem still remains that existing event listeners are affected when new overlays are added to the control.

**Comment by bethanywallace** [comment]
Furthermore, when I try to create an event which affects the control panel itself (such as toggling the layer), it seems to wipe all of the JavaScript I made which is linked to the control panel. 

An example:

```
buttonsOnControlPanel.foreach(buttonElement => {
	let button = document.getElementById(buttonElement.id);
	L.DomEvent.on(button, 'click', function () {
		if(!map.hasLayer(layer)){
			map.addLayer(layer); 
		}
		map.fitBounds(layer.getBounds());
	});
});
```

Current behaviour: When a button on the control panel is clicked, it zooms and toggles the layer on as it should, but then no events are triggered for that same button or any other buttons on the control panel from this point. The event listeners are also removed when inspecting dev tools.

Expected behaviour: When a button on the control panel is clicked, it zooms and toggles the layer on as it should. If the same button is clicked it should repeat this behaviour. If another button is clicked for a different layer it should repeat this behaviour for that layer.

An example of the buttons: 
![image](https://github.com/Leaflet/Leaflet/assets/34375680/fc05a416-e799-4e5e-b939-ff6d005756fa)

**Comment by Falke-Design** [comment]
It is not possible what you want to achieve. The problem is, that the inner html of the control will be cleaned and re-created when layers are added or removed.

But you can add a "global" listener on the control container and then check if the id of the clicked target is the id of the button:
```
layerControl.getContainer().addEventListener('click', (e)=>{
	if(e.target.id === buttonID){
		console.log('run Button code');
	}
})
```
