### ISSUE TITLE
Paste open street map node link and then display the location as well info and directions to the left-hand side

### ISSUE THREAD

**Issue by Goldmaster** [Leaflet/Leaflet#9151]
### Checklist

- [X] I've searched through the [plugins](https://leafletjs.com/plugins.html) to make sure this feature isn't already available, or think it shouldn't require a plugin.
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this feature hasn't been requested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Motivation

I want to be able to paste in an open street node link and simply embed the map on a website. However, there are times when the information or even location gets updated, so using coordinates may not be enough

### Suggested solution

Some ability via JavaScript plugin (I am happy to develop this as a plugin) that allows a user to paste an OpenStreetMap node link and leaflet will be able to load the up information from the node.

### Alternatives considered

Embedding a Google Maps place is an option, as the data is updated automatically. But the problem is the server load may be higher and risk of API access.

**Comment by jonkoops** [comment]
This is not a feature that we want to implement in Leaflet core, and seem very application specific so likely belongs in a plugin. Feel free to create a plugin for this use-case and submit a PR to add this to our plugins page.

**Comment by Goldmaster** [comment]
not a problem. I will work on creating a plugin when I have the chance. it is quite easy to do with some javascript
