### ISSUE TITLE
Assign the same map to 2 (or more) different divs

### ISSUE THREAD

**Issue by Arpapiemonte** [Leaflet/Leaflet#9169]
### Checklist

- [X] I've searched through the [plugins](https://leafletjs.com/plugins.html) to make sure this feature isn't already available, or think it shouldn't require a plugin.
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this feature hasn't been requested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Motivation

I'm creating an app with ionic Angular for smartphone with different tabs and i want to recall the same map in different tabs.
I trying with the "standard" map creation code:
```js
var map = L.map('div_id');
```
But I have to create two different maps into 2 different divs.
I also tried with: https://github.com/bluehalo/ngx-leaflet , calling the same component in different tabs, but in any case each tab has the own initialization of the component, and I have to manage more than one map.

### Suggested solution

I would have the possibility to create a map without declaring a div, and then to assign this single map to different div, something like this:
```js
var map = L.map()
map.render('div1')
map.render('div2')
```

**Comment by jonkoops** [comment]
This is not something we want to add due to the complexity of implementing such a feature, vs. the benefits that it would bring to only a niche subset of users. If you have to render two maps you'll have to create two `Map` instances and keep them in sync. You could perhaps create a plugin to do this for you.

**Comment by IvanSanchez** [comment]
There's already https://github.com/jieter/Leaflet.Sync , BTW.

**Comment by Arpapiemonte** [comment]
Thanks guys for the answers and the plugin, we didn't know it.
We'll try it.
