### ISSUE TITLE
Map broken

### ISSUE THREAD

**Issue by dmtzs** [Leaflet/Leaflet#9177]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Im following the documentation and still the map shows broken, the steps to reproduce is the same documentation just using flask.
Also navigator issues are discarded cause using folium of python the map is renderer correctly.

Sorry if im doing something wrong im new on this so hopefully i create the issue correctly

### Expected behavior

See the complete map with the expected dimensions

### Current behavior

The current behavior is a map broken that doesnt render as expected
<img width="1017" alt="image" src="https://github.com/Leaflet/Leaflet/assets/45855697/ce790665-557c-4160-9c8d-e646a8ea2771">

### Environment

- Leaflet version: 1.9.4
- Browser (with version): Microsoft Edge 119.0.2151.72 
- OS/Platform (with version): Windows 11

**Comment by IvanSanchez** [comment]
https://leafletjs.com/reference.html#map-invalidatesize
