### ISSUE TITLE
Add L.Icon as a property of L.CircleMarker

### ISSUE THREAD

**Issue by lmocsi** [Leaflet/Leaflet#9178]
### Checklist

- [X] I've searched through the [plugins](https://leafletjs.com/plugins.html) to make sure this feature isn't already available, or think it shouldn't require a plugin.
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this feature hasn't been requested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Motivation

I'm always frustrated, when I'd like to display an object on a map, and:
1. I'd like to add an image to it (L.Icon supports this)
2. I'd like to dynamically change its border-color from javascript (L.CircleMarker supports this)

However, both cannot be done right now:
1. With L.Icon, you can only specify its border-color via css, so not dynamically from javascript.
2. L.CircleMarker does not have an icon property.

### Suggested solution

L.CircleMarker should have an icon property.

### Alternatives considered

Either stick to dynamic coloration of the border, or use image within.

**Comment by IvanSanchez** [comment]
Cannot do - a `L.CircleMarker` is a `L.Path`, drawn into either a `L.Canvas` or a `L.SVG`, whereas a `L.Icon` implies a `HTMLImageElement`. It's not possible to mix those.

> With L.Icon, you can only specify its border-color via css, so not dynamically from javascript.

`marker.getElement().style.borderColor = "red";`
