### ISSUE TITLE
Docstrings needed for L.Marker.getElement

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#9179]
### Checklist

- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this change hasn't been suggested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Which documents need updating?

reference.html

### Motivation

I was looking at #9178, and had to look at the JS code to see how to get a reference to the `HTMLElement` of a `L.Marker`.

### Suggested changes

The `getElement()` method of `L.Marker` needs docstrings.

The docstrings for the `getElement()` method of `L.ImageOverlay` can serve as a starting point.

**Comment by hollowM1ke** [comment]
Hello. Can I still contribute to this issue?
