### ISSUE TITLE
layerGroup does not add a "wrapping" element

### ISSUE THREAD

**Issue by Pomax** [Leaflet/Leaflet#9193]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

```js
const map = L.map('map').setView([0, 0], 13);

L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
    maxZoom: 19,
    attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
}).addTo(map);

for (let i=0; i<2; i++) {
	const group = L.layerGroup();
  group.addTo(map);
	L.circle([0, i/100], {radius: 200}).addTo(group);
}
```

This will create two groups, each with a marker in it. Except it doesn't: it _actually_ sets up the following document fragment:

```html
<div class="leaflet-pane leaflet-overlay-pane">
  <svg pointer-events="none" class="leaflet-zoom-animated" width="480" height="240" style="transform: translate3d(-40px, -20px, 0px)" viewBox="-40 -20 480 240">
    <g>
      <path class="leaflet-interactive" ... d="M190,100a10,10 0 1,0 20,0 a10,10 0 1,0 -20,0 "></path>
      <path class="leaflet-interactive" ... d="M248.2542222221382,100a10,10 0 1,0 20,0 a10,10 0 1,0 -20,0 "></path>
    </g>
  </svg>
</div>
```

So the layers that _should_ have been grouped, are only grouped "virtually". They aren't grouped on the page at all, making it impossible to properly control z-indexing, CSS animations (e.g. fading or filtering the entire group), etc.

### Expected behavior

The document fragment should have been:

```html
<div class="leaflet-pane leaflet-overlay-pane">
  <svg pointer-events="none" class="leaflet-zoom-animated" width="480" height="240" style="transform: translate3d(-40px, -20px, 0px)" viewBox="-40 -20 480 240">
    <g id="layerGroup1" class="">
      <path class="leaflet-interactive" ... d="M190,100a10,10 0 1,0 20,0 a10,10 0 1,0 -20,0 "></path>
    </g>
    <g id="layerGroup2" class="">
      <path class="leaflet-interactive" ... d="M248.2542222221382,100a10,10 0 1,0 20,0 a10,10 0 1,0 -20,0 "></path>
    </g>
  </svg>
</div>
```

With a class that can be set using `group.addClass`, or specified via the options object.

Or, alternatively, as actual full panes:

```html
<div class="leaflet-pane leaflet-overlay-pane">...</div>
<div class="leafet-pane leaflet-overlay-pane leaflet-layer-group" id="layerGroup1">
  <svg pointer-events="none" class="leaflet-zoom-animated" width="480" height="240" style="transform: translate3d(-40px, -20px, 0px)" viewBox="-40 -20 480 240">
    <g>
      <path class="leaflet-interactive" ... d="M190,100a10,10 0 1,0 20,0 a10,10 0 1,0 -20,0 "></path>
    </g>
  </svg>
</div>
<div class="leafet-pane leaflet-overlay-pane leaflet-layer-group" id="layerGroup2">
  <svg pointer-events="none" class="leaflet-zoom-animated" width="480" height="240" style="transform: translate3d(-40px, -20px, 0px)" viewBox="-40 -20 480 240">
    <g>
      <path class="leaflet-interactive" ... d="M248.2542222221382,100a10,10 0 1,0 20,0 a10,10 0 1,0 -20,0 "></path>
    </g>
  </svg>
</div>
```

### Current behavior

see above

### Minimal example reproducing the issue

https://jsfiddle.net/r4ba76oe/

### Environment

- Leaflet version: 1.9.4
- Browser (with version): n/a
- OS/Platform (with version):  n/a

**Comment by Falke-Design** [comment]
@Pomax thank you for creating this issue.

If you want to seperate the layers in the DOM you can use [panes](https://leafletjs.com/reference.html#map-pane). But the LayerGroups are working like designed.

**Comment by Pomax** [comment]
I see, thank you. It would probably be worth adding that to the "explanation" paragraph on https://leafletjs.com/reference.html#layergroup so that folks know that what they think of as "layers" is different in Leaflet, with that link to get them on the right track.
