### ISSUE TITLE
DivOverlay giving "Cannot read properties of undefined (reading 'style')"

### ISSUE THREAD

**Issue by ParikshitGalaxeye** [Leaflet/Leaflet#9206]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [ ] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Parent Component
`<MapContainer
      center={[10.858635, 76.897929]}
      zoom={10}
      scrollWheelZoom={true}
      zoomControl={false}
      style={{ height: '100%', width: '100%' }}
  >
      <Testing />
       <TileLayer
            attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
            url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
        />
 </MapContainer>`

Child Component
`import React, { useEffect } from 'react'
import L from "leaflet";
import { createDivOverlayHook } from "@react-leaflet/core";
import { useMap } from 'react-leaflet';

function Testing() {
    const map = useMap();
    const LeafletDivOverlay = createDivOverlayHook((props)=>new L.DivOverlay(props), (element, context, props, setOpen)=>console.log(element, context, props, setOpen))
    LeafletDivOverlay(new L.LatLng(10.858635, 76.897929), {
        content:"<h1 style=\"color:red;padding:100px\">Hello</h1>"
    })
    useEffect(() => {
        const velocityLayer = new L.DivOverlay(new L.LatLng(39.202911,-94.602887), {
            content: "<h1>Hello</h1>",
            
        })
        console.log(velocityLayer)
        map.addLayer(velocityLayer);
    }, [])

    return (
        <>
            {/* <LeafletDivOverlay>
            <h1>Hello</h1>
            </LeafletDivOverlay> */}
        </>
    )
}

export default Testing`

### Expected behavior

 A 'div' is placed on leaflet maps, that particular div should be stitched properly on the bounds passed to it as ImageOverlay does.

### Current behavior

 A 'div' is placed on leaflet maps, Whenever the map is zoomed in or zoomed out, the div is not adjusting properly as <ImageOverlay/> does under the same situation. So the divOverlay is not working becuase of  "Cannot read properties of undefined (reading 'style')" issue.

### Environment

- Leaflet version: 1.9.3
- Browser (with version): Chrome(120.0.6099.130)
- OS/Platform (with version): Windows(11)

**Comment by jonkoops** [comment]
There is not enough information here to reproduce this issue. Please create a minimal reproducible example with as little code as possible and only vanilla Leaflet (e.g. no React code), and open up a new issue if the problem persists.
