### ISSUE TITLE
panTo() does not center map at requested coordinate

### ISSUE THREAD

**Issue by broofa** [Leaflet/Leaflet#922]
Let's try to center and zoom a map on the greenwich observatory ...
- Go to a leaflet map (e.g. the one on http://leaflet.cloudmade.com/)
- `map.setZoom(0); map.panTo(0,0);` (start at a known coord/zoom level)
- `map.panTo([51.4768, 0.0006])` to center map at greenwich observatory (in theory)
- `map.setZoom(16)` to zoom in
- Notice the map is nowhere near the observatory.  In fact, we're ~10 miles north of it

This is confirmed by `map.getCenter().toString()` => `LatLng(51.61802, 0)`

**Comment by miguelcobain** [comment]
Sorry, for commenting here, but this seems like a very accurate description of what I'm seeing.

I've made this jsbin: https://jsbin.com/putezoyido/edit?js,console,output

When you click "Go to new location" we call
```js
map.panTo([41.142937, -8.534538]);
```

however, `moveend` is triggered and if we check the map's center there we get
```
41.14293584388727
-8.534536957740785
```

Is this something expected or a bug?

**Comment by chrillewoodz** [comment]
So what's the solution? :S I'm trying to pan but it pans me nowhere near the coordinates I'm giving it.. Been trying to find a solution for the last hour but none of them works. Why can't the panTo just work like it's supposed to?

**Comment by bashirpour** [comment]
Use this way :

    map.project([lat, lng], Zoom);

https://stackoverflow.com/questions/48450191/have-leaflet-panto-not-center/53410229#53410229
