### ISSUE TITLE
using rate-limited WMS sources

### ISSUE THREAD

**Issue by staterconsulting** [Leaflet/Leaflet#9223]
### Checklist

- [X] I've searched through the [plugins](https://leafletjs.com/plugins.html) to make sure this feature isn't already available, or think it shouldn't require a plugin.
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this feature hasn't been requested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Motivation

I'm hitting a problem requesting tiles from a source that is throttled to 10 requests per second. I'm getting 429 responses after the first ten tiles - is there any way to limit the request rate for either WMS or tiles in general?

### Suggested solution

Would be really useful to be able to pass in a parameter to the tile layer that defines max requests/s

**Comment by IvanSanchez** [comment]
10 requests, you say? Sounds like Leaflet is behaving properly. I'd be worried if the requests would be measured in the hundreds or in the thousands.

Consider contacting the provider of the WMS, or using something like MapProxy.

**Comment by staterconsulting** [comment]
Hi, the provider is a government source and the rate limit is 10 per second.

I'm not sure why this comment has been closed - it wasn't a bug report, it was a question as to whether there was an ability to pass a limit into leaflet.

Is there the ability to do that?

**Comment by IvanSanchez** [comment]
> Hi, the provider is a government source and the rate limit is 10 per second.

So? Ask them about the rate limit! Add a caching layer! Get a copy of the data and set up your own WMS!

> I'm not sure why this issue has been closed - it wasn't a bug report

If the URL for it contains "issues", then it's meant to be a bug report.

> it was a question as to whether there was an ability to pass a limit into leaflet.
> 
> Is there the ability to do that?

No there isn't, and it's not the right solution to the problem. Limiting requests for one specific client doesn't guarantee that rate limits won't be hit anyway. Change the framing of the problem.

**Comment by staterconsulting** [comment]
> > Hi, the provider is a government source and the rate limit is 10 per second.
> 
> So? Ask them about the rate limit! Add a caching layer! Get a copy of the data and set up your own WMS!
> 
> > I'm not sure why this issue has been closed - it wasn't a bug report
> 
> If the URL for it contains "issues", then it's meant to be a bug report.
> 
> > it was a question as to whether there was an ability to pass a limit into leaflet.
> > 
> > Is there the ability to do that?
> 
> No there isn't, and it's not the right solution to the problem. Limiting requests for one specific client doesn't guarantee that rate limits won't be hit anyway. Change the framing of the problem.

Wow.

I love leaflet, and I clicked a link to request features, as it seemed like the right place to ask about....features.

Get a copy of the data and set up my own WMS? Really? That's the kind of reply you make to a genuine query?

What an incredibly unhelpful, unwelcoming and arrogant response. Wish I'd not asked.

**Comment by IvanSanchez** [comment]
> Get a copy of the data and set up my own WMS? Really? That's the kind of reply you make to a genuine query?

Yes, that's the kind of answer I give.

I mean, please do feel free to set up a caching layer, or go crazy with Service Workers to intercept requests and delay them. Or go crazy with https://github.com/ismyrnow/Leaflet.functionaltilelayer and a timed request pool with automatic delayed retries in case of `429`s.

What you may not be realizing is that trying to work around rate limits is an arms race. Sooner or later you'll hit a new rate limit, an IP ban, or something of the like.

Ask the gov't agency in charge. I mean it. There's a reason they set up rate limits, and they're the ones that can let you access the data avoiding WMS altogether.

**Comment by ulzha** [comment]
Rate limits (429 status) are retryable errors in most client-server setups worth their salt. They aren't designed to be shrugged off by client implementors as fatal errors. They're designed to gracefully allow client implementation to retrieve the full set of data, just spread over longer time span.
