### ISSUE TITLE
fitBounds() fails when instantiated from within hidden layer

### ISSUE THREAD

**Issue by quantegy** [Leaflet/Leaflet#926]
http://pastie.org/4557134

The map will not fully load, tile images show up pixellated, and map will not zoom in or out. Apparently, according to other Leaflet devs, this appears to be an issue with a layer containing the map layer being hidden during the fitBounds() call.

**Comment by aaani** [comment]
I ran into the same issue today. I tried to use the workaround suggested by @Komzpa, but didn't work because `map.getBoundsZoom(bounds)` is always returning 3, so even though the map is centered at the right coordinates, it zoomed out too far away.
@mourner any official workaround from leaflet?

**Comment by IvanSanchez** [comment]
@aaani Please don't reopen 3-year-old bugs. Open a new one **with** a minimal reproducible test case **if** it is a Leaflet bug.
