### ISSUE TITLE
Packaged CSS is not what is shown in repository

### ISSUE THREAD

**Issue by jovermier** [Leaflet/Leaflet#9260]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Compare `dist/leaflet.css` in the npm repository to the source code `dist/leaflet.css` and notice they are different. Updates being made to the CSS are not making it to the published release.

It appears dist/leaflet.css current version is no longer being bundled and instead an older version is being used. I diffed the dist/leaflet.css file changes until I found similar contents. The issue happens between commits:
https://github.com/Leaflet/Leaflet/commit/0fa492c239e10ab21d688f7ea1afe9f6fefe6505 and https://github.com/Leaflet/Leaflet/commit/0fa492c239e10ab21d688f7ea1afe9f6fefe6505

What is weird is there is never a commit that has an exact match of the contents of the dist/leaflet.css file contained in the npm bundle.

### Expected behavior

na

### Current behavior

na

### Environment

- Leaflet version: 1.9.4
- Browser (with version): na
- OS/Platform (with version): na

**Comment by mourner** [comment]
It's not a bug — the `main` branch tracks an unrelease major version of Leaflet, v2. If you're looking for source code of the released versions, see the `v1` branch https://github.com/Leaflet/Leaflet/tree/v1
