### ISSUE TITLE
role="auto" unnecessarily added to images.

### ISSUE THREAD

**Issue by DennisSuitters** [Leaflet/Leaflet#9267]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

When running page speed insights, the following is reported as an accessibility error on the role attribute being set to auto:

`<img src="[URL]" class="leaflet-marker-icon leaflet-zoom-animated leaflet-interactive" alt="Marker" tabindex="0" role="auto" style="margin-left: -12px; margin-top: -41px; width: 25px; height: 41px;">`

The role attribute is not required in this instance, as the image is not masquerading as another element, making role redundant.

### Expected behavior

That the generated markup via the script isn't unnecessarily adding attributes.

### Current behavior

The role attribute does not need to be added to images, as `role="image"` or `role="auto"`. The only time a role attribute is required is to tell the browser that the current element is a particular function, or if the current element is masquerading as another element, for e.g. a link being a button.

### Environment

- Leaflet version: 1.9
- Browser (with version): Chrome (latest), but irrelevant in this case.
- OS/Platform (with version): Linux

**Comment by Falke-Design** [comment]
@Malvoz some thoughts from you?

**Comment by Malvoz** [comment]
For markers we're only setting:

https://github.com/Leaflet/Leaflet/blob/80a42768306c8c2f9f1bd1eb48d529ffcac3072f/src/layer/marker/Marker.js#L238

See all instances of "role": https://github.com/search?q=repo%3ALeaflet%2FLeaflet%20role&type=code

@DiemenDesign `auto` is an invalid `role` value. Which URL did you analyze? Do you have a screenshot of the PageSpeed Insights results? Was a plugin in use?
