### ISSUE TITLE
Is Marker missing the data attribute in the typescript definition?

### ISSUE THREAD

**Issue by phil-hudson** [Leaflet/Leaflet#9289]
Is the marker class missing data prop as a type?

I've seen a few other people using it around, and it can be accessed, but doesn't have the associated type in the typescript definition.

Thanks

**Comment by IvanSanchez** [comment]
Typescript definitions are not kept in this repo.

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* NativeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.
