### ISSUE TITLE
'undefined' is not an object (evaluating 'e.addLayer')

### ISSUE THREAD

**Issue by erasmuss22** [Leaflet/Leaflet#929]
I am using a Leaflet map in an iPad web app. I do my debugging using Safari's Developer tools. My map doesn't seem to work very consistently. Sometimes it will load perfectly, and other times it won't and the Error Console will say "TypeError: 'undefined' is not an object (evaluating 'e.addLayer')" I just upgraded to Leaflet 0.4.4, but it is still an issue.

**Comment by sebastianthomas** [comment]
I got this in Safari because I was declaring `var map;` and Safari freaks out when you do that.
