### ISSUE TITLE
Cannot see cursors on Chromium Browsers

### ISSUE THREAD

**Issue by DQB061204** [Leaflet/Leaflet#9290]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. Open a Chromium Based Browser like Edge or Chrome.
2. Type any website that uses Leaflet like www.openstreetmep.org
3. Move your cursor on to the map
4. The cursor is disappear

### Expected behavior

There's a cursor on the map

### Current behavior

No cursor, but still can operate the map.

### Environment

- Leaflet version: The version that openstreetmap use
- Browser (with version): Microsoft Edge Version 124.0.2438.2 (Official build) stable app, dev channel (64-bit)
- OS/Platform (with version): Windows 11 Home 24H2 26063.1 Windows Feature Experience Pack 1000.26063.1.0

**Comment by IvanSanchez** [comment]
Can't reproduce.

Please try on a different computer and report back.

**Comment by DQB061204** [comment]
By the way, my computer got another problem that the system time is 1 hour earlier than the correct time. Which Microsoft officially announced it is a bug.
Here's the link: https://aka.ms/AAnpt06

**Comment by DQB061204** [comment]
> Can't reproduce.
> 
> Please try on a different computer and report back.

Hello, the bug is now disappeared, thank you for your helping on this. It is now confirmed by me is a system problem. the way to how to solve it is that to upgrade your system to the newest version if you are dev system users. For the system time error, just change your time manually to the time zone to the one that shows correct time and set the time zone automatically then sync with the Microsoft time server. As you read here, it means that you can close the issue now.
