### ISSUE TITLE
leafletjs.com welcome banner dead URLs

### ISSUE THREAD

**Issue by horseDeveloper** [Leaflet/Leaflet#9291]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

The first time you visit leafletjs.com (or just clear cookies and site data + refresh page).
The 2nd to last line reads: 
"It is chilling to see Leaflet being used for [documenting Russia’s war crimes](https://ukraine.bellingcat.com/), [factual reporting of the war](https://liveuamap.com/) and for coordination of humanitarian efforts [in Romania](https://refugees.ro/) and [in Poland](https://dopomoha.pl/). We commend these uses of Leaflet." 
The last two URLs are dead. 

### Expected behavior

- Remove the dead URLs?
- Separate the last 2 URLs and put them under "archived projects"?
- Put archive.org URLs?

### Current behavior

See above.

### Environment

- Leaflet version: 
- Browser (with version): Firefox 123.0.1 (64-bit)
- OS/Platform (with version): Windows 10

**Comment by Falke-Design** [comment]
Thank you for reporting.

@mourner do you have some other links that you want to add instead?

**Comment by mourner** [comment]
Maybe just replace "[in Romania](https://refugees.ro/) and [in Poland](https://dopomoha.pl/)" with "across Europe" without a link. We can add something back later. Not sure what happened to those two websites.

**Comment by Malvoz** [comment]
Fixed in https://github.com/Leaflet/Leaflet/pull/9305.
