### ISSUE TITLE
Backup/secondary tile server

### ISSUE THREAD

**Issue by thibaultmol** [Leaflet/Leaflet#9293]
### Checklist

- [X] I've searched through the [plugins](https://leafletjs.com/plugins.html) to make sure this feature isn't already available, or think it shouldn't require a plugin.
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this feature hasn't been requested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Motivation

It would be nice if you could specify a secondary url in case the primary tile server url doesn't work.

### Suggested solution

have another parameter in the embed code to specify a second tile server if the first tileserver fails

**Comment by IvanSanchez** [comment]
See https://github.com/ghybs/Leaflet.TileLayer.Fallback
