### ISSUE TITLE
Map attribution Flag Removal where not appropriate

### ISSUE THREAD

**Issue by dawesi** [Leaflet/Leaflet#9298]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Load attribution

### Expected behavior

Simple attribution, without political statement

### Current behavior

Subjective Political opinion applies itself to maps where political opinions are not allowed. (govt websites, etc)

### Environment

Latest version.

**Comment by dawesi** [comment]
Or is the only option to hack the code, or remove attibution?

**Comment by IvanSanchez** [comment]
See https://github.com/Leaflet/Leaflet/pull/8109#issuecomment-1086842633

**Comment by jonkoops** [comment]
We will not be removing this in support of Ukraine's defense against unjust Russian aggression. It is not a political opinion that Russians have invaded Ukraine, it is a fact. You can overwrite the attribution if you please.
