### ISSUE TITLE
Marker loads png from media instead of own image folder.

### ISSUE THREAD

**Issue by fudom** [Leaflet/Leaflet#9299]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Following is tested in Angular.

1. Install the package.

```
npm i leaflet
```

2. Import in styles.scss

```
import 'leaflet';
```

3. Load map in component.

```ts
import * as L from 'leaflet';
// ngAfterViewInit:
const coords = [0, 0];
const map = L.map('map');
map.setView(coords, 20);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(map);
L.marker(coords).addTo(map);
```

Run `ng serve`.

Result:

Marker is shown as broken image link.

```
GET http://localhost:4200/media/marker-icon-2x.png 404 (Not Found)
GET http://localhost:4200/media/marker-shadow.png 404 (Not Found)
```

The URLs in the css file are correct. Not sure where the media path comes from. 
Ok, the marker is an `img` element. So the css image url is not used. I wonder why img instead.

### Expected behavior

The images should be loaded from `images/` of the package.

### Current behavior

Trying to load the images from the root `media/`.

### Environment

- Leaflet version: 1.9.4
- Browser: Chrome 122
- OS/Platform: Win 10 22H2

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* NativeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.
