### ISSUE TITLE
import are not working 

### ISSUE THREAD

**Issue by xalteropsx** [Leaflet/Leaflet#9314]
import * from 'leaflet';
unknown: Unexpected token, expected "as" in localbrowser while in codesandbox another issue 

https://codesandbox.io/p/sandbox/modest-beaver-v23ptt?file=%2Fsrc%2Findex.js%3A2%2C1

**Comment by IvanSanchez** [comment]
[Works for me](https://plnkr.co/edit/6SMhGFVDxbbyxWnP).

If you've got problems to bundle Leaflet using rollup/webpack/parcel/whatever, that's *your* problem, not a Leaflet issue.

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* NativeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.
