### ISSUE TITLE
unpkg distribution currently gives http code 520

### ISSUE THREAD

**Issue by krilbe** [Leaflet/Leaflet#9320]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Try to load the Control.Geocoder.js from unpkg: https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.js
You get http 520.

### Expected behavior

Script should be loaded.

### Current behavior

http errro 520.

### Environment

- Leaflet version: Current distro at the given URL.
- Browser (with version): Doesn't matter, but tested with Edge and Firefox.
- OS/Platform (with version): Doesn't matter but we use Windows 11.

**Comment by tim-minshall** [comment]
I am also having the same problem. Thank you for raising the issue :)
