### ISSUE TITLE
Tile events are not being cleaned up

### ISSUE THREAD

**Issue by gerhardmeyer** [Leaflet/Leaflet#9324]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

I noticed when zoomin and out on the map the event listeners are growing quite quickly. It looks like the createTile function is creating events inside the TileLayer.js. I don't think these are cleaned up properly. 

To reproduce just look at the event listerners inside Chromes performance monitor while zooming in and out. The events keep climbing. 

### Expected behavior

Events should be cleaned up when calling map.off() or map.remove().

### Current behavior

"load" and "error" Events are leaking

### Environment

- Leaflet version:  latest
- Browser (with version): Chrome Version 123.0.6312.122
- OS/Platform (with version): Windows 11

**Comment by lmdc45** [comment]
Noticed the issue as well. While the delay is no problems on android or desktop, it seems to induce some crash/map reload on iOS to due maybe to more strict memory management
