### ISSUE TITLE
zoom level less than 3 hide the leaflet layer

### ISSUE THREAD

**Issue by bondythegreat** [Leaflet/Leaflet#9327]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. zoom out until the zoom value less than 3
2. the leaflet layer hidden.
3. zoom in again to 3 and more, leaflet showing

### Expected behavior

Im new in the game. I want to have map with graphical info and I try something like the 'from-to' flights. I use maptiler as the map.
just realised if it's zoomed out to zoom level less than 3 the leaflet graphical is gone.
i try to enforce with `setData(mapData)` again in the `map.addEventListener("moveend", {})` event, but the position is wrong.
https://leaflet-zoom-bug.netlify.app/
https://leaflet-zoom-bug-with-zoomend.netlify.app/

expected behaviour: 
the leaflet layer should be still showing at least in zoom level 1 or 2 

### Current behavior

when zoomed-out to the zoom level less that 3, leaflet layer hidden

### Minimal example reproducing the issue

https://leaflet-zoom-bug-with-zoomend.netlify.app/

### Environment

- Leaflet version:  latest
- Browser (with version): chrome 124.0.6367.60
- OS/Platform (with version): Macos Sonoma 14.1

**Comment by IvanSanchez** [comment]
Cannot reproduce. Vector tiles from the maptiler API (through leaflet-maplibre, I guess?) load just fine.
