### ISSUE TITLE
Roads had explicit names on 

### ISSUE THREAD

**Issue by codingtillclosing** [Leaflet/Leaflet#9331]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

![image](https://github.com/Leaflet/Leaflet/assets/40300410/8aa7bf42-d45d-479e-91b7-e0e270578b92)

### Expected behavior

A client reported a leaflet provided map had explicit road names. See screenshot. 

"Andy Shitty face townsend"

It's now been resolved, leaflet must have realised, but I wanted to flag. 

Can you tell me why this occurred, please?

### Current behavior

A client reported a leaflet provided map had explicit road names. See screenshot. 

"Andy Shitty face townsend"

It's now been resolved, leaflet must have realised, but I wanted to flag. 

Can you tell me why this occurred, please?

### Environment

- Leaflet version: 
- Browser (with version): 
- OS/Platform (with version):

**Comment by IvanSanchez** [comment]
@codingtillclosing  The nitty-gritty details of this particular instance of OSM vandalism are at https://community.openstreetmap.org/t/the-osm-standard-tile-layer-looks-wrong-white-lines-abusive-comments-etc/111583/33 , BTW.
