### ISSUE TITLE
Read Vectors from .geoparquet file

### ISSUE THREAD

**Issue by kach4n** [Leaflet/Leaflet#9332]
### Checklist

- [X] I've searched through the [plugins](https://leafletjs.com/plugins.html) to make sure this feature isn't already available, or think it shouldn't require a plugin.
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this feature hasn't been requested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Motivation

GeoParquet is a columnar data format that allows for significantly faster reading of vector data. As of now, no web GIS tool has native support for reading GeoParquet files. While some tools can read these files by converting them on the fly to .geojson format, this process eliminates the time-saving benefits that GeoParquet offers.

The absence of native GeoParquet support in web GIS tools limits the efficiency and speed at which geospatial data can be processed and analyzed. Incorporating direct reading capabilities for GeoParquet files in tools like Leaflet would revolutionize the way geospatial data is handled on the web.

By enabling Leaflet to directly read GeoParquet files, users would experience a dramatic improvement in data loading times and overall performance. This would not only enhance the user experience but also unlock new possibilities for real-time data visualization and analysis in web-based GIS applications.

The development of native GeoParquet support in Leaflet would bridge a crucial gap in the geospatial data ecosystem, empowering users to work with large-scale vector data efficiently and seamlessly. It's a step towards a more optimized and effective approach to web-based geospatial data management and analysis.

### Suggested solution

Create new method to read from a parquet file generating the same result that reading from a geojson does.

### Alternatives considered

Convert it on the fly to geojson using webAssembly and read as it is

**Comment by IvanSanchez** [comment]
Closing this down because (a) there's things like Leaflet.Omnivore and more importantly (b) reads like generated by a LLM. 

@kach4n I'm aware English is not your native language, but please use your own words and a translation tool instead.
