### ISSUE TITLE
mouseover and mouseout events are switching continuously.

### ISSUE THREAD

**Issue by pyprince** [Leaflet/Leaflet#9337]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [x] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Expected behavior

In my map there are sprinklers and when I hover them there supposed be a popup and circle.
Sprinklers are drawn as circle markers.

### Current behavior

When I hover a sprinkler, mouseover and mouseout event are switching continuously and the popup and circle are blinking.
But when browser is focused out and I just hover on the marker it works really well.

```js
let marker = L.circleMarker(coordinates, customMarkerStyle);
marker.addTo(map);

// Create HTML content for the popup.
const popupContent = get_popup_content(properties.SprnklrID, properties.moisture, properties.uniformity, properties.measurements, properties.throw_radius)
// Create a sprinkler popup for details.
let sprinkler_popup = L.popup()
.setLatLng(coordinates)
.setContent(popupContent);
marker.bindPopup(sprinkler_popup);

// Draw circle around the marker
let circle = undefined;
marker.on('mouseover', function (e) {
	map.getContainer().style.cursor = 'pointer';
	marker.openPopup();
	// Create a circle and specify its options (e.g., color, opacity, etc.)
	if(circle)
		circle.remove();
	circle = L.circle(coordinates, {
		color: '#fff',      // Stroke color
		fillColor: '#fff', // Fill color
		fillOpacity: 0.2,  // Fill opacity (0 to 1)
		radius: parseFloat(properties.throw_radius) * 0.3048  // Radius of the circle in meters
	}).addTo(map);
});
marker.on('mouseout', function(e) {
map.getContainer().style.cursor = 'grab';
marker.closePopup();
if(circle) circle.remove();
})
```

### Environment

- Leaflet version: 1.5.1
- Browser (with version): 124.0
- OS/Platform (with version): Windows 10

**Comment by Falke-Design** [comment]
Hi,

that is the default behavior on any browser. The problem is, that when you hover the circle, the popup opens and then the mouse is hovering the popup. This means the mouseout event is triggered because the mouse is now hovering the popup instead of the circle.

You can see this, with hovering the circle on the bottom, then is your code working fine:
https://plnkr.co/edit/NEyYQ7MgkoQYIFjz
