### ISSUE TITLE
Default maximum zoom level

### ISSUE THREAD

**Issue by josephernest** [Leaflet/Leaflet#9345]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

- Go to https://leafletjs.com/  or any leaflet-based map, such as https://www.openstreetmap.org/ if I'm correct
- Zoom a few times on the map
- The zooming level is blocked **too early**, we cannot zoom on the building details (they are present in the vector shapes, but we cannot clearly see them), this is the max zoom factor:
![image](https://github.com/Leaflet/Leaflet/assets/6168083/a1d6dde2-8a57-40f1-83ee-871aa53b17bc)

### Expected behavior

We should allow to zoom a few times more, to see more details of buildings shapes, for example.

### Current behavior

The zooming is blocked too early.

### Environment

Any environment

**Comment by IvanSanchez** [comment]
Read the documentation. Search for `maxZoom`.

**Comment by josephernest** [comment]
@IvanSanchez Thank you for your answer.
I'm not speaking about the `maxZoom` customization *for my own use* of leaflet (of course I could customize this).

I'm speaking about the *default* value shipped with leaflet, used on https://leafletjs.com/, used on openstreetmap.org/, etc.

May I ask what is the rationale to ship it with a default value of `18` for `maxZoom`?
Could ship ship with `20`, so that every downstream projects would have 20 by default?

Currently, nearly all websites that use leaflet use this default max zoom ; as a result, on many popular websites using leaflet, we cannot zoom closely on buildings.

Is there a discussion somewhere for potentientally highering the default value to 20 or more?

Thank you Ivan!
