### ISSUE TITLE
Cities have the wrong names

### ISSUE THREAD

**Issue by FlipFloop** [Leaflet/Leaflet#9346]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. Have a NextJS site and load a map

### Expected behavior

Cities have the right name

### Current behavior

Paris is renamed "Penis".
London is named "Allahu Akbar".

### Environment

- Leaflet version: 1.9.4
- Browser (with version): Brave
- OS/Platform (with version): Mac

**Comment by FlipFloop** [comment]
<img width="601" alt="Screenshot 2024-05-19 at 09 55 27" src="https://github.com/Leaflet/Leaflet/assets/19635051/03917247-bcdf-4669-a74e-0726824e1462">
<img width="906" alt="Screenshot 2024-05-19 at 09 58 58" src="https://github.com/Leaflet/Leaflet/assets/19635051/b00203d4-8827-44db-aefd-5c3c7463394a">
<img width="700" alt="Screenshot 2024-05-19 at 09 59 09" src="https://github.com/Leaflet/Leaflet/assets/19635051/edefeee3-d0d6-47fe-bc65-1b3576bfc3a8">

**Comment by jonkoops** [comment]
This data comes from Open Street Map, and not from Leaflet. Leaflet is just a library to show the data, we do not managed this data.

**Comment by IvanSanchez** [comment]
Duplicate of https://github.com/Leaflet/Leaflet/issues/9331 , actually. There seems to be waves of vandalism at OSM lately.
