### ISSUE TITLE
Cannot read properties of undefined (reading 'classList')

### ISSUE THREAD

**Issue by iqbalhassan-7654** [Leaflet/Leaflet#9347]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Expected behavior

![image](https://github.com/Leaflet/Leaflet/assets/170302501/4ba73369-2f76-40f3-8f16-5f5448091e14)

### Current behavior

![image](https://github.com/Leaflet/Leaflet/assets/170302501/d798e1e2-fdeb-4793-a550-e6a2f57f52ef)

### Environment

- Leaflet version: 
- Browser (with version): 
- OS/Platform (with version):

**Comment by IvanSanchez** [comment]
An error stack involving `invokeGuardedCallbackAndCatchFirstError` seems to involve React Native, so I'm closing this with the usual "submit bug reports reproducible without frameworks" template.

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* NativeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.
