### ISSUE TITLE
custom control with <select><option>...</option></select>

### ISSUE THREAD

**Issue by ghost** [Leaflet/Leaflet#936]
I put on the map custom control with "< select ></ select >". The list does not drop down. What's the problem?

var legend = L.control({position: 'topright'});
        legend.onAdd = function (map) {
                var div = L.DomUtil.create('div', 'info legend');
            div.innerHTML = '< select >< option >1</ option >< option >2</ option >< option >3</ option ></ select >';
            return div;
        };
legend.addTo(map);

**Comment by tlomiej** [comment]
Silly question... how to get value when object is change?
