### ISSUE TITLE
Cannot read properties of undefined (reading '_leaflet_pos')

### ISSUE THREAD

**Issue by iqbalhassan-7654** [Leaflet/Leaflet#9361]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Expected behavior

![image](https://github.com/Leaflet/Leaflet/assets/170302501/a4f79cce-f056-47ad-80ef-c7928d967f8a)

### Current behavior

![image](https://github.com/Leaflet/Leaflet/assets/170302501/10702c3a-c26c-43ff-b96f-26097602abce)

### Environment

- Leaflet version: 
- Browser (with version): 
- OS/Platform (with version):

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?

**Comment by iqbalhassan-7654** [comment]
i am using the react-leaflet version 4.2.1 and old version 2.0.1 react-leaflet it's working 
 
this is in old version 2.0.1 in stackoverflow that's resolved 
export function getPosition(el) {
	// this method is only used for elements previously positioned using setPosition,
	// so it's safe to cache the position for performance

	return (el && el._leaflet_pos) || new Point(0, 0);
}

But in Version 4.2.1 
// Returns the coordinates of an element previously positioned with setPosition.
export function getPosition(el) {
	// this method is only used for elements previously positioned using setPosition,
	// so it's safe to cache the position for performance

	return el._leaflet_pos || new Point(0, 0);
}
The issue in first api'call for data fetching in same component will Ok but when again call the api for data fetching they show me this type of error and optional chaining or && in console how can i resolve him

**Comment by iqbalhassan-7654** [comment]
![image](https://github.com/Leaflet/Leaflet/assets/170302501/1572f5d9-4025-4f60-b45e-f4f54ac972cb)
check this

**Comment by iqbalhassan-7654** [comment]
@IvanSanchez may understand my issue if not then tell me

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* NativeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.

**Comment by iqbalhassan-7654** [comment]
can you tell me why they give me type of error ? @IvanSanchez

**Comment by IvanSanchez** [comment]
> can you tell me why they give me type of error?

If you're willing to give me access to your full codebase and pay me my usual consulting fee for the time needed to debug the problem (which I'll estimate at... 20 hours of work), then the answer is yes.

If you think that FLOSS maintainers are magical beings that instantly know the root cause of your problems and will spend time gratis, then the answer is no.

**Comment by kofronpi** [comment]
@iqbalhassan-7654 you could at least share how you solved it :)
