### ISSUE TITLE
broken maps with retina display enabled & maps with max-zoom

### ISSUE THREAD

**Issue by seyfro** [Leaflet/Leaflet#939]
I think I found a bug with the newly introduced detectRetina-feature introduced in v0.4 with my plugin mapsmarker.com:
if you creat a map which uses the maximum zoom level of a basemap/tilelayer and open this map with a device that has a retina display, the map area stays grey - I think this is because leaflet tries to fetch tiles with a zoom level +1 to support the higher resolution.

I made a showcase to make this more clear: http://current.mapsmarker.com/2012/08/26/leaflet-js-0-4-4-retina-bug-showcases/
please access those maps both with a desktop pc and a device with a retina display:

Both maps use OGD Vienna basemaps with a max zoom level of 19 and enabled retina-support. The first map has zoom level 18 and the second zoom level 19. On desktop pcs, both maps displays without any errors. On devices with retina displays, the map with zoom level 19 stays grey.

As said above, I guess the problem is that leaflet ignores the max-zoom-level of the map and tries to fetch tiles with zoom-level 20 to support the higher resolution.

A fix for this could be like this: if retinadetection is enabled, leaflet checks the max-zoom-level of a map and if user is on a retina device, the zoom level of the map with max zoom level is decreased by 1.

It would be great there would be a fix for this soon as I enabled retina support for all maps by default with v2.7.1 of my plugin and thus this bug is propagated to all my plugin users through the automatic update & I wouldnt like to make a new release with retinaDetection disabled by default as this is a great improvement for showing high quality maps...

**Comment by mapmatters** [comment]
I also experienced same problem.. if you want to show zoom level 19 in retina display, how about try this?

var mylayer = L.tileLayer(url,{
		detectRetina: true,	
		maxZoom: 20   //  **zoom level you want to display + 1 more level, you need to render tiles for zoom level 20**
});

var map = new L.Map('mymap', {
  center: [37.4446, 127.1331], 
  maxZoom: 19, //  **zoom level you want to display**
  zoom: 16,
  layers: [mylayer]
});

I think this is not fundamental solution, but it works for my purpose. If you want to show zoom level 19 in retina display, set layer maxZoom 20 and set map maxZoom 19. You may see your map at zoom 19 in retina display
(Zoom level 20 may be shown in desktop, but not shown in retina(ex. iphone)).

**Comment by robertharm** [comment]
@mourner @danzel 4 years after initially opening the ticket I re-investigated the issue (as this is currently driving me crazy in another context as originally reported). 

I wonder if there is an issue in leaflet if `maxZoom` is set both in `Map` and `TileLayer` and if `detectRetina` is set to true on TileLayer. To demonstrate this, I created a fiddle with leaflet 0.7.7 at http://jsfiddle.net/robertharm/qb3r2e7d/2/ (the issue can also be reproduced with leaflet 1.0.1, see fiddle at http://jsfiddle.net/robertharm/gk3b7nyu/1/)

Open the fiddle zoom from 19 to 21 - on retina displays, zoom level 21 will result in no tiles being displayed in constrast to non-retina devices, where tiles show up correctly. 

The current workaround for me is to remove `maxZoom` from `L.Map` - anyway this creates another issue on certain types of WordPress themes (hard to reproduce), which results in console error `no maxZoom specified` (mostly for Google Maps created with https://github.com/shramov/leaflet-plugins/commits/master/layer/tile/Google.js)

Any help on how to solve this would be appreciated!
