### ISSUE TITLE
Marker does not render when deployed

### ISSUE THREAD

**Issue by stephendotgg** [Leaflet/Leaflet#9407]
### Checklist

- [ ] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [ ] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [ ] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Use this code on a SvelteKit site: 

```<script>
    import { onMount } from 'svelte';
    import { browser } from '$app/environment';

    export let address

    let map;
    let L;

    onMount(async () => {
        if (browser) {
            L = await import('leaflet');

            // Initialize the map
            map = L.map('map', {
                zoomControl: false,
                dragging: false,
                touchZoom: false,
                scrollWheelZoom: false,
                doubleClickZoom: false,
                boxZoom: false,
                tap: false,
                keyboard: false,
            });

            L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
            }).addTo(map);

            // Set a tighter bounding box for the UK
            const ukBounds = L.latLngBounds(
                L.latLng(48.0, -11.5), // Southwest corner
                L.latLng(60.0, 2.5)    // Northeast corner
            );

            map.fitBounds(ukBounds);

            // Zoom in by a factor (adjust as needed)
            map.zoomIn(1);  // Increase this number to zoom in more

            // Add marker for property
            L.marker([address.latitude, address.longitude])
                .addTo(map)
                .bindPopup(address || 'Property');
        }
    });
</script>

<svelte:head>
    {#if browser}
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"/>
    {/if}
</svelte:head>

<div id="map"></div>

<style>
    #map {
        height: 400px;
        width: 100%;
        border-radius: 12px;
    }
</style>
```

Works locally, but when deployed through Azure does not render. Not having this issue with any other images. Has this been seen before?

### Expected behavior

Marker should render

### Current behavior

![image](https://github.com/user-attachments/assets/0eebb998-5db4-4453-93a4-6ee61e8c187f)

### Environment

- Leaflet version: 1.9.4
- Browser (with version): Brave v1.6.7.123
- OS/Platform (with version): Windows 22631.3880

**Comment by stephendotgg** [comment]
Sidenote......... anyone know how to remove the big gray line around the country?

**Comment by DanIsLit** [comment]
> Sidenote......... anyone know how to remove the big gray line around the country?

I've been wondering this also!

**Comment by IvanSanchez** [comment]
Most likely there's a 404 error somewhere in the browser's dev tools, due to the deployment process not copying the marker images. Look for those errors.

Closing, since it's not an actionable Leaflet bug.

**Comment by DanIsLit** [comment]
> Most likely there's a 404 error somewhere in the browser's dev tools, due to the deployment process not copying the marker images. Look for those errors.
> 
> Closing, since it's not an actionable Leaflet bug.

There is a 404- we deploy on Azure, might you have any idea how to fix that?

Also, is there any way to remove the lines around countries on the map?

**Comment by Falke-Design** [comment]
You need to make sure that you deploy the images as well. You can look in the dev tools which path the marker-images should have.

You can also try to include the images in your Code with:
```
import icon from "leaflet/dist/images/marker-icon.png"; 
import iconShadow from "leaflet/dist/images/marker-shadow.png"; 
```

Or you can overwrite the Default Icon Path:
```
delete L.Icon.Default.prototype._getIconUrl;

L.Icon.Default.mergeOptions({ 
iconRetinaUrl: require("leaflet/dist/images/marker-icon-2x.png"), 
iconUrl: require("leaflet/dist/images/marker-icon.png"), 
shadowUrl: require("leaflet/dist/images/marker-shadow.png") 
});
```
There are so many solutions for this, just google "leaflet marker icon not showing"

2. The borders around the countries are displayed by the Tile provider , this has nothing to do with Leaflet. Use a different one from here: https://leaflet-extras.github.io/leaflet-providers/preview/
