### ISSUE TITLE
Auto-detect changes to map size (and invalidateSize)

### ISSUE THREAD

**Issue by broofa** [Leaflet/Leaflet#941]
I have a map that's styled like this:

```
#map {position: absolute; top: 10px; left: 10px; right: 10px; bottom: 90px;}
```

... i.e. it has no explicit height.  So, of course, leaflet isn't rendering all of the tiles.  However I do `setTimeout(map.invalidateSize.bind(map))`, after creating the map it renders properly.

This has me thinking that it's not actually necessary for the map to have an explicit height - it's just a question of insuring Leaflet is smart about detecting the height at the appropriate time.

**Comment by HarelM** [comment]
My two cents:
I think a minor fix would help in order to prevent a bug I had: keep trying to get the size if it is 0,0.
```js
getSize: function () {
		if (!this._size || this._sizeChanged || (this._size && this._size.x == 0 && this._size.y == 0) {
			this._size = new Point(
				this._container.clientWidth || 0,
				this._container.clientHeight || 0);

			this._sizeChanged = false;
		}
		return this._size.clone();
	},
```
The element could be initialized with zero size but later change without calling resize (I think, at least this is what I think happened in the scenario I had to fix).

**Comment by CourtneyJane2904** [comment]
I appreciate that this issue has been closed; I had this issue today and reading this discussion inspired my fix (bare in mind that my case is VERY simple- just a map with a view and a marker)

It might help a fellow noob like myself:

`$('#tab').click(function()
    {setTimeout(function(){setView|tileLayer|add to map|add markers},200);}`

This prevents the default none display of tab content interfering with the tiling process (I'm sure this has probably been mentioned though!) :)
