### ISSUE TITLE
Signal when `leafletProxy` is done rendering on the client side

### ISSUE THREAD

**Issue by daattali** [Leaflet/Leaflet#9415]
With a plain `leaflet` map, we can use `htmlwidgets::onRender()` in order to perform an action when the map finishes rendering.

When using `leafletProxy()` to update a map, I don't think there's any way to know when the rendering of the update finished.

Here's an example shiny app, when you press the button it adds polygons. I would like to have some signal or callback when the rendering is complete. Even just triggering shiny's `outputinvalidated` javascript event would be a step in the right direction.

```
library(shiny)
library(leaflet)
library(sf)

polys <- st_sf(
  geometry = st_sfc(
    st_polygon(list(rbind(
      c(-101.744384765625, 39.32155002466662),
      c(-101.5521240234375, 39.330048552942415),
      c(-101.40380859375, 39.330048552942415),
      c(-101.33239746093749, 39.364032338047984),
      c(-101.041259765625, 39.36827914916011),
      c(-100.975341796875, 39.30454987014581),
      c(-101.0399169921875, 39.24501680713314),
      c(-101.243896484375, 39.16414104768742),
      c(-101.455078125, 39.11125631228113),
      c(-101.737060546875, 39.13006024213511),
      c(-101.77825927734375, 39.16839962520706),
      c(-101.734619140625, 39.254884981213734),
      c(-101.744384765625, 39.32155002466662)
    )))
  )
)

ui <- fluidPage(
  leafletOutput("map"),
  actionButton("go", "go")
)

server <- function(input, output, session) {
  output$map <- renderLeaflet({
    leaflet() %>% 
      addTiles() %>%
      setView(-101, 39, 8)
  })
  
  observeEvent(input$go, {
    leafletProxy("map") %>%
      addPolygons(data = polys)
  })
}

shinyApp(ui, server)
```

**Comment by IvanSanchez** [comment]
Wrong repo, pal. You're using `shiny` and this is for vanilla Leaflet.

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* NativeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.

**Comment by daattali** [comment]
Whoops, sorry, definitely wrong repo! This was meant to go in the R leaflet repo :)

**Comment by bcalvet-masseeds** [comment]
@daattali : did you receive any feedback on this question, I have the exact same requirement but could not find an equivalent issue in [the R leaflet repo](https://github.com/rstudio/leaflet/issues?q=is%3Aissue%20state%3Aopen). Did you post it there? 
There seems to be a way of performing it using the js library but it involves interacting with the layer renderer and I am not sure it is possible using R code : 
https://stackoverflow.com/questions/76457939/how-to-know-whether-leaflet-layer-is-fully-rendered-or-not-in-browser

Thanks! :)

**Comment by Falke-Design** [comment]
@bcalvet-masseeds 10 seconds of search: https://github.com/rstudio/leaflet/issues/926
