### ISSUE TITLE
Why are 2.0 versions not published in NPM?

### ISSUE THREAD

**Issue by geferon** [Leaflet/Leaflet#9421]
### Checklist

- [X] I've searched through the [plugins](https://leafletjs.com/plugins.html) to make sure this feature isn't already available, or think it shouldn't require a plugin.
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this feature hasn't been requested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Motivation

Currently the only way of getting the 2.0 version is to clone the github repo and build it for yourself or going to the download page and downloading the last version for the CDN, but for some reason it's not being published into NPM, not even as beta/alpha versions...

### Suggested solution

Publish them to NPM for ease of use.

**Comment by mourner** [comment]
It's because 2.0 is not released yet, obviously.

**Comment by geferon** [comment]
But how is it that it's being released to your CDN?
I'm not saying making a major release yet but you could release them in NPM as alphas or similar
