### ISSUE TITLE
SVG.VML.js error 

### ISSUE THREAD

**Issue by vammex** [Leaflet/Leaflet#9454]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

run html page with leaflet element inside with devtools opened
function 
export var vmlCreate = (function () {
	try {
		document.namespaces.add('lvml', 'urn:schemas-microsoft-com:vml');  // HERE Exception occurs
		return function (name) {
			return document.createElement('<lvml:' + name + ' class="lvml">');
		};
	} catch (e) {
		return function (name) {
			return document.createElement('<' + name + ' xmlns="urn:schemas-microsoft.com:vml" class="lvml">');
		};
	}
})();

refresh the page

### Expected behavior

nothing happens

### Current behavior

devtools debug stops with warning
cannot read prop-s of undefined (reading 'add')

### Environment

- Leaflet version:  https://unpkg.com/leaflet@1.7.1/dist/leaflet.js
- Browser (with version): Chrome Version 127.0.6533.120 (Official Build) (64-bit)
- OS/Platform (with version): Win 11

**Comment by IvanSanchez** [comment]
> Leaflet version: https://unpkg.com/leaflet@1.7.1/dist/leaflet.js

Use 1.9.x instead.

SVG.VML was meant for MSIE8, and we dropped support for MSIE<=11 some versions ago. See also https://github.com/Leaflet/Leaflet/pull/8196

**Comment by vammex** [comment]
> > Leaflet version: https://unpkg.com/leaflet@1.7.1/dist/leaflet.js
> 
> Use 1.9.x instead.
> 
> SVG.VML was meant for MSIE8, and we dropped support for MSIE<=11 some versions ago. See also #8196

exactly the same error at the same place

**Comment by vammex** [comment]
guys it really makes debugging impossible, this error is highly annoying

**Comment by Falke-Design** [comment]
Does this error occour for you on this page too? https://leafletjs.com/examples/quick-start/example.html

You should not reach the vml code, because it was only used for IE. 
If you run `L.Browser.vml` what do you get? It should be `false`.

**Comment by vammex** [comment]
> Does this error occour for you on this page too? https://leafletjs.com/examples/quick-start/example.html
> 
> You should not reach the vml code, because it was only used for IE. If you run `L.Browser.vml` what do you get? It should be `false`.

yes
but i am in Chrome  Version 127.0.6533.120 
L.Browser.vml returns false

**Comment by Falke-Design** [comment]
Please describe step by step what you, because for me everything works fine on different machines and chrome.

No error:
![grafik](https://github.com/user-attachments/assets/587ebe64-720a-4930-80bb-5b23c18a21bf)

**Comment by vammex** [comment]
I come to any page with a map
click refresh
at opened console I see (stopping as it were a breakpoint): 
![23424432423432423](https://github.com/user-attachments/assets/ae0977ce-98a7-443e-aa8d-7046ea7b2e6d)

**Comment by IvanSanchez** [comment]
Once again:

VML Support was dropped in https://github.com/Leaflet/Leaflet/pull/8196 . The entire `SVG.VML.js` file was removed then.

If you see `SVG.VML.js`, then you are not using v1.9.1.

**Comment by vammex** [comment]
> Once again:
> 
> VML Support was dropped in #8196 . The entire `SVG.VML.js` file was removed then.
> 
> If you see `SVG.VML.js`, then you are not using v1.9.1.

i made search for leaflet in all the code:

![756754656](https://github.com/user-attachments/assets/6f6853d8-e988-4400-a005-dc2464dce1d0)

**Comment by Falke-Design** [comment]
> Once again:
VML Support was dropped in https://github.com/Leaflet/Leaflet/pull/8196 . The entire SVG.VML.js file was removed then.
If you see SVG.VML.js, then you are not using v1.9.1.

@IvanSanchez We removed SVG.VML.js with v2 not with v1.9.1: https://github.com/Leaflet/Leaflet/blob/v1/src/layer/vector/SVG.VML.js
You also find it in the latest src files, when you search for "vmlCreate": https://unpkg.com/leaflet@1.9.4/dist/leaflet-src.js

Yes the error exists but it is not thrown, because of the `try-catch`, so you should not able to see it.
You can test it by your self with this:
```
(function () {
try {
        document.namespaces.add('lvml', 'urn:schemas-microsoft-com:vml');
        return function (name) {
            return document.createElement('<lvml:' + name + ' class="lvml">');
        };
    } catch (e) {
        // Do not return fn from catch block so `e` can be garbage collected
        // See https://github.com/Leaflet/Leaflet/pull/7279
        console.log('RUNS IN CATCH - no error')
    }
})()
```
![grafik](https://github.com/user-attachments/assets/47a90546-dd2b-469d-a0b1-b4fd94cf2ffa)


Maybe you have any plugins or something else enabled? Also test it on other devices, I think then you will see that it works there and that it has something to do with some custom settings from your browser.

Anyways it is no Leaflet error when the browser ignores a `try-catch`. I wish you luck with finding the error but we can't help you more.

**Comment by vammex** [comment]
i do not understand why would you not just give me a link to v2 package?

**Comment by Falke-Design** [comment]
Because it is not released yet. But you can build it by your self by using the main branch from this repo und run `npm run build`
