### ISSUE TITLE
Default marker image src broken

### ISSUE THREAD

**Issue by LukeTOBrien** [Leaflet/Leaflet#9466]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. Go through the [quick start](https://leafletjs.com/examples/quick-start/) tutorials

### Expected behavior

Img src should be: `https://unpkg.com/leaflet/dist/images/marker-icon-2x.png`

### Current behavior

Img src is: `https://unpkg.com/leaflet/distmarker-icon-2x.png`

![image](https://github.com/user-attachments/assets/d800a0f0-9365-4446-b092-1f1ece8db8cb)

### Environment

- Leaflet version: 1.9.4

**Comment by steffenz** [comment]
Hi!
I thought this might be a good issue for me to start with - but I cannot seem to reproduce it. I followed the quick start guide both locally and in a [new CodePen](https://codepen.io/steffenz/pen/ZEgzJGq) and the asset seems to be loading correctly on my end. 

Would you mind posting some code or sharing some more details about your environment to make it easier to reproduce this issue? Seems like a missing ```/``` is causing it which might be something related to your environment configuration.

Thanks in advance 😊

**Comment by Muhammad-Owais-Warsi** [comment]
I can't reproduce it on my end. It would be really helpful if you could mention it. Based on what you've mentioned above, I think the directory path is incorrect.
Thanks :)

**Comment by LukeTOBrien** [comment]
I am now trying to create a repo for this... I should of mention that I am using Typescript and importing from `node_modules`, maybe it's my bundler?  
...

**Comment by Muhammad-Owais-Warsi** [comment]
> I am now trying to create a repo for this... I should of mention that I am using Typescript and importing from `node_modules`, maybe it's my bundler? ...

maybe that's the possible reason, or you could save marker to some assets or public folder and fetch from their.. I think that could work if am not wrong
