### ISSUE TITLE
Documentation of how to populate popup contents via ajax

### ISSUE THREAD

**Issue by typeshige** [Leaflet/Leaflet#947]
Is it documented anywhere how to populate the contents of a marker popup upon clicking on it?  

Also, is it possible to populate the popup contents for all visible markers?  I'm using Leaflet.markercluster and it would be nice to only load in popup contents when I'm zoomed in enough to see individual markers.

I'm not very good with js and my searches didn't come up with anything but I sense that what I'm trying to do is possible... ?

Thanks again!

**Comment by jonenst** [comment]
This was well referenced on google, so here's for people looking:
  * You don't have to manually create a popup and calling map.openPopup; if you have a marker, you can use bindPopup() and getPopup() if you want.
  * don't forget to call popup.update() http://leafletjs.com/reference.html#popup-update

Here's a working example with leaflet 0.7.3:
```javascript
var marker = L.marker([48.859085, 2.347403]);
marker.bindPopup("Loading...")
marker.on('click', function(e) {
    var popup = e.target.getPopup();
    var url="DYNAMIC_CONTENT_URL";
    $.get(url).done(function(data) {
        popup.setContent(data);
        popup.update();
    });
```

**Comment by cdauth** [comment]
Note that you can also pass a function to [`bindPopup()`](http://leafletjs.com/reference-1.0.0.html#popup-bindpopup). It will be called when the popup is opened and has to return a `String` or `HTMLElement`. So another version of your code (that doesn't dictate which event type causes the popup to open):

```javascript
var marker = L.marker([48.859085, 2.347403]);
marker.bindPopup(function() {
    var el = $('<div/>');
    
    $.get("DYNAMIC_CONTENT_URL").done(function(data) {
        el.setContent(data);
        popup.update();
    });

    return el;
});
```

**Comment by njander** [comment]
Does anyone have a live working example of this that they'd be willing to share?

**Comment by chriszrc** [comment]
Here's a plunkr- 

http://plnkr.co/edit/ps1MNhUMMO7vZCnQN7Cg?p=preview

**Comment by ozgursarikamis** [comment]
@chriszrc that saved me a lot of trouble. thanks man

**Comment by chriszrc** [comment]
@kunaldhariwal you'll need to post a plunkr or something, impossible to say without an example. For starters though, the url you're loading the code snippet ("http://www.example.com/data") doesn't appear to return valid json-

**Comment by kunaldhariwal** [comment]
@chriszrc  That's an example URL though. For some obvious reasons i cannot reveal the exact url.
I'm sorry but i'll try to figure out something.

**Comment by Guilouf** [comment]
I still really struggled even with the examples given here, so here is how i did, with fetch API instead of jquery:
```javascript
 layer.bindPopup(
            function (target) {
                const popup = target.getPopup()
                const url = 'someurl'
                fetch(url).then(response => response.json()).then(
                    function (jsonData) {
                        let html = `
                                    <p>Foo: ${jsonData.bar}</p>
                                    `;
                        popup.setContent(html);  // i didn't need to call .update(), windows resized well
                    }
                )
                return 'Loading...'  // Display loading till the url is fetched
            }
        )
```
Hope it could help someone
