### ISSUE TITLE
replace `circle` with `circleMarker` in quick-start guide

### ISSUE THREAD

**Issue by mattdzugan** [Leaflet/Leaflet#9490]
### Checklist

- [x] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this change hasn't been suggested already.
- [x] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Which documents need updating?

https://leafletjs.com/examples/quick-start/

### Motivation

I believe that for most leaflet users, **especially** those coming to the quick-start guide - the idea of using a circle as an "abstract representation of data" (e.g. a marker) is more common than the use-case for "plotting a real-world circle of fixed radius in meters".

We can debate this a bit, but I see quite a few examples of folks using `circle()` incorrectly as markers (and thus running into weird effects at extreme latitudes), and I feel that using `circleMarker()` within the quick-start guide will help mitigate this.

### Suggested changes

I'd change
https://github.com/Leaflet/Leaflet/blob/main/docs/examples/quick-start/index.md
https://github.com/Leaflet/Leaflet/blob/main/docs/examples/quick-start/example-overlays.md

to reference `circleMarker()` instead of `circle()` and update with an appropriate `radius` as needed.

I'm happy to make this PR myself - but wanted to discuss here first

**Comment by bhavyaKhatri2703** [comment]
Hi i am new to open source Maybe this is an issue i can start with?

**Comment by Falke-Design** [comment]
Hi,
thank you for your suggestion.

In my eyes there are less usecases to use a CircleMarker then a Circle. Most of the users have own Icons for theier Marker so they are not using a CircleMarker (which can't be customized except for color-style) . The Circle is used to show in which range something will be or the accouracy GPS or a search radius, etc. 

Do you have some references that the CircleMarker is more common?

**Comment by Famzy077** [comment]
Hi am new to open source can I work on this project

**Comment by Falke-Design** [comment]
Please take another one, I will close this one.
