### ISSUE TITLE
Feature: Search bar to search through documentation

### ISSUE THREAD

**Issue by JoT8ng** [Leaflet/Leaflet#9492]
### Checklist

- [x] I've searched through the [plugins](https://leafletjs.com/plugins.html) to make sure this feature isn't already available, or think it shouldn't require a plugin.
- [x] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this feature hasn't been requested already.
- [x] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Motivation

The current documentation for Leaflet is very comprehensive and covers a lot of areas. When reading the Leaflet documentation it would be convenient if there was a search bar to search for key words relating to methods and events. 

### Suggested solution

A little search bar at the top of the documentation page or in the table of contents where users can search for key words relating to methods and events in the documentation.

**Comment by IvanSanchez** [comment]
Your browser has a search function (most probably `Ctrl`+`F`). Use it.
