### ISSUE TITLE
Add setZIndexOffset method to circleMarker

### ISSUE THREAD

**Issue by amokrunnr** [Leaflet/Leaflet#9526]
### Checklist

- [ ] I've searched through the [plugins](https://leafletjs.com/plugins.html) to make sure this feature isn't already available, or think it shouldn't require a plugin.
- [x] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this feature hasn't been requested already.
- [x] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Motivation

In a series of CircleMarkers, need to bring one to the front programmatically.

### Suggested solution

Add the setZIndexOffset() method to CircleMarker.
`circleMarker.setZIndexOffset()`

Or, could also add a "type:circle" field when creating a marker, eg:
`L.marker([],{..., type:'circle'})`

### Alternatives considered

Creating my own circle SVG and assigning it works, but less than ideal.
`L.marker([],{..., icon: L.divIcon({html:[here]}) })`

**Comment by IvanSanchez** [comment]
`L.CircleMarker` is a subclass of `L.Path`, which implements `bringToFront()`.
