### ISSUE TITLE
设置地图EPSG:4326再次加载EPSG:3857谷歌地图时，有纬度消失了。初步判断计算问题

### ISSUE THREAD

**Issue by xhccode** [Leaflet/Leaflet#9538]
### Checklist

- [x] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [x] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [x] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [x] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

<!DOCTYPE html>
<html lang="en">
 
<head>
  <title></title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
	<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
	 <script src="https://unpkg.com/proj4"></script>
	 <script src="https://unpkg.com/proj4leaflet"></script>
  <style>
    #map {
      position: absolute;
      width: 100vw;
      height: 100vh;
    }
  </style>
</head>
 
<body>
  <div id='map'>
  </div>
  <script>
		function getCrs () {
			const res = []
			for (let i = 0; i < 20; i++) {
				res[i] = 1.40625 / Math.pow(2, i)
			}
			return new L.Proj.CRS('EPSG:4326', '+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs', {
				origin: [-180.0, 90],
				resolutions: res,
			})
		}
    let map = L.map('map', {
			crs: getCrs(),
			maxZoom: 19,
			minZoom: 10,
			zoomSnap: 0.5,
			zoomDelta: 0.25,
			doubleClickZoom: false,
			zoomControl: false,
			attributionControl: false,
			continuousWorld: true,
			worldCopyJump: false,
			useDefault: false,
			closePopupOnClick: false,
			basetileLayer: []
    }).setView([31.591808, 120.345325], 13);
		
		function zeroPad(num, len, radix) {
			let str = num.toString(radix || 10);
			while (str.length < len) {
				str = "0" + str;
			}
			return str;
		}

		let customWMSLayer = L.TileLayer.extend({
			getTileUrl: function (coords) {
			  const zoom = this._getZoomForUrl();
				// 获取瓦片的经纬度范围
				let bounds = this._tileCoordsToBounds(coords);
				// 瓦片范围的经纬度（左上角和右下角）
				let latLngTopLeft = bounds.getNorthWest(); // 左上角
				let latLngBottomRight = bounds.getSouthEast(); // 右下角
				const center = bounds.getCenter();
				// 将中心点转换为 EPSG:3857 坐标
				const mercator = latLonToMercator(center.lng, center.lat);
				// 计算 EPSG:3857 的瓦片编号
				const tile = mercatorToTile(mercator.x, mercator.y, zoom);
				// 调用父类的同名方法来生成基础的tile URL
				let url = L.TileLayer.prototype.getTileUrl.call(this, coords, zoom);
				let x = tile.x;
				let y = tile.y;
				let z = zoom;
				return this._url + '&z=' + z + '&y=' + y + '&x=' + x;
			}
		});
		// EPSG:4326 到 EPSG:3857 的坐标转换
		function latLonToMercator(lon, lat) {
		  const R = 6378137; // 地球半径（米）
		  const x = R * lon * Math.PI / 180; // 经度转 Mercator x
		  const y = R * Math.log(Math.tan(Math.PI / 4 + lat * Math.PI / 360)); // 纬度转 Mercator y
		  return { x, y };
		}
		
		// 计算 EPSG:3857 的瓦片编号
		function mercatorToTile(x_merc, y_merc, zoom) {
		  const maxExtent = 20037508.342789244; // EPSG:3857 最大投影范围
		  const tileSize = 256; // 瓦片大小
		  const resolution = (maxExtent * 2) / (tileSize * Math.pow(2, zoom)); // 每像素分辨率
		
		  const x_tile = Math.floor((x_merc + maxExtent) / (tileSize * resolution));
		  const y_tile = Math.floor((maxExtent - y_merc) / (tileSize * resolution));
		
		  return { x: x_tile, y: y_tile };
		}

		let corner1 = L.latLng([31.7510636486429,120.281287917284]),
		      corner2 = L.latLng([31.4867845979049,120.60065854459]),
					bounds = L.latLngBounds(corner1, corner2);
					
		let tileLayer = new customWMSLayer(
		'https://mt3.google.com/vt/lyrs=s&x={x}&y={y}&z={z}',
		{
			tileSize: 256,
			tms: true, // 瓦片坐标方向
			noWrap: true, // 禁止重复绘制瓦片
			minZoom: 8,
			maxZoom: 20,
			format: 'image/png',
			attribution: '3857',
			// bounds:bounds
		});
		tileLayer.addTo(map);
  </script>
</body>
 
</html>

### Expected behavior

运行上面HTML代码,将重现错误。应该正常加载地图,现在地图缺失部分内容。
![Image](https://github.com/user-attachments/assets/58ffaed4-6fd3-419f-9d97-622f3dea43e8)

### Current behavior

地图加载错误
![Image](https://github.com/user-attachments/assets/58ffaed4-6fd3-419f-9d97-622f3dea43e8)

### Environment

- Leaflet version: all
- Browser (with version): all
- OS/Platform (with version): all

**Comment by jonkoops** [comment]
We only accept issue reports in English.
