### ISSUE TITLE
When setting the map EPSG: 4326 and loading EPSG: 3857 Google Maps again, the latitude disappeared. Preliminary assessment of calculation issues

### ISSUE THREAD

**Issue by xhccode** [Leaflet/Leaflet#9539]
### Checklist

- [x] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [x] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [x] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [x] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

```
function getCrs() {
  const res = [];
  for (let i = 0; i < 20; i++) {
    res[i] = 1.40625 / Math.pow(2, i);
  }
  return new L.Proj.CRS(
    "EPSG:4326",
    "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs",
    {
      origin: [-180.0, 90],
      resolutions: res,
    },
  );
}
let map = L.map("map", {
  crs: getCrs(),
  maxZoom: 19,
  minZoom: 10,
}).setView([31.591808, 120.345325], 13);

let customWMSLayer = L.TileLayer.extend({
  getTileUrl: function (coords) {
    const zoom = this._getZoomForUrl();
    let bounds = this._tileCoordsToBounds(coords);
    let latLngTopLeft = bounds.getNorthWest();
    let latLngBottomRight = bounds.getSouthEast();
    const center = bounds.getCenter();
    const mercator = latLonToMercator(center.lng, center.lat);
    const tile = mercatorToTile(mercator.x, mercator.y, zoom);
    let url = L.TileLayer.prototype.getTileUrl.call(this, coords, zoom);
    let x = tile.x;
    let y = tile.y;
    let z = zoom;
    return this._url + "&z=" + z + "&y=" + y + "&x=" + x;
  },
});

function latLonToMercator(lon, lat) {
  const R = 6378137;
  const x = (R * lon * Math.PI) / 180;
  const y = R * Math.log(Math.tan(Math.PI / 4 + (lat * Math.PI) / 360));
  return { x, y };
}

function mercatorToTile(x_merc, y_merc, zoom) {
  const maxExtent = 20037508.342789244;
  const tileSize = 256;
  const resolution = (maxExtent * 2) / (tileSize * Math.pow(2, zoom));
  const x_tile = Math.floor((x_merc + maxExtent) / (tileSize * resolution));
  const y_tile = Math.floor((maxExtent - y_merc) / (tileSize * resolution));
  return { x: x_tile, y: y_tile };
}

let tileLayer = new customWMSLayer(
  "https://mt3.google.com/vt/lyrs=s&x={x}&y={y}&z={z}",
  {
    tileSize: 256,
    minZoom: 8,
    maxZoom: 20,
    format: "image/png",
  },
);
tileLayer.addTo(map);

```

### Expected behavior

That's right
![Image](https://github.com/user-attachments/assets/0e356c88-f2fc-4cb6-8536-1be7b33cdb4d)

### Current behavior

This is wrong，you can try.
![Image](https://github.com/user-attachments/assets/c0acf757-c266-494b-8032-9a524944676c)

### Environment

- Leaflet version: all
- Browser (with version): all
- OS/Platform (with version): all

**Comment by IvanSanchez** [comment]
You're using `L.Proj.CRS`, which means you're using `proj4leaflet`.

This bug tracker is for *core* Leaflet *only*.

Also, that example is not reproducible (What are the bboxes of the rectangles? What are the start/end points of the arrows?), and you should not expect Leaflet to perform automatic reprojection of raster tiles.

**Comment by xhccode** [comment]
May I ask if there is a way for me to avoid this issue? The boundary box of the rectangle indicates an error in the display of the base image, and the arrow indicates that there are two blocks. How can I reference the EPSG: 3857 map on EPSG: 4326?

**Comment by IvanSanchez** [comment]
Ah, I see what you mean. There's horizontal artifacts spawning the entire screen (not the boxes you highlighted).

I guess this is due to your custom function to calculate the `y` in the tilelayer, which is *trying* to account for the reprojection.

Again: if your leaflet map uses the EPSG:4326 CRS, then use EPSG:4326 basemaps. If your leaflet map uses EPSG:3857 CRS, use EPSG:3857 basemaps. Mixing them will lead to reprojection issues (or, in your case, tile mismatch artifacts).
