### ISSUE TITLE
TileLayer.createTile display tile if WMS request fails

### ISSUE THREAD

**Issue by ciossi** [Leaflet/Leaflet#9541]
### Checklist

- [x] I've searched through the [plugins](https://leafletjs.com/plugins.html) to make sure this feature isn't already available, or think it shouldn't require a plugin.
- [x] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this feature hasn't been requested already.
- [x] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Motivation

Hello,

we use Leaflet to display openStreetMap with an overlay map. We get overlay map tiles from WMS service url (https://wms.cartografia.agenziaentrate.gov.it/inspire/wms/ows01.php?language=ita&service=WMS&version=1.3.0&request=GetMap&bbox=45.92058734473366,8.48419189453125,45.92249798457993,8.4869384765625&crs=EPSG:6706&width=256&height=256&layers=province,CP.CadastralZoning,acque,CP.CadastralParcel,fabbricati,codice_plla,simbolo_graffa&styles=default&format=image/png&transparent=false). Sometimes we receive connection error from the url to use in the tile.src, and the method TileLayer.createTile raise the event _tileOnError.

### Suggested solution

We suggest to modify the event function _tileOnError to manage the exception and try to make a new request to get the tile correctly and then show it on the map grid.

Thanks.

**Comment by IvanSanchez** [comment]
On one hand, there's already `errorTileUrl` and a few plugins (FunctionalTileLayer, TileLayer.Fallback) that could be applied to this use case.

On the other hand, I'm against a retry mechanism on tileservers by default: this will probably increase load in tileservers, which is not a nice thing to do - in the end, a tile server is only capable to cope with a given load, and retrying will use up some of that load capacity. You should research caching mechanisms (e.g. mapproxy) instead.
