### ISSUE TITLE
wrong territory on map

### ISSUE THREAD

**Issue by bmt-t** [Leaflet/Leaflet#9558]
![Image](https://github.com/user-attachments/assets/ebd4a0ef-8851-4782-89e0-8203a55e268e)

**Comment by jonkoops** [comment]
This data comes from Open Street Map, and not from Leaflet. Leaflet is just a library to show the data, we do not manage this data.

**Comment by IvanSanchez** [comment]
Duplicate of #3896 and a bunch others.
