### ISSUE TITLE
Leaflet line ending style is mixed

### ISSUE THREAD

**Issue by lapo-luchini** [Leaflet/Leaflet#995]
OK, this is really really minor.
But still… ;-)
Different Leaflet sources use a different line ending style (src/map/Map.js uses CRLF, src/map/handler/Map.TouchZoom.js LF), so the generated -src.js script is mixed.
(Of course the minified isn't anways.)

**Comment by 12finger** [comment]
it's 2021 and i am experiencing the same still.
i forked and wanted to work on some code amends for my own project and later maybe roll them up to a PR 

Popup.js is CRLF
while 
SVGOverlay is LF
